### ISSUE TITLE
Parse units from data

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#1000]
As discussed slightly with @kanitw, it could be nice to get the unit directly from the data provided vs. having people pre-prune the data and then need to explicitly state the unit. This would be helpful for a column with units inside (e.g. $1000), or perhaps from a parentheses in the header `Volume of Rainfall (ml)`. This is likely beyond the scope of vega-lite and could be built as an independent dependency or module.

**Comment by kanitw** [comment]
Yeah this probably should be something that's filed down the stack -- I'm not sure if it's Vega or Datalib.

**Comment by domoritz** [comment]
#1000 :sparkles:
