### ISSUE TITLE
Should bar with color but having non-sum aggregate (e.g., “mean”) be stacked by default?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1012]
I think it should not be stacked by default.  In this case, making a layered bar chart with some opacity and good sorting order lead to a better visualization by default.  However, I don’t know if this rule is too complex. 

@domoritz any thoughts?

**Comment by domoritz** [comment]
Agreed. Maybe add some offset to the bars because opacity can be hard to see.

**Comment by kanitw** [comment]
Thinking more about this, I think this should be the default so that it won't cause glitches as an intermediate visualization during transitions from one effective visualization to another but we can throw some warning as in #726.
