### ISSUE TITLE
Allow line’s path to be ordered by the original order of the data.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1020]
Currently, we always sort line's path based on fields of the discrete axis (x or y) or specified `order` channel.   However, users might want to order line based on the original order in the data.

**Comment by kanitw** [comment]
This is actually not just for path.  For scale-based sort,  maybe simply adding `sort: 'none'`  (in addition to `'ascending'` and `'descending'`) would make this generalize.    

As a result, 
- For `path`, no transform will be produced. 
- For scale-based sort, scale's `sort` will be set to false.

**Comment by kanitw** [comment]
`sort: 'none'` actually doesn't make sense for path.  Maybe an escape hatch for this is setting path to `[]`

**Comment by kanitw** [comment]
Maybe we can allow this by letting users set `encoding.order = null`

**Comment by kanitw** [comment]
Note that order is an encoding channel, so mapping a channel to null isn't something exist in the language before.  So we might want to be careful about this.  Another option is `order: {value: null}` but this is not really mapping fixed value to `order` either.

**Comment by domoritz** [comment]
`order: {value: null}` looks okay

**Comment by kanitw** [comment]
Yeah, I guess `order: {value: null}` makes sense as in a way it would mean assign no specific order to each point in the line.  

@willium  feel free to submit a PR if you need this for your geo example.

**Comment by domoritz** [comment]
@ilokhov asked for this feature as well.

**Comment by kanitw** [comment]
The problem with `{value: null}` is that it suggests that `{value: <other_value>}` is also valid, so I'm no longer sure if this is the ideal solution.   (Compared to encoding.order = null?)

**Comment by kanitw** [comment]
I guess if we bring back generic `ValueDef`, then we can enforce that value of order can only be null?

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3693.
