### ISSUE TITLE
Moving default values of `value` to `config`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1029]
The reason that we have color and size channel automatically maps to `fill`/`stroke` and `size` / `width` / `height` of tick and bar / `fontSize` is that we allow seamless transition between mark types.

Suppose a field is mapped to `bar`'s `color` (practically to bar’s `fill`), if users change the mark type to line, this allow the field to automatically be mapped to line’s `stroke`.  

Similarly, suppose a field is mapped to `point`'s `size` (practically to point's `size`), if users change the mark type to `text`, this allow the field to automatically be mapped to text's `fontSize`.  

And then we added `value` field to allow setting constant values for these fields.  

However, having `value` property that seamlessly work across mark type is not always sensible.  For example, if user explicitly set `size` to 96 when using `point` mark.  This does not mean that user would want `fontSize=96` if the user changes mark to `text`.  

Therefore, we should instead move all `value` to `config.mark` so that we can have separate config for `config.size`, `config.barWidth`, `config.tickWidth`, `config.fontSize` respectively.  For `config.mark.color`, we can maintain similar behavior to `encoding.channel`.  Basically, if `config.mark.color` is set but `config.mark.fill` and `config.mark.stroke` is not,  then the color config is automatically applied to both fill and stroke.   (Explicitly specifying `fill` or `stroke` config will override `color` config.)

In addition, as @mcorrell point out, user might wonder when would a value be in encoding channel and when would it be in config.   This move will allow us to add other visual properties as an encoding channel in the future without deprecating their config.  

This proposal could work perfectly under the current model. 

One exception that we might need to bring value back in the future is only for `x` and `y`.  With layering, one sensible thing we might do is to add a reference line.  For a horizontal line, `y` channel should have a constant value.   I don’t know if it makes sense to set the reference line’s y value in `config.mark.y` because this doesn’t feel like config to me. 

@domoritz thoughts?

**Comment by domoritz** [comment]
One thought I have is that different defaults could be hierarchical. So for example we can have a default for color. That default applies to text color, fill color and line color. But we can also have values for the other three that default to undefined. The last level (that takes precedence), is the color channel.

**Comment by kanitw** [comment]
That's what I described except that I take color field first,  fill/stroke second and config.mark.color the third.   The reason the `fill/stroke` come first is that it is more specific, so it should override less specific config.

**Comment by domoritz** [comment]
I want the same precedence. Color channel has highest precensdence, then fill/text color/line/...., then color in config. I guess we wanted to say the same then and both didn't say it clear enough.

**Comment by kanitw** [comment]
Ok.   I guess so, but wasn't sure from your comment.    Also, there is no color/line -- it's line's `stroke` :p

**Comment by domoritz** [comment]
Details.

**Comment by kanitw** [comment]
Confusion :p

**Comment by kanitw** [comment]
Anyway, I'll do this this evening ;)

**Comment by kanitw** [comment]
One important observation I just found on the way home.

The value should still exist but only for constant value in the data domain.   Because encoding is mapping from data to visual channels (via scale for each channel).  Therefore, if a value is a part of "the data being mapped", it should be in the data domain.  

The use case that I mentioned for reference line is a constant value in data domain while the current use of value is on the range / visual domain.   

I think this should make sense in context of layering.  For the reference line layer, If x is specified with a constant value = “100”, its scale should have domain `[100]`.  When combined with another layer, then union scale would always have `100` included not matter the other layer has `100` in the domain or not.  

Similarly, if we think about layered color line chart with each layer and color as different measure.  (Each layer of line has the one color.)  Basically, for each layer of color, the domain of color scale is `[“<measure_name>”]`.  Once combined, the union color scale would have all measure names.

**Comment by kanitw** [comment]
Now `color|size|shape.value` are no longer used.  The next step (post 1.0) for this issue is the following:

- [ ] `has` method should look at value as well.
- [ ] if value is provided but field is not, then produces scale with `[value]` as the default domain.

**Comment by kanitw** [comment]
Actually, with interaction, value in the range domain might be useful.    
So the whole `config.mark` vs `value` thing now makes me really doubtful.

**Comment by domoritz** [comment]
Well, in that case you'd have a data source that you can use. I don't see the conflict.

**Comment by kanitw** [comment]
Let me clarify:

Suppose a point's color is determined by a selection-based predicate.   If selected, then color = red, else color =grey.   We probably need value property (in range/visual domain) for this purpose.  

Meanwhile, as mentioned earlier, we need `value` property in the data domain for things like reference line as well.

**Comment by domoritz** [comment]
A selection should include every point and say whether it is selected or not. At least that's what I imaged how you use a selection as a dataset. Probably something worth discussing with @arvind.

**Comment by kanitw** [comment]
Still, I assume you make a predicate and assign values (which could be a visual domain value)?  
Unless we want to go weird and do binary scale.
