### ISSUE TITLE
vl.compile does not appear to parse a .json spec contained in a file, does it ?

### ISSUE THREAD

**Issue by Georgeouz** [vega/vega-lite#1035]
When vl.compile is fed with an URI string (e.g. `vl.compile("uri/to/your/vega-lite/spec.json").spec;`) vl.compile throws an error: `TypeError: undefined is not an object (evaluating 'markCompiler[mark].markType')`. I'm using a browser to render the vega specification.

Is there a way to load a json specification file with vl.compile ? I could not find anything about it in the documentation. When I define the same specification directly in the script as a variable instead, everything works as documented.

**Comment by kanitw** [comment]
Currently our `vl.compile` only accepts spec in object form, so this would not work.   

You probably want to do something like:

```js
d3.json(url, function(error, spec) {
  const vgSpec = vl.compile().spec
  ...
}
```

If you just want to render the visualization, another alternative is to use [vega-embed](https://github.com/vega/vega/wiki/Embed-Vega-Web-Components).

```js
vg.embed({
  mode: 'vega-lite',
  url: <url_to_your_spec>
});
```

(We are updating the document, so more detail about using Vega-lite with vega-embed will be included in the docs/tutorial soon.)

**Comment by Georgeouz** [comment]
Thank you very much for the very swift response! I'll try the two suggested alternatives.

**Comment by arvind** [comment]
Worth noting that Vega [does allow](https://github.com/vega/vega/wiki/Runtime) a URL to a spec as input without needing a D3/vg.embed wrapper. Might be good to ensure Vega-Lite supports this as well for consistency?

**Comment by kanitw** [comment]
`vl.compile` is currently synchronous and I don't feel like losing the benefit of being synchronous for this purpose.  

That said, maybe we could introduce `vl.parse.spec` (or some better name?) that loads the spec, compile the spec and call `vg.parse.spec`?  

@domoritz  what do you think?

**Comment by domoritz** [comment]
I agree that it's nice to have a synchronous API to vl. I don't think there is too much need to a wrapper for vl.compile and vg.parse because we have vega embed.
