### ISSUE TITLE
Easy way to render inline specs in docs

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1036]
```html
<span class="render-vl">
'''json   <- replace with backticks
{
  "data": {
    "values": [
      {"a":"A", "b":28}, {"a":"B", "b":55}, {"a":"C", "b":43},
      {"a":"D", "b":91}, {"a":"E", "b":81}, {"a":"F", "b":53},
      {"a":"G", "b":19}, {"a":"H", "b":87}, {"a":"I", "b":52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"type": "ordinal","field": "a"},
    "y": {"type": "quantitative","field": "b"}
  }
}
''' <- replace with backticks
</span>
```

This should automatically render the source code and a chart next to it.

Bonus points for a script that automatically extracts the json specs into a directory under examples. We want this so we can test the examples. You can use something like https://www.npmjs.com/package/markdown-code-blocks. Probably we need to add an id to the block above to have a unique file name.

For examples that should be loaded from a URL, this would be awesome:

```html
<div class="vl-chart" data-file="ex-point_1d"></div>
```

This should automatically replace the element so that the result looks like above but the spec should be loaded from `examples/ex-point_1d.json`.

**Comment by kanitw** [comment]
I don't think you should include back ticks in this case, since you backtick stuff will be processed by markdown's redcarpet?  (Or if you wrap it with `<div>` maybe it does not get processed.)

Also, if you really want this, you better implement it now because this is time that we are writing docs.  Writing this later and refactor everything isn't a good use of time.

**Comment by domoritz** [comment]
Yes, ``` get's translated by markdown into a code block. But what I imagine is that we just let markdown render the code block and then add the visualization next to it. I'm not sure how we would be able to access the raw data in js any more. 

Maybe you're right and we don't add the backticks and just render in js.

**Comment by domoritz** [comment]
Done in dc1090842e98684bd38a697aec42c1380c33079c
