### ISSUE TITLE
Highlightjs and rendered syntax highlighting look different. 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1037]

**Comment by domoritz** [comment]
<img width="272" alt="screen shot 2016-01-30 at 13 48 01" src="https://cloud.githubusercontent.com/assets/589034/12698683/1d75a692-c758-11e5-87f0-49c5940d75fb.png">
<img width="218" alt="screen shot 2016-01-30 at 13 48 06" src="https://cloud.githubusercontent.com/assets/589034/12698685/21a19d84-c758-11e5-9ee4-d747f068a261.png">

**Comment by kanitw** [comment]
Maybe the Mou theme I got for markdown is out of date.

**Comment by domoritz** [comment]
> Maybe the Mou theme I got for markdown is out of date.
No. 

The fundamental issue is that highlightjs does not distinguish `""` and `:`.

**Comment by willium** [comment]
This should mostly be fixed by https://github.com/vega/vega-lite/pull/1065

We should make sure to update highlight.js on the next release as well: https://github.com/isagalaev/highlight.js/issues/1074
