### ISSUE TITLE
Revise how to specify multiple fields for an encoding channel

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1047]
From a conversation with @arvind 

With a future extension that supports production-rule like structure. 

We need to revise how to we specify multiple fields (for `detail` especially)

Currently it is something like this:

``` js
{
  ...,
  encoding: { 
    ...,
    detail: [ {field: 'g1', ...},  {field: 'g2', ...}
  }
  ...
}
```

But if a production rule is an array too.  Maybe we need something like: 

``` js
{
  ...,
  encoding: { 
    ...,
    detail: { "field(s)": [{field: 'g1', ...},  {field: 'g2', ...}] }
  }
  ...
}
```

Probably need to consider about this more a bit.  But we should get it right before releasing 1.0.   

A few options:
a) Think about how to modify now.
b) We could release 1.0 with only full support for a single detail field (and consider array of detail as an experimental feature and thus we do not write docs about it.)
c) plan to remove it entirely.  We should just think that this action can be sort of done by concatenating two group by fields.  The weakness of this option is that `sorting` might no longer works with detail. 

(Probably need to decide on sorting (#993) first.)

**Comment by arvind** [comment]
My vote would be to punt on this for v1.0 unless there is a critical/compelling example for which this is useful for. Seems like a good feature to include in a subsequent minor release.

**Comment by kanitw** [comment]
Ok That has to be b. then.  Spending effort to remove this from the structure while we might add it back isn't a good use of time as well.

**Comment by kanitw** [comment]
Our current proposal in #1971 no longer requires us to make this revision.
