### ISSUE TITLE
Bin number does not always match tick number

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1050]
<img width="275" alt="screen shot 2016-02-02 at 16 12 18" src="https://cloud.githubusercontent.com/assets/589034/12768857/cc80c010-c9c7-11e5-99c1-187f51504aba.png">

```json
{
  "data": {"url": "data/seattle-weather.csv","formatType": "csv"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "precipitation","type": "quantitative", "bin": true},
    "y": {"field": "*","type": "quantitative", "aggregate": "count"}
  }
}
```

**Comment by kanitw** [comment]
We already opened this and discover that it is okay.  Please see the conclusion in https://github.com/vega/vega-lite/issues/868.
