### ISSUE TITLE
scale's useRawDomain:  calculate min/max values instead of passing raw data to scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1053]
Currently when we have `scale.useRawDomain`, true -- we pass source data table to scale so that it includes min and max of the data.  This is bad for some aggregation function such as `count` or `sum` that might have totally different domain.  

Instead of passing source data to the scale, 
- [x] we should rename this to `includeRawDomain` 
- [ ] calculate min and max in the summary table and pass min and max and the aggregated value being used.   (See `data.summary` method in `data.ts`)  This way, if the users use `aggregate: "sum"` but turn on `includeRawDomain`, we do not have to add rules to prevent passing the raw domain while this still behave correctly if the `aggregate` is `sum`.

**Comment by kanitw** [comment]
@yhoonkim  This is the issue I talk about.  I already rename `useRawDomain` to the new `includeRawDomain` but still haven't changed the behavior.

**Comment by kanitw** [comment]
@domoritz   I think this issue is a good idea and it might simplify the transform order.  

I totally forgot about this when we consider the transform order.

**Comment by domoritz** [comment]
Yeah, this sounds reasonable. I already extracted the scale data source in my code and this should be easy to add.

**Comment by kanitw** [comment]
@domoritz  seems like you have already done this?

**Comment by kanitw** [comment]
This is already done.
