### ISSUE TITLE
Revise `config.cell`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1057]
Current structure of `config.cell` does not make sense.  The "cell" concept should only happens when things are being faceted (and composed in the future, but we do not have it yet).  Right now, `config.cell` are mixing up three things: 

- [x] 1)  config.cell.width|height => `config.unit.width`, `config.unit.height`  

(in the future we add `config.unit.fitOrdinalScale` as boolean to the width. )

- [x] 2) The rest of cell config only makes sense when the visualization is faceted.  
-  `gridColor`, `gridOpacity`, `gridOffset` => These are facet's grid and thus should become `config.facet.grid.color`, `config.facet.grid.opacity`.  (I'm no longer sure if `gridOffset` is truly useful.)  
  - This should be nested under `config.facet` because we will have `config.facet.scale`, `config.facet.axis` as described in #1056 as well

- [ ] `'clip', 'fill', 'fillOpacity', 'stroke', 'strokeWidth',  'strokeOpacity', 'strokeDash', 'strokeDashOffset'`  are the real properties of the facet cells.   Maybe these could stay `config.cell.*` because it can be shared with other composition in the future.  Otherwise, it could be `config.facet.cell.*`.  

Although I do not like multiple level of nesting, I think this new proposed grouping make much more sense.  

@domoritz  Name suggestions are welcomed!

**Comment by kanitw** [comment]
A possibly better alternative to 1):

1) config.cell.width|height => `config.unit.width`, `config.unit.height`  and in the future we add `config.unit.fitOrdinalScale` as boolean to the width.

**Comment by kanitw** [comment]
With the proposal above, for unit visualization, `config.scene.*` and `config.cell.*` are now redundant.

**Comment by kanitw** [comment]
@domoritz   This is almost done ... have to decide between `config.cell.*` or `config.facet.cell.*`.  

It is unclear if people would expect the theme for facet's cell and concat's cell to be the same.   (If same -> `config.cell.*`.  Otherwise, `config.facet.cell.*`.)

**Comment by domoritz** [comment]
Why would they be different? Do they have different properties?

**Comment by kanitw** [comment]
They should have most of their properties the same, but theming wise they might appear slightly different because they are different operation.   I'm not really sure.
