### ISSUE TITLE
Support Wilkinson Dot Plots

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1060]
This will allow us to nicely create the [Wilkinson Dot Plots](https://community.jmp.com/t5/JMP-Blog/Two-kinds-of-dot-plots/ba-p/30446).

A few superb examples that inspire me:

http://graphics.wsj.com/job-market-tracker/

![track_national_unemployment__job_gains_and_job_losses_-_wsj_com](https://cloud.githubusercontent.com/assets/111269/12787578/dba882fc-ca4a-11e5-9f51-8b197de3ea3b.png)

http://roadtolarissa.com/nba-minutes/

![minute_by_minute_point_differentials_of_2015_nba_games](https://cloud.githubusercontent.com/assets/111269/12787612/ff9e1f1e-ca4a-11e5-986b-6dd52bf448c1.png)

To do this, we need to:
- [x] allow stacking point
- [ ] allow putting `_id` in the `field` (esp. for `detail`)
- [ ] allow using mid point of the stack operation instead of stack start / end

**Comment by domoritz** [comment]
Yeah, that would be amazing. Especially with animation!

**Comment by kanitw** [comment]
Another reason to support stacked point / line: overlay point and area on top of stacked area. 

![vega_editor](https://cloud.githubusercontent.com/assets/111269/16174649/0942a912-3581-11e6-8d21-df3138872559.png)




```
{
  "layers": [
    {
      "data": {"url": "data/cars.json"},
      "mark": "area",
      "encoding": {
        "color": {"field": "Origin","type": "nominal"},
        "x": {
          "bin": true,
          "field": "Horsepower",
          "type": "quantitative"
        },
        "y": {
          "aggregate": "count",
          "field": "*",
          "type": "quantitative"
        },
        "opacity": {"value": 0.5},
        "config": {"mark": {"stacked": false}}
      }
    },
    {
      "data": {"url": "data/cars.json"},
      "mark": "line",
      "encoding": {
        "color": {"field": "Origin","type": "nominal"},
        "x": {
          "bin": true,
          "field": "Horsepower",
          "type": "quantitative"
        },
        "y": {
          "aggregate": "count",
          "field": "*",
          "type": "quantitative"
        }
      }
    },
    {
      "data": {"url": "data/cars.json"},
      "mark": "point",
      "encoding": {
        "color": {"field": "Origin","type": "nominal"},
        "x": {
          "bin": true,
          "field": "Horsepower",
          "type": "quantitative"
        },
        "y": {
          "aggregate": "count",
          "field": "*",
          "type": "quantitative"
        }
      },
      "config": {"mark": {"filled": true, "strokeWidth": "1", "stroke":"#fff", "fill":"red"}}
    }
  ]
}
```

**Comment by kanitw** [comment]
ID can be done using `row_order` operator in the pending window transform #2488.

**Comment by kanitw** [comment]
Note that currently non-ranged mark (e.g. point, line) uses stack end point for it position (to allow overlaying point and line on top of stacked area.  However, when stacking point along like in Wilkinson dot plot.  We will need to use the mid position.

Two possible solutions:
1.  Use stack transform and manually calculate mid point
2.  Extend the `stack` property to support new type of "zero" offset.  (Maybe call it `zero-mid`?)

**Comment by kanitw** [comment]
Closing as this should be done as a part of https://github.com/vega/vega-lite/issues/3819
