### ISSUE TITLE
Replace type string with string literals. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1080]
Currently for most of Vega's string enums, we use `string;`  as a type.  
However, TS now supports [string literals](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types).  

Therefore, we should go through our schema and replace string with string literals where applicable.  

For example, Scale's `type` could become  `"linear" | "ordinal" | ...` instead of `string` (Simply copy full list from Vega!)

**Comment by domoritz** [comment]
We should wait for ts to support https://github.com/Microsoft/TypeScript/pull/6554

Otherwise we cannot use variables.

**Comment by kanitw** [comment]
I'm not sure if we still wanna do this since we already use these enums in other dependent projects.  Plus enum has the benefit of having autocomplete..

**Comment by kanitw** [comment]
I'll close this.  Please reopen if you have strong opinion about this.
