### ISSUE TITLE
Showcase Gallery

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1084]
Our gallery was originally designed for debugging and thus it shows the whole canvas for all visualizations.  This takes up a lot of space. 

However, showing just clipped examples would make the layout much nicer.  
For example, protovis's gallery looks really nice. 
https://mbostock.github.io/protovis/ex/

![protovis_-_examples](https://cloud.githubusercontent.com/assets/111269/12874615/ccc35dea-cd8b-11e5-9843-522c308e242b.png)

**Comment by kanitw** [comment]
@ZeningQu  Some more thoughts for you.  

Ideally, we should be able write markdown like this in gallery.md. 

```md
## Basic Plots
Add text description here

<script>showGallery("basic")</script>

## Customized
Add text description here

<script>showGallery("showcase")</script>

## Customized
```

(The `showGallery` method basically populate the examples in `"Basic"`, `"Showcase"` groups inside `examples/vl-examples.json` and use "title" field inside the gallery as each item's title.)

For images, we will need another script that run vl2vg script to pre-populate the images files.  

Depending on if css's `background-size: cover` leads to nice enough result, we might need to add offset parameter to `vl-examples.json`, similar to Vega's `examples.js`. (See [Vega website](http://vega.github.io/vega/).

**Comment by domoritz** [comment]
Instead of calling js function, which means that you don't actually know where to put the results, we should use tags. 

`<div class="gallery" data-gallery="basic"></div>` or something like that

**Comment by ZeningQu** [comment]
@domoritz Could you rename `gallery.md` something else so that the name `gallery.md` can be used by this showcase gallery?

**Comment by kanitw** [comment]
- [ ] should add good example with ordinal color scale to the chart.
