### ISSUE TITLE
Setting `channelDef.sort` to array for ordinal field should explicitly set the domain

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1085]
This use case shouldn't make sense for quantitative, temporal and nominal.   

- [ ] modify schema for `fieldDef.sort` 
- [ ] add a case to `scale.domain` in `scale.ts`

**Comment by ayush29feb** [comment]
Can you please elaborate? I am not sure what this feature is for.

**Comment by kanitw** [comment]
As mentioned in the meeting, ordinal data has inherent order (e.g., "small", "medium", "large").

`sort` property in a field def (soon to be renamed to channel def) then should support an array that explicitly sets the order, which in turn directly sets Vega's scale domain.

**Comment by kanitw** [comment]
@domoritz Thinking more about it I think we should mention in the docs that for sorting ordinal field, they should set the order custom `domain` explicitly instead of setting `sort`.  This way it will keep codebase simpler.   If you agree, I can easily update the docs now.
