### ISSUE TITLE
Unit Tests for Date/Time Labels Formatting

### ISSUE THREAD

**Issue by ayush29feb** [vega/vega-lite#1090]
I have been working on the issue #817, where I did something that made the formatting for labels with date/time go away. I think there should be some unit tests that checks if the final outcome have the formatted date/time. 

I am not sure if this is `vega` level detail or `vega-lite` though

**Comment by domoritz** [comment]
Can you provide steps to reproduce this? A vl spec would be helpful.

**Comment by kanitw** [comment]
@ayush29feb  Can you reply to @domoritz

**Comment by ayush29feb** [comment]
Hey, I think I discussed this in the meeting and realized it wasn't a problem, I was doing something wrong. I will look at it again
