### ISSUE TITLE
Wrong tick labels with simple dataset

### ISSUE THREAD

**Issue by johanneskoester** [vega/vega-lite#1091]
Hello and thanks for this great piece of software. I get wrong tick labels with this little spec:

```
{
  "description": "Dot-plot of two genes across a set of samples.",
  "data": {
    "values": [
      {
        "sample": "DLD_ETOH",
        "ARL8A": -0.040789,
        "GATA3": 0.23429
      },
      {
        "sample": "GBM_T21",
        "ARL8A": 0.03683,
        "GATA3": -0.077213
      },
      {
        "sample": "HCT116_2_T18",
        "ARL8A": -0.052044,
        "GATA3": 0.17492
      },
      {
        "sample": "HELA_T18",
        "ARL8A": -0.07994,
        "GATA3": 0.13834
      },
      {
        "sample": "MCF7_E2",
        "ARL8A": -0.3886,
        "GATA3": -0.78496
      }
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "ARL8A","type": "quantitative"},
    "y": {"field": "GATA3","type": "quantitative"}
  },
  "config": {"mark": {"filled": true},"grid": false}
}
```

You will see in the live editor that somehow the order of magnitude of the given values is misinterpreted.

**Comment by domoritz** [comment]
Thank you @ johanneskoester! 

The axis ticks are actually correct. by default, we use SI units (formatter is `s`). I changed the format to `f` so you can see the format without SI units. We use SI units because it better shows data of unknown magnitude. Please have a look at https://github.com/mbostock/d3/wiki/Formatting#d3_format to see the different formatting options.

```json
{
  "description": "Dot-plot of two genes across a set of samples.",
  "data": {
    "values": [
      {
        "sample": "DLD_ETOH",
        "ARL8A": -0.040789,
        "GATA3": 0.23429
      },
      {
        "sample": "GBM_T21",
        "ARL8A": 0.03683,
        "GATA3": -0.077213
      },
      {
        "sample": "HCT116_2_T18",
        "ARL8A": -0.052044,
        "GATA3": 0.17492
      },
      {
        "sample": "HELA_T18",
        "ARL8A": -0.07994,
        "GATA3": 0.13834
      },
      {
        "sample": "MCF7_E2",
        "ARL8A": -0.3886,
        "GATA3": -0.78496
      }
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "ARL8A","type": "quantitative", "axis": {"grid": false}},
    "y": {"field": "GATA3","type": "quantitative", "axis": {"grid": false}}
  },
  "config": {"mark": {"filled": true}, "numberFormat": "f"}
}
```

**Comment by domoritz** [comment]
<img width="270" alt="screen shot 2016-02-13 at 19 26 51" src="https://cloud.githubusercontent.com/assets/589034/13031594/c68ec22e-d287-11e5-8542-8dd1368a8f1f.png">

**Comment by johanneskoester** [comment]
Ok thanks! That makes a lot of sense. Sorry for the noise :-).

**Comment by domoritz** [comment]
We've had endless discussions about what should be the default because SI units can be confusing. You'r question is completely valid. Do you mind sharing what you use Vega-Lite for? Danke!

**Comment by johanneskoester** [comment]
Sure, I am writing a database application to store and visualize biomedical scores across samples. I'd  have expected scientific notation for small values. But I'm fine with switching it manually.

**Comment by domoritz** [comment]
Fantastic! 

One design decision in Vega-Lite is that we never need to see the data and compile a Vega spec with reasonable default values. Right now there is no way to switch the format depending on the magnitude of values in Vega.
