### ISSUE TITLE
Correctly Support Quantile, Quantize, Threshold Scales

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1092]
These are special scale types.  See [D3's docs](https://github.com/mbostock/d3/wiki/Quantitative-Scales) for more information. 

TODO:
- [ ] automatically set the range of these scales to discrete range `"ordinal"`.

- [ ] update rules method: `supportScaleType` and `fieldDefMatchScaleType`
  
- [x] don't provide unsupported properties such as `clamp`

- [ ] Create examples

- [ ] Update scale docs

Relevant to https://github.com/vega/vega/issues/518

See example specs: https://github.com/vega/vega/pull/727/files

**Comment by kanitw** [comment]
This is generally most useful for map, so should be done together with map.

**Comment by kanitw** [comment]
@willium   I'm currently revising scale docs (and refactor scale a bit) and just realized that we haven't implemented quantize, quantile, threshold scales.  

Since these scales are mostly useful for maps (and heatmaps), I'll assign this for you as you're doing the geo support.  

You can wait until I finish rewriting docs and refactoring scales first though. :)

**Comment by kanitw** [comment]
- [ ] Once `quantize` is implemented, revert https://github.com/vega/vega-lite/pull/2920 to include SchemeParams.count in the schema & docs again

**Comment by kanitw** [comment]
@zanarmstrong is asking for this in https://github.com/altair-viz/altair/issues/998

**Comment by domoritz** [comment]
This should probably wait for https://github.com/vega/vega-lite/pull/3825.

**Comment by zanarmstrong** [comment]
I saw that clamping was requested at the top of this bug, but is not supported.  

For what it's worth, there seems to be a clamping workaround for those who desire it. Presumably this is based on how linear interpolation works in D3.

<img width="582" alt="screen shot 2018-07-04 at 3 59 38 pm" src="https://user-images.githubusercontent.com/7397271/42295829-4b8d38fa-7fa3-11e8-891d-77c9c5034ccf.png">

<img width="571" alt="screen shot 2018-07-04 at 3 59 44 pm" src="https://user-images.githubusercontent.com/7397271/42295830-4d0d318a-7fa3-11e8-9867-cb6b7114cee1.png">


```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/us-10m.json",
    "format": {"feature": "counties", "type": "topojson"}
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "rate",
      "scale": {
        "domain": [
          0.07,
          0.07,
          0.10,
          0.10
        ],
        "range": [
          "#aaaaaa",
          "#aaaaaa",
          "#555555",
          "#555555"
        ],
        "type": "linear"
      }
    }
  },
  "height": 300,
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
          "format": {"type": "tsv"}
        },
        "key": "id",
        "fields": ["rate"]
      }
    }
  ],
  "width": 500,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}```

vs without clamp

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/us-10m.json",
    "format": {"feature": "counties", "type": "topojson"}
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "rate",
      "scale": {
        "domain": [
          0.07,
          0.10
        ],
        "range": [
          "#aaaaaa",
          "#555555"
        ],
        "type": "linear"
      }
    }
  },
  "height": 300,
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
          "format": {"type": "tsv"}
        },
        "key": "id",
        "fields": ["rate"]
      }
    }
  ],
  "width": 500,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}
```

**Comment by kanitw** [comment]
#4000 will fix this.
