### ISSUE TITLE
Consider if we should distinguish ordinal time unit and time (temporal) time unit by data type.  

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1096]
(I will describe more about this later.... but wanna jot down so we don't forget to discuss)

**Comment by domoritz** [comment]
As discussed, the types are not fundamentally different. We just treat them differently because we think there are better defaults if we know that the cardinality is small.

**Comment by kanitw** [comment]
Please do not close it, there is an issue here to be discussed (easier in person).

**Comment by kanitw** [comment]
This is one of the issue related to whether `type` should refer to the type post-transformation or pre-transformation.

**Comment by kanitw** [comment]
For the record, we discussed this and lean toward  the type as  post-transformation type.

**Comment by kanitw** [comment]
This will affect how we structure constraint in CompassQL as in https://github.com/uwdata/compassql/pull/104

**Comment by kanitw** [comment]
For temporal let's keep the type as is, asking users to use time data as ordinal type just feels so confusing.
