### ISSUE TITLE
Format is not applied to range

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1112]
When we use binning, we generate a range. However, that range does not respect number or time formatting. Note that for timeUnit, things are correct.

**Comment by kanitw** [comment]
Is there a transform in Vega that be can apply format before we concatenating bin_range?

**Comment by kanitw** [comment]
Here is an example screenshot and output spec:

<img width="428" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/18155449/98f880ec-6fc2-11e6-8010-2e06f0e84caf.png">

http://pastebin.com/CDrWHZAs

@arvind   is there any way we can apply number format in formula transform?  

@jpocom need this fixed for this research.

**Comment by arvind** [comment]
There are three format functions (that I just noticed are undocumented!) that can be called within an expression: `format` (for numbers), `timeFormat` and `utcFormat`. The first argument to each of these is a corresponding format string specifier, and then the value to format. So in the above example, the formula expr can be as follows: 
```
"expr": "format(',.2f', datum[\"bin_gas_start\"]) + '-' + format(',.2f', datum[\"bin_gas_end\"])"
```

Hope that helps, and I'll update the [Vega Expression documentation](https://github.com/vega/vega/wiki/Expressions) presently.
