### ISSUE TITLE
Do not output stroke property e.g., strokeWidth when there is no stroke fill.  

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1116]
(I guess the same has to be true for fill.)

**Comment by YuhanLu** [comment]
Could you please be more specific?

**Comment by kanitw** [comment]
Sorry I forgot to post an example.  

http://vega.github.io/vega-editor/?mode=vega-lite&spec=area&showEditor=1

Look at the output Vega spec.  We have output the following x-axis properties

```
"properties": {
            "axis": {"strokeWidth": {"value": 0}},
            "labels": {"angle": {"value": 0}}
}
```

But there is no `stroke` color, strokeWidth is unnecessary.   
(In fact, `labels` angle seems unnecessary here as well.)

**Comment by YuhanLu** [comment]
I am kind of confused. Doesn't it always have a default value for stroke? Then why `strokeWidth` is unnecessary? So does 'labelAngle'?

**Comment by kanitw** [comment]
Nope. To give an example

We have default color, which is applied to fill or stroke based on mark
type e.g., area = fill, line=stroke

**Comment by YuhanLu** [comment]
So the point here is we need to eliminate `strokeWidth` when mark is area? I looked at `axis.ts` there's nothing about `fill`. Doesn't label always have a default color as well? When do we need to remove `labelAngle` since label always exists?

**Comment by kanitw** [comment]
> When do we need to remove labelAngle since label always exists?

For `labelAngle` it's a different problem.  I think we should not output `{value: 0}` because it is implicitly 0 in Vega.
