### ISSUE TITLE
Refactor for composition & interaction

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1124]
## ~~To Support Production Rules~~

We no longer plan to have production rules in VL -- no need to handled any of these
```
- [ ] `model.fieldDef()` and `model.field()` should be eliminated since its assumption that there is one fieldDef per channel is no longer true)
  - [ ] For now, we can get a fieldDef from `model.encoding().<channel>`, but that's not good too.  Ideally, we should just pass the `fieldDef` we need around
- [ ] Reduce direct `model.axis()` call in `axis.ts` -- same for `model.legend()` in `legend.ts`
- [ ] ~~Split `properties()` in mark-*.ts into multiple methods (e.g.,   `x()`, `y()`, `shape()`).~~ (forked as #1284)
  - ~~Each of these methods should take `fieldDef` and `scaleName` rather than the model as input since one channel might have multiple fieldDefs.~~
```

## Other Refactor
- [x] Rename `model.has()` to either `model.hasScale()` (and support either `field` or `datum`)

**Comment by arvind** [comment]
A running list of notes/observations of possible areas for refactoring:

* [ ] All model init methods (`initScales`, `initAxis`) should have a standard method signature. 
* [ ] Variable extraction should not break the type system. For example, changing
```js
const scaleSpec = encoding[channel].scale || {};
const channelDef = encoding[channel];
```
   to
```js
const fieldDef  = model.fieldDef(channel),
          scaleSpec = fieldDef.scale || {};
```
* [ ] Standardize on accessing the full encoding
  * Currently: model.encoding(), model._encoding, model.mapping(). 
* [ ] Standardize accessing a particular channel 
  * Currently: model._encoding[channel], model.fieldDef()

**Comment by kanitw** [comment]
Looks like most of these have been handled.  If there is any specific thing, you still think should be done, please file another issue.
