### ISSUE TITLE
Need to adjust color and size range if scale.zero=true

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1132]

**Comment by ZeningQu** [comment]
If scale.zero = true, default size could start from 0 px or 1 px, color could start from white, or a light color, or black, or a dark color. This should be consistent with the current defaults.

**Comment by kanitw** [comment]
To clarify, you only need to adjust the default scale ranges.   If user explicitly specify scale `range`, no need to deal with them.  

For example, `9` in [this line](https://github.com/vega/vega-lite/blob/master/src/compile/scale.ts#L398) could become `1` if `zero` is true.

For [this line](https://github.com/vega/vega-lite/blob/master/src/compile/scale.ts#L406), you might need to add another config `sequentialColorRangeWithZero` and find a reasonable light green value.  (If you think existing color is good, then there is no need to change.)

**Comment by kanitw** [comment]
The tricky part is that `zero(...)` should now be called before `rangeMixins()` in `scale.ts`.

**Comment by kanitw** [comment]
Already done!
