### ISSUE TITLE
Generate docs from schema

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1133]
The process could look as follows:

* Generate json schema from typescript with comments
* A script takes the json schema and creates a file in `_includes` with a table just like the ones we have in the docs for each defined object.
* We manually include the tables in the docs with `{% include bin_properties.md %}`

**Comment by kanitw** [comment]
The description here is as completed as what we discussed in person.  

We need to be able to specify which properties we want in each table.  For example, [axis.md](https://github.com/vega/vega-lite/blob/master/site/docs/axis.md) nicely group axis properties into multiple tables although all of them are properties of `Axis` object.

**Comment by kanitw** [comment]
The description here is **NOT** as completed as what we discussed in person.  

We need to be able to specify which properties we want in each table.  For example, [axis.md](https://github.com/vega/vega-lite/blob/master/site/docs/axis.md) nicely group axis properties into multiple tables although all of them are properties of `Axis` object.

**Comment by kanitw** [comment]
Actually, another thing to consider is that currently in the table, sometimes to highlight code using backtick.   

Maybe when copying description to the TS  file, we might need to convert the backtick to html so that the tables stay the same.   (Or find a way to parse the comment in TS as markdown, but I'd say converting to html would be much simpler.)

**Comment by domoritz** [comment]
As an alternative, we could simply not do this and only have very brief descriptions in the code and not bother about keeping the code and docs automatically in sync. I think I actually prefer that.

**Comment by kanitw** [comment]
I'm fine with that too.

**Comment by kanitw** [comment]
Yeah, given this complicated requirement, let's not do this.
