### ISSUE TITLE
Support Binning post-aggregation

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1152]
```
{
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "column": {"field": "Origin", "type": "O"},
    "row": {"bin": true, "field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"aggregate": "count", "field": "*", "type": "quantitative", "bin": true}
  }
}
```

![screen shot 2016-02-18 at 16 47 10](https://cloud.githubusercontent.com/assets/589034/13163122/4656c44a-d65f-11e5-83a3-27e33b26f8d2.png)

**Comment by kanitw** [comment]
which aspect of this plot do you mean?

**Comment by domoritz** [comment]
The axis labels are inside.

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/14260832/40a1a016-fa62-11e5-9f19-5c8dfe2ff144.png)

I tried this on the published version and rotation is no longer a problem.  

The only problem left is this spec is binning a count field.  Thus, binning should be applied after aggregation?

A more general question is if both `aggregate` and `bin` are specified, do we always add binning post-aggregate?

**Comment by domoritz** [comment]
> A more general question is if both aggregate and bin are specified, do we always add binning post-aggregate?

I believe that's always correct. But only for fields where we specify both aggregate and bin. In other cases we have to bin before aggregating.

**Comment by kanitw** [comment]
I guess it is the same for timeUnit as well?

**Comment by kanitw** [comment]
Looks like this should not be a problem for supporting in the transform order, but we don't really need to support this so let's close it.
