### ISSUE TITLE
Some example vega-lite specs do not produce valid vega specs

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1156]
`examples/examples.test.ts` is not actually validating that the compiled specs match `vega-schema.json`, since https://github.com/vega/vega-lite/blob/master/examples/examples.test.ts#L28:

```
  const isVgValid = validator.validate(vegaSpec, vgSchema);
```

should instead be:

```
  const isVgValid = validator.validate(vegaSpec.spec, vgSchema);
```

Once the above change is made, 23 of the vega specs fail schema validation:

1. area.json
2. area_vertical.json
3. bar_yearmonth.json
4. line.json
5. line_color.json
6. line_detail.json
7. line_monotone.json
8. line_month.json
9. line_step.json
10. point_dot_timeunit_color.json
11. point_ordinal_color.json
12. scatter_color_ordinal.json
13. scatter_color_ordinal_custom.json
14. stacked_area.json
15. stacked_area_normalize.json
16. stacked_area_ordinal.json
17. stacked_area_stream.json
18. trellis_bar.json
19. trellis_barley.json
20. trellis_row_column.json
21. trellis_scatter.json
22. trellis_scatter_binned_row.json
23. trellis_stacked_bar.json

**Comment by domoritz** [comment]
Oh wow. Good catch. We moved the vega output spec into an object and forgot to update.

**Comment by arvind** [comment]
Note, there have been some errors in the Vega schema that have been fixed in the master branch. For example, `area.json` validates for me.
