### ISSUE TITLE
Start page looks different in Firefox vs Chrome

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1174]
The height of the images is different. 

<img width="1079" alt="screen shot 2016-02-23 at 00 05 11" src="https://cloud.githubusercontent.com/assets/589034/13245327/2cc9bb80-d9c1-11e5-8f53-5b8c92b8f1a3.png">
<img width="1070" alt="screen shot 2016-02-23 at 00 05 15" src="https://cloud.githubusercontent.com/assets/589034/13245331/30cc2aba-d9c1-11e5-8574-08a9b686cfbd.png">

**Comment by willium** [comment]
This will need to redone. Probably okay for v1?

**Comment by willium** [comment]
I'm not entire sure how, but this seems to work fine for me as-is. 
![screen shot 2016-03-06 at 2 17 49 am](https://cloud.githubusercontent.com/assets/356976/13553533/b7f7a2c4-e341-11e5-9555-e408b3bcefaa.jpg)

**Comment by domoritz** [comment]
Yeah, something changed. The plots used to not be squares but rectangles that are slightly wider than tall.

**Comment by willium** [comment]
Good to close?

**Comment by domoritz** [comment]
Let me see at what point the rectangles became squares. I feel the showcase is too tall now and we could show more content.

**Comment by domoritz** [comment]
Looks like it was changed in https://github.com/vega/vega-lite/commit/b72da4622bbb624fd2810cec6c075c00b5ca4c44. We were under time pressure to fix it so the patch was fine. I created this issue when we merged so we can clean things up now.
