### ISSUE TITLE
Facet with Independent Scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1193]
- [ ] correct `assembleSignals()` in `facet.ts`

**Comment by kanitw** [comment]
@domoritz test this

**Comment by domoritz** [comment]
It's broken

```json
{
  "facet": {
    "column": {
      "field": "numParts",
      "type": "ordinal"
    },
    "row": {
      "field": "regex",
      "type": "nominal"
    }
  },
  "spec": {
    "data": {
      "values": [
        {
          "regex": 0,
          "globalTime": 256,
          "numParts": 256
        },
        {
          "regex": 0,
          "globalTime": 512,
          "numParts": 512
        },
        {
          "regex": 0,
          "globalTime": 64,
          "numParts": 64
        },
        {
          "regex": 0,
          "globalTime": 1024,
          "numParts": 1024
        },
        {
          "regex": 0,
          "globalTime": 128,
          "numParts": 128
        }
      ]
    },
    "mark": "bar",
    "config": {
      "cell": {
        "width": 600,
        "height": 350
      }
    },
    "encoding": {
      "y": {
        "field": "globalTime",
        "type": "quantitative"
      },
      "x": {
        "field": "numParts",
        "type": "nominal"
      }
    }
  },
  "resolve": {
    "x": {
      "scale": "independent"
    }
  }
}
```


Error: `Uncaught Error: Undefined data set name: "scale_child_main"`

**Comment by domoritz** [comment]
@kanitw What's odd is that the labels on the bottom are misaligned. Is there a way to fix this in the layout?

**Comment by kanitw** [comment]
I think there is a way to set the width of the axis to be larger

**Comment by kanitw** [comment]
I think you can use `minExtent` and `maxExtent` 

See  https://vega.github.io/vega/docs/axes/

Not sure if we really have to modify any rule -- maybe just setting the value for this spec is fine?

**Comment by kanitw** [comment]
Or maybe we can set a fixed `min/maxExtent` https://github.com/vega/vega-lite/issues/2282

**Comment by rsiebeling** [comment]
For what it's worth, I found myself wanting this today: specifically, a version with independent scales. This would be nice for comparing trends in similar but distinct data sets that have very different magnitudes without normalizing them (and losing information). 

Would this be solved?

**Comment by kanitw** [comment]
@rsiebeling Yep, very soon

**Comment by rsiebeling** [comment]
Great, can't wait till the final release. Keep up the good work ;-)

**Comment by kanitw** [comment]
This will be fixed as a part of https://github.com/vega/vega-lite/pull/2697
