### ISSUE TITLE
Decide if we want to cause side effect to the original spec.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1195]
Our model may drop some channel definition from the encoding if the channel is not supported by the mark.    However, this dropping process currently causes side effect to the original spec.   
We should decide if we still want that to be the case.

**Comment by domoritz** [comment]
You mean we modify the spec that is passed to `vl.compile`? That seems undesirable.

**Comment by kanitw** [comment]
Side effect removed in #1192
