### ISSUE TITLE
time unit 

### ISSUE THREAD

**Issue by masalmon** [vega/vega-lite#1198]
Great tool!

Would you consider adding "yearmonthdayhoursminutesseconds" as a time unit?

**Comment by kanitw** [comment]
Yes.    

We will also make all time units singular compound   (`yearmonthdayhourminutesecond` rather than `yearmonthdayhoursminutesseconds`).

**Comment by kanitw** [comment]
Thanks for catching our oversight :)

**Comment by domoritz** [comment]
Will add.

**Comment by kanitw** [comment]
> We will also make all time units singular compound (yearmonthdayhourminutesecond rather than yearmonthdayhoursminutesseconds).

Actually let me take that back.   We would keep it the same.

**Comment by masalmon** [comment]
Thank you!
