### ISSUE TITLE
background not present when export as PNG

### ISSUE THREAD

**Issue by hrbrmstr** [vega/vega-lite#1204]
Ref: https://github.com/hrbrmstr/vegalite/issues/6

(I noticed this myself in my own tests). Is there something I need to add via `<link>…` or <script>…` tags to make this work?

**Comment by domoritz** [comment]
This is a Vega issue. I reported it at #543

**Comment by domoritz** [comment]
Fixed in Vega 2.5.1. We will release a new vl version with the fixes soon.
