### ISSUE TITLE
Concatenation

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1206]
- [ ] arbitrary concat
- [ ] shared scale concat

It seems like arbitrary concatentation (without shared scale is more important?)
- [ ] update vl.fieldDef.fieldDefs()

**Comment by domoritz** [comment]
For the overview + detail we could share the x axis/ scale but if they are independent, we will be fine as well.

**Comment by kanitw** [comment]
We now have basic support for vconcat.  Unfinished things now have separate issues.
