### ISSUE TITLE
Conflicting Browserify requirement

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1224]
Vega-lite currently requires 

```
"browserify": "^13.0.0",
```
but it also requires `"browserify-shim": "^3.8.12",` which requires ` browserify@>= 2.3.0 < 12`

Thus, installing Vega-Lite in dependent project such as compass would fail due to this conflicting requirement. 

```
npm ERR! peerinvalid The package browserify does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tsify@0.13.2 wants browserify@>= 6.x
npm ERR! peerinvalid Peer browserify-shim@3.8.10 wants browserify@>= 2.3.0 < 12
```

@domoritz  any reason why we need browserify 13.0.0?  FYI, try this compass branch https://github.com/vega/compass/pull/158
I wonder if this is simply caused by your version update script.

cc: @yhoonkim

**Comment by kanitw** [comment]
@domoritz   FYI, try this compass branch https://github.com/vega/compass/pull/158

**Comment by domoritz** [comment]
The new release is coming soon with support for 13 https://github.com/thlorenz/browserify-shim/blob/master/package.json#L34

We should be able to say how the conflict should be resolved, right?

**Comment by domoritz** [comment]
Also, why are the tests passing on travis in https://github.com/vega/compass/pull/158?

**Comment by kanitw** [comment]
Because you don't need to build typescript to test?  Haven't looked closely.

**Comment by kanitw** [comment]
> We should be able to say how the conflict should be resolved, right?
If I understand correctly, normally the `resolveConflict` is mostly for resolving conflicts between the dependencies of dependencies.  In this case, it's a conflict between a dependency of a dependency (browserify shim depends on browserify 12) and the dependency of the project itself (Vl depends on browserify 13).   So the right we to resolve conflict is to set VL's dependency to a non-conflicting version.  

> The new release is coming soon with support for 13
Sure, but we shouldn't update before it is supported, right?

**Comment by domoritz** [comment]
> Sure, but we shouldn't update before it is supported, right?

Definitely! We don't rely on any features in 13 so set it to 12 if that helps compass.

**Comment by kanitw** [comment]
ok will do.
