### ISSUE TITLE
Binning legend has inconsistent overlap and sorting

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1242]
A spec with a binned color legend had two problems:

1. The legend items are not sorted by their underlying values (3-4 comes after 8-9).
2. Some ranges overlap (5-6 & 6-7), while other ranges do not (6-7 & 8-9). The overlapping of bins should be consistent.

Example (similar to `examples/specs/scatter_binned_color.json`):

```
{
  "data": {"url": "data/cars.json"},
  "mark": "point", 
  "encoding": {
    "x": {"field": "Horsepower","type": "quantitative"},
    "y": {"field": "Miles_per_Gallon","type": "quantitative"}, 
    "color": {"bin": {"maxbins": 5}, "field": "Cylinders","type": "quantitative"}
  }
}
```

![unknown](https://cloud.githubusercontent.com/assets/659086/13790409/adeadc90-eabe-11e5-9178-a6ca86ee0301.png)

**Comment by kanitw** [comment]
Thanks for reporting.  

@domoritz – haven't we already fixed this?

**Comment by kanitw** [comment]
The current master branch already produces correct result for this.
