### ISSUE TITLE
Stacking should be enabled when bar size is set

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1243]
The following bar chart with both a size and shape channel will correctly stack the chart:

```
{
  "data": {"url": "data/seattle-weather.csv", "formatType": "csv"},
  "mark": "bar",
  "config": {
    "mark": { "opacity": 0.5 }
  },
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "timeUnit": "month"
    },
    "y": {
      "field": "*",
      "type": "quantitative",
      "aggregate": "count"
    },
    "color": {
      "field": "weather",
      "type": "nominal"
    },
    "size": {
      "field": "weather",
      "type": "nominal"
    }
  }
}
```

![unknown-1](https://cloud.githubusercontent.com/assets/659086/13793011/1e63bb48-eacb-11e5-89d1-b61fcaf11b48.png)

But if the color channel is removed:

```json
{
  "data": {"url": "data/seattle-weather.csv", "formatType": "csv"},
  "mark": "bar",
  "config": {
    "mark": { "opacity": 0.5 }
  },
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "timeUnit": "month"
    },
    "y": {
      "field": "*",
      "type": "quantitative",
      "aggregate": "count"
    },
    "size": {
      "field": "weather",
      "type": "nominal"
    }
  }
}
```

The bars are no longer stacked and are overlayed on top of each other:

![unknown-2](https://cloud.githubusercontent.com/assets/659086/13793025/358105c4-eacb-11e5-8355-a7d57b2c0792.png)

**Comment by kanitw** [comment]
Thanks for reporting.  I think stacking should be **supported** for size, but I need to think about what's the best default (I'm leaning toward your suggestion though).
