### ISSUE TITLE
Composition Docs Revision

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1245]
- [ ] Rule Mark
  - [ ] `ruleSize`, `ruleRangeSize`

**Comment by kanitw** [comment]
## `composition.md`


- [ ] layer is a bit too detailed

> Vega-Lite automatically unions scale domains and combines axes and legends.
> However, Vega-Lite can not enforce that a unioned domain is semantically meaningful. To prohibit layering of composite views with incompatible layouts, the layer operator restricts its operands to be single or layered views.

I think these information are too detailed for a composition intro page.

**Comment by mcorrell** [comment]
The [resolve page](https://vega.github.io/vega-lite/docs/resolve.html) is a little too abstract, compared to the others. It could benefit from an example, and some words about when these field should be used (like with the other docs, esp. mark and composition).

**Comment by kanitw** [comment]
# `facet.md`

- [ ] Missing details in the properties table
- [ ] Missing links for special properties in the properties table
- [ ] Add example to help explain how a shortcut is transformed (normalized) into a full spec
- [ ] Missing sort 
- [ ] Missing details about how to customize facet labels and title -- @kanitw

> A `FacetFieldDef` is similar to a [channel definition](encoding.html#def).

- [ ] once we refactor encoding.md to distinguish field def and value def, we should say field def here, not channel def.

**Comment by ZeningQu** [comment]
> Through this **hierarchical composition**, you can create a whole dashboard as a single specification.

This is so exciting! It would be nice if there is an example specification for a whole dashboard. 

The word "dashboard" makes me think of layout, which Tableau and PowerBI supports (e.g., organizing small and large views, arranging repeated views and layered views on the same dashboard etc.). I doubt that's the kind of dashboard you mean here right?

**Comment by jhoffswell** [comment]
On the [resolve](https://vega.github.io/vega-lite/docs/resolve.html) page, you say:

> The defaults documented on the faceting, layering, concatenation, and repeating pages.

However, the documentation for resolve on these pages seems to generally be about one sentence, e.g.

> The default resolutions for facet are shared scales, axes, and legends.

If the default documentation is going to be this short on the other pages, I think it might be more reasonable to just include the same level of documentation on this page as well, rather than requiring the user to check each other page individually. Maybe something like:

> The default resolutions for [facet](https://vega.github.io/vega-lite/docs/facet.html#combined-scales-and-guides) and [layer](https://vega.github.io/vega-lite/docs/layer.html#resolve) are shared scales, axes, and legends. The default resolutions for [concatenation](https://vega.github.io/vega-lite/docs/concat.html#resolve) are independent scales, axes, and legends. The default resolutions for [repeat](https://vega.github.io/vega-lite/docs/repeat.html#resolve) are independent scales and axes for spatial channels and shared scales and legends for legends.

**Comment by jhoffswell** [comment]
On the [repeat](https://vega.github.io/vega-lite/docs/repeat.html) page, you say:

> To create a faceted view, define how the data should be faceted in facet and how each facet should be displayed in the spec.

This sentence probably needs to be changed (or removed) for this page.

**Comment by jhoffswell** [comment]
On the [composition](https://vega.github.io/vega-lite/docs/composition.html) page, it might be nice to have small examples/images to help explain what each operator is for to help readers find the correct part of the documentation for their task.

**Comment by jhoffswell** [comment]
On the [layer](https://vega.github.io/vega-lite/docs/layer.html) page, you say:

> This operator is none of Vega-Lite’s view compositon operators.

Which has two typos, fixed below:

> This operator is one of Vega-Lite’s view composition operators.

**Comment by jhoffswell** [comment]
On the [layer](https://vega.github.io/vega-lite/docs/layer.html) page, when you say:

> The population of the German city of Falkensee over time. Based on a visualization built using Vega.

The link does not work.

**Comment by kanitw** [comment]
- [ ] Clarify that https://github.com/vega/vega-lite/issues/2415 is not supported yet

**Comment by domoritz** [comment]
Fixed broken link to fsee example in c04f86d0. Thanks @jhoffswell!

**Comment by domoritz** [comment]
Fixed typos in 87340ccf

**Comment by kanitw** [comment]
- [ ] Repeat page should mention that Field is now an object to refer to the values in the repeat operator.

**Comment by kanitw** [comment]
- [ ] Properties in Repeat page is incomplete

**Comment by kanitw** [comment]
- [ ] Examples for concat docs (https://github.com/vega/vega-lite/issues/2886)

**Comment by kanitw** [comment]
- [ ] Add more examples to the gallery

**Comment by kanitw** [comment]
- [ ] Add more clarification about legend resolution (see https://github.com/vega/vega-lite/issues/2987#issuecomment-328289343 for example).

**Comment by kanitw** [comment]
- [ ] How to modify axis properties for shared scale

**Comment by kanitw** [comment]
- [ ] resolve docs is completed outdated (it's still `resolve.<channel>.scale/axis/legend` rather than `resolve.scale/axis/legend.<channel>`

**Comment by kanitw** [comment]
- [ ] Facet properties table does not show description for `facet` and `spec`.  May need to modify the template.
