### ISSUE TITLE
Revising Fill and Stroke

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1246]
@domoritz  We could discuss about different alternatives here.

**Comment by domoritz** [comment]
What's wrong with the current model?

**Comment by kanitw** [comment]
@domoritz  Well, you're complaining about it the other day that the overriding logic can be complicated.

**Comment by domoritz** [comment]
Oh, I see. Yeah. I wonder if we could put the logic into a function. Something like `getValue('color', 'fillColor')` that first looks up the most specific value and bubbles up through to the config if there is no value defined anywhere else.

**Comment by kanitw** [comment]
How is that different from the way it is currently written?

**Comment by kanitw** [comment]
#1655 is one problem with the current approach and I certainly think #1278 is the way to go, so let's close this in favor of #1278.
