### ISSUE TITLE
Correctly implement scale union

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1250]
- [ ] ordinal requires union support in Vega.
- [ ] quantitative is not implemented yet.

**Comment by domoritz** [comment]
I believe scale union works except for the case where the domain is an array. The problem is that we cannot union for the layout.

**Comment by kanitw** [comment]
@domoritz I believe you might have solve part of this or even all of this.

**Comment by domoritz** [comment]
Yes, I think so.
