### ISSUE TITLE
Layering: Follow-up

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1254]
- [ ] Correctly compute layout (not just the first view)
- [ ] Stacking inside layering
- [ ] Merge the domains for the legend scales in parseScale
- [ ] https://github.com/vega/vega/issues/722 allows us to have explicit domains merged with reffed domains.
- [ ] Unit tests
- [ ] More tests 
- [ ] Let users define the data source in the layer spec itself

**Comment by kanitw** [comment]
- [ ] parseLayer
  - [ ] incorrect propagation
  - [ ] incorrect merging logic

**Comment by domoritz** [comment]
What's incorrect? I think this comment is too ambiguous to be useful.

**Comment by kanitw** [comment]
- [ ] incorrect isFaceted condition in `mark.ts`  -> should be renamed to `useFacetedData`   

> 
However, this still seems wrong if the facet is a grandparent:

```
{
   data: ...,
   facet: ...,
   spec: {
    layer:  [{  
        // no data here and its parent is not a facet. 
        mark: ...
        encoding: ...
    }, {  
        // no data here
        mark: ...
        encoding: ...
    }]
  }
}
```
> and is also wrong in the case of splom.

**Comment by domoritz** [comment]
- [ ] Merge the domains in parseScale

**Comment by kanitw** [comment]
- [ ] take bin parameter into account for aggreage (see `addDimension()` in `src/compile/data/aggregate.ts`)

**Comment by domoritz** [comment]
Closing because it's outdated.
