### ISSUE TITLE
Considering removing `spec` property of facet and repeat

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1258]
Looking at the specs, I start wondering if it is too verbose.  

That said, this is a very minor point that we can revise later.

**Comment by kanitw** [comment]
Actually, besides verbosity, more important motivations are

1) if there is no `spec` property, we don't have to worry about preventing users from adding `data` property to the child spec. 

2) Transitioning between unit spec and faceted unit spec is simpler (simply adding `facet.column/row` to the spec).  

```js
{
   // To transition back to a unit spec, we have to 
   // (1) remove facet 
   // (2) move stuff inside `spec` outside 
   // (3) remove the `spec`

  "data": {"url": "data/movies.json"},
  "facet": {
    "column": {"field": "MPAA_Rating","type": "ordinal"},
    "row": {"field": "Major_Genre","type": "ordinal"},
  },
  "spec": {
    // NEED TO PREVENT INSERTING DATA HERE otherwise this will break facet semantic.
    "mark": "point",
    "encoding": {
      "x": {"field": "Worldwide_Gross", "type": "quantitative"},
      "y": {"field": "US_DVD_Sales", "type": "quantitative"}
    }  
  }
}
```
 

```js
{
  "data": {"url": "data/movies.json"}, // always one place to put data

  // To a transition back to a unit spec, simply removing this `facet` property. 
  "facet": {
    "column": {"field": "MPAA_Rating","type": "ordinal"},
    "row": {"field": "Major_Genre","type": "ordinal"},
  },

  "mark": "point",
  "encoding": {
    "x": {"field": "Worldwide_Gross", "type": "quantitative"},
    "y": {"field": "US_DVD_Sales", "type": "quantitative"}
  }
}
```

Similar for repeat, 

```
{
   // To transition back to a unit spec, we have to 
   // (1) remove repeat 
   // (2) move stuff inside `spec` outside 
   // (3) remove the `spec`

  // NEED TO PREVENT USERS FROM PUTTING DATA HERE
  "repeat": {
    "row": ["petalWidth","petalLength","sepalWidth","sepalLength"]
  },
  "spec": {
    "data": {"url": "data/iris.json"}, // need to put data in the child `spec`
    "mark": "point",
    "encoding": {
      "x": {"field": "petalWidth","type": "Q"},
      "y": {"field": {"repeat": "row"},"type": "Q"},
      "color": {"field": "species","type": "N"}
    }
  }
}
```

```
{
  // To reduce to unit spec, just remove this `repeat` part.  
  "repeat": {
    "row": ["petalWidth","petalLength","sepalWidth","sepalLength"]
  },
  "data": {"url": "data/iris.json"}, // one place to put data
  "mark": "point",
  "encoding": {
    "x": {"field": "petalWidth","type": "Q"},
    "y": {"field": {"repeat": "row"},"type": "Q"},
    "color": {"field": "species","type": "N"}
  }
}
```

Note that the model tree structure that we build should remain the same. 
For ease of implementation, we can expose the non-spec version as official support version but internally, we can have our `normalize` step produce the `nested spec` format?

**Comment by domoritz** [comment]
Or 

```json
{
  "data": {"url": "data/iris.json"}, // one place to put data
  "mark": "point",
  "encoding": {
    "x": {"field": "petalWidth","type": "Q"},
    "y": {"field": {"row": ["petalWidth","petalLength","sepalWidth","sepalLength"]},"type": "Q"},
    "color": {"field": "species","type": "N"}
  }
}
```

**Comment by kanitw** [comment]
From slack:

> @dom:    For your suggestion  I like its conciseness,  but I don’t like it’s subtly hidden in the spec.
I think people are familiar with having a wrapper of for loop with reference to iterator more than having repeat construct inside a repeated code.

So maybe the one in my comment might be better :)

**Comment by domoritz** [comment]
What would a layer inside a facet look like?

**Comment by kanitw** [comment]
{ facet:..., layer:[...] }

**Comment by kanitw** [comment]
{ data: ..., facet: ..., layer:[...]}

**Comment by domoritz** [comment]
And what about facet inside repeat?

**Comment by kanitw** [comment]
Good point.  As discussed in private conversation,  I think `repeat` should have higher precedence than `facet`.   

```
repeat: ..., // independent from data
data: ...,
facet: ...,  // requires data 
```

I can't think of one case where it is useful to have `facet` have higher precedence over repeat.
If we can find one, we might need to support `spec` property as a longer format to support this use case.  
(We shouldn't need to unless we find a convincing example.)

In general, they also shouldn't be used together because it might cause confusion due to the visual similarlity.  Plus, unless one operator operates on `column` and another operates on `row`, the output visualization might become too large.

**Comment by domoritz** [comment]
What about repeat inside repeat? The problem is that we remove the nesting property from the spec. This can be fine but may be problematic. We have to think through all the cases.

**Comment by kanitw** [comment]
> repeat inside repeat

Suppose we want to support it.  First we need to introduce alias for disambiguating different levels of repeat's iterator name. 
```
{
    values: ["A", "B", "C"]
    as:  "outer_column_iterator_name"
}
```

Then we need to either introduce `spec` or allow array of `RepeatValueDef = Array | { values: Array, as: string }`

That said, repeat over repeat would mostly produce too large charts, so I don't think we need to support it in the first release.

**Comment by kanitw** [comment]
(or even never support)

**Comment by kanitw** [comment]
I guess this is done?

**Comment by domoritz** [comment]
> I guess this is done?

I think your point is valid that you likely won't have a repeat inside a repeat or a facet inside a facet. But still, removing `spec` makes nesting even harder to understand.

**Comment by kanitw** [comment]
For repeat, keeping spec might make sense.   I'm not sure.  

For `facet`, I strongly think that you should not have spec because it screw up the order.   Plus, having `spec` might confused users that they can put `data` in the inner spec.  

```
{
  "data": {"url": "data/movies.json"}, // always one place to put data

  // To a transition back to a unit spec, simply removing this `facet` property. 
  "facet": {
    "column": {"field": "MPAA_Rating","type": "ordinal"},
    "row": {"field": "Major_Genre","type": "ordinal"},
  },

  "mark": "point",
  "encoding": {
    "x": {"field": "Worldwide_Gross", "type": "quantitative"},
    "y": {"field": "US_DVD_Sales", "type": "quantitative"}
  }
}
```

Facet splits the data, so the `facet` transform actually logically come after `data`.   

Plus, see my second comment from above.

**Comment by kanitw** [comment]
From the discussion today with @jheer, @arvind, @domoritz,

Another alternative we're considering is to keep `spec` property of a `facet` spec, but move `data` to the inside spec. In this case, we have to support disambiguating between the data source that we partition inside `spec`.

**Comment by kanitw** [comment]
I think we discussed about this and decide not  to do it.
