### ISSUE TITLE
Repeat: Follow-up

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1263]
We should consider
### Model
- [ ]  removing `model.title()`
- [ ] remove `fieldOrig()` since it is simply  `field()` with  `opt.nofn = true`
### colorrank.ts
- [ ] reconsider `colorrank.parseUnit`  (@domoritz has a comment there)
- [ ] consider merging multiple colorrank into one in `parseRepeat`
### formula.ts
- [ ] rename the file to `calculate.ts` for consistency with the component name? 
### nullfilter.ts
- [ ] correct propagate nullFilter in `parseRepeat`  (See FIXME)   ---  (or even nullFilter in other methods too?)
### source.ts
- [ ] merge children into different groups that are mergable.  (Current we only merge into one.) 
### stackscale.ts
- [ ] implement `parseRepeat`
### summary.ts
- [ ] extract a common method for `parseLayer` and `parseRepeat` if the current code is correct.  (They are exactly the same!)
### facet.ts
- [ ] implement `isRepeatRef`
### layer.ts
- [ ] move logic for `parseScale()` to `scale.ts` for easier readability.
### layout.ts
- [ ] support when each repeated unit do not have the same size 
### repeat.ts
- [ ] separate `config.repeat` from  `config.facet` 
- [ ] support repeated `layer` (separate issue for later?)  
- [ ] implement `isRepeatRef`
- [ ] move this `repeat.ts` to `scale.ts` for readability & comparability?
- [ ] complete `parseScale()`
- [ ] move `getRepeatGroupProperties` into the model if possible 
### FieldDef.ts
- [ ] update vl.fieldDef.fieldDefs()

**Comment by kanitw** [comment]
We should consider

### Model 

- [ ]  removing `model.title()`
- [ ] remove `fieldOrig()` since it is simply  `field()` with  `opt.nofn = true`

### colorrank.ts

- [ ] reconsider `colorrank.parseUnit`  (@domoritz has a comment there)
- [ ] consider merging multiple colorrank into one in `parseRepeat`

**Comment by kanitw** [comment]
### formula.ts

- [ ] rename the file to `calculate.ts` for consistency with the component name? 

### nullfilter.ts
- [ ] correct propagate nullFilter in `parseRepeat`  (See FIXME)   ---  (or even nullFilter in other methods too?)

### source.ts

- [ ] merge children into different groups that are mergable.  (Current we only merge into one.) 

### stackscale.ts
- [ ] implement `parseRepeat`

### summary.ts
- [ ] extract a common method for `parseLayer` and `parseRepeat` if the current code is correct.  (They are exactly the same!)

### facet.ts
- [ ] implement `isRepeatRef`

### layer.ts
- [ ] move logic for `parseScale()` to `scale.ts` for easier readability.

### layout.ts
- [ ] support when each repeated unit do not have the same size 

### repeat.ts
- [ ] separate `config.repeat` from  `config.facet` 
- [ ] (separate issue for later?) support `layer`
- [ ] implement `isRepeatRef`
- [ ] move this `repeat.ts` to `scale.ts` for readability & comparability?
- [ ] complete `parseScale()`
- [ ] move `getRepeatGroupProperties` into the model if possible

**Comment by domoritz** [comment]
I feel a lot of issues are related to the follow up changes in #1254

**Comment by domoritz** [comment]
One really important thing

- [ ] Figure out a smarter merging strategy for datasets. Right now we merge only into a single source. We should be able to push up individual transforms once we have figured out an order on transforms. It seems smarter to just leave a smaller data source that only does the necessary thing rather than a "move all or nothing" strategy. But this requires some careful thinking and design.

**Comment by kanitw** [comment]
- [ ] add example specs in #1257 or better examples to unit test and validation test

**Comment by domoritz** [comment]
I feel this is outdated. Reopen if you feel this is still relevant.
