### ISSUE TITLE
Supporting binding with UI element for quick filter

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1269]
For example, Vega-Lite spec should easily support filter and time slider widget as we see in [Gapminder](http://www.gapminder.org/world/#$majorMode=chart$is;shi=t;ly=2003;lb=f;il=t;fs=11;al=30;stl=t;st=t;nsl=t;se=t$wst;tts=C$ts;sp=5.59290322580644;ti=1800$zpv;v=0$inc_x;mmid=XCOORDS;iid=phAwcNAVuyj1jiMAkmq1iMg;by=ind$inc_y;mmid=YCOORDS;iid=phAwcNAVuyj2tPLxKvvnNPA;by=ind$inc_s;uniValue=8.21;iid=phAwcNAVuyj0XOoBL_n5tAQ;by=ind$inc_c;uniValue=255;gid=CATID0;by=grp$map_x;scale=log;dataMin=194;dataMax=96846$map_y;scale=lin;dataMin=23;dataMax=86$map_s;sma=49;smi=2.65$cd;bd=0$inds=;modified=75)

**Comment by kanitw** [comment]
I think Vega-Embed will have natural support for this.

**Comment by domoritz** [comment]
Crossfilter will be supported and you can build quickfilters that way. Not sure what you want with this issue.
