### ISSUE TITLE
Support multiple source datasets like vega

### ISSUE THREAD

**Issue by rufuspollock** [vega/vega-lite#1271]
At the moment vega-lite's data property is a little different from vega's in that it only allows one data source (and does not name it).

Will it be possible in future to have vega-lite support multiple datasets similar to vega?

Aside: whatever you do it might be worth documenting the difference here and what happens in the transformation to vega data as technical users (like me) would be interested. It took me a while to grok what was happening e.g. that the data from vega-lite always ends up in a dataset called source -- and I'm still unsure whether i can do late data binding (does the `layout` dataset get transformed ...)?

**Comment by domoritz** [comment]
We do not plan to support multiple data sources in a single view.  With multiple data sources the compiler wouldn't be able to resolve some ambiguities and so far we couldn't think of any use cases. We might add support for an initial union or join to combine multiple data sources into one, though. Is that what you were thinking about? 

Having said that, we do plan to support different data sources in different layers and when views are concatenated. We already have a few prototypes working (see https://github.com/vega/vega-lite/pull/1241 for example) but it's not production ready yet. 

> Aside: whatever you do it might be worth documenting the difference here and what happens in the transformation to vega data as technical users (like me) would be interested.

Yes. We should add more developer documentation. Probably in the form of readmes in the source code directories. 

> that the data from vega-lite always ends up in a dataset called source

Actually we create a `source` and also a s `summary` if the visualizations uses aggregation.

**Comment by rgrp** [comment]
@domoritz here's a summary of where i found "sharp edges": https://github.com/okfn/datapackage-render-js#research - a result of my working getting a rudimentary data package + vega-lite integration working :smile: )

BTW if you have time for a call at some point with me and e.g. @pwalsh think that could be super productive ...

**Comment by pwalsh** [comment]
@rgrp @domoritz would love to jump on a call for this.

**Comment by domoritz** [comment]
@rgrp Sure. Let's organize a call. I sent you a message.

**Comment by kanitw** [comment]
We now support lookup transform which allow a form of joining multiple data sources

**Comment by kanitw** [comment]
I'm closing this since I'm not sure what are the actionable items left.

**Comment by tcar06** [comment]
Does vega support multiple datasets now? Hope someone can show me an example or point me in the right direction.

**Comment by domoritz** [comment]
Vega or Vega-Lite?

**Comment by tcar06** [comment]
Vega-Lite

**Comment by domoritz** [comment]
In Vega-Lite, data can be defined per view. For example, two [hconcated charts](https://vega.github.io/vega-lite/docs/concat.html) may have different data.

**Comment by anandsunderraman** [comment]
what happens if there are multiple records matching an entityId ?

**Comment by ratnanil** [comment]
I would like to aggregate two datasets from two different API calls with identical structure (see below). I'm using `vconcat` now, but I was wondering is there a way to aggregate the data on a JavaScript level before using the data in Vega-Lite?


![image](https://user-images.githubusercontent.com/12532091/215998362-2682ad33-993e-405b-a7c6-9f328fe63806.png)

Data from 
1. https://api.stackexchange.com/2.3/users/4139249/top-tags?site=stackoverflow and
2. https://api.stackexchange.com/2.3/users/40929/top-tags?site=gis.stackexchange.com
