### ISSUE TITLE
Layer inside facet

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1272]
``` json
{
  "data": {"url": "data/weather.csv","formatType": "csv"},
  "facet": {"column": {"field": "location","type": "nominal"}},
  "spec": {
    "layers": [
      {
        "mark": "line",
        "encoding": {
          "x": {
            "field": "date",
            "type": "temporal",
            "timeUnit": "month"
          },
          "y": {
            "field": "temp_max",
            "type": "quantitative",
            "aggregate": "mean"
          },
          "color": {"field": "location","type": "nominal"}
        }
      },
      {
        "mark": "circle",
        "encoding": {
          "x": {
            "field": "date",
            "type": "temporal",
            "timeUnit": "month"
          },
          "y": {
            "field": "temp_max",
            "type": "quantitative",
            "aggregate": "mean"
          },
          "color": {"field": "location","type": "nominal"}
        }
      }
    ]
  }
}
```

Need to fix
- [ ] Creates references to summary that does not exist
- [ ] Does not create axis groups and keeps inner axes

**Comment by kanitw** [comment]
This is sort of done?

**Comment by kanitw** [comment]
Another example: Becker's barley with group median.
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "The Trellis display by Becker et al. helped establish small multiples as a “powerful mechanism for understanding interactions in studies of how a response depends on explanatory variables”. Here we reproduce a trellis of Barley yields from the 1930s, complete with main-effects ordering to facilitate comparison.",
  "data": {"url": "data/barley.json"},
  "facet": {
    "row": {
      "field": "site", "type": "ordinal",
      "sort": {"op": "median", "field": "yield", "order": "descending"}
    }
  }
  "spec": {
    "layer": [{
      "mark": "point",
      "encoding": {
        "x": {
          "aggregate": "median", "field": "yield", "type": "quantitative",
          "scale": {"zero": false}
        },
        "y": {
          "field": "variety", "type": "ordinal",
          "sort": {"field": "yield","op": "median", "order": "descending"},
          "scale": {"rangeStep": 12}
        },
        "color": {"field": "year", "type": "nominal"}
      }
    },{
      "mark": "rule",
      "encoding": {
        "x": {
          "aggregate": "median", "field": "yield", "type": "quantitative",
          "scale": {"zero": false}
        }
      }
    }]
  }
}
```

**Comment by domoritz** [comment]
Another example from https://github.com/vega/vega-lite/issues/1544

```
{
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv", "format": {"type": "csv"}},
  
  "mark": "line",
  "encoding": {
    "row": {"field": "symbol", "type": "nominal"},
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  },
  "config": {
    "overlay": {
      "line": true
    }
  }
}
```

**Comment by domoritz** [comment]
Still kinda broken but the dataflow is correct.

```
{
  "data": {"url": "data/seattle-weather.csv","formatType": "csv"},
  "facet": {"column": {"field": "weather","type": "nominal"}},
  "spec": {
    "layer": [
      {
        "mark": "line",
        "encoding": {
          "x": {
            "field": "date",
            "type": "temporal",
            "timeUnit": "month"
          },
          "y": {
            "field": "temp_max",
            "type": "quantitative",
            "aggregate": "mean"
          }
        }
      },
      {
        "mark": "circle",
        "encoding": {
          "x": {
            "field": "date",
            "type": "temporal",
            "timeUnit": "month"
          },
          "y": {
            "field": "temp_max",
            "type": "quantitative",
            "aggregate": "mean"
          }
        }
      }
    ]
  }
}
```

![screen shot 2017-04-14 at 16 15 04](https://cloud.githubusercontent.com/assets/589034/25058387/9a989e56-212d-11e7-9b90-d93d224c87d4.png)

**Comment by kanitw** [comment]
Many examples here are still broken, not sure why you close this issue.

**Comment by domoritz** [comment]
The dataflow is correct so I'm closing this issue. The problems with the layout and axes are contained in https://github.com/vega/vega-lite/issues/1544.

**Comment by kanitw** [comment]
FYI, given how you close it, there is no way to understand that things are in #1544 and that #1544 should re-use spec in this issue.

**Comment by domoritz** [comment]
Just copied the relevant specs.

**Comment by enotspe** [comment]
Is there a way to make a wrapped facet with layer inside???? I would like this visualization splitter just in 4 columns

`{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Histograma coloreado mayor a 80%",
  "data": {"url": "snmp-yanbal_1w.csv", "format": {"type": "csv"}},
    
  
  "facet": {
	"column" : {
		"field":"sede",
		"sort": {"op": "max", "field": "fgSysCpuUsage","order": "descending"}
		}
	},
	
  "spec": {
  
	  "layer": [		
			
			{
			  "mark": "bar",
			  
			  "encoding": {
				
				"x": {
					"bin" : {"step" : 20, "extent" : [0,100] },
					"field": "fgSysCpuUsage", 
					"type": "Q",
					"axis": {"title": "% CPU Usage"}
					},
				"y": {
					"aggregate" : "count",
					"scale": {"type": "log"},
					"axis": {"title": "1/4 minutes"}
					},
				"color": {"value": "#c8c2c2"}
				}
			},
			{
			  "mark": "text",
			  
			  "encoding": {
				"x": {
					"bin" : {"step" : 20, "extent" : [0,100] },
					"field": "fgSysCpuUsage", 
					"type": "Q"
					
					},
				"y": {
					"aggregate" : "count",
					"scale": {"type": "log"}
					},
				"text": {
					"aggregate" : "count",
					"scale": {"type": "log"}
					}
				
				}
			},
			{
				"mark": "bar",
				"transform": [
				  {"filter": "datum.fgSysCpuUsage >= 80"}
				],
				"encoding": {
				"x": {
					"bin" : {"step" : 5, "extent" : [0,100] },
					"field": "fgSysCpuUsage", 
					"type": "Q"
					},
				"y": {
					"aggregate" : "count",
					"scale": {"type": "log"}
					},
				"color": {"value": "#e45755"}
				}
			}
		]
	}
}
[snmp-yanbal_1w.zip](https://github.com/vega/vega-lite/files/3069885/snmp-yanbal_1w.zip)

`

**Comment by enotspe** [comment]
by the way, the 2 examples provided on https://vega.github.io/vega-lite/docs/facet.html#facet-full are exactly the same for Wrapped Facet and Wrapped Facet (with Facet Encoding)

**Comment by kanitw** [comment]
Please ask usage questions on stackoverflow or slack.  

To answer your first question, you can use wrapped facet with layer. (Just put a layered spec inside.  (If you have additional question, let's discuss on stackoverflow or slack.)
