### ISSUE TITLE
Support layer as a channel in repeat with color encoding

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1274]
We haven't implemented this but this seems useful for statistical plot.  

From a conversation this morning, @jheer has example statistical plot this would benefit from this.  

``` js
{
  "layers": [
{
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "select": {
    "sub": {"type": "interval"}
  },
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "size": {"field": "Acceleration", "type": "quantitative"}
  }
},
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "filterWith": "sub"
  },
  "mark": "rule",
  "encoding": {
    "y": {"field": "Miles_per_Gallon",  "type": "quantitative",
          "aggregate": "mean"},
    "color": {"value": "red"}
  }
},
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "filterWith": "sub"
  },
  "mark": "rule",
  "encoding": {
    "y": {"field": "Miles_per_Gallon",  "type": "quantitative",
          "aggregate": "median"},
    "color": {"value": "green"}
  }
},
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "filterWith": "sub"
  },
  "mark": "rule",
  "encoding": {
    "y": {"field": "Miles_per_Gallon",  "type": "quantitative",
          "aggregate": "q1"},
    "color": {"value": "black"}
  }
},
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "filterWith": "sub"
  },
  "mark": "rule",
  "encoding": {
    "y": {"field": "Miles_per_Gallon",  "type": "quantitative",
          "aggregate": "q3"},
    "color": {"value": "black"}
  }
}
 ],
 "config": {"cell": {"width":500, "height":500}}
}

```

**Comment by kanitw** [comment]
Another more compelling use case would be to create multiple series line chart of different fields without the need to unpivot the data into a long format.

For example, given a table from https://github.com/altair-viz/altair/issues/292,


![](https://cloud.githubusercontent.com/assets/7890526/22400015/dcd07518-e56f-11e6-8bc8-2278253bb4dc.png)


one should be able to create a spec like

```js
{
   repeat: {
     layer: ['Total', 'Tilt', 'Timing'] 
   },
   spec: {
       mark: 'line',
       encoding: {
          x: {field: {repeat: 'layer'}, ...}
          y: {field: 'date', ...},
          color: ... // still need to design how to map these color values to scale
       }
   }
}
```

**Comment by JonasSprenger** [comment]
It would be very useful.

**Comment by domoritz** [comment]
@JonasSprenger Yes. We won't release this in 2.0 but we will try to get this in soon after.

**Comment by LukasGrebe** [comment]
+1!
i'm currently trying to create a multi series line chart and was hoping this would work via repeat, instead of a verbose ~D~RY layering with copies of the view.

**Comment by domoritz** [comment]
You can create a multi-series line chart by pivoting the data such that you only have three fields: series, x, and y. https://vega.github.io/vega-lite/examples/line_color.html

**Comment by LukasGrebe** [comment]
Thanks! I had seen and used this, however i'd also like to use a transform to calculate the % difference between the series which, i think, i am unable to do having pivoted the data.

**Comment by domoritz** [comment]
This may be possible with window aggregates. Anyway, I think repeat into layer would be super useful. If you want to work on it, let me know.

**Comment by jakevdp** [comment]
I would also love to have this for multi-mark plots. For example, something like

```
{
   repeat: {
     mark: ['line', 'point'] 
   },
   spec: {
       mark: {repeat: 'mark'},
       encoding: {
          x: {field: 'date, ...}
          y: {field: 'value', ...},
       }
   }
}
```

**Comment by kanitw** [comment]
@jakevdp 

I was even thinking that we might consider  allowing mark to be an array to support the use case you mention

```
{
       mark: ['line', 'point'] ,
       encoding: {
          x: {field: 'date, ...}
          y: {field: 'value', ...},
       }
}
```

That said, it's just a thought -- we don't have any final call about this yet.

**Comment by jakevdp** [comment]
That could be useful.

The context in which I thought of this was in creating this example: https://bl.ocks.org/jakevdp/1643ebb6853e76c32e47a969f415f3ea

It's three layers in which the ``x``, ``y``, and ``color`` encodings are identical, but the ``mark`` and some other info differs.

**Comment by domoritz** [comment]
Repeat is really only syntactic sugar. I found Altair to be a great fit for this. It make sit super easy to create multiple subspecs with slightly varying values.

**Comment by kanitw** [comment]
Currently we can get around this using fold, however folding means we can't produce tooltip for both lines at the same time.

But using layer means we can't use color mapping yet.

That said, once we introduce `datum` (#1601, #4201), we can do the same mapping this elegantly:

```
{
   repeat: {
     layer: ['Total', 'Tilt', 'Timing'] 
   },
   spec: {
       mark: 'line',
       encoding: {
          x: {field: {repeat: 'layer'}, ...}
          y: {field: 'date', ...},
          color: {datum: {repeat: 'layer'}, type: 'nominal'}
       }
   }
}
```

**Comment by kanitw** [comment]
Basic implementation in https://github.com/vega/vega-lite/pull/6142, but we still need to add `datum` to create a compelling example.

**Comment by kanitw** [comment]
close https://github.com/vega/vega-lite/pull/6150
