### ISSUE TITLE
Add Other Encoding Channels as ValueDef only channel

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1278]
Many mark properties are currently customizable only via mark config. 
However, they should become new encoding channels. 
For now, let's make them constant values only.  

- [ ] text properties: align, angle, baseline, radius, theta, font, fontSize, fontStyle, fontWeight, ...
- [ ] `interpolate`, `tension`
- [ ] `orient`

- Fills and Strokes (Related, but let do it separately) #1821

## New Properties in Vega 3

- [ ] `cornerRadius`
- [ ] Check Vega 3's schema (See Mark's encodeEntry) to check if there are other properties not listed here 
- [ ] ...

## STEP
- [ ] Make `ValueDef` interface that only contains `value` and make `FieldDef` implements `ValueDef`
- For each one
  - [ ] Add channel to channel.ts
  - [ ] Add its ~~FieldDef~~ ValueDef to encoding.ts. 
  - [ ] ~~For ones that support `field`, add rules for scale type, domain (?), and range~~ 
  - [ ] Add reference in `compile/marks/*.ts`
     - [ ] Instead of calling `applyMarkConfig`, create a similar method in `valueref.ts` to output the value of these properties from `encoding`. 
     - [ ] Remove `applyMarkConfig` and make those references (e.g.,) correctly read from `encoding` instead. 

- [ ] Write Test
- [ ] Manually test specifying each of the property

**Comment by domoritz** [comment]
Opacity?

**Comment by kanitw** [comment]
Any other important ones?

**Comment by domoritz** [comment]
Line width?

**Comment by kanitw** [comment]
> Line width?

`strokeWidth` is an important one.  We couldn't map field to it yet though.   (Vega's line doesn't support variable width yet.)

**Comment by kanitw** [comment]
- [ ] all other properties that are passed through `applyMarkConfig` in `common.ts` – refactor `applyMarkConfig` to become `applyMarkProperty` to read from channel then config.

**Comment by kanitw** [comment]
- [ ] filled

**Comment by kanitw** [comment]
#1655 is one good example why we should support `fill` / `stroke` channel for fine-grain control.

**Comment by nielsmde** [comment]
I was missing an encoding channel for the line-style in vega-lite and came across this issue.
I would look into this and try to implement some of these new channels, if no one else is already on it.

Since I haven't contributed to vega-lite so far, I'm wondering if this is doable as a first-time contributor? It looks so for me, but I'm not so sure about the last point in the list above (refactor applyMarkConfig).

**Comment by kanitw** [comment]
@nielsmde Currently we are in the middle of migration to Vega 3, so this might not be the best time to do this yet.  

That said, if your use case is to create just one plot:
a) If you only want to change line style for all lines, you can use just [`config.mark.strokeDashOffset`](http://vega.github.io/vega-lite/docs/config.html#stroke-style)

b) If you want to map a field/variable to `strokeDashOffset`, you might consider to modify the vega output by (1) creating a scale for strokeDashOffset and (2) mapping a field to `strokeDashOffset` using the created scale.

**Comment by nielsmde** [comment]
All right then. Thanks for the tip, I will try that.

**Comment by kanitw** [comment]
To give an example, currently to change angle for text we have to use `config.text`

```
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "calculate": [{
      "as": "OriginInitial",
      "expr": "datum.Origin[0]"
    }]
  },
  "mark": "text",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal"},
    "text": {"field": "OriginInitial", "type": "nominal"}
  },
  "config": {
    "text": {"angle": 90}
  }
}
```

Ideally, we should just be able to do 

```
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "calculate": [{
      "as": "OriginInitial",
      "expr": "datum.Origin[0]"
    }]
  },
  "mark": "text",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal"},
    "text": {"field": "OriginInitial", "type": "nominal"},
    "angle": {"value": 90}   **   (or even map it to a field)
  }
}
```

**Comment by kanitw** [comment]
We no longer plan to do this, at least for now.
