### ISSUE TITLE
Revise how we specify selection predicate

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1281]
Right now it is 

```
{
   "if": selection_name
}
```

But we could support more general production rule too.
- [ ] We need to think ahead to see if we should support general production rule 
- [ ] if so, how would we design syntax such that we don't have to introduce breaking changes.

**Comment by arvind** [comment]
What is a "more general production rule"?

**Comment by kanitw** [comment]
Production rule that's not based on just selection.
Like mapping `color ` to  `{value: "red"}` if  `data.x > 5`  and `{value: "grey"}` otherwise.

**Comment by kanitw** [comment]
Subsumed by #1971
