### ISSUE TITLE
 Split properties() in mark-*.ts into multiple methods (e.g., x(), y(), shape())

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1284]
Each of these methods should take `fieldDef` and `scaleName` rather than the `model` as input since one channel might have multiple fieldDefs.

(forked from #1124, so we can assign to other people)

**Comment by kanitw** [comment]
@ayush29feb  This is the issue I talk about.  I suggest that you submit a separate PR for refactoring each mark type.

**Comment by ayush29feb** [comment]
@kanitw thanks for pointing it out. I will work on this on the weekend

**Comment by kanitw** [comment]
only have to this for `bar`

**Comment by kanitw** [comment]
@willium  We have done this for some mark types, but not all.   This is critical for moving forward to support interactions in 2.0.

Ideally, all output vega output properties should have their own methods so we can call them multiple times to produce production rules in Vega 2.

For the mark types we haven't done this, we can approach this issue in the follow steps:

- [ ] 1. write unit tests to have 100% coverage for existing code.  (You might discover some bugs along the way)
- [ ] 2. Refactor the methods.

Don't do 2. directly as you'll surely produce regression bugs.  (Ask @ayush29feb :p)

**Comment by willium** [comment]
Working on this @kanitw

**Comment by kanitw** [comment]
@willium  Any update on this?  If you're busy, I'll just do this on the flight to Baltimore on Saturday.

**Comment by kanitw** [comment]
Done in #1614
