### ISSUE TITLE
Allow specifying property to really be undefined in the output Vega spec

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1285]
When a config property is `undefined`, Vega-Lite automatically determines the default value for the property (sometimes the default value is `undefined` too but not always.)

However, for the case that the default value is not `undefined`, if the users want the output Vega specification to have that property as `undefined` (empty), we current do not have a way to support this.  

For example, we make `config.mark.fill` = `transparent` for point mark by default.  
This is probably a good default for tooltipping, but we also want to allow users to disable the transparency fill. 

A few options
a) introduce `"none"` or `"empty"` or some similar string literal
b) introduce `null` as a way to say "don't specify the property" while `undefined` remains "auto" by default.

I'm leaning toward b) because `null` could work with any type of properties (`boolean`, `number`, `string`) 
If we are doing b), we should revise existing `"none"` enum property for existing properties.

**Comment by kanitw** [comment]
For the record,  @domoritz and I kinda agree to 'null' approach in a slack conversation.

**Comment by kanitw** [comment]
Note: possibly relevant to  #1148

**Comment by kanitw** [comment]
@YuhanLu – I'm assigning to you, but let's chat when I'm back before you proceed with this :)

**Comment by kanitw** [comment]
@jakevdp  I wonder if choosing b) over a) would affect how Altair handle this case. 
Similarly, in #1384 we consider using `null` to disable axis and legend instead of using false. 
(So that axis and legend have single types in the schema (rather than Axis/boolean, Legend/boolean)

cc: @domoritz  @arvind

**Comment by jakevdp** [comment]
In Altair, I think we will continue to use "None" to mean "leave this entry out of the JSON specification". If explicit nulls are introduced in Vega-Lite, I think the best approach would be to introduce a singleton ``altair.null`` that can be used for this purpose.

**Comment by kanitw** [comment]
- [ ] Related question:  should `"bandSize": "fit"` simply become `"bandSize": null`.  In a way, it is equivalent to disabling bandSize.

**Comment by kanitw** [comment]
We mostly already check `value !== undefined`, which means the value is null, they will be included in the output.  This seems sufficient.
