### ISSUE TITLE
Support setting height for non-mapped axis. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1288]
```
{
  "data": {"values": [
  {
    "Sales": 35.8,
    "Day": 1,
    "Month": 1
  },
  {
    "Sales": 35.6,
    "Day": 2,
    "Month": 1
  },
  {
    "Sales": 36.5,
    "Day": 3,
    "Month": 1
  },
  {
    "Sales": 38.1,
    "Day": 4,
    "Month": 1
  },
  {
    "Sales": 39.8,
    "Day": 5,
    "Month": 1
  },
  {
    "Sales": 41.4,
    "Day": 6,
    "Month": 1
  },
  {
    "Sales": 42.4,
    "Day": 7,
    "Month": 1
  },
  {
    "Sales": 42.4,
    "Day": 8,
    "Month": 1
  },
  {
    "Sales": 41.9,
    "Day": 9,
    "Month": 1
  },
  {
    "Sales": 41.3,
    "Day": 10,
    "Month": 1
  }
]},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Day","type": "quantitative", "scale": {"nice": false}},
    "color": {"field": "Sales","type": "quantitative"}
  },
  "config": {
    "cell": {"width": 720},
    "mark": {"tickThickness": 2, "tickSize": 50}
  }
}
```

<img width="354" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/14334798/b437ad72-fc0b-11e5-8281-0afed25e00d3.png">

Setting `config.scale` to `{"bandSize": 50}` can solve the problem.  

<img width="359" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/14334917/5db14ed0-fc0c-11e5-982a-9c33df843c37.png">

but ideally we should support setting `height`.

Relevant to #194

**Comment by kanitw** [comment]
but ideally we should support setting `height`.

Relevant to #194

**Comment by kanitw** [comment]
It seems like this requires different name than normal `config.cell.height`.  

Maybe something like `config.cell.nonAxisWidth|Height`.  

@domoritz  any thoughts?

**Comment by kanitw** [comment]
Maybe the right solution is we never set `config.cell.width|height` by default

- `config.cell.axisWidth|Height` = size of continuous scale (and ordinal scale if `bandSize` = `"fit")
- `config.cell.nonAxisWidth|Height`  (`config.scale.bandSize` by default)

whenever `config.cell.width|height` is specified, it overrides both of these two?  

(Otherwise, it's confusing why `config.cell.width|height` only applies when the axis has a value mapped.)

**Comment by domoritz** [comment]
The suggestion makes sense. But can we just not have `config.cell.nonAxisWidth|Height` and instead always use `config.scale.bandSize`?

**Comment by kanitw** [comment]
I could go either way.  On one hand, less property is better.  On the other hand, the preferred `nonAxisWidth` for a theme isn't necessarily always `config.scale.bandSize`.

**Comment by kanitw** [comment]
With the top-level "width" and "height", now this can be set!

```
{
  "height": 50,
  "data": {"values": [
  {
    "Sales": 35.8,
    "Day": 1,
    "Month": 1
  },
  {
    "Sales": 35.6,
    "Day": 2,
    "Month": 1
  },
  {
    "Sales": 36.5,
    "Day": 3,
    "Month": 1
  },
  {
    "Sales": 38.1,
    "Day": 4,
    "Month": 1
  },
  {
    "Sales": 39.8,
    "Day": 5,
    "Month": 1
  },
  {
    "Sales": 41.4,
    "Day": 6,
    "Month": 1
  },
  {
    "Sales": 42.4,
    "Day": 7,
    "Month": 1
  },
  {
    "Sales": 42.4,
    "Day": 8,
    "Month": 1
  },
  {
    "Sales": 41.9,
    "Day": 9,
    "Month": 1
  },
  {
    "Sales": 41.3,
    "Day": 10,
    "Month": 1
  }
]},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Day","type": "quantitative", "scale": {"nice": false}},
    "color": {"field": "Sales","type": "quantitative"}
  },
  "config": {
    "cell": {"width": 720},
    "mark": {"tickThickness": 2, "tickSize": 50}
  }
}
```

However, looks like the default offset is still slightly off.  

![vega_editor](https://cloud.githubusercontent.com/assets/111269/17761489/6344976c-64bc-11e6-8fcc-1ad7068809bc.png)

**Comment by kanitw** [comment]
#1554 is a special case of this.
