### ISSUE TITLE
Integrate Vega-Lite as a custom visual in Power BI

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1289]
https://powerbi.microsoft.com/en-us/custom-visuals/

**Comment by kanitw** [comment]
This sounds like a nice idea for external project, but not necessarily a VL issue.

**Comment by domoritz** [comment]
Where is a place for ideas like this? Wiki, website, issues?

**Comment by kanitw** [comment]
Currently, our [contribution guide](https://github.com/vega/vega-lite/blob/master/CONTRIBUTING.md#looking-for-a-task-to-contribute) points to this doc:
https://docs.google.com/document/d/1u1T9HOTXABqusSX-n6aM8FSsXdhTnrdlaZ-pzNInNik/edit

But we should organize a section for external project ideas that aren't necessary Vega-Lite issues.

**Comment by danyelf** [comment]
To follow up a little: @domoritz got this into the official Microsoft repository on this, https://github.com/Microsoft/vegalite-for-powerbi
