### ISSUE TITLE
JSON filename is too long to perform an checkout

### ISSUE THREAD

**Issue by nahshaviki** [vega/vega-lite#1303]
Error from the console:
> 

bower vega-lite#^0.7.11               not-cached https://github.com/uwdata/vega-lite.git#^0.7.11
bower vega-lite#^0.7.11                  resolve https://github.com/uwdata/vega-lite.git#^0.7.11
bower vega-lite#^0.7.11                 checkout v0.7.18
bower vega-lite#^0.7.11                  ECMDERR Failed to execute "git clone https://github.com/uwdata/vega-lite.git -b v0.7.18 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects
Resolving deltas: 100% (6/6), done. remote: Total 149 (delta 6), reused 77 (delta 4), pack-reused 0         Checking connectivity... done. Note: checking out '6defff5c3014b43cc1de3bf9f1719db768ec2a4b'.  You are in 'd
etached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want
to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  error: unable to create file bin/shorthand
2vg/birdstrikes.bar.x-sum_Cost__Total_$-Q.y-Effect__Amount_of_damage-O.row-When__Phase_of_flight-O.col-When__Time_of_day-O.color-Wildlife__Size-O.json (Filename too long) fatal: unable to checkout working tree warnin
g: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 149, done.
remote: Compressing objects: 100% (142/142), done.
Receiving objects: 100% (149/149), 1.76 MiB | 982.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
remote: Total 149 (delta 6), reused 77 (delta 4), pack-reused 0
Checking connectivity... done.
Note: checking out '6defff5c3014b43cc1de3bf9f1719db768ec2a4b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: unable to create file bin/shorthand2vg/birdstrikes.bar.x-sum_Cost__Total_$-Q.y-Effect__Amount_of_damage-O.row-When__Phase_of_flight-O.col-When__Time_of_day-O.color-Wildlife__Size-O.json (Filename too long)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by domoritz** [comment]
What command are you executing? What system are you using? Can you upgrade to vega-Lite 1.0 and see whether you get the same error? 

I just tried `bower install vega-lite` and it worked fine.
