### ISSUE TITLE
Font configuration options for axis, legend, and spec

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1307]
In addition to `MarkConfig`'s `font` and `fontSize` options, `AxisConfig` and `LegendConfig` should have these properties. In addition, they should fall back to spec-global `font` and `fontSize` options, which would allow a user to specify a single font to be used for the entire visualization.

**Comment by kanitw** [comment]
Thanks for reporting. We're actually addressing these in the pending PR #1290 and #1302.
