### ISSUE TITLE
Show warning when users aggregate time by month

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1321]
According to Zan Armstrong's talk at OpenVis, aggregating by month might not be so meaningful.

**Comment by domoritz** [comment]
Can you elaborate?

**Comment by domoritz** [comment]
Because months don't have the same number of days or they don't line up with weeks? Not that relevant for example for the weather data and if you use mean.

**Comment by kanitw** [comment]
https://twitter.com/eagereyes/status/724693321344516096

**Comment by domoritz** [comment]
I just argued that that doesn't apply to anything that is not man made since the weather for example doesn't care about weekdays.

**Comment by zanarmstrong** [comment]
FWIW this can actually apply to something that seems as impossibly robust to human intervention as seismic readings. To be sensitive enough to capture relevant seismic information, the sensing instruments will also pick up on vibrations from highway traffic... which of course has strong day-of-week and hour-of-day patterns.

And, as I showed in my Scientific American article and OpenVisConf talk, something as "natural" as birth is also highly dependent on day-of-week x hour-of-day. 

For weather, perhaps the mean temperature is not going to have a day-of-week cycle. But, something like ppm for pollution likely does, at least as it relates to road traffic or construction. 

All in all, finding information that humans care about which is truly unaffected by humans hourly/daily patterns is... difficult.
