### ISSUE TITLE
Maps - Geo lookup Plugin

### ISSUE THREAD

**Issue by bobocandys** [vega/vega-lite#1323]
Depends on: #1322 

Implement
- [ ] Generic geo lookup(From name to geolocation),  transform for vl

Data source
- [ ] U.S. States
- [ ] zip codes
- [ ] Countries
- [ ] Cities 
- [ ] Airports

**Comment by rubik** [comment]
The link is outdated. This now depends on https://github.com/vega/vega-lite/issues/1454 I belive?

**Comment by kanitw** [comment]
@willium  -- looks like our lookup already support this so we can close this?

**Comment by willium** [comment]
we don't support "Generic geo lookup(From name to geolocation)" but I believe we also don't plan to.
