### ISSUE TITLE
Maps - Milestone 1.5: Geo marks

### ISSUE THREAD

**Issue by bobocandys** [vega/vega-lite#1326]
Depends on: #1322 

Support geo marks:
- [x] point
- [ ] line: an arbitrary line/path composed of a set of points.
- [ ] polygon: a closed line/path that is fillable.

**Comment by kanitw** [comment]
what's line? here  I guess it's not a typical line, but rather an arbitrary path?

**Comment by bobocandys** [comment]
In my understanding, it refers to a straight line because a polygon can be drawn by drawing some arbitrary paths. 
@domoritz What do you think?

**Comment by domoritz** [comment]
A path/line is an arbitrary line defined by a set of points. A polygon is a closed line/path, which can be filled.

**Comment by kanitw** [comment]
Let's close this so we can put all instruction in #1322
