### ISSUE TITLE
useRawDomain should be pre-filter?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1327]
Should `filter` affect the raw data domain? Right now, if I set both `transform.filter` and `config.scale.includeRawDomain` in a Vega-lite spec, I get the filtered data domain instead of the raw data domain.

For example, if I filter out `Europe` and set `includeRawDomain` to `true`, I no longer have `Europe` in my legend. This suggests that the `color` scale has the filtered data domain instead of the raw data domain.

![filter_rawdomain](https://cloud.githubusercontent.com/assets/822034/14908927/74152a10-0d92-11e6-8f3d-4deff2b275d3.png)

Similarly, filtering on `Horsepower` and setting `includeRawDomain` to `true` also gives me the filtered data domain.
![filter_x](https://cloud.githubusercontent.com/assets/822034/14908919/65328fec-0d92-11e6-9acf-694e7aced16c.png)

**Can we make the raw domain pre-filter** so that we can always get the raw domain when `includeRawDomain` is `true`?

**Comment by ZeningQu** [comment]
Here's a scenario where I want to use the raw domain. When I have multiple visualizations of the same data set on the same screen (e.g. in narrative visualizations, in visualization recommender systems), I want the color mappings to be consistent across visualizations. Therefore I always want to set the `domain` of the color scale to `raw`.

![consistent_colors](https://cloud.githubusercontent.com/assets/822034/14909076/1ad88562-0d94-11e6-992c-5101bad273f6.png)

**Comment by ZeningQu** [comment]
@domoritz will this be easy or hard to do?

**Comment by kanitw** [comment]
The right question is how would this affect the transform order we discussed earlier

**Comment by domoritz** [comment]
So you want it to be pre-filter and also pre selection filter? I'm not sure
whether we are putting too much configurability into Vega-Lite with this.

**Comment by kanitw** [comment]
> I'm not surewhether we are putting too much configurability into Vega-Lite with this.

Well, it's not extra level of configurabililty.  This discuss doesn't add new config, but rather discuss how existing config should behave.

**Comment by domoritz** [comment]
> Well, it's not extra level of configurabililty. This discuss doesn't add new config, but rather discuss how existing config should behave.

My comment was regarding the option to change the behavior of inlcudeRawDomain. 

Concerning the default. I don't think there is a clear preference for either behavior.

**Comment by kanitw** [comment]
Trying the new quick filter UI and I feel very strongly that useRawDomain should be pre-filter.  
(Otherwise we're moving quick filter and scale domain changes!)

**Comment by kanitw** [comment]
- [ ]  Once we implement this ,we need to remove the condition that apply apply this to aggregate table.  

```
// only applied to aggregate table
    fieldDef.aggregate &&
```

**Comment by kanitw** [comment]
Hmm Tableau is actually NOT doing this, so I'm not sure about this anymore.

**Comment by kanitw** [comment]
I think we can just explain in the docs that this is only applied after filter and close this issue?

**Comment by g3o2** [comment]
If something is named `raw` then it should also be raw. Otherwise `includeFilteredDomain` would be an acceptable name.

**Comment by kanitw** [comment]
Closing in favor of #1656
