### ISSUE TITLE
Text in legend?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1328]
Right now, the `text` encoding doesn't get into legend. I think this is fine when there is double-encoding:

![text_color](https://cloud.githubusercontent.com/assets/822034/14909172/34890706-0d95-11e6-9c41-d54ac2acc188.png)

Here, `color` appears in legend and we can infer from the color mappings that 'E' stands for 'Europe' and 'J' stands for 'Japan' -- text is kind of self-explanatory.

However, if I remove the `color` channel, the above visualization becomes something like this:
![just_text](https://cloud.githubusercontent.com/assets/822034/14909228/d87f7728-0d95-11e6-8ec7-323a0d80f059.png)

Without legend it becomes very hard to tell what 'E', 'J' and 'U' each stands for.

**Comment by kanitw** [comment]
This is such as rare case.  If you look at the spec, users manually trim the first letter from the full string.  Plus, this isn't even pass through scale.  Users can use concat and manually make legend.
