### ISSUE TITLE
Rename `includeRawDomain` to `useRawDomain` and set default to `true`

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1330]
Because we want to see consistent scale domains across visualizations. Defaulting `useRawDomain` to `true` will give us more consistent scale domains when there is data aggregation.

**Comment by kanitw** [comment]
Changing it to `true` will change existing behavior.  So be cautious about it. 

@domoritz What do you think?

**Comment by domoritz** [comment]
I agree that it should be closed.
