### ISSUE TITLE
Publish on bower.io

### ISSUE THREAD

**Issue by aranm** [vega/vega-lite#1335]
Please:
- Avoid creating duplicate issues (Check  with https://github.com/vega/vega-lite/issues).
- Make clear and descriptive title
- Describe how to reproduce the bug /  the goal of the new feature request
- If applicable, provide an example spec that causes the bug / example spec draft for the feature + screenshots/animated GIFs (Try skitch.com for annotating screenshot)
- Describe why current behavior is incorrect  / why the feature is needed + expected behavior (ideally a Vega specification or a part of it)

**Comment by aranm** [comment]
When searching either:

http://bower.io/search/?q=vegalite

or

http://bower.io/search/?q=vega-lite

The search returns no results. There was another issue that is marked as closed that looks related but is not.

https://github.com/vega/vega-lite/issues/421

This library should be published to bower.io

**Comment by domoritz** [comment]
We have definitely registered the package as `vega-lite` and actually use it in voyager and polestar. 

Also, `bower install vega-lite` works and registering it again does not work

<img width="814" alt="screen shot 2016-05-03 at 10 51 28" src="https://cloud.githubusercontent.com/assets/589034/14987239/279b1d78-111d-11e6-8499-1f2085f58e3a.png">

I'm sure it's a bower issue.

**Comment by aranm** [comment]
Fair enough, is there any reason that using the command "bower install vega-lite" installs all of the examples as well into your project and not just the core src files (or maybe I'm missing the point somehow?)

**Comment by domoritz** [comment]
Bower simply pulls from git. If you want a cleaner package with only the code, use npm.

**Comment by QuantumInformation** [comment]
Bower is out of date

**Comment by domoritz** [comment]
@QuantumInformation Bower doesn't have the prereleases. I'm getting the latest stable version `1.3.1`.
