### ISSUE TITLE
Add version to ``vegalite-json-schema.json``

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1338]
As we're working on adapting the schema for the [Altair](https://github.com/ellisonbg/altair) project, we noticed that the vega-lite schema doesn't record any version. Would it make sense to add that?

**Comment by domoritz** [comment]
Yes, definitely. We are automatically adding versions to our code with https://www.npmjs.com/package/browserify-versionify but adding the version to the schema file makes sense.

**Comment by rgbkrk** [comment]
It would be great to also know which versions of vega-lite (the package) match which version of the schema. If they're tighly aligned, that's ok to know too.

**Comment by jakevdp** [comment]
> It would be great to also know which versions of vega-lite (the package) match which version of the schema. If they're tighly aligned, that's ok to know too.

I think this could be best done with a documented and well-defined policy for what is implied by version numbers, as I mentioned recently on the slack channel.

**Comment by kanitw** [comment]
I think we can just use MAJOR.MINOR version number as schema version?  (Assuming the patch doesn't change schema.)

**Comment by jakevdp** [comment]
Sure, but I'd add there should be a field in the schema so the spec can record that version, and the major/minor should have well-defined meaning with regards to backward compatibility.

**Comment by domoritz** [comment]
We discussed this offline and decided on the following (@kanitw correct me if I'm wrong)

* We will include the schema in the repo to track changes.
* The version of the schema is the version of the package it comes with.
* We use semantic versioning. Patches don't change external behavior. Minor versions may add features (the schema can change as long as it is still valid JSON schema). Major versions may break backward compatibility.

**Comment by domoritz** [comment]
We might add a link to the right schema to vega and veg-lite versions in the near future. Along with it, we will also have a repository of vega and vega-lite schemas. See https://github.com/vega/vega-lite/issues/1661.

I think we can close this issue.
