### ISSUE TITLE
Make "auto" more explicit

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1341]
Right now we use `undefined` as an implicit value for auto. We should consider changing that to `auto` for the next version. I believe this causes less confusion and better interoperability with other languages.

**Comment by kanitw** [comment]
I don't think this is a good idea.   In JSON, when you don't defined a property, it's equal to `undefined`. That's why it implicitly means "auto".   For example:

```js
var o = {a: 1}
o.b === undefined; // this is true
```

Introducing explicit "auto" property for non-string property also complicates the schema.

**Comment by domoritz** [comment]
We could still have `"auto"` as the default value in the config. It would make things a bit more explicit and actually allow you to override the default in the config to be auto if it is not already the default.

For example, if `config.foo = "bar"` by default but the property `foo` supports auto. With auto, you could set `config.foo = "auto"` but with `undefined` as auto, you have to write `config.foo = undefined`, which is equal to not defining it at all.

**Comment by domoritz** [comment]
Actually this issue led to confusion such as https://github.com/vega/vega-lite/issues/1285

**Comment by kanitw** [comment]
> you have to write config.foo = undefined, which is equal to not defining it at all.

But you can't distinguish between when a property is not defined and when it is explicitly `undefined`.  That's why your proposal doesn't make sense anyway.

**Comment by domoritz** [comment]
> But you can't distinguish between when a property is not defined and when it is explicitly undefined. That's why your proposal doesn't make sense anyway.

Didn't I say exactly the same thing?

I forgot to say that in JSON, `undefined` does not exist. My main point being that in JSON, you cannot override something that does not default to auto with auto if we use `undefined` to encode auto.

**Comment by kanitw** [comment]
I mean your original proposal.  Whatever, I'm happy that this issue is closed.

**Comment by domoritz** [comment]
I'm a bit confused. Especially since the clean solution for #1285 seems to be this issue.

**Comment by kanitw** [comment]
#1285 is related.  But I don't think the proposal here is the clean solution for #1285.  

Good default should be implicit and a property should only have "auto" if "auto" provides good default.
Thus "auto" should be implicit.

**Comment by domoritz** [comment]
Totally agree. I was only talking about how we specify auto in the config. the user should not see this until they want to make something auto that has not auto as the default.

**Comment by kanitw** [comment]
> the user should not see this until they want to make something auto that has not auto as the default.

If there is such a case, that makes sense.  But I would strongly say that we should not have such case because if auto isn't good enough to be a default, why the heck should we implement the auto :)

**Comment by domoritz** [comment]
That's an excellent point. In that case the only thing that changes is that the code would be easier/safer because there is an explicit value for "auto". User's would never see it.

**Comment by domoritz** [comment]
So reopen and consider?

**Comment by kanitw** [comment]
nope. My whole point is explicit auto is useless.

**Comment by kanitw** [comment]
I don't think it is necessary, we have too many other important things to do.   This would require us to complicates the schema without real gain.  People might compare schema code and docs and wonder why we have to add weird `string` type to many properties.
