### ISSUE TITLE
Legend should support opacity 

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#1349]
Legend should support the new channel opacity. Now the spec cannot generate a output with desired legend.

```
{
  "data": {"url": "data/seattle-weather.csv", "formatType": "csv"},
  "mark": "bar",
  "config": {
    "mark": { "opacity": 0.5 }
  },
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "timeUnit": "month"
    },
    "y": {
      "field": "*",
      "type": "quantitative",
      "aggregate": "count"
    },
    "opacity": {
      "field": "*",
      "type": "quantitative",
      "aggregate": "count"
    }
  }
}
```
![vega 1](https://cloud.githubusercontent.com/assets/11696585/15170129/d3791f48-16f7-11e6-946b-a5ca7e508fa7.png)

**Comment by kanitw** [comment]
@YuhanLu  Have you file an issue in Vega as well?  If not please do so and link to this issue :)

**Comment by YuhanLu** [comment]
Just did it.

**Comment by kanitw** [comment]
Given that https://github.com/vega/vega/issues/570 is fixed, we will get this for free whenever Vega release new update.

**Comment by kanitw** [comment]
Actually we still need to add some code to legend.ts
