### ISSUE TITLE
Tick for dotplot with timeUnit gets wrong orientation 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1354]
```
{
  "data": {
    "url": "https://vega.github.io/vega-lite/data/seattle-weather.csv",
    "formatType": "csv"
  },
  "mark": "tick",
  "encoding": {
    "x": {
      "timeUnit": "year",
      "field": "date",
      "type": "temporal"
    }
  }
}
```

<img width="219" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/15338182/98006fc0-1c33-11e6-9d9b-6674761b3514.png">

**Comment by domoritz** [comment]
@YuhanLu You are our tick expert. Can you look into this?

**Comment by kanitw** [comment]
Actually, this is already fixed in the latest master as well.  We just need to deploy it.
