### ISSUE TITLE
Clarify how to resize a visualization / customize

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1356]
[This page](http://vega.github.io/vega-lite/docs/size.html) is so hard to read.

Plus, there should be another tutorial that focus on customizing Vega-Lite plot for presentation

**Comment by peller** [comment]
@kanitw I've been scratching my head over this for the last few days and stumbled on this issue.  Looking for a way to set the height/width of a single plot, like spec.width/spec.height on vega.  Does it exist?

**Comment by kanitw** [comment]
@peller Currently you have to rely on `config.cell.width` and `config.cell.height` if quantitative scales on x and y axis respectively.   For ordinal scale, currently you have to adjust `bandWidth` to adjust the size of the visualization.  

We plan to add support fitting ordinal scale to a fix width/height (#194)
and top-level `width` and `height` (#1421) in the new few weeks.

**Comment by peller** [comment]
thanks, @kanitw!  config.cell was not working for me for a single plot.  Will wait for #1421.   Will top level width/height settings include padding and label areas as well?  Would be great if the width/height accessors on the view object could also be used.

**Comment by kanitw** [comment]
Can you provide an example spec where `config.cell` is not working?   That seems important for us to fix too.  Thank you!

**Comment by peller** [comment]
Taking a closer look, it appears to be user error.  There was an ordinal scale involved, also no accounting for padding/labels, so not useful to me regardless.

**Comment by kanitw** [comment]
Done in #1214, pending final docs revision.
