### ISSUE TITLE
Should we move "edit this page" link to top of the page?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1359]
Putting it at the end is kinda useless.

**Comment by domoritz** [comment]
Top right on each page maybe? 

@willium what do you think?

**Comment by willium** [comment]
I prefer it at the bottom, but am open to the idea. It's a little crowded at top.

**Comment by kanitw** [comment]
I think top right of a page's content (not part of the menu) makes sense.

**Comment by willium** [comment]
Cool. Works for me

**Comment by willium** [comment]
I implemented this here: https://github.com/vega/vega-lite/tree/will/docs/edit-page
It'd be great if you could run it and try it out. On second thought, stylistically, I'm not sure I like this.

Reasoning:
- It's not clear where to put it (especially on the homepage, and smaller screens (though I suppose it could be hidden on smaller screens)
- 99% of readers don't/won't/shouldn't edit pages, and it's given a lot of prominence
- it doesn't make good use of space (especially on homepage)
- people generally look for this link in the footer (citation needed)

Why is putting it at the end useless? Have people had trouble finding it?
