### ISSUE TITLE
Can't use log scale with bar?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1368]
For example, we can't add `scale: {type: "log"}` to the `histogram` example.  
```
{
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"maxbins": 10},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative",
      "scale": {"type": "log"}
    }
  }
}
```

**Comment by kanitw** [comment]
The culprit is that we for `bar`, we output

`"y2": {"scale": "y","value": 0}`

So we should avoid  passing 0 through log scale) by default for `bar` / `area`.
The solution is probably don't include `scale` if the scale type is log by default.  

@ayush29feb  since you have to modify `mark.properties`, could you take care of this too?  This should not take too much time to fix.

**Comment by jheer** [comment]
This is worth fixing. But for the examples, I recommend not using bar
charts over a log-scaled domain. A dot plot would be a better example of
what to do!

**Comment by kanitw** [comment]
>  But for the examples, I recommend not using bar charts over a log-scaled domain. A dot plot would be a better example of what to do!

Yep.  We definitely wouldn't include this in the example gallery. 


More note for @ayush29feb, if we don't pass this through the scale, the correct value might not always be 0.  For example,  y-axis's value should be the height.

**Comment by domoritz** [comment]
@kanitw makes sense. Points work. 

<img width="269" alt="screen shot 2016-05-18 at 15 33 20" src="https://cloud.githubusercontent.com/assets/589034/15377073/e79971e6-1d0d-11e6-9ee8-859e655fac98.png">

**Comment by ayush29feb** [comment]
Yeah I can take care of it while working on #1284 over the weekend

**Comment by domoritz** [comment]
Thanks

**Comment by domoritz** [comment]
@kanitw How should @ayush29feb get the height of the visualization/ cell? He needs to get it from the layout because the `cellHeight` may not be the actual height for instance with layering.

**Comment by kanitw** [comment]
If you have layering that two layers do not have the same `cellHeight`, both layer should have their own `cellHeight`  (with the correct prefix) so I don't see why that is an issue.

**Comment by domoritz** [comment]
The cell height will only be available from the layout data source, though.

**Comment by kanitw** [comment]
> The cell height will only be available from the layout data source, though.

If you have two layer that do not have the same layout, there should be more than one layout data sources.

**Comment by domoritz** [comment]
My question is how we access the layout from the mark properties?

**Comment by kanitw** [comment]
> My question is how we access the layout from the mark properties?

Good question.   I was wrong about this sentence.  (My memory starts coming back.)

> If you have two layers that do not have the same layout, there should be more than one layout data sources.

The correct one is "there should be more than one `*-cellHeight` fields in the layout data source.

**Comment by domoritz** [comment]
> The correct one is "there should be more than one *-cellHeight fields in the layout data source.

This is not the issue. The issue is only how to access the layout data source.

**Comment by kanitw** [comment]
Actually, just like `rule`, you can use `{group: 'width'}` (or `height`)?

**Comment by ayush29feb** [comment]
Yeah @domoritz, I think you actually can do that.

**Comment by domoritz** [comment]
I see. So we don't need access to the layout data source. Perfect.

**Comment by kanitw** [comment]
Another case -- I think we have the same problem if `scale.zero = false`  :)
