### ISSUE TITLE
Can't change temporal with timeUnit to use categorical color scale.  

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1369]
We would like to use different hues for different years. 

```js
{
  "data": {"url": "data/seattle-weather.csv","formatType": "csv"},
  "transform": {
    "calculate": [
      {
        "field": "temp_range",
        "expr": "datum.temp_max - datum.temp_min"
      }
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"timeUnit": "month","field": "date","type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "temp_range",
      "type": "quantitative"
    },
    "color": {"timeUnit": "year","field": "date","type": "t"}
  }
}
```

**Comment by kanitw** [comment]
@domoritz  Actually we can do

```
{
  "data": {"url": "data/seattle-weather.csv","formatType": "csv"},
  "transform": {
    "calculate": [
      {
        "field": "temp_range",
        "expr": "datum.temp_max - datum.temp_min"
      }
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"timeUnit": "month","field": "date","type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "temp_range",
      "type": "quantitative"
    },
    "color": {
      "timeUnit": "year","field": "date","type": "t",
      "scale": {
        "type": "ordinal",
        "range": "category10"
      }
    }
  }
}
```

The question is why does `month` output a `time` scale by default?

**Comment by kanitw** [comment]
Looking at the code, I think this makes sense because ordinal scale doesn't support color ramp.  
This is quite unfortunate, but we can't really fix this unless Vega reshuffle scale type taxonomy.

**Comment by domoritz** [comment]
@ctb Not sure who asked but categorical color scales work (by specifying the color range) for temporal data.

<img width="398" alt="screen shot 2016-05-18 at 15 24 56" src="https://cloud.githubusercontent.com/assets/589034/15376892/c11b777c-1d0c-11e6-948b-caf9dd22d05a.png">

**Comment by domoritz** [comment]
@kanitw I think this is a good example where the data type should specify the output, not the input.

**Comment by kanitw** [comment]
I agree.  

At the same time, the fact that Vega's ordinal scale only supports categorical color (but not ordinal color ramp confuses me a lot).  

Thinking more about it, should we leave this open and think about how we can correct fix vega?
