### ISSUE TITLE
Proposal for renaming the definitions (classes) in the JSON spec

### ISSUE THREAD

**Issue by ellisonbg** [vega/vega-lite#1377]
Please:
- [X] Check for duplicate issues
- [X] Describe how to reproduce the bug /  the goal of the new feature request
- [X] Provide an example spec and/or screenshots (if applicable) 

In altair, we are autogenerating our Python API from the JSON spec. In that process, the defs in the JSON spec end up becoming the names of Python classes. It would be great if we could standardize on the names of those classes. In altair we have renamed some of them to be more internally consistent and be more user friendly. Here are the aliases we have created:

```
AxisProperties->Axis
BinProperties->Bin
LegendProperties->Legend
VgFormula->Formula
Top-level object->Layer
```

The first three of these were done because other peer attributes (`Scale`, etc.) didn't have the `Properties` suffix.

In addition to this we have defined top-level classes for the main channel types, such as `X`, `Y`, etc. that are subclasses of the appropriate underlying channel class.

**Comment by kanitw** [comment]
1) For `VgFormula`, we actually already renamed it to `Formula`, so please removing the alias should still work. 

2) I will do the rename like you suggest for `Axis` / `Bin` / `Legend`.  

FYI, currently they are named like this because they can accept `boolean` value as well.  
   - For `bin`, `bin: true` means using enable the bin with default parameters.  We considered `bin: {}` for enabling `bin`. (Practically `Bin = boolean | BinProperties`.)  
   - `axis/legend: true` is kind of useless.  We only add boolean so that people can do `axis: false` to hide axis (same for legend).  
       - That said, I think we should remove the support for `axis: false` and just support `axis: null` and simplify the schema.   (@domoritz -- what do you think about this part?) 
   - We did not support disabling scale (that's why scale doesn't have the same feature).  However, from a user request, we now realize that there is a use case for it (#1340)

3) Top-level Object as a `Layer` doesn't make sense for us.  It is a `UnitSpec` that can be combined with a layer operator (and thus produces a [`LayerSpec`](https://github.com/vega/vega-lite/blob/master/src/spec.ts#L53)), or a concat operator (which produces a [`ConcatSpec`](https://github.com/vega/vega-lite/blob/repeat3Selections3/src/spec.ts#L79)) or modified with facet and repeat operator.  

Note that `ConcatSpec` is still not in master.   I guess you might want to ask us rename `UnitSpec` to `Unit` but I prefer not to do so because it will cause variable name mismatch in our codebase.  

Plus, for Atlair, IMHO a sensible alias might be `View` (or `Chart` / `Visualize` -- but I like View better).       

Thus, the syntax could for layered view become 
```
Layer(
   View(data1).encode(...),
   View(data1).encode(...) 
)
```

So you might still want to have code for creating top-level alias.

**Comment by ellisonbg** [comment]
On Thu, May 19, 2016 at 5:14 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> 1) For VgFormula, we actually already renamed it to Formula, so please
> removing the alias should still work.
>

Great!


> 2) I will do the rename like you suggest for Axis / Bin / Legend.
>
> FYI, currently they are named like this because they can accept boolean
> value as well.
>
>    - For bin, bin: true means using enable the bin with default
>    parameters. We considered bin: {} for enabling bin. (Practically Bin =
>    boolean | BinProperties.)
>    - axis/legend: true is kind of useless. We only add boolean so that
>    people can do axis: false to hide axis (same for legend).
>    - That said, I think we should remove the support for axis: false and
>       just support axis: null and simplify the schema. (@domoritz
>       <https://github.com/domoritz> -- what do you think about this
>       part?)
>    - We did not support disabling scale (that's why scale doesn't have
>    the same feature). However, from a user request, we now realize that there
>    is a use case for it (#1340
>    <https://github.com/vega/vega-lite/issues/1340>)
>
> Also great!


> 3) Top-level Object as a Layer doesn't make sense for us. It is a UnitSpec
> that can be combined with a layer operator (and thus produces a LayerSpec
> <https://github.com/vega/vega-lite/blob/master/src/spec.ts#L53>), or a
> concat operator (which produces a ConcatSpec
> <https://github.com/vega/vega-lite/blob/repeat3Selections3/src/spec.ts#L79>)
> or modified with facet and repeat operator.
>
> Note that ConcatSpec is still not in master. I guess you might want to
> ask us rename UnitSpec to Unit but I prefer not to do so because it will
> cause variable name mismatch in our codebase.
>
> Plus, for Atlair, IMHO a sensible alias might be View (or Chart /
> Visualize -- but I like View better).
>
> Thus, the syntax could for layered view become
>
> Layer(
>    View(data1).encode(...),
>    View(data1).encode(...)
> )
>
> So you might still want to have code for creating top-level alias.
>

When we talked with @jheer, we were thinking about using the `+` operator
for the layering API so it would look something like this:

`Layer(data1).encode(...)+Layer(data1).encode(...)`

If that is renamed `Unit` it would be:

`Unit(data1).encode(...)+Unit(data1).encode(...)`

Question: Will there be options to the `LayerSpec` and `ConcatSpec` in
addition to the raw Units? If so, we may want to have a set of functions
such as `layer` and `concat` for composing the units.

Some thoughts:

* Maybe `LayersSpec` rather than `LayerSpec` as that type of spec contains
multiple layers, not just one?
* In the Python API, I don't think we would use names that have `Spec` on
them as it is too verbose and suggestive of low-level details that don't
matter to those users - at least for classes they instantiate.
* The name `Unit` is pretty descriptive of the role it plays in layers and
concat, but it is going to be more difficult to explain to users what that
means. Would love to get @jheer 's thoughts on that versus Layer.
* I think the names of the composite objects (`LayerSpec` and `ConcatSpec`)
matter much less as users probably won't instantiate those classes
themselves but instead using helper functions.

Question: it make make sense for us to run the autogenerator over the
layering and concat spec. Is that in a branch where we could start to play?


> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/1377#issuecomment-220486015>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
@ellisonbg  Quick question, don't you have to make an alias for `AggregateOp` (as `Aggregate`)  as well? 

I'm happy to change it if you think it's a good idea. 

(For your questions the previous comment, I have a reply drafted in another computer and will get back to you later today)

**Comment by ellisonbg** [comment]
This one is less important as in our code base AggregateOp is just an enum,
so the actual type a user works with is a string. But fine if you do rename
it.

On Fri, May 20, 2016 at 3:32 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> Quick question, don't you have
> to make an alias for AggregateOp (as Aggregate) as well?
>
> I'm happy to change it if you think it's a good idea.
>
> (For your questions the previous comment, I have a reply drafted in
> another computer and will get back to you later today)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/1377#issuecomment-220734011>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
Thank you.  

 > The name `Unit` is pretty descriptive of the role it plays in layers and concat, but it is going to be more difficult to explain to users what that means. Would love to get @jheer 's thoughts on that versus Layer.

I agree that `Unit` doesn't make sense in Altair context, that's why I think `View` makes more sense. (It's a spec of a unit view, that's why we call it `UnitSpec` in the code.) 

And I think `View` is better than `Layer()`.  `HConcat(View(), View())`  is better than `HConcat(Layer(), Layer())`.   

To follow ggplot, we could have `+` as shorthand for `Layer(View(), View())`.

> Maybe `LayersSpec` rather than `LayerSpec` as that type of spec contains
multiple layers, not just one?

> Question: Will there be options to the `LayerSpec` and `ConcatSpec` in
addition to the raw Units? If so, we may want to have a set of functions
such as `layer` and `concat` for composing the units.

Right now all composite specs take the form `VerbSpec` (`FacetSpec` / `LayerSpec` / `RepeatSpec` / `H/VConcatSpec`).  Here, we treat layer as verb.  

There will be `FacetSpec` and `RepeatSpec` too.   

See this branch https://github.com/vega/vega-lite/tree/composition-interaction-prototype.

Note this branch is not 100% finalized.  Things are still subject to minor changes, but probably get you an idea what we'll be able to do.

**Comment by ellisonbg** [comment]
I will read through your comments more in a bit.

Question:

@domoritz and @kanitw would it make sense to create a branch of ipyvega called `composition-interaction-prototype` that follows the vega-lite branch so we can have a full vega-lite, ipyvega, altair toolchain for testing these things out?

**Comment by ellisonbg** [comment]
I tried to build the spec for this branch and ran into problems...opened an
issue here:

https://github.com/vega/vega-lite/issues/1380

On Fri, May 20, 2016 at 7:11 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> Thank you.
>
> The name Unit is pretty descriptive of the role it plays in layers and
> concat, but it is going to be more difficult to explain to users what that
> means. Would love to get @jheer <https://github.com/jheer> 's thoughts on
> that versus Layer.
>
> I agree that Unit doesn't make sense in Altair context, that's why I
> think View makes more sense. (It's a spec of a unit view, that's why we
> call it UnitSpec in the code.)
>
> And I think View is better than Layer(). HConcat(View(), View()) is
> better than HConcat(Layer(), Layer()).
>
> To follow ggplot, we could have + as shorthand for Layer(View(), View()).
>
> Maybe LayersSpec rather than LayerSpec as that type of spec contains
> multiple layers, not just one?
>
> Question: Will there be options to the LayerSpec and ConcatSpec in
> addition to the raw Units? If so, we may want to have a set of functions
> such as layer and concat for composing the units.
>
> Right now all composite specs take the form VerbSpec (FacetSpec /
> LayerSpec / RepeatSpec / H/VConcatSpec). Here, we treat layer as verb.
>
> There will be FacetSpec and RepeatSpec too.
>
> See this branch
> https://github.com/vega/vega-lite/tree/composition-interaction-prototype.
>
> Note this branch is not 100% finalized. Things are still subject to minor
> changes, but probably get you an idea what we'll be able to do.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/1377#issuecomment-220753151>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
I like the naming of the different composition classes being `VerbSpec`. But I don't think that `View` is quite the right naming for the primitive object in those composition operations:

* It has way too many other connotations that will confuse users (the View in MVC).
* A View is often used to represent the most abstract thing that can be shown to a user. If we were going to use the name View, I would say that *anything* that can be rendered as a visualization should be a view, which would include (`Unit` as well as all of the `VerbSpec` classes). In this way of thinking all of these classes would be `View` subclasses.
* When you are using a unit with the composition operations, the unit is not the thing that the user is looking at, even though view has a visual connotation. The user is looking at a composition of units and that is really the view.

The other name that kept coming up when we picked `Layer` was `Chart`. I also think that is the best now:

```python
layer(Chart(data1).mark_point().encode(...), Chart(data1).mark_line().encode(...), ...)
vconcat(Chart(...), Chart(...), ...)
```

**Comment by kanitw** [comment]
I am happy with `Chart`.  It's definitely better than `Layer`.  :)

**Comment by kanitw** [comment]
Looks like we're done with this conversation.
