### ISSUE TITLE
Modify interface for Data

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1381]
```
export interface Data {
  formatType?: DataFormat;
  url?: string;
  /**
   * Pass array of objects instead of a url to a file.
   */
  values?: any[];
}
```

Practically, we should split this into `type Data = UrlData | InlineData` where `UrlData` contains `url` and `formatType` while `InlineData` contains `values`.

**Comment by kanitw** [comment]
This way, we will get more correct JSON schema.

**Comment by domoritz** [comment]
Yes.

**Comment by domoritz** [comment]
Can you wait after the layering pr though? Similarly to this proposal, we should also have different schemas for the top level spec and nested specs (the top level spec has a name, for example).

**Comment by kanitw** [comment]
Sure.  Definitely No hurry on this :)

**Comment by domoritz** [comment]
I guess this should be done against vg3, right?

**Comment by kanitw** [comment]
Depends on whether you do this before or after we merge vg3 into master.  (For now, vg3.)

**Comment by NeelMohapatra** [comment]
What do you mean by splitting the interface?

**Comment by kanitw** [comment]
@NeelMohapatra  I was trying to type to explain but the more I type the more I realize that I should just do it because it's so simple.  Instead, I'll assign you to the review the PR and point to concepts you should be aware of. ;)

**Comment by NeelMohapatra** [comment]
That would be great, thanks!
