### ISSUE TITLE
Remove automatically augmented timeUnit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1385]
We currently automatically augment `month` and `day` (of week) to fixed domains (including all months and weekdays).  

What if users have data for three months and only wanted to show those? 

We need another property to turn this magic off.  (Or maybe remove this problematic feature.)   

@YuhanLu @domoritz

**Comment by kanitw** [comment]
Old text from the duplicate #1212

> Currently, we impute month, day, and a few time units with custom domain for ordinal scale. 
> However, there is no option to turn that off.  
> Moreover, there is also no way to impute custom domain for `year-month`, etc.

**Comment by kanitw** [comment]
In discuss with Jeff, we observe Tableau and found that the do not input missing values for `timeUnit` by default.

**Comment by domoritz** [comment]
Out layout approach is very different from tableau though. We have to  se how that affects things.

**Comment by kanitw** [comment]
I don't think whether to impute really depends on layout method.  

One example that this should not be true is when rows encode quarter and y encodes month.

**Comment by kanitw** [comment]
- [ ] Once we do this, we have to update CompassQL's `schema.cardinality` to handle things correctly based on this flag.

**Comment by kanitw** [comment]
I'm thinking about naming this `imputeTimeUnit: boolean`.  (It should take me less than 30 mins to finish this one.)  

@arvind @domoritz

**Comment by kanitw** [comment]
- [ ] scale.ts - enable `imputedDomain` only if `imputeTimeUnit` is true.
- [ ] `timeunitdomain.ts`
- [ ] unit test

**Comment by kanitw** [comment]
We decide not to allow this at all.  

> - [ ] add `imputeTimeUnit` to Scale* interface
- [ ] scale.ts - enable `imputedDomain` in `domain()` only if `imputeTimeUnit` is true.
- [ ] `timeunitdomain.ts`
- [ ] unit test 

- [ ] remove `timeunitdomain.ts`
- [ ] remove relevant code in scale.ts
- [ ] remove relevant test.
