### ISSUE TITLE
Consider renaming our examples json files to have `.vl.json` extension

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1387]
So that it works with our VSCode plugin: https://github.com/vega/vega-vscode.

Although just to make it work with the plugin might sound like a weak reason, I think this actually have other benefits.  Basically, having a distinguished file extension is a good convention anyway.  Suppose someone develop an offline viewer for Vega/Vega-Lite (e.g., with Electron) in the future.  One can easily map the app as a default viewer for our specific file types (as opposed to any JSON files).

**Comment by domoritz** [comment]
> Suppose someone develop an offline viewer for Vega/Vega-Lite (e.g., with Electron) in the future.

CC @kristw :-P

**Comment by kanitw** [comment]
Duplicate of #1472
