### ISSUE TITLE
Temporal fields don't always work in Safari or Firefox

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1389]
The new punchcard viz (added in https://github.com/vega/vega-lite/pull/1361) works in Chrome:

![punch-chrome](https://cloud.githubusercontent.com/assets/659086/15508634/401759b6-219e-11e6-9a1b-7592b09c9d68.png)

But doesn't display any points or legend in Safari or Firefox on the Mac:

![punch-safari](https://cloud.githubusercontent.com/assets/659086/15508647/49643926-219e-11e6-8697-ba6dd0e5daf0.png)

Looking at the SVG output, there is exactly one mark at the origin:

```svg
<path transform="translate(0,0)" d="M0,1.692568750643269A1.692568750643269,1.692568750643269 0 1,1 0,-1.692568750643269A1.692568750643269,1.692568750643269 0 1,1 0,1.692568750643269Z" style="fill: #4682b4;">
```

I suspect it has something to do with the temporal fields in the spec not being processed correctly by non-V8 JavaScript engines. 

```json
{
  "data": { "url": "data/github.csv"},
  "mark": "circle",
  "encoding": {
    "y": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "day"
    },
    "x": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "hours"
    },
    "size": {
      "field": "count",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}
```

**Comment by mprudhom** [comment]
Digging a little deeper, it appears that "2010-03-03 02:00" isn't parsing in Safari/FireFox, but "2010/03/03 02:00" does. I.e., this works:

```json
{
  "data": { 
    "values": [
      {"time": "2010/01/01 00:00","count": 20},
      {"time": "2010/02/02 01:00","count": 200},
      {"time": "2010/03/03 02:00","count": 2000},
      {"time": "2010/04/04 03:00","count": 1000}
    ]
  },
  "mark": "circle",
  "encoding": {
    "y": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "day"
    },
    "x": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "hours"
    },
    "size": {
      "field": "count",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}
```

But this does not:

```json
{
  "data": { 
    "values": [
      {"time": "2010-01-01 00:00","count": 20},
      {"time": "2010-02-02 01:00","count": 200},
      {"time": "2010-03-03 02:00","count": 2000},
      {"time": "2010-04-04 03:00","count": 1000}
    ]
  },
  "mark": "circle",
  "encoding": {
    "y": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "day"
    },
    "x": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "hours"
    },
    "size": {
      "field": "count",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}
```

So a quick fix might be to update https://github.com/vega/vega-datasets/blob/gh-pages/data/github.csv with a date format with works, but a better solution would be to fix the date/time parsing so they work the same in all browsers.

**Comment by mprudhom** [comment]
Dropping the time component from the YYY-MM-DD date format also works:

```json
{
  "data": { 
    "values": [
      {"time": "2010-01-01","count": 20},
      {"time": "2010-02-02","count": 200},
      {"time": "2010-03-03","count": 2000},
      {"time": "2010-04-04","count": 1000}
    ]
  },
  "mark": "circle",
  "encoding": {
    "y": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "day"
    },
    "x": {
      "field": "time",
      "type": "temporal",
      "timeUnit": "hours"
    },
    "size": {
      "field": "count",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}
```

**Comment by mprudhom** [comment]
This sounds a bit like https://github.com/vega/datalib/issues/63, which was closed for being "beyond datalib". I think that it would be better to wholesale reject the parsing of dates that have different behaviors in different browsers rather than having a spec work in one but not in another.

**Comment by arvind** [comment]
[datalib uses](https://github.com/vega/datalib/blob/master/src/util.js#L114) the browsers' native `Date.parse` method directly. Perhaps I'm misunderstanding your suggestion, @mprudhom, but we do not want to codify cross-browser idiosyncrasies within datalib -- it would be difficult to make sure that always stayed up-to-date and accurate. Instead, I think the right fix is to correct the format of the dates in the `github.csv` file in `vega-datasets`.

**Comment by arvind** [comment]
Though, perhaps a more forgiving option would be to have the default format in datalib be something like `d3.time.format('%c')` rather than `Date`.

**Comment by mprudhom** [comment]
I agree that browser compatibility fixes shouldn't be included in vega*/datalib. What I am suggesting is having a blacklist of certain formats that are known to be inconsistent or ambiguous and simply reject the parsing out of hand with some "Bad Date Format" exception. That way, people wouldn't accidentally create a spec that works fine on their desktop but is broken on another platform/device.

**Comment by kanitw** [comment]
I think this discussion is not really at the Vega-Lite level, so I'm closing it.  
Feel free to continue discussing about this is a relevant repo.

**Comment by jheer** [comment]
I agree that the primary issue under discussion here is more suited to datalib and/or Vega. However, it does raise the important issue that Vega-Lite examples should only use date/time formats that work across all major browsers. We should definitely fix the input data in any such examples.

**Comment by kanitw** [comment]
Oh good catch!  Will do that tmr then.
