### ISSUE TITLE
Use vega-embed for the site gallery

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1390]
The vega-lite example gallery at https://vega.github.io/vega-lite/examples/ currently renders previews using pre-generated svg files. If it embedded the specs directly or via iframes, the specs would be rendered live instead, which would allow interactive features to be demonstrated.

Furthermore, there have been a number of issues where specs don't render properly in non-Chrome/V8 environments. Having the example gallery render live specs would be a good way to smoke test a release by opening the gallery in different browsers and verifying that they all render, or even using a tool like http://browsershots.org to see how they all render on other operating systems.

**Comment by kanitw** [comment]
Thanks for suggestion.   However, loading examples directly will be much slower.
We already have test example gallery for visual testing.  The only problem is that we sometimes didn't test that with different browsers.   So I don't think we are going to do this.
