### ISSUE TITLE
Add PlaceholderData interface

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1392]
(For binding data at runtime) 

To allow sharing across multiple units, maybe allow `name` property?

**Comment by kanitw** [comment]
@willium  This would be one of the good core issues to tackle.

**Comment by willium** [comment]
Cool. Would love see an example spec for this. I'm doing it in Vega I believe for my current project:
```
{
  "width": 750,
  "height": 750,
  "data": [
    { "name": "nodes" },
    { "name": "links" },
    {
      "name": "products",
      "source": "nodes",
      "transform": [{"type": "filter","test": "datum.type == 'product'"}]
    },
    {
      "name": "countries",
      "source": "nodes",
      "transform": [{"type": "filter","test": "datum.type == 'country'"}]
    },
```
but not sure how this would look in VL

**Comment by kanitw** [comment]
Hmm actually this one is specific to composition stuff, so let's wait, but there are a number of other things to do. :)
