### ISSUE TITLE
Create bar with negative value example

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1418]
We need an easy way to move axis in the middle where there are negative values. 

<img width="993" alt="bar_chart_with_negative_values_-_bl_ocks_org" src="https://cloud.githubusercontent.com/assets/111269/15909465/5de920e4-2d7b-11e6-872f-80d4b6221a42.png">

**Comment by kanitw** [comment]
We can manually draw rule or using condition as in https://github.com/vega/vega-lite/pull/3239

**Comment by kanitw** [comment]
Actually, let's make this an issue to create this example once #3239 is merged

**Comment by pratapvardhan** [comment]
Example appears to be added to gallery. Issue is good to be closed?

**Comment by domoritz** [comment]
It's not in the official gallery yet, though.

**Comment by kanitw** [comment]
I'm adding a better version, which uses conditional grid color in https://github.com/vega/vega-lite/pull/6105
