### ISSUE TITLE
Custom datetime parsing

### ISSUE THREAD

**Issue by aishfenton** [vega/vega-lite#1419]
Maybe an invalid feature request (but I can't see an existing way to do this). 

Is there some way in vega-lite to specify a custom datetime parser for a field? For example, if i have a temporal field that is encoded YYYYMMDD (as integer, not a string), so Vega-Lite doesn't recognize it as a datetime, how do I get vega-lite to treat this as a datetime?

**Comment by kanitw** [comment]
I would request this at the Vega level first.  We simply rely on Vega's parser.

**Comment by aishfenton** [comment]
Raised here: https://github.com/vega/vega/issues/586

**Comment by domoritz** [comment]
You already can ;-) See vega/vega#586

**Comment by aishfenton** [comment]
+1, I think this'll be a common need and your suggestion solves it.

**Comment by kanitw** [comment]
> I propose that we add a parse transform to Vega-Lite.

Since this should be a part of `format.parse`, it's coming even before the `transform`.  

We're breaking `formatType` into `format.type` in this PR.  https://github.com/vega/vega-lite/pull/1409

After it's merged, we can add `parse` there.

**Comment by kanitw** [comment]
#1409 is merged, let's address this as a part of https://github.com/vega/vega-lite/issues/1419

**Comment by domoritz** [comment]
#1419 is this issue and it's been closed. Should we reopen or did you mean another issue?

**Comment by kanitw** [comment]
Oops I meant #1436
