### ISSUE TITLE
Easier way to set width and height

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1421]
Right now `width` and `height` are sort of hidden inside `config.cell`.   

Maybe we can add top-level `width` and `height` for `UnitSpec` and `LayerSpec` for easier width and height adjustment?  

(I don't want to add these to `Facet/Repeat/ConcatSpec` though at least until we support top-down layout sizing.)

Blocked by #194
Relevant to #1288

**Comment by domoritz** [comment]
Definitely more discoverable and an important feature. However, it's confusing if ordinal charts are not sized correctly with width/height right now.

**Comment by kanitw** [comment]
Agree, that's why I haven't done it.  I'll do this after #194  (Adding "Blocked by #194" to above)

**Comment by kanitw** [comment]
Done in #1214
