### ISSUE TITLE
Description field missing in much of the Schema

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1424]
In the [Altair](https://github.com/ellisonbg/altair/) project we now auto-generate Python wrappers from the schema; part of this is documenting the interface by extracting the ``description`` field from the Vega-Lite schema. An example of the generated code can be seen here: [``axisproperties.py``](https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/axisproperties.py).

The description fields are filled-out rather sparsely through the package; for example, many are missing in [``cellconfig.py``](https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/cellconfig.py).

Are there plans to fill these out? It would be very helpful from the standpoint of usability of these kinds of generated wrappers. I'd be happy to help out if you'd like to do an afternoon sprint on this some time soon.

**Comment by kanitw** [comment]
Good point.  We mostly have description of properties in the docs in markdown.  I think we just have to copy them over.  Maybe I can just do that when I watch NBA finals or GOT this weekend.  :)

**Comment by jakevdp** [comment]
Thanks! That was fast

**Comment by domoritz** [comment]
Or world cup. Your choice :-P

**Comment by kanitw** [comment]
@domoritz  That will have  to wait two years. lol

**Comment by domoritz** [comment]
fixed (world -> euro), ups...

**Comment by jakevdp** [comment]
Do you think it would be possible to get this into a minor release soonish? We're trying to get an altair release out the door, and having these comments would be very helpful. Thanks!

**Comment by kanitw** [comment]
Just release `v1.0.12` for you :)

Some descriptions still need to be filled / improved, but we will gradually do that over time.

**Comment by jakevdp** [comment]
That's great – thanks!
