### ISSUE TITLE
Should we rename `filterNull` to `filterInvalidValues` since it's no longer just null

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1426]
In #1416, we make `filterNull` also filter `NaN`.     Should we rename `filterNull` to `filterInvalidValues` since it's no longer just null?   (Of course, but offer backward compatibility.)

@domoritz @jheer @arvind

**Comment by kanitw** [comment]
@domoritz  ping.

**Comment by arvind** [comment]
SGTM! `filterInvalid` for conciseness?
