### ISSUE TITLE
Should we make `stack` less obscure?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1434]
I think having `stack` as a part of config (`config.mark.stacked`) might be too obscure since it's a kind of visual encoding/layout transformation (Just like `width` and `height` -- #1421).

A few alternatives:
- `stack` as top-level property 
- `layout.stack` -- this way we can still add other transform e.g., `layout.treemap` and group them inside other visual transforms.

**Comment by domoritz** [comment]
or stack could be part of `enocoding.y/x` depending on how the chart is oriented.

**Comment by kanitw** [comment]
Stack involves both the measure and the level of detail channel (`color`, `detail`, `opacity` or, in a bad case, `size`) so adding it to `x`, `y` might be confusing?

**Comment by kanitw** [comment]
This will be handled as a part of https://github.com/vega/vega-lite/issues/1882
