### ISSUE TITLE
Single plot, multiple marks

### ISSUE THREAD

**Issue by aishfenton** [vega/vega-lite#1435]
Feature request: Add support to vega-lite for having multiple, but different, mark types on a single graph. This is useful in many scientific plots, where often you want to visualize different summaries of the data together on a single plot (e.g. error bars, quantiles, etc). 

For example, ggplot lets you add multiple "marks" to its plots like this:
http://docs.ggplot2.org/current/geom_smooth.html#examples

**Comment by aishfenton** [comment]
Ahh, I see in another branch there is a "layers" element in the works. Awesome!

**Comment by kanitw** [comment]
I'll close this then since this is duplicate with already planned feature.
