### ISSUE TITLE
Test for exampls specs should not pass when key is a typo (not in JSON schema).

### ISSUE THREAD

**Issue by felixcodes** [vega/vega-lite#1440]
In any of JSON files in example/specs/ (area.json, bar.json, etc.) when you change "timeUnit" to "tim", "scale" to "skill" or create some other typo on a key, the tests still pass when they should not.

Is this an issue with the schema or with examples.tests.ts?

**Comment by felixcodes** [comment]
Changing an array to a string or a string to an array will cause the test to fail, as expected, however.

**Comment by domoritz** [comment]
Could be an issue with extra properties being allowed.

**Comment by kanitw** [comment]
Not sure if this is still an issue. Seems like we changed schema validator.  Someone should check this out.
