### ISSUE TITLE
single-page example would be really helpful

### ISSUE THREAD

**Issue by lwhite1** [vega/vega-lite#1443]
I'm sure i'm in the minority, but having all the examples 'js-fiddle' style, where you show only the javascript code, is needlessly difficult for newbies. When you do 'show source' on the example page, you get all the code for the surrounding app. Also not very helpful.

If the single page example(s) used cdn, that would be another win.

**Comment by kanitw** [comment]
Thanks for the feedback.  

We have an example boilerplate here.  https://github.com/vega/vega-lite-demo

If we're to have a function in Vega-editor to generate standalone example in JSFiddle, it should be from vega-editor, not the examples page.  I don't think we'll add that ourselves , but I think it's a good idea and we're welcome if you want to send a PR to [vega-editor](https://github.com/vega/vega-editor). 

I also update docs to clarify the link to vega-lite-demo repo as well, but need to wait until our colleague fix something that's wrong with github pages build first before that'll show up on the website. 
https://github.com/vega/vega-lite/commit/27103ecef689622d8b803c028174847e40bc10ee


cc: @willium -- another motivation for fixing gh-pages build soon :)
