### ISSUE TITLE
Extensive Time Support

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#145]
in #48  we support basic time binning  (`second`, `minute`, `hour`, `dayofweek`, `date`, `month`, year`)

- [ ] add century, decade, quarter

- [x] other time “flooring” function — we need to implement floor instead of transforming to ordinal in order to utilize the time scale.   And thus, we should have the following functions:

- `yearmonth` or `%y-%m` in [`d3.time.format()`](https://github.com/mbostock/d3/wiki/Time-Formatting)
- `yearmonthday` or `%y-%m-%d` 
- `yearmonthdayhour` or `%y-%m-%d-%H` 
- `yearmonthdayhourminute` or  `%y-%m-%d-%H-%M` 
- `hourminute` or  `%H-%M` 
- `hourminutesecond` or  `%H-%S`

Note that using the the format like above would simplify sorting order of the data.  (For labeling, we can use %b instead of %m but it would make sorting more difficult)

Even better, we could support
- [ ]  using custom label on the axis (later)

——

In any case, make sure we update
- [ ] `axisTitleOffset()` to provide correct estimator for length of labels

- [ ] `scale.type` add add default timeUnit

**Comment by domoritz** [comment]
Support mapping numbers to day of week string as in examples from @depstein. 

`0` -> `Monday` ...

**Comment by depstein** [comment]
Unsure if you want to support this, but I map hours to 12-hour time as well.

`14` -> `2 PM` (`%I %p`)

**Comment by domoritz** [comment]
@depstein thank for the suggestion. The challenge there is that you want to parse the number before you use a formatter (like https://github.com/mbostock/d3/wiki/Time-Formatting). Unfortunately, we won't support parsing arbitrary formats a la http://momentjs.com/docs/#/parsing/ soon. We have special functions for month and day of week names (https://github.com/vega/datalib/blob/master/test/template.test.js#L159), though and I might add support for times at some point.

**Comment by domoritz** [comment]
I think I'm wrong. At least d3 supports parsing with formats (https://github.com/mbostock/d3/wiki/Time-Formatting#format) so we should be able to add that easily.

**Comment by depstein** [comment]
That would be great! I've worked around it for the time being, but it sounds useful long-term. Thanks for the good work.

**Comment by domoritz** [comment]
I should see what works now.

**Comment by kanitw** [comment]
@domoritz bump

**Comment by kanitw** [comment]
Seems like there are 3 cases for timeUnit scales:
1) ordinal scale where you want all data (e.g., month on x, y) -- row and column should not support this
2) ordinal scale where you want only data that exists (e.g., month on row, column) - this is for dimension of bar/tick mark.  (See `type()` in `scale.ts` for how to determine what is dimension.)
3) time scale -- row and column should not support this

**Comment by kanitw** [comment]
@domoritz I guess this is done.

**Comment by domoritz** [comment]
Well, I haven't added century, decade, quarter but other than that, yes.

**Comment by depstein** [comment]
Darn, I really needed those.

~Daniel Epstein

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/issues/947
