### ISSUE TITLE
Unrecognized date and '2006' fallback

### ISSUE THREAD

**Issue by BrunoMRP** [vega/vega-lite#1456]
I have created the following vega-lite spec:

```
{
  "data": {
    "values": [
      {"date": "2016-06-09T17:25:57.000Z","id": "HS"},
      //snip...
      {"date": "2016-06-06T10:15:52.000Z","id": "CHECK"}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {
      "timeUnit": "monthday",
      "field": "date",
      "type": "temporal",
      "axis": {"format": "%x"}
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    },
    "color": {"field": "id","type": "nominal"}
  }
}
```
(Spec with more test data [here](https://gist.github.com/BrunoMRP/8588c118b599968e33bdd53fdead913a))

Compiling this to vega and rendering or using the Vega Editor, shows the date as '2006'. It seems that the year '2006' is hardcoded and used when the year is not found in the `timeString` property. 

Yet, using the above spec, replacing the hardcoded '2006' with `get('year')` seems to work.

```
if (timeString.indexOf('year') > -1) {
    out += get('year');
} else {
    out += get('year');
}
```

**Comment by kanitw** [comment]
Hi,  Thanks for reporting. 

However, this is not a bug.  If you use `monthday` as your `timeUnit`, the data would not contain information about the year and thus we have to supply arbitrary year as the year value (We use `2006`).

If you want to use the actual year value, you can use `yearmonthday` as your `timeUnit` like this:

```
{
  "data": {
    "values": [
      {"date": "2016-06-09T17:25:57.000Z","id": "HS"},
      {"date": "2016-06-06T10:15:52.000Z","id": "CHECK"}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {
      "timeUnit": "yearmonthday",
      "field": "date",
      "type": "temporal",
      "axis": {"format": "%x"}
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    },
    "color": {"field": "id","type": "nominal"}
  }
}
```

If you don't want to show date at all, you can use a time format that only includes month and day.
