### ISSUE TITLE
Document deprecation of data.formatType

### ISSUE THREAD

**Issue by adam-iris** [vega/vega-lite#1457]
The main example on https://vega.github.io/vega-lite/ includes the old way of specifying the data format:

    {
      "data": {"url": "data/seattle-temps.csv", "formatType": "csv"},
      ...
    }

This should be updated to the new syntax.

As an aside, I have to note that I find this issue extremely worrisome:

- The example on the home page actually still works, because the format is inferred from the file extension (".csv") in the absence of an explicit value. Basically, the system is just smart enough to cover up the error.
- The page on embedding (https://vega.github.io/vega-lite/usage/embed.html) encourages using the "current" version of various libraries. This is obviously bad practice, but by encouraging it you suggest to the user that it's at least somewhat safe (eg. you aren't going to push backward-incompatible changes without some sort of mitigation).
- And yet the change is completely backward-incompatible, it doesn't so much as log a warning when it finds the old syntax.

The upshot is that use cases suddenly fail without warning, without a clear indication of what's going wrong, and in contradiction to the documentation. (What's going wrong is that the CSV data is being parsed as JSON, but the only way to see this is to look at the stack trace.)

We are evaluating Vega/Vega-Lite, and I really like it so far. I would love to start using it widely and be confident in doing so. So I hope this is taken as the constructive criticism that is intended. But this is a **huge** red flag, and I really hope that this sort of consideration gets higher priority in future releases.

**Comment by kanitw** [comment]
Thanks for reporting.  We just have [added backward compatible code](https://github.com/vega/vega-lite/commit/02fee54710102571677ddc3f2e1bed01b4800284) for this one. 

Apologies for this oversight this time, rest assured that we rarely make breaking changes and will take care of it better next time.  Note that we originally in the release note that [we removed the property (now changed to deprecated)](https://github.com/vega/vega-lite/releases/tag/v1.0.13) but yeah we shouldn't have mistakenly introduce this in a patch version. 

That said, you should still remove `formatType` as we will likely remove it in the next major version.  

One thing that might help you discover this syntax changes in the future is to validate your specification with our JSON schema, which is automatically generated from our typescript interface and thus is always up-to-date.  

Most examples we show are tested with the JSON schema too, except some in the docs that are currently inlined.  We're considering removing all inline examples to prevent this in the future too.

**Comment by adam-iris** [comment]
Thanks for the quick response, and apologies if I ended up ranting a bit. Just got a little frustrated.

**Comment by domoritz** [comment]
Thank you for the detailed report. Just keep in mind that we are only a few (graduate) students working on this project and we try our best to make sure things work and are documented but we cannot deliver the same maturity as a commercial product. We hope that with bug report and pull requests this project can grow and mature further to get closer, though ;-)

**Comment by kanitw** [comment]
Thank for the response.  No worries.  Your feedback are helpful, but like @domoritz said. 
We're a small team (a few graduate students, with occasional help from a few more undergrads) and 
this is our side project since our main duty is to do research so please be forgiving to us.  
Of course, we will definitely try our best to avoid glitches but if you experience some please feel free to report.  Comments, bug reports and PRs are definitely welcomed.
