### ISSUE TITLE
timeUnit with empty dataset throws error

### ISSUE THREAD

**Issue by peller** [vega/vega-lite#1458]
see JSFiddle: https://jsfiddle.net/sjbkb77k/2/

providing an empty array for `data` results in:

> Cannot read property 'getFullYear' of undefined

**Comment by domoritz** [comment]
Thanks for the bug report. Do you have a specific use case where this came up?

**Comment by peller** [comment]
plotting with that timeUnit setting, against a dataset which is filtered.  User typed an invalid filter resulting in an empty dataset.

**Comment by kanitw** [comment]
This is a Vega bug, so I'm filing it here: https://github.com/vega/vega/issues/604.

**Comment by kanitw** [comment]
I'm closing as there is nothing we need to do in VL codebase and an issue has been filed in Vega.
