### ISSUE TITLE
Better timeUnit `day` and `date` combinations?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1473]
Right now for `day` we support:
- [x] `yearmonthday`: 2016-July-Friday 
> This is ambiguous to me, as there are multiple Fridays in July. I can only imagine this one to be useful if we are analyzing weekly patterns.

- [x] `yearday`: 2016-Friday
> Why do we have this? Weekly patterns in a year?

- [x] `yearmonthdayhours`: 2016-July-Friday 15
> Should we auto-append ":00" (e.g., 2016-July-Friday 15:00)? It will be more clear that the last two digits mean `hours`

- [x] `yearmonthdayhoursminutes`: 2016-July-Friday 15:41

For `date` we support:
- [x] `yearmonthdate`: 2016-July-15

- [x] `yeardate`: 2016-15
> Monthly pattern in a year?

- [ ] `yearmonthdatehours`: 2016-July-15 15
> This is not currently supported but I think it could be useful... It would be even better if we auto-append ":00" (e.g., 2016-July-15 15:00)

- [ ] `yearmonthdatehoursminutes`: 2016-July-15 15:41
> I think this is a commonly seen timestamp format, but it's not currently supported.

And what about these timeUnits?
- [ ] `yearmonthdateday`: 2016-July-15-Friday
> It's a common timestamp format too

**Comment by kanitw** [comment]
We already have `yearmonthdatehours` and `yearmonthdatehoursminutes` (https://github.com/vega/vega-lite/blob/master/src/timeunit.ts#L17)  in the master as of friday.

(You might not have pulled what I fixed on the flight lol) 

In terms, data transformation  `yearmonthdateday` is the same as `yearmonthdate` users can customize their timeFormat themselves.
