### ISSUE TITLE
vl.spec.fieldDefs() returns empty array for layered line and area charts

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1476]
For the layered line chart and area chart specs:
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_line_full.json
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_area_full.json

`vl.spec.fieldDefs()` returns `[]` instead of a complete list of `fieldDefs` that's used for encoding. 

This is blocking https://github.com/vega/vega-tooltip/issues/47

**Comment by kanitw** [comment]
Feel free to send a PR to fix this.  This should be straightforward.

**Comment by kanitw** [comment]
@ZeningQu  I remember you already started a bit on this?  If so, do you mind submitting the PR so someone can take over (or even better finish it).  Thanks
