### ISSUE TITLE
Support for Vega and VegaLite files in JupyterLab

### ISSUE THREAD

**Issue by ellisonbg** [vega/vega-lite#1477]
Please:
- [x] Check for duplicate issues
- [x] Describe how to reproduce the bug /  the goal of the new feature request
- [x] Provide an example spec and/or screenshots (if applicable) 

I have a prototype of a JupyterLab plugin that enables users to "just double click" on a Vega or VegaLite file and view/render the visualization in JupyterLab - with no notebook or kernel...

<img width="1271" alt="screen shot 2016-07-25 at 9 24 51 pm" src="https://cloud.githubusercontent.com/assets/27600/17126087/c41e5732-52ae-11e6-8081-a69622fa2238.png">

This also allows you to edit the JSON in an editor and see the changes rendered in real-time...

**Comment by kanitw** [comment]
This looks pretty cool.   I guess there is no actionable item from our side? 

Btw, as mentioned in #1472 I think that if `.vl.json` is a better file extension that `.vl` as any editor would pick up automatically that it's a JSON format.

**Comment by kanitw** [comment]
I think there is no actionable item from our side here, so I'm closing :)
