### ISSUE TITLE
Temp Mean Example doesn't render

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1485]
```js
{
  "data": {"url": "data/seattle-weather.csv"},
  "transform": {
    "calculate": [
      {
        "field": "temp_range",
        "expr": "datum.temp_max - datum.temp_min"
      }
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {
      "timeUnit": "month",
      "field": "date",
      "type": "temporal"

    },
    "y": {
      "aggregate": "mean",
      "field": "temp_range",
      "type": "quantitative"
    }
  }
}
```

**Comment by kanitw** [comment]
The culprit is that filterNull comes before formula transform in the Vega output.  

@domoritz  Not sure if this is fixed in the layering branch?

**Comment by domoritz** [comment]
Might be the same as https://github.com/vega/vega-lite/issues/1453

**Comment by domoritz** [comment]
Hmm. Somehow neither this, nor #1453 work with the current layering branch. Fundamentally there is a bit of an issue because in the current layering branch nullfilter does not depend on formula (but maybe should).

**Comment by kanitw** [comment]
I thought you say #1453 works in the layering branch

**Comment by domoritz** [comment]
It did.
