### ISSUE TITLE
Combine and Clarify Fielddef.field() parameters

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#1493]
Currently we have some ambiguous stuff going on that was likely patched per individual use scenarios. Because Fielddef is rather import and already being considered for feature additions (#1449), here's some nice-to-have low hanging fruit.
1. combine `prefix` and `prefn` into HashSet of functions
   
   Since a field can be prefixed by multiple functions, it makes some sense to have opt.fn be a HashSet and then order these functions as prefixes within fielddef.ts (make sure they're applied in the right order)
   
   usage
   
   ```
   { fn: [rank, bin] }
   ```
   
   fielddef
   
   ```
   for [fn in possible_fns]
   if (opt.fn.includes(fn))
    field = `${fn}_${field}`
   ```
2. combine `binSuffix` and `suffix` using some alternate flag for conditionally adding these
   Currently they're two different options (likely because binSuffix should only be added given certain conditions, while suffix should be added indiscriminately)
3. implement the `nofn` flag in another way? This strikes me as sort of a dark pattern
4. improve implementation of `binSuffix`
   Current binSuffix implements defaults within field() but also several times within it's usage (in other files). This might be because of an oversight? Or perhaps because it needs further conditionals (like also having scale be true? (not sure what this means, but saw it in one instance)).

**Comment by kanitw** [comment]
Your `fn` as suggested above is an array, not a HashSet.

**Comment by domoritz** [comment]
Is this still relevant?

**Comment by kanitw** [comment]
probably not. Let's close for now. We can reopen if needed.
