### ISSUE TITLE
field "in" in InFilter

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1508]
I'm working on upgrading Altair with recent Vega-Lite changes: our scripts are now breaking because the InFilter definition has a field named "in", which is a reserved keyword in Python.

For Altair to work, we have two options:

1. change the field name in Vega-Lite, and make sure future changes don't use Python keywords as field names (e.g. in, for, while, if, else, is, not, and, or, etc.)
2. add some logic to Altair's code generation that will detect such keywords and modify them within the Altair wrapper, for example using the property ``in_`` rather than ``in``

The way forward probably comes down to a decision of how central Altair is to the project. I'm fine either way you decide, although I'll note that option 2 will come at the cost of some non-negligible complexity added to Altair.

**Comment by jakevdp** [comment]
cc/ @ellisonbg @domoritz

**Comment by kanitw** [comment]
I don't have strong opinion about which way to go.  

Suppose we do 1,  here are a few other options:

- `contains`  (lodash's deprecated name)
- `includes` (lodash's name method name)
- `has`
- `(is)memberOf`
- `(is)oneOf`
- `inSet`

cc: @jheer @arvind

**Comment by jakevdp** [comment]
Thanks @kanitw. IIUC, this filters by a list of valid values. Maybe it could be called ``validValues``? I think ``oneOf`` is probably a no-go because of its current use in the schema definition. 

Or perhaps it could be ``EnumFilter``/``enum`` referring to enumerated values, in analogy to ``RangeFilter``/``range`` and ``EqualFilter``/``equal``.

**Comment by arvind** [comment]
My vote would be to go down (1) as well as I can imagine it being an issue beyond Altair/Python. Moving forward, it would be good practice for us to be cognizant of these reserved keywords which, I believe, broadly overlap between languages. Of the suggestions, my preference would be `enum` which more closely matches the existing `in` as I understand it (`contains` and `includes` are subtly different, no?).

**Comment by jakevdp** [comment]
Thanks @arvind. Now that I think about it, though, ``enum`` might be a problem in some languages as well...

**Comment by willium** [comment]
Are you talking about 
https://github.com/vega/vega-lite/blob/345f7de9d96884946538471f0ef4e1b551a68b4f/src/filter.ts#L87 and https://github.com/vega/vega-lite/blob/345f7de9d96884946538471f0ef4e1b551a68b4f/test/filter.test.ts#L7
? 

Can we not just change
```
  return filter && !!filter.field && isArray(filter.in);
```
to
```
  return filter && !!filter.field && isArray(filter['in']);
```

Sorry if I'm misunderstanding the problem

**Comment by kanitw** [comment]
In a meeting today, @jheer, @arvind, and I conclude that we'll change it to `oneOf` while adding backward compatibility for `in` (but deprecate `in` by removing it from the schema).

**Comment by jakevdp** [comment]
Great - thanks for that! Will the definition name be changed to 'OneOfFilter' to match?

**Comment by kanitw** [comment]
> Will the definition name be changed to 'OneOfFilter' to match?

Exactly :)
