### ISSUE TITLE
Output source map in a separate file, rather than at the end of file.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1515]
Currently the output Vega-lite.js includes source map at the end of file instead of having a separate `vega-lite.js.map`, which can be annoying for people who don't need it.

**Comment by willium** [comment]
of course its called exorcist

**Comment by domoritz** [comment]
Don't forget to change the deployment script. I believe we still want to the sourcemaps to be included.

**Comment by domoritz** [comment]
Opening until it's fixed.

**Comment by kanitw** [comment]
Can u fix that? Lol
