### ISSUE TITLE
While using log scale the legend is formatted badly

### ISSUE THREAD

**Issue by chananelp** [vega/vega-lite#1518]
While using log scale the legend is formatted badly.

If i run this code with linear scale all seems OK:
```
{
  "data": {"url": "data/movies.json"},
  "mark": "point",
  "encoding": {
   
    "y": {
      "field": "Rotten_Tomatoes_Rating",
      "type": "quantitative"
    },
    "size": {
      "scale": {
        "type": "linear"
      },
      "field": "Rotten_Tomatoes_Rating", 
      "type": "quantitative",
      "legend":{"values":[0,1,50,100]}
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/16744321/17851379/57f6dda0-686a-11e6-9f22-8bb4120319c7.png)

But if I change the scale to "log", the legend looks bad:
**1)** All legend numbers are one on each other.
And now, if I remove the 0 from the "values" list
**2)** The legend looks better but still has bug that the number 50 is missing.

![image](https://cloud.githubusercontent.com/assets/16744321/17851342/1caf731a-686a-11e6-9b75-e43671c5bd94.png)

![image](https://cloud.githubusercontent.com/assets/16744321/17851351/2ebb801c-686a-11e6-8e12-b3d0b4f455af.png)

**Comment by kanitw** [comment]
This is a bug at the Vega level, I've re-created https://github.com/vega/vega/issues/630 for you.

Thanks for reporting!
