### ISSUE TITLE
vega-embed page in docs could be made much more helpful

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#1529]
https://vega.github.io/vega-lite/usage/embed.html

So the typical user accessing this page is like me: wants to use vega-embed with a minimum of fuss, perhaps knows little/no Javascript, but most importantly, has a blob of JSON vega-lite and wants to embed it in an HTML web page. 

The required libraries list is fine, that's clear. (I personally find the `src="//` bit weird – is it a file or is it remote? – but I figure I can track down how that works under the hood.)

It's not clear to me why I need to install vega-lite (locally?) if I'm going to source the libraries externally. 

Then we get to DOM element. I'm a little fuzzy on DOM anyway, but I'm presuming I can cut and paste this, though it seems weird that there's nothing inside it. 

What is confusing is what comes next. I'm presuming that's Javascript code, but it's not wrapped in any sort of `<script>` tag. It makes reference to a `function` that's a callback. What does that function look like? Example? You'd like this to be accessible to someone who doesn't know Javascript. What is `result.view`?

Much more useful would be concrete examples of:
1. "I have a JSON vega-lite description that I want to embed directly in the HTML of this web page. What does the complete HTML code I need to write look like?"
2. "I have a JSON vega-lite description that is stored in a particular file. What does the complete HTML code I need to write look like?"
3. "I have a JSON vega-lite description that is stored at a particular URL. What does the complete HTML code I need to write look like?"

Obviously there's a lot more options – https://github.com/vega/vega/wiki/Embed-Vega-Web-Components – but providing three minimal examples of that type (or one example that incorporates all three) would go a long way to helping your users.

**Comment by domoritz** [comment]
This will become clearer when we address #1352.
