### ISSUE TITLE
docs are inconsistent on script loads of JavaScript d3/vega/vega-embed

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#1530]
https://github.com/vega/vega/wiki/Embed-Vega-Web-Components gives a different recipe than
https://vega.github.io/vega-lite/usage/embed.html .

**Comment by kanitw** [comment]
Can you explain which part is different?  You mean the URL?

**Comment by jowens** [comment]
Yes. It appears that's what I was thinking when I opened this. The URLs are different.

**Comment by kanitw** [comment]
I see.   I feel like the way we do in Vega-Lite makes more sense and shorter:

```
<script src="//vega.github.io/vega/vega.js" charset="utf-8"></script>
<script src="//vega.github.io/vega-lite/vega-lite.js" charset="utf-8"></script>
```

(Using vega-editor's vendor is kinda weird because I can't see a  reason why we should load it from the editor.)

However, since vega-embed doesn't have it's own published version (AFAIK), we actually load it from the editor like the wiki. 

```
<script src="//vega.github.io/vega-editor/vendor/vega-embed.js" charset="utf-8"></script>
```

@arvind  @domoritz  -- Any opinion about this?

**Comment by jowens** [comment]
Can you clue me in on what the `//` means at the start of the `src` field? Does it default to `http:` or ... what?

**Comment by kanitw** [comment]
> Does it default to http: or ... what?

Good question.  Yes -- but I think we better include `http:`. :)

**Comment by arvind** [comment]
The double slash is a "protocol-relative" link -- i.e., it uses `http` or `https` depending on how the host page is loaded. This avoids errors on some (older) browsers if you mix between protocols (e.g., loading via http on a https page or vice-versa). I believe it is now considered [an anti-pattern](https://www.paulirish.com/2010/the-protocol-relative-url/) when an https URL is available (as it is with our GitHub-hosted assets) so we should probably make them point to https consistently. 

I do not have strong preference about which set of URLs to use in the documentation. What role vega-embed will play once we switch over to Vega 3 remains to be seen.

**Comment by jowens** [comment]
Thanks guys. Appreciate the illumination. Just filing issues when I see inconsistencies. Figure if it's confusing for me, might be worth fixin'.

**Comment by domoritz** [comment]
I think they are not consistent.
