### ISSUE TITLE
UseRawDomain with log scale broken

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1537]
Basically, we have non-positive value filter for log scale in summary data source. 
However, if useRawDomain is true, we draw scale values from summary.  Thus the scale would be broken.

**Comment by kanitw** [comment]
For now, I disable it.  But with the new data source structure, we could revise and consider turning it back on.  

cc: @domoritz

**Comment by domoritz** [comment]
Best fix would be to union with `[0]`, so that 0 is always included.

**Comment by kanitw** [comment]
Actually that will make it always break?

**Comment by domoritz** [comment]
To fix this, we would have to add an additional filter that requires the source to be >0. But we cannot apply the filter to the source directly because we don't want to filter before we aggregate.

**Comment by kanitw** [comment]
Still broken:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": -28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "scale": {"domain": "unaggregated", "type": "log"}}
  }
}
```

**Comment by kanitw** [comment]
![image](https://user-images.githubusercontent.com/111269/33621754-b894e582-d9a0-11e7-95c5-b620d0e2dd81.png)

**Comment by kanitw** [comment]
This is actually not related to `"domain": "unaggregated"`.

It's intentionally broken as we no longer automatically filter negative values for log scale.
