### ISSUE TITLE
Temporal Filter with timestamp range without timeUnit does not work

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1541]
```
{
  "data": {"url": "data/cars.json"},
  "transform": {
    "filter": [{
        "field": "Year",
        "range": [114754909091, 239072727273]
    }]
  },
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "count", "field": "*", "type": "quantitative"},
    "y": {"field": "Cylinders", "type": "nominal"}
  },
  "config": {
    "overlay": {"line": true},
    "scale": {"useRawDomain": true},
    "facet": {
      "cell": {"width": 150, "height": 150}
    }
  }
}
```

The culprit is that date doesn't get parsed correctly.

**Comment by kanitw** [comment]
For example, in Voyager 2 -- we can only see on plot working here. 

<img width="1239" alt="voyager_2" src="https://cloud.githubusercontent.com/assets/111269/18280388/b4ec539c-740d-11e6-855a-7b4372dd4186.png">

**Comment by kanitw** [comment]
A few things we could do
- [ ] We could infer parsing a bit better if filter contains a date time object
- [ ] make `type` optional for filter?

**Comment by kanitw** [comment]
@domoritz  What do you think about 

> - [ ] make `type` optional for `filter` and `sort`?

**Comment by domoritz** [comment]
Hmm, that's a tricky one. I think we need to know the type if it is not specified anywhere. Maybe we do need that schema next to the data. For the filters, we actually need low level types, not Q, N, O, or T.

**Comment by kanitw** [comment]
It's true that what we really need is primitive type, but it seems like it is only wrong for `datetime` fields, which is always a `temporal` field -- so I wonder if we should just stick with Q, N, O, T?

(Can you think of other cases that it will be wrong?)

**Comment by domoritz** [comment]
Maybe even better, let users customize parse.

**Comment by kanitw** [comment]
Users can customize parse already but the problem is its not obvious for them that they need to.

**Comment by domoritz** [comment]
I guess if we require a parse for every field in filter/ compute, we might as well just have users specify it there directly. 

I'm a bit worried about cases where a field gets used in different ways and so we should not reuse a parse from a channel def.

**Comment by kanitw** [comment]
> I guess if we require a parse for every field in filter/ compute, we might as well just have users specify it there directly.

- [ ]  At this point, I think what we definite should do is throw warning if filter/calculate/sort's field is not included in the parse / encoding and thus do not have primitive types defined. Doing this for a unit spec should be easier, but doing for a composite can be complicated (as you can sometimes infer type from other parts of the spec.  Maybe it's not that complex, but this requires deeper thinking.) 

- [ ] I still wonder if we should add optional type (N,O,Q,T) to `filter / sort` for consistency as they still look like field def though.

> I'm a bit worried about cases where a field gets used in different ways and so we should not reuse a parse from a channel def.

Can you come up with a practical example for this case that you are worried?

**Comment by kanitw** [comment]
Another thing to take into consideration is how Vega infer default parse.  
If I remember correctly, it usually correctly infer number and string, but not date?

**Comment by domoritz** [comment]
Date is difficult and can't be inferred automatically in al cases. Sometimes you need to provide a parse expression. Vega could of course try to parse strings to dates and only succeed if the dates are in a standard format.

**Comment by domoritz** [comment]
I think this is sufficiently addressed by Vega-Lite with date parsing support.

**Comment by kanitw** [comment]
> I think this is sufficiently addressed by Vega-Lite with date parsing support.

This is not true.  We still run into this problem during latest development in Voyager.  

The temporary solution is to add custom `parse` for our temporal field.

**Comment by kanitw** [comment]
I think we should add this workaround to the docs for now too.

**Comment by manuelgomezrico** [comment]
Could I do the filter date within Transformer object? Example
I want to get the data last 30 days

**Comment by kanitw** [comment]
> Could I do the filter date within Transformer object? Example  I want to get the data last 30 days

You can write a custom Vega expression for that.  

> The temporary solution is to add custom parse for our temporal field.

I guess that's enough for now.  Let's close this.
