### ISSUE TITLE
Specifying interactivity in charts

### ISSUE THREAD

**Issue by hellochar** [vega/vega-lite#1547]
Does vega-lite support interactions in its JSON spec? All the examples on the website are non-interactive (by interactive I mean "show number on mouse hover", "click and drag to pan/zoom", "click a legend to show/hide that series", etc.). If the spec doesn't support interactivity, will it in the future?

Thanks,
Xiaohan

**Comment by kanitw** [comment]
Thanks for asking.  Please wait for our 2.0 release (hopefully by the end of fall), which will include interaction support.   For now, you can read [our research paper and watch our video demo](http://idl.cs.washington.edu/papers/vega-lite).

**Comment by hellochar** [comment]
Thanks for the timely response! Look forward to it.
