### ISSUE TITLE
Binning nulls?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite#1548]
``` json
{
  "data": {"url": "data/movies.json","formatType": "json"},
  "transform": {"filterInvalid": false},
  "mark": "bar",
  "encoding": {
    "x": {"bin": {},"field": "IMDB_Rating","type": "quantitative"},
    "y": {"aggregate": "count","field": "*","type": "quantitative"}
  },
  "config": {
    "overlay": {"line": true},
    "scale": {"useRawDomain": true},
    "facet": {"cell": {"width": 150,"height": 150}}
  }
}
```

![image](https://cloud.githubusercontent.com/assets/822034/18374348/f85f597c-7600-11e6-9cb1-e81ca7bc1ef5.png)

This showed up in VY2 study

**Comment by ZeningQu** [comment]
![image](https://cloud.githubusercontent.com/assets/822034/18374379/37863b5c-7601-11e6-8c28-34d4ed8bc932.png)

**Comment by kanitw** [comment]
Good catch, that's partly motivates why we always exclude invalid numbers.

Since binning uses linear scale, I think there is not really a good way to get around this besides always excluding  invalid values from bin.

**Comment by kanitw** [comment]
@domoritz @jheer @arvind  -- any idea how we should handle this?   I don't really know if there is a good way to handle this.

**Comment by domoritz** [comment]
Tableau shows an annotation such as "42 null values" but this does not work well with multiple dimensions. Another approach is to have a separate bin for `null` but it's hard to get the scales right.

**Comment by willium** [comment]
I too thought of Tableau's solution, but I think that works well for them because it's interactive (you can click on the annotation that says 42 nulls and decide what to do with them). Agreed that it fails with multiple dimensions and might as well not be there (doesn't really add much information to someone viewing the chart, only really to the creator?).

Just wanted to summarize the discussion @kanitw and I had on slack re: this --
My perhaps slightly ignorant preference (or I guess I'm wondering why this is a bad idea) would be to use a ordinal scale for bins and impute missing bins linearly (perhaps using a vega transform?). Then it would be as simple as adding an ordinal category called nulls below 0/1. @kanitw mentioned that @jheer suggested against this initially. Naively th

**Comment by kanitw** [comment]
>  @kanitw mentioned that @jheer suggested against this initially.

I did NOT mention that he's against what you describe above.  
I only said that @jheer previously suggests the current implementation with linear scale, but we didn't discuss the case when null values is not filtered. 


> click on the annotation that says 42 nulls and decide what to do with them

For binning, Tableau doesn't even include min/max value for binning. They just convert numerical value to (ordinal) bin value.  Putting null values aside, our binned axis is more sophisticated that Tableau.

**Comment by willium** [comment]
Sorry -- that's what I meant! :)

**Comment by jheer** [comment]
To review, the reasons we chose a linear scale over an ordinal scale for histograms:

  1. Linear scales better handles empty cells. Ordinal scales will omit these, creating a misleading axis.
  2. Linear scales can accommodate arbitrary bin sizes. Currently we only produce uniform bins, but if we ever decide to support non-uniform binning, the linear scale approach "just works".
  3. Linear scales are better suited to layering: adding annotations for interquartile ranges, medians, means, etc works without any hassles or special alignment logic.

The downside of course is that we don't handle nulls as easily as an ordinal scale might. Then again, that's true for *any* linear axis situation (e.g., scatter plots where one co-ordinate is null). So a more general solution might be worth considering anyway.

**Comment by kanitw** [comment]
Noting down Jeff's note about null values for binned fields on slack:

> @kanitw, I was thinking more about null handling, and I don't think the bin scale is the appropriate place for special treatment. The problem is more general than just bins and I think the bin scale should focus on handling proper binned numerical data. Instead, I started playing with an example that uses Vega constructs more generally to specially handle null data. The resulting spec is more complicated but not convoluted: it is a straightforward use of Vega abstractions to create a special region for null values. See the example spec in the snippet below. (Note: be sure to update your Vega 3 sub-modules to the latest releases to ensure this works!)

spec: http://pastebin.com/Q6vDQTqN

**Comment by kanitw** [comment]
This should be a part of a more general https://github.com/vega/vega-lite/issues/2544
