### ISSUE TITLE
vega-embed requires embed-spec, but vl2vg requires simple spec

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1551]
This is a somewhat annoying inconsistency that I've found when working on auto-docs in Altair.

I'd like to save the example script to JSON, and then use this to (1) embed directly into a webpage via a filename, and (2) run the `vl2png` script.

But unless I'm mistaken, the spec within the filename passed to `vg.embed` must be an embed-spec of the form `{'mode': 'vega-lite', 'spec': {....}}`, while the spec in the filename passed to `vl2png` must be a raw spec.

Is there any way to do both these things from one file, or do I need two different JSON files for these tasks?

**Comment by kanitw** [comment]
Good point. We definitely should make this less annoying. Maybe after CHI
deadline (in 10 days)

**Comment by jakevdp** [comment]
Thanks!

**Comment by domoritz** [comment]
Embed now takes a normal vega or vega-lite spec.
