### ISSUE TITLE
Allow Assigning Repeat values to color scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1552]
(That would be equivalent to coloring by measure name in Tableau)

**Comment by kanitw** [comment]
@domoritz I'm moving this one to post 2.0.  If you disagree, feel free to move it back.

**Comment by kanitw** [comment]
@ZeningQu  expressed the need for this in a DM:

![image](https://user-images.githubusercontent.com/111269/30244715-bf399052-9578-11e7-9fb1-e69d23dc8f35.png)


Note that the output in the screenshot behaves correctly based on the spec.  We need a different syntax for this use case.  But I'm posting the screenshot anyway as it at least describes what we want from this issue better.

**Comment by kanitw** [comment]
One possible way to support this would be supporting `repeat` values to be an object like 
```
column: [{field: "Horsepower", color: "red"}, ...]
```

and allow accessing property of the repeated value via `repeat` accessor like

```
x: {field: {repeat: 'column', field: 'field'}, ...},
...
color: {value: {repeat: 'column', field: 'color'}, ...},
```

This approach will allow multiple color and should be not too difficult to implement, but won't support scale properties / using preset scale range.

**Comment by domoritz** [comment]
I had thought about this before and think the object idea works best. Why are you using a nominal color scale in the screenshot?

**Comment by ZeningQu** [comment]
That's because the screenshot was my doodle!

**Comment by ZeningQu** [comment]
Mocking up Ham's proposal, this is what the spec would look like:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "repeat": {
    "column": [
      {"field": "Horsepower", "color": "steelblue"},
      {"field": "Miles_per_Gallon", "color": "orange"},
      {"field": "Acceleration", "color": "green"}
    ]
  },
  "spec": {
    "data": {
      "url": "data/cars.json"
    },
    "mark": "bar",
    "encoding": {
      "x": {
        "field": {
          "repeat": "column", "field": "field"
        },
        "bin": true,
        "type": "quantitative"
      },
      "y": {
        "aggregate": "count",
        "type": "quantitative"
      },
      "color": {
        "value": {"repeat": "column", "field": "color"}
      }
    }
  }
}
```

**Comment by kanitw** [comment]
This should come for free with datum #4201.  See https://github.com/vega/vega-lite/issues/1274#issuecomment-500185352.
