### ISSUE TITLE
Setting cell height in text tables?

### ISSUE THREAD

**Issue by longouyang** [vega/vega-lite#1554]
Hi there,

I'm trying to set the height of cells in text tables. I know I can set the width using `config.scale.textBandWidth` but I can't seem to figure out the analogous setting for height.

Example:

```js
{
  "data": {"url": "data/cars.json"},
  "mark": "text",
  "encoding": {
    "row": {"field": "Origin", "type": "ordinal"},
    "column": {"field": "Cylinders", "type": "ordinal"},
    "color": {"aggregate": "mean", "field": "Horsepower", "type": "quantitative"},
    "text": {"aggregate": "count", "field": "*", "type": "quantitative"}
  },
  "config": {"mark": {"applyColorToBackground": true},
    "scale": {"textBandWidth": 50}
  }
}
```

I have tried setting `scale.bandSize` for the row encoding, but this didn't work in the online editor.

**Comment by kanitw** [comment]
Thank you for reporting. 

With the latest fix in the master, you should be able to use `height` to set the cell height (for example, see the screenshot below).  I agree that we should support setting it via config, but that's a special case of #1288.  Thus, I would close this issue for now to avoid duplication.  

![vega_editor](https://cloud.githubusercontent.com/assets/111269/19013791/8316db06-8805-11e6-85d5-d9b40dd0d141.png)
