### ISSUE TITLE
Bug: DayOfWeek has an off-by-one error

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1556]
The Axis labels for weekdays seem to be off by one in the current Vega-Lite release.

![vega 22](https://cloud.githubusercontent.com/assets/781659/18887118/af2e4988-84a7-11e6-927d-d893a432c78d.png)

This is produced by the following Vega-Lite specification, where I put in the correct days-of-week by hand:
```json
{
  "encoding": {
    "x": {"timeUnit": "day","type": "temporal","field": "date"},
    "text": {"type": "nominal","field": "day"}
  },
  "mark": "text",
  "data": {
    "values": [
      {"day": "Sun","date": "2016-09-25"},
      {"day": "Mon","date": "2016-09-26"},
      {"day": "Tues","date": "2016-09-27"},
      {"day": "Wed","date": "2016-09-28"},
      {"day": "Thurs","date": "2016-09-29"},
      {"day": "Fri","date": "2016-09-30"},
      {"day": "Sat","date": "2016-10-01"}
    ]
  }
}
```

I think this *might* be due to Vega-Lite treating ``"2016-9-25"`` as "Sept 25 at 00:00", which is then interpreted in the code as midnight of Sept 24.

**Comment by jakevdp** [comment]
Here's a simpler case that shows the bug; it turns January 1st into December 31st:
```json
{
  "data": {
    "values": [{"date": "2016-01-01"}]
  },
  "mark": "text",
  "encoding": {
    "text": {"type": "temporal","field": "date"}
  }
}
```
Here's the output:
![vega 23](https://cloud.githubusercontent.com/assets/781659/18889819/79eb1e84-84b3-11e6-80d1-b150dd42858a.png)

**Comment by domoritz** [comment]
```json
{
  "encoding": {
    "x": {"timeUnit": "day","type": "temporal","field": "date"},
    "text": {"type": "nominal","field": "day"}
  },
  "mark": "text",
  "data": {
    "values": [
      {"day": "Sun","date": "2016-09-25 00:00"},
      {"day": "Mon","date": "2016-09-26 00:00"},
      {"day": "Tues","date": "2016-09-27 00:00"},
      {"day": "Wed","date": "2016-09-28 00:00"},
      {"day": "Thurs","date": "2016-09-29 00:00"},
      {"day": "Fri","date": "2016-09-30 00:00"},
      {"day": "Sat","date": "2016-10-01 00:00"}
    ]
  }
}
```

Is correct.

**Comment by domoritz** [comment]
It's not incorrect but pool handling of UTC and non UTC dates. Should be handled as part of https://github.com/vega/vega-lite/issues/446.
