### ISSUE TITLE
Support month date with leap year

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1557]
From @jakevdp's question [here](https://groups.google.com/forum/#!topic/vega-js/451aFN7_2_k),
thinking more about it -- we can actually support MONTHDATE unit correctly without modifying anything because year 0 that we [automatically augment to the formula](https://github.com/vega/vega-lite/blob/master/src/datetime.ts#L152) is a leap year. 

For example, the output Vega Expression will be `datetime(0, month(datum[\"date\"]), date(datum[\"date\"]), 0, 0, 0, 0)`.

This way, the output time scale will always have February 29 on the time scale no matter the data include a leap year or not.  I think this is the correct behavior since I can't think of any other ways to make the scale correct.  

@arvind @jheer @domoritz - Do I overlook anything?

**Comment by kanitw** [comment]
I got #1570 for this.

**Comment by ijlyttle** [comment]
I agree completely with the intent here, but I think there is a problem in the implementation. As I understand, year 0 in the `Date` constructor translates to the year 1900, which is not a leap year.

In this demonstration, I expect all the 2012 values to be 10, and all the 2013 values to be 15. I believe the 2012-02-29 and 2012-03-01 values are aggregated to 1900-03-01. You can use the tooltip to see the aggregated year.

https://bl.ocks.org/ijlyttle/b61d20e6f6476f9cdac1254937f7cb6c

**Comment by ijlyttle** [comment]
Here's an observable notebook showing the same thing: https://beta.observablehq.com/@ijlyttle/vega-lite-timeunit-issue-leap-days
