### ISSUE TITLE
mark='errorBar' fails in a Layered chart (version 1.2)

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1583]
The following spec works with the current release:

``` json
{
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/population.json"
  },
  "encoding": {
    "size": {"value": 5},
    "x": {"field": "age","type": "ordinal"},
    "y": {
      "aggregate": "min",
      "field": "people",
      "type": "quantitative"
    },
    "y2": {
      "aggregate": "max",
      "field": "people",
      "type": "quantitative"
    }
  },
  "mark": "errorBar",
  "transform": {"filter": "(datum.year==2000)"}
}
```

But when I try to put this spec in a layer along with another mark type, it fails:

``` json
{
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/population.json"
  },
  "layers": [
    {
      "encoding": {
        "size": {"value": 5},
        "x": {"field": "age","type": "ordinal"},
        "y": {
          "aggregate": "min",
          "field": "people",
          "type": "quantitative"
        },
        "y2": {
          "aggregate": "max",
          "field": "people",
          "type": "quantitative"
        }
      },
      "mark": "errorBar"
    },
    {
      "config": {"mark": {"size": 2}},
      "encoding": {
        "x": {"field": "age","type": "ordinal"},
        "y": {
          "aggregate": "median",
          "field": "people",
          "type": "quantitative"
        }
      },
      "mark": "point"
    }
  ],
  "transform": {"filter": "(datum.year==2000)"}
}
```

**Comment by kanitw** [comment]
@domoritz  I think this is probably in part due to the old assumption that layer can only contain unit spec.  To fix this, we can either (1) allow `layer` to have layers inside or (2) always normalize to have `layer` only contain unit specs. 

I prefer the former if it's not too difficult as I remember I found is a case where (1) can be better a while ago.  (I'm trying to think what's that case though. ><")

**Comment by kanitw** [comment]
> I prefer the former if it's not too difficult as I remember I found is a case where (1) can be better a while ago. (I'm trying to think what's that case though. ><")

I think the main rationale is that if we allow layer to have layer inside, we only have to implement that once and whatever macro we add in the future can benefit from this.  While if we have to always normalize macros to have `layer` only contain unit specs, we need to introduce more complex code every-time we add a new macro.  (Error Bar, Box Plots ...)

**Comment by kanitw** [comment]
This spec works now.

```
{
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/population.json"
  },
  "layer": [
    {
      "encoding": {
        "size": {"value": 5},
        "x": {"field": "age","type": "ordinal"},
        "y": {
          "aggregate": "min",
          "field": "people",
          "type": "quantitative"
        },
        "y2": {
          "aggregate": "max",
          "field": "people",
          "type": "quantitative"
        }
      },
      "mark": "error-bar"
    },
    {
      
      "encoding": {
        "x": {"field": "age","type": "ordinal"},
        "y": {
          "aggregate": "median",
          "field": "people",
          "type": "quantitative"
        },
        "size": {"value": 2}
      },
      "mark": "point"
    }
  ],
  "transform": [{"filter": "(datum.year==2000)"}]
}
```

That said, people can just use the `rule` marks to create error bar. The ticks are in fact unnecessary.  We don't plan to include error-bar in the first 2.0 release.
