### ISSUE TITLE
`legend.labelColor` and `axis.titleColor` should compile into `fill` instead of `stroke`

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#1592]
When specifying `legend.labelColor` and `axis.titleColor` as e.g. "gray", the font's weight appears much bigger than when set to none. It appears that in the compiled vega spec, the label receives the stroke property instead of the fill property, thus increasing its apparent font weight.

**Comment by kanitw** [comment]
@g3o2 It would be great if you could help provide an example spec.  Thank you :)

**Comment by g3o2** [comment]
Sure, sorry about not doing it right away. I'll try to reproduce my future issues using (whenever possible) the available examples in Vega(-lite) Editor. That should make the process more efficient on both sides :)
