### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1594]
The file ``examples/vl-examples.json`` refers to an example named ``"bar"``, but this doesn't exist in the ``examples/json`` directory.

**Comment by kanitw** [comment]
It [exists](https://github.com/vega/vega-lite/blob/master/examples/specs/bar.vl.json) in `examples/specs` just like other specs.   Let me know if I overlook anything :)

**Comment by jakevdp** [comment]
Ah, my mistake. Sorry for the noise
