### ISSUE TITLE
Better mechanism to notice changes in Vega output

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1598]
In the past, we skim the example gallery to make sure that we do not break the output.

However, given that the number of example will only keep growing, this approach is no longer sustainable. 

As I mentioned earlier, we might consider adding compiled Vega output to the repo so we can explicitly see diffs when we make changes (and run test that pass only if the compiled examples match the stored output.) 

Other suggestions are welcomed!

**Comment by g3o2** [comment]
An alternative is to test the `svg` output, though testing the `vega` output would probably be a more consistent approach.

**Comment by kanitw** [comment]
@domoritz  This should be the very first thing we do after migration to Vega 3. 

Right now, while I'm refactoring scale, I feel that the gallery has become too large for manual inspection every time I do something.
