### ISSUE TITLE
Shared Grid for grouped bar chart 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1636]
As discussed in [Vega user group](https://groups.google.com/forum/#!topic/vega-js/P7a_k0sEVNA) and shown below,  grouped bar chart do not share axis grid by default.   We definitely should have a property for customizing this.  

![](https://lh3.googleusercontent.com/-pSpClk1WK0k/WAFRCJmsypI/AAAAAAAAN-4/CuOuOTgnWssyfATDkzrJu4elqcAFBixBwCLcB/s1600/vega.png)

```
{
  "data": {"url": "data/population.json"},
  "transform": {
    "filter": "datum.year == 2000",
    "calculate": [
      {
        "field": "gender",
        "expr": "datum.sex == 2 ? \"Female\" : \"Male\""
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "column": {
      "field": "age",
      "type": "ordinal",
      "scale": {"padding": 4},
      "axis": {"orient": "bottom","axisWidth": 1,"offset": -8}
    },
    "y": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative",
      "axis": {"title": "population","grid": true}
    },
    "x": {
      "field": "gender",
      "type": "nominal",
      "scale": {"bandSize": 6},
      "axis": false
    },
    "color": {
      "field": "gender",
      "type": "nominal",
      "scale": {"range": ["#EA98D2","#659CCA"]}
    }
  },
  "config": {"facet": {"cell": {"strokeWidth": 0}}}
}
```

**Comment by ngaloppo** [comment]
Appreciate this effort, thanks @kanitw

**Comment by kanitw** [comment]
This should become a part of https://github.com/vega/vega-lite/issues/2180

**Comment by tonyxiao** [comment]
Is there a way to specify grouped bar chart without using faceting / trellis plot? In particular it makes things like adding tooltip / rules so much tricker. I wish I can just specify `stack: 'grouped'` for the `x` encoding and have it just work.

**Comment by domoritz** [comment]
We plan to support offset for this.

**Comment by tonyxiao** [comment]
Just found the right issue here - for others (including my future self) stumbling here https://github.com/vega/vega-lite/issues/4703

**Comment by tonyxiao** [comment]
Is this only an issue for vega-lite? Meaning does Vega have better support for grouped bar charts? @domoritz

**Comment by domoritz** [comment]
Vega-Lite generates Vega. In Vega, you more or less draw shapes so grouped bar charts are possible.

**Comment by tonyxiao** [comment]
In the only grouped bar chart example I could find for vega, it still seems to be using facets to accomplish the grouping. https://vega.github.io/vega/examples/grouped-bar-chart/

Do you have another example where the grouping is done without using facets?

**Comment by domoritz** [comment]
I don't but you could just offset the bars differently for the different categories.

**Comment by tonyxiao** [comment]
Gotcha. Good to know that it's just a vega-lite limitation, not vega. More motivation to learn vega then. Thanks!

**Comment by domoritz** [comment]
You can also use Vega-Lite to generate Vega and then modify it by hand. And once you learned Vega, please come back and help us improve Vega-Lite ;-)
