### ISSUE TITLE
Correctly import subfiles in vega-util

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1642]
(Currently we import the whole compiled file)

**Comment by domoritz** [comment]
Possible this get's fixed by using a different compiler e.g. rollup.

**Comment by kanitw** [comment]
Or webpack

**Comment by domoritz** [comment]
Why is it better to import only subfiles? I think we almost use all of it at this point.

**Comment by jheer** [comment]
Probably better _not_ to import subfiles -- use the publicly exported API. Vega 3 uses all of it, so in almost all deployments you'll need the whole library anyway.

**Comment by kanitw** [comment]
The real problem we try to tackle here is to minimize file size, esp. redundancy with Vega.  I'll create a new issue for that.
