### ISSUE TITLE
Why values small than 1 are parsed as millions?

### ISSUE THREAD

**Issue by chuanconggao** [vega/vega-lite#1662]
Please:
- [X] Check for duplicate issues

- [X] Describe how to reproduce the bug /  the goal of the new feature request
This can be reproduced using the online editor. 
```json
{
  "data": {
    "values": [
      {"a": "A","b": 0.28}, {"a": "B","b": 0.55}, {"a": "C","b": 0.43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

- [X] Provide an example spec and/or screenshots (if applicable) 
As you can see, the values are parsed as millions.
![vega](https://cloud.githubusercontent.com/assets/6963729/19975729/4f463326-a1aa-11e6-9ba3-94379b00bac5.png)

**Comment by kanitw** [comment]
Hi Thanks for reporting. 

m is actually SI unit, which means milli.  We're aware of this confusion and plan to change default axis number format in 2.0 https://github.com/vega/vega-lite/issues/1539.

**Comment by kanitw** [comment]
(So i'm closing this as it's a duplicate of #1539.) :)
