### ISSUE TITLE
The new clean command leads to warning

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1667]
```
> rm -f vega-lite.* & find -E src test site -regex '.*\.(js|js.map|d.ts)' -delete & rm -rf examples/_diff examples/_original examples/_output examples/images && rm -rf data

find: unknown predicate `-E'
```

**Comment by domoritz** [comment]
I know. It's because it's not supported outside osx. http://stackoverflow.com/a/24552202/214950

**Comment by kanitw** [comment]
Why do we need to run clean in travis?

**Comment by domoritz** [comment]
We shouldn't have to so we should rather remove the call to clean than fix the command.

**Comment by domoritz** [comment]
Removed the clean in 51e3fe5
