### ISSUE TITLE
Get rid of string literal constants?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1675]
A lot of properties in Vega-Lite are string enums.  However, enums in TS are numbers, not strings.  Instead, we use string literals to define these string-based enum instead.  However, currently the way we declare types of string literals is quite an overkill:

```
export namespace AxisOrient {
    export const TOP: 'top' = 'top';
    export const RIGHT: 'right' = 'right';
    export const LEFT: 'left' = 'left';
    export const BOTTOM: 'bottom' = 'bottom';
}
export type AxisOrient = typeof AxisOrient.TOP | typeof AxisOrient.RIGHT | typeof AxisOrient.LEFT | typeof AxisOrient.BOTTOM;
```

Except for frequently used items like `Mark`, `Channel`, and `Type` (and maybe `ScaleType`), the namespace seems unnecessary.

Instead, simply do 
```
export type AxisOrient = 'top' | 'right' | 'left' | 'bottom'
```
should be sufficient. 

Thus, for all **top-level files** under `src/`, let's 

- [ ] get rid of the overkill pattern for declaring string literals described above and replace them with simple string literal type declaration (except for `Mark`, `Channel`, `Type`, and `ScaleType`)

- [ ] Update their references in the codebase with the right string values.

**Comment by domoritz** [comment]
It's true that they are not really necessary. We could easily just remove the exports of the string constants (but keep the namespace and type).

**Comment by kanitw** [comment]
- [ ] Get rid of string literal union type and namespace collision 

I think the namespace can cause confusion too.  

For example: 
```
export namespace Channel {
  export const X: 'x' = 'x';
  export const Y: 'y' = 'y';
  export const X2: 'x2' = 'x2';
  export const Y2: 'y2' = 'y2';
  export const ROW: 'row' = 'row';
  export const COLUMN: 'column' = 'column';
  export const SHAPE: 'shape' = 'shape';
  export const SIZE: 'size' = 'size';
  export const COLOR: 'color' = 'color';
  export const TEXT: 'text' = 'text';
  export const DETAIL: 'detail' = 'detail';
  export const LABEL: 'label' = 'label';
  export const PATH: 'path' = 'path';
  export const ORDER: 'order' = 'order';
  export const OPACITY: 'opacity' = 'opacity';
}
export type Channel = typeof Channel.X | typeof Channel.Y | typeof Channel.X2 | typeof Channel.Y2 | typeof Channel.ROW
  | typeof Channel.COLUMN | typeof Channel.SHAPE | typeof Channel.SIZE | typeof Channel.COLOR
  | typeof Channel.TEXT | typeof Channel.DETAIL | typeof Channel.LABEL | typeof Channel.PATH
  | typeof Channel.ORDER | typeof Channel.OPACITY;
```

This makes it unclear whether `Channel` is a type or a namespace.

**Comment by domoritz** [comment]
Just to mention the alternative, we could have a namespace `Channels` and a type `Channel`. I'm okay with only having a type.

**Comment by kanitw** [comment]
I just just further check that partly VSCODE doesn't check for type of import.  So in a way, this is not that big problem (but still reads very confusing for new joiners / contributors).
