### ISSUE TITLE
Too many `point`?  (mark, selection, scale type)

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1695]
We currently use `point` to create scatterplots in Vega-Lite (similar to Tableau and ggplot2).
However, the same thing is called `symbol` in Vega.

Since we are adding `point` selection and there is the new `point` scale, I wonder if we're using the term "point" too often. 

For these reasons, I wonder if we should rename `point` mark to `symbol`? 

(I don't have strong opinion about this -- just wanna raise a point for us to consider since this is a good time to rename if we want to do so.)

cc: @jheer @domoritz @arvind

**Comment by g3o2** [comment]
How about `dot`? `symbol` would be the same as it's vega pendant, which might lead to confusion.

**Comment by jheer** [comment]
I think we should be extremely reticent to rename anything without a strong rationale. Why introduce confusion to existing users without a good reason? I argue we should rename point/list selections (which have no user base yet) to single/multi (or similar).

**Comment by domoritz** [comment]
I'd also rather rename the selections than the mark.
