### ISSUE TITLE
Build fails in osx

### ISSUE THREAD

**Issue by stuta** [vega/vega-lite#1702]
When I run npm install and npm run build I get vega-lite.js of size 0 bytes. I could not find build instructions anywhere. 

It would be great to have prebuild versions in git.

**Comment by domoritz** [comment]
We have a released version on https://github.com/vega/vega-lite/tree/gh-pages. The current master is for vl 2.0 and we don't have builds yet. The build works on my machine and travis though. Can you provide some more details what's going wrong?
