### ISSUE TITLE
How to keep insert order for nominal field?

### ISSUE THREAD

**Issue by chuanconggao** [vega/vega-lite#1703]
Please:
- [X] Check for duplicate issues
- [X] Describe how to reproduce the bug /  the goal of the new feature request
Consider the following example:
```json
{
  "data": {
    "values": [
      {"a": "C","b": 28}, {"a": "B","b": 55}, {"a": "A","b": 43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
How can I make sure the labels on x-axis are ordered in certain order (like insert order) instead of the default alphabetical order?
- [X] Provide an example spec and/or screenshots (if applicable) 
![test](https://cloud.githubusercontent.com/assets/6963729/20253740/1d55b59e-a9e3-11e6-92e3-1519ad773db2.png)

**Comment by domoritz** [comment]
You can specify `sort: none`. See https://vega.github.io/vega-lite/docs/sort.html#ordinal-scale

```json
{
  "data": {
    "values": [
      {"a": "C","b": 28}, {"a": "B","b": 55}, {"a": "A","b": 43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "sort": "none"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

**Comment by chuanconggao** [comment]
Thanks very much for the quick reply. I missed this part in the document.
