### ISSUE TITLE
Sort by first ocurrence

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1705]
Can we sort an axis by when the first value occurs?

**Comment by kanitw** [comment]
If I remember correctly, for non-streaming data, I believe `sort: "none"` should does the trick.  ([`sort: "none"` is equivalent to `sort: undefined` in Vega](https://github.com/vega/vega-lite/blob/master/src/compile/scale.ts#L389).)
However, I think the behavior is not guaranteed for streaming data in Vega 2.  
@arvind definitely know about this better.  (Can you please confirm?)

In any case, I don't know what's the default behavior for Vega 3 + I think behavior for sort: undefined should be documented though.

**Comment by domoritz** [comment]
To clarify what I mean by first occurrence, imagine you have a dataset like 

```
a    * *     *    *   *
b         *  * *
c                   ** *
```

where x is e.g. time. 

I want to sort the groups by the first occurrence in each group. I think this should be equivalent to `sort: undefined` in vega if (and that's an important if) the data points are sorted by occurrence.

**Comment by jheer** [comment]
Sort by min(time)?

**Comment by domoritz** [comment]
Duh.

**Comment by domoritz** [comment]
```json
{
  "description": "Shows the relationship between horsepower and the numbver of cylinders using tick marks.",
  "data": {"url": "data/cars.json"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Cylinders", "type": "ordinal", "sort": {
      "op": "min",
      "field": "Horsepower"
    }}
  }
}
```

![download](https://cloud.githubusercontent.com/assets/589034/20368486/39062cce-ac22-11e6-82ab-fe79b3fe029d.png)
