### ISSUE TITLE
Inconsistency in version 1.3.1 Legend / Axis

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#1706]
The 1.3.1 schema introduced a change in ``Axis`` and ``Legend`` that makes them much harder to wrap with an API. Now rather than being objects themselves, they are ``anyOf`` definitions, where one of the options is an unnamed object containing what used to be the Axis/Legend definition. Elsewhere in the schema, the ``anyOf`` is not in the definition, but rather in the place that references the definition (see for example the ``bin`` property of ``PositionChannelDef``).

I prefer the previous way of doing things, because I think it keeps the schema cleaner. Is there a chance we can change back?

**Comment by kanitw** [comment]
I agree with @jakevdp.  Its kinda weird that it outputs this.
@domoritz I wonder if this is a bug in the schema generator for @nullable.

In any case, in the master branch, we include schema as a part of commit, so in 2.0 we will be aware of any change to the schema and be more careful with it.

Btw @jakevdp, i ping u in the vegalite slack channel to ask abt openvis submission.  Please let me know what u think. (Ull need to scroll up a bit)

**Comment by domoritz** [comment]
I agree that this is weird and the fewer oneOf we have, the better. Moreover, we should fix the version of the json-schema generator rather than using ~ or ^ because the pre 1.x versions can produce different outputs.

**Comment by domoritz** [comment]
In 1.2.0, we used to have the `oneOf` where the definition was used, rather than in the definition https://github.com/vega/vega-lite/blob/v1.2.0/vega-lite-schema.json#L171. I think this makes sense. I don't think this is fixed by just reverting the schema generator as we actually changed from `Axis | boolean` to an `@nullable` Axis. The clean fix is to change the schema generator to put the `anyOf` in the place where it used to be. I'll look into this but it's not a trivial fix.

**Comment by domoritz** [comment]
@jakevdp The issue should be fixed (pending a new release) and with 2.0 we will always commit the schema to ensure that we don't break it. Let me know if thigs are looking good.

**Comment by jakevdp** [comment]
Awesome – thanks!

**Comment by jakevdp** [comment]
Could we do a 1.3.2 or 1.4 release with this fix? I could pull from master, but it's easiest to track in Altair if we can reference a release version. I'd love to try updating the Altair wrappers incrementally as we approach 2.0. Thanks!
