### ISSUE TITLE
Default sizing of circles + Legend of Size When Zero is included

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1711]
```json
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 10},
      {"a": "B","b": 20},
      {"a": "C","b": 30},
      {"a": "D","b": 40}
    ]
  },
  "mark": "circle",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "size": {"field": "b", "type": "quantitative"}
  }
}
```
<img width="191" alt="screen shot 2016-11-22 at 21 39 21" src="https://cloud.githubusercontent.com/assets/589034/20552095/260c349a-b0fc-11e6-946f-2b16ab3c2f28.png">

Shouldn't we use a sqrt scale by default to accurately represent the values?

**Comment by kanitw** [comment]
[The size value of Vega already maps to area](https://github.com/vega/vega/wiki/Marks#symbol), so using linear scale is already correct.  

The culprit is that I didn't make the scale include zero by default and set range to start from 0.  

For now, manually overriding the scale with zero=true, range starting from zero produce reasonable output:

```js
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 10},
      {"a": "B","b": 20},
      {"a": "C","b": 30},
      {"a": "D","b": 40}
    ]
  },
  "mark": "circle",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "size": {"field": "b", "type": "quantitative", "scale": {"zero": true, "range": [0, 361]}}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20552569/3e71cef0-b101-11e6-98d1-594ecd670c7f.png)

I will change the default when I get a chance.  Maybe it's worth doing a hot fix to 1.x as well?

**Comment by domoritz** [comment]
Here is an example where it's easy to see that scale is correct. 

<img width="155" alt="screen shot 2016-11-22 at 22 21 07" src="https://cloud.githubusercontent.com/assets/589034/20552668/03c027b0-b102-11e6-9dd5-b8ad15036803.png">

We should definitely include 0 by default. Let's not backport this to 1.x as it's technically not wrong but just confusing.

**Comment by kanitw** [comment]
The default is wrong...

**Comment by kanitw** [comment]
Btw, looks like even a fix I suggested, the dumb part is that legend for "0" is pretty useless.

**Comment by domoritz** [comment]
Yeah, it's odd that 0 is in the legend. Let's address this in vl 2.0

**Comment by kanitw** [comment]
> it's odd that 0 is in the legend

@jheer @arvind  -- any idea how we can automatically get rid of 0 from the legend? 
(Seems like it should be handled as a part of Vega's legend logic?)

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/issues/404 is a related issue. 

Ideally, I think if `domain` is `[2, 10]` and `zero` = `true`, the legend should show size for 2 and 10 and some nice ticks in between and do not show 0.  :)

**Comment by kanitw** [comment]
Created an issue in Vega (https://github.com/vega/vega/issues/717).  
I don't think we can fix anything at the Vega-Lite level.
