### ISSUE TITLE
labelAlign configuration for y axis not working as expected

### ISSUE THREAD

**Issue by vinayaknamye** [vega/vega-lite#1713]
For the label align config for y-axis 
The right align option is working fine, but for left align and center align option the tick values get overlapped with the axis ticks
![left](https://cloud.githubusercontent.com/assets/3284924/20595494/1a957a44-b260-11e6-8237-d702d6fa9119.PNG)
![center](https://cloud.githubusercontent.com/assets/3284924/20595506/272f9b04-b260-11e6-9a80-46c46113dd8d.PNG)
![right](https://cloud.githubusercontent.com/assets/3284924/20595510/2c8e8aa6-b260-11e6-8008-6f28393644d7.PNG)

Also, this property is not listed in the documentation.

**Comment by kanitw** [comment]
LabelAlign is now only an axis config in Vega and should work properly.  If it doesn't please file a bug in vega-parser.
