### ISSUE TITLE
Utilizing JSON schema to populate docs

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1723]
Currently, we have both docs in the JS interface (which produces "description" in the JSON schema) and our markdown files. 

The benefit of markdown files is that we can add live examples in the docs nicely.  

The problem with this approach is that the (TS) JSDocs isn't always synced with the markdown file. 

We might want to consider other approach for 2.0. 

For example, I wanna look closer at 
https://blog.cloudflare.com/cloudflares-json-powered-documentation-generator/
(maybe it can provide a good solution for us)

**Comment by kanitw** [comment]
Actually, if there is a way for us to generate "properties tables" in our docs from the JSON schema that we can include / import to our docs easily.  (Maybe using template tricks similar to Altair could work.)

cc: @willium

**Comment by kanitw** [comment]
http://typedoc.org/ is another option.

**Comment by domoritz** [comment]
* [ ] Consider using @default properties and populating the docs from that.

**Comment by kanitw** [comment]
For static default values, I think `@default` is a great candidate. 
However, we also need to decide what to do for default rules (when something is conditional).

**Comment by kanitw** [comment]
@YuhanLu you say #2085 fixes part of this -- I guess the only part left is to use this engine with all other pages?  If so, let's have a TODO list

- [ ] aggregate.md
- [x] axis.md
- [ ] bin.md
- [ ] composition.md
- [ ] config.md
- [ ] data.md
- [ ] encoding.md
- [ ] facet.md
- [ ] label.md
- [x] legend.md
- [ ] mark.md
- [ ] overview.md
- [ ] scale.md
- [ ] size.md
- [ ] sort.md
- [ ] spec.md
- [ ] timeunit.md
- [ ] transform.md

**Comment by YuhanLu** [comment]
Those are the pages that we might need to manually update the table:
- [ ] aggregrate
