### ISSUE TITLE
Extract mark-specific config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1727]
As discussed in #1720, we should consolidate mark-specific mark config (e.g., `config.mark.barXXX,tickXXX` ) with the  mark-specific size range (e.g., `config.scale.{min/max}{Bar/Tick/Rule/Point/Text}Size`).

For example, we could have `config.bar.size` (if size is not mapped) and `config.bar.min/maxSize` (or longer `config.bar.sizeRangeMin/Max`). This will make configs way more concise.  

Plus, this way `config.mark.*`and `config.scale.*` can just serve as generic mark and scale config, while mark-specific config can be `config.<markname>.*`.  By separating this, we can also have bar use blue color by default while line use grey color by default as well.  

- [ ] ~~move mark-specific config to `config.<markname>.*`~~ (#1728)
- [x] move mark-specific scale range to `config.<markname>.*` 
- [ ] move overlay config 
- [ ] update docs

Question:
- [x] `config.bar.min/maxSize` or `config.bar.sizeRangeMin/Max` ?
  - [x]  `config.text.minSize` or `config.text.minFontSize` or `config.text.sizeRangeMin` (and max)?

cc: @domoritz @arvind

**Comment by domoritz** [comment]
* `config.bar.min/maxSize`
* `config.text.minSize`

**Comment by kanitw** [comment]
We should also 
- [ ] remove `config.overlay.line` and add `config.line.pointOverlay` where `pointOverlay` is either null or a mark config.  (This will allow users to customize the theme of the overlayed points as well.) 
- [ ] remove `config.overlay.area` and add `config.area.lineOverlay` and `config.area.pointOverlay` similar to line.

**Comment by kanitw** [comment]
- [ ] move mark config to `src/mark.ts` (similar to how scale config is in `src/scale.ts`)

**Comment by kanitw** [comment]
Forked unfinished stuff.
