### ISSUE TITLE
Compiled files include duplicate of vega-util

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1736]
Forked from #1642 

The compiled Vega-Lite files includes vega-util, which is also a part of Vega.

Users can of course manually compile vega and vega-lite together manually to avoid duplication.

I wonder if we should include this detail how to do this in the doc or offer a combined compile file to make it easier for users?  

(Not the highest priority for now, but maybe worth have junior team members doing this.)

**Comment by domoritz** [comment]
I guess we could compile a vega + vl binary.

**Comment by domoritz** [comment]
But again, I want to see a case where you get vega-util twice if you build vega + vega-lite.

**Comment by kanitw** [comment]
>  if you build vega + vega-lite.

If you build them separately and import

**Comment by kanitw** [comment]
I guess we won't get to address this.

**Comment by domoritz** [comment]
When I have some time, I can take another look at rollup.
