### ISSUE TITLE
Split Axes into grid layer and tick / label layers

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1742]
As discussed in https://github.com/vega/vega/issues/651

**Comment by kanitw** [comment]
There are two approaches to make the layer order correct

a) use `zindex`  (less restructuring in Vega-Lite).
b) restructure Vega-Lite to compile grid axes first then actual axes later. 

I'm leaning toward a).  Thoughts?)

**Comment by domoritz** [comment]
a) sounds good.

**Comment by kanitw** [comment]
Fixed in #1800
