### ISSUE TITLE
Cannot bin the same field twice

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1747]
`Uncaught Error: Duplicate signal name: Rotten_Tomatoes_Rating_extent`

**Comment by kanitw** [comment]
Oh yeah. Which specific example cause this?

**Comment by domoritz** [comment]
```json
{
  "data": {"url": "data/movies.json"},
  "mark": "circle",
  "encoding": {
    "x": {
      "bin": {"maxbins": 10},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "bin": {"maxbins": 10},
      "field": "Rotten_Tomatoes_Rating",
      "type": "quantitative"
    },
    "color": {
      "bin": {"maxbins": 10},
      "field": "Rotten_Tomatoes_Rating",
      "type": "quantitative"
    },
    "size": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    }
  }
}

```

**Comment by kanitw** [comment]
The problem is that the `parse` method in `compile/data/bin.ts` output extend using the same signal names.  

- [ ] make signal name based on `key`
  - [ ] If we do so, `key` now has two problems, making it not a valid signal name:
     - [ ] 1. Key has to be valid variable name.  Currently it calls hash which in turns call stringify.  Reimplement a way to hash `bin` as a valid signal name  (e.g.,  `maxbins_20__<params>_<value>__`)
     - [ ] 2. It has colon, which might not be a valid signal name.  To be sure, replace `'oc:' + hasDiscreteDomainOrHasLegend` with `hasDiscreteDomainOrHasLegend ? '_range' : ''` 
- [ ] update unit tests

**Comment by NeelMohapatra** [comment]
Might be a vega issue. Let's see what happens of this issue: https://github.com/vega/vega/issues/745 and then we can reopen if issue persists.
