### ISSUE TITLE
Replace Transform

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1761]
I want to be able to specify what text is shown in the legend for ordinal colors but setting the domain and range only let's me override the colors but not the labels. 

See https://github.com/altair-viz/altair/issues/278

**Comment by kanitw** [comment]
Users should simply derive a new data field and use the new field. 

That said, I see that this would be painful:

```
transform: {
    calculate: { 
       expr: "datum.name === 'tom' ? 'Thomas' : datum.name === 'dick' ? ... : ... "
       as: "fullname",  // `field:` in v1
    }
}
```

Instead of making this specific to legend, I propose that we add a `replace` transform that can be useful for all of axis label, legend label, text marks, and the future label marks.

```
transform:  {
   replace: {
      field: 'name',
      as: 'fullname',
      dict: { 'tom' : 'Thomas', 'dick' : 'Richard', ... }
   }
}
```

This would be way less painful to use than

**Comment by kanitw** [comment]
A syntax that might be more appropriate for the new transform array might be:

```
transform: [{
   replace: 'name'
   to:  { 'tom' : 'Thomas', 'dick' : 'Richard', ... }
   as: 'fullname'
}]
```

**Comment by kanitw** [comment]
The code that @sirahd add to generate sort index in https://github.com/vega/vega-lite/pull/3423 is definitely useful for this "replace" transform.

**Comment by domoritz** [comment]
Yes. Close this then?

**Comment by domoritz** [comment]
Oh, I meant close this issue and don't support replace.

**Comment by kanitw** [comment]
Why?  The current way to do replace is still super annoying.  (Write ugly chains of ternary operator)

**Comment by domoritz** [comment]
@sirahd will have a better fix with #3423 for the problem in this issue so there is no need for the replace transform for now.

**Comment by domoritz** [comment]
Never mind. I misunderstood that this issue has some other benefits besides sorting domains.

**Comment by kanitw** [comment]
> this issue has some other benefits besides sorting domains.

Yes it does ;)

**Comment by domoritz** [comment]
Cool. Somebody implement this then :-P

**Comment by kanitw** [comment]
I wonder if it would be best implemented as a function in Vega expression though so it will benefit the whole stack.

**Comment by domoritz** [comment]
I defer that question to @jheer

**Comment by kanitw** [comment]
Actually something like `{'Sat': 'Weekend', 'Sun': 'Weekend'}[day] || 'Weekday'` would be sufficient for this purpose.

**Comment by domoritz** [comment]
We use this in https://github.com/vega/vega-lite/pull/4020 😛

**Comment by domoritz** [comment]
It might be worth documenting this somewhere.

**Comment by domoritz** [comment]
Yes, you can write a calculate transform with an expression as in @kanitw's comment.
