### ISSUE TITLE
Format text without config

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1762]
I want to do

```json
{
  "data": {"values": [{"m_teps": 859}]},
  "mark": "text",
  "encoding": {
    "text": {"field": "m_teps","type": "Q", "format": "d"}
  }
}
```

But have to 

```json
{
  "data": {"values": [{"m_teps": 859}]},
  "encoding": {
    "text": {"field": "m_teps","type": "Q"}
  },
  "mark": "text",
  "config": {
    "numberFormat": "d"
  }
}
```

**Comment by kanitw** [comment]
I guess this make sense esp that we want to move toward having config as purely for a theme. 

A side note that I just observe now: the formatter is the scale for the text channel.   (Text doesn't support scale, but if you say scale = function that maps values in data domain to visual domain, then this is somewhat similar.)

**Comment by kanitw** [comment]
- [ ] Declare `TextChannelDef` interface that extends`FieldDef` with `format` property. 

- [ ] Modify `src/compile/mark/text` to read from `encoding.text.format` before reading from config. 

- [ ] Update Test
