### ISSUE TITLE
Cannot format row/col

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1763]
```json
{
  "data": {"values": [{"a": 1.01,"b": 1.01,"m_teps": 859}]},
  "encoding": {
    "column": {"axis": {"format": "d"},"field": "b","type": "O"},
    "row": {"axis": {"format": "d"},"field": "a","type": "O"},
    "text": {"field": "m_teps","type": "Q", "format": "d"}
  },
  "mark": "text"
}
```

<img width="153" alt="screen shot 2016-12-05 at 20 40 35" src="https://cloud.githubusercontent.com/assets/589034/20913274/176d92ba-bb2b-11e6-987c-b62c7351b1dc.png">

**Comment by jowens** [comment]
Any, you know, gross temporary hack you could suggest that we could make in our vl sources? 'Cause we're about to submit in a few days a paper with the following plots.

![main_pdf__page_35_of_50_](https://cloud.githubusercontent.com/assets/976970/21078065/41af12b2-bf16-11e6-9db8-4a0191984c40.png)

**Comment by domoritz** [comment]
I think the only option right now is rounding the numbers before you use them in altair. That should do the trick for your paper. 

As far as I can see there is no way to format the axis labels in a facet. Correct me if I'm wrong @kanitw @arvind.

**Comment by jowens** [comment]
Good call, thanks @domoritz. This appears to be working fairly well (for posterity):

```
def roundSig(column, significant_figures=1):
    # http://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python
    def roundSigFn(x, sig):
        return round(x, sig - int(math.floor(math.log10(x))) - 1)

    def fn(df):
        df[column] = df[column].apply(
            lambda x: roundSigFn(x, significant_figures))
        return df
    return fn
```

**Comment by jowens** [comment]
![do_ab_random_rmat_n23_e32](https://cloud.githubusercontent.com/assets/976970/21082850/e994f1c2-bf98-11e6-8c7f-868863a081b6.png)

**Comment by NeelMohapatra** [comment]
Seems to be a vega issue. Let's see what happens to this https://github.com/vega/vega/issues/745 and then we will reopen if issue persists

**Comment by domoritz** [comment]
Okay, the fact that axis labels cannot be formatted is by design (https://github.com/vega/vega/issues/745#issuecomment-283156390). Two ways forward are: format numbers before we group them, or file an issue with Vega to support. The problem with the first approach is that it doesn't work well if the same field is used for different guides. However, I'm okay with not supporting that.

**Comment by kanitw** [comment]
I think users can use calculate and Vega expression to reformat it? 

(We could throw warning that format doesn't work for ordinal scales though.)

**Comment by domoritz** [comment]
That might not work well if you use the same fields in different guides.

**Comment by kanitw** [comment]
> That might not work well if you use the same fields in different guides.

Yeah, but they can derive field a1 from a and use a1 only then they want to format?

**Comment by domoritz** [comment]
Yes.

**Comment by jowens** [comment]
Can y'all add an example of this (Vega expression to reformat) (and @jakevdp, perhaps an example of how Altair would target the necessary Vega expression)?

**Comment by domoritz** [comment]
Not pretty but here is one (note that this is vl 2)

```json
{
  "data": {"values": [{"a": 1.01,"b": 1.01,"m_teps": 859}]},
  "transform": {
    "calculate": [
      {
        "as": "fa",
        "expr": "format(datum.a, ',.1f')"
      },
      {
        "as": "fb",
        "expr": "format(datum.b, ',.1f')"
      }
    ]
  },
  "encoding": {
    "column": {"axis": {"format": "d"},"field": "fb","type": "O"},
    "row": {"axis": {"format": "d"},"field": "fa","type": "O"},
    "text": {"field": "m_teps","type": "Q", "format": "d"}
  },
  "mark": "text"
}
```

@NeelMohapatra will add a warning to vega-lite when you try to format an ordinal guide label and link to an example like the one above.

**Comment by jakevdp** [comment]
Here's the equivalent Altair command to what @domoritz wrote, I think:
```python
from altair import Chart, expr, Axis, Column, Row
data = pd.DataFrame({"a": [1.01],"b": [1.01],"m_teps": [859]})

df = expr.DataFrame(data)
df['fa'] = expr.format(df['a'], ',.1f')
df['fb'] = expr.format(df['b'], ',.1f')

Chart(df).mark_text().encode(
    Row('fa:O', axis=Axis(format='d')),
    Column('fb:O', axis=Axis(format='d')),
    text='m_teps'
)
```

**Comment by domoritz** [comment]
I corrected the specs. You cannot format the axes if they are ordinal.

**Comment by kanitw** [comment]
As of #2254, we can format the row if we use type = `quantitative`

```
{
  "data": {"values": [{"a": 1.01,"b": 1.01,"m_teps": 859}]},
  "encoding": {
    "column": {"format": "d", "field": "b","type": "quantitative"},
    "row": {"format": "d","field": "a","type": "quantitative"},
    "text": {"field": "m_teps","type": "Q", "format": "d"}
  },
  "mark": "text"
}
```

The question is whether we need to support for ordinal / nominal.  If so, how do we know whether the format is a number or time format in such cases.

**Comment by kanitw** [comment]
@NeelMohapatra We can actually allow formatting for nominal and ordinal fields. 

- [ ] Add `formatType: 'number' | 'time' | 'utc'`  to `Axis`, `Legend`, and `TextFieldDef`

- [ ] For text, tooltips and row/column headers, check if format is explicitly specified in [`formatSignalRef` in `compile/common.ts`](https://github.com/vega/vega-lite/blob/master/src/compile/common.ts#L103).  If so, apply the right format function (based on `formatType`) to the output signal.  If `formatType` is not specified, use `'number'`.

- [ ] For axis and legend, in [`compile/axis/encode.ts`](https://github.com/vega/vega-lite/blob/master/src/compile/axis/encode.ts#L15) and `compile/legend/encode.ts`, check if fieldDef.type is ordinal / nominal and if format is explicitly specified.  If so, apply the right format to labels's `text`.

Note: see links for specific lines.

**Comment by domoritz** [comment]
What's the status of this issue @NeelMohapatra?

**Comment by NeelMohapatra** [comment]
I'm working on it. Will probably be done with the PR tonight

**Comment by kanitw** [comment]
row and column no longer use axes.  Thus we might not need this anymore, at least for this specific case.

**Comment by domoritz** [comment]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 12.4,"b": 28}, {"a": 32.2,"b": 55}
    ]
  },
  "mark": "bar",
  "encoding": {
    "column": {"field": "a", "type": "quantitative", "header": {
      "format": ".2f"
    }},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

Works but I think we should be able to do this correctly even if the type is ordinal, no?

**Comment by domoritz** [comment]
I also don't think formatType works for headers.
