### ISSUE TITLE
Add a page/section about Vega-Lite (and its applications) in the media / in the wild

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1764]
For example, [this talk](https://blog.dominodatalab.com/video-huge-debate-r-vs-python-data-science/) greatly compliments Altair.

**Comment by domoritz** [comment]
I kept track of some other users, talks and blog posts in a file on my computer ;-)

**Comment by g3o2** [comment]
In the short run, it seems desirable to have such a section. Ultimately though, Vega-Lite's success will depend on the quality of the [applications](https://vega.github.io/vega-lite/usage/applications.html) and [examples](https://vega.github.io/vega-lite/examples/) pages, not on awards and press coverage.

BTW what does the name `Vega` stand for precisely ? That explanation would certainly deserve a front page exposure.

**Comment by jheer** [comment]
Totally agree with @g3o2.

The Vega name has multiple influences. First, "vg" -> "Visualization grammar". Second, use of the star "Vega" is an homage to the original Stanford Polaris project that led to Tableau. Polaris is currently the northern pole star but in ~10000 years Vega will be the pole star.  So it is a bit tongue-in-cheek, too :)

**Comment by kanitw** [comment]
> First, "vg" -> "Visualization grammar". 

Looks like using `vega` as the namespace for Vega 3 API is losing this part a bit, but yeah we probably wanna distinguish legacy Vega APIs and newer ones :p. 

In a way, vl could be visualization language too I guess :p
