### ISSUE TITLE
Add a Unit Test to test if the vega-lite-schema.json is up to date

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1773]
## Problem 

Currently, we use `npm run schema` to create a JSON schema and include the output `vega-lite-schema.json` in our commits. This allows us to make sure that we don't accidentally introduce schema changes. However, sometimes we forget to run the command to update the schema when we update our syntax in the code. Meanwhile, our test (and Travis) do not fail if we forget to do so.  

## Solution

We should add a test in Travis that throws an error when `vega-lite-schema.json` is out-of-date. The schema is out of date when `npm run schema` creates a new schema that is different that the committed one.  

To implement this add a test that runs `npm run schema` and checks whether git status says that there have been changes to `vega-lite-schema.json`. Make sure that travis tests fail in that case.

**Comment by domoritz** [comment]
Can you explain this issue again? I don't understand it.

**Comment by kanitw** [comment]
@domoritz Ok updated the description above.   
@YuhanLu I think this one has lower priority compared to other issues assigned to you.
