### ISSUE TITLE
Convert to HTML in Node project

### ISSUE THREAD

**Issue by geekplux** [vega/vega-lite#1797]
any way to convert vega-lite spec to HTML directly? 
I've Google it, searched in issues and checked the test folder, but not found..

I see vega-lite spec could convert to vega spec in the bin/vl2vg, but meet some error (vega/vega#697, vega/vega#698).

Happy New Year! 🤗

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite-demo has some instructions for embedding Vega-Lite on the web. Right now we only have exporters for raster and vector images from Vega but the new editor may add support for exporting HTML pages. 

Closing this as it is a [vega editor](https://github.com/vega/vega-editor) issue.

**Comment by geekplux** [comment]
thanks! I'll try to use https://github.com/tmpvar/jsdom
