### ISSUE TITLE
Incorrect Positioning for Vertical Point scales

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1807]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/21831523/42f1a44a-d759-11e6-98d3-f81aa1682205.png)

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/21831541/5de3cbc0-d759-11e6-942d-f5cff3a3d7f2.png)

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/21831570/887e5d3c-d759-11e6-976d-a46a3bf6d213.png)

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/21831583/9bb61278-d759-11e6-8f1d-e0532d5fd432.png)

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/21831603/bf5a6742-d759-11e6-9502-24ad7869d7f2.png)

**Comment by domoritz** [comment]
Do you mean the horizontal scale?

**Comment by kanitw** [comment]
Umm, no I really mean vertical scale / axis.

Compared to Vega 2 , Vega-Lite 1, the y-axis is not "floating" like it is now:

![vega_editor](https://cloud.githubusercontent.com/assets/111269/21832089/63c806d8-d75d-11e6-8ff8-651f95135225.png)

Currently I have no idea what's wrong in these Vega-Lite's Vega outputs.  (Wondering if this is a Vega bug, but not sure yet.  Maybe it's related to changes in plot positioning in Vega 3.)

For reference, here is [a Vega output](http://pastebin.com/9Xtfa600) for the aggregate bar chart above.

cc: @jheer @arvind

**Comment by kanitw** [comment]
(Maybe it's a problem in Vega -- see https://github.com/vega/vega/issues/706)

**Comment by kanitw** [comment]
Fixed in #1812
