### ISSUE TITLE
Use cdnjs to the vega-lite usage docs and tutorial page

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#1809]
Instead of using files from vega, vega-lite and d3, we should pull files from cndjs.

```
<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="//vega.github.io/vega/vega.js" charset="utf-8"></script>
<script src="//vega.github.io/vega-lite/vega-lite.js" charset="utf-8"></script>
<script src="//vega.github.io/vega-editor/vendor/vega-embed.js" charset="utf-8"></script>
```

And since links from cndjs include version name, we should also have the version info in some file for easy update. 

- [ ] Tutorial page 
- [ ] Usage page
- [ ] others
- [ ] version file

**Comment by domoritz** [comment]
Related https://github.com/vega/vega-lite/issues/1529

**Comment by kanitw** [comment]
Is this assigned to @YuhanLu? If so, can you mark the assignee?

**Comment by domoritz** [comment]
To get the version of a package: `npm info vega version`.

**Comment by kanitw** [comment]
If I remember correctly, we have to deal with beta releases not showing up?

**Comment by domoritz** [comment]
"Beta, release candidate and alpha releases are not usually considered ready for full production status. Requests for pre-release versions of libraries may be declined after peer review." From https://github.com/cdnjs/cdnjs

So we can make a request.

**Comment by domoritz** [comment]
https://cdnjs.com/libraries/vega-lite https://cdnjs.com/libraries/vega

**Comment by sirahd** [comment]
-use cdnjs on example page, but link to the version that corresponds to current vega and vega-lite. 
-remove Vega-lite inside `<script>` for example page, use the one in `test-gallery/main.ts` 
-search for all files that contain url vega.github.io and replace with the link to cdnjs with the current version
