### ISSUE TITLE
Fix JSON formatting in Vega output

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#1811]
This is a very minor issue, but it nevertheless trips me up when I'm reading JSON generated by Vega-Lite: why does the Vega JSON generated by Vega-Lite drop spaces between object attributes? The current scheme causes visual grouping of unrelated things.

Instead of this: `{"type": "filter","expr": "datum.year == 2000"}`
I would expect output like this:  `{"type": "filter", "expr": "datum.year == 2000"}`

**Comment by domoritz** [comment]
Vega-Lite only returns javascript objects. I believe the bug is in the compact stringify in the editor in https://github.com/vega/vega-editor/blob/dom/vg3/lib/json3-compactstringify.js.

**Comment by kanitw** [comment]
Close and filed in vega-editor https://github.com/vega/vega-editor/issues/78

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/editor/pull/38

**Comment by domoritz** [comment]
We now use json-stringify-pretty-compact in the editor at https://vega.github.io/editor/.
