### ISSUE TITLE
Remove unnecessary "as"

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1820]
Looks like with Typescript 2.1, we should remove unnecessary "as" from our codebase. 

- [ ] `{} as Dict <T>`
- [ ] `as any`
- [ ] Also remove explicit `: any` if possible.

**Comment by kanitw** [comment]
@dbautistav – If I remember correctly, I think I have already fixed this but still have some occurrences of these left behind as we can't remove some of them. 

That said, feel free to check if there are some other places that we can still remove this.  Thanks!

**Comment by dbautistav** [comment]
Ok. Thank you!
