### ISSUE TITLE
Add Channels for fill/stroke related stuff 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1821]
Forked from #1278 

- [ ] Fill / Stroke / FillOpacity / StrokeOpacity
   - These properties should have higher precedence over `color` channel.  For example, for a filled mark, `fill` should override `color` while `fillOpacity` should override `opacity`. 

- [ ] filled (affect whether color is applied to `fill` or to `stroke`)
- [ ] strokeWidth
- [ ] StrokeDash, StrokeDashOffset

**Comment by kanitw** [comment]
Need to resolve our conversation in https://github.com/vega/vega/issues/711 before we proceed.

**Comment by g3o2** [comment]
I would agree with the overriding nature of such specific properties. Would it be possible to specify both overriding properties `fill` and `stroke` instead of `color` ?

As specified in my second comment in vega/vega#711, one should probably think about employing a more gentle naming convention in `vega-lite` for those properties or encoding channels. `vega-lite` users are not necessarily familiar with `svg`. My suggestion was e.g. `fillColor` instead of `fill` and `strokeColor` instead of `stroke`.

**Comment by kanitw** [comment]
@g3o2 Thanks for your comments. 

> I would agree with the overriding nature of such specific properties. Would it also be possible to specify both overriding properties fill and stroke instead of color ?

Yes.  

> Maybe it is a good idea to add only a few of those properties that you have mentioned, namely those which are likely to be frequently used. Later on, one can still add the others ...

That's what we did with v1, but the feedback we got are like why don't you have this and that encoding channels and the reasons are simply we haven't implemented them.  There is no good way to determine when is a good time to add this "later on" and I'd say that that time is now.  Adding relevant encoding channels all at once are way easier to do than slowly adding one by one.  

> As specified in my second comment in vega/vega#711, one should probably also think about employing a more telling naming convention in vega-lite for those properties or encoding channels, as has already been done for many other properties.

We will not rename `fill` to `fillColor` since they have exactly the same functionality as in Vega.   I'd argue that it's actually more complicated to explain that way.   We certainly do not want to explain why it's `fill` in Vega but `fillColor` in Vega-Lite. . After all, it's not that hard to learn that values of `fill` and `stroke` are colors.

**Comment by g3o2** [comment]
I understand the consistency objective. Though, in that light, the existence of the `color` channel in vega-lite is even more surprising. It will be more complicated to explain the coexistence of `color`, `fill` and `stroke`, in particular the overriding character of the two latter.

**Comment by kanitw** [comment]
@g3o2  I appreciate your comment.  However, we will stick with `color`, `fill`, and `stroke`. 

As explained, the addition of `color` means we have to explain how `color` works and interacts with `fill` and `stroke` but doesn't mean we have to introduce new names for  `fill` and `stroke`, which require extra explanation about the different names.

**Comment by kanitw** [comment]
For now, we gonna just add `strokeDash` as channel (https://github.com/vega/vega-lite/issues/1855) and leave other properties in config.
