### ISSUE TITLE
More specific FieldDef interface

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1826]
Just a thought. 
Consider splitting `FieldDef` into:

```
type ChannelDef = FieldDef & ValueDef
```
(Need to check with @domoritz if & is supported by the JSON schema generator. 

Note that more precise definition would be:

```
type ChannelDef = FieldDef | ValueDef
```
However, it will require too much type checking downstream and will become annoying. 

(This will make type more solid, but require some more refactoring of channelDefs.)

**Comment by domoritz** [comment]
Type intersections are supported so you can do `FieldDef & ValueDef`. 

Why is `FieldDef | ValueDef` annoying? I believe it should just work.

**Comment by kanitw** [comment]
I think we always have to check if a `ChannelDef` is a `FieldDef` or `ValueDef` otherwise, we can't call `channelDef.field` or `channelDef.value`.

**Comment by kanitw** [comment]
I think we always have to check if a `ChannelDef` is a `FieldDef` or `ValueDef` otherwise, we can't call `channelDef.field` or `channelDef.value`.     Not 100% sure though -- need to try.

**Comment by domoritz** [comment]
I think if you have something like this ts can figure things out. 

```ts
if (channelDef.field) {
  // we know it's a fieldDef
} else {
  // we know if's a value def
}
```
