### ISSUE TITLE
Combine legends based on the same underlying variables into a single legend

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1844]
For example, if we over-encode both size and color with the same variables, this should create one legend, rather than two.

I'm creating this to replace #821 to start a clean slate.  (The old #821 contains workaround while we haven't fixed this problem though.)

**Comment by NeelMohapatra** [comment]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "b", "type": "quantitative"},
    "size": {"field": "b", "type": "quantitative"}
  }
}
```
generates 
<img width="972" alt="screen shot 2017-05-04 at 4 17 09 pm" src="https://cloud.githubusercontent.com/assets/12771661/25728636/2c887810-30e5-11e7-9069-41181aa9f6bb.png">
Also `scatter_colored_with_shape.vl.json`

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2567

**Comment by jowens** [comment]
I ran into this issue again today. VL json (generated from Altair): https://gist.github.com/jowens/4bdaad3fc4e12c7be9444fd00bd1458f

This is a little more complex than the first time I brought this up because it's got both a point marking and an errorband, but still, I think it should generate only one legend.

Will politely reopen this issue.

![perf-var-analysis_perf-var-analysis_errorband](https://user-images.githubusercontent.com/976970/75632810-97f6db80-5bb4-11ea-8351-2d71c300ec2c.png)

**Comment by domoritz** [comment]
Is this a case of https://github.com/vega/vega-lite/issues/5695 or https://github.com/vega/vega-lite/issues/5543

**Comment by jowens** [comment]
There's no sort, so it's not https://github.com/vega/vega-lite/issues/5695 .

It doesn't seem like it's https://github.com/vega/vega-lite/issues/5543 either. That one has separate `color` entries within the two `line`/`point` encodings, whereas my JSON has one `color`/`shape` entry that is in a separate encoding. That being said, my JSON does have separate `color` and `shape` encodings; I'm not sure where those are combined into one (Altair, VL, or vega).

**Comment by domoritz** [comment]
Okay, I created a new issue https://github.com/vega/vega-lite/issues/5996 to consolidate related issues since I have not had time to investigate what the underlying issue is.

**Comment by marc-precisionlife** [comment]
FYI, seems a valid workaround for this is explicitly specifying the domain on the encodings so seems to be related, modifying your gist with:
```
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "schedule",
      "legend": {"title": "Schedule"},
      "scale": {"scheme": "dark2",
            "domain":[
              "cublas",
              "stream-kxmxn",
            ]
          }
    },
    "shape": {
      "type": "nominal",
      "field": "schedule",
      "legend": {"title": "Schedule"},
      "scale": {
        "domain":[
          "cublas",
          "stream-kxmxn",
        ]
      }
    }
  },
```
gives

![Image](https://github.com/user-attachments/assets/6bede525-acb8-46e6-9f59-394ace125989)
