### ISSUE TITLE
Audit Vega-Lite Axis/Legend Config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1845]
# Distinguish Between Config and Properties of Axis/Legend

## Axis 

- [x] Axis 

Right now `Axis` extends `AxisConfig`.  However some property such as `axisColor` only make sense as a theme (you won't make one axis red and another black.   Thus, we should distinguish the two and properties such as `axisColor` should be `AxisConfig`.

- [x] If there are shared properties between them, then we want  `Axis` and `AxisConfig` extend common `AxisBase`.

- [x] Modify the axis compile code to only deal with what's in `Axis`  (`_initAxis` in `UnitModel` and `FacetModel`)

- [x] We have a code to copy all config values to actual axis object. However, we should not copy *all* config properties anymore since `Axis` and `AxisConfig` are not the same.
   - [x] We need to think what are the few that we need to copy and how
       - [x] labelMaxLength

- [x] update all docs

- [x] make sure we don't left any property undecided

## Legend

- [x] Do it similar to axis

# 2. Make sure our configs match with Vega

I think Vega-Lite config for each of scale/axis/legend can either be (1) exactly the same as Vega's or (2) has a few more properties.   (It shouldn't have fewer properties.)

- [x] If there are properties missing from VL -- add them.

- [x] If there are properties in VL that are not in VG, check if they are renamed in VG.

- [x] Make new interface `VgAxisConfig` and make `AxisConfig implements VgAxisConfig` (or define `type AxisConfig = VgAxisConfig` if there is no additional properties)

- [x] Update examples in examples/spec accordingly

**Comment by kanitw** [comment]
- [ ] @YuhanLu  looks like we still have `domainWidth` in `defaultFacetAxisConfig`.  Could you please check if we really need it.  (Does it matter to remove it?)  If not, remove it and we can remove `defaultFacetAxisConfig` entirely.

**Comment by kanitw** [comment]
@YuhanLu 

From recent changes in https://github.com/vega/vega/pull/748, 
we can just remove `labelMaxLength` and add `labelLimit`, `textLimit` to config :)

**Comment by g3o2** [comment]
> some property such as axisColor only make sense as a theme (you won't make one axis red and another black.)

Why not just keep the flexibility ?

**Comment by kanitw** [comment]
> Why not just keep the flexibility ?

More redundant code to maintain (we now rely on Vega-parser to produce these colors) and more documentation for a feature that simply leads to bad design in most cases.

**Comment by kanitw** [comment]
@YuhanLu is there any unfinished item leave in this issue?

**Comment by kanitw** [comment]
@YuhanLu  Looks like this part is done.   If I'm wrong, please re-open this issue.
