### ISSUE TITLE
Links Broken in Documentation

### ISSUE THREAD

**Issue by NeelMohapatra** [vega/vega-lite#1852]
Links not working.
![screen shot 2017-01-18 at 9 53 57 am](https://cloud.githubusercontent.com/assets/12771661/22076226/12d7704e-dd64-11e6-8aa0-33296df17ffc.png)
https://vega.github.io/data/seattle-weather.csv
https://vega.github.io/vega-lite/examples/gallery.html
For the last link, jekyll is generating the link as `/examples/gallery.html` instead of just `/examples`.

**Comment by domoritz** [comment]
Would you have time to look into these?

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/1856
