### ISSUE TITLE
Domain of index scale for ordinal color should not be sorted

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1857]
```json
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"},
      {"a": "B","b": 55, "c": "small"},
      {"a": "C","b": 43, "c": "x-large"},
      {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal"}
  }
}
```

wrong
<img width="204" alt="screen shot 2017-01-18 at 23 05 48" src="https://cloud.githubusercontent.com/assets/589034/22096864/bb5ea552-ddd2-11e6-8ecb-ba8c283b5fcd.png">

correct
<img width="206" alt="screen shot 2017-01-18 at 23 06 11" src="https://cloud.githubusercontent.com/assets/589034/22096869/c4fed14a-ddd2-11e6-8d33-54b4ea11a9d8.png">

This was correct as of #1746

**Comment by domoritz** [comment]
Hmm, technically the mapping is still correct. Maybe we have to ask users to disable sorting explicitly for this case. 

```json
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"},
      {"a": "B","b": 55, "c": "small"},
      {"a": "C","b": 43, "c": "x-large"},
      {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal", "sort": false}
  }
}
```

**Comment by kanitw** [comment]
Your "correct" figure is also *not* correct.  "x-large" is larger than "large". 

The only way to make ordinal field have correct order (unless they are alphabetically ordered) is to specify it and we should throw a warning for that (See https://github.com/vega/vega-lite/issues/1725).
