### ISSUE TITLE
Broken link in documentation : https://vega.github.io/vega-lite/gallery.html#trellis-plots

### ISSUE THREAD

**Issue by owendall** [vega/vega-lite#1859]
https://vega.github.io/vega-lite/gallery.html#trellis-plots

on page:

https://vega.github.io/vega-lite/docs/facet.html

![image](https://cloud.githubusercontent.com/assets/10927/22111776/907983a0-de2e-11e6-8180-39822202dfce.png)

**Comment by owendall** [comment]
Also, link for "Open in Vega Editor"  just loads the default page, not this particular example.

**Comment by kanitw** [comment]
Thanks for the report!

**Comment by NeelMohapatra** [comment]
I thought we fixed it in #1852
