### ISSUE TITLE
MariMekko Chart

### ISSUE THREAD

**Issue by amitkaps** [vega/vega-lite#1871]
Is it possible to make a MariMekko Chart - Mark (area) for two categorical variables. Here is an example - http://narrativeviz.com/showcase/devices/

I know you guys are busy in the 2.0 release, but it would be good to have an easy way to create this. I am happy to help if you can point me in the right direction.

**Comment by kanitw** [comment]
This would require a layout transform in Vega for it and then we need to think about how to surface these layout transforms in Vega-Lite (https://github.com/vega/vega-lite/issues/1872).  

I'd close this as I consider it's a part of broader layout support issue (https://github.com/vega/vega-lite/issues/1872).   If you want to request for a layout support, please file a separate issue in the Vega repo.
