### ISSUE TITLE
Try typescript interface generator

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1873]
See https://github.com/vega/vega-lite/issues/1843

Try different typescript schema generators. We have had to put a lot of effort into manually curating the typings. 

To try:
- https://www.npmjs.com/package/json-schema-to-typescript
- json2ts.com/

(If these don't work, google for more!)

**Comment by kanitw** [comment]
Not sure why you have to create a new issue lol

**Comment by domoritz** [comment]
Because adding missing interfaces (the safe option) and an experiment to try a generator are two different things.

**Comment by kanitw** [comment]
I would say that let's Zoe take care of this as a part of #1843, so less overlapping responsibilities.
