### ISSUE TITLE
Example: Group Bar

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1878]
This could a facet of hconcat (as described in https://github.com/vega/voyager2/issues/256)

**Comment by domoritz** [comment]
Why is this not https://vega.github.io/vega-editor/?mode=vega-lite&spec=bar_grouped? Is it because we look at different fields?

**Comment by kanitw** [comment]
Yes

**Comment by kanitw** [comment]
Part of https://github.com/vega/vega-lite/issues/1486
