### ISSUE TITLE
sort: none seems not to work with numeric values in ordinal scale

### ISSUE THREAD

**Issue by mojaie** [vega/vega-lite#1886]
sort: none seems not to work with numeric values in ordinal scale.

Example:

```
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "1","b": 28},
      {"a": "2","b": 55},
      {"a": "C","b": 43},
      {"a": "3","b": 91},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "E","b": 81},
      {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a","type": "ordinal", "sort": "none"},
    "y": {"field": "b","type": "quantitative"}
  }
}
```

Results from http://vega.github.io/vega-editor/?mode=vega-lite

![1](https://cloud.githubusercontent.com/assets/1174134/22280989/8f94fc42-e317-11e6-8684-c9b36a152e0a.png)

**Comment by domoritz** [comment]
This seems to be a Vega issue. We don't output scale sorting. And even if I set sort to false, the order is not quite correct. 

However, this works correctly in master with Vega-Lite 2 and Vega 3.

**Comment by mojaie** [comment]
Thank you for your quick reply.
Adding some text(or space) prefix to the values works enough for me now.
I'm looking forward to new Vega and Vega-Lite release.

**Comment by domoritz** [comment]
If you want a particular order, I recommend that you add a field you want to sort by. Usually, it's difficult to rely on the input order because Vega is reactive.

**Comment by kanitw** [comment]
> add a field you want to sort by

or manually provide `scale: {domain: ["1", "2", C"...]}` :)

**Comment by mojaie** [comment]
scale: domain looks elegant.
Thank you very much for your suggestions.
