### ISSUE TITLE
Usage of domainRaw

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#1889]
Not sure about how `domainRaw` works for scale in vega/vega-lite.

**Comment by domoritz** [comment]
The idea is that we use the unaggregated data to drive the domain of a scale. this can be helpful if you want to compare two charts -- one with unaggregated data and one with means -- because the axes will be aligned.

**Comment by kanitw** [comment]
> The idea is that we use the unaggregated data to drive the domain of a scale. this can be helpful if you want to compare two charts -- one with unaggregated data and one with means -- because the axes will be aligned.

This describe `useRawDomain`, a special property in Vega-Lite, rather than the new `domainRaw` in Vega 3. Note that we should consider renaming `useRawDomain` to better describe what it does #1656 (especially now that we have another confusing property). 

I think @jheer replied to me about `domainRaw` on slack, but I can't remember and can't find it in slack history -- maybe it's older than 10000 messages.  So I'll let him reply here.  (Sorry Jeff!)

**Comment by domoritz** [comment]
Ups. I should not post after midnight. Sorry about the confusion.

**Comment by arvind** [comment]
`domainRaw` was introduced to simplify interactive recalculation for scale domains ([see this diff](https://github.com/vega/vega/commit/bd628515c970f8331dd4c06a3402ce44e40f915b)). When a raw domain is specified, it is used directly as a scale's domain, circumventing any DataRef calculations as well as the `zero` and `nice` settings. Thus, we can have a scale domain be initialized, and then subsequently overridden by interactions. 

I don't think we should expose `domainRaw` within Vega-Lite, but we do use it internally in the selections compiler.

**Comment by jheer** [comment]
Be careful about a terminology collision here!
- `domainRaw` in Vega 3 is an override for the scale domain.
- In Vega-Lite, "raw" domains refer to domains computed over un-aggregated data to enable stable axis ranges for comparisons across charts (as in Voyager).

**Comment by kanitw** [comment]
@jheer  I think after @domoritz  refactor all the transform pipeline, we might revise the name of `useRawDomain` in Vega-Lite.  

I'm closing this for now and there is no follow TODO.
