### ISSUE TITLE
Scale config is being ignored

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1894]
In https://github.com/vega/vega-lite/pull/1876, we discovered, that the bar_1d_rangestep_config does not work correctly because the config is ignored.

**Comment by kanitw** [comment]
Just got a chance to look closely, I  found that my code reads the [value normally](https://github.com/vega/vega-lite/blob/master/src/compile/scale/range.ts#L82) and it's also working in the editor.

![vega_editor](https://cloud.githubusercontent.com/assets/111269/22322725/e050bb5e-e352-11e6-95ae-aba4a2179457.png)


This is not an ideal way to change height of a 1D bar though, so I think we should just support modifying `height` for this (https://github.com/vega/vega-lite/issues/1288).
