### ISSUE TITLE
npmignore doesn't work

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1913]
Just installed vl with npm

<img width="252" alt="screen shot 2017-02-03 at 11 00 56" src="https://cloud.githubusercontent.com/assets/589034/22604362/19125296-ea00-11e6-9309-805d4b5d95f8.png">

**Comment by kanitw** [comment]
Hmm interesting ...

**Comment by domoritz** [comment]
You can try this by running the following: `npm view vega-lite dist.tarball`.

**Comment by ydlamba** [comment]
Is this an issue anymore? Because when I tried `npm view vega-lite dist.tarball` or `npm pack` it's perfectly ignoring specified files/directories.

**Comment by domoritz** [comment]
Yeah, I fixed that a while ago but forgot to close the issue.
