### ISSUE TITLE
why does a line plot have such a weird order for connecting the lines?

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#1916]
Running the following in the vega-lite editor at https://vega.github.io/vega-editor/?mode=vega-lite

The dates are sorted in ascending order. I would expect the three y datapoints would be connected by a line from the 2009 date to the 2012 date, then to the 2016 date. Oddly, no. What am I doing wrong?

```
{
  "mark": "line",
  "data": {
    "values": [
      {"date": "2009-06-22","y": "482"},
      {"date": "2012-06-13","y": "1403"},
      {"date": "2016-12-10","y": "2534"}
    ]
  },
  "encoding": {
    "y": {
      "field": "y",
      "scale": {"type": "log"},
      "type": "nominal",
      "axis": {"title": "Y"}
    },
    "x": {
      "field": "date",
      "type": "temporal",
      "axis": {"title": "Date"}
    }
  }
}
```

<img width="268" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/976970/22616350/586c1944-ea60-11e6-8fda-e14c7c5e6533.png">

**Comment by jheer** [comment]
Weird! I noticed the Y-axis was upside down, which then led me to notice that the `y` encoding channel has a data type of `"nominal"`. If I change that to `"quantitative"` the chart becomes well-behaved.

**Comment by jowens** [comment]
And here I was trusting Altair to make perfect guesses as to what I really meant by data types. Learned my lesson!

**Comment by kanitw** [comment]
cc: @jakevdp

**Comment by jakevdp** [comment]
It appears the values are strings. If you pass strings to Altair, it will always use nominal types unless otherwise specified. I suppose we could check whether the strings contain valid integers/floats and silently convert them, but to me that seems like it's assuming too much.

**Comment by jowens** [comment]
@jakevdp, you're right, certainly passing in strings is not what I ought to be doing. Might be worth a warning though ... "did you really mean to pass in strings not numbers"?
