### ISSUE TITLE
Add Tooltip Channel & Update vega-lite-tooltip

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1921]
`tooltip` channel is added in [Vega 3 beta 18](https://github.com/vega/vega/releases/tag/v3.0.0-beta.18) and can be helpful for Vega-Lite.

**Comment by kanitw** [comment]
Done in https://github.com/vega/vega-lite/pull/2132 with great help from @doug! :)

**Comment by g3o2** [comment]
Unfortunately, the spec shown here above does not work with the current implementation (vega-lite 2.0.0-beta.2 and vega 3.0.0-beta.30).

**Comment by domoritz** [comment]
It works if you set the type to ordinal

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": 52}
    ]
  },
  "transform": [
    {
      "calculate": "datum.a + ', ' + datum.b",
      "as": "tooltip"
    }
  ],
  "mark": "bar",
  "encoding": {
    "x": {"field": "a","type": "ordinal"},
    "y": {"field": "b","type": "quantitative"},
    "tooltip": {"field": "tooltip", "type": "ordinal"}
  }
}
```

Vega-Lite should automatically do that!

**Comment by g3o2** [comment]
Thanks, so what's left is that `tooltip` does not appear to work in all cases, such with the `line` mark here below. Replace `line` by `bar` or `point` and the tooltip is shown. With `area`, tooltip does not seem to work either.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "grouped lines",
  "width": 300,
  "data": {
    "values": [
      {"year": 2012, "cat" : "orig", "val": 90}, {"year": 2012, "cat" : "adj", "val": 110},
      {"year": 2013, "cat" : "orig", "val": 70}, {"year": 2013, "cat" : "adj", "val": 100},
      {"year": 2014, "cat" : "orig", "val": 130}, {"year": 2014, "cat" : "adj", "val": 105},
      {"year": 2015, "cat" : "orig", "val": 180}, {"year": 2015, "cat" : "adj", "val": 120}
    ]
  },
  "transform": [
    { 
      "calculate": "datum.val + ' (' + datum.year + ' ' + datum.cat + ')'",
      "as": "mytooltip"
    }
  ],
  "mark": "line",
  "encoding": {
    "x": {"field": "year", "type": "temporal", "timeUnit": "year"},
    "y": { "field": "val", "type": "quantitative" },
    "color": { "field": "cat", "type": "nominal" },
    "tooltip": { "field": "mytooltip", "type": "ordinal" }
  }
}
```

**Comment by domoritz** [comment]
I believe the problem is that tooltips work per mark and line and area are a single mark.The tooltips work for lines but you cannot use it for individual points on that line.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Stock prices of 5 Tech Companies Over Time.",
  "data": {"url": "data/stocks.csv", "format": {"type": "csv"}},
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
    "y": {"field": "price", "type": "quantitative"},
    "color": {"field": "symbol", "type": "nominal"},
    "tooltip": {"field": "symbol", "type": "ordinal"}
  }
}
```

<img width="323" alt="screen shot 2017-05-02 at 08 51 11" src="https://cloud.githubusercontent.com/assets/589034/25626547/b7196a98-2f14-11e7-9e95-e31ee58e77ff.png">

You can make it work by adding a layer of (transparent) points with the tooltip. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Stock prices of 5 Tech Companies Over Time.",
  "data": {"url": "data/stocks.csv","format": {"type": "csv"}},
  "transform": [
    {
      "calculate": "datum.symbol + ' ' + datum.price",
      "as": "mytooltip"
    }
  ],
  "layer": [
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal",
          "axis": {"format": "%Y"}
        },
        "y": {"field": "price","type": "quantitative"},
        "color": {"field": "symbol","type": "nominal"}
      }
    },
    {
      "mark": "point",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal"
        },
        "y": {"field": "price","type": "quantitative"},
        "color": {"value": "transparent"},
        "tooltip": {"field": "mytooltip","type": "ordinal"}
      }
    }
  ]
}
```

<img width="324" alt="screen shot 2017-05-02 at 08 54 09" src="https://cloud.githubusercontent.com/assets/589034/25626663/19c260be-2f15-11e7-904e-f213475cc32e.png">

This is definitely not ideal. I wonder whether Vega-Lite should just automatically do this rewrite so that tooltips just work for lines.

**Comment by domoritz** [comment]
I created an issue at https://github.com/vega/vega-lite/issues/2341. @doug, @g3o2 if you can send us a pull request for this, that would be awesome. I think the best place for this rewrite is in `normalize` in https://github.com/vega/vega-lite/blob/master/src/spec.ts#L200.

**Comment by kanitw** [comment]
As mentioned in #2341, I think this proposal for adding transparent point still cause other usability issues so I don't think it should be added to Vega-Lite.
