### ISSUE TITLE
Responsive Ordinal Scale (Ordinal Fit Mode)

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#194]
Currently  `config.cell.width`, `config.cell.height`  are ignored for x and y if they ordinal scales respectively.  
Basically, the cell width and height of an ordinal scale is determined by the `band size * cardinality`.   

- [ ] ~~Let's add `config.unit.fitOrdinalScale` as boolean to make the ordinal scale rely on the `config.unit.width/height` value instead of bandWidth.~~  See below
- [ ] Need to deal make the scale work with all mark type.  
- [ ] corner case when the cardinality of the ordinal field is too high
- [ ] Of course, add tests.

**Comment by vivekratnavel** [comment]
I am facing this issue.

```
{
  "marktype": "bar",
  "encoding": {
    "x": {"name": "Aircraft__Make_Model","type": "N"},
    "y": {"name": "*","type": "Q","aggregate": "count"}
  },
  "config": {"singleHeight": 400,"singleWidth": 400,"largeBandMaxCardinality": 20},
  "data": {"url": "data/birdstrikes.json"}
}
```

This visualization is displayed with a scrollbar. Is there any hack for now to control the width?

**Comment by kanitw** [comment]
For non-band scale, you can adjust `config.singleHeight` or `config.singleWidth`.
For band scale (e.g., `x`), you can adjust band size.   For example 

`encoding.x` = `{"name": "Aircraft__Make_Model","type": "N", "band":{"size": <BAND_SIZE>}}`

We will write better docs once we are closer 1.0.  In the meantime, please take a look at `src/schema/schema.js` to search for properties you want ;)

**Comment by kanitw** [comment]
`config.unit.fitOrdinalScale` sounds confusing.  

One possible way to make a readable syntax is the allow `scale.bandWidth` to be `"fit"` besides number.  

@domoritz  thoughts?

**Comment by domoritz** [comment]
`scale.bandWidth` with `fit` sounds much better.

**Comment by kanitw** [comment]
Earlier, we planned to allow `scale.bandWidth` to be `"fit"` to support ordinal scale fit. 

Here I'm extending my thinking to #1421 (support `width` and `height` at the top-level).  

1) If top-level `width` is provided, always use it (fit ordinal scale to `width` no matter `scale.bandWidth` is explicitly specified or not.)
2) If top-level `width` is not provided:
-  For non-ordinal scale always use `config.cell.width`.
-  For ordinal scale:
  - If `scale.bandWidth` is not `"fit"`, use `bandSize * cardinality`.  
  - If `scale.bandWidth` is `"fit"`, use `config.cell.width` and fit the scale.  

(Same logic for `height`)

@domoritz

**Comment by kanitw** [comment]
(Just clarified the comment above after conversation with @arvind, who agrees with the proposal.)

**Comment by kanitw** [comment]
Done in #1214, pending docs revisions and should be ready for merging.

**Comment by devgru** [comment]
Looks like in vega-lite 2.0.1 this feature is removed?

**Comment by domoritz** [comment]
It's been improved. Docs are at https://vega.github.io/vega-lite/docs/size.html.

**Comment by kanitw** [comment]
It is now called rangeStep, which is a bit more precise name.

**Comment by kanitw** [comment]
Basically, bandwidth supposes to be a fraction of range step. See https://vega.github.io/vega-lite/docs/scale.html#band for illustration.
