### ISSUE TITLE
Facet child config should not inherit from parent

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#1950]
For example, when we set `config: {"facet": {"axis": {"labelMaxLength": 123}}}`, child config should not inheritance from parent.

**Comment by kanitw** [comment]
Can you be more descriptive?  For example, give your input spec and describe what's wrong with output spec.  (Even though it's likely you gonna fix this yourself, still better describe this well just in case you might forget what you mean later :D)

**Comment by YuhanLu** [comment]
I am sorry that I did not add the description on time. To refresh my memory I can only check our chatting history on slack. Based on our discussion on slack, I think this issue is not valid either because: 1. I was using a wrong spec to debug with when I found the issue (did not have correct understanding about the data flow at that time) or 2. The file has been modified a few time and its behavior might be corrected.

**Comment by kanitw** [comment]
No worries! Let's close it then :)
