### ISSUE TITLE
Follow up Minor Fixes for `as/selections`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1966]
We'll merge https://github.com/vega/vega-lite/pull/1795 first so the code doesn't linger for long and we can build production rules.  However, at some point it's probably worth addressing comment left in the PR (including ones that got collapsed due to file  renaming / other changes on the same lines).

A few style comments:
- Let's keep `index.ts` -- I think it's a better style. We should restyle the rest of the code base to use index.  (Sorry about that!)

- If you do not want to declare full interface for a thing, giving it a name and do
`type XXX = any` can make the code is a bit more understandable. 

- When you add more code later, let's try avoid using default export ([why?](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html)).  
If we have time (definitely not important for now), we might wanna turn on a tslint flag for this for consistency, so not adding more reduce refactor efforts required if we wanna do so in the future.

**Comment by arvind** [comment]
* [ ] Add unit tests for code paths introduced by multiview operators.

**Comment by kanitw** [comment]
I think we can revise these later ...
