### ISSUE TITLE
Title formatter

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1977]
Many datasets have `field` name as lower case strings with underscore or dashes (e.g., "curb-weight").

Oftentimes, users would want the title to nicely have title case e.g., (`"Curb Weight"`). 
It's probably nice if we have titleFormat support in the config.

**Comment by danyelf** [comment]
Adding to this:  I might want to title my axis "Sum of Area", rather then SUM(area)." Can you give me the ability to provide a raw "Title:" field and have it respected? (That might also address your underlying issue.)

**Comment by kanitw** [comment]
@danyelf Thanks.  I think Sum of Area is really nicer than `SUM(area)`. 

I think it's even a better default, but that will be a breaking change though.

In any case, maybe we should support title as either `string` or an object describing title parameter:

```
{
  text: string;
  field: string; // This can be the text for just the field part 
  style: 'parenthesis' | 'of';
}
```

@domoritz @arvind @jheer  Any thoughts? 

(This is only for VL.)

**Comment by domoritz** [comment]
I'd say we can support titles with variable such as `Sum of {}` or something similar. I also like `Sum of X` better than `Sum(X)` and would be supportive of breaking it now rather than for v3. I do not like the object idea above. There will always be some other alternative that people will ask for.

**Comment by kanitw** [comment]
> I do not like the object idea above

How do you specify that you want `SUM()` then?   For example, in Voyager, we would want the old style. 

Another possibility is to have `config.guide.title.style: 'parenthesis' | 'of'`; (or `config.guideTitle`) but `config.title` is for the view-level `title`.

**Comment by kanitw** [comment]
Note that the object style is consistent with how `title`, `bin` and many other properties that support param objects work.

**Comment by domoritz** [comment]
You're right, it is the way we do it in a lot of other places. I'm just thinking that it is not very extensible. For example, what if I want `Sum(X)` instead of `SUM(X)` or even a localized `Summe von X` or `Average of X` instead of `MEAN(X)`?

**Comment by kanitw** [comment]
I think one extensible way is allow `compile` function to take more parameter in the future. 
e.g., maybe users can specify `titleFormat` function .

**Comment by kanitw** [comment]
I don't think we would ever have a cycle to implement that though.  
But I also do not want to reimplement everything in Voyager.

**Comment by kanitw** [comment]
Actually, the compile function way would actually work for Voyager very well.

**Comment by kanitw** [comment]
Done in https://github.com/vega/vega-lite/pull/3092
