### ISSUE TITLE
Including vega-parser imports almost all of vega

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1987]
Vega-Lite is not almost 1MB large because we include a lot of Vega. Also, we cannot build images because of this. 

https://github.com/vega/vega-lite/pull/1984#issuecomment-282629274

**Comment by kanitw** [comment]
Why is large file preventing us from compiling images?

**Comment by domoritz** [comment]
@kanitw Without being able to thoroughly test it, I saw that the error is `canvas = new Canvas(w, h);` and we never use (or should use) canvas in vega-lite.
