### ISSUE TITLE
Make isContinuous / isDiscrete depend on scale type 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2011]
Currently it can be slightly incorrect for temporal with timeUnit

**Comment by domoritz** [comment]
Can you look into this because I tink you have a better handle on this? It would b great to have this before the bin-scale stuff.

**Comment by kanitw** [comment]
I don't think you need this for bin-scale stuff.  You only need to deal with hasDiscreteDomain / hasContinuous domain.

**Comment by kanitw** [comment]
Now that we make temporal always use time scale, this is handled for free.
