### ISSUE TITLE
Cannot bin count

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2013]
The problem is that a signal name cannot start with `*`. It should be easy to just replace `*` with `count` or something like that.

**Comment by domoritz** [comment]
Or even better, get rid of the `*` field entirely and say it's okay to just provide an aggregation. Why don't we do that already?

**Comment by kanitw** [comment]
You cannot bin count anyway, so I don't know why this is a problem.

**Comment by domoritz** [comment]
Why not? Anyway, I think the `*` field is odd anyway for count. Let's just remove it.

**Comment by domoritz** [comment]
Okay, right now vl does not allow binning and aggregation together (https://github.com/vega/vega-lite/issues/2014). This may change in the future.
