### ISSUE TITLE
Allow aggregation and binning of the same field

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2014]
Binning should be applied after aggregation.

**Comment by kanitw** [comment]
Unless users really ask for it, I don't think we should do this because in many parts of the code we write logic assuming that they are mutually exclusive.  Plus, I don't feel like they are that useful.

**Comment by kanitw** [comment]
Also, it would seem unclear if bin is really applied after aggregation in the syntax.

Yes, if you're an expert, it makes sense, but many users won't figure this out when they read the spec.  Plus, they can achieve this using the array transform anyway.
