### ISSUE TITLE
Format in FieldDef and/or axis/legend

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2016]
It would be great if users could specify the axis/legend format in the field def. 

```json
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "format": "0.2f"}
  }
}
```

**Comment by kanitw** [comment]
Would we remove format from axis and legend in this process?  If not, we can do this post 2.0 release.  If we do, then this is pre-release.

**Comment by kanitw** [comment]
I have added `format` to fieldDef as a part of #2254.  The question is whether we keep them in axis and legend?  I am leaning toward yes.

**Comment by kanitw** [comment]
Ok. 

In #2292, we decided not to add `format` to fieldDef, except for text channel where there is no scale.
