### ISSUE TITLE
[documentation] vega-lite vs vega

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2035]
In the vega-lite [documentation](https://github.com/vega/vega-lite/blob/master/site/comparison.md#vega-and-d3), the difference between vega and vega-lite does not appear to clearly differentiate both packages. vega-lite is meant for "visual analysis" but then is also limited to the "common" chart types and transformations. It is also mentioned that vega-lite specs are shorter at the expense of flexibility. 

My suggestion is to reformulate the documentation as follows:

> Vega-Lite and Vega are both visualization specification languages in JSON.
>
> Vega-Lite is a higher-level grammar for visual analysis. It supports existing chart types (bar chart, line chart, area chart, scatter plot, heatmap, trellis plots, ...) and simple data transformations (sorting, aggregation, faceting). Vega provides a declarative language for describing visualizations. Some visualizations (trees, graphs, word cloud, custom chart types...) and interaction techniques which are expressible in Vega cannot be expressed in Vega-Lite.
>
> Vega-Lite specifications are significantly shorter (about 1/10th) than Vega specifications. In Vega, you have to manually construct axis and legends and you have to decide how to map the data to visual properties. Vega-Lite automates the construction of axes, legends, and scales from a high level encoding specification. At the same time, Vega-Lite is compiled to Vega, which allows to further customize Vega specifications generated by Vega-Lite.

**Comment by kanitw** [comment]
Thanks.  We'll add a short page for comparing Vega and Vega-Lite once we update the documentation for Vega-Lite v2 (which will include interactions support).

**Comment by domoritz** [comment]
This is covered in https://vega.github.io/vega/about/projects/
