### ISSUE TITLE
`sort` appears broken in `layer` context

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2038]
Compare this spec:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"var1": "A1","var2": 0.6, "var3": 3},
      {"var1": "A2","var2": 1.2, "var3": 3},
      {"var1": "A3","var2": 2.6, "var3": 2},
      {"var1": "A4","var2": 1.3, "var3": 3},
      {"var1": "A5","var2": 2.2, "var3": 2.5},
      {"var1": "A6","var2": 0.4, "var3": 1.5},
      {"var1": "A7","var2": 0.4, "var3": 1}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": { "field": "var2","type": "quantitative" },
    "y": {
      "field": "var1", "type": "nominal", 
      "sort": {"field": "var2", "op": "mean", "order": "descending"}
    }
  }
}
```

to this one

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"var1": "A1","var2": 0.6, "var3": 3},
      {"var1": "A2","var2": 1.2, "var3": 3},
      {"var1": "A3","var2": 2.6, "var3": 2},
      {"var1": "A4","var2": 1.3, "var3": 3},
      {"var1": "A5","var2": 2.2, "var3": 2.5},
      {"var1": "A6","var2": 0.4, "var3": 1.5},
      {"var1": "A7","var2": 0.4, "var3": 1}
    ]
  },
  "layer": [
    {
      "mark": "bar",
      "encoding": {
        "x": { "field": "var2","type": "quantitative" },
        "y": {
          "field": "var1", "type": "nominal", 
          "sort": {"field": "var2", "op": "mean", "order": "descending"}
        }
      }
    },
    {
      "mark": "tick",
      "encoding": {
        "x": {"field": "var3","type": "quantitative"},
        "y": {
          "field": "var1", "type": "nominal",
          "sort": {"field": "var2", "op": "mean", "order": "descending"} 
        },
        "color": {"value": "red"}
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
I believe this is a vega limitation. Unioned scales can only use count for sorting (https://github.com/vega/vega-parser/blob/master/schema/scale.js#L125). However, in the case above we don't have to union because the scale domains of both layers are the same. However, that's not true in general. 

@jheer why is this limitation in the schema but [the docs](https://vega.github.io/vega/docs/scales/#domain) don't mention it. How difficult would it be to allow arbitrary aggregates to sort unioned scale domains by an aggregate?

**Comment by domoritz** [comment]
Related https://github.com/vega/vega-lite/issues/1895

**Comment by kanitw** [comment]
I think given that we will have an array of domains in https://github.com/vega/vega-lite/pull/2536 -- this is fixable.

**Comment by kanitw** [comment]
From Vega docs: "Note: For domains drawn from multiple fields, the sort.field property is not allowed and the only legal op is count.". 

The case that should work is if all layers use the same domain and sort.

**Comment by kanitw** [comment]
@domoritz  Can you recheck this one and close if it is handled?

**Comment by domoritz** [comment]
The scale merging logic is correct but the datasources are different.

```
      "domain": {
        "fields": [
          {"data": "data_1","field": "var1"},
          {"data": "data_2","field": "var1"}
        ],
        "sort": true
      },
```

The only way to change this for the example above is merging datasources. We will be doing this post 2.0. Closing as this will fix itself then and the behavior of the scale merging logic is correct.

**Comment by kanitw** [comment]
I'm gonna re-open this as there is no warning for users about this bug yet and this has confused our users again in https://github.com/vega/vega-lite/issues/3152

**Comment by kanitw** [comment]
(For actually fixing the issue, we have https://github.com/vega/vega-lite/issues/2177 filed -- so this re-opening is only for generating warning.)

**Comment by domoritz** [comment]
I'm getting a warning: `vega-lite.js:1913 WARN Dropping sort property "{"field":"var2","op":"mean","order":"descending"}" as unioned domains only support boolean or op 'count'.`
