### ISSUE TITLE
Support Top-Level `autosize`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2047]
> Vega 3 adds a new top-level `"autosize"` property to set the layout mode. The allowed options are `"pad"` (the default, similar to `"padding": "auto"` in Vega 2, the chart dimensions will be expanded as needed to fit the chart, axes and legends), `"fit"` (similar to `"padding": "strict"` in Vega 2, the data rectangle size will be decreased in an attempt to force the chart to fit within the given width and height) and `"none"` (no resizing is performed, and the chart size is solely determined by the width, height and padding settings). 

The tricky part with `autosize` is that we have to test if our layout (esp. for faceted plot) will totally break with `"fit"` or `"none"` mode.  (Currently it's always "pad".)

Forked from #1778 as this seems tricky and not that important.

**Comment by kanitw** [comment]
Looks like this won't even be possible given the new Vega layout operator that we will have soon.

**Comment by pelotom** [comment]
I'd like to vote to reopen this... it's the main reason why I'm unable to use Vega Lite for my product (though I'd very much like to!) and have to fall back to basic Vega. I need to be able to ensure that a chart is rendered exactly within certain bounds, even though it might be trellised.

**Comment by domoritz** [comment]
We can keep the conversation going in here even though the issue is closed. I understand your frustration and agree that we should aim to have top-down sizing for composed charts as well. However, we do need better support for this in Vega first before we can consider changes to Vega-Lite. For this reason, let's not open an issue here (since we can't do anything about this right now) and instead discuss this in Vega, okay?

**Comment by pelotom** [comment]
Fine by me! I don't know what the technical issues are, I just know the end state I'd like to get to 🙂 I'm happy to open an issue in Vega, but I'm not sure what it should say other than "Rearchitect so that Vega Lite can do top-level autosizing".

**Comment by domoritz** [comment]
I'd something like "Support top-down layout" and link to this issue.

**Comment by pelotom** [comment]
[Done!](https://github.com/vega/vega/issues/1444)
