### ISSUE TITLE
Off-by-one year in temporal-year axis

### ISSUE THREAD

**Issue by rgrzywinski** [vega/vega-lite#2048]
The following spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Line chart of Horsepower over time",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "Year", "type": "temporal", "timeUnit": "year"},
    "y": {"field": "Horsepower", "type": "quantitative", "aggregate": "mean"}
  }
}
```

results in the following plot:
<img src="https://cloud.githubusercontent.com/assets/813117/24326408/8528cf3a-117b-11e7-907f-5374b590d1d6.png" width="200">

Note that the domain of the data is 1970 - 1982 (*not* 1969 - 1981).

Interestingly, the following spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/seattle-weather.csv","format": {"type": "csv"}},
  "mark": "bar",
  "encoding": {
    "x": { "field": "date", "type": "temporal", "timeUnit": "year" },
    "y": { "field": "precipitation", "type": "quantitative", "aggregate": "sum" }
  }
}
```

results in the following *correct* plot:
<img src="https://cloud.githubusercontent.com/assets/813117/24326476/1e90c7a8-117d-11e7-9537-f79ab729e68b.png" width="200">

(VL: v2.0.0-alpha.6; VG: v3.0.0-beta.27)

**Comment by kanitw** [comment]
Thanks for reporting, this might be related to timezone (#446).  We will revisit this soon.  Thank you!

**Comment by kanitw** [comment]
@YuhanLu   -- can you check if this is still a problem in Vega-Lite 2?  

It seems like a part of the problem is that cars.json has date in ISO format.

**Comment by kanitw** [comment]
@YuhanLu looks like the assumption that if users use timeUnit with utc, we should use scale = utc is wrong.  Same for the other way round.

**Comment by YuhanLu** [comment]
yeah currently this spec has `"timeUnit": "utcyear"`
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Line chart of Horsepower over time",
  "data": {"url": "data/cars.json"},
  "mark": "text",
  "encoding": {
    "x": {"field": "Year", "type": "temporal", "timeUnit": "utcyear"},
    "y": {"field": "Horsepower", "type": "quantitative", "aggregate": "mean"},
    "text": {"field": "Year", "type": "temporal", "timeUnit": "utcyear"}
  }
}
```

and it automatically set scale type = "utc",

Screenshot 1
<img width="291" alt="screen shot 2017-05-03 at 5 32 28 pm" src="https://cloud.githubusercontent.com/assets/11696585/25686890/b1dc97cc-3026-11e7-80a9-6119516ebb1b.png">

But if we set scale type = time, then it's right


<img width="271" alt="screen shot 2017-05-03 at 5 34 45 pm" src="https://cloud.githubusercontent.com/assets/11696585/25686909/d2d9a7f8-3026-11e7-8c9c-56d57e64c2ac.png">
