### ISSUE TITLE
Parallelize the build:examples script

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2060]
We now include the output Vega specs in the repo, using the `build:examples` (introduced in #2057).

However, `build:examples` is now single-thread.  We can make it faster using `parallel` as we use in `generate-images.sh`.  However, previously we assume that users of  `generate-images.sh` will manually install the right dependencies. 

Two things we have to guarantee:
- [x] Make sure `npm install` include the right dependency.
- [ ] Make sure travis includes the right dependency.

**Comment by domoritz** [comment]
Yeah, it's really slow right now...

**Comment by kanitw** [comment]
> 1.5 minutes for a build.
Huh, mine wasn't that bad.  If it's that bad, we should inspect and find a bottleneck spec.

**Comment by kanitw** [comment]
partly done in #2067, but still have to 

- [ ] update echo comment
- [ ] Make travis use `parallel`
- [ ] add a script to postinstall to make sure `parallel` is install for local development too?  (It's probably okay to make the script only work for mac and does not thing for Linux / window and add note to CONTRIBUTING.md.)

**Comment by domoritz** [comment]
I'm against number 3. Add it to the instructions and throw a warning. Don't install things on the users system without asking.

**Comment by YuhanLu** [comment]
https://github.com/vega/vega-lite/issues/2068

**Comment by kanitw** [comment]
@NeelMohapatra @sirahd -- would any of you have free time to help with this one?

**Comment by NeelMohapatra** [comment]
I am acclimating to the internship but I can start working on it as soon as I finish the axes format PR. I plan to finish the PR by this Friday. So I can start working on this on Monday, I guess.

**Comment by kanitw** [comment]
To clarify the main issue left is that travis does not run build:examples in parallel and thus is very slow.
