### ISSUE TITLE
Setting timeUnit to aggregate a temporal variable on a weekly basis?

### ISSUE THREAD

**Issue by dhimmel** [vega/vega-lite#2062]
Currently, my `x` channel is temporal. The `y` channel applies aggregation. Currently, the aggregation interval is specified by `"timeUnit": "yearmonth"`:

```json
    "x": {
      "axis": {
        "axisWidth": 0.0,
        "format": "%Y",
        "labelAngle": 0.0,
        "tickSize": 0.0
      },
      "field": "Date",
      "scale": {
        "nice": "month"
      },
      "timeUnit": "yearmonth",
      "title": "",
      "type": "temporal"
    },
```

Is there a way to aggregate on a weekly (7 day) basis? I didn't see that option on the [`timeUnit` doc](https://vega.github.io/vega-lite/docs/timeunit.html#datetime-units).

**Comment by dhimmel** [comment]
Or any other arbitrary temporal range?

**Comment by kanitw** [comment]
Thanks for asking. 

For arbitrary temporal range, you can use the `calculate` transform and [Vega Expression](https://github.com/vega/vega/wiki/Expressions) to perform custom calculation that you want.

**Comment by dhimmel** [comment]
@kanitw thanks for the help. I [ended up](https://github.com/dhimmel/biorxiv-licenses/blob/16cdfccef4ac1fb30cfb3de784b686659ce1de52/3.impact.ipynb) performing the aggregation by week in pandas before passing the dataframe to vega-lite. Using `calculate` is still a bit daunting for me.

So unfortunately I won't be able to post the solution here... feel free to close this issue unless you'd like to implement a `yearweek` setting `timeUnit`. Of course you know better than I whether that fits within the design methodology.

**Comment by domoritz** [comment]
Closing as we would need support in Vega first.

**Comment by drorata** [comment]
I have a use case where the back-office aggregation returns daily counts. However, for visualization purposes, I want to switch to week-of-the-year level. Seems like I need this `calculate` option. Are there any further details?

**Comment by domoritz** [comment]
Yes, you need to use calculate or we need to implement this in Vega. We are happy to review a PR towards this feature.

**Comment by kanitw** [comment]
Also, it's a special case of #3290

**Comment by aborruso** [comment]
@kanitw if I understood you, it is possible to aggregate per week also in vegalite.

Do you have a working example?

Thank you
