### ISSUE TITLE
Support band scale for bin

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2063]
TimeUnit:
* Uses ordinal scale for discrete timeUnit (e.g., month, (week)day)
* can be sorted

Bin
* Uses bin scale (similar to linear)
* cannot be sorted unless you set the scale type to ordinal

**Comment by domoritz** [comment]
See #1366

**Comment by kanitw** [comment]
I just updated the description above a bit.

**Comment by kanitw** [comment]
- [ ] To make timeUnit always use time scale by default, we need to make bar size automatically adjustable based on the timeUnit's cardinality

- [ ] Thinking more about, it is okay to make scale type for bin and timeUnit depend on sorting. 
(The transition won't be smooth, but at least we will produce less broken state by default.)

**Comment by kanitw** [comment]
We cannot use time scale by default for discrete timeUnit as timeUnit produces non-uniform bin.
For example, Q1, Q2, Q3, Q4 do not have identical numbers of days and thus can lead to incorrect labels as in https://github.com/vega/vega-lite/issues/2045.

However, changing bin's scale type when sort is applied is worth considering. 
In any case, we currently don't even support band scale for bin so we should support that too.

That said, I think this can come after 2.0.

**Comment by kanitw** [comment]
I think we already support this for both consistently (via casting them as "ordinal")
