### ISSUE TITLE
Table size for doc should be fixed

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2091]
<img width="1023" alt="screen shot 2017-04-08 at 2 45 42 pm" src="https://cloud.githubusercontent.com/assets/11696585/24832773/25cd030c-1c6c-11e7-944b-eae95f4f4793.png">

The table size for doc should be fixed and from the pic above we can see that now it's depends on the length of the description.

**Comment by kanitw** [comment]
@domoritz is this fixed?

**Comment by YuhanLu** [comment]
Yes Dom fixed that already
