### ISSUE TITLE
Cannot build npm scripts on windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vega/vega-lite#2100]
On a Win 10 command window, after a clean `git clone` and `npm install`:
![image](https://cloud.githubusercontent.com/assets/3335181/24890394/8536a302-1e24-11e7-8d72-dcf759f5ba3e.png)

> 'rm' is not recognized...

**Comment by domoritz** [comment]
Unfortunately, none of us use windows and we don't have the capacity to maintain windows compatible scripts. Sorry. 

You can run `npm run tsc` to test https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15768.

**Comment by JoshuaKGoldberg** [comment]
Ah well, thanks!

**Comment by JoshuaKGoldberg** [comment]
Ah well, thanks!

`npm run tsc` does fail too, but just `tsc` is fine.

**Comment by domoritz** [comment]
Oh yeah. That's the one that runs `rm`. I'm glad tsc works.
