### ISSUE TITLE
tsc is broken by the latest Chai typings

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vega/vega-lite#2102]
Cross-posting here what was reported by @domoritz in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15768. I'm averse to changing the typings to not being as strict by default because I think there's benefit in enforcing type safety on these supposed-to-be-type-safe assertions. But, since I inconvenienced you with this, I'm willing to go through your test files and add the types.

**Comment by domoritz** [comment]
That would be awesome! Since the corresponding ts issue has been open for a while, it seems worth it to explicitly specify the types. However, I'm also okay with sticking with `3.4.35` (don't want to create unnecessary manual labor for you).

**Comment by JoshuaKGoldberg** [comment]
Too late :)

**Comment by domoritz** [comment]
Many thanks from the other side of the lake!
