### ISSUE TITLE
Bin doc code block not working

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2110]
<img width="847" alt="screen shot 2017-04-11 at 1 18 00 pm" src="https://cloud.githubusercontent.com/assets/11696585/24929008/55499ed4-1eb9-11e7-9cf1-95a0bfa7f2f3.png">

**Comment by YuhanLu** [comment]
PR has reverted

**Comment by domoritz** [comment]
Run `npm run build:site` with the latest master.

**Comment by YuhanLu** [comment]
thanks!

**Comment by YuhanLu** [comment]
nope it is still now working...

**Comment by YuhanLu** [comment]
It works fine here https://vega.github.io/vega-lite/docs/bin.html
