### ISSUE TITLE
Re-apply the new layout from Vega

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2113]
- [ ] Use it with facet

**Comment by domoritz** [comment]
- [ ] Delete `axes`, `scales`, `legend`, and others from model. We only need it in unit. 
- [ ] Instead of nesting things under component, make scales, axes, legends, ... properties of the model.

**Comment by domoritz** [comment]
I think this is a good place to fix the problem of merging axis groups (https://github.com/vega/vega-lite/issues/1544).

- [ ] https://github.com/vega/vega-lite/issues/1544

**Comment by kanitw** [comment]
These are all done in #2168
