### ISSUE TITLE
Check new added/renamed properties consistent with doc

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2114]
I am working on enabling auto-generation for tables in doc. I will migrate all properties from old doc to new doc and will try to find the renamed properties for each interface, and replace them in the doc. But I need help from people who added/renamed properties in those interfaces to put these new properties into the right table after I finish enable all the table. I have already check every properties for `Axis` and `Legend` and may need to check the following doc as well. And this is a list for all docs need to be checked.

- [x] bin.md
- [x] config.md
- [x] data.md
- [x] encoding.md
- [x] facet.md
- [x] label.md
- [x] mark.md
- [x] overview.md
- [x] scale.md
- [x] size.md
- [x] sort.md
- [x] spec.md
- [x] timeunit.md
- [x] transform.md

**Comment by kanitw** [comment]
This seems redundant with https://github.com/vega/vega-lite/issues/1723#issuecomment-293344680, so I'm gonna close this.  If this is not the case, feel free to re-open.

**Comment by YuhanLu** [comment]
They are 2 different issues. I will generate those table, but I don't know if there's more properties need to be added

**Comment by kanitw** [comment]
Oh ok.  FYI, our release notes can be helpful for this. :)
