### ISSUE TITLE
Inline data requires a bogus URL to control parsing.

### ISSUE THREAD

**Issue by mbostock** [vega/vega-lite#2143]
Say I have some inline data like this:

```json
[
  {"date": "20010101", "close": "1"},
  {"date": "20010102", "close": "2"},
  {"date": "20010103", "close": "3"}
]
```

This date format (`%Y%m%d`) doesn’t work with the default date parser, so I need to tell Vega the format. When the data is specified by URL, that works fine:

```json
{
  "data": {
    "url": "https://rawgit.com/mbostock/b556aa0f77b48505ea074469333125ae/raw/test.json",
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/230541/25050923/e08c896a-20fe-11e7-9133-7241e2072b81.png)

However if the data is specified inline, it appears the format.parse is ignored, so you get a blank chart:

```json
{
  "data": {
    "values": [
      {"date": "20010101", "close": "1"},
      {"date": "20010102", "close": "2"},
      {"date": "20010103", "close": "3"}
    ],
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/230541/25050938/fc345a26-20fe-11e7-8da7-fca45afa7df8.png)

Strangely enough, if you specify a data.url in addition to data.values, regardless of the value of data.url, it has the desired result of using your inline values and applying the format.parse. So the simplest workaround is to just put a blank `data:` URL in for data.url:

```json
{
  "data": {
    "url": "data:",
    "values": [
      {"date": "20010101", "close": "1"},
      {"date": "20010102", "close": "2"},
      {"date": "20010103", "close": "3"}
    ],
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/230541/25050978/31555ad4-20ff-11e7-9d5b-4bab1adcba93.png)

**Comment by domoritz** [comment]
Thanks for the bug report. Vega-Lite currently doesn't allow overriding the parse property for inline data. If you paste the example in the new editor (https://vega.github.io/new-editor/#/examples/vega_lite/bar), you'll see the JSON schema validation fails. 

However, that doesn't make any sense. We should support it.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2153
