### ISSUE TITLE
Grid goes too far / Consider removing nice for timeUnit

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2147]
https://vega.github.io/new-editor/#/examples/vega_lite/area

![screen shot 2017-04-14 at 11 11 05](https://cloud.githubusercontent.com/assets/589034/25051753/13c19146-2103-11e7-8679-3da102de2cdf.png)

**Comment by Fil** [comment]
it's due to ` "nice": "month" `

I have the inverse problem: I want to add some margin on the right of my date scale :)

**Comment by kanitw** [comment]
Taking tableau as inspiration, this may be okay.   
![image](https://user-images.githubusercontent.com/111269/31001738-dd1f3dac-a49a-11e7-970c-7f8aa4ebd8a4.png)

One thing that I wonder is whether it shift by one year because of UTC time?

**Comment by kanitw** [comment]
Maybe it's worth removing `nice` for timeUnit -- and if we wanna do that, better do it now before 2.0.

**Comment by domoritz** [comment]
Maybe. We can decide once we see what axes look like without nice but I suspect it will be fine for timeUnit.

**Comment by kanitw** [comment]
This issue will be fixed in https://github.com/vega/vega-lite/pull/3078.

@Fil -- FYI, Vega now have [`padding` property for quantitative scales](https://vega.github.io/vega/docs/scales/#quantitative).  We will add that to Vega-lite very soon.
