### ISSUE TITLE
Interval selection fails over ordinal scale

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#2148]
Expected behavior: A continuous brush that selects the discrete values it contains
Actual behavior: Error messages in console

(Note: `single`/`multi` selections projected over "y" are working.)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A bar chart showing the US population distribution of age groups in 2000.",
  "data": {
    "url": "data/population.json"
  },
  "transform": [
    {
      "filter": "datum.year == 2000"
    }
  ],
  "mark": "bar",
  "selection": {
    "brush": {
      "type": "interval",
      "encodings": [
        "y"
      ]
    }
  },
  "encoding": {
    "y": {
      "field": "age",
      "type": "ordinal",
      "scale": { "rangeStep": 17 }
    },
    "x": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative",
      "axis": { "title": "population" }
    },
    "color": { "value": "steelblue" }
  }
}
```

**Comment by arvind** [comment]
The error seems to be in inverting coordinates with the `point` y-scale generated. 

```json
{
  "name": "y",
  "type": "point",
  "domain": {
    "data": "source_0",
    "field": "age",
    "sort": true
  },
  "range": {
    "step": 17
  },
  "round": true,
  "padding": 0.5
}
```

If I switch it to the following `band` scale, the interval selection works again. @jheer, would you like me to file an issue in vega-scale?

```json
{
  "name": "y",
  "type": "band",
  "domain": {
    "data": "source_0",
    "field": "age",
    "sort": true
  },
  "range": [0, 400]
}
```

**Comment by jheer** [comment]
I don't think so. AFAICT the scale inversions are performing as designed. The console errors do go away when I switch the generated Vega to a band scale, but the brush still does not behave correctly (or, at minimum, as I expect it should).

I believe the Vega code as generated will _never_ work with a point scale. (1) On mousedown, the brush interval is initialized through `invert` by passing the mouse position as the brush extent (e.g., `[x, x]`). For a point scale, that will typically resolve to nothing (i.e., `undefined`), as the scale bandwidth is zero and so a single coordinate will only resolve to a range if it _exactly_ matches a value. (2) On mousemove, only a single coordinate (not a range) is run through `invert`. Again, for a point scale this will fail unless an _exact_ match occurs.

Instead, the _full brushed range_ (start and end coordinates) should be run through inversion on each update. I also think the original mouse coordinates should be preserved to define the brush extents (in terms of pixels), and then run through scale inversions to determine the selected data. Thus the brush itself will behave in a continuous manner, but resolve to a discrete selection.

FWIW, @kanitw may be updating the scales to use `band` rather than `point`. Nevertheless, some of the issues above are relevant!

**Comment by arvind** [comment]
Oh right, of course! Having interval selections build discrete state is likely something prioritized for a post-OVC beta. It would handle the case of a CxA plot that @kanitw was describing as well. Great example to help think through this though, thank!

**Comment by domoritz** [comment]
@kanitw created an issue to change from point to band scales at https://github.com/vega/vega-lite/issues/2161.

**Comment by kanitw** [comment]
In #2377, interval selection seems to work correctly with band and point scales. 

Band would better match user's mental model and thus is a better default. I'll change that in #2161.
