### ISSUE TITLE
Default scale for bar

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2161]
Consider if we want to use band scale by default.

**Comment by domoritz** [comment]
Any reasons against it.

**Comment by kanitw** [comment]
I think point support size, band doesn't yet.  

If I remember correctly, point center it while band offset it by 1px.

**Comment by domoritz** [comment]
Yeah, that seems to be a vega issue. For example, see https://vega.github.io/new-editor/#/examples/vega/crossfilter.

![screen shot 2017-04-14 at 16 33 33](https://cloud.githubusercontent.com/assets/589034/25058599/2b981894-2130-11e7-868a-64d7282e9b62.png)

@jheer Is there a way to resolve this issue with the 1px offset in a general way?

**Comment by kanitw** [comment]
Thinking more about it, band is more responsive.  We can limit the size to be [0, 1] and make it scale based on rangeStep.  We could handle this 1px thing by adding +/- 0.5 offset to both `x`, `x2`.

**Comment by kanitw** [comment]
Ok -- I think we should change the default to band scale as selection is smarter on band scale

Band

![vega_editor](https://cloud.githubusercontent.com/assets/111269/26812111/a72247fa-4a2a-11e7-92b1-637667d9e7b9.png)

Point

We really need to cover the point of the band to select a bar, which might not match well to user's mental model.  
![vega_editor](https://cloud.githubusercontent.com/assets/111269/26812126/b85d80d4-4a2a-11e7-93a1-3507db1ecf59.png)

**Comment by jheer** [comment]
Yes, a band scale is much more appropriate as the default here.

**Comment by kanitw** [comment]
Done in #2309
