### ISSUE TITLE
FacetNode should support bin and timeUnit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2167]
The current implementation of `FacetNode` only takes `field` into account, but not `bin` and `timeUnit`

- [ ] Instead of storing `columnField` and `rowField`, I believe we may want to store `column/rowFieldDef`.

- [ ] On a related note, `AggregateNode`'s public `addDimensions` method doesn't consistently use the local `addDimension` in the same file (which has more proper support for binned field).

cc: @domoritz

**Comment by domoritz** [comment]
Can you post an example spec?

**Comment by kanitw** [comment]
This is issue is filed from inconsistent found when reading code.  (Started from `addDimension` of `AggregateNode`.)

I don't have an example spec yet, but you can create any facet spec with bin and timeUnit

(I start doubting if we need to store `timeUnit`, maybe only the `bin` case.)

**Comment by kanitw** [comment]
@YuhanLu  Can you help test if  bin and timeUnit work with `FacetSpec`?

**Comment by YuhanLu** [comment]
I think it works for timeunit. 
```
{
  "data": {"url": "data/seattle-weather.csv", "formatType": "csv"},
  "mark": "line",
  "encoding": {
    "x": {
      "field": "weather",
      "type": "nominal"

    },
    "y": {
      "aggregate": "mean",
      "field": "precipitation",
      "type": "quantitative"
    },
    "row": {
      "timeUnit": "month",
      "field": "date",
      "type": "temporal"
    }
  }
}
```
<img width="218" alt="screen shot 2017-04-27 at 10 36 14 am" src="https://cloud.githubusercontent.com/assets/11696585/25496344/7210fb2e-2b35-11e7-8d8b-d64f5e5697f9.png">

**Comment by YuhanLu** [comment]
And also works for bin:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A trellis scatterplot showing Horsepower and Miles per gallons, faceted by binned values of Acceleration.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "row": {"field": "Acceleration","type": "quantitative", "bin": {"base": 40}},
    "x": {"field": "Horsepower","type": "quantitative"},
    "y": {"field": "Miles_per_Gallon","type": "quantitative"}
  }
}
```

<img width="415" alt="screen shot 2017-04-27 at 10 51 22 am" src="https://cloud.githubusercontent.com/assets/11696585/25496882/7c9f2690-2b37-11e7-99c0-7f9a3d4c2da3.png">
