### ISSUE TITLE
`datum[""]` -> `datum['']`

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2179]
It would be nice to avoid escaping in the JSON output by using ' instead of ".

**Comment by domoritz** [comment]
This also needs to be done in https://github.com/vega/vega-lite/pull/2174 or after it has been merged.

**Comment by kanitw** [comment]
Can you explain more?

**Comment by domoritz** [comment]
We should instead use vega.stringValue and it already generates " so let's ignore this.
