### ISSUE TITLE
Design new way to specify grouped bar chart

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2180]
Previously grouped bar chart are expressed using facet.  However, by using layout to implemen facet, facet's column/row will no longer have axis lines like normal x/y axis, we need an alternative way to specify grouped bar chart.

1) One way is to include `dx/dy` or ` x/yOffset` channels to specify within group offset.  
This should be something somewhat equivalent to `position="dodge"` in ggplot. 
This `dx` will be useful for jittering as well.

2) Another way is to have two types of facets -- one type uses layout, another uses our old calculation (for grouped bar chart).

I think 1) sounds way more desirable.  

## Original Spec

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "mark": "bar",
  "encoding": {
    "column": {
      "field": "age", "type": "ordinal"
    },
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population", "grid": false}
    },
    "x": {
      "field": "gender", "type": "nominal",
      "scale": {"rangeStep": 6},
      "axis": null
    },
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#EA98D2", "#659CCA"]}
    }
  },
  "config": {
    "facet": {"cell": {"strokeWidth": 0}},
    "axis": {"domainWidth": 1}
  }
}
```

## Alternative Spec 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "age", "type": "ordinal"
    },
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population", "grid": false}
    },
    "dx": {  // dx doesn't support axis as it's just adding offset to x-channel
      "field": "gender", "type": "nominal",
      "scale": {"rangeStep": 6} //
    },
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#EA98D2", "#659CCA"]}
    }
  },
  "config": {
    "facet": {"cell": {"strokeWidth": 0}},
    "axis": {"domainWidth": 1}
  }
}
```

**Comment by kanitw** [comment]
From https://github.com/vega/vega-lite/pull/2168#issuecomment-294369352, here is how bar_grouped looks like currently 

<img width="672" alt="screen shot 2017-04-16 at 12 26 05" src="https://cloud.githubusercontent.com/assets/589034/25073660/e5aaa0b0-229f-11e7-8caa-8bedf6cbb642.png">

**Comment by kanitw** [comment]
Note that I update the `bar_grouped` example to become a bit more okay.

![vega_editor](https://cloud.githubusercontent.com/assets/111269/25074285/8a18a898-22ac-11e7-93d2-6347ba017536.png)

**Comment by kanitw** [comment]
- [ ] With a new approach, grouped bar chart should share grid (https://github.com/vega/vega-lite/issues/1636).

**Comment by oleg131** [comment]
Has anything been decided on this? I agree that the new format is better. See it this way: if you remove groups, you are plotting vs age. However, when you introduce groups, you are now suddenly plotting vs gender, while using age as facets. By using new format, we preserve the notion that plotting is still done vs age in both grouped and non-grouped cases.

**Comment by kanitw** [comment]
Not yet, but it should be a part of more general discussion about how we design `dx` and `offset`.  
For now, we plan to finish other more important tasks for 2.0 release first.

**Comment by oleg131** [comment]
I see. Am i correct in understanding that at this point in v2, there won't by any way to change e.g. font size of facet titles, since `axis` is not longer attachable to them?

**Comment by kanitw** [comment]
I'm gonna close this as this should be a part of #396
