### ISSUE TITLE
Why isn't each type of Node constructor include parent?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2197]
It seems like we always know its parent when we build things.

Including parent in the constructor will make the code shorter and further avoid typo bugs.

**Comment by kanitw** [comment]
(Of course -- except for SourceNode)

**Comment by domoritz** [comment]
I found it easier when you want to merge things to create a node and connect things one by one. But I can see the value of including the parent in the constructor to simplify the parse code.

**Comment by kanitw** [comment]
This should be a simple and relevant refactor for your part.

**Comment by kanitw** [comment]
The code for data.parse in getting crazily longer.  I think having this parameter can shorten the code a lot!

**Comment by domoritz** [comment]
Okay, I'm happy to review a PR for this change.
