### ISSUE TITLE
Revise Faceted Selection

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2204]
Since we're pretty much re-implementing facet with the new Vega layout operator and remove the top-level main-group and the layout data source, the `faceted_selection` is now getting weird – I cannot really drag the brush properly like before.

I believe this is related to the fact that main-group is now gone.

I'm not gonna try to debug this now as the new Vega layout operators has changed a bit so I better update the latest one first before seeing if there is any problem with this one.

**Comment by arvind** [comment]
Which branch of vega and vega-lite should I check out to reproduce this?

**Comment by kanitw** [comment]
Layout branch, but wait a bit because Jeff had new changes in the layout so i need to update the branch to use the new syntax

**Comment by kanitw** [comment]
Try this branch https://github.com/vega/vega-lite/pull/2238

**Comment by domoritz** [comment]
And the latest vega with updated dependencies (master of vega parser and vega view as well)

**Comment by arvind** [comment]
I can no longer reproduce whatever error this issue was referencing (including once the "main group" is removed in #2463). So, closing for now, but please re-open if you continue to experience issues.

**Comment by kanitw** [comment]
Yeah it seems to work well  when I was testing one of your prior PRs offline as well ;)
