### ISSUE TITLE
Make predicate signal correct

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2209]
See https://github.com/vega/vega-lite/commit/a2e88d294a44b023b08dcd1327537799e3e486fe#commitcomment-21799792

**Comment by kanitw** [comment]
@arvind   Let's continue the discussion here.   

Before I revert and bring "main-group" back -- I want to understand a bit more.

> The predicates used to use parent to identify which unit a particular selection was defined in and 
called from. 

Reading the first part here sounds like this parent reference is only necessary if the unit is being composed by another operator.  However, I am not sure about my proposal yet as I do not clearly understand the "but" case below yet.  

> The closest would be item.mark.group._id but that would not work if we wanted to use predicate functions within filter transforms...

Could you please provide a spec for the "use predicate functions within filter transforms"? 
Specifically, I wonder if such case is also problematic for a single top-level unit spec, or mainly just for a unit spec that is a child of a composite spec.   

If it is problematic for a single top-level unit spec, I guess we'd have to bring the main group back for now as the issue seems very delicate.  If it's just a child unit spec, I think we can safely use `item.mark.group._id` when the unit model has no parent and use `parent.id` when the unit model has a parent.

**Comment by kanitw** [comment]
This is temporarily fixed by bringing back the `main-group`

**Comment by arvind** [comment]
Fixed with #2463.
