### ISSUE TITLE
Update mark.md to include ranged marks.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2213]
We haven't shown how to use x2 and y2 at all

**Comment by domoritz** [comment]
Also make sure we talk about all mark types. For example rule.

**Comment by kanitw** [comment]
**Step 1.** Create examples for different ranged mark types

- [ ] area
  - [ ] use ranged area to show confidence interval of line charts akin to last example in http://ggplot2.tidyverse.org/reference/geom_ribbon.html  (You will have a find a good data yourself
- [ ] bar/rule 
  - [ ] replicate https://vega.github.io/vega/examples/timelines/?
  - [ ] replicate error bar with rule similar to https://vega.github.io/vega/examples/error-bars/? (Just do confidence interval is fine)

(You can submit one or more example at a time -- whichever you think makes it easier for us to review.)  

**Step 2.** Add them to different parts of marks.md with description paragraphs

**Comment by ayush29feb** [comment]
Ran into some issues while recreating the https://vega.github.io/vega/examples/timelines/ example.
- [ ] vega-lite doesn't allow multiple data sources so I couldn't figure out how to load both presidents and events described in the vega doc. Maybe I misunderstood but this was presented in #1271 
- [ ] the sort property of the mark wasn't working. I made a separate issue for that #2533 

Another small thing, the size property isn't documented for rules mark in the docs. Maybe we should include it.

Here is what I got so far.
![image](https://user-images.githubusercontent.com/8674376/27266699-f742f824-5457-11e7-9e96-cc1c6dd979a3.png)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "name": "people",
    "values": [
      {
        "label": "Washington",
        "born": -7506057600000,
        "died": -5366196000000,
        "enter": -5701424400000,
        "leave": -5453884800000
      }
      ...
    ]
  },
  "layer": [
    {
      "mark": "rule",
      "encoding": {
        "x": {
          "field": "born",
          "type": "temporal",
          "timeUnit": "year",
          "axis": {"title": "Year"}
        },
        "x2": {
          "field": "died",
          "type": "temporal",
          "timeUnit": "year"
        },
        "y": {
          "field": "label",
          "type": "nominal",
          "axis": {"title": "President"}
        },
        "color": {"value": "black"},
        "size": {"value": 2}
      }
    },
    {
      "mark": "rule",
      "encoding": {
        "x": {
          "field": "enter",
          "type": "temporal",
          "timeUnit": "year"
        },
        "x2": {
          "field": "leave",
          "type": "temporal",
          "timeUnit": "year"
        },
        "size": {"value": 4},
        "y": {
          "field": "label",
          "type": "nominal",
          "label": "President"
        },
        "color": {"value": "red"}
      }
    }
  ]
}
```

**Comment by ayush29feb** [comment]
For the confidence intervals, do we have a aggregate function to calculate the 95% value? I am currently plotting q1 and q3

**Comment by ayush29feb** [comment]
For the ranged area chart, is this example not good enough?
http://www.ayush.xyz/vega-editor-demo/?mode=vega-lite&spec=confidence_interval
![image](https://user-images.githubusercontent.com/8674376/27267116-03b214e8-545b-11e7-856b-b255ebd1f7d5.png)

**Comment by domoritz** [comment]
> vega-lite doesn't allow multiple data sources so I couldn't figure out how to load both presidents and events described in the vega doc

Use layers or lookup

**Comment by domoritz** [comment]
> Another small thing, the size property isn't documented for rules mark in the docs. Maybe we should include it.

Please send a separate PR!

**Comment by kanitw** [comment]
> For the confidence intervals, do we have a aggregate function to calculate the 95% value? I am currently plotting q1 and q3


They are called `ci0` and `ci1` -- I believe.  (See Vega docs and if Vega-Lite docs do not have them, please help update accordingly.)  :)

**Comment by kanitw** [comment]
Consolidated as a part of https://github.com/vega/vega-lite/issues/2854.
