### ISSUE TITLE
Documentation for BoxPlot

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2222]
Add new `compositemark.md` with the following content.

- [ ] Intro to describe that composite marks are shorthand for layered marks.

- [ ] Box
  - [ ] Explain how we determine the box orientation
  - [ ] Explain that `aggregate: "box-plot"` is implicit and that it's the only aggregate function applicable for boxplot's encoding.
  - [ ] Explain how size and color works.
  - [ ] Explain different parts of the compiled box-plot (show full spec examples with roles) and explain how users can use `config.box|boxWhisker|boxMid` to customize style of each parts.

You might want to look at `mark.md` as an inspiration.  Feel free to add other things that I might have overlooked here.

**Comment by g3o2** [comment]
Is it possible to combine other marks than `mark.box-plot` to draw a box plot ? I'm thinking about [Edward Tufte's minimised box plot](http://i.stack.imgur.com/UFPUq.png) or [Leland Wilkinson's dot-box plot](http://r.789695.n4.nabble.com/overlap-dot-plots-with-box-plots-td2134530.html).

**Comment by domoritz** [comment]
@g3o2 Yes, a box plot in Vega-Lite is actually just a macro that expands to layering different marks. Documentation for layering is forthcoming but in short, use the `layer` keyword and assign to it an array of single view specifications. Would you like to send us a pr with an example of a minimized box plot?

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/blob/master/examples/specs/box_plot_minmax_2D_vertical_full.vl.json  might give you an inspiration.

**Comment by g3o2** [comment]
Truly remarkable what you have achieved here! Thanks a lot for the swift reply :-)

**Comment by kanitw** [comment]
This will be fixed in #2264 pretty soon.
