### ISSUE TITLE
link to text table heatmap example on on-line editor does not work

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2224]
[Broken link ?](https://vega.github.io/new-editor/#/examples/vega_lite/text_table_heatmap)

**Comment by domoritz** [comment]
This seems to be a problem with the new editor. CC @mathisonian

**Comment by kanitw** [comment]
I think we removed the text table heatmap example as it should become labels of heatmap.

**Comment by kanitw** [comment]
No longer a problem with https://vega.github.io/editor/#/examples/vega-lite/layer_text_heatmap. 

(The example got renamed though.)
