### ISSUE TITLE
Can we turn off truncation for schema generation

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2228]
The schema currently contains ... like this:

`GenericUnitSpec<\"point\" | \"area\" | \"bar\" | \"line\" | \"text\" | \"tick\" | \"rect\" | \"rule\" | \"circle\" ...`

**Comment by domoritz** [comment]
I don't see where names get clipped in https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts, though.

**Comment by kanitw** [comment]
Looks like our rename script has cloaked this problem, so I'm closing this.
