### ISSUE TITLE
Add document for stack property in encoding.md

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2232]
- [ ] add to the table

- [ ] add a few examples to demo

**Comment by YuhanLu** [comment]
Do you mean `stack` in `PositionFieldDef`? Should I put the example right under the `PositionFieldDef` table?

**Comment by kanitw** [comment]
> Do you mean stack in PositionFieldDef?

Yes

> Should I put the example right under the PositionFieldDef table?

IDK.  It depends.  

Another related task would be read mark.md and see if it still correctly describes stack.

**Comment by YuhanLu** [comment]
I think this one is merged
