### ISSUE TITLE
Correctly apply selection for the box-plot composite mark

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2235]

**Comment by arvind** [comment]
The milestones on this confuse me -- I thought our consensus was to not support selections for composite mark types for 2.0?

**Comment by arvind** [comment]
In fact, my notes suggest we'd decided on releasing box plots encodings as part of 2.1 to provide a more cohesive overall experience for users. Did this change at some point?

**Comment by kanitw** [comment]
>  I thought our consensus was to not support selections for composite mark types for 2.0?
> In fact, my notes suggest we'd decided on releasing box plots encodings as part of 2.1 to provide a more cohesive overall experience for users. Did this change at some point?

Hmm I don't remember we agree on this.  I remember saying that we should support selection of the category of the box plot, which is not aggregate field. The latter is then universally not supported.

**Comment by kanitw** [comment]
> support selection of the category of the box plot

This should be trivial to try. I could help trying to add.

**Comment by kanitw** [comment]
This is a part of the bigger https://github.com/vega/vega-lite/issues/3443, closing as it's redundant.
