### ISSUE TITLE
Update table with new interface name

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2240]
After a lot of changes, some names of interfaces changed and those tables need to be updated

**Comment by kanitw** [comment]
You can do the following rename in `replaceschema`:

- `FieldDef<Field>`  => `FieldDef`
- `LegendFieldDef<Field, string>` => `LegendFieldDef<string>` (And similar for other things that extends `FieldDef` -- as in the schema `FieldDef<F>` should be always `FieldDef<Field>` so we can just make it not generic in the schema.)

- Make travis check that the output schema does not contain FieldDef<Field>

Related questions
- [ ] I wonder if `sed` requires regular expressions?  If not, writing a replace scripts where we directly like string to match will be a bit easier to modify in the longer term. 
- [ ] Can we rename `replaceschema` to `schema:rename`?
