### ISSUE TITLE
Correctly merge scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2251]
(Currently we just always use the first axis/legend)

- [x] Consider precedence of explicitly specified properties
- [x] Consider if there are conflicting properties

- [x] when merging band vs point scale, favor band scale as it produces better selection 

- [ ] For example, layer_histogram's x-scales somehow have not been merged.

- [x] `parseDomain` must be called separately after `parseScale` since `domain` depends on `type` and will persist after merging.  (Other properties that depends on type can get overridden.)   
- [x] `initSize` should become a part of parse and come after `parseScale` as size (`width`/`height`) depends on `rangeStep`
- [x] `initMarkDef` should not depend on scale (as it can have incorrect scale type) -- maybe `initMarkDef` should simply become a part of `parseMark`
  - orient depends on scale.type (whether the type is discrete or not)   
  - parsePathOrder depends on orient, but is a part of `parseData`, which happens before `parseMark`

- [x] get rid of initResolve()

- [x] rename
  - [x] layout/index => layout/assemble
  - [x] scale.rules => properties

- [x] Don't read `width` / `height` directly

**Comment by domoritz** [comment]
- [ ] Be smarter about merging the grid for dual axis charts.

**Comment by domoritz** [comment]
We could be smart about things and use a single scale and axis if the layers use the same field and transformations.

**Comment by kanitw** [comment]
> We could be smart about things and use a single scale and axis if the layers use the same field and transformations.

Isn't our default is union scale already?

**Comment by domoritz** [comment]
> Isn't our default is union scale already?
Not for concat.

**Comment by kanitw** [comment]
Yeah but your comment above discusses layer

>  if the __layers__ use the same field and transformations.

**Comment by kanitw** [comment]
Looks like a lot of things depends on scale init, but to make sure that we treat scale merging correctly, we will have to remove a lot of these dependencies.  (I'm still investigating -- will update more.)

**Comment by kanitw** [comment]
- [ ] when merging band vs point scale, favor band scale as it produces better selection

**Comment by kanitw** [comment]
- [ ] `parseDomain` must be called separately after `parseScale` since `domain` depends on `type`.

**Comment by kanitw** [comment]
- [ ] initMarkDef should not depend on scale (as it can have incorrect scale type)

**Comment by kanitw** [comment]
- [ ] Consolidate initScale with initSize (previously https://github.com/vega/vega-lite/issues/1802)

**Comment by kanitw** [comment]
- [ ] initSize should become a part of parse and come after parseScale as size depends on rangeStep

**Comment by kanitw** [comment]
- [ ] remove references to `model.scale()`
  - [ ] src/compile/layout/index.ts
  - [ ] src/compile/mark/tick.ts
  - [ ] src/compile/scale/domain.ts
  - [ ] src/compile/scale/parse.ts
  - [ ] src/compile/scale/range.ts
