### ISSUE TITLE
Sort by count is not working

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2253]
While I was working on #2069, I found that sorting by count field is not working like before.

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "*",
        "type": "quantitative",
        "aggregate": "count"
      },
      "y": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "descending","op": "count"}
      }
    }
  }
```

![image](https://cloud.githubusercontent.com/assets/6269456/25297091/986721f2-26a0-11e7-9cb6-8ab2b7699812.png)

From my short investigation on compiled vg spec, I think that
1) source_0's aggregation doesn't return `as` to be referred from the below.
2) `scale.domain.order` refer a wrong field name.

**Comment by kanitw** [comment]
@NeelMohapatra  can you help investigate if this is a Vega bug.

**Comment by kanitw** [comment]
Part of #2390
