### ISSUE TITLE
Change Interactive SPLOM example

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2281]
- [ ] Separate SPLOM with brush, splom with multiple interactions
- [ ] Make 3x3

**Comment by arvind** [comment]
I'll note that we have separate brushing and pan/zoom examples. I can break apart the current SPLOM example if you feel strongly about it, but I'm not sure three mostly similar examples is very useful?

**Comment by domoritz** [comment]
We can ignore the first point of this issue then.

**Comment by kanitw** [comment]
> I'll note that we have separate brushing and pan/zoom examples. I can break apart the current SPLOM example if you feel strongly about it, but I'm not sure three mostly similar examples is very useful?

I don't feel strongly about the first one.  Let's say if it happens to be natural for you to break them apart to explain them in the documentation / tutorial, then let's do it ;)
