### ISSUE TITLE
Axis title can be "jumpy" during pan/zoom interactions

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#2282]
To reproduce, pan and zoom in this example:
https://vega.github.io/new-editor/?mode=vega-lite&spec=panzoom_scatter

To stabilize axes, we could adjust the default configuration:
- Set the y-axis minExtent to something reasonable (40px?) that accommodates a wider array of labels without the need to reposition the title.
- Include a meaningful maxExtent so that the title does not jump out of the display. Possibly even lock this to the same value as minExtent, so that the title will not ever move.

**Comment by kanitw** [comment]
@jheer   Is this still the case?  I try to reproduce but I don't see a problem or maybe I overlook something.

**Comment by kanitw** [comment]
Fixed in #2673
