### ISSUE TITLE
Overview + Detail example is broken; need to redeploy

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#2285]
I discovered a bug in `vlIntervalDomain` (in vega-parser) that was breaking the O+D example. I've published a new vega-parser version (beta.50) with a fix. However, you will need to redeploy the editor and also add an image thumbnail for the example.

**Comment by domoritz** [comment]
I just pushed the update to the new editor (see https://vega.github.io/new-editor/?mode=vega-lite&spec=overview_detail). The website will be updated with the next Vega release.
