### ISSUE TITLE
Brush interactions exhibit buggy behavior

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#2288]
- https://vega.github.io/new-editor/?mode=vega-lite&spec=interactive_splom
Translating the brush (with shift-drag) can result in distortion / non-uniform sizing of the visual brush extents, for example after panning/zooming a display. I expect brush extent to stay constant when translating the interval selection.

- https://vega.github.io/new-editor/?mode=vega-lite&spec=overview_detail
Dragging out a brush works fine, but when I attempt to translate or scale the brush it disappears entirely. Possibly due to an issue with handling the temporal data type?

**Comment by kanitw** [comment]
Fixed in #2377
