### ISSUE TITLE
Decide on geo syntax in Vega-Lite

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#2290]
## 1. Name for geo mark
Options:
- [x] `geoshape` (using [geoshape](https://vega.github.io/vega/docs/transforms/geopath/) transform)
- [ ] `geopath` or `path` (using [geopath](https://vega.github.io/vega/docs/transforms/geopath/) transform)

> Tentative decision: `geoshape`

## 2. Joining shape data with geo-encoded data
In Vega, to create a choropleth, we use multiple data sources and a `lookup` transform:
```
"data": [
    {
      "name": "unemp",
      "url": "data/unemployment.tsv",
      "format": {"type": "tsv", "parse": "auto"}
    },
    {
      "name": "counties",
      "url": "data/us-10m.json",
      "format": {"type": "topojson", "feature": "counties"},
      "transform": [
        { "type": "lookup", "from": "unemp", "key": "id", "fields": ["id"], "as": ["unemp"] },
        { "type": "filter", "expr": "datum.unemp != null" }
      ]
    }
  ],
```
However, Vega-Lite doesn't support using multiple data sources. So we must decide how we want to support encoding color for shapes based on a field. Tentative options:
- [x] support some kind of lookup in Vega-Lite, and inside the lookup, describe the "dependent" data source (think, nested data)
  <details>
  <summary>Sample Spec</summary>
  <pre><code>
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
    "mark": "geoshape",
    "data": {
      "url": "data/us-10m.json",
      "format": {
        "type": "topojson",
        "feature": "counties"
      }
    },
    "transform": [{
      "lookup": "id",
      "field": "id",
      "as": ["newFieldName1", "newFieldName2"],
      "from": {
        "url": "data/unemployment.tsv",
        "format": {
          "type": "tsv",
          "parse": "auto"
        }
      }
    }],
    "projection": {
      "type": "albersUsa"
    },
    "encoding": {
      "color": {
        "field": "rate"
      },
      "opacity": {
        "value": 0.7
      }
    }
  }
  </code></pre>
  </details>

- [ ] source the geo-shape data (topojson) inside the projection instead of as a first-level data
  <details>
  <summary>Sample Spec</summary>
  <pre><code>
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
    "mark": "geoshape",
    "data": {
      "url": "data/unemployment.tsv",
      "format": {
        "type": "tsv",
        "parse": "auto"
      }
    },
    "projection": {
      "type": "albersUsa",
      "field": "id",
      "data": { // other possible names: from, geodate
        "key": "id",
        "url": "data/us-10m.json",
        "format": {
          "type": "topojson",
          "feature": "counties"
        }
      }
    },
    "encoding": {
      "color": {
        "field": "rate"
      },
      "opacity": {
        "value": 0.7
      }
    }
  }
  </code></pre>
  </details>

> Tentative decision: lookup
## 3. Support `field` property in geoshape/geopath
The `field` property in a `geoshape` transform is to specify which field in the provided data contains the geojson data. This answer somewhat depends on how we answer **2**, but supposing we choose some kind of lookup model, or at least want to allow people to preprocess geo-data where some field has geojson data and others do not--where should the person using Vega-Lite specify this field.

Options:
- [x] since its an encoding of "field" to "shape" it should be inside of encode, and either use the `shape` channel or a new `path` channel if we decide on geo-path.
  <details>
  <summary>Sample Spec</summary>
  <pre><code>
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
    "mark": "geoshape",
    "data": {
      "url": "data.json" // some composite, pre joined data
    },
    "projection": {
      "type": "albersUsa"
    },
    "encoding": {
      "shape": { // optional encoding, only needed for composite data
        "field": "gjShape" // field with geojson data
      },
      "color": {
        "field": "rate"
      },
      "opacity": {
        "value": 0.7
      }
    }
  }
  </pre></code>
  </details>

  Exact naming of encoding channel is TBD. Also, should we include "`"type":"geojson"` in channel? Fairly implicit, but was explicitly included in previous implementation
  
- [ ] similar to how `feature` is implemented inside of topojson data, we could allow for an additional property inside the data (or inside the projection) specifying which field contains the geojson. That way it fits the "data" paradigm, and doesn't confuse with being an encoding channel.
  <details>
  <summary>Sample Spec</summary>
  <pre><code>
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
    "mark": "geoshape",
    "data": {
      "url": "data.json", // some composite, pre joined data
      "geojson": "gjShape" // field with geojson data
    },
    "projection": {
      "type": "albersUsa"
    },
    "encoding": {
      "color": {
        "field": "rate"
      },
      "opacity": {
        "value": 0.7
      }
    }
  }
  </pre></code>
  </details>

> Tentative decision: encoding

**Comment by domoritz** [comment]
Can you elaborate on the second option for 2 and explain how the user defines how users customize the join? I think it would be good to have example specs for the 6 cases above. I'm having a hard time imagining what exactly the user has to write.

**Comment by willium** [comment]
sure. i'll put together some sample specs

**Comment by g3o2** [comment]
How about `map` mark ? (as a name)

**Comment by domoritz** [comment]
@g3o2 interesting idea but we will go with `geoshape` as map is an overloaded term (map as in mapping, map for the whole map, not just a single shape).

**Comment by domoritz** [comment]
Since we have decided this, I'm closing the issue.
