### ISSUE TITLE
Lookup transform

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2298]
```js
{
    "lookup": "key in source",
    "from": {"data": Data, key: "key in from", "fields" : ["a", "b"]},
    "as": ["foo", "bar"]
}
```

* `as` is optional
* If `fields` is not specified, `as` has to be a string and we put the whole object into the data. To enforce this, use a union type (`|` in TypeScript)

The trickiest bit is figuring out how to create the right dataflow. You need to add a separate source node. Unfortunately, we have to break the assumption that every dataflow node has a single parent for this operator. To make it less painful, I think we can just use a reference to the source in the lookup node (not as a parent) and add lookup as a child of the source it references. I think the rest should just work (TM).

**Comment by kanitw** [comment]
- [ ] indexed chart example
