### ISSUE TITLE
Support width for vconcat and height for hconcat

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2306]

**Comment by domoritz** [comment]
I think if we implement a generic logic in https://github.com/vega/vega-lite/pull/2304, we can use it here so I'll wait for that.

**Comment by domoritz** [comment]
Also, how should this work if the child is not a layer or a unit? For example, what is the child is a facet or a itself a repeat. In that case you cannot set the width/height.

**Comment by kanitw** [comment]
I think let's not do it at all as it will be confusing.  Even if the child is unit, vconcat can only have width and hconcat only have height -- this is pretty weird.

**Comment by domoritz** [comment]
Well, with my proposed algorithm, that is okay. https://github.com/vega/vega-lite/issues/2308
