### ISSUE TITLE
Size algorithm

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2308]
I am proposing the following algorithm to determine the size of a view. Since we only allow bottom up sizing, the only views who can be sized are units. However, we still allow `width` and `height` at every level. When we want to determine the `width`/`height` of a unit view, we walk up the parents until we find a definition. If no parent defines a size property, we use the config (which we may call `config.width` and `config.height`).

**Comment by kanitw** [comment]
1) `facet`, `repeat`, etc still should not have `width` and `height` as people will not expect `width`/`height` of them to mean width/height of a single view.    

2) Maybe call it `config.width` and `config.height` would give expectation that it's top-down.  We need better name.

**Comment by kanitw** [comment]
Actually instead of look up parent which is pretty complicated, we can just pass it down in the constructor like config.

**Comment by domoritz** [comment]
> Actually instead of look up parent which is pretty complicated, we can just pass it down in the constructor like config.

Well, @arvind already implemented looking into parents for selections. We should build one infrastructure and use it for everything. I don't think it's that complicated, actually. It's more a matter of performance. 

And if we do this only for layer anyway, then it's really not a big deal.

**Comment by kanitw** [comment]
Meh. I already got it right and way less complicated.

**Comment by domoritz** [comment]
Well, "I already got it right" is not correct :-P At least there was a bug last time I checked.

**Comment by kanitw** [comment]
Well, you haven't checked the latest update

**Comment by domoritz** [comment]
lol, you basically implemented this proposal (or at least what I meant) so I'm happy.
