### ISSUE TITLE
What is the json-e file?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2316]
This is in my build folder:

<img width="217" alt="screen shot 2017-04-28 at 23 19 19" src="https://cloud.githubusercontent.com/assets/589034/25553485/21784156-2c69-11e7-83fa-40d76cb19b9f.png">

**Comment by kanitw** [comment]
Is it related to `sed`?

**Comment by domoritz** [comment]
Probably. I haven't looked further into it.
