### ISSUE TITLE
Scale and axis resolution

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2319]
Port over resolve from https://github.com/vega/vega-lite/pull/1304/files

**Comment by domoritz** [comment]
We already have layer. I just implemented repeat. Missing one is facet. 

I don't see this ever working for concat but I think that's okay.

**Comment by kanitw** [comment]
> I don't see this ever working for concat but I think that's okay.

I don't understand this comment.  If it works for repeat, why not for concat?

**Comment by domoritz** [comment]
I implemented resolve for layer, repeat, facet, and concat. 

The one this missing is correctly implementing merging of axes in repeat and concat. Legends are already merged correctly. Look at how it's done in facet.

**Comment by kanitw** [comment]
There are more aspects missing, but this issue is redundant with #2473
