### ISSUE TITLE
Incorrect single selection predicate for repeated binned views

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2320]
I'd expect to be able to just replace the interval selection with a single selection and clock on bars to select them. 

However, the spec below throws an error: `Uncaught Error: Duplicate signal name: "sel"`

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/flights-2k.json",
    "format": {"parse": {"date": "date"}}
  },
  "transform": [{"calculate": "hours(datum.date)", "as": "time"}],
  "repeat": {"column": ["distance", "delay", "time"]},
  "spec": {
    "layer": [{
      "selection": {
        "sel": {"type": "single", "encodings": ["x"]}
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": {"repeat": "column"},
          "bin": {"maxbins": 20},
          "type": "quantitative"
        },
        "y": {"aggregate": "count", "type": "quantitative"}
      }
    }, {
      "transform": [{"filter": {"selection": "sel"}}],
      "mark": "bar",
      "encoding": {
        "x": {
          "field": {"repeat": "column"},
          "bin": {"maxbins": 20},
          "type": "quantitative"
        },
        "y": {"aggregate": "count", "type": "quantitative"},
        "color": {"value": "goldenrod"}
      }
    }]
  }
}

```

**Comment by arvind** [comment]
The duplicate signal name issue is addressed in de3eb9b. However, this issue highlights a similar issue as #2284: building the predicate over the raw (unbinned) domain yields a broken interaction. Here, by switching from an interval to a single selection, the underlying data tuples for each of the histograms no longer contains a `distance`, `delay` or `time` fields which is what the single selection expects to interactively pick.
