### ISSUE TITLE
Selection should be empty when there is no brush

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2321]
I would like to be able to set a selection to be empty when there is no brush. Right now every point is in the selection when there is no brush for example in https://vega.github.io/new-editor/?mode=vega-lite&spec=brush. I see why the default makes sense in this case but this should be configurable. 

![brush](https://cloud.githubusercontent.com/assets/589034/25558080/5d64fa9a-2cd4-11e7-866a-912034df1888.gif)

**Comment by arvind** [comment]
Fixed with #3038.
