### ISSUE TITLE
publish 2.0.0 beta to npm?

### ISSUE THREAD

**Issue by skokenes** [vega/vega-lite#2323]
The vega 3.0.0 beta is up to date on npm, but the latest vega-lite version on npm is only 1.3.1. Can the vega-lite 2.0.0 beta be published to npm?

**Comment by domoritz** [comment]
It is already on npm as a prerelease. You get it via `npm install vega-lite@2.0.0-beta.1` for example (latest version number is at https://github.com/vega/vega-lite/releases).

**Comment by domoritz** [comment]
We might switch to official npm releases soon.

**Comment by domoritz** [comment]
We decided to change this with beta 2. You will automatically get it when you run `npm install vega-lite`. https://github.com/vega/vega-lite/pull/2324
