### ISSUE TITLE
axes formatting not working with vega-embed

### ISSUE THREAD

**Issue by skokenes** [vega/vega-lite#2329]
Following the instructions on [https://vega.github.io/vega-lite/usage/embed.html](https://vega.github.io/vega-lite/usage/embed.html), I produced [this block](https://bl.ocks.org/skokenes/81dcbec773cea5a100fc3fed8e62e54b).

The spec in that block has some random formatting applied to the axes (red ticks, slightly thicker, different font). The rendered chart does not show any of these properties. If you click "Open in Editor", the tick properties render properly but the font does not change.

**Comment by domoritz** [comment]
Yeah, something funky is going on with the config. 

This spec works the fist time I parse but as soon as I change the renderer for example, the formatting disappears. I suppose that the problem is that the config needs to be passed separately from the spec. This is definitely a bug! 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "selection": {"brush": {"type": "interval","encodings": ["y"]}},
  "encoding": {
    "x": {"field": "a","type": "nominal"},
    "y": {
      "aggregate": "average",
      "field": "b",
      "type": "quantitative",
      "axis": {"title": "Average of b"}
    }
  },
  "config": {
    "axis": {
      "labelFont": "serif",
      "labelFontSize": 16,
      "tickWidth": 3,
      "tickColor": "red"
    }
  }
}
```

**Comment by kanitw** [comment]
I think it's more like a bug in the editor than a Vega-Lite bug.

**Comment by domoritz** [comment]
I think it's a problem I'm Vega embed. I'm looking into it.

**Comment by domoritz** [comment]
It was a bug in Vega-Embed that I just fixed. I will make a release.

**Comment by domoritz** [comment]
I just deployed a fix to https://vega.github.io/new-editor/, btw.
