### ISSUE TITLE
Do not init all resolve for all channels.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2331]
Follow up for this thread: https://github.com/vega/vega-lite/pull/2327#discussion_r114066873.

**Comment by domoritz** [comment]
wasteful -> confusing (I don't care about perf here)

**Comment by kanitw** [comment]
By initing resolve, we cannot choose not to merge scales if their types are conflicting.  
This can come after 2.0 though.

**Comment by kanitw** [comment]
>By initing resolve, we cannot choose not to merge scales if their types are conflicting.
This can come after 2.0 though.

We actually can, but the problem is that their corresponding axis/legend would not know from the resolve value.

**Comment by kanitw** [comment]
We might be able to work around this by check if scale component exist.

**Comment by kanitw** [comment]
Fixed in #2642
