### ISSUE TITLE
implement `axis.titleAngle`

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2333]
It would great if it was possible to read the `y` axis title without head tilting.

**Comment by kanitw** [comment]
Thanks.  I'm re-filing this in Vega-parser as the right place to implement it would be in the config.axis, which is in Vega parser code.  

https://github.com/vega/vega-parser/issues/28

**Comment by g3o2** [comment]
I saw yesterday that `titleAngle` has already been implemented in `vega` but it is not suggested by the `vega-lite`'s schema and documentation. Nonetheless, following Jeffrey Heer's reply, I've given it a try and it works out-of-the-box indeed. Thanks!

**Comment by domoritz** [comment]
@g3o2 The config has to be passed to Vega separately. See https://vega.github.io/vega/docs/config/. Vega-Embed takes care of this for you.

**Comment by kanitw** [comment]
@domoritz I think @g3o2  is aware of this but Vega-Lite schema and docs are simply a bit outdated https://github.com/vega/vega-lite/issues/2342

**Comment by domoritz** [comment]
I like to be a bit more verbose when I respond to issues in case somebody else finds this vis google in the future when they wonder about this problem. But yes, I agree that the docs need to be updated.

**Comment by g3o2** [comment]
Thank you for your confidence, @kanitw, yet I'm afraid @domoritz correctly assumed that I was not aware that vega-lite passed on the config separately :-)

From that perspective, my question was not clear enough: is there any practical reason why the `config` is passed on separately? Or put differently: why not pass it on as a top-level vega `config` block?

If I understand correctly, the [`vega-parser` API reference](https://github.com/vega/vega-parser) specifies that the configuration can also be defined as a top-level `config` block, which then takes precedence over any configuration which is passed on separately via the parse method.

In my opinion, using the "top-level vega config block" method provides two significant advantages over the parse method in the context of vega-lite:

* the vega-lite `config` block becomes visible in the compiled `vega` spec, which enhances transparency and eases debugging;
* it allows for additional theming via the parse method for all those parts which are not part of the top-level vega-lite config block. The process is predictable because the top-level vega config block takes precedence over the configuration provided via parse. That said, it is also unlikely that a user would specify a standard theme by adding it to each vega-lite spec. Most likely, the said user would want to load such a theme via the parse method, whereas additional tweaking in the context of the graphic would be performed in the top-level vega-lite `config` block.
