### ISSUE TITLE
[layering] `axis` only reacts when defined in the first layer

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2334]
When defined in another layer such as here below, e.g. the `title` remains unaffected. 

Should the other layers simply not be allowed to have any axis definition, all the settings having to be defined in layer 1 ? The schema does not appear to test for this at the moment.
 
__tested with__: vega 3.0.0-beta.30, vega-lite 2.0.0-beta.2, vega-embed 3.0.0-beta.14

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-weather.csv"},
  "layer": [
    {
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal",
          "timeUnit": "month"
        },
        "y": {
          "aggregate": "mean",
          "field": "precipitation",
          "type": "quantitative"
        }
      }
    },
    {
      "mark": "rule",
      "encoding": {
        "y": {
          "aggregate": "mean",
          "field": "precipitation",
          "type": "quantitative",
          "axis" : {"title": "test"}
        },
        "color": {"value": "red"},
        "size": {"value": 3}
      }
    }
  ]
}
```

**Comment by kanitw** [comment]
Thanks for reporting.  We will actually support this as a part of https://github.com/vega/vega-lite/issues/2251, but haven't implemented it yet.

**Comment by g3o2** [comment]
Oops, apologies for having missed the other issue.

**Comment by kanitw** [comment]
No worries! Thank you so much for helping us test things. ;)
