### ISSUE TITLE
is parse:auto better than manually mapping field with type 

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2337]
Vega supports `parse:auto` and it will do the type mapping for user. Vega-lite now doesn't support auto but it allows user to not specifying `parse`. Vl will do the mapping by itself than using vega's `parse:auto`.
Is there a reason why not just passing `parse:auto` to vega?

**Comment by kanitw** [comment]
From my testing, if you load a JSON file with a date field (such as `cars.json`) and have `parse: "auto"`, the date field will be just a string.   Thus, `parse: "auto"` is not better.

@YuhanLu  Could you please verify this?  If you find the same result, then we can close this issue.

**Comment by YuhanLu** [comment]
How did you test it will become a string? if `parse: auto` is not better than manually mapping, why does vega support it?
