### ISSUE TITLE
Tooltips for lines and area

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2341]
We should automatically rewrite the spec to add a layer with transparent points as described in https://github.com/vega/vega-lite/issues/1921#issuecomment-298678178

**Comment by kanitw** [comment]
Hovering over invisible point is kinda difficult anyway and readers might be confused why they can hover only some part of the line.  Thus, this seems too magical.

We should just throw warning and suggests user to overlay line/area with points to support hovering individual data points.

**Comment by domoritz** [comment]
idk, it's not more magical than having to wait a bit to see the tooltips on bars. Also, if vega-tooltip supports the tooltip channel, this will work better.

**Comment by kanitw** [comment]
> wait a bit to see the tooltips on bars

That's orthogonal to this problem and is simply just SVG's limitation that we have no control over.

**Comment by domoritz** [comment]
> Hovering over invisible point is kinda difficult anyway and readers might be confused why they can hover only some part of the lines.

Having a tooltip for lines if the tooltip is for a field that we are not grouping by would not make any sense to be shown for a line segment, let alone the whole line. So I think only having tooltips around the points that are defined is fine. 

To explain what "magic" I am proposing. If the user specifies a tooltip for something we are not grouping by, then we add the point overlay. Otherwise, we don't have to do anything as the tooltip is the same for the whole line. 

If you feel strongly about it, we definitely have to add some logic to detect which case we have so that we can show the right warning.

**Comment by g3o2** [comment]
Maybe just documenting this limitation would be sufficient, I can personally live with that. Maybe suggest a workaround using layer.

**Comment by kanitw** [comment]
@sirahd  -- I wonder if we have documented about this?

**Comment by kanitw** [comment]
Redundant with https://github.com/vega/vega-tooltip/issues/120, i'll close this one since this issue should be in Vega-Tooltip anyway.
