### ISSUE TITLE
Time scale nice can be a little funny

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2346]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {
    "values": [
      {"date": "10 Oct 2011 22:48:00"},
      {"date": "11 Oct 2022 23:00:00"}
    ],
    "format": {"type": "json"}
  },
  "mark": "point",
  "encoding": {
    "x": {"timeUnit": "date","field": "date","type": "temporal"},
    "y": {"timeUnit": "hours","field": "date","type": "temporal"}
  }
}
```

<img width="266" alt="screen shot 2017-05-02 at 1 47 20 pm" src="https://cloud.githubusercontent.com/assets/11696585/25638650/e9f94644-2f3d-11e7-82a7-bd73a9a27db5.png">

**Comment by kanitw** [comment]
More likely a vega issue, but I'm posting it here so we can investigate more first.

**Comment by domoritz** [comment]
This is definitely an issue with how you specify the axis formatting. The two solutions are: use fewer ticks, or set a label formatting that includes more than just the day.
