### ISSUE TITLE
text mark is center aligned and not customizable 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2349]

**Comment by YuhanLu** [comment]
Do you want to change it to left aligned by default? do we support customized alignment by introducing something like text.align?

**Comment by kanitw** [comment]
If we don't have default align set, it should be left by default (based on Vega default).  
Then users can already use `config.text.align` to customize.

Currently users cannot use config to customize because we output `align = 'center'` in the Vega output.

**Comment by kanitw** [comment]
From testing, looks like we can already customize text align with `config.text.align`

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "transform": [{"calculate": "datum.Origin[0]","as": "OriginInitial"}],
  "mark": "text",
  "encoding": {
    "x": {"field": "Horsepower","type": "quantitative"},
    "y": {"field": "Miles_per_Gallon","type": "quantitative"},
    "color": {"field": "Origin","type": "nominal"},
    "text": {"field": "Origin","type": "nominal"}
  },
  "config": {
    "text": {"align": "right"}
  }
}
```
