### ISSUE TITLE
What/how to build?

### ISSUE THREAD

**Issue by javadba** [vega/vega-lite#2363]
The documentation provides no information on how/what to build in this project.  I have been messing around with e.g.    `npm run-script build`  and other attempts.. but they fail miserably.   I also see a `bower.json`, `Gemfile`, `package.json` and wonder if that comes into play or not.

Need some kind of roadmap here. Thanks.

**Comment by NeelMohapatra** [comment]
You can run 'npm run build'. It says so in 'Contributing.MD'

**Comment by javadba** [comment]
I had already tried that.

$npm run build

> vega-lite@1.3.1 build /xfer/vega-lite
> browserify src/vl.ts -p tsify -d -s vl | exorcist vega-lite.js.map > vega-lite.js

sh: browserify: command not found
sh: exorcist: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vega-lite@1.3.1 build: `browserify src/vl.ts -p tsify -d -s vl | exorcist vega-lite.js.map > vega-lite.js `
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vega-lite@1.3.1 build script 'browserify src/vl.ts -p tsify -d -s vl | exorcist vega-lite.js.map > vega-lite.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vega-lite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/vl.ts -p tsify -d -s vl | exorcist vega-lite.js.map > vega-lite.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vega-lite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vega-lite
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/boescst/.npm/_logs/2017-05-14T23_32_16_818Z-debug.log

**Comment by NeelMohapatra** [comment]
Weird. Did you run 'npm install' first?

**Comment by javadba** [comment]
I am new to node/ npm. So doing `npm install` *before* any "build" is
counter-intuitive (from maven / sbt background) .  It appears to have
resolved.  I will look again at the docs, but can say I went through a few
times and it was not clear

2017-05-14 16:33 GMT-07:00 Swojit Mohapatra <notifications@github.com>:

**Comment by javadba** [comment]
Still can not get anything to display on web page.

So where is the documentation for building - i looked yet a fifth time:
here is what I see

https://vega.github.io/vega-lite/docs/

The word "build" does not appear.

2017-05-14 16:38 GMT-07:00 Stephen Boesch <javadba@gmail.com>:

**Comment by javadba** [comment]
Here is what shows up on the SimpleHTTPServer console when accessing `test-gallery.html`. 

Note that due to the issues I had reverted to using branch `1.x` so this is for that branch:

    Serving HTTP on 0.0.0.0 port 8007 ...
    127.0.0.1 - - [14/May/2017 16:40:15] "GET / HTTP/1.1" 200 -
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /test-gallery.html HTTP/1.1" 200 -
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /site/static/test-gallery.css HTTP/1.1" 200 -
    127.0.0.1 - - [14/May/2017 16:40:20] code 404, message File not found
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /bower_components/d3/d3.min.js HTTP/1.1" 404 -
    127.0.0.1 - - [14/May/2017 16:40:20] code 404, message File not found
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /bower_components/vega/vega.min.js HTTP/1.1" 404 -
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /vega-lite.min.js HTTP/1.1" 200 -
    127.0.0.1 - - [14/May/2017 16:40:20] code 404, message File not found
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /bower_components/vega-embed/vega-embed.js HTTP/1.1" 404 -
    127.0.0.1 - - [14/May/2017 16:40:20] code 404, message File not found
    127.0.0.1 - - [14/May/2017 16:40:20] "GET /site/static/test-gallery.js HTTP/1.1" 404 -

**Comment by NeelMohapatra** [comment]
That documentation is written for people who intend to learn how to use Vega Lite. If you want to develop Vega Lite, refer to this https://github.com/vega/vega-lite/blob/master/CONTRIBUTING.md

**Comment by javadba** [comment]
Ok thanks.  A note: this structure and process are foreign to jvm people.  A simple way to "help" us would be to have a link of some sort for a "How to build".  That should be in the user docs since we do not know there were a "CONTRIBUTING.md". I saw that file but it is not the standard for build instructions to be in there.

**Comment by javadba** [comment]
The build instructions in CONTRIBUTING.md are good.  I do however have a separate build issue. I will make another issue specifically for that.  

Suggestion here is to include link to CONTRIBUTING.md from the README.md and then this particular issue/question would not have seen light of day.
