### ISSUE TITLE
Minimum html page (with javascript scripts) to display visualization 

### ISSUE THREAD

**Issue by javadba** [vega/vega-lite#2365]
I have been searching for how to display a single vega-lite visualization given its json declaration. 
This would afaict be an html page with the requisite vega and vega lite and vega-lite embed JS scripts.  

Is there a simple html page including the requisite javasript libraries in which it is possible to simply cut and paste in a vega-lite json snippet and then the viz works?

Building the site from scratch is a challenge: I currently have a library that does not build on 64 bit mac and no clear resolution from google searches.  https://github.com/vega/vega-lite/issues/2364

So a simplified "end-user" approach of just the min web page  would be helpful.

**Comment by kanitw** [comment]
Our usage guide https://vega.github.io/vega-lite/usage/embed.html includes a link to a [block](https://bl.ocks.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9). 

You can also use the online [vega-editor](https://vega.github.io/new-editor/?mode=vega-lite) to experiment with things.

**Comment by javadba** [comment]
The block is perfect. Thanks.

2017-05-14 19:45 GMT-07:00 Kanit Wongsuphasawat <notifications@github.com>:
