### ISSUE TITLE
Unable to add annotation marks and link onto chart display (`href` channel)

### ISSUE THREAD

**Issue by rapport** [vega/vega-lite#2367]
I can't find a way to add an annotation mark with a hyperlink onto the chart data. I think many users will need this. Is there any way to do this? If not can this be added?

I simply want to add annotation marks to some of the outlier points on the chart with a hyperlink to explain what happened at that point. I think I have a workaround adding in the marks into the SVG with JavaScript  after it has created the chart but I think it would be far better to write the annotations while processing the data in vega-lite 2.0 if possible!

**Comment by domoritz** [comment]
This is a great idea. Can you send a pull request with the `href` channel similar to https://github.com/vega/vega-lite/pull/2132? Maybe @doug can help.

**Comment by domoritz** [comment]
https://vega.github.io/vega/docs/marks/symbol/ documents the href for symbol marks.

**Comment by kanitw** [comment]
If I understand correctly, I think there are two different things requested here:

1. Href channel (you can help add this easily - see https://github.com/vega/vega-lite/pull/2332 like @domoritz suggested)

2. Label or annotation support.  For labeling, we have this in mind and @willium is working on that.  For more general annotation suppor, we have this in mind too but it's more involved to design this so we don't plan to include in 2.0, but will come back to design this at some point in the future.

**Comment by rapport** [comment]
Ideally we would have:
1. a href link location   (which has the bonus that we can pass additional params after '?' in url)
2. icon inline-code (svg, base64 png or something else) I am not sure a mark will stand out enough! 
3. a html/svg 'title' attribute ( for hover over information text ) 
4. an id to get a handle for other interactions

**Comment by willium** [comment]
1. I think this comes with the href channel suggested above
2. can't you achieve this already with the symbol mark?
     ```
{
      "type": "symbol",
      "interactive": false,
      "from": {"data": "capitals"},
      "encode": {
        "enter": {
          "shape": {"value": "M0,.5L.6,.8L.5,.1L1,-.3L.3,-.4L0,-1L-.3,-.4L-1,-.3L-.5,.1L-.6,.8L0,.5Z"},
          "fill": {"value": "#639"}
        },
        "update": {
          "x": {"field": "x"},
          "y": {"field": "y"}
        }
      }
    },
    ```
full: https://vega.github.io/vega/docs/transforms/geopoint.vg.json
3. this is possible using the tooltip channel
4. what do you mean an 'id'? I think this is already possible via selections.

**Comment by rapport** [comment]
Hi, Willium, Many thanks for the pointers on this thread especially with the symbol mark!  My thinking with the id is that this could make it easier to find the symbol/mark for the annotation in the final SVG created... As we want to make some marks on the chart and prompt the users viewing the charts to edit the mark with comments and turn it into a proper annotation (a health event).... I am working on some post process of the charts with JavaScript. Once I have the annotations running on the latest vega-lite 2.0 beta I will put it on our demo site (  http://addon.care ) with a link to edit the chart code. This is a pretty important part of our app as we are detecting unusual data marks  and patterns in health data charts and helping users and their care-givers annotate these marks and convert them into meaningful and actionable health 'events'!

**Comment by rapport** [comment]
I just noticed the layers are now working in the latest build of vega-lite which looks like great progess towards a solution for this. Does anyone know if there any is a way I can overlay charts with a time scatter with hover over label text points? Or is there some way in vega-lite to escape code in vega-lite spec and directly insert code for the vega interpretter along lines above pointed out be willium? Many thanks in advance for any help or pointers!

**Comment by domoritz** [comment]
You can use tooltips? Either via the tooltip channel or the vega-tooltip plugin.

**Comment by rapport** [comment]
Thanks, found it, it looks great and like it should work!... https://github.com/vega/vega-tooltip

**Comment by domoritz** [comment]
cc @sirahd

**Comment by kanitw** [comment]
I think we now have a support for `href` so I'll close this.

**Comment by domoritz** [comment]
Yeah, we have a tooltip and an href channel now.
