### ISSUE TITLE
BinTransform does not support rangeFormula

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2368]
In https://github.com/vega/vega-lite/pull/2360, I didn't add format to support `rangeFormula` and we might need it in the future.

**Comment by YuhanLu** [comment]
https://github.com/vega/vega-lite/blob/2684aeca8f49b53c2a6a7ec12552fa9ddd2f5b1a/src/compile/data/bin.ts#L25 we require `model.axis` or `model.legend` as a guide to get the format from them but in `makeBinFromTransform()` we are not supposed to deal with encoding at all. The solution for this is to let user specify `format` in BinTransform and that might involve a lot changes. So we just don't support rangeFormula for now.

**Comment by kanitw** [comment]
> The solution for this is to let user specify format in BinTransform and that might involve a lot changes.

That's one solution but not a good one.  The better one is to only add bin_range when we use the bin field in a channel that requires range, but that is trickier and doesn't seem like worth doing now.

**Comment by kanitw** [comment]
Close as it's a part of https://github.com/vega/vega-lite/issues/2912
