### ISSUE TITLE
Add Title Config to Vega-Lite schema

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2371]
See https://vega.github.io/vega/docs/config/#title

**Comment by imlucas** [comment]
@kanitw Is this as simple as updating `build/vega-lite-schema.json` or is there more to it? Happy to work on a PR to fix this as I believe it's the root cause of one of the issues currently blocking our upgrade from `1.x` ➡️ `2.x`.

**Comment by domoritz** [comment]
The schema is automatically being generated from the typescript source code. I can take a stab at it today if it's blocking you.

**Comment by imlucas** [comment]
@domoritz aha suspected there was more to it :) Thx! 

(#2131 is a bigger blocker in the long-term)

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega-lite/pull/2444

**Comment by imlucas** [comment]
@domoritz awesome! thx again!
