### ISSUE TITLE
More intuitive grouped bars

### ISSUE THREAD

**Issue by eibanez** [vega/vega-lite#2374]
Reading the documentation I can see that there are several options to deal with bar chart stacking:

- Default: Stacking
- `"stack": "none"`: 
- `"stack":  "normalize"`: 

However, the vega-lite [example](https://vega.github.io/vega-lite/docs/mark.html#grouped-bar-chart) to make grouped bars seems overly complicated. Furthermore, using the `x` channel to be the same as `color` puts unnecessary information in the axis, and prevents creating faceted grouped bars (at least in one direction).

Would it make sense to enable `"stack": "group"` to look closer to the [Vega grouped bar example](https://vega.github.io/vega/examples/grouped-bar-chart/)?

If there is interest, I could put an example of what the vega-lite and the transformed Vega schemas would look like.

**Comment by kanitw** [comment]
Thanks for asking. I agree that the current way to do group bar in Vega-Lite is non-ideal.  
However, group bar is adding offsets to the bars, not stacking so I disagree with the proposed `"stack": "group"` syntax. 

In any case, we have an existing discussion about this topic in this issue: https://github.com/vega/vega-lite/issues/2180.

**Comment by eibanez** [comment]
Sorry, i searched but missed that issue. Very interested to see what happens

**Comment by kanitw** [comment]
@eibanez  No worries. Thanks for voicing your opinion.  At very least, it's nice to hear that people have similar opinions about some current problem(s). :)
