### ISSUE TITLE
Make box2DOrient and box2DParams more general to support 1D boxplots

### ISSUE THREAD

**Issue by mattwchun** [vega/vega-lite#2379]
In `compositemark/boxplot.ts` there exists two functions `box2DOrient()` and `box2DParams()` currently used by only `normalizeBoxPlot()`. `box2DOrient()` returns the orientation of a 2D box-plot given a spec. `box2DParams()` returns `discreteAxisFieldDef`, `continuousAxisChannelDef`, `discreteAxis`, and `continuousAxis` required in `normalizeBoxPlot()`. 

TODO: 
- [ ]  Make these two functions more general so they support 1D boxplots.
- [ ] Rename `box2DOrient()` to `boxOrient()` and `box2DParams()` to `boxParams()`

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2485
