### ISSUE TITLE
Sorting no longer draw from raw data

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2390]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "Cylinders","type": "nominal", "sort": {"op": "count", "field": "*", "order": "descending"}},
    "y": {"aggregate": "count","type": "quantitative"}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/26272014/5f56d6bc-3cc3-11e7-8b3f-ed6e9b20ed99.png)

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/issues/2253 is an instance of this problem.

**Comment by domoritz** [comment]
Weird observation: adding and removing `"field": "*"` changes the order.

**Comment by domoritz** [comment]
Type should be "ordinal". Should we throw an error if the user specifies nominal with sort?
