### ISSUE TITLE
Make sure selection project works with color channel

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2392]
Since this maps to fill/stroke based on mark type, not sure if it works.  
(Maybe it already works--but I'm filing an issue so that we check it for sure.)

**Comment by arvind** [comment]
Yup, it works. E.g., with both `point` and `circle` mark types in the following spec. Selections use `model.fieldDef` to identify the correct field based on the channel, so it should presumably be agnostic to whether color maps to fill or stroke.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Drag out a rectangular brush to highlight points.",
  "data": {"url": "data/cars.json"},
  "selection": {
    "cyl": {
      "type": "single", "encodings": ["color"]
    }
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
      "condition": {"selection": "cyl", "field": "Cylinders", "type": "ordinal"},
      "value": "grey"
    }
  }
}
```
