### ISSUE TITLE
Allow disabling scale with `scale: null`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2400]
Basically, if values of a data field are already color names, we should be able to disable scale.  
(Possibly with `"scale": null`)

For example, we should be able to reproduce this spec:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "red","b": 28}, {"a": "green","b": 55}, {"a": "blue","b": 43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "a", "type": "nominal", "scale": {"range": ["blue", "green", "red"]}}
  }
}
```

using
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "red","b": 28}, {"a": "green","b": 55}, {"a": "blue","b": 43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "a", "type": "nominal", "scale": null}
  }
}
```

**Comment by jheer** [comment]
Or `"scale": "identity"`?

**Comment by kanitw** [comment]
Yeah, I thought about `"scale": {"type": "identity"}` (for consistency), but prefers `null` as it is consistent with how to disable axis and legend.

**Comment by g3o2** [comment]
I would agree with @jheer 's suggestion, as it is more intuitive and explicit regarding its purpose. Disabling a guide (e.g. axis) is also not the same as "disabling" a scale.

**Comment by kanitw** [comment]
@willium since you're projection PR pretty much did half of this already, i'll assign this to you.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3511
