### ISSUE TITLE
Make Vega-Lite examples have proper relative paths

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2418]
So that it works with Vega Desktop

- [ ] Update Gallery
- [ ] Update Vega-Editor

**Comment by domoritz** [comment]
We actually correct the paths in the spec right now, which shows that there is a hack.

What's the corresponding vega issue?

**Comment by kanitw** [comment]
> We actually correct the paths in the spec right now, which shows that there is a hack.

You mean baseUrl is a hack?

> What's the corresponding vega issue?

There is none yet.

**Comment by domoritz** [comment]
> You mean baseUrl is a hack?

Even worse: https://github.com/vega/vega-lite/blob/master/site/static/main.ts#L38. We are not even using it. I don't understand how this even works for nested specs...

**Comment by domoritz** [comment]
On second thought, I think the Vega desktop app should set the base URL. It's hard for us to use relative URLs because our specs appear on different pages at different nesting levels. See https://github.com/vega/vega-lite/pull/2722

Thoughts @kristw?

**Comment by domoritz** [comment]
Reopen if you think we can use relative URLs and should use it instead of baseURLs.

**Comment by kanitw** [comment]
How would the Vega Desktop app know what's the right base URL?

**Comment by kanitw** [comment]
(It seems impossible to do that specifically for specs in Vega-Lite repos.)

Instead different pages that use different nested level should set correct base url.

**Comment by domoritz** [comment]
The base URL is by default the URL of the app. For the Vega-Lite examples, it should be the base directory of the repo. 

I don't see how relative URLs would work.

**Comment by kanitw** [comment]
> The base URL is by default the URL of the app.

But you cannot develop Voyager or Vega-Desktop to set the baseURL differently based on whether it is an example in the vega-lite repository.  I can't think of a reasonable way to ensure that. 

Suppose a spec in directory`/D` points to `data/xxx.json`,  Voyager/Vega-Desktop should better assume that the data is in `/D/data/xxx.json` rather than `~/Application/data/xxx.json` (For Mac).

**Comment by domoritz** [comment]
I guess things work for the website and docs if we set the base URL for be the directory that has the specs.

**Comment by domoritz** [comment]
Instead, we will
* Create a symlink to data in the example spec directory
* Move the normalized specs to `compiled`

**Comment by kanitw** [comment]
@mattwchun  -- Would you have time to help submit a PR to move the normalized specs to `examples/compiled` instead of `examples/specs/normalized`?   Thanks.
