### ISSUE TITLE
Simple bar chart order by value of other field 

### ISSUE THREAD

**Issue by whuthwhut123** [vega/vega-lite#2426]
```
"data": { "url": "/Data/data.json" },
            "mark": "bar",

            "encoding": {
                "y": {
                    "field": "Gemeente", "type": "ordinal",
                },
                "x": {
                    "aggregate": "sum", "field": "Respons", "type": "quantitative",
                    "axis": {
                        "title": "Respons"
                    },
                },               
                "color": { "field": "Provincie", "type": "ordinal" },
            },
            "config": {
                "background": "#f6f6f6",
            },
            "width": 640
        };
```
The above code results in following chart:
![image](https://cloud.githubusercontent.com/assets/5947133/26761376/fb61f890-492d-11e7-94f6-509791c8e0b3.png)

The goal is to have the gemeente (municipality) sorted by provincie (state) and then sorted in alphabetical order.  So the dark blue bars will be under each other etc.

I tried already sort but it gives not the desired result.

**Comment by domoritz** [comment]
If I understand your questions correctly, yes, it should be possible. Does https://vega.github.io/vega-lite/docs/sort.html#ordinal-scale what you want?

**Comment by kanitw** [comment]
Looks like @domoritz has addressed the issue, so I'll close this.  
If it still doesn't work, feel free to re-open the issue.
