### ISSUE TITLE
candlestick charts 

### ISSUE THREAD

**Issue by paintdog** [vega/vega-lite#2432]
Do you support or will you support [candlestick charts](https://en.wikipedia.org/wiki/Candlestick_chart)? Is this already in the roadmap? (Thx.)

**Comment by kanitw** [comment]
Thanks for asking. 

You can use `layer` operator to overlay bar and rule marks to product a candlestick chart, akin to [a box plot](https://github.com/vega/vega-lite/blob/master/examples/specs/layered_box_plot.vl.json) except that you should encode  `y` and `y2` of the bars with open and close values of the security instead showing Q3 and Q1.

I'll leave this issue open as it is probably a good example to add to the example gallery.

**Comment by paintdog** [comment]
Support from the beginning would also be nice. I mean direct support and not a work-around.

**Comment by kanitw** [comment]
@paintdog  The solution I mention is *not* a workaround.  As a visualization grammar, Vega-Lite provides flexible building blocks for composing charts, not a collection of chart templates.  Other visualization grammars such as Protovis uses a similar mechanism for creating [candlestick chart](http://mbostock.github.io/protovis/ex/candlestick.html). 


@NeelMohapatra Please help create an example for this. (You can use the data from the Protovis example.)

**Comment by kanitw** [comment]
Will be done in https://github.com/vega/vega-lite/issues/2505
