### ISSUE TITLE
Add assemble-time way to put the name of a models data source as a expression for fit

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#2437]
As discussed in person with Dom, we need to have the name of a model as a signal expression for the projection property fit. This needs to likely be done at assemble time and can't easily be done with requestDataName on the model

**Comment by domoritz** [comment]
In other places, we assign a temporary name at parse time and then rename again at assemble time.

**Comment by willium** [comment]
That seems sensible here. There might be complications because it's inside a signal expression

**Comment by domoritz** [comment]
Yeah, that's a problem. Can we delay the generation until assemble somehow?

**Comment by domoritz** [comment]
As discussed, we should use a component and assemble the expression when we know the correct name. It's important to request the data name in parse, though so that we do not delete the output node.
