### ISSUE TITLE
Redundant scales with repeat

### ISSUE THREAD

**Issue by arvind** [vega/vega-lite#2438]
With a repeated spec (e.g., the [SPLOM](https://vega.github.io/new-editor/?mode=vega-lite&spec=interactive_splom)), each child contains an x and y scale and then these x and y scales are also collected at the top-level. These additional scales incur a performance penalty if we're panning/zooming them, so we should try to reduce this redundancy if possible.

**Comment by domoritz** [comment]
We are generating the correct resolve in https://github.com/vega/vega-lite/blob/a3492bc80aaf6aac7db3e8b58c3f6097e21f65cd/src/resolve.ts#L63
