### ISSUE TITLE
is the box-plot example spec supposed to work with vega-lite v2.0.0-beta.3 ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2442]
[box-plot example](https://github.com/vega/vega-lite/blob/master/examples/specs/layered_box_plot.vl.json)

I've adjusted the path of the data set to `"data": {"url": "https://vega.github.io/vega-editor/app/data/population.json`

This spec runs flawlessly in vega-editor. Does the latter use a newer version of vega-lite than v2.0.0-beta.3 ? 

When running the said spec with a prepared html file locally, the following warning appears in the browser:

```
[Warning] WARN – "Ignoring an invalid transform: {\"summarize\":[{\"aggregate\":\"min\",\"field\":\"people\",\"as\":\"people_min\"},{\"aggregate\":\"q1\",\"field\":\"people\",\"as\":…" (vega-lite.js, line 1073)
"Ignoring an invalid transform: {\"summarize\":[{\"aggregate\":\"min\",\"field\":\"people\",\"as\":\"people_min\"},{\"aggregate\":\"q1\",\"field\":\"people\",\"as\":\"people_q1\"},{\"aggregate\":\"q3\",\"field\":\"people\",\"as\":\"people_q3\"},{\"aggregate\":\"max\",\"field\":\"people\",\"as\":\"people_max\"},{\"aggregate\":\"median\",\"field\":\"people\",\"as\":\"people_median\"}],\"groupby\":[\"age\"]}."
```

Also worth noting that the schema of beta.3 does not seem to recognise the `summarize` or `groupby` transform in the box-plot example.

Here is the header of my html file.

```
<script src="https://d3js.org/d3.v4.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.0-beta.32/vega.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0-beta.3/vega-lite.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-beta.16/vega-embed.js" charset="utf-8"></script>
```

EDIT: clarified the issue because it was confusing as for what worked where.

**Comment by domoritz** [comment]
Just checking, are you using https://vega.github.io/new-editor/?mode=vega-lite? 

> Does vega-editor use a newer version of vega-lite

Sometimes, yes. I have not kept Vega-Lite and the editor in sync. Once we have a final release, we will update the Editor and Vega-Lite together.

**Comment by g3o2** [comment]
I don't get any issues in vega-editor. 

I'm running into the above issues by using a simple browser with a html file, run on a local webserver - that's what I've meant by "locally". This setup works with any example currently disclosed on the official vega-lite website but not with the box-plot.

So it seems to me that the vega-lite version, including the corresponding schema, in vega-editor would be newer than the one currently released here on Github. Unless the issue is something else...

**Comment by g3o2** [comment]
Not sure what you have changed between beta.3 and beta.4 but whatever it was, it now works. Thanks! Closing the issue.
