### ISSUE TITLE
Facet customization

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2446]
Facet operator still lacks ways for customizing many underlying properties.

- [x] labels / title configs like https://vega.github.io/vega-lite/docs/axis.html#labels-config and https://vega.github.io/vega-lite/docs/axis.html#title-config.
  - [x] Some properties such as labelBaseline are still missing

Steps:
1. Add `HeaderConfig` to `Config` like `AxisConfig`
2. Add the output
- For title properties, add the right output to the output `encode` block in `getTitleGroup()` in `header.ts`
- For label properties, add the right output to the output `encode` block in `getTitleGroup()` in `header.ts`
- (In both cases, writing a helper method to enumerate through all source VL properties (e.g., `labelLimit` and target VG properties (e.g., `limit`) could be helpful. 
4. Write unit tests for both cases. 

-----

- [ ] Header orient 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A bar chart of the Berkeley Admissions data, showing Simpson's Paradox",
  "width": 100,
  "data": {
    "values": [
      {"Department": "A", "gender" : "Male", "value" : 62.06},
      {"Department": "A", "gender" : "Female", "value" : 82.41},
      {"Department": "B", "gender" : "Male", "value" : 5.90},
      {"Department": "B", "gender" : "Female", "value" : 7.04},
      {"Department": "C", "gender" : "Male", "value" : 33.09},
      {"Department": "C", "gender" : "Female", "value" : 34.93},
      {"Department": "D", "gender" : "Male", "value" : 63.04},
      {"Department": "D", "gender" : "Female", "value" : 68.00},
      {"Department": "E", "gender" : "Male", "value" : 36.92},
      {"Department": "E", "gender" : "Female", "value" : 34.06},
      {"Department": "C", "gender" : "Male", "value" : 27.75},
      {"Department": "C", "gender" : "Female", "value" : 23.92}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "gender", "type": "nominal", 
    "axis" : null},
    "y": {"field": "value", "type": "quantitative",
      "axis" : {"title": "Acceptance Rate  (%)"}},
    "color": {"field": "gender", "type" : "nominal", 
    "scale": {
      "range" : ["pink","steelblue"]
    }
    },
    "column" : { "field": "Department", "type": "nominal", "header":{"orient": "bottom"}}
  }
}
```

- [ ] `encoding` block for header title, labels (just like axis/legend)

- [x] properties of underlying layout operator (See https://github.com/vega/vega-lite/issues/3270)
  
- [x] ~~header/footerBand~~  -- should not be customizable

**Comment by kanitw** [comment]
Depends on https://github.com/vega/vega/issues/931

**Comment by eibanez** [comment]
Would (or could) this include position of the facet? E.g., column axis can be placed at the bottom or column placed at the right?

Then this example could be updated to put the labels under the boxes:
https://bl.ocks.org/domoritz/f5abc519dd990bfcbc3f20f634658364

**Comment by kanitw** [comment]
@eibanez  what you asked for is basically `orient` :)

**Comment by eibanez** [comment]
Thanks; wasn't completely clear. Can't wait!

**Comment by kanitw** [comment]
- [ ] test the example in https://github.com/vega/vega-lite/issues/3657

**Comment by domoritz** [comment]
- [ ] Customize header label font (size, bold, color, ...) like in axes and legends.

**Comment by kanitw** [comment]
Only orient left, will create a new issue to discuss.
