### ISSUE TITLE
Some zoom level in the overview_detail example leads to occluding label

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2453]
Need minor customization of the label format or the tick to eliminate this problem

**Comment by kanitw** [comment]
![vega_editor](https://cloud.githubusercontent.com/assets/111269/26812264/9259b636-4a2b-11e7-8adf-e3eafa2767a6.png)

**Comment by domoritz** [comment]
I think this is going to be fixed by the changes @jheer is working on.

**Comment by kanitw** [comment]
@domoritz please check if it's fixed.

**Comment by domoritz** [comment]
Fixed in master.
