### ISSUE TITLE
Crossfilter starts out blue and has odd padding

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2457]
https://vega.github.io/new-editor/?mode=vega-lite&spec=layered_crossfilter

Odd padding
<img width="760" alt="screen shot 2017-06-06 at 12 46 08" src="https://user-images.githubusercontent.com/589034/26848854-cc71de76-4ab6-11e7-8917-6446032f2e40.png">

**Comment by arvind** [comment]
This was closed by #2458, which only addresses the interaction bug logged here. The axis padding remains unless it's been fixed elsewhere?
