### ISSUE TITLE
Put source into a separate source when using values or named datasources

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2462]
* Only need to do this for values
* Make sure that format parsing is not part of the first data source

This is going to fix https://github.com/vega/vega-lite/issues/2131.

**Comment by imlucas** [comment]
@domoritz Any update on this? #2131 is still blocking our upgrade to `2.x`. Again, happy to help here with more details on where/how to implement this change.

**Comment by domoritz** [comment]
Working on now. Resolving this issue will also fix https://github.com/vega/vega-lite/issues/2500.

**Comment by imlucas** [comment]
@domoritz 🎉 Thanks much!  We're now running everything on vega@3 and vega-lite@2.  cc @rueckstiess

**Comment by domoritz** [comment]
Fantastic!
