### ISSUE TITLE
Why SelectionDomain doesn't require selection?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2470]
From the type guard in `src/scale.ts`
```
export function isSelectionDomain(domain: Domain): domain is SelectionDomain {
  return domain && domain['selection'];
}
```
SelectionDomain should have `selection`. 

However, its declaration does not require `selection`. 

```
export type SelectionDomain = {signal?: string, selection?: string, field?: string, encoding?: string};
```

Any reason for this?

**Comment by arvind** [comment]
I recall that this is a hack we introduced. More details [in the commit](https://github.com/vega/vega-lite/commit/77ff32cac13bc47f4682e9bde936f93ae6ed37cf) that introduced this change:

> The current approach is hacky for two reasons:
> 1. parseScale must occur before parseSelection. Thus, we cannot add `domainRaw`
>   within parseScale. Yet, in assembleScale, we no longer have access to channel.
> 2. Referencing any selection.ts method from within assembleScale throws a
>   JavaScript error. Possible circular dependency?

Will investigate this again now. Thanks for flagging it.
