### ISSUE TITLE
Is `encodings` in BaseSelectionDef only channel

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2483]
Currently it's 
```
encodings?: string[];
```

but I doubt if it is only projectable `Channel`s   (all channels excluding detail/order).

**Comment by kanitw** [comment]
I track down the reference path and it seems to be the case. Will fix this as a part of https://github.com/vega/vega-lite/pull/1980

**Comment by arvind** [comment]
I'm not sure I understand the question but yes, we could switch `encodings` to be `Channel[]`.
