### ISSUE TITLE
Zoomable bar plot

### ISSUE THREAD

**Issue by lemoncyb** [vega/vega-lite#2484]
One problem has been puzzled me for a long time, and I did many attempts but failed.
Is possible for Vega-Lite to draw a zoomable bar plot like [this](http://mbostock.github.io/d3/talk/20111018/area-gradient.html) in D3?
Zoomable for x-axis is necessary because we have a huge number of bars.
Thanks!

**Comment by g3o2** [comment]
You've asked the very same question in the Vega repository, where it has been answered: https://github.com/vega/vega/issues/849
