### ISSUE TITLE
Compiled vega spec has improper filter expression

### ISSUE THREAD

**Issue by sniperliu** [vega/vega-lite#2500]
Please:
- [x] Check for duplicate issues
- [x] Describe how to reproduce the bug /  the goal of the new feature request
- [x] Provide an example spec and screenshots (if applicable) 

I am doing a project with vega-lite stacked area chart with dynamic data.
But vega-lite does not render the chart properly after call the view.change & view.run with changeset.

Below is the example spec, it's in clojure edn, but similar to js map.
```
{:width 300
  :height 200

  :data {:name "table"}
  :mark "area"
  :encoding {:x {:timeUnit "yearmonthutcyearmonthdatehoursminutes" :field "start" :type "temporal"
                  :scale {:nice "minute"}
                  :axis {:domain false :format "%Y%m%d %H%M" :labelAngle 0}}
              :y {:aggregate "sum" :field "value" :type "quantitative"}
              :color {:field "categories" :type "nominal" :scale {:scheme "category20b"}}}}
```

After some investigation, I found after compiled, the vega spec has filter like below, which caused problem, because start is a date string, not number.

**Not work**
```
{:type "filter"
  :expr "datum[\"start\"] !== null && !isNaN(datum[\"start\"]) && datum[\"value\"] !== null && !isNaN(datum[\"value\"])"}
```
If I remove the isNaN checking for start, then works well.
**work**
```
{:type "filter"
  :expr "datum[\"start\"] !== null && datum[\"value\"] !== null && !isNaN(datum[\"value\"])"}
```

**Comment by domoritz** [comment]
Can you send me a snippet of the data?

**Comment by sniperliu** [comment]
Thanks for your quick response.

Actually I tried to replaced the expression with warn(datum.start), also warn(!isNaN(datum.start)), it always return false.

Below is the data sample.

{"bounds: [1493382600000,1493383499999],"value":8574741,"start":"2017-04-28T20:30:00"}

**Comment by domoritz** [comment]
Hmm, it's hard to debug this way. Can you send me a spec with embedded data that I can run in the editor?

**Comment by sniperliu** [comment]
Here you are. But I have no problem with setting data values directly.
The problem is when I use named data, then update view with change set dynamically.
After I remove the filter inside compiled vega spec, then everything works fine.

```
{
  "width": 1000,
  "height": 600,
  "data": {
    "values": [{"bounds": [1493382600000,1493383499999], "value":8574741,"start":"2017-04-28T20:30:00", "categories": "ABC"},
               {"bounds": [1493382600000,1493383499999], "value":7574741,"start":"2017-04-28T20:45:00", "categories": "ABC"},
               {"bounds": [1493382600000,1493383499999], "value":8074741,"start":"2017-04-28T21:00:00", "categories": "ABC"}]
  },
  "mark": "area",
  "encoding": {
    "x": {
      "timeUnit": "yearmonthutcyearmonthdatehoursminutes",
      "field": "start",
      "type": "temporal",
      "scale": {"nice": "minute"},
      "axis": {
        "domain": false,
        "format": "%Y%m%d %H%M",
        "labelAngle": 0
      }
    },
    "y": {
      "aggregate": "sum",
      "field": "value",
      "type": "quantitative"
    },
    "color": {
      "field": "categories",
      "type": "nominal",
      "scale": {"scheme": "category20b"}
    }
  }
}
```

**Comment by domoritz** [comment]
Hmm, sorry for not being able to fix this issue right away. Could you help me and create an example block that shows the error? You can fork https://bl.ocks.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9.

**Comment by sniperliu** [comment]
Sure. I will try to create the example and let you know.

**Comment by domoritz** [comment]
Thank you @sniperliu! I appreciate that you put in the effort to help us debug this issue.

**Comment by sniperliu** [comment]
I have created an example
http://blockbuilder.org/sniperliu/659f857bc459466131b59a440c065764

* stackarea.v2.json is the vega-lite spec
* stackarea.vega.v3.json is the compiled vega spec of stackarea.v2.json
* stackarea.work.v3.json is the one I modified the filter, and remove !isNaN(datum[\"start\"])

btw: you may need to change vega-embed {"mode": "..."} when you try different spec.

**Comment by domoritz** [comment]
Excellent. This is exactly what I need to debug. I don't see any obvious problems but will debug more closely in the morning.

**Comment by domoritz** [comment]
Turns out, the issue is that Vega-Lite does not generate the parse expression and so the `isNaN`filter fails. This will actually be resolved once I fix https://github.com/vega/vega-lite/issues/2462, which I'm working on now.
