### ISSUE TITLE
Bad number of bins

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2515]
<img width="294" alt="screen shot 2017-06-15 at 21 55 17" src="https://user-images.githubusercontent.com/589034/27212499-5b24099a-5215-11e7-8790-c4b035047353.png">

**Comment by kanitw** [comment]
I don't think the number of bins is bad here, but "the number format" of binned field is bad?

**Comment by domoritz** [comment]
Yes, it's a formatting issue. So we should flag it in Vega, right?

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"maxbins": 30},
      "field": "IMDB_Rating",
      "type": "quantitative",
      "axis": {
        "format": ".1f"
      }
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    }
  }
}
```

<img width="268" alt="screen shot 2017-06-22 at 19 39 01" src="https://user-images.githubusercontent.com/589034/27464458-7728e26a-5782-11e7-909b-c12faf64e7a3.png">

**Comment by kanitw** [comment]
Yeah

**Comment by domoritz** [comment]
In https://github.com/vega/vega/issues/877
