### ISSUE TITLE
document the references to best practices in chart design

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2531]
In this excellent [vega-lite presentation](https://m.youtube.com/watch?v=9uaHRWj04D4), it is mentioned at around 4:32 that vega-life's default config is meant "to follow best practices in visualization". In the documentation, I don't see any references to such best practices though. 

Could those references be disclosed in the documentation?

**Comment by kanitw** [comment]
Thanks for asking.  We plan to revise & updates the docs and will make sure to explain the reasoning behind default rules where applicable.  However, we don't plan to list exhaustive references to book chapters.

**Comment by g3o2** [comment]
No worries, I am just curious, I've read many books on the topic myself ;-)
