### ISSUE TITLE
Sort Property of Mark Not Working

### ISSUE THREAD

**Issue by ayush29feb** [vega/vega-lite#2533]
Sort property seems to be broken for the [example](https://vega.github.io/vega-lite/docs/sort.html) in the docs.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative", "sort": "descending"}
  }
}
```

![image](https://user-images.githubusercontent.com/8674376/27266628-7e13160a-5457-11e7-9627-721abed68ac5.png)

**Comment by domoritz** [comment]
Hmm, in this case we should reverse the scale, right?

**Comment by ayush29feb** [comment]
Yes, at least thats what the documentation says. I am using the online editor https://vega.github.io/new-editor/?mode=vega-lite

**Comment by g3o2** [comment]
Does `sort` make sense at all for `quantitative` given the existence of `scale.reverse`?

**Comment by kanitw** [comment]
@g3o2  -- good point.  I think there are distinction between `scale.reverse` and scale sort order in Vega.  We should add `reverse` and correctly distinguish their behaviors.

**Comment by g3o2** [comment]
It is only now that I've realised that there is indeed no `scale.reverse` in vega-lite :-)

**Comment by kanitw** [comment]
@g3o2 Previously sort: "descending"  maps to reverse in the underlying Vega.  However, there is a case where they are different and thus we no longer map sort order to reverse.  We still need to add `reverse` back.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2545

**Comment by ayush29feb** [comment]
@kanitw is it updated in https://vega.github.io/new-editor/?mode=vega-lite?

**Comment by kanitw** [comment]
Nope -- that will require a release.
