### ISSUE TITLE
make `labelOverlap` depends on scale type

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2543]
This is a follow up for https://github.com/vega/vega-lite/pull/2510

From [this comment](https://github.com/vega/vega-lite/issues/1539#issuecomment-307180157), I think we should use 
- [ ] `true` for non-log continuous scales
- [x] `"greedy"` for log scales
- [ ] `undefined` for discrete scales (as it's better to use limit anyway

Obviously we should experiment with a few examples before adding this rule

**Comment by domoritz** [comment]
Done

**Comment by kanitw** [comment]
Why is we only using undefined for nominal 

(Wouldn't it be better to check scale type for discrete scale?) 

https://github.com/vega/vega-lite/blob/master/src/compile/axis/rules.ts#L48

**Comment by domoritz** [comment]
For ordinal scale, I think it's fine to preven label overlap.

**Comment by kanitw** [comment]
> For ordinal scale, I think it's fine to prevent label overlap.

Do you mean "For ordinal field"?   Nominal field uses ordinal scales too.  

I think if the ordinal values are straightforward, I think it is fine too but 
users won't know what the possible labels are.  

Also, I think for discrete scales, we also set angle so not sure if preventing label overlap is really more useful.   (I'm not sure -- need to test more)

**Comment by domoritz** [comment]
> Do you mean "For ordinal field"? Nominal field uses ordinal scales too.
Yes.

**Comment by domoritz** [comment]
> Also, I think for discrete scales, we also set angle so not sure if preventing label overlap is really more useful. (I'm not sure -- need to test more)

It can be if there are a lot of labels and the size is constrained.

**Comment by kanitw** [comment]
Okie good point!
