### ISSUE TITLE
Concat/Facet width/height signals reference out of scope scales

### ISSUE THREAD

**Issue by arvind** [vega/vega-lite#2555]
- [x] **Concat**

With the following concatenated spec, the `concat_width` and `concat_height` signals are defined at the top-level. However, the corresponding scales referenced within their `update` expressions are not in scope (the scales are only defined within each `concat_group`). As a result, these top-level signals have a value of `0`. This is problematic for selections (which reference the size signals to clamp interactions correctly).

If the size signals are moved to be within the correct scopes (e.g., `concat_0_width`/`height` is moved to be a child of `concat_0_group`), the values are correctly calculated.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/seattle-temps.csv"},
  "vconcat": [{
    "mark": "bar",
    "encoding": {
      "x": {
        "timeUnit": "month",
        "field": "date",
        "type": "temporal"
      },
      "y": {
        "aggregate": "mean",
        "field": "temp",
        "type": "quantitative"
      }
    } 
  }, {
    "mark": "bar",
    "encoding": {
      "x": {
        "timeUnit": "month",
        "field": "date",
        "type": "temporal"
      },
      "y": {
        "aggregate": "median",
        "field": "temp",
        "type": "quantitative"
      }
    }
  }],
  "config": {"cell": {"fill": "yellow"}}
}
```

**Comment by kanitw** [comment]
Sounds like we have to implement a lot of signals that push value to outer scope instead?

**Comment by arvind** [comment]
Pushing to outer scope is fairly easy. We do it with selections. Signals should have the same name, and the inner signals should be marked with `"push": "outer"`. 

> One observation -- this is only necessary for shared scales.

Not sure what "this" is referencing but selections need valid size signals to clamp interaction correctly. 

>

**Comment by kanitw** [comment]
@arvind  -- This is a pretty quick reply for vacation day :p   Thanks!

> Not sure what "this" is referencing but selections need valid size signals to clamp interaction correctly.

Sorry this is more like a note to myself -- I mean we only have this problem for independent scales (actually not shared scale -- typo*) as shared scale would be moved to parent's scope.  

Currently, I plan to work on merging size signals first (#2198), which hopefully will make it easier for me to fix this one.

**Comment by kanitw** [comment]
> Pushing to outer scope is fairly easy. We do it with selections. Signals should have the same name, and the inner signals should be marked with "push": "outer".

Yep.  Shouldn't be too bad

**Comment by kanitw** [comment]
@domoritz  I could move the scale inside (like I tried [here](https://github.com/vega/vega-lite/compare/kw/layout-signal?expand=1)) but we will need to duplicate signal and do push outer, which I think make the output spec and our compiler a little bit convoluted.  

An alternative option would be to produce the scales in the outer scope -- I wonder if there would be any case where this would be problematic.   If not, I think this will produce a simpler output and may require less code.

**Comment by domoritz** [comment]
I'm a bit lost about what exactly the inner and outer scopes are. Scales have to stay within the group that corresponds to the model that they are used in. Pushing the scales up won't work in general because the data may not be defined there (only relevant for facet specs). Oher than that, we can move scales.

**Comment by kanitw** [comment]
- [ ] This is also problematic for faceted plots with independent scales.

Example spec:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A trellis bar chart showing the US population distribution of age groups and gender in 2000.",
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "facet": {"row": {"field": "gender", "type": "nominal"}},
  "spec": {
    "mark": "bar",
    "encoding": {
      "y": {
        "aggregate": "sum", "field": "people", "type": "quantitative",
        "axis": {"title": "population"}
      },
      "x": {
        "field": "age", "type": "ordinal",
        "scale": {"rangeStep": 17}
      },
      "color": {
        "field": "gender", "type": "nominal",
        "scale": {"range": ["#EA98D2","#659CCA"]}
      }
    } 
  },
  "resolve": {
    "x": {"scale": "independent"}
  }
}
```

**Comment by kanitw** [comment]
FYI I just added `"config": {"cell": {"fill": "yellow"}}` to both examples to help test

**Comment by kanitw** [comment]
Some toy spec to test an extreme case:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"values": [
    {"r": "r1", "c": "c1", "a": "a1", "b": "b1"},
    {"r": "r1", "c": "c1", "a": "a2", "b": "b2"},
    {"r": "r2", "c": "c2", "a": "a1", "b": "b1"},
    {"r": "r3", "c": "c2", "a": "a3", "b": "b2"}
  ]},
  "facet": {
    "row": {"field": "r", "type": "nominal"},
    "column": {"field": "c", "type": "nominal"}
  },
  "spec": { 
    "mark": "rect",
    "encoding": {
      "y": {"field": "b", "type": "nominal"},
      "x": {"field": "a", "type": "nominal"}
    }
  },
  "resolve": {
    "x": {
      "scale": "independent"
    },
    "y": {
      "scale": "independent"
    }
  }
}
```

**Comment by kanitw** [comment]
Handled in https://github.com/vega/vega-lite/pull/2697
