### ISSUE TITLE
Change vega-datasets dependencies

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2587]
`"vega-datasets": "vega/vega-datasets#gh-pages"` is a bad idea because yarn would lock it to a particular commit and won't get updated.

**Comment by domoritz** [comment]
I get the correct hash in yarn.lock. Not sure why this is a problem.

**Comment by kanitw** [comment]
Well, it is a problem because it does not always update the right hash.

**Comment by domoritz** [comment]
I haven't seen this issue but I'm happy to investigate when you see it next time.

**Comment by kanitw** [comment]
I'm still seeing it even now, but running `npm install vega-datasets` (not `yarn`) makes the problem go away.  In any case, this is obviously still problematic when we update a new version in the future.

**Comment by domoritz** [comment]
The yarn hash is correct, though. Can you try cleaning your yarn cache?

**Comment by kanitw** [comment]
I run `yarn cache clean && yarn` but still does not have `node_modules/vega-datasets//data/lookup_people.csv`

**Comment by kanitw** [comment]
`npm install vega-datasets` temporarily solves the problem but when I run `yarn` again, the problem comes back.

**Comment by domoritz** [comment]
That sounds like an issue with yarn then that should be filed at https://github.com/yarnpkg/yarn/issues/new.

**Comment by kanitw** [comment]
Sure, but we can still avoid  easily by using proper versions.
