### ISSUE TITLE
The schema does not include description for $schema and config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2600]
See `TopLevelFacetedUnitSpec` in the schema for example. 

Note that we already include description for them in `spec.ts`.  (See `TopLevel`'s declaration)

**Comment by domoritz** [comment]
So, we are missing descriptions for `TopLevelFacetedUnitSpec`, `$schema`, and `config`? What is `config`?

**Comment by kanitw** [comment]
> So, we are missing descriptions for TopLevelFacetedUnitSpec, $schema, and config?

`config` is literally our config object lol

**Comment by domoritz** [comment]
Okay, so `Config` with capital c. I'll fix it this weekend.

**Comment by kanitw** [comment]
It's `config` property, which has a type `Config`.  The description is defined with the property, not the interface.

**Comment by domoritz** [comment]
Thanks for the clarification. The descriptions would be in different places so now i know where to look.

**Comment by domoritz** [comment]
Ha, weird. 

```
export type MyType = {
    /**
     * Where is this comment?
     */
    foo?: number;
};
```

produces

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "MyType": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "number"
        }
      },
      "type": "object"
    }
  }
}
```

But `interface` works. I should be able to fix this easily.
