### ISSUE TITLE
mark.role makes circle marks larger?

### ISSUE THREAD

**Issue by mcorrell** [vega/vega-lite#2616]
Here's a spec of a scatterplot

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple scatterplot with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": 52}
    ]
  },
  "mark": {"type": "circle"},
  "encoding": {
    "x": {"field": "a","type": "ordinal"},
    "y": {"field": "b","type": "quantitative"}
  }
}
```

Compare to:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple scatterplot with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": 52}
    ]
  },
  "mark": {"type": "circle","role": "foo"},
  "encoding": {
    "x": {"field": "a","type": "ordinal"},
    "y": {"field": "b","type": "quantitative"}
  }
}
```

Where the points are larger, despite the fact that all I've done is set mark.role

**Comment by kanitw** [comment]
I think it's hard to really change this behavior since default size are determined by default role.  

Let's just update documentation to be clearer about this.

**Comment by mcorrell** [comment]
Why wouldn't the default size be consistent? Isn't "role" just supposed to be a way of creating metadata/handles?

**Comment by kanitw** [comment]
Yes, but high-level marks (which turn into different marks in Vega) use their role config to determine default mark properties.    (For example, default circle size is determine by the default `config.circle.size`.) 

I just updated documentation in #2670

**Comment by kanitw** [comment]
@mcorrell  Good news -- with new Vega updates we will be able to fix this problem!
