### ISSUE TITLE
Misaligned labels when using both row and column faceting

### ISSUE THREAD

**Issue by tomerk** [vega/vega-lite#2624]
Hi all,

I've been trying to use Vega-lite to generate some faceted plots for a paper. I've noticed that when I use both row and column faceting, Vega-lite will order the cells according to certain parameter values, but not reorder the labels. This means the labels get assigned to the wrong cells.

An example when using both row and column faceting:
```
{
  "data": {
    "values": [
      {
        "regex": 0,
        "globalTime": 584.996,
        "policy2": "constant:0,False",
        "numParts": 256
      },
      {
        "regex": 0,
        "globalTime": 329.725,
        "policy2": "constant:0,False",
        "numParts": 512
      },
      {
        "regex": 0,
        "globalTime": 2203.649,
        "policy2": "constant:0,False",
        "numParts": 64
      },
      {
        "regex": 0,
        "globalTime": 341.32,
        "policy2": "constant:0,False",
        "numParts": 1024
      },
      {
        "regex": 0,
        "globalTime": 1128.079,
        "policy2": "constant:0,False",
        "numParts": 128
      }
    ]
  },
  "mark": "bar",
  "config": {
    "cell": {
      "width": 600,
      "height": 350
    }
  },
  "encoding": {
    "y": {
      "field": "globalTime",
      "type": "quantitative"
    },
    "x": {
      "field": "numParts",
      "type": "nominal"
    },
    "column": {
      "field": "numParts",
      "type": "ordinal"
    },
    "row": {
      "field": "regex",
      "type": "nominal"
    }
  }
}
```

<img width="682" alt="screen shot 2017-07-03 at 12 51 32 pm" src="https://user-images.githubusercontent.com/676357/27806465-91116a9c-5fef-11e7-9989-e4e78806a743.png">

The cell contents are ordered according to the value of `numParts`, but the labels appear in the order that they appear in the data specification.

On the other hand when we remove the row facet:

```
{
  "data": {
    "values": [
      {
        "regex": 0,
        "globalTime": 584.996,
        "policy2": "constant:0,False",
        "numParts": 256
      },
      {
        "regex": 0,
        "globalTime": 329.725,
        "policy2": "constant:0,False",
        "numParts": 512
      },
      {
        "regex": 0,
        "globalTime": 2203.649,
        "policy2": "constant:0,False",
        "numParts": 64
      },
      {
        "regex": 0,
        "globalTime": 341.32,
        "policy2": "constant:0,False",
        "numParts": 1024
      },
      {
        "regex": 0,
        "globalTime": 1128.079,
        "policy2": "constant:0,False",
        "numParts": 128
      }
    ]
  },
  "mark": "bar",
  "config": {
    "cell": {
      "width": 600,
      "height": 350
    }
  },
  "encoding": {
    "y": {
      "field": "globalTime",
      "type": "quantitative"
    },
    "x": {
      "field": "numParts",
      "type": "nominal"
    },
    "column": {
      "field": "numParts",
      "type": "ordinal"
    }
  }
}
```

<img width="647" alt="screen shot 2017-07-03 at 12 51 47 pm" src="https://user-images.githubusercontent.com/676357/27806481-a70eafee-5fef-11e7-8630-1300981c1ac5.png">

Now the labels and cell contents both appear in the order in which they are specified in the data. I'm not sure whether you prefer the cell contents to be automatically sorted or not (and I assume either way I could always manually re-order them), but the labels being assigned improperly is an issue.

Best,
Tomer

**Comment by domoritz** [comment]
Thanks! I remember that we had issues with sorting facets. This is definitely a critical bug.

**Comment by domoritz** [comment]
Thought this was fixed in #https://github.com/vega/vega-lite/pull/2412

**Comment by domoritz** [comment]
I don't see how the labels are assigned incorrectly. Yes, when you facet, by column and row, we automatically sort because it is necessary to make the crossproduct work. But the labels should still be correct.

I changed the height of the bar to correspond to the label and to make it clearer.

```json
{
  "data": {
    "values": [
      {
        "regex": 0,
        "globalTime": 256,
        "numParts": 256
      },
      {
        "regex": 0,
        "globalTime": 512,
        "numParts": 512
      },
      {
        "regex": 0,
        "globalTime": 64,
        "numParts": 64
      },
      {
        "regex": 0,
        "globalTime": 1024,
        "numParts": 1024
      },
      {
        "regex": 0,
        "globalTime": 128,
        "numParts": 128
      }
    ]
  },
  "mark": "bar",
  "config": {
    "cell": {
      "width": 600,
      "height": 350
    }
  },
  "encoding": {
    "y": {
      "field": "globalTime",
      "type": "quantitative"
    },
    "x": {
      "field": "numParts",
      "type": "nominal"
    },
    "column": {
      "field": "numParts",
      "type": "ordinal"
    },
    "row": {
      "field": "regex",
      "type": "nominal"
    }
  }
}
```

**Comment by domoritz** [comment]
Now I see it. The header is not sorted and so the assignment doesn't match.

**Comment by domoritz** [comment]
This is actually corrected in master already. Just wait for the next release.

<img width="687" alt="screen shot 2017-07-03 at 17 59 53" src="https://user-images.githubusercontent.com/589034/27811290-7b084494-6019-11e7-86d6-7c799fe6aa84.png">
