### ISSUE TITLE
Legend has stroke even though marks don't have it

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2626]
<img width="86" alt="screen shot 2017-07-03 at 18 41 09" src="https://user-images.githubusercontent.com/589034/27811861-6642c9b6-601f-11e7-8631-2a0e2737930e.png">

**Comment by kanitw** [comment]
Spec?

**Comment by domoritz** [comment]
github punchcard for example

**Comment by kanitw** [comment]
Looks like this is somehow Vega's default.  (We didn't output any stroke.)  Maybe file an issue in Vega's repo?

**Comment by domoritz** [comment]
I'm away till next Friday so if you want this to be fixed in Vega, could
you file an issue?

**Comment by kanitw** [comment]
Fixed in Vega

**Comment by kanitw** [comment]
It's coming back

**Comment by jheer** [comment]
This was a necessary reversion to fix the issue with transparent fill symbols disappearing, which was a higher priority problem. I believe the solution here is to generate custom encoding as needed.

**Comment by kanitw** [comment]
I think we have 3 options here:

1) Keep the reversion and make Vega-Lite outputs `stroke: transparent` for most of the specs.

2) Keep the original fix (revert the reversion) and make Vega-Lite do not output fill: transparent for legend.

3) Modify the original fix to ignore `config.legend.color` when fill is set (except when fill is set to transparent). 

As a Vega user, I think always applying default legend color to stroke is a bit weird.
In addition, this requires Vega outputs from Vega-Lite to be a bit more complicated (need hard-coded `stroke: transparent`).  
Thus, I think 2 or 3 would be a better solution. (I think 2 is not a bad solution and we already have a code for 2, but didn't merge it as we thought we will fix it in Vega)  
That said, if you feel strongly about this 1 is not hard to implement in Vega-Lite.

**Comment by kanitw** [comment]
From discussion, we will do 1 in Vega-Lite and @jheer will remove `config.legend.symbolColor` and add `config.legend.symbolFill/Stroke`

**Comment by kanitw** [comment]
Actually from slack conversation, we don't have to do 1 anymore, but we will do 2 by bringing back #2721
