### ISSUE TITLE
Cannot resize a Vega-Lite chart

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2645]
I'd like to call `view.width(200).run()` but it doesn't work even for a simple barchart because we set the range of the x and y explicitly. Yes, we cannot always do this (especially for nested charts) but we should make an effort to allow dynamic resizing where possible.

**Comment by domoritz** [comment]
Why are we not just using the size signal for the range instead of `[0,200]`?

**Comment by kanitw** [comment]
> I'd like to call view.width(200).run() but it doesn't work even for a simple barchart because we set the range of the x and y explicitly. 

Duplicate of https://github.com/vega/vega-lite/issues/1497. 
I won't work for general case though and should not be priority for 2.0 IMHO.

> @kanitw Why are we not just using the size signal for the range instead of [0,200]?

Duplicate of https://github.com/vega/vega-lite/issues/618

**Comment by domoritz** [comment]
Sure, it doesn't work in general but it works for unit specs, which are the most common type. It would certainly make it easier to build applications with vl.

**Comment by jheer** [comment]
In general, putting size (or other constants) into signals enables subsequent parameterization. I think we should follow this strategy as much as possible.

**Comment by kanitw** [comment]
We already agree to do the signal in #618, im just closing since it s a duplicate...
