### ISSUE TITLE
Revise selection predicate generation code

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2646]
See #2591

* Construct the timeunit nodes outside the predicate function
* Add more tests

**Comment by arvind** [comment]
I think this might warrant a quick video chat to understand what requires revision...

**Comment by kanitw** [comment]
Ok i actually assign to two of you because i have no idea too. Lets wait until @domoritz is back then

**Comment by domoritz** [comment]
This is not pressing but I want to have a look at the code again because I am still not happy with it. Once I had a look at it, I can give more detailed feedback about what I think we could clean up. 

Definititely not a critical issue.
