### ISSUE TITLE
Output plot as HTML does not work, the vega-lite.js is unavailable

### ISSUE THREAD

**Issue by sladkovm** [vega/vega-lite#2652]
Example plot (see below) does not yield working html. The *https://vega.github.io/vega-lite/vega-lite.js* dependency cannot be found.

**Comment by arvind** [comment]
Hi @sladkovm, unfortunately your issue does not include any code (or link to code) for us to be able to help you debug further. However, as our [usage page](https://vega.github.io/vega-lite/usage/embed.html) describes, we recommend loading Vega-Lite through cdnjs URLs. This ensures that any changing we make to our site architectures do not inadvertently break your visualizations. 

```json
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.0-rc1/vega.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0-beta.8/vega-lite.js"></script>
```

Hope that helps!

**Comment by sladkovm** [comment]
*cdnjs* would work for self-hosted graphs, but the error occurs when using local server.

Here is the example of the code i run in jupyter:

```
from altair import Chart, Color, Scale

data = 'https://vega.github.io/vega-datasets/data/population.json'
pink_blue = Scale(range=["lightblue", "pink"])

Chart(data).mark_bar().encode(
    x='age:O',
    y='mean(people):Q',
    color=Color('sex:N', scale=pink_blue)
).serve()

```

This is the error I get in the chrome console:

`vega-lite.js Failed to load resource: the server responded with a status of 404 (Not Found)`

And the actual code of the html page looks like this, where the most interesting part is of course the header. Would it be possible to replace the  <script src="https://vega.github.io/vega-lite/vega-lite.js"></script> with *cdnjs* version in the ouput of serve() method?


  |  
-- | --
  | <!DOCTYPE html>
  | <head>
  | <title>Vega-Lite Chart</title>
  | <meta charset="utf-8">
  |  
  | <script src="https://d3js.org/d3.v3.min.js"></script>
  | <script src="https://vega.github.io/vega/vega.js"></script>
  | <script src="https://vega.github.io/vega-lite/vega-lite.js"></script>
  | <script src="https://vega.github.io/vega-editor/vendor/vega-embed.js" charset="utf-8"></script>
  |  
  | <style media="screen">
  | /* Add space between vega-embed links  */
  | .vega-actions a {
  | margin-right: 5px;
  | }
  | </style>
  | </head>
  | <body>
  | 
  | <div id="vis"></div>
  |  
  | <script>
  | var vlSpec = {
  | "data": {
  | "url": "https://vega.github.io/vega-datasets/data/population.json"
  | },
  | "encoding": {
  | "y": {
  | "field": "people",
  | "aggregate": "mean",
  | "type": "quantitative"
  | },
  | "x": {
  | "field": "age",
  | "type": "ordinal"
  | },
  | "color": {
  | "field": "sex",
  | "scale": {
  | "range": [
  | "lightblue",
  | "pink"
  | ]
  | },
  | "type": "nominal"
  | }
  | },
  | "mark": "bar"
  | }
  |  
  | var embedSpec = {
  | mode: "vega-lite",  // Instruct Vega-Embed to use the Vega-Lite compiler
  | spec: vlSpec
  | };
  |  
  | // Embed the visualization in the container with id `vis`
  | vg.embed("#vis", embedSpec, function(error, result) {
  | // Callback receiving the View instance and parsed Vega spec
  | // result.view is the View, which resides under the '#vis' element
  | });
  | </script>
  | </body>
  | </html>
  |

**Comment by domoritz** [comment]
This is because altair used an outdated path. See https://github.com/altair-viz/altair/issues/342. Should be fixed in the latest release.
