### ISSUE TITLE
Box plot normalization references config object which may be undefined when in a repeat spec

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega-lite#2655]
In `normalizeBoxPlot` https://github.com/vega/vega-lite/blob/master/src/compositemark/boxplot.ts#L86 is the following:

```
const sizeMixins = size ? {size} : {size: {value: config.box.size}};
```

However, `config` may be undefined (which happens when in a `repeat` spec), giving the error `Cannot read property 'box' of undefined`. This should probably be guarded against with an ultimate default value, or perhaps this is a bug where `config` is not initialized/passed properly in a `repeat` spec for boxplot and/or composite marks in general.

This shows up in this spec:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52},
      {"a": "A","b": 2}, {"a": "B","b": 5}, {"a": "C","b": 4},
      {"a": "D","b": 9}, {"a": "E","b": 8}, {"a": "F","b": 5},
      {"a": "G","b": 1}, {"a": "H","b": 8}, {"a": "I","b": 5}
    ]
  },
  "repeat": {"row": ["b"]},
  "spec": {
    "mark": "box-plot",
    "encoding": {
      "y": {"field": {"repeat": "row"}, "type": "quantitative"}
    }
  }
}
```

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/issues/2700
