### ISSUE TITLE
how to make the aspect ratio for plots equal

### ISSUE THREAD

**Issue by gdmcbain** [vega/vega-lite#2661]
(After reading the documentation) I couldn't figure out how to have the scale for x and y (both "quantitative") equal, in the sense of "same scaling from data to plot units" (from matplotlib's [matplotlib.axes.Axes.set_aspect](http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_aspect.html#matplotlib-axes-axes-set-aspect), e.g. when both fields represent coordinates in a real two-dimensional geometry which I don't want to distort, e.g. so that circles are circular rather than elliptic.

**Comment by kanitw** [comment]
Thanks for asking.  You can directly set `encoding.x/y.scale.domain` and `width` and `height` to be the same.If you use default `width` and `height`, then you only need to set `domain`.

**Comment by gdmcbain** [comment]
Thanks.

For future reference: `width` and `height` are fields in `config.cell`.

So there doesn't seem to be an equivalent to `matplotlib.axes.Axes.set_aspect('equal')`.

The use-case (which inspired the corresponding matplotlib FAQ [Make the aspect ratio for plots equal](https://matplotlib.org/faq/howto_faq.html?highlight=equal#make-the-aspect-ratio-for-plots-equal)) is that the `encoding.x.scale.domain` and `encoding.y.scale.domain` are not specified explicitly but conveniently calculated by the computer to (a) show all points and (b) have nice round bounds but (c) not be all that easily accurately predictable in advance by the user in the way that they would have to be if the user was to calculate and set `config.cell.width` and `height` to maintain a precise specific aspect ratio (typically 1.0).

I suppose this would often apply to geographic data?  In my case, it was an industrial design.  Either way, both `x` and `y` are spatial coordinates.

Do you think that a functionality like:

-  matplotlib's `set_aspect('equal')`
- ggplot2's [`coord_fixed(ratio=1)`](http://ggplot2.tidyverse.org/reference/coord_fixed.html)
- gnuplot's [`set size square`](http://gnuplot.sourceforge.net/docs_4.2/node230.html)
- Octave's [`axis("equal")`](https://www.gnu.org/software/octave/doc/interpreter/Axis-Configuration.html#XREFaxis)

would be a welcome enhancement to Vega-Lite?  May I try drafting and proposing a pull request?  Would `config.cell.aspect` be a reasonable place to put it in the schema?

**Comment by kanitw** [comment]
> For future reference: `width` and `height` are fields in `config.cell`.

You can actually set the top-level `"width"` and `"height"` properties directly.  

For geographic data, which will be supported in a later minor release, you would use `projection` rather than scale.  


> would be a welcome enhancement to Vega-Lite?

I think so.  

>  May I try drafting and proposing a pull request?

Yes, but it might be a little tricky without some guidance.  I can later point to how to do this, but I'm currently on vacation so I won't go into details about it for now.  Feel free to ping me in 2 weeks.
