### ISSUE TITLE
Interactive charts hijack scroll

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2662]
I cannot scroll a page when my cursor is on an interactive plot even if the plot doesn't use the scroll event.

**Comment by domoritz** [comment]
Okay, I take that back. It doesn't happen for `paintbrush`.

**Comment by arvind** [comment]
Thanks for filing this issue, @domoritz! The problem occurs for `interval` selections which register `wheel` event handlers by default. Unfortunately, it looks like the Vega view is set to consume _all_ events by default (whether they are marked as such or not). I've opened vega/vega-view#12 to discuss this behaviour further (as well as describing the workaround). 

This issue also helped me identify a bug in Vega-Lite: `wheel` events _should_ be consumed to prevent accidental scrolling from being triggered. Addressing this with #2665.
