### ISSUE TITLE
stacked_area_binned broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2663]
On master

<img width="363" alt="screen shot 2017-07-12 at 23 42 58" src="https://user-images.githubusercontent.com/589034/28153724-e1d447e2-675b-11e7-913d-7fc906837123.png">

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/issues/2669 might be related?

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/pull/2753

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2753
