### ISSUE TITLE
lookup.vl.json broken

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2678]
(It doesn't render x-axis)

**Comment by willium** [comment]
This is either because you haven't updated your vega-datasets or because the lookup transform is broken. Did we introduce something that might've broken lookup transforms?

**Comment by kanitw** [comment]
> updated your vega-datasets

Is this because vega-datasets do not have specific version and thus doesn't get update with yarn?  

If so, we should make versions for vega-datasets otherwise people gonna keep running into this problem.

**Comment by willium** [comment]
Yeah, @domoritz why is it currently a `gh-pages` branch? It also seems lookup data is in v1.9 (according to the readme), but package.json puts the version number at 1.8. 

@kanitw did updating `vega-datasets` fix the example?

**Comment by willium** [comment]
Relevant: #2587

**Comment by domoritz** [comment]
Works for me. 

![image](https://user-images.githubusercontent.com/589034/28760790-83b5b00e-755e-11e7-9c07-0d58abc4b783.png)
