### ISSUE TITLE
Unknown "child_width" signal for Facet of Repeat

### ISSUE THREAD

**Issue by arvind** [vega/vega-lite#2686]
The following spec throws an error: `Uncaught Error: Unrecognized signal name: "child_width"` because the `column_header` group is specified with `"encode": {"update": {"width": {"signal": "child_width"}}}`

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/anscombe.json"},
  "facet": {"column": {"field": "Series","type": "nominal"}},
  "spec": {
    "repeat": {"row": ["A","B"]},
    "spec": {
      "mark": "rule","encoding": {"x": {"value": 10}}
    }
  }
}
```

**Comment by arvind** [comment]
A similar error is also thrown for the complement (facet into `row` and repeat over `column`).

**Comment by kanitw** [comment]
I'll handle this once vega 3 rc4 lands, so I can use the new `headerBand` property.

**Comment by kanitw** [comment]
This works fine in https://github.com/vega/vega-lite/pull/2697 :)
