### ISSUE TITLE
Bugs in scale domain example brush 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2695]
From the example here https://vega.github.io/vega-lite/docs/selection.html#scale-domains:

The interval brush does not match my cursor when selecting

![scaledomainbrush](https://user-images.githubusercontent.com/111269/28436216-f5951fc8-6d4a-11e7-9178-9883bc02c8a1.gif)

**Comment by arvind** [comment]
Thanks! This has been fixed by vega/vega-view#13 and should be resolved once it's released in a new Vega version and deployed to the docs.
