### ISSUE TITLE
How to use database table data  json into the Vega json data 

### ISSUE THREAD

**Issue by Richard-bizruntime** [vega/vega-lite#2699]
Hi Vega Team , you guys did awesome work in the Visualization , i gone through the Vega Documentation there is taking all the data from either Json or csv, file but in my question was there is any way to rendering the table data into Vega Json data ,for  creating  SVG image of geo map visualization  .If its there please share the link or give some suggestion of it, Thank you..

**Comment by willium** [comment]
Vega-lite doesn't currently support geo projections, but that's something that is actively being worked on.
If you're asking particularly about being able to have data in a Vega JSON spec, you may also find the [relevant docs](https://vega.github.io/vega/docs/data/) helpful. For Vega specific questions, you should ask in the https://github.com/vega/vega repo.

**Comment by kanitw** [comment]
To reply to your question about "database", if you have your data in a database table, you can query them into row-oriented JSON array and either use [inline data](https://vega.github.io/vega-lite/docs/data.html#inline) or bind it to [a named data source](https://vega.github.io/vega-lite/docs/data.html#named).
