### ISSUE TITLE
Rect marks in Heatmap overlap with cell (stroke) border

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2713]
<img width="482" alt="screen shot 2017-07-25 at 17 37 10" src="https://user-images.githubusercontent.com/589034/28599602-b30e6636-7160-11e7-8e4b-0371b085bb34.png">

**Comment by kanitw** [comment]
See spec [here](https://github.com/vega/vega-lite/pull/2710/commits/e6c0aec7fcae15c9a4bf3c4b7841a7a8e8361237)

**Comment by domoritz** [comment]
We do put the data behind the axis lines so maybe we should put it behind the cell border as well.

**Comment by kanitw** [comment]
Need to check if there is a way to do that.  (I'm not sure if there is, but I could be wrong.)

**Comment by kanitw** [comment]
Adding 

```
      "zindex": {
        "value": 100
      }
```

to the encode block does not help.  


cc: @jheer -- is there any other way to achieve this?  (Or should we just ignore it.)

**Comment by jheer** [comment]
The group mark background is *always* in the background so `z-index` has no effect here relative to the group's inner content. If you want a "frame" that is always drawn on top, you can add your own rect mark (set to [0, 0, width, height]) as the last mark within a group (or add axes with domain lines only, though that would probably be overkill).

Also (tangential question), do we want to include a frame border by default?

**Comment by kanitw** [comment]
>  Also (tangential question), do we want to include a frame border by default?

Thanks for asking.  (I think this is actually not really tangential, we don't have to handle this at all if we want to just remove it.) 

Since we enable grid by default, I like the frame border when the grids do not have close ends.  

Otherwise, we get something like these:

![vega_editor](https://user-images.githubusercontent.com/111269/28900000-d6b85496-77a2-11e7-9bce-176aab047d55.png)

![vega_editor](https://user-images.githubusercontent.com/111269/28900010-f049c9b2-77a2-11e7-8ff7-3eea99d4a397.png)

which look pretty imbalanced IMHO:

**Comment by kanitw** [comment]
It turns out this is not a problem for general heatmap (as band scale has padding), but only for binned heatmap, which uses linear scale.  

Instead of creating a special code path for it, I'll set the example to use cell.stroke = "transparent". 
We can deal with this later if our users request a fix.
