### ISSUE TITLE
shapes don't appear in legend (but do on plot)

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#2719]
Altair-generated Vega-Lite JSON, stored in https://owensgroup.github.io/gpustats/plots/Processing%20Power%20over%20Time.html

Using:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.0-rc4/vega.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0-beta.10/vega-lite.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-beta.19/vega-embed.js">
```

Shapes seem to work OK when there's only a shape, but not when there's shape+color.

**Comment by domoritz** [comment]
Thanks! Can you find a smaller spec that shows this issue?

**Comment by domoritz** [comment]
This spec works

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A scatterplot showing horsepower and miles per gallons.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal"},
    "shape": {"field": "Cylinders", "type": "nominal"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/28749689-fd0bfee8-7484-11e7-95de-dc824001bdb0.png)

**Comment by domoritz** [comment]
Oh funny, not in the latest versions.

![image](https://user-images.githubusercontent.com/589034/28749690-14b618ee-7485-11e7-9081-d3628e45201d.png)

**Comment by domoritz** [comment]
Looks like a vega issue. See https://github.com/vega/vega/issues/946. 

@kanitw Any reason why we output `fill: transparent`?

**Comment by kanitw** [comment]
Its just same code path with mark. Maybe we have to remove this in the new version of Vega since if fill is set, now default color dont get applied.

**Comment by domoritz** [comment]
We have a PR for fixing this in VL but it may also be fixed on the Vega side. Either way, closing issue.

**Comment by jowens** [comment]
@domoritz it would be helpful to know "it's fixed in version X, update your .js includes accordingly" ... ?

**Comment by domoritz** [comment]
@jowens I don't know when https://github.com/vega/vega/issues/946 will be fixed but yes, that would be a better message :-)
