### ISSUE TITLE
Trellis Barley example refers to undefined data source

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2731]
This is first introduced in the facet of facet PR.  

Uncaught Error: Undefined data set name: "scale_trellis_barley_child_main"
"scale_trellis_barley_child_main"

(If you want to fix, please fix it in https://github.com/vega/vega-lite/pull/2730 so I can reapply facet of facet to hotfix branch and work on relevant issues from there.)

**Comment by kanitw** [comment]
Looks like the bug is introduced in 7292050600605557efe44ec38bdae473e58cae8f

**Comment by kanitw** [comment]
@domoritz  I don't understand this change [here](https://github.com/vega/vega-lite/pull/2730#discussion_r130732180).  Can you take a look?  

I'm sure it will be very easy for you to fix but gonna take hours for me.

**Comment by kanitw** [comment]
I tried both reverting and applying  `model.getName` together with what you add.  
It seems like this is deep into what you did in facet of facet, which you should definitely fix!

**Comment by domoritz** [comment]
Yeah, there are some funny looking output nodes

<img width="715" alt="screen shot 2017-08-01 at 22 49 32" src="https://user-images.githubusercontent.com/589034/28859374-bcf23df2-770b-11e7-9531-d20e529e0819.png">

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2747
