### ISSUE TITLE
Need to link from Bin transform docs to Bin object def

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2732]
Can't click on `Bin` here:

![image](https://user-images.githubusercontent.com/589034/28805805-5a7d8310-7621-11e7-818e-f171ef5ccd06.png)

Should link to https://vega.github.io/vega-lite/docs/bin.html

**Comment by kanitw** [comment]
Done in https://github.com/vega/vega-lite/pull/2872

**Comment by domoritz** [comment]
Actually, I did that before and then you undid it because you renamed Bin -> BinParams :-P

**Comment by kanitw** [comment]
Haha ok sorry about that.
