### ISSUE TITLE
Support RegExp flag for build:examples

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2758]
Suppose we update one or a few examples for docs, we should not have to run the whole build:examples to update every single examples.

**Comment by domoritz** [comment]
Aka, we need a better build system that tracks what specs have changed.

**Comment by kanitw** [comment]
I think RegExp is easier to begin with.  

Tracking changed Vega specs can be helpful, but we may still need to run the whole thing when we bump vega version as SVG may still change.

**Comment by kanitw** [comment]
We now have build:example for single file, which should be sufficient.
