### ISSUE TITLE
Lookup on a materialized selection + Indexed Chart Example

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2765]
We now have look up -- is there anything preventing us from adding it back?

**Comment by arvind** [comment]
Yes, unfortunately -- performing a lookup on a materialized selection (i.e., on a new derived dataset+selection filter). My preference would be to address this in 2.1.

**Comment by domoritz** [comment]
We are now moving towards v4. Can we implement the index chart now?

**Comment by arvind** [comment]
Yes, this would be great to support in v4. I had a branch that had implemented performing lookups on selections but I'd experienced issues where the lookup transform (or timeUnit on the selection) got moved around in ways that I could not understand and thus needed your help @domoritz. Unfortunately, I don't see the branch here on GitHub anymore, and can't find the issue/comment I'd left documenting the issue. 

Will see if I can recreate it soon.

**Comment by domoritz** [comment]
I'm happy to help. Let me know when you have something to demonstrate the issue. We also now have much better debugging of the dataflow. For example, you can comment out https://github.com/vega/vega-lite/blob/262ce13c725bf9021cb1436fab231cc52c61b04b/src/compile/compile.ts#L101 to get a graphical representation of the dataflow.

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega-lite/pull/5286
