### ISSUE TITLE
How to customise initial configuration for single selection?

### ISSUE THREAD

**Issue by amitkaps** [vega/vega-lite#2788]
I created a mulit-line chart which highlights the nearest line, by changing the size of the line. See block here - https://bl.ocks.org/amitkaps/fe4238e716db53930b2f1a70d3401701

The chart works fine once the mouse moves and is over the chart view. However, when the chart first loads, the selection is treated as entire dataset and all the lines are highlighted. Is it possible to customise the behaviour, such that when the mouse is out of the view - 'mouseout', then the selection is treated as none?

I tried playing with event stream, to modify this like below, but this does not seem to work.
```
"on" : "`mouseover, !mouseout`"
```

Any suggestions on how to make this happen? And a broader question, on what the default behaviour of `mouseover` selection should be, when the mouse is not on the view?

**Comment by domoritz** [comment]
Is this related to https://github.com/vega/vega-lite/issues/2696?

**Comment by amitkaps** [comment]
Yes. Apologies, I had not seen that discussion thread, which addresses the design decision around `empty` vs `full` selection at the start. I had seen the documentation and the ability to use `and`, `or` and `not` for multiple selections, but it was not immediately apparent how to use it for single selection.

In case of single selection, the main example of [conditional encoding using selection](https://vega.github.io/vega-lite/docs/selection.html#conditional-encodings), should then be changed by using the `not` selection and reversing the values. It is not as intuitive (for a starter example), but makes more logical sense for this paintbrush highlight example and for single selections in general. 

```js
      "condition": {
        "selection": {"not": "paintbrush"},
        "value": 50
      },
      "value": 300
```
This principle simplifies the code for the multi-line highlight too. I have updated the same. Thanks @domoritz

**Comment by amitkaps** [comment]
If you are ok with this logic, then I have sent a pull request to modify this example - https://github.com/vega/vega-lite/pull/2804

**Comment by kanitw** [comment]
@domoritz  is this issue resolved?

**Comment by domoritz** [comment]
@arvind is https://github.com/vega/vega-lite/pull/2804#issuecomment-321374998 addressed so that we can close this issue?

**Comment by domoritz** [comment]
related: https://github.com/vega/vega-lite/issues/2321

**Comment by pelotom** [comment]
Any update on how to do this without the `not` operator?

**Comment by kanitw** [comment]
Looks like the example here https://vega.github.io/vega-lite/docs/selection.html#conditional-encodings already flipped the conditional logic and removed not?

**Comment by pelotom** [comment]
@kanitw how so? when it first loads all the circles are large, i.e. the selection is active for all elements. This issue is about achieving the opposite: that nothing is selected at the outset.

**Comment by arvind** [comment]
Hi @pelotom: With PR #3038, a new `empty` property will be available for all selections. It can be set to `all` (the default behavior you currently see) or `none`. The latter setting will no longer require the inversing logic discussed here as empty selections will truly be empty. Hope that helps!

**Comment by pelotom** [comment]
Awesome, thanks for the update!
