### ISSUE TITLE
`resolve[channel].scale` => `resolve.scale[channel]` (same for axis/legend)

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2794]
Currently `resolve` is indexed by channel (e.g., `resolve[channel].scale`, not resolve.scale[channel]`.
This is currently fine.  

However, once we introduce `projection`, it should have resolution too.
Since projection is not specific to one channel, resolve.projection wouldn’t fit well under `resolve[channel].scale`, but would fit fine under `resolve.scale[channel]`.  

Thus, I think we might wanna switch to the latter to prevent breaking changes in the future.

**Comment by domoritz** [comment]
```
{
  resolve: {
    scale: {
      x: shared 
    },
    axis: {
      x: shared
    }
  }
}
```

vs
```
{
  x: {
    scale: shared
    axis: shared
  },
  projection: shared
}
```

?

**Comment by domoritz** [comment]
I prefer the latter.

**Comment by domoritz** [comment]
I agree with swapping the key and value. The choice in the first place was arbitrary.
