### ISSUE TITLE
Avoid side effect in assembleData

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2795]
Currently data component optimization happens in `assembleData()` and thus cause side effect in the model.component and requires that assembleData must be the first thing in assemble.  

I think we should have a separate optimizeData() method at the end of the parse.

**Comment by kanitw** [comment]
This is at least causing problem in https://github.com/vega/vega-lite/issues/2736

**Comment by domoritz** [comment]
So you would want assmebleData to come after some other assemble potentially?

**Comment by kanitw** [comment]
It currently is not -- see https://github.com/vega/vega-lite/blob/master/src/compile/compile.ts#L93.

One potential quick fix is to call `const data = model.assembleData()` on the first line for `assembleTopLevelModel` and punt on refactoring this for now.

But in longer term, I think this refactor make sense since we do 
`return assembleTopLevelModel(model, getTopLevelProperties(inputSpec, config));`

as last line of `compile()`, which does not suggest that `assembleTopLevelModel` would have side effect on `model`.

**Comment by kanitw** [comment]
FIxed in #2810
