### ISSUE TITLE
Make count field output as "count", not "count_*"

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2818]
So that it appears nicer on tooltip by default

![image](https://user-images.githubusercontent.com/111269/29148225-dfc87556-7d20-11e7-9326-a176e28aeb8c.png)

**Comment by domoritz** [comment]
Could be problematic since someone may have a field called `count` in their data. It's unlikely that they have `count_*`. Maybe we should start making our generated fields with `__` and remove that from the tooltips.

**Comment by kanitw** [comment]
I don't think we should hide count, but yeah, this could be handled in Vega-tooltip https://github.com/vega/vega-tooltip/issues/129

**Comment by domoritz** [comment]
I wonder whether we should make all internal fields with a `__` prefix to avoid polluting the field names namespace.
