### ISSUE TITLE
Year axis labels are duplicated for datasets with only a 2-year range

### ISSUE THREAD

**Issue by leibatt** [vega/vega-lite#2822]
When a dataset has dates that only span a range of two years (e.g., only 2016 dates and 2017 dates) and x axis is mapped to the years function, the axis labels are duplicated.

```
{
  "data": {
    "values": [
      {
        "date": "2016-07-02"
      },
      {
        "date": "2017-07-02"
      }
    ]
  },
  "transform": [],
  "mark": "tick",
  "encoding": {
    "x": {
      "timeUnit": "year",
      "field": "date",
      "type": "temporal"
    }
  },
  "config": {
    "scale": {
      "useUnaggregatedDomain": true
    }
  }
}
```

**Comment by kanitw** [comment]
This might be a Vega problem, or we need a new trick to deal with this case.

**Comment by kanitw** [comment]
This is a Vega problem and will be fixed as a part of https://github.com/vega/vega-encode/issues/7
