### ISSUE TITLE
Axis labels overlap between visualizations in column layout

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega-lite#2825]
Axis labels may overlap between charts when using the 'column' encoding as in this example specification taken from Voyager:

<img width="563" alt="vegalite-axislabeloverlap" src="https://user-images.githubusercontent.com/3392218/29189336-eec38b36-7dca-11e7-98cc-dd46239723c5.png">

```
{
  "data": {
    "url": "data/population.json"
  },
  "transform": [],
  "mark": "tick",
  "encoding": {
    "column": {
      "field": "sex",
      "type": "nominal"
    },
    "color": {
      "field": "sex",
      "type": "nominal"
    },
    "y": {
      "field": "age",
      "type": "nominal",
      "scale": {
        "rangeStep": 12
      }
    },
    "x": {
      "field": "people",
      "type": "quantitative",
      "scale": {}
    }
  },
  "config": {
    "overlay": {
      "line": true
    },
    "scale": {
      "useUnaggregatedDomain": true
    }
  }
}
```

**Comment by kanitw** [comment]
From quick investigation 

Using
```
                "align": {
                  "signal": "item === item.mark.items[0] ? 'left' : item === peek(item.mark.items) ? 'right' : 'center'"
                }
```
produces

![image](https://user-images.githubusercontent.com/111269/29193244-3b0566f0-7dd9-11e7-97b6-4b2fc9cbd2c0.png)

which no longer have the overlapping problem, but it is not clear whether this is the label of the last tick. 


Tableau seems like solve the problem by skipping last label

![image](https://user-images.githubusercontent.com/111269/29193276-68a2f42e-7dd9-11e7-8feb-527a0363bf12.png)


So one solution is to use:
```
                "align": {
                  "signal": "item === item.mark.items[0] ? 'left': 'center'"
                },
                "text": {
                  "signal": "item === peek(item.mark.items) ? '' : datum.value"
                }
```

to output something like this 

![image](https://user-images.githubusercontent.com/111269/29193305-8a12ab22-7dd9-11e7-8115-07ae788d4cb8.png)

which I like better that the output above. 

We will need to investigate more if this works okay if the minimum domain value is negative though.

**Comment by g3o2** [comment]
While the above example demonstrates collision of labels, it also contains a design flaw: the big numbers on the `x` axis should be shown as millions using `format`, thus making the chart more readable as a whole.

**Comment by kanitw** [comment]
Since it's likely we gonna handle this in Vega (https://github.com/vega/vega/issues/976) and we will have #2880 open, I'll close this.
