### ISSUE TITLE
Bin Transform broken

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2839]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/movies.json"
  },
  "transform": [
    {
      "bin": true,
      "field": "IMDB_Rating",
      "as": "bin_IMDB_Rating"
    }
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "bin_IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

**Comment by kanitw** [comment]
- [ ] please add this back to bin.md once it is ready

**Comment by kanitw** [comment]
Relevant cases to check for pre-binned field 
- [ ] Would it work correctly with stack?
- [ ] Would it work correctly with facet?

**Comment by domoritz** [comment]
Problem is that `bin_IMDB_Rating` is not a field after the binning.

**Comment by domoritz** [comment]
Hmm, I wonder how this ever worked. How do we track that a field is binned?

**Comment by kanitw** [comment]
>  How do we track that a field is binned?

I don't remember seeing any of that, but that's exactly missing.

**Comment by kanitw** [comment]
- [ ] Would it work with selection projection?

**Comment by kanitw** [comment]
One temporary solution is remove `_start` suffix for bin_start.  This means that at very least, users will be able to use the bin_start value. 

I don't think I'm super happy with this but at least this will render some reasonable result (In fact, this is exactly what Tableau does.) 

Even if we have a bin component or something to track if a field is binned, I think we should still do this anyway, just in case some component isn't perfectly wired up with bin, we still always show some result.

**Comment by domoritz** [comment]
> please add this back to bin.md once it is ready

Where was it removed?

**Comment by domoritz** [comment]
Until we have a cleaner solution, ordinal gives better results than quantitative (but hides empty bins!). 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/movies.json"
  },
  "transform": [
    {
      "bin": true,
      "field": "IMDB_Rating",
      "as": "bin_IMDB_Rating"
    }
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "bin_IMDB_Rating",
      "type": "ordinal"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
Closing since we have a working solution now.
