### ISSUE TITLE
Unit charts and `stack=unit` option?

### ISSUE THREAD

**Issue by amitkaps** [vega/vega-lite#2845]
Unit Charts are really helpful when you want to do large multi-dimensional data exploration. See recent example of Facet Dive tool from PAIR - https://pair-code.github.io/facets/

![facet-dive](https://user-images.githubusercontent.com/878499/29240974-bb018b76-7f8d-11e7-86c4-a133d7995d2c.png)

I experimented with creating Unit Charts in Vega-Lite  and you can see the examples for  [Rectangular](https://bl.ocks.org/amitkaps/d6648bd8ddb1c1e3706d7530126d1e2b), [Stacked](https://bl.ocks.org/amitkaps/cdc7dacd8f7d9f2a9cff4b10d3279b86) &  [Small Multiple](https://bl.ocks.org/amitkaps/67bd6dcb2af300a2b76f1e2351c1afdc) Unit Charts in these blocks. See image for Rectangular Unit Chart below.

![thumbnail](https://user-images.githubusercontent.com/878499/29240964-84201ed8-7f8d-11e7-9d7d-be91717c74cd.png)

It is possible to hack & create them (with some manual assumption on sizing) using `transform`, if you already have a primary key e.g. `id` in your datasets. 

```js
  "transform": [
    {"calculate": "ceil(datum.id/ 10)", "as": "X"},
    {"calculate": "datum.id - (datum.X - 1) *10", "as": "Y"}
  ]
```
This works fine at the top-level, but when trying to do small multiples or stacking on `x`, I need to again create keys at that level. See example for [Stacked Unit Chart](https://bl.ocks.org/amitkaps/cdc7dacd8f7d9f2a9cff4b10d3279b86).

![thumbnail](https://user-images.githubusercontent.com/878499/29241850-d91094b0-7f9f-11e7-919d-9bb20ea1ab1f.png)

Two questions:
1. Is there currently an easier way to create Unit Charts, without pre-processing the data and creating these keys manually? Is there a way to access a `key` id, after the top-level transforms for the data have been done? 
2. If not, are there any plans to support this in the future?  It would be great to have an easy way to do these three `unit chart` behaviours: 
    - Stack the space vertically, if `x`channel only has a field.
    - Stack the space horizontally, if `y` is only has a field
    - Fill the cell space , if neither `x` or `y` channel has a field.
 
We can have an option in the `stack` encoding called `unit`, which would make this behaviour happen. However, I don't know how easy this is to implement, or what the impact of this change would be on the current defaults. Just wanted to suggest this as maybe one possible route to take, if you decide to implement this. Thanks.

**Comment by domoritz** [comment]
CC @StevenMDrucker @intuinno

**Comment by amitkaps** [comment]
On further investigation, the transform function from Vega that would make at least the vertical and horizontal stacking straightforward is the [`window`](https://vega.github.io/vega/docs/transforms/window/) transform. That provides access to a `row_number` field -  with or without `groupby` operations. See the Vega code block for Stacked Unit Chart - https://bl.ocks.org/amitkaps/afc67606c057d1c8021d0f8e0d2cfa3e

So maybe the right starting point would be to expose the `window` function as a top-level transform in Vega-Lite. It would also help in doing moving averages for time-series charts.

**Comment by kanitw** [comment]
Vega and D3 stack operator only does 1D stacking, so this wouldn't be a property of `stack`.

But yes, `window` transform can be added to Vega-Lite but we don't plan to do that for 2.0. 

You're welcome to submit a PR though.  :)

**Comment by amitkaps** [comment]
Thanks @kanitw Will take a shot at it and send a PR.

**Comment by domoritz** [comment]
@amitkaps Thanks for helping out! Since the major concern for any new feature in Vega-Lite is how it fits into the overall design, I would propose that you create a design proposal before implementing this feature. We can help you by reviewing the design and telling you what parts of the compiler it affects.

**Comment by kanitw** [comment]
We actually have https://github.com/vega/vega-lite/issues/2488 for window, so I'm closing this. 

If you still planning to send in a PR, please let us know.
