### ISSUE TITLE
Barley's example broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2846]
<img width="870" alt="screen shot 2017-08-12 at 13 21 42" src="https://user-images.githubusercontent.com/589034/29243963-3f1d5156-7f61-11e7-81b0-4d14cb2fc817.png">

**Comment by kanitw** [comment]
Can't reproduced, both locally and online

![image](https://user-images.githubusercontent.com/111269/29245304-0187ccac-7f8b-11e7-9a92-84499ca70b69.png)
