### ISSUE TITLE
add more examples from the documentation to the Example Gallery

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2887]
The documentation shows some nice examples which, maybe after a little refinement, should make it into the Example Gallery, for they nicely illustrate vega-lite's capabilities:

* [line step](https://vega.github.io/vega-lite/docs/config.html#example-interpolate-with-line-step-step-chart);
* [Falkensee](https://vega.github.io/vega-lite/docs/layer.html#advanced-layering-example);
* [log scale](https://vega.github.io/vega-lite/docs/scale.html#example-log-scale);
* [dash plot](https://vega.github.io/vega-lite/docs/tick.html);

**Comment by kanitw** [comment]
Yep, we definitely have to do that.   Thanks for reminder
