### ISSUE TITLE
interactive plots: manipulate legend not data?

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#2888]
Consider a plot with a legend on the right side. For instance, https://owensgroup.github.io/gpustats/plots/Processing%20Power%20over%20Time.html

I'd like to be able to toggle the legend, to turn "on" and "off" data by clicking elements in the legend (in the example, selecting only one vendor or only one datatype). This might completely turn off a channel of data, or perhaps alternatively it might dim it.

All of the [interactivity examples](https://vega.github.io/vega-lite/docs/selection.html) manipulate data within the plot frame. Is it consistent with the grammar to manipulate a legend rather than data?

**Comment by arvind** [comment]
Thanks @jowens! Supporting interactive legends is definitely on the roadmap, but won't initially be supported in 2.0 as there are a number of open questions about what the default behavior should be with explicitly specified selections (#1657). We hope to support it in 2.1.

**Comment by kanitw** [comment]
2.1 => More precisely a subsequent minor versions (just in case other new features land first ;D)
