### ISSUE TITLE
Conditional axis config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2907]
- [x] Remove _future suffixes from examples in https://github.com/vega/vega-lite/pull/3283

**Comment by kanitw** [comment]
The current syntax also feels a bit too many level of nesting for me.  But we can decide about this in the future.  

```
            "axis": {
                "format": "%Y",
                "labelAngle": 0,
                "labelOverlap": false,
                "encoding": {
                    "ticks": {
                        "stroke": {
                            "condition": {
                            "test": {"timeUnit": "monthdate", "field": "value", "equal": {"month": 1, "date": 1}},
                            "value": "black"
                            }
                        }
                    },
                    "labels": {
                        "fill": {
                            "condition": {
                            "test": {"timeUnit": "monthdate", "field": "value", "equal": {"month": 1, "date": 1}},
                            "value": "black"
                            }
                        }
                    }
                }
            }
```

Maybe the "encoding" is not a sufficient level of nesting.   ("ticks", "labels" are just boolean anyway, if they are objects, they are basically "enabled") 

```
            "axis": {
                "format": "%Y",
                "labelAngle": 0,
                "labelOverlap": false,
                "ticks": {
                    "stroke": {
                        "condition": {
                        "test": {"timeUnit": "monthdate", "field": "value", "equal": {"month": 1, "date": 1}},
                        "value": "black"
                        }
                    }
                },
                "labels": {
                    "fill": {
                        "condition": {
                        "test": {"timeUnit": "monthdate", "field": "value", "equal": {"month": 1, "date": 1}},
                        "value": "black"
                        }
                    }
                }
            }
```

**Comment by kanitw** [comment]
@domoritz  Any thoughts about this?

**Comment by domoritz** [comment]
I like your second suggestion.

**Comment by kanitw** [comment]
I feel like the only two cases we need for accessing encode blocks are:

1) Adjusting expression, which might be better done via including expression as a part of format (https://github.com/vega/vega-lite/issues/5122#issuecomment-506870319).

2) Conditional appearance / color for axis/legend parts (e.g., ticks and labels in [the lasagna plot](https://github.com/vega/vega-lite/blob/master/examples/specs/rect_lasagna_future.vl.json) and grid e.g., in [voyager user study plot](https://github.com/vega/vega-lite/blob/master/examples/specs/concat_layer_voyager_result_future.vl.json).

Thus, I think it might be better to just make the following properties support conditional value: 
- `gridColor/Dash/Opacity/Width`
- `labelAlign/Baseline/Color/Font/FontWeight/Opacity`
- `tickColor/Opacity/Width` 

For example, we can make conditional grid color in the Voyager study plot like:

```
axis: {
  tickColor: {
    "condition": {"test": "datum.value === 0", "value": "#666"},
    "value": "#CCC"
  }
}
```

This way, we don't have to open a new can of worm and multiple ways to do the same thing.

**Comment by domoritz** [comment]
I like not opening a can of 🐛s.

**Comment by kanitw** [comment]
We npw support conditional axis properties in https://github.com/vega/vega-lite/pull/5253 -- but we can't use them in the config yet.

**Comment by kanitw** [comment]
Perhaps, this shouldn't be in config anyway since the conditional is data dependent.
