### ISSUE TITLE
Revise if we really ever need bin_range

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2911]
In the past, we definitely need calculate bin_range string but given `bin-ordinal` and `bin-linear` scales, we might not need it anymore.

**Comment by domoritz** [comment]
I tried it but had some problems with ordinal legends. Maybe bin ordinal works in that case but I'd have to try.

**Comment by kanitw** [comment]
Good to know, but lets try this post 2.0

**Comment by domoritz** [comment]
Here is the problem. If you want to use color with binned ordinal (so that empty ins are skipped and you can sort bins), then we need the range for the legend.

**Comment by kanitw** [comment]
I see.  Should we only create range for that case (post 2.0) then?

**Comment by domoritz** [comment]
I have a pr in a minute that cleans up bin scales and also this case.

**Comment by kanitw** [comment]
Your PR pretty much fixes this :)
