### ISSUE TITLE
Custom sort order

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2915]
Currently, for unit encoding, we can specify custom order for normal (non-facet) encoding channel by specifying `scale.domain` directly.

However, we don't have similar support for 
1) facet channel
2) stack (https://github.com/vega/vega-lite/issues/1734)

Since facet does not have scale domain, we can't use similar syntax.  But facet has `sort` property like other encoding channel.  Thus, I think we should make `sort` support a custom array, which derives a formula like [this](https://github.com/vega/vega-lite/issues/1734#issuecomment-263481177) so that it's safer than setting domain directly (as domain would still include omitted values).  

For stack, we can then also make stack order orders by color/detail (or any other stack-by field) by default.

**Comment by curran** [comment]
Great idea! Being able to specify facet ordering seems like an essential feature.

FWIW, as a Vega-Lite noob, I tried the following:

```
        "column": {
          "field": "variable",
          "type": "ordinal",
          "scale": {
            "type": "ordinal",
            "domain": ["Online news sites","Social media","Printed newspapers","TV"]
          }
        },
```

Then I tried this (your proposal here):

```
        "column": {
          "field": "variable",
          "type": "ordinal",
          "sort": ["Online news sites","Social media","Printed newspapers","TV"]
        },
```

I think the above syntax would be really great.

As a separate thought, if the notion of "ordinal" is there in Vega, and is distinct from "nominal", wouldn't it be nice to be able to specify _in the data definition_ the natural ordering of a column?

**Comment by kanitw** [comment]
The same data field can be treated as ordinal or nominal so it makes more sense to specify it as `sort` of a data field definition like proposed above.

**Comment by curran** [comment]
Makes sense. Thanks for your reply.

**Comment by domoritz** [comment]
Column used to be implemented with scales but now we use Vega layouts (which is more flexible and produces nicer output). Does the code snippet with scale pass JSON schema validation in the editor?

**Comment by curran** [comment]
@domoritz No, it does not pass schema validation.

I discovered the validation in the editor only after trying the configuration (rather blindly) in my code.

**Comment by domoritz** [comment]
Okay, that's what I wanted. When we implement this feature, you'll use a sort order on the `header` property.

**Comment by curran** [comment]
Sounds good!

If I had some time to dig and try to implement this, where would be the place to start?

**Comment by domoritz** [comment]
I'd first check how to sort facets in Vega, then see where in Vega-Lite we already generate the order property, and then lastly I'd write some code to let users override the default (+tests).

**Comment by kanitw** [comment]
I would say start with non-facet channel like x and y first. 

Try to see how you can derive a new field by generating a Vega formula transform and then use the new field to sort scale.

For facet channel, then you would similar use the same formula flow, but apply it to facet mark definition groups and headers.

Note that there is also the stack case that you should handle for consistency.

To make review easier, u might want to just tackle the simplest case which is the non-facet channels first.

**Comment by curran** [comment]
Maybe I'm missing something, but as far as I can tell, non-facet channels like X and Y already support custom sort ordering by explicitly setting the scale domain, right?

**Comment by domoritz** [comment]
Yes! The difference is that faceting doesn't use scales but Vega layouts instead.

**Comment by kanitw** [comment]
Yes, we already support scale domain for non-facet channels.

But if `sort` in facet can be an array of values, I think `sort` in non-facet channels should support array of values as well for consistency.

Another thing that is better about the proposal for `sort` array above than `scale.domain` is that if certain value is accidentally omitted from  the `sort`, the underlying ordinal scales could still contain these values. (For example, `sort: ["a", "b", "c"]` like you specify that the scale should start with a, b, and c, and other values come later.)  Meanwhile, if you set `domain` directly, only domain values specified would be include in the scale.

**Comment by curran** [comment]
Aha that's a great point!

**Comment by kanitw** [comment]
Closing this as the core issue for custom sort order will be fixed in https://github.com/vega/vega-lite/pull/3423.

For stack case, I'll re-open https://github.com/vega/vega-lite/issues/1734 so we can keep track of it.  

We also should support sort array for facet as a part of https://github.com/vega/vega-lite/issues/2176.
