### ISSUE TITLE
y axis named `Avg. Time(ms)` does not work, but `Avg Time(ms)` does

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#2932]
If I change `Avg. Time(ms)` to `Avg Time(ms)` in both places it appears below, the graph works properly, but in the current online editor as is, it makes no graph. What's so horribly wrong about the name `Avg. Time(ms)`? That period is really throwing a wrench into things, I guess.

I like the error/warnings part of the online editor. If this is my fault and I'm naming it something dumb, maybe the error/warnings could say so.

```
{
  "data": {
    "values": [
      {
        "#GPUs": 64,
        "Avg. Time(ms)": 900
      }
    ]
  },
  "encoding": {
    "y": {
      "field": "Avg. Time(ms)",
      "type": "quantitative"
    },
    "x": {
      "field": "#GPUs",
      "type": "quantitative"
    }
  },
  "config": {
    "cell": {
      "width": 500,
      "height": 350
    }
  },
  "mark": "point"
}
```

**Comment by arvind** [comment]
The period is being interpreted as a JavaScript field accessor (e.g., `data.price` to mean the `price` property of the `data` variable). For your use case, you could always drop the period in the field names, but add it back in for the axis title. 

I'm not sure if there's anything we can reasonably do to better support this within Vega-Lite. We never load the dataset during compilation (and thus, cannot test for whether periods occur within field names).

**Comment by jowens** [comment]
Thanks. Sensible. Maybe noting this in the docs somewhere would be useful (if it's not already there). As well, in the online editor, maybe this could be a error/warning (if you parse the dataset there)?
