### ISSUE TITLE
Binned Stack Area Broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2936]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "area",
  "width": 800,
  "encoding": {
    "x": {
      "bin": {"maxbins": 100},
      "field": "Horsepower",
      "type": "ordinal"
    },
    "color": {
      "field": "Origin",
      "type": "nominal"
    },
    "y": {
      "field": "Acceleration",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}

```

![image](https://user-images.githubusercontent.com/111269/40764570-729f1306-645e-11e8-8c77-a817278792d1.png)

See https://github.com/vega/vega-lite/pull/2923#issuecomment-325011269

**Comment by kanitw** [comment]
I don't know if we should care about using ordinal for binned stack area since it's bad idea anyway.
However, normal binned stack area seems also broken!

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "area",
  "encoding": {
    "x": {
      "bin": {"maxbins": 100},
      "field": "Horsepower",
      "type": "quantitative"
    },
    "color": {
      "field": "Origin",
      "type": "nominal"
    },
    "y": {
      "field": "Acceleration",
      "type": "quantitative",
      "aggregate": "sum"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/40764734-fe6ed54c-645e-11e8-97cc-ade977f8a515.png)

**Comment by kanitw** [comment]
Likely similar to https://github.com/vega/vega-lite/issues/4939, so I'll close this one as https://github.com/vega/vega-lite/issues/4939 has more info.
