### ISSUE TITLE
Ticks for binned fields are no longer nice

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2942]
```
{
  "data": {
    "url": "data/cars.json"
  },
  "transform": [],
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {},
      "field": "Acceleration",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    }
  },
  "config": {
    "overlay": {
      "line": true
    },
    "scale": {
      "useUnaggregatedDomain": true
    }
  }
}
```

![pasted_image_8_31_17__3_43_pm](https://user-images.githubusercontent.com/111269/29948346-2476cf6a-8e63-11e7-8549-424b89b3e810.png)

@domoritz I remember that you change something earlier -- it might be related to this?

**Comment by domoritz** [comment]
Odd. Works for the one I used for experiments

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": true,
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

This may be related to the fix in https://github.com/vega/vega-lite/pull/2864#issuecomment-322059822

**Comment by domoritz** [comment]
Hmm, bin does not try to get multiples of 5, while axis ticks do.

**Comment by domoritz** [comment]
I think we need a fix in Vega https://github.com/vega/vega-parser/issues/59 and then we can add back the `values` to the Vega output but also output the tickCount.
