### ISSUE TITLE
Legend does not have opacity.

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2948]
`"opacity":{"value": 0.1}`
![image](https://user-images.githubusercontent.com/6269456/29999558-8388841c-9002-11e7-9571-0f0fb45bed8d.png)
`"opacity":{"value": 1}`
![image](https://user-images.githubusercontent.com/6269456/29999574-12b2555a-9003-11e7-9fa5-5fc19197ab3c.png)
Default opacity
![image](https://user-images.githubusercontent.com/6269456/29999583-360067b8-9003-11e7-9547-8c027d1ab559.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "mark": "point",
  "encoding": {
    "x": {
      "field": "AWND",
      "type": "quantitative"

    },
    "color": {
      "field": "WDF5",
      "type": "quantitative"
    },
    "y": {
      "field": "name",
      "type": "nominal"
    }
  },
  "data": {
    "values": [
      {
        "name": "Texas",
        "AWND": 19.46138,
        "WDF5": 160
      },
      {
        "name": "Texas",
        "AWND": 9.39515,
        "WDF5": 310
      }
    ]
  }
}
```
User cannot look up the values represented by those colors if the legend's color scale is not matched. 

The default of opacity value is 0.7 and is also not matched with the default color legend. It seems error-prone.

**Comment by domoritz** [comment]
Good catch. Do you want to send a PR?
