### ISSUE TITLE
How to connect to an external csv file?

### ISSUE THREAD

**Issue by marcelobp** [vega/vega-lite#2962]
Hi all,

I would like to use an external CSV file as a dataset. How can I do that?

In the following example, I would like to change "data/population.json" for something like "http://my_url/population.json"

Is that possible?

{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "mark": "bar",
  "encoding": {
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"},
      "stack":  "normalize"
    },
    "x": {
      "field": "age", "type": "ordinal",
      "scale": {"rangeStep": 17}
    },
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#EA98D2", "#659CCA"]}
    }
  }
}

**Comment by domoritz** [comment]
Yes, that is possible. Just point to your CSV file but make sure that the same origin policy doesn't prevent your browser from accessing the file.

**Comment by marcelobp** [comment]
Hi Dominik,

Thank you for your quick response.
I have tried it locally and with a csv file hosted in another place.
Neither locally or remotely work for me.
Do you have an example of something similar to share with me please?

In addition, we are trying to connect to datasets on Figshare repository.
Do you have any available library to do that?

Thank you again.

Marcelo

**Comment by domoritz** [comment]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "https://vega.github.io/editor/data/movies.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": true,
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

I'm sure figshare has externally visible URLs to their datasets.

**Comment by marcelobp** [comment]
That is awesome.
Thank you Dominik.

**Comment by domoritz** [comment]
I'm glad I could help. Let me know if you run into any issues and I would also love to see the figures you are creating.

**Comment by scokobro** [comment]
Hi - just wondering if @marcelobp got anywhere with connecting to figshare data? 
If so any advice much appreciated.

Thanks.

**Comment by domoritz** [comment]
Yes, we resolved it via Email.

This spec works

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "url": "https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/3576933/hd_antisaccade.csv"
  },
  "mark": "circle",
  "encoding": {
    "x": {"field": "age", "type": "quantitative", "bin": true},
    "y": {"aggregate": "mean", "field": "depression", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/33309999-711f172a-d420-11e7-8087-f6d2e8bb2914.png)

**Comment by scokobro** [comment]
Thanks for this. 
For some reason am still not able to connect to my data; get an 'Access denied' message when I try the URL(for my data, constructed based on the working example you shared) in my browser. 
Weird, as everything figshare-side is set to 'public' access as far as I can see...
Appreciate your help anyway!

**Comment by domoritz** [comment]
What’s your url to the CSV file?

**Comment by scokobro** [comment]
As far as I can work out it should be...

https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/9816337/rsf-fh-columns.csv

'9816337' is the number on the data sheet tab as displayed on the figshare page and 'rsf-fh-columns.csv' is the name of my data file.

The URL for the figshare page is: https://figshare.com/articles/Japan_Press_Freedom_Rankings/5635246

**Comment by marcelobp** [comment]
Hi Scott,

Have you tried this URL: https://ndownloader.figshare.com/files/9816337 ?

Cheers,
Marcelo


On Wed, Nov 29, 2017 at 3:40 PM, Scott Koga-Browes <notifications@github.com

**Comment by domoritz** [comment]
@scokobro Looks like the permissions are different on S3. 

<img width="735" alt="screen shot 2017-11-29 at 22 59 41" src="https://user-images.githubusercontent.com/589034/33401299-1292b894-d559-11e7-9b64-abc2abed07ca.png">

@marcelobp's download like looks better.

**Comment by scokobro** [comment]
Hi Marcelo - that's got it! Excellent, thanks very much. I had tried something similar before but I think I had a trailing slash at the end of the URL, and no "format' set for the data...

This works as expected...

```
  "data": {
    "url": " https://ndownloader.figshare.com/files/9816337", 
    "format": {"type": "csv"}
  }
```

Thanks again @domoritz and @marcelobp (how's sunny Sheffield?)
