### ISSUE TITLE
Layering mean value rule over histogram produce two axes

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2963]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/movies.json"},
  "layer": [{
    "mark": "bar",
    "encoding": {
      "x": {
        "bin": true,
        "field": "IMDB_Rating",
        "type": "quantitative"
      },
      "y": {
        "aggregate": "count",
        "type": "quantitative"
      }
    }
  },{
    "mark": "rule",
    "encoding": {
      "x": {
        "aggregate": "mean",
        "field": "IMDB_Rating",
        "type": "quantitative"
      },
      "color": {
        "value": "red"
      },
      "size": {
        "value": 5
      }
    }
  }]
}
```

![image](https://user-images.githubusercontent.com/111269/30132631-e2ea7838-9305-11e7-9a75-5ff318276f2f.png)

**Comment by kanitw** [comment]
The problem is that binned axis do not have grid by default but the axis for rule have grid by default and with the current structure, we cannot merge if one layer has both main and grid axis and another has only the main axis. 

We may need to split the grid and main axis during assemble instead to enable this, but that requires some major restructuring in axis code.  Thus, I will punt this to post 2.0.

For now, one can always set to the rule's x-axis to `null`.

**Comment by g3o2** [comment]
Maybe an easy way to document this limit would be to provide this example (where the axis is set to `null`) in the example gallery or in the relevant section of the documentation.

**Comment by kanitw** [comment]
This should be a part of https://github.com/vega/vega-lite/issues/3034
