### ISSUE TITLE
Layering error bar with sort field does not work

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2964]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/barley.json"},
  "layer": [{
    "mark": {"type": "point", "filled": true},
    "encoding": {
      "x": {
        "aggregate": "mean", "field": "yield", "type": "quantitative",
        "scale": {"zero": false},
        "axis": {"title": "Barley Yield"}
      },
      "y": {
        "field": "variety", "type": "ordinal",
        "sort": {"field": "yield","op": "mean", "order": "descending"}
      },
      "color": {"value": "black"}
    }
  }, {
    "mark": "rule",
    "encoding": {
      "x": {
        "aggregate": "ci0", "field": "yield", "type": "quantitative",
        "scale": {"zero": false}
      },
      "x2": {
        "aggregate": "ci1", "field": "yield", "type": "quantitative"
      },
      "y": {
        "field": "variety", "type": "ordinal",
        "sort": {"field": "yield","op": "mean", "order": "descending"}
      }
    }
  }]
}
```

gets
```
WARN Dropping sort property "{"field":"yield","op":"mean","order":"descending"}" as unioned domains only support boolean or op 'count'.
```

The output also does not sort correctly:

![image](https://user-images.githubusercontent.com/111269/30133210-e0a39c92-9307-11e7-9c76-2a8124e4c133.png)

**Comment by kanitw** [comment]
I'll remove `sort` from the `layer_error_bars` example for now.
- [ ] Once we fix this, let add the `sort` back.

**Comment by domoritz** [comment]
This is not possible with Vega. We have to optimize the dataflow to merge redundant dataflows. So this is on the agenda anyway and this specific issue doesn't need to have a new issue.

**Comment by kanitw** [comment]
At first glance I agree with you, but thinking a bit more, this case should not require dataflow optimization.

Basically, you have two layers with their own aggregate data. However, both layers sort `variety` by another field, which means that the domain for `variety` (y-scale) should be drawn from the pre-aggregate data (`data_0`) anyway.  Thus, this is definitely possible in Vega.  There must be some bug in domain that makes this wrong.

**Comment by domoritz** [comment]
I think I disagree. data_0 and data_2 are the non-aggregated datasets but they are not merged.

**Comment by kanitw** [comment]
Oh true, I'll add this as a test case for #2177 then.
