### ISSUE TITLE
galleryParameter no longer works on the example gallery

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2969]
I remember you change the example gallery style.

Somehow the gallery layout is badly cropped and can no longer be customized

![image](https://user-images.githubusercontent.com/111269/30177791-ba6a23ac-93bb-11e7-9ce6-19ec1f6f16c7.png)

**Comment by domoritz** [comment]
You can now hover over a chart to see it completely. I don't see a simple way to support both.

**Comment by kanitw** [comment]
Sure but that gives terrible first impression... In general, don't require interactions if you have make it nice staticly

**Comment by domoritz** [comment]
The Vega examples have the same issue: https://vega.github.io/vega/examples/

Maybe it's sufficient to scale some of the images.

**Comment by kanitw** [comment]
> Maybe it's sufficient to scale some of the images.

I think so, or change default height should be fine.
