### ISSUE TITLE
Revise if `autoResize` is a name that we will not change forever

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2981]
@domoritz I remember you add `autoResize`, which is basically `autosize.resize` in Vega.

I can't remember exactly why they should have different names, except that we do not support other `autosize` parameters in Vega-Lite (as least for now).  However, I am not sure if this will remain true forever.  Thus, I wonder if we should either revise this naming or not `@hide` it until we're confident about it. 

(I also can't remember the use case for it.)

**Comment by domoritz** [comment]
I thought we needed that for the streaming data example https://vega.github.io/vega-lite/tutorials/streaming.html. I think the option is useful if you want to avoid layout changes when you add or remove data.

**Comment by domoritz** [comment]
So experimenting a bit, I noticed that Vega treats top level `width` and `height` different from signals in general. With top level width and height, we could support `fit`.
