### ISSUE TITLE
Extract typing files for vega-embed, vega-util, vega

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2984]
Better move them to their repos and make them more complete.

**Comment by arvind** [comment]
There's also the `typings` branch in vega-parser that could prove useful in the future.

**Comment by domoritz** [comment]
Yes, it would be great to have typings right in the projects.

**Comment by chadbr** [comment]
and for reference: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/vega

Any reason they shouldn't be there (vega-embed.d.ts, vega-lite.d.ts)?

**Comment by kanitw** [comment]
Note that given how we generate some parts of vl interfaces, we probably will need to copy some definitions (and tsdocs) into VL's unterface directly.


@chadbr -- for definitelytyped, isnt usually when third party author the typing files? I know embedding in the repo is another reasonable option and maybe more convenient if the project author creates declaration files themselves?

**Comment by domoritz** [comment]
Embedded files would definitely be the preferred option.

**Comment by chadbr** [comment]
@kanitw it makes sense for you to embed vega-lite in your package -- for sure...

but vega, vega-embed, etc... should be shipped in those repo's / packages. If not, then definitelytyped should be used.

Also - you shouldn't need to create any .d.ts's yourself -- the compiler will generate them and you can ship them with your npm package.

{
  "compilerOptions": {
    "target": "es6",
    "outDir": "dist",
    "rootDir": "src",
    "moduleResolution": "node",
    "module": "commonjs",
    **"declaration": true,**

**Comment by chadbr** [comment]
@kanitw it makes sense for you to embed vega-lite in your package -- for sure...

but vega, vega-embed, etc... should be shipped in those repo's / packages. If not, then definitelytyped should be used.

regarding this:
>> Note that given how we generate some parts of vl interfaces, we probably will need to copy some definitions (and tsdocs) into VL's unterface directly.

You shouldn't need to create any .d.ts's yourself -- the compiler will generate them and you can ship them with your npm package.

```
{
  "compilerOptions": {
    "declaration": true,
```


If you do want to "generate" them for some reason -- you can export the same interface from multiple places and TypeScript will automatically merge them:

see Merging Interfaces here: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by domoritz** [comment]
> You shouldn't need to create any .d.ts's yourself -- the compiler will generate them and you can ship them with your npm package.

@chadbr That's assuming that the code is typescript, which is only true for Vega-Lite right now. I have a pending PR to port Vega-Embed ;-)

**Comment by domoritz** [comment]
I'm closing this issue as we have a Vega-Embed ts pr at https://github.com/vega/vega-embed/pulls and a Vega typings issue at https://github.com/vega/vega-parser/issues/63.

**Comment by chadbr** [comment]
ok - the main reason I brought it up is there is a vega.d.ts in both vega-lite and definitelyTyped -- and the one is definitelyTyped is far more complete. It's just a bit confusing.

Thanks!

**Comment by domoritz** [comment]
The typings branch has much more complete typings: https://github.com/vega/vega-parser/tree/as/typings/typings

**Comment by chadbr** [comment]
awesome! looking forward to it landing sometime.
