### ISSUE TITLE
Interactive dashboard experiment

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2987]
I built an interactive dashboard and noticed a few things.

* [x] @arvind, I had to add `"encodings": ["x"]` to the selection. Otherwise, the selection would not work across the charts. Why is that? 
* [x] @arvind, I'd like to start with an empty selection. https://github.com/vega/vega-lite/issues/2321
* [x] @kanitw, why is the legend in the upper chart always aligned with the lower chart. I don't think they should be linked or at least there should be an option to unlink them. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/movies.json"},
  "vconcat": [
    {
      "layer": [{
        "mark": "rect",
        "encoding": {
          "x": {
            "bin": {"maxbins": 10},
            "field": "IMDB_Rating",
            "type": "quantitative"
          },
          "y": {
            "bin": {"maxbins": 10},
            "field": "Rotten_Tomatoes_Rating",
            "type": "quantitative"
          },
          "color": {
            "aggregate": "count",
            "type": "quantitative",
            "legend": {
              "title": "All Movies"
            }
          }
        }
      }, {
        "transform": [{
          "filter": {"selection": "pts"}
        }],
        "mark": "point",
        "encoding": {
          "x": {
            "bin": {"maxbins": 10},
            "field": "IMDB_Rating",
            "type": "quantitative"
          },
          "y": {
            "bin": {"maxbins": 10},
            "field": "Rotten_Tomatoes_Rating",
            "type": "quantitative"
          },
          "size": {
            "aggregate": "count",
            "type": "quantitative",
            "legend": {
              "title": "In Selected Category"
            }
          },
          "color": {
            "value": "#333"
          }
        }
      }]
    }, {
      "mark": "bar",
      "selection": {
        "pts": {"type": "single", "encodings": ["x"]}
      }, 
      "encoding": {
        "x": {"field": "Major_Genre", "type": "nominal"},
        "y": {"aggregate": "count", "type": "quantitative"},
        "color": {
          "condition": {
            "selection": "pts",
            "value": "steelblue"
          },
          "value": "grey"
        }
      }
    }
  ],
  "config": {
    "range": {
      "heatmap": {
        "scheme": "greenblue"
      }
    }
  }
}
```

It's kind of amazing how easy it is to create these interactive visualizations with just a few lines on json. 

<img width="489" alt="screen shot 2017-09-08 at 23 00 35" src="https://user-images.githubusercontent.com/589034/30237563-a46a7316-94e9-11e7-91fa-42203e6df360.png">

**Comment by kanitw** [comment]
Just like Tableau, legends are "shared" by default. 

![image](https://user-images.githubusercontent.com/111269/30242043-15f25080-9544-11e7-9f23-e12af39dad2c.png)

You can make them independent legend:

```
  "resolve": {
    "legend": {
      "color": "independent",
      "size": "independent" 
    }
  },
```

![image](https://user-images.githubusercontent.com/111269/30242056-3d03f566-9544-11e7-9184-815b1283cebd.png)

**Comment by arvind** [comment]
As per the milestone designation in #2321, controlling the empty behavior for a selection has been deferred to a subsequent release. 

With regard to your first question, the default projection for single and multi selections identifies the specific point(s) interacted with (i.e., the projection is over the `_vlsid_` field). In your dashboard, as binning and aggregation occurs in both views, no two tuples share the same identifier.

**Comment by kanitw** [comment]
Looks like all questions are answered.  Close?
