### ISSUE TITLE
Pad continuous scales for bar

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2988]
Currently, we use `continuousBandSize` for bar = 2.  

This means that bars on continuous scales (such as linear and time scales) are very thin.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": "bar",
  "encoding": {
    "x": {"timeUnit": "month", "field": "date", "type": "temporal"},
    "y": {"aggregate": "mean", "field": "price", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/30244644-150acf98-9577-11e7-8189-0f9eff0bf5aa.png)
 
Looking at Tableau, they actually set default bandSize on quantitative scale to be quite big.

![image](https://user-images.githubusercontent.com/111269/30244648-42b12bcc-9577-11e7-9314-88a1f742138a.png)

However, note that they also automatically pad the domain of the x-scale so that the bar fits within the plot.  

 In VL, if we only increase  `continuousBandSize`, we will get something like this:

![image](https://user-images.githubusercontent.com/111269/30244665-7aca30a8-9577-11e7-9887-4e6254bbc9ba.png)

It seems like we should determine a method to expand the x-domain by a little bit akin to Tableau.

- Maybe we can do this by calculating extent and set the domain to slightly expanded extent.  But I wonder if we should make [Vega scale domain's data reference](https://vega.github.io/vega/docs/scales/#domain) support this feature.
- Moreover, we need a good rule of thumb for how much should we expand the domain by default.  The rule might vary for quantitative and temporal data and for binning/timeUnit. 

Note that Tableau also consistently expand the scale domain even for scatter plots -- probably for consistency when users transition between different marks. 

![image](https://user-images.githubusercontent.com/111269/30244688-1c1a323c-9578-11e7-85ed-b786351bd703.png)

cc: @jheer @arvind @domoritz -- Any thoughts?

**Comment by kanitw** [comment]
For prebinned data, we need a similar data domain expansion to make bar fits within the scale.

```
{
    "data": {
        "values": [
            {
                "bin": 0.0,
                "count": 28
            },
            {
                "bin": 0.1,
                "count": 55
            },
            {
                "bin": 0.2,
                "count": 43
            },
            {
                "bin": 0.3,
                "count": 91
            },
            {
                "bin": 0.4,
                "count": 81
            },
            {
                "bin": 0.5,
                "count": 53
            },
            {
                "bin": 0.6,
                "count": 19
            },
            {
                "bin": 0.7,
                "count": 87
            },
            {
                "bin": 0.8,
                "count": 52
            }
        ]
    },
    "description": "A simple bar chart with embedded data.",
    "mark": "bar",
    "encoding": {
        "x": {
            "field": "bin",
            "type": "quantitative"
        },
        "y": {
            "field": "count",
            "type": "quantitative"
        },
        "color": {
            "value": "#007AFF"
        },
        "size": {
          "value": 30   
        }
    },
    "width": 600,
    "height": 450
}
```

![image](https://user-images.githubusercontent.com/111269/30403786-1d923d08-9898-11e7-8d47-e53637d885cd.png)

**Comment by kanitw** [comment]
Note that I have changed continuous bandSize to `5` in https://github.com/vega/vega-lite/pull/3012.  The remaining issue is how do we pad continuous scales.

**Comment by volh** [comment]
Hi, 

I've stumbled upon this issue while implementing bar chart for temporal data.
 
At first, I did increase continuousBandSize, which resulted in the wrong padding just like you illustrate. So I ended up making this a special case ( user can change the type of the chart ), changing the scale to nominal and reformatting input data from dates to a strftime string. 

What I'd ideally do is just manually increase the scale domain, like I did in d3. I believe this is possible in Vega, but not in Vega Lite. But anyway, the defaults you are suggesting would be very helpful too as I won't have to introduce any special cases to the app ( which was the whole point to chose Vega for me in the first place ).

Just my 2c. Thanks for looking into this.

**Comment by kanitw** [comment]
Thanks for your comments.

> What I'd ideally do is just manually increase the scale domain, like I did in d3. I believe this is possible in Vega, but not in Vega Lite. 

Note that you can use customize scale [`domain`](https://vega.github.io/vega-lite/docs/scale.html#domain) in VL just like in Vega/D3.  (See [this comment](https://github.com/vega/vega-lite/issues/2912#issuecomment-329315656) for example.)

So the remaining issue is only how do we pad continuous scales automatically.

**Comment by kanitw** [comment]
Seeing https://github.com/vega/vega-lite/issues/2147, I wonder what should be the default padding for area.

**Comment by kanitw** [comment]
Taking tableau as inspiration, this is not a bad thing. 
![image](https://user-images.githubusercontent.com/111269/31001738-dd1f3dac-a49a-11e7-970c-7f8aa4ebd8a4.png)

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3147
