### ISSUE TITLE
Support autosize: fit for facet/concat/repeat

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2992]
In https://github.com/vega/vega-lite/pull/2991, we support autosize: fit for layer and unit specs.
Other specs are not supported yet.

**Comment by pelotom** [comment]
This would be a killer feature for our team. We have a requirement to keep everything within a certain externally-defined bounds and allow the user to resize it at will. Currently we are limited to using raw Vega because Vega Lite doesn't allow for this.

**Comment by kanitw** [comment]
I agree this will be extremely useful.  

Note that we didn't implement this yet because  the`layout` operator in Vega currently operates without interacting with `autosize` fit -- thus we can't implement this to works in Vega-Lite.  

Supporting this will actually require a major change in Vega.

**Comment by djahandarie** [comment]
@kanitw Do you know if there is any progress on this? (Is there a vega issue that could be linked to?)

FWIW, I keep on running into this.

**Comment by domoritz** [comment]
Nothing yet and I don't think we will get to it anytime soon. We would appreciate contributions from the community (e.g. design documents, prototypes, pull requests), though.

**Comment by pelotom** [comment]
See related:

https://github.com/vega/vega-lite/issues/2047
https://github.com/vega/vega/issues/1444

**Comment by domoritz** [comment]
I am going to close this issue since we need major changes in Vega, which are tracked in https://github.com/vega/vega/issues/1444.

**Comment by kanitw** [comment]
Suppose vega/vega#1444 is done, there is still a lot of work items to do in VL? 

I'd rather only close this if we say vega/vega#1444 is a wontfix too.

**Comment by domoritz** [comment]
Talking to @jheer it sounds like it's not even on the roadmap. And yes, we would still need to do a thing or two here.
