### ISSUE TITLE
Typings for InlineData's values

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2998]
- [x] Why is it `any[] | string`, not `object[] | string`?  

- [x] `any[]` would appear as `[]` in the table 

![image](https://user-images.githubusercontent.com/111269/30289829-45d2d712-96e2-11e7-8010-3ec60a365c88.png)

> This can be a string or an array of objects or primitive values. 

- [x] Need more explanation what string is for (I guess for csv/tsc/etc.) + what's the format for the string.   Maybe it's worth adding an example to the docs given that you already create an example anyway.

**Comment by domoritz** [comment]
> Why is it any[] | string, not object[] | string?

Because you can have an array of primitive values. See https://vega.github.io/vega/docs/data/

**Comment by kanitw** [comment]
Ok Thanks.  Then make sure this doc is sufficient by itself so readers of this docs don't have to see  https://vega.github.io/vega/docs/data/ ;P

**Comment by domoritz** [comment]
@kanitw The particular question you had is already answered. "Arrays of primitive values are ingested as objects with the `data` property."
