### ISSUE TITLE
compile() produces a spec with a default height but no default width

### ISSUE THREAD

**Issue by pelotom** [vega/vega-lite#3039]
When compiling a vega-lite spec which has no specified `width`/`height`, the resulting vega spec obtains a default `height` but no default `width`.

```js
import { compile } from 'vega-lite'

const { spec } = compile({ /* ... */ })

spec.width // === undefined
spec.height // === 200
```

This is causing a downstream [issue in `react-vega-lite`](https://github.com/kristw/react-vega-lite/issues/2).

**Comment by kanitw** [comment]
Hi, 

I think your x-axis must be an ordinal or nominal field in this case and thus width is dynamically determined based on rangeStep at runtime.  

See the rules for default width [here](https://vega.github.io/vega-lite/docs/spec.html#single). 

If you think it is not the case, please provide the VL specification that you use.

**Comment by pelotom** [comment]
That makes sense, thanks. Looks like something `react-vega-lite` is failing to take into account.

**Comment by kanitw** [comment]
cc: @kristw
