### ISSUE TITLE
"labelOverlap": false is not respected

### ISSUE THREAD

**Issue by pelotom** [vega/vega-lite#3045]
(this originated as an issue on `vega`, opening an issue here as requested in [this comment](https://github.com/vega/vega/issues/1019#issuecomment-332741429))

Using `"labelOverlap": false` seems to have no effect; in the following chart every other label on the x axis is still being removed:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
    "type": "line",
    "interpolate": "step-after"
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": { "labelAngle": -60, "labelOverlap": false } },
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

![60](https://user-images.githubusercontent.com/128019/30952595-5e58f502-a3dd-11e7-8577-55c2d0b2b6bf.png)

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3071
