### ISSUE TITLE
x axis potentially goes too far

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3048]
https://vega.github.io/editor/#/examples/vega-lite/area

<img width="411" alt="screen shot 2017-09-28 at 22 08 26" src="https://user-images.githubusercontent.com/589034/31001560-a50ca9f0-a499-11e7-9306-3b80933b3228.png">

**Comment by kanitw** [comment]
You already filed https://github.com/vega/vega-lite/issues/2147 ....
