### ISSUE TITLE
Field names are incorrectly escaped in the marks and scales sections

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3055]
This graph works fine when the field name is "Close", but I need to use "Adj. Close", which fails even if i enclose it in quotes. Looking into the compiled spec, the field is correctly used in the `data` section, but needs to be escaped as `['Adj. Close']` inside `marks` and `scales` section.

```js
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "https://www.quandl.com/api/v3/datasets/WIKI/TSLA.csv"
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "Date",
      "type": "temporal",
      "axis": {"format": "%Y-%m-%d"}
    },
    "y": {"field": "Close", "type": "quantitative"}
  }
}
```

**Comment by kanitw** [comment]
Looks like it's fixed! :) 

![image](https://user-images.githubusercontent.com/111269/40764491-12479d2a-645e-11e8-98e8-f2f2125b07ed.png)
