### ISSUE TITLE
Sort by field's ascending and descending might be incorrect for ordinal scales

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3061]
@kristw Can you provide an example?

**Comment by kristw** [comment]
The y-axis is described as "ascending", but the topmost bar has the highest value.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 600,
  "height": 300,
  "data": {
    "values": [
      {
        "category": "d3",
        "value": 168
      },
      {
        "category": "excel",
        "value": 129
      },
      {
        "category": "tableau",
        "value": 109
      },
      {
        "category": "other javascript",
        "value": 89
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "axis": {
        "title": "Count",
        "tickCount": 5
      },
      "field": "value",
      "type": "quantitative"
    },
    "y": {
      "axis": {
        "title": "Technology"
      },
      "field": "category",
      "type": "nominal",
      "sort": {
        "field": "value",
        "op": "mean",
        "order": "ascending"
      }
    }
  }
}
```

**Comment by domoritz** [comment]
<img width="739" alt="screen shot 2017-10-02 at 21 31 54" src="https://user-images.githubusercontent.com/589034/31110064-258962cc-a7b9-11e7-839b-e2dabf0b7bb6.png">

Here is descending

<img width="730" alt="screen shot 2017-10-02 at 21 32 38" src="https://user-images.githubusercontent.com/589034/31110082-3f908894-a7b9-11e7-8b10-a050780862a5.png">

I don't think this is necessarily wrong if you look from the bottom :-P. Yeah, we should flip it.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3063
