### ISSUE TITLE
improve utility function to extract all transform to `transform` block

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3069]
Currently, `aggregate`, `bin`, `timeUnit` can be done inside `encoding`.  
However, for larger data, it may make more sense to extract heavy data processing to a database. 

We should provide a utility function to take a Vega-lite spec as input, and output another Vega-Lite spec that do not use any transform function ( `aggregate`, `bin`, `timeUnit`) inside `encoding`. 
This should make it easier to integrate with a database.

**Comment by domoritz** [comment]
I think this needs some more thought than just this one utility function. I'm going to close this as it is not actionable.

**Comment by kanitw** [comment]
Why is this not actionable?  This is already needed by Voyager.

**Comment by kanitw** [comment]
I guess you're complaining about composite plot. So what I describe above is a version for single view plot.  

A more generalized version of this would be extract a transform tree from a visual encoding spec so that people can re-use the transform tree and reapply it in database.

**Comment by domoritz** [comment]
Thanks for the explanation. I wonder whether a utility function is the right approach. I would think that a flag to return a spec without transforms and a spec with just the transforms would be super useful to that the database knows what exactly it needs to compute.

**Comment by kanitw** [comment]
Note: timeUnit in transform do not make the right timeFormat in encoding, so we would have to manually include `format` in this function.

**Comment by kanitw** [comment]
We already have it, just need to improve it (see https://github.com/vega/vega-lite/issues/3765).
