### ISSUE TITLE
Add week-related timeUnits? (or document an alternate strategy?)

### ISSUE THREAD

**Issue by mstone** [vega/vega-lite#3081]
I'm working on a histogram where I'd like to bin a temporal field by "yearweek", rather than "yearmonth" or "yearmonthdate".

Should I expect to be able to do this via the "timeUnit" temporal binning indicator?

(Or should I instead transform my data to calculate "yearweek" keys using an algorithm of my choice, thereby allowing me to control the boundaries of a "week", or should I instead pursue some other strategy entirely?)

Thank you!

**Comment by domoritz** [comment]
Vega does not support week (assuming you mean the week of the year, not the day of the week) and so vega-Lite does not support it either. You can compute it externally and just pass the computed data to Vega-Lite.

**Comment by kanitw** [comment]
Note that one of the main reason Vega does not support this is that Javascript does not provide a native `getWeek()` functions for date.
