### ISSUE TITLE
Document how to customize facet 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3083]

**Comment by kanitw** [comment]
cc: @oleg131

To answer your questions here: https://github.com/vega/vega-lite/issues/2180#issuecomment-335734635.  

The key idea is that title and label headers for facet use `guide-title` and `guide-label` styles, so you can use `config.style.guide-title/label` to customize

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Anscombe's Quartet",
  "data": {"url": "data/anscombe.json"},
  "mark": "circle",
  "encoding": {
    "column": {"field": "Series", "type": "nominal"},
    "x": {
      "field": "X",
      "type": "quantitative",
      "scale": {"zero": false}
    },
    "y": {
      "field": "Y",
      "type": "quantitative",
      "scale": {"zero": false}
    },
    "opacity": {"value": 1}
  }
  ,
  "config": {
    "style": {
      "guide-label": {
        "fontSize": 30
      }
    }
  } 
}
```

![image](https://user-images.githubusercontent.com/111269/31463318-c102206a-ae83-11e7-890c-933870d95a31.png)

**Comment by oleg131** [comment]
A couple of issues with this:

- including

```
"style": {
      "guide-label": {
        "fontSize": 30
      }
    }
```

in the config makes xticks disappear altogether (even though you can see that their size changes, since the whole image scales up). 

![untitled](https://user-images.githubusercontent.com/10161825/31487561-ee64ef42-af32-11e7-8412-ad78d371b5be.png)


- The facet texts which are unmodifiable at the moment are the facet titles and "facet ticks", i.e. "Series", "I", "II", and "III" in your image, not the xticks.

**Comment by kanitw** [comment]
@oleg131 Thank for your comments.

- The first issue about text disappearing is no longer happen with the latest codebase.  
We will release a new version of RC shortly so this should no longer be a problem.

> The facet texts which are unmodifiable at the moment are the facet titles and "facet ticks", i.e. "Series", "I", "II", and "III" in your image, not the xticks.

- You can use `header.title` of a row/column to customize the title.  We do not have `values` properties like axis yet but you can derive a new field using a calculate transfrom to customize the labels too.  

In any case, I'm documenting current possible customization for facet in https://github.com/vega/vega-lite/pull/3095 so I'm closing this issue. 

For further facet customization feature request, please file them in https://github.com/vega/vega-lite/issues/2446 or as a separate issue.
