### ISSUE TITLE
Can NaN values be displayed as split lines?

### ISSUE THREAD

**Issue by hadim** [vega/vega-lite#3098]
See the following plot produced with Matplotlib:

![plot](https://user-images.githubusercontent.com/528003/31580733-d692b1c4-b126-11e7-809f-f148a3821b38.png)

The line has been produced with a single vector that contains NaN values. Vega-lite joins all the point together:

![screenshot from 2017-10-14 21-30-43](https://user-images.githubusercontent.com/528003/31580737-fbc1507c-b126-11e7-84be-b04e8e7e65a7.png)

Is that possible to do that with Vega-Lite?

**Comment by domoritz** [comment]
You could add a new field for each group and use that with the detail channel.

**Comment by hadim** [comment]
The thing is I don't know how many groups are going to be present in the data and it could be a lot potentially.

**Comment by domoritz** [comment]
That's okay. You add an additional column with the group number.

**Comment by kanitw** [comment]
@domoritz is this issue done? If so close?

**Comment by domoritz** [comment]
I think so.
