### ISSUE TITLE
Change default time format

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3103]
Why is the default time format for year month "January of 2010"?

This seems extremely inefficient and verbose.   

Maybe Jan 2010 is better?

**Comment by kanitw** [comment]
(Shorter one is especially important since we no longer rotate labels for temporal)

**Comment by kanitw** [comment]
I also wonder if default time format for "temporal" field should be just the large time unit part?

For example, for yearmonthdate, is it really sufficient to show all year and month and date on the label?  Maybe just year is better use of space. 

![image](https://user-images.githubusercontent.com/111269/31588653-0ac60648-b1aa-11e7-9766-f5396b0b6067.png)

**Comment by kanitw** [comment]
I think it might make sense to have `timeFormat` function as a compile option so users can have a custom function to generate timeFormat from a timeUnit.  (This one isn't critical for 2.0 though)

**Comment by kanitw** [comment]
> For example, for yearmonthdate, is it really sufficient to show all year and month and date on the label? Maybe just year is better use of space.

Or maybe first two units?  (Just in case users try to show  Feb 2017 to May 2017)

**Comment by domoritz** [comment]
I agree that "Jan 2010" or even "01/2010" is better.

**Comment by domoritz** [comment]
Although I like "Jan" better than "01" because it is not ambiguous.

**Comment by kanitw** [comment]
Yes.  Thanks for American standard that makes the world confused. 

![image](https://user-images.githubusercontent.com/111269/31588734-24808b8e-b1ab-11e7-81b7-511e5fd20fc8.png)


From https://www.theguardian.com/news/datablog/2013/dec/16/why-do-americans-write-the-month-before-the-day

**Comment by domoritz** [comment]
"standard"

**Comment by domoritz** [comment]
It's already short.
