### ISSUE TITLE
Composite examples missing

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3150]
See https://vega.github.io/vega-lite/docs/compositemark.html

**Comment by domoritz** [comment]
Hey @mattwchun, are you fixing this?

**Comment by mattwchun** [comment]
@domoritz I won't be able to get to it for a couple of weeks but I can definitely fix it.

**Comment by domoritz** [comment]
Since we don't ship this in 2.0, it's fine. Just wanted to make sure
somebody is looking at it.
