### ISSUE TITLE
DOCs: broken "type" link

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3155]
At [encoding docs](https://vega.github.io/vega-lite/docs/encoding.html#field-def), property `type` in the table links to https://vega.github.io/vega-lite/docs/encoding.html#data-type (broken link).  I think it should be linking to https://vega.github.io/vega-lite/docs/type.html

**Comment by domoritz** [comment]
Good catch! This fix required only a single line change in `link.yml`
