### ISSUE TITLE
Tukey box plot in gallery has incorrect whisker calculations

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3163]
The calculation of the whiskers in the Tukey box plot in the gallery is incorrect, although it inadvertently produces a correct-looking plot. `lowerWhisker` is defined twice:

    {
      "calculate": "datum.upperBox - datum.lowerBox",
      "as": "IQR"
    },
    {
      "calculate": "datum.lowerBox - datum.IQR * 1.5",
      "as": "lowerWhisker"
    },
    {
      "calculate": "datum.upperBox + datum.IQR * 1.5",
      "as": "lowerWhisker"
    }

The final calculation should be `"as": "upperWhisker"` and probably more correctly the lowerWhisker should be clamped, to avoid negative population figures:

    {
      "calculate": "datum.upperBox - datum.lowerBox",
      "as": "IQR"
    },
    {
      "calculate": "max(0,datum.lowerBox - datum.IQR * 1.5)",
      "as": "lowerWhisker"
    },
    {
      "calculate": "datum.upperBox + datum.IQR * 1.5",
      "as": "upperWhisker"
    }

**Comment by domoritz** [comment]
Good catch! I am looking into it right now.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3165. Thank you for reporting the issue @jwoLondon!  

I think clamping is correct for the population example but not in general, right?

**Comment by jwoLondon** [comment]
In general, I think Tukey plot whiskers should never extend beyond the actual range of data, so to make a faithful Tukey plot, clamp by min and max values.

**Comment by domoritz** [comment]
You're right, we should clamp to the min and max values. We will address this in a separate issue: https://github.com/vega/vega-lite/issues/3166.

**Comment by g3o2** [comment]
It would be nice if the example also plotted the outlying points, i.e. those beyond the quartile3/1 ± 1.5 * IQR. After all, that's the point of a Tukey box plot.

**Comment by domoritz** [comment]
@g3o2 good point. Note that we are generating the example using the "box-plot" marktype. It is currently hidden from the documentation and the schema but we will publish it after the 2.0 release. We will add support for clamping and outliers. 

cc @mattwchun
