### ISSUE TITLE
Clamp whiskers to min and max

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3166]
See https://github.com/vega/vega-lite/issues/3163

**Comment by kanitw** [comment]
@jwoLondon @domoritz  -- Can you post a reference that says that Tukey's original box plot supposes to do this clamping? I don't remember seeing one.

**Comment by mattwchun** [comment]
@kanitw it says here: https://www.graphpad.com/support/faq/five-ways-to-plot-whiskers-in-box-and-whisker-plots/

**Comment by kanitw** [comment]
@mattwchun  Thanks.  This means that it makes sense for you to fix this issue then :)

**Comment by kanitw** [comment]
- [ ] This also makes Tukey box plot a better default than min-max box-plot
- [ ] I think it also makes sense to add the outliers by default.  (Perhaps add a flag called `outliers: boolean` in the BoxPlot definition to allow disabling the outliers layer.)

**Comment by kanitw** [comment]
Actually, the outlier is a bit more complicated to do, so let's ignore that comment for now.

**Comment by g3o2** [comment]
outliers are best added "manually" using filter transform on a separate layer...

**Comment by kanitw** [comment]
> outliers are best added "manually" using filter transform on a separate layer...

Yes, but you have to filter by the aggregated value, and there is no easy way to do that automatically yet until we have the (pending) window transform.

**Comment by kanitw** [comment]
Done in #3237 -- other subtasks are now forked as new issues.
