### ISSUE TITLE
Candlestick chart example has conflicting color scales

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3170]
In the Candlestick chart example in the gallery, the two layers each define their own color scale range mapping. By default, the scales in each of the layers are unioned so these two color scales are in conflict. This is not detectable in the plot as both colour definitions are the same.

Either add

    "resolve": {"scale": {"color": "independent"}}

which would theoretically allow the colours of bars and lines to be different, or remove the second layer's color scale object (which is probably the best solution for this example where both layers use the same colouring).

I note also that in the online editor, the warning about the conflicting scales only appears if the example is re-parsed (along with an additional warning : Cannot stack "y" if there is already "y2". Shouldn't the warnings appear when first parsed?

**Comment by domoritz** [comment]
Thank you for the report. I removed the second scale domain definition. I noticed that the definition of `isIncrease` was also incorrect. I also corrected that.

The warning not appearing on the first parse is a bug in the editor that is tracked at https://github.com/vega/vega-editor/issues/210.

**Comment by domoritz** [comment]
I also created an issue for the odd warnings: https://github.com/vega/vega-lite/issues/3172.
