### ISSUE TITLE
AxisConfigMixins defined in schema but never used

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3183]
in [v2.0.0-rc6](https://github.com/vega/schema/blob/master/vega-lite/v2.0.0-rc6.json). Should this be removed, or is it meant to be used elsewhere in the schema?

**Comment by domoritz** [comment]
The schema may contain things that are never used because we hide features that are not ready yet or because of inheritance. That's the case in this particular one because JSON schema does not support inheritance and we merge interfaces. That means we can have stray interfaces that are inherited from.

**Comment by jakevdp** [comment]
Ah, that makes sense. From the schema user's point of view, is there any situation in which this added definition would be useful? If not, it may be worth black-listing it from export to avoid confusion.

**Comment by domoritz** [comment]
There isn't any use. However, to remove unused definitions, we would have to walk the whole schema tree from the root and keep track of what is used. So far it hasn't been an issue. 

We could either clean up the schema in Altair before generating the schema or add a cleanup script to Vega-Lite. Another option is that we add an annotation to the JSON schema about what a class inherited from. I'm not sure how useful that would be, though. Certainly for what Vega-Lite and the Editor use the schema for (namely validation and auto complete), we don't need it.

**Comment by jakevdp** [comment]
The other option would be some sort of post-processing step of the schema to remove any unused definitions. I just checked – there are a couple dozen of them (see below). It just seems like if you're treating the schema as a user-consumable product, this sort of extra noise should be removed.
```
>>> unused
{'AxisConfigMixins',
 'BaseBin',
 'BaseSelectionDef',
 'BaseSpec',
 'BoxPlotConfig',
 'BoxPlotConfigMixins',
 'CompositeMarkConfigMixins',
 'DataFormatBase',
 'DataFormatType',
 'FacetedCompositeUnitSpecAlias',
 'FacetedUnitSpec',
 'FieldDefBase',
 'Guide',
 'LayoutSizeMixins',
 'MarkConfigMixins',
 'MarkPropFieldDef',
 'ScaleFieldDef',
 'TextFieldDef',
 'TitleBase',
 'TopLevelProperties',
 'VLOnlyConfig',
 'VgAxisBase',
 'VgLegendBase',
 'VgLegendConfig',
 'VlOnlyGuideConfig'}
```

**Comment by domoritz** [comment]
Okay, let's do that in the schema generator: https://github.com/vega/ts-json-schema-generator/issues/18.
