### ISSUE TITLE
Composition example in gallery (NY/Seattle weather) not parsing dateTimes correctly

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3185]
The example of repeated column composition in the gallery using NY and Seattle weather is not parsing the date field correctly. Can be fixed by specifying the parsing format as below:

    "format": {
      "parse": {
        "date": "date:'%Y-%m-%d %H:%M'"
      }
    }

**Comment by domoritz** [comment]
What is parsed incorrectly? I checked the timestamps and they look reasonable and the output is the same for me with or without the format.

**Comment by jwoLondon** [comment]
Hmm, very odd. On MacOSX, if I view the example with Chrome, there is no problem. With Safari it requires the format spec before any data will appear.

**Comment by domoritz** [comment]
That's a bug in Safari's date parsing, I think.

**Comment by domoritz** [comment]
Sorry, didn't mean to close yet.

**Comment by domoritz** [comment]
Chrome:

```
new Date('2012-01-01T00:00')
Sun Jan 01 2012 00:00:00 GMT-0800 (PST)
```

Safari:

```
> new Date('2012-01-01T00:00')
< Sat Dec 31 2011 16:00:00 GMT-0800 (PST)
```

**Comment by domoritz** [comment]
This is a problem with the browser. Vega would need to replace its date parsing to fix this. 

@jheer, what are your thoughts on this? 

I remember having this problem in https://github.com/domoritz/himawari-8-chrome and ended up writing my own date parsing function.

**Comment by jheer** [comment]
Yes, `Date.parse` (which is used by default in lieu of a specific format) is **NOT** standardized across browsers. I don't think there is a spec / standard for it. (I know, I know... Ugh.)

As a result, I think it makes sense for canonical examples that do not use a "safe" date format to include a format parsing directive. Longer term, Vega could consider having it's own cross-browser stable parsing, but there's no clear sense of if/when that could happen.

**Comment by domoritz** [comment]
Since not even ISO 8601 is safe, we need to replace a bunch of dates in vega-datasets. I'm going to close this issue in favor of https://github.com/vega/vega-lite/issues/3185. 

I wonder whether it would be a good idea to show a warning if no date format is specified.
