### ISSUE TITLE
Re-consider rollup

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3190]
Vega uses rollup. We could consistently use rollup in all our projects. Would be great if somebody tried it and sent a pr :-)

**Comment by kanitw** [comment]
Well the upstack projects use webpack.

**Comment by nyurik** [comment]
I think there is a significant migration from webpack to rollup, but these things tend to be "flavor of the month"  a bit.  D3 uses rollup, and so did many other projects. My understanding is that rollup is geared more towards libraries, and webpack is more towards full site assembly.   https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c  -- mentions the same thing - rollup is better for libs.

**Comment by domoritz** [comment]
We actually use browserify right now. The advantage of rollup (as I understand it) is that it supports tree shaking because it expects es6 imports.

**Comment by domoritz** [comment]
Experiments at https://github.com/vega/vega-lite/tree/rollup
