### ISSUE TITLE
Specify Label Width for Facet

### ISSUE THREAD

**Issue by curran** [vega/vega-lite#3195]
This is perhaps an issue where it's configurable already, but I just cannot find the way to configure it.

The issue is, I'd like to allocate more space for the labels of cities here, so the city names don't get truncated:

![image](https://user-images.githubusercontent.com/68416/32604176-b52f4848-c572-11e7-8d57-12b075713716.png)

This is the spec I have:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 805,
  "height": 52,
  "data": {
      "url": "data.csv"
  },
  "mark": "area",
  "encoding": {
      "x": {
          "field": "timestamp",
          "type": "temporal",
          "axis": {
              "title": "Time",
              "grid": false
          }
      },
      "y": {
          "field": "temperature",
          "type": "quantitative",
          "axis": {
              "title": "Temp °C",
              "grid": false
          }
      },
      "color": {
          "field": "city",
          "type": "nominal",
          "legend": null
      },
      "row": {
          "field": "city",
          "type": "nominal",
          "header": {"title": "City"}
      }
  }
}
```

You can see it running here: https://datavis.tech/edit/5a391ee51b1043c5ac7c8cb1fd0249e7

I've looked in the following places in the documentation to see if the label spacing is configurable:

 * [Faceting a Plot into a Trellis Plot](https://vega.github.io/vega-lite/docs/facet.html)
 * [Example: Styling Labels](https://vega.github.io/vega-lite/docs/mark.html#example-styling-labels)

The closest thing I've found so far is [titleMaxLength for Axis](https://vega.github.io/vega-lite/docs/axis.html#title), but I don't think that's the thing to configure for these labels.

Fingers crossed this is something easy to do already :)

Thanks for the great ongoing work!

**Comment by kanitw** [comment]
Thanks for asking!

The underlying Vega may have an unintended text limit set -- please follow the issue that I have filed [here](https://github.com/vega/vega/issues/1074).  

In any case, I agree you should be able to adjust the underlying `labelLimit`, but we haven't implement it yet (as noted in https://github.com/vega/vega-lite/issues/2446). 

I'm gonna close this issue now as we have tracked both issues.  Note that I have listed some instruction in the first part https://github.com/vega/vega-lite/issues/2446 if you want to help contribute support for header label and title properties.
