### ISSUE TITLE
Some tables in https://vega.github.io/vega-lite/docs/encoding.html are empty

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3201]
Some renaming probably get outdated.

![image](https://user-images.githubusercontent.com/111269/32918421-3d4cdc72-cad7-11e7-850c-c1d67e23d64c.png)

![image](https://user-images.githubusercontent.com/111269/32918417-390b298e-cad7-11e7-9965-b79cee66ef19.png)

**Comment by domoritz** [comment]
Works for me on master

<img width="879" alt="screen shot 2017-11-17 at 18 13 57" src="https://user-images.githubusercontent.com/589034/32959815-1d544ddc-cbc3-11e7-8d0c-30b4e76ede48.png">

**Comment by kanitw** [comment]
It's empty on github. I think we better push the latest to the github page.

**Comment by domoritz** [comment]
Direct link https://vega.github.io/vega-lite/docs/encoding.html#mark-prop-field-def

**Comment by domoritz** [comment]
Hmm, looks like https://github.com/vega/vega-lite/blob/gh-pages/_data/vega-lite-schema.json is horribly outdated. Seems to be a bug in the deploy script.

**Comment by domoritz** [comment]
Same issue in #3202. I have a local fix but github doesn't let me push for some reason. Consider this fixed.

**Comment by kanitw** [comment]
Some in the specs are also problematic.  So let's re-open this issue.

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/commit/c6f3131ae13c109a727bb4a7b015c1fc7099e0c2#diff-99972a007a7e3a2daf66e3ca921e62c6 broke `TopLevel<FacetedUnitSpec>`.
