### ISSUE TITLE
Facet's Resolve is empty in the table

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3202]
![image](https://user-images.githubusercontent.com/111269/32918506-772853ae-cad7-11e7-8a69-fc2aac29f98b.png)

**Comment by domoritz** [comment]
Hmm. Works for me on master. Maybe we just need to redeploy the website. 

<img width="865" alt="screen shot 2017-11-17 at 18 12 53" src="https://user-images.githubusercontent.com/589034/32959758-f711f4e4-cbc2-11e7-826a-37f39411f07d.png">
