### ISSUE TITLE
Axis title truncated

### ISSUE THREAD

**Issue by asmyers** [vega/vega-lite#3207]
I've not been able to find a way to pad out the width of a narrow chart to accommodate a long title. 

Note here that the X axis title is truncated:

![vega-truncated](https://user-images.githubusercontent.com/122908/33137109-02f753a2-cf75-11e7-9eca-364c6d9bdf12.png)

My current workaround is rotating the title, which looks wonky:
![vega](https://user-images.githubusercontent.com/122908/33137111-04a534d0-cf75-11e7-82ec-9d5c75b84758.png)

Thanks for the great library!

**Comment by domoritz** [comment]
Could you [file this as a Vega issue](https://github.com/vega/vega/issues/new) with a small working example?

As a short term fix, you can rotate the chart.

**Comment by kanitw** [comment]
@asmyers  You can actually set the top-level `padding` like this:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "padding": {
    "top": 0,
    "bottom": 0,
    "left": 0,
    "right": 30
  },
  "data": {
    "values": [
      {"abcdefghijklmnop": "A","b": 28}, {"abcdefghijklmnop": "B","b": 55}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "abcdefghijklmnop", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/33142460-6b76abbc-cf6b-11e7-8d3d-f8b44a8f13a3.png)


But I agree that Vega's automatic padding should be a bit smarter about this.

**Comment by kanitw** [comment]
Note that I think `"top": 0,"bottom": 0,"left": 0` should not be required, but currently the underlying Vega requires it (https://github.com/vega/vega/issues/1077).
