### ISSUE TITLE
Design composite mark for error bars

### ISSUE THREAD

**Issue by alshain** [vega/vega-lite#3212]
Vega-lite should provide first-class support for error bars.

[Currently](https://vega.github.io/vega-lite/examples/layer_error_bars_dev.html), I can force vega-lite to aggregate data in some way, produce new fields, further process these fields to produce even more new fields, and use *these* new fields to draw a line, which just happens to represent an error bar. This is rather imperative and laborious.

Is there any plan to support error-bars natively, or "declaratively"?

Why not provide the ability to produce an error-measure when aggregating the data?

One idea:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/barley.json"},

  "transform": [
    {
      "aggregate": [
        {"op": "mean", "field": "yield", "as": "mean", "error": "stdev"}, // here
      ],
      "groupby": ["variety"]
    },
  ],
  "layer": [{
    "mark": {"type": "point", "filled": true},
    "encoding": {
      "x": {
        "field": "mean", "type": "quantitative",
        "scale": {"zero": false},
        "axis": {"title": "Barley Yield"}
      },
      "y": {
        "field": "variety", "type": "ordinal"
      },
      "color": {"value": "black"}
    }
  }]
}
```

This could automatically calculate the standard deviation and and display the corresponding error bar.

I don't know how this feature should interact and compose with the rest of the grammar, but I think it may be worth exploring this.

I have found a couple issues (#269 #1401) that mention error bars, but still, there seems to be no such feature except for visual markers that can be used to render error bars and the `x2` functionality which allows to draw a line that represents an errorbar.

**Comment by kanitw** [comment]
Good point.  Thanks for suggesting.

We have some plan for composite marks (basically, macro for composing multiple marks).
For example we have an experimental feature for box plot like in [this example](https://github.com/vega/vega-lite/blob/master/examples/specs/box-plot_tukey_2D_vertical.vl.json). 

We probably will provide a composite error-bar macro to make it slightly easier to produce error bar.  

Probably something like this:

```
{
  mark: {
    "type": "errorbar", 
    "center": "mean" | "median", 
    "extent": "stdev" | "stderr" | "ci",
    "ticks": true | false, // whether error bar contain end ticks -- not sure if ticks is the best name though
    "centerMark": "point" | "circle" | "square" | "bar" | "line"
}
```

That said, for now, like you describe, you can compose the layer manually.  Here is one example:
https://vega.github.io/vega-lite/examples/layer_error_bars_dev.html.

**Comment by kanitw** [comment]
We want to be able to write https://vega.github.io/vega-lite/examples/layer_error_bars_dev.html

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/barley.json"},
  "layer": [{
    "mark": {"type": "point", "filled": true},
    "encoding": {
      "x": {
        "aggregate": "mean", 
        "field": "yield", "type": "quantitative",
        "scale": {"zero": false},
        "axis": {"title": "Barley Yield"}
      },
      "y": {
        "field": "variety", "type": "ordinal"
      },
      "color": {"value": "black"}
    }
  }, {
    "mark": {"type": "errorbar", "center": "mean", "extent": "stdev"},
    "encoding": {
      "x": {
        "aggregate": "error-bar", // implicit (no need for user to specify)
        "field": "yield", "type": "quantitative"
      },
      "y": {
        "field": "variety", "type": "ordinal"
      }
    }
  }]
}
```

**Comment by kanitw** [comment]
@chanwutk  Besides `errorbar`, we should also consider `errorband` that share similar infrastructure. 

See https://vega.github.io/vega-lite/examples/layer_global_mean_dev.html and https://vega.github.io/vega-lite/examples/layer_area_ci.html and think if we can use similar marks

**Comment by kanitw** [comment]
I thought about it more -- instead of having "centerMarkType" -- we could just have "point", "line", "bar" options for users like we will have "point", "line", for line and area marks (See https://github.com/vega/vega-lite/pull/3604). 

```
{
  mark: {
    "type": "errorbar", 
    "center": "mean" | "median", 
    "extent": "stdev" | "stderr" | "ci",

    "point": true | false | MarkProperties,
    "line": true | false | MarkProperties,
    "bar": true | false | MarkProperties,

     // I'm debating whether we should use other properties of this object to customize the rule style or have another key / style name?
    "rule": true | false | MarkProperties, // for customizing style of the "rule"?

    "ticks": true | false, // whether error bar contain end ticks -- not sure if ticks is the best name though
}
```

**Comment by kanitw** [comment]
Not sure what we should call

- [ ] whisker
- [ ] extent
