### ISSUE TITLE
Docs bug: encoding.html#text-field-def & #text-value-def are broken

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3217]
Not sure where these two anchors should point to:
* https://vega.github.io/vega-lite/docs/encoding.html#text-field-def
* https://vega.github.io/vega-lite/docs/encoding.html#text-value-def
* encoding.html#value (ValueDef)

I found both on https://vega.github.io/vega-lite/docs/encoding.html but there might be others.

**Comment by kanitw** [comment]
Thanks for reporting!  https://github.com/vega/vega-lite/pull/3218 should fix this. ;)
