### ISSUE TITLE
Header titles/labels are not aigned correctly

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3225]
On master, the barley plot looks like

<img width="418" alt="screen shot 2017-12-06 at 15 35 26" src="https://user-images.githubusercontent.com/589034/33712948-8923ff90-db49-11e7-9c1f-1c1e8751c1de.png">

Although titles should be aligned

<img width="424" alt="screen shot 2017-12-06 at 15 35 17" src="https://user-images.githubusercontent.com/589034/33712992-acbffea4-db49-11e7-88e4-fcacfacfff69.png">

**Comment by domoritz** [comment]
The titles are aligned correctly if I set `"labelAngle": -90` on the row header.

**Comment by kanitw** [comment]
This seems like a critical bug but easy to fix -- can u help fix it -- ill be on a flight and will be busy until mid week next week

**Comment by domoritz** [comment]
Yeah, this is not good but I'm a bit swamped with Eurovis things right now. Maybe this weekend.

**Comment by kanitw** [comment]
Will be merged as a part of #3244
