### ISSUE TITLE
Vega lite release package is humongous

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3227]
The node_modules/vega-lite dir is 34.1 MB! For comparison, Vega is 2.1MB, and most other well known packages are a tiny fraction of that. Recently, github reduced the size of the release files, which means I can no longer publish release packages that contain the entire node_modules.   BTW, this also means that anyone using vega lite lib has to download the whole thing when installing it, even though most of the code is just a few hundred KB.  

![image](https://user-images.githubusercontent.com/1641515/33764664-66f79a5e-dbe3-11e7-8615-1eb6f8b2e253.png)

**Comment by domoritz** [comment]
I think a lot of it will be dev dependencies. What's the size when you exclude those?

**Comment by nyurik** [comment]
Dev dependencies are only 319KB, plus whichever modules shared by other modules - those would be in the root `node_modules/` dir.
![image](https://user-images.githubusercontent.com/1641515/33783295-353b2bce-dc2a-11e7-82de-b7e56cd02782.png)

**Comment by nyurik** [comment]
Correction: there are no dev dependencies here - only production dependencies.  My code lists `vega-lite` as a regular dependency, so when I do `npm install`, the `vega-lite` lib gets added to node_modules, with all of its production dependencies.
