### ISSUE TITLE
Copy disaster chart to examples

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3232]
https://bl.ocks.org/domoritz/8afa8f0ce5e03b43497e821f7a9cf216. It's a great demonstration of an ordinal bubble chart.

**Comment by kanitw** [comment]
You add to blocks in #3233, but if you want this to be core examples, why not adding it to examples folder?

**Comment by domoritz** [comment]
I thought this would be a great task for one of our ugrads to learn how to add data and specs.
