### ISSUE TITLE
"null" is missing from invalidValues attribute in vega-lite 2 scheme

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#3234]
In the vega-lite 2 [scheme ](https://vega.github.io/schema/vega-lite/v2.json)for `invalidValues` it is only mentioned that `"filter"` is accepted while in the [documentation](https://vega.github.io/vega-lite/docs/config.html#top-level-config) `"null"` is also a valid option (which also works in the editor as documented)

**Comment by kanitw** [comment]
Thanks for reporting.  This will be fixed in https://github.com/vega/vega-lite/pull/3240. :)
