### ISSUE TITLE
Problems with autosize when streaming data

### ISSUE THREAD

**Issue by alf** [vega/vega-lite#3235]
Hi, I'm having difficulties with getting the graphs shown correctly when loading data using the view.insert et.al. Methods as described in the [documentation](https://vega.github.io/vega-lite/docs/data.html#named) and in the [Streaming Tutorial](https://github.com/vega/vega-lite/blob/v2.0.3/site/tutorials/streaming.md).

My problems are mostly related to using faceting and other techniques where the result of inserting the data causes large changes in the size of the graph.

This also goes for legends, so by changing [L35](https://github.com/vega/vega-lite/blob/3a125cf4b4adcb3b03addcb0711f882c3196484d/site/static/streaming.ts#L35) of the streaming example and making the category name wider, for instance `Category {category}` results in the legend being clipped/truncated in that example.

I'm able to work around the issues by using a javascript object for the spec and shoving my data in as values instead of a named data source.

**Comment by domoritz** [comment]
Are you using `autosize.update: true` as in https://github.com/vega/vega-lite/blob/master/site/static/streaming.ts#L8?

**Comment by alf** [comment]
Yes. The only change to the streaming example needed to trigger the issue is to make the category name wider.

**Comment by domoritz** [comment]
This sounds like a Vega issue. Could you file it at https://github.com/vega/vega/issues/new? Thanks!
