### ISSUE TITLE
Opacity specified in mark definition block not respected

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3238]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "point", "opacity": 1},
  "encoding": {
    "x": {"field": "Horsepower","type": "quantitative"},
    "y": {"field": "Miles_per_Gallon","type": "quantitative"}
  }
}
```

The output Vega still has `"opacity": {"value": 0.7},`

**Comment by domoritz** [comment]
The problem is that we normalize specs to have an opacity enocding.

**Comment by domoritz** [comment]
Should `getMarkConfig` return only things from the config or also from the mark def? I feel this is a bit unclean right now. Maybe there are more bugs related to this so I'd prioritize this.

**Comment by kanitw** [comment]
If you think this is important, go ahead and fix it-- i dont have the bandwidth to fix it now

**Comment by domoritz** [comment]
Can you explain to me how getMarkConfig is supposed to work and how it's supposed to be used?

**Comment by kanitw** [comment]
`getMarkConfig` for reading config only and isn't the root cause of this problem.  
The existing code is already clean in this respect.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3252
