### ISSUE TITLE
"order" only working in Chrome

### ISSUE THREAD

**Issue by roy7** [vega/vega-lite#3243]
I had a situation where my data had 2 points out of order. I was unsure how to fix on my server side because of how our data is generated, so I figured I'd use "order" in the chart to re-order the line data points by the Y axis value. (The data points have the same X value, but looking closer I think my raw data is in the correct order after all already.) I saved out a static copy of the graph and data so you can see what I mean:

http://zero.sjeng.org/view/player/bug.html

The key area is in the upper right. I have two values with the same X and different Y. It was drawing them in an order where the line graph would dive down and back up instead of looking smooth. So I added this to my chart's encoding section for the line:

```Js
"order": { "field": "net", "type": "quantitative" }
```

  Which immediately made it look good in Chrome as I expected:

![In Chrome](http://puu.sh/yM1U3/c50256a7be.png)

  However MSIE, Firefox, Edge still show it badly with the order having no effect:

![In Firefox](http://puu.sh/yM1Vf/f8e563851f.png)

**Comment by gcp** [comment]
> MSIE, Firefox, Edge still show it badly

These originally showed it correct. The "order" field that was added for Chrome broke them.

**Comment by roy7** [comment]
Oh, here is a version without the order command:

http://zero.sjeng.org/view/player/bug2.html

Since I personally use Chrome I didn't realize it looked fine before. This reverses the issue. The raw data is ordered correctly, I believe:

http://zero.sjeng.org/view/player/elograph.json

So the issue is that in Chrome, two items with the same X value are drawing the line in an opposite sort order than the other major browsers. If I use "order" to force Chrome to sort the way I expect, it then reverses the sort over in all the other major browsers.

**Comment by kanitw** [comment]
Can you post a complete Vega-lite spec that produces the problem?   

I suspect that this is due to different behavior of javascript in different browser rather than a Vega-lite specific bug. (One might do stable sort, another might not.) There might be a way to fix this at the Vega level (by avoiding different JS behavior). 

In any case, since you sort by "net" and two points have the same "net" value, the right order between this two points is not defined.  You might want to specify more than one order field.  For example, if you want to sort the line by a, then by b.  you can do `"order": [{"field": "a", "type": "quantitative"},{"field": "b", "type": "quantitative"}]` like in the following example 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 10,"b": 28},
      {"a": 20,"b": 55},  
      {"a": 20,"b": 43},
      {"a": 30,"b": 91}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"field": "a", "type": "quantitative"},
    "y": {"field": "b", "type": "quantitative"},
    "order": [{"field": "a", "type": "quantitative"},{"field": "b", "type": "quantitative"}]
  }
}
```
You can also add `"order": [{"field": "a", "type": "quantitative"},{"field": "b", "type": "quantitative", "sort":"descending"}]` to flip the order.

**Comment by roy7** [comment]
I'm not sure what you mean by a complete Vega-lite spec, but the example bug html I saved out at http://zero.sjeng.org/view/player/bug.html still behaves as I showed in the screenshots. Chrome and Edge draw different results (opposite ordering in case of a tie).

It just seemed like different results in different browsers would be a bug in the library, but it sounds like the issue is that the tie behavior was just undefined and Chrome does it differently than all other browsers. In that case should we accept a tie is undefined and I'll close the issue?

To work around it I handled it on the data source end by adding a tiny amount to the data so there would never be ties and it'd enforce the ordering I was expecting.

**Comment by kanitw** [comment]
Sorry, i mean a Vega-Lite spec that we can copy and paste to the editor and see the problem.  But don't worry, I just make one from your `bug.html`.

> It just seemed like different results in different browsers would be a bug in the library, but it sounds like the issue is that the tie behavior was just undefined and Chrome does it differently than all other browsers. In that case should we accept a tie is undefined and I'll close the issue?

Although the tie behavior is undefined, I agree that we should make it consistent.  
I think this is more like an issue for underlying vega though so I'll close this issue.  Please follow a new issue that I filed (https://github.com/vega/vega/issues/1140) instead.  

> To work around it I handled it on the data source end by adding a tiny amount to the data so there would never be ties and it'd enforce the ordering I was expecting.

I recommend adding second sort field like suggest above than adding random epsilon to the data.  This way you can control how you want to tie-break the order.
