### ISSUE TITLE
Multiple charts in same html page

### ISSUE THREAD

**Issue by geminusbc** [vega/vega-lite#3247]
Hello I am currently looking for a way to insert multiple charts into the same HTML 5 page.
I am only having some basic understanding of HTML.
Thank you

**Comment by domoritz** [comment]
You can totally do that with Vega-Lite. Check out https://github.com/vega/vega-lite/blob/master/test-gallery/index.html.

**Comment by kanitw** [comment]
To answer your questions, you can run the code in https://vega.github.io/vega-lite/usage/embed.html multiple times, just with different containers (e.g., multiple `<div>`s with different `id`s).
