### ISSUE TITLE
Axis Title Component should store field def 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3249]
So that we can merge "min of x" and "max of x" into just "x" instead of "min of x, max of x".

(Follow up conversation in https://github.com/vega/vega-lite/pull/3245)

**Comment by domoritz** [comment]
Do you want "min of x, max of x" -> "extent of x"?

**Comment by kanitw** [comment]
No thats too much -- there are cases like ci0 and ci1 too

**Comment by domoritz** [comment]
So you just want to remove the aggregation?

**Comment by kanitw** [comment]
Yes, only when we merge multiple aggregate ops

**Comment by g3o2** [comment]
wouldn't it then be better to make it sth like `aggregated x` to show that it is not simply the original x but the aggregated variety ?

**Comment by kanitw** [comment]
Thats non standard and isn't very helpful anyway

**Comment by domoritz** [comment]
or "min, max of x" instead of "min of x, max of x"

**Comment by kanitw** [comment]
https://vega.github.io/vega-lite/examples/layer_falkensee.html

![image](https://user-images.githubusercontent.com/111269/35303314-5ef0d190-0046-11e8-836f-3247727a2343.png)

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3527
