### ISSUE TITLE
Not able to create an autosize object in config

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3250]
Perhaps I'm missing something, but if I try to create an `autosize` object in `config`, Vega-Lite reports the fatal error `TypeError: Attempted to assign to readonly property.`. The documentation implies that `config` can use `autosize` with an object parameter. This becomes a problem when wishing to set some of the other autosize parameters that require an object (`resize` and `contains`)

This is valid:

    "config": {"autosize":"fit"}

But this generates the error:

    "config": {"autosize": {"type":"fit"}}

Setting the same as a top level property rather than via `config` works fine:

    "autosize":{"type":"fit"}

**Comment by kanitw** [comment]
Looks like this is a Vega issue, I am re-creating a new issue at https://github.com/vega/vega/issues/1103.
