### ISSUE TITLE
Data parsing does not support nested fields

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3251]
As described in https://github.com/vega/vega-parser/issues/64#issuecomment-355054535 - if the source data has nested fields, e.g.
```
data: {
 xxx: [
  { a: { b: '2018-01-01T00:15:07.5235123+00:00' }},
  { a: { b: '2018-01-02T00:15:07.5235123+00:00' }},
  { a: { b: '2018-01-03T00:15:07.5235123+00:00' }}
] }
```

The data is not parsed with this format:

```
      "format": {
        "property": "xxx",
        "type":"json",
        "parse": { "a.b": "date" }
```

**Comment by domoritz** [comment]
What's the Vega-Lite issue here?

**Comment by nyurik** [comment]
@domoritz are you saying it should be handled by Vega itself? CC: @jheer

**Comment by kanitw** [comment]
I believe that is the case, but let's wait to see @domoritz's answer

**Comment by nyurik** [comment]
@kanitw I think VL uses a different field semantics than Vega. For example, a field "a.b" gets converted by VL to "a['b']" in Vega.  I wonder if similar conversion is also needed here.

**Comment by domoritz** [comment]
I think Vega should handle this correctly. We want `a.b == `a['b']` in Vega and Vega-Lite, right?

**Comment by nyurik** [comment]
I suspect Vega doesn't support either at this point. As for VL, the `a.b` plus escaping is the method used everywhere else in VL, so it should probably stay that way for consistency.
