### ISSUE TITLE
vega(-lite) online editor offline

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#3257]
I tried to access https://vega.github.io/editor/#/custom/vega-lite, but it doesn't initiate.

On Chrome I cannot get an error log, but on IE it shows the following:
![capture2](https://user-images.githubusercontent.com/5186265/34674483-60887948-f486-11e7-8246-8b77ee9c0e4e.PNG)

**Comment by mattijn** [comment]
works again

**Comment by domoritz** [comment]
Interesting. Could this have been an issue with the Github CDN or a filter rule in your adblocker?
