### ISSUE TITLE
Oblique rule mark

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3263]
Currently a bounded `rule` mark can be either horizontal (if `x` and `x2` are defined) or vertical (if `y` and `y2` are defined).

Would it be possible to allow both x and y bounds to be defined for the same rule so rules can be oblique? (And as an aside, the current wording in the documentation ["a rule can be used to draw a line segment between two positions"](https://vega.github.io/vega-lite/docs/rule.html) does not make it clear that those positions have to share either a horizontal or vertical coordinate).

This would allow parallel coordinates plots (PCPs) to be easily built such as in the following:

    {
      "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
      "width":100,
      "data": { "url": "data/cars.json"},
      "mark": "rule",
      "encoding": {
        "x": { "value": 0},
        "y": {"field": "Horsepower","type": "quantitative"},
        "x2": { "value": 100},
        "y2": {"field": "Weight_in_lbs","type": "quantitative"}
      }
    }

While PCPs can be partially simulated using the `line` mark and `detail`, this only works if all variables in the PCP share a common scale. This means that PCPs that mix measurement types and ranges have to be rescaled with a data transform rather than relying on Vega-Lite's built-in scaling of any measurement type.

**Comment by kanitw** [comment]
Thanks for reporting.  We actually intended to support using rules for line segment so this is obviously a bug.  Will submit a fix for this soon.  

> This means that PCPs that mix measurement types and ranges have to be rescaled with a data transform rather than relying on Vega-Lite's built-in scaling of any measurement type.

Yes, otherwise we are violating an assumption that one axis (x or y) can have only one scale per plot, which would requires us to re-design a lot of things.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3265

**Comment by jwoLondon** [comment]
Thanks for a quick and helpful response. I thought I had seen a VL chart with dual vertical axes (left and right), but I think it must have been a composite layered chart.

I guess one could simulate a PCP with two differently scaled vertical axes by always scaling between min and max on a quant scale but hiding the axes and then having two 'annotation axis layers' with the units of the unscaled axes displayed.

**Comment by kanitw** [comment]
> Thanks for a quick and helpful response. I thought I had seen a VL chart with dual vertical axes (left and right), but I think it must have been a composite layered chart.

Yep, you're right. :) 

> I guess one could simulate a PCP with two differently scaled vertical axes by always scaling between min and max on a quant scale but hiding the axes and then having two 'annotation axis layers' with the units of the unscaled axes displayed.

Yeah, that's probably the best way for now.

**Comment by jwoLondon** [comment]
Just tried creating a PCP for the [Iris dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set) using `line` and `detail` for now (pending release of the fixed `rule`). Normalising the scale to [0,1] and an axis annotation layer seems to work well:

<img width="455" alt="pcptest" src="https://user-images.githubusercontent.com/1846999/34922544-5c3c768e-f989-11e7-8f4e-45e3cd0ae799.png">

**Comment by kanitw** [comment]
This is pretty nice.  Do you have a spec that can be shared?  

(Btw, you might want to hide y-axis?)

**Comment by jwoLondon** [comment]
In the context of this discussion I kept the y-axis visible to demonstrate the scaling to [0,1], but yes, in a real PCP it would be sensible to hide that axis.

I've created [a commentary](http://www.staff.city.ac.uk/~jwo/datavis/vega-lite/pcp/index.html) (as part of a larger project) that explains how I used [elm-vega](http://package.elm-lang.org/packages/gicentre/elm-vega/latest) to create PCPs. If you skip to the bottom of that page, you can see the vega-lite spec in the final example. Feel free to use and amend it as you see fit.

Most of the work is in manipulating the data to be amenable to PCPs rather than in the Vega-Lite spec, so this is not an ideal example for anyone using only JSON, but it may help nonetheless.
