### ISSUE TITLE
Support all Vega transforms

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3267]
Via a special syntax and we won't optimize it but we allow it for expressivity.

**Comment by domoritz** [comment]
Related: https://github.com/vega/vega-lite/issues/3264

**Comment by kanitw** [comment]
I think #3264 is a better alternative to do for now -- especially since some of Vega transforms interact with signals, which is a lower level concept that do not existing in Vega-Lite.

**Comment by domoritz** [comment]
I was thinking that this would be a feature for experts just to give them the flexibility. I'd be okay with not even documenting it properly.

**Comment by g3o2** [comment]
Wouldn't and shouldn't experts edit the compiled vega spec instead ? :-)

**Comment by domoritz** [comment]
You're always welcome to do that but it is pretty tricky to get the transforms right. But yes, the beauty of the stack of tools is that you can interact with it at any point.
