### ISSUE TITLE
"Data store" for using named datasets

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3268]
This is useful for jupter lab. The idea is that one would use named data sources + a storage in a spec. VL will automatically inline any source that exists in the storage.

**Comment by kanitw** [comment]
If we gonna have a data store, it's probably worth having a top level "constants" (can be implemented using signal) for referring throughout the specs too.  This would be incredibly useful for annotations.

**Comment by randre69** [comment]
@domoritz Thanks for doing this!  I'm trying to grok how to use the new dict from the tests, but am not *quite* getting it. Do you have a small Vega or Vega-Lite json snippet that shows how this works with a named data set?

**Comment by domoritz** [comment]
@randre69 check out the example inhttps://github.com/vega/vega-lite/pull/3417

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/pull/3417#issuecomment-370681624 -- we should still consider if we want to support URL

**Comment by domoritz** [comment]
I don't see why. You can just put the URL in place of the name...

**Comment by kanitw** [comment]
I guess it makes more sense when you have a URL that you want to further transform and reuse that transformed dataset for different subplots.

**Comment by domoritz** [comment]
The datastore doesn't let you transform data, though.

**Comment by kanitw** [comment]
> doesn't 

The first version with array doesn't,  doesn't mean that url object shouldn't support it?  

That said, I think what you had in the merged PR is good enough the first release.  If we hear more feedback, we can consider this option more later.

**Comment by domoritz** [comment]
Can we close this issue until then?

**Comment by kanitw** [comment]
I don't have strong opinion.  I'll let @ellisonbg voices his opinion about this.
