### ISSUE TITLE
header/footer/titleBand for Composition Layout

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3270]
Good examples to add:
- [ ] Ridgeline plot https://github.com/vega/vega-lite/issues/3036

**Comment by kanitw** [comment]
Should we call it `layout`?   --- but if `layout` is used for this, what would layout-transform (#1872) be called should we add them in the future?

**Comment by domoritz** [comment]
Why not have it at the top level in the composition operator?

**Comment by kanitw** [comment]
Yes.  It should definitely be at the top-level.  The quesiton is how we call it.  `layout` maybe?

**Comment by kanitw** [comment]
Given that `facet`, `concat`, `repeat` are layout operator already, having a nested `layout` property probably doesn't make sense.  Doing so also introduce more complex specs and config (Properties will be `config.facet/concat/repeat.layout.XXX` rather than `config.facet/concat/repeat.XXX`.

So I'd propose that we add these layout properties to the top-level spec.  The question are (1) which one do we want to support and (2) how do we name them. 

1) `padding` is probably the most important.  However, we already have `padding` as a top-level property for the whole canvas's padding.  Thus we would need a different name for this padding of the inner/sub view.    Given that CSS grid uses `gap` for this and it's a better name anyway, let's call this gap.

```
{
   "facet": {"row": ...},
   "spec": {...},
   "gap": 5 // or {row: 5, column: 4}
}
```

2) `align`, `bounds`, and `center` are probably useful for advanced use case.

3) `offset`, `headerBand`, `footerBand`, `titleBand` are currently only useful for facet as repeat/concat do not have headers yet.   I think once we allow shared axis for concat and repeat, `offset` may be useful for concat/repeat too, but I'm not sure about  `headerBand`, `footerBand`, `titleBand`. 

4)  `headerBand`, `footerBand`, `titleBand` are also currently only useful for facet as repeat/concat do not have headers yet.  However, I'm not sure if  `headerBand`, `footerBand`, `titleBand` would be useful when we allow shared axis for concat and repeat.  So if that's the case, we might want to add this property to be a part of 

5) `columns`  should be supported once we supported wrapped facet/repeat so it's not a part of this issue.

**Comment by kanitw** [comment]
Since the padding/gap is the only critical one, let's plan to add that one first.

**Comment by domoritz** [comment]
Facet wrap is in https://github.com/vega/vega-lite/issues/393

**Comment by kanitw** [comment]
From my experiment, we don't need `header/footer/titleBand` in Vega-Lite as they only creates bad settings.
