### ISSUE TITLE
Horizontal header label overlaps axis labels

### ISSUE THREAD

**Issue by danmarshall** [vega/vega-lite#3272]
Hi Vegans, I'm creating issues because I really like what you are doing 😀 this is a great project!

Maybe there is a better spec than this to accomplish horizontal text, but anyways:
```
{
    "data": {"values": [
      {"a": "1492", "b": 8, "c": "Xanadu"},
      {"a": "1812", "b": 28, "c": "Xanadu"},
      {"a": "1900", "b": 48, "c": "Xanadu"},
      {"a": "1492", "b": 55, "c": "Zootopia"},
      {"a": "1812", "b": 45, "c": "Zootopia"}, 
      {"a": "1900", "b": 35, "c": "Zootopia"}
    ]},
    "mark": "bar",
    "encoding": {
        "x": {
            "field": "b", "type": "quantitative"
        },
        "y": {
            "field": "a", "type": "nominal", "axis": { "title": null }
        },
        "row": {
            "field": "c", "type": "nominal",
            "header": {
              "title": null,
              "labelAngle": 360
            }
        }
    }
}
```
Currently this renders:
![image](https://user-images.githubusercontent.com/11507384/35025167-9ff0a0ec-faf8-11e7-921f-abcc47147729.png)

Also note the `360` which is filed in #3271

**Comment by kanitw** [comment]
Thanks for reporting. The header should have a (missing) rule to automatically determine text alignment and baseline.
