### ISSUE TITLE
Automatically enable pointer cursor when href channel is present

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3274]
We should implement this smart default.

**Comment by domoritz** [comment]
The idea of this issue is that we should set `cursor: 'pointer'` when the [href channel](https://vega.github.io/vega-lite/docs/encoding.html#href) is being used for a mark.

**Comment by Asutosh989** [comment]
Hi @domoritz I am interested to take up this issue?

**Comment by domoritz** [comment]
Excellent. We'll discuss details on slack.

**Comment by kanitw** [comment]
Please make sure to
1)  consider [`baseEncodeEntry`](https://github.com/vega/vega-lite/blob/master/src/compile/mark/mixins.ts#L37) 
2) make sure that users can still specify `cursor` in the mark definition to override this automatic default.

**Comment by domoritz** [comment]
Fixed in #3876

**Comment by domoritz** [comment]
@kanitw How should we consider baseEncodeEntry? We implemented this in normalizeMarkDef and it seems like a good place to do so.
