### ISSUE TITLE
Facet headers do not sort

### ISSUE THREAD

**Issue by danmarshall** [vega/vega-lite#3278]
When adding `sort` to a facet like `row` or `column`, the charts are sorted but the headers are not:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"maxbins": 15},
      "field": "Horsepower",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    },
    "row": {"field": "Origin", "type": "nominal", "sort": "ascending"}
  }
}
```
Change `sort` to `descending`:
![image](https://user-images.githubusercontent.com/11507384/35167502-ad28020a-fd0a-11e7-9807-d32d576253ba.png)

**Comment by kanitw** [comment]
Thanks for reporting. We will try to look into this as soon as possible.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3279
