### ISSUE TITLE
Parse is added after transform

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3282]
The parsing should be done before the aggregate transform. Note that this is not true in general for all parses. The parse of `max_price` should happen after the aggregation. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 600,
  "height": 300,
  "data": {
    "url": "data/stocks.csv",
    "format": {"parse": {"price": "number"}}
  },
  "transform": [{
    "aggregate": [{"op": "max", "field": "price", "as": "max_price"}],
    "groupby": ["date"]
  }],
  "mark": "point",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
    "y": {"field": "max_price", "type": "quantitative"}
  }
}
```

**Comment by amitkaps** [comment]
@dmoritz Is the default infer type for an array of integer and null values  always string? Should it not be integer.... Maybe this is an issue for vega.infertype but just asking what the default here in vega-lite is?

**Comment by amitkaps** [comment]
@dmoritz Is the default infer type for an array of integer and null values  always string? Should it not be integer.... Maybe this is an issue for vega.infertype but just asking what the default here in vega-lite is?

**Comment by amitkaps** [comment]
@dmoritz Is the default infer type for an array of integer and null values  always string? Should it not be integer.... Maybe this is an issue for vega.infertype but just asking what the default here in vega-lite is?

**Comment by amitkaps** [comment]
@dmoritz Is the default infer type for an array of integer and null values  always string? Should it not be integer.... Maybe this is an issue for vega.infertype but just asking what the default here in vega-lite is?

**Comment by domoritz** [comment]
Vega-Lite generates Vega and thus uses the default behavior of Vega. Vega does not parse fields by default and thus treats them as strings. You can pass `auto` to `format.parse`to infer a type. Note that we do automatically add a correct parse instruction when we can know the type from the context of the spec. For example, `quantitative` fields get parsed as numbers. The tricky thing in the example above is that we only infer that `max_price` is a number but not `price`. For the specific example above, we should be able to infer that `price` is a number but for general expressions, we can no do that.

**Comment by kanitw** [comment]
@domoritz – I think we can make a good guess that price is a number, but `max` can in fact be 
 used with a temporal value too.  (That said, I think Q is a sensible default.)

**Comment by domoritz** [comment]
Max makes sense with strings as well. The way we would infer in the example above is that we know that `max_price` has to be a number and `max` preserves the type. However, this kind of backward type inference is not very common so I don't think this is high priority for me.
