### ISSUE TITLE
Improve time unit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3290]
- [ ] automatically replace day with date for timeunit with multiple time parts (e.g, "yearmonthday" with "yearmonthdate") to avoid user error.

- [ ] Support more concise way to specify timeUnit (`yearmonthdatehoursminutesseconds` is crazy)

- [ ] what if users want to bin time field by every other week

**Comment by ijlyttle** [comment]
Just an observation, but it seems like you are asking TimeUnit to do two separate things:

1. Specify how time is to be discretized
2. Specify how the resulting labels are to formatted

I think trying to do both things in one parameter leads to the craziness of `yearmonthdatehoursminutesseconds`.

As well, having a parameter that focuses only on the discretization might make it easier to do things like bin every other week.

**Comment by kanitw** [comment]
To be clear, timeUnit is designed to focus on 1. It's just that 1. would affect the default label format (2.).  To do only 2, you can use axis/label's `format` property. 

But yeah, I agree that `yearmonthdatehoursminutesseconds` is crazy though and right now time unit is not flexible enough to do things like bin every other week.

**Comment by ijlyttle** [comment]
Understood - I should have noted that time unit offers a default for the format, and that it can be changed in `format`. 

Just to make sure that I understand correctly: in terms of discretization only, is `yearmonthdatehoursminutesseconds` equivalent to `seconds`?

**Comment by kanitw** [comment]
> Just to make sure that I understand correctly: in terms of discretization only, is yearmonthdatehoursminutesseconds equivalent to seconds?

Nope. `seconds` is like mod by seconds.  (Just like `month` collapse all January of every single year into the same bucket)

`yearmonthdatehoursminutesseconds` is basically rounding the to the seconds (ignoring information about sub/milliseconds).

**Comment by ijlyttle** [comment]
🤦‍♂️ 

Thanks, that makes much more sense to me now, and completely invalidates the premise of my original post. Sorry.

**Comment by kanitw** [comment]
No problem, perhaps there is a room to improve the documentation to avoid confusion.  

Feel free to submit a PR to help.  :)

**Comment by ijlyttle** [comment]
Hi @kanitw, just a short note to let you know I despite my lack of a PR, I have been spending a lot of time (pardon the expression) wrapping my head around the topic. For me, there are three separate issues that end up getting mixed-together in my head:

1. Documenting the current behavior of time unit.
2. Imagining a more-expressive system (capture 2-week periods, to quote your example). I have some ideas here, but finding that balance between expressiveness, conciseness, while maintaining backwards compatibility seems very challenging. Although I might have some suggestions on the API side, I'm afraid I have an incomplete understanding of how practical they may be to implement.
3. Keeping timezone issues straight in my head ([this Altair page](https://altair-viz.github.io/user_guide/times_and_dates.html) is super helpful). 

I don't know that this requires any specific action; this is just to let you know I had not forgotten.

**Comment by ijlyttle** [comment]
Here's a first step: https://beta.observablehq.com/@ijlyttle/vega-lite-timeunit

I suspect that you will want a "proper" PR into the standard documentation, but I thought this might help me get some ideas worked out.

I know it's a bit verbose, but, to me, there are are a lot of things happening implicitly when you use a timeUnit with aggregation.

Happy for your feedback while I wrap my head around the ins-and-outs of the "real" documentation.

**Comment by davidanthoff** [comment]
We just came across a situation where someone wanted to bin by half hours, which might be another kind of use-case that it would be nice to support.

**Comment by djahandarie** [comment]
Can definitely echo @davidanthoff's request. I find myself wanting to bin by 5,10,30 minute intervals fairly often.

**Comment by danyelf** [comment]
I'm echoing the requests above.

To recast this conversation slightly, I think we're doing several things at once here.

- It's common with time units to see them in cycles. For example, it's interesting to see month-over-month across multiple years, without caring which year it is.
- Time has some well-defined binning functions.

The current string-based system is based on (essentially) choosing binary flags for each field as "keep" or "set to default" For example, "monthdate" means "set year to 1900, keep month, keep date, set hour & minute & second to 0". Then there's an extra boolean flag for "convert to UTC time"

You might imagine making this a set of boolean flags instead: (0,1,1,0,0,0).

But now we're getting feature requests -- and I have the same one! -- for binning by 15 and 30 minute (or second, or whatever) segments. I'm also _fairly_ sure that:
- The 'true' fields must be sequential (I don't think you want to support yearsecond)
- Only the last field is really variable (I don't think you want to support "group by 2 minutes, and also 30 seconds")

So this begins to sound to me like either a single parameter -- "hourminute,2" -- or a structured form, "0,0,0,1,2".

**Comment by domoritz** [comment]
Thanks for the write-up! I agree with a lot of your points but there are some details I wanted to add. 

First, the fields don't have to be sequential. For example, not year-month and year-quarter make sense. 

Second, at the end of the day time unit is just a function we apply and some default time formats. I'd be curious to see how difficult it is to create 15minute bins with Vega-Lite right now and what we can learn from it for the design of time unit in the future.

**Comment by danyelf** [comment]
That's a really good point that time units are a DAG, not a sequence. (Week of year is smaller than year, and neither bigger nor smaller than quarter or month.)

**Comment by drorata** [comment]
Maybe related #2062

**Comment by kanitw** [comment]
Now that Vega has introduced time unit transform with features like step. It's now feasible to support this in Vega-Lite.  https://vega.github.io/vega/docs/transforms/timeunit/

**Comment by kanitw** [comment]
@domoritz and I discussed and it would make sense to support timeUnit definition object (in addition to existing enum strings) so we can support `step`, `extent`, `maxbins`.

**Comment by kanitw** [comment]
Time unit will be improved immensely in https://github.com/vega/vega-lite/pull/5578.

If anyone has any specific request, please file an issue.
