### ISSUE TITLE
Support line segments with line marks

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#3299]
Currently, you must you a rule mark to achieve the effect of a line segment (encoding `x`, `y`, `x2`, and `y2` seperately. As a user, I would find it confusing to use `rule` to achieve this. I propose we make line capable of both encoding data by specifying only `x` and `y` (as it is now) or by specify all four (a segment, if you will)

**Comment by kanitw** [comment]
The cleanest approach would be writing a method to overwrite line with rule during the normalize phase and throw warning to say that they should use rule for this purpose.  This way, the internal logic between continuous line and line segments can remain the same

**Comment by kanitw** [comment]
@willium  Feel free to submit a PR.
