### ISSUE TITLE
Support valid value for order indicating not to order input data

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#3300]
Sometimes a user may not want a line to default order their data. This might be a rare occurrence, but when it happens there's no easy way to vega to respect the indexed order of the data. I propose a
```"order": "index"```
or similar, alongside "ascending" and "descending"

**Comment by domoritz** [comment]
This should be covered by `order: null`. Do you have an example where this does not work?

**Comment by kanitw** [comment]
Duplicate of https://github.com/vega/vega-lite/issues/1020
