### ISSUE TITLE
Poor mobile performance for example gallery page

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#3303]
When viewing https://vega.github.io/vega-lite/examples/ using Safari on an iPhone 6, I experience poor performance, with loading delays, temporarily empty space, chunky scrolling, etc. I believe this is due to the SVG rendering cost, particularly for the very detailed SVGs included in the new geographic examples.

Perhaps we should switch to using PNG output images instead (double-sized for retina display), akin to the Vega gallery?

**Comment by domoritz** [comment]
Yes, the zip code example is about 7mb of SVG. The issue with switching to PNG is that we resize images in the gallery. A small chart will be scaled up, while a large image is scaled down. I can't think of a clean way to generate all images at the same size.

**Comment by domoritz** [comment]
I just deployed some code to selectively use PNGs for large examples.
