### ISSUE TITLE
`data: null` to ignore data from parent + better annotation support

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3316]
Suppose users want to add an annotation layer with just one mark, we need a way to tell that we don't want to derive data from its parent.

**Comment by domoritz** [comment]
We only need this after we have designed how annotations work. For anything that we do in VL right now, this is not an issue at all.

**Comment by kanitw** [comment]
> We only need this after we have designed how annotations work. For anything that we do in VL right now, this is not an issue at all.

Well, if you want to add annotation with existing construct, this is needed.  
Even if we have macro for annotations, we still have to normalize them to standard VL primitives.

**Comment by kanitw** [comment]
Currently we can use `layer` for annotation.  

However, to make the annotation have a single data point, we always have to input `"data": {"values": [{}]}`, which is highly confusing.
