### ISSUE TITLE
Scatter plot matrix: diagonal facets have static horizontal axis

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3321]
In the [scatter plot matrix](https://vega.github.io/editor/#/examples/vega-lite/interactive_splom) example, diagonal facets can be zoomed and panned on the vertical scale, but not on the horizontal scale. From the spec, I would have assumed that both horizontal and vertical scales would allow interaction.

**Comment by domoritz** [comment]
![zoom](https://user-images.githubusercontent.com/589034/35697528-55ac1a86-073f-11e8-808c-7754682f8c88.gif)
