### ISSUE TITLE
Drawing lines with two quantitative fields throws a warning

### ISSUE THREAD

**Issue by starry97** [vega/vega-lite#3326]
The spec below throws a warning:
![image](https://user-images.githubusercontent.com/19985016/35586873-e236f768-05b0-11e8-8ed3-c6acfd6364a5.png)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 10,"b": 28}, 
      {"a": 20,"b": 55}
    ]
  },
   "mark": "line",
   "encoding": {
     "x":{"field": "a", "type": "quantitative"},
     "y": {"field": "b", "type": "quantitative"},
     "color": {"value": "black"}
   }
}
```

**Comment by kanitw** [comment]
Thinking more about it, the warning makes sense. Given that Vega-Lite doesn't read data, it's impossible to know that there are only two data points. 

In cases there are more than two points:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 10,"b": 28}, 
      {"a": 20,"b": 55},
      {"a": 30,"b": 45}
    ]
  },
   "mark": "line",
   "encoding": {
     "x":{"field": "a", "type": "quantitative"},
     "y": {"field": "b", "type": "quantitative"},
     "color": {"value": "black"}
   }
}
```

This is vertical:

![image](https://user-images.githubusercontent.com/111269/35587100-a251df18-05b1-11e8-8c92-f89a1d670062.png)

This is horizontal:

![image](https://user-images.githubusercontent.com/111269/35587130-b4f659be-05b1-11e8-8fd5-6b87347b1087.png)
