### ISSUE TITLE
offset as mark definition properties

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3328]
Forked from https://github.com/vega/vega-lite/issues/396, we discussed earlier today that it might make more sense to provide support for `offsetX`, `offsetY`, `offsetX2`, and `offsetY2` in [mark definition](https://vega.github.io/vega-lite/docs/mark.html#mark-def) first.

- [x] Add these properties (`offsetX`, `offsetY`, `offsetX2`, and `offsetY2`) to `MarkDef`

- [x] Use them in related position mixins in https://github.com/vega/vega-lite/blob/master/src/compile/mark/mixins.ts –– there are many mixins methods with Position in the name.  Make sure the offset are correctly included in all the cases.  (Modifying some of the help refs method in https://github.com/vega/vega-lite/blob/master/src/compile/mark/valueref.ts may actually make it work for all cases. 

- [x] Write test for different scales on x,y (linear, bin-linear, band, point, time, etc.)

**Comment by kanitw** [comment]
For a bit more context,  see how these mixins are getting called by different mark compilers in https://github.com/vega/vega-lite/tree/master/src/compile/mark. :)

**Comment by kanitw** [comment]
@domoritz @starry97  -- I wonder if calling them   `xOffset`, `x2Offset`, `yOffset` are actually better (sounds more like proper english) than offsetX, ...

**Comment by domoritz** [comment]
I think the most important question is how we want things to be grouped

`x, xOffset, y, YOffset` or `x, y, offsetX, offsetY`

**Comment by kanitw** [comment]
Yep, I actually prefer:

> x, xOffset, y, yOffset

**Comment by kanitw** [comment]
(That's my original motivation to think about this before I start thinking about English)

**Comment by kanitw** [comment]
Already included in https://github.com/vega/vega-lite/pull/3378
