### ISSUE TITLE
Allow filtering of data for views

### ISSUE THREAD

**Issue by LukasGrebe** [vega/vega-lite#3331]
I'm trying to create a compositional graphics where some views do not include all data.

for example https://vega.github.io/editor/#/examples/vega-lite/point_color_with_shape hconcatted with the same chart filtered on cars out of Japan.

Effectively i'd like to create a transform filter for a single view, however a filter can only be applied in the top-level transform, not within an encoding or view spec.

**Comment by kanitw** [comment]
Filter can work for a sub-view. See https://vega.github.io/vega-lite/examples/interactive_layered_crossfilter.html for example. 

If you have any suggesting to improve the documentation to make this clearer, feel free to submit a PR.

**Comment by LukasGrebe** [comment]
sweet, thanks!
i've submitted a pull request:  #3332
