### ISSUE TITLE
Vega & Vega-Lite site should use same order of tabs

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3333]
Its a bit confusing to have a different order of top tabs for Vega and for Vega-Lite:

* https://vega.github.io/vega/
* https://vega.github.io/vega-lite/

Also, ideally, switching between Vega & Vega-Lite should stay in the same area. For example, if I'm in documentation, switching should stay in documentation.

**Comment by domoritz** [comment]
I agree! Which order do you think makes more sense? Do you want to send a pr to make them consistent? 

I'm not sure how we can make sure that URLs stay in the same area except for writing special cases.

**Comment by nyurik** [comment]
I'm not sure about the doc/link generation process - if they are done as part of the main template, or if you could have a javascript there with a predefined set of mappings?

**Comment by domoritz** [comment]
We generate our pages with Jekyll and it would be nice to implement it in the template language. We could define a mapping.

**Comment by domoritz** [comment]
I'm happy to adopt the order from Vega with Application instead of About. Okay @kanitw?
