### ISSUE TITLE
A bug when accessing nested field after aggregated argmin/argmax

### ISSUE THREAD

**Issue by chanwutk** [vega/vega-lite#3361]
This bug happens when aggregate `argmin`/`argmax` and trying to use the field in one of the axis and type is set to `quantitative`.

This is the vega-lite that works, when type is `ordinal`.
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "A","b": 28}, 
      {"a": "B","b": 55}
    ]
  },
  "mark": "point",
  "transform": [
    {
      "aggregate": [
        {
          "field": "b",
          "op": "argmax",
          "as": "arg"
        }
      ],
      "groupby": []
    }
  ],
  "encoding": {
    "x": {"field": "arg.a", "type": "nominal"},
    "y": {"field": "arg.b", "type": "ordinal"}
  }
}
```
<img width="1280" alt="screen shot 2018-02-06 at 02 48 47" src="https://user-images.githubusercontent.com/30903997/35855807-11b2e8ca-0ae9-11e8-87c4-9ce227b8df88.png">

This is the vega-lite that has a bug, when type is `quantitative`. When the vega-lite is compiled to vega, it tries to create a new field with name "arg.b" from field `arg.b`, which does not exist at the time because when it creates the new field, it is before `argmax` is aggregated. Then, it has an error as seen in the next image.
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "A","b": 28}, 
      {"a": "B","b": 55}
    ]
  },
  "mark": "point",
  "transform": [
    {
      "aggregate": [
        {
          "field": "b",
          "op": "argmax",
          "as": "arg"
        }
      ],
      "groupby": []
    }
  ],
  "encoding": {
    "x": {"field": "arg.a", "type": "nominal"},
    "y": {"field": "arg.b", "type": "quantitative"}
  }
}
```
<img width="1280" alt="screen shot 2018-02-06 at 02 48 24" src="https://user-images.githubusercontent.com/30903997/35855856-3425b8f6-0ae9-11e8-9ddb-72f42db31eba.png">
<img width="1280" alt="screen shot 2018-02-06 at 03 02 52" src="https://user-images.githubusercontent.com/30903997/35856259-53668456-0aea-11e8-85d0-146412c892f1.png">

**Comment by domoritz** [comment]
We could automatically flatten fields that are coming from an argmin/argmax computation.

**Comment by kanitw** [comment]
Yes, we need general infrastructure for tracking fields.
This would be useful for this argmin/argmax issue, and for timeUnit and bin in `transform` as well.

**Comment by domoritz** [comment]
Yes, I don't believe this is really something we should patch without proper tracking. cc @sirahd

**Comment by kanitw** [comment]
No longer a bug 

![image](https://user-images.githubusercontent.com/111269/55207000-c050ab80-5195-11e9-8184-36b489b5be67.png)
