### ISSUE TITLE
Issues with nesting

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3369]
* #3361
* #3368
* #3351
* #3251 
* #3441

I thought I had fixed most of the issues in https://github.com/vega/vega-lite/pull/3141 so it would be good to look into this patch. 

There are two ways forward. One is to clean up these issues with proper fixes. The other is to just flatten nested accesses. I feel the second option might make sense since we flatten nested data anyway when we parse it as a number.

**Comment by kanitw** [comment]
Should we close other issues and consolidate them as one issue here?

**Comment by domoritz** [comment]
Let's leave them open as they have some examples and potentially different fixes.

**Comment by domoritz** [comment]
We discussed this issue with @jheer and decided that it's okay to flatten the data on ingestion. 

@nyurik I know you are one of the main users of nested data and wanted to know your thoughts before we go down this route.

**Comment by nyurik** [comment]
@domoritz sorry, could you elaborate a bit? I'm not sure what you mean by flattening access.

**Comment by domoritz** [comment]
We are having a few issues with nested data in Vega and consider flattening all data at the beginning of the dataflow. We would automatically convert `field: 'foo.bar[0]'` -> `foo\\.bar\\[0\\]` so that specs will continue to work. The only case where we won't be able to automatically escape field names is when you use a an expression as we don't parse them.

**Comment by nyurik** [comment]
@domoritz sorry, still a bit unclear. Do you propose that VL somehow would modify the actual underlying data?  Introducing magical conversion seems like a bad idea because it would work very differently between expressions and everything else, but I think I still don't understand the proposal.

**Comment by nyurik** [comment]
Summing up today's discussion: per @domoritz, it **might** be possible to keep data in the original format for all user-specified transformations, and afterwards "flatten" them. This way, if the source value is `{ foo: { bar: 10 }}`, it would use a formula transformation `{type: 'formula', expr: 'datum.foo.bar', as: 'foo.bar'}`, resulting in the new value `{ foo: { bar: 10 }, 'foo\.bar': 10 }`.  User filtering and expressions would be done before the flattening, so only the generated code will directly use the flattened values, not any of the user expressions.

The only exception is faceting (which currently doesn't work at all). With faceting, VL may have to create expressions before applying user's expressions. TBD: it might be possible to do faceting without flattening, and flatten values only inside each facet.

TODOs:
- [ ] Establish all use cases of VL graphs with nesting that would be affected. This can be used for unit testing later.
- [ ] List all cases when it is not possible to avoid using `calculate` (e.g. additional parsing done by VL)
- [ ] See if its possible to delay flattening until after user code

**Comment by domoritz** [comment]
https://vega.github.io/vega/docs/transforms/flatten/ could be quite useful.

**Comment by jheer** [comment]
The flatten transform is solely for array values. If you want to map nested fields to top level fields you can use either formula (one at a time) or project (do it all at once) transforms.
