### ISSUE TITLE
Date Filter within Transformer Object

### ISSUE THREAD

**Issue by manuelgomezrico** [vega/vega-lite#3370]
I have this case:

I have un dataset with data all year and I want filter with date field. My goal is filtering data: last 30 days

Can somebody help me?

**Comment by domoritz** [comment]
You can write an expression with `now()`: https://vega.github.io/vega/docs/expressions/#datetime-functions. Please post further questions on the mailing list: https://groups.google.com/forum/?fromgroups#!forum/vega-js.
