### ISSUE TITLE
Make line skip null values

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3372]
This is a feature request forked from [a comment in another issue](https://github.com/vega/vega-lite/issues/3261#issuecomment-362227449), 

> null values shall be simply skipped and not connected with existings values. 

![34883382-c91038da-f7b9-11e7-8a30-6e5ab71c7019](https://user-images.githubusercontent.com/1797931/35674271-6953f41e-0744-11e8-9d6b-cf657ee8b67b.PNG)

This may require some change / some transform in Vega?  

cc: @jheer

**Comment by kanitw** [comment]
Vega `line` and `area` actually have the new `defined` encoding channel.  We should automatically apply this channel by default.

**Comment by g3o2** [comment]
Stephen Few's [article (see pages 2 and 3)](http://perceptualedge.com/articles/visual_business_intelligence/missing_values_and_incomplete_periods_in_time_series.pdf) on displaying missing values provides in addition a suggestion to what should happen if a data value is surrounded by missing values.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3618
