### ISSUE TITLE
Question regarding population.json / grouped bar chart

### ISSUE THREAD

**Issue by vikpe** [vega/vega-lite#3383]
**Is repetition of data required in order to create a grouped bar chart?** 

In the data file [population.json](https://vega.github.io/editor/data/population.json) from [the example](https://vega.github.io/editor/#/examples/vega-lite/bar_grouped), data is repeated for each `sex`.
```json
[  
   {  
      "year": 1850,
      "age": 0,
      "sex": 1,
      "people": 1483789
   },
   {  
      "year": 1850,
      "age": 0,
      "sex": 2,
      "people": 1450376
   }
]
```

The data could be defined as (and reduce file by 50%):
```json
[  
   {  
      "year": 1850,
      "age": 0,
      "men": 1483789,
      "women": 1450376
   }
]
```

**Comment by domoritz** [comment]
Yes, for now that is the case. The size of the spec has very little effect on the performance so I wouldn't worry about it.

**Comment by vikpe** [comment]
@domoritz Ok, thank you!

**Comment by kanitw** [comment]
Note that the data in this "long" format 
```
[  
   {  
      "year": 1850,
      "age": 0,
      "sex": 1,
      "people": 1483789
   },
   {  
      "year": 1850,
      "age": 0,
      "sex": 2,
      "people": 1450376
   }
]
```

is considered cleaner/[tidier](http://vita.had.co.nz/papers/tidy-data.html) as all keys are variable names and all values are the actual values.  

That said, in the future, you will be able to create a grouped bar chart for the short form using facet of a concatenated bar.  But we currently don't support it yet.

**Comment by vikpe** [comment]
@kanitw "Tidy data" is a very interesting article. It might be a good idea to reference it in the [data docs](https://vega.github.io/vega-lite/docs/data.html).

**Comment by kanitw** [comment]
Sure, feel free to submit a PR to suggest edits.
