### ISSUE TITLE
Legend title=false is shown as "false"

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3387]
In an encoding channel, using `"legend": {"title": false}` shows a string "false" instead of the expected no title.

**Comment by kanitw** [comment]
`title` has a string type,  so `false` would be coerced to a string.   Please use `""` or `null` instead.

**Comment by nyurik** [comment]
Thanks, makes sense. Could VL  throw an error, or at least a warning?  If the value has unexpected type, it is not a valid spec, and this would allow users to self-correct things much more rapidly?

**Comment by kanitw** [comment]
Actually, let me just add a check for false too.  It's kinda dumb to coerce type here anyway.

**Comment by kanitw** [comment]
(I won't add boolean to the schema / docs, but I think it's a reasonable fallback not to show anything)

**Comment by domoritz** [comment]
Agreed with @kanitw. This is a good starter task.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3388#pullrequestreview-97052085
