### ISSUE TITLE
Property "step" in histogram produces no output when "step" < 1

### ISSUE THREAD

**Issue by dhuppenkothen** [vega/vega-lite#3390]
I am fairly new to Vega-Lite, so this may be due to my relative ignorance, but there's something I stumbled upon while playing around in the [online Vega-Lite Editor](https://vega.github.io/editor/#/custom/vega-lite) that may be a bug or at perhaps something that could use a note in the documentation.

I've been trying to create a histogram while specifying the step-size with the `step` property. 

The following will produce an output as expected:

```
{
  "data": {"url": "data/movies.json"},
  "transform": [{
    "bin": {"step":0.5},
    "field": "IMDB_Rating",
    "as": "bin_IMDB_Rating"
  }],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "bin_IMDB_Rating",
      "type": "ordinal"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

<img width="466" alt="screen shot 2018-02-16 at 2 46 23 pm" src="https://user-images.githubusercontent.com/5237391/36332715-316eb26a-1328-11e8-8c18-599cd8af16b1.png">

However, when I specify `step` in the `x` property within `encoding`, it will *only* create a plot when `step` is *integer*:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/movies.json",
    "format": {
      "type": "json"
    }
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"step": 0.5},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```
This produces:

<img width="232" alt="screen shot 2018-02-16 at 2 50 33 pm" src="https://user-images.githubusercontent.com/5237391/36332852-c1c3fdc0-1328-11e8-8008-4c5be7c99859.png">

Is this expected behaviour? Does the property `step` mean different things when used within `encoding` than when it does for `transform`?

**Comment by domoritz** [comment]
Thanks m you so much for the detailed bug report. I will have a look at this to see what's happening.

**Comment by domoritz** [comment]
This is a bug in the way we generate some names. 

We don't convert `0.5` to `0_5` and Vega tries to access a nested field that doesn't exist. The fix is easy but crusical. Thank you @dhuppenkothen for the bug report.
