### ISSUE TITLE
Rename composite mark to compound mark?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3392]
I think compound is a better term and shorter.

**Comment by domoritz** [comment]
But we have composition operators... so depending on whether you like that association or not, I'm okay with changing.

**Comment by kanitw** [comment]
That’s why we had the original name but its only layer so the name may hint that this can be more than layer.  

But the issue is that composite is just so long and complicated.

**Comment by domoritz** [comment]
```
composite
compound
```

**Comment by kanitw** [comment]
I know, but the compound is two syllable, making it way easier to say.

**Comment by jheer** [comment]
FWIW composite also matches the terminology used for software design patterns.
