### ISSUE TITLE
Script for generating image files

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#34]
create cli for generating image file from spec

basically just wiring `vl2vg` and vega's `vg2png` and `vg2svg` should work

**Comment by kanitw** [comment]
Maybe need to modify  `vg2png` and `vg2svg`  to support unix pipe

**Comment by yhoonkim** [comment]
I'm stuck with the error that ```Cannot find module 'canvas'```
I'm new to node and NPM. But as I know, ``vega`` includes ``canvas`` and ``vega-lite`` includes ``vega``. So I think that we don't have to include ``canvas`` again.   
Could you( @kanitw ) comment about this? 

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.instance (/Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/node_modules/vega-scenegraph/src/util/canvas.js:11:18)
    at CanvasRenderer.prototype.initialize (/Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/node_modules/vega-scenegraph/src/render/canvas/CanvasRenderer.js:20:25)
    at View.prototype.initialize (/Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/src/core/HeadlessView.js:57:6)
    at View.prototype.renderer (/Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/src/core/View.js:235:10)
    at View.prototype.renderer (/Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/src/core/HeadlessView.js:16:34)
    at /Users/younghoonkim/Desktop/dev/vega-lite/node_modules/vega/src/core/View.js:435:8
```

**Comment by kanitw** [comment]
We did not include `canvas` in package.json.   

However, since you're running Vega, you still need canvas.  Try running `npm install` again.  I think I ran `npm install --no-optional` the other day, which would skip canvas.

Note that installing `canvas` on a mac is tricky so you might be to brute through some trial-and-errors and googling.

**Comment by yhoonkim** [comment]
Thanks. It was my fault.
The reason was I skipped the error message when I ran ```npm install```.
The error was about ``cairo`` something and I realized that to I should have installed that [cairo](https://www.npmjs.com/package/canvas) in my Mac.
So I ran this
```brew install pkg-config cairo libpng jpeg giflib```

**Comment by yhoonkim** [comment]
But still, there a issue that ```vl2png``` is not working properly. 
It draws text really largely.
![bar](https://cloud.githubusercontent.com/assets/6269456/11621085/66e9907e-9c6d-11e5-9aee-f001dc5e9538.png)
It's the same when I run ```vg2png``` in vega.

**Comment by jpocom** [comment]
Check it https://github.com/vega/vega/issues/356

**Comment by yhoonkim** [comment]
@jpocom Thanks!
I updated cairo 1.14.2 to 1.14.4 and it solved.

**Comment by kanitw** [comment]
Also delete vl2png, vl2svg

**Comment by ZeningQu** [comment]
There are some giant text in the output of node vl2png:
![area](https://cloud.githubusercontent.com/assets/822034/12938573/5cb90ba4-cf6a-11e5-9400-4c58e08c51ee.png) area.json
![bar](https://cloud.githubusercontent.com/assets/822034/12938574/5cc2b820-cf6a-11e5-9e9e-d27c816bb587.png) bar.json

**Comment by domoritz** [comment]
@ZeningQu Is this a problem with vg2png as well?

**Comment by ZeningQu** [comment]
@domoritz Thanks for the new scripts!

**Comment by domoritz** [comment]
No problem. I ended up using the svg files instead of png because they are resolution independent.

**Comment by ZeningQu** [comment]
Cool, good to know :) I will try to use svg too for the gallery page.
