### ISSUE TITLE
Setting domain for line plot should clip values outside domain

### ISSUE THREAD

**Issue by gregnordin** [vega/vega-lite#3402]
This is my problem - when the original data extends outside the specified domain, it still gets plotted:
![temp](https://user-images.githubusercontent.com/4380622/36506880-1c991d12-1715-11e8-9f9d-b898e8c97b22.gif)
Shouldn't setting the domain clip the line to stay within the range of the plot? Is this a bug or am I misunderstanding how Vega-Lite should operate? Or perhaps I have implemented something incorrectly? Any insight would be much appreciated.

Here is the JSON that creates the above plot:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"wavelength": 250, "normalized_power": 1},
      {"wavelength": 300, "normalized_power": 2},
      {"wavelength": 330, "normalized_power": 3},
      {"wavelength": 390, "normalized_power": 4},
      {"wavelength": 420, "normalized_power": 2},
      {"wavelength": 450, "normalized_power": 1.8},
      {"wavelength": 500, "normalized_power": 1.1}
    ]
  },
  "encoding": {
    "x": {
      "axis": {
        "title": "Wavelength (nm)"
      },
      "field": "wavelength",
      "scale": {
        "domain": [
          300,
          450
        ]
      },
      "type": "quantitative"
    },
    "y": {
      "axis": {
        "orient": "left",
        "title": "Normalized LED Power"
      },
      "field": "normalized_power",
      "type": "quantitative"
    }
  },
  "height": 250,
  "mark": "line",
  "width": 400
}
```

**Comment by kanitw** [comment]
Hi, 

This is a desired behavior -- changing scale domain should only change the "domain" of the scale function, but doesn't change the data that get passed through the scale. 

You could instead use a filter transform to filter the data:
```
transform: [{filter: {"field": "wavelength", "range": [300, 450]}}]
```

**Comment by domoritz** [comment]
I was about to post this. You might want to add `scale.zero: false`. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"wavelength": 250, "normalized_power": 1},
      {"wavelength": 300, "normalized_power": 2},
      {"wavelength": 330, "normalized_power": 3},
      {"wavelength": 390, "normalized_power": 4},
      {"wavelength": 420, "normalized_power": 2},
      {"wavelength": 450, "normalized_power": 1.8},
      {"wavelength": 500, "normalized_power": 1.1}
    ]
  },
  "transform": [{
    "filter": {"field": "wavelength", "range": [300, 450]}
  }],
  "encoding": {
    "x": {
      "axis": {
        "title": "Wavelength (nm)"
      },
      "field": "wavelength",
      "scale": {
        "zero": false
      },
      "type": "quantitative"
    },
    "y": {
      "axis": {
        "orient": "left",
        "title": "Normalized LED Power"
      },
      "field": "normalized_power",
      "type": "quantitative"
    }
  },
  "height": 250,
  "mark": "line",
  "width": 400
}
```

**Comment by domoritz** [comment]
<img width="475" alt="screen shot 2018-02-21 at 13 50 55" src="https://user-images.githubusercontent.com/589034/36507359-44a13c2e-170e-11e8-90e8-eb1a88df1804.png">

**Comment by domoritz** [comment]
An alternative is clipping

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"wavelength": 250, "normalized_power": 1},
      {"wavelength": 300, "normalized_power": 2},
      {"wavelength": 330, "normalized_power": 3},
      {"wavelength": 390, "normalized_power": 4},
      {"wavelength": 420, "normalized_power": 2},
      {"wavelength": 450, "normalized_power": 1.8},
      {"wavelength": 500, "normalized_power": 1.1}
    ]
  },
  "encoding": {
    "x": {
      "axis": {
        "title": "Wavelength (nm)"
      },
      "field": "wavelength",
      "scale": {
        "domain": [
          300,
          450
        ]
      },
      "type": "quantitative"
    },
    "y": {
      "axis": {
        "orient": "left",
        "title": "Normalized LED Power"
      },
      "field": "normalized_power",
      "type": "quantitative"
    }
  },
  "height": 250,
  "mark": {
    "type": "line",
    "clip": true  
  },
  "width": 400
}
```

<img width="476" alt="screen shot 2018-02-21 at 13 52 50" src="https://user-images.githubusercontent.com/589034/36507437-894ac610-170e-11e8-8e4f-1dd69d134d57.png">

**Comment by domoritz** [comment]
When you use clipping and set the domain, you might want to disable nice.

```json
...
     "scale": {
        "domain": [
          300,
          450
        ],
        "nice": false
      },
...
```

**Comment by domoritz** [comment]
@gregnordin If you want to write these suggestions up, we would love to have some notes on this in the docs.

**Comment by gregnordin** [comment]
Wow, you guys are awesome! I figured I was probably missing something, and both of your comments are extremely helpful. 

Regarding notes for docs, is there a particular place you would recommend that they go?

**Comment by domoritz** [comment]
I think in https://github.com/vega/vega-lite/blob/master/site/docs/encoding/scale.md, we could have a section about customizing the domain and what to consider (clipping, nice, with examples).

**Comment by gregnordin** [comment]
Ok, that looks like a good place. I just looked through the markdown source for that page. In particular I'm trying to understand how images are handled since I would need to include several of them. As an example of an image, there is this line in the Color Schemes section:

    <div class="vl-example" data-name="point_color"></div>

Evidently there is some post-processing to insert images? How should I handle this to include images?

**Comment by domoritz** [comment]
> `<div class="vl-example" data-name="point_color"></div>`

Includes the spec named `point_color`. If you run `yarn run site`, you can look at the page in action. 

If you want to write up some docs and just include the specs, we can move it to the docs for you. Just write it in markdown somewhere.

**Comment by gregnordin** [comment]
Ok, I created Pull Request #3403 with some text and images that can be integrated into the documentation.
