### ISSUE TITLE
Consistently use `vega-util` error instead of `throw new Error(...)`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3406]
Like in https://github.com/vega/vega-lite/pull/3394

**Comment by ydlamba** [comment]
I would like to work on this issue.

**Comment by domoritz** [comment]
@ydlamba Excellent. You can ask @kanitw specific questions if you have any.

**Comment by ydlamba** [comment]
When I try to throw the error using error function from `vega-util`, the `tsc` is giving the error (`error TS7030: Not all code paths return a value.`) which is possibly due to the fact that no return value is explicitly specified when throwing the error by calling a function.

**Comment by kanitw** [comment]
I see.  Then I guess we can stick with standard `throw` then.   (`return error()` could work too, but it's not really short anymore.)  

Instead, we should consistently remove `error` and use `throw new Error()` then.

**Comment by ydlamba** [comment]
Currently, each error is thrown by `throw new Error()` and `error()` is nowhere used in vega-lite.

**Comment by ydlamba** [comment]
There are few places where `error()` is used. Changing them to `throw new Error()`.
