### ISSUE TITLE
Selecting values upon start in a barchart

### ISSUE THREAD

**Issue by dionverbeke** [vega/vega-lite#3409]
Hi, 

I would like to pre-select certain values in a barchart up loading.

How would I do that?

For Example:

Selecting in advance Feb 2018 in this graph

![image](https://user-images.githubusercontent.com/5289831/36605352-c0e73690-18c0-11e8-972a-16e0a4c75f31.png)

Current spec:

var vlSpec =
        {
            "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
            "data": { "url": "php/solar.php" },
            "vconcat": [{
                "width": 1000,
                "mark": "area",
                "encoding": {
                    "x": {
                        "field": "date",
                        "type": "temporal",
                        "scale": { "domain": { "selection": "brush" } },
                        "axis": { "title": "" }
                    },
                    "y": { "field": "price", "type": "quantitative" }
                }
            }, {
                "width": 1000,
                "height": 50,
                "mark": "area",
                "selection": {
                    "brush": { "type": "interval", "encodings": ["x"] }
                },
                "encoding": {
                    "x": {
                        "field": "date",
                        "type": "temporal",
                        "axis": { "format": "%Y-%m" }
                    },
                    "y": {
                        "field": "price",
                        "type": "quantitative",
                        "axis": { "tickCount": 3, "grid": false }
                    }
                }
            }]
        }

**Comment by iliatimofeev** [comment]
I will be great to extend values of  "empty" with something like filter transform and kind of aggregate to allow select first, last or median values. 
I think it will be very helpful improvement for dependent charts.  By the way I found another mention of this problem on forum https://groups.google.com/forum/#!topic/vega-js/ctj8jFP-aaA

**Comment by king612** [comment]
+1 on this feature request.  I really need just the feature described as my main chart is very busy (15 - 20 lines) and not really useful until you zoom in on a section.  I'd love to be able to have the overview selection default to an initial domain.
