### ISSUE TITLE
Refactor/extend sort

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#341]
Forked from #27  

### Summary 

I try to summarize what we can do and we we need to do with sorting here. 
We can only sort nominal/ordinal fields.   We can sort them in the following ways. 

- [ ] temporal *** 

#### 1) manual order
- setting domain directly (and maybe add filter)
- [ ] support manual order
  - [ ] test what happens if we specify domain and there is a value not exist 
-  we might need to filter.
  - [ ] extend the scale — (append that at the end)

#### 2) alphabetical 
Vega 1: `sort:true`

- [x] `dl.cmp` — should be what vega already used. 
- [ ] support `reverse`  (now it doesn’t do anything)

#### 3) original order of the data 
Vega 1:  `sort: false`

#### 4) sort by aggregated value.  

There are a few cases:

4-a) **raw plot**  
We can sort by aggregated value of any column (not matter it’s included in the encoding or not). 
In Vega 1, this **requires** generating a separate aggregated table.  
because there might be multiple values for each O value of the column. 
However, Vega 2 we can use scale’s `sort` property directly. 

4-b) **aggregate plot with one dimension**.  
This does **not require** generating a separate aggregated table in both vega 1 and 2 as 
we can augment the generated aggregated table with the measure sorted on.

4-c) **aggregate plot with multiple dimensions** 

We can sort an ordinal column by aggregated value of another column.  This is quite complicated because the original aggregated table isn’t sufficient since there are still multiple aggregated value for each value of the column.   There are two ways to handle this: (1) create a separate aggregated table from the source (2) aggregate the aggregated table.   We should support (1) for now as (2) doesn’t make much sense. 

- [ ] support 1.

- [ ] support filter in the sort by "aggregated with filter” 

In addition, a commonly used sort includes filtering. 

For example if we have two ordinals O<sub>1</sub> and O<sub>2</sub> and one Q.    
We can sort O<sub>1</sub> by `aggr(Q)` where O<sub>2</sub> = `<value>`

![sort__product__and_tableau_-_book2](https://cloud.githubusercontent.com/assets/111269/6313041/699f7cd4-b94c-11e4-8609-3f0c4f776ecf.png)

----------------

### Other TODO

- [x] refactor sort to be consistent with vega2’s sort

- [ ] add `type` to sort’s schema

- [ ] auto sort that include ascending / descending  -- right now toggle sort has fixed ascending/descending https://github.com/uwdata/vegalite/pull/343/files

**Comment by kanitw** [comment]
@domoritz   I’ve just updated this issue with all information / plan about sorting.  I will discuss this a bit with Jeff tomorrow.

**Comment by domoritz** [comment]
Thanks. Sounds good.

**Comment by kanitw** [comment]
We already supported all sort described above except to sort by mutiple fields (e.g,. "sort by mean of A, then by mean of B")  but that's not supported in Vega and it's less important for now.  So I'm closing this!
