### ISSUE TITLE
Missing stderr in aggregate ops

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3414]
It's a Vega aggregate but not Vega-Lite. Is that intentional?

**Comment by kanitw** [comment]
I don't think so.  We discussed this earlier right?

@chanwutk -- Can you check if this actually work in Vega-Lite?  If so, correct the schema and update documentation?

**Comment by kanitw** [comment]
FIxed in https://github.com/vega/vega-lite/pull/3473.  

cc: @chanwutk  Don't forget to close fixed issue :)
