### ISSUE TITLE
Return warnings and errors from assembleTopLevelModel

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3416]
The`assembleTopLevelModel` function returns an object but the only property is just `spec`.

**Comment by domoritz** [comment]
Why do we need this if we have a logger? @kanitw? 

Should we return the non-normalized spec? What else would be useful to return?

**Comment by kanitw** [comment]
normalized (not non-normalized) spec could be useful.

**Comment by domoritz** [comment]
Why would you want the non=normalized spec again?

**Comment by kanitw** [comment]
> Why would you want the non-normalized spec again?

Ask yourself?  lol  

From: https://github.com/vega/vega-lite/issues/3416#issuecomment-370255725

> Should we return the non-normalized spec? What else would be useful to return?

**Comment by domoritz** [comment]
We already return the normalized spec. https://github.com/vega/vega-lite/blob/master/src/compile/compile.ts#L131

Warnings are coming from the logger so let's not make changes here.
