### ISSUE TITLE
[FR] Defining initial state in query widgets

### ISSUE THREAD

**Issue by eibanez** [vega/vega-lite#3431]
Hi,

I believe that, by default, plots with query widgets default to an empty selection. For example, the plot in [this section](https://vega.github.io/vega-lite/docs/bind.html#input-element-binding) shows all the points in blue, regardless of origin.

However, the dropdown shows "Europe" so the perception is that the filter has been applied. Moreover, if you select another value and come back to "Europe" the selection is applied. In the end, the reader can and will be exposed to two different versions on the graph for the same value in the selector. Also, using the dropdown and reselecting "Europe" right after loading the graph doesn't do anything.

Same thing happens with slides as in [this example](https://vega.github.io/vega-lite/examples/interactive_query_widgets.html). That case is not that bad because the label next to the slider is empty.

In both cases, I think it would be great to have the ability of selecting the initial state and apply it to the graph, because:
- It would solve the issues around the dropdown inconsistencies
- Would allow the definition of any point in the range as a starting point (e.g., the end of a sequence, letting the user walk back)

As always, thanks for all your work.

**Comment by eibanez** [comment]
Probably related to #3409

**Comment by arvind** [comment]
Implemented with #4139. A new `init` property is now available for selections, and should propagate to the initial state of query widgets.
