### ISSUE TITLE
Problem accessing geojson properties when generated inline

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3432]
Perhaps I am missing something, but there appears to be a problem in accessing inline geoJson objects. 

The following spec, which loads a geoJson file works as expected:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200, "height": 200,
  "data": {
    "url": "https://gist.githubusercontent.com/jwoLondon/6caab27b0d131c74c194efd943389201/raw/e9ea15b56001dfac9c3795dff4f2a0f67dbfc710/geojsontest.json",
    "format": { "type": "json", "property":  "features" }
  },
  "projection": { "type":  "orthographic" },
  "encoding": {
    "color": {
      "field": "properties.myRegionName",
      "type": "nominal"
    }
  },
  "mark": "geoshape"
}
```

But if I generate the same content inline, I do not seem to be able to access the `myRegionName` property:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200, "height": 200,
  "data": {
    "values": [
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "Polygon",
            "coordinates": [ [ [-3,52], [4,52], [4,45], [-3,45], [-3,52] ] ]
          },
          "properties": { "myRegionName": "Southern region" }
        },{
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [ [ [-3,59], [4,59], [4,52], [-3,52], [-3,59] ] ]
            },
            "properties": { "myRegionName": "Northern region" }
          }
        ]
      }
    ],
    "format": { "type": "json", "property": "features" }
  },
  "projection": { "type": "orthographic" },
  "encoding": {
    "color": {
      "field": "properties.myRegionName",
      "type": "nominal"
    }
  },
  "mark": "geoshape"
}
```

This spec generates the error : `TypeError: undefined is not an object (evaluating 'e.hasOwnProperty’)`

Is this perhaps related to one of the issues in #3369, or is there some other way of accessing nested inline fields?

**Comment by jwoLondon** [comment]
This can be fixed in the inline data specification by making `features` an object rather than a singleton list containing the object (i.e. removing square brackets immediately following `"features":`).

But it remains the case that when the singleton array version (which is a valid geojson spec) is loaded from a file it works, but when generated inline, it does not.

**Comment by domoritz** [comment]
Thank you for the comment @jwoLondon. I think this is related to https://github.com/vega/vega-lite/issues/3369. We will fix this soon after the vis deadline.

**Comment by iliatimofeev** [comment]
According to specification [RFC 7946 ](https://tools.ietf.org/html/rfc7946#section-2)
>**2.  GeoJSON Text**
>    A GeoJSON text is a JSON text and consists of a single GeoJSON object.
>**3.  GeoJSON Object**
>  A GeoJSON object represents a Geometry, Feature, or collection of Features.

Example uses `"values":[{GeoJSON Object},{GeoJSON Object}] ` which is not valid GeoJSON specification.
Specification without array will work as expected:
```javascript 
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200, "height": 200,
  "data": {
    "values": // <--- no array here
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "Polygon",
            "coordinates": [ [ [-3,52], [4,52], [4,45], [-3,45], [-3,52] ] ]
          },
          "properties": { "myRegionName": "Southern region" }
        },{
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [ [ [-3,59], [4,59], [4,52], [-3,52], [-3,59] ] ]
            },
            "properties": { "myRegionName": "Northern region" }
          }
        ]
      }
    ,
    "format": { "type": "json", "property": "features" }
  },
  "projection": { "type": "orthographic" },
  "encoding": {
    "color": {
      "field": "properties.myRegionName",
      "type": "nominal"
    }
  },
  "mark": "geoshape"
}
``` 
![export 4](https://user-images.githubusercontent.com/11561581/40259025-88b5e5fe-5afc-11e8-9d39-781e7df374a0.png)

Actually the array of GeoJSON objects is valid data format for vega, and issue in this example in `data.format.property==="features"` that is not correct path to retrieving GeoJSON objects. Setting it to `[0].features` will result the same correct visualisation.

BTW:  thank you @jwoLondon , for me it was a first working example in internet on splitting  GeoJSON into manageable vega shapes.

**Comment by domoritz** [comment]
Thank you @iliatimofeev! Do you want to update the documentation to make this clearer? Can we close the issue then @jwoLondon?

**Comment by jwoLondon** [comment]
Thanks @iliatimofeev, that's helpful and clarifies where the problem lies, and so as far as I can see once the documentation is updated this issue can be closed.

**Comment by ratnanil** [comment]
OMG I was searching around for *hours* trying to find out why I coudn't use a specific field to encode / colorize my `markGeoshape()`. This thread helped me figure out that the field (e.g. `myfield`)  had to be accessed via `"properties.myfield"` rather than just `"myfield"`.

**Comment by domoritz** [comment]
Uff, I hope we can avoid that in the future. Is there something in the docs you propose we change?

**Comment by ratnanil** [comment]
Well, the Vegalite-API docs completely lack examples. There are some examples on observableHQ, but they are somewhat complex and not plaintext. I was thinking about adding a few examples to the docs via a PR, but it might take a while till I get to it.

**Comment by domoritz** [comment]
Yes, that's a bigger issue. I have some ideas to generate docs for all APIs (Vega-Lite, Vega-Lite-API, Altair, etc) from one source but that will take some work to get up a running.

**Comment by ratnanil** [comment]
Ok, so you have something planned? Would suggestions for some minimal examples be helpful?
