### ISSUE TITLE
ability/parameter to only show part or none of rect if data goes into that area

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#3436]
(using vega-lite through Altair)

Here is what the plot looks like:
![image](https://user-images.githubusercontent.com/1798497/36899574-ab4ffcfe-1ded-11e8-9fd3-f19167fd0e47.png)

I am trying to find out if there is a way to only show part of a rect.
For example, in the above plot - is there a way to flag the rects only up to the point of other data in the plot, in this instance the plot 's y-axis would only go up to around 70, as that is where the data ends.

The idea is similar to what is seen here in bokeh:
(box annotations)
https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#box-annotations
scroll down one time to see the plot.

I used the "open in vega editor" and here is the code that I was trying to do this with:

{
  "config": {
    "view": {
      "width": 400,
      "height": 300
    }
  },
  "layer": [
    {
      "mark": {
        "type": "rect",
        "color": "red",
        "opacity": 0.2
      },
      "data": {
        "values": [
          {
            "fifth": 60,
            "first": 0,
            "fourth": 60,
            "second": 10,
            "sixth": 100,
            "third": 10
          }
        ]
      },
      "encoding": {
        "y": {
          "type": "quantitative",
          "field": "first"
        },
        "y2": {
          "type": "quantitative",
          "field": "second"
        }
      }
    },
    {
      "mark": {
        "type": "rect",
        "color": "green",
        "opacity": 0.2
      },
      "data": {
        "values": [
          {
            "fifth": 60,
            "first": 0,
            "fourth": 60,
            "second": 10,
            "sixth": 100,
            "third": 10
          }
        ]
      },
      "encoding": {
        "y": {
          "type": "quantitative",
          "field": "third"
        },
        "y2": {
          "type": "quantitative",
          "field": "fourth"
        }
      }
    },
    {
      "mark": {
        "type": "rect",
        "color": "orange",
        "opacity": 0.2
      },
      "data": {
        "values": [
          {
            "fifth": 60,
            "first": 0,
            "fourth": 60,
            "second": 10,
            "sixth": 100,
            "third": 10
          }
        ]
      },
      "encoding": {
        "y": {
          "type": "quantitative",
          "field": "fifth"
        },
        "y2": {
          "type": "quantitative",
          "field": "sixth"
        }
      }
    },
    {
      "mark": "circle",
      "data": {
        "url": "https://vega.github.io/vega-datasets/data/movies.json",
        "format": {
          "type": "json"
        }
      },
      "encoding": {
        "size": {
          "type": "quantitative",
          "aggregate": "count",
          "field": "*"
        },
        "x": {
          "type": "quantitative",
          "field": "IMDB_Rating"
        },
        "y": {
          "type": "quantitative",
          "field": "Rotten_Tomatoes_Rating"
        }
      },
      "transform": [
        {
          "filter": "datum.Rotten_Tomatoes_Rating < 70"
        }
      ]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}

Additionally, if the data only went to 4, then this plot:
![image](https://user-images.githubusercontent.com/1798497/36900875-07707658-1df3-11e8-97c4-e8a6760341e2.png)
would only show red as it extends to the top of the data, and the green orange areas would not be visible since 7 would be the top of the plot, and red would only be visible in the background.

**Comment by domoritz** [comment]
I might be misunderstanding the question but can you limit the scale domain?

**Comment by afonit** [comment]
@domoritz I think that may be it - I will play around with that.

**Comment by afonit** [comment]
@domoritz , I think I am lacking in understanding of the scale domain.  I have read up on it in the docs and have played with it.

I am just not seeing how that would affect the partial display of the rect's.

I have redone the rect data to make this much simpler into a single rect that is colored instead of three rects.

{
  "config": {
    "view": {
      "width": 400,
      "height": 300
    }
  },
  "layer": [
    {
      "mark": {
        "type": "rect",
        "opacity": 0.2
      },
      "data": {
        "values": [
          {
            "classification": "orange",
            "y": 0,
            "y2": 10
          },
          {
            "classification": "red",
            "y": 10,
            "y2": 60
          },
          {
            "classification": "green",
            "y": 60,
            "y2": 100
          }
        ]
      },
      "encoding": {
        "color": {
          "type": "nominal",
          "field": "classification",
          "scale": {
            "domain": [
              "orange",
              "red",
              "green"
            ],
            "range": [
              "orange",
              "red",
              "green"
            ]
          }
        },
        "y": {
          "type": "quantitative",
          "field": "y"
        },
        "y2": {
          "type": "quantitative",
          "field": "y2"
        }
      }
    },
    {
      "mark": {
        "type": "circle",
        "opacity": 0.1
      },
      "data": {
        "url": "https://vega.github.io/vega-datasets/data/movies.json",
        "format": {
          "type": "json"
        }
      },
      "encoding": {
        "size": {
          "type": "quantitative",
          "aggregate": "count",
          "field": "*"
        },
        "x": {
          "type": "quantitative",
          "field": "IMDB_Rating"
        },
        "y": {
          "type": "quantitative",
          "field": "Rotten_Tomatoes_Rating"
        }
      },
      "selection": {
        "selector006": {
          "type": "interval",
          "bind": "scales",
          "encodings": [
            "x",
            "y"
          ],
          "on": "[mousedown, window:mouseup] > window:mousemove!",
          "translate": "[mousedown, window:mouseup] > window:mousemove!",
          "zoom": "wheel!",
          "mark": {
            "fill": "#333",
            "fillOpacity": 0.125,
            "stroke": "white"
          },
          "resolve": "global"
        }
      },
      "transform": [
        {
          "filter": "datum.Rotten_Tomatoes_Rating < 30"
        }
      ]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}

**Comment by domoritz** [comment]
Here is a sketch if what I meant

```json
{
  "config": {
    "view": {
      "width": 400,
      "height": 300
    }
  },
  "layer": [
    {
      "mark": {
        "type": "rect",
        "opacity": 0.2,
        "clip": true
      },
      "data": {
        "values": [
          {
            "classification": "orange",
            "y": 0,
            "y2": 10
          },
          {
            "classification": "red",
            "y": 10,
            "y2": 60
          },
          {
            "classification": "green",
            "y": 60,
            "y2": 100
          }
        ]
      },
      "encoding": {
        "color": {
          "type": "nominal",
          "field": "classification",
          "scale": {
            "domain": [
              "orange",
              "red",
              "green"
            ],
            "range": [
              "orange",
              "red",
              "green"
            ]
          }
        },
        "y": {
          "type": "quantitative",
          "field": "y",
          "scale": {
            "domain": [0, 30]
          }
        },
        "y2": {
          "type": "quantitative",
          "field": "y2"
        }
      }
    },
    {
      "mark": {
        "type": "circle",
        "opacity": 0.5,
        "clip": true
      },
      "data": {
        "url": "https://vega.github.io/vega-datasets/data/movies.json",
        "format": {
          "type": "json"
        }
      },
      "encoding": {
        "size": {
          "type": "quantitative",
          "aggregate": "count"
        },
        "x": {
          "type": "quantitative",
          "field": "IMDB_Rating"
        },
        "y": {
          "type": "quantitative",
          "field": "Rotten_Tomatoes_Rating",
          "scale": {
            "domain": [0, 30]
          }
        }
      },
      "transform": [
        {
          "filter": "datum.Rotten_Tomatoes_Rating < 30"
        }
      ]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}
```

<img width="595" alt="screen shot 2018-03-05 at 10 58 55" src="https://user-images.githubusercontent.com/589034/36993893-432e967a-2064-11e8-889b-fe2a2cad0f9e.png">
