### ISSUE TITLE
Move line hover example to example gallery

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3439]
See #3438. CC @jakevdp

**Comment by ydlamba** [comment]
Can I work on this?

**Comment by domoritz** [comment]
Of course. You will need the `yarn run build:example NAME` function to build the vega and svg files. Also, add an entry to https://github.com/vega/vega-lite/blob/master/_data/examples.json

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3440
