### ISSUE TITLE
lessThan / moreThan Filter

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3452]
For timeUnit, we can't just use expression.   Using range with null values make spec not very readable. 

So I think we better support `lessThan` / `moreThan` filter.    
And perhaps, `lessThanOrEqual` / `moreThanOrEqual`.

**Comment by domoritz** [comment]
lt, lte, gt, gte, are pretty standard. At least we should call it greater, not more.

**Comment by kanitw** [comment]
What's wrong with "more"?  (It's way shorter.)

lt, lte, gt, gte --> maybe they are okay, but less readable.

**Comment by domoritz** [comment]
`greaterThan` not `moreThan` is the standard name for `>`. If you want brevity, we can use `gt` which is standard in many query languages. E.g.: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html

**Comment by kanitw** [comment]
Let's say `gt`, `gte`, `lt`, `lte` then.

**Comment by kanitw** [comment]
Will be addressed in https://github.com/vega/vega-lite/pull/3561
