### ISSUE TITLE
Candlestick example is broken

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3457]
https://vega.github.io/vega-lite/examples/layer_candlestick.html is broken - both `data_1` and `data_2` has no data after filtering.

![image](https://user-images.githubusercontent.com/1641515/36951614-b08e2ffa-1fba-11e8-9d62-389e13a73330.png)

**Comment by kanitw** [comment]
Can you explain more?  It still shows up fine for me.

![image](https://user-images.githubusercontent.com/111269/36951637-de32752e-1fba-11e8-8dab-9037fb3dc3a3.png)

**Comment by nyurik** [comment]
Hmm, this works in Chrome, but not in Firefox

**Comment by nyurik** [comment]
Broken on Friefox 58.0.2 (64-bit) on Ubuntu 17.10

**Comment by domoritz** [comment]
Then it's a vega bug. Can you file the issue there?

**Comment by nyurik** [comment]
@kanitw @domoritz per @jheer , most likely this is an issue with the example's date parsing, not Vega.  In Firefox, date parsing has different rules from Chrome, so the date format used in the example may need to be changed.

**Comment by domoritz** [comment]
@nyurik Can you send a PR? I also noticed a missing space `Protovis(`

**Comment by nyurik** [comment]
fixed in https://github.com/vega/vega-lite/pull/3462 - please merge
