### ISSUE TITLE
Stroke in legend even if mark doesn't use it

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3463]
Is there a reason that we show the border?

https://vega.github.io/vega-lite/examples/circle_binned.html

<img width="440" alt="screen shot 2018-03-04 at 19 59 08" src="https://user-images.githubusercontent.com/589034/36957042-87127b50-1fe6-11e8-90cc-82d9df63a289.png">

**Comment by kanitw** [comment]
The reason is called a bug lol

**Comment by domoritz** [comment]
I thought I've seen this one before...

**Comment by domoritz** [comment]
Ahh, because we actually did discuss this a while ago. https://github.com/vega/vega-lite/issues/2626

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3545
