### ISSUE TITLE
Add more concat / repeat examples to the gallery

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3469]
Right now we only have one example listed, but there are actually many good examples in the documentation.

**Comment by ydlamba** [comment]
How about adding repeated histogram (vertically) in example gallery? https://vega.github.io/vega-lite/docs/repeat.html#example-repeated-histogram

**Comment by kanitw** [comment]
I think we should add all examples in the concat and repeat pages except for SPLOM, we can just link to [interactive one](https://vega.github.io/vega-lite/examples/interactive_splom.html).     

(We should also add a note to https://vega.github.io/vega-lite/docs/repeat.html#example-scatterplot-matrix-splom to say that there is an interactive version too.)

**Comment by ydlamba** [comment]
In concat docs, the same example is displayed first horizontally and then vertically. Should we add both to the gallery or just one of them?

**Comment by kanitw** [comment]
One is fine I guess. :)

**Comment by ydlamba** [comment]
Can I work on this?

**Comment by kanitw** [comment]
Definitely!

For any small issue, feel free to comment the issue that "I would like to work on this" so that we and other people know that you will work on it.

For larger issue that involves syntax or rule design, also feel free to comment to propose a design (or even better a few designs) first before going to implement them.  This way will help reduce the development time required.
