### ISSUE TITLE
Multi-Series Line Chart w/ Tooltips Example is broken

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#3479]
Example on this page:
https://vega.github.io/vega-lite/examples/interactive_multi_line_tooltip.html

On the website no chart shows up (tested on both Chrome & Firefox). The console includes the following error:
`interactive_multi_line_tooltip.html:75 Uncaught SyntaxError: Unexpected identifier`

Originally reported on Twitter: https://twitter.com/GGlusman/status/971112649860644864

**Comment by domoritz** [comment]
I fixed it in https://github.com/vega/vega-lite/commit/8300a542994bda5db8ce289eddc6fd5de519d929 but the caches take a while to refresh.
