### ISSUE TITLE
Should TopLevel<FacetSpec> require data?

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3489]
This is a valid spec according to the schema, but it results in no plot because the data is not defined at the top level:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "facet": {
    "column": {
      "field": "species",
      "type": "nominal"
    }
  },
  "spec": {
    "mark": "point",
    "data": {
      "url": "https://vega.github.io/vega-datasets/data/iris.json"
    },
    "encoding": {
      "color": {
        "field": "species",
        "type": "nominal"
      },
      "x": {
        "field": "petalLength",
        "type": "quantitative"
      },
      "y": {
        "field": "sepalLength",
        "type": "quantitative"
      }
    },
    "height": 150,
    "width": 150
  }
}
```

Should the schema be changed such that the ``"data"`` property is required within ``TopLevel<FacetSpec>``? I can't seem to create any valid spec that doesn't have a top-level data property.

**Comment by domoritz** [comment]
For this specific case, yes. Any other composition operator does not necessarily have to have data at the top level. Adding this was  abit tricky but it makes our types better as well.
