### ISSUE TITLE
circles not showing up in legend of Seattle weather example

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#3494]
In the recent example:
https://bl.ocks.org/jakevdp/5d1915d808d3d91ce86f0bc3ca066d48
I do not see the circles showing up in the legend, for the precipitation portion. (when viewed on bl.ocks.org)
![image](https://user-images.githubusercontent.com/1798497/37207510-5d74892c-236b-11e8-9150-2c40244de511.png)

However, when I view the example in altair with jupyter lab I do see the precipitation circles:
![image](https://user-images.githubusercontent.com/1798497/37207568-93d37794-236b-11e8-9f5a-7cccbe41a461.png)

If I then do the 'open in Vega Editor' from jupyter lab, the circles are not in the legend anymore.

I have been having lots of issues with the interactive examples in jupyter lab
https://github.com/altair-viz/altair/issues/538

But since this issue was in external viewers I thought I would mention it to see if others are having a similar issue.

**Comment by domoritz** [comment]
That sounds like a regression. Can you find out what versions of Vega-Lite your Altair is using? If possible, I'd also love to see the Vega output of these two cases.

**Comment by eitanlees** [comment]
I too do not see the circles for the precipitation legend. 

When I make a selection they appear but if there is no selection they are missing. 

The behavior is the same in both jupyter lab with altair as well as on bl.ocks.org.

**Comment by afonit** [comment]
@domoritz Jake replied that this depends on the renderer used by jupyter lab's vega-lite plugin.
Here is the discussion:
https://github.com/altair-viz/altair/issues/563

I think I read somewhere that you were working on getting that merged into jupyter lab proper?  I ask because I have been trying to find the source for that to file some other related bugs with the renderer that I have found in a windows environment (works fine on linux though) where the interactive examples don't work completely. https://github.com/altair-viz/altair/issues/538

**Comment by domoritz** [comment]
Looks like this works in master. Will confirm with the next release. 

<img width="764" alt="screen shot 2018-03-10 at 23 02 07" src="https://user-images.githubusercontent.com/589034/37250689-24b7b972-24b7-11e8-80bb-99c28e377ac2.png">

**Comment by kanitw** [comment]
I can confirm that this works fine in master.
