### ISSUE TITLE
Ordering z-index of point-based symbols

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3495]
When creating a line chart, the order in which vertices are joined can be controlled by specifying `order` within the encoding:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"x": 60, "y": 45, "cat": "a"},
      {"x": 40, "y": 50, "cat": "b"},
      {"x": 50, "y": 65, "cat": "c"},
      {"x": 99, "y": 99, "cat": "d"}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "y", "type": "quantitative"},
    "order": {"field": "x", "type": "quantitative"}
  }
}
```

However, if point-based symbols are used (`point`, `circle` etc.), the z-order of overlapping symbols is not affected by `order`, but instead the ordering of the data values in the specification:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"x": 60, "y": 45, "cat": "a"},
      {"x": 40, "y": 50, "cat": "b"},
      {"x": 50, "y": 65, "cat": "c"},
      {"x": 99, "y": 99, "cat": "d"}
    ]
  },
 "mark": "circle",
  "encoding": {
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "y", "type": "quantitative"},
    "order": {"field": "x", "type": "quantitative"},
    "color": {"field": "cat", "type": "nominal"},
    "opacity": {"value": 1},
    "size": {"value": 3000}
  }
}
```

<img width="317" alt="overlap" src="https://user-images.githubusercontent.com/1846999/37212567-3f056ba0-23a7-11e8-9ed0-1eef1194a9b6.png">

Ignoring `order` in favour of data table ordering seems counterintuitive behaviour and violates the principle of _representation invariance_ (Kindlmann & Scheidegger 2014).

While one may argue that good design should avoid overlapping point symbols, there are many valid examples of partial overlapping, especially now VL has geo capabilities allowing proportional symbol maps.

Would it be possible to make z-index dependent on `order` if specified?

**Comment by kanitw** [comment]
Sure.  You just found an unimplemented TODO in our codebase.  :)

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3499.

Blue is now upfront:

![image](https://user-images.githubusercontent.com/111269/37244598-558e3bb0-2459-11e8-8e87-f266059d0570.png)
