### ISSUE TITLE
axis title behaviour appears buggy when switching from 2.1.3 to 2.2.0 for layer use cases

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3510]
Between version 2.1.3 and 2.2.0 of vega-lite, I have noticed a change in axis title behaviour when layering, in particular when setting `title` to `""` or `null` in combination with `domain`, `labels` and `ticks` set to `false`. 

Here is a __spec that does not work__:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "layer": [
    {
      "mark": "area",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal",
          "timeUnit": "year"
        },
        "y": {
          "aggregate": "ci0",
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "axis": {"domain": false, "labels": false, "ticks":false, "title": null}
        },
        "y2": {
          "aggregate": "ci1",
          "field": "Miles_per_Gallon",
          "type": "quantitative"
        },
        "opacity": {"value": 0.3}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal",
          "timeUnit": "year"
        },
        "y": {
          "aggregate": "mean",
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "axis": {"title": null}
        }
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/12123506/37253521-2059797a-2533-11e8-9a71-f001f5e92082.png)

Here a __spec that does work__:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "layer": [
    {
      "mark": "area",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal",
          "timeUnit": "year"
        },
        "y": {
          "aggregate": "ci0",
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "axis": {"ticks":false, "title": null}
        },
        "y2": {
          "aggregate": "ci1",
          "field": "Miles_per_Gallon",
          "type": "quantitative"
        },
        "opacity": {"value": 0.3}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal",
          "timeUnit": "year"
        },
        "y": {
          "aggregate": "mean",
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "axis": {"domain": false, "labels": false, "title": null}
        }
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/12123506/37253528-4894cade-2533-11e8-80e7-b300abb57de2.png)

I've checked the release documentation and noticed:

![image](https://user-images.githubusercontent.com/12123506/37253429-edbfbc5a-2531-11e8-9794-040d0dfeb8e1.png)

Does this have anything to do with it ? Or what does this refer to and where would it be documented ?

**Comment by domoritz** [comment]
That's a bug. Thank you for reporting it. We will fix it asap.

**Comment by domoritz** [comment]
This does seem to work on master. But you're right, in the deployed editor, I also get `Cannot read property 'getWithExplicit' of undefined`. 

<img width="232" alt="screen shot 2018-03-11 at 11 12 36" src="https://user-images.githubusercontent.com/589034/37256811-2acd6dc8-251d-11e8-945d-e9891997cbbc.png">

**Comment by kanitw** [comment]
It works in master because I just redesign axis logic to fix other problem and it appears to fix this problem too.
