### ISSUE TITLE
Support mark as an array as a way to repeat multiple layers with different marks?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3516]
```
{
       mark: ['line', 'point'] ,
       encoding: {
          x: {field: 'date, ...}
          y: {field: 'value', ...},
       }
}
```

Forked from https://github.com/vega/vega-lite/issues/1274#issuecomment-365461548

Example to update:

- [ ] layer_falkensee

**Comment by kanitw** [comment]
Note: from thinking about overlay config -- one thing we have to do for this macro is to ensure all the layers get the same stack offset applied.

**Comment by domoritz** [comment]
Should we do this for v5? I think this may actually be easier to understand than the mark object where line has a point property.

**Comment by kanitw** [comment]
> Should we do this for v5? I think this may actually be easier to understand than the mark object where line has a point property. 

This might not solve the issue that point has to be grouped with line in a layer-facet though.  Plus we need some backward compatibility.

**Comment by domoritz** [comment]
Or we close this issue and say that instead we just do (which we already support):

```
{
       layer: [{mark: 'line'}, {mark: 'point'}],
       encoding: {
          x: {field: 'date, ...}
          y: {field: 'value', ...},
       }
}
```

**Comment by kanitw** [comment]
Yeah, let's close this one until we find a convincing use case.
