### ISSUE TITLE
A way to use argmin/argmax inside encoding

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3520]
Argmin/argmax won't work in `encoding` as it involves two fields.  We need better syntax for this.

**Comment by kanitw** [comment]
It's not just that.  You normally want to calculate argmin / argmax of one field, but refer to another field.

**Comment by domoritz** [comment]
https://vega.github.io/vega/docs/transforms/flatten/ could be useful here. If we see that a field comes from argmin/argmx, we can flatten it.

**Comment by kanitw** [comment]
That's insufficient.  For argmin and argmax to be used in encoding, we need two `field`s -- one is the field you are optimizing, another is the field that you want the value from.  

For example, we might need something like this syntax

```
x: {"aggregate": {"argmin": "a"}, "field": "b", ...} 
```
to encode the `b` value of the data point that has the min of `a`.

**Comment by kanitw** [comment]
To provide more concrete [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxgSFZdMWwtCtIC33lFFQBfdQhIPF0Q2DTdVAaAbVAIHvYPBr7WZFUoFMZkMU0GyABZSJ0AfVjdXYBxdATlNSh0WA3ppV3UQmpIDS6Jych0ampdYTxkMY0kzA1W4hA22WoGAAHhdIMtVutTGZ4PBVrZrMZYVdwbpIegobt0CjIB1AWAALrdd7fXKEdgATzGkFu90esJZD2ou2QoUg5JelNKGF0AGsNgEPHgSj0efBuJoPE8qmTIIyqnCVmscXiCUT4HQABLpPwBVy2NS9emxDYAR1YISMeAxVBJVJ6MPVtxuHiUyHWiw1CO9d05FrwVv+pjtDuYzv+XRVUIATA1qvCtaYOY9ubzSRBSaSgA) 

```
{
  "data": {"url": "data/cars.json"},
  "transform": [{
    "bin": true, "field": "Miles_per_Gallon", "as": "bin_mpg"
  },{
    "aggregate": [
      {"op": "argmax", "field": "Acceleration", "as": "argmax_acc"}
    ],
    "groupby": ["bin_mpg", "bin_mpg_end"]
  }],
  "mark": "point",
  "encoding": {
    "y": {"field": "argmax_acc.Horsepower","type": "quantitative"},
    "x": {"bin": "binned", "field": "bin_mpg","type": "quantitative"},
    "x2": {"field": "bin_mpg_end"}
  }
}
```

should become just:

```
{
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "y": {"aggregate": {"argmax": "Acceleration"}, "field": "Horsepower", "type": "quantitative"},
    "x": {"bin": true, "field": "Miles_per_Gallon", "type": "quantitative"}
  }
}
```

@jheer @arvind @domoritz  -- any opinion?

**Comment by domoritz** [comment]
I think the suggestion makes a lot of sense.

**Comment by jheer** [comment]
This makes sense from a pure JSON perspective, but could be awkward from an Altair or Vega-Lite API perspective. In addition to some potential implementation headaches, it's pretty confusing what `vl.argmin('Horsepower', 'Acceleration')` means... any thoughts on what a proper API should look like, given that we already have `op(field)` as a standard representation?

**Comment by jheer** [comment]
I guess one idea would be to have `argmin` and `argmax` exists as operations with different semantics, such that `vl.argmin('Acceleration').field('Horsepower')` makes sense in a way that `vl.sum('foo').field('foo')` does not. I think that a separate argmin/argmax design would be easy enough to add to the Vega-Lite API, too.

**Comment by kanitw** [comment]
lol you beat me to it.  :) 

I've `vl.argmin('Acceleration').field('Horsepower')` in the comment box right here. :p

**Comment by kanitw** [comment]
Another question would be what would be an appropriate default title. 

Currently I have `Horsepower of argmin(Acceleration)` for 

`vl.argmin('Acceleration').field('Horsepower')` / 
`{"aggregate": {"argmin": "Acceleration"}, "field": "Horsepower", ...}`

**Comment by kanitw** [comment]
(But it's a bit awkward that we won't really use the form `f(a)` in other title by default anymore.)

**Comment by domoritz** [comment]
"Horsepower of the record with the smallest Acceleration" or something slightly shorter.

**Comment by jheer** [comment]
"Horsepower for minimum Acceleration"?

Something like "X corresponding to minimum/maximum Y" is perhaps clearer but likely too long.

**Comment by kanitw** [comment]
"Horsepower for min Acceleration" vs "Horsepower for minimum Acceleration"?

Min is shorter and a bit consistent with min in the "argmin" op.  We also say "Min of X" for min(x),  but minimum is obviously clearer.

Right now I'm leaning towards just "min" because title shouldn't be long by default.

**Comment by kanitw** [comment]
We now have a PR (https://github.com/vega/vega-lite/pull/4794.)

Let's discuss more about the title format in https://github.com/vega/vega-lite/pull/4794..
