### ISSUE TITLE
Offset vs dx

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3523]
What's the difference between https://vega.github.io/vega-lite/docs/mark.html#example-offsetting-labels and offsets in https://github.com/vega/vega-lite/pull/3367?

**Comment by kanitw** [comment]
dx = `dx` encoding channel in Vega, which is only for text and is affected by `angle`. 

offset = `offset` in field reference, which is usable for any marks and is *not* affected by angle.

**Comment by domoritz** [comment]
Does offset work for text?

**Comment by kanitw** [comment]
Yes, but you still need dx, dy if you want to offset along the rotated axis.

**Comment by domoritz** [comment]
I don't seem to get it to work

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "transform": [{
    "calculate": "datum.Origin[0]",
    "as": "OriginInitial"
  }],
  "mark": {
    "type": "text",
    "yOffset": 100
  },
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal"},
    "text": {"field": "OriginInitial", "type": "nominal"}
  }
}
```

<img width="880" alt="screen shot 2018-03-11 at 21 51 47" src="https://user-images.githubusercontent.com/589034/37266282-774eecc2-2576-11e8-879c-12be896cf808.png">

**Comment by kanitw** [comment]
offset is in annotation branch, not in master
