### ISSUE TITLE
line shape change?

### ISSUE THREAD

**Issue by Vxider** [vega/vega-lite#3530]
Many paper require to use black and white graphs, can I change line shape in vega-lite like the figure below?
<img width="704" alt="2018-03-12 16 34 14" src="https://user-images.githubusercontent.com/6134315/37273168-ec943684-2613-11e8-852e-5bf88e322dc4.png">

**Comment by kanitw** [comment]
Yep.  You can add another layer with mark = point and `shape`.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "layer": [{
    "mark": {"type": "line", "color": "black"},
    "encoding": {
      "x": {"field": "Year","type": "temporal"},
      "y": { "aggregate":"mean", "field": "Miles_per_Gallon","type": "quantitative"},
      "detail": {"field": "Origin", "type": "nominal"}
    }
  },{
    "mark": {"type": "point", "color": "black"},
    "encoding": {
      "x": {"field": "Year","type": "temporal"},
      "y": { "aggregate":"mean", "field": "Miles_per_Gallon","type": "quantitative"},
      "shape": {"field": "Origin", "type": "nominal"}
    }
  }]
}
```

![image](https://user-images.githubusercontent.com/111269/37297738-a0f378b2-25db-11e8-8f49-d7038c21b1fe.png)



We probably will add a macro in the future that if you add `shape` to line, we will automatically add `point` layer for you.

**Comment by Vxider** [comment]
Thanks for your help. In my case, there are about 300 data, and the output will like the figure below
<img width="56" alt="2018-03-13 09 29 26" src="https://user-images.githubusercontent.com/6134315/37317646-0eaa9686-26a1-11e8-8ce0-bb6035ae04a2.png">
Can I use sometings like  [Sample Transform](https://vega.github.io/vega/docs/transforms/sample/) in `vega`? I have found [#477](https://github.com/vega/vega-lite/issues/477) but I cannot found relevant information in  Document.

**Comment by kanitw** [comment]
In that case, we plan to add `strokeDash` as an encoding channel in the future (https://github.com/vega/vega-lite/issues/1855).  

For now, you might consider modifying output Vega specs and add `strokeDash` in the Vega spec.

**Comment by Vxider** [comment]
Sorry, I may not described clearly. In my data file, there are more than 300 points, if I use multi-layer, every point in data file will generate a shape on figure, so the figure will like what I mentioned before. `strokeDash` in vega cannot add shape on lines.

**Comment by Vxider** [comment]
I am trying to use `strokeDash` in `vega`, but I found that strokeDash for `shape` will like the figure below.
<img width="727" alt="2018-03-16 18 01 56" src="https://user-images.githubusercontent.com/6134315/37514949-489ef422-2944-11e8-8ebc-55dc9b72ee8a.png">
The strokeDash is in circle shape but not reduce the number of shape.
The vega code is
```
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 500,
  "height": 200,
  "padding": 5,

  "signals": [
    {
      "name": "interpolate",
      "value": "linear",
      "bind": {
        "input": "select",
        "options": [
          "basis",
          "cardinal",
          "catmull-rom",
          "linear",
          "monotone",
          "natural",
          "step",
          "step-after",
          "step-before"
        ]
      }
    }
  ],

  "data": [
    {
      "name": "table",
      "values": [
        {"x": 0, "y": 28, "c":0}, {"x": 0, "y": 20, "c":1},
        {"x": 1, "y": 43, "c":0}, {"x": 1, "y": 35, "c":1},
        {"x": 2, "y": 81, "c":0}, {"x": 2, "y": 10, "c":1},
        {"x": 3, "y": 19, "c":0}, {"x": 3, "y": 15, "c":1},
        {"x": 4, "y": 52, "c":0}, {"x": 4, "y": 48, "c":1},
        {"x": 5, "y": 24, "c":0}, {"x": 5, "y": 28, "c":1},
        {"x": 6, "y": 87, "c":0}, {"x": 6, "y": 66, "c":1},
        {"x": 7, "y": 17, "c":0}, {"x": 7, "y": 27, "c":1},
        {"x": 8, "y": 68, "c":0}, {"x": 8, "y": 16, "c":1},
        {"x": 9, "y": 49, "c":0}, {"x": 9, "y": 25, "c":1}
      ]
    }
  ],

  "scales": [
    {
      "name": "x",
      "type": "point",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "y"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category",
      "domain": {"data": "table", "field": "c"}
    }
  ],

  "axes": [
    {"orient": "bottom", "scale": "x"},
    {"orient": "left", "scale": "y"}
  ],

  "marks": [
    {
      "type": "group",
      "from": {
        "facet": {
          "name": "series",
          "data": "table",
          "groupby": "c"
        }
      },
      "marks": [
        {
          "type": "line",
          "from": {"data": "series"},
          "encode": {
            "update": {
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"},
              "stroke": {"scale": "color", "field": "c"},
              "strokeWidth": {"value": 2}
            },
            "hover": {
              "fillOpacity": {"value": 0.5}
            }
          }
        },
        {
          "type": "symbol",
          "from": {"data": "series"},
          "encode": {
            "update": {
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"},
              "shape":{"value": "circle"},
              "strokeDash": {"value": [5, 5]},
              "stroke": {"scale": "color", "field": "c"},
              "strokeWidth": {"value": 2}
            },
            "hover": {
              "fillOpacity": {"value": 0.5}
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by kanitw** [comment]
Try using stroke dash with the line marks and remove the circle/point marks

**Comment by domoritz** [comment]
Try to apply stroke dash to the line, not the shape.

**Comment by Vxider** [comment]
Thank you for your help. I finally use matplotlib to generate my figure.

**Comment by domoritz** [comment]
Oh no, that wasn't what we are hoping the outcome to be. Can you tell us where you got stuck so that we can improve the API and documentation?

**Comment by domoritz** [comment]
Thank you for the explanations. We will add the feature in #1855.

**Comment by kanitw** [comment]
Yeah, @NeelMohapatra is working on it so I'd expect it to come pretty soon!
