### ISSUE TITLE
zindex appears broken as of 2.3.x

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3537]
As of version 2.3.x, [`zindex`](https://vega.github.io/vega-lite/docs/axis.html#general) no longer works as expected. 

In the following example spec, it would be expected that the (purposefully) black grid lines would be in front of the bar mark. No matter whether one puts 0 or 1, nothing happens.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "axis":{"zindex":1}}
  },
  "config": {
    "axis": {
      "gridColor": "black"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/37334161-66c53a6a-26ab-11e8-9dc8-7819bae6c79a.png)

**Comment by domoritz** [comment]
Thanks for the bug report. There was a change in how we sort non path marks in https://github.com/vega/vega-lite/pull/3499. Can you set the z-index to 1000 to see whether that works?

**Comment by domoritz** [comment]
Hmm, never mind, the zindex is being ignored completely.

**Comment by kanitw** [comment]
Thanks for reporting!

@domoritz This is zindex for axis— i think i made a bug when i fix axis component structure. Will try to fix it soon

**Comment by g3o2** [comment]
Thank you, indeed the compiled Vega spec shows a zero `zindex` value, no matter the value set in the vegalite spec.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3539
