### ISSUE TITLE
 Binning’s label should be a range

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#354]
- [ ] add custom scale for binning
- [ ] use the scale for axis 
- [ ] use the scale for legend label
```
setter(def, ['properties', 'labels', 'text', 'scale’], …)
```

**Comment by kanitw** [comment]
An alternative is to use have linear and ordinal scale on top of each other so ticks fall on the borders between bins.

(See http://bl.ocks.org/mbostock/3048450, for example)

**Comment by domoritz** [comment]
> An alternative is to use have linear and ordinal scale on top of each other so ticks fall on the borders between bins.

Even better

**Comment by kanitw** [comment]
> Add a scale for labels and somehow use it in the text property of the axis? 

This is actually not a bad idea, so I’m re-opening #221 as we can do that later.

**Comment by kanitw** [comment]
Note that this 

>  modify vega's bin transform to add range instead of the min value of the bin

actually doesn’t work because then we can’t map the range to color scale.

**Comment by kanitw** [comment]
#693 solved this issue in a better way. so I’m closing this.
