### ISSUE TITLE
How to show all same field values of the selected(filtered) items in a tooltip?  

### ISSUE THREAD

**Issue by swaydeng** [vega/vega-lite#3541]
How to show all same field values of the selected(filtered) items in a tooltip?  

like this example:
[Multi Series Line Chart with Tooltips](https://vega.github.io/vega-lite/examples/interactive_multi_line_tooltip.html)

As mouse move, I want to show all price infos of the selected(filtered) stocks in the tooltip. anyone knows how to do that?

tooltip:
APPL: 88.05
GOOG: 127.85
...

**Comment by domoritz** [comment]
Interesting idea! Unfortunately, that's not possible in Vega-Lite at the moment. I recommend generating a spec with Vega-Lite and then modifying the generated Vega to do what you want.

**Comment by kanitw** [comment]
I think @ericsoco is trying to modify vega-lite-tooltip to support that?  Not sure how far it goes yet.
