### ISSUE TITLE
Incorrect legend for combined fill, stroke and color encodings

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3543]
Looking at the new fill and stroke encodings, I think there is an inconsistency in legend generation. If marks are encoded with both the `color` and `fill` channels, `fill` takes precedence (as indicated in the documentation). However, the legend shows both the color (which should be ignored) and fill encodings:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200,
  "height": 200,
  "data": {
    "values": [
      { "x": 10, "y": 1, "cat": "a" },
      { "x": 20, "y": 2, "cat": "b" },
      { "x": 30, "y": 3, "cat": "c" },
      { "x": 36, "y": 4, "cat": "d" }
    ]
  },
  "encoding": {
    "x":     { "field": "x", "type": "quantitative" },
    "y":     { "field": "y", "type": "quantitative" },
    "size":  { "value": 2000 },
    "color": { "field": "cat", "type": "nominal" },
    "fill":  { "field": "y", "type": "ordinal" }
  },
  "mark": { "type": "circle", "stroke": "black" }
}
```

<img width="312" alt="color and fill legend" src="https://user-images.githubusercontent.com/1846999/37425126-36215f82-27ba-11e8-9809-2d2558b3c8b3.png">

This also applies if `fill` is set to a constant, this time (correctly) not showing the fill legend at all, but incorrectly showing the color legend:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200,
  "height": 200,
  "data": {
    "values": [
      { "x": 10, "y": 1, "cat": "a" },
      { "x": 20, "y": 2, "cat": "b" },
      { "x": 30, "y": 3, "cat": "c" },
      { "x": 36, "y": 4, "cat": "d" }
    ]
  },
  "encoding": {
    "x":     { "field": "x", "type": "quantitative" },
    "y":     { "field": "y", "type": "quantitative" },
    "size":  { "value": 2000 },
    "color": { "field": "cat", "type": "nominal" },
    "fill":  { "value": "red" }
  },
  "mark": { "type": "circle", "stroke": "black" }
}
```

<img width="308" alt="color and constant fill" src="https://user-images.githubusercontent.com/1846999/37425361-fff54b8e-27ba-11e8-8fe5-f5d29aed9b16.png">

As a workaround one can obviously remove the color encoding entirely, but I think it would be preferable to follow the (consistent) behaviour of the `stroke` rather than `fill` channel:

<img width="306" alt="screen shot 2018-03-14 at 19 14 37" src="https://user-images.githubusercontent.com/1846999/37425665-0fff24ea-27bc-11e8-9e64-b7d5e7ed4a66.png">

As a more minor inconsistency, when encoding the `stroke` channel the stroke is not applied to the legend symbols when it is a constant:

<img width="309" alt="screen shot 2018-03-14 at 19 15 02" src="https://user-images.githubusercontent.com/1846999/37425688-2223c928-27bc-11e8-9cfb-f3f794441692.png">

**Comment by domoritz** [comment]
This may be related to https://github.com/vega/vega-lite/issues/3463.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3545.    

We will ignore color if fill/stroke is specified.  This way there won't be "bad specs" that uses color with fill or use color with stroke.   (Either color-only or fill and/or stroke will be allowed as mark property and encoding.)
