### ISSUE TITLE
Problem with concatenation of more than two projected maps 

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3544]
_(I know the team are already aware of this, but am documenting it as an issue to make tracking easier)_

If more than two projected maps are added to a concatenation, the third and any subsequent are not projected. The following minimal example shows the problem, noting that the three specs added to `hconcat` are identical.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "hconcat": [
    {
      "width": 100,
      "height": 100,
      "data": {
        "url": "data/graticule.json",
        "format": { "type": "topojson", "feature": "graticule" }
      },
      "projection": { "type": "orthographic" },
      "mark": { "type": "geoshape", "filled": false }
    },
     {
      "width": 100,
      "height": 100,
      "data": {
        "url": "data/graticule.json",
        "format": { "type": "topojson", "feature": "graticule" }
      },
      "projection": { "type": "orthographic" },
      "mark": { "type": "geoshape", "filled": false }
    },
     {
      "width": 100,
      "height": 100,
      "data": {
        "url": "data/graticule.json",
        "format": { "type": "topojson", "feature": "graticule" }
      },
      "projection": { "type": "orthographic" },
      "mark": { "type": "geoshape", "filled": false }
    }
  ]
}
```

<img width="606" alt="screen shot 2018-03-14 at 23 11 43" src="https://user-images.githubusercontent.com/1846999/37435888-24044efe-27dd-11e8-829c-f456384e18b5.png">

**Comment by jakevdp** [comment]
I ran into this today as well.

**Comment by jimmywan** [comment]
Also ran into this problem. Any updates or suggested workaround?

**Comment by domoritz** [comment]
We haven't had time to look at this yet. If someone has time, please help us out.

**Comment by jheer** [comment]
Is this issue still an active problem? If so, I might be able to take a closer look while I work on related projection issues. (I note that it is not even flagged as a bug, but very much looks like one!)

**Comment by jwoLondon** [comment]
It remains a problem for me, so great if you were able to look at this.
