### ISSUE TITLE
Please add example for Pie/Doughnut

### ISSUE THREAD

**Issue by king612** [vega/vega-lite#3547]
Please add example for Pie/Doughnut to the gallery.  Thanks!

**Comment by kanitw** [comment]
We currently do not support pie and donut or polar coordinate.  As they are generally not ideal visual encodings, we didn't prioritize implementing them yet.  Oftentimes, you can create a normalized stacked bar chart to visualize the same data in a more efficient way. 

Please track the progress on https://github.com/vega/vega-lite/issues/408.

If you need them soon, feel free to contribute too. (Please start from proposing a design.)

**Comment by jwoLondon** [comment]
It is possible, but not quite as straightforward as Cartesian layouts:

<img width="863" alt="screen shot 2018-03-16 at 23 12 59" src="https://user-images.githubusercontent.com/1846999/37548581-e12815da-2970-11e8-8652-7f2bc6b35ef8.png">

See my comment in #408 for details.
