### ISSUE TITLE
Consider bringing back fieldDef.title?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3548]
We originally remove `title` and `format` from `FieldDef` in 2.0 as we used to implement it as internal property of field def, so it is a bit hard to maintain.   Also, removing it means we have only one way of doing things. 

Plus, there are also other common properties between  axis/legend/header. So if we make `title` available, there is a question why we don't support other common properties like `labels`, `format`, `values`.  (Doing so will explode number of properties in fieldDef though -- so we shouldn't really do that.)

That said, having `title` in fieldDef makes it easy to change encoding channel without having to change between axis/legend/header.  Altair users are discussing that this introduce inconsistency for specifying `title` https://github.com/altair-viz/altair/issues/585.

One possible argument is that supporting `title` ~~and `format`~~ in fieldDef may make sense since they are properties of the field that users define.  (To enable `labels` or not is not a property of the field.) 

Note that implementation wise, we can make this quite easy to maintain by introducing it as a macro in the `normalize` stage.  This way we can keep the internal compiler code the same. 

(I'm not 100% convinced that we should bring it back, but I think probably yes -- so we should at least discuss and consider.)

cc: @jakevdp @malramsay64

**Comment by domoritz** [comment]
I'm in favor of this. We need to discuss what the precedence is when there is a title on the fielddef and the axis, though.

This change is worth discussing in a broader context with @arvind and @jheer.

**Comment by kanitw** [comment]
axis / legend / header should have higher precedence because it's more localized.  
That said, it's not a big deal since people shouldn't use both anyway.

**Comment by kanitw** [comment]
Thinking more — i think format better sray in axis/legend/header since it only affects labels, not the actual data encoded.

Title is a bit more like metadata?

**Comment by kanitw** [comment]
I think I'll just do this on the plan unless there is any objection

**Comment by domoritz** [comment]
Sounds good but make sure to explain in the docs why we only do this for title.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3620.  

I think that explanation is a bit too much.  If you disagree, feel free to do it in a way that's not overdoing in a separate PR.
