### ISSUE TITLE
Tooltip customization

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3560]
Related to: https://github.com/altair-viz/altair/issues/240#issuecomment-374711742

> - What if one wants to include some form of custom formatted string in the tooltip?

- [ ] We need a syntax that generates Vega `signal` value ref

> - What if one doesn't want tooltips shown for a given mark?

- [ ] Tooltip plugin should read if the `tooltip` channel is `''` or `null`

> - What if one wants only a subset of fields shown in the tooltip?

- [ ] This one we need a new mechanism

**Comment by eibanez** [comment]
Related to https://github.com/vega/vega-tooltip/issues/148

**Comment by eibanez** [comment]
Would it be worth merging the vega-tooltip options into the vega-lite scheme?

`null` to skip the tooltip makes most sense to me.

**Comment by domoritz** [comment]
We will wait for the discussion in https://github.com/altair-viz/altair/issues/240. If we want to be agnostic about the specific tooltip library, we probably won't just merge the tooltip options into Vega and Vega-Lite.

**Comment by kanitw** [comment]
I don't think we gonna add all vega-tooltip options to the vega-lite scheme as some are very specific to vega-tooltip.  Plus, some properties there expect a function, which is not applicable to JSON format. 

But we will probably need to add some generally applicable properties to Vega-Lite as `vega-tooltip` can't support view-specific customization (or mark-level customization for Vega) without those customization properties at the view-level.

**Comment by eibanez** [comment]
I wasn't advocating for that. But the way the `fields` entries in the tooltip spec are defined would cover most of what you want.

There is already some overlap between that piece of the vega-tooltip spec (e.g., `formatType`) that could be simplified.

**Comment by kanitw** [comment]
From conversation in https://github.com/vega/vega/issues/1198,  we can support "subset of fields shown in the tooltip" by allowing the tooltip to accept an array of fieldDefs.  

Then we can generate output `signal` that is basically is an object so the output tooltip can be a table.

**Comment by domoritz** [comment]
https://github.com/vega/vega/issues/1198 is released in Vega 3.3
