### ISSUE TITLE
Consider scale zero rule based on orientation?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3562]
From https://github.com/altair-viz/altair/issues/619, the  base axis of bar have zero=true by default too.

For example: 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 2003,"b": 28}, 
      {"a": 2005,"b": 55}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "quantitative"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/37692067-99334e06-2c73-11e8-96d0-6615523eeb01.png)

Having x-scale's `zero=false` actually make more sense:

![image](https://user-images.githubusercontent.com/111269/37692080-ad2316f8-2c73-11e8-9201-7b298fdf439e.png)

Same for line

![image](https://user-images.githubusercontent.com/111269/37692196-623c5d06-2c74-11e8-8b4e-c88c7d7879e2.png)

We could make scale zero depends on mark type and orient too.

However, I'm not 100% sure if we should do this since `point` will be inconsistent with `bar`/`line` since `point` has no orientation so this rule won't automatically make point's x-scale zero=false. 

![image](https://user-images.githubusercontent.com/111269/37692155-1f018de0-2c74-11e8-988f-c042dabf3ed7.png)

Note that if users use type=temporal and force `"parse": {"a": "date:'%Y'"}`, the plot will [work correctly](https://github.com/altair-viz/altair/issues/619#issuecomment-374817930).  However, new users might not discover the `parse` so good default here is still useful.

**Comment by domoritz** [comment]
I think this makes sense. I actually implemented this in [Draco](https://github.com/domoritz/draco). Setting zero true is most important for the main positional channel of bar and area charts.

**Comment by kanitw** [comment]
Note that the proposal above keep zero=true for both axis for point/rect/other marks with no orient(atation) -- what do you think about that part?

I'm also curious what's the use case that you implement in Draco.

**Comment by domoritz** [comment]
> Note that the proposal above keep zero=true for both axis for point/rect/other marks with no orient(atation) -- what do you think about that part?

Makes sense to me.

> I'm also curious what's the use case that you implement in Draco.

Mostly line charts and area charts. I wanted to automatically add zero but found it only useful for the main axis. I also added a soft constraint to prefer not to use zero when the data is clustered very far away from zero. For example `[1001, 998, 1002, 1000, 997]` is all very far away from zero and it might make sense not to use zero (but also as a consequence not use bar or area for the chart).

**Comment by g3o2** [comment]
IMO the requested solution for the examples above is not reasonable, for x could be easily encoded as ordinal and not quantitative. Would there be any realistic use cases where quantitative scales should have zero false?

**Comment by domoritz** [comment]
Zeronis recommended for the main axis of bar and area charts. However, in a line chart it usually doesn't make sense to include zero on the dimension axis. Switching to ordinal would mean that we could hide missing data.

**Comment by g3o2** [comment]
I can agree with the `zero: false` recommendation for a unit spec having mark `line`. 

How would this be handled in layered specs ? Which `zero` setting of which mark would be prevail in case of conflict ? Typical examples of such layering: `bar` and `line` and `point` / `circle` and `line`, etc.

**Comment by kanitw** [comment]
>  Last but not least, adding scale: { zero: false } to the spec is practically a zero overhead solution.

For people who know the tool well, this is small epsilon but for novices, it will take them sometimes to discover this option.


> zero: true is a common recommendation in the visualization literature. 

Yes, for quantatitive field that have a "ratio" [level of measurement](https://en.wikipedia.org/wiki/Level_of_measurement). 


> Would there be any realistic use cases where quantitative scales should have zero false?  (From older, edited comment)

However, it is also uncommon for people to use two "ratio" level of measurement with bars or line.  
Likely one of them is "interval" level of measurement (like time value), which zero=true doesn't make sense.   

> How would this be handled in layered specs ? Which zero setting of which mark would be prevail in case of conflict ? Typical examples of such layering: bar and line and point / circle and line, etc.

Great point!  For bar and line, they use the same rule, so no conflict.

For line and point, right now we resolve by using lower (first) layer.   Typically, you should place point over lines, so this sensible case zero=false will be preserved.   If you place point below layer though, this case will currently be problematic.  However, we can fix this by having a resolution rule that false has higher precedence than true as doing nothing = true.

**Comment by g3o2** [comment]
one more question, how can vega-lite tell the quantitative dimension from the quantitative measure?

**Comment by domoritz** [comment]
> one more question, how can vega-lite tell the quantitative dimension from the quantitative measure?

We can infer that when an aggregation is used. The dimension/measure distinction sort of doesn't matter for scatterplots. For line charts, by default, we assume that a chart in vertical (independent variable on x).

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3568
