### ISSUE TITLE
Print actual text

### ISSUE THREAD

**Issue by chuski92** [vega/vega-lite#3565]
Hello.
Does exists any way that I can print the actual text of one field?
For example I have a field that cointains "Up" and "Down" showing the status of our network. I want to show that state, and if it is possible changing colors. But I don't find the way to do that.
I am using a vega-lite kibana plugin and I don't know why kibana doesn't let you show text fields because grafana does...

**Comment by domoritz** [comment]
Can you use the text channel with a text mark?

**Comment by eibanez** [comment]
Looks like a question for the kibana developers...

**Comment by domoritz** [comment]
Pinging @nyurik

**Comment by nyurik** [comment]
@chuski92 take a look at https://www.elastic.co/blog/custom-vega-visualizations-in-kibana -- i show how to draw text from Elasticsearch data.  Or you might want to draw it using text channel, e.g. https://vega.github.io/vega-lite/docs/text.html .  Note that Vega is a generic language to draw data visualizations. Pure Vega has no notion of Kibana / Elasticsearch.  It simply allows you to create a converter from any data into a visualization.

**Comment by kanitw** [comment]
Thanks @nyurik

**Comment by chuski92** [comment]
Thank you very much @nyurik and @domoritz
