### ISSUE TITLE
Fix vega to support spaces in variable name

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#358]
Look at `vg.field` (in the top-level `_package.js` file). 

Ref #357

**Comment by kanitw** [comment]
should we discuss this a bit with folks

**Comment by kanitw** [comment]
I start wondering if using backslash in front of space works

**Comment by jheer** [comment]
Note that Vega now uses an updated datalib.field parser that supports both dot (foo.bar) and bracket (foo['bar']) notation. That might be useful here.

**Comment by domoritz** [comment]
In genreal, we seems to have issues with variable names with . and spaces.

**Comment by domoritz** [comment]
https://mothereff.in/js-variables
