### ISSUE TITLE
TopLevelSpec missing from schema

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#3582]
The [release notes](https://github.com/vega/vega-lite/releases/tag/v2.3.0) for v2.3.0 say that ``TopLevelExtendedSpec`` was renamed to ``TopLevelSpec`` in the JSON schema, but in fact it just seems to be gone, i.e. I don't see anything for ``TopLevelSpec`` in the JSON schema.

Which is a problem for [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl) because that is the starting point for us :)

**Comment by davidanthoff** [comment]
Thanks! @domoritz any chance you could release a new point release with this relatively soon? Probably easier for me to just wait until that rather than work around this in VegaLite.jl (which is slowly, slowly coming together).

**Comment by domoritz** [comment]
It's fixed in master and will be included in the next release.
