### ISSUE TITLE
SVG export does not work in the online Vega editor

### ISSUE THREAD

**Issue by ralienpp** [vega/vega-lite#3603]
I am not sure this is the most appropriate project for this issue, but this is where the link on the site itself brought me to.

This can be replicated with any chart, including the ones distributed in the examples, e.g.: https://vega.github.io/editor/#/examples/vega-lite/bar

1. open the URL above or use your own chart code
2. set the rendered to `SVG`
3. press `Export SVG`

The expected outcome is a "Save file as ..." dialog, but that doesn't happen. I tried it in several browsers, with the following outcomes:

- Edge: nothing happens, but there's an error message in the console saying `SEC7134: Resource 'blob:https://vega.github.io/8b031d10-553c-42e3-9cfd-1eb41a7d4c0a' not allowed to load.`
- Firefox: a pop-up window prompt is shown, asking me whether I allow it or not (the URL is something like `blob:https://vega.github.io/9891d3dc-d7d3-4631-958b-8f7f01ac7f5e`. When I press `allow`, the screen flickers and I think I see the SVG mage in a separate tab, but it closes very fast and I really can't figure out what happens under the hood. If I open the debugging tools (`ctrl+shift+i`) then go to `responsive design` and export the SVG again - I see the same image, and the page stays open, so I can save the SVG file normally. If I set the browser settings to always allow pop-ups on the domain, I see the flickering image, as described above.
- Opera: the same flickering behaviour as in Firefox, nothing is shown in the log, switching it to `Responsive design` mode doesn't have the same effect.

I have several privacy-related plugins (Ublock origin in Opera, and Privacy Badger in Firefox). Completely disabling them seems to do the trick, but I have to point out that none of them reported that they blocked anything. Moreover, no such plugins are present in Edge, so it is a bit puzzling, especially that enabling "responsive mode" in Firefox had a positive effect, even without disabling the Privacy Badger plugin.

So, take this info about plugins with a grain of salt, I am not sure I have the complete picture.

**Comment by domoritz** [comment]
The SVG export is supposed to open only the SVG in the browser so that you can either download it or print to PDF. It works fine in chrome but we will check other browsers.

**Comment by domoritz** [comment]
Cc @ydlambda

**Comment by domoritz** [comment]
Cc @ydlambda

**Comment by domoritz** [comment]
Moved to the editor: https://github.com/vega/editor/issues/56
