### ISSUE TITLE
In example gallery, object type attributes appear as [object Object] in tooltip

### ISSUE THREAD

**Issue by yyyliu** [vega/vega-lite#3606]
For instance, in the US unemployment choropleth map example, some fields appear as "[object Object]". Perhaps either do not show these object type fields, or stringify them before displaying.

https://vega.github.io/vega-lite/examples/geo_choropleth.html

<img width="520" alt="screen shot 2018-04-12 at 2 17 58 pm" src="https://user-images.githubusercontent.com/25254084/38705022-0564d4d2-3e5d-11e8-9c84-637eff97201f.png">

**Comment by kanitw** [comment]
Thanks for reporting.  This is a vega-tooltip though, can you close this and post in vega-tooltip instead?

**Comment by yyyliu** [comment]
Okay! Thanks Ham.
