### ISSUE TITLE
partition y-axis by more than 2 fields

### ISSUE THREAD

**Issue by nmaar** [vega/vega-lite#3612]
Hello,

(This is my first Github Issue post)

Is it possible to partition the y-axix by multiple fields? Or will this be possible in a future release?

In de example below: they y-axis is partitioned by two fields "variety" and "site".
-> My goal is to partition the y-axis by more fields,  for example the field "year" or even more fields.
-> In that case there would be one column and multiple (repeating) rows:
    year 1 - site - variety
    year 2 - site - variety

(In the example temporary the visualization is partitioned on the x-axis by the field "year", but I would rather partition the x-axis on one or multiple other fields).

Thanks,

N. Maar

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "name": "trellis_barley",
  "description": "The Trellis display by Becker et al. helped establish small multiples as a “powerful mechanism for understanding interactions in studies of how a response depends on explanatory variables”. Here we reproduce a trellis of Barley yields from the 1930s, complete with main-effects ordering to facilitate comparison.",
  "data": {"url": "data/barley.json"},
  "mark": "point",
  "encoding": {


     "column": {
      "field": "year", "type": "ordinal"
    },


    "row": {
      "field": "site", "type": "ordinal"
    },
    "x": {
      "aggregate": "median", "field": "yield", "type": "quantitative",
      "scale": {"zero": false}
    },
    "y": {
      "field": "variety", "type": "ordinal",
      "sort": {"field": "yield","op": "median", "order": "descending"},
      "scale": {"rangeStep": 12}
    },
    "color": {"field": "year", "type": "nominal"}
  }
}
```

**Comment by domoritz** [comment]
Yes, you can do that with faceting. Look in the docs and let me know if you have questions.

**Comment by nmaar** [comment]
Hi Domoritz, 
I looked into the documentation and also the examples. But I can't find how to partion the y-axis by more than two fields. Is it possible to provide an example? Thanks N. Maar

**Comment by domoritz** [comment]
You can create a facet of a facet. See https://vega.github.io/vega-lite/docs/facet.html

I'm on mobile right now so I can't create an example but you can ask on the mailing list.

**Comment by nmaar** [comment]
Hi, ok i will ask for an example on the mailing list.
Is https://groups.google.com/forum/#!forum/vega-js the correct mailing list for this question?

Thanks N. Maar

**Comment by domoritz** [comment]
Yes, or slack.
