### ISSUE TITLE
Irregular color scales are interpolated in a strange way

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3631]
An Altair user noticed this issue. For example, consider the following spec:
```json
{
  "layer": [
    {
      "mark": "rect",
      "encoding": {
        "color": {
          "type": "quantitative", "aggregate": "mean", "field": "precipitation",
          "scale": {
            "domain": [15, 2, 0.1, 0],
            "range": ["purple", "darkorange", "yellow", "white"]
          }
        }
      }
    },
    {
      "mark": "text",
      "encoding": {
        "text": {"type": "quantitative", "aggregate": "mean", "field": "precipitation"}
      }
    }
  ],
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-weather.csv",
    "format": {"type": "csv"}
  },
  "encoding": {
    "x": {"type": "ordinal", "field": "date", "timeUnit": "day"},
    "y": {"type": "ordinal", "field": "date", "timeUnit": "month"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.3.0.json"
}
```
![visualization 4](https://user-images.githubusercontent.com/781659/39074642-137419f2-44a7-11e8-9585-12e132d26c2d.png)
Notice in particular that Wednesdays in June have a value of 0.14, but the color is associated with the value 0 in the scale (or somewhere between 0 and 0.1 at best)

**Comment by jakevdp** [comment]
Thanks! What does type=sequential actually mean in this context? It's unclear to me in what sense the default behavior could be considered correct.

**Comment by mattijn** [comment]
Sequential scales default to a domain of [0, 1]. They "support piecewise domain settings with more than two entries. In such cases, the output range is subdivided into equal-sized segments for each piecewise segment of the domain."

So in your spec only the tickpositions are changed, while the colors are devided equally.

Vega use by default `linear` scale, where I don't know the reasoning of vega-lite to choose `sequential`.

I firstly thought its because the data is not recognized as a number but as string, but both scales are for `quantitative` data.

**Comment by jakevdp** [comment]
Ah, makes sense. I think in VL 1 scales were linear by default, so I was confused when my code didn't work in VL 2

**Comment by kanitw** [comment]
I suspect this is a bug in the underlying Vega sequential scale (which in turn wraps D3 sequential scale).  So I'll close this and file a new issue in Vega    https://github.com/vega/vega/issues/1252

Here are some clarifications: 

> Sequential scales default to a domain of [0, 1]. They "support piecewise domain settings with more than two entries. In such cases, the output range is subdivided into equal-sized segments for each piecewise segment of the domain."

This is the behavior of D3 sequential, but Vega-Lite maps the data field's domain to the domain of the scale by default.  (In D3, you have to connect the domain values to scale yourselves.)  

For example, see Vega output of [`rect_heatmap`](https://vega.github.io/editor/#/examples/vega-lite/rect_heatmap).

> Vega use by default linear scale, where I don't know the reasoning of vega-lite to choose sequential.

Vega does NOT have default scale type.  You always have to select your own scale type for each scale declared.  

Sequential scale has been added to D3 v4 for coloring quantitative values as it has been shown that well designed sequential scales can be more effective than simple linear interpolation. So it's totally sensible to make `sequential` scale the default quantitative color scale.

**Comment by kanitw** [comment]
Thanks for reporting!  :)

**Comment by kanitw** [comment]
Oh sorry, I'm wrong about that then.  

The correct difference is that Vega-Lite's default scale type depends on the encoding's data type and channel whereas Vega's default scale type is fixed.
