### ISSUE TITLE
Make test run faster

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3643]
Consider `jest` or some mocha parallel solutions

**Comment by kanitw** [comment]
Actually the real test is pretty fast, but the tsc and schema before hand are not

**Comment by kanitw** [comment]
The runtime test is pretty slow so parallelization may still help.

**Comment by domoritz** [comment]
I don't think we can really speed up tsc and schema generation. However, we can use `tsc -w`.

**Comment by domoritz** [comment]
Working on it
