### ISSUE TITLE
matrix - map interaction in vega-lite

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#3647]
I had an example of a matrix-map interaction in vega 3 ([editor-link](https://vega.github.io/editor/#/gist/vega/mattijn/890506e75a502b41a73b5e61dccd0469/af6df4aed5fef8bf12fd63c0df5813c18220c5c7/vega3_som_EU_river_extremes_touch.json)) which I discussed some months ago at the vega repository at https://github.com/vega/vega/issues/1094 and now I'm trying to convert it to vega-lite 2. 

I am quite satisfied and was able to do the lookup and filtering of the spatial locations while interacting in the matrix. And my code went from more than 1100 lines of code in vega to ~100 in vega-lite. 

Here my WIP [editor-link](https://vega.github.io/editor/#/gist/vega-lite/mattijn/70a693b61bae0fe22fc91f1712acefed/b6c4580dd30026ad970dee7b02106e06bd1768f7/vegalite2_som_EU_river_extremes.json)

While converting I noticed some issues:
- ~~The `size` element in the `geoshape` mark is not respected and ignored in compilling the underneath vega code.~~ https://github.com/vega/vega-lite/issues/3335
- The `legend` of the `color` in the `geoshape` is not removed, but set to `undefined`, while `"title": null`.
- I was not able to change the background color of the map. 
- Selection `type: interval` works great, but changing the type to `single` or `multi` doesn't work.
- Seems I cannot sort the filtered locations so high values are drawn on top as I cannot find an encoding option or transform that behaves similar as vega's `collect` transform.
- No `bind: range` option 
- No `bind: select` option to change the variable. Dominik mentions in #3338 I should pivot the data, but this is before the data enters vega-lite? This will still work with `lookup`?

General remark: once inserting a selection `type: interval` it introduce a nice big block in the underlying vega code. In here I added the signals for `touch` events. It would be nice if the behaviour of selections works for `touch` and `mouse` by default in vega-lite.

**Comment by kanitw** [comment]
Thanks so much for reporting.  This one github issue contains multiple bugs/requests though.  Do you mind filing separate issues for each of them so it's easier to track?
