### ISSUE TITLE
Stacked bar chart with log scale gives incorrect results

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3653]
When a stacked bar chart is used with a log scale, the results are strange.

For example:
```json
{
  "data": {"url": "data/movies.json"},
  "hconcat": [
    {
      "mark": "bar",
      "encoding": {
        "x": {
          "bin": {"maxbins": 10},
          "field": "IMDB_Rating",
          "type": "quantitative"
        },
        "y": {
          "aggregate": "count",
          "type": "quantitative",
          "scale": {"type": "log"}
        }
      }
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {
          "bin": {"maxbins": 10},
          "field": "IMDB_Rating",
          "type": "quantitative"
        },
        "y": {
          "aggregate": "count",
          "type": "quantitative",
          "scale": {"type": "log"}
        },
        "color": {"field": "Major_Genre", "type": "nominal"}
      }
    }
  ]
}
```
![export 1](https://user-images.githubusercontent.com/781659/39137228-f143fc62-46d1-11e8-9acc-52d1b537b600.png)

The bars in the two panels should be the same height, but they are not.

**Comment by kanitw** [comment]
I think the right one are not stack by default since stacking with log scale can be misleading.  

In any case, we shouldn't use bars with log scale anyway, so not sure how important to fix this.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3661
