### ISSUE TITLE
customize layout (padding) between facets

### ISSUE THREAD

**Issue by nmaar** [vega/vega-lite#3657]
While creating a facet of a facet, I noticed the padding between cylinder 3 and 4 and between 5 and 6 is wider than ->  cylinder 4 and 6 and  6 and 8.

Regards,
N. Maar

>The spec looks good. Can you create an issue for the second point about padding? I think we can resolve this by letting you customize the Vega layout operator. Right now, we give every facet the same space (not a bug, but a limitation). 
D Moritz

```
{
 "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
 "data": {
 "url": "data/cars.json",
 "format": {
 "type": "json"
 }
 },



"facet": {
 "row": {
 "field": "Cylinders",
 "type": "nominal"
 }
 },
 

"spec": {

 "facet": {
 "row": {
 "field": "Origin",
 "type": "nominal"
 }
 },




 "spec": {
 "mark": "bar",
 "encoding": {
 "x": {
 "bin": {
 "maxbins": 15
 },
 "field": "Horsepower",
 "type": "quantitative"
 },
 "x": {
 "aggregate": "count",
 "type": "quantitative"
 }
 }
 }

}
}

```

**Comment by kanitw** [comment]
Since this is a special case of https://github.com/vega/vega-lite/issues/2446, let's close this one.
