### ISSUE TITLE
Consume all test warnings with log.wrap()

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3663]
We normally use `log.wrap()` to consume all warnings during test (and make sure that our code throws the right warnings. 

However, some test files have not used them yet. 

See https://github.com/vega/vega-lite/blob/master/test/compile/compile.test.ts#L114 for example (of how to use `log.wrap()`. 

After doing this, we should make test fails if the output something to the console as well so make sure all warnings are properly consumed.

**Comment by domoritz** [comment]
It looks like it's using `log.wrap` already, no?

<img width="672" alt="screen shot 2018-04-25 at 21 11 52" src="https://user-images.githubusercontent.com/589034/39280415-5698a7e6-48cd-11e8-8f52-43456a177e86.png">

**Comment by kanitw** [comment]
> However, some test files have not used them yet.

**Comment by kanitw** [comment]
Duplicate of #2723
