### ISSUE TITLE
Disable format parse

### ISSUE THREAD

**Issue by saulshanabrook** [vega/vega-lite#3665]
Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON and, if applicable, screenshots, GIF videos (e.g. using [LICEcap](https://www.cockos.com/licecap/)), or working example (e.g. based on [this Block](https://bl.ocks.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9)).
- [x] Please ensure all code snippets and error messages are formatted in appropriate code blocks. See [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Is it possible to get vega lite to compile vega that doesn't try to transform the data to the right type? For example, in [the bar example](https://vega.github.io/editor/#/examples/vega-lite/bar), it has this transform:

```json
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {"type": "formula", "expr": "toNumber(datum[\"b\"])", "as": "b"},
        {
          "type": "filter",
          "expr": "datum[\"b\"] !== null && !isNaN(datum[\"b\"])"
        }
      ]
    }
```

I know I can remove the `null` checks by setting `invalidValues` to `null` in the config, but I am still left with the `toNumber` conversion. What if I already know it will be a number, isn't this conversion superfluous? Is there a way to disable it and have the vega that is produced only create one data source?

I am asking because [the mapd implementation of transform](https://www.mapd.com/docs/latest/mapd-core-guide/vegaReference/#vegarefdatatrans) only supports `formula` transforms against previously aggregated columns and [I am trying to render vega lite with mapd](https://github.com/Quansight/jupyter-mapd-renderer/pull/7).

**Comment by domoritz** [comment]
Hmm, that's an interesting use case. I guess you would be okay with having to manually specify some additional properties(?).

We could easily support this spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ],
    "format": {
      "parse": {
        "a": null,
        "b": null
      }
    }
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

Vega-Lite would then disable all kind of parsing. We already support parse so this would just be a small change. 

I have to check more carefully, but maybe we can remove the null checks from Vega-Lite in a lot of cases now because Vega 3 handles nulls in aggregates much better but I'd need to check before I know for sure.

**Comment by kanitw** [comment]
> Vega 3 handles nulls in aggregates much better but I'd need to check before I know for sure.

We never filter null for aggregate.  Null filtering is for raw data.

**Comment by domoritz** [comment]
See, that's why I need to check ;-)

So what we decided is that for this spec

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": null}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

We want

![image](https://user-images.githubusercontent.com/589034/39281096-f5f259b0-48d0-11e8-8f32-96e4b388bb57.png)


rather than

![image](https://user-images.githubusercontent.com/589034/39281101-fc4449b8-48d0-11e8-8470-2b490bc6c878.png)

So let's support `null` as a valid parse value then to resolve this issue. @saulshanabrook do you feel like you could send a PR?

**Comment by saulshanabrook** [comment]
The syntax you put in https://github.com/vega/vega-lite/issues/3665#issuecomment-384481085, setting format values to `null`, makes sense to me. I can attempt a PR that adds `null` as a valid format value, which disables the automatic parsing and assumes things are the right types.

I don't understand what the two graphs have to do with this though. The plot you want seems to be what is implemented now by default.

**Comment by domoritz** [comment]
> I don't understand what the two graphs have to do with this though. The plot you want seems to be what is implemented now by default.

Ignore it. This was about handling null/nan values.

**Comment by saulshanabrook** [comment]
Thanks you!
