### ISSUE TITLE
es2015 imports

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3677]
According to https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features, the `module` property points to files that use es2015 imports, not commonjs. We are currently shipping commonjs files to make it easier for downstream libraries and apps. I think we should change that in the coming versions.

**Comment by kanitw** [comment]
We should point to ES2015, doesn't mean we should strictly stop shipping commonjs.  

(I am not saying we should not stop shipping commonjs either, but another option is to ship both and it will still satisfy this requirement.)

**Comment by domoritz** [comment]
Let's see what it takes to make downstream tools support es2015 imports but we don't have to rush this. I just want to keep this issue as a reminder.

**Comment by kanitw** [comment]
@domoritz this seems outdated?
