### ISSUE TITLE
Unhelpful error message:  Unexpected Token ;

### ISSUE THREAD

**Issue by king612** [vega/vega-lite#3687]
I have a composite layout spec like this

`repeat: {
    column: ...
},
spec {
    :
    mark: "point",
    encoding: {
        x: {...},
        y: { field: { repeat: "column"},    },
        color: {
            condition: { ...
            }
        },
        fill: { ....}
    }
}`

As soon as I add any channel below color, I get this:

ERROR: SyntaxError: Unexpected Token ;

I've tried multiple channels and simple values.  All produce the same error.  I seem to remember reading somewhere about restrictions on fields and encoding channels, so maybe this is the root cause?  If that's the reason, a better error message would be very helpful.

Thank you for your help.

**Comment by domoritz** [comment]
Please put a complete spec in the issue so we can look at it.

**Comment by king612** [comment]
I'm sorry, I can't.   It's on a secure client system with no connection.

Somewhere in the docs I now I saw some sort of restriction, and I thought it about conditional encoding could only be applied to one channel within an encoding?  Or something along those lines.  I can't find it now, but I know I saw it in the docs somewhere.

It's the addition of the second channel that causes the error, I'm certain of that.  I've tried putting a couple different channels in there even with simple values specified, and it fails there every time.  It's not a syntax error.

The point of the post was simply that the error message is not helpful, and perhaps a feature request could be put in to improve it, if it's possible for the compiler to detect that problem in context and emit a better message.

Thanks.

**Comment by domoritz** [comment]
Unfortunately I don't know where the error message is coming from. Can you try to create a specification that shows the problem? It can use fake data.

**Comment by kanitw** [comment]
> ERROR: SyntaxError: Unexpected Token ;

I suspect that you copy your code from Javascript to the editor and have `;` at the end of your JSON object.  Hence, the editor throws this error as JSON shouldn't have `;` at the end. 

If that is not the case, please re-open this issue and provide an example that similarly causes the problem.  (As domoritz said, you don't have to use exactly the same code you use locally.  We just need one that produces the same problem.)
