### ISSUE TITLE
Consider adding interesting properties to the dataflow nodes

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3715]
When we construct the dataflow, we track what fields have been parsed as what type or what fields are derived fields. We currently track this information in the `AncestorParse` object. However, it would make sense to track this in the dataflow nodes themselves.

**Comment by kanitw** [comment]
Why would to make more sense to track this in the dataflow nodes themselves?

**Comment by domoritz** [comment]
Right now, we track this in a separate object and the object changes as we parse all the nodes in a model. However, if we want to optimize the dataflow later, all the information about interesting properties is lost. We would preserve it if we tracked it in the nodes.

**Comment by kanitw** [comment]
Unless there are other benefits, sounds like this is a subissue of #2502 (as we won't do it until we want to optimize dataflow ?  May close this and add a TODO bullet there?

**Comment by domoritz** [comment]
It's also a refactor for the format parsing so I could go either way: keep it separate or merge it into #2502.

**Comment by kanitw** [comment]
It's a huge refactor without other benefit, which mean we won't do it separately, so I'd rather combine the issue.
