### ISSUE TITLE
Bullet Chart Example

### ISSUE THREAD

**Issue by apbreports** [vega/vega-lite#3716]
Hello.

You mentioned in [#1486](https://github.com/vega/vega-lite/issues/1486) about your interest in Bullet charts: https://bl.ocks.org/mbostock/4061961

Could this be done with vega-lite using layers? The only issue I see is the performance bar needs to be thinner than the range bars and previous performance indicator (black line). I could not see support for setting with width one one bar layer.

It would be great if you could add this to your example page since I know it is very popular. WE could then add multiple bars using the Faceting setup.

Keep up the amazing work.

**Comment by g3o2** [comment]
I've already designed a simplified version of the above visualisation. However, I have no example ready based on the available vega-datasets.

This can be achieved in several ways:

* layer of several `bar` marks with different `size` values - the order of the layers in the spec is important (do not confuse order here with the `order` encoding channel);

* one bar `mark` with a `condition` on `size`, allowing for two different bar sizes in one single layer based on a condition:

```javascript
    "size": { 
      "value": 20,
      "condition": {"test": "toNumber(datum.year) === 2015" , "value": 8}
    }
```
* The same two ideas can be transposed to the `color` channel;

* `facet` or `vconcat` should be used to separate the indicators, i.e. revenue, profit, etc.

* The data should be in a long form, i.e. one line for each bar per indicator with a value column. With filtering and grouping, you can then extract the necessary information per layer.

Nonetheless, the example you are referring to will probably result in a more complex vega-lite specification.

**Comment by apbreports** [comment]
Thanks for your quick feedback. 
I will setup an example and revert later so you can verify the code and perhaps the code could be the basis of an example going forward.

**Comment by kanitw** [comment]
Since you're asking, I just made an example https://github.com/vega/vega-lite/pull/3717. 

Right now it's not working perfectly yet as we still need to add facet header customization support #2446.
But you probably get the idea.

If you need to use it now, I recommend using `vconcat` of similar specs 5 times where you filter data for each plot by the title.  (That's basically "faceting" by hand.) 

I'll close this issue for now as we have #3717 pending.

**Comment by olly-writes-code** [comment]
Hi @kanitw, did the weird text alignment problem ever get resolved?
