### ISSUE TITLE
Examples on the website are not interactive

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3724]
e.g. https://vega.github.io/vega-lite/examples/selection_layer_bar_month.html

**Comment by jheer** [comment]
Is this running Vega 3.3.1? If so, perhaps try bumping your bundle to 4.0.0-rc.1. Or alternatively lock vega-scenegraph to 2.4.2 and see if that helps? I'm worried there may be an inadvertent version incompatibility here...

**Comment by domoritz** [comment]
According to the yarn.lock, we use Vega scenegraph 2.5. Could that be a problem? I can't test it right now unfortunately.

**Comment by domoritz** [comment]
I'm having a hard time figuring out exactly what's going wrong but with an older version of all vega libraries, the examples work so I suspect that that's the issue.

**Comment by domoritz** [comment]
Fixed with https://github.com/vega/vega-lite/commit/40f18b9c594b32d991b3cd8171d9dacaa0ada8d4
