### ISSUE TITLE
Create method for Supported Scale Types

### ISSUE THREAD

**Issue by ssharif6** [vega/vega-lite#3725]
With Voyager now supporting custom encoding, users can change Scale Types. It would be nice if Vega-Lite could have a `supportedScaleType` method that would determine the possible valid scale types given the Field Definition and encoding channel. This would avoid having tedious if/else logic trees within libraries that use Vega-Lite, like the code snippet below in Voyager.

```
function getSupportedScaleTypes(shelfId: ShelfId, fieldDef: ShelfFieldDef): string[] {
  switch (fieldDef.type) {
    case ExpandedType.QUANTITATIVE:
      if (contains([Channel.X, Channel.Y], shelfId.channel)) {
        return ["linear", "log", "pow", "sqrt"];
      } else if (shelfId.channel === Channel.COLOR) {
        return ["linear", "pow", "sqrt", "log", "sequential"];
      } else if (shelfId.channel === Channel.SIZE) {
        return ["linear", "pow", "sqrt", "log"];
      }
    case ExpandedType.ORDINAL:
    case ExpandedType.NOMINAL:
      if (contains([Channel.X, Channel.Y], shelfId.channel)) {
        return ["point", "band"];
      } else if (shelfId.channel === Channel.COLOR) {
        return ["ordinal"];
      } else if (shelfId.channel === Channel.SIZE) {
        return ["point", "band"];
      }
    case ExpandedType.TEMPORAL:
      if (contains([Channel.X, Channel.Y], shelfId.channel)) {
        return ["time", "utc"];
      } else if (shelfId.channel === Channel.COLOR) {
        return ["time", "utc", "sequential"];
      } else if (shelfId.channel === Channel.SIZE) {
        return ["time", "utc"];
      }
    default:
      return [];
  }
}
```

Both CompassQL and Voyager can benefit from this method!

**Comment by kanitw** [comment]
Thinking a bit more, we actually have a method that contains similar information in Vega-Lite and is perhaps more accurate that what you paste above.  

See https://github.com/vega/vega-lite/blob/master/src/compile/scale/type.ts#L30.

We have `channelSupportScaleType` and `fieldDefMatchScaleType` separately. 

To get the mapping that you have in the above method, you can run a code that call these two methods to derive an index that return supported scale types based on channel and type.  

I think this will be more accurate than having our custom rules like above, especially once we have more channels.

**Comment by kanitw** [comment]
- [ ] The method should be in `src/scale.ts` and just accept `channel` (not `shelfId`) from Voyager
- [ ] Since this method will depend on `fieldDefMatchScaleType`, better move `fieldDefMatchScaleType` to `src/scale.ts` too.
