### ISSUE TITLE
Can't sort by subobject field

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#3727]
Can't sort by field stored in properties of geojson object.
Vega-light processes fields with dot in name but not in "sort field definition object"

### Simplified example to reproduce situation :

```javascript
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json",
    "data": {
        "values": [
            {"name": "a0", "a": {"i": 0}}, 
            {"name": "a1", "a": {"i": 1}},
            {"name": "a2", "a": {"i": 2}}
        ]
    },
    "mark": "bar",
    "encoding": {
        "x": {"field": "a.i", "type": "quantitative"},
        "y": {"field": "name", "type": "ordinal",
            "sort": {
                "order": "descending",
                "op": "sum",
                "field": "a.i"//  "a\\.i" will work
            }
        }
    }
}
```
this example on [bl.ocks.org](https://bl.ocks.org/iliatimofeev/309b8529c14886fed6f9e05d124a99eb/4f257d0fee1ce1d56ff95893fdec6f3caf355423)

**Comment by domoritz** [comment]
Thank you for the issue report! I'm going to look into it.

**Comment by domoritz** [comment]
Vega-Lite should use the flattened field but I am surprised that the small example doesn't work because the data does contain both the flattened and the nested data.

<img width="422" alt="screen shot 2018-05-09 at 12 59 59" src="https://user-images.githubusercontent.com/589034/39836671-02fd3d6a-5389-11e8-8543-bb80082f528b.png">

**Comment by domoritz** [comment]
Here is another problematic example to consider. What if we use a field that is not used anywhere else. We need to automatically flatten it. 

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json",
    "data": {
        "values": [
            {"name": "a0", "a": {"i": 0}, "b": 2}, 
            {"name": "a1", "a": {"i": 1}, "b": 3},
            {"name": "a2", "a": {"i": 2}, "b": 1}
        ]
    },
    "mark": "bar",
    "encoding": {
        "x": {"field": "b", "type": "quantitative"},
        "y": {"field": "name", "type": "ordinal",
            "sort": {
                "order": "descending",
                "op": "sum",
                "field": "a.i"
            }
        }
    }
}
```

**Comment by domoritz** [comment]
@iliatimofeev Can you check whether #3728 fixes the problem in your larger example?
