### ISSUE TITLE
Data from URL not found

### ISSUE THREAD

**Issue by alu0100892833** [vega/vega-lite#3733]
Hello, this may seem very basic, but I have just started using Vega and I have been incapable of loading the data set from a URL. ¿Does the external JSON file have to be in a specific folder, or maybe have a specific syntax? When I load the data manually using a "values" array, it works perfectly, but I have thousands of entries, so I need to read it from an external JSON. In the external JSON, I am defining the data exactly the same way as in the "values" array: a JSONArray of JSONObjects.

```
[{"a":1, "b":2}, {"a":1, "b":2}, {"a":1, "b":2}...] 
```

When I try to load the data using "url", the graphics appear empty.

**Comment by domoritz** [comment]
Can you look at one of our examples that uses data from a URL and see what is different?

Unfortunately, I'll have to close this issue as we don't answer questions on GitHub. Please use slack or the mailing list.

**Comment by kanitw** [comment]
The data file should be like values array.

For URL, it depends on how you set up your web server.  Either relative or absolute URL works
