### ISSUE TITLE
Interval selection on temporal data returns empty selection

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3737]
It seems that interval selections do not work properly on temporal data (reported in https://github.com/altair-viz/altair/issues/828):

```json
{
  "data": {
    "values": [
      {"t": "2017-01-01 01:00:00", "values": 6, "x": 1},
      {"t": "2017-01-01 02:00:00", "values": 10, "x": 2},
      {"t": "2017-01-01 03:00:00", "values": 16, "x": 3},
      {"t": "2017-01-01 04:00:00", "values": 10, "x": 4},
      {"t": "2017-01-01 05:00:00", "values": 11, "x": 5},
      {"t": "2017-01-01 06:00:00", "values": 6, "x": 6},
      {"t": "2017-01-01 07:00:00", "values": 14, "x": 7},
      {"t": "2017-01-01 08:00:00", "values": 12, "x": 8},
      {"t": "2017-01-01 09:00:00", "values": 13, "x": 9},
      {"t": "2017-01-01 10:00:00", "values": 1, "x": 10}
    ]
  },
  "hconcat": [
    {
      "mark": "point",
      "encoding": {
        "x": {"type": "temporal", "field": "t"},
        "y": {"type": "quantitative", "field": "values"}
      },
      "selection": {"interval": {"type": "interval", "encodings": ["x"]}}
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {"type": "quantitative", "field": "values"},
        "y": {"type": "quantitative", "aggregate": "count"}
      },
      "transform": [{"filter": {"selection": "interval"}}]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json"
}
```
<img width="541" alt="screen shot 2018-05-11 at 6 52 28 am" src="https://user-images.githubusercontent.com/781659/39921184-f11f8962-54e7-11e8-8c94-783c6c663fc7.png">

If you switch the x encoding in the scatter plot from ``{"type": "temporal", "field": "t"}`` to ``{"type": "quantitative", "field": "x"}``, then the selection works as expected:

<img width="530" alt="screen shot 2018-05-11 at 6 55 34 am" src="https://user-images.githubusercontent.com/781659/39921296-5955e184-54e8-11e8-9b23-1921a78aeec5.png">

**Comment by arvind** [comment]
It looks like this is happening because the second display's data set (`data_2`) does not have the formula transform that parses the date as necessary (`{"type": "formula", "expr": "toDate(datum[\"t\"])", "as": "t"}`), which then causes the interval predicate to fail. 

Selections _do_ insert these transforms but, currently, [only if a `timeUnit` has been specified](https://github.com/vega/vega-lite/blob/master/src/compile/selection/transforms/project.ts#L25). This code block likely needs to be updated to reflect default `timeUnit` settings (i.e., for temporal fields where no explicit `timeUnit` property has been specified). 

In the interim, one workaround is specifying a `timeUnit` in the above specification like so:

```json
{
  "data": {
    "values": [
      {"t": "2017-01-01 01:00:00", "values": 6, "x": 1},
      {"t": "2017-01-01 02:00:00", "values": 10, "x": 2},
      {"t": "2017-01-01 03:00:00", "values": 16, "x": 3},
      {"t": "2017-01-01 04:00:00", "values": 10, "x": 4},
      {"t": "2017-01-01 05:00:00", "values": 11, "x": 5},
      {"t": "2017-01-01 06:00:00", "values": 6, "x": 6},
      {"t": "2017-01-01 07:00:00", "values": 14, "x": 7},
      {"t": "2017-01-01 08:00:00", "values": 12, "x": 8},
      {"t": "2017-01-01 09:00:00", "values": 13, "x": 9},
      {"t": "2017-01-01 10:00:00", "values": 1, "x": 10}
    ]
  },
  "hconcat": [
    {
      "mark": "point",
      "encoding": {
        "x": {"type": "temporal", "field": "t", "timeUnit": "hours"},
        "y": {"type": "quantitative", "field": "values"}
      },
      "selection": {"interval": {"type": "interval", "encodings": ["x"]}}
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {"type": "quantitative", "field": "values"},
        "y": {"type": "quantitative", "aggregate": "count"}
      },
      "transform": [{"filter": {"selection": "interval"}}]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json"
}
```

**Comment by arvind** [comment]
As of Vega 5.17.1, Vega-Lite 4.17.0, the initial spec in this issue is working. So we likely fixed the underlying issue at some point along the way. Thanks for filing the bug, Jake!
