### ISSUE TITLE
compiled vega source contains outdated `$schema` property

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3739]
currently contains:

`"$schema": "https://vega.github.io/schema/vega/v3.0.json"`

instead of the more general:

`"$schema": "https://vega.github.io/schema/vega/v3.json"`

**Comment by domoritz** [comment]
Yeah, we should change that. Also, Vega 4 is almost out so let's go straight to `"$schema": "https://vega.github.io/schema/vega/v4.json"` when we update.
