### ISSUE TITLE
x2 title ignored when titles of both x and x2 are specified

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#3742]
x2 axis title in stacked bar is hidden when x has title 
```javascript
{
  "mark": "bar",
  "encoding": {
    "y": {
      "field": "question",
      "type": "nominal"
    },
    "x": {
      "field": "percentage_start",
      "type": "quantitative",
      "title": "percentage_start" //<----  change chart view (intentionally)

    },
    "color": {
      "field": "type",
      "type": "nominal"
    },
    "x2": {
      "field": "percentage_end",
      "type": "quantitative",
       "title": "percentage_end" //<----  do not change chart view (expected that both titles would show)


    }
  },
  "data": {
    "values": [
      {
        "question": "Question 3",
        "percentage_start": 10,
        "percentage_end": 50,
        "type": "Agree"
      },
      {
        "question": "Question 3",
        "percentage_start": 50,
        "percentage_end": 70,
        "type": "Strongly agree"
      }
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json"
}
```
![export 1](https://user-images.githubusercontent.com/11561581/40023679-8c3e7b26-57d4-11e8-80d0-2389420e101c.png)
**without title**
![export](https://user-images.githubusercontent.com/11561581/40023674-88f5681c-57d4-11e8-9ea3-195fe7758540.png)

live demo https://iliatimofeev.github.io/sharer/testreport/#diverging_stacked_bar_chart

**Comment by domoritz** [comment]
I think this is actually intended behavior. You are manually setting the title for X and that overrides implicit titles. X2 belongs to X so we don't treat them separately.

**Comment by iliatimofeev** [comment]
Sound logical but in case of titles on both x scales that behavior seems unexpected.

**Comment by kanitw** [comment]
>  in case of titles on both x scales that behavior seems unexpected.

Good point.
