### ISSUE TITLE
Missing chart

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3750]
https://vega.github.io/vega-lite/docs/repeat.html#repeat-operator

**Comment by kanitw** [comment]
What's missing?

**Comment by kanitw** [comment]
This is also not a "bug"

**Comment by domoritz** [comment]
Oh, now I know what the issue was. Here is safari but this has been fixed in https://github.com/vega/vega-datasets/commit/a3ea2890736748d4ced479680c3ec5c776f973aa

![screen shot 2018-05-18 at 22 03 13](https://user-images.githubusercontent.com/589034/40265140-4de41e24-5ae7-11e8-8e7c-ee564043a1ba.png)
