### ISSUE TITLE
Make type of field definition optional

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#3757]
Right now, if I don't specify a type for a field definition, I get ``WARN Invalid field type "undefined" for channel "y", using "quantitative" instead.``, and then in most cases the figure looks just fine.

Would it be an option to just entirely remove that warning and make specifying the type optional? Or maybe only show a warning if the auto-detect code here really fails.

I don't really see the need to make this required. I would guess that in about 80% of my plots things work great without specifying it, and then I end up with shorter specs.

It would also make the whole julia API that we are working on right now more concise, without unnecessary warnings.

**Comment by kanitw** [comment]
>  most cases the figure looks just fine.

Vega-Lite does not look at the data during its compilation and thus we do not have a way to distinguish categorical from quantitative fields without the "type" provided.  If a categorical field is provided without type, a lot of figures will be bad and users might not know why without warning.  

Thus, we won't change this requirement for all encoding channels.  But I can see dropping type from some encoding channel like detail and tooltip that do not have underlying scales.

That said, If in Julia context you already know data type, you can make your API augment appropriate type too. For example, Altair already knows data type from Panda data frame and thus automatically augment data type in the output Vega-Lite.  Then you won't get unnecessary warnings.

**Comment by domoritz** [comment]
I completely agree with @kanitw. We can make smart decisions (and do in some obvious cases) but I think the warning are still a good thing.

**Comment by davidanthoff** [comment]
> That said, If in Julia context you already know data type

That is not correct. As soon as there is any transform in the spec, I have no idea what types I should assign to the field.

> If a categorical field is provided without type, a lot of figures will be bad and users might not know why without warning.

Well, aren't there a gazillion things that a user can do that will lead to bad figures? And then I go to the doc and try to figure out what is going on. How is this case any different from any other mistake I might make in the spec?

I think the reality is that if things work without the ability to specify the type (as it does right now), folks will not specify it because they are lazy. I certainly am :) We are using the same shortcut syntax as altair (``field:q``), and I just end up leaving the ``:q`` out all the time, and then I get the warning, which is annoying, but not annoying enough to push me to write the extra ``:q``.

**Comment by kanitw** [comment]
Since you have full control over your library, you can augment quantitative in your json output if type is not specified too. Then you wont get that warning in your library.

**Comment by domoritz** [comment]
I think the main issue is that we currently don't know how we can infer types in a predictable way where users are not surprised that they have to specify the type all of a sudden. I think especially for beginners they are useful and help with the understanding of the grammar of graphics concepts. 

I

**Comment by davidanthoff** [comment]
> Since you have full control over your library, you can augment quantitative in your json output if type is not specified too. Then you wont get that warning in your library.

No, as I said, then I would have to understand the semantics of the spec and any transformations in the spec. That is not really feasible.

> We could introduce a way to disable specific warnings so that experts don't get annoyed. 

That would be a great solution!

**Comment by domoritz** [comment]
> That would be a great solution!

Let's do that then. I opened #3759 and will close this issue.

**Comment by kanitw** [comment]
> No, as I said, then I would have to understand the semantics of the spec and any transformations in the spec. That is not really feasible.

Always applying Q is feasible, but sometimes incorrect like the "hotfix" that we are doing right now.
(For this reason, I actually do not think you should do it -- for the same reason that we do not want to do it in Vega-Lite.)
