### ISSUE TITLE
Support Image Mark

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3758]
See https://github.com/altair-viz/altair/issues/848

If anyone wanna help, #3615 is a good reference PR.

**Comment by domoritz** [comment]
Vega-Lite supports paths as shapes. Elm-Vega has an example: https://github.com/gicentre/elm-vega/blob/master/vlExamples/isotype.html

It will look like this
<img width="605" alt="screen shot 2018-05-31 at 17 54 02" src="https://user-images.githubusercontent.com/589034/40815482-a7460518-64fb-11e8-89bd-09b4458232b3.png">

We should add an example to the gallery. I don't know whether we really need support for general images.

**Comment by kanitw** [comment]
Yeah, we should add path-based isotype to the gallery.

I think isotype is still a good use case for image mark though.  If you already have a collection of high-definition images, having to convert them into a path isn't a reasonable ask.  

That said, this is obviously not a high-priority task.

**Comment by doug** [comment]
+1 to supporting image mark

**Comment by domoritz** [comment]
@doug, we won't get to it anytime soon but we are happy to review pull requests.

**Comment by kanitw** [comment]
@dhuppenkothen also asks for this!

**Comment by dhuppenkothen** [comment]
I enthusiastically endorse this issue. :)

**Comment by stoneyv** [comment]
vega has a mark type of image, but vega-lite does not.  Would you need to post process vega-lite output to accomplish this or add the mark type of image with default vega parameters to the vega-lite schema and associated functions?
I analyze metrics of camera images and would benefit from the mark type of image. I combine multiple plot types that relate metrics to a series of images.  Currently I often use matplotlib to do these plots. 
 I usually use vega-lite via the python altair library. 

 Astronomers, biologists (microbiology, botany, etc), material scientists, and biophysics people might benefit from being able to display images with interactive vega-lite plots.

**Comment by domoritz** [comment]
Thank you for voicing your interest in this feature. We have to see when we get to implement it but in the meantime if anyone wants to implement this feature, please go ahead and send us a PR.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5060.
