### ISSUE TITLE
Using chai with jest produces TERRIBLE diff for deepEqual

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3761]
(It doesn't compare the diff.) 

~~This might be one solution. https://www.npmjs.com/package/chai-jest-diff~~  Try and it doesn't work

**Comment by kanitw** [comment]
This basically makes the diff no longer debuggable...

**Comment by domoritz** [comment]
The solution is to use `expect(...).toEqual(...)` and we started doing the conversion step by step. I think we can close this issue unless you want us to do this in one big refactor step.

**Comment by kanitw** [comment]
Let's close.  Refactoring in one big step is a pain and I don't want to volunteer anyone for it. lol
