### ISSUE TITLE
Error Band + ErrorBar Refactor

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3770]
@chanwutk  When you do error band, please also do the following refactor 

1) Drop size in ErrorBar by `filterUnsupportedChannels`

Currently we drop size using `const {size: _s, ...sharedEncoding} = encodingWithoutContinuousAxis;`
but we already have `filterUnsupportedChannels` -- better use it.  

2) Better move the following code inside `errorBarParams`  as they are "params" of errorbar too -- this way we can just reuse the whole `errorBarParams` for errorBand.  (You may need to input "mark" between errorbar or errrorband to customize error message. 

```
spec = filterUnsupportedChannels(spec, ERRORBAR);

  // TODO: use selection
  const {mark, encoding, selection, projection: _p, ...outerSpec} = spec;
  const markDef: ErrorBarDef = isMarkDef(mark) ? mark : {type: mark};

  // TODO(https://github.com/vega/vega-lite/issues/3702): add selection support
  if (selection) {
    log.warn(log.message.selectionNotSupported('errorbar'));
  }

  const center: ErrorBarCenter = markDef.center || config.errorbar.center;
  const extent: ErrorBarExtent = markDef.extent || ((center === 'mean') ? 'stderr' : 'iqr');

  if ((center === 'median') !== (extent === 'iqr')) {
    log.warn(`${center} is not usually used with ${extent} for error bar.`);
  }
```

**Comment by kanitw** [comment]
It's also ok for `errorband.ts` to improve things from `errorbar.ts` (no need to move to common)

**Comment by chanwutk** [comment]
If we drop size in filterUnsupportedChannels, wouldn't it also drop the size of Boxplot in its encoding?
