### ISSUE TITLE
Update Legend, Axis, and Title properties for Vega 4

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3779]
Vega 4 adds some properties that were previously only in the config as properties of Axes, Legends, and Titles. We can add those to Vega-Lite. 

See https://github.com/vega/vega/pull/1269

**Comment by kanitw** [comment]
Note:  

1) Implementing this would involve moving these properties from `VgAxis/LegendConfig` to `VgAxis/LegendBase` and update the `COMMON_AXIS/LEGEND_PROPERTIES_INDEX` accordingly.

2) One  part to be careful is to make sure that a lot of default rules in `compile/axis/encode.ts` (e.g., `labelAlign/Baseline`) are only applied if the labelAlign/Baseline properties are not specified by users. 

3) Also remove manual implementation of labelAngle in VL.  (Also, check if there is any other manual implementation.)

**Comment by kanitw** [comment]
I'm close since this is pretty much done if #3999 is merged.
