### ISSUE TITLE
Support renaming tooltip fields

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3785]
We want to be able to customize the name that is used for the tooltip. This is only relevant if there is a table. 

```
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "tooltip": [
      {"field": "a", "type": "ordinal"},
      {"field": "b", "type": "quantitative"}
    ]
  }
}
```

<img width="234" alt="screen shot 2018-05-21 at 10 10 13" src="https://user-images.githubusercontent.com/589034/40320063-303d53b4-5cdf-11e8-9274-82a8233939fb.png">

## Option 1

Consistent with transforms. 

```
{"field": "b", "type": "quantitative", "as": "Field B"}
```

## Option 2

Consistent with other field defs

```
{"field": "b", "type": "quantitative", "title": "Field B"}
```

But a bit odd if you want to set the title of the tooltip (`"as": "title"` is more natural here). 

```
{"field": "b", "type": "quantitative", "title": "title"}
```

**Comment by g3o2** [comment]
Option 2 already works and is consistent, or is there something that I'm missing?

Anyhow, at first glance `title` seems weird even for the `color` channel. However, once you think of it being the guide's title (in that case, the legend), it is perfectly fine. Here, the guide is the tooltip itself.

**Comment by kanitw** [comment]
Option 2 already works and tooltip is an encoding channel so `title` is the right thing to do.

**Comment by kanitw** [comment]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "circle",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "tooltip": [{
      "field": "Name",
      "title": "aaa" 
    }]
  }
}
```

![image](https://user-images.githubusercontent.com/111269/40322783-5405e960-5ce8-11e8-8a11-e95b44a2e66f.png)

**Comment by domoritz** [comment]
Ha, cool. 🎉
