### ISSUE TITLE
how do you do a simple click event?

### ISSUE THREAD

**Issue by silky** [vega/vega-lite#3790]
to save my life i cannot make any sense of the documentation to do with ["events" and "streams"](https://vega.github.io/vega/docs/event-streams/) and whatever to simply implement the following:

1. when someone clicks on a point in my data,

![image](https://user-images.githubusercontent.com/129525/40393480-f706a1d8-5e62-11e8-8e5e-471d6bd7bf3c.png)

2. i want to open a link to a new page ...

as i read it, it seems to be impossible. but this can't be the case, right?

appreciate any help!

**Comment by domoritz** [comment]
You can use the `href` channel in Vega-Lite. See https://vega.github.io/vega-lite/docs/encoding.html#href

**Comment by silky** [comment]
can we close this issue with an **example!**

i'll try and make one

the problem is the documentation here is just impossible to make sense of :(

**Comment by domoritz** [comment]
@silky Please note that Github issues are reserved for issues and feature requests and we may close questions without answering questions: https://github.com/vega/vega-lite/blob/master/.github/ISSUE_TEMPLATE.md. 

Anyway, here is an example:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "href": {"value": "https://idl.cs.washington.edu/"}
  }
}
```

**Comment by silky** [comment]
fine, thanks for the example. i appreciate your help.

**Comment by domoritz** [comment]
@silky Why do you react with a "thumbs down" to my response? We are working very hard on being welcoming but we only have a limited amount of time and energy. Please be kinder to us.

**Comment by domoritz** [comment]
I updated the docs in https://github.com/vega/vega-lite/pull/3794.

In the future, please be kind with the people who are working on all of this in their free time and read the issue template and the [code of conduct](https://github.com/vega/vega/blob/master/CODE_OF_CONDUCT.md) carefully.
