### ISSUE TITLE
Support for Radar Plots

### ISSUE THREAD

**Issue by aishfenton** [vega/vega-lite#3805]
Useful and currently missing.
https://en.wikipedia.org/wiki/Radar_chart

**Comment by g3o2** [comment]
This issue may be related to #408

**Comment by domoritz** [comment]
Let's track this as #408. We need support for polar coordinates for any of these chart types.

**Comment by kanitw** [comment]
Note that Radar chart has a lot of problems, some of which are already noted in the Wikipedia article.  
So I don't think we would prioritize supporting it.  

> We need support for polar coordinates for any of these chart types.

That's not true.  Vega supports arc as a native mark, so pie and arc do not need a special polar coordinate.  However, to support the radar chart, a new coordinate must be supported.  So if you think this is important, please file a feature request for polar coordinate in Vega.
