### ISSUE TITLE
Allow bin's `as` to be an array of (two) strings?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3831]
Currently `as` is a string, which makes sense if we only want to used the binned output in aggregate.

However, if we plan to use the two output to do additional calculation, then it's unclear from the spec that the second field is `<field_name>_end`.  Given that we enforce all fields in `transform` to be named, this can violate our policy if `<field_name>_end` is directly used. 

cc: @domoritz @invokesus

**Comment by invokesus** [comment]
So, the new type of `as` should be `string | string[]` or `string | [string, string]`? 
Or do we drop `string` and only keep the array?

**Comment by kanitw** [comment]
1) Do not drop `string`
2)`[string, string]` is more accurate, but we don't support them well in the documentation yet.  So maybe fix the documentation support and do `[string, string]` after fixing doc support?

I think we already have issue with `[string, string]` for another transform (can't remember which one).  But we better be consistent here.
