### ISSUE TITLE
Typescript 2.9 changes

### ISSUE THREAD

**Issue by jasongrout** [vega/vega-lite#3838]
It looks like this line https://github.com/vega/vega-lite/blob/cdbd87078b60d217d1d03c013af1937631daa219/src/util.ts#L266
should be updated to be something like this to compile in the newly-released Typescript 2.9:
```typescript
export type Diff<T extends PropertyKey, U extends PropertyKey> = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T];
export type Omit<T, K extends keyof T> = {[P in Diff<keyof T, K>]: T[P]};
```

**Comment by jasongrout** [comment]
Even better, get rid of Diff and just use the Omit from the ts 2.8 release notes:

```
Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
```
Or just use that explicitly where you currently use Omit, like

```typescript
export type ScaleComponentProps = Pick<VgScale, Exclude<keyof VgScale, 'domain'>>;
```

**Comment by jasongrout** [comment]
(This error makes it impossible to use vega-lite in a typescript 2.9 project unless we turn on skipLibCheck)

**Comment by domoritz** [comment]
Working on it. I have a fix for this and just need to clean up some things before I send the PR.

**Comment by jasongrout** [comment]
Great, thanks! We were just hoping to update JupyterLab to ts 2.9, and this was the only sticky point.

**Comment by domoritz** [comment]
You're fast ;-)

**Comment by jasongrout** [comment]
Or bored... :)

**Comment by kanitw** [comment]
Yeah the old Diff/Omit were there simply because TS didn't ship them in earlier version.  :)

**Comment by domoritz** [comment]
2.5.1 is out. I'm still trying to resolve some other build issues but you can use it for now.
