### ISSUE TITLE
Revise default legend

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3853]
1) It seems liked the default legend orient is changed when we [upgraded to Vega 4 rc](https://github.com/vega/vega-lite/pull/3743) -- not sure if this is simply due to Vega 4's changed default?

Since we didn't have a check to always re-compile examples until recently: https://github.com/vega/vega-lite/commit/cba6f359128792b90ca66fe04d86f9b36bfaa5d0. 
This change slipped through our releases. 

2) This leads to some better orient

![image](https://user-images.githubusercontent.com/111269/40945415-8a1dd9a6-680d-11e8-82fc-5a6e9b8c0fca.png)

But this also leads to so many examples that has very imbalanced layout.

![image](https://user-images.githubusercontent.com/111269/40945519-1054f8a6-680e-11e8-9f9c-9cd779452895.png)

![image](https://user-images.githubusercontent.com/111269/40945322-29880422-680d-11e8-9ff8-effe89a1e866.png)

I think horizontal is still a better default since it looks less worse in many general cases.   For example, even when the plot is tall enough but the legend's field has long title it still looks imbalanced.  

Plus, this will be more inline with previous behavior prior to 2.5.  

![image](https://user-images.githubusercontent.com/111269/40945506-fee9ac7e-680d-11e8-8060-b082cfe37c44.png)

**Comment by tonne1** [comment]
Seems like it mainly looks messy because you give the legend a fixed height. If you adapt the legend to the height of the chart, it should be ok, especially for continous legends. It might not be feasible for ordinal legends with many items.

**Comment by domoritz** [comment]
As a side note, if you continue to use Vega 3 nothing changes but charts look different in Vega 4.

**Comment by kanitw** [comment]
> Seems like it mainly looks messy because you give the legend a fixed height. If you adapt the legend to the height of the chart, it should be ok, especially for continous legends. It might not be feasible for ordinal legends with many items.

I like this suggestion.  We could try to see if we can set the legend height only for continuous legends.

**Comment by domoritz** [comment]
You have to keep the height of the title in mind, though. I filed an issue about legend titles in https://github.com/vega/vega/issues/1279

**Comment by domoritz** [comment]
Ther is an issue if we have multiple legends as they take up a lot of vertical space. See https://github.com/vega/vega-lite/issues/3873

**Comment by domoritz** [comment]
We could count the number of legends and divide the space equally. Or automatically change to horizontal legends if there is more than one scale. I think I prefer the latter.

**Comment by domoritz** [comment]
I think the new default is fine but we might want to a) automatically set the gradient length b) change the default direction when there are more than one legend.

**Comment by kanitw** [comment]
Vertical is probably good default in Vega because people tend to customize things more in Vega.

However, in Vega-Lite, there are so many cases where this can be broken.  
I'd say that horizontal is a more conservative choice, taking Tableau as inspiration. 

For example, vertical legend here leads to so much wasted space and imbalance for aggregated field (which happens so often in VL, but you won't have similar title in Vega.) 

![untitled](https://user-images.githubusercontent.com/111269/49423154-40688680-f74b-11e8-8e53-98254b4ab5e5.png)

Way less space wasted 

![image](https://user-images.githubusercontent.com/111269/49423267-bd93fb80-f74b-11e8-823e-374d15e48e3b.png)

I think the vertical one is better for the map examples though.  But if our optimization goal is to minimize layout imbalance and % of wasted space, then I think horizontal fits our optimization goals in VL better. 

> b) change the default direction when there are more than one legend.

So far, we actually generally avoid a design where one focused change affects another  change.
Thus, I'd argue that this design is bad.   (Adding one encoding channel should not change the legend of an existing channel.  The encoding should be orthogonal.) 


> a) automatically set the gradient length

This might be okay.  But how would you set it in such as way that works for multiple legends, esp. if one is continuous and another is discrete?

**Comment by kanitw** [comment]
Since changing the orientation is also easy enough, we could make horizontal the default, but customize our map examples to use `"vertical"`.

**Comment by kanitw** [comment]
Let's outline all different cases

## 1) Continuous scale

1a) with reasonable height

`concat_marginal_histograms`

![image](https://user-images.githubusercontent.com/111269/49473787-da6e1480-f7c7-11e8-87af-67989dfcb19e.png)

`rect_binned_heatmap.svg`

![image](https://user-images.githubusercontent.com/111269/49474128-c676e280-f7c8-11e8-8395-a35605e6730c.png)

1b) with a bit small plots

![image](https://user-images.githubusercontent.com/111269/49474219-0342d980-f7c9-11e8-8036-cc94858b0e88.png)

`rect_heatmap`

![image](https://user-images.githubusercontent.com/111269/49474248-10f85f00-f7c9-11e8-8b73-88b96d146c80.png)


`rect_heatmap_weather`

![image](https://user-images.githubusercontent.com/111269/49474255-18b80380-f7c9-11e8-80c7-02078504ba6b.png)

`rect_lasagna_future`

![image](https://user-images.githubusercontent.com/111269/49474272-1f467b00-f7c9-11e8-8de1-1e9b6dff7f75.png)


## 2) binned color

![image](https://user-images.githubusercontent.com/111269/49474076-a515f680-f7c8-11e8-93fb-31d314900d6e.png)

It's unclear to me why binned color legend should look different from quantize scale's legend

![image](https://user-images.githubusercontent.com/111269/49474466-9d0a8680-f7c9-11e8-97d9-2372752684ef.png)



## 3) Geo -- vertical is clear better (unless the color field name is long)

`geo_choropleth`

![image](https://user-images.githubusercontent.com/111269/49473820-f1146b80-f7c7-11e8-81aa-6eb19c594c69.png)

`geo_repeat`

![image](https://user-images.githubusercontent.com/111269/49473869-0ab5b300-f7c8-11e8-808b-70615241cc43.png)

## 4) Temporal

`line_quarter_legend` -- **both of these seem wrong? -- quarter should be discrete**

![image](https://user-images.githubusercontent.com/111269/49474034-8152b080-f7c8-11e8-8520-77fa1a484541.png)

`point_dot_timeunit_color` (This might be the case where horizontal makes more sense as it is temporal?

![image](https://user-images.githubusercontent.com/111269/49474186-eefedc80-f7c8-11e8-9cae-dadb07aca389.png)
