### ISSUE TITLE
Sequence data source

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3864]
The syntax probably look like this

```
data: {
   sequence: {
      start: ...,
      stop: ...,
      step: ...
   }
}
```

- [ ] Perhaps we should support datetime object and convert them to timestamp

**Comment by domoritz** [comment]
@invokesus Are you interested in adding this feature?

**Comment by kanitw** [comment]
We have it! https://vega.github.io/vega-lite/docs/data.html#sequence
