### ISSUE TITLE
Chart freezes on empty selection with quantitative color

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3865]
The following chart freezes if an empty selection is computed.

If the color type is changed from "quantitative" to "ordinal", everything works as expected, so I suspect the problem is that the code that creates the color scale chokes when it's given an empty selection.

```json
{
  "layer": [
    {
      "mark": {"type": "point", "color": "lightgray"},
      "selection": {"box": {"type": "interval"}}
    },
    {
      "mark": "point",
      "encoding": {"color": {"type": "quantitative", "field": "Cylinders"}},
      "transform": [{"filter": {"selection": "box"}}]
    }
  ],
  "encoding": {
    "x": {"type": "quantitative", "field": "Horsepower"},
    "y": {"type": "quantitative", "field": "Acceleration"}
  },
  "data": {"url": "data/cars.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.1.json"
}
```
(our workaround was to instead use a single layer and make the point color conditional on the selection, but I suspect this bug may come up in circumstances where there's not a good alternative)

*Edit: made the spec more compact*

cc/ @dhuppenkothen

**Comment by arvind** [comment]
As far as I can tell, this bug is not specific to selections but rather how gradient legends are drawn when their backing datasets may be interactively filtered. I've raised a corresponding issue in vega/vega#1401. Thanks @jakevdp and @dhuppenkothen!
