### ISSUE TITLE
Support for columnar data (more compact json representation)

### ISSUE THREAD

**Issue by bluenote10** [vega/vega-lite#3867]
Follow-up of an [SO question](https://stackoverflow.com/questions/49310078/how-to-work-with-primitive-values-in-inline-data): It would be nice if the JSON representation of `data`/`values` could support columnar data directly. I.e. instead of having to specify

```json
"data": {
  "values": [
    {"first column": "A", "second column": 28, "third column": 32}, 
    {"first column": "B", "second column": 55, "third column": 94}, 
    {"first column": "C", "second column": 43, "third column": 21},
    ...
  ]
}
```

this would work

```json
"data": {
  "values": [
    {"first column": ["A", "B", "C"]}, 
    {"second column": [28, 55, 43]}, 
    {"third column": [32, 94, 21]},
    ...
  ]
}
```

This would get rid of the excessive duplication of field names and make the JSON representation much more concise. The compression would not only be handy for embedding use case, but can also reduce the message sizes in backend/frontend scenarios.

In case this is already possible it would be good add an example to the documentation -- I couldn't figure it out last time I tried.

**Comment by domoritz** [comment]
Thank you for filing this issue. We already implemented the fold transform as part of #3822.
