### ISSUE TITLE
Combined shape and size scales render unexpected symbol sizes

### ISSUE THREAD

**Issue by d-werner** [vega/vega-lite#3869]
Changing the size for one domain either also changes the size for another domain or gets overridden or ignored.

This spec defines different shapes for each graph but equal sizes for each one.
As expected, the chart gets rendered with equally sized squares, circles and triangles.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Year", "type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "Miles_per_Gallon",
      "type": "quantitative"
    },
    "shape": {
      "field": "Origin",
      "type": "nominal",
      "scale": {
        "domain": ["Europe", "Japan", "USA"],
        "range": ["square", "circle", "triangle-down"]
      }
    },
    "size": {
      "field": "Origin",
      "type": "nominal",
      "sort": "ascending",
      "scale": {"domain": ["Europe", "Japan", "USA"], "range": [100, 100, 100]}
    }
  }
}
```
![bildschirmfoto 2018-06-11 um 10 51 39](https://user-images.githubusercontent.com/2510850/41221802-7b46b71a-6d65-11e8-9984-0a4c819a9855.png)

## Changing square size ("Europe")
The following spec only decreases the size for domain "Europe" in the range array.
The expected behaviour would be only smaller symbols for "Europe". But the symbols for "Japan" get smaller, too. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Year", "type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "Miles_per_Gallon",
      "type": "quantitative"
    },
    "shape": {
      "field": "Origin",
      "type": "nominal",
      "scale": {
        "domain": ["Europe", "Japan", "USA"],
        "range": ["square", "circle", "triangle-down"]
      }
    },
    "size": {
      "field": "Origin",
      "type": "nominal",
      "sort": "ascending",
      "scale": {"domain": ["Europe", "Japan", "USA"], "range": [10, 100, 100]}
    }
  }
}
```
![bildschirmfoto 2018-06-11 um 10 58 47](https://user-images.githubusercontent.com/2510850/41222170-7e99418e-6d66-11e8-949a-5cfc457a5e67.png)

## Changing circle size ("Japan")
Vega-Lite behaves similar when resizing only "Japan".
In this case the symbols of "Japan" and "USA" get changed at the same time.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Year", "type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "Miles_per_Gallon",
      "type": "quantitative"
    },
    "shape": {
      "field": "Origin",
      "type": "nominal",
      "scale": {
        "domain": ["Europe", "Japan", "USA"],
        "range": ["square", "circle", "triangle-down"]
      }
    },
    "size": {
      "field": "Origin",
      "type": "nominal",
      "sort": "ascending",
      "scale": {"domain": ["Europe", "Japan", "USA"], "range": [100, 10, 100]}
    }
  }
}
```
![bildschirmfoto 2018-06-11 um 11 16 03](https://user-images.githubusercontent.com/2510850/41223001-dab7f03a-6d68-11e8-90c7-0a46c0b62404.png)

## Changing triangle size ("USA")
A different behaviour can be seen if size changes are only applied to "USA".
The size value gets ignored and all symbols are of equal size.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Year", "type": "temporal"},
    "y": {
      "aggregate": "mean",
      "field": "Miles_per_Gallon",
      "type": "quantitative"
    },
    "shape": {
      "field": "Origin",
      "type": "nominal",
      "scale": {
        "domain": ["Europe", "Japan", "USA"],
        "range": ["square", "circle", "triangle-down"]
      }
    },
    "size": {
      "field": "Origin",
      "type": "nominal",
      "sort": "ascending",
      "scale": {"domain": ["Europe", "Japan", "USA"], "range": [100, 100, 2000]}
    }
  }
}
```
![bildschirmfoto 2018-06-11 um 11 03 21](https://user-images.githubusercontent.com/2510850/41222420-157c2cec-6d67-11e8-8645-6d5552d87aa4.png)

BTW, I just set `sort` for the size channel because I got this warning otherwise:
`[Warning] Channel size should not be used with an unsorted discrete field.`

**Comment by domoritz** [comment]
I havent looked closely but I believe that we use the first two elements of the range array as the minimum and maximum of the range and then interpolate linearly.

**Comment by d-werner** [comment]
Oh, right! Size for nominal data types is documented as point scale here:
https://vega.github.io/vega-lite/docs/scale.html#type

So, it's just not possible to set specific symbol sizes this way ...

**Comment by domoritz** [comment]
You could try nominal instead or customize the scale type. I'm sure there is a way but I don't know whether the results will be understandable.

**Comment by d-werner** [comment]
OK, thank you!
