### ISSUE TITLE
continuously vary the color of a line/trail

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega-lite#3870]
Hello,

Thanks for Vega-lite. It's fantastic! I have a question:

I'm tying to encode the color of a line to a continuous variable. I thought that I could use the trail mark and specify color, but this doesn't work (only size does). So I can change the entire line/trail to a specific color, but I cannot seem to have the color change as a function of say the y axis for example.

Here is an example of what I'm looking for:
![line_gradient](https://user-images.githubusercontent.com/4624246/41243163-81bf65ce-6d6f-11e8-8877-5a49d0c13509.png)

Is there a way to do this?

Sincerely,
Al

**Comment by domoritz** [comment]
I believe this is not possible in Vega either so we won't be able to implement it in Vega-Lite. Please file an issue in Vega: https://github.com/vega/vega
