### ISSUE TITLE
y axis labels look bad on Chrome and Firefox on Windows 10

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#3875]
I have a standard Windows 10 machine, and when I look at vega-lite plots, the vertical axis labels really look bad, i.e. the text is munged, on Chrome and Firefox. It looks better on Edge.

Here are screenshots from one of the examples in the gallery, displayed on all three browsers:

# Firefox
![image](https://user-images.githubusercontent.com/1036561/41310659-fe733bd2-6e36-11e8-9e0e-53e94c36c4b4.png)

# Chrome
![image](https://user-images.githubusercontent.com/1036561/41310696-1b67da40-6e37-11e8-829a-c5d02b84bb80.png)

# Edge
![image](https://user-images.githubusercontent.com/1036561/41310729-3425c0d8-6e37-11e8-8b5a-a3cd34bba1f7.png)

As you can see, the letters on Chrome and Firefox bump into each other, and it all just looks not very good.

This might just be a problem with those browsers, but I am wondering whether there is something that could be done about this, because it does make for a pretty poor first experience for most likely a large number of folks.

**Comment by domoritz** [comment]
Can you try https://vega.github.io/editor/#/examples/vega-lite/histogram with SVG and Canvas? 

Vega-Lite won't be able to do anything here and I doubt even Vega can. D3 must have the same problem.

**Comment by jheer** [comment]
This looks like a browser + platform issue. To start, try changing the default font. Vega uses `sans-serif` as the default font. I don't know what that maps to on Windows. Try setting it to `Arial`, `Calibri`, or some other typeface and see what happens. You can set the font by adjusting the configuration, or just by explicitly setting it in the specification.

**Comment by davidanthoff** [comment]
All based on Chrome and canvas rendering.

Here is how it looks when I set `titleFont` to `Arial`:

![image](https://user-images.githubusercontent.com/1036561/41313053-bab0cec6-6e3d-11e8-9f21-30400147d1b2.png)

With `Calibri`:

![image](https://user-images.githubusercontent.com/1036561/41313098-d89efe1c-6e3d-11e8-9b36-e6e539ec7087.png)

**Comment by jheer** [comment]
Based on the evidence so far, this seems to be a platform-specific browser issue and outside the scope of Vega and Vega-Lite. We simply use built-in browser text rendering methods (either via Canvas Context2D `fillText` or SVG `text` elements) so there is really nothing to change or fix at the Vega level other than default font settings.

Are you using the Canvas renderer, and if so, does the output look different with SVG? If so, this might be more specifically a Canvas text rendering issue on Windows. That would also give you the option of using SVG if you want a better looking output.

**Comment by davidanthoff** [comment]
Yeah, this definitely seems to be just a browser thing... I don't see a difference between Canvas and SVG rendering.

I've exported the graph to SVG now, and just opened that in the various browsers, and it looks ok on Edge, and really not good on Chrome and Firefox... This is on a computer with a pretty high resolution, but no DPI scaling (as far as I can tell). On my laptop, with an even higher resolution and DPI scaling, things look fine. I'll try again tonight at my home computer (no DPI scaling, low res display).

Things do look slightly better if the text isn't bold... It is unclear how widespread this issues is (i.e. just my system, or all Windows systems), but maybe it would be worth thinking about changing that default in vega-lite...

I'm kind of amazed that there is still a difference (and issues!) between different browsers on something as basic as that. And also kind of amazed that of all the browsers, Edge has the best result...

**Comment by davidanthoff** [comment]
So I tried this on my home machine now. Same result: Chrome and Firefox look really garbled with incorrect spacing between letters etc. Edge looks fine.

I played around a bit with different fonts, and maybe one can make an argument that without bold and at different text sizes things look a bit better. Not great, but maybe slightly better. Things certainly get a lot better with bigger font sizes (say 14 and up).

So not really clear what can be done on this, other than maybe open issues with Chrome and Firefox and complain?

**Comment by domoritz** [comment]
What happens if you create an SVG and rotate the text? That would be a good minimal example for a bug report. 

I'm going to close the issue here as there isn't anything Vega-Lite can do. You can keep responding, though.

**Comment by davidanthoff** [comment]
I exported a graph as a SVG, and then stripped out almost everything. With that I got down to this:
````svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg class="marks" width="276" height="251" viewBox="0 0 276 251" version="1.1" 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <g transform="translate(70,11)">
        <g transform="translate(0,0)">
            <g transform="translate(0.5,0.5)">
                <text text-anchor="middle" transform="translate(-52,100) rotate(-90) translate(0,-2)" style="font: bold 11px sans-serif;">Number of Records</text>
            </g>
        </g>
    </g>
</svg>
````
And that file looks crappy on Chrome and Firefox, and ok on Edge.
