### ISSUE TITLE
Alternative to null significance in JSON schema

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#3877]
A number of places in the vega-lite schema use `null` as a significant value, for example:

```json
"scale": {
  "anyOf": [
    {
      "$ref": "#/definitions/Scale"
    },
    {
      "type": "null"
    }
  ],
  "description": "…If `null`, the scale will be [disabled and the data value will be directly encoded] … If undefined, default [scale properties]… are applied."
}
```

This is fine for JavaScript, which treats `null` as distinct from `undefined`, but most other languages don't have that distinction, and thus their JSON serialization frameworks treats `null` the same as the absence of a property. Some frameworks have an option to output explicit `null` values for absent keys, but these are often configured at a global level, such as Scala's Circe property `dropNullValues`, which is even more problematic, because very verbose schemas would be output with many null values that trigger Vega-lite's explicit null handing.

I would suggest adding a global definition that acts as an explicit null value and using that instead. It could be a `oneOf` with `null` (for backwards-compatibility) and some constant object, something like:

```json
"ExplicitNull": {
  "oneOf": [
    { "type": "null" },
    { "type": "object", "required": [ "explicitNull" ], "properties": { "explicitNull": { "type": "boolean" } } }
  ]
}
```

That type could then be referenced as so:

```json
"scale": {
  "anyOf": [
    {
      "$ref": "#/definitions/Scale"
    },
    {
      "$ref": "#/definitions/ExplicitNull"
    }
  ],
  "description": "…If `ExplicitNull`, the scale will be [disabled and the data value will be directly encoded] … If undefined, default [scale properties]… are applied."
}
```

That way, a language/framework that has difficulty serializing null values to JSON could specify that it should be treated as null with JSON like:

```json
{ "scale": { "explicitNull": true } }
```

See also: https://github.com/vega/vega-lite/issues/2400 (where there was proposed having an explicit value that signified `null`)

**Comment by domoritz** [comment]
Would this change be useful for Altair @jakevdp?

**Comment by kanitw** [comment]
Thanks for the proposal.

However, `{"explicitNull": true}` sounds quite weird for a direct usage in Vega-Lite. Plus, one can always define a placeholder object for null (like `{"explicitNull": true}` and preprocess it before calling it Vega-Lite. So I'm not convinced we should do this in Vega-Lite.

It might be better to report if there are parts of the language that better support alternative values to `null`.  For example, we could support `axis: false` for `axis: null`.  (Please file a different issue for parts that you find a part that's worth revising.)
