### ISSUE TITLE
Unify the many spec definitions in the JSON schema

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#3884]
There are twelve different "*Spec" types defined in `vega-lite-schema.json`: `CompositeUnitSpec`, `LayerSpec`, `FacetSpec`, `HConcatSpec`, `RepeatSpec`, `VConcatSpec`, `TopLevelLayerSpec`, `TopLevelHConcatSpec`, `TopLevelRepeatSpec`, `TopLevelVConcatSpec`, `TopLevelFacetSpec`, `TopLevelFacetedUnitSpec`, in addition to two union spec types: `TopLevelSpec` and `Spec`. The majority of properties in all these types are shared between all the other types, with a couple of extra properties serving as the discriminator for the type (e.g., the `vconcat` property is the discriminator for the `VConcatSpec` type). These redundant definitions make up about 15% of the size of the `vega-lite-schema.json` file.

I understand that these schema types are generated from TypeScript types that use inheritance, generics, and mixins, none of which are representable in JSON schema. However, for clients of the schema who might not understand (or care) about the internal implementation details, it can be a bewildering group of types to choose from, and for strongly typed language source files that are generated from JSON schema, there will be a dozen mostly-redundant types created for these different spec types.

I would recommend just having a single "Spec" type that just contains the aggregate sum of all the properties in the various "*Spec" types. This would mean the loss of a bit of static validation (e.g., a spec declaring both "vconcat" and "hconcat" properties at the same time would pass JSON schema validation), but I think that would be a fair price to pay to reduce the complexity of the specification.

**Comment by domoritz** [comment]
I agree with the sentiment. However, unless you have a specific use case for this, I don't want to make the effort to provide another type. The various specs have not been an issue for Altair for example. 

Another way to implement Vega-Lite in a different language is to use the typescript typings directly instead of going through the JSON schema.

**Comment by mprudhom** [comment]
Good point about using the typings. I'll use them to augment my own generated model, which should help ease some of the cumbersome API interactions required with a pure representation of the types in the JSON schema. I still think that a unified spec type would be a "nice to have", but feel free to put this issue on ice for now.

In case you are interested in how the vega-lite JSON schema model looks in Swift, you can see it at: 

  https://gist.github.com/mprudhom/f597f6fc65ddf2c2ece5a638132d6657

**Comment by domoritz** [comment]
Uhh, that's awesome. One thing we could do is annotate the schema with the parent class and whether a method is inherited. I don't know whether json schmea alllows custom properties, though.

**Comment by mprudhom** [comment]
Annotating with parent class would definitely be handy for many scenarios. Another option that would greatly reduce the size of the schema without any loss of information could be to represent inheritance and mixins using the proposed Draft-08 `propertyNames` field combined with `anyOf` and `allOf` as described at: http://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-all-the-discussions-around-re-using-schemas-with-additionalproperties

**Comment by domoritz** [comment]
Draft-08 is not supported by monaco, our docs table generation, or the altair interface generators. 

If you want to have annotations for inheritance, we would need to add it to https://github.com/vega/ts-json-schema-generator.
