### ISSUE TITLE
rule mark gets positioned incorrectly

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#3885]
I would have expected that this spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {
    "url": "data/stocks.csv"
  },
  "transform": [
    {
      "filter": "datum.symbol==='GOOG'"
    }
  ],
  "layer": [
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal"
        },
        "y": {
          "field": "price",
          "type": "quantitative"
        }
      }
    },
    {
      "mark":"rule",
      "encoding":{
        "y":{
          "value": 50
        }
      }
    }
  ]
}
```
shows a horizontal line/rule at y=50, but instead it shows up as a horizontal line/rule at y=600.

**Comment by domoritz** [comment]
50 is in pixels (it is the range, not the domain). The same happens when you set `value: red`. You don't want the color to go through the scale. You either have to add a fake data source with 50 in it or wait for https://github.com/vega/vega-lite/issues/1601 or send us a PR ;-)

**Comment by g3o2** [comment]
You can also apply a `calculate` transform to the value as a field.

**Comment by davidanthoff** [comment]
Ah, that makes sense. I just added a voice of support for #1601, I think that would be super useful. No PR coming from my end, getting the julia wrapper in shape is enough for my plate ;)

**Comment by domoritz** [comment]
Thank you @davidanthoff. We will bump the priority on the issue.
