### ISSUE TITLE
inconsistent `fill` behaviour in legend due to presence or absence of `condition`

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3892]
Currently, `size`'s legend fill appears to depend on the presence of `condition`, yielding inconsistent results.

Here below an example with `circle`.

Spec __with a condition__ in color channel
-> __filled circles__ in the `size` legend = expected behaviour

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 500, "height": 500,
  "background": "white",
  "data": {"url": "data/cars.json"},
  "mark": {"type":"point", "filled": true},
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
        "condition": {"test": "datum.Miles_per_Gallon > 150", "value": "gray"},
        "field": "Origin", "type": "nominal"
    },
    "size": {"field": "Acceleration", "type": "quantitative"},
    "opacity": {"value": 0.7}
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/41594476-d62f5c7c-73c3-11e8-916d-5da44f64e30b.png)

Spec __without any condition__ in color channel 
-> __unfilled circles__ in the `size` legend
vs expected behaviour: filled

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 500, "height": 500,
  "background": "white",
  "data": {"url": "data/cars.json"},
  "mark": {"type":"point", "filled": true},
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
        "field": "Origin", "type": "nominal"
    },
    "size": {"field": "Acceleration", "type": "quantitative"},
    "opacity": {"value": 0.7}
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/41594617-3cd95f86-73c4-11e8-8b46-09c07ffe7426.png)

The `vega` compiled source code yields the following difference between both specs

![image](https://user-images.githubusercontent.com/12123506/41594683-7b778ca4-73c4-11e8-92f6-3216c525e25f.png)

In general, legend's `size` channel circles should be filled or not depending on the `fill` settings of the mark:

* in case of `mark: circle` or `mark: {type: point, filled: true}`, `size`'s legend circles should be filled to allow for better readability -`stroke` should be transparent;
* in case of `mark: point`, `size`'s legend points should not be filled to allow for better readability - `fill` should be transparent.

**Comment by g3o2** [comment]
Also raised under sub issue D in #3208.

**Comment by domoritz** [comment]
It looks like it's fixed in master.

![image](https://user-images.githubusercontent.com/589034/46387140-2db5d080-c67a-11e8-959d-97d24ee518ba.png)
