### ISSUE TITLE
Unified sort syntax for nominal

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3893]
One issue that has come up in Altair is the fact that pandas dataframes have an ordered categorical data type, whereas JSON does not. This means that people pass a dataframe expecting values to be in a certain order, and are confused when they are not (e.g. #940)

I think a useful enhancement to Altair would be to automatically populate the encoding argument that controls sorting, the same way we automatically populate the ``type`` argument based on the data type. The problem is, the way that Vega-Lite specifies sorting within encodings varies depending on encoding type... e.g. x and y encodings take a ``sort`` parameter, colors take a ``domain`` parameter, and rows/columns currently have no way to specify a nominal order.

Would it be possible to add an ``sort: EncodingSortField`` parameter for *every* encoding type that would be applied in the case of nominal data?

**Comment by kanitw** [comment]
Sure. `color` encoding and other non-position encodings (with scales) already have `sort` properties.

Facet will have `sort` soon (#3854), so we will just need to implement https://github.com/vega/vega-lite/issues/3856 and we should be all good.

> I think a useful enhancement to Altair would be to automatically populate the encoding argument that controls sorting, the same way we automatically populate the type argument based on the data type. 

That's an excellent idea.  I guess the type of `sort` you want may be the sort array, not the `EncodingSortField`?

**Comment by jakevdp** [comment]
Ah, yes, my mistake. Sort array is what I had in mind :smile:

**Comment by kanitw** [comment]
Cool.  Since all TODO are tracked by other issues, I'll close this for now :)
