### ISSUE TITLE
Cannot find module './package.json'.

### ISSUE THREAD

**Issue by artfulgarfunk** [vega/vega-lite#3897]
I'm using Angular 6 and TS 2.9.2 and so far cannot get vega-lite working. Thought it was an old TS issue but evidently not. 

I've installed vega, vega-lite & vega-embed using npm.

Getting the following error when compiling: 

ERROR in node_modules/vega-lite/build/src/index.d.ts(26,25): error TS2307: Cannot find module './package.json'.

I tried adding the following line to tsconfig.json which stops the error, all errors in fact, but then the app just never displays. 
"include": ["node_modules/vega-lite/typings/*.d.ts"]

Any help appreciated - cheers

**Comment by domoritz** [comment]
Try adding https://github.com/vega/vega-lite/blob/a4900a3541668fb79afeb6b12a9cf8fc8e107bda/tsconfig.json#L7 or `"include": ["node_modules/vega-lite/typings/*.d.ts"]`. If you don't see anything, that's probably an issue with the bundler you use.

**Comment by reckoner** [comment]
I am having the exact same problem. I tried the two suggestions above but they don't work.

**Comment by domoritz** [comment]
Can you show me a minimal example to reproduce this issue?

**Comment by reckoner** [comment]
Here is my angular config:

    Angular CLI: 6.0.8
    Node: 8.11.2
    OS: linux x64
    Angular: 6.0.6
    ... animations, common, compiler, compiler-cli, core, forms
    ... http, language-service, platform-browser
    ... platform-browser-dynamic, router

    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.6.8
    @angular-devkit/build-angular     0.6.8
    @angular-devkit/build-optimizer   0.6.8
    @angular-devkit/core              0.6.8
    @angular-devkit/schematics        0.6.8
    @angular/cli                      6.0.8
    @ngtools/webpack                  6.0.8
    @schematics/angular               0.6.8
    @schematics/update                0.6.8
    rxjs                              6.2.1
    typescript                        2.7.2
    webpack                           4.8.3

And here are the steps.

1.  ``ng new vega-proj``
2.  ``npm install vega-lite@2 vega-embed@3 vega``
3. ``ng serve`` (within the vega-proj directory)

    `ERROR in node_modules/vega-lite/build/src/index.d.ts(26,25): error TS2307: Cannot find module  './package.json'.`

Please tell me what I am missing here?

**Comment by domoritz** [comment]
I don't use angular. Can you try to reproduce it without it?

**Comment by reckoner** [comment]
@domoritz  I'm a beginner here. If you give me a sequence of steps, I can try.

**Comment by domoritz** [comment]
Can you install https://github.com/systemjs/plugin-json? This seems to help: https://stackoverflow.com/a/47167168/214950

**Comment by reckoner** [comment]
There are other typescript problems also.

    ERROR in node_modules/vega-lite/build/src/util.d.ts(1,8): error TS1192: Module '"/home/reckoner/vega-proj/node_modules/@types/json-stable-stringify/index"' has no default export.
    node_modules/vega-lite/build/src/util.d.ts(56,41): error TS2304: Cannot find name 'Extract'.
    node_modules/vega-lite/build/src/util.d.ts(71,100): error TS2536: Type 'T' cannot be used to index type '{ [P in T]: P; } & { [P in U]: never; } & { [x: string]: never; }'.
    node_modules/vega-lite/build/src/util.d.ts(72,11): error TS2322: Type 'T' is not assignable to type 'string'.
      Type 'PropertyKey' is not assignable to type 'string'.
        Type 'number' is not assignable to type 'string'.
    node_modules/vega-lite/build/src/util.d.ts(74,11): error TS2322: Type 'U' is not assignable to type 'string'.
      Type 'PropertyKey' is not assignable to type 'string'.
        Type 'number' is not assignable to type 'string'.

**Comment by domoritz** [comment]
Please use the tsconfig from Vega-Lite.

**Comment by reckoner** [comment]
I pulled tsconfig from 

https://github.com/vega/vega-lite/blob/a4900a3541668fb79afeb6b12a9cf8fc8e107bda/tsconfig.json#L7

I made the changes noted above. I'm still having the same problem noted above, however.

**Comment by domoritz** [comment]
Also add `esModuleInterop` and `allowSyntheticDefaultImports`.

**Comment by domoritz** [comment]
This seems to be good here.
