### ISSUE TITLE
"stack" control

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#39]
- [ ] whether to stack or not

> By default would "auto" choose to stack based on mark (current behavior)
> If true, stack regardless of mark type
> If false, do not stack for any mark type

- [ ] sortby

**Comment by kanitw** [comment]
For control whether to stack or not,  should this property be a `stack` of encDef for `COLOR`, `LOD`?

@jheer @domoritz

**Comment by domoritz** [comment]
So if you don't stack bars you get a grouped bar chart? Stack only works for bar charts anyway, right?

**Comment by kanitw** [comment]
> So if you don't stack bars you get a grouped bar chart? 

No, you get layered bar chart, which is confusing as it looks similar to stacked -- which I hate but some people make it.  (A better idea design is `grouped bar chart`)

> Stack only works for bar charts anyway, right?
Stack also works for area.

**Comment by domoritz** [comment]
> No, you get layered bar chart, which is confusing as it looks similar to stacked -- which I hate but some people make it. (A better idea design is grouped bar chart)

It could be okay if the bars (or the area) is semi transparent. Like https://static1.squarespace.com/static/52b5eb00e4b0ca7bf17667b6/t/553eb9e0e4b014e1ca35e62f/1430174178308/

Not sure how well this works for bars, though.

**Comment by jheer** [comment]
I'm a little skeptical of adding a "stack" option. I would prefer to start
with simpler specs and good defaults (stacking for bar charts) and see how
far we get with that. In addition, stacking is only sensible for a limited
set of marks, so it introduces a non-orthogonal design element. Perhaps we
could add some kind of additional feature or config override (to disable
stacking) in the future, if needed.

**Comment by kanitw** [comment]
@jheer 

>  Perhaps we could add some kind of additional feature or config override (to disable
stacking) in the future, if needed.

This issue is actually about the config to override stack.   The questions is whether we put that in `color/detail` or in `config`.  I prefer the former because we are trying to minimize number of general configs and only put things in configs if it does not make sense to put it somewhere else.  

> I would prefer to start with simpler specs and good defaults (stacking for bar charts) and see how
far we get with that.

Totally agree with good defaults.  The `stack` option should be `true` by default, so people only need to specify it if they want to turn it off. 

I don't think this is a particularly important feature but we discussed that some people will eventually want it and since it will be only a few lines of code, I think we can just decide and implement it so we have less open issues. :)

**Comment by jheer** [comment]
Thanks for the clarification. This makes sense to me.
