### ISSUE TITLE
log scale with zero data should give a better warning

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#3911]
In Altair, I had a column of data that I plotted on a log scale:

```
sh = Chart(df).mark_point().encode(
    x='Launch:T',
    y=Y('Pixel/unified shader count:Q',
        scale=Scale(type='log'),
        ),
```

and a zero snuck into the column that I didn't know about and the debugging of that took a really really long time. Here's what Altair output looked like:

![image](https://user-images.githubusercontent.com/976970/41695131-819787c0-74c2-11e8-9b7c-1ebce8ab1a65.png)

I guess I would have expected that the zeroes would be silently dropped OR the console would have thrown a warning ... anyway, the Altair output was perplexing. One zero out of several hundred data points made everything plot on a single line.

@jakevdp suggested this was the right place to raise the issue (https://github.com/altair-viz/altair/issues/953).

**Comment by domoritz** [comment]
Vega-Lite actually never sees the data so the warning would need to be in Vega.

**Comment by jowens** [comment]
@domoritz should I go file this in vega's issues?

**Comment by domoritz** [comment]
One thing we could do in Vega-Lite is automatically filter out values less or equal to zero (in https://github.com/vega/vega-lite/blob/master/src/compile/data/filterinvalid.ts) but that seems like it could have all kinds of bad effects.

Yes, I think this needs to be in Vega itself.

**Comment by kanitw** [comment]
> One thing we could do in Vega-Lite is automatically filter out values less or equal to zero (in /src/compile/data/filterinvalid.ts@master) but that seems like it could have all kinds of bad effects.

We used to, but not any more. (Look at the code you link to.)

**Comment by domoritz** [comment]
What do you mean? I know that we used to and we don't right now but I linked to the code where we would add this functionality.

**Comment by g3o2** [comment]
wouldn't it be better to plot the invalid values as missing values?

**Comment by domoritz** [comment]
@g3o2 yes. We haven't figured out a good way to  show missing values in all chart types.

**Comment by kanitw** [comment]
> What do you mean? I know that we used to and we don't right now but I linked to the code where we would add this functionality.

Oh I see.  We intentionally remove that filter because it's magical so I don't think we should add it back.   Plus, D3 log scale works with either strictly positive or strictly negative values, so it's quite tricky to write the right filter.

> wouldn't it be better to plot the invalid values as missing values?

Yes, but invalid values is also a part of scale domain and thus it will break the scale like shown in the screenshot at the top of this issue.  Filtering it correctly can be tricky.
