### ISSUE TITLE
Controlling order of timeUnit day

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3919]
When you use ``sort`` to try to control the order of day time units on an axis, it leads to strange results. For example:
```json
{
  "data": {"url": "data/stocks.csv", "format": {"type": "csv"}},
  "mark": "rect",
  "encoding": {
    "color": {"type": "quantitative", "aggregate": "count"},
    "x": {"type": "ordinal", "field": "date", "timeUnit": "month"},
    "y": {
      "type": "ordinal",
      "field": "date",
      "sort": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      "timeUnit": "day"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.5.2.json"
}
```
![export 1](https://user-images.githubusercontent.com/781659/41780616-15a1390c-75ea-11e8-81e2-8be1a18402a7.png)

**Comment by kanitw** [comment]
Ah that's because the underlying data is still a timestamp.

**Comment by kanitw** [comment]
Fixed in #3944

See the updated [github punchcard example](https://github.com/vega/vega-lite/pull/3944/files#diff-315a4eaa483085f599b1c8c58faac1e)

**Comment by maxauthority** [comment]
It is still annoying (and more importantly - error prone) to do this sorting by hand. Couldn't the sort order of having Monday first (or maybe Saturday first for some locales) be infered from the current locale? Or at least as a simple property "daySort" or similar where one could say "iso" e.g. to sort weekdays starting with monday?

**Comment by kanitw** [comment]
Unfortunately our implementation uses JS's `getDay()` method and thus is limited.
