### ISSUE TITLE
Suggest an ISO-Standard day-of-week unit transform

### ISSUE THREAD

**Issue by coolum001** [vega/vega-lite#3925]
According to international standard ISO 8601, Monday is the first day of the week.

Pandas has:
" DatetimeIndex.dayofweek

The day of the week with Monday=0, Sunday=6"

I suggest a new time unit transformation (say ```dayISO```, that has Monday as the first day of the week (ie to align with Pandas).

This would have the advantage of grouping non-working days together, which might make some graphics produced by Altair easier to understand.

**Comment by kanitw** [comment]
This will be difficult as the underlying Vega language uses Javascript `day()` function. 

Instead, I think we will just make it easier for you to customize sorting of discrete time data (https://github.com/vega/vega-lite/issues/3932).  That would also support this use case.
