### ISSUE TITLE
Clipping line of area mark

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#3927]
```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
   "type": "area",
   "line": true, //{"clip": true}--> [Warning] Validation: /mark should match some schema in anyOf
   "clip": true, 
   "interpolate": "step-after" // <--Now works as expected :) thanks!
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal",
    "scale": {
        "domain": [
          {"year": 2006},
          {"year": 2009}
        ]}
    },
    "y": {"field": "price", "type": "quantitative"}
  }
}
```
![export 12](https://user-images.githubusercontent.com/11561581/41821831-26a02b1c-77ef-11e8-905c-1a03e077ee6f.png)
I expected that clip will be inherited from the area description like "interpolate" does now. At least `"line": {"clip": true}` should not violate schema.

By the way `"line": {"interpolate": "basis"}` would not have any effects or errors that is backward incompatible.

**Comment by domoritz** [comment]
This works but fails validation but we should be inheriting `clip` from the mark def since we are inheriting `interpolate`. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
   "type": "area",
   "line": {
     "clip": true
   },
   "clip": true, 
   "interpolate": "step-after"
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal",
    "scale": {
        "domain": [
          {"year": 2006},
          {"year": 2009}
        ]}
    },
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3928

**Comment by iliatimofeev** [comment]
>` "line": {"interpolate": "basis"}` would not have any effects or errors that is backward incompatible.

Should I file it separately or its intentional?

**Comment by domoritz** [comment]
What is the issue?

**Comment by iliatimofeev** [comment]
```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "https://vega.github.io/vega-datasets/data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
   "type": "area",
   "line": {
    "interpolate": "step-after"
   },
    "interpolate": "basis"
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  }
}
```
Vega-Lite version 2.5.1
![export 14](https://user-images.githubusercontent.com/11561581/41824161-7fa0f35c-7814-11e8-9bdd-74aa38b5362c.png)
Vega-Lite version 2.4.1
![visualization 19](https://user-images.githubusercontent.com/11561581/41824246-efa0804a-7815-11e8-967b-b6036837a019.png)

If you omit `"interpolate": "basis"`  Vega-Lite version 2.5.1 will display as Vega-Lite version 2.4.1 that seems illogical.

**Comment by domoritz** [comment]
This is fixed in master, I believe.
