### ISSUE TITLE
Support string datetime format in domain definition.

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#3929]
Currently supported milliseconds since 1970 could be not really natural for other languages something like `int(time.mktime(datetime.date(2009,1,1).timetuple()))*1000`. The [datetime](https://vega.github.io/vega-lite/docs/types.html#datetime)`{“year”: 2006, “month”: “jan”, “date”: 1}` is it not really human readable in comparison to classical string representation which is supported in most languages.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
   "type": "area",
   "clip": true 
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal",
      "scale": {
          "domain": [ 
                            "2006-01-01", //<- date
                            "2009-01-01T00:00.000Z" //<- datetime
                          ]
        }
    },
    "y": {"field": "price", "type": "quantitative"}
  }
}

```
![export 13](https://user-images.githubusercontent.com/11561581/41823246-87990856-7805-11e8-86c2-af708d259d09.png)

**Comment by kanitw** [comment]
Will be fixed in #3954
