### ISSUE TITLE
level of detail are not included in the legend

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#394]
at least, there should be some more contextual information

**Comment by kanitw** [comment]
@domoritz Should we handle this?  I think we should assume that UI like Polestar / Voyager has enough contextual information.  or independent plot can have a title (#431) or tooltip (#525).  If you agree, we can close this.

**Comment by domoritz** [comment]
Yes, close for now. I think that you have to make a very conscious decision to use detail. 

Does compass ever recommend detail?

**Comment by kanitw** [comment]
> Does compass ever recommend detail? 

Yes -- for high cardinality categorical.
