### ISSUE TITLE
Yarn site broken

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3947]
```
node_modules/vega-lite/build/src/index.d.ts:26:25 - error TS2497: Module '"/Users/kanitw/Documents/_code/_idl/_visrec/vega-lite/node_modules/vega-lite/build/src/package"' resolves to a non-module entity and cannot be imported using this construct.

26 export { version } from './package.json';
```

**Comment by domoritz** [comment]
You need to copy `build` to `node_modules/vega-lite/build/`. This will fix itself when we make a release. I don't know any other way.

**Comment by kanitw** [comment]
What's the root cause for this, would this repeatedly occur or is it specific to current version?  If it's repeated, we should have a `postinstall` script to do symlink.

**Comment by kanitw** [comment]
Also, copying like you say still lead to this error.  

```
node_modules/vega-lite/build/src/header.d.ts:1:30 - error TS2307: Cannot find module '../node_modules/vega'.

1 import { TextBaseline } from '../node_modules/vega';
                               ~~~~~~~~~~~~~~~~~~~~~~
```

which mean I have to do more hacky copying

**Comment by domoritz** [comment]
Can you build with commonjs imports and try again?

We cannot use linking because then typescript will complain that you are overwriting the input. I don't know what a good solution to this problem is.

**Comment by domoritz** [comment]
Well, I know what the solution is. Dump vega-embed and write some version of embed ourselves.

**Comment by domoritz** [comment]
Wait, we already do that... let me check.
