### ISSUE TITLE
"bin": true on color in geoshape broken

### ISSUE THREAD

**Issue by kobben** [vega/vega-lite#3951]
When using `"bin": true` in a color encoding of a `geoshape`, Vega-Lite breaks.

 In a local embed installation ([see link](http://kartoweb.itc.nl/kobben/Vega-Lite/bin-broken.html)) it fails completely, with js errors:
```
ERROR TypeError: Cannot read property 'bev_dichth' of undefined
    at Object.eval (eval at nD (vega@3.0.10:1), <anonymous>:3:83)
    at vega@3.0.10:1
    at Array.forEach (<anonymous>)
    at ot (vega@3.0.10:1)
    at Ar.Cr.visit (vega@3.0.10:1)
    at ug.Y.transform (vega@3.0.10:1)
    at ug.Br.evaluate (vega@3.0.10:1)
    at ug.Br.run (vega@3.0.10:1)
    at xD.jr.run (vega@3.0.10:1)
    at xD.wD.run (vega@3.0.10:1)
    at vega@3.0.10:1
    at xD.jr.runAfter (vega@3.0.10:1)
    at u._pending.o.done (vega@3.0.10:1)
```

In the online vega-editor the binned legend shows, but no map appears...
![image](https://user-images.githubusercontent.com/1540072/42086774-724c920a-7b94-11e8-866e-549f2bdc19f8.png)

See Vega-Lite spec below, if you remove the `"bin": true` no problems (but no binning either, ofcourse)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.3.json",
  "width": 800,
  "height": 600,
  "data": {
    "url": "https://kartoweb.itc.nl/kobben/Vega-Lite/data/overijssel.geo.json",
    "format": {
      "type": "json",
      "property": "features"
    }
  },
  "projection": {
    "type": "mercator"
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "bin": true,
      "field": "properties.bev_dichth",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
I get a 404 when I try to load your last example in the editor. 

One solution may be to use quantize scale but I can see whether that's a viable solution when I get the example to work.

**Comment by kanitw** [comment]
@domoritz -- we have to fix #1092 first before using quantize.

**Comment by domoritz** [comment]
Totally. I just think that in this case it might work as a temporary fix that would for now need some manual tuning of other parameters as well. But it would be good to understand what's going wrong here.

**Comment by kobben** [comment]
Sorry, accidentily had removed the data geojson. Should be ok now...

**Comment by domoritz** [comment]
It seems to work in the editor now: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgEY6AZjoArWNwB2kADTgoAd0YATFtjAAOAAyXdESCkbV8ZgGzXbUI+jyYcoCHasAE5iZvYExGSkANboQXjc+siczPB0GmIx3OzsyBqkAGrCIgAykqRePqTcVEGMarDIYgzI3KrqWh52AGbcQRh4Zv4BdngAnoTIYWqaOnojkIRB3JPxY2HdyN7ByLCQ82AAvnqHHovLKsjweDxafgeQ45NhqMhB8N59+xCnepAYQWiYWorVgiHQzzOeXg3CMjA01CGDxhYi+9xGdnY8LMeCCrGQXQCkG6jCaRjCSxWbxuuzouQoAH04UhTITRhMpjhIABHVjoDQ3Hw3KjfALHH4gQ5AA

![image](https://user-images.githubusercontent.com/589034/46385993-d4e33980-c673-11e8-9d6e-78cef535b347.png)

@kobben Can we close the issue?

**Comment by domoritz** [comment]
I don't know what fixed it but it works with the latest Vega-Lite rc.
