### ISSUE TITLE
Clean up for 3.0

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3964]
@domoritz's TODO:
- [x] Deprecate old legend code

@kanitw's TODO:
- [x] Remove lat-long types 
- [x] Remove nonsense config.stack
- [x] Test composite mark thoroughly
- [x] Remove "in" filter

----

Other TODO

- [x] Clean up axis docs

**Comment by domoritz** [comment]
Should we also add prettier?

**Comment by domoritz** [comment]
- [ ] Drop auto parse? #3970
- [ ] Consider switching to es2015 import syntax #3924, cc @backspaces

**Comment by backspaces** [comment]
I'd really appreciate es2015 imports, my project depends on them. I'll get started using script tags and Observable which has several vega-lite examples. Thanks for considering this.

**Comment by domoritz** [comment]
We switched to es2015 imports.

**Comment by backspaces** [comment]
Nice, thanks. Vega itself is still script tags?

**Comment by domoritz** [comment]
No, it's es2015 imports as well.
