### ISSUE TITLE
Consider calculating tickStep from field_start and field_end

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3969]
In #3937, we're adding support for pre-binned field (binned outside of Vega-Lite).
Currently we requires user to specify 

1) bin start field
2) bin end field
3) axis's tickStep (bin's step size)

However, for uniform binning, 3) can be derive from 1) and 2).  Thus, I wonder if we should consider having a pipeline to calculate 1 and 2, especially when we extract transform from Vega-Lite to the outside. (That said, if we were to do it, I don't think this is a high priority task.) 

cc: @sirahd @domoritz @Saba9 -- any thoughts?

**Comment by domoritz** [comment]
If you want to derive 3 from 1 and 2, you need the bin count though.

**Comment by kanitw** [comment]
No, you don't. `step = binEnd - binStart` - we just need to check if the diff has min=max (otherwise, it's not an output from uniform binning).

**Comment by domoritz** [comment]
Oh binEnd, not binStop.

**Comment by kanitw** [comment]
> we just need to check if the diff has min=max (otherwise, it's not an output from uniform binning).

Since uniform binning is way more common, I wonder if `step = binEnd - binStart` is already a more sensible default (without having to do complex calculation)?

**Comment by kanitw** [comment]
Given tickStep is gone, I think this is no longer relevant.
