### ISSUE TITLE
For QxYear(T), if there are not many years, default size is too thin

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#398]
For example, try `YEAR` in BirdStrike

**Comment by kanitw** [comment]
Currently, `year` uses linear scale by default and there is no good way to determine bar’s width. 

However, if we override the scale to be ordinal, then it could be nice

```
{
  "description": "Line chart of Horsepower over time",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "Year", "type": "temporal", "timeUnit": "year", "scale": {"type": "ordinal"}},
    "y": {"field": "Horsepower", "type": "quantitative", "aggregate": "mean"}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/11923360/db3e4c04-a7d4-11e5-9935-4936404350b6.png)


The only question is whether `year`’s default scale should be `’linear'` or `’ordinal’`.  
Now I’m leaning toward ordinal ….

**Comment by kanitw** [comment]
@domoritz  any thought on this?  I think ordinal would makes default size of the bar nice but cause too wide chart when there are too many years.

**Comment by domoritz** [comment]
I feel that it depends on the marktype. For a bar chart, you want a fixed interval, so `ordinal`. But for a scatter plot maybe `linear` makes more sense.

**Comment by kanitw** [comment]
Good idea.  Fixed in #912.

**Comment by domoritz** [comment]
Do you know that if you have a commit message or pr message such as `Fixes #398`, issues are closed automatically?

**Comment by kanitw** [comment]
Do you know that I know but I still like to close them as soon as I got them fixed? :p

**Comment by domoritz** [comment]
Now I do :-P

**Comment by rgrzywinski** [comment]
It seems that `"timeUnit":"year"` has regressed. The following spec (from above):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Line chart of Horsepower over time",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "Year", "type": "temporal", "timeUnit": "year", "scale": {"type": "ordinal"}},
    "y": {"field": "Horsepower", "type": "quantitative", "aggregate": "mean"}
  }
}
```

results in the warning:
```
Channel x does not work with ordinal scale. We are using time scale instead.
```

The net result is that the plot has the same issue as was originally filed:

![image](https://cloud.githubusercontent.com/assets/813117/24326362/aec6cc3a-117a-11e7-8511-308dfe098b0a.png)

Also note that the years are offset by 1 which I will file separately. Please let me know if I should file a new issue rather than tacking this on to an existing closed issue.

**Comment by kanitw** [comment]
@rgrzywinski 

We updated scale types to match Vega 3 and D3 v4.  
Thus you should use `type: "point"` instead of `type: "ordinal"` in this case. 

We might consider adding better error fallback in the future.
