### ISSUE TITLE
Default color scale type for piecewise domain/range

### ISSUE THREAD

**Issue by zanarmstrong** [vega/vega-lite#3980]
If I set a color domain to [0.02, 0.04, 0.06, .5] and range to ['gold','white','white','black'] I would expect that values close to 2% would be gold, between 4% and 6% would be white, and between 6% and 50% would fade from white to black. I expect linear interpolation between the cut points, but for the mapping from number to color to respect the cut-points set between the domain and range (ie - 0.04 maps to "white"). 

color=alt.Color('rate:Q',
scale=alt.Scale(domain= [.02,.04,.06,.50],
range=['gold','white','white','black'])),

However, this doesn't seem to be the case. It appears that the min/max values of the domain are used to set the min/max of the color range. But, beyond that, the middle values of the domain are ignored. Instead, there is just a linear extrapolation from 'gold' to 'white' to 'white' to 'black' between the min/max of the domain, as if the domain was set to [0.02,0.18, 0.34,0.5]. It appears to be ignoring the 0.04 and 0.06 in the domain. 

<img width="575" alt="screen shot 2018-07-04 at 9 03 53 am" src="https://user-images.githubusercontent.com/7397271/42286905-32b941dc-7f69-11e8-8007-61b6fc6e6903.png">

I wasn't sure if this is an Altair or Vega-lite thing, but since I see the same issue when I open in the Vega-lite editor, I think it's a Vega-lite thing. 

Vega-lite spec
```json
{
"config": {"view": {"width": 400, "height": 300}},
"data": {
"url": "https://vega.github.io/vega-datasets/data/us-10m.json",
"format": {"feature": "counties", "type": "topojson"}
},
"mark": "geoshape",
"encoding": {
"color": {
"type": "quantitative",
"field": "rate",
"scale": {
"domain": [0.02, 0.04, 0.06, 0.5],
"range": ["gold", "white", "white", "black"]
}
}
},
"height": 300,
"projection": {"type": "albersUsa"},
"transform": [
{
"lookup": "id",
"from": {
"data": {
"url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
"format": {"type": "tsv"}
},
"key": "id",
"fields": ["rate"]
}
}
],
"width": 500,
"$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}
```

Example w/ Altair in Colab:
I've reproduced the bug in colab w/ Altair here, and described it in more detail: 
https://colab.research.google.com/drive/1odvUbN2E3ChyvUIkhdY8mf88G-UMhRrv#scrollTo=vUmI-q9h5rlr

Expected Behavior as shown in D3: 
https://bl.ocks.org/zanarmstrong/290b263913b6ca8ae9b0128ecf3e041e

D3 color scale
var color = d3.scaleLinear()
		.domain([2, 4, 6, 50])
    .range(["gold", "white", "white","black"]);

Note - the unemployment data in D3 and Vega come from different years, so aren't expected to be identical. However, they should still be similar enough for this purpose. 

<img width="1045" alt="screen shot 2018-07-04 at 9 02 30 am" src="https://user-images.githubusercontent.com/7397271/42286888-1e007666-7f69-11e8-8542-af078ec9c723.png">

**Comment by kanitw** [comment]
The problem is the default sequential scale doesn't support piecewise scale.  For now, please set the scale type to be "linear" and it will work.  

We'll see if we can fix the default type if piecewise domain and range are specified (or if we can adjust sequential scale to support piecewise scales.)

**Comment by kanitw** [comment]
Thanks for reporting!

**Comment by zanarmstrong** [comment]
Cool - I confirmed in the colab that this worked. Thanks for the quick reply. 

https://colab.research.google.com/drive/1odvUbN2E3ChyvUIkhdY8mf88G-UMhRrv#scrollTo=srF4s3EhMwgY

**Comment by kanitw** [comment]
Close #4017
