### ISSUE TITLE
Normalized Stacked Bar/Area Chart 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#402]
We now support `offset:normalize` but the following spec still doesn’t work yet since Vega's stack transform output domain in range `[0,1]`

```js
{
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "variety",
      "type": "N"
    },
    "y": {
      "field": "yield",
      "type": "Q",
      "aggregate": "sum"
    },
    "color": {
      "field": "site",
      "type": "N",
      "stack": {
        "offset": "normalize"
      }
    }
  },
  "data": {
    "url": "data/barley.json"
  }
}
```

### TODO

- [x] modify `domain` in scale.ts for channel `x` and `y` when stack is enabled and set domain to `[0,1]`
- [ ] write unit test

**Comment by kanitw** [comment]
We now support `offset:normalize` but the following spec still doesn’t work — need further investigation.  

```js
{
  "marktype": "bar",
  "encoding": {
    "x": {
      "name": "variety",
      "type": "N"
    },
    "y": {
      "name": "yield",
      "type": "Q",
      "aggregate": "sum"
    },
    "color": {
      "name": "site",
      "type": "N",
      "stack": {
        "offset": "normalize"
      }
    }
  },
  "data": {
    "url": "data/barley.json"
  }
}
```

**Comment by jheer** [comment]
In case it helps, keep in mind that normalized stacks always use the value
domain [0,1] for the full (stacked) height.

Also, from a syntax design perspective, should the stack property be on
"color" or on "y"? I would think that "y" might be more intuitive.

**Comment by ayush29feb** [comment]
Hey, so can you give me more context to the `domain` in the scale.ts file? There are very few inline comments to understand what is going on.

**Comment by domoritz** [comment]
We model scales after d3. Maybe https://github.com/mbostock/d3/wiki/Quantitative-Scales helps you understand what domain and range mean. If not, please ask again.

**Comment by kanitw** [comment]
Copied my comment from slack here

> It is producing `domain` property of a Vega scale
https://github.com/vega/vega/wiki/Scales#common-scale-properties

Better look at Vega scale docs first i think :)

**Comment by ayush29feb** [comment]
@kanitw when you say I should set the `domain : [0, 1]` do you mean I am indirectly adding 
```javascript
"scale" : {
   "domain" : [0, 1]
}
```
to the `y encoding` channel?

**Comment by kanitw** [comment]
Yep

From vega’s `scale.domain` doc: 
> For quantitative data, this can take the form of a two-element array with minimum and maximum values.

**Comment by ayush29feb** [comment]
I tried that it kinda gets weird. I am not sure how just `domain : [0,1]` will result in percentages. 

<img width="1279" alt="screen shot 2016-01-22 at 3 31 31 pm" src="https://cloud.githubusercontent.com/assets/8674376/12525918/3fd094e0-c11d-11e5-911a-9301f90d7378.png">

**Comment by kanitw** [comment]
https://github.com/vega/vega/wiki/Data-Transforms#-stack

> The "normalize" offset will compute percentage values for each stack point; the output values will be in the range [0,1].

**Comment by kanitw** [comment]
I modified vega stack_bar example successfully

```json
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 0, "y": 28, "c":0}, {"x": 0, "y": 55, "c":1},
        {"x": 1, "y": 43, "c":0}, {"x": 1, "y": 91, "c":1},
        {"x": 2, "y": 81, "c":0}, {"x": 2, "y": 53, "c":1},
        {"x": 3, "y": 19, "c":0}, {"x": 3, "y": 87, "c":1},
        {"x": 4, "y": 52, "c":0}, {"x": 4, "y": 48, "c":1},
        {"x": 5, "y": 24, "c":0}, {"x": 5, "y": 49, "c":1},
        {"x": 6, "y": 87, "c":0}, {"x": 6, "y": 66, "c":1},
        {"x": 7, "y": 17, "c":0}, {"x": 7, "y": 27, "c":1},
        {"x": 8, "y": 68, "c":0}, {"x": 8, "y": 16, "c":1},
        {"x": 9, "y": 49, "c":0}, {"x": 9, "y": 15, "c":1}
      ]
    },
    {
      "name": "stats",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["x"],
          "summarize": [{"field": "y", "ops": ["sum"]}]
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": [0,1]
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category10",
      "domain": {"data": "table", "field": "c"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x"},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {
        "data": "table",
        "transform": [
          {"type": "stack", "groupby": ["x"], "sortby": ["c"], "field": "y", "offset": "normalize"}
        ]
      },
      "properties": {
        "enter": {
          "x": {"scale": "x", "field": "x"},
          "width": {"scale": "x", "band": true, "offset": -1},
          "y": {"scale": "y", "field": "layout_start"},
          "y2": {"scale": "y", "field": "layout_end"},
          "fill": {"scale": "color", "field": "c"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

**Comment by ayush29feb** [comment]
Hey @kanitw are you sure the schema you gave above was correct?
I feel like it should have been the following
```js
{
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "variety",
      "type": "N"
    },
    "y": {
      "field": "yield",
      "type": "Q",
      "aggregate": "sum"
    },
    "color": {
      "field": "site",
      "type": "N"
    }
  },
  "config" : {
    "stack": {
      "offset": "normalize"
    }
  },
  "data": {
    "url": "data/barley.json"
  }
}
```

**Comment by kanitw** [comment]
@ayush29feb   I gave you a working Vega spec.    Your Vega-Lite spec is also correct, but it won't produce correct vega spec unless you fix this issue. :)

**Comment by kanitw** [comment]
Looks like you found a solution from the commit above.

Feel free to submit a pull request with an example vlspec when you're done :)
