### ISSUE TITLE
Customizing view background fill and stroke. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4025]
Currently the only way to customize single and layered views's background and border is via `config.view`, but there is no way to directly customize it in the spec. 

Similarly, there is no way to customize background for composite view.

One question is how should we support these at all.

**Comment by domoritz** [comment]
Bug?

**Comment by kanitw** [comment]
It's a bug because we should require users customize things via config.

**Comment by kanitw** [comment]
I actually run into a use case that I need this.  

A few alternatives:

1) Add `view` property to support `fill`, `fillOpacity`, `stroke`, `strokeOpacity`, ...


```js
{
  mark: 'bar',
  encoding: ...,
  view: {fill: ..., stroke: ...}
}
```

2) Just like 1), but call the property `background` 

```js
{
  mark: 'bar',
  encoding: ...,
  background: {fill: ..., stroke: ...}
}
```

This might be more sensible than 1) since `config.view` has `width` and `height`, but this object won't.  (`width` and `height` are already top-level properties). 

3) Instead of nesting them, add them to the top-level. 


```js
{
  mark: 'bar',
  encoding: ...,
  fill: ..., stroke: ...
}
```

I think 3) is bad as these properties will be confused with encoding properties.  Currently I prefer 2.  

cc: @domoritz @arvind @jakevdp @jheer -- Any comments?

**Comment by kanitw** [comment]
NVM, I investigate further and found that we already have `background:string` as a top-level property. So it’s totally reasonable to promote it to be every spec’s property and support a definition object in addition to string.

Summary: 2) is good.

**Comment by kanitw** [comment]
Hmm, the problem is that top-level `background` is the canvas-wide background (like in Vega).  If we want to limit the background to just the view, then we need a different property name.  Thus, I think `view` (1) might be a more sensible property name.

**Comment by kanitw** [comment]
The reason that I think `view` is better than other name is that we already use the same keyword inside config.

**Comment by kanitw** [comment]
This will be handled in https://github.com/vega/vega-lite/pull/4463.  Let's discuss more there.
