### ISSUE TITLE
Log colour scales don't seem to choose sensible default domains/ranges

### ISSUE THREAD

**Issue by claresloggett** [vega/vega-lite#4037]
Summary: If I use a log colour scale, there is very little variation across the colour range. If I log-transform the variable myself, or, oddly, set the colour range for the scale, I get a much better result.

I assume it is about the range being chosen by default in this case. I don't have this issue with linear colour scales, and don't see any analogous issue with using a log scale on a spatial axis.

I originally raised this issue for Altair at https://github.com/altair-viz/altair/issues/1014 . You can see the Python code for the example there - I've extracted the JSON below from that as I don't usually use vega-lite directly. I hope it's what's needed. 

@jakevdp (https://github.com/altair-viz/altair/issues/1014) has pointed out that this behaviour seems to occur in Vega 4 but not Vega 3.

Here's a toy example:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json",
  "config": {"view": {"height": 300, "width": 400}},
  "vconcat": [
    {
      "data": {
        "values": [
          {"c": 1, "x": 1, "y": 1},
          {"c": 10, "x": 2, "y": 2},
          {"c": 100, "x": 3, "y": 3},
          {"c": 1000, "x": 4, "y": 4}
        ]
      },
      "encoding": {
        "color": {
          "field": "c",
          "scale": {"type": "log"},
          "type": "quantitative"
        },
        "x": {"field": "x", "type": "quantitative"},
        "y": {"field": "y", "type": "quantitative"}
      },
      "mark": {"size": 90, "type": "circle"},
      "title": "A: log scale"
    },
    {
      "data": {
        "values": [
          {"c": 1, "x": 1, "y": 1},
          {"c": 10, "x": 2, "y": 2},
          {"c": 100, "x": 3, "y": 3},
          {"c": 1000, "x": 4, "y": 4}
        ]
      },
      "encoding": {
        "color": {"field": "logc", "type": "quantitative"},
        "x": {"field": "x", "type": "quantitative"},
        "y": {"field": "y", "type": "quantitative"}
      },
      "mark": {"size": 90, "type": "circle"},
      "title": "B: log transform, linear scale",
      "transform": [{"as": "logc", "calculate": "log(datum.c)"}]
    },
    {
      "data": {
        "values": [
          {"c": 1, "x": 1, "y": 1},
          {"c": 10, "x": 2, "y": 2},
          {"c": 100, "x": 3, "y": 3},
          {"c": 1000, "x": 4, "y": 4}
        ]
      },
      "encoding": {
        "color": {
          "field": "c",
          "scale": {"range": ["red", "blue"], "type": "log"},
          "type": "quantitative"
        },
        "x": {"field": "x", "type": "quantitative"},
        "y": {"field": "y", "type": "quantitative"}
      },
      "mark": {"size": 90, "type": "circle"},
      "title": "C: log scale with range set"
    },
    {
      "data": {
        "values": [
          {"c": 1, "x": 1, "y": 1},
          {"c": 10, "x": 2, "y": 2},
          {"c": 100, "x": 3, "y": 3},
          {"c": 1000, "x": 4, "y": 4}
        ]
      },
      "encoding": {
        "color": {
          "field": "logc",
          "scale": {"range": ["red", "blue"], "type": "linear"},
          "type": "quantitative"
        },
        "x": {"field": "x", "type": "quantitative"},
        "y": {"field": "y", "type": "quantitative"}
      },
      "mark": {"size": 90, "type": "circle"},
      "title": "D: log transform, linear scale, range set",
      "transform": [{"as": "logc", "calculate": "log(datum.c)"}]
    }
  ]
}
```

![altair_logcolourbug](https://user-images.githubusercontent.com/1815107/42778907-43175a56-8904-11e8-97ff-a484a0cd4a43.png)

The problem occurs in Plot A, where I use a log colour scale and do not set the range. I would expect A to look very similar to B, where I use a log data transform instead of a scale transform. As you can see though the colour bar covers a pretty small range - Plot B, which uses a transform instead of a scale, is much better. Conversely, Plot C does look very similar to D. The only difference is in these two plots I have set the scale range explicitly.

**Comment by domoritz** [comment]
This is a but in Vega-Lite and let me explain what is happening.

Vega color scales for quantitative data can be sequential, linear, or log (and some others but let's ignore them for now. The range of a sequential scale is an array of color values. For linear and log scales, Vega assumes that the range is two values and it will interpolate between the two. If we provide a color scheme, Vega will interpolate between the first two values. 

<img width="1003" alt="screen shot 2018-07-16 at 12 42 40" src="https://user-images.githubusercontent.com/589034/42779646-db739c6a-88f5-11e8-82b6-4c991c6c6ca1.png">
<img width="1006" alt="screen shot 2018-07-16 at 12 42 30" src="https://user-images.githubusercontent.com/589034/42779649-deaff202-88f5-11e8-9d89-b70bdf34fc82.png">

**Comment by domoritz** [comment]
For now the right solution is to change the scale range if you change the scale type. We can provide better defaults in the future.

**Comment by domoritz** [comment]
@kanitw @jheer What do you think about this issue? Should Vega-Lite generate a different scale range for linear and logarithmic scales (e.g. `["white", "steelblue"]`) or should vega support sequential log scales?

**Comment by kanitw** [comment]
I'm fine with different scale range. The question is how to pick one for log scales.

**Comment by domoritz** [comment]
And linear `scales`. I think we should choose the same. I think something like https://vega.github.io/vega/docs/schemes/#blues is reasonable.

**Comment by domoritz** [comment]
![image](https://user-images.githubusercontent.com/589034/42789219-d738d174-8918-11e8-86eb-87c84139158a.png)

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4040
