### ISSUE TITLE
Off-by-one error in year-month timeUnit

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4044]
The following specification has dates starting and ending in the month of June, but the chart renders with data starting and ending in the month of May. Reported in https://github.com/altair-viz/altair/issues/1027
```json
{
  "data": {
    "values": [
      {"date": "2017-06-01", "pct_change_rounded": 0},
      {"date": "2017-07-01", "pct_change_rounded": 0.1},
      {"date": "2017-08-01", "pct_change_rounded": 0.4},
      {"date": "2017-09-01", "pct_change_rounded": 0.5},
      {"date": "2017-10-01", "pct_change_rounded": 0.1},
      {"date": "2017-11-01", "pct_change_rounded": 0.3},
      {"date": "2017-12-01", "pct_change_rounded": 0.2},
      {"date": "2018-01-01", "pct_change_rounded": 0.5},
      {"date": "2018-02-01", "pct_change_rounded": 0.2},
      {"date": "2018-03-01", "pct_change_rounded": -0.1},
      {"date": "2018-04-01", "pct_change_rounded": 0.2},
      {"date": "2018-05-01", "pct_change_rounded": 0.2},
      {"date": "2018-06-01", "pct_change_rounded": 0.1}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "type": "ordinal",
      "axis": {"format": "%b %y"},
      "field": "date",
      "timeUnit": "yearmonth"
    },
    "y": {"type": "quantitative", "field": "pct_change_rounded"}
  }
}
```
![visualization 9](https://user-images.githubusercontent.com/781659/42825192-5830da10-8996-11e8-9dc4-7e15056c97da.png)

**Comment by kanitw** [comment]
This is because [Javascript parses time in an ISO into UTC time](https://vega.github.io/vega-lite/docs/timeunit.html#input).
Since Vega-Lite doesn't look at the data, we only always output local time by default even if the input is in UTC time. 

If you use `utcyearmonth`, then this would work correctly.  

```
{
  "data": {
    "values": [
      {"date": "2017-06-01", "pct_change_rounded": 0},
      {"date": "2017-07-01", "pct_change_rounded": 0.1},
      {"date": "2017-08-01", "pct_change_rounded": 0.4},
      {"date": "2017-09-01", "pct_change_rounded": 0.5},
      {"date": "2017-10-01", "pct_change_rounded": 0.1},
      {"date": "2017-11-01", "pct_change_rounded": 0.3},
      {"date": "2017-12-01", "pct_change_rounded": 0.2},
      {"date": "2018-01-01", "pct_change_rounded": 0.5},
      {"date": "2018-02-01", "pct_change_rounded": 0.2},
      {"date": "2018-03-01", "pct_change_rounded": -0.1},
      {"date": "2018-04-01", "pct_change_rounded": 0.2},
      {"date": "2018-05-01", "pct_change_rounded": 0.2},
      {"date": "2018-06-01", "pct_change_rounded": 0.1}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "type": "ordinal",
      "axis": {"format": "%b %y"},
      "field": "date",
      "timeUnit": "utcyearmonth"
    },
    "y": {"type": "quantitative", "field": "pct_change_rounded"}
  }
}
```

**Comment by kanitw** [comment]
This is a bit annoying, but there is no good way to solve this in Vega-Lite unless we revamp how Vega works with time.

**Comment by jakevdp** [comment]
Thanks

**Comment by ijlyttle** [comment]
Hi all,

I'm not sure if this is the right place to start such a conversation (maybe you can direct me), but how feasible might it be to revamp how Vega deals with time?

My motivation is that I am trying to get my company to adopt Vega/Vega-Lite, but we are an international company, with international customers. For example, it would not be unusual for someone in `"Europe/Paris"` to want to see data in the context of `"America/New_York"`, regardless of the timezone of their browser. 

Accordingly, I see these sorts of time-zone issues as being the principal barrier to eventual widespread adoption within my company.

I know this is not a small problem to tackle, so I do not bring this up lightly. Of course, I would be happy to pitch in. Although I (currently) lack in JavaScript skills, addressing this issue would motivate me to (try to) get up to speed.  

I am happy to continue this conversation wherever. This is the sort if thing I can (pardon the pun) make the time to participate in.

Thanks!

**Comment by domoritz** [comment]
We're having a discussion about this in the vega slack in #altair. 

The short story is that JavaScript date parsing is odd and it's hard to get around that.

**Comment by domoritz** [comment]
Also https://github.com/altair-viz/altair/issues/1027

**Comment by jakevdp** [comment]
@ijlyttle are you creating charts from Vega-Lite directly, or using Altair?

**Comment by jakevdp** [comment]
I think the solution is to use fully-specified ISO-8601 dates everywhere.

**Comment by ijlyttle** [comment]
I have been creating using Altair, but I have been careful (or at least I think I have been careful) to use ISO-8601 whenever I can.

I agree that ISO-8601 is the only way to maintain sanity 😬

Let me see what I can reproduce.

**Comment by ijlyttle** [comment]
@jakevdp Just to say thanks for the conversations across the various issues. I am glad to see Altair moving towards ISO formatting. 

I want to think about different ways of handling time when building a spec - your local-time way being one of them, and to open an issue to see it there's a way to support many ways of doing things. I think I want to take some time to go through all of the slack and github conversations first, to make sure I get all the different perspectives.

**Comment by jakevdp** [comment]
Thanks @ijlyttle – and thanks for your comments and feedback.

One thing that would be worth thinking about is whether we can support ``datetime64[ns,utc]`` as well as ``datetime64[ns]`` in a streamlined way. That way people could choose UTC or not within Python, and everything else should just flow from there.

**Comment by iliatimofeev** [comment]
> whether we can support datetime64[ns,utc]

I guess Altair is already support timestamp with timezone including 'utc'. https://github.com/altair-viz/altair/issues/926

**Comment by jakevdp** [comment]
It supports them in the sense that it doesn't raise an error if you use UTC dates. I'm talking about supporting them in the sense of propagating the UTC property through to the vega-lite spec.

**Comment by mattijn** [comment]
Little comment regarding timezones: probably best bet to have timezones
based on a package that implements the Olson/IANA timezones database (like
luxon or moment.js), but realise that some timezones still using POSIX
standard and not ISO 8601.

Which I faced last week in Python:
https://stackoverflow.com/q/51542167/2459096

**Comment by jakevdp** [comment]
Fix for this in Altair: https://github.com/altair-viz/altair/pull/1053
