### ISSUE TITLE
Graph subtitle

### ISSUE THREAD

**Issue by gwdekker** [vega/vega-lite#4055]
Vega combined with altair is fantastic to quickly create great looking charts! One small feature that I am missing is the possibility to have a subtitle for a graph. More specifically, to be able to regenerate a plot in  [538 style](https://www.dataquest.io/blog/making-538-plots/) I think this would be the only main feature missing.

**Comment by kanitw** [comment]
Great feature request. I agree this could be a very nice addition, but this would require Vega to add support for subtitle first. https://github.com/vega/vega/issues/782 is the relevant issue.

**Comment by gwdekker** [comment]
Thanks for the link to the relevant vega issue, will follow along!

**Comment by aaronbarzilai** [comment]
Posted this on 782 but realized it might make more sense on this thread.  Is there a temp workaround like adding a \n or <br> tag to force a second line in the title?

**Comment by domoritz** [comment]
Vega does not support line breaks. You have to add separate text marks for now.

**Comment by domoritz** [comment]
Subtitle support is coming in https://github.com/vega/vega-lite/pull/5473
