### ISSUE TITLE
Vega-Embed giving build error Cannot find name 'Extract' and 'Exclude'

### ISSUE THREAD

**Issue by vishalbedre** [vega/vega-lite#4059]
I created angular 6 application (Using node). In this application I used vega-embed module. It is giving me compilation error.

**import embed from 'vega-embed';**
 I also changed code in util.d.ts  **import stableStringify = require('json-stable-stringify')** but giving following error

**ERROR in node_modules/vega-lite/build/src/util.d.ts(58,41): error TS2304: Cannot find name 'Extract'. node_modules/vega-lite/build/src/util.d.ts(73,58): error TS2304: Cannot find name 'Exclude'.**

**Comment by domoritz** [comment]
What version of ts are you using?

**Comment by vishalbedre** [comment]
I install latest one using npm install -g typescript.  
>tsc -v
Version 1.0.3.0

**Comment by domoritz** [comment]
Exclude was added in TS 2.8. 

I'm going to close this issue since it's unrelated to this module.

**Comment by vishalbedre** [comment]
Sorry but if I am using + typescript@2.7.2 It is still giving me same 

**ERROR in node_modules/vega-lite/build/src/util.d.ts(58,41): error TS2304: Cannot find name 'Extract'. node_modules/vega-lite/build/src/util.d.ts(73,58): error TS2304: Cannot find name 'Exclude'.**

**Comment by domoritz** [comment]
You either have to add the typings manually or upgrade to Typescript 2.8+. You can file an issue with angular about updating typescript.

**Comment by vishalbedre** [comment]
Sure .. Thank you
