### ISSUE TITLE
Create a Roadmap

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4078]
We intend to create a `Roadmap.md` file. To seed it initially, let's collect some things here. Feel free to comment if you think we have missed something. 

## Goals

We want Vega-Lite to become a standard langauge for decarative Data Visualization across different programming languages. Morover, we want Vega-Lite together with Vega to be a standard language in the visualization reserch community. A core principle is the declarative grammar of visualization and interactions and compiling to low level Vega to allow maximum flexibility. To this end, it is important to extend the supported features, refine existing feature and make sure they are complete within our grammar, and improving scalability to larger datasets. 

## Planned to work on or being worked on

* Interactions with Maps (???)
* Facet Wrap (#3270)

## We have figured out the details but don't have the bandwidth to implement it

* Jittering (#396)
* Join aggregates (#3912)
* Arc Marks (#408)

## No timeline yet

* Support Vega timers (#4060)
* Supporting Layouts (#1872)
* Support in Wikipedia (https://phabricator.wikimedia.org/T165118)

See https://github.com/vega/vega/issues/1377 for Vega equivalent

**Comment by kanitw** [comment]
Replaced with #4096
