### ISSUE TITLE
Binned bar chart bar too wide

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4088]
<img width="870" alt="screen shot 2018-07-27 at 12 29 27" src="https://user-images.githubusercontent.com/589034/43342769-c4033706-9198-11e8-9e25-adc55c93488a.png">

in https://vega.github.io/vega-lite/docs/bin.html#binned looks funny

**Comment by kanitw** [comment]
Hmm, looks reasonable to me:

![image](https://user-images.githubusercontent.com/111269/43345170-57313b7e-91a1-11e8-9175-52510f7c9670.png)

**Comment by domoritz** [comment]
Had to hard reload...
