### ISSUE TITLE
Typings are broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4090]
<img width="720" alt="screen shot 2018-07-27 at 12 58 43" src="https://user-images.githubusercontent.com/589034/43343922-e37515b0-919c-11e8-99d7-0e6a2971450e.png">

Why is my local path in there?

**Comment by kanitw** [comment]
lol --- wonder if we should have a post processing script to clean this up (for now)?

**Comment by domoritz** [comment]
I think this is https://github.com/Microsoft/TypeScript/pull/25110

**Comment by domoritz** [comment]
Yeah, it seems to work in Typescript 3.1. We can just switch to that.
