### ISSUE TITLE
Remove Number Parsing

### ISSUE THREAD

**Issue by Saba9** [vega/vega-lite#4101]
We don't really need to parse numbers because Vega automatically casts to numbers in scales and transforms. 

Depends on 
* Cast input to numbers in sum aggrgeates
* Cast input to numbers in min/max aggregates

**Comment by domoritz** [comment]
Are the depends on points something we have issues for? Can you search for them or make issues?

**Comment by domoritz** [comment]
@Saba9 I don't think this is blocked, is it?

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/issues/4988 is presenting a conflicting argument. 

What's the deal for this issue?  Is it blocked? Should it be done?

**Comment by domoritz** [comment]
We've already done this.
