### ISSUE TITLE
3.0.0-rc0: strange schema for FoldTransform.as

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4105]
The [schema definition](https://github.com/vega/schema/blob/master/vega-lite/v3.0.0-rc0.json#L3784-L3809) for ``FoldTransform.as`` is a bit strange. It's supposed to be a two-element array, correct? So what is the purpose of ``additionalItems: anyOf: ["string", "string"]``?

I'm wondering if this is indicative of some mis-specification in the typescript.

**Comment by jakevdp** [comment]
Also, I'm not certain what vega-lite version the currently-live docs refer to, but the described syntax of the fold transform there does not match the schema: https://vega.github.io/vega/docs/transforms/fold/

**Comment by domoritz** [comment]
Here is the type in Typescript: https://github.com/vega/vega-typings/blob/e22ed3faa7dc7e9bba5607c249f526f98de23436/types/spec/transform.d.ts#L186

The type is a bit odd but not wrong. It says that we want an array with at least two items and the items should be strings. Any additional item should also be a string. 

We can try to make the schema more strict.

**Comment by jakevdp** [comment]
Agree that it's technically correct but a bit odd.

What caught me off-guard is the use of an array of schemas for items. It's currently the only place in the vega-lite schema that that is used, and the fact that it led to such a strange schema made me wonder if the schema building tool was not handling it properly.

**Comment by jakevdp** [comment]
Maybe changing ``as?: [string, string];`` to ``as?: string[];`` would give a cleaner result?

**Comment by domoritz** [comment]
I'll look into it over at https://github.com/vega/ts-json-schema-generator/issues/40.

**Comment by domoritz** [comment]
The typings now come from Vega-Typings and it would be nice to keep the strict TS typings.

**Comment by kanitw** [comment]
> It says that we want an array with at least two items and the items should be strings. Any additional item should also be a string.

This is a bit inaccurate. The type there means there should b __strictly two items_, and each of them should be a string.

**Comment by kanitw** [comment]
I see.   Sounds like a bug that `additionalItem` is included.

**Comment by domoritz** [comment]
It's not wrong, just imprecise.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4107
