### ISSUE TITLE
Support nested input data

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4110]
@dhuppenkothen mentions a use case where there is a time series associated with some selection.  Currently, this requires some duplication of the data and can be inefficient for large datasets.  

(@dhuppenkothen --please expand on this / provide example so we can think more about it)

**Comment by dhuppenkothen** [comment]
Here's an example from astronomy. The [ZTF telescope](https://www.ztf.caltech.edu) observes certain patches of sky repeatedly. So for a given star, we have e.g. its position (and perhaps some additional information, like its temperature or mass or something like that) and also a time series of how its brightness changes over time. 

Imagine I'd want to plot the temperature versus the mass for a bunch of stars, and then e.g. plot the time series from ZTF for a star I click on a point in this plot. 

If my time series for each star has 200 data points, and I have 100 stars, that's an unfolded table of 20000 data points, where the properties that don't change from one measurement to the next for a given star (like the temperature and mass and position in the sky) are duplicated 200 times for each star, which ends up making huge data files. 

It'd be super useful if the data structures used in vega-lite could be nested, something like this:

`
data = [{"pos_x": 10, "pos_y": 100, "temp": 6500, "timeseries":[{"time": 0, "mag":15}, {"time":1, "mag":16}, {"time":2, "mag":16.5}]}, {"pos_x: ...}]
`

**Comment by kanitw** [comment]
@domoritz Did we support this already? If so, document in data.md?

**Comment by domoritz** [comment]
We support it by flattening with https://vega.github.io/vega-lite/docs/flatten.html. I think that's as far as we will support for now. Operating on nested data is a can of worms I am not willing to open anytime soon.
