### ISSUE TITLE
Flatten transformation is broken

### ISSUE THREAD

**Issue by VladiTD** [vega/vega-lite#4113]
Hi Team,

Flatten transformation seems to be broken in Vega-Lite but Vega works fine.
All examples return the error:
[Warning] Ignoring an invalid transform: {"as":["foo","bar"],"flatten":["foo","bar"]}
https://vega.github.io/vega-lite/docs/flatten.html

![image](https://user-images.githubusercontent.com/26317357/43624111-a5f18c8c-9728-11e8-8770-6eae881e3f1d.png)

Regards,
Vlad

**Comment by domoritz** [comment]
Flatten in Vega-Lite 3. I'm working on a release right now so check again in an hour.
