### ISSUE TITLE
errorband tooltip flipped on x axis

### ISSUE THREAD

**Issue by tnolli** [vega/vega-lite#4120]
Please:
- [X] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
* I have found none opened
- [X] Describe how to reproduce the bug / the goal of the feature request.
* In the Error Band documentation page (https://vega.github.io/vega-lite/docs/errorband.html#compare-to-errorbar) hovering the Error band chart: if you enter from right, it shows the tooltip for the elements on the left (and vice versa).
I.e.: entering from right, you see "Jan, 01 1970" but you should see "Jan, 01 1982" (the same is true for the numeric values; they are "swapped"); entering from left, you see 1982 data
- [X] Use the latest versions of Vega and Vega-Lite.
- [X] Provide an example spec in JSON, wrapped by triple backticks like this:
* The Issue is present in the online docs
- [X] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. https://bit.ly/vega-lite-blocks)
* See https://vega.github.io/vega-lite/docs/errorband.html#compare-to-errorbar

**Comment by domoritz** [comment]
I think this may be a Vega issue: https://github.com/vega/vega/issues/1201

**Comment by domoritz** [comment]
I'm going to close this until we find out.
