### ISSUE TITLE
Add symlog scale

### ISSUE THREAD

**Issue by mattpitkin** [vega/vega-lite#4127]
Sometimes you have data that spans a many orders of magnitude across both positive and negative values. It is often useful to be able to plot both the positive and negative ranges on a logarithmic scale, with a linear range spanning between them. This is done in, e.g., Matplotlib, using the `symlog` [scaling](https://matplotlib.org/gallery/scales/symlog_demo.html).

Would adding something like this be possible in Vega-Lite?

Refs altair-viz/altair#1077.

**Comment by domoritz** [comment]
Thanks for the issue. Before we can add this to Vega-Lite, we need support for this in Vega. Can you file an issue there and link to this one?

**Comment by mattpitkin** [comment]
@domoritz - thank. Yes, I'll file issue in the Vega repo.

**Comment by domoritz** [comment]
Closing this until we get support in D3 and Vega.

**Comment by mattpitkin** [comment]
@jheer once vega/vega#1544 appears in the next Vega release, will it be possible/simple to also add symlog support into vega-lite?

**Comment by domoritz** [comment]
Yes, we will add it to Vega-Lite 3.

**Comment by domoritz** [comment]
You're very welcome to send a PR to update Vega-Lite to the new scales as well.

**Comment by mattpitkin** [comment]
Thanks

**Comment by mattpitkin** [comment]
I'll take a look and see if it's reasonably obvious hour to add it. I
assume it would be along the lines of adding it as another continuous scale
option in
https://github.com/vega/vega-lite/blob/master/src/scale.ts?

**Comment by domoritz** [comment]
It might be a bit more involved since Vega's scales are different now. It's not just about adding a new scale type but updating the existing onces as well.
