### ISSUE TITLE
The fold transformation does not work on ObservableHQ

### ISSUE THREAD

**Issue by nicola** [vega/vega-lite#4130]
I have written up an observable showing that neither `vega-embed` nor `vega-lite` has the transformation `fold` implemented and working.

I am lost on what the cause could be, there you go: https://beta.observablehq.com/@nicola/fold-does-not-work-on-vega-lite

It works however in the vega editor (see link)

**Comment by domoritz** [comment]
We have to update to Vega-Lite 3 but a bug in typescript is preventing the release right now (beyond my control). I'm working on it and will make sure it's gets out asap.
