### ISSUE TITLE
Error bar macro for value + error

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4131]
Commonly users come with data of the form `value, error`. Our errorbar macro should support this use case and not require users to create a transform. 

```
mark: "errorbar",
encoding: {
  y: {field: value, type: "quantitative"},
  yError: {field: error, type: "quantitative"}
}
```

```json
{
  "data": {
    "values": [
      {
        "yield_error": 3,
        "yield": 32.4,
        "variety": "Glabron"
      },
      {
        "yield_error": 3.2,
        "yield": 30.96667,
        "variety": "Manchuria"
      },
      {
        "yield_error": 1.2,
        "center": 33.966665,
        "variety": "No. 457"
      },
      {
        "yield_error": 2,
        "yield": 30.45,
        "variety": "No. 462"
      }
    ]
  },
  "layer": [
    {
      "mark": "errorbar",
      "encoding": {
        "x": {
          "field": "yield",
          "type": "quantitative",
          "scale": {"zero": false},
          "title": "yield"
        },
        "xError": {"field": "yield_error", "type": "quantitative"},
        "y": {"field": "variety", "type": "ordinal"}
      }
    },
    {
      "mark": {
        "type": "point",
        "filled": true,
        "color": "black"
      },
      "encoding": {
        "x": {
          "field": "yield",
          "type": "quantitative"
        },
        "y": {"field": "variety", "type": "ordinal"}
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
Here is a super short alternative to the thing above but I remember @kanitw and @jheer had some convincing reason why we shouldn't do it.

```json

{
  "data": {
    "values": [
      {
        "yield_error": 3,
        "yield": 32.4,
        "variety": "Glabron"
      },
      {
        "yield_error": 3.2,
        "yield": 30.96667,
        "variety": "Manchuria"
      },
      {
        "yield_error": 1.2,
        "center": 33.966665,
        "variety": "No. 457"
      },
      {
        "yield_error": 2,
        "yield": 30.45,
        "variety": "No. 462"
      }
    ]
  },
  "mark": {
    "type": "errorbar",
    "point": {
      "filled": true,
      "color": "black"
    }
  },
  "encoding": {
    "x": {
      "field": "yield",
      "type": "quantitative"
    },
    "xError": {"field": "yeld_error", "type": "quantitative"},
    "y": {"field": "variety", "type": "ordinal"}
  }
}
```

**Comment by domoritz** [comment]
@g3o2 fixed, thanks

**Comment by domoritz** [comment]
@chanwutk and I think we decided not to support the super short version yet because you could for example have a `point: true` inside a line mark def. We can also always support the shorter syntax in the future but the errorbar syntax we currently have makes sense regardless.

**Comment by domoritz** [comment]
@jakevdp if you like the spec in https://github.com/vega/vega-lite/issues/4131#issue-350983639, we will implement it.

**Comment by domoritz** [comment]
> how would we support asymmetric errorbars? Maybe yError can be a list of fields of length 2 speficying lower and upper error?

We would still support `y` and `y2`. Like in https://vega.github.io/vega-lite/docs/errorbar.html#pre-aggregated-usage

> ability to pass an encoding value in addition to a field would be useful for constant errorbars.

Value will be supported just like in any other encoding. @chanwutk we should make sure to test this. 

> do you imagine supporting both xError and yError in a single plot, to create +-shaped multi-errorbars without manual stacking?

We thought about this for error bars already and decided not to support this for now. It seems like an interesting use case and we will revisit it when the dust has settled a bit.

**Comment by domoritz** [comment]
To make it clear: we are not changing support for error bars as it's already documented. We just add another way to specify errors when they are symmetric.

**Comment by kanitw** [comment]
The question is whether the length of the error bar is `2*error` or just `error`.  If a given input `error` is standard error, then the length should be `2*error`.  

> how would we support asymmetric errorbars? Maybe yError can be a list of fields of length 2 speficying lower and upper error?

I'd say that having `yError` and `yError2` would make more sense. (A list may mistakenly suggest that there can be more than two values.) 

> ability to pass an encoding value in addition to a field would be useful for constant errorbars.

Definitely. 

> do you imagine supporting both xError and yError in a single plot, to create +-shaped multi-errorbars without manual stacking?

That will make the code unnecessarily complex.  I'd vote for no, at least for the MVP.  We can revise this if a lot of users asks for it.

**Comment by kanitw** [comment]
For the [short version](https://github.com/vega/vega-lite/issues/4131#issuecomment-413355259), it's actually @domoritz who suggested that people want to add error bar to points, not the other way around.

**Comment by domoritz** [comment]
> I'd say that having yError and yError2 would make more sense. (A list may mistakenly suggest that there can be more than two values.)

I think y and y2 already do this. No need to invent new channels.

**Comment by kanitw** [comment]
> I think y and y2 already do this. No need to invent new channels.

Well, if your argument is that yError reduce the need to do calculate, I don't buy that for asymmetric errorbar, you have to still do calculate.

**Comment by domoritz** [comment]
I don't understand. A symmetric error is defined by an error value (the +- from a value). An asymmetric error is defined by a lower and an upper value.

**Comment by domoritz** [comment]
> Or upper delta and lower delta?

I have never seen that and would say it's rare enough that we can ask users to sue calculate.

**Comment by g3o2** [comment]
> The question is whether the length of the error bar is 2*error or just error. 

Actually, it'd be best if the user specified the `t` to apply. Depending on the number of observations, the acceptable error margin and the underlying distribution, the factor may be well different from 2.

**Comment by g3o2** [comment]
Regarding the interface, ggplot uses the approach of y2/x2 rather than yerror.

**Comment by jakevdp** [comment]
> > Or upper delta and lower delta?

> I have never seen that and would say it's rare enough that we can ask users to use calculate.

A lower and upper delta is exactly how I've always thought of an asymmetric errorbar, and I would be quite surprised if a visualization tool didn't make that use case the default. I think others coming from a scientific viz background would feel similarly.

**Comment by jakevdp** [comment]
e.g. matplotlib lets you set xerr to a single array for a symmetric errorbar (x+xerr, x, x-xerr) or to a pair of arrays for asymmetric errorbars (x + xerr[1], x, x - xerr[0])

**Comment by jakevdp** [comment]
If people want to draw a line from a lower point to an upper point, we already have ``{'mark': 'rule'}`` where ``y`` and ``y2`` behave exactly like that.

I know that some encodings allow a list of fields (e.g. order, tooltip, etc.). Would it be possible to make ``y2`` accept a list of fields for this case? Then the errorbar syntax could look something like this for symmetric errorbars
```
{
  "mark": "errorbar",
  "encodings": {
    "x": {"field": "x", ...}
    "y": {"field": "y", ...}
    "y2": {"field": "yerr", ...}
  },
  ...
}
```
or like this for asymmetric errors:
```
{
  "mark": "errorbar",
  "encodings": {
    "x": {"field": "x", ...}
    "y": {"field": "y", ...}
    "y2": [{"field": "yerr_lower", ...},
           {"field": "yerr_upper", ...}]
  },
  ...
}
```

**Comment by domoritz** [comment]
> If people want to draw a line from a lower point to an upper point, we already have {'mark': 'rule'} where y and y2 behave exactly like that.

Errorbar also supports ticks for the ends so it's not just a rule. However, if having two errors for asymmetric errors is common, we could support that with an array for the `error` channel (two field defs) like we support tooltips. I think that's less confusing than supporting arrays in y2.

**Comment by g3o2** [comment]
Weren't macros initially supposed to be just shortcuts for stuff that could otherwise be designed with vega-lite's building blocks? i.e. without building a any new interface around it

**Comment by kanitw** [comment]
> Errorbar also supports ticks for the ends so it's not just a rule. However, if having two errors for asymmetric errors is common, we could support that with an array for the error channel (two field defs) like we support tooltips. I think that's less confusing than supporting arrays in y2.

I think `error` channel without specific axis and with array support is confusing.  Better make it clear whether it's `yError` or `xError` and use yError2 if there are asymmetric errors. This will be more consistent with how we design encoding channels (e.g., provide default x2 if x2 is not specified.)  Unlike `tooltip` and `detail` that can have as many fields as you want, error could only have two so we definitely shouldn't use array.  

The question is whether the x/yError2 should take positive or negative number as input.  (I think negative values is better since that means x/yError and x/yError2 can be used interchangeably without fixing which one is upper/lower (just like how `x` and `x2` work for ranged marks.)

**Comment by domoritz** [comment]
I fixed my message to use `x/yError`.

**Comment by domoritz** [comment]
> Weren't macros initially supposed to be just shortcuts for stuff that could otherwise be designed with vega-lite's building blocks? i.e. without building a any new interface around it

Yes and you can already construct errorbars if you use calculate. Does this address your question?

**Comment by g3o2** [comment]
oh, I see. So, you could invoke the same strategy for the value/error use case ...

**Comment by domoritz** [comment]
Unless @arvind or @jheer have additional comments, have we reached consensus on this?

**Comment by domoritz** [comment]
Hmm, I see your arguments and agree that `expr` is useful but we will need to think more carefully through all possible complications. I also now agree with `xError` and `yError` being channels. 

One question. How is a user supposed to know which error (`xError` or `xError2`) is positive or negative? Should we expect people to know this, specify errors with negative values, or rename the channel to `xErrorPos` and `xErrorNeg`? @jakevdp how would you expect this to work?

Here is a spec that should work later:

```json
{
  "data": {
    "values": [
      {
        "yield_error": 3,
        "yield": 32.4,
        "variety": "Glabron"
      },
      {
        "yield_error": 3.2,
        "yield": 30.96667,
        "variety": "Manchuria"
      },
      {
        "yield_error": 1.2,
        "center": 33.966665,
        "variety": "No. 457"
      },
      {
        "yield_error": 2,
        "yield": 30.45,
        "variety": "No. 462"
      }
    ]
  },
  "mark": "errorbar",
  "encoding": {
    "x": {
      "field": "yield",
      "type": "quantitative"
    },
    "xError": {
      "field": "datum.yield_error",
      "type": "quantitative"
    }
  }
}
```

and asymmetric (yield_error_2 goes negative??)

```json
{
  "data": {
    "values": [
      {
        "yield_error": 3,
        "yield_error_2": 2,
        "yield": 32.4,
        "variety": "Glabron"
      },
      {
        "yield_error": 3.2,
        "yield_error_2": 0.3,
        "yield": 30.96667,
        "variety": "Manchuria"
      },
      {
        "yield_error": 1.2,
        "yield_error_2": 1.9,
        "center": 33.966665,
        "variety": "No. 457"
      },
      {
        "yield_error": 2,
        "yield_error_2": 1,
        "yield": 30.45,
        "variety": "No. 462"
      }
    ]
  },
  "mark": "errorbar",
  "encoding": {
    "x": {
      "field": "yield",
      "type": "quantitative"
    },
    "xError": {
      "field": "datum.yield_error",
      "type": "quantitative"
    },
    "xError2": {
      "field": "datum.yield_error_2",
      "type": "quantitative"
    }
  }
}
```
