### ISSUE TITLE
Default stroke width for symbols

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4132]
The default for marks in Vega is 2 but 1 is nicer if there are a lot of marks. 

![image](https://user-images.githubusercontent.com/589034/44249335-3a529800-a1a4-11e8-8c53-9138d2c9507c.png)

![image](https://user-images.githubusercontent.com/589034/44249330-34f54d80-a1a4-11e8-917d-5d1f8abf6edd.png)

I know @kanitw set the default in Voyager to 1px so I was wondering what his thoughts are concerning the default. I don't think the default in current default is bad so I'm happy to say we leave things as they are.

**Comment by domoritz** [comment]
Asking for input from @kanitw @arvind and @jheer

**Comment by domoritz** [comment]
Okay, so we are sticking with 2px?

**Comment by kanitw** [comment]
You could send a PR to try if it looks better in general and we can decide.

1px might look worse on a non-retina display though

**Comment by domoritz** [comment]
I don't have a non-retina display, lol.

**Comment by kanitw** [comment]
At 100% (rather than 200%), strokeWidth = 1 looks pretty bad.  Let's not do it.
