### ISSUE TITLE
Example missing for ranged area

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4135]
![image](https://user-images.githubusercontent.com/111269/44291550-e3949f00-a233-11e8-968d-7805ee91ab62.png)

**Comment by domoritz** [comment]
It renders for me :-/

**Comment by kanitw** [comment]
@chanwutk this might be related to some old example that got renamed?

**Comment by chanwutk** [comment]
Now, the example is not explicitly using `x2` and `y2` anymore. Should I create another example for this or should I just use the normalized version of the `errorband`?

**Comment by domoritz** [comment]
An explicit example would be good. For example minimum and maximum temperature would be an easy one.

**Comment by kanitw** [comment]
If the normalized version is clear (and explicit), then it's fine too.

**Comment by chanwutk** [comment]
Should we close this issue?
