### ISSUE TITLE
Color scale legend does not show max value

### ISSUE THREAD

**Issue by epietrig** [vega/vega-lite#4144]
First thanks for developing vega-lite. Yet another great project from UW/IDL.

Setting a legend for the color scale (see attached screenshot *force_values*), it seems a bit odd that the max value does not appear as a label on the color scale. I realize I can force this using explicit values, as shown in the second screenshot, but I would expect this to be the default behavior?

Maybe linked to the fact that this is a temporal/timeUnit==year legend?

I do have data points with discovered == 2018, as the tooltip in the screenshot testifies.

Using vega-lite 3.0.0-rc4.

[exoplanet.eu_catalog.csv.zip](https://github.com/vega/vega-lite/files/2324005/exoplanet.eu_catalog.csv.zip)

<img width="917" alt="donot_force_values" src="https://user-images.githubusercontent.com/11522723/44662084-fe71cb00-aa0c-11e8-92d1-a26ece6f3008.png">
<img width="933" alt="force_values" src="https://user-images.githubusercontent.com/11522723/44662085-fe71cb00-aa0c-11e8-916c-aa2a848f3c55.png">

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
    "data": {
        "url": "exoplanet.eu_catalog.csv",
    },
    "transform": [
        {"filter": {"field": "mass", "valid": true}},
        {"filter": {"field": "star_mass", "valid": true}},
        {"filter": {"field": "detection_type", "oneOf": ["Radial Velocity", "Primary Transit", "Microlensing"]}},
    ],
    "mark": "point",
      "encoding": {
        "x": {"field": "star_mass", "type": "quantitative", "axis":{"title": "Star Mass (Msun)"}},
        "y": {"field": "mass", "type": "quantitative", "axis":{"title": "Mass (Mjup)"}},
        "color": {"field": "discovered", "type": "temporal", "timeUnit": "year", "legend": {"title": "Year Discovered"}},
        "shape": {"field": "detection_type", "type": "nominal", "legend": {"title": "Detection Method"}},
        "tooltip": [{"field": "# name", "type": "nominal"}, {"field": "discovered", "type": "temporal", "timeUnit": "year"}]
      }
}```

**Comment by domoritz** [comment]
I believe this is the intended behavior in Vega but I will have to check in detail later.

**Comment by domoritz** [comment]
Quantitative legends do not show labels for the extreme values. I can't find the corresponding Vega issue but it's intended behavior.
