### ISSUE TITLE
Tooltips show up with incorrect date in charts

### ISSUE THREAD

**Issue by SyntaxRules** [vega/vega-lite#4147]
Using vega-editor I produced a one of the examples [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVqqADNuRjHjMG8AT0LIzSAVlSABfUPUISDF0H2QjMwBtDQhQCHSoDCMAay8UjKhff0D4ozd2dCVNNXyMyGQADzxkJU8cSHhGGoL0yHY3TXjYL0huQnRO3zMABjoAVidIWDwy7OQAEXRYRCSANicAFgBdUNqwCLP6pXhuTUYlajyeqJ8n56jnRmQxavaAWUYYmQsAA+v4jCCAOLoMRiEKRd6FPwBdoAR1YlTwzB0jCo3URS2sQJGAC94twzM4YbBkBdEYVmMT-oDgWBwWBobDlGAABQATjmAFIwABhACSsAAlJAzhA6c9IA0Rp9vr8oABNZA2NRI4rtZqoQhuGE6yBY1DIACqSmYgTi2tOPUd6XlqUuWVy7QkSgCCLqLRudwebx6kFe+llvRVP0CAKBoPBUJhcMckaiRRRUHRmOxWLxfoV6Go1CMwmagQtlRl71dBUVyq+Mfamu1iwzgQNRqMJrbjAt1tt7XtCWdGVH5w0RwRHWUn0e+kg6AajFg6pGqHuAFEmi02mAAMzTcIgUJAA). Also found in the docs [here](https://vega.github.io/vega-lite/docs/mark.html#stroke). Also example [here](https://vega.github.io/editor/#/examples/vega-lite/layer_line_errorband_ci).

In this example the tooltips show the wrong dates. For example, the screenshot below should show somewhere around the begining of 1974.

![image](https://user-images.githubusercontent.com/4117657/44812816-7a971a80-ab95-11e8-8740-94b86af3d9c2.png)

I would not care **if** the tooltip showed data for 1974-01-01 (as that is where the closest data to my cursor actually is), but showing data for 1969-01-01 is pretty off far off.

Here's the spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json", "format": {"type": "json"}},
  "layer": [
    {
      "mark": {
        "type": "errorband",
        "extent": "ci",
        "borders": {"opacity": 0.5, "strokeDash": [6, 4]}
      },
      "encoding": {
        "y": {
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "scale": {"zero": false},
          "title": "Miles per Gallon (95% CIs)"
        },
        "x": {"field": "Year", "type": "temporal", "timeUnit": "year"}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "y": {
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "aggregate": "mean"
        },
        "x": {"field": "Year", "type": "temporal", "timeUnit": "year"}
      }
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

Some other examples: 

[Area Chart Example](https://vega.github.io/editor/#/examples/vega-lite/area) - Same issue
![image](https://user-images.githubusercontent.com/4117657/44814328-9bfa0580-ab99-11e8-9777-87aefbf1c5b2.png)

[Horizion Chart example](https://vega.github.io/editor/#/examples/vega-lite/area_horizon) - Same issue
![image](https://user-images.githubusercontent.com/4117657/44814299-81279100-ab99-11e8-8a32-e3344730c70b.png)

[Area Chart](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlWStITHcAnqmRK8I9PCPdYsEYyWarLB4RozIsPKKKgC+6hCQAO6MmixmAMwADBmquMiM1Phm0llxUBhGANZmkOhGyJilkC7w3Jr+1GagEPEAHp0a3VB4jM4AqkrM1Q71RqjKqTmQAGZhYprV2njIakMOhNs4kFuohNxG6KalgzU9jLCdkJrcGP5mSxewyItLZxh41QBSACakGiAzAsXBkAc-UG8XQ1GodVoW2qsFYqB2y1W60OLWs-1URz2BygAEdWOhXMwdIwqGpwfDbvccEpWGIxFdupBgh4qoclL8LowAF7bEDgyHXFr2IwPFbINbYHnIULhLF4EnKwWofwXLEIC4HAz8NCkyDwHQ0M4OYrsUFS7l4bjcMTDQhmADajLhXTh-uxitx5lRXP98R+sx0gKBIgBqDj6zD4aOI2Q40mh2mtTmrkQm22yYDmv21WOp3Oph9g0d4bAfrrEZx1XxrgZjadWoFzz1VY7tfDDcbgaVh0+avuRbhxNL3d1Sn11e6YLrAF0NGCwUA) - The tooltip works, but adding it in causes the graph to display strange lines
![image](https://user-images.githubusercontent.com/4117657/44814363-b46a2000-ab99-11e8-97ec-0513a9c721d6.png)

[Line chart](https://vega.github.io/editor/#/examples/vega-lite/line_overlay) - Works as expected

**Comment by g3o2** [comment]
Have you tried adding a layer of marks `point` or set the point overlay (see `line` mark), and applying the tooltip channel on that mark instead? The point could have `color` set to `transparent` but it should help with proper tooltip rendering, if I'm not mistaken.

**Comment by SyntaxRules** [comment]
Hovering directly over the line on the [line errorband chart](https://vega.github.io/editor/#/examples/vega-lite/layer_line_errorband_ci) does produce the right tooltip. Points and lines don't seem to be a problem. Area charts are the non-functional case here. 

@g3o2 Are you thinking I add point marks to fill the area? Or just add a few points in the area to mark locations of interest? I think both would work- but i wouldn't consider either ideal.

**Comment by g3o2** [comment]
I think that `area` and `line` are related, so the `point` overlay or layer workaround should work the same.

**Comment by SyntaxRules** [comment]
Do you mean like [this](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIyJfG6bGS6mdAQrgAe-hqBUABmjMhimmaQAJrINmphgZB4AJ6EyPF4aITcRuimLuFQeIyoyACqSszxmclGkGmOGs4akGLoTS04ANppAeWQGEYA1v4Z2bk4bkZGRezoSnGqUMhB+Up48fCMkJ3lmx5ePn76aeGQmaEnN1ExcfMAsoxiyLAA+jlG3wBxEpiZSpB7pLI5eIAR1Yq0qukqVDB4IqzE+8VeySUYG4ETA70+sDAfzAQLEIJxAAoAJwAVgApGAAMIASVgAEpWuD2ideYFjoERjdxlN9DMofMJEpcmANpBCj49vM8MUlLBCDZ3HtBTd3J5vL57g9bsbwZB0NRqEZhPl4tVVijzU9YpiPl9fsh-uTKU6TZC5lBYfDmDpGMjrgLI-yIPyALogRxAA)? I afraid I don't quite understand.

**Comment by g3o2** [comment]
I'm not sure this will work, for I have no experience with the recently composite marks, yet. So this may well be a bug.

Have you tried your spec outside of vega-editor ? Normally, a tooltip is only rendered for any given mark if you define a tooltip channel therein. The idea is then to only define the tooltip channel for transparent point marks and not for area/line marks. This increases the length of the spec but at least it should solve the problem. 

The relevant issues I've found are #1921, #2341 and [vega-tooltip #120](https://github.com/vega/vega-tooltip/issues/120).

**Comment by domoritz** [comment]
Does this look like https://github.com/vega/vega/issues/1390?

**Comment by SyntaxRules** [comment]
@domoritz Yes, it does appear the same. I may be that resolving that issue will solve this one.

**Comment by domoritz** [comment]
Okay, I'm going to close the issue here and leave a note at the issue that we need to try the issues described here later.
