### ISSUE TITLE
Ability to draw polygons of geoshape on top of other geoshapes while allowing tooltips from lower layers to still show up

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#4154]
I am not sure if this is a bug or feature request.

Below is the smallest reproducible example I could make.

The issue is this:  Is it possible to put a mark_geoshape , then a layer of points, then `another` geoshape on top - while allowing the points to have a tooltip that comes through.

Reasoning, in plotting geoshapes with points and tooltips, it is helpful to layer another geoshape on top to highlight a custom area that occurs on the map.

Below is the smallest reproducible example I could make.
granted - below the upper layer is just a reproduction of the state outlines - my attempt was to put 
```
"fill": "None",
"fillOpacity": 0,
```
but that does not seem to bring the tooltips through that layer.
In the bottom example without the top layer you can see the tooltips of lon/lat/city.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.json",
  "width": 800,
  "height": 500,
  "projection": {
    "type": "albersUsa"
  },
  "layer": [
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {
          "type": "topojson",
          "feature": "states"
        }
      },
      "mark": {
        "type": "geoshape",
        "fill": "lightgray",
        "stroke": "white"
      }
    },
    {
      "data": {
        "url": "data/us-state-capitals.json"
      },
      "encoding": {
        "longitude": {
          "field": "lon",
          "type": "quantitative"
        },
        "latitude": {
          "field": "lat",
          "type": "quantitative"
        }
      },
      "layer": [{
        "mark": {
          "type": "circle",
          "color": "orange"
        }
      }, {
        "mark": {
          "type": "text",
          "dy": -6
        },
        "encoding": {
          "text": {"field": "city", "type": "nominal"}
        }
      }]
    }
    ,
        {
      "data": {
        "url": "data/us-10m.json",
        "format": {
          "type": "topojson",
          "feature": "states"
        }
      },
      "mark": {
        "type": "geoshape",
        "fill": "None",
        "fillOpacity": 0,
        "stroke": "black"
      }}
  ]
}

```

Here is what the hover looks like without the top layer geom:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.json",
  "width": 800,
  "height": 500,
  "projection": {
    "type": "albersUsa"
  },
  "layer": [
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {
          "type": "topojson",
          "feature": "states"
        }
      },
      "mark": {
        "type": "geoshape",
        "fill": "lightgray",
        "stroke": "white"
      }
    },
    {
      "data": {
        "url": "data/us-state-capitals.json"
      },
      "encoding": {
        "longitude": {
          "field": "lon",
          "type": "quantitative"
        },
        "latitude": {
          "field": "lat",
          "type": "quantitative"
        }
      },
      "layer": [{
        "mark": {
          "type": "circle",
          "color": "orange"
        }
      }, {
        "mark": {
          "type": "text",
          "dy": -6
        },
        "encoding": {
          "text": {"field": "city", "type": "nominal"}
        }
      }]
    }
    
  ]
}

```

Edit: I replaced the examples above with one directly from the vega-lite site so the example is clearer and cleaner.

**Comment by kanitw** [comment]
The tooltip seems to [work fine in the latest version of the editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10AOAAwe7uZI2r4Nl4+kLB4AJ4ANjo4kPDIkZHG9gboeJg4ANpKEKAQ+VAy6KgxUNKsAE7xAPoeyQVQlUmxqemkrLAAtACMHqiS0nI+BZAAZtwVGHi6wJARhKVz3ITcUrIKUKPIaZWLYWnIsJAAvjlgx8NgeQ2QRSW6odyVNd31I00PrSIdnft4yJ14OhCMx0JFYAN1pd7ONJmkZnNwgsHms5KcChcztcRndFl9am98o9nnsnlVkNVXtCoHgKugZLBYahdNkGvlsWyaUjFtRkKtBoS2WNGAkDEcspBIlCoJF4QBdakjDTUIrNGXocLICqU6qyzXajzVXn82QEs4YxVXc03eY8vkrSzTS32QgVVbIeB4HhyWKu92e72Cm6jEWRMUsyXSyXy53KcVgTLR-U6vVa2rVAAeGyTae6uo1acN4UgcutEHRDVLFqx1tuxTxaXQlKDxPJD3K5Ob1LmdIZTJZZatnKJtoextRQZGIdF8cTUqG6umCsH9mVqoeqe1ec3OvHgzNw8xw45QtHsWNDpkTpXejdEg9XvWvrvD8DseFM4j8+zsqX7-Qs45lu+bJnmWbyOqoEgbm1TFlWnIVgU8Hlkoy4ui+AayLONZCriDx+vemFDLWGjaAia5gg8mROC4iAQSg-j4HKJzdiG0w4CeRIUWqkCZF8AAUADkHY1B4gkAJQQTu24FgaRp8qitRSbJKYqXme6mh4zHWkeNrcg8YLsFqsAAKqwJgZwVmhUAYBUADW2EFJxdb3LEO6GrZDktmeZSIMCOjdmEUSlImxqwH5yLWVObrMhxkBfO2ZKiSxtbIDI8DcAYpScfYrCEK02XCokCIUGCrCLJEjF4NQdLFhcZS0twdmFaVkTlQ8DiIMwOjHIh+S6SMtL0oyEyxQmsw+ZAYURQFt7+o+PpzYRC0nMh5yXM5eFuWp0FyZ5RzdpNsDhKg7DcEkgURNEEbwIwVTXVFRKjDFCIJS0jYEgNRJpRlWUzIOkB5QV-3DvYyzoLdEQlWVpQeHQADsX1CiGxVxa17WxBM9K8iloM0tw51eoQIN42U-jrrEwAADqRjINM4EyaT8a0rCoJkNPzjTCpgDTNOSTz0Z4PTYCM3gzM7GzHNpFzEG85A4nHJAN5IzcWZxdOYYbjt7mZrjoOQMW6uhkY21QTrdXvuF-nQ21iy3fdPWDn1KHVk5tZbZBMHSdU+3efpsT-Bm15CkF10SoHf61s93BjbMb1QPirwq5AP2ZdlANAwcJPDvFhtXJA6OlJ0ABsKtTowqP54XDzsLK8B2XrOdqITjDExxN6ruTlGUxzsjC6L4t4Kz7O0zLAt87Lgv96NTMs5LU8lpPE8C5D4TC4JgkANRzyPq9c4ryvvmr+caybnvAd7WZl0SeezKfWtmztFs3nMyBB+RXc8Rv28S7vzBryWRunJIBgnJjbDGUB4hXi1EAoU7AAIJEsC1GGDxUDOAMNdZ2-UdKWQ2u7esD80wACYfboHsgdWsR0ZotlDiFKafIraRVYi9OK8dWzJWTqnP67cc6Z3+NnYBKM1SzGrrEAAcrIHq74hEAHl9Cr3AbDa+q5GrNUUTXOuDcsEuwaMnIafZRosgmv7KA01rYQVMBhFaz55qBmOGtKyIBjhAA). 

![image](https://user-images.githubusercontent.com/111269/59142351-dd61e180-8971-11e9-8855-3a288504949e.png)


Please feel free to reopen the issue with more description / example if it still doesn't work for you.  :)

**Comment by mattijn** [comment]
I think this issue should be reopened. See the following animated gif:
![ezgif com-optimize-9](https://user-images.githubusercontent.com/5186265/76150030-419f0680-60a6-11ea-90ef-386cf0fc4ffa.gif)

Which correspond to the following specification:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 300,
  "layer": [
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson", "feature": "counties"}
      },
      "projection": {"type": "albersUsa"},
      "mark": {
        "type": "geoshape",
        "fill": "lightgray",
        "stroke": "white",
        "strokeWidth": 0.5
      },
      "encoding": {"tooltip": [{"field": "id", "type": "quantitative"}]}
    },
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson", "feature": "states"}
      },
      "projection": {"type": "albersUsa"},
      "mark": {
        "type": "geoshape", 
        "filled": false, 
        "stroke": "black"
      }
    }
  ]
}
```

That can be opened in the Vega-Editor directly by clicking [HERE](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwGAzKfNQx6AJ7IATgYDaGiKAhAqB10PEwcAKDAyFYPMQNIELDSVlgRAEZjVHlFFScoqAAzbg8MPANgSDxXQmQEvG5CbgVlNSLkUNi6nEh4blYlPEZkWEgAXz9Asfzowg9m5Hgh1oiqmu6odDF2T1gAVVhMacmLDA8AawqT6OrahOpkblhEdDuZoMhCxjF4nokbPDUDxuNTXCywPDzc4bSCaRCSUEFcGQ7jQgDqun0OGMdEM12OBUgyCUfR0jCU1AqVW43DEQ0IPkqX2QYh0CV0bTWdx6AEdWOhBsxQowqOMALoTIIEwKRD5JcJgWVRGJxBLylJpTLZFp5MFFEplKm3GENJo6zmFDp4LoJCGhEbjfHvKBzBZLHgqVbGhJbHYefaHcbOyBnS5e9b3R7PV51VRFb5iZBsnCFLawZBxyAQqEw9gueCXSVTDRikBjIA)

**Comment by mattijn** [comment]
Maybe it should be possible to set `"interactive": false` within the `"mark"` config:
```json
"mark": {
  "type": "geoshape", 
  "filled": false, 
  "stroke": "black",
  "interactive": false <--
}
```

Aahh, I'm not the only one: https://github.com/vega/vega-lite/issues/4567

**Comment by mattijn** [comment]
The documentation PR https://github.com/vega/vega-lite/pull/6337, did fix this request to re-open (which didn't happened) as well.

So instead of using `"filled": false` use `"fill": null`. One could argue if this is desired behaviour, but it works!

+ working example spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 300,
  "layer": [
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson", "feature": "counties"}
      },
      "projection": {"type": "albersUsa"},
      "mark": {
        "type": "geoshape",
        "fill": "lightgray",
        "stroke": "white",
        "strokeWidth": 0.5
      },
      "encoding": {"tooltip": [{"field": "id", "type": "quantitative"}]}
    },
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson", "feature": "states"}
      },
      "projection": {"type": "albersUsa"},
      "mark": {
        "type": "geoshape", 
        "fill": null, 
        "stroke": "black"
      }
    }
  ]
}
```
+ animated gif:
![ezgif com-optimize-11](https://user-images.githubusercontent.com/5186265/79491011-15b85e80-801e-11ea-92e4-ff188287978d.gif)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwGAzKfNQx6AJ7IATgYDaGiKAhAqB10PEwcAKDAyFYPMQNIELDSVlgRAEZjVHlFFScoqAAzbg8MPANgSDxXQmQEvG5CbgVlNSLkUNi6nEh4blYlPEZkWEgAXz9Asfzowg9m5Hgh1oiqmu6odDF2T1gAVVhMacmLDA8AawqT6OrahOpkblhEdDuZoMhCxjF4nokbPDUDxuNTXCywPDzc4bSCaRCSUEFcGQ7jQgDqun0OGMdEM12OBUgyCUfR0jCU1AqVW43DEQ0IPkqX2QYh0CV0bTWdx6AEdWOhBsxQowqOMALoTIIEwKRD5JcJgWVRGJxBLylJpTLZFp5MFFEplKm3GENJo6zmFDp4LoJCGhEbjfHvKBzBZLHgqVbGhJbHYefaHcbOyBnS5e9b3R7PV51VRFb6-MBKVg-OOQCFQmHsFzwS6SqYaMUgMZAA)
