### ISSUE TITLE
timeUnit utcday not supported

### ISSUE THREAD

**Issue by ijlyttle** [vega/vega-lite#4157]
I am trying to organize date-oriented data by day and I am using the ISO-8601 format. I think it is logical to use `"utcday"`, but it is not supported. 

For an example:

https://bl.ocks.org/ijlyttle/57bfeddee4243389d4338cf41f9d9115

This block uses Vega-Lite 2.6.0, but if you open in the editor, the problem appears also for the current version.

For completeness, a workaround is to parse as local time and use `"day"`:

https://bl.ocks.org/ijlyttle/335c6dd7bb5711b4772dd14e2070b45c

---

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {
        "date": "2018-09-09",
        "value": 1
      },
      {
        "date": "2018-09-10",
        "value": 2
      },
      {
        "date": "2018-09-11",
        "value": 3
      },
      {
        "date": "2018-09-12",
        "value": 4
      },
      {
        "date": "2018-09-13",
        "value": 5
      },
      {
        "date": "2018-09-14",
        "value": 6
      },
      {
        "date": "2018-09-15",
        "value": 7
      },
      {
        "date": "2018-09-16",
        "value": 1
      },
      {
        "date": "2018-09-17",
        "value": 2
      },
      {
        "date": "2018-09-18",
        "value": 3
      },
      {
        "date": "2018-09-19",
        "value": 4
      },
      {
        "date": "2018-09-20",
        "value": 5
      },
      {
        "date": "2018-09-21",
        "value": 6
      },
      {
        "date": "2018-09-22",
        "value": 7
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "date",
      "timeUnit": "utcday",
      "type": "ordinal"
    },
    "y": {
      "field": "value",
      "aggregate": "mean",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
Works now. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoVZjhoQAJgAMARgAc-awE4nzxSG27zqWwF8FEzUfKztHF35baw8vPTRLAKCzCxsHN0jbGJ041ABmRJVglLD020ss7zQxAtMQ1PDXW1yKnIBWGqL0etKxFp8ANg7krpKI21a+tAB2IbrRxv7J31nitLGppYTAwuHQtcb7Jfzt2tWGyPclWJ9qk86985sl9rvd7ojLTKvsgZWR-f4lnK30qqBmAF0AiBkAAnADWFiYSBhHjgsigbGUNFkZDQoAAHniQAAzGhwQTKCynJSYGgIOAAVVkdAsDEwUFUAE8PJhOTgQmwYVjZDoQFDuZoSWSKRZrh4kGQyDC+Lt6Uh5DS+SEAI4MdW09S00hivx+IA)

**Comment by ijlyttle** [comment]
Thanks!
