### ISSUE TITLE
hasDiscreteDomain vs hasDiscreteRange

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4161]
In https://github.com/vega/vega-lite/blob/d696943bcb35c8a19c067fb55acfe19506aa7b76/src/scale.ts#L743, shouldn't we use `hasDiscreteRange` rather than `hasDiscreteDomain`? Looking through the code, I see a few places where `hasDiscreteDomain` is used and it seems to me that there scales that have a discrete range would work as well.

**Comment by domoritz** [comment]
The particular example that should work are discretizing scales such as threshold and quantize.

**Comment by iliatimofeev** [comment]
based on https://github.com/altair-viz/altair/issues/1135
```javascript
"shape": {
      "type": "nominal",
      "field": "val_y",
      "scale": {
        "type": "threshold",
        "domain": [
          0
        ],
        "range": [
          "triangle-down",
          "triangle-up"
        ]
      }
    },
````

[vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoARpKYBOAQwBMTSroLQAbA12HDADmgSA7IkqaLTRJsMXIIsZAKEgBOANYqAA6wyPC8ohCQBPBwlDHoWKAQCQDOtBIRyhmQ1ACeBSrwsAoxEgA2kOyQKAS1lCq4dQD6JQ1iOY61hZlgfVkJpeVYxbTBBLmwrb1jY6pVEjGkANpMALrxywkAXsjBsJjUwQCuBPsHkMES8KiFYJvFwciPqIPqlLBE8EgYEaF0+Tx+lwiQJ2o0EsNuUAAHrJimUXpAAI6XR7UZDSXG4ZSNZqLKYdWqdZH+FY9IoTdFYnF4qTIQkNKAktpkro9OEQalQAAk2WgnCCKh41Ai2QwAHpZYTUBIAHSoPG0S6aZXIWCykViiQKghK9S1PEEBWGZUWZVMZUAK2yCCW4ikEmyBGo2Vko1Ubq0On0TCMJjMlmstgczlc7k83l8WE2owgOHJlNI6j4FkaadpYGYArGqa6yKw6ic2aguYzTgArIWssWKaWwOpDABGHM8jPWBspvAljNZrsUvO1ux9shplu6NhV7tlwyTpvpsu1ysD0eMdvLzer1vjkfdDO6CcI-vTnsMI95gS7y9lhgb6tYOv3weP6-zreLizv5snoYN5Dkw-77kB37HmWTgMGBLZ2HYwFYLo9bnlOH75nwSFgOOcGkBYtbYeo7ZCGhK4tsRWGQXmDB8Hha5OERuFkXuFEwdhtaocm6EAVgHZEe2S4sQ+YDtroRFGPRYCIdRGYWEJ3HkRmdhUXut6wcJGFGNhfBnoprE9thdh-ppvGtl+an4U4UlthBllYKBpn7uotZ2S+YAdlJfAWe57YafpIkWKp7k+DZfDBQurZ2EuowwvyICCEAA)
expected 
![visualization 54](https://user-images.githubusercontent.com/11561581/45564794-37f26500-b85a-11e8-817c-7da3497a08e7.png)

**Comment by domoritz** [comment]
@kanitw can you help me with this? I'm happy to fix it when we know what the right way forward is.

**Comment by kanitw** [comment]
The data type is the data that feed into the scale, so it's the domain that should be discrete, not the range.  

Please feel free to re-open this issue if I misunderstand anything.
