### ISSUE TITLE
Boxplot: temporal -> ordinal axis labels do not format correctly

### ISSUE THREAD

**Issue by ijlyttle** [vega/vega-lite#4164]
The formatting for the labels does not seem to work - I have concatted a chart using points for comparison.

![image](https://user-images.githubusercontent.com/2800934/45605017-60679400-b9ff-11e8-9f36-147210d376d5.png)

Please see https://bl.ocks.org/ijlyttle/8cce9bf5458d4e10b4de1e828e4eade1 for a live example.

As well - I the boxplots themselves don't seem correct, and there are no outliers plotted. Please advise if you would like me to file separate issues for these.

Per usual, I keep open the possibility I am doing something wrong...

---

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-weather.csv",
    "format": {
      "type": "csv"
    }
  },
  "hconcat": [
    {
      "mark": {
        "type": "boxplot",
        "extent": 1.5
      },
      "encoding": {
        "x": {
          "field": "date",
          "timeUnit": "month",
          "type": "ordinal",
          "axis": {
            "format": "%b"
          }
        },
        "y": {
          "field": "temp_max",
          "type": "quantitative"
        }
      }
    },
    {
      "mark": {
        "type": "point"
      },
      "encoding": {
        "x": {
          "field": "date",
          "timeUnit": "month",
          "type": "ordinal",
          "axis": {
            "format": "%b"
          }
        },
        "y": {
          "field": "temp_max",
          "type": "quantitative"
        }
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
Thank you for reporting the issue. Note that boxplots are part of the release candidate so there are definitely a few bugs to iron out. We will fix this before the final release.

**Comment by artfulgarfunk** [comment]
I would just like to add that Boxplot also does not allow axis title to be set on the ordinal axis. 
![screen shot 2018-09-21 at 11 36 25](https://user-images.githubusercontent.com/22254546/45876480-a7081600-bd92-11e8-826d-bd86fe99db10.png)

**Comment by domoritz** [comment]
Thank you! We're looking into this issue.

**Comment by domoritz** [comment]
@artfulgarfunk Your issue has been fixed in master. We are working on also supporting formatting when there is no time unit.
