### ISSUE TITLE
{"title" : null} prints out the string null for axis labelling

### ISSUE THREAD

**Issue by artfulgarfunk** [vega/vega-lite#4195]
need to set title as null otherwise it automatically uses the Data name ("Response" in this case as the axis label), however this then prints out null as part of the axis title.

https://tinyurl.com/ya5ersw7

**Comment by domoritz** [comment]
@chanwutk The problem with the example above is with errorbars. Can you look into this?

**Comment by domoritz** [comment]
Regardless, we should treat `null` the same `""` and when merging titles we should treat them like `undefined`.

**Comment by domoritz** [comment]
The fix for now is to set the same title twice.

**Comment by chanwutk** [comment]
I create a small example to test this:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0-rc5.json",
  "data": {
    "values": [
      {"Dose": 0.5, "Response": 30778},
      {"Dose": 0.5, "Response": 4000},
      {"Dose": 1, "Response": 30814},
      {"Dose": 1, "Response": 50814},
      {"Dose": 10, "Response": 28355},
      {"Dose": 10, "Response": 35355},
      {"Dose": 75, "Response": 40467},
      {"Dose": 75, "Response": 25467}
    ]
  },
  "layer": [
    {
      "mark": "point",
      "encoding": {
        "x": {"field": "Dose", "type": "ordinal", "title": "Axis title"},
        "y": {"field": "Response", "type": "quantitative", "aggregate": "mean"}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "y": {"field": "Response", "type": "quantitative"},
        "x": {"field": "Dose", "type": "ordinal", "title": null}
      }
    }
  ]
}
```

should composite mark be the one to handle this problem (remove `title` when `title` is null)? Or should we handle this in normalize layer?

**Comment by domoritz** [comment]
This should be handled in the legend merging logic.
