### ISSUE TITLE
Support for touch and pinch in interactions 

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4208]
Currently there is only support for mouse click, mouse move and scroll for vega-lite declared interactions. 

It would be great if this was extended with touch touchmove and pinch.

**Comment by kanitw** [comment]
I think this is already possible.  Perhaps, someone should provide an example and we can close this.

**Comment by mattijn** [comment]
This is surely working in Vega, https://vega.github.io/vega/examples/zoomable-scatter-plot/. 
It is just not implemented in Vega-lite.

**Comment by domoritz** [comment]
https://github.com/uwdata/falcon also works on mobile.

**Comment by domoritz** [comment]
This issue is about seeing whether it's possible to manually customize the events in VL to capture touch as well.

**Comment by mattijn** [comment]
At this falcon website it seems the anchorpoint is snapping to the left or right edge handlers of the interval.

**Comment by domoritz** [comment]
> At this falcon website it seems the anchorpoint is snapping to the left or right edge handlers of the interval.

Can you elaborate?

**Comment by mattijn** [comment]
![681CE082-22F6-4ADD-B587-45284DE3B3DC](https://user-images.githubusercontent.com/5186265/54073885-8ffba880-428c-11e9-93c9-6d8ac8042283.gif)

**Comment by mattijn** [comment]
Touch works indeed, I can't get the pinch to work.

Example for creating interval selection box (rectangle will be orange if using touch events):
[Click on mobile](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIsZGOTw8PFfo2uALIA8gCqAMoAomagEHFQeACehMhmkIxKeMhGFOimLvFQymkA2qjcrO6a3ADuSqpg5ZXIrIQAumAAfI0V7uVUagFxkHhG6EqwYjqpOJBlvcjVdQ1N7q0d3ato3ANDzkOQACphAMIAEjFDrkkpaRlZOXmDhUV+UCV4FUiwukZ4DZ9WEhkEpNBswICkP1UgV4iMxhMpllSpDED8bP8IV8UKDwajoc9CpAMEYANYxSAAM0YYlMswAxJTNOx2AAOAAsaig1NpwUI6HgzESZgADHQAKwNNyjbikmZQenIaTs9DSaSQRx7DT7Vwk8mzIxePCEyAg+DcTQZaiXOHC-RUxgeTRpYJGRhMFRSm7yyDcIyWpRPHXDAAeFOpTrSJ0SElB2VgXJGyR9foDQdhUHNYj9NqJ5tBzF8uZebg8RqL9pzOBKkBCEWiUuOoXOkDawZL6Go1ENtGRs3NrEyhJL3rSAEdWOMfLofLsXu3hrkxKwfd3kMKtRBNY4gA/view)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/cars.json"},
  "selection": {
    "MOUSE": {
      "type": "interval",
      "on": "[mousedown, mouseup] > mousemove",
      "translate": "[mousedown, mouseup] > mousemove"
    },
    "TOUCH": {
      "type": "interval",
      "on": "[touchstart, touchend] > touchmove",
      "translate": "[touchstart, touchend] > touchmove",
      "mark": {"fill": "#fdbb84", "fillOpacity": 0.5, "stroke": "#e34a33"}
    }
  },
  "mark": "rect",
  "encoding": {
    "y": {"field": "Origin", "type": "ordinal"},
    "x": {"field": "Cylinders", "type": "ordinal"},
    "color": {
      "condition": {
        "selection": {"or": ["MOUSE", "TOUCH"]},
        "aggregate": "count",
        "type": "quantitative"
      },
      "value": "grey"
    }
  }
}
```

And an example where one can pan when two touch events are captured. So the panning is only captured when you touch with one finger somewhere outside the chart and pan the chart with another finger:
[Click on mobile](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIsZGOTw8PFfo2uALIA8gCqAMoAomagEHFQeACehMhmkIxKeMhGFOimqlDsGZppCHnIsGrxAXGQeEboSrBiOqk4kADaqNys7prcAO5KBQPFg1jdvcishAC6YAB8YKNK-QMTPe7dVACEkDXONZAAKmEAwgASMTWuSSlpGVk5eVWQRaul1p6VLvEJDU0Wlk0h08D0kLBdEY8B1kFRMnQwawkBU6J4lNQWABeHEAJlmBSRKNW8yWRMQ21SB2qEEOrgwRgA1ml4IwjPBPGoNJBkEp4NxNBlqNd4pAAB4iv6QABmjA8JXaF24tmQhEG2VedzaUAAjqxGj5dD4qFy-lAypz9JB+hgMmYOgB2ACsBQAjE6AAyzRwHX6uRKS0Wy+VpQKMb4AfRSRgjAHE8mJlJrktrIHqDcwdIwTX7ahbtQYbeg7TgOriPQUACxen3xOl5xgALwLMrlYgVUDOiQkq2yPwSKbS6cymeNqVrYB9PqAA/view)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/cars.json"},
  "selection": {
    "MOUSE": {
      "type": "interval", "bind": "scales",    
      "translate": "[mousedown, window:mouseup] > window:mousemove!"
    },
    "TOUCH": {
      "type": "interval", "bind": "scales",
      "translate": "[touchstart[event.touches.length===2], touchend] > touchmove"
    }    
  },
  "mark": "circle",
  "encoding": {
    "x": {
      "field": "Horsepower", "type": "quantitative",
      "scale": {"domain": [75, 150]}
    },
    "y": {
      "field": "Miles_per_Gallon", "type": "quantitative",
      "scale": {"domain": [20, 40]}
    },
    "size": {"field": "Cylinders", "type": "quantitative"}
  }
}
```

For the last only the `TOUCH` selection is captured, not in combination with a `MOUSE` selection.

I can't get the pinching to work within `zoom` since I can't find a method to access the [pinchDistance](https://vega.github.io/vega/docs/expressions/#pinchDistance) expression

Also when looking to the underlying created Vega, it doesn't combine the mouse and touch events within a single `on` directive, but it rather creates two different code blocks.

**Comment by domoritz** [comment]
Thanks for the video! I filed https://github.com/uwdata/falcon/issues/123. 

I guess we can close this issue here then and discuss how we can support this natively in #4661.

**Comment by corradio** [comment]
Any idea of how to make this work with `{"type": "point"}` instead of `{"type": "interval"}`?
Use case is to highlight a point using touchmove, the same way a point is highlighted using mouseover on desktop.
