### ISSUE TITLE
setting scale:zero:false does not automatic clip channel y

### ISSUE THREAD

**Issue by cnliao** [vega/vega-lite#4209]
The following spec leave too much space between the x-axis and the mark area. That space is removable by `"clip":true`. But since it works out of the box for the y-axis I assume that this is a bug.
```json
{
    "data": {"url": "https://raw.githubusercontent.com/vega/vega/master/docs/data/cars.json"},
    "facet": {"column": {"field": "Cylinders", "type": "nominal"}},
    "spec": {
        "mark": {"type":"point"},
        "encoding": {
            "x": {"field": "Weight_in_lbs","type": "quantitative","scale":{"zero":false}},
            "y": {"field": "Horsepower","type": "quantitative","scale":{"zero":false}}
        }
    }
}
```
![screenshot from 2018-10-09 18-04-29](https://user-images.githubusercontent.com/15000700/46662464-116fe180-cbee-11e8-8c09-650cd11ef6ad.png)

**Comment by domoritz** [comment]
There are values in your data at 0 but they are rendered without opacity. 

<img width="1121" alt="screen shot 2018-10-09 at 12 57 13" src="https://user-images.githubusercontent.com/589034/46665029-e6bc6380-cbc2-11e8-98f0-30c9caa83d97.png">

@kanitw why are they rendered at 0?

**Comment by domoritz** [comment]
I went to the Vega and changed `transparent` to `red`. We changed from filters to predicates in https://github.com/vega/vega-lite/pull/4032.

**Comment by kanitw** [comment]
It's now fixed in the master.
