### ISSUE TITLE
labelAngle in specs overrides config only if larger than config

### ISSUE THREAD

**Issue by Casyfill** [vega/vega-lite#4210]
and ignores otherwise 

```json
{
  "config": {
    
    "axisX": {"labelAngle": 0}
  },
  "data": {"name": "data-4f0d7b4226c2951b0538ba566f579d0d"},
  "mark": "bar",
  "encoding": {
    "color": {"value": "#032765"},
    "x": {
      "type": "nominal",
      "axis": {"labelAngle": -45, "labelAlign":"right"},
      "field": "name",
      "title": null
    },
    "y": {
      "type": "quantitative",
      "axis": {"format": "%", "title": "Return"},
      "field": "value"
    }
  },
  "height": 300,
  "title": "",
  "width": 450,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",
  "datasets": {
    "data-4f0d7b4226c2951b0538ba566f579d0d": [
      {"name": "Bushwick", "variable": "RoI", "value": 1},
      {"name": "Bedford-Stuyvesant", "variable": "RoI", "value": 0.99095},
      {"name": "Crown Heights", "variable": "RoI", "value": 0.878788},
      {
        "name": "Prospect Lefferts Gardens",
        "variable": "RoI",
        "value": 0.821271
      },
      {"name": "Flatbush", "variable": "RoI", "value": 0.716903},
      {"name": "Brownsville", "variable": "RoI", "value": 0.690476},
      {"name": "Ditmas Park", "variable": "RoI", "value": 0.689589},
      {"name": "Greenwood", "variable": "RoI", "value": 0.679733},
      {"name": "Greenpoint", "variable": "RoI", "value": 0.674224},
      {"name": "East New York", "variable": "RoI", "value": 0.671261}
    ]
  }
}
```

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIEMBXAF1gGdkAvAU020gCdqKa7iHDqAaKYgTwAOtLJAH4AJpAC+XcLkgA3ZNQDudYJBXJxxABZ0AbAEYALD0i7qaXcToBmAwZly8ZfgBth9aNXfv1kG4MsADWXpDs+PBkYkzwtlLOuFD4TPgBKH50kADEAAxGAJwArACixdKyyQQAHshk6i7y4rAAtvjI8HSI+O5k3E14qAza3b39VclQLe2dAMKw7rAM2TmlJuvrkJPVw9oLSysiaxun24NQ7vgARr4Hy6sAgkbPz+dTlze+AGIIxADKVC8RgATAA6Yo7eRXW7uX7xbL-WCEBg+MD-KJkMAABWC7ymkBhPz+AHUrKgbHQTHk8lC8MRkNAQvcjlATpsTPjqgymfCAUC6KCIXTeIyQnzEcjUdR0ZicXiRRExXyydZbFhqbSLkriJ4WU8XoaufIGbrqHzAawsELIdrTZ4JSIkSi0RjovLYMb6cgzSryZSNTTFUT3NiJOJOuhrVqPjrPGHxBH4FGwHkmkl5Pg6mQABoBEOPZOeOh5DN4TyoajwSRYHAEkOOqDO6Wy924z3Br7ufXHIpGb4ggAiXs+sL9arohSD2obf0twKMirIfFa10W86pMYJ9vNf0lLplbqx7ZHceoPbZfYHw8VO4tAutttjd9J-vVYCnW+5Pvj4cjJcVYYJGUeJB2QJhoAZBBsgUagGB5XpT2WED3wiWABAAWk8RBbHTKFCU6LwNCCUJwnyIoygqMsoAYKJK0aWNoHwYhqFQZY+DoABtC48HyOwQQAdgMCoRV4goSnKEdeLsb5SgADkHb4pLZUo8nKQTlNyAT+MKb4lNEtlqHEITEGuSALgAXUVCNYIYVB-ywTjcnEyjtigFRdB9WhzCYSQrO1SxmPaAQuM0TyWLc3I5lKb4TD0yLyIkip-NjZYk0Qxywq8hLoti+LzES1yLLwppGGoSCMmQLJjhcyTqNEP9k3zagcLoEE8jscxSBCx9IRoidrTkwpzDXYhSFaQVimKeqs3qABNAI9hrMB2E4cwlovXIOS2cwZg6LosB6PpqHqgRYE6d8NEyTxltWk78OuVIAjgeJOkIZEyAAISicQNywdrzGu1ZaqouQM0gcRmPSWtIHgfBWnCSHiHwDCTEQPJjOuEwQRBAxoBBEojGuPJijsOTHuKRxEGKATCnEDHKjkSB2gYEJskelZJkgKs4CTFM6zwOBDgCBRek4YH+KEqj8JqBjt0EcJ4DaTpEMVWaGhhgsiy8WlR18R53DQA7CRahJFRQXxlth+HvLtH8vHgQg-BK6oONrO0FeyABHQgolNZjkFg091YyZZ2lQgBSSKd2yAAlahiBRLpqLwC33Ct0X3HF9Mwa5ywBrAOxp29M1snxTRtD0Klii3SAABIyGgSx2myGxiAEMgMAAei72DUHwMF7L0QhrjBZBYC7xvm-wXvWJRw2WN78EDDBPIwQAKzIaCuaR-B+mIDXsFK3fUfRzHsdx-HCeJ0nyfwSmDGp2n6eW7iPg0OGEeyT7CDIXQtCZJFUWIwbjFhELHWAABJIBYtgQp3oJ-cIn0jKIDShhf4ic+CwTIH7GBIDrhgKgBA6B5hM7iywGvQoU4SjwI-jbbIcxggqHgGAAAEm+BopDUjIFAeEYhMCs46zBHJASIi5JyVoTxKAiDsjthiOVYgYAAAyLVEBwQPmAAA4qkcQVZOFSMUNw3hccoGaTIUIuSIJQQCSMBcWh1sv4iG+FcYg1xf76C4fgwhkB+FcMESWMENiDBTjsPYmRIhPpMOiEoPw3koDAJ4QQvhpi-HkNTGCYJeQTBCTCfQkQYFiDtGPKkNmnjEneN8fE2BASDBDWKENXJjioCaKYFWFQsBYCSDKcY8BKSqn+IoRk2m2lQkijoU0yALTqBVjOhdPB5TkkkP6WkteBgBIXxMI08IpQ96KIAHKqDAHNZYpSqleMWQIlZQzQTGCkE0YqEA7lSCAA

**Comment by domoritz** [comment]
@sirahd can you look at this?

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4702
