### ISSUE TITLE
Import of vega-lite fails importing package.json

### ISSUE THREAD

**Issue by backspaces** [vega/vega-lite#4231]
Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [n/a] Provide an example spec in JSON, wrapped by triple backticks like this:
- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

#3964 reports that es6 modules are supported in latest. Using an import from unpkg.com produces an error caused by index.js importing package.json.

    GET https://unpkg.com/vega-lite@3.0.0-rc6/build/package.json?module net::ERR_ABORTED 403

To reproduce, run this:

```
<!DOCTYPE html>
<html>
<head>
    <title>Vega Test</title>
</head>
<body>
    <script type='module'>
        import * as vega from 'https://unpkg.com/vega-lite/build/src/index.js?module'
    </script>
</body>
</html>
```

The problem is simply that es6 does not support import of json files. There are other ways to make package.json available as a module, such as wrapping it in a function that returns the json/object.

**Comment by domoritz** [comment]
You can instead import `build/vega-lite.js`.

**Comment by backspaces** [comment]
https://unpkg.com/vega-lite@3.0.0-rc6/build/vega-lite.js is a UMD, not an es6 module.

**Comment by domoritz** [comment]
I see. Yeah, this is by design right now. If you want to use es6, you need to use a bundler like webpack, rollup, or parcel that supports json until browsers also support json modules.

**Comment by backspaces** [comment]
OK .. I'll try that. Thanks.
