### ISSUE TITLE
Legend text (field name) is truncated

### ISSUE THREAD

**Issue by nelson-liu** [vega/vega-lite#4233]
Not sure if this is a bug or if the problem lies between the chair and the keyboard, but:

I tried to make a visualization, but it seems like the text of the legend is unexpectedly clipped. It looks like:

![screen shot 2018-10-28 at 10 37 06 pm](https://user-images.githubusercontent.com/7272031/47631158-0a0f6a00-db02-11e8-850f-789da8696c97.png)

In terms of expected behavior, it'd be great if the line plot could have a slightly smaller width and the legend would have a larger width---this would enable the full text of the legend text to display.

Here's the JSON config that we're using:

```json
{
  "$schema": "https:\/\/vega.github.io\/schema\/vega-lite\/v2.json",
  "title": "Changes in fruit prices across different regions",
  "data": {
    "url": "fruitprices.csv.cleaned",
    "format": {
      "type": "csv",
      "parse": {
        "date": "date"
      }
    }
  },
  "width": 800,
  "height": 400,
  "selection": {
    "org": {
      "type": "single",
      "fields": [
        "food_type"
      ],
      "bind": {
        "input": "select",
        "options": [
          "Click to choose a fruit type",
          "Fruits and Veggies",
          "Canned Fruit",
          "Fruit Juice"
        ]
      },
      "on": "click",
      "resolve": "global",
      "empty": "none"
    }
  },
  "mark": "line",
  "transform": [
    {
      "filter": {
        "selection": "org"
      }
    }
  ],
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "axis": {
        "title": "Date"
      }
    },
    "y": {
      "field": "price",
      "type": "quantitative"
    },
    "color": {
      "field": "division",
      "type": "nominal"
    }
  }
}
```

The live version is at https://cse442-18f.github.io/A3-An-Overview-of-Food-Prices/ . `fruitprices.csv.cleaned` is a standard CSV file, a snippet is below:

```
food_type,date,division,price
Canned Fruit,Jan 1 1999,New England,0.2462253075
Canned Fruit,Apr 1 1999,New England,0.268969828
Canned Fruit,Jul 1 1999,New England,0.267929145
Canned Fruit,Oct 1 1999,New England,0.2571147275
Canned Fruit,Jan 1 2000,New England,0.2589657875
Canned Fruit,Apr 1 2000,New England,0.256763309
```

Thanks in advance!

cc: @tczhan, @dchin996, @gogomathew

**Comment by domoritz** [comment]
Thank you for creating the issue @nelson-liu. To make it easier to debug, can you create a minimal example that reproduces this issue? It will help us figure out whether the issue is Vega or Vega-Lite.

**Comment by nelson-liu** [comment]
not sure what you mean by minimal example here, sorry---what would you recommend trying to strip out of the gist linked above?

**Comment by domoritz** [comment]
Like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [{"a": "hello world here I am a long title"}]
  },
  "mark": "point",
  "encoding": {
    "color": {
      "field": "a",
      "type": "nominal"
    }
  }
}
```

**Comment by domoritz** [comment]
Anyway, I found the issue. You need to set `resize`. See https://vega.github.io/vega-lite/docs/size.html#autosize

**Comment by nelson-liu** [comment]
Thanks for the help / sorry for the hassle!
