### ISSUE TITLE
escaped quote in encoding title results in parse error

### ISSUE THREAD

**Issue by sidaw** [vega/vega-lite#4234]
setting `/encoding/x/title` to a string with quotes in it results in `Error: Expression parse error: {"nasdfad"sfdsa": ''+datum["a"], "b": format(datum["b"], "")}`

Works in `/title` though, and other escape chars work.

[editor link](https://vega.github.io/editor/#/url/vega-lite/N4KAkARAJAzgxgCwKYFsCGEBcACCCAu+ADjJgPRkBuSA5mgHQ0CW+CArgEb1MD2Z8ydFVpoAtABsWSKgCZ6AKxg8AdhAA04CABM0+DDlBhIlNOLZIYWbAG1wRw0cj7cAQXV2jEDlZkAODwC+Go4Ons4QAELujpDeOACs8YF2ALrgQZpaFnAATkxE+LyqOBAu2DBMKETiSNgcaDnYiA342ADuLAjYqBxIWlla2Dp69NEQSMpwPFpMyjRWDhAAHgseEABmTEjiWlYQGMGehfg1e8poMFrraFoAOhAw61owB2v4AJ5ESHs8OTPn4ggdgynneq0cGy2Oz23kOkA+Xz2AEc2GhlMddExqECjAF0sEIOgcgBrGENIEBIA)

Example spec:
```json
{
	"$schema": "https://vega.github.io/schema/vega-lite/v2.json",
	"data": {
		"values": [
			{
				"a": "A",
				"b": 28
			},
			{
				"a": "B",
				"b": 55
			}
		]
	},
	"description": "A simple bar chart with embedded data.",
	"encoding": {
		"x": {
			"field": "a",
			"title": "nasdfad\"sfdsa",
			"type": "ordinal"
		},
		"y": {
			"field": "b",
			"type": "quantitative"
		}
	},
	"mark": "bar"
}
```

**Comment by domoritz** [comment]
Good catch. Fixed in https://github.com/vega/vega-lite/pull/4235
