### ISSUE TITLE
Empty color encoding passes JSON schema validation

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4236]
In vega-lite 3.0.0rc8, the following JSON passes schema validation (in the online vega-lite editor, as well as elsewhere) with an empty "color" encoding object:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [ {"a": "A","b": 28} ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": { }
  }
}
```

This isn't the case with other encodings like "x" or "y", since they will complain that the "type" field is required. The issue seems to be that "color" is `anyOf` either `MarkPropFieldDefWithCondition` or `MarkPropValueDefWithCondition`, but since `MarkPropValueDefWithCondition` consists of only non-required properties `condition` and `value`, an empty object passes validation.

The underlying issue seems to be that in the `ValueDefWithCondition` type, `condition` and `value` are both optional. It would be nice to be able to express that either one or the other be optional, but since that isn't possible in TypeScript, one solution might be make `value` a required member of `ValueDefWithCondition` and add a new type `ConditionWithoutAnyValue`, and change `ChannelDefWithCondition` to be like:

```typescript
export type ChannelDefWithCondition<F extends FieldDef<any>> = FieldDefWithCondition<F> | ValueDefWithCondition<F> | ConditionWithoutAnyValue<F>;
```

Note that there is a runtime warning about the property ("Dropping {} from channel "color" since it does not contain data field or value."), but since the schema can require that there be a valid value, this enables external tools to be stricter with the vega-lite specs that can be generated.

**Comment by domoritz** [comment]
We never guarantee that a spec that passes schema validation is valid. Having said that, stricter types are usually better so I'd be happy to review a PR along those lines.
