### ISSUE TITLE
size of tick should set stroke width

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4240]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "precipitation", "type": "quantitative"},
    "size": {"value": 2}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/47956917-2c720f00-df6a-11e8-9ae6-5eb758f2d490.png)

**Comment by kanitw** [comment]
This is the right behavior.  Tick is a special form of rect, just like a bar.  So the color you see is the fill, not stroke.  Thus, the size should adjust its width.  Adjusting stroke width makes no sense at all.

**Comment by domoritz** [comment]
Sorry, not stroke width but the width instead of the height maybe? How can users set it right now?

**Comment by kanitw** [comment]
there is mark.thickness, but that's not a channel since you shouldn't do ticks with varying thickness.

**Comment by domoritz** [comment]
Yeah, it should be a mark config prop. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Shows the relationship between horsepower and the numbver of cylinders using tick marks.",
  "data": {"url": "data/cars.json"},
  "mark": {
    "type": "tick",
    "thickness": 2
  },
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Cylinders", "type": "ordinal"}
  }
}
```

I think this is enough.
