### ISSUE TITLE
monthdatehours

### ISSUE THREAD

**Issue by sornen** [vega/vega-lite#4256]
In vega-lite documentation [Time Unit ](https://vega.github.io/vega-lite/docs/timeunit.html) monthdatehours is not mentioned although this works and is useful. The other option yearmonthdatehours takes up too much space on the graph x-axis to be useful in certain situations.

**Comment by domoritz** [comment]
Thanks. I don't think it's officially supported but I can check and add it to the docs.

**Comment by kanitw** [comment]
Be careful to test about leap year.

**Comment by kanitw** [comment]
Will be fixed in 
https://github.com/vega/vega-lite/pull/4258
