### ISSUE TITLE
Support compact embedded data format(s)

### ISSUE THREAD

**Issue by aishfenton** [vega/vega-lite#4264]
Add a new data format option that lets you embed data in something more size efficient than JSON. This is important for large embedded datasets.

Formatting your JSON to be in columnar layout gets some of the way there, but having direct support for something like CBOR, or some other binary variant of JSON, is needed.

**Comment by domoritz** [comment]
Vega-Lite never sees the data so this would need to be supported in Vega (unless we parse the data in Vega-Lite before we generate Vega. We already have support for embedded CSV and arrow is on the roadmap: https://github.com/vega/vega/issues/1300 and I think would be the ultimate goal. Do you agree?

**Comment by aishfenton** [comment]
+100 for Arrow. The main use-case I have is for transferring from Spark to vega-lite charts (embedded in notebooks) so that's a perfect fit. Also didn't realize we had embedded CSV already, so that's already a step forward for me.

**Comment by domoritz** [comment]
Sweet. If you have resources to support us in doing these improvements, we appreciate your help. I will close this issue for now as we already have other issues that cover the issue of transferring data at scale and our roadmap.
