### ISSUE TITLE
Defining selections outside a multi-view operation

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4268]
I am building a multi-view visualization where each view visualizes data from the same table. I am applying a global filter transform outside of a concatenation and would like to similarly define a selection (using **bind**) to generate a dynamic query widget. However, Vega-Lite fails if I define the selection at the top-level. If I instead define the selection on one of the sub-plots, it is correctly hoisted. Still, I don't think this should be necessary.

Here is an [example spec in the Vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YWIm4B3RkupgWyMAFUAymCE3ISsYuhGymCajLB4+uyskUpg3ABmYOjUPtS63KzEmUqaYNnFyDbuYABMAAz1dGogGpBGeGLI2FC+dP50YAAKIWERxpYAnmBm2UUlAOLI5bpNEJCaEZg4wFCsumJdaxukwaHhyfKKKgC+6qvx6Eqwady6qF0A2hoQwJBpjGJ4CpdH6wZAdeDJA7jZDWSBXK4aAC66haiHgyngEQ+XzAoAg+Kg90ez1e2IJBJ+fwBQNM6zwrFQdFBAA8wABeNk1OE4iDInlQDC6ADWBysy1u5MgoPBkK2-NW0NhcvJkrw40InVMsHc1A6KxV+N+jDBmlgH0giuWfINhvczC6dXqEptkHY7k0wMg7lCeAOuge2TUUCU6FQmqglqDkFQ7i6AEYABwAVlqqgF6GZDvqqagcWQhHjtQRNuL5Ju-Mgi3RMQ8wPlEbrNtWfxNByynTTrXV4cgLxr6H2zoNUpevtpOngixr1H1LoQA-DP39HmQ-kBBZwcaT5abUAzsU9bT1OCUYTEnZexqUY6g+mo+Cj4XYYLNODSA9BpZVO+HmeVTcgLJcmEQEDgwTNOxbMQPVMDUQj1Ts1Q1A4AEdWAeNpRioWdh0UXQbzWCcpx1HCVSlTFj1xNZuAwWMcHeHM40dbNakRH8XX3V8qKPHsADE0AXQZhjOYwoxJDACLNL8yyHAlIHRMQXk9CgB1YHsAGJkGkAB2bT4GqOFZMNEJ0HgZhxmU1Tw1qOhtOkiBpPY3EKyJJ4Xjeej60pf5AWWWkIgZJlkFZDkwDjbkVWtSVBRFUwxVIqAq24adG2HCz-xdKCYL3QNEO7A4+3cAcErkvCCO0BBiNrIzSooxdIGXbI13zeNtxqw1OMPZhKNPMRzygJ8wTMCRqBMKBJ2vIFO0GsQBnQTQUpwOz6ycuS-2c3dAOoYDaFA0xwLE41oIOODCAQwl8tMNCMOYLCO3rVZ50on5NBo9A6LABi0yYlj6jY9rVk6rZWm6nsAFlBKGU5RmUMT3KxLUIoNVbDQUpTgZUsQ1IOdS4zSXT2AAFkM+te0IUzzMsrHrNs+ywEcpEJSlcmzNrHBqiTJn2HyYouN+LGnEgEAESAA).

**Comment by arvind** [comment]
Fixed with #6926 — selections can now be defined at the top level of the specification, with an optional `views` property to constrain event handling to specific subviews.
