### ISSUE TITLE
Error with selection on multiple layers

### ISSUE THREAD

**Issue by bkfarnsworth** [vega/vega-lite#4271]
I get the following console errors when I hover over my line chart that has multiple selections defined:
`TypeError: Cannot set property 'source' of undefined at LE.oo._getPulse (run.js:203)`
also
`ERROR TypeError: Cannot read property '0' of undefined at LE.oo._getPulse (run.js:203)`

To reproduce: 
1. Open my vega-lite editor: [Chart broken on hover](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgAZ5IgE7wAHHQBWsbgDtIAGnBR26eAGtqS7qx0ATbFADEAMwCcbtwaOQUjavgcAJldAwwhIAHdGWxYHABYARjkwqFt0PEwcUAhwinQxVmRYBwBtIxywbIqcyDS8ZAdIQLkE1REEhJE5AFYAFTkAdiw5OWGFEbkALS9qmsIlRngGnASANg7uulW4id2RhJTZyFhkBaKHZPLqyHhGOQcExIH1ZsC46QHV1VVD69uEoKuOLdBJ0QLBbrdYKuH5XCqQZAAD0IyHg9VsADV8oUgq1HnQBgluq5XN1pO84WAAL6-CBVI51ZZQZqtdqdOSrfpDEZjeQjaa0uYLJZBaSuDl0OKC8InM7FHCXWbhW73FbrboDLYJQKEnqJaVQf4OaRrAYKOKfQLSN6BWFKqBIlFo5CY7FMq2ufFyOI+wlxVRxSk0yn066MxostodLoDLljXkTAWU8LzRZMhKkmF0JJ7XahZNQWWMc4Kg03O4PVTSVSrLb+1YeuSuMtGnDSaRfdQ+j4dx7SMuO1HorEFd2rOQfOjdOLrVQjQKrIOC0Pw8M4JotKPs1RxnkjPlTGZKyCpkUrVztuKSu3HoslsCK48qh4guTqJuqGEwwLdFuMAFtoMUJams3qfs2BYIsiQ4uiOOI4OCF4KNIkLBAMHaBEuIaQWuzKbmyXSuLuoz7omR5HKe6aknEgRTmWd7yg+f6qmA2rjrW2qem8MJ-gBYC2oE2p0AGGpAv6A7Qc6rqjkE3pNteAzAq46FYbMK41LhG6stGSTEQm-LkdclFBP6SR0DxkEMRczEPKs1abKJMINj6vHGq0PR0OSHx2WaN5HIOUlwe6OykpKs6Kcpi6zMGak4ekTJaVubJ6aRBllsZCEdMCU6-pZpzFoxj5HM+aralezyfJ+qgDLl9rlnxJq9nWVqfms-aQQFw5uqKimyIJ3QTqSGaqdU6nhJpkYEdqKXjGlkEZfx3lXh89H5feRV-BWKw0T6YLgjRF7Eq5CEXnOnnbNVyk0RJTpdTJmWqEJwQdtOkIjRUY2pPFEb4Tp0gzQeSZ1QtbzVQoGqrXK1mQSVrHbGZXw-gG+3HWAJqJJsVrSG+ObtXVnWwd1CFikJpLPNa6zSO9OSfbU33rpNOlxADZHpcK6bk1e3yQwV0N1bDCSKe85kY90qjPaj1q2pqAyuKs4rYwMN0wdJ8H8fWmw1iE2NfAk1N0nF9Q-dpnREizc3A+zDyfISko8+tNnbSS6jrOOPTikrMP-sachvAozwNqoA3vMrgVE-xC4ZgSLSPNONX65UhsJYzpucoM8apYebNprJn6yBm9uFY7rEofL2Y6hVSRSl7fG2p6shi4S6HVqHd1q4JbygihilzjaCe0xNv2m7G6d7rNWfzVbmUhJqOa5vOhd80+W1w4StHfjqceS60QJbNjHbeoSreE-d6v78JHImrLhL90nxtJa05sT5bOcIc0ynZrVt5rUXXssWsIJayIzeA2fM-NvZtiJCSSUzRe7glWMfVWwUejvhBFCGiVpb51UHibdoRFR4kXHkDY8INbSJGzH5a4VlSx-weB8AaBJVggg7IkMBy9a7VSjgkD4HRBLekQUFXEVorxDTKkjLBx4cFJWaE-YhFEp78UGpqCydVqFMVoWqPO5lmgDCtFCL+xUIFo0FtWKc4s44-gMdcAmSCTImlrD+NqZJXASIZPTPCuDBKyMMvCBa3xPzZkXjQ8B-9ujrCvBOccAx0Lcxrj7Gc6g5ZJFliAgR4crTelBHEGEGoqyC1cWGdxiUCLgm8dnM86jVE-yXoYliG14StkqceGxgiFQFNXEUlOIgrRlMnq-JpRw1H1JqLDYZyojFjIdJJNuTI5DtI0p0oe3TmYEP0s-EhCjJnHGqcE5edTUZbJaeHOZ0Vlx3wZksn8vSX4VK2UM4uWzGmHOmSfNWJzqgxVGucjx0i07ckIYDHxQp+l3J2QMza+y4m7P8i82xbTTnYWwYszxI9-lrLkUZTZQTwUNJXo8iZaTT7vIqJ8j63zinRltNcjZILsX4sheAvizzbqvNmfM8ayLpH4LRZnDFvisV5ShtCiFNTNpMsJW89lX0jYXNwdjal8jaWCt5sK3FDL2GivhEcolUq6Yyp+e0QIXQEgKsxUqqpQqcUjLxQciVbKEWxSRfqil7I+irN5UClMCjkkDVkCEbFBwNGsRGBeWQ4Edq2lRtqMWVpzLanBB8NhMKWVwtYtwj4iSUFvF1VIgiHJTX8v6R0asqxNQmgDcXSKQd5BB2aPDBBULWKCUJK4YSoMmxEjtQ8JsZpaLAgGoMZ4ObOV5tRRnIhnqoALSSNwwWYJxTz0DRalVrFi4+reMJQkPkjqNvTZ8WQzwOghEel2lYdbdoUwxphB1XynXJyWW+AtwKKlJBhB0cylD4RqKXXshwJJ9rCQOkHHeUa3g+gUG8RyKFT1ptaNaKc3YQg6mHc6rpTYn1eqLVXH814K1BpJKsJhkomxvlLeLUDM51iSl0fGz0MHeFtUlDscc-pugofvbg3S7qJ3lPTI8cWtE3x4ZCd2hcoUvjTiBGSUDj18Q1g7RaPGzTYWtLTdODyOprTejsux++U0TXccBbxh4HRPi1lfIu4Tv6VgtDFJsaJHZZbklA+qc044TTemrvjFT4di0OezGsEk-oXE3rJXevTOlAgYand6zuttBhWdqd232wF0ELlkxR9468GwtAGlYrVPnT68PJLRXqjwiSqF07Kh+-1DOsz6S+wW2oG4QWXfeH9SWcBvovHtKsTx5agbE7IFjXwQgdesYVtWHRPOyESEwok2SqsGqZtFk8CigRrzMYlkVNmxZ2TBNknYGoG2MroVaHDOxTJgfoxmJsy0dSvr1qFmm5KulmzqxbGlL7fbyyvFabbaq-3iwtFsOW3xtSgY7F8a8WtSQ3abGLeQM8FZseewbcL1Wpp-PHUZhr6YmyltkAl5V7XK1AgbAdz05PfagecWG6q1VAE3ZtO+CT5JvhLZde0MdY9cc3Px1CHrcsAfWv-i0UkB6LR9c-DJsTwkgRIc9t5lNqmNgdFBOLbhzxKto8Thj5bpsdwffWYqxrxbzRee-pa8bgObPehCMJacXx2w2+tXxNi0SZbAd0esG7HYUKeQzMjqKHyzn665xmVb07+qKUCSTxirvxli-K1k9YF5titY1Wem2fb6zdnyzUbVU3Y7kNJIL7017Q+IskSOylcgo-eozM3eQSaqFgsT4aFeyk5xXid18aJwJIegS2M0AdJ6OqTb42BWiYsUJAltJzrpXjjd8ufUyEEYP50i6T92+hfUyqPUH7u7GSSthkmRrLG76ENSShdw2bUi-LlRZX5Otb5qrcro7+WdVhjxUT5V8co-p4rVjyjxnjpqjUN+g8rav-irKpsSjkKSi9uHkvisqAXzl9rMtvp3j-mKhAeEEXvalXo6jXqhpcm6ugfVvzvgYWO3tAY2synAYAbrgPLXp0AuA3u-oMnQUGvin-srkwTqiwa9pcjzgClQZgTQdstbvQadqqoXpPhcEAdIkbpQZ9qblgfHg8LIVnlagQYofCsQbeqQRxlypwbctgd-lIU8jBggRAEgejiYRFp0PKi-sZvITKDwSJh4Z3vwcpgAUIUYWFk4ZjtqMauYZoW1gnjob-lIYQUodFFcAALpGCfIIg6DwDcC2CMA6DUAOChiQCIj5GUiQB4AACeKIjQ9QqAhA3ASg+QQKkAzgxYYg9g644YgopRzAYgTIzg+QJwVwVIqRKQNwugzReRWQVwJ43AOReAxRgyjAAAXvjggUMfYSMWIOgGUacKUFcOpJAJsdsUoLsfaJ9OEBgEoGYPMfaDUOUZUeuBIDoA0AaF+ngFYGYMgAACLoCwCIAnE3EVAnYAk5CBjAlgBJEvE1DcCECmDMBlEXBTgFjrFIkOgZFZE5ETF67AmjFiB1HXFglNEtFtG0FQyQnwh3EJQ6DcCoA5ENFkk1A9HUDIB2AOB9FiADFgkOHHjwmTFgnhDNHICtGNDxH0nhAUmNAACOrA6AOgeAzA6QjAVAk6Rw6AiIjAjEZxx4cpeAPRrJ-RyAopNQixORtgSICRfJaxwJXJRw0JsJ5R+J2JmRdgzAPAegvJfJnhPRaIrpDpHpkAVJcx64Mp1J+QBUIgiA3AVAxxKJuuAJkAeQgRnJhp8ZxyiJnJKJlpsZWJdUFxVx64pwVgSgJgLJkJ6RmR2RuRvpT43AuJxx7pBJApQp64VkyZ4p64VJNJOgdJMZDJNAzJxJbJHJVp9JkAPJ2Z2JjZxJ9Uyp1wbZUAUpMp2pCpSpyZqp6pVZcZ2pupOAg5BpPZ8IxpdgZphh6ZSZPZo5gQG5x4k5jQz4rZFRCUC5sp8pcpSpPZ1p1wtptw9p9Zjpug2RcpugV5VSXpgFbp45fpAZjQwZGAEgRQ4ZkZOx+5iBhpuQzBFpyZCZbyaZVpGZBYH5mpkAuZwFtxD5jQjxzx55sAbx3AHxAA6tELEDgDrjcR+Z6UOD6b+XVDBaGfBRGVGSReSWRc2RibqcmUBeuKgNYCcIhdGaeaxaWcyeWRiYJVAGOZqfCDeeuMZPefcfOdKc+RkK+ZRX6WuRqchWKd0b0fqahVAIeaaUUSebhWeQSZkbWapfyUSY0C2chaUcJVAB2bSWIDOfCIyf2XqeycgO+SOV+XCR5VAFhUQQCZmUqClSSpSCkSSr8PsW8TKbAM4HUagP8SQXVM0WIPUHWRBd-KBZxVOjMbKQhQJXhfaGleCZ0cRVxaRXpZAEoKwGJTDDWXieuJYFsa-ngNwDWXKYQBFUOelVlXsSUUpeiZWZ1eEOpSiYSYKVOTpRtXOZAE+UucZTOZAGZapV0TqdZZFSOfZceQ+M1alS2INZVYRVpSSbzKWXtYFV2cFaWWFSyTufqfhQnAcVsTsTgGUKcRtR1VABRZAPhQaIRdDRpVAHtbUbMSFVAGVT0cSW8YUBmaWScDVRJVVRRPVXgI1WDSTVqf5ccKJSZXyf6cgOgEoEUIGWALjXuX6cTURdJcgLJRjQQWiRWdQIxBDR6VAEUchRCb5WgIQD+QFboA0O+fjRtUtcLWdbFfLcjcqP+S6cTdrZAYKRxdzWjQ1fxTsbZSmUVshWxdcIleaclfdYkbMJlYgUYCkVSEAA)
2. Hover over the chart
3. Open the developer console and see the errors.

For reference, my goals with this chart are:
1. Shows error bands when hovering over a line (see [this vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgAZ5IgE7wAHHQBWsbgDtIAGnBR26eAGtqS7qx0ATbFADEAMwCcbtwaOQUjavgcAJldAwwhIAHdGWxYHABYARjkwqFt0PEwcUAhwinQxVmRYBwBtIxywbIqcyDS8ZAdIQLkE1REEhJE5AFYAFTkAdiw5OWGFEbkALS9qmsIlRngGnASANg7uulW4id2RhJTZyFhkBaKHZPLqyHhGOQcExIH1ZsC46QHV1VVD69uEoKuOLdBJ0QLBbrdYKuH5XCqQZAAD0IyHg9VsADV8oUgq1HnQBgluq5XN1pO84WAAL6-CBVI51ZZQZqtdqdOSrfpDEZjeQjaa0uYLJZBaSuDl0OKC8InM7FHCXWbhW73FbrboDLYJQKEnqJaVQf4OaRrAYKOKfQLSN6BWFKqBIlFo5CY7FMq2ufFyOI+wlxVRxSk0yn066MxostodLoDLljXkTAWU8LzRZMhKkmF0JJ7XahZNQWWMc4Kg03O4PVTSVSrLb+1YeuSuMtGnDSaRfdQ+j4dx7SMuO1HorEFd2rOQfOjdOLrVQjQKrIOC0Pw8M4JotKPs1RxnkjPlTGZKyCpkUrVztuKSu3HoslsCK48qh4guTqJuqGEwwLdFuMAFtoMUJams3qfs2BYIsiQ4uiOOI4OCF4KNIkLBAMHaBEuIaQWuzKbmyXSuLuoz7omR5HKe6aknEgRTmWd7yg+f6qmA2rjrW2qem8MJ-gBYC2oE2p0AGGpAv6A7Qc6rqjkE3pNteAzAq46FYbMK41LhG6stGSTEQm-LkdclFBP6SR0DxkEMRczEPKs1abKJMINj6vHGq0PR0OSHx2WaN5HIOUlwe6OykpKs6Kcpi6zMGak4ekTJaVubJ6aRBllsZCEdMCU6-pZpzFoxj5HM+aralezyfJ+qgDLl9rlnxJq9nWVqfms-aQQFw5uqKimyIJ3QTqSGaqdU6nhJpkYEdqKXjGlkEZfx3lXh89H5feRV-BWKw0T6YLgjRF7Eq5CEXnOnnbNVyk0RJTpdTJmWqEJwQdtOkIjRUY2pPFEb4Tp0gzQeSZ1QtbzVQoGqrXK1mQSVrHbGZXw-gG+3HWAJqJJsVrSG+ObtXVnWwd1CFikJpLPNa6zSO9OSfbU33rpNOlxADZHpcK6bk1e3yQwV0N1bDCSKe85kY90qjPaj1q2pqAyuKs4rYwMN0wdJ8H8fWmw1iE2NfAk1N0nF9Q-dpnREizc3A+zDyfISko8+tNnbSS6jrOOPTikrMP-sachvAozwNqoA3vMrgVE-xC4ZgSLSPNONX65UhsJYzpucoM8apYebNprJn6yBm9uFY7rEofL2Y6hVSRSl7fG2p6shi4S6HVqHd1q4JbygihilzjaCe0xNv2m7G6d7rNWfzVbmUhJqOa5vOhd80+W1w4StHfjqceS60QJbNjHbeoSreE-d6v78JHImrLhL90nxtJa05sT5bOcIc0ynZrVt5rUXXssWsIJayIzeA2fM-NvZtiJCSSUzRe7glWMfVWwUejvhBFCGiVpb51UHibdoRFR4kXHkDY8INbSJGzH5a4VlSx-weB8AaBJVggg7IkMBy9a7VSjgkD4HRBLekQUFXEVorxDTKkjLBx4cFJWaE-YhFEp78UGpqCydVqFMVoWqPO5lmgDCtFCL+xUIFo0FtWKc4s44-gMdcAmSCTImlrD+NqZJXASIZPTPCuDBKyMMvCBa3xPzZkXjQ8B-9ujrCvBOccAx0Lcxrj7Gc6g5ZJFliAgR4crTelBHEGEGoqyC1cWGdxiUCLgm8dnM86jVE-yXoYliG14StkqceGxgiFQFNXEUlOIgrRlMnq-JpRw1H1JqLDYZyojFjIdJJNuTI5DtI0p0oe3TmYEP0s-EhCjJnHGqcE5edTUZbJaeHOZ0Vlx3wZksn8vSX4VK2UM4uWzGmHOmSfNWJzqgxVGucjx0i07ckIYDHxQp+l3J2QMza+y4m7P8i82xbTTnYWwYszxI9-lrLkUZTZQTwUNJXo8iZaTT7vIqJ8j63zinRltNcjZILsX4sheAvizzbqvNmfM8ayLpH4LRZnDFvisV5ShtCiFNTNpMsJW89lX0jYXNwdjal8jaWCt5sK3FDL2GivhEcolUq6Yyp+e0QIXQEgKsxUqqpQqcUjLxQciVbKEWxSRfqil7I+irN5UClMCjkkDVkCEbFBwNGsRGBeWQ4Edq2lRtqMWVpzLanBB8NhMKWVwtYtwj4iSUFvF1VIgiHJTX8v6R0asqxNQmgDcXSKQd5BB2aPDBBULWKCUJK4YSoMmxEjtQ8JsZpaLAgGoMZ4ObOV5tRRnIhnqoALSSNwwWYJxTz0DRalVrFi4+reMJQkPkjqNvTZ8WQzwOghEel2lYdbdoUwxphB1XynXJyWW+AtwKKlJBhB0cylD4RqKXXshwJJ9rCQOkHHeUa3g+gUG8RyKFT1ptaNaKc3YQg6mHc6rpTYn1eqLVXH814K1BpJKsJhkomxvlLeLUDM51iSl0fGz0MHeFtUlDscc-pugofvbg3S7qJ3lPTI8cWtE3x4ZCd2hcoUvjTiBGSUDj18Q1g7RaPGzTYWtLTdODyOprTejsux++U0TXccBbxh4HRPi1lfIu4Tv6VgtDFJsaJHZZbklA+qc044TTemrvjFT4di0OezGsEk-oXE3rJXevTOlAgYand6zuttBhWdqd232wF0ELlkxR9468GwtAGlYrVPnT68PJLRXqjwiSqF07Kh+-1DOsz6S+wW2oG4QWXfeH9SWcBvovHtKsTx5agbE7IFjXwQgdesYVtWHRPOyESEwok2SqsGqZtFk8CigRrzMYlkVNmxZ2TBNknYGoG2MroVaHDOxTJgfoxmJsy0dSvr1qFmm5KulmzqxbGlL7fbyyvFabbaq-3iwtFsOW3xtSgY7F8a8WtSQ3abGLeQM8FZseewbcL1Wpp-PHUZhr6YmyltkAl5V7XK1AgbAdz05PfagecWG6q1VAE3ZtO+CT5JvhLZde0MdY9cc3Px1CHrcsAfWv-i0UkB6LR9c-DJsTwkgRIc9t5lNqmNgdFBOLbhzxKto8Thj5bpsdwffWYqxrxbzRee-pa8bgObPehCMJacXx2w2+tXxNi0SZbAd0esG7HYUKeQzMjqKHyzn665xmVb07+qKUCSTxirvxli-K1k9YF5titY1Wem2fb6zdnyzUbVU3Y7kNJIL7017Q+IskSOylcgo-eozM3eQSaqFgsT4aFeyk5xXid18aJwJIegS2M0AdJ6OqTb42BWiYsUJAltJzrpXjjd8ufUyEEYP50i6T92+hfUyqPUH7u7GSSthkmRrLG76ENSShdw2bUi-LlRZX5Otb5qrcro7+WdVhjxUT5V8co-p4rVjyjxnjpqjUN+g8rav-irKpsSjkKSi9uHkvisqAXzl9rMtvp3j-mKhAeEEXvalXo6jXqhpcm6ugfVvzvgYWO3tAY2synAYAbrgPLXp0AuA3u-oMnQUGvin-srkwTqiwa9pcjzgClQZgTQdstbvQadqqoXpPhcEAdIkbpQZ9qblgfHg8LIVnlagQYofCsQbeqQRxlypwbctgd-lIU8jBggRAEgejiYRFp0PKi-sZvITKDwSJh4Z3vwcpgAUIUYWFk4ZjtqMauYZoW1gnjob-lIYQUodFFcAALpGCfIIg6DwDcC2CMA6DUAOChiQCIj5GUiQB4AACeKIjQ9QqAhA3ASg+QQKkAzgxYYg9g644YgopRzAYgTIzg+QJwVwVIqRKQNwugzReRWQVwJ43AOReAxRgyjAAAXvjggUMfYSMWIOgGUacKUFcOpJAJsdsUoLsfaJ9OEBgEoGYPMfaDUOUZUeuBIDoA0AaF+ngFYGYMgAACLoCwCIAnE3EVAnYAk5CBjAlgBJEvE1DcCECmDMBlEXBTgFjrFIkOgZFZE5ETF67AmjFiB1HXFglNEtFtG0FQyQnwh3EJQ6DcCoA5ENFkk1A9HUDIB2AOB9FiADFgkOHHjwmTFgnhDNHICtGNDxH0nhAUmNAACOrA6AOgeAzA6QjAVAk6Rw6AiIjAjEZxx4cpeAPRrJ-RyAopNQixORtgSICRfJaxwJXJRw0JsJ5R+J2JmRdgzAPAegvJfJnhPRaIrpDpHpkAVJcx64Mp1J+QBUIgiA3AVAxxKJuuAJkAeQgRnJhp8ZxyiJnJKJlpsZWJdUFxVx64pwVgSgJgLJkJ6RmR2RuRvpT43AuJxx7pBJApQp64VkyZ4p64VJNJOgdJMZDJNAzJxJbJHJVp9JkAPJ2Z2JjZxJ9Uyp1wbZUAUpMp2pCpSpyZqp6pVZcZ2pupOAg5BpPZ8IxpdgZphh6ZSZPZo5gQG5x4k5jQz4rZFRCUC5sp8pcpSpPZ1p1wtptw9p9Zjpug2RcpugV5VSXpgFbp45fpAZjQwZGAEgRQ4ZkZOx+5iBhpuQzBFpyZCZbyaZVpGZBYH5mpkAuZwFtxD5jQjxzx55sAbx3AHxAA6tELEDgDrjcR+Z6UOD6b+XVDBaGfBRGVGSReSWRc2RibqcmUBeuKgNYCcIhdGaeaxaWcyeWRiYJVAGOZqfCDeeuMZPefcfOdKc+RkK+ZRX6WuRqchWKd0b0fqahVAIeaaUUSebhWeQSZkbWapfyUSY0C2chaUcJVAB2bSWIDOfCIyf2XqeycgO+SOV+XCR5VAFhUQQCZmUqClSSpSCkSSr8PsUpeiZWVxTUOpSiYSYKVOTpcVXOZAE+UucZTOZAGZapV0TqdZZFSOfZceQ+HhfaB+TiXiQVZpV5c2dUqWZVYFV2cFaWWFSyTufqfhQnAcVsTsTgGUKccVcRQ8TkQ0PhQaIRetRBVqf5dMbMSFVAM0WID0cSW8YUF1alRlYMUYCkVSEAA) for the desired behavior)
2. Has a vertical rule that follows the cursor
3. Have the points on the lines show up as the vertical rule passes through the points

Right now I can achieve 1, but not if I combine it with 2 and 3.  That is when I get the console errors. 
 
Update: Here is a link to a video of the chart I am trying to recreate with vega-lite:
https://drive.google.com/file/d/16t6OTnTcfUwaG-5B1ZDP8Ngghol-a2Df/view?usp=sharing

**Comment by arvind** [comment]
Fixed with #4353. Thanks @bkfarnsworth!
