### ISSUE TITLE
Duplicate Dataset error in Vega-Lite 3

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4274]
Recently an Altair user discovered this error in the Vega editor, which is running Vega 3. Example here:

[Vega Editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KABsAhgE8CAJ1IBtMRFAR1USpOqTSOeJIC2BUpC06AtNAIB2ABwAjSXbsNoAThsBGPpMl9EBwIGG18vREoCADYAVkkTERV1SENJOQBrUwAHWGR4XlENCEgCeDhKPPQsNSLigA89SGppLJMsSABHAFdJfOQdamRcE3ZIFAJxSlMGxNri6Ubm1tNu3sGBoZGoccnTBcEkiAONWfUajTNtXWrIA2NTc0krW0dnVw9vX39A4NDJcMisXikFOF1SGVM4jyI0OUFK5Uqelh9UWLTaUFWfQ2w0gox2U3aM0Kc0gCxuS3RnR6WO0m1x20Iu3a+1hx3UbIAusTIAASADO0E4qVMPGoWT5GAA9JLhqhJAA6VD9WhdBzy5CwSUCoWSGUEOUWKHUAgygBM8qi8qY8oAVnyELixJcdHyCNQ+UiLo9nvYnC43J4fH4AkEQmEItE4ujlLUcA0sGwoGSwExQWdIPGwF5RsmvGnVBnSKac6RU0kOWIDoIgA)

The Altair chart that generated this is as follows:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({'x': [0, 1, 2], 'y': [0, 1, 0]})
chart = alt.Chart(data).encode(x='x', y='y')
chart.mark_point() + chart.mark_line()
```

Is this intended, that a named dataset can only be referred to once within any compound chart in Vega-Lite 3? If so, we'll need to rework how Altair handles data internally.

**Comment by domoritz** [comment]
That's a bug. I'll fix it ASAP.

**Comment by jakevdp** [comment]
Thanks!
