### ISSUE TITLE
bind select should respect numbers

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4276]
For options in the `input` `select` option within `bind`, it mentions that I've used an `"incorrect type: Expected "string"` when using integer values. 

I think it should be a valid type. (it doesn't work if my `select` options are strings, and it does when set as integers)

Screenshot:
![type_string](https://user-images.githubusercontent.com/5186265/48902773-e4078c00-ee59-11e8-8832-7e119c1a1f57.png)

[Specification url](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIsZGOTw8PFfo2uAJpGZqAQ4VB4AJ6EyGZujErUnmoB4ZAAZowemrBmANqQgcg2kAC6LhFQ7ImaoUUlIfqQiYSsePHunt5qUNyEPsp5OPkAjACcAOzSqmATkwAsZY6OaasQzhqQeEboSrAZ3EaoBWkG1mLwrGI6cTiQUY0AFNp4rKh0xTYAlL2Q6MMoF8QpsIgYsmI8MgmmADF0vIM-ECQeswBUthgjABreLwRhGeApSqQZBKeDcTSJaihNKQAAe9SyOXiAAkju5CNwAO7Qv7RWLxACOrD2Pl0PiokFB6SijOyYjq9wAsoxPLAAPqxIzqgDi6DEYmUfJidygwtFzB0jEl0tc5MNMPB8sVUAA8kZGEwVLNtib4kpuKhEvqpRpVo4gA)

**Comment by domoritz** [comment]
@arvind is there any reason to use only strings? If not, I'll fix it.
