### ISSUE TITLE
Drop ES5 support

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4283]
Since almost all browsers are on ES6 now and node has been on ES6 for a while, it's time to drop support for ES5 and create smaller/faster code and use new features like Set. 

The only straggler is RStudio, which is still on ES5 but will update to a modern engine with 1.2 (https://community.rstudio.com/t/version-of-javascript-es5-es6-supported-by-the-ide-browser/14484, cc @ijlyttle). The release is planned for the end of the year 2018. We will wait till then and it might make sense to push off the Vega-Lite 3 release till then.

**Comment by kanitw** [comment]
This sounds nice to do, but requires a lot of engineering efforts. Thus, I don't think this should be a blocker for 3.0 release.

**Comment by domoritz** [comment]
The easiest thing would be to just switch the output from Typescript. The only piece of our build pipeline that does not support es6 is uglifyjs but we can just switch to https://github.com/terser-js/terser.

**Comment by domoritz** [comment]
I'm switching to terser in https://github.com/vega/vega-lite/pull/4285. It is the actively maintained fork os uglify anyway.

**Comment by ijlyttle** [comment]
Hi @domoritz, @kanitw - please don't let R block you moving forward with v3 release. The new RStudio IDE is in preview and there are some packages, [r2d3](https://rstudio.github.io/r2d3/) for example, that require the new version.

My guess is that 99% of what we need to do, we can already do in the browser - and in the new IDE. There are some functions in the "vegawidget" package that use an implementation of V8 or phantomJS - functions to validate and compile specs, and to create pngs or svgs. These packages are "stalled" at ES5, but it is clearly on us (R folks) to sort that stuff out.

**Comment by domoritz** [comment]
Okay, I'll bring this up in our next meeting with @jheer and @arvind so we can make one decision and move not just Vega-Lite but also Vega, Vega-Embed, and Vega-Tooltip to ES6.
