### ISSUE TITLE
Selection code generates non string keys

### ISSUE THREAD

**Issue by jsa-aerial** [vega/vega-lite#4286]
VGL 3.0.0-rc8 with VG 4.3.0

In a layer view, for a given layer an encoding field with a string name containing non legal JavaScript name characters whose encoding channel is referenced in a selection will cause a parse error. The ultimate cause is that the field's name is not maintained as a string.

For example, this:

```
{"hconcat":[{"encoding":{"y":{"field":"-log10(pval)","type":"quantitative"},"color":{"field":"NM","type":"nominal","scale":{"range":["#e45756","#54a24b","#4c78a8"]}},"size":{"condition":{"selection":{"not":"brush"},"value":40},"value":400},"x":{"field":"log2FoldChange","type":"quantitative"}},"mark":{"type":"circle","size":40},"selection":{"grid2":{"type":"interval","bind":"scales","translate":"[mousedown[event.shiftKey], window:mouseup] > window:mousemove!","encodings":["x","y"],"zoom":"wheel!","resolve":"global"},"brush":{"type":"interval","on":"[mousedown[!event.shiftKey], window:mouseup] > window:mousemove!","translate":"[mousedown[!event.shiftKey], window:mouseup] > window:mousemove","resolve":"global","mark":{"fill":"#333","fillOpacity":0.125,"stroke":"white"}}},"height":400}],
"data":{"values":"fake_data_val"}}
```

Will result in this being generated during selection compilation:

`{log2FoldChange: grid2_log2FoldChange, -log10(pval): grid2__log10_pval_}`

Which will generate a JavaScript syntax error for the `-log10(pval)` key which signals a "Expression parse error" from VL: 
```
Error: Expression parse error: {log2FoldChange: grid2_log2FoldChange, -log10(pval): grid2__log10_pval_}
```

The generated keys should be maintained as the original JavaScript strings, so the above generated code should be:

`{"log2FoldChange": grid2_log2FoldChange, "-log10(pval)": grid2__log10_pval_}`

**Comment by arvind** [comment]
Fixed with #4287.
