### ISSUE TITLE
Nearest transform can cause "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4298]
Basically, `nearest` transform can cause a selection entry value to be `undefined`.

**Example**: [link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVkrSEx3AJ6pkSvCPTwT3WLBGMSpqssHgmjMiw8ooqGgC+6kZh6EqwAGbcJqgWANoaEAaGRmmMYnjIJhaQ2nisqHSwFRGwALxtAOQAkkoZWTo8Su2Q+WBxGgC6iVBu8NyagdQWhUYAHksjxRFimlU1yGobUHhOhPs4kOWohJno5iMJI5BO60WbyNtVs7Z4B69HJ2coABHVgpPDMfpUYZFMYQB5GMToJwVXIjZaGSAYEwAaxef3+pyqEjsv3xkHgpkUlXO10C5UqUz+kBKYjEyB2ODSt0ah1hhnhhnRRixuP0hySAKqtPcpKZFJMVKl3DpKMZr0g3EIXmYzxwAEY1UVIKEfNjAZB2Ij4LjDRiWeZzgBiAAs8AA7AAOdAe6GvAVGxps+Dg5R4pmB5DB9lhsnHQnnVCsMqMWVk0PneASa2ppkmSLcMRQ87URzsW459X2Y5VW53fGjW1GRCMaiICSt8ocsBC9Vx82wBZsitGqu6qBKZT7RsYuzoPOhCxhVjIadGdNQVDcELIbhUSri0a822QGZzBYxo2a7XVsX1oyzILMAYX2ORH63u+X6lgPKfv49v8oAjYNn3OZtW3bfBowPet-UA7sYLvSAUi7X94KZNklGoFgAAoanQHCAB1jXeSNOwAfVCTJkGIgBKWjh3ggD0KA0iQPXEig07X0WP5RD63Gfi-SEiBBMAuD60gChbmXCw9UQiT1WksRZJwAAGA8+Rhe4JhAOIgA)

This will cause `"TypeError: Cannot read property '0' of undefined"` on [this line in the vega-parser code](https://github.com/vega/vega-parser/blob/master/src/parsers/expression/selection.js#L30).  

Perhaps, the fix is to check if `values[i]` is valid before running `isDate(values[i][0])`.
But I'm not sure if there is a bug elsewhere in the nearest transform's logic. 

Note that removing `nearest: true` makes the problem disappear. 

cc: @jheer

-------

**Spec**: (Just in case the sharing function is broken)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/unemployment-across-industries.json"
  },
  "transform": [
    {
      "filter": "datum.series==='Information'"
    }
  ],
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "count",
      "type": "quantitative"
    }
  },
  "layer": [
    {
      "mark": {
        "type": "line",
        "cursor": "pointer",
        "filled": false
      }
    },
    {
      "mark": {
        "type": "point",
        "cursor": "pointer",
        "opacity": 1,
        "stroke": "black",
        "fill": "#4c78a8"
      },
      "selection": {
        "selected": {
          "type": "multi",
          "on": "click",
          "resolve": "global",
          "empty": "all"
        },
        "highlighted": {
          "type": "single",
          "empty": "none",
          "nearest": true,
          "on": "mouseover"
        }
      },
      "encoding": {
        "opacity": {
          "condition": {
            "test": {
              "or": [
                {
                  "selection": "highlighted"
                },
                {
                  "and": [
                    "length(data(\"selected_store\"))",
                    {
                      "selection": "selected"
                    }
                  ]
                }
              ]
            },
            "value": 1
          },
          "value": 0
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Great bug report, @kanitw. Thanks for narrowing it down to the `nearest` transform. Should be fixed with #4353.
