### ISSUE TITLE
Add support for clearing selection

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4306]
1) Cannot deselect marks in tabular heatmaps

As deselection is only triggered on the plot area, there is no area to click to deselect 

```json
{
  "data": {
    "values": [
      {
        "Actual": "Class A",
        "Predicted": "Class A",
        "Count": 13
      },
      {
        "Actual": "Class A",
        "Predicted": "Class B",
        "Count": 0
      },
      {
        "Actual": "Class A",
        "Predicted": "Class C",
        "Count": 0
      },
      {
        "Actual": "Class B",
        "Predicted": "Class A",
        "Count": 0
      },
      {
        "Actual": "Class B",
        "Predicted": "Class B",
        "Count": 10
      },
      {
        "Actual": "Class B",
        "Predicted": "Class C",
        "Count": 6
      },
      {
        "Actual": "Class C",
        "Predicted": "Class A",
        "Count": 0
      },
      {
        "Actual": "Class C",
        "Predicted": "Class B",
        "Count": 0
      },
      {
        "Actual": "Class C",
        "Predicted": "Class C",
        "Count": 9
      }
    ]
  },
  "encoding": {
    "y": {
      "field": "Actual",
      "type": "nominal"
    },
    "x": {
      "field": "Predicted",
      "type": "nominal"
    },
    "color": {
      "field": "Count",
      "type": "quantitative",
      "scale": {
        "zero": true
      }
    }
  },
  "layer": [
    {
      "mark": {
        "type": "rect",
        "cursor": "pointer",
        "filled": true
      },
      "selection": {
        "selected": {
          "type": "multi"
        },
        "highlighted": {
          "type": "single",
          "empty": "none",
          "on": "mouseover"
        }
      },
      "encoding": {
        "fillOpacity": {
          "condition": {
            "test": {
              "and": [
                "length(data(\"selected_store\"))",
                {
                  "not": {
                    "selection": "selected"
                  }
                }
              ]
            },
            "value": 0.3
          }
        }
      }
    },
    {
      "transform": [
        {
          "filter": {
            "or": [
              {
                "selection": "highlighted"
              },
              {
                "and": [
                  "length(data(\"selected_store\"))",
                  {
                    "selection": "selected"
                  }
                ]
              }
            ]
          }
        }
      ],
      "mark": {
        "type": "rect",
        "cursor": "pointer",
        "opacity": 1,
        "filled": true,
        "stroke": "black"
      },
      "encoding": {
        "strokeWidth": {
          "condition": {
            "test": {
              "and": [
                "length(data(\"selected_store\"))",
                {
                  "selection": "selected"
                }
              ]
            },
            "value": 2
          },
          "value": 1
        }
      }
    }
  ],
  "config": {
    "axis": {
      "zindex": 0
    },
    "scale": {
      "bandPaddingInner": 0,
      "bandPaddingOuter": 0
    },
    "range": {
      "ramp": {
        "scheme": "yellowgreenblue"
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/111269/49404964-ec877e80-f705-11e8-9a0b-49c7c1c1d238.png)

2) Similarly, when `nearest: true` is enabled, there is also no way to deselect mark. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Drag out a rectangular brush to highlight points.",
  "data": {"url": "data/cars.json"},
  "selection": {
    "sel": {
      "type": "single",
      "nearest": true
    }
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
      "condition": {"selection": "sel", "field": "Cylinders", "type": "ordinal"},
      "value": "grey"
    }
  }
}
```
![image](https://user-images.githubusercontent.com/111269/49405048-33757400-f706-11e8-9fd4-aa18ec80652e.png)

**Comment by djbarnwal** [comment]
@kanitw Changing `field_tuple` signal's source from `scope` to `view` seems to generate the expected behavior. That is, changing the deafult source to `view` in the below line
https://github.com/vega/vega-lite/blob/b4bc7fe2594bedb446a0a17d49daf418b6030a62/src/compile/selection/parse.ts#L45

Is there a case where we would want to avoid using `view` source? I ran all interactive visualizations from Vega-Lite examples. All of them worked as expected except for the Multi-view Crossfilter example. Would it be a good idea to change the default scope to `view` and refactor interval selection accordingly (so that examples like Crossfilter are supported)?

**Comment by domoritz** [comment]
@arvind?

**Comment by arvind** [comment]
This issue is tricky to address because we don't have true event capturing/bubbling (vega/vega-scenegraph#53). As a result, we've had to rely on the `scope` source to ensure that signals only fire for the subplot a user is currently interacting with. If we were to switch it to `view`, we would find (as @djbarnwal) has that when selections are defined within faceted/repeated views, all signals within each subplot fire during the same cycle and would produce conflicting effects on the selection state. Moreover, once we introduced interactive legends (#4317), the `view` sourced signals will also fire over legends (which have a separate backing data structure) and pollute the selection state.

I've proposed a way of stopping event propagation in vega/vega-scenegraph#66 that should help us properly support this feature request.

In the interim, one workaround might be to say that for discrete selections, if only one item is in the selection store, clicking a mark that is selected would toggle the item out of the store. I'm not fully convinced that this behavior is right -- and I would need to test it out to be sure -- but I'm not able to think of any other viable workarounds right now.

**Comment by kanitw** [comment]
Oh and for `nearest: true` case, [having `nearest`'s distance limit](https://github.com/vega/vega-lite/issues/4262) could help mitigate this.

**Comment by kanitw** [comment]
I start wondering if `clear` is a better term than `reset` -- I'll amend the comment above.

**Comment by kanitw** [comment]
This issue is extremely critical. 

If we have to implement one of these, `clear: {"on": "dbclick"}` might be a better one because toggling wouldn't work well for non-clicking interarction. 

For example, [a line chart with rule on hover](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAMp5u8ANZhC++DrDcAZmACsYACrIkYAMLcqIToSoxO3FS63oyoyHRqGpCa6HiYOMCQrLpi2Fqp6HyWNrB08LAUkAC+6hCQeLqhsC7cuqh5ANqgEHUujGJ4yLp5mX3IYpp5kLAAnqjs3LmqUMgAjqzouaYAgtsACgAy1RpVALq1K0rw3JqMStQjGnUAHiOQYxNTKYNqUHgzhGQU0GwVam2OEBqSTE6BmQ063R6kAwumsUwkSiBFzqyCuNzuDwyTyRMzeH0mpnsjEcv3qAKBpnWoSMaSMVAhPSqJ1UwDAxMguOut3ujx6SO4IXgzFJRLFYsg1yUtyMyjesHGvhVJlwjGoiAkesGk2WkAom1YDLAAEYoXKkWaxBa8gAGYmQvli21ImFw4Y4LpuqAotEZOmAqa6VhiLF-biLIyEPIuTbqrme5aI+XBt7-cOmQbPPDVbFIwX4kWyu1-ZCFsnhT6UhwxsOWyBMpQs1KMdleu2QGVgTIOp04ETuNNyieQjOB6Ya+Ba0VVyCIXX6tdGpdVv70qawAnR36B+Wq0yobisdWReHLY+lvHC6iwTqQV7nO844L-KZKZRYj9QJi6C6DoRY4A0Fp3lOnIlnU2ahrmraENwdxFiaEroFK344FaJr7gAXpaVrOs6Jp9GIWxQAA7quPx4Q03DWK27AwjYxazmWj5bnK-Z1uMFJQFSNImohUztp2bJAtBkLEmcJynCAXJAA) would need a good way to hide the rule on mouseout.  

It seems like we can easily add the following to the tuple signal (`highlighted_tuple` in this example) 

```
{
  "events": [{"source": "scope", "type": "mouseout"}],
  "update": "null",
  "force": true
}
```

and get [the right mouseout effect](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAynm7wA1mEKb4asNwBmYUWAAqyJGADC3VIXQzGNtxU6i6MqMh0CkqQ6KzGsIwAXsjYUL7KURCQ6cqMMtSpoopZAO6MyiypAEwADDXFuMiM1PjVdQ2QsHgAngA2KfrWvb2ZKuh4mDgA2koQwJAy6OGpkIjNiL3reMjKAPpd3OopAL4Nc7MQUIvL+tKs6ta7NaOXUPcj+srjIgdmsHTwWAUF6XSB2Q4YPCpUCvV6QHqEAZQQHAs6w7LodSwJHzWDdVDsbgfKBdTT5BRjbYrL5U04XOGqTaoZjIdQreSQelgOmwqB4dR+WDg9SoVJTeYIpFgxi9bZs+RQZAAD0s1PGrFQUwAOp18YTejqALoAXlNOoAguaAAoAGR1kGOhouxyUho6CWoi16sDFFxh6OuUtY-ihaKyFHQvVYOJ56Nkvt5c0gyCoMjwPv0qG4rGxWaoFMgrEINKljFgziL-QAFNR1NnCFWAJSNsAAfjAtfrTbAOGDzAdXKdr1j515CyWUrWLU2LW2GTDb2L4ylFF6BmQ-XgOlkACU1ESqFWdVONlsdvtjEcdY3OcO0f64YGVieZ-hz3hKykF5B49MuaPEyyFNkDTDMwHFTpsweKUEG4REC0lFYsxzZAglZB03X-UEixLNUP1QMAADJCLAFlUCbOgMHUUxKMxUxJTAABCU0wAAck7ItWLbMBgD7PAcB1Xp0G6VldgARl2ISRPUXYqh1BU7ACXplBIMAXzPPYP0IfpdkUjcVIVCMozUaYqzIiiywANUOWRuEYbiaQ1OhHIInAXMbbVIBLI1DWOHswBkVhhhBMdhWsVJ+WjLDTgfRNk1TdMxVxKDwtueA4K-PlungzNs2xbMoUdBc4Rw5cVkC4LitBMKkUi5BosHZ17y5ccblwdZXznXYtJ0vTlJ9b8jOjJLpX0vDMsgJA-BkDcViVBDsqlABRDCmr9Fqn30dTZ3PLNcjsboQsXXDcv27oj1WDqNIvQ5kHktSrp2zTPwVOqb2dV0Oio0wwJmV5YqyTaoCk0Sal2b6BpaxD9E2Gajs6Hp+jFSBYZSTCx2kdQoRweY+oyT51U1HVvMgQ0C0OVQ2U+NRrBkXJyRHaq61FHGvO+FY7mgp4HW-ED0tUaEsMLJcqRxrCslJbhTBxSAhqlABiAAWeAAHYAA50DVnnxb5bgiR0QhBcAuEPS9FZgGJ5cdRwHRwgAMQhcYqxczySbdNiAFJ2DAD3lAVD2AE1WMbBUdUsRhrGtsBhUhZ3Cc88PI9J0PIGvY5b2Nxmx3m1mEEjKV5oVUblPG7XjagQ7c-gfOVkOou8ZWROTiqrJVEUmb8Z4nWJeaM2Cfw12rdJpiWIq3oiJIxiywAOXQae44Hy3tiNFtiLAF2w6sO7h+Y40AqC8e16n2BZ-njfsi3leM8Al0b65W-LkZgGrgnFYQZkiT36ecG6MhsdoagOoIKX4WpdD6EiKYkAgFI3RuiOwzNoRswmBzFKyBuZZ0VDIfmOIhalVFl3cu8I9ayi0IguWqQ7CRmxBgk2-IpYQO7gQ8uoJthdDwhqQey9h6mj3mPMAAAffhpET5zwXhwpe29DQ3hbuichOAx6MJobCeYcioDsCEmYAc5dYGAR-L4eAzBK7gUYc-XRrDsZQCrKudcm5twyFcF0C6203x7AOFeCk7lpGMPDJGYaOAxKKJkUmVRNQH6AR0XFHOPFOjVyRvoQuUAG792bjrSARjcZKU7vMDihstpNFnA6JRWRuhVDIb4pEoSGq8jCdyZqY4gYo2EqJT+TSP4-2on-dEAD4TKlDKAxGECelKihBErI8DvCIJpJMEkqD0G8ywdwAWYtdF4JwYQxSwU-zMKYdsnpbD+7iKQZIsAPD97DAEUImeojz5uy8dsnxxlUgKO2UUy4KjykrHUegTRNTeSjLjPowxCZmGmLiuYlYVi1wbjcHYhxeAnGPRcTddxCpPFHV0aogJLygnRJCb82E-y4TGH1qQ5ZzDOi90jObCRUdbbIAdiKJ2Nyh7u1Yl7H2fsfZBxDmATeEdt44Bjky+OfKk7ux1Gna+iZXmQCibiWJBcCxJMpCkwh6TZYfJwAAWlEDK7YwzEGmypfoIV8Lz5NyNCna8ZdjYxBnHoXFmrkQgTlFo6V981r-Q2q-GGrTxKST9VUdpP14bdLxASIk8MwFxPAtkOyaZk4tXGSzaJUyUH3EeM8DByYFlLJ2eiVZRtbVwW+UCrZILvF8jUBYyAkKbEwt0HChF05rpuO3qiwmzZ0VxUxYEkxGrHk4EqdomR0pNnGO2aC-+1b2FEyOUaE5o8D4XOEafMRc7bkrvNZfbhS7zmCNXdckVF9+VXxxQ8vxZzeh9snQOy9kAShrFpDrQloJJbS2BeXKdXSZ0HI3SyxdvDl0HquWfY9m6D3btPbuoD+7LkiLA4vE9Yq7n3LvUiZ5zDXnBKdZAL5PyX2joSMkMpg6wBiTqHq4hBsi2EKNcSSAFt50RTCPSx2ZrwMsoVGy72vt-bcpThaih7H10Jx3eK1OkBGzpx1jKuVMSa7xKVZk0uMr1V5xjWk5TY19BNzddUj1d51r1J9cDP1LTpKyV2BQGyMg7KhsWo3cYiB4bJsmezX1lmLOiSDRDG1cI+aLLWXFF16EyW6I2cSd5ZH4QChkLAXwRwE0yvfcgAA6uUSorMQl0AAMy6qI3Qj92XcP8kFIll1-m4pWVs-ZkrZG6r4ogPi7NZX4sx0-co1J3SbN1js4wbtWR5PKlVH+5yhM6BKhXVm0d6qRtUygDN1JxGIG4kpQxsoFQXOnGifR58+TWiOiqQSj6EBYEKf6L9YzAZTOyoczlPkrH4bKG8OgPI7nkG3Fmc8euKnklVayHF6gED6i7fWysTblQjtGa9SZtqWnvzdNRpiZ7r33uszTV9jNaCfuJL+2kLeAPAF+GByNPbeStg8zADUf5Cx+URSAcgb8yQ6wM6isOT60R0BKjUJ15+F3FXfkOAEBN+hCQEAmd+Ws5QKFUKZ1DZgmncLfiEuwDcdsoywBczbRnKv0Bq96AAeWCEJXJYA6qI4jqYLwwYLFrc9Ma51MoqyQ8QKQRWNQbzZsSHkVQUSsWPzqeiDTguWrC8q2L7gEvRRS80MoAwCra7w2l53C3CuzA29F2Dh3DHrDO9d+7z3ROvJo4dZQ708uxyq43GBcv2JvwYCVEtYZEfqcN7yM37YWf6jp5DYKuXzPffKlSDUT1bzQGJ-0HXMPmhW8o2QHYPpY4U+y4r5bvAmm9N64N8b1kpu2eV66VbzPduKU55WHn3oVYUBbEL17wfdNh-+LHwBE2k+K7w3D1n+fi-k9x4T4plAIXC1CvjrtGJbhntmFnvbn3E7lfjfrOHfsXi9hgOjtHAPi1NXt6KvvXi1I3p3q3j3mOMyDIAQd3hAX3ugWvi1D7o-lEqPhzmdh0OlDIIpAUKzNzmWAHIgiQWQRYrlqEi6McEAA).

**Comment by arvind** [comment]
I think supporting `clear` should be straightforward enough, and a good first feature for @allenjlee to take a shot at. We'll want to make sure that `clear` is not only supported by discrete selections (`single`/`multi`) but `interval` selections as well.

**Comment by kanitw** [comment]
> Regarding syntax, I'm not sure we need the extra nesting? Perhaps just "clear": "dblclick" is sufficient. This would mirror the syntax for the other transforms ("toggle", "translate", "zoom", etc.).

Yep, that totally makes sense, esp. that `"toggle"` already exists.  (I didn't realize that at first.) 

> a good first feature for @allenjlee to take a shot at

I agree this would be a good first feature to tackle as it's not too complicated. 

That said, I'd like to note that I'd need this soon (likely in a week or two). 
@allenjlee -- would you have time to work on this week?  If so, I think it'd be a fun issue to tackle.  

Note that since I will need it soon, I might take it over next weekend or so (if we don't have it yet).  For now, I'll work on other stuff first so you get to work on this. :) 


In a follow-up PR, it might be worth defining a rules for default "clear" too.
(For example, a natural "clear" for `"on": "mouseover"` would be `"mouseout"`.  `"dblclick"` might be a reasonable default for `"on": "click"` (though I'm not as confident about the latter.)  To make PR small and easier to get done, I think the first PR should just focus on "clear" support without defaults (and do the defaults as a follow-up PR).

**Comment by allenjlee** [comment]
Yes, @kanitw I will have time to work on it this week. Will try to take a look at it a bit today and after Wednesday. Will keep you updated if I'm not able to complete it by this Saturday.

**Comment by yaakovfeldman** [comment]
Thank you for this! However, it's still not clear from this issue or the docs how to clear a selection using the javascript API. I have a 'reset filters' button in my dashboard that calls something like `chartHandle.view.signal("my_selection_x", [0, 0])` for each chart, which seems to work most but not all the time. This was based on looking in the editor what signals occur when a selection is cleared.

This issue implies there is a specialised `clear` signal that should be used - is this correct?
