### ISSUE TITLE
Support adding title to a plot 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#431]
- [ ] ~~Need to add another text mark group to the top-level marks~~
- [ ] ~~The first step is to always add title to the bottom.~~  
- [ ] ~~Then we might add mode for adding title to the top (and thus offset the main mark group)~~

**Comment by jowens** [comment]
I'd also like this capability.

**Comment by kanitw** [comment]
We're punting on this to see if we should support this by composition instead.

**Comment by kanitw** [comment]
Note: @pteehan asks for this in https://github.com/altair-viz/altair/issues/258.

**Comment by kanitw** [comment]
Now that Vega has `title` directive for group mark, we can easily add this.

**Comment by kanitw** [comment]
We can add `title` to `BaseSpec` with properties similar to https://vega.github.io/vega/docs/title/. 

(Maybe except `encode` for now.)

**Comment by kanitw** [comment]
Fixed in #2779
