### ISSUE TITLE
Need to add test to prevent importing actual method from Vega

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4322]
Otherwise our users can no longer use `vega-lib`.

This is actually a non-trivial problem since vscode will add autocomplete from Vega, so we better add some warnings. 

See https://github.com/vega/vega-lite/pull/4321, for example.

**Comment by domoritz** [comment]
How do we prevent this?

**Comment by kanitw** [comment]
One dumb way I can think of is to check that none of the output JS files contain imports from vega.  (Since we should only import Types from vega, not actual methods.)

**Comment by domoritz** [comment]
👍

**Comment by kanitw** [comment]
@domoritz  Same for `util`?

**Comment by domoritz** [comment]
Vega lib is not a thing anymore so at least importing from Vega is not an issue.

**Comment by kanitw** [comment]
@domoritz fixed this in https://github.com/vega/vega-lite/pull/4692. 

Hooray!
