### ISSUE TITLE
package.json `module` requires undeclared vega

### ISSUE THREAD

**Issue by colehaus** [vega/vega-lite#4339]
I think this issue is somewhat similar to #881.

If you clone https://github.com/colehaus/ve-test and run `run.sh`, you should see that `webpack` builds using `vega-lite` fail. The error I get is:

```
[...]

ERROR in ./node_modules/vega-lite/build/src/compile/data/expressions.js
Module not found: Error: Can't resolve 'vega-expression' in '/home/pseudonom/code/ve-test/node_modules/vega-lite/build/src/compile/data'
 @ ./node_modules/vega-lite/build/src/compile/data/expressions.js 1:0-40 23:14-19
 @ ./node_modules/vega-lite/build/src/compile/data/calculate.js
 @ ./node_modules/vega-lite/build/src/compile/data/assemble.js
 @ ./node_modules/vega-lite/build/src/compile/compile.js
 @ ./node_modules/vega-lite/build/src/index.js
 @ ./index.js
```
Looking at the error and the referenced files, I see that there's a chain of imports starting from `./node_modules/vega-lite/build/src/index.js` which eventually looks for `vega-expression`. Because `vega-lite` only declares `vega` as a `devDependency` instead of a `dependency`, `webpack` (understandably) fails to find `vega-expression`. I believe `webpack` starts at `./node_modules/vega-lite/build/src/index.js` because that's the file declared in the `module` field of `vega-lite`'s `package.json`.

As far as I understand it, there are two approaches to resolve the issue:

1. Declare `vega` as a dependency of `vega-lite` (probably not a good solution)
2. Change the `module` field to point to the same file as `main`

There may well be other better solutions.

**Comment by domoritz** [comment]
Ahh, we should make Vega expression a dependency now that we parse expressions. Good catch and thanks for filing the issue.

**Comment by colehaus** [comment]
I think there may be other similar issues elsewhere in the ecosystem. When I try to import `vega-embed` in a file that gets `webpack`ed, I get a complaint about not being to find `vega`:

```
ERROR in ./node_modules/vega-embed/node_modules/vega-lite/build/src/compile/data/aggregate.js
Module not found: Error: Can't resolve 'vega' in '/home/pseudonom/code/ve-test/node_modules/vega-embed/node_modules/vega-lite/build/src/compile/data'
 @ ./node_modules/vega-embed/node_modules/vega-lite/build/src/compile/data/aggregate.js 2:0-30 162:20-26
 @ ./node_modules/vega-embed/node_modules/vega-lite/build/src/compile/data/optimizers.js
 @ ./node_modules/vega-embed/node_modules/vega-lite/build/src/compile/data/optimize.js
 @ ./node_modules/vega-embed/node_modules/vega-lite/build/src/compile/compile.js
 @ ./node_modules/vega-embed/node_modules/vega-lite/build/src/index.js
 @ ./node_modules/vega-embed/build/src/embed.js
 @ ./index.js
```

**Comment by domoritz** [comment]
Does the pr fix it for you?

**Comment by colehaus** [comment]
This did fix the issue with `vega-lite`. The issue that I highlighted in my second comment with `vega-embed` is still there. I've updated https://github.com/colehaus/ve-test to make that one fully explicit. Should I go ahead and file the issue on `vega-embed`?

**Comment by domoritz** [comment]
This has not been published but I believe this has been fixed. Can you show me the offending js line?

**Comment by colehaus** [comment]
Ah, looks like you're right. `vega-embed` was pulling in the released (i.e. unfixed) version of `vega-lite` and it wasn't obvious to me that this fix fixed that problem too since the error trace was a little different. Copying the latest version of `vega-lite` into `vega-embed`'s `node_modules` confirms that this fix seems to fix `vega-embed` too.

Thanks!

**Comment by domoritz** [comment]
Excellent.
