### ISSUE TITLE
Support pre-aggregated box plot

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4343]
(or at least create an example that shows an equivalent data)

**Comment by robert-moore** [comment]
Are there any examples out there of this? I have a pre-calculated min, q1, med, q3, max + outliers and I'm not sure how to create a box plot in vega or vega lite with this

**Comment by kanitw** [comment]
I'm adding an example in https://github.com/vega/vega-lite/pull/6654.  Please take a look. :)
