### ISSUE TITLE
Revise default rangeStep?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4348]
In the old days, we used point scale for bars and somehow found that 21 (odd number) make the bar looks nicer. 

However, now that we use band scale for bars (a more sensible default). Right now we still use rangeStep = 21, but need to use the fractional padding. Thus, currently the bars boundary do not fall on exact pixel.  

We could revise the rangeStep to be 20, so that applying paddingInner = 0.1 makes the bar boundaries fall on the exact pixel.

On a related note:

1) If we want to use stroke to highlight selection like in the [interactive_bar_select_highlight](https://vega.github.io/editor/#/examples/vega-lite/interactive_bar_select_highlight).  
Changing the `barBandPaddingInner` to 0.15 or 0.2 gives more breathing room for the strokes by default. 

2) (minor) we may want to change the default barBandWidth for point scale to match the band scales to make it consistent for layering.  

Any thoughts?

**Comment by domoritz** [comment]
20 makes sense to me. I don't think we want to increase the badding by default, though. The stroke hover is a special case, no?

**Comment by kanitw** [comment]
>  I don't think we want to increase the badding by default, though. The stroke hover is a special case, no?

It depends. The current 0.1 was in fact arbitrarily chosen, so I don't see why we can't increase it.  (we could also start a PR and look at the changes if it's really worse.) 

> The stroke hover is a special case, no? 

It might no longer be the special case in the future if my experiments with highlighting / selection presets go well.

**Comment by domoritz** [comment]
> It might no longer be the special case in the future if my experiments with highlighting / selection presets go well.

We can always wait for that and update it in 3.1 (it's not a breaking change).

**Comment by kanitw** [comment]
Will be resolved in https://github.com/vega/vega-lite/pull/4351
