### ISSUE TITLE
Upcoming init feature also for interval selections?

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4358]
I thought it will be included in the VL 3.0 release, but not completely sure, therefor the following question:

Will it be possible to use the `init` parameter to initiate predefined interval selections?

I was for example hoping to preselect a certain area in my chart on rendering for highlighting purposes

Example, here the detail panel is initiated with an area between half 2003 - half 2005 as it is 'preselected' in the overview panel:
![init_interval_selection](https://user-images.githubusercontent.com/5186265/49811648-fba0a900-fd63-11e8-9bbe-98289bb880aa.PNG)

**Comment by kanitw** [comment]
Yes, the init does work with interval selection. :)
