### ISSUE TITLE
tickOffset doesn't apply to gridlines

### ISSUE THREAD

**Issue by Corvince** [vega/vega-lite#4363]
The documentation for the axis property "tickOffset" states
> Position offset in pixels to apply to ticks, labels, and gridlines.

However, the gridlines seems to be unaffected by the tickOffset.

Here is the spec for the [example scatterplot with tickOffset](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxgSFZdMWwtCtIC33lFFQBfdQhIDF0AawbIAI88Ep7kJXhuTQ9qBtAIHoAPBcgUxmQxTSGACXS-ANdbNSg8AE9YoYBHVhCjPGtGKkgujR7zhfel9c3toYAspEdAB9WK6EEAcXQCWU4yWPQuV1Mt3uzCeL26CKg6GWjFgayM8H6AHkUik-GMcAAmAAMHW+DIgDI6QA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "axis": {"tickOffset": 20}
    }
  }
}
```

![tickOffset](https://user-images.githubusercontent.com/13568919/49863356-68698100-fe00-11e8-939d-a162d075a5d0.png)

Side question: Since offset works only in pixels, how would I offset them exactly x (e.g. 0.5) data units?

**Comment by domoritz** [comment]
Thank you for the report. I wonder whether we should disallow tick offset in Vega-Lite. What is the use case?

**Comment by Corvince** [comment]
I want to create a new visualization front-end for the [Mesa - Agent-based modeling package](https://github.com/projectmesa/mesa). One of the core elements is a grid view (see the Mesa front-page), where the position of the agents are integer x,y values. [For this prototype](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdlwFiZUk1h4GzNu1axkJ+MrzIlDz6lIAYW4TCkYleCl4AAYATgA2ACYAMwBGTWRNVIB2TXj47IBWBOR4dnZ4wvjUxIAOaIAWdFITdAB3UlTkZETC1PZYquR0ZEKRzWzkZMLo7PZkWoac+HR0bOlRiYb4UkJ3RSVYOnhYCjUNI2SQjDwLYEhCdBM3O8gADwtIJVZUeZM1KAAT0+31+7gBkAAyt5CCCfn9IABfREaRHqIx4VqHK4mVAWADaFzA9xWYngrDEOmQn20eB+dDeYAA1GBonRChD0LBPh80USSegyRSqTSdPTAczWezOdycJBgSiIABddFQCieCI6An8olGNxiUp4HgqfS6wyQRDcKj-U2GO3mvCAvafWDhagG872+2QZKMZBiTSysD4yAAQWoPjwAEkACKQFVmu2QZSfVDcVzIK3g1VeoxoQiOz6C8yJsB83NQezIWG2itQR3OuWupTu6k53M+v0BoMh6HV+Ptr2QdjhTSvcKEVi3OVYiMQ1DhCzRVRQDAfHCJZeVmEWVKK3P7u3l70YEwAa0+8EYHg9g6gPk8mjdd1L7xfdagvv9Y7lHzvSYbak5QAR1YdBfGYHRGCoT060gBBBSA4lIE0bgMEXHB8S3TclWPCtIHQN5GCDe4jXgM8+xrMA91LPDvWBWt8K-ANPmBf8HSdJDIFA8CjV0I0YPYvVSSQ+5UPQk1g2w6JcKEqBCOI14yIonccBois6KTTwxBCd84OYn8oHDSNY1g-DAM+HiIP46C21LIwNSfI0U30eD-UNY1Pkta0IQoQVWC47Rz3YMQAqRWj2MgPBuG4MQjSowkP3uAzPmM3xTJXKLOMssDrKgmDNPtZKu0MyAAHVhjixAIQskDcr4-LqUPe0lTNQqoqxWAcTxTDiri8E5VpelKLAABeUawCrQgAH1KKRVqj3bAxvUpQEBuDUtlvMzruoJPrvBtLQxVQOgRoAHgmqbZp3REEw-SBTwvOUJCUOz7ofbgnxbPT7vXZCUrlObMtqqArIagSmrkowGP+krPgqwUWBq7K6t4yCIaRKGoG03TGI-T84blNLozjLGMRR0H6vR2yzPxyBHOYTzXP1DyXNwLN-kyvzQq4kJwLnZqNKx5NHivQs8fu7mwpwNlEjJ7HlCcpnkJZ+BnMki0Od8-ykOiQWD3sssIs2w2OvArrrj2zt+sOlDjtOmEwAuyaYWu-tbrkh6nieqAXreuCPq+6gfrgv7iu-T4gfrCnuKpmyCuFmHw5YuUEaq5HG0ptH48hw2HNi3HiTz80AaMiN0tJ4vycz2Ps8a2n7oQj1maQNAuOoExukOTGq4VpQlbZ+5VfVryta5nXRWCnnwvxsthe4UXmCT3vIClpDUnl+nFcZwe3INNXlfuJRuGndmfLRNUJ5l-WvRvww78KiAto7TFzd23rrYO0U6RO87LtduaHtTaPU+H7Bu3pA7Pglh2MOnYI6Ax3MDGOYNqYJ2LvKEO91S7lUqkjTeINa55QxpvdA1AO7CG8EWa0pDqTF0ft6HGh17hr0+HzFsTVDYPzNAte+GhWqIiAA) I shifted the actual coordinates by 0.5, because I wasn't able to move the gridlines.

**Comment by Corvince** [comment]
Ok so [here is an example ](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkAB5WAjKqgBPK9IC+Hg3tDZysAJg9IbxxXO0NfWIBdDX8NSAwAJwBrK0h4RnT4MWQ1VOQleG5NRiVqbECjF31YowAzRmQxTRyXdSCoPE9CYpxIbnSqpVMSvsgEU2GHSE1uDGqra3cwcLBpBIilRngFltNYZAiBoZz2dCUulJn0J0ZLfUgbu4AFblhmHhUcAAGCLUdKMLo4PDpczxewPYJRBzNKBtDoQrzTIKQS4LSAAR1YtzwzB0jComPss3g8ysjmWqwBNkBdAArB5ZCy9lADkcrCcxGd4ZSni9adjDpkAMp4ZCENywuJgZIgXxAA)with two possible bugs, one for each axis:

![visualization](https://user-images.githubusercontent.com/13568919/50000986-ad75ea80-ff9b-11e8-8994-b67a97eaecf4.png)

The x-axis is pretty much what I want, except for the grid lines, which are not aligned with the ticks. Not sure if this is a bug or expected behavior, but I would expect the grid lines where the ticks are.

On the y-axis I the relative alignment of the grid and points is correct, but the ticklabels are simply wrong. The ticks are actually at .5 values and the points at whole point values

**Comment by kanitw** [comment]
The fix is probably simply changing `tickOffset`'s axis property type https://github.com/vega/vega-lite/blob/master/src/axis.ts#L161 to `'both'`.

Feel free to submit a PR.  (Or wait a bit and we will fix this when we get time.)

**Comment by kanitw** [comment]
> The x-axis is pretty much what I want, except for the grid lines, which are not aligned with the ticks. Not sure if this is a bug or expected behavior, but I would expect the grid lines where the ticks are.

This is a bug. Will fix. 


> On the y-axis I the relative alignment of the grid and points is correct, but the ticklabels are simply wrong. The ticks are actually at .5 values and the points at whole point values

This is not the intended use of tickOffset. To change the actual tick values, use `values`.  We'll add notes that this property would not change the actual tick values.

**Comment by Corvince** [comment]
> This is not the intended use of tickOffset. To change the actual tick values, use values. We'll add notes that this property would not change the actual tick values.

But I did not use tickOffset for this! I could probably have included the spec inline earlier, but the y-encoding is just: 
```json
    "y": {
      "field": "y",
      "type": "quantitative",
      "scale": {"domain": [0.5, 3.5], "nice": false},
      "axis": {"tickStep": 1}
    } 
```
(and y values are 1 and 3)
It must be due to a combination of the off-value domain and the tickStep. I am pretty sure this is a bug.

Thanks for looking into this!
