### ISSUE TITLE
A predicate to check whether a selection is empty or not

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4371]
Our selection can include `empty: "all" | "none"`.  However, sometimes, we want to apply each of the modes to a different part of the same visualization.  

For example, in https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html:

- We want the `fillOpacity` to activate the selection predicate both when there are selected data for the `select` selection and when there is none.  
- However, we want the strokeWidth to appear only when there are selected data for the `select` selection, but **not** when there is none.   Currently, I had to add a hack where I have to combine an expression with the selection predicate: 

```
           test": {
            "and": [
              {"selection": "select"},
              "length(data(\"select_store\"))"
            ]
          }
```

Note that the expression ` "length(data(\"select_store\"))"` is a hack as I know the underlying data store name in Vega.

It would be more natural to provide a syntax for this as a part of a [selection predicate](https://vega.github.io/vega-lite/docs/filter.html#selection-predicate) (and a [condition definition](
https://vega.github.io/vega-lite/docs/condition.html)).

The tricky part is that the new syntax that we can add here may be overriding the "empty" defined.

Some alternatives (given a selection named `select`):

### a) Add `{empty: "sel_name"}` to the selection logical chain

```json
{
  "condition": {"selection": {"or": ["select", {"empty": "select"}], "value": ...}
}
```

```json
{
  "condition": {"selection": {"and": ["select", {"not": {"empty": "select"}}], "value": ...}
}
```

### b) Add `{empty:  "sel_name"}` to the predicate chain

```json
{
  "condition": {"test": {"or": [{"selection": "select"}, {"empty": "select"}], "value": ...}
}
```

```json
{
  "condition": {"test": {"and": [{"selection": "select"}, {"not": {"empty": "select"}}], "value": ...}
}
```

### c) Add boolean empty to both the selection predicate and condition predicate

```js
{
  "condition": {
    // Don't trigger predicate if empty (equivalent to "and not empty") 
    "selection": "select", "empty": false,  
    "value": ...
  } 
}
```

```js
{
  "condition": {
    //Trigger predicate if empty (equivalent to "or empty")
    "selection": "select", "empty": true,  
    "value": ...
  } 
}
```

For this c) design  we can also add `"empty"` to the [selection predicate](https://vega.github.io/vega-lite/docs/filter.html#selection-predicate) too: ` {"selection": "select", "empty": false}`

-----

After writing these alternatives, I think c) is probably the most user-friendly. 

@arvind @domoritz

**Comment by domoritz** [comment]
C definitely makes sense to me. Why do we even need an empty property on the selection itself? I feel how we handle empty is something that should be in the condition or the filter, not the definition of the selection.

**Comment by kanitw** [comment]
I think if we have to pick one having only on the predicate make more sense.

However i can see that if we apply the predicate multiple times like in multi-view plots having it in the selection is good for setting the default empty for a certain selection.

**Comment by kanitw** [comment]
Plus, we already have these on selection — better avoid breaking changes.

**Comment by kanitw** [comment]
Reading this again, I still like option c). 

> Plus, we already have these on selection — better avoid breaking changes.

Given we may introduce this in VL 5.0, which will already introduce a number of changes. It might make sense to just move this "empty" bit to predicate.
