### ISSUE TITLE
Separate Unit Schema (at least for Composite Mark)

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4372]
Currently we have one unified UnitSpec (Single View) schema.

This means that the schema will validate all encoding channels for all mark types. 

However, as we're moving toward more encoding channels that are specific to composite marks. 

We should at least separate composite mark's unit spec from normal unit spec.  So that channels like `xError` won't get suggested by autocompletion and validated by the schema for marks other than `errorbar`.   

We might even want to split these for all mark types.  However, given the performance of the current schema generator, I'm a bit worried that it will be too slow if we do that right now (before we dive into improving the schema generator).  

cc: @jakevdp  This probably help generate better class for composite marks in python too. 
I wonder if you have any preference about this?  (I think we definitely should do it for composite marks, but not sure if we should do it for normal marks yet.)

**Comment by domoritz** [comment]
In the Vega typings, we have encodings for each mark type. It definitely helps with correctness.

**Comment by kanitw** [comment]
Oh sure. As said, the only worried i have is that our schema gen, which we need to run for testing, gonna take forever:)

**Comment by kanitw** [comment]
Done in latest master.

**Comment by kanitw** [comment]
Will be done in #4440 **
