### ISSUE TITLE
Infinitely long output in the Travis script

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4406]
I don't know why there are so many lines of RVM nonsense in the Travis log after the `lint` command.  

(Our real log is like ~ 2k lines, but there are >8k lines of gibberish output!)

**Comment by kanitw** [comment]
It's quite annoying as we can't go to the end of the page to see end of the log.

**Comment by kanitw** [comment]
Hmm, this sometimes doesn't happen. Let's not worry about it for now then.

**Comment by kanitw** [comment]
Saw it again

@domoritz Is this related to the command "set -ev"?  (What is it for?) 

It'd be great for us to add more comment to the build scripts.  So many encrypted bash commands at this point ...

**Comment by domoritz** [comment]
I sent a PR that seems to fix it. 

Also, here is an explanation: https://explainshell.com/explain?cmd=set+-ex
