### ISSUE TITLE
Version 2.6.0 has duplicate package.json file included 

### ISSUE THREAD

**Issue by saulshanabrook** [vega/vega-lite#4415]
The latest version of Vega Lite 2 (2.6.0) has duplicate incompatible package.json files.

To see this download the package and look at `./build/src.package.json` and `./build/package.json`:

```bash
$ npm pack vega-lite@2.6.0
# unzip package
$ cat package/build/src/package.json  | grep version
  "version": "2.5.1",
    "build:versions": "scripts/update-version.sh",
    "presite": "npm run prebuild && npm run data && npm run build:site && npm run build:toc && npm run build:versions && scripts/create-example-pages",
$ cat package/build/package.json  | grep version
    "version": "2.6.0",
        "build:versions": "scripts/update-version.sh",
        "presite": "npm run prebuild && npm run data && npm run build:site && npm run build:toc && npm run build:versions && scripts/create-example-pages",
```

It looks like the `./build/src/package.json` is unintentionally there and refers to an  old version. 

When it is processed by webpack in JupyterLab, it warns us that two versions are found because of these: https://github.com/jupyterlab/jupyterlab/issues/5420

**Comment by kanitw** [comment]
This should no longer be an issue. :)
