### ISSUE TITLE
Tooltip for Range 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4423]
Tooltip for ranged mark / binned field would benefit a lot from an ability to combine multiple fields in one slot. 

We could consider extending `TooltipFieldDef` to have `field2` and `delimiter` properties.

For instance, for a prebinned field we could say:

```
tooltip: {
  field: "binned_x_start",
  field2: "binned_x_end",
  type: "quantitative",
  title: "X (binned)",
  "delimiter": " - " // This should be the default value
}
```

Or more generally, we could consider supporting expression via [`signal`](#3338). 

cc: @domoritz @chanwutk

**Comment by domoritz** [comment]
I think for advanced use cases, signals would be good.

**Comment by kanitw** [comment]
Thinking more the problem with the `field2` approach is that it's a bit inconsistent with how `x2` and `y2` work. Basically, `x` and `y` do not have `field2` as we have `x2` and `y2`.  

We originally makes this decision as we may want to apply different aggregate / timeUnit to `x2` and `y2` and having `timeUnit2` and `aggregate2` seem a bit too confusing (though requiring `type` in both `x`/`x2` and `x2`/`y2` is a bit unnecessary and potentially confusing as `x2`/`y2` must have the same type as `x` and `y`. 

Due to this consistency, I agree with @domoritz that `signal` is perhaps a better choice.  That said, I don't think we can simply add `signal` to `tooltip` without deciding if we will support `signal` throughout the language at all (#3338).

**Comment by kanitw** [comment]
FWIW, tooltip for prebinned field would work correctly as of #5129 

![image](https://user-images.githubusercontent.com/111269/60379358-a0c05d80-99e6-11e9-8cd2-8348acfaea57.png)

I think we probably can avoid the unnecessary complexity here. (We can reopen this again if we found a better motivating example.)
