### ISSUE TITLE
JSON Schema definition names contain invalid characters

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4448]
As of v3.0.0-rc11, the `vega-lite-schema.json` schema contains definitions like:

```json
    "FieldDefWithCondition<MarkPropFieldDef<(\"nominal\"|\"ordinal\"|\"geojson\")>,string>": {
      "additionalProperties": false,
      "description": "A FieldDef with Condition<ValueDef>\n{\n   condition: {value: ...},\n   field: ...,\n   ...\n}",
```

While these sorts of names may or may not be legal in the JSON Schema spec, they make generating code from the schema require a lot of sanitization. Previous versions of the spec seem to have had the definition names pre-sanitized (perhaps from #2391); it would be nice if that could be restored.

**Comment by kanitw** [comment]
Sure. Will be fixed in https://github.com/vega/vega-lite/pull/4452
