### ISSUE TITLE
Documentation examples broken

### ISSUE THREAD

**Issue by metasoarous** [vega/vega-lite#4451]
Documentation viz examples aren't rendering for some reason. For example, here

https://vega.github.io/vega-lite/docs/scale.html#continuous

I see this:

![image](https://user-images.githubusercontent.com/88556/51066449-0b0f4e00-15bf-11e9-8433-eda1986d4dcd.png)

I observed this in both Chromium and Firefox.

Wondering if there's any relation to #3535.

Thanks

**Comment by domoritz** [comment]
We're working on fixing this.

**Comment by domoritz** [comment]
I'm super confused. We're getting an empty SVG element but the calls to embed the chart seem completely okay. 

<img width="725" alt="screen shot 2019-01-20 at 17 51 27" src="https://user-images.githubusercontent.com/589034/51448530-0c85f800-1cdc-11e9-92e8-8616eb1e4562.png">


```js
  const vgSpec = compile(spec).spec;

  const view = new vega.View(vega.parse(vgSpec))
    .renderer('svg')
    .initialize($target)
    .run();
```

I can even run `vgSpec` in the editor without problems.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4479
