### ISSUE TITLE
Syntax for Wrapped/Flow Layout Support for Repeat / Facet / Concat

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4457]
We previously discussed this in #393, but that discussion has been too long to follow (and sidetracked by comments about a slightly different discussion). 

So I'd like to start a new issue to summarize proposed solutions.

We have considered two possible syntaxes for supporting wrappable facet/repeat concat so far 

## A) Using unnested `facet` / `repeat` / `concat` as the "general" `facet` / `repeat` / `concat` syntax that supports wrapping

Basically, a general 1D facet spec could look like this:

```js
{
  // if facet is fieldDef right away, then it's a wrapped facet
  "facet": {"field": "Origin", "type": "nominal"},
  "columns": 4,  // The maximum number of columns on a row
  "spec": ...
}
```

then we can have the following syntax as our shorthand (just like `row` / `column` encoding channel). 

```js
{
  ...
  "encoding": {
    "facet": {"field": "Origin", "type": "nominal", "columns": 4}
  }
}
```

Note that we discussed the possibility of a `{facet: {wrap: ...}, ...}` syntax earlier. In that case, the macro's channel name could be `"wrap"`. However, @jakevdp suggests that it [could be confusing](https://github.com/vega/vega-lite/issues/393#issuecomment-390380096), especially in Altair.  I agree with him. 

We can do the same unnested `repeat`:

```js
{
  // if repeat is an array of repeatet value rigth away, it's a wrapped repeat
  "repeat": [..., ..., ...],
  "columns": 4, 
  "spec": ...
}
```

This could work well in a consistent fashion with a wrapped `concat`.

```js
{
  concat: [spec1, spec2, spec3, spec4],
  columns: 2
}
```

Note that I thought about the name for wrapped concat for a while, but `wrappedConcat`, `flow`, `grid` all sound worse than simply a generic `concat`, which can serve as a generic concat (vconcat when `columns=1` and `hconcat` when `columns` = `undefined` / Infinity or wrapped concat for other numbers of `columns`). 

By using the term `concat`, we can preserve `grid` for a possible macro/shorthand like this:

```js
{
  grid: [
    [spec1, spec2], 
    [spec3, spec4]
  ]
}
```

(This `grid` thing has a lower priority though).

### Pro

- The syntax is quite concise.  It does not require an additional level of nesting when we only facet / repeat by one field (rather than two).  Faceting by one field is gonna be much more common use case, so opting for concision for this use case is favorable.  

- We can achieve a consistent syntax for generic facet/repeat/concat (which can wrap / or not depending on the number of `columns`).

### Cons

- The transition (spec edits) from faceting by one field to two fields is a bit more involved as users need to add one additional level of nesting.  Same for repeating.  (That said, I think this is less important than having a simple syntax for faceting by one field, which would cover the majority of the use case.)

## B) Extend existing row/column/hconcat/vconcat syntax to support `columns` (or `rows`)

The other alternative is to extend existing row/column syntax:

```js
{
  data: ...
  facet: {
    column: {field: 'category', type: 'nominal'}
  },
  columns: 5, // there will be 5 columns per row
  spec: ...
}
```

```js
{
  data: ...
  facet: {
    row: {field: 'category', type: 'nominal'}
  },
  rows: 5, // there will be 5 rows per column
  spec: ...
}
```

If both facet.row and facet.column are specified, columns or rows will be ignored and there will no wrapping.

One _minor_ note is that the latter (`rows`) requires some extension to Vega. (We could try to do the similar math in Vega-Lite, but I don't think we could as doing the same in Vega will benefit both abstraction level.) 

We could do the same for repeat:

```js
{
  repeat: {
    column: [..., ..., ...]
  },
  columns: 5, // there will be 5 columns per row
  spec: ...
}
```

and concat:

```js
{
  hconcat: [..., ..., ...],
  columns: 5 // there will be 5 columns per row
}
```

## Pros

- This syntax is nice in the sense that we preserve the existing syntax and only need to extend the facet spec with rows/columns.

## Cons

- It's semantically _misleading_.  A wrapped facet does not encode data by either row or column but rather _both_.  `hconcat` with a number of columns is also misleading as it's no longer purely "horizontal".  I think this is a critical con for this design. 

- It leads to a complex schema when both `facet.row` and `facet.column` are specified, columns or rows will be ignored and there will no wrapping.

- (Minor point) Supporting `rows` requires some works. This solution requires that we support `rows` right away to make it not weird. (The first solution is fine with just `columns` for now.) 
 
----

As I summarize these pros and cons for these two approaches, I think a) is a stronger solution. 

cc: @domoritz @arvind @jheer @jakevdp  -- Please comment if you have any thoughts.

**Comment by domoritz** [comment]
I like a) a lot. It seems much more intuitive than b). I still struggle to understand when to use column or row and a) makes it less important.

Another future extension of either syntax could be to support faceting by multiple fields at once (multiple group by's). Not saying that we should do this soon but we are not preventing this extension. 


```
{
  "facet": [
    {"field": "Origin", "type": "nominal"},
    {"field": "Cylinders", "type": "ordinal"},
  ]
  "columns": 4,  // The maximum number of columns on a row
  "spec": ...
}
```

**Comment by kanitw** [comment]
One thing that I don't like about a) is that the repeater syntax will use "repeat" as both key and value:

```js
x: {field: {repeat: "repeat"}, ...}
```

because now repeat is a repeat channel name just like row/column

```js
x: {field: {repeat: "row/column"}, ...}
```

That said, I guess this is probably fine.

**Comment by kanitw** [comment]
@jheer @arvind @domoritz  Given that we will do a), I have a follow up question:

For the shorthand, should the composition layout properties be in fieldDef or in the outer spec?

### a-1) in fieldDef

```
{
  ...
  "encoding": {
    "facet": {"field": "Origin", "type": "nominal", "columns": 4, "spacing": 20}
  }
}
```

```js
{
  ...
  "encoding": {
    "row/column": {"field": "Origin", "type": "nominal", "spacing": 20} // this would be only either row/column spacing
  }
}
```

### a-2) outside

```
{
  ...
  "columns": 4,
  "spacing": 20,
  "encoding": {
    "facet": {"field": "Origin", "type": "nominal"}
  }
}
```

```js
{
  ...
  "spacing": 20,
  "encoding": {
    "row/column": {"field": "Origin", "type": "nominal"}
  }
}
```


I slightly prefer a-1), but would like to hear what you think

**Comment by domoritz** [comment]
a-2 seems cleaner to me as well since you need to add objects in the general facet case anyway and the nesting gets pretty deep.

**Comment by kanitw** [comment]
Cool thanks -- This issue will be finished in #4541

**Comment by domoritz** [comment]
Just noting here that after a discussing with @davidanthoff we noted that these two are equivalent and so this can help resolve https://github.com/vega/vega-lite/issues/393#issuecomment-391169108.

```json
{
  "name": "trellis_barley",
  "data": {"url": "data/barley.json"},
  "columns": 2,
  "facet": {
    "field": "site",
    "type": "ordinal",
    "sort": {"op": "median", "field": "yield"}
  },
  "spec" : {
    "mark": "point",
    "encoding": {
      "x": {
        "aggregate": "median",
        "field": "yield",
        "type": "quantitative",
        "scale": {"zero": false}
      },
      "y": {
        "field": "variety",
        "type": "ordinal",
        "sort": {"encoding": "x", "order": "descending"},
        "scale": {"rangeStep": 12}
      },
      "color": {"field": "year", "type": "nominal"}
    }
  }
}
```

```json
{
  "name": "trellis_barley",
  "data": {"url": "data/barley.json"},
  "mark": "point",
  "columns": 2,
  "encoding": {
    "facet": {
      "field": "site",
      "type": "ordinal",
      "sort": {"op": "median", "field": "yield"}
    },
    "x": {
      "aggregate": "median",
      "field": "yield",
      "type": "quantitative",
      "scale": {"zero": false}
    },
    "y": {
      "field": "variety",
      "type": "ordinal",
      "sort": {"encoding": "x", "order": "descending"},
      "scale": {"rangeStep": 12}
    },
    "color": {"field": "year", "type": "nominal"}
  }
}
```

**Comment by jheer** [comment]
Somehow I am only getting to this issue now. I apologize I missed it earlier!

The design arguments above strike me as rather system-developer-centric. It is my strong suspicion that users would find the localized a-1 examples easier to understand (I certainly do). In any case, I naturally assumed that facet wrap would place the parameters within the facet definition itself, not outside it. The outside placement confused me as it seems to unnecessarily disconnect logically connected things. (Or, does it make sense to define any of those properties outside specific composition operators?)

From the standpoint of user-centric API design I would argue for including support for a-1.

**Comment by jheer** [comment]
Unfortunately, the use of `facet` at both the spec-level and the encoding-level causes a potential namespace collision for external APIs that use Vega-Lite. For example, `vl.facet(...)` could mean either an encoding-level facet channel or a spec-level facet composition operator. Obviously it's too late to change this for v3, but this design choice has already led to errors/incompatibilities over in [vega-lite-api](https://github.com/vega/vega-lite-api). As a result, I will have to redesign parts of the API.

**Comment by kanitw** [comment]
> It is my strong suspicion that users would find the localized a-1 examples easier to understand (I certainly do). In any case, I naturally assumed that facet wrap would place the parameters within the facet definition itself, not outside it.

It's not too late to add support for a-1 and deprecate a-2 (with backward compatibility support).  


The `facet` channel name for the macro is definitely harder to change.
