### ISSUE TITLE
I'm having issues in visualizing elastic search data on vega bar graph, as i'm not able to read the array in a  json object.

### ISSUE THREAD

**Issue by Purushotham95** [vega/vega-lite#4458]
![image](https://user-images.githubusercontent.com/43606081/51240206-3f10b780-19a1-11e9-9ada-eb592024033d.png)

{
  "hits": {
    "hits": [
      {
        "_source": {
          "@timestamp": "2019-01-14T11:45:32.193Z",
          "factor": [
            {
              "index": 0.02,
              "Spraying_machine_N_2_gas_flow_rate_S#1": 59.76,
                          },
            {
              "index": 0.04,
              "Spraying_machine_N_2_gas_flow_rate_S#1": 59.76,
              },
            {
              "index": 0.06,
              "Spraying_machine_N_2_gas_flow_rate_S#1": 104.53,
              }
          ],
          
          "SerialNumber": "101"
        }
      }
    ]
  }
}

I am using vega lite v2 in kibana 6.3.2. In the above JSON data I am not able to fetch the fields from the array i, e i want to fetch index data from factor array. I tried flatten function but still no output is displaying. But got output by using object.
I have multiple objects in for one serial number so using array is the only way out. Please help me out in figuring out the issue

**Comment by domoritz** [comment]
We don't provide support for elastic. @nyuriks
