### ISSUE TITLE
Type Error due to `clone` dependencies

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4461]
```
/Users/kanitw/Documents/code/tune-vis/node_modules/vega-lite/build/src/util.d.ts
(1,8): Module '"/Users/kanitw/Documents/code/tune-vis/node_modules/@types/clone/index"' has no default export.
```

**Comment by domoritz** [comment]
What's your tsconfig?

**Comment by kanitw** [comment]
I think you add automatically converting non-default export to default export in Vega-Lite.  

I could do the same for now, but I don't think it makes sense for us to expect that all users of Vega-Lite has to adjust the config to be like us.

**Comment by domoritz** [comment]
Yeah, you might need to add

```
"allowSyntheticDefaultImports": true
```

I don't know whether we can change it easily but I'm not opposed to changing things.

**Comment by kanitw** [comment]
If we want to remove `"allowSyntheticDefaultImports": true` from Vega-Lite, we have to make the following change: 

```diff
-import clone_ from 'clone';
+import clone_ = require('clone');
```

However, we will get the following error:

```
{
	"resource": "/Users/kanitw/Documents/code/vega-lite/src/util.ts",
	"owner": "typescript",
	"code": "1202",
	"severity": 8,
	"message": "Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from \"mod\"', 'import {a} from \"mod\"', 'import d from \"mod\"', or another module format instead.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 34
}
```

So nope, we can't change it easily ><"

**Comment by domoritz** [comment]
I think the problem is the way `clone` is written. Is it a big deal to require `"allowSyntheticDefaultImports": true`?

**Comment by kanitw** [comment]
I guess it's probably okay, but it's not nice.  It's better if we don't enforce build configuration on dependent projects because it's contagious.  
Say library A depends on VL, then any library that depends on A needs this config too.

**Comment by domoritz** [comment]
@israeltq There probably is but we don't have time to look into this. If you find a solution, please send us a pull request.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4547

**Comment by dileepyelleti** [comment]
Hi
Is this change available in latest version?
