### ISSUE TITLE
Sort By Encoding

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4477]
Just like how selection can project by another encoding channel, it makes sense that users may want to order a discrete field by another field. 

(For example, ordering x by the y-field where y could be a sum of something.) 

To be consistent with selection, a reasonable syntax could be:

`"sort": {"encoding": "x"}`

For example, we can modify the [`bar_aggregate` example](http://vega.github.io/vega-editor/#/examples/vega-lite/bar_aggregate) like this: 

```
{
  "data": { "url": "data/population.json"},
  "transform": [{"filter": "datum.year == 2000"}],
  "mark": "bar",
  "encoding": {
    "y": {
      "field": "age", "type": "ordinal",
      "sort": {"encoding": "x"}
    },
    "x": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"}
    }
  }
}

```

**Comment by domoritz** [comment]
I like this. It makes charts with sorting more reusable as users only have to change the field in one place.

**Comment by kanitw** [comment]
Will be done in https://github.com/vega/vega-lite/pull/4478

**Comment by manzt** [comment]
This feature does not seem to be working: 
![image](https://user-images.githubusercontent.com/24403730/52537884-95380700-2d63-11e9-982f-1481674ed7dd.png)

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YFugeLdeWI5RgAniIroxVh1Lb09kMAAPPwCg2Do1DUhNZ0wcYEhWXTFsLRTSQm5CVjFnY3lFFQBfdQhIPF10JVgAM25dVByAbXTmxjE8ZF0cpOdWVDpvZGswAF4ZsAAmAAYVyEqAXRqoDF0Aa2GrIa3IZCV4bk1GJWoc0Aha71vIXuQxTWH0amQ1KDxvQm+pjalyUAR+kFceCep3OIJupgia2qGlqiLSKPukE+1F0wgGw1gYwS90xLzewwBhTE3y2JLq-0BUAAjqxGkY8KUqMSSVB0BFGLAnuzqRTCsVSso1hjKhpkbVzkpevCwOk+QKAJpPVBXACiEQGSihOGkS0qMsqQA

**Comment by domoritz** [comment]
We haven't released it yet.

**Comment by manzt** [comment]
Ah sorry. Just seeing it in the docs.
