### ISSUE TITLE
Title config ignoring frame parameter (Vega-Lite version 3.0.0-rc12)

### ISSUE THREAD

**Issue by itsozz** [vega/vega-lite#4481]
Hi,

I am trying to create a config file to align the titles of charts to the position of the y-axis, i.e. `group` as opposed to the full bounding box. Specifying this within the `title` object achieves this:

```json
"title": {
    "text": "A title",
    "anchor": "start",
    "frame": "group"
}
```

[View in Vega-Lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg4wAbU0mTwKBmVNM4m1ADCqFPqR1aABrIkDcAEYAJgAGAF8NR0dnV3dzLwARHjQrfCYEMG89IKhQ8LAAFgAOBIckiBS3Dy8AcSYAJwwAMy6UErKbAFYo2vrjRrTPXCgACR52uD61ELCbKpq64wBdOtGtTHbgrw4MdvU6qBRlBB5tJmUaGyMkqAAPJ6guphRxbS8B5ZQfAATyIfWmAEc2K48vo8tQoHtHFBgR8vj8-tNUs1ASCwV5lNl7uk4rtElpYeJwWBnsj8ChXvgvAAVHhEMBwMEobTWcnI1zIeZeOD6dpMvkmT6dHJeGjtHhsIhQXYgOJAA)

However when specifying this within `config`, it appears that `frame` is ignored:

```json
"title": {
    "text": "A title"
},
"config": {
    "title": {
        "anchor": "start",
        "frame": "group"
    }
}
```

[View in Vega-Lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg4wAbU0mTwKBmVNM4m1ADCqFPqR1aABrIkDcAEYAJgAGAF8NR0dnV3dzLwARHjQrfCYEMG89IKhQ8LAAFgAOBIckiBS3Dy8AcSYAJwwAMy6UErKbAFYo2vrjRrTPXCgACR52uD61ELCbKpq64wBdOtGtTHbgrw4MdvU6qBRlBB5tJmUaGyMkqAAPJ6guphRxbS8B5ZQfAATyIfWmAEc2K48vo8tQoHtHFBgR8vj8-tNUs1ASCwV5lNl7uk4rtElpYeJwWBnsj8ChXvgvAAVHhEMBwMEobTWMkXG7KL6PQybCksKlPUXI1zIeZeOD6dpM8ljaBdTo5Lw0do8NhEKBSsCk4ykuJAA)

The [docs](https://vega.github.io/vega-lite/docs/title.html#config) imply that config supports all title parameters. `anchor` works fine but it seems that `frame` is ignored. Apologies if this is a duplicate issue or I have not understood the docs correctly.

Many thanks.

**Comment by domoritz** [comment]
That's a bug. We do set the frame parameter to a better default but fail to respect the config.

**Comment by itsozz** [comment]
Thanks very much for the quick response. I'll specify the `frame` parameter within `title` for the time-being.
