### ISSUE TITLE
Support diverging color scheme 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#449]
Need to test if we support this and create example if we do, or modify code if we do not.

**Comment by kanitw** [comment]
@YuhanLu   This is another fun one.   I would start with testing if Vega supports diverging color scale (like shown in D3 here -- https://github.com/d3/d3/wiki/Quantitative-Scales#linear_domain)

If Vega support this, then the next step would be testing / modifying the scale code to support this.

**Comment by arvind** [comment]
Vega does indeed support diverging color scales, encoded like the D3 example linked above. See [Vega's heatmap example](http://vega.github.io/vega-editor/?mode=vega&spec=heatmap).

**Comment by kanitw** [comment]
Thanks @arvind!  Then it should be very easy to support this in Vega-Lite :)  
(Maybe we already support this, but just need to add examples.)

**Comment by domoritz** [comment]
This would be great to have!

**Comment by YuhanLu** [comment]
- [ ] create example json 
- [ ] add it to the docs (When people read scale.md they won't know that we support diverging color)
