### ISSUE TITLE
Is there a way to rotate the y-axis label and sit it in the upper left corner?

### ISSUE THREAD

**Issue by palewire** [vega/vega-lite#4492]
Many news charts rotate the y-axis label so it can be read left to right and lift it to sit above the top of the axis. I've roughly recreated this in Vega-Lite via Altair, but longer axis titles generate the bug below. Any idea how to fix it? I don't see a text anchor setting in Vega-Lite I can use.

![screenshot from 2019-01-24 22-57-02](https://user-images.githubusercontent.com/9993/51730190-631c6a80-202b-11e9-9390-6da5d645e79f.png)
```json
{
  "config": {
    "view": {"width": 400, "height": 300},
    "axisY": {"titleAngle": 0, "titleX": -10, "titleY": -10}
  },
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/iowa-electricity.csv",
    "format": {"type": "csv"}
  },
  "mark": "line",
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "source",
      "legend": {"title": "Electricity source"}
    },
    "x": {"type": "temporal", "axis": {"title": "Year"}, "field": "year"},
    "y": {
      "type": "quantitative",
      "field": "net_generation",
      "title": "Net generation (in thousand megawatthours)"
    }
  },
  "title": "Iowa's renewable energy boom",
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json"
}
```

**Comment by g3o2** [comment]
The available properties for the axis title can be found [here](https://vega.github.io/vega-lite/docs/axis.html#title)

What bug are you precisely referring to? 

* Title not left aligning with the y axis labels? (see `titleAlign` or set `titleX` such that it moves further to the right)
* Title not wrapping to two lines? (not yet possible)

With long titles, there could even be "trouble" with the default vertical presentation. The best workaround is to try shortening the title: e.g "Net generation (th. MWh)", "Net generation ('000 MWh)" or "Net generation (GWh)" ...

**Comment by palewire** [comment]
Ah. Interesting. I didn't know about titleAlign. Am I using it correct here?

![download](https://user-images.githubusercontent.com/9993/51815059-4c685480-2273-11e9-970c-79a65fb445a4.png)
```
{
  "config": {
    "view": {"width": 400, "height": 300},
    "axisY": {"titleAngle": 0, "titleX": -10, "titleY": -10, "titleAlign": "left"}
  },
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/iowa-electricity.csv",
    "format": {"type": "csv"}
  },
  "mark": "line",
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "source",
      "legend": {"title": "Electricity source"}
    },
    "x": {"type": "temporal", "axis": {"title": "Year"}, "field": "year"},
    "y": {
      "type": "quantitative",
      "field": "net_generation",
      "title": "Net generation (in thousand megawatthours)"
    }
  },
  "title": "Iowa's renewable energy boom",
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json"
}
```

**Comment by domoritz** [comment]
Yes, that looks right. Thanks, @g3o2 and @palewire!
