### ISSUE TITLE
Merge Bin Nodes in Dataflow

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4496]
We don't seem to be merging the bin transforms in interactive_layered_crossfilter (although they are the same). This would simplify the generated code significantly. 

![image](https://user-images.githubusercontent.com/589034/51808667-afde8c00-224b-11e9-9ee0-12b8d8dc5000.png)

**Comment by domoritz** [comment]
The way we should implement the logic here (I tried some other things but they are not as good) is that we create a new bin node right before the current node and then merge all the bins that are not produced by the current node into that new bin node. Then we take the rest and merge them into a single node that comes after the current node. 

@Saba9 let me know if you have any more questions.

**Comment by domoritz** [comment]
I started the optimizer at https://github.com/vega/vega-lite/pull/4497 so hopefully this will be easy for you to pick up from there. In the end, it should look something like this:

<img width="680" alt="screen shot 2019-01-27 at 16 44 17" src="https://user-images.githubusercontent.com/589034/51809208-11562900-2253-11e9-81fc-dde896926698.png">

**Comment by Saba9** [comment]
This was addressed by #4497. The current data flow diagram appears as below

![image](https://user-images.githubusercontent.com/3665042/57896028-89952a00-7803-11e9-8481-af3701925088.png)
