### ISSUE TITLE
Quantize scale does not use heatmap scheme

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4500]
Shouldn't this example use `greenblue`?

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESHiPolsAGbcjVDMAbVAId19GMTxkIzMDb00QjXCwA0jkMSScSABJAFkAEQAhAH0AJR1GJWo1KAp0CWywT1ZkVxTw9Lsss0hy7gJkJVKAFW4MPG57CqqausgGprNW9s6AXWcNZ3W3KAwjAGs+o2R4PDUNSAB3Rk0WM2kABie9yBRGanwzACYXt+G8G4mmqtX0nUgAA94p13OxqvFIBhIfCfNgAGxPDqpCI9Zp5IplSp4UGXHFQPAAT0IyD6AEdWN4SboSVRIJ1seFIJSYeTIKjEcjUbAzAAWLF7VKQDK9HIDIYjcaTaawWYk+aSrlUmn0xlKZlVNkczWQIFiAK8nGQdDUainWgxPpA1j6slW7W0nIMpnMQ20zXuBCNT1pWFa6khyDe-WMABetLDW1SSbAnNNykiYNDUq8NRDYStKB0GEIlr5-DQkbtyGG7DEbXZ5JTEE57lsyGuZa5sE83EOkc83lghHQp1dHO2IC2QA

![image](https://user-images.githubusercontent.com/589034/51861756-db1bb680-22f1-11e9-8061-00a166649480.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/movies.json"},
  "transform": [{
    "filter": {"and": [
      {"field": "IMDB_Rating", "valid": true},
      {"field": "Rotten_Tomatoes_Rating", "valid": true}
    ]}
  }],
  "mark": "rect",
  "width": 300,
  "height": 200,
  "encoding": {
    "x": {
      "bin": {"maxbins":60},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "bin": {"maxbins": 40},
      "field": "Rotten_Tomatoes_Rating",
      "type": "quantitative"
    },
    "color": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {
        "type": "quantize"
      }
    }
  },
  "config": {
    "range": {
      "heatmap": {
        "scheme": "greenblue"
      }
    },
    "view": {
      "stroke": "transparent"
    }
  }
}
```

**Comment by kanitw** [comment]
@domoritz  Does https://github.com/vega/vega-lite/pull/4566 fix this?

**Comment by domoritz** [comment]
![image](https://user-images.githubusercontent.com/589034/53303537-3cb34000-3820-11e9-8a7c-95233f318c0d.png)
