### ISSUE TITLE
Support binning and aggregation together

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4503]
I'm proposing to support binning and aggregation together for color channels.

It would be nice to bin the output of an aggregation. We could easily support this by mapping the code below to a `quantize` scale. I think the semantics are fairly clear and not too surprising for users but I would like to hear your concerns. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/movies.json"},
  "transform": [{
    "filter": {"and": [
      {"field": "IMDB_Rating", "valid": true},
      {"field": "Rotten_Tomatoes_Rating", "valid": true}
    ]}
  }],
  "mark": "rect",
  "width": 300,
  "height": 200,
  "encoding": {
    "x": {
      "bin": {"maxbins":60},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "y": {
      "bin": {"maxbins": 40},
      "field": "Rotten_Tomatoes_Rating",
      "type": "quantitative"
    },
    "color": {
      "bin": true,
      "aggregate": "count",
      "type": "quantitative"
    }
  },
  "config": {
    "range": {
      "heatmap": {
        "scheme": "greenblue"
      }
    },
    "view": {
      "stroke": "transparent"
    }
  }
}
```

**Comment by kanitw** [comment]
Feel free to re-open the issue if you have a more convincing use case.

**Comment by domoritz** [comment]
In your spec example, there is no way to do binning before count since there is no field.

**Comment by kanitw** [comment]
So? It’s still confusing to read what’s the order. Plus, what if it’s other aggregation?
