### ISSUE TITLE
Symbol legend has gradient length

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4508]
See https://vega.github.io/editor/#/examples/vega-lite/point_color_with_shape

`gradientLength` is not needed here. 

```json
"legends": [
    {
      "stroke": "color",
      "gradientLength": {"signal": "clamp(height, 64, 200)"},
      "title": "Origin",
      "encode": {
        "symbols": {
          "update": {
            "fill": {"value": "transparent"},
            "opacity": {"value": 0.7}
          }
        }
      },
      "shape": "shape"
    }
  ],
```

**Comment by jshreyans551** [comment]
Hi @domoritz! 
Considering that this issue was a trivial one, I have directly submitted a PR for this. You can find it here:
[#4560](https://github.com/vega/vega-lite/pull/4560)
