### ISSUE TITLE
Fix domains of scales with filtered domains

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4513]
With Vega-Lite selections, we can filter data to match a selection. However, this causes scales to jump uncontrollably inhibiting users ability to make comparisons. It would be nice to have a way to fix scale domain to their initial domain. 

requested by @jheer

**Comment by kanitw** [comment]
One possible hack that could work for now is to add another layer for the unfiltered data with opacity = 0.  Obviously allowing this without a hack is probably useful

**Comment by arvind** [comment]
Duplicate of #4327.
