### ISSUE TITLE
"legend-orient"="none" behaves as "top-left"

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4515]
In vega-lite 3.0.0rc12, when you set a legend's orient to none, it behaves as if you had set it to "top-left":

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "sum", "field": "yield", "type": "quantitative"},
    "y": {"field": "variety", "type": "nominal"},
    "color": {"field": "site", "type": "nominal", "legend": { "orient": "none" }}
  }
}
```

![image](https://user-images.githubusercontent.com/659086/52170731-defa6f00-271d-11e9-8ac6-24f0127eb4c3.png)

Since the "none" option for "orient" is tantamount to simply disabling the legend by setting it to an explicit null, I think the "none" option should be removed altogether. "AxisOrient" does not contain a "none" option, so "LegendOrient" probably shouldn't either.

**Comment by domoritz** [comment]
As you explained, you can disable legends with `null`. 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "sum", "field": "yield", "type": "quantitative"},
    "y": {"field": "variety", "type": "nominal"},
    "color": {"field": "site", "type": "nominal", "legend": null}
  }
}
```

`none` allows you to customize the location by setting x and y. See https://vega.github.io/vega/docs/legends/#orientation

**Comment by marcprux** [comment]
Understood. I guess my assumption that leaving "orient" unset when a legend was part of a group mark would cause the automatic placement to use the "x" and "y" of the group.
