### ISSUE TITLE
nested objects wrongly serialised 

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4517]
Consider the following minimal spec:
```json
{
"config": {"view": {"width": 400, "height": 300}},
"data": {"values": [{"nested": {"key": 2}}, {"nested": {"key": 4}}]},
"transform": [
   {"aggregate": [{"op": "sum", "field": "nested.key", "as": "sum_keys"}]}
],
"mark": "bar"
}
```

I would expect it returns a `sum_keys` with value `6`, but it doesn't (its 0).
Looking to the created Vega code it seems the serialising within the `transform` is going wrong:

```json
"transform": [
   {
      "type": "aggregate",
      "groupby": [],
      "ops": ["sum"],
      "fields": ["nested\\.key"],
      "as": ["sum_keys"]
   }
]
```

If I remove the `\\` within `"fields": ["nested\\.key"]` it works as expected.

**Comment by kanitw** [comment]
@domoritz is this a bug? Or do users need to use some format to access nested data?

**Comment by domoritz** [comment]
We do flatten nested fields but I guess we are not doing it for fields used in transforms. I don't think users can do much other than flatten the tuples themselves with `calculate`.

**Comment by mattijn** [comment]
Another use cases where this error comes forward is with interval selections on scales, eg. zooming in a chart ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCixkY5PDw8VOUBAiRqAJ0YATbGGMnTeAJ6FktyIyV5k5iujFqGg6Q7J42OJAI-siwkEFgAL4aCeqmVuh4mEbxkH5irDG2ANrxEMCQSjHe4cBQWVAAjGpQ7LYATAAcCSmldhVVyDV17m3NIbYArBPdqQ59lbDV2LWQ9ZDSY604ACzSM73lC0tYK2vbm7YAnA37c-MDQ6vuExc4HTc9d4cPy8MRAGyvMATPafObfRaDX5PCIAdiBDUut3B-UhjzWHSBHVhMzmB1Rx1O7kxqhakza3XiAF1krNIBhzABrdyEbiePCBUzIJTwbhWTzUWz2UxOIW9SAAM0Y2nCUCOgzomFmwWcrncAEdWOgvMwMowqHEHGDTAAPMV3SXSsSygkK1rKkyQVVuCKa7X6TL6A3xJIQJIJIA)):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "selection": {
    "grid": {
      "type": "interval",
      "bind": "scales"
    }
  },
  "data": {
    "values": [
      {"nested":{ "a": "1", "b": 28}},
      {"nested":{ "a": "2", "b": 55}},
      {"nested":{ "a": "3", "b": 43}},
      {"nested":{ "a": "4", "b": 91}},
      {"nested":{ "a": "5", "b": 81}},
      {"nested":{ "a": "6", "b": 53}},
      {"nested":{ "a": "7", "b": 19}},
      {"nested":{ "a": "8", "b": 87}},     
      {"nested":{ "a": "8", "b": 52}}
    ]
  },
  "mark": "point",
  "encoding": {
    "y": {
      "field": "nested.a",
      "type": "quantitative"
    },
    "x": {
      "field": "nested.b",
      "type": "quantitative"
    }
  }
}
```
I try to zoom using scrolling in this animated gif:
![ezgif com-optimize-3](https://user-images.githubusercontent.com/5186265/63640917-2a6a6f80-c6a6-11e9-9173-e0597ec6bea5.gif)
The domain arrays is updated accordingly, but it cannot resolve, so the chart stay as is.

**Comment by domoritz** [comment]
The solution to the first example is to flatten fields explicitly. I now think that this is the right approach since Vega-Lite internally assumes that fields have been flattened. If we want to resolve this, we need to add field tracking, which is a bigger issue (https://github.com/vega/vega-lite/issues/2862).

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"values": [{"nested": {"key": 2}}, {"nested": {"key": 4}}]},
  "transform": [
    {"calculate": "datum.nested.key", "as": "nested.key"},
    {"aggregate": [{"op": "sum", "field": "nested.key", "as": "sum_keys"}]}
  ],
  "mark": "bar"
}
```

**Comment by domoritz** [comment]
I field a separate issue for the selection issue: https://github.com/vega/vega-lite/issues/5334.
