### ISSUE TITLE
Sorting broken with multiple layers when using min/max

### ISSUE THREAD

**Issue by jsoma** [vega/vega-lite#4522]
While #2964 sorting in layered charts seemed to be generally fixed in #3959, if you change the barley example from `ci0` and `ci1` (left) to `min` and `max` (right), sorting is dropped.

![image](https://user-images.githubusercontent.com/95126/52380179-c601fe80-2a3a-11e9-9915-f582570169f1.png)

Log reads with the error:

```
Dropping sort property {"field":"yield","op":"mean","order":"descending"} as unioned domains only support boolean or op 'count'.` error.
```

Maybe I'm totally missing something, as all other types of aggregation work, just not min/max.

**Links:**  [working with `ci0` and `ci1`](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl26E8gCe8xSoC+6iJDHo7yI2YDaoBDuGEYA1mYGeHaEyGaQhNyMSnhqUABmjGJiyJpmeEasyK4a7shK8NyaSdQRJUGQAB61QS1Q6NTURsJ4sTiQqMjoKqrpjMhiuX12YxOpkFExcQCOrEN4zDqMVGp1LZAI6NkRkABePtxmaYewRW6t7ugNjLDH63hHfQBCNtl2YACaM1yzl2YGK90gdma91G40mUAoNjGUTmC16UG4RiqSkOOxhUEURhS+kgGThcWm5NUkG4hDiAyGc0xmh8cRZCDK2JqIPu4NakAqYkxx0RYkKcXYnng4R5QVlrjAgXqIXCfQKRzupXKlWq0L2TX0oIeHS6tB6cXgjAADHMybMpkDUdF0ZAVmsNuttqC+fqAEx6-ntTrdF2WgCMtsdDqpUDRy1WyQ9W1i3s19ShhvxpKjCKRyBRI3mzrizKSuLTe0JxMV2fJ0dmhdp9MGwwxWNZfXZ8E5utlLT7YI0zgAuiBnEA) vs. [not working with `min` and `max`](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl26E8gCe8xSoC+6iJDHo7yI2YDaoBDuGEYA1mYGeHaEyGaQhNyMSnhqUABmjGJiyJpmeEasyK4a7shK8NyaSdQRJUGQAB61QS1Q6NTURsJ4sTiQqMjoKqrpjMhiuX12YxOpkFExcQCOrEN4zDqMVGp1LZAI6NkRkABePtxmaYewRW6t7ugNjLDH63hHfQBCNtl2YACaM1yzl2YGK90gdma91G40mUAoNjGUTmC16UG4RiqSkOOxhUEURhS+kgGThcWm5NUkG4hDiAyGc0xmh8cRZCDK2JqIPu4NakAqYkxx0RYkKcXYnng4R5QVlrjAgXqIXCfQKRzupXKlWq0L2TX0oIeHS6tB69KSczJsymQNR0XRkBWaw2622oL5+oATHr+e1Ot1HRgmiNSXbbVSoGjlqtkq6trEPZr6lDDfiw+S+oijMioaHo31mUlccm9oTiYqMzaoJTZqHafTBsMMVjWX12fBObrZS0e2CNM4ALogZxAA)

**JSON:**

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "layer": [{
    "mark": {"type": "point", "filled": true},
    "encoding": {
      "x": {
        "aggregate": "mean", "field": "yield", "type": "quantitative",
        "scale": {"zero": false},
        "axis": {"title": "Barley Yield"}
      },
      "y": {
        "field": "variety", "type": "ordinal",
        "sort": {"field": "yield","op": "mean", "order": "descending"}
      },
      "color": {"value": "black"}
    }
  }, {
    "mark": "rule",
    "encoding": {
      "x": {
        "aggregate": "min", "field": "yield", "type": "quantitative"
      },
      "x2": {
        "aggregate": "max", "field": "yield", "type": "quantitative"
      },
      "y": {
        "field": "variety", "type": "ordinal",
        "sort": {"field": "yield", "op": "mean", "order": "descending"}
      }
    }
  }]
}
```

**Comment by domoritz** [comment]
Vega does not allow sorting unioned domains by anything other than count. Vega-Lite makes a best effort to reduce transformations to make scale domain not unioned but fails here. I suspect it's because min and max require parsing we don't merge.

**Comment by kanitw** [comment]
Looking at the Vega outputs for both min/max and ci0/ci1 cases, I don't understand why `min` and `max` require explicit parsing as number with

```
{"type": "formula", "expr": "toNumber(datum[\"yield\"])", "as": "yield"}
``` 

but `mean`, `ci0` and `ci1` do not?

**Comment by kanitw** [comment]
Is it because mean, ci0, ci1 always cast string into numbers? 

If so, I wonder if the parse merging logic is a bit wrong? 
(Namely that the parse as number node should be moved up?)

**Comment by domoritz** [comment]
Looks like the merge logic is missing a case (@Saba9).

In the graph below we should move the parse node up right after the source but as a parent of both fork ing paths.
