### ISSUE TITLE
Improve diverging scales UX and add `domainMid`

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4542]
Right now, diverging scales are a bit opaque. How do they relate to domains with 3 values? When does the diverging scheme get used? How do they relate to `domainMid`? All of these need to be clarified and maybe implemented. 

See discussion in https://github.com/vega/vega-themes/issues/15

Related #4323

**Comment by domoritz** [comment]
Initial documentation of diverging schemes came in https://github.com/vega/vega-lite/commit/2d4b2522cdd4cf7b687ca18c444e99d0c767945b

**Comment by kanitw** [comment]
Yes we should add domain mid. 

To provide an example of domain mid, I think we can add color to https://vega.github.io/vega-lite/examples/joinaggregate_residual_graph.html

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/5671
