### ISSUE TITLE
Add angle channel for symbols

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#4548]
I couldn't find any previous discussion on this, but apologies if I am repeating previous discussion. 

Would it be practical / desirable to have an orientation channel? This seems one of Bertin's more straightforward retinal variables that is currently absent from Vega-Lite. Personally I would find this very helpful, especially for geographically embedded visualisations.

One use case: To create directional glyphs for representing vector fields. I have managed to [simulate these programmatically](https://gist.github.com/jwoLondon/896e094ac367779e46f1a5d4f9c53d41) by generating a set of SVG path custom shapes, but this is too cumbersome to be a routine approach and requires the data to encode with orientation to be categorical. 

One could imagine a syntax consistent with other channel encodings, such as 

```json
    "shape": {"value": "triangle-up"},
    "size": {"field": "speed","type": "quantitative"},
    "orientation" : {"field": "direction", "type": "quantitative"}
```

leading to output such as

![orientationexample](https://user-images.githubusercontent.com/1846999/52540584-223e8880-2d83-11e9-903c-ac0682eb3a8d.jpg)

**Comment by iFlameing** [comment]
@kanitw I would like to work on this issue.

**Comment by iFlameing** [comment]
can you provide me some starter file so that I can get started with this issue?

**Comment by kanitw** [comment]
I'd look at https://github.com/vega/vega-lite/pull/4259 as a guideline for adding a new channel. 

Note that unlike strokeWidth, `angle` is a quantitative scale.
It also should only be added to text mark and point mark compilers, using a `mixins.nonPosition` (see size in the point mark compiler).

**Comment by kanitw** [comment]
As a part of this PR, it's probably nice to replicate https://vega.github.io/vega/examples/wind-vectors/ in VL.

**Comment by jwoLondon** [comment]
Are there plans to implement the angle channel for the VL4.0 release? I note it listed in the **Maybe 4.0** milestones, but not sure if that means most likely yes or no. Personally, I would find an angle encoding channel very useful for certain mapping tasks.

**Comment by domoritz** [comment]
We won't have cycles to get this in for 4.0 (which we want to get out asap) but it makes sense for 4.1.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5675
