### ISSUE TITLE
Have the default documentation reflect the latest released version, not pre-release versions

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#4549]
We direct users of the julia package [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl) to the main [vega-lite documentation](https://vega.github.io/vega-lite/docs/) in many places. What has happened a fair bit now is that users read about a feature in the vega-lite documentation that has actually not shipped in a released version of vega-lite, then they tried to use that in VegaLite.jl only to figure out it didn't work (because VegaLite.jl always tracks the latest *released* version of vega-lite, not release candidates or other pre-release versions).

Would it be possible to have the docs for the latest released version to be the default? Or maybe have another URL that always hosts those, rather than the docs for pre-release versions? Or something like the julia documentation system, where one can switch between different doc versions, like [here](http://fredo-dedup.github.io/VegaLite.jl/stable/) in the top left corner?

**Comment by iliatimofeev** [comment]
I will be very helpful to understand in which version of the specification feature was introduced. Altair currently supports v2 and it takes some time to understand is that new feature or just an issue in Altair.

**Comment by kanitw** [comment]
Fixed

**Comment by davidanthoff** [comment]
Is this really fixed? When I go to https://vega.github.io/vega-lite/docs/, I see for example the documentation for the regression transform, which AFAIK is a 4.0.0 feature, right?

This whole situation is really quite confusing for our Julia users...
