### ISSUE TITLE
Wrong whiskers of box plot

### ISSUE THREAD

**Issue by akngs** [vega/vega-lite#4568]
Box plots (the schematic plot, a.k.a. *Tukey box plot*) rendered by vega-lite have the wrong length of whiskers. This is different issue from already closed one: #3163

It seems like vega-lite draws whiskers using the following formulas:

> Q1 - 1.5 IQR for the lower one and Q2 + 1.5 IQR for the upper one,

while the correct ones are:

> **the smallest data within** Q1 - 1.5 IQR for the lower one and **the largest data within** Q2 + 1.5 IQR for the upper one. (J. Tukey, p44-47, Exploratory Data Analysis)

Here's a detailed explanation and demonstration:

https://beta.observablehq.com/@akngs/vega-lite-renders-box-plots-differently

**Comment by domoritz** [comment]
If this is wrong, we should fix it for the 3.0 release.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/4573
