### ISSUE TITLE
Make selection init work without projection

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4575]
(Copied from Slack)

From https://github.com/vega/vega-lite/pull/4139, it seems like init only works when there is a selection projection (`fields` or `encodings`).
(At least I see that the `init` is only initialized in the project transform compiler.)

I wonder if `init` should actually work as the `datum` object when there is no projection.  ~~(Basically, default to “field” when none of the projection type is defined.)~~

This is not blocking for 3.0 though.  I also haven’t looked deeply enough if this is even feasible in Vega, but since it’s not pressing for 3.0, I’ve stopped looking. 

cc: @arvind

**Comment by arvind** [comment]
When not projected over and fields or encodings, discrete selections works by using an internal `__vgsid__` field that is calculated via an identifier transform. User's don't have access to their field apriori, and the identifier transform maintains a global counter so consistent IDs are not guaranteed between re-parsing.

I'm not sure what you mean by "default to 'field'".

**Comment by kanitw** [comment]
Oh right, I forgot that we use the internal `__vgsid__` field for syncing discrete selection.  (Thus, please ignore the "default to 'field'" part.)

Sounds like we can't really support this then. 

Perhaps, it's worth throwing a warning that `init` must be used with a selection projection? 

(Currently, if user specify [`init` without projection](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckACK701MC2RhYE7btg3uYRI2qIJXvGELcjEp4sHRqGpCa6HiYOMCQrLpi2FrR6KTw6M7yiioAvuoQkHiWSrAAZty6qCkA2vGZYvCsYtHIKZAAnshZABRReKyodACaPboAlGpQ6LAdY1mQeQC6hVCt3bp1oBBFsMhiyPBGyik7u0UAwp1iI1txGhdFeJ2E7aawQdSH4U+7kEFmGdINcJEonHMcAAWVRQBb3MAARgAnAB2VEFR5PSDsIKaM5Yv4gm545DOYFBQisPAdUrUdqwyCoIIpaSMjAADxSAA5GbA8MhCClEZi-hdIPCKUoqTTTHSGVBmSYkciAGzI9noLk4FHcxF8gVCnV5Qm7E1-c1mtZFDC6ADWHXgjF08B+1qgyCU8G4mi+BKJ2rA8XKjAO+NMAAkqvsAgB3MnTYqvd5QACOrHQwWY0UYVCW7qKnWBIbDHQAsoxDrAAPpvXTVgDi6DEYlOjJebw66czRhiRjzoux3tbCPORO94OYxmB+0Ox2nplBd0TJbE4agAHl9EwVO3kx0lNwlc386aihRm6wU5BqLpkEXTZaIJaCkGscVShUqjUcPVICGxAFUdIFnI4TmVYlbi2PIVndJksgdUwnRdN1309b1fSUah-WxQNg1DNcOijZxBW4eMtj3TtTG7LM+1zdpB3FIs4n-Aj10gCsq1rMlG2bVtdygDtrxo3scwHAsoGHKpizYjot08FlKOvQ9j2SRj-k+AAvFN4gvMQr2FAAGQynzAF9lhAE0gA), it will be quietly ignored.)

**Comment by kanitw** [comment]
From Slack conversation>

> Arvind: One thing we can do is infer the right projection if only an init has been specified.
> There’d be some ambiguity between fields/encodings, but I think we can resolve that via warnings/errors and by having people disambiguate vis explicit projection.

> Kanit:  Yeah, I think we can define that if there is no project defined, we simply just stick to some rules.  (e.g., field only)
> (I could see encoding-first rules too, but that’s harder to understand/explain, so I prefer field-only.) (edited)

> Arvind Satyanarayan:
> I’m fine with fields only
> Though I’d have to double check how that would work for interval selections
> Particularly over binned fields
> Not sure that would work.
> So maybe encoding-first. TBD

**Comment by arvind** [comment]
Added with #4691.
