### ISSUE TITLE
Make docs for padding more consistent with Vega

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4582]
See https://github.com/vega/vega-lite/pull/4581

**Comment by kanitw** [comment]
Note that Vega's property name is offset, and it aims to be more generic than our specific use of it for padding, which is a bit more similar to axis.

**Comment by kanitw** [comment]
And our descriptions of axis label/titlePadding are already identical with Vega. 

So not sure if we should really do anything here.
