### ISSUE TITLE
Smart alignment based on angle for header

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4586]
(We already do this for axis, but not for header.)

**Comment by domoritz** [comment]
We can probably reuse the logic, though.

**Comment by kanitw** [comment]
Yes, but right now we haven’t yet

**Comment by EvsChen** [comment]
Hi guys, new to this repo, can I take a try on this?

**Comment by domoritz** [comment]
Welcome. Sounds good to me. @kanitw and I can answer any questions you might have.

**Comment by kanitw** [comment]
FYI here is the axis code:

https://github.com/vega/vega-lite/blob/master/src/compile/axis/properties.ts#L85


Here is the header code: 

https://github.com/vega/vega-lite/blob/master/src/compile/header/index.ts#L110

It looks like header has some code already, but it's somehow a bit different from the code for axis.  Also, it probably doesn't work that well. (At least there must be a case bad enough that prompted me to file this issue.  However, I can't remember what's the problem the prompted me to file this issue anymore.)

**Comment by domoritz** [comment]
So the first step is to find examples where the alignment is bad so we can then see what you're changing.

**Comment by EvsChen** [comment]
Is something like this considered a "bad alignment"? Reproducible [Here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJg8u5GImww7dLrBIneMLETcA7oyXVLFDAAVQBlMEJuQlYxdCNlME1GWCtGdlZ4pTBuADMwdGpkMGpdblZifKVNYuQq5Gc-MAAmAAY2ujUNSE04zBxgSFZdMWwtXtJI6NjM+UUVAF91CEgrdCVYHO5dVFGAbQ0IAZzGMTx60e641lQ6AE9kJzAAXifmtpbIRYOwAfh0MXgMTiyAuPTw1zosGQAA9nq8mmAAPxgADkADE0P9kCiwDgUQBZLEotRQdCwC6FOq6T4aAC6SygGF0AGsLo5qQzILV4Nwkv5RqAIMseWJriYft8hVBjjZNBTatoOZKhStboQQaYlNxUH5-p0pVLICh0IqBcrDUY8GJkGjlHhQowAF4asAARhaDINKti7BstqU9qdLtdAFZPV6oD6bGZ-NbRgBOFrmsDzb5fQ23M1eyAFErCM4XWDXfUGyAysRy0zqqJx8PLPBql2QACOrDWlrijCoJcN6GhySzEfrzDjVaiQMykGTqal6ZV0IFZcYsouBRBqigDfVFy2fL1G8gCCxi90a0KoTOhFGroA7PM58LuGItoPDeXK1BKaa65vGxctTqSj7sqh5-KOPyQKe-gurskAAMQAKJmPGAAcAAiTQkvBABsIbxgAwvhZiQLSM5CmRc6QDySjHNQi59skACai6AQh0JnAGozSC094gPMQA)
I guess the code in header does not take into consideration the channel, "row" or "column". The code seems to me only for the "row" case.
<img width="759" alt="default" src="https://user-images.githubusercontent.com/20365185/53471254-f881a300-3a9e-11e9-80d3-96dd63f727ad.png">

**Comment by domoritz** [comment]
Yeah, that looks bad

**Comment by EvsChen** [comment]
Thanks @domoritz! I'll try fixing this and submit a PR.

**Comment by EvsChen** [comment]
I noticed in here

https://github.com/vega/vega-lite/blob/master/src/compile/header/index.ts#L110

It uses some special number like `135` and `225`. While in 

https://github.com/vega/vega-lite/blob/master/src/compile/axis/properties.ts#L85

it's just regular number like `180` and `270`.  I'm wondering if there are some special rules for that, something like "keep it center when it's not too tilted". And which one should I follow?

**Comment by kanitw** [comment]
135, 225 are all variant of 45 degree from the horizontal / vertical orient.  

You should play with axis orient and angle and see how it works. 

Note that we haven't added header orient, but it's probably useful to consider it too.  https://github.com/vega/vega-lite/issues/2446

**Comment by kanitw** [comment]
FYI, I'm refactoring header code.  Watch for a PR.

**Comment by EvsChen** [comment]
I've submitted a PR. Please take a look. Thanks!
