### ISSUE TITLE
Named dataset resolution in layer fails (schema v3)

### ISSUE THREAD

**Issue by ocramz** [vega/vega-lite#4600]
The vega-lite online editor doesn't seemingly work with named datasets. In the example below, referencing the dataset by name yields a blank plot. 

Few things are unclear to me : is the named datasets feature available in schema v3? Did I get its usage right? 

Thank you in advance

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "datasets": {"stocks": {"url": "data/stocks.csv"}},
  "layer": [
    {
      "data": {"name": "stocks"},
      "mark": "line",
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {"field": "price", "type": "quantitative"},
        "detail": {"field": "symbol", "type": "nominal"}
      }
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

- [x] If applicable, include error messages and screenshots, 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/5902760/53331623-a51e2200-38f1-11e9-952f-3f841856d28d.png">

**Comment by domoritz** [comment]
Datasets currently only supports inline data. See https://vega.github.io/vega-lite/docs/data.html#datasets
