### ISSUE TITLE
Add gradient definition

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4611]
As added in Vega in https://github.com/vega/vega/pull/1648/commits/4ca11a254e3e4937a192e81cd3f5f219c687059e

**Comment by domoritz** [comment]
We might get this for free if we use the Vega typings.

**Comment by kanitw** [comment]
Not in encoding though, at least we need to modify the type of valueDef for color/fill channel.

**Comment by PUNITBATRA** [comment]
@kanitw  Can I work on this issue as a beginner? In this issue, I have to replicate it like vega or can you provide any more information about it.

**Comment by kanitw** [comment]
The tasks is to

1) Expose the gradient definition in the typings of
- [ ] value definition of color/fill/stroke encodings 
- [ ] color/fill/stroke properties of mark definition and config

2) Create new line chart example with area gradient.

**Comment by PUNITBATRA** [comment]
Hi @kanitw can you please tell me the specific folder where I have to do the task 1 as specified by you above or I have to do it by creating a new file(Add gradient) here:- [https://github.com/PUNITBATRA/vega-lite/tree/master/site/docs].

**Comment by kanitw** [comment]
You should modify existing typings for `Encoding`, `MarkDef` and `MarkConfig`.

You may need to update `vega-typings` for the new gradient too, if they haven't been updated yet.

**Comment by PUNITBATRA** [comment]
@kanitw As mentioned above (task 2) by you I have created the line chart with area gradient by reading the docs as shown below in the screenshot. In this, I have taken data values randomly. Is it fine or I have to take the data from some specific JSON file?
Please suggest me the changes which you want in the task 2...
![Screenshot from 2019-03-12 19-58-28](https://user-images.githubusercontent.com/34002809/54230496-85f7d500-452c-11e9-9374-dec012760975.png)

**Comment by kanitw** [comment]
I'd modify this example: https://vega.github.io/editor/#/examples/vega-lite/area_overlay and check if it is referenced in any docs in `site/docs`.  
If not, just modify the example directly in examples/specs.  If it is referenced, create a new area_overlay_gradient.

You spec won't pass the schema validation when you have to do 1. first before submitting a PR.

**Comment by kanitw** [comment]
@PUNITBATRA any update on this?

**Comment by PUNITBATRA** [comment]
@kanitw  ya I found that [https://vega.github.io/editor/#/examples/vega-lite/area_overlay](url) It is referenced in site/docs here.[http://127.0.0.1:4000/vega-lite/docs/area.html](url).Now i am trying to modify existing typing for Encoding ,Markdef etc.I will try to do the changes in one day. :)

**Comment by kanitw** [comment]
Let's close this as #5180 is almost done.
