### ISSUE TITLE
Add DS_Store to .gitignore

### ISSUE THREAD

**Issue by EvsChen** [vega/vega-lite#4616]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.

I'm developing on MacOS, I found that `.DS_Store` has not been added into `gitignore` file, and it's quite annoying to see this everytime when doing `git diff`. I guess we should ignore this. Willing to submit a PR.

**Comment by domoritz** [comment]
Can you add it to your global gitignore? This will solve it once and for all projects you work on.

**Comment by kanitw** [comment]
Let's close this as there is already a PR for this.
