### ISSUE TITLE
Use Vega's label alignment logic if it makes sense

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4632]
See https://github.com/vega/vega-lite/pull/4613#issuecomment-467952963

**Comment by kanitw** [comment]
Instead of blinding using it, it'd be great to compare the rules (just in case the rules in VL is better than Vega) and see if they can be combined.

**Comment by domoritz** [comment]
That was what I meant: test whether it makes sense and use what makes sense. I revised the title.

**Comment by domoritz** [comment]
It doesn't make too much sense to use it.
