### ISSUE TITLE
Compiler API Revision 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#464]
Here are the current sketches for Vega-lite API

#### Compiling to Vega Specification Object

- (internal) `vl.compile(vlSpec, stats)` => **Vega Specification Object**

- `vl.VegaCompiler().compile.spec/encoding(spec/encoding, stats {, theme})` => **Vega Specification Object**

#### Encoding <=> Vega-lite Spec / Shorthand

This is probably less commonly used by our users. 

- `vl.Encoding.fromSpec(vlSpec, theme)` => **Encoding Object**

- `vl.Encoding.fromShorthand(shorthand, data, config, theme)` => **vl.Encoding Object**

- `encoding.toShorthand()` => **Shorthand**

- `encoding.toSpec(excludeConfig, excludeData)` => **Vega-lite Specification Object** 

@jheer, @domoritz  any comments?

**Comment by kanitw** [comment]
FYI, I have just updated the issue with more info / note.  

Note that I am not contented with how I currently name all these things.

**Comment by jheer** [comment]
I'm a bit confused here. A surprising array of compile/parse methods!
Perhaps better to discuss in person?

**Comment by domoritz** [comment]
I'm confused as well. Maybe show API examples instead to make things more concrete?

**Comment by kanitw** [comment]
@domoritz  Based on conversation with Jeff, I have simplified the "Compiling to Vega Specification Object” section above.  

We will distinguish between  `vl.compile`, `compiler`.  The current `src/compile/*` would become `src/VegaCompiler`.  Meanwhile, `vl.compile` is a wrapper method that calls the default compiler.

**Comment by kanitw** [comment]
duplicate with #727
