### ISSUE TITLE
Support axis.orient in the config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4648]
In Vega, config.axisX/Y.orient doesn't make sense as we determine the axis properties from the orient.  

However, in Vega-Lite, we can read from channels and apply the orient accordingly.

**Comment by EvsChen** [comment]
I'm not sure if I understand it correctly. If I set `config.axis.orient = 'top'`, does that mean we'll generate all the properties of `config.axis` under `config.axisTop` of the output?

**Comment by kanitw** [comment]
We should only do this for axisX and axisY

**Comment by EvsChen** [comment]
So, that's `"bottom"` for `"axisX"` and `"left"` for `"axisY"`?

**Comment by kanitw** [comment]
We should support setting them, but they don’t have to be set by default.

**Comment by EvsChen** [comment]
What about precedence, for example, if the user set `config.axis.orient = "bottom"` and `config.axisX` at the same time? I guess `config.axisX` should have a higher priority?

**Comment by kanitw** [comment]
As said above: 

> We should only do this for axisX and axisY

`config.axis.orient` doesn't make sense.   For example, config.axis.orient = "bottom" will break all y axis.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4701
