### ISSUE TITLE
List companies that use and universities that teach Vega/Vega-Lite

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4655]
- Organizations: 
  - AirBnB
  - [Apple](https://github.com/apple/turicreate/search?utf8=%E2%9C%93&q=vega-lite&type=)
  - [CERN](https://github.com/scikit-hep/histbook)
  - [Google](https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/charts.ipynb&scrollTo=beTgCbVa_wFA)
  - Intel
  - LA Times
  - [Microsoft](https://github.com/Microsoft/vegalite-for-powerbi)
  - [Netflix](https://twitter.com/oceankidbilly/status/931633519813582848)
  - Twitter
  - Uber

- Universities:
  - Carnegie Mellon  
  - City, University of London
  - Maryland 
  - [Michigan](http://www.mjskay.com/presentations/si649-w19-week3-data_models_gg.pdf)
  - [MIT](http://vis.csail.mit.edu/classes/6.894/)
  - Stanford
  - UC Berkeley
  - Universidad de los Andes, Colombia
  - [Washington](http://cs.uw.edu/442)

Any missing?

**Comment by domoritz** [comment]
CERN, LA times

**Comment by kachkaev** [comment]
_City University London_ has been renamed to [_City, University of London_](https://www.city.ac.uk/) (it’s a [part of the University of London](https://en.wikipedia.org/wiki/Colleges_of_the_University_of_London) now)

**Comment by domoritz** [comment]
Intel

**Comment by domoritz** [comment]
Mostly done in https://github.com/vega/vega-lite/pull/5558
