### ISSUE TITLE
Default autosize doesn't work with custom font

### ISSUE THREAD

**Issue by melissachang** [vega/vega-lite#4657]
With default font, default autosize works properly. The labels are clipped only at the end:

![1](https://user-images.githubusercontent.com/10929390/53835255-dd50e080-3f41-11e9-9868-0aa0f5ec8180.png)

With custom font, labels are cut off at beginning and end:

![2](https://user-images.githubusercontent.com/10929390/53835270-e641b200-3f41-11e9-9b99-b1f9027f076a.png)

I expect labels to be clipped only at the end.

[Link to online editor with spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgYATgGtsYYJDwBPQsn2R26LWqjxWWxTZyRC3RkrzIbAX3URIZCV4bgATD2p9UAgAkLFuZwMNGKgAM0ZkMVCLcNRUZGz-FKgTMwslblQPdDE1ZJjIBBrzHEMtdCVqFrAAbUgAYgB2AAZBgE4ADgA2WwH4edTQgBZIAF0-eoCxGiDsnCVWMTF6jZSjbm4xPEZCKMh0zL2S5AAPPFnS7sgKqqUayFODReUU2aQyWQsIVYnjqxRKpi+AEdWB1rnh0NcqLDikZmNsLNizrB0fA9PtDmIimd0C9GLAQXCtuh2JkAMKXBIWfrDHm80LmKk4sTMzIAMWU7xcAFkJbBvO13oKzsKWWJxZ4AMqMABe3QAjHrQYCifBmnd2p1kBqvLccAAmYY+E6CyDGBk4h4QlypdDwZB4AD6FBqrAFoKMCPKlWqtSVJTx3QORzjjQSkt6oICAE0Ehx0GAPGAAJJWUIdVRgAByjC6WkYmDjAQAqujEGAtMhYIx+Z5YGAAO7MNuVtMoLRKMAdUJgADqna847AAFEHNwzB1J8F51o3Y2oABxdCodj1ieFufE7wTgAijAodJ4SgrABUUGBD8f64ScUvYBvC9WtZfnukAatwrAsFeYAABIbqyiAeJ2yAVvB1TfmcJbeKeYBuIQhwYo+faFhqhDoB46ENAACtCcjMowBYTgAMugiAJMhlHoDodLoioIHUd4eDcGAABKjCmmeE78VogkiWJ3AUQE7LxJ+-4TlKBSZBIT5gEplQng2mZQAAQkEtASAxYBGR01DCvysCIApUCUd4rD3qpYCMYwGAVs5WisI5kDqUo-IWVq8r5oxyDKGGjJQBqdYeR0Ogbs+R6MGIFmQWATYANIBTlHhtoW0FCahYBSoVOnMMYFYAGoZHgfyoAFACCqR1uJOnWIw7Asu5VlaKW3D0iBRbBdhz6ZKw1CsJlb65QFjGsIgxj5ueyDsKwxjIWAOVBKtAX7qwtEKvRY3hO5JWsMSyiqM+AAarXtWJG4tVuxI7qF4EsP287ZRqAXPsN4n0YWRbomIu6GZAqFKEhYDXmRFn3XSbDWVYSh-ChCF-AFsETrD8OFiZcgRNjaEgUZdbXPZFlLp0wrBZu04aiEeCM4U0PqbSnVvX6H3GBZjHDWAb1dNssAoTUjCpAkSjAdDooePLtOFkrSgcwFABS6CkXDcoWUDOjGNwFY63rkCgqsKY0nS7pwpAKpshyiQDLyfIxYyjsimqEoWDKvbhYq0NO77mo6vqdogaHnlVOmBrDEaKZNPirSuOgoThJ0Y1w4kwx0MMUdQBaXTWsgtpgA6TopMaUBrr61X2w0npPJA9fIp7ZyfFGvz-MnpqpwYkAl90PTDBWerrCm2xdMF+hJscNcaICkBluiTeQMGYihvSOA9KC0Rez6fqBlvoYWDmflWBZJYZ+WVY1lhBmxZAUIwjgerTCBuT5E8PpiHKECXg3gX1zNfMGpZ76ASfh-aYAV27nxwHgPyyAk4H2hsff0QYQxfBbCxdsnZuxBDwH2QcLAqyjiglOWc84oIri0GuZAG4Oj82QVDF+b944TGkN-Lyv99D-0AdDYB6ZIB4LbB2LsPYSEDiHBQ6SY4JzUIvAuCc9DGHMPemw2B0h4GkQ7voZBoY0FwkPg7TBp8cEWA-PpCSNDLyLlvPeLst0wCvmQO+I8+kAqcP0J-ce0Mf4FAETUIRL8RHWK8dhdaDibx3gfK49xniVKwOGHo9ABikEoJMcUMxHpfRYLPl8X87loF1mfl7XxH9Bg8MCXw4JOBBHIWEa8URJS7FlPrNU3RIEEHdCMaguEtcIB5LOBY7B28vhgQgoomCcEcZIXJrjECVSwB6kGHqXheQGlgCaUA1pFhpmQUXPjHSCzAFnOqNUvU6TMlgAGTklIozm4FMsZMiwmFykTlwvha4ygiIThImRXi0NVl6imFHOp2y-6hOaeEg5LhPnYR+cKP5SgAVgCBR4D+ELbmIPudkoZcZnkBHGUUiw1ElC0RPELFibFVAcS4sSDoPjwLvzWQAVgmFs-hjTYX7JAS4Sl1LQZMTpR2BlnFuIdA-lyvF-TCXFGGUkF+ZKrFCtDNJISolOqFikjJHV8kVlsvjhygJL8gkwoAXCr2ESNUCW1S9Ox+rHUhFlWk3p+j8UPKJeg1VryJn4phhyFSdj1L8iOB4FCIbvHGuhPHJY3KoW8t2fylpgqoC6VDRZcNmko06RjV0tZib5WGMVTXYlGCA3kpcCZTo0sLJWQZhnTsDk43sr1EsJYPKdl7PTaIutZlRWWWsrZVtH8u2lqycY31piq0n0DV8XyrlolMS8ugHyLlWXxr8dIc1XtLUhOtQK0Ry63J2NjhusAy6P57qnQSmdSrK3+oXTWqAQUQrEQyFodoHkopw23R2u0SaLX1KtWE21CL327A8V+8Kf7oof2A-en1T6-VH2requKCVmJKGShOVKVQMqFiygtdt8dgM9vAzah2drsP0Vw-htxaViMTlIzlJDEwUPlpiMqklaRMPvJcAVJQRUJwlUueVSqrJqp1Qak1QDFHu3Jt7Wm+FGbIAibEzBUqCEpOiaqiYOT-ompIZWJ6jJ3qeMQD4-OwpWHIBtQ6nBbqvUmF2IGkNEaoKTV+LtLU0D0Kj0Qdo1Bxzz1Oqslc31Dz1gvNIZ6dDPpZbH0VvQ+YwTQbzoTSmjNOaHiyM+Z3R-T+VHgs0ZxHRyA2WUq5dmiR+aHG1mf246l3jz6MOvoc0tFaa0Jxzk2ttCse0lAHXI348FZW+XHv7RYHrq0LIDa2jtEbq0SszAs3c1DaW50vvs0Jg8x1rAEWLONS64EbpPgeopibAWD1gfKye6xR3TqnYunYq6l27r3RK4ll+yXp2DLQ7tzr+2g1OadaLLRn1iLfUQL9Yk-0bslchYFlNfb1OiIh7zaHgtYczIR3gf6KPWtA527kuzbyg1AyaPLG+EN2GVN8yjqbqaZuY4sDTkG9OajGBJ5tqzbWbMdYy11g7MNzkeMRsOlG9kUSdAxljS5yyisduGGMVnGPIMacJgbaXyNUby+oIrq9sN0Af3V6Tx5MR+P3Ey18U5uvYMThJmTZXFSHZguGCB+7QXpshcq2Fx3kvG3IFJp0JZ5u1ne6t7Oine2qdfCpswVGdNm1M2oazbg7MpzI+j4MTXantcDupqnws9MbLUMz2zDmFvBix+B-H0Hif-avEh3zbceOmIizFpkTsUsJCy3HArDhzP8+F-Z8X1vPNXq46Fj3y0EsB8yzlkWvUowG-k6eZTxdFh1Yq20+rTW42LcconwHruYX99l4nEfqcp-N-tfS-ksXQbzYdCJgR7gxtTZgHfyC0fYraPM-FTajJ7Fwf-T-Nxb-E2M2XWGVYAx-YXZ-MZe3UBK+PrYsSBbSTpD3HEMFL+UAx7WbFwS+PMG+bAisXA2BDbJLL1boJpa3EZHfN9MRVsAhKRYhUhOREcBRKhJmFROhVcdcJRXHPPT+KYc-CrS-DTcRDgohXsWRchXg45UQ6cQQxcdREQzcVhHcHRe9RguPbfBPXfFwGxVdexVRBGeJFxbSJJcwvAs4AgyQog-3aQhoKrBwuxDQuJZxR8F8N8Bw1JAw2FJglVZvUwqAdpCyXA8QwgtHVTSfULDTaIgCR+cpbpEI61MI23NVcXI5WZYPRCC5M3OIlwhIsAkguKOHKCIo-WHaM3a5LIuUHIlghzJFDcFFAif5UKUiciE-NZeI33dHIvZI0RDo75NcX5QiXo4FHFO0ZosnJ-EHUXMHJdGiOiWlViCVRlaVAApnIAiQqQ8ApyDYmlQsZibY9iKVZlJQWVLjAXBg0Iowm3No8XF1WSXVSSTVA1OSMo44qoyAD4nVdyYEuSd1RY1okw1grNWxHNDSSNbSWEkfA4jtIYh2Q9Nwk44NZSOEwsXNRE6NXEtfEtR48rKEiI1gwdBtYmUdFteyf41wtnC-DwsLak8yWk5tOyRACdczOgyzJ47Il45g6EhzM9Cwy9TdPyRkio4gjnIVFyc9IWddKU1gW9D1fku5QwxvYwykhzD9Z3TFb9X9SKaKGU4YxIlkgIKrA00KY0iKf9ZATjSE4U8I1YlvFweKBjJKFKFjfLbKPKAYo4pkrXMYw5HDH0gjP0hrArJrPUZDMktwik90yIzTSqYqXTeiCqAzGTIzMAeqEzI8c0jEh7LEwErTCyCTMqbMtsXMmqfM+TI8MzF0nU140U8XbHFzOsNzfqOLDOYaYsnETE5k9w60sLTsgmaLdzRtPs0IYaBLFsrfNsvU8XGrAjOrf0wrQAtE8oi0yo+UqANctxDcmMgMkrB4zU-FbUpckUlcoNebTApbIbXafaRwhoZwgEg8yAB8xbDaZbYbV89bRc5YpvFM1go6E6E7I8jM66QSK7R6IM9Eoc0skc7EiC47a4N7Cwz7OC77X7YC5AlYl-NYiwCcqHXQrvTFOHQnJHRC3cksv3VCwEsijvAWL6AnP6JsDUfnS8wUlo103ItAlwLnDoYdcGXnQcs4Yc0MwPDTESunMGBnHi-7eg8kgSt4oNJ3BGJGQsWXNGBXDoJXUouiz8qfFwLS-XXSw3dGQy03HGKPdfMYAisAWzdsoNOoqA13CPd3SShoaS0Y2S0RDyg2YmMPN3Ro6PC8lSgUtS1s28sChzZPGmbTCvDmZmTFGvXPEykMgKmQkvFPVWNRdPacavbPWvfPZy1yu8r4bmdvOfC4hfcWfvLqQfVfN82IMfYM2Ussr82qnHCi+fPsXvJfFqlfYfByjfRMkc5M4ij0qAa-QqsAO-OebK7qpir8haw-Dwcq9fDlSqkXWa1MyAkKr-H-OAi2VavcuUsyqAY6w0o2WAv-eAu4xAqa683jeoVYZeEAHwIAA). But I don't know how to use custom font in online editor, so this bug can't be reproduced in online editor.

**Comment by domoritz** [comment]
That seems like a Vega issue. Can you file an issue there?

**Comment by domoritz** [comment]
The custom font you chose does not show an errs for me. Can you choose a font that is commonly installed to demonstrate the problem?

**Comment by melissachang** [comment]
Filed [vega issue](https://github.com/vega/vega/issues/1671). Put instructions on how to repro with editor there. Thanks.
