### ISSUE TITLE
Missing color in legend with redundant size + color encoding 

### ISSUE THREAD

**Issue by haldenl** [vega/vega-lite#4664]
Not sure if this has already been addressed, I couldn't find anything with a search. Redundantly encoding a transformed field with a both size and color doesn't result in the legend reflecting both encodings. I'm not sure if this is a bug or just an artifact of the VL model.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {
    "url": "data/cars.json"
  },
  "mark": "circle",
  "encoding": {
    "x": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "bin": true
    },
    "size": {
      "field": "Horsepower",
      "type": "quantitative",
      "aggregate": "average"
    },
    "color": {
      "field": "Horsepower",
      "type": "quantitative",
      "aggregate": "average"
    },
    "y": {
      "field": "Origin",
      "type": "nominal"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/11954298/53853973-8c121280-3f7c-11e9-81ad-72b6f251f6a7.png)

[Link to editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxQCAhIVl0xbC0K0gLfeUUVDQBfdVqMXQBrJsh4Rl14KJLa5CV4bk0PaibqmsgADxWNGqgUxmQxTRGAWUidAH1Y3XOAcXQE5WmdqDwAT1iRgEdWEKM8a0YVCeO0g7A8TTwulYyG2YF6sMgsEYAC9kFtnrt9ocRgAJdJ+AKuWzAtZvD6mb6-ZgAoF9Z6QdDUai6YR4NGmdBUXSMtGw+Eg+YOXTo+l7A5HUx43z+QLCukgsnsqCUpR-Glo+VrRnM1lKhlcnmQPmayCvEUgsXY0wAeX0TBUmtqipGSm4ESU9yNO26PRA3SAA)

A quick hack in this case would be to change the aggregate of one of the `Horsepower` encodings to `mean`, and then you would get two legends, but that wouldn't generalize to other aggregate functions.

**Comment by domoritz** [comment]
That seems like a bug to me.
