### ISSUE TITLE
RepeatRef declared but never used in 3.0.0RC14

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4672]
The `RepeatRef` definition is never used anywhere:

https://github.com/vega/vega-lite/blob/v3.0.0-rc14/build/vega-lite-schema.json#L9389

Previously, the `Field` definition was wither a string or `RepeatRef`:

https://github.com/vega/vega-lite/blob/v3.0.0-rc13/build/vega-lite-schema.json#L4232

But now `Field` is a string, `SignalRef`, `DatumFieldRef`, `GroupFieldRef`, or `ParentFieldRef`, with no reference to any `repeat` option, which makes it surprising that some of the example specs (like `geo_repeat.vl.json`) would validate against the schema.

**Comment by domoritz** [comment]
We don't guarantee that everything in the schema is used but this is clearly a bug somewhere.

**Comment by kanitw** [comment]
The following "weird" definitions in the schema refers to `"#/definitions/Field"` that would expect Vega's Field:

1. `BaseValueRef<TitleAnchor>` -- referred by `ScaledValueRef<TitleAnchor>` -- (See 2.)
2.`ScaledValueRef<TitleAnchor>` -- refered by `AnchorValueRef` -> `AnchorValue` -> `"titleAnchor"` of `Axis` and `AxisConfig` -- we should fix the BaseAxis in vega-typing

3. `DatumFieldRef`
4. `GroupFieldRef`
5. `ParentFieldRef`

All of 3-5 are all referred by the Vega's Field. 

Fixing the `Axis` definition should solve the problem

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/4711

**Comment by marcprux** [comment]
`RepeatRef` is still orphaned, as can be seen by searching for it in https://github.com/vega/vega-lite/blob/v3.0.0/build/vega-lite-schema.json#L9524 . You can also see this by loading the example spec `selection_resolution_intersect.vl.json` in the vega-lite editor and seeing that the `repeat` object for `field` is marked as being invalid.

I'm surprised that the example specs aren't being validated as part of the test suite; I could've sworn that they used to be. A lot of these sorts of issues would be caught much easier is there was a quick validation pass during the test run.

Please re-open this issue.
