### ISSUE TITLE
Suppress grid lines for dual axis charts?

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4676]
When generating a dual-axis chart via the `layer` operator in Altair, the resulting plot includes grid lines for both axes. It might be better to suppress default grid line inclusion for axes when the scale resolution is set to `independent`.

[Here is an editor example of the Altair output.](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEA2CGCeBTATpAXGA2uCZS90gFtZkBrdPSAewAdYBjASwBd5KAGAOgGYAaKG1qJKkUoliQAvnxwFIiAHYNqAEyaKA5pXwFC7DLr2FYmzckSbYLERjEA3FKZGzj8gGZNE0VaJtFaAH0SAA9IVzcISABnBlhoWypVahINSkwOAR4OAF0ZOTdIIUTIAEcAV1hFFlZrJkdwguMxEKZonSLWBNEAQXtNLjAAFUQApxZyizAABoBhaSbcfMjIMMNFjy8fUVVrFw2TVvbDSHdqZBIWUQBSACNwwS7ExXLoaGXIwXhhP1Hac-ijU+jyIiAAqopWKIiNRqgALSAHD7NeAAJh0ByipnMlj2olgjmQziBn1OW18dn8QSIaQiK2KogqVRqLDqDSRiykBWReEWxFIFBO0RYyGoZBKOPYAiK3xK0A0LigGhsyH+cBs0Nh1BYsJEPKiShU6i0GJWBl5wLEZgsVg1dgJTk0+0tnm8FKgtAszFotRqsJJ9NljMq1V99WdpNgRw6LO6dgACl6mD7WX7FAtIvrCGsqK7tnZdhrpQzKX8AdAHp1QRCoXYYfCM3ouQRm2AchFIBZotRoA0hXE41RzZANKpEMJFGPqpWczE4eJfFIPpAVIpPNoTvYvAB3DrbpiqFgIjAAFg4mSgcMQTE0cKuGGyHCXHZFVWiZwu6WAZOgKp21nKIguGgag4jTMAAF4ILAAAdSAAGUJBYFgEjg6R2xwSAABJYivEhRDvFhaGiNAAHpSMcKwuE0Vg4XKW4uCYahSNw0ZYAo3EAFp5RsCjUS4AA2LhuAAK27dMO0LSR1nkSYKzsQjiLIjiqJoo96MY5jKNgTipOiRAWGiUipNI7ckKvZAuAYaJ7ADKAP0uGMgzsazbNbLkpCAA)

**Comment by kanitw** [comment]
@jheer is this a part of the education material, if so, we should bump the priority of this issue.

**Comment by jheer** [comment]
@kanitw yes it is.

**Comment by kanitw** [comment]
Okie, will be fixed in #4689 

![image](https://user-images.githubusercontent.com/111269/54010560-1779d800-4124-11e9-98da-5c31cacb3ee9.png)

**Comment by kanitw** [comment]
Note that I added this to our example gallery too. 

I also added "(inches)" to the title and adjust title color to match the layer. :)
