### ISSUE TITLE
Vega is not in devDependencies anymore

### ISSUE THREAD

**Issue by nohanna** [vega/vega-lite#4679]
Hello,

It is not really a bug but there is no Vega dependency in the devDependencies anymore.
In this commit 596bb5544c8d40969d9f64618e07e76d23cf21b4, dependency was removed.

So I've got a compilation error:
`ERROR in node_modules/vega-embed/build/src/embed.d.ts(1,29): error TS2307: Cannot find module 'vega'.`

Should I add Vega dependency myself now?

**Comment by domoritz** [comment]
We depend on vega-cli, which depends on Vega.

**Comment by nohanna** [comment]
Indeed, vega-cli depends on Vega.
This is weird, I'm getting this compilation error since 2-3 days so I had to depend on Vega.

**Comment by domoritz** [comment]
There is probably a place in Vega-Lite where we wrongly depend on Vega.
