### ISSUE TITLE
Vega module not found in webpack build

### ISSUE THREAD

**Issue by erikjchan** [vega/vega-lite#4683]
This is a similar issue to #4339. In fact, it is almost identical. Webpack builds using vega-lite are failing.

The errors I get are:

ERROR in ./node_modules/vega-lite/build/src/compile/repeat.js
Module not found: Error: Can't resolve 'vega' in '/Users/ndb071/Desktop/ve-test/node_modules/vega-lite/build/src/compile'
 @ ./node_modules/vega-lite/build/src/compile/repeat.js 1:0-31 17:22-29 18:25-32 19:30-37 43:24-31
 @ ./node_modules/vega-lite/build/src/compile/buildmodel.js
 @ ./node_modules/vega-lite/build/src/compile/compile.js
 @ ./node_modules/vega-lite/build/src/index.js
 @ ./index.js

ERROR in ./node_modules/vega-lite/build/src/compile/scale/component.js
Module not found: Error: Can't resolve 'vega' in '/Users/ndb071/Desktop/ve-test/node_modules/vega-lite/build/src/compile/scale'
 @ ./node_modules/vega-lite/build/src/compile/scale/component.js 1:0-31 21:12-19 22:38-45
 @ ./node_modules/vega-lite/build/src/compile/scale/parse.js
 @ ./node_modules/vega-lite/build/src/compile/model.js
 @ ./node_modules/vega-lite/build/src/compile/layer.js
 @ ./node_modules/vega-lite/build/src/compile/buildmodel.js
 @ ./node_modules/vega-lite/build/src/compile/compile.js
 @ ./node_modules/vega-lite/build/src/index.js
 @ ./index.js

ERROR in ./node_modules/vega-lite/build/src/spec/base.js
Module not found: Error: Can't resolve 'vega' in '/Users/ndb071/Desktop/ve-test/node_modules/vega-lite/build/src/spec'
 @ ./node_modules/vega-lite/build/src/spec/base.js 1:0-31 26:35-42
 @ ./node_modules/vega-lite/build/src/config.js
 @ ./node_modules/vega-lite/build/src/compile/compile.js
 @ ./node_modules/vega-lite/build/src/index.js
 @ ./index.js

Perhaps this is related to vega no longer being in devDependencies?

**Comment by domoritz** [comment]
Vega-Lite depends on Vega CLI which depends on Vega, no?

**Comment by domoritz** [comment]
Actually, only for Dev. Vega-Lite should not use Vega except for the typings. Is this the bug?

**Comment by erikjchan** [comment]
That might just be the bug. Do you know when your next release is?

**Comment by domoritz** [comment]
Fixed in #4690
