### ISSUE TITLE
[Refactor] Remove custom logic for formatType in Vega-Lite

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4694]
(Now that we have it supported in Vega.)

**Comment by kanitw** [comment]
We can't do this as Vega and underlying D3 doesn't have "quarter" support.

**Comment by kanitw** [comment]
This will simplify our codebase a lot, but we probably should fix this in `d3-time-format` first.  https://github.com/d3/d3-time-format/issues/56

Solving the issue at the d3 level is one good first issue to tackle!

cc: @chanwutk

**Comment by domoritz** [comment]
Depends on https://github.com/vega/vega/issues/1830

**Comment by domoritz** [comment]
Mike added quarter support: https://github.com/vega/vega/issues/1830#issuecomment-545256830

**Comment by domoritz** [comment]
@kanitw Can you point out which code can be refactored now? Or have we done this already?

**Comment by kanitw** [comment]
For axis and legend labels, we only output `format` for numbers. 

For time and custom formatter, we customize the `text` in the label encode block.  We still need to do this for custom formatter.  

The question is whether we can simplify the output for time formatter, which may work if we just pass the format.

**Comment by domoritz** [comment]
@haldenl looked into this. Can you note down what you learned?

**Comment by kanitw** [comment]
Done in https://github.com/vega/vega-lite/pull/6400
