### ISSUE TITLE
"path" mark?

### ISSUE THREAD

**Issue by manzt** [vega/vega-lite#4699]
For a custom path, it is cumbersome to use `"mark" : "line"` and set `"order" : {"value": null}` in the encoding field to makes the marks use the original order in the data sources. It would be nice to make a convenient `"path"` mark for this situation (similar to ggplot's `geom_line()` vs `geom_path()`). 

<img width="293" alt="Screen Shot 2019-03-09 at 6 46 06 PM" src="https://user-images.githubusercontent.com/24403730/54075998-eae9cb80-429d-11e9-94d5-f06d2f488604.png">vs.<img width="287" alt="Screen Shot 2019-03-09 at 6 45 50 PM" src="https://user-images.githubusercontent.com/24403730/54076001-ef15e900-429d-11e9-8166-2a08986fd4e1.png">

**Comment by kanitw** [comment]
I think you're asking for a path mark, which makes sense. 

Note that line is also an open-path (last point doesn't connect the first point), but I think path should be closed.

**Comment by manzt** [comment]
Good point--that's right. I changed the issue.

**Comment by manzt** [comment]
Maybe a transformation can be made, concatenating the first entry to the end of the source for a closed path:  
<img width="271" alt="Screen Shot 2019-03-09 at 7 25 06 PM" src="https://user-images.githubusercontent.com/24403730/54076226-1e7a2500-42a1-11e9-87a2-305794377a1a.png">

[Check out the Vega-Lite schema in the editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkAB7YADKqgBPbACYAvur2EI4uWO5e2AAsAXaGIb4ekN5YAGwxQQ7OUYnJaYFB8ak5UekFWUURWP759oWRxWGlteU+Da5NceXhSb5+sQC6GqWQGABOANZWjniehMhWkBJK84mE3IxKeFZ4o+bDyErw3Job1FOx5Q6xRgBmjMhimgsuiTNzCwCOrOibzDqMVEgsQ6PX01ygdweTxwPVes3mMK+PzwfxRgOBNSg3FGmmQoymxlM5isSlYYjEfQgfT6QA)

**Comment by domoritz** [comment]
I like the idea of a path mark.

**Comment by kanitw** [comment]
Actually path in ggplot is an open-path.  I'm not sure if there is a common use case for closed path in data analysis though.

**Comment by g3o2** [comment]
Would a `path` not also allow variable strokeWidth, which `line` does not?

**Comment by domoritz** [comment]
I don't think we want a closed path. Instead, path would just disable ordering.

**Comment by kanitw** [comment]
> I don't think we want a closed path. Instead, path would just disable ordering.

If that's the case, I'd refrain from adding it since `{mark: 'line', order: null}` seems fine for now.  If a lot of people are asking for this, I might re-consider.

**Comment by jwoLondon** [comment]
For simple open lines, @kanitw 's solution of a null ordering makes sense to me. For closed polygons and complex polygons (rings, islands, discount polygons etc.), the geoJson spec already provides a great deal of flexibility. I wonder if there might be a way of integrating geoJson specs into the standard Cartesian space of Vega-Lite (therefore allowing axes to be displayed, scales to be configured and shared across layers etc.).

My understanding is that while the [GeoJson format](https://tools.ietf.org/html/rfc7946#section-3.1.1) permits locations to use eastings/northings (i.e. not longitude/latitude), Vega-Lite will assume coordinates are geographic and will therefore project accordingly and not allow integration with 'normal' Cartesian coordinates. One possible solution might be to allow a special projection option of `"projection { type": "cartesian" }` that treats the coordinates in the GeoJSON as Cartesian values without reprojecting. That way you get all the benefits of complex geometry specification of geoJson with virtually no expansion of the Vega-Lite API.

**Comment by mattijn** [comment]
In my understanding there is already a projection that uses a cartesian-like projection, namely `"projection { type": "identity" }`:

> The null projection represents the identity transformation: the input geometry is not projected and is instead rendered directly in raw coordinates. This can be useful for fast rendering of pre-projected geometry, or for fast rendering of the equirectangular projection.
[source d3-geo](https://github.com/d3/d3-geo#path_projection)

Some further investigation is still required though, since this `identity` projection has some options in d3, namely: 
`identity.reflectX`:

> If reflect is specified, sets whether or not the x-dimension is reflected (negated) in the output.

`identity.reflectY`:

> If reflect is specified, sets whether or not the y-dimension is reflected (negated) in the output. If reflect is not specified, returns true if y-reflection is enabled, which defaults to false. This is especially useful for transforming from standard spatial reference systems, which treat positive y as pointing up, to display coordinate systems such as Canvas and SVG, which treat positive y as pointing down.
[source d3-geo#geoIdentity](https://github.com/d3/d3-geo#geoIdentity)

I don't know if these options can be set from within the Vega-lite spec. Probably better to test first within Vega spec.

Here a [vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDuCWAmAXAFpAXGAzABmwGnCngENFj0xQIJIA7YgWwFMLIHiAHAfRLMgOpQAZgHsATu0QVgkRAE8OLDJABWAZxG1+UDmJGKx81kKakArmKZrIAX0I2BUdmIDWrAOZMRa5JxaPIXREVJgBjRFhNaVkFJSgEJloIowdCSETQkXhYWndpQhpMgBtxaKFYJiL4ViCDCKsAOnpmbRjFVloRBhziIttHGkQRESKIjgoAbRlyyurlWqZDCrUmxn8oeXblTu76PpsAXXsA3mI1JkRrDCpqNk4eUnJrgtvNuMgAMVNECyYAYRGRTCESiA1uJnMliuYAmL0EN0Egja7y+kP8cMRgT0dWW0Wa7xEACMQuEwABGfoYpGeLoXMRyfKIpkbWKsAAKIzk7lBVMxmXE2XoiCskwmE3wYGwBzwMIlACYpTKJgqZQrpTCVZL1eKZVKDkdmdQ7IbUoaEczkaxUT9LPxeTQFksRdc6GtWESSYgwHLKYaaDTmIh6Yy-YNWcoOUUuTzQ4VhmJBaRnTCxQA2VMygDs2vTMswmG1AE4yXmC0ri1mcxmwNn9fawMbmabmeamZblNbfnbQ1j9It6tCZPj3cTgVhfX7IAG6QznrGWVsoJHo1owYbIPyEz1hdCxRMACwSgCsiphqYlmdPEwAHMer4eZSf9Qa-Y2mW-qC+II27DYgA) spec to test, but as can be seen, a triangle is a triangle and a rectangle is a rectangle:
<img width="363" alt="Screenshot 2019-03-13 at 18 59 45" src="https://user-images.githubusercontent.com/5186265/54302983-3f54ba00-45c2-11e9-8e91-7618309f205a.png">

**Comment by mattijn** [comment]
That seems to _just_ work, add: `"projection": {"type": "identity", "reflectY": true},` and one can combine it with a line layer.

The axis are not really shared though, as the `[0,0]` of the square is not placed on the `[0,0]` point of the line.
<img width="313" alt="Screenshot 2019-03-13 at 20 43 52" src="https://user-images.githubusercontent.com/5186265/54309604-c446d000-45d0-11e9-8a96-fac47c070ab3.png">
But maybe someone else knows more. Vega-Lite spec in [editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEA2CGCeBTATpAXGA2uCZS90gBNYAXWdPSAO1gFtFKYBLaxAfRPMgF8AaHAUh1YyANZNorRgIIRIiagGMA9kVYBzSvjnyAHtsgAzZomhEmFPlFLwADowyQAjgFdY1Us3JeAbo35BOUh4QxMzCycAI0hrSFsHJjcPLx9mf15ZXShVaBVUDGBjU3MmJVibe0coahU6VlhoTKChUhUVaC87Skwi8NKncriE6po6hqaeAF0WsB4g-gIgnSEuCkLZ+VoGJhE7TjIrTagjfJFSQxGmACsAZxVqCsg7ZBUHZFsmI0QyV2REW68WaBXTCUQSQrxKpMDSIFS3AAWsEScRM0CaTlIyA8tzsokUFxBwReKmuiCUXgel2hTmYRAJ3lCcX+Rmg5NIAE1KFjXIgiUJFKp1NQtBtslBbliVGJqn0SpEoCT3l4AQA6bYySqJJy1eq0SZZUGS14ygDqdNICMMvkavMoAGZ+cE2h0uj05REmEqUCrbur6JqodqauN9bwZrp5gQo2ApllIP97tAMpC2bDqAqirl8kxWPSHBmCbwicRDrdEKRAWLCFI2AduBhsLoiuswAAGOIxDAdnKSaTNZuQVsAJgALJ3KABWSdxcpOWsBQ24FsOgBsE4wo-ts77bAHchXm4AHBuwABOACMO-n-adEEP5-XUC7YCPV97N73d6oI5nz6n24flAC77gQD6Tj2kAvheZ7XsBt5LveQ6UAA7H+UGUEeKFwSwX6IT+lAXm2kEvpOw44SBMYQHGQRgvsazaLMQajAAYj8pB-IgADCHRshSzBUvhxjsZxVZYMcKzZMxTBsb8-yxMc8jeh8phiUUGpMLcyTyd+QiwnUFbIKE1bivIVxOAACh08AaIJimEKo+TCmQAI9JgmA9m2cZYD2w5edYmB+dYfneYFnmheFUwRqZVFyLpeD2dJTiyRx8n4UIym+oYGlOP8FIeBobKgVJ+kMFixkJaZhDmVAVnQDZdlVfIjnIM5pCuY27kQdYKGhd1YAhQFRG+f5WDDT1fU9r1UX2bF0bpZVplJVAKWcQpVXPK8yqqdlAZMFizAFUV8XyKVhkVZJ4rLZAdUNY8C1CC1bUdVg7mjj2EGhauU2jZgR4fb973WJ9M1VXNuDg9FEAxvMPBAA)

**Comment by kanitw** [comment]
The axes are not shared as the geoshape layer don't have x/y scales.  I don't think there is a way to pass a path through a scale in Vega yet.

In any case, the discussion here is now a bit off from the original topic (about "path" mark), which I don't think we gonna do (for now).  

Thus, I'll close this issue.  Feel free to re-open if you have a good argument for a path mark.  

If you have a different specific feature request, please create a new issue. :)
