### ISSUE TITLE
x/yOffset channel

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4703]
Follow previous conversation to support jittering/dodge in #396, I'm creating this new issue to propose that `x/yOffset` channel is the solution. 
(The old issue is getting too long). 

Here are a few demonstrative use cases:

## Grouped Bar 

![image](https://user-images.githubusercontent.com/111269/54079476-f9ca8100-4291-11e9-988f-7dc12b30eaaf.png)

To replicate a group bar chart like [this one in Vega](https://vega.github.io/editor/#/examples/vega/grouped-bar-chart) (ignoring the text for now), the syntax should be the following:

```js
{
  data: ..., // same as the vega example
  mark: 'bar', 
  encoding: {
     x: {field: "value", type: "quantitative"},
     y: {field: "category", type: "nominal"},
     yOffset: {field: "position", type: "nominal"},
     color: {field: "position", type: "nominal"}
  } 
}
```

Basically yOffset can have its own scale _without_ an axis. The scale will be a band scale by default for nominal. 

This is better than allowing `row`/`column` to have `axis` as the row and column encoding should only have `header` as its guide. This way, the types for all channels (row/column, x/y, x/yOffset) have consistent types. 

To determine the default range for y and yOffset, yOffset could just use the default rangeStep. When there is `yOffset` encoding, y-encoding then uses a formula to calculate its rangeStep from yOffset's padding, cardinality, and rangeStep.  
Users can still override one or both of the scale's range. 

## Jittering

![image](https://user-images.githubusercontent.com/111269/54079551-74e06700-4293-11e9-988d-8c43ad7acdca.png)

[Vega Spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAyom4B3WGBbIw65ABt0O2bERaw7ZHhPJkMsMfWwyISmyOpg6DLKFihgMqyo7FRh3ABmYPAAnraMkaHmrLA51BaM8ADWYBjqZbB0CkqQ6Kx43IUAXsjYUIToyvUQkD3KykVdoooDJozKLF0ATAAMCxNQsHhZnfrwdrb9Kg6YOADaShDAkDLoqJur3Kzq2wD6CwpQ97v6ygek8OgBktI5PIoCluOoMHguud1oQbpApLJIABfYGQPDqCKwUHgrpHaEZWFdSDY1CseyvSDIAAehHURIxkW4qAAFABKCnoWD0iLKJnIgC6SJASn5K0ghWol1sXOOpzA50u1yJGUeayCFIo6FsrBuABYFii5aAICaoIq4ShGNR8HtTZBWIQvng4ewebAettmbyMDlmQByDJ+1l0Ww+agsYEARmBCzoolZYAAVGAVWrCJA5UKIKKGlUarijXKBuaiXmuSs7TC4bAMgluLsKybxetQ7jBtwcpCc6aBil1HycOcnYdbvcni9DT2oD54NxVFCi02HU6bsap03uB7mBkoZBNdqbrGAOyT9e9xi2D5gE5n01r29N51rIlO+JHAA6kAAEmDAsEvOon78mAAC8YGxGSthgAAPtBYCMLAABy6CIV6Dhvp+P4BEEISAZA-Lso2D57lqOpdHEl6LlOp4Puc+5kfo6KYj0NgyJCWa3t2t7Nv2ZQ3DeD7ylR65omokKfOhqAft+v44QBQGgeBFFQbB8FIShaF4BhMnYf+oRAYRwlTiRB7kZBRkmjRt50aRcIAMS6vAR4ABzoM5yIWVxZ5otw9Y6Omg4WQMEpSkSwCYbJel4TgJIOJp2lYX+uFAcCn6fqyqWQAAwlkOSqAEn44H6foANSvlJn45dkuQFfhSIZg+VnGVSu4IFqcItaiKSMHYfT6IlcmhMiRE9pAO6DuKvytvoO5dT1th9VAVV5XkFKpCkgTifKk3tcqADyKQbR4FLdb13KMqgyIcdRi7XWAHFcTtoYytehbGSW+idYuaIEnC1XIH8tpNt66A5Luw5EtIY7IM8J3zYtOlJQBw3fQy1D8cs20hVqRJTDMiACiNFylDc6I6kTHT9l0ZPIJmjb3k2H1QBkB1HZCRNVkS-2A0TINgxNEP6FDDwwy8c1nfoDLeijxlo-x5zY1ekAALRgLGupJimqrOoQYCkGAczDVjVqhfo6ua6mOt6wbhPfTIJPU+o5PfZT3COzqdNvaNTNjUDAyc-owSdn7KhMqDejbYLo4i7D4sLUSy01eWtzqFtNNNVAcutTrrUmzjM3a+qSIZ4MvQjDI1BdLGoiZiKYroFSagFne31tdNUBfcZYI9WxRLsNwBB8kT1CaItKRaoEHPMO3iODXSRP2O4tgAGLas47vIAv6BL3tST2AFFhO5v306OUWV3L3E2K0S2wXsyeMsKQ+rsiXbQrS1OCRp7LfGW3HUh5AbuPgtqQH7oPS6w9R4GCmnCWa30R7TA3lPM+F8toKzzkrW+th77TEfs-GWo0+YR3HtKY+xlF52BeiQye30MBUgAKJUmdJfNWRNUA5EYcwraywT6lHzDFCeZDRpv1yB-NW38TQM2CjA5UACgEsMgKGFI7N4Gjy6NQoRlZp5wkTvlcs30KG2F3qEfeSCXbvy6F-U0D0QBIiAA)

With this offset channel, we can do jittering using the following spec. 

```js
{
  "data": {"url": "data/cars.json"},
  "transform": [{calculate: "random()", as: "random"}],
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Cylinders", "type": "ordinal"},
    "yOffset": {"field": "random", "type": "quantitative"}
  }
}
```

The range of yOffset linear scale should be within the boundary of the y-scale's rangeStep.  For example, we could do `[- (1 -  yPaddingInner) * rangeStep / 2, (1 -  yPaddingInner) * rangeStep / 2]` (simply +/- `(1 -  yPaddingInner) * rangeStep / 2`) by default.  

We can later add syntactic sugar / macro to make jitter even more convenient, but this should demonstrate that offset is a general building blocks.

A macro could be just as simple as  `"yOffset": {"random": true}` (which I think is more straightforward for readers than adding a jargon like "jitter"). 

In any case, the first PR would focus on the xOffset/yOffset channel first, a macro can come later. 

## Conditional Offset for Bar Labeling

![image](https://user-images.githubusercontent.com/111269/54079529-f683c500-4292-11e9-875f-75d9d7c76fb3.png)

```js
{
  data: ...,
  encoding: {
     x: ...
     y: ...
  },
  layer: [
    {mark: 'bar'}
    {
      mark: 'text',
      encoding: {
      	yOffset: {
		  condition: {
			test: {field: "y_field", gte: 0},
            value: 10
          },
          value: -10
        },
        text: ...
      }
    }
  ]
}
```

## Nudge

In #396, we also discuss about nudge. 

However, we already have `xOffset/yOffset` as mark definition properties. So [nudge](https://ggplot2.tidyverse.org/reference/position_nudge.html) is already supported.  See https://vega.github.io/vega-lite/docs/mark.html#offset.

cc: @domoritz @jheer @arvind -- let me know what you think.

Grouped bar is a very common chart that we don't do well. I want to provide better support for it.

**Comment by kanitw** [comment]
Adding a bit more info about possible syntactic sugar: 

A macro for jittering could be just as simple as  `"yOffset": {"random": true}` (which I think is more straightforward for readers than adding a jargon like "jitter").

**Comment by jheer** [comment]
Thanks for starting this! I’ll think more about this design. What you describe with labels above is already supported (in Vega, not Vega-Lite) using the `dx` and `dy` channels, do that might be an alternative naming scheme.

**Comment by kanitw** [comment]
FYI, we intentionally name it `xOffset` and `yOffset` rather than `dx` / `dy` because `dx` and `dy` for text in Vega shift text on a rotated plane. For example, I duplicate text and [set angle = 45, dx=5 in this Vega plot](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10AmAAwe7uZI2r47l4+kLB4AJ4ANjo4kPDIkZHG9gboeJg4ANpKEKAQ+VAy6KgxUNKsAE7xAPoeyQVQlUmxqemk8OgVsJLScj4FkABm3BUYeLrAkBGEpZBSspAAvv35UxXoMrDDo7rZDfmT07PbqKyRmPJQyAAehBW6kK2sqHQA8hX+lpkeALoKyrAHu9PjIAJIyZiMdBJRY5fI-OGwiA-EIYCoAa0BWTheQakCKJQeaMx9QGRweeBu4xW9jCUVKmSmVMgKLh9kGFW4qAmjzSGTK3EqNTqyzZVxk8G4BlKuP2kFYhFaMrFA0GjESuxVDVl+zxlLCDyeqEyAB1IAAJEawZCEbgOZAVM0-MAAXjdYBkZ0iYAAPj6wIxYAA5dBBgAURtNFqtNrtDqdAEpff7I2aALLq5CwaozCrVADi0MisidrvdnsSyYDwdDEbSzyjGei2dzBaLJZZCdJuoGFGhrFKFciWoKop7BUmCGhs0lxfulyGjASRliwKYciR49Z46gam4kTwjEIExHqw01CKzSgwDNlq6sftjt0JzSdbwDdvMdtj6dlzNZoTP9ICbLMcwdNtEg7HAXzwN8P2AzMW3AwtIJkX8wH-SBAIwyA10sM0cAAckIgBqVNcI+dd0LNPCwQhQ9oQIsBiLI+tjRoyjLHBSFGJZRZIFPMdx0ga4eSnaIHlEhc1WXB472tb8HSWGk8XCMSOgk2I1OkpdIhXKAQKQvMUOLDcVLJZkcEnfxLweFjyNo7iGMiJ1lNPSBoRsnk+0iAcHniGRKXuISew8qxNLASYfL8nAABZRE3fZEvyZLlh1ewCVmYk3EBFSpnCGYKWZPK6QixlKWucZtzxDkuR5Vp+VCQUqmQWo3LlZAJSlZVQoVJUTx3RcNWxHdclPCyDRaNio3kh94xZMsXQ9L0q0DENw3I2bFKfH4kz9MByMMsDjPbNCFrdJah1WmsNum9NEOOiDTMTbtBuiwcvXGsAQvHScNJnfcRn+RdZNXTiN1ParQr3A8jwG0bQhs6EHhvaN722piYLg9i0YUuMdqAgCgKO1sTKgsAscOh7SdO6jICJnDaKY+y7ookE6cc+ioRc3QWffHHOZ4nmfn4wTzNWUSrNCf7JOBmS9Lkr98fa4S1Kl8TZm0qB5f0hDm0esmzPcirxnVpGr0gPn4MF5zXJ+uVPIvbz+xnTqgpV0KNmoCKopd3R4vtvEDElyLIHemxktHMVUqUarpenLEwD2A4xXxYpZik1PyViSJLGQTpXqgAwuXQSx6r5B5yhatqdNBqAtuVwPIHWKwGW8UPz1s2InBcRAlih1YIXiXQ8AqAc8u0TkR7H5BERWdLCnTh5tKzgrZlzmR8-nVPi4wMupYayvmuFOXdN1knkNOj3Vhb6gGWsi9kdiFB-ECZYwF+PKh9KUfx9TyfuDTwHHPHEqdMr+UBtvOU2coAjAsLZPKu9S5yAPhXWIVcT61wVmDEEwNpAVFNmAX+yAm63xnGkGgIwV5yksEFW05xKQPEQPAJIiJY4hHQNcLMmoJypw1rLPKIwlyBQeOwbgBA6p5WoB8fSgxoTWjyoePAEVcZzSgXic47AEgADFfKwD7jgYheVNEJFeFQCo5xjyGJnooxg8B0QAGFBQiLNo-C28R1Rhh7iwUgsUPBdibpoSw0oQ4AEYQG8LlPw2Imc5RCLdqI8RahuRSJkQAZRllpQukBpHOCAcgWx9inGsBcR3c2-k-CRC8c4HxfiAmIJLvvCm8iCmpxMZEROciOmtLlBga4ABRSqCScDeFTqgSwgzKSlNGdAuxJJoItInsEm4ugPARJTlEzJUBqF4niaUyA0RBjUlTrk2Riys7MBURfE6qFsntLMQ6Sx+TCmOOcYQh+XcoAeKqS-AIeBfH+OvvYIJMgQm6HCaOeefCtmQB2QMPZhCDnICOdk05GTpwCJOTI55FyilvLEuU2I3ywy-PwAC+pO9GkoOad04x6AtEdOfOc3pnDJnDI-nlcZMg2XTJeZ05leIQVgpGWw5EIRoh31BYnZOY05RqmGl8yBqL1gWDdgAGU6tQVwrjPlxHOKgQgJK-B-MuAANlipcTwgKm5KJUbRbJnVJTSjEuEVAYjGVSz6hQsSiB0CFSluHdBABHVgnQdCLAjTHZEIBFhAA):

![image](https://user-images.githubusercontent.com/111269/54079853-7e6ccd80-4299-11e9-9eef-dad132164f35.png)


We want this xOffset/yOffset to be always parallel to x/y (and we can simply uses `offset` in Vega like this):

```
// Vega output
x: {scale: 'x', field: ..., offset: {scale: 'xOffset', field: ...}}
```

Note that, unlike Vega, `xOffset` shouldn't be an `offset` property in the Vega-Lite `x` channel as it's breaking the encoding structure in VL namely that one channel should have one field (see https://github.com/vega/vega-lite/issues/396#issuecomment-362867869).

**Comment by kanitw** [comment]
With this setup, users and shift text along the original xy-plane with xOffset/yOffset and along the rotated plane with dx/dy.

**Comment by eibanez** [comment]
The proposed specification for grouped bar looks perfect! Is the intention to have other marks also support x/yOffset? I assume so, as that would make it very easy to support the bar+label example from Vega, right?

**Comment by domoritz** [comment]
Yes, that's the plan.

**Comment by davidanthoff** [comment]
I'd love to see this feature, I was just trying to jitter some errorbars for a plot, and I think for now it is back to ggplot2 ;) The proposal here seems perfect for the use-case I'm trying to solve right now.

**Comment by domoritz** [comment]
We need to bribe @kanitw to finish https://github.com/vega/vega-lite/pull/4969 ;-)

**Comment by davidanthoff** [comment]
How can he be bribed? I'm all ears :)

**Comment by joelostblom** [comment]
I am also really looking forward to this feature being available in vega-lite and altair as it will make it much easier for me  to use these libraries for teaching. Thank you for working on it @kanitw !

**Comment by firasm** [comment]
If anyone comes across this issue looking for a temporary fix while this issue is still outstanding, here's the closest thing I was able to do riffing on the "grouped bar chart" example^:

```
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar().encode(
    alt.X('year:O', axis=None),#axis=alt.Axis(title=None, labels=False, ticks=False)),
    alt.Y('sum(yield):Q', axis=alt.Axis(grid=True)),
    alt.Facet('site:N',title="Facet title Here",),
    color='year:N',
).properties(height=150, width=80).configure_view(
    stroke='transparent'
).configure_scale(bandPaddingInner=0,
                  bandPaddingOuter=0.1,
).configure_header(labelOrient='bottom',
                   labelPadding = 3).configure_facet(spacing=5
)
```

![visualization](https://user-images.githubusercontent.com/2507459/95175368-3b722500-0770-11eb-8377-cd8547bd4845.png)

Other than the break in the x-axis (which I'm sure some enterprising Altair expert can tweak that so the gap is 0 and it looks like a single x-axis) this at least, accomplishes one of the goals. 

^ Mostly, I didn't want to just comment to add a +1 comment on this issue as I too, am waiting for this as I intend to teach Altair again to my students this year.

**Comment by joelostblom** [comment]
For the jittering implementation, could it be made flexible to support jittering within the extent of a KDE in addition to a uniform distribution? This would allow to make density/violin point/scatter plots which are both very informative and solve many of the issues with violin, swarm, and stripplots.

![image](https://user-images.githubusercontent.com/4560057/106965096-f945f980-66f7-11eb-88b7-f7c1462edd05.png)

**Comment by danr** [comment]
I wrote a function that fixues up the breaks on the axis by manipulating the svg dom. It could be a starting point if someone needs to do something similar:
https://github.com/NBISweden/encam/blob/cdb5bf695f8498c14aa7280a476096faa99b7951/frontend/src/Vega/EmbedInner.tsx#L59-L113

**Comment by joelostblom** [comment]
[They are also interested in this for the new d3-based Plot library](https://github.com/observablehq/plot/issues/164), maybe there is some common groundwork that can be shared?

**Comment by smashmirrorcardboardface** [comment]
it would be lovely to get this implemented, esp. with deneb using vega-lite in PBI.  the PBI clustered charts just don't cut it.
please, @kanitw - finish #4969 :)

**Comment by wylieconlon** [comment]
Could we use `xOffset` with a temporal or quantitative X axis? While it might not work for all mark types, it would make sense for bar charts using discrete `timeUnit` or `bin` options. My impression is that this is a difficult request [due to the issues with converting timeUnit into discrete values](https://github.com/vega/vega-lite/issues/6593), but it would be my main use case for an offset channel.

**Comment by kanitw** [comment]
Will be fixed in the pending https://github.com/vega/vega-lite/pull/7684.

**Comment by kanitw** [comment]
> Could we use xOffset with a temporal or quantitative X axis? 

No, I think breaking continuous scales into sub discrete scale seems weird. 

However, in #7684, you can make quantitative / time field use discrete scale (by casting them into ordinal), which will still allow grouped bar for such use cases. 

cc: @wylieconlon

**Comment by kanitw** [comment]
> For the jittering implementation, could it be made flexible to support jittering within the extent of a KDE in addition to a uniform distribution? 

@joelostblom  I don't think think this is feasible in Vega yet, and seems to add much more complexity for the feature. So I don't think that's within the scope of this issue.
