### ISSUE TITLE
Overview and Detail example is broken

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4712]
- Go to https://vega.github.io/vega-lite/examples/interactive_overview_detail.html
- Visualization is missing...
- Browser console has error message:

```
Uncaught TypeError: (void 0) is not a function
    at RG (bundle.js:22)
    at zG (bundle.js:22)
    at PG (bundle.js:22)
    at window.onload (interactive_overview_detail.html:109)
```

**Comment by clemens-tolboom** [comment]
### Broken

- https://vega.github.io/vega-lite/docs/concat.html#example
- https://vega.github.io/vega-lite/docs/concat.html#example-1 (doh)

### Working

- https://vega.github.io/vega-lite/tutorials/getting_started.html
- https://vega.github.io/vega-lite/docs/aggregate.html

**Comment by clemens-tolboom** [comment]
Could it be these broken examples need release v3.0.0-rc15?

**Comment by domoritz** [comment]
It works in the editor so I suppose an update might fix it. Will investigate once we make a new release.

**Comment by jwoLondon** [comment]
I am finding a whole host of examples that use selections are now not working with V.3.0.0-rc15 when they worked with rc14. The console reports the error:

    Error: Cycle detected in dataflow graph.
    at i (vega@5:1)
    at OD.qr.rerank (vega@5:1)
    at OD.qr.connect (vega@5:1)
    at Mr (vega@5:1)
    at OD.qr.on (vega@5:1)
    at _D.update (vega@5:1)
    at gD (vega@5:1)
    at vega@5:1
    at Array.forEach (<anonymous>)
    at vD (vega@5:1)

**Comment by kanitw** [comment]
It's good now!
