### ISSUE TITLE
Reset a selection to a specified state

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4715]
While trying out this `init` feature with a single select option, it seems the selected `init` parameter is lifted upon clicking in the chart.

See following animated gif:
![init_click](https://user-images.githubusercontent.com/5186265/54207219-10fbaf80-44da-11e9-9f34-20ffb705cbf6.gif)

Click [here ](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KABsAhgE8CAJ1IBtMRFAR1USpOqTSOeJIC2BUpABGkgM7JLAfS07IIlesiHJcgNanxyeCdENCEgCeDhKP3QsNSDguHFYBWiXWMhqaQAHEyxIeFhDP0lxSEDY1xQCcUpTAHVteUsdeGrSsqhLaCLssg7OY1N8OSobJ1aytORqcW7IOuoGpsowRUMAOQBBAAUAXUgU9Wc2tNhYcWpkDKUcdKzTPIKDYvZICqra+rlGyWanbbGNSAADz0+wBNxmAEcAK7fc46c64AKg8qEN45ABKyAAVgZELhYPISsjgh0unpIAAveSwUiIIqWAiHNpQOHTUyYnGSPEEuTLQx8AD0ll2yKZqWkIOZLMykJh8Dh2mQiKJUpeqOqOQAWgRiB8vj9-kFIKS2dFKdTafTGYawZNTVBtbr5p9FnyNjs9m1BPsxa4GdNoOcEJLxgBlAAq63DAFVQyGjuDTNZ4Kg2TbXH5JuSvtQoZZTBFoDxRsSoK9KPmsIpjfC85A-qXzH4NWQ-Bkobwcv6CIGSlBYBkg-BK8tIAPQn3IIXi9tvV6fYa0nJvpZEIlDFc1WdCWbu4HkMGchGo7GnIJti5fTEIPsp9pdGaDP0chlYH5qLY97xfcF3F5yYmGCQK+74lFu0wttQchQtat6hOEkTxkawLJKqgFQNCsKTIqyrpsE5bstiuL4oSorppAEqocyaQyqYmHythCJIqqBFajqRB6osnplD+frIFSSGpLgRQwaQACsTBkciMCnIkglGsJ4iiTkcgENUoptD6QSXmIDbBA4VgENQI7XlAIHyp+lQ9p2yw4I6HHOvqLYMM8HLETypAAGwAIwABzeQAdL555jOYVg2PY95KPspkAnMCzfC23nkW5XIkUkYA+f5QXkfZnGJaQgXeZ55E5nWOTTrwC4xdJ8UugVWDJdJqXcjumUsGw0l5Y5XGNQFfmlbWI5TsgRZVbEvGxa4dVOYVKVEWlHlYMwLC5ex+U-H1DBNUcZXDZV3EaJNtUbUl82cq1GUAEwdWtToJZtYCBWJO3jHtBajcW1WxFNwQzb1T3ne5bWeatXXrT1DVPQFADsMODdo5WaJ941BMdRz-VDz1A4tbXeVdDAMDD-V3Q5D1Jf1JXSe9FUo4dByGr9UCY492PNQtl2FR1nVHN15OFQFL0I7m+1099QRM7Mp0C2JOOc1gvm3eD931azAWeQAnMLSMjWN9MQOj4wsxTsvsxd6VeUrvMQ-zfW+Vd2ui3r4saJLxsy3LFvLVb4x86rLZXQFTB8I7H3OxNjMnZDaum0cLVe2AfAw75DABSHytk-7pCB0wLnU0NYdfRHNUY9LfWx+M8dLWAN1g9bKuzVggfFaHtPh2jkel9HJue9XoM877NtZ03AUMOnu0F23RcdyXRtlzXvcg3Xg8NwDVMT4jTvT0dndz932eLxl3ka5548r5njdgGJQd5xvIuF6jO+z6k7tN4f2c+6kfuX9fTCvakNNkbtyfj9KOtsF5m2BtdXyYkNZp1JvPVOudW5AO3gzZ+RpX4QLjhzBOK0B5fyHpfQOvl15vUnqgx+6DQFd3AQ7SBuMMr9wIUab+ANA5ExQbrNBBtd4v3nvQnB5tq6K2XoQ1eUNA58DPgAih3CqG8IwXFAR79GrcwQfvEeV0ZFGkAfI-WYBDb8M0dgyuuDq7eW8gIVOOiARsMkTfLhB0XbqDdiohh8snoCDEawohANArJycWLYuNC950NUU9ZhGjwGBQYBXWRm8H4GKMZg9xQioGFVESwuxfisYBSumQhJ98p4KMMXw1JJjA7xKNFXNqDBPK+T4AFLWGd56eUcfnRJJTknlOUZUwWESXpiWJrY1w9jHq-1vuQrplCelKOmgIgZHiE7DI1nA0ZwRxnOQ6XfHWziQkSzAcPGuSz0mMMtj4nJEjHpNJhhs9ocj9kz1CcYuhpyzHCJBp5O58DWkmKacgzpxTZkuNUEc4h7zUi1Iylk6JxySEtN2VvUpKS+lvOqQCaFXNP6+OuQHZpgjpnAv0aC7A4L2GQpqeYvG3jsljNyY9DhvkgnAOoYc2h8LKWYupUfKJfy3neSmUUvZwTnnsrCZyjFrgsWNRhkwCSo84UQsBUipJpK3H9KlcEGVT1YX8uOYFDWWqHkzJJQc125Kob3MgDqmGGs+DtPhvqy+7SVVEpFayxRLyKngOtTqvV9cL4A2vjAllPCynzL+vPP1PLSD+RPrDJVwadnuuRXM71aLjkxs+RlDWDBFYk2dQDJBQrdGPNFSA8Vrys0RO8uootVqgrWr0U8ytFqOWX2zRkxqtKk2NpbkCj14bUULP+bWseBT8l9puSm4Vab1WWpubWvlgbFmkLDSi3po7fW1oDefRZ3yN3pqrT6rNXLpWxqwPasSJDp0tldaWgELaK1svbRKzt57tWXqevW1dJjf6FLLaa1tr7XGLpbE041Nrv11qYFdQKhLxFBqhpMo9C6O0A0g7W7yycAl3sYLOoDxKQNepPZmj9UGdVWJxVc5DM67lofNWBjDjbKMwZXfu-5irB3zqY2CljM62M5syTR+leL+D5MRamtVfGyUCecth3O18nV-vAQ+xjYq33Vsvo+i9wnGrwYYIHKTSH56oZ4zJzTzH33Ftrb2htj1U5iWZRZ7p6GbNQ101+-TT181XV8oW1TxyS0abbdZ7TtnlkWI46ZrjvkTNEaHZuyNzNEG7tE5shlEHYYudVW52TGrwFObsywVOKnONqcI0+8tnqI0Zu3cFz9UAqP1NITlBzLZzN5ZBQV8DBGhPdsiRlh0WWCOeS8ya4jL7SNadPTppr0GfN+WG5ALZBG+BQefbVkdUb-21rEnwbagWKvHPU65nrVn+MeYmculba2sDKdC6Bq7EWUO1rtUZ-DD2qt+hq8Ordu3wEDfOY1PdsWgdB2bX95L9XAcGoiVlQKuWTuXyKoB6rprxzwGPbN8j-iEd3dG31Aa52xxZGx+517rMIn4K+9DbaXCsc4-C3N-HUW2q1zpZl8T5d-6JeGkzynrOsYE65yNnn0M4aM-J8zl7wuY61oJkTY74ODWU2lxOIXeO8nA88bBy5Ym6MU3zRrinvX5Me3ZzCwnEvAqeUQ-z0wgvzfXZ7lbi5YvVtE+hvbU3su5Ou8t2czxtOOvZ0h37rXDXUcLZ1UnFOvygvKomzWTHMuo9w5j7rhOnO6fN3R79tPmuXdU7d8HhO-c8+jyh0Xs3l2A+l4Pu7rAlew9YCaYKyPJf5cBwiRrK65XVcfrdXOp36fu-a8ZRE3PbeTnI9HzkZ39fCvwppzbo34eC8kjkUvsLcvJ+9+b+1A33ON8jwZ6T3fz2G896b+XkR6-FnaK78vvrb8j-689-dk5+MX975vwfnfh8oNnWncmVlXiPo7ovuPq-hbu-vfjSo-iYgEptjvjAf-ivsQrdifuLmfvTjXsSlfjNizoAfAcASDrqkgTEvklvpNjrEQXVmRtHhStnn3DgV7hLkgg7hjoQegdfpgSwdPlQWemJCnnogwTtqlpqmvuwd-h3gljwfQXwcQfvswQ4qwW1Adj8lBnIT9tvrXv7gIeoaLl-t7sZvPlAf2MoYwbjmoYyrHt+mDringYHHan-vwW-ichoUfL+ijhSp5LQanrwcXrAYHiPN4YVPZknhSg6u4SoQAXYfihEY1DFs4YskwBYYoQLtYZIVLNIR-gERrHbhAWIWgSERgZ4VUulrId7oaqUQYRnlITukfq3tEZ5jlnETYSQYkfwEITUZwWnHzlkWPuUR4XAYnBEnwJYsVrPiFpfjkQDk0TWkfqHm0TOqGvMaMfEUYUui0cIRRgQUoVsV0aoZnphhEk4bRtGpJp0bkVgl2hQZ-nTh3oPpYWTscXcdGthkak0pkYbtcZAcMdAR8YsXkc0QgUfFEX4Q4nmrcaCfcdgaYRLoHKfHCSlmCcsRCSJv0S4aPH8focEXXhUeMVhnsUiXgdfIEeIQseifcQ4UthrDDDMWsZ1noXQdkSCbSdcckTXPscmsHGibDksRRjIeSYgoLEMYXoSYYZ4aSViS3nye0UwK8UCVYZyUKRiSKS0d5GJNfNat-nMd1u8USWMWEYnPSYNpcf8VxjDFSWUSadsbKRaY8b4UPphurIKUwWcaxiVjidcfUdKY0Zqe6TycVIqTOjqZ6bYd6YJu9jenAinroYCVKUcQ6ScQkTGdlqGVaafl8ZsWmZ8SYinlRllB6bPmdkaRIfCWlkfjPiyeJEFPieySMQWdWUWaKXTtfPBlGd0ZmYwDTgwEaontCRMmyUEamTKeMcWd+qkVcUWerHaQ0RPj0ctBceGdsgUj2accKZFvKWAIyQmjod7oadJsCa2Vye2R-q6WkfOXBluRmTuZ5r6WKXFgGROUGVgtOUtrOdab6mWZWTSRqZ+dUS+X+XEveTsdsjyXwBrDAtxvWS3mOdSeqV6Y+Y5s6SHuuV5EhfaZOWacyeQZ4j+bmf+mnNwSmRyeeUBeKTyQ0oOf+SOaycmQSe+cuX2ctBhQnDmbgeKYEvmXhY3hxaGdeXOUVqPAoRRS2QJbfkJc+XTqnFdKgUuaEYJWAARVCjBrAnDPBYxQRsxc2WedJaQWpZxdFlhRxfpeOZRUZSuSZdmeZeafFhBZ4bRThkwO1ghZlDhcpcSWaTydxRwRSdXs5eMTyUasfCrjeRDpZchVRahcGW9leQ5anCfCFX5XJbMerG+dZR+WZoifJTpQvmqXFdGWhZ1iBQVVdBJSxTlWxWVQ2f5aIcTJKSRZVjFbhblaRcJQ5ZSSqZJYZZ1RDqGVCW6Sht5YGXVQlaOcNT1eNaxSpTJVfKZXjMRTxfObaWlapdfPZX6fOQEZtYtYEVRoKodh5bpYhe1T5aaapUdTBiNVFccpSU2VZVJYNadvlbPtfCTgBShaVVNfeu9jDAPsOaNaOZdRNQtcZbdUtgFd-r-IcbVZDbZe0qGfUjDCGnThWaecVTZexV5aGatYFWZkFORTVa9ZNVgijRVZ9erKTQZTjT6C4BeAbCAIIEAA)for the vega-editor spec to reproduce.

**Comment by arvind** [comment]
Hi @mattijn, I just want to make sure I understand this correctly. Are you expecting that when you click in white space, the selection should reset to the values specified in `init`? If so, then yes, this is expected behavior in that `init` simply specifies the _initial_ values of a selection, not what it should reset to when no points are selected. 

I'm going to relabel this issue an enhancement, and adjust the title accordingly. Please let me know if I've misunderstood, however!

**Comment by mattijn** [comment]
You are right. The `init` part work as appropriate. At that moment I was surprised by the behaviour of lifting both the `init` and `bind` options once clicking in the chart.

Recently I [learned](https://github.com/altair-viz/altair/issues/1617#issuecomment-516920461) I could add this:
```json
"clear": false,
"on": "click[event.shiftKey&!event.shiftKey]"
```
to the `single STATUS selection` to make the interaction not responding on chart clicking. ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIDdkBTAd023FzxOQBMAXAC3IBYAGNgGkqskaLSN65AMwceYAL6VJ3PABsAhgE8iAJ3IBtCTipRai+ovK69UeIoC2RcpABGigM7JHAfQNHIEiLO9RLimoA1rbyyPA2cnqQRPBwtOHoWKbRcPKwGsl+vPTKAA42WJDwsJbhivKQUWZ4KETytLYA6obqjkbwjdU1kI7QFYUUNdF9-Na2hGp0Ll7DPt1mkPTI9PKDkC30bR20YJqWAHIAggAKALqzNb7DS7Cw8st5Wtm4KTe5BbYlZRaVCz11BrNVpqdqKTqXYbSYZnf54AAeJheeA+6wAjgBXcHLIzLfCRZFQQGNIoAJWQACsLIh8LB1FVCb1+mskXNcJAAF7qWDkRAVRxEQnXOZLFYssmU6m09R7SwiAD0jguL2Fi2UrJFqNsmOxK0MyHxDLZkGJtgAWkRSCCwRC4ey+gMNcauWoeVg+fIBUK7SixesLVatqCdrLjudIXpoZH-r16kRoMsEE7ogBlAAqRzTAFUU8nFlqis54KgWT6oOEVnmemD6BjHLYEtAhBGzKqAcQGvWsNo2Xga3WW3pYYy7OESUNe5BwnkMcJC3GE0bJ7A8on4F29oTeCvYkve-pkE3hFuwGdvYzoGtArz+UQy5Ak0VL4egpoiPj4PQAHSORjIRD0AA0kQygAGQAITvrE36-v+QEgcqUJ+G2KJqOCjiIBkljPMMbzRCgDz0lk+6xmsCbII+UDppmOaDlQUatn4Z70d0eGQB4xjET0FjjEUeSwOE9CuAKZHHq2MYBMEVYovk6z8YJe74cg8hrOO9BqBigriX4MRxLACTFtJUCIlx7yydqWKfnqeIEsapoSlSig0nSGgqnakDqqZPQFlAOpWbiBq2SK9lQAGJDWjsdFSO5zhckZeD4BUmnkAArGwbkvDA9wZPFUCJfIyVFGoRCNCqyESFGw54BxAr0BuKSQPJn7CQuc6bmYeF4GFEXguOLDueSjnOURYAAGwAIwABzjV+k3lVQVXsg4zhuBxOF6J1UCbNsvXkONA2Sk50qZGNU0zZN7ndUGNrjjN42jTFuIDkUjbNsh-ybRsPUQlg+2ZYNUoueQo0cFwmVXTtP1gHdF2Zf2G7sYeb3aR1mXbcGu2-QdQ3HawoOXZa4XXZFv1fiwf03PDDZI2J0Z+J96M3Xt2OAyNABM+Pg4T323V+KUU9WT0I69tMsfTaM88z-2HcNJ0g2DNwQxjUMzQA7Krj2GM9B5HoOKETosjMk9DfMs0dQO-WzLAsKrX4C4sStM6T92a7Wws03rH0S8TmMmylZuy3toMKz0jvGzN-Ou9riO6+94s3EbvsRwHuNYJNnOK9zPsq1+o0AJxR+7scoxt3uQ7z-vSzjFtjRnodZ+Xe2zWzhfU8XdOownkuk5XNwA+bI3sBwBOBo3WBs1+bAiK3L0e3Hnc9InOe9z0-eB1gIiq5NLBftPXOj8r44T2w-Vw0LbfIx3pdd9nFcpzXHPD-vRNj2AE8u2fWtF5fYsL4b3d+3viNeWI8X6H3IBPFge9Kbn1nu3X+19F4AJblXVmcsn6ZwPk7MaM8dY-1wPrBmyCgEnXGnnUa0D65YONilSep8YFfwvqLAhXsb6vxQX3GWqc351wdg3cBWBaFsHtiMWBeDmHzHjkg2+ECSEQMmilPOu9QEAJ3ifXBMd8GSL-tEJeR85FYCHiHPh1DfYT0mg9T+bsmGeykf-GR48DG1wwVQsB2DIEaysdHEWtidG8D0bI1BA8TrpxcSYtxxsJ4iEoYsKmcCtHRTsbo4hQT17Q2Diohxb8vxsxiaIxh8SJGJL8eyAJjjUncPGuNMQO88m8DDmYuhGifHz0QfY9hTjqm8OiA0nOW9mlzxLlQIhWSOGry4TXe63T6n8OwTNFgK9YliM0UUwhZcBFv06aE4xPTZnhxyZYhh1jCm+Lack0ZpsKk1xYKNSaIgvwF2fgA0aTSvHf1Waw6R7DLmcOriNfmKVbZ1PZL08cQj6GCwKeI05wz1nuJ+eMv5J1AV5yUcCrqezfZqIhUsqFKyYWvDhZEhFiw17cPljsmZpiob3NVuiqAcToWtNhWwjZE9FnRDJTXUao06XKKeVk+56i3k2OZYS1l8KOW8C5SNbZmTvmTUeUc7xgyr4sq+WyklnKJkjXGhkgV3y85jNxccplQzxUaslZ0sQYTdnUqPmTWGyr3kEogCM75Ur2QytIRS+Vmrxo4vyaa-FYq3VEsaZ6vA3q9qqzYGlMmfr4XCudaK81YaJXEsjVAaNv05UGo2TNPOWbejLJaWmg25zX70sgDmsAqs84iBeZ4zBETfYvOTZC4NZa1UWvaRs6tta80toAbQhRAz4EsKSf4gBA6dUhLIU2xNNDXkppOaGit07BVOLziwdOdsl1YpXZ2lVE7tFnM3VWzp+rh2CtmtWxlIby3uv7da6ZILMU0rtoc49Lr13PuwbOpFe0oFsxecau1rbP0dpNSehJayM2+0A2gvavr83woseOuDny+0Aa2W+jF9qIG52bT+1NPb02WuNvc4ttaG0pXMQeqG7bA28Afd2hB6qcNUa1dKudQd8OhQ-WCye36YO-qfeGz9NG+O-Q4GzGa4GqWQeE9BoNsGPlTtKTOnjXqZPQ3GlvNWjG+pHrE2RjjvbK39p01GvTXTbVKe03SzDGmSl4DKWAajnTUM3qrQmkVa6JMIak3hhz77CMbxyUq0jgXyMbq01kljumgO-T1Qsr8JHwnPNM2p8TcX-3GyS7ZlL0N5MsAntFrLWTwUuddfF9zqjX1hYI8p1gfMnUxbNflyTfVOm7rZpNfdaHCs5dY6W1VFmKNcaxd5gTkBQWiFmpV3L5nJ1ua2o1q5uqh2uKcx1szsXJv1Y24lmz2a7M2p3pliD2XVNjbxextb56Euvx3tJkrAbbkvP2zd6ro37TjdPcU57DXTvveQ79Hzu3TujSKwywHWHNOg9e2dmtdmdtVZRyIYtbGJtPc41Z7B4Pgl7RSiIcmQ3fMbOY7Vv9PXUqzea4JiLYBaHXfu12vHZ6CcXo2cTtJBmd2KfC61wR-2+wI9cyDk7r9+eVIx792Xk972S7qwVpOTiJrTVmsZpuH9V1QB3PANX9OsZbfQUz+bQm9c-Y59HI3Jvgu3ScUY3XpNyYaId3Tp3UtfkQ54ZbhbPcRF24Rl7oLlGNfm+BoH63pN1ae4KMb73kfl6dKtjbSn0PX53VEytoo4fus+57leubQeTa7sT7uFP020-R7TmXuPJtRrC4l3iwvR31d179yTrAUPMcFublX5PEfa933r2AV3w3GlT2H471P4+e9pM3tvflVOk1w5Le3pP8+x9Nzlw-RvLP3559D7YDv+PLO87maj2tIDp9Q0gSr7f1fR+E8iZr2PLP7kBrnzX9-Zi26bM7OIu2md2AOL+I+ReC+gSS+3Cj8lKoBFytuEBwaF+3OV+L2bKLuR+ou2Sp+qB9uO+-+1+H+E+-eiumqHuAWhuxBb+pBgBE+CujmFyuSf+9BWB7ipeX+eB78re8OkBu+ABj+V6dKV2bu2S4BbeaBdB0Be+5ScBkyNqiBLWACasOOyy6BwOPOnBZBihuqFBLBOeZMz+Mhr+chwh+iE+U0uBahBy7BFhDBj+t+em9+6+I2bA-BW+ZhUBnepu2SB+7Mtht6KUm+D6Wh8GMB48LhJWU+7hiGdsy2Z+BeshfhxeARTiZOfKxa5eQqYRmhqRl+U2lhRGgRFuKhzOvBDyKB0hRB5haRURGRTBwR3y9aDhDR8hTR+hpC162emqPK7RRRx2X0FyZRe0yhEhUSBBtRYehRGBxRThDqYxkOLRmqbANRAhPhQhixpR3m+cM00xlRyC4umxdRvhQxXeSxoWFRVuLOha+RghJBuhiGn+Nx5eV2Gx3hZx2xzxNKTiCBEhtSIehBsx9RFx-hSGvenmVSb2gJJxXxoJ5x8xwxHmkJaScRfRAGs0GhjxHByOL65BqxWJZOgxyJlxogTizBSBfmbMSRIJ5+cx2hmB+JuG1hvRA+WJBmpJTJCxvx44aJlSZCZOOuD+-J8J4RjJkRnRApShRJxKO63JUpJRG8jObxTeE8FCip2Gypnm1xkxjqWpSOMu1myxziEhtChxCJDJYJZJEJMR-uZCqssJopqU4pBRNpPJKJ2mppAJLpYus+NBD4kp2pOxkWppGJHJI2kcgZERIZfJi2pphh1JGyaiIBMx1pSJnp5JYZmu40KUtC1a7xbpuJjh8ZOZzRPBTmlpEpHpSpoZnm9pUJeqcpCR1Z7pmZdZZZDZpp9map3+-mBuQZtZcZLJ3GPZSZqht6eZhp62IxfmPZqs9GSim+uRxZWxTxo5CRPZVJk5l6MZwZRpc5KZ3mU0ucEhNO+5w5h5Hmm+tavp8RUMo6nxNZHZI5xp2Ct5emEZlBROOSwJ6ZKRV5s5N5LuLARaa+mJy6UhpxiJPxm5UMn5JWE5RxMObZJZHROpiF-uO5KFKOoGM50uR5H5269aLyORTe2KBFOh8FvWbJLZCFk8XhL5cF75hWTWfZeB9y28VFzJrFM21hyFtxnFZ5l5r515m23Re0OFQl2mCyPFvJNFbWppIgecCiA5kFbaa53xG5fFDF4Z9F44F5g5sZ4lYOrxHFI6u8TF7ZLFRFUZmu28Silp5eNWoltlN5jZaS0lRZ-SblOldlh6PZ7JP5I2YF8lXpZl1hExfpk+OSOJ65eJulJmPZii6s6lkZh60FVpgFYlwFqinllSglRZWVzF-lHl25Bli2iq4V2ZrOuZsaIpD5hlWlsFZVI6lJlVYuUCNV-hppRaZCWeGVj5LVGZ7l7VdFlZp25CPV6RPZ0VTVbWsOM1jR45nVsVDxCVpZilgiepMVO8tJy1nRtCppCime-5uF1OI1OVY1f2QVa1FpaZMFo1bVt17F5pV1tBQFhFHmx1b1MVrlxlB5eVr1Ala1V2aFm1GF9Zv11h3lFFucEN2liVAVTGnSAa5OjVGlTGH1Q5uV31zyf1C1Yutyh1OplptaUyk1SuU0pN9Z5Ndm6swBEFQ1KmG1SNW1SVwMu1RNrOyutNXZZFfWvKo655ONJlwNr8gtoNVNfOQ+flyNHmUtklua91uc1l6FBCEgzEUgIAkgQAA))

**Comment by arvind** [comment]
Thanks @mattijn! Yes, it seemed that our defaults with binding + direct manipulation interaction were confusing for a lot of folks. So, in 4.0, we'll be switching the default to disable any direct manipulation when a selection is bound to HTML input widgets (#4936).
