### ISSUE TITLE
Updating docs for Step function

### ISSUE THREAD

**Issue by PUNITBATRA** [vega/vega-lite#4716]

**Comment by domoritz** [comment]
Please describe the issue in more detail.

**Comment by PUNITBATRA** [comment]
Hi @domoritz In the docs [https://vega.github.io/vega-lite/docs/area.html](url) step and step-after function are written exactly the same. So I want to correct it.
Can you reopen the issue?

**Comment by domoritz** [comment]
Ahh, thanks. Yes, please fix it.
