### ISSUE TITLE
vl2vg STDIN error in Windows

### ISSUE THREAD

**Issue by crouthamela** [vega/vega-lite#4727]
**OS:**
Windows 7

**Versions:**
vega-cli - 5.2.0 (from npm)
vega-lite - 3.0.0-rc15 (from npm)

I have a simple Vega-Lite diagram:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "width": 500,
  "data": {
    "values": [
      {"Customer": "Customer1", "Bandwidth": 250},
      {"Customer": "Customer2", "Bandwidth": 50}
    ]
  },
  "mark": "bar",
  "encoding": {
    "color": {"field": "Customer", "type": "nominal"},
    "x": {
      "field": "Bandwidth",
      "scale": {"domain": [0, 500]},
      "type": "quantitative",
      "axis": {"title": "Circuit Bandwidth Guarantee (Mbps)"}
    }
  }
}
```

When I run `vl2vg < test.json`, I receive the following error:
```
H:\Documents>vl2vg < test.json
C:\Users\ancro\AppData\Roaming\npm\node_modules\vega-lite\bin\vl2vg:35
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'H:\dev\stdin'
```

This appears similar to [this vega issue](https://github.com/vega/vega/issues/1276).

**Comment by domoritz** [comment]
We should use `process.stdin`. Can you send a PR?

**Comment by crouthamela** [comment]
Sorry, I'm not really a coder, just a network engineer. This ends up causing asciidoctor-diagram to fail on Windows though, so I certainly hope someone can make the change.

**Comment by jheer** [comment]
In addition to having vl2vg use `process.stdin`, it looks like each utility function (e.g., `vl2pdf`) needs to be rewritten to work cross-platform. I'd recommend dropping the bash scripts and using node instead. At least, this is what Vega does.

**Comment by SoftwareApe** [comment]
Could we use https://github.com/mbostock/rw here?

That way you only need to do:

    var rw = require('rw');

and later 

    rw.readFile(...

The rest can stay the same. With `rw`'s readFile `/dev/stdin` works on Windows.

**Comment by domoritz** [comment]
Yes, we could but we usually prefer not to add dependencies if we can.

**Comment by stenzengel** [comment]
I have the same problem. I am also using asciidoctor-diagram. Vega works correctly, only vega-lite has problems. 

The milestone was removed recently. Will this issue be solved?

Does anybody know a workaround?

**Comment by domoritz** [comment]
It's not on our roadmap so the best would be to send a pull request.

**Comment by crouthamela** [comment]
Very cool, thank you!
