### ISSUE TITLE
Crossed facet doesn't work correctly with streaming data

### ISSUE THREAD

**Issue by 3Diego** [vega/vega-lite#4736]
When dynamically updating data in a crossed facet leading to the disappearance of some categories of the row or column faceted fields, the row_domain and column_domain lose these categories whereas the cell don't lose them (because of "aggregate": {"cross": false}) leading to an incorrect visualization. 

![image](https://user-images.githubusercontent.com/12158642/54483128-d46be300-484e-11e9-9ab1-01e936f5c2a0.png)

--- Example ---
![vega-lite1](https://user-images.githubusercontent.com/12158642/54482981-4858bc00-484c-11e9-9d58-fd714ed57c8b.gif)

Can be checked executing 
```
VEGA_DEBUG.view.change('table', VEGA_DEBUG.vega.changeset()
.remove(VEGA_DEBUG.vega.truthy).insert( [
      {"x": 1, "y": 3 , "c0": "A", "c1": 1},
      {"x": 2, "y": 2 , "c0": "B", "c1": 1},
      {"x": 2, "y": 2 , "c0": "A", "c1": 3},
      {"x": 3, "y": 1 , "c0": "B", "c1": 3}])).run()
```
in this [vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJCXpUybFF3sx59YagV0Y1slgWA2hvvBIADwsAjKpQAJ4W0mDBkPAADBaQAIJqUPABgQC+dvZgPv44AExRYQWRKXE4kABCydFpOAGZXoa54UWBpdHlUElRqRb5jdk5foFtOBG9XVU1fQWD2S0FY2D5HbHxPSl1YNLz3iPjywFrU9W927tNALoa85AAZujwyHgWBobR3M6oKvqQeCFCOYKkpuKhGCYxDV7oxkGJNPF1nsoAAnbgAdze-0BwKgoPBkOhsPhiLS6VuWUgsCB8DeTUg6MYmhYFgALDEskYUIxqPg2Rz6RgUQBreKEbgQ16cqDIJTwbiaCHUOlDA7DGFwhEVfxRAFA+IAR1Y6CUeGYOkYVEgyKMxXVxK1oRqetxkCNJrNujNVvJ9l9YDu8qUMOV+nJ6SAA)

--- Posible fix ---
Don't know if it will break other situations, but this can be fixed by adding `"drop": false` to the transform of row_domain and column_domain.

![vega-lite2](https://user-images.githubusercontent.com/12158642/54483107-9ec6fa00-484e-11e9-8b29-00b9eb242431.gif)

[Vega-editor of the compiled to vega version](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6ArIoiQD6PJhwBtJRFAQfUGelQdHEgXdgAbHXtfKAp0MNZkWF0PaJ9gSAAPXQBGeSgAT10AZjzIeAAGXUgAQQUoeGycgF8o1PSsnAAmUsKu0oqqgCE6ssacbJbPaPbinpz+yuDa-rGwTsnUr0z5gtn6xahhld111untvt3LsoOakYbijc2ZnBKrsFz9ofvVoqapiAAXSmTy8AL8ASC9W48VQMgA+gZuBhLMZUpBpKwAE7wKEhdDhSLgkJY9AyWAAM24WNQyXSeHyhDx6Go1CxwjwkSgbO4rEI7F6YDcN0ggKawN8oLA3mikH8gSqWO4AHdEcj0Kizg5MTi8aEImjZXhSeSqTS6SFGczWezaJyRjy+QLkqNReKQUpAVEMYxqP4wkl3FN0vK8UhGGEDPDlYwDCwRrF4lDROUpSHIVVw5H4ShffgE3EEroU-8gd6wuh8ry8LoZQ4zBYrLXIErlTlyv0Yaw4e2pZBuBSKbBkDWcOlWwAVZgG8Yd6GwmRTvAzj6ps5lLtwwPSn1+uJVCJWFgACicLmPAHJ4JuEUiUTILwBKR+QPvsXkyAzbyAU1hhMKGg4cS+nIwRxABShPJAGBYgA1tuKRpMSoaKiqAC0eDTkS6IMkyVSOoQgE+C2MJ4q2GFYURDiYcuUJ1kayAZKO9SNFqxEDkOI7tmxDjUowyAyMxkARBSNY8VAsAMiukDUKwsbIBRtGQOCpY+GmyEZsE14LopBpsZaeHBARVFQEq0nad2Mi6dhRqUWOISMUJAylBxw7Mdkc4YlJeKyfJ1mviCZz0Q4KHBK2ObIIYyBYiZBk+UqfKxWZZHoSgUUxfpFJKrS9lnq4pkqmq96vvp0hYsx6QUvxkZVGe3ZuAAOqMTWAiM1IGNFVToAgAmNtYUrUXZ0rgtRjnNhoe4AcEF4XgA1Po7KCY1zWiiVI1QK5XGzuJ-ZYvxgkHsgokmdq3n4XJHVoRW7DIABO3sN1t2WHiqCxgYBoqfpAnXh1zZ8medGQLm1D5vZE3+pmiARlGwP5k08P6egGSJMk63BbKCBxHihTibxe0CUJIlietDhsrGugUnEw641ANHSTjJNQNdt0APJUFiFaETgxoJDTISMPAsEAMIfhVu4Q1pyARseWYw1LIN4KQKYvgNsqaJYHUdB862qb4EpqUFGkKlpN4RelsW4fFvKEfpyWZjeaFpR1GXEllyLNnl9sLkVGpyKrGLUmLVW3UYwR1agy0VC1bVYs7XU9Z+lj9fpdN0etDlMeNIH7tNc0LQTkflNHqu8YObncenkn5NJvmXczd3pw9w5hM9VSveYH2pP733cL99n-c4gMxnGiBZ5NkPQ9GsbxvDutgOp6KhfOlnwlS3Cci7OFWvhCU28Sdsmzpa8b7Fbs5TunuHyvd6+2t6JlUH1Wh1A4eF9HLmx51YEJ31d+yj3fcdwD3tPZYe8YwbZymvUKG2YwGj1nojZGCE0aMwxPALGVQsh8z4gTKo74CDuz5mTZ+lMAzID5qnTBJ1iL1wAGLxFgKPbmWJeaoPrmzaKnNdA83IagzCgsRasAOhA8ektpayyniPJW5QVZ83Vp+RiOQdbgn1hABesol5lFug3LehluS71ilXcy2jT7ZVrOnSmuIKqoM0ZYrifNL60wJHpVBBFnTuFdAsUUfMWRsg5IDeASpYDbh4XPSUn1iQP3MZsKAwcaoeNfk1Bo78X7OHqkkouq0vTp3al-IUkBuq4kTk2UohTepJ1FBE9EAC04xMgMA2pMSoBwLHhLaBk8Wkl2IrDMW4Mc7tOzD0gKMSwnz30jBeCqMYno18HKTSAyowTKSBQ7ewRYD5FQO+HRTSvLVyhMKQg3BLA1myU02JZjcrOHyj+dAVi-51JqdEs5UAGlPOeRtfQ8BmCCnSImIsOByh0AAOxdPRFVf8Uz3lIShQxSStU0kRyahkFqYAAC86KwAyD-GEMAAAfXFYBGCwAAHLoGJaeBFy1kWikfHigliTID5BRei1FmLsV0sJSSslFK8DpMZS1F8NM6l-KhFi-8jMu5CvOCKqoxoySwHzgdUZMTTlQq8kqWC+yJXTG1ThRIQkGXUsBGijFYqcX4s5aS8lhqBUcoZUy0UJrWVmo5USq1PK+UOsBIK3VsoZU4DNb6tRUrfC-MLHiAAxKIeAQKAAc6BY3DKhaq95IRuAwkwlzYaMLtSQKqMAJFTUcBmgwHgD1iLMgtTyE1Jqj5q38optSUt5blpevrbWpoykYWgtlFrdImNpJYNiU-KhPbZk-LQRg4IONh0hyqIUZV0RF1qOUakFNxEkYoyDNM1BA68RYNQTg4RUB8FqFpEQvaBgADK6D6bUNJpe7hLDeFnP5gI0WrT+laPETAqMcDpGyNQTfVExaqYvp2fXbcpDqaoIwBkAAokxXBAK+avRkIhzkx6Ox8IFpM0DZC5Ea0UQCnW4kZnET3fO+9G18bHuEkdYmr7iE3qnVAA9THH3MNYa+-hwsP0iLad+sIMtf0RTzIrZW9zNiOHVCBsA0HwN1MgxTMDqGkYYeQ2AbDr60MaawxQ3DUHVOoPkZrXQ5RV3RFUfPT03o93INDUbfdFtVlM2eugTespgOgQvlc2VziuQ-hHcELI-sTTUH2XOfteatKic6eukKAsoQ8P0toJUT6EiBWDE5qjKdXPCXc552Z3mPZ+eCPqQLcTn6Mqkw4cL+zouiIWWJhWJUtMJb8EljLiniJpe4N1j0ZYTDXhkFVaw9kkZEoAJrNl00h49RRUz-CaEAA)

Example Spec
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "name": "table",
    "values": [
      {"x": 1, "y": 3 , "c0": "A", "c1": 1},
      {"x": 2, "y": 2 , "c0": "B", "c1": 1},
      {"x": 3, "y": 1 , "c0": "A", "c1": 2},
      {"x": 1, "y": 3 , "c0": "B", "c1": 2},
      {"x": 2, "y": 2 , "c0": "A", "c1": 3},
      {"x": 3, "y": 1 , "c0": "B", "c1": 3}
    ]
  },
  "facet": {
    "column": {"type": "nominal", "field": "c0"},
    "row": {"type": "nominal", "field": "c1"}
  },
  "spec": {
    "width": 40,
    "height": 40,
    "mark": "point",
    "encoding": {
      "x": {"field": "x", "type": "quantitative"},
      "y": {"field": "y", "type": "quantitative"}
    }
  },
  "config": {}
}
```
Example Spec compile to Vega
```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "autosize": "pad",
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1, "y": 3, "c0": "A", "c1": 1},
        {"x": 2, "y": 2, "c0": "B", "c1": 1},
        {"x": 3, "y": 1, "c0": "A", "c1": 2},
        {"x": 1, "y": 3, "c0": "B", "c1": 2},
        {"x": 2, "y": 2, "c0": "A", "c1": 3},
        {"x": 3, "y": 1, "c0": "B", "c1": 3}
      ]
    },
    {
      "name": "column_domain",
      "source": "table",
      "transform": [{"type": "aggregate", "groupby": ["c0"]}]
    },
    {
      "name": "row_domain",
      "source": "table",
      "transform": [{"type": "aggregate", "groupby": ["c1"]}]
    }
  ],
  "signals": [
    {"name": "child_width", "value": 40},
    {"name": "child_height", "value": 40}
  ],
  "layout": {
    "padding": {"row": 10, "column": 10},
    "offset": {"rowTitle": 10, "columnTitle": 10},
    "columns": {"signal": "length(data('column_domain'))"},
    "bounds": "full",
    "align": "all"
  },
  "marks": [
    {
      "name": "row-title",
      "type": "group",
      "role": "row-title",
      "title": {
        "text": "c1",
        "offset": 10,
        "orient": "left",
        "style": "guide-title"
      }
    },
    {
      "name": "column-title",
      "type": "group",
      "role": "column-title",
      "title": {"text": "c0", "offset": 10, "style": "guide-title"}
    },
    {
      "name": "row_header",
      "type": "group",
      "role": "row-header",
      "from": {"data": "row_domain"},
      "sort": {"field": "datum[\"c1\"]", "order": "ascending"},
      "title": {
        "text": {"signal": "''+parent[\"c1\"]"},
        "offset": 10,
        "orient": "left",
        "style": "guide-label",
        "baseline": "middle"
      },
      "encode": {"update": {"height": {"signal": "child_height"}}},
      "axes": [
        {
          "scale": "y",
          "orient": "left",
          "grid": false,
          "title": "y",
          "labelOverlap": true,
          "tickCount": {"signal": "ceil(child_height/40)"},
          "zindex": 1
        }
      ]
    },
    {
      "name": "column_header",
      "type": "group",
      "role": "column-header",
      "from": {"data": "column_domain"},
      "sort": {"field": "datum[\"c0\"]", "order": "ascending"},
      "title": {
        "text": {"signal": "''+parent[\"c0\"]"},
        "offset": 10,
        "style": "guide-label",
        "baseline": "middle"
      },
      "encode": {"update": {"width": {"signal": "child_width"}}}
    },
    {
      "name": "column_footer",
      "type": "group",
      "role": "column-footer",
      "from": {"data": "column_domain"},
      "sort": {"field": "datum[\"c0\"]", "order": "ascending"},
      "encode": {"update": {"width": {"signal": "child_width"}}},
      "axes": [
        {
          "scale": "x",
          "orient": "bottom",
          "grid": false,
          "title": "x",
          "labelFlush": true,
          "labelOverlap": true,
          "tickCount": {"signal": "ceil(child_width/40)"},
          "zindex": 1
        }
      ]
    },
    {
      "name": "cell",
      "type": "group",
      "style": "cell",
      "from": {
        "facet": {
          "name": "facet",
          "data": "table",
          "groupby": ["c1", "c0"],
          "aggregate": {"cross": true}
        }
      },
      "sort": {
        "field": ["datum[\"c1\"]", "datum[\"c0\"]"],
        "order": ["ascending", "ascending"]
      },
      "encode": {
        "update": {
          "width": {"signal": "child_width"},
          "height": {"signal": "child_height"}
        }
      },
      "marks": [
        {
          "name": "child_marks",
          "type": "symbol",
          "style": ["point"],
          "from": {"data": "facet"},
          "encode": {
            "update": {
              "opacity": {"value": 0.7},
              "fill": [
                {
                  "test": "datum[\"x\"] === null || isNaN(datum[\"x\"]) || datum[\"y\"] === null || isNaN(datum[\"y\"])",
                  "value": null
                },
                {"value": "transparent"}
              ],
              "stroke": [
                {
                  "test": "datum[\"x\"] === null || isNaN(datum[\"x\"]) || datum[\"y\"] === null || isNaN(datum[\"y\"])",
                  "value": null
                },
                {"value": "#4c78a8"}
              ],
              "tooltip": {
                "signal": "{\"x\": format(datum[\"x\"], \"\"), \"y\": format(datum[\"y\"], \"\")}"
              },
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"}
            }
          }
        }
      ],
      "axes": [
        {
          "scale": "x",
          "orient": "bottom",
          "gridScale": "y",
          "grid": true,
          "tickCount": {"signal": "ceil(child_width/40)"},
          "domain": false,
          "labels": false,
          "maxExtent": 0,
          "minExtent": 0,
          "ticks": false,
          "zindex": 0
        },
        {
          "scale": "y",
          "orient": "left",
          "gridScale": "x",
          "grid": true,
          "tickCount": {"signal": "ceil(child_height/40)"},
          "domain": false,
          "labels": false,
          "maxExtent": 0,
          "minExtent": 0,
          "ticks": false,
          "zindex": 0
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {"data": "table", "field": "x"},
      "range": [0, {"signal": "child_width"}],
      "nice": true,
      "zero": true
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "table", "field": "y"},
      "range": [{"signal": "child_height"}, 0],
      "nice": true,
      "zero": true
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

**Comment by domoritz** [comment]
cc @jheer

**Comment by kanitw** [comment]
I think it's an instance of https://github.com/vega/vega-lite/issues/3900
