### ISSUE TITLE
Allow comparing a field with selection. 

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#4740]
### Motivation 
I was trying to reproduce  Hans Rosling's interactive chart: Life expectancy/Fertility rate on time. On presentation, he shows the history of a country as a tail up to the select moment and I could not find a way to express in vega-lite.
![image](https://user-images.githubusercontent.com/11561581/54648150-31b59d80-4ab6-11e9-8d81-6ec1faff3e5d.png)
https://youtu.be/hVimVzgtD6w?t=329

### Proposed syntax variations 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "selection": {"select": {"type": "single"}, "fields": ["b"]},
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "fillOpacity": {
      "condition": {"test": "datum['b'] >= selection('select')['b']",  "value": 1},
      "value": 0.3
    }
  }
}
```
expected result [editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJBSNq+XQCYADO7tRYeAJ4ANjo4kPDIAQHG9gboeJg4ANpKEMCQMuiowT7hyPB4APq+3ABOOgC+3inJEFDpmbqQ0qzFYfnuUTX2FOgBrMiwukmdnanxUACCClDsbgAcFdUjkGOQAEJTkDM4oqILwzWjDQDCG1tgACwAzHv7YIchACKnugCcAIw3+-dQAKLPOLMPpVht9IAAxf5gUTXYFLFYAcUhbxenxBywaAAlIbMAOyouENACSkNErjKizAAF1quSIJTvI0nOkAgNEtVUnUspAAB6FPDIQgbbq9LIeVGgfZpDJcgDujAMLA6nUgrEIMX5DXY6BkBlg+jCAAoDNwMJYDQBybnmgCUdCCVhY8jA7jobydLvcomtYAAVGBeb4BZAacCJcMpfUQqwZMwlTVIMK+rpgPioLJBhSUpBkFQZHhWVBUNxWLA0NwqBtVequYxYAAVVVBA3UYrFwgG63egD8YBbbY7YBw0djtOG1M64ojXNLQTylbVsS5FACAGUcnkeDIAEr9bgBKgGgA6jXXBSKpWP1sg4opU4aM9yBTwjZ0sLTcjZtzumfjOeQeYLBJUiaFpp3gbhCFfKB-Eghp4ACRh4AAa2vekf3sKtFwadVWFQMAADJ8LAZg0A7OgMGKJDyPQSiYOQMAAEIAF4mLAc0+1Vc0wB7YBhzwHBj2PJ0ADNGHCXUcAfPJ8mfQggnyUTxNgJ1E36RIDRI1AyNrAA1EpZG4RhuLAHDUDoUzBxM2JcOtBJj3YY9KUpMpLJkVgIjjSVhJKMJdDwYo+h-UdOnHGpJ05e9Txkl8FLEgJdSFHok0SVJFPizUNjoho-jKZzQ1vCKQikgoiwsYS-E8qBMI1EJSsYcqjxPWczzUC8pmK6K5OQJ1-L6K8aSUND7AopDAPZArpQaEaBjfSAspCUo51m3xAiyBJNhoyAhvDYTW1QZNIHVFYQNadpU2zGRwIMLIw0laqbvQqBRI8z8vwOR7lX5XxsOs1A7M2RywBY1i3IiMAAB9weI2AADl0Bho1fv+hytqvN8vwTJKslBgIPrAVMvkxkUGgAYnOeAcVmdBZmvR7tox56AgAeX1ZgKtet7v05z7+jwBoGINe1qBYRG4kajrz2QS9OwhqHRfQcWosly8EncSk6FU2BVcpAAeVjTORxy0bxrosd0N48YJtFVN0F1rjp9H4zUPc8EYQUcFut7GWoZkGmAY90GPHBzXNABqA2A8cp17KDsBvOKDA8FF3DDa26PIEvMpg05q37G5A6EB6Ll86dSA0qMEJMFzqA5QVRAC-gIuGhL6ZtQrsBeuQavIHZu5GkboIGgq0vy4y7u-FcBum5CYeoBtnB3GC4Yl4gJfR22-ui7GkYJsjKAS9vebW51SrDpNdBLAOo772LUC2g2UfK42aRij5nBO-O4ptWoG7Gn5d2+4aB9j0ZufIgxlHOmYCwVhCQyBkMgYottXSzSgZYagTNVAIKQZ6EM41JSFSgMPQ+fhYIhAQvAzas1jSmg-H3a+RVb6nQfnFdumxryzS-lYNawEmQgJCI4ZwfMKjOnpvGGMvl34BW6rebQrY-JSIGnSBk6BuT9AzDvSUhdB4hAPpKEoYk8yam4AQE0p8Wzyl0MJHopZZquzwNo5Qp8AjoHYOEcYCEfYNGKE4Fws1nGuICOMKwDjXA4i8Lefx4RVjoBnJYLkqB5QGEHn4lx4QmZUGKM4gBndZqaEsNdfOOALYTnypogeXIiF6O8f+N+UAgjCT5rNcx7crEsmkZKOxDi2EpICekhBWT5F9FsYhJCRxiyGI9t7X2IQwiMACAaAR+BSDnHcFec6eSdTIEKWAYpYVSnhi0RU0++iakNHqY028zSVzlObmY7x7ccmHxGWM6MtSeHAMiDM5AcyFnfMEcs1Z7DbzUIvrQ1pNiImpJZJY6x7TwwYG5D8bk-IJnOlmgkmQSKUW1PCR0kZBZwVwuVBsgpttFFUhAGUIAA)

```
    "fillOpacity": {
      "condition": {"test": {"field":"b", "gt":{"selection":"select", "field":"b"}},  "value": 1},
      "value": 0.3
    }
```
For nonsingle selections should be used an aggregation function.

```
   "fillOpacity": {
      "condition": {
        "test": {
          "field": "b",
          "gt": {"selection": "select", "field": "b", "aggregate": "min"}
        },
        "value": 1
      },
      "value": 0.3
    }

```

**Comment by kanitw** [comment]
As @djbarnwal starts #4971 to discuss the syntax for this feature request, I'll close this to avoid redundancy.  Please follow #4971 instead. :)
