### ISSUE TITLE
Add band align from vega spec

### ISSUE THREAD

**Issue by melissachang** [vega/vega-lite#4741]
I'd like to use [band align property](https://vega.github.io/vega/docs/scales/#band) from vega spec.

See [screenshots here](https://github.com/d3/d3-scale/issues/164#issue-418997920). The first screenshot is what I'm trying to implement in vega-lite. It's not possible because vega-lite doesn't expose band align.

I'm not sure what the policy is on requesting additions to vega-lite spec. I'm using react-vega-lite. For now, I'm going to try to get the compiled Vega spec from Vega-Lite React component, and manually adjust it.

**Comment by melissachang** [comment]
I'm also interested in axes encode, for showing tooltip on axis labels. Maybe this one is too obscure for vega-lite?
```
    vegaSpec.axes[2].encode = {
      labels: {
        interactive: true,
        update: {
          tooltip: {
            signal: signalStr
          }
        }
      }
    };
```

**Comment by kanitw** [comment]
Thanks for filing the issue.

Band align will be added in #5055.  The encoding block will be determined in #5056.

ps. Please file two different feature requests and two separate issues in the future. That will make it much easier to manage/track issues.  Thank you :)
