### ISSUE TITLE
Experimental selection APIs

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4751]
- `vl.selection(view, "name")` 
- `vl.add/removeSelectionListener` or `vl.selection.add/removeListener`

I guess `add/removeSelectionListener` is better (a bit more modern style--flattened)?

**Comment by djbarnwal** [comment]
@kanitw I would like to work on this issue. From my understanding, the new APIs would be a wrapper for `view.signal` API. Can you please explain breifly what we want to achieve here?

**Comment by kanitw** [comment]
Thanks / Yep, this should be quite simple thin wrappers. 

Basically provide APIs so users can (1) read selection and (2) listen to selection changes without having to call the `view.signal`  / `view.add/RemoveSignalListener` directly.

(Vega-Lite users do not know what signals mean and they should not have to know that in order to interact with selection.) 

The signatures for these methods should be just like `view.signal` / `view.add/RemoveSignalListener`, but all having `view` as  the first parameter.


Then document about it. :)

**Comment by kanitw** [comment]
Closing as this is a duplicate of https://github.com/vega/vega-lite/issues/1830
