### ISSUE TITLE
Brush does not work for multi-view with time axis

### ISSUE THREAD

**Issue by nfoti** [vega/vega-lite#4752]
I ran into an issue when making a multi-view plot consisting of a scatter plot and two plots of time series. When I use timestamps as the x-axis for the time series plots and brush data in either of the two time series plots the data is not highlighted in the scatter plot. However, when I brush data in the scatter plot then the data is correctly brushed in the two time series plots.

You can find an example [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4DnHjQAhrywBtMRFAQVUSjKmkc8KQFsCpSOupSAtAQDsARgCcUgEZ97UhhYYAmGwFZ3BLwA4+fw97KwtKKyl-aCtIEUUVSF0pACcAa0MAB1hkeF5RVQhIAklYSlz0LGVCorgAG1gUrQSamARy6mQELTwpOoBXAyxIAGdqAgI6+wGDdlHJgmhO7uGRhaXGpndY+JrVXpnDOu5qVBSpAE9IFpVdvcgADx7qC8yhqABHfqk85BNO3CzKAoSaUQwAITiBXuVyqkBeb0MXx+nX+yEBkDmILqYOGAGE4jc7vs1nVFst4M09lBSeTNtsqdSoAj3pBcuMUrg+pibvsVlA5LpYP01pRYER4OwKPAxUQMEKRQR+pkALpgAB8YGlsvlwrWQsBAEIeUyoCU4OV4KgRqQ5I9MVArirodT4ed4CM6jJWYK9QRZZKtbkdQq1sq1ZrteLdYqDQRjS77gAvWCwXSGIicSYJ3mJZLpHooOp1QwAYj4FYdkCLdQA8pkpNA-rCwEwAHRWdxeOZjFKwNKszN-AzE+4pAgjWB1DHDVANZwl3OCIkJUfVfZei4EJryXPr+7GTRwnT6QyH8zWOyOZyuDzeXwBIIhMIRKIxKG5or5jLDY7wWafmapSWpU2CAbUU6NIypoQTKfxdJScJcocqzjJM0yDFWtJLAhhjYdQ9I7ImpoHJhv4nGclzXDBYCjq6TxwiyhjjLo2TnCWWKEDihgAIIfjRkAtjgTHDMivxohinGghChKmsu1J0So+6tIePQnqy56WLYDhOC4bieD4fiBME7ihOEkTRERgFJKkP5QNk7ImkyxTARU0HOfUUFVOBiQSB0uFIX0ZE0mhUyHD26wUnhkWEfxNFQMhwWQMcqA8JRVw+YprQMWQInMgQrGNNyUnccMfFZYUgnPK8rJiaiMjokC1ZcbiUCQvJTIVUU+EBWBAn4bF3nxcyNWGOy27IU5An8pAvqKgGUrBtGoZKqqGpBjKy1+nGObDS5FoVDa8j2nMTrEc51Dup63qGHNorioGUZyit4brU9Mb6rARpTTBkApmmGZZnUu3xTZBZwjWZYVnwVY1vWjbNqQ7adt2IV9gOgPDnFAnjpO06snOsALtRMEdQpS43Cqq6JspUCbtutp7tZqnHnoGkaBe2nXnpd6GY+Jlma+lnY-c35ZDkeQ-a05plG5Q2-Z5O59aDfnwfyOCJayYwTGFmERWSOEzQNKRbFZe2a0cFHnBlNFdYkOXCaNwwsWxxXAi1vEi66Qnwk7nzfOJDWSe70n4rJnXnSSkW9bTrTG6b7kkXlbJ5BNxU+UUM13f6D2LZtz1+q9kZLQXsZffGUvOTLIFHWAdpPKdkDOhnzJXV64y3StC0bSGhdrcX+cfQV5cgwJ-3psMmY66Pv1ixDyDFlDlaccW8NNi8SMdl2PaXf2g60Fjdv7LjU4zlAhPE5lgFk4UFWx4kLNkOpZ4c1pV66beBkPsZz7mW+ZvOTnnTXIAESLVzlsrEiitE4eXaGrRCZALaoR1hhJqPUjYxRNgyI+iQkHANSqca2JM5KR0qg7X2iJnYFVdhxEOpUoDlVIfsH2yc6p-CDk1bErVIAEhvjUPhtxKarjEM3IoAASEY0BODJEMDwagmQRgYAAPRKMBKgKQbZUB-FoP0ewbYuhKMkdIqQqiCDqNMMccYqj3BtgAGxtnbAAK0nJSaERgNBrGoLXfc7iTCc3fjefS94jJPlMi+Cy75dw1HvpAPiwx3BMFsKYLYpgrBMAACosAwFklgySLDZKYJXIokIsDtgSQwHwNhbH+DSUwWxFgakMH8KQnhpBkltj4O4TwDAql8BsBWTwFgLBMC8ESc6MS4lQASUklJaTMlMAwFYLwBS8kFKKW1TeTAKmdP8A0nwNTbFdgYHwFpBIsCpLbMMgI7g+CdhsMwJgFYLC2LGTcCZhhpk2GSe4VJGSskCBWUwfJLB1mQBKa2DsVhbCeHcP4LwTSbmdKsLY05m8vDQtsbYjwgRkUMAYLYmwrzom5liR8xJXzZl-IWRUwFwLCktPBe2Cw8KvB1PqTcuFcL6moqwFYBxNgtg2GCAwKwfSBU2CWUSwo7z4nku+b8zJVgCm0rWQyzetitleHhbYfwNhmU9MxTyiForbFpKqVUvFQLyXuClaoGVUy5WUsVYs5ZuSgWqpJYyts-gfVuCWf0iwnS8VLKNe0twuyblMAlW4IZXggi2qUiSyZkBPnyrmYkjAAK3V0tBV61lVhmDPORXqgQ-h3AopJWciFEq4UFsRf4OpSyGkJqUEmslMyfnpqVTS7NHrXRet2T64yIyoU2CFcy0NfLbkVlNZ4W5TSrBwtGfw8ZbbZUdoVVsZVvaQVqtKZcxpzKG3PL4ASi1ob2wVJ8EsmpDavDVL4A0l5K63lrodRu9N7gXUqt3Z6zeFgbDuFvHwLwwyRmmsA0a9s97MX+FNeBht1T8UrlUFTCAy5BBAA).

**Comment by domoritz** [comment]
Can you create a gif that shows the error?

**Comment by kanitw** [comment]
Hey Dom, the spec should be sufficient here.

**Comment by kanitw** [comment]
Fine: 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/111269/54871783-2d6bd780-4d77-11e9-8bdc-bd230eaddcc4.png">

Broken:  (Nothing in the first plot is selected)

<img width="788" alt="image" src="https://user-images.githubusercontent.com/111269/54871785-38266c80-4d77-11e9-8826-c4c20b7a0b20.png">

**Comment by arvind** [comment]
I'm no longer able to replicate the original issue (see screenshot below where it seems brushing in the center plot correctly highlights points in the first and last plots). 

So, I wonder if we fixed the bug in the interim. @nfoti, please re-open if you continue to experience an issue and apologies that it took me this long to respond.

![image](https://user-images.githubusercontent.com/42262/62570715-f990da80-b85d-11e9-94bc-484203f1a618.png)

![image](https://user-images.githubusercontent.com/42262/62570827-0ca3aa80-b85e-11e9-8107-11aca58f45c1.png)
