### ISSUE TITLE
Support columnar initialization for multi selections

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#4766]
See:
<img width="1046" alt="Screenshot 2019-03-24 at 20 47 22" src="https://user-images.githubusercontent.com/5186265/54884891-6fc80e00-4e76-11e9-87a0-e381c1f322e9.png">

Validation shows that `"init": {"x": ["E", "I"]}` can be one of many options, but `array` is not one of them, which should be included as well I guess.

[Editor-spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YAO7NEYRI2qIJno0uphlN24qG3QlTTBYZDFkeF9-QPgJeABrOjAACgBJJVhCRl1kCPYATzAAFXR2GPRWAHJYMEYlPGRddDjjSLwSmLoASjUNSE10PEwcUAgISAp0MVYdbDAAbQ1psGBICagzNUh2ZYAmAA4AX1VN7eXIACF9w5wAVieLq53IAGEH5YAWaQu62mWw+ABEfjgAJwARjeIJuAFEIWATrDLvDTAAxZFPAHqDYQDFQADiyOhkLh11MAAlkScAOyUj5ZHFHM5AgC6GkBMyiMU6ymWU2mkHcnm8+CFkB6hGQN1gzWoMTUUDQhhKNyUyjll0ggtMqG4rCiwTakB5Ir5sTwUplcoNrDERhVkGazClAA9litIEjdSyOWd2RALZAMLoUkKgdKSrKblZdEMNpAAGaMMRiG4AYl+n3pJzMJyTlrwum4KXtUGqHUj+JF8FYukUidMhG4zVaie5dcgyCU8G4mkVUeTXsmqcY0U0N0wurtN24uiHSnm5rrMw147TU-jLvnpgAjqwwkZxkYqGvo2mMwB5QgdZibzZAmYD8LMYxSq0CkxQb823U5gWSs0RfKAgMWZYAAY6GkIELV5Uty2QAB1RhNBYEcCUgN8hyMfVVjAwkiJFVpYBtSYSOTMJpxwNYCQY4FIH-T9TH-S9GMYyAYj8FgMlGcYMgAHWY6JrQAfXIxdkBE-pBio6YuU4kN1y4iDKyOEiEIJLYWII0UPC8QyAPA+ZIJwWEwI5VSZnU6D4O7YY3zTagsN5eB5krYVkyscIAAV0E0ZdqByJQzRwGDNI2YMwHZdkgA)

BTW. Vega-editor update is great!

**Comment by domoritz** [comment]
that's odd. In particular, we allow an array of mappings but then crash: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YAO7NEYRI2qIJno0uphlN24qG3QlTTBYZDFkeF9-QPgJeABrOjAACgBJJVhCRl1kCPYATzAAFXR2GPRWAHJYMEYlPGRddDjjSLwSmLoASjUNSE10PEwcUAgISAp0MVYdbDAAbQ1psGBICagzNUh2ZYAmAA4AX1VN7eXIACF9w5wAVieLq53IAGEH5YAWaQu62mWw+ABEfjgAJwARjeIJuAFEIWATrDLvDTAAxZFPAHqDYQDFQADiyOhkLh11MAAlkScAOyUj5ZHFHM5AgC6GkBMyiMU6ymWU2mkHcnm8+CFkB6hGQN1gzWoMTUUDQhhKNyUyjll0ggtMqG4rCiwTakB5Ir5sTwUplcoNrDERhVkGazGWKy2AA9Eeb0ZAfaYWWcOeyIBbIBhdCkhUDpSVZTcrLohhtIAAzRhiMQ3ADEv0+9JOZhOqcteF03BS9qg1Q6MfxIvgrF0ihTpkI3GarRT3MbkGQSng3E0itjacDV0z0U0N0wurtN24ulHSnmfrjGsmGcYM6TLsXpgAjqwwkZxkYqBu05nswB5QgdZhbzZAmbD8LMYxSq0CkxQX8bV1OYFhrNE3ygEDFmWAAGOhpCBC1eQrKtkAAdUYTQWHHAlIA-UcjH1VYIMJEiRVaWAbUmMi0zCWccDWAkmOBSBAO-UxAOvZimMgGI-BYDJRnGDIAB1WOia0AH1KOXZAxP6QYaOmLluPDRtuNmeZoJwI4yKQgktjYojRQ8LxTKAyCtLAsMCQ5dSRSgmsYMQvthg-TNqBw3l4HmGthTTKxwgABXQTRV2oHIlDNHA4N0jYbPZdkgA

**Comment by arvind** [comment]
Yes, this is an intentional typings/schema design for multi-selections because an array of values is only valid when a multi selection is projected over a single field. Instead, multiple selections must be initialized via an array of objects (`"init": [{"x": "E"}, {"x": "I"}]`). #5298 preserves this workaround and polishes it to ensure that toggling continues to work when multi selections are initialized in this way.

I'm re-labeling/re-titling this issue to instead consider supporting columnar initialization for multi-selections. i.e., `"init": {"x": ["E", "I"], "y": ["A", "B"]}` maps to `"init": [{"x": "E", "y": "A"}, {"x": "I", "y": "B"}]`.
