### ISSUE TITLE
Do not set interpolation for nominal color scales

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4775]
For example in https://vega.github.io/editor/#/examples/vega-lite/stacked_bar_weather, we should not set the `interpolate` property on the color scale.

**Comment by kanitw** [comment]
Can you provide more context?

**Comment by kanitw** [comment]
Instead of saying good first issue, I think you better just fix it since it would involves only < 20 LOCs.

**Comment by kanitw** [comment]
Took me 5 mins to fix in https://github.com/vega/vega-lite/pull/4816 :p
