### ISSUE TITLE
bandSize parameters ineffectual on Bar mark

### ISSUE THREAD

**Issue by jtbaker** [vega/vega-lite#4783]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "width": 120,
  "height": 120,
  "config": {
    "bar": {
      "discreteBandSize": 50,
      "binSpacing": 10
    }
  },
  "data": {
    "url": "data/cars.json"
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "Origin",
      "type": "nominal"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

Setting `continuousBandSize`/`discreteBandSize` from the top level `config` seems to have no effect, and it's not clear from the [documentation](https://vega.github.io/vega-lite/docs/bar.html#configA) how to set them from within the encoding channel. not totally sure if this is an API change or a bug - but I'd ideally like to set the maximum width of a band on a bar mark, and let it autosize when it is below that width.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/4817

**Comment by jtbaker** [comment]
Thanks @kanitw! Will the updated changes be reflected in the `https://vega.github.io/schema/vega-lite/v3.json` $schema when merged - or do I need to get a new version of vega-embed/vega-lite from NPM?

**Comment by kanitw** [comment]
It will be included in the next release, and you need to get the new version from NPM.  The schema is only for validation -- it doesn't affect the program's behavior.
