### ISSUE TITLE
Having 3 plots where two shared x scales make brush work incorrectly. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4784]
This one has a different root cause from #4779.

In this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2XAWJkhtBszace10dt2xkeWKRfpSAMwnU+LAiAEwA1vKKKgC+6hCQFPDK8DpmANoaEMAQmRBQAO6MmixmAIwArAAMqjl5eZAojIF4ZlVxdVDISkmajErUZtl5uXWQAB6DIx2Q7H2DkBhjs0qwZiGVsVOjvozIYppmkL2wut3Ialv1eACehOc4kACOrOhKeMw6jFSQl5sd9ddJv9RuhqNQjMI8PcoElWG8LsCrrdoU8Xm8Pu9vr8pn9pmJ0NdkEZ0pdQIj4hgjGFDux0MT2ojIG4xMh4O9lEDyfF2EZWLBEJyufEbndDn0oUYKOhTAyhZAuj0+tRVjg0uNIABdWVc+WoQg3Q5KZTnbXkyAQxRib4PcVEtxsn5CsDRS4QF2I3H-MlmvBGV6wXzcIyodIGHZiCXzZms9kqB48vkC6LRLWuqCU6n6SAilG0+kw7hiIOHaiFzRdIzcA7u4E1uoa3Kxb2jRLJVKqsCktOQQrFAU4CrVTs6xrNVrVbsKqtKwVmib6NOjZbzRbLFVgdaeuU7PYHB7l-GA02MnOHZ6vd66THnRfO4-TQELp3xUHgyEo2Hw+--bPIs9oy9PixJ061rGpu0PIl0mHIVslvCk6UzKA8wRZ8mT2GMeDjMBmzQhN+VnZ8oFPG03iJKUZXg6Yp16fp1zVCZUyI0Y0H1R8oCNJQTSo0YLULa0oFtIx7RaGCiOiMShQk2opJqSTEVwnVfX9QNg1DSBw0jLNozZLCaV5AjkyYtCM3mEjkLpNQCyLYkHlLfYKyrSBQI9NMGw9OT5LyRTpl7EoBzabtR3wMpAp1GiZyfOV5xwjTdn2Q4DwJKzf1FB5z3RK8vnOLdGXYsN4r3LRGBOV54BNYi-3SgCMWy5y01yvECSgjtbzgoiFkQw54EYIx4BZVCnXQlldI5KKOvw-scJ4pE0sEsjJWlQbmN1NjDWNZaOr4q0USEkTHWYlzySO-5Gq9Kjsz9FZVJDVUCojFrYp02N9MTZyU2-aZTKzczIB6vqBpqP7C2LOyy0c6tbxOvJ3NrKZjN45BLQEgwEGlaEDBiplEDpZBq1AmtjPNJH+IxyAWWoLoitRxgAC9dqUcs7kZroWiBpIbLFFnmfLeFkxAaIgA), there are 3 plots and the bottom two share the x-scale. The brush doesn't always update correctly esp. the top one.  (Sometimes brushing on the middle plot works fine, sometimes it doesn't.  I can't summarize when it goes wrong yet. 

![3plot-2shared-brush](https://user-images.githubusercontent.com/111269/55109980-3f5dbb00-5094-11e9-8ea0-37146fc06c27.gif)

However, making the bottom two use independent x-scales by removing `"resolve": {"scale": {"x": "shared"}}` makes the problem disappear. 

Note that this is still a problem even on the https://github.com/vega/vega-lite/pull/4780 branch, so it's definitely a different issue.

**Comment by kanitw** [comment]
Hmm, I'm not sure if shared scale is the problem anymore since [this spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2XAWJkhtBszace10dt2xkeWKRfpSAMwnU+LAiAEwA1vKKKgC+6hCQeEboSrC+3EaoZgDaBvDoYvCsYjrIZpCI3MawABQurKh0LsgAlGpQ6LBleIyopdEAunFQFPDKeXjZGhCgELNQAO6MmixmAIwArAAMQ3PlyIyBEzhbO7OQyEqjmoxK1GYzc2cAHvdTj-HsN-eQGE+fKWYQptYm93pBfIxkGJNGVrrBdJdSqcwXgAJ6EUo4SAAR1YyW6um6VEgoNmIPe8VR33Q1GoRmEeExUFGrCUE1UUDRGLKuPxzB0jGJHISzDETMgAGFKmzINFSeTHpBiqjkEZJhSwA8NT90EYwmV2Lq1KTdm4xfBuspXhrduwjKxYIhvlzxTdGUYKPk2udLtxrrdOjgspAXoMoGhCGiykplH0TWT4wr3lqKQkkik0hlsgYIWJ3d8zcgLTwVFi7Q6ndEBsjFRg9c70eLDWrhaMxOkytRuNCLkY-bLE6T+m8k5rSeVRpcdOqKSmwSMxtOg-G5nObZBFssnTgNtsV4qUAd8GYTvvdhcrjc7voz4qXjebev-t9fv9A2AgaPH7sIVCYVjNChdAqRrb9OUbHk8TZfkiVKW85i-b9ICpB8wMVGk6QZcUWRlUCkJdSC+UJQUkXgxUCTFMopVZCYyIgOU0LARDtWVVUZ0YtcwJ1esyyNPDH0gQtiytVDGNte1HWtMSUQgrE3VVT1TH4tCfUvANshDSBBjo1MIyjLEYyUODpIQnT6J05ibU4-D01SdJMiDHNGDzNj9EEqEi0tUsoHLSSq20kyoDrfU3II3iW2ZbsOyxLseyUPsYQYsSkrA4cwMs1cyI3JYVh3U9GL2I8jjAXdlPPX1-WvMdpM0tzf2hWEgJA8DuSxXloOI4kMtTFDNXBSEGoAxh4WSeAkRa8V2oJAUurI7rdlYtVl2k6yBOCsp4EYIx4EosrUyErypMCyBfO3PqwqgeSPS9YU9N6yBDL6PbtQqKgluqwKzguwSr12szFREoLKjcbg3uNT6zju6NYxJCGUuSizntmVb10SZI7KzZbPpRrjc3zUSIagaKwBydzzUOssJMrDkDAOksyletiBn+0y4f+gKTO4kLztk5ktp28bIDbYnIFiwD4v7eH0rItLvylx5ZfeSyUcgBcp2KrJbxxs5N1ykr8pUw9DhPPcCovP0ryOlT7w+mrnzc18bnfT8kZ-Ab-05HpSOO76ppgkjYeS12oF67WwQw+laEZDbpXZf6El5nEoOm2Dwc5ijxWomULLmpGlWA1ySZ0sPa11bmTr4+O6cBkuwVOq2fcTq7FLTiHVIt9Sg00jm26hgyYZZpj-vlx95seWuvtszMHJJpyXPe2mPOE7yTqp2Vq3j9bQsT5tvWF97Re7cWEoHaSR4pRWbTHkvsq3NYDa4o3jzy02VPNyqG6Qm2nL-Love9X2yd-ZdWDshb49UPaQDhAiMaADE5+06nGRiY94iLXYmhCe8Qt5822n9Y61dvKYLOPXberVLpsgUjdcMqBIz3UerKYOuxGYL0HvEb6sBfre0JpAQGPxgbIFBmxDkrDqG0OhkZQOgVz6j0RsXeOaMMz2XQStER-V56f2OsTUmBCDRr1iH1HRWJmGykvlIwe0ibQ9zElzBsZChb812pFdsB8xa9kljnRipiKQWK8eZd4l8koc0gPSRQYhiRuTFNQC4HtaaMAAF6uiUIBDESSLjsicSLG4yTolpPXiAaIQA),  which have no shared scale, also has a problem with the brush on the scatter plot:  
(Deselection doesn't really clear selection.) 

![broken-deselect](https://user-images.githubusercontent.com/111269/55114503-51912680-509f-11e9-882f-14c4a281b3b8.gif)

It could be that this is a different issue though.

**Comment by kanitw** [comment]
The first [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2XAWJkhtBszace10dt2xkeWKRfpSAMwnU+LAiAEwA1vKKKgC+6hCQFPDK8DpmANoaEMAQmRBQAO6MmixmAIwArAAMqjl5eZAojIF4ZlVxdVDISkmajErUZtl5uXWQAB6DIx2Q7H2DkBhjs0qwZiGVsVOjvozIYppmkL2wut3Ialv1eACehOc4kACOrOhKeMw6jFSQl5sd9ddJv9RuhqNQjMI8PcoElWG8LsCrrdoU8Xm8Pu9vr8pn9pmJ0NdkEZ0pdQIj4hgjGFDux0MT2ojIG4xMh4O9lEDyfF2EZWLBEJyufEbndDn0oUYKOhTAyhZAuj0+tRVjg0uNIABdWVc+WoQg3Q5KZTnbXkyAQxRib4PcVEtxsn5CsDRS4QF2I3H-MlmvBGV6wXzcIyodIGHZiCXzZms9kqB48vkC6LRLWuqCU6n6SAilG0+kw7hiIOHaiFzRdIzcA7u4E1uoa3Kxb2jRLJVKqsCktOQQrFAU4CrVTs6xrNVrVbsKqtKwVmib6NOjZbzRbLFVgdaeuU7PYHB7l-GA02MnOHZ6vd66THnRfO4-TQELp3xUHgyEo2Hw+--bPIs9oy9PixJ061rGpu0PIl0mHIVslvCk6UzKA8wRZ8mT2GMeDjMBmzQhN+VnZ8oFPG03iJKUZXg6Yp16fp1zVCZUyI0Y0H1R8oCNJQTSo0YLULa0oFtIx7RaGCiOiMShQk2opJqSTEVwnVfX9QNg1DSBw0jLNozZLCaV5AjkyYtCM3mEjkLpNQCyLYkHlLfYKyrSBQI9NMGw9OT5LyRTpl7EoBzabtR3wMpAp1GiZyfOV5xwjTdn2Q4DwJKzf1FB5z3RK8vnOLdGXYsN4r3LRGBOV54BNYi-3SgCMWy5y01yvECSgjtbzgoiFkQw54EYIx4BZVCnXQlldI5KKOvw-scJ4pE0sEsjJWlQbmN1NjDWNZaOr4q0USEkTHWYlzySO-5Gq9Kjsz9FZVJDVUCojFrYp02N9MTZyU2-aZTKzczIB6vqBpqP7C2LOyy0c6tbxOvJ3NrKZjN45BLQEgwEGlaEDBiplEDpZBq1AmtjPNJH+IxyAWWoLoitRxgAC9dqUcs7kZroWiBpIbLFFnmfLeFkxAaIgA) is not problematic in VL3-rc12 and VG 4.4 -- so there must be some regression since.  

(Tested using Vega-Editor `v0.23.2`)

**Comment by kanitw** [comment]
The second [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2XAWJkhtBszace10dt2xkeWKRfpSAMwnU+LAiAEwA1vKKKgC+6hCQeEboSrC+3EaoZgDaBvDoYvCsYjrIZpCI3MawABQurKh0LsgAlGpQ6LBleIyopdEAunFQFPDKeXjZGhCgELNQAO6MmixmAIwArAAMQ3PlyIyBEzhbO7OQyEqjmoxK1GYzc2cAHvdTj-HsN-eQGE+fKWYQptYm93pBfIxkGJNGVrrBdJdSqcwXgAJ6EUo4SAAR1YyW6um6VEgoNmIPe8VR33Q1GoRmEeExUFGrCUE1UUDRGLKuPxzB0jGJHISzDETMgAGFKmzINFSeTHpBiqjkEZJhSwA8NT90EYwmV2Lq1KTdm4xfBuspXhrduwjKxYIhvlzxTdGUYKPk2udLtxrrdOjgspAXoMoGhCGiykplH0TWT4wr3lqKQkkik0hlsgYIWJ3d8zcgLTwVFi7Q6ndEBsjFRg9c70eLDWrhaMxOkytRuNCLkY-bLE6T+m8k5rSeVRpcdOqKSmwSMxtOg-G5nObZBFssnTgNtsV4qUAd8GYTvvdhcrjc7voz4qXjebev-t9fv9A2AgaPH7sIVCYVjNChdAqRrb9OUbHk8TZfkiVKW85i-b9ICpB8wMVGk6QZcUWRlUCkJdSC+UJQUkXgxUCTFMopVZCYyIgOU0LARDtWVVUZ0YtcwJ1esyyNPDH0gQtiytVDGNte1HWtMSUQgrE3VVT1TH4tCfUvANshDSBBjo1MIyjLEYyUODpIQnT6J05ibU4-D01SdJMiDHNGDzNj9EEqEi0tUsoHLSSq20kyoDrfU3II3iW2ZbsOyxLseyUPsYQYsSkrA4cwMs1cyI3JYVh3U9GL2I8jjAXdlPPX1-WvMdpM0tzf2hWEgJA8DuSxXloOI4kMtTFDNXBSEGoAxh4WSeAkRa8V2oJAUurI7rdlYtVl2k6yBOCsp4EYIx4EosrUyErypMCyBfO3PqwqgeSPS9YU9N6yBDL6PbtQqKgluqwKzguwSr12szFREoLKjcbg3uNT6zju6NYxJCGUuSizntmVb10SZI7KzZbPpRrjc3zUSIagaKwBydzzUOssJMrDkDAOksyletiBn+0y4f+gKTO4kLztk5ktp28bIDbYnIFiwD4v7eH0rItLvylx5ZfeSyUcgBcp2KrJbxxs5N1ykr8pUw9DhPPcCovP0ryOlT7w+mrnzc18bnfT8kZ-Ab-05HpSOO76ppgkjYeS12oF67WwQw+laEZDbpXZf6El5nEoOm2Dwc5ijxWomULLmpGlWA1ySZ0sPa11bmTr4+O6cBkuwVOq2fcTq7FLTiHVIt9Sg00jm26hgyYZZpj-vlx95seWuvtszMHJJpyXPe2mPOE7yTqp2Vq3j9bQsT5tvWF97Re7cWEoHaSR4pRWbTHkvsq3NYDa4o3jzy02VPNyqG6Qm2nL-Love9X2yd-ZdWDshb49UPaQDhAiMaADE5+06nGRiY94iLXYmhCe8Qt5822n9Y61dvKYLOPXberVLpsgUjdcMqBIz3UerKYOuxGYL0HvEb6sBfre0JpAQGPxgbIFBmxDkrDqG0OhkZQOgVz6j0RsXeOaMMz2XQStER-V56f2OsTUmBCDRr1iH1HRWJmGykvlIwe0ibQ9zElzBsZChb812pFdsB8xa9kljnRipiKQWK8eZd4l8koc0gPSRQYhiRuTFNQC4HtaaMAAF6uiUIBDESSLjsicSLG4yTolpPXiAaIQA) is definitely a different issue since it's problematic in both latest editor and editor v0.23.2.  

I've simplied the issue and file it separately in https://github.com/vega/vega-lite/issues/4790

**Comment by arvind** [comment]
As far as I can tell, the first spec linked to in this issue is working in v4.0. Please reopen if it's still broken.
