### ISSUE TITLE
Filter with "or" between two selection does not update correctly . 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4790]
Forked from https://github.com/vega/vega-lite/issues/4784#issuecomment-477360568. 

Origin GIF from the original issue

![broken-deselect](https://user-images.githubusercontent.com/111269/55114503-51912680-509f-11e9-882f-14c4a281b3b8.gif)

[Simpler Spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdlwFiZIbQbM2nHrdHbdsZHlik36UgDMJanxYEQAmAGt5RRUNAF91I2QleG5NRiVqCwNDSAAPbI1DKH9GZDFNC0hNcvQATzUi3Lw6wmQqgEdWdCU8Zh1GKkgmhKbIBv0mo1LyypxqxlhdFPbE4qgWts7u3v6+oZH4tcgxeuQTCwBtJpziyAwTCKr4RhN4MVWpqA8P+D7lQrrXLsEysWCIQFA5qtdrzDJ4c4UdDmNZQqBoQgtKpKZTtL4QUZoyCIbhUC6TNFGTaw74ZagfRqUqAA+aobhg5Ck86MymQDFY+Y4pR4tFxL5i4qEwy3ZomHqwfzcEyoK74sAyoGQUpiBHk9Vqu5K1VM4oak2QH7IP48FTzEFgiEG9ZSk36113S3Wlm4LkXJ2S-1gAC6TolULDxSDqNyDyeFKhkGpz1e70+RNSYiN82o3AqyRMaWGQIjYDDIbiQA)

**Comment by arvind** [comment]
Linked spec appears to be working in v4.0. Please reopen if needed.
