### ISSUE TITLE
Stacked bar not working

### ISSUE THREAD

**Issue by eibanez** [vega/vega-lite#4796]
Hi,

I am in the process of upgrading to vega-lite 3, but I run into an issue. The spec below used to produce a stacked bar chart, but it does not in the new version.

If I add `"stack"` to the `y` channel and a value other than `"zero"`, the stacking kicks in.

I don't see this issue in any of the examples in the website and documentation, but all of them seem to use an aggregation transform, instead of the raw values, like the spec below.

Thanks in advance for your help!

```{
    "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
    "data": {
        "values": "a,b,c,d\r\n1,1.4,a,2\r\n1,4.0,b,3\r\n1,2.0,c,1\r\n2,2.2,a,2\r\n2,2.0,b,3\r\n2,2.0,c,1\r\n3,2.0,a,2\r\n3,2.0,b,3\r\n3,1.7,c,1\r\n",
        "format": {
            "type": "csv"
        }
    },
    "mark": "bar",
    "encoding": {
        "color": {
            "field": "c",
            "type": "nominal"
        },
        "y": {
            "field": "b",
            "type": "quantitative"
        },
        "x": {
            "field": "a",
            "type": "nominal"
        }
    }
}
```

Link to example: https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg5oGNRzUI12gDoAnF8oCMar-QAsanYATO6ePv70AAz2ajJh3mrB0Y6+CcFJ9Bkh6ZkxDvEeyhnJMU5eCTJ5QUmV1QV1fgDsqRVF6pom0ABmPG6Y+DZGXSZQ+ACeRCg2UAhwlFCdJgC+S8saxlCYbgDWMxwYbh2bKMoIPNpMyjRDS5vn4n23I6PdTCji2jMIxy9aE1MZsoeGgruZFi91nctONnn8IFA3h8vrgoBxfvCxpNpqiAI5sDDKfAsPRMagQkZQl5QAAecMxSM+MywG3h0ABOOgwNBynB0Igq2Mq2WQA

**Comment by eibanez** [comment]
This issue seems to affect stacked areas too:

https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg5oGNRzUI12gDoAnF8oCMar-QAsanYATO6ePv70AAz2ajJh3mrB0Y6+CcFJ9Bkh6ZkxDvEeyhnJMU5eCTJ5QUmV1QV1fgDsqRVF6pom0ABmPG6Y+DZGXSZQ+ACeRCg2UAhwlFCdJgC+S8saxlCYbgDWMxhuKFgbWijKCDzaTMo0Q0ubF+J9dyOj3Uwo4tozCB2vmxMpjNlDw0NdzItXut7lpxi9-hAoO9Pt9cFAOH8EdBAdM0QBHNgYZT4Fh6JjUSEjaGvKAAD3hCKRHy++0xjJxwNB4PElK6q2Mq2WQA

**Comment by eibanez** [comment]
More info:

I compared the compiled vega schemas with and without adding `"stack": "normalize"` and they were nearly identical. There were only two changes:
- The `offset` value in the `stack` transformation
- The domain of the y scale

Both changes are as expected, so I wonder if this is a vega issue.

Thanks for looking into this!

**Comment by eibanez** [comment]
Ok, some more digging... It looks like the issue is that the values for the `y` encoding are not being interpreted as numbers but as strings, when reading the CSV string.

![image](https://user-images.githubusercontent.com/438494/55234619-8b764000-51f9-11e9-9d4b-f1e3d50e622d.png)

**Comment by eibanez** [comment]
Ok, I can make it work if I add `parse` to `format` inside `data`. That adds the `formula` transform that vega-lite 2 used to add automatically

I guess the only lingering questions is whether the type inference could be automatic. @kanitw @domoritz ?

Fixed graph:
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxR0q9qvirNAHQBOTpQEZVHugBZVNgBMru5evnQADLaq0iGeqoGR9t5xgQl0aUGp6VF2sW5KaYlRDh5x0jkBCeWVeTU+AOzJZQVqGkYAZtwuGHhWwJB4AJ6EyFaQ8LAUalCE6C6wY1gD7ONKrKjsyC6QAL67GrvqRhguANbj7PNtRshK8NyajErU-e1QD2Ld-ZAdjMhiTTjeAzQYjJZQJTcVDPUx7Y6GSBDH5-AFAnCQVaqKDDUbjACOrHQSjwzB0jCo8PekAAHij-oDxphsWC8RioTClHCDhADrsgA

**Comment by domoritz** [comment]
Thanks for the debugging. We either have to parse in Vega-Lite or change Vega to not expect numbers.

**Comment by eibanez** [comment]
No worries. The new-and-improved editor made this a lot easier.

**Comment by domoritz** [comment]
@jheer The issue here is that the stack transform does not automatically parse the `field` as a number. Should we update Vega to do this (similar to how Vega parses aggregate fields to numbers automatically)?

**Comment by domoritz** [comment]
https://github.com/vega/vega/pull/1740 may be enough.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega/pull/1741

**Comment by eibanez** [comment]
Thanks! @domoritz @jheer
