### ISSUE TITLE
Expression parse error - Space in Field Name

### ISSUE THREAD

**Issue by suhasgupta1** [vega/vega-lite#4797]
Hi All,

I am getting Expression parse error for the step below:
      "format": {"property": "aggregations.heatmap.buckets", "type": "json"},
      "transform": [
        {"type": "formula", "expr": "datum.key.Tf", "as": "Tf"},
        {"type": "formula", "expr": "datum.key.City", "as": "City"},
        {"type": "formula", "expr": "['datum.key.Analysis Date']","as": "AnalysisDate"},
        {"type": "formula", 
        "expr": "'Tf:\\t\\t' + datum.source_0.Tf + '\\nCity:\\t\\t' + datum.source_0.City + '\\nTotal Sales, s:\\t' + datum.source_0.Total_sales + '\\nAnalysis Date:\\t' + datum.source_0.@['Analysis Date'])","as": "tooltip"}]}

If I remove datum.source_0.@['Analysis Date'] from last expr then it works fine,So I am sure that it is because of _Analysis Date_ that too I think because it is time field and also it has space in the name.  I tried below:
datum.@['source_0.Analysis Date']
datum.source_0.['@Analysis Date']
@['datum.source_0.Analysis Date']

Please help me in resolving this error.

Thanks & Regards
Suhas Gupta

**Comment by kanitw** [comment]
This seems like a Vega error.  
If you have a Vega-Lite spec, please reopen and provide a full Vega-Lite spec to reproduce the error.  Otherwise, we can't really help you.
