### ISSUE TITLE
Make syntax consistent with datalib & vega

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#480]
- [ ] ~~aggregate => summarize~~
- [x] avg => mean
- [x] name => field
  - [x] rename existing `field` variable to `fieldDef` first 
- [x] `col` -> `column`

**Comment by kanitw** [comment]
@domoritz @jheer   

I think we should pick ‘mean’ over ‘average’ because it will take less screen estate in the field list.

**Comment by domoritz** [comment]
I prefer average because mean and median sound so similar.

**Comment by kanitw** [comment]
Hmm I don't feel that mean and median sounds that similar ...

**Comment by kanitw** [comment]
I think AVERAGE is way to long in the UI here.  

MEAN is 4 character, while MEDIAN is 6 so they are different enough.  

![data_voyager](https://cloud.githubusercontent.com/assets/111269/8816670/37589c2e-2ff8-11e5-9329-da86d94af284.png)

**Comment by kanitw** [comment]
@jheer @domoritz 

When we rename `name` => `field`, we need another name (for variable naming and for documentation) to refer to the property object in the `encoding` key-value object.  
Currently in vega-lite, we refers to this object as `field`, which is misleading.

I’m thinking about a few candidates:
-  "encoding property definition”/`def` or  "encoding property object”/`prop` (because it contains property for each encoding channel)
-  "encoding value object”/`encVal` (because it’s the value in `encoding` key-value pairs/dict) 
  
Now I prefer "encoding property definition”/`def`, but let me know if you have a better suggestion. 
Otherwise, I’ll go ahead with "encoding property definition”/`def`.

**Comment by kanitw** [comment]
@jheer @domoritz   I also start thinking that we should keep `aggregate` property name since `summarize` in vega is aggregate transform’s property which expect a mapping between name and ops (for the short format) while `aggregate` here just expect the op.  

Since we expect different property format in these two cases, using the same property name could be misleading.

**Comment by kanitw** [comment]
From a conversation with @domoritz, we think `encDef` is not a bad idea.

**Comment by jheer** [comment]
Is this discussion solely about variable names in the vega-lite compiler
code? If so, I think this is fine. If instead this relates to something
that actually surfaces into the Vega-lite JSON spec, let me know.

**Comment by kanitw** [comment]
We are discussing a few things in the comments here.  Only the last topic affects vega-lite spec syntax. 


### Mean vs average

(old discussion) `avg` -->  `mean` vs `average` as the default in UI --> we prefer `mean`.


### Encoding property definitions / `encDef`

This is about variable names in the vega-lite compiler and __how we refer to this object in the documentation__.  

For example, in the doc for [encoding mapping](https://github.com/vega/vega-lite/wiki/Encoding-Mapping) I mention that 
> Vega-lite's top-level `encoding` property is a key-value mapping between encoding channels (`x`,`y`, `row`, `col`, `color`, `size`, `shape`, `text`, `detail`) and encoding property definitions.

> 

(__Note: we are considering to rename `encoding` property to `mapping` – see #607__)


### Aggregate vs Summarize

> @jheer @domoritz   I also start thinking that we should keep `aggregate` property name since `summarize` in vega is aggregate transform’s property which expect a mapping between name and ops (for the short format) while `aggregate` here just expect the op. 
> Since we expect different property format in these two cases, using the same property name could be misleading.  

This is actually related to the `aggregate` property in the vega-lite JSON spec.
