### ISSUE TITLE
Binned facets have incorrect title string

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4805]
[This editor example showcases the problem](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOChL0qZNih4ATsjETYAfXboDY5AE81GyABNkCA40J4eKnJAAqKGB+RiaMsGBOYYRi6LZg7HEAQsjwANbIBmDIeGDoYnRgKGKEyE5ZsHjo7KaIYLAYJmCorGJe0a654ehggDgEhNwA7hkAZi1NKYjoSmGoYMPcmaxKLgYVU5FK1GCMSngZ6PBeyuE7dXiskR3cw4WDuWBGsP1KsMgRyCXL4cpZAB7RU3QeAWcQoVkYVRssEAuAQFAASGTeQweHwM3CcrHgb26hmMpjA1zAiSsNjitkYxic4WGaNmLDeAEYAJzSAAMsFUYHg3FQ7T2YAGzFqGB2ImQw2GKTw3wMKx2W2BcwOjAklX53N54MUSjoDggziBmBwwEgrGsegNlVIlmsdnk2sgAF91PqMAZUhb4IwDPAbHqoNyxKxUC89NIXVBkEpuRtqHpQBB9cMDtl4xpE1BhhSxE4LeTKf6M5A8LYShaFhs8mooOwdnpDKxkOmwM7m5B7Mbm0ns7nfGD3Nl7BGiyWy74lDydlXh4nIAg8rpjZADFNqMgAMp7Qh6BkAJkdzdbRdgjAAXouwCb0NRqEZaHtPdwlnhq8XSxfIABHVhTLxqxhUE6GgHgeQA): the title string has `NaN` instead of a proper bin boundary.

Examining the compiled Vega, the error appears to be that the facet definition is missing a groupby term. Below, the missing term `"bin_maxbins_10_yield_end"` should be included in `from.facet.groupby`:

```
      "title": {
        "text": {
          "signal": "parent[\"bin_maxbins_10_yield\"] === null || isNaN(parent[\"bin_maxbins_10_yield\"]) ? \"null\" : format(parent[\"bin_maxbins_10_yield\"], \"\") + \" - \" + format(parent[\"bin_maxbins_10_yield_end\"], \"\")"
        },
        "style": "guide-label",
        "frame": "group",
        "offset": 10
      },
      "style": "cell",
      "from": {
        "facet": {
          "name": "trellis_barley_facet",
          "data": "source_0",
          "groupby": ["bin_maxbins_10_yield"]
        }
      },
```

When I add the term, the example appears correct.

**Comment by kanitw** [comment]
Thanks for the detailed info, making it really to fix. :) 

This will be fixed in https://github.com/vega/vega-lite/pull/4814
