### ISSUE TITLE
Alignment for header labels

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4815]
[This example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOChL0qZNih4ATsjETYAfXboDY5AE81GyABNkCA40J4eKnJAAqKGB+RiaMsGBOYYRi6LZg7HEAQsjwANbIBmDIeGDoYnRgKGKEyE5ZsHjo7KaIYLAYJmCorGJe0a654ehggDgEhNwA7hkAZi1NKYjoSmGoYMPcmaxKLgYVU5FK1GCMSngZ6PBeyuE7dXiskR3cw4WDuWBGsP1KsMgRyCXL4cpZAB7RU3QeAWcQoVkYVRssEAuAQFAASGTeQweHwM3CcrHgb26hmMpjA1zAiSsNjitkYxic4WGaNmLDeAEYAJzSAAMsFUYHg3FQ7T2YAGzFqGB2ImQw2GKTw3wMKx2W2BcwOjAklX53N54MUSjoDggziBmBwwEgrGsegNlVIlmsdnk2sgAF91PqMAZUhb4IwDPAbHqoNyxKxUC89NIXVBkEpuRtqHpQBB9cMDtl4xpE1BhhSxE4LeTKf6M5A8LYShaFhs8mooOwdnpDKxkOmwM7m5B7Mbm0ns7nfGD3Nl7BGiyWy74lDydlXh4nIAg8rpjZADFNqMgAMp7Qh6BkAJkdzdbRdgjAAXouwCb0NRqEZaHtPdwlnhq8XSxfIABHVhTLxqxhUE6GgHgeQA) has unaligned headers.

![image](https://user-images.githubusercontent.com/111269/55284286-721fe180-5328-11e9-9d38-b29448007e69.png)

**Comment by domoritz** [comment]
They are aligned with the chart area, no?

**Comment by kanitw** [comment]
I understand why it's appearing like this, but ask any graphic designer they will say this is bad :)

**Comment by domoritz** [comment]
Ups, now I see what you mean. I thought you were complaining about the horizontal alignment (which I think is good). The vertical alignment is definitely bad!

**Comment by jheer** [comment]
Good catch @kanitw!

**Comment by kanitw** [comment]
It is now align as of Vega 5.8.1, Vega-Lite 4.0.0-beta.12
