### ISSUE TITLE
Add labels boolean flag to header object?

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4835]
To disable facet headers one needs to remove the title and also the labels. For the former, (`title: null`) works just fine! For the latter, we have to do something like (`labelFontSize: 0, labelPadding: 0`) -- but it would be easier and arguably more intuitive to also support a boolean flag `labels` (just like axes!) to disable labels with a single property.

Here is a motivating example: https://observablehq.com/@vega/psr-b1919-21-with-vega-lite

**Comment by kanitw** [comment]
Yep, totally agree.  Will fix in https://github.com/vega/vega-lite/pull/5032.
