### ISSUE TITLE
Porting guide disappeared

### ISSUE THREAD

**Issue by jonathanzong** [vega/vega-lite#4838]
There was a Vega-Lite 1.0 -> 2.0 porting guide at this url that seems to be no longer present: http://vega.github.io/vega-lite/docs/porting-guide.html

Has this been moved to another place? If not, could we get it back up?

**Comment by domoritz** [comment]
It was deleted in https://github.com/vega/vega-lite/pull/4670. You can view the file at https://github.com/vega/vega-lite/blob/e30bbbfa9c19c19a3f96b22779ade2554a293451/site/docs/portingguide.md

**Comment by arvind** [comment]
But why was it deleted? We still have porting guides up from Vega 1-> 2 and 2 -> 3. Seems like an unnecessary deletion that makes things more difficult to find?

**Comment by domoritz** [comment]
I didn't expect anyone to still use Vega-Lite 1.

**Comment by jonathanzong** [comment]
Lyra's currently migrating from Vega-Lite 1. 

People will have any number of reasons not to migrate right away. It costs nothing to leave it up, and I think there's a lot of value in having it available.

**Comment by domoritz** [comment]
Instead of putting it back on the main website, I propose that we make a copy of the v2 website (similar to https://github.com/vega/vega-lite-v1) with the v1->v2 porting guide so that people can look up the docs for Vega-Lite 2. Does that sound reasonable?
