### ISSUE TITLE
Add force directed layouts to Vega-Lite

### ISSUE THREAD

**Issue by metasoarous** [vega/vega-lite#4839]
I'd love to be able to create force directed graph layouts from Vega-Lite, as in this Vega example:

https://vega.github.io/vega/examples/force-directed-layout/

This seems to be related to #3421 (swarm plots). I'm not sure whether these should be counted as two separate issues, or whether one of these should be considered a duplicate (or generally subsumed) by the other. In any case, just wanting to make clear that I see value in force directed layout outside of the specific context of the swarm plot use case.

Thanks for all your work!

**Comment by domoritz** [comment]
Part of #1872

**Comment by apb-reports** [comment]
I recently had an issue with overlapping points on a map and I only got the tooltip on the outermost point.
I decided to add a jitter myself with some transforms which worked reasonably well.
Just change the 0.08 value to match your needs.

But it would be much better to have a force transform that applies gravity to group them in a smarter way.

![image](https://github.com/vega/vega-lite/assets/118884817/26bb66ce-f74c-44b3-affd-4a11c45246d2)


```
{"calculate": "(random() * 0.08) + datum.lastScanLongitude","as": "jitter_lon"},
{"calculate": "(random() * 0.08) + datum.lastScanLatitude","as": "jitter_lat"}
```

```
"mark": "circle",
"encoding": {
"longitude": {
"field": "jitter_lon",
"type": "quantitative",
"axis": null
},
"latitude": {
"field": "jitter_lat",
"type": "quantitative",
"axis": null
},
```
