### ISSUE TITLE
Layers with similar names raise: Duplicate signal name: "MyLayer_x_step"

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4846]
The following spec (which has two layers with the same name) raises the error: `Error: Duplicate signal name: "MyLayer_x_step"`

If this is an intended limitation, then it should be documented. Otherwise, perhaps signal names could be generated by suffixing the name with the layer index.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {
        "a": "A",
        "b": 28
      },
      {
        "a": "B",
        "b": 55
      }
    ]
  },
  "concat": [
    {
      "name": "MyLayer",
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "a",
          "type": "ordinal"
        },
        "y": {
          "field": "b",
          "type": "quantitative"
        }
      }
    },
    {
      "name": "MyLayer",
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "a",
          "type": "ordinal"
        },
        "y": {
          "field": "b",
          "type": "quantitative"
        }
      }
    }
  ]
}
```

**Comment by marcprux** [comment]
It should be noted that layer names don't need to be exact duplicates. Any characters that result in the generated signal name using an underscore will trigger this issue. E.g., if one layer is named "Good?" and the other layer is named "Good!", the following error will be raised: `Error: Duplicate signal name: "Good__x_step"`

**Comment by domoritz** [comment]
You're expected to use different names for different layers. We should not simply remove special characters. This is a bug (albeit a minor, imo).

**Comment by marcprux** [comment]
I imagine that special characters are being removed/substituted to make the names valid JS identifiers for use in the compiled signals. There's probably no way around this if you want to keep the pure layer names useful as debugging tokens, otherwise you could just use a hash of the name.

In any case, it should be documented (and, ideally, validated at runtime) that layer names need to be distinct, since it is an easy error to make if you are just copying & pasting one layer to use as a template as a new one. Personally, I'd rather permit duplicate layer names and then have the VL compiler perform the de-duplication for me.

**Comment by domoritz** [comment]
Why do you name layers? If we allow duplication, then the naming would be useless, no?

**Comment by marcprux** [comment]
As a title for documentation & commentary purposes, like the `description` field.

**Comment by kanitw** [comment]
Feel free to submit a PR to update the documentation, or automatically change layer name if there is a collision. (That should happen in the model class constructors.)

**Comment by domoritz** [comment]
I don't even think we want to fix this. Names are like IDs and therefore should be unique (minus special characters, which are replaced with _). I'm going to close this to reduce the number of issues we have to triage.
