### ISSUE TITLE
The boxes in Boxplot have incorrect size and offset when setting both fields quantitative.

### ISSUE THREAD

**Issue by chanwutk** [vega/vega-lite#4849]
```json
{
  "mark": {"type": "boxplot"},
  "data": {
    "values": [
      {"lat": 47.608013, "sunshine": 69},
      {"lat": 47.608013, "sunshine": 108},
      {"lat": 41.881832, "sunshine": 135},
      {"lat": 41.881832, "sunshine": 187}
    ]
  },
  "encoding": {
    "x": {"field": "lat", "type": "quantitative"},
    "y": {"field": "sunshine", "type": "quantitative"}
  }
}
```

This spec produces this chart:
![visualization](https://user-images.githubusercontent.com/30903997/55658642-39ae5680-57b3-11e9-8875-11f059ce089f.png)

**Comment by chanwutk** [comment]
@kanitw @domoritz should we be supporting `boxplot` with 2 `quantitative` fields?

**Comment by domoritz** [comment]
I don't think it's high priority but we should at least throw a warning if someone uses it.

**Comment by domoritz** [comment]
Related: https://github.com/vega/vega-lite/issues/5263
