### ISSUE TITLE
Selection nearest invalidates tooltip

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4859]
When using a selection with `nearest: true`, the `tooltip` encoding becomes incorrect, showing `undefined` instead of the tooltip value. [Here is a spec demonstrating the issue.](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMoIUgFwJ4AcBTVKAYwEt5SAbY8MAXwBp7IATWbWEjTSAV3jUS7TrAD00APYA3coQDOAOgBWCqQDtI9ZqwWFapbOU096WABazC8M5j54iIheQ0BzWpBb2shaPjwRDU1ibx9IUzQYKX59a1sw+0gNQgRFbBJseH5Cc0YdMMhCDVIpNlc3Oz4ADyqkgDN5ajYRACUpbGxigH0AFSk4bClFbtbOCq88rEdiKIBHflgNYy5jGTp7XSTcOr5GgxaogEkAWQARACFR8fdJnygZkQWllfH17U3Eh6kpamN8XZYfbNES9cjYTxfaYEWZQYLQVywYR5LZ8UrUKS2NC8JIyJE5ZxdAwAI2oBKhZE05WMkXQUz4+kMNK0USs6wS9KweLJsMgjXghGJ8HIpGQ9IYKIKrAA7uQ2NgLCQACwABhVhQshHIbgsGTQAGY1SAGEA)

It appears that the error is due to the Voronoi cells intercepting the mouse event but attempting to produce a tooltip for the wrong data field. As the Voronoi cells use reactive geometry, to reference an underlying data field one should use `datum.datum.field`, not the normal `datum.field`.

**Comment by jheer** [comment]
I just ran into this bug again in another context, so I'm upping the priority and assigning.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4888
