### ISSUE TITLE
Non-projected selection fails across views

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4860]
The following spec uses a `single` selection to select a point, then attempts to use that selection in a concatenated view. This fails, as the selection never matches a point in the other view. 

[Here is the spec.](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAWDGD2A7WBDALpAXGA2uCYoBBkAtigE4DWWh+xEkaAngA4CmtksAlhbABtO9AgF8ANCMYATdClpEGjAK4UBXWWhQB6UvABuPdgGcAdACtjSSFLATbkY+yGw0Pa9kVLIAIwrLjaAVbYiY2TmxHHkQAcyFISSVQ9lJWFi5EJE5EpMYPKD0A9gN2CgSQkkR2ShMMbDR-dgrRW3tvdmR4aWiY4NzIAA8+3KgAMyMBaS4AJXg0NA6AfQAVeHI0eBNF6fQe8pGoFg4uAEdlFEQ3LTd9YVy2pMhmYf7x5ynIgEkAWQARACFtrtYvsRmFjpEzhcrrtbjZ7jlvAgBPAyp4Kox9CgBMoIlBjAtnD4cdkMVAEIhum58l4wU4XNTEFw-AEgoiwViSVxxhR2H4eLAaGSWvdWiIHhBaYxyNQXgxwXimOwBhhWuyZHI5aFVOpIpodHpDCYLFYmWqHA0LsZRqjSLQ8LkpfLxgIFmi6AdGPT2K53EzIizAvCRiKkqHiABddVQDoIbog9H9IaJsFvSYzOYLRArNboTbGIFuEHR0JHRVQy48a48OElkjGVDxTyQaS56L2gAM4gAjB2OxHwwwJfLninXhMPlAfgDC3s64wy6dzpXq7WyY5G3jgC22-7cF3ewPmnWlSqtc6J1xllX4vPDuEMmtotjg0pBxBB6GIyBREA)

The error arises because the inserted `identifier` transform writes to `data_0`, causing Vega to copy the dataset. As a result no tuple in `data_1` can match. If I rewrite the generated Vega spec by moving the identifier to `source_0`, all works as expected.

Similarly, rewriting `data_1` to use `data_0` as a source resolves the issue:

```json
    {
      "name": "data_1",
      "source": "data_0",
      "transform": [
        {"type": "filter", "expr": "(vlSelectionTest(\"brush_store\", datum))"}
      ]
    }
```

This is not a major issue, as one can project the selection instead, but it caught me by surprise nonetheless. Perhaps some revised  dataflow logic would help here?

**Comment by arvind** [comment]
Fixed with #5531.
