### ISSUE TITLE
Selection unresponsive in layer plot

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4861]
The following spec should have circles turn red upon mouseover, but it doesn't work: [example spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEA2CGCeBTATpAXGA2uCZS90gBNYAXWdPSAV2WkuLNgHoBbAewDcBLRAZwB0AKz7sAdpAC+AGhwFIrWMgDWlfAUKl4AB0QMAxt2T7oeubhnmIkPolP7S3cWquEARsmp8AFi40bILV0GPm4xAHNTSFl-eURWbS0GMXE9GNjrZwwFdi9ELhRo13kxRCV+UkpST0RisElXS39IRDF9diIw8L9YyAAPHozIADNeaCIGACV2UlJWgH0AFXZFUnZ+ecmyLqKM6yC9bIBHalgxR3JHTjMMpt74Qd7RuwnsgEkAWQARACFN7Yiuz2gR0hygJzOF2210gdTuzXa0HYqAw6iGnFg0GoYJsczsbixaTq1naYk6jiyeGJhFs9gpEmyHi8vnSeygGMJDFGyEQHm4+lU1Iat0a5mFYAAuiBJEA).

If I don't include the circle mark within a layer spec, then it works. Strangely enough, if I move the `data` definition to the outer layer level, then it also works. Perhaps this is related to #4860: using a projected selection works and the major difference with placing data on the outer layer appears to be the inclusion of an `identifier` transform. The lack of an `identifier` transform for the example spec above looks like it might be the root cause of the error.

(I know putting a single mark within a layered spec is odd, but I noticed the error with multiple layers, then simplified down to the current spec, which still exhibits the issue.)

**Comment by arvind** [comment]
Fixed with #5531.
