### ISSUE TITLE
Make `order` use Vega's `zindex` rather than sort

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4864]
- This allows more efficient re-drawing. 

- This will make order support conditional encoding (https://github.com/vega/vega-lite/issues/5764)

----- 

Open Question:

- What does order = array of field defs mean for zindex?
- What does value def order mean for non z-index order? (e.g., stacking.)

**Comment by jheer** [comment]
_Context_:

In terms of underlying Vega output:
- `sort` reorders sibling items within the scenegraph. It is _necessary_ for tasks such as setting the path order for line or area marks.
- `zindex` dynamically changes the rendering and picking order, but does not re-order the underlying array of scenegraph items. It exists solely to change the drawing order, and nothing else.

So, at minimum, Vega-Lite must use `sort` when needed. For stacking order (as in stacked bar charts), one can apply sort criteria to the [`stack` transform itself](https://vega.github.io/vega/docs/transforms/stack/). It might be nice to instead use `zindex` in those cases where sorting is not necessary.

For line and area marks, all sibling scenegraph items are drawn as a single rendered path, so `zindex` has no effect. (One may, however, want to modify the `zindex` of the groups containing each line or area instance to determine, for example, which lines are drawn on top each other.)

_Questions_:

For setting z-index based on an `order` array, I can think of two options. The first is to just use `sort` and forego `zindex`. The second is to use a window transform, sorting by the provided field defs and outputting ranks that can be used to configure the zindex. As both involve sorting, I would prefer option 1 and simply use `sort`.

To include value defs in sort criteria (Vega's `compare` type), we could use the syntax `{"expr": "<signal expression>"}` instead of a direct field reference. This is not currently supported in the Vega v5 schema, but I think I can add it pretty easily (fingers crossed).

Based on the considerations above, an implementation plan might be to:

1. Continue using `sort` output, but add support for value defs, for example enabling ordering control using selections. (One might even imagine supporting `"order": {"selection": "name"}` directly, though not strictly necessary.)
2. Examine potential optimizations (e.g., depending on mark type and stacking use) to add a `zindex` channel to the output Vega instead of a `sort` directive.

I would definitely prioritize task 1. For task 2 to be most efficient, we also need to examine ways to avoid recalculating properties for _all_ mark siblings upon selection updates.

**Comment by jheer** [comment]
FYI, I am adding `expr`-valued sort fields in vega/vega#1763.

**Comment by kanitw** [comment]
Thanks @jheer.  I have a question though:

From https://vega.github.io/vega/docs/types/#Expr:

> An expr reference provides an expression string that should be evaluated once per datum:

Given `expr` only evaluate once, I'm not sure how it can be useful for including conditional valueDef (with selection in the condition) in the sort criteria? 

(It can be useful for a conditional `test` expression that involves the data field only though.)

**Comment by jheer** [comment]
Not sure I follow you. Expressions are separately evaluated _per datum_, whereas signals (when used as sort or transform parameters, not in encodings) are evaluated only once. Both of course re-run if an upstream dependency changes.

**Comment by kanitw** [comment]
Then we should revise the documentation in  https://vega.github.io/vega/docs/types/#Expr to account for "upstream dependency changes".  Reading the following text confused me.   :) 

> Unlike signal references that are evaluated once per parameter, expr references behave like anonymous (or lambda) functions that are evaluated once per data object.

**Comment by kanitw** [comment]
@jheer  It's unclear to me how to use the `expr` support you added to `sort` with selection. 

I tried [this](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJkRMATwA2h9FDiPHRjUkwpUAbVBxJAQXDBoyGEcIrAB9OzZlQwBfKSCQsLEGZTdYgAYjYiRHBjgINECQeUwGYu0AQSMcJPMoTDgtdEaZKDVxTDQARgBmVNBq2s8uppaaNo7tACEjXvUB1DyxqrbJhpmOufbOkABhFb71zbTtmrr0ZZlmg-nj7pBV-rQr8Z27kAfjLMXktzmsht8brt7vtWkdtGcehc0AA2LYTP4IwHPOHTRFgjZo35TU4ww4LaF4z4E67o4mYp6w8kkynrACcyQAultgqFtN5fPkjFkcpk1CLBTJMMokOIIAAzRIICqgBw4MI0DRwfo0OU0ODKIxIcroWLEMgQDWxEBbVVhXWOdoGmRwAAezW0NAgADVihqABT8hgIfwAHXeFzDHIAlAACABkcZjnoAYhYDH6ANSB4Nhj6YSNR61cjm2CLBRzGyo8sIu+LtHCFYqlNAAFgh1e0Og19CMDBw-LCck0EBMbgDbGQFj9AHIXdOo5RnJZ6FIY3lV3lYwAqGO1uxwBvcjLaex1g+NkouNtH3noeAxAYyPsD7RDjQj+RwceT8Qz+zzxctTIFc1w3bcY1PfdD2uDt0HUOgL2bVBgFSEAJGVEA4FIfpjRABA1AgRA2FIXt+x8dUIAAFT7Zw-RUNQcD9KNYwAfhjei+yYmNUBjeCBk5G8wn0SJokiR8QGfcjtGIRwAGV3DgNp2HEAAlMo2EcUg-TDYSogfOtEjgMNVzDeCJDDQtBO0XTRLiGocGcIx0ICUAsK1TBK1AYU3G0aA2DVIxbW0KBokUIsnzI9o+R8IN40TAwECYyhkGUBRkqQVLbRjABCABeXKY2nDicGnGM2OAPieLDYyY11dx3x4mz9Ps5xYjqxx31XIpL3wGN-D9BKks9L1EgkNgaDKmNs0obNuKmmKECjUMQFNc1LUjLk5vEBgPCMBURTQKVSi2NycIw7zMl6ALJXsAL0A0JhHBCuYFHCiTIrCbbdoEmDjzvGJbMwWIWrgNq9Q68oZG6pDKiC9AAFE9vB45VotDQrR+9Jb3CET9Pw8w5XsJzJBczDsI8tAvLLP4mrE4GaJSCKX3QfGdXsbScb0umEiSGrabshnVyOuBLOLGQUoUTyQFgvCMslwLbrCJI2iFBxHICEBlYGEsQAsR1qhoEjUGFmQ5VUJVkJAfk-CtnwkEFVCxGUdZQHazpXLdA10Bk+TnCUiRKLKTAOf5oGeaM6R5pqRbJoAJjmwZrVQrVek1Sn3uZrypTYBQ4AAdW7GB0+hlxY9Q+0pi8qBijtGhdtN5HgqRR3s9zjD2jsbQ-Wyv0l2AmAAztkOAf08OLOYmMAB9J5jP0fYU-3xEDuxh9x7nMEMmrs2Y2ME1nvv6EH3xV65uIx5AHfEMHRx5FerYS7QL7HE5GR-PkOgidJjv1hAHuD4H62J9AYGV5hfCe09Z7zz9pgZSy9g46RHuvTekdt6Fihk2Fwgx74YK+JQAQL8rZlCgMoGgOAYHOSpmQcs2gwy0jDDGDMMYwxVRAAw2ew1fQaCPkGZadCQDRkmtmXhRJIxzWqiALMC1hG3EcAWNhYYADcTDWGMLDAyMkGh6GqLQMothA1vScO4TmLEjJNH8NYlHHhaigRHFESwsMkjo7LXUS8OR2ilFaOUXmTxzDdGML9PtZAwchG5gjPwkyIBx7WhkC6dO0Aa7aFiQ3eq2gXFwlQl2DQPZLbxPViAJJsgZSdCwTIT+VcEnoCJskjq2haTRIwHAB8cTq55KqYUzQQxkhdIIbksoGEZYFLhu0rQMgNATiQBYdO1tooCgKNU44aSFi2ESOsYWqFpSWBcFnc8OTqbEj3PWJOjxTDmEsAASXEOIfUXxjlmAsGQAA8gwR0XwrKVIVndYZXhxmTMttM+6dsJQgDdrUokQoVmHWUMdGQGyyBbJAFBOJeyTxnkPKhEwdzzmXOuRsW5pzHnPJxe2P6wK66eBup86IVyMrfJ-FMu2Mz7ZzNJSk1wzcYUyjhdZOAPhkANhkHrfUOANJSTvCFIwAAvfUbA0BymKIRAhSAXR9NJr0xJTkSHuVfGwbAE4jAqA1LK+VcBJR0DyYskZIAb5MHcPUUSJNNZNJkNa21lh1axwAOzritUgG1jhFhGncBYMICANQaEcjICVFhNSxOpOU1pGq9RUitXAOU4kDWdDlRWE1IAYGYDyXUyN0bXSvJ1s4OFw4MIV20NWmQKhTBJswAAGSAtkyh1DXA3wQIxe8YlVzIhbKuWOeRNz1IgPYBATANKUUVr5AAjrUJIgUzVhDzEYFObA06W3reYLVltJJRUtm-KAH9i44NQFg7pBDejiF1FYS2sL4XSm7c07gYR7DuEcGwHQKg4Bakes2LpMglWeimT8kmWbCJFs0CWgkXSgA):

```
"sort": {"field": {"expr": "vlSelectionTest(\"highlight_store\", datum) ? 2 : 1"}},
```

and [this]({
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "background": "white",
  "padding": 5,
  "style": "cell",
  "data": [
    {"name": "highlight_store"},
    {
      "name": "source_0",
      "values": [
        {"actual": "A", "predicted": "A", "count": 13},
        {"actual": "A", "predicted": "B", "count": 0},
        {"actual": "A", "predicted": "C", "count": 0},
        {"actual": "B", "predicted": "A", "count": 0},
        {"actual": "B", "predicted": "B", "count": 10},
        {"actual": "B", "predicted": "C", "count": 6},
        {"actual": "C", "predicted": "A", "count": 0},
        {"actual": "C", "predicted": "B", "count": 0},
        {"actual": "C", "predicted": "C", "count": 9}
      ]
    },
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {"type": "identifier", "as": "_vgsid_"},
        {
          "type": "filter",
          "expr": "isValid(datum[\"count\"]) && isFinite(+datum[\"count\"])"
        }
      ]
    }
  ],
  "signals": [
    {"name": "x_step", "value": 40},
    {"name": "width", "update": "bandspace(domain('x').length, 0, 0) * x_step"},
    {"name": "y_step", "value": 40},
    {
      "name": "height",
      "update": "bandspace(domain('y').length, 0, 0) * y_step"
    },
    {
      "name": "unit",
      "value": {},
      "on": [
        {"events": "mousemove", "update": "isTuple(group()) ? group() : unit"}
      ]
    },
    {
      "name": "highlight",
      "update": "vlSelectionResolve(\"highlight_store\", \"union\")"
    },
    {
      "name": "highlight_tuple",
      "on": [
        {
          "events": [{"source": "scope", "type": "click"}],
          "update": "datum && item().mark.marktype !== 'group' ? {unit: \"\", fields: highlight_tuple_fields, values: [(item().isVoronoi ? datum.datum : datum)[\"_vgsid_\"]]} : null",
          "force": true
        },
        {"events": [{"source": "scope", "type": "dblclick"}], "update": "null"}
      ]
    },
    {
      "name": "highlight_tuple_fields",
      "value": [{"type": "E", "field": "_vgsid_"}]
    },
    {
      "name": "highlight_modify",
      "on": [
        {
          "events": {"signal": "highlight_tuple"},
          "update": "modify(\"highlight_store\", highlight_tuple, true)"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "rect",
      "style": ["rect"],
      "interactive": true,
      "from": {"data": "data_0"},
      "sort": {"expr": "vlSelectionTest(\"highlight_store\", datum) ? 2 : 1"},
      "encode": {
        "update": {
          "strokeWidth": {"value": 2},
          "fill": {"scale": "fill", "field": "count"},
          "stroke": [
            {
              "test": "(!(length(data(\"highlight_store\"))) || (vlSelectionTest(\"highlight_store\", datum))) && (length(data(\"highlight_store\")))",
              "value": "black"
            },
            {"value": null}
          ],
          "opacity": [
            {
              "test": "!(length(data(\"highlight_store\"))) || (vlSelectionTest(\"highlight_store\", datum))",
              "value": 1
            },
            {"value": 0.5}
          ],
          "description": {
            "signal": "\"actual\" + \": \" + (isValid(datum[\"actual\"]) ? datum[\"actual\"] : \"\"+datum[\"actual\"]) + \"; \" + \"predicted\" + \": \" + (isValid(datum[\"predicted\"]) ? datum[\"predicted\"] : \"\"+datum[\"predicted\"]) + \"; \" + \"count\" + \": \" + (format(datum[\"count\"], \"\"))"
          },
          "x": {"scale": "x", "field": "predicted"},
          "width": {"scale": "x", "band": 1},
          "y": {"scale": "y", "field": "actual"},
          "height": {"scale": "y", "band": 1}
        }
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "band",
      "domain": {"data": "data_0", "field": "predicted", "sort": true},
      "range": {"step": {"signal": "x_step"}},
      "paddingInner": 0,
      "paddingOuter": 0
    },
    {
      "name": "y",
      "type": "band",
      "domain": {"data": "data_0", "field": "actual", "sort": true},
      "range": {"step": {"signal": "y_step"}},
      "paddingInner": 0,
      "paddingOuter": 0
    },
    {
      "name": "fill",
      "type": "linear",
      "domain": {"data": "data_0", "field": "count"},
      "range": "heatmap",
      "interpolate": "hcl",
      "zero": false
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "title": "predicted",
      "labelAlign": "right",
      "labelAngle": 270,
      "labelBaseline": "middle",
      "zindex": 0
    },
    {
      "scale": "y",
      "orient": "left",
      "grid": false,
      "title": "actual",
      "zindex": 0
    }
  ],
  "legends": [
    {
      "fill": "fill",
      "gradientLength": {"signal": "clamp(height, 64, 200)"},
      "symbolType": "square",
      "title": "count",
      "encode": {"gradient": {"update": {"opacity": {"value": 1}}}}
    }
  ],
  "config": {
    "range": {"ramp": {"scheme": "yellowgreenblue"}},
    "axis": {"domain": false, "zindex": 0}
  }
}): 

```
"sort": {"field": {"expr": "vlSelectionTest(\"highlight_store\", datum) ? 2 : 1"}},
```

Neither of them leads to an expected result (that the selected layer is on top).

**Comment by kanitw** [comment]
So after further investigation, it seems to be simplest to map fields to `sort` but conditional value defs to `zindex`.  

I'm fixing this in https://github.com/vega/vega-lite/pull/6632.  

To avoid unnecessary complexity, my current implementation in #6632 will not allow mixing field in one condition but value in another.  If we find convincing use cases, we extend `zindex` support condition of field as long as it's not an array of field in the future.

**Comment by loganpowell** [comment]
Sorry to ping on this relatively newly closed issue, but I was looking for some guidance on how to get my marks to float to the highest zindex on mousemove/click as @arvind did here:

https://github.com/vega/vega-lite/issues/1684#issuecomment-282379770

**Comment by joelostblom** [comment]
@loganpowell In case you are still looking for a way to achieve this, I added an example in https://github.com/vega/vega-lite/pull/9136

**Comment by loganpowell** [comment]
Thank you @joelostblom!
