### ISSUE TITLE
Improve timeUnit positioning  

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4868]
(Copied from slack) 

@jheer: 

> I have a temporal domain with timeUnit `yearmonth`. I want to show a histogram with bars for each month. If I use a `bar` mark this works but the bars have a fixed size. I want them to scale to fit the known timeUnit, just like numerical bins do. Do we have any support for this? (Note that I don’t want to switch to an `ordinal` domain, as then empty/missing time units get dropped.)

@kanitw: 

> The way to do this in Vega is probably offset the `x2` by the smallest unit (a month for `yearmonth`)
> In fact,  I think this should even be the default behavior.
> The tricky part for this is that months have uneven number of days

@jheer 
> Yeah, I think the solution is to treat time units as bins. If no time unit is given (just type `T`) I think the current behavior is reasonable — it’s just like plotting bars over a `Q` domain. For a given time unit, we could calculate start/stop boundaries that are specific to the time unit, just like binning.

> Happy to look at Vega modifications to achieve this. I also added a Vega issue to perform imputation for time units (https://github.com/vega/vega/issues/1764), so that ordinal scales over proper time domains could also work.

**Comment by kanitw** [comment]
FYI, this would work by deriving another field for month_end (just like bin produces two fields).  

The trick is to add +1 at the smallest unit that we care about. 

```
{
          "type": "formula",
          "as": "month_date_end",
          "expr": "datetime(0, month(datum[\"date\"]) + 1, 1, 0, 0, 0, 0)"
        }
```

Full [vega spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4t27UANsgDksMLDzd4AazCFN8ZGG5V1YHamR0FJUh0VjtYRgAvZGwoQnRlQIhIOOVlRhlqGNFFJIB3RmUWGIAmAAZSnNxkRmp8EvLKyFsAT3MYyDdTU0SVdDxMHABtJQhQCHGoGXQ-dulWdTcAfVKeich57v1lPpFbewdYOnhYClXxyAAzbnUMPBjgSDxmwmj9Y9P5WPR1WFewB+2eD+kEB0QAvp8QchTIxUMxkOp2vJIBCRuc8Op0DJYFcbjFhhMJg8ni92hdGKYgYjIcgAB4udqA1ioOiwZqodjcUwAXl5FgMAHkBQYLCjKoT-miJY9nsDcahWKZMOKJVB0LB2qhZCxFqCztK6Qytn1kL5kAAKCpgLUyFjmpmoQYAHRBJpdAF0AJSfACMnytAf9nsgUvGqNVkojSRJcuuCqV+sJwQ1+htOtBi2QMgSKoN9MRxqBZstnzTiHtfWZztdQI9nrAAGowH7m-622AA8HQxBw6qxlGZaT9OhqNR1MIgYm1mPuKxCOxmvjIGXdSaFMvtYhV0DM9nIO7c0nuMQl34sfvD2tydDlCmwINkq5ogfu+d1afkFjFi5GG596-ewlfsI0HOUKSpKdzkNAtejwKsXRXUEPTAABCXkwBkRVTDAAAyHDUMYWAADl0CIis4MdBDN23ZA6xDCMwVDd00UYiAXySDB1AOfE0WA84phmVNvm4w9QPacd4DuUSWjaIZIHYb4L1DS51G4VB7hrAYoDmBZkGWMVlKzeBuFUe5X3WQg9RwPjpXJLoNIodBTFYYEAGIABZ4AAdgADnQHyDKjKA7C5HRCDMoKknCagpk2KBgBdUEwHNMtPRdHAzQAMTjPpyPgjdbS3JCLzACwAFJ2Asb0wBdABZT8ZA8C5nCfdKwHlXKHWrM8ZG-VqSpdF1PTBeio0A1VIFpDSECc4Epsha9TASVNqL1SFuAuC5fjuHBinG6VaWKab4Fm9p5qgRblqgRCTV3HMoA2rbTRiABaPbL3ORdrKaE7ZKgRcFsYG9NQavrf3BD6kmaI7vpmv7IABqBHOcv5SlY1V0YmTGwHR9jtN+tQeKJZSBLmxMxP0M1yeUNT0HSDTLrvQYAR2WZZ10-TAeBlbCposUWf6Nn5iWFYuaWzVVturMEjBd19qgTEMj+QYrQeaLYvafJCkQFE8bWFI0gyLIWJVGzJmmYEAeUmN2hhGRP2pZSaYwenvsBLSmnZkWFAuoHxdTUGfz-eXIEV6hlbVmoNf0FAajqCEOz1-jwZiDEXNEqJVNT9QXJYpQ8eCWlCaGXjlLhsnROuIHbXaTkCDU8mxwKGILic35RJ0PB4aSlLN2DUSlXYaFMuc2AdYynPkAH9Ah9MAUvCVcKJ-TwyZGM0zrPMwfoTvM21jnKz-keOkdqP9WnPaLKcrwPKWWR9PSoqqqUWxrHQxDiJ0lUKacB9E3S+lOXM65Mq5ZlPvJbg9d1KiSbsoAAygTdoVtpSwOzivaUzs6Z6Ham3Keylt6mDvK3QheDpQYFpAAUVpECGuOAKjKThDIKhNDT70OlDoRwRDcEZy-nSGIpR-7E0AYg-QyCjyaDAbbZAFwpLKVQTgYh7drbMHhvVLETUWop2nrPeeCJF5oNIUmDhDgADCs5aFnyjhfN41RTDmljrUPApB3KlGDB-XhP9myCPGGbH6p1REgIkRYyA5gZGN00PAkRUB5pyIiQYjuv5THmNPpHGK1ioBuApPY6ojjnGuMCkmTBrscEkO0TvFu3CGHoEodQyRdDRKMOYXUjsCTOEVNKcpT+2Y+F0LzmxEAYIgA). 

![image](https://user-images.githubusercontent.com/111269/59652011-e2c4e600-9140-11e9-8655-1403d67397a5.png)

**Comment by kanitw** [comment]
Note that the grid is a bit off somehow -- probably an instance of https://github.com/vega/vega/issues/1837#issuecomment-502934879.

**Comment by kanitw** [comment]
The question now become what should be the default for line. Should the position be:


a) in the middle of the band (band=0.5)

![image](https://user-images.githubusercontent.com/111269/59652362-43a0ee00-9142-11e9-84f5-9c6769f30194.png)


or b) the beginning of the band (basically current VL behavior, which doesn't have month_date_end):

![image](https://user-images.githubusercontent.com/111269/59652386-616e5300-9142-11e9-8bb0-14eead50e2a1.png)



a) would make a smoother transition between bar and line
However, b) would be a less breaking change. 

In any case, users should be able to switch between the two.  If that's the case, how should they be able to specify it? 

cc: @jheer @domoritz @arvind

**Comment by domoritz** [comment]
I don't like bin labels for time Unit as much, though. I'd usually label a whole bar as being June, rather than saying it's the bar from June to July.

**Comment by kanitw** [comment]
[Align left with labelBound](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4t27UANsgDksMLDzd4AazCFN8ZGG5V1YHamR0FJUh0VjtYRgAvZGwoQnRlQIhIOOVlRhlqGNFFJIB3RmUWGIAmAAZSnNxkRmp8EvLKyFsAT3MYyDdTU0SVdDxMHABtJQhQCHGoGXQ-dulWdTcAfVKeich57v1lPpFbewdYOnhYClXxyAAzbnUMPBjgSDxmwmj9Y9P5WPR1WFewB+2eD+kEB0QAvp8QchTIxUMxkOp2vJIBCRuc8Op0DJYFcbjFhhMJg8ni92hdGKYgYjIcgAB4udqA1ioOiwZqodjcUwAXl5FgMAHkBQYLCjKoT-miJY9nsDcahWKZMOKJVB0LB2qhZCxFqCztK6Qytn1kL5kAAKCpgLUyFjmpmoQYAHRBJpdAF0AJSfACMnytAf9nsgUvGqNVkojSRJcuuCqV+sJwQ1+htOtBi2QMgSKoN9MRxqBZstnzTiHtfWZztdQI9nrAAGowH7m-622AA8HQxBw6qxlGZaT9OhqNR1MIgYm1mPuKxCOxmvjIGXdSaFMvtYhV0DM9nIO7c0nuMQl34sfvD2tydDlCmwINkq5ogfu+d1afkFjFi5GG596-ewlfsI0HOUKSpKdzkNAtejwKsXRXUEPTAABCXkwBkRVTDAAAyHDUMYWAADl0CIis4MdBDN23ZA6xDCMwVDd00UYiAXySDB1AOfE0WA84phmVNvm4w9QPacd4DuUSWjaIZIHYb4L1DS51G4VB7hrAYoDmBZkGWMVlKzeBuFUe5X3WQg9RwPjpXJLoNIodBTFYYEAGIABZ4AAdgADnQHyDKjKA7C5HRCDMoKknCagpk2KBgBdUEwHNMtPRdHAzQAMTjPpyPgjdbS3JCLzACwAFJ2Asb0wBdABZT8ZA8C5nCfdKwHlXKHWrM8ZG-VqSpdF1PTBeio0A1VIFpDSECc4Epsha9TASVNqL1SFuAuC5fjuHBinG6VaWKab4Fm9p5qgRblqgRCTV3HMoA2rbTRiABaPbL3ORdrKaE7ZKgRcFsYG9NQavrf3BD6kmaI7vpmv7IABqBHOcv5SlY1V0YmTGwHR9jtN+tQeKJZSBLmxMxP0M1yeUNT0HSDTLrvQYAR2WZZ10-TAeBlbCposUWf6Nn5iWFYuaWzVVturMEjBd19qgTEMj+QYrQeaLYvafJCkQFE8bWFI0gyLIWJVGzJmmYEAeUmN2hhGRP2pZSaYwenvsBLSmnZkWFAuoHxdTUGfz-eXIEV6hlbVmoNf0FAajqCEOz1-jwZiDEXNEqJVNT9QXJYpQ8eCWlCaGXjlLhsnROuIHbXaTkCDU8mxwKGILic35RJ0PB4aSlLN2DUSlXYaEAEEYRi23kAuKTlMH6FMuc2AdYynPkAH9Ah9MAUvCVcLl-Tmf1+hAAhWc9z31fDJkYzTOs8zZ9MO8zbWOcrP+R46R2t-1ac9ospyvA8osmRunUqFUqoomxljUMIcIjpFUFNHAPoTal2lOXM65Mq5Zk-vJbg9d1KiSbsoAAygTdoVtpSEOzvvaUzs6Z6Ham3C+0p753lbg-JhSYMC0gAKK0iBDXHAFRlJwhkLw-hn8hHSh0I4VhjCM5wLpDEUoyDiaoNIfochR5NBYInlPRumgrpsPbtbZg8N6pYiai1FOa8N5bwRDvKhHC1jSIcAAYVPp-SOMUf5vGqKYc0sdah4FIO5UowYYEKIQc2FR4wzY-VOhojB2iBFQHMHoghBiSEJKgPNZSlDz4d1-G4jx00o4+KgG4CkATqhBJCWEwKSZaGuwYewmx0JZGtOEegHhfCdGCNEiIsRfSOyFJkS3ORylYHZkUYIvObEQBgiAA) would help:

![image](https://user-images.githubusercontent.com/111269/59655016-a3e95d00-914d-11e9-8d97-392177279579.png)

**Comment by kanitw** [comment]
This [one](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4t27UANsgDksMLDzd4AazCFN8ZGG5V1YHamR0FJUh0VjtYRgAvZGwoQnRlQIhIOOVlRhlqGNFFJIB3RmUWGIAmAAZSnNxkRmp8EvLKyFsAT3MYyDdTU0SVdDxMHABtJQhQCHGoGXQ-dulWdTcAfVKeich57v1lPpFbewdYOnhYClXxyAAzbnUMPBjgSDxmwmj9Y9P5WPR1WFewB+2eD+kEB0QAvp8QchTIxUMxkOp2vJIBCRuc8Op0DJYFcbjFhhMJg8ni92hdGKYgYjIcgAB4udqA1ioOiwZqodjcUwAXl5FgMAHkBQYLCjKoT-miJY9nsDcahWKZMOKJVB0LB2qhZCxFqCztK6Qytn1kL5kAAKCpgLUyFjmpmoQYAHRBJpdAF0AJSfACMnytAf9nsgUvGqNVkojSRJcuuCqV+sJwQ1+htOtBi2QMgSKoN9MRxqBZstnzTiHtfWZztdQI9nrAAGowH7m-622AA8HQxBw6qxlGZaT9OhqNR1MIgYm1mPuKxCOxmvjIGXdSaFMvtYhV0DM9nIO7c0nuMQl34sfvD2tydDlCmwINkq5ogfu+d1afkFjFi5GG596-ewlfsI0HOUKSpKdzkNAtejwKsXRXUEPTAABCXkwBkRVTDAAAyHDUMYWAADl0CIis4MdBDN23ZA6xDCMwVDd00UYiAXySDB1AOfE0WA84phmVNvm4w9QPacd4DuUSWjaIZIHYb4L1DS51G4VB7hrAYoDmBZkGWMVlKzeBuFUe5X3WQg9RwPjpXJLoNIodBTFYYEAGIABZ4AAdgADnQHyDKjKA7C5HRCDMoKknCagpk2KBgBdUEwHNMtPRdHAzQAMTjPpyPgjdbS3JCLzACwAFJ2Asb0wBdABZT8ZA8C5nCfdKwHlXKHWrM8ZG-VqSpdF1PTBeio0A1VIFpDSECc4Epsha9TASVNqL1SFuAuC5fjuHBinG6VaWKab4Fm9p5qgRblqgRCTV3HMoA2rbTRiABaPbL3ORdrKaE7ZKgRcFsYG9NQavrf3BD6kmaI7vpmv7IABqBHOcv5SlY1V0YmTGwHR9jtN+tQeKJZSBLmxMxP0M1yeUNT0HSDTLrvQYAR2WZZ10-TAeBlbCposUWf6Nn5iWFYuaWzVVturMEjBd19qgTEMj+QYrQeaLYvafJCkQFE8bWFI0gyGJShYlUbMmaZgQB5SY3aGEZE-allJpjB6e+wEtKadmRYUC6gfF1NQZ-P95cgRXqGVtWag1-QUBqOoIQ7PX+PBmIMRc0SolUtP1BclilDx4JaUJoZeOUuGydE64gdtdpOQINTybHAoYguJzflEnQ8HhpKUs3YNRKVdhoQAQRhGK7eQC4pOUofoUy5zYB1jLc+QQf0GH0wBS8JVwpXjPZ436EACFZz3fe18MmRjNM6zzLn0w73NtY5ys-5HjpHb3-Vpz2iynK8B5RZMjDOpUKpVRVu6FE2MsahlDhEdIqgpo4B9KbMu0oK5nXJtXLMX95LcAbupUSzdlAAGUCbtGttKEhOcD7ShdnTPQ7V26X2lA-O8bdH6sKTBgWkABRWkQJa44AqMpOEMgBFCK-qI6UOhHAcJYZnRBdJjZoOJhgih+gqFHk0Lgye08m6aCupwjuNtmDw3qliJqLVU7r03tvBEu9aHcLWHIhwABhM+X8o4xV-m8aophzRx1qHgUg7lSjBngco5BzY1HjHNj9U6WjsG6OEVAcwBjiFGPIUkqA81lI0Ivp3X8HivHTWjn4qAbgKRBOqCEsJETApJgYW7ZhXC7HQgUe0sR6B+GCL0SI0S4jJEDI7MU+RrdFHKQQdmFRIj85sRAGCIAA) uses x-scale padding=0 and month initials instead:

![image](https://user-images.githubusercontent.com/111269/59655886-ba44e800-9150-11e9-9bfd-0f84b7957e3a.png)

**Comment by willium** [comment]
Adding a voice to this, perhaps favoring using bin-like axis labels.
Shouldn't it be possible to create a contour plot using temporal x temporal or temporal x quantitative?

[This chart isn't great](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAMp5u8ANZhC++DrDcAZmACsYACrIkYAMLcqIToSoxO3FS63oyoyHRqGpCa6HiYOKAQEJCsumLYWqnofJY2sHTwsBSQGgC+6tkYutYFmVmQeACehMgFkITcjEp4NRD1SchK8NyaQ9StGtkAHgtZ7UZxAKphI6adyOi6iWvZLuFimn0peL0NJx3dvaY3wdy66PmLYONrkJ2r9zOyAufXsjEcx3uXR6fQAjqxQkY0kYqJDfuwhgU8LpWMgvj92rBGAAvJ5gNq-dDUai6YQ3PrTVjDNHrR5whHDZipRiou6-BAfMkU+6k3TcLE4vEnb74uogWpAA), without some override to use bin-style axis, for example.

**Comment by kanitw** [comment]
Will be fixed in #5096

**Comment by kanitw** [comment]
@willium  -- Thanks for mentioning the case.  

For the [specified chart](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAMp5u8ANZhC++DrDcAZmACsYACrIkYAMLcqIToSoxO3FS63oyoyHRqGpCa6HiYOKAQEJCsumLYWqnofJY2sHTwsBSQGgC+6tkYutYFmVmQeACehMgFkITcjEp4NRD1SchK8NyaQ9StGtkAHgtZ7UZxAKphI6adyOi6iWvZLuFimn0peL0NJx3dvaY3wdy66PmLYONrkJ2r9zOyAufXsjEcx3uXR6fQAjqxQkY0kYqJDfuwhgU8LpWMgvj92rBGAAvJ5gNq-dDUai6YQ3PrTVjDNHrR5whHDZipRiou6-BAfMkU+6k3TcLE4vEnb74uogWpAA), it might better to just use rect mark and color. 

With #5096, it will look nice like this. 

![image](https://user-images.githubusercontent.com/111269/62002930-c5315780-b0c2-11e9-980a-1fc89e7eb9e5.png)


The problem with the point mark is that it can't scale differently vertically and horizontally.  Thus, even if we treat timeUnit more like bin, it still doesn't completely solve the problem.  There might be a way to set scale range based on the timeUnit (similar to how we do it for bin in https://vega.github.io/editor/#/examples/vega-lite/circle_binned). However, such logic is definitely beyond the scope of this issue. 

Note that the plot you point out isn't exactly a contour plot though (but it  shows similar information).

**Comment by hoclun-rigsep** [comment]
> I don't like bin-like labels for time Unit as much, though. 

> I'd usually label a whole bar as being June, rather than saying it's the bar from June to July.

Anyone know a way to achieve this now?

**Comment by Flix6x** [comment]
@hoclun-rigsep This should do the trick:

```
"axis": {
    "labelOffset": {"expr": "(scale('x', 30* 24 * 60 * 60 * 1000) - scale('x', 0)) / 2"},
    "labelFlush": false,
    "labelBound": true
}
```

- The labelOffset moves the x-axis labels right by 15 days.
- The labelFlush makes sure the original position of the first and last labels are centered with their ticks.
- The labelBound make sure that the last label (the end-of-the-year January tick), which is pushed out of bounds, is removed.

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAMyUAVhDYA7EABoQAEzjQATjRyZ289AGVMbKAGsABDk1Q1ZtgDMzAVjMAVOLDMBhNghxJZNDZspOquNAhwlIoqSJgoqKAM6oJoMXGcRqYQlFAQxCAAvkrI6iZooJgAnjhwqUxI6oVKcLJQbMo0smTlIAAePToRAKoBmKkIcvTRdoGCyqnKsbVKVTWpmIg4bOpIKUpIvTQQPYJITHCCAPJ2dhBwYwkgcL2WqQAU0LtwbwDkvT8KMxiAAMACozAAmAAsZnBADZgbCzAikQBGYEYgCUZn4Zk+gm+fwBZmBmOxBEhTRAp3OggAYoIGBAYGg7Ls7koaRcAEJsBiyeaoTDqBhwApFECVHozC6CkCWGjWaJIMhkdR8DbjOD+aKrWroACODH8OjiOlIhQlwv8EDs2wQaAA2qAZoINo1HjK5qkIJUEEw2HsQHI4NcnSAAOKXS4RkAAXXFCaAA)

![visualization (2)](https://github.com/vega/vega-lite/assets/30658763/2d229aa8-053c-4e71-81b0-04ecc066f994)
