### ISSUE TITLE
Make Vega-editor supports Vega-lite

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#487]
Better fork from https://github.com/uwdata/vega/vega-editor so we get the ACE Editor integration.

**Comment by jheer** [comment]
Rather than fork, should we consider building this out into a single editor
that supports both vega and vega-lite?

**Comment by kanitw** [comment]
That's not a bad idea, but we should do this when vega-lite is more stable then.

**Comment by jheer** [comment]
Certainly should wait until vega-lite moves over to vega 2.0.

**Comment by kanitw** [comment]
I just renamed this issue to reflect current plan. 

It is also worth nothing that we have to 
-  [ ] consolidate data sources for vega and vega-lite since we made some modification in cars.json and movies.jso.  For example, making the variable name more obvious (e.g., `hp` => `Horsepower`), renaming `“null”` to `null`.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-editor/issues/11

**Comment by domoritz** [comment]
This is vega editor issue and I have a pr there. I'm closing this.
