### ISSUE TITLE
Graticule extent to use inclusive bounds?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#4876]
Not sure if this counts as a bug or feature:

The new graticule data generator (which is great BTW!), allows the extent to be defined by 
`[ [longMin,latMin], [longMax,latMax] ]` where min values are inclusive and max values are exclusive. This gives rise to ugly ragged N and E bounds for typical round numbers. For example:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "width": 300,
  "height": 300,
  "projection": {"type": "orthographic", "rotate": [-42, -30, 0]},
  "layer": [
    {
      "data": {"sphere": true},
      "mark": {"type": "geoshape", "fill": "aliceblue"}
    },
    {
      "data": {"graticule": {"extent": [[0, 0], [90, 60]]}},
      "mark": {"type": "geoshape", "filled": false}
    }
  ]
}
```

<img width="390" alt="Screen Shot 2019-04-14 at 16 11 19" src="https://user-images.githubusercontent.com/1846999/56095049-b686b200-5ed0-11e9-8cb0-96c1c86bc4eb.png">

While the workaround is to define the max values as angle + epsilon (e.g. 60.001), this is a bit hacky. I can't see many situations where an exclusive upper bound is necessary, but plenty where an inclusive one is.

Would you consider making both sets of bounds inclusive?

**Comment by domoritz** [comment]
Can you check whether we need to change this in Vega or Vega-Lite?

**Comment by jwoLondon** [comment]
Good point. I've just checked and the same behaviour occurs with Vega's graticule transform. 

I guess there's a small risk that if changed in Vega, this could introduce unexpected behaviour for legacy specs, whereas in VegaLite, this is new, so little risk.

**Comment by domoritz** [comment]
We can change it in Vega since it doesn't seems to be documented behavior. I think we prefer exclusive bounds when you create graticules for the whole globe.

**Comment by jheer** [comment]
All Vega does is pass the parameters to d3-geo’s graticule API. So I think the issue might be lower level than either Vega or Vega-Lite?

**Comment by domoritz** [comment]
Okay, I don't think we should be doing anything different in Vega-Lite here so I'm going to close the issue.
