### ISSUE TITLE
VL 3.2 breaks multi mouseover selection handling?

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4879]
Consider this [example multi-selection spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMoIUgFwJ4AcBTVKAYwEt5SAbY8MAXwBp7IATWbWEjTSAV3jUSkABbZs+AM4oA9LIBuhAOawAdMvLZR-AEZryAe0UrYAWg5cphbFNmXYs0gilqAVlMMA7SPWatrWlJsIx80XixAgGYAJh56TCg8IhFofmoQyBZErG9Uw35rQyV4X0SGP2yoQi9SQzZyL2V4xMgADxacyAAzckJqNhEACUN4a3xDAHdCUqrW5OI0SABHflgvEK4QpTLMf1bcTtbe-sGlgFlyWikAfSJ4G4BxWGpqPLm+BZFV9c3Och2CUYH0gdTepXCQKwdS8DRCeUhOT4gUIwVCImicQ+xz6AxEAGFcNRGmwZlIslDPgRFlBRg0vC9duVsVAFC9+DTIMp4IRDkD9nxDPhYBQ8Ec+DC4ejEUioCi0Qi5f1YhTZaz2TSAAxqAAclIFrTZ1A5JG1AEZ+ZVWJNyGxtCQYgAWTVVMSEcjKcQkM06l2sTa0ETndIhMAACgAyqJyN1sGZzgUiiUAJS+BhAA):
- Prior to 3.2, shift-mouseover would color multiple points
- Post 3.2, shift-mouseover only ever highlights a single point

Looking at the generated Vega, the issue appears to stem from here:

```json
{
  "name": "sel32_toggle",
  "value": false,
  "on": [
    {
      "events": [{"source": "scope", "type": "mouseover"}],
      "update": "event.shiftKey"
    },
    {"events": [{"source": "scope", "type": "mouseout"}], "update": "false"}
  ]
},
{
  "name": "sel32_modify",
  "update": "modify(\"sel32_store\", sel32_toggle ? null : sel32_tuple, sel32_toggle ? null : true, sel32_toggle ? sel32_tuple : null)"
}
```

Notice that, upon mouseout events, the `sel32_toggle` goes to false no matter what, even if `shiftKey` is true. If I replace `false` on mouseout with `event.shiftKey` the example appears to behave more reasonably, but I'm not 100% sure this is the right solution, as I'm assuming this bug was introduced while trying to resolve some other issue?

In any case this is **breaking** the interaction notebook I wrote that is going to students **later this week**. I may simply have to rewrite the notebook to avoid the issue, but in any case I'm flagging this as a high priority bug so that it gets attention and we can decide what needs to be done.

**Comment by jheer** [comment]
This issue also appears to have broken the documentation example here:
https://vega.github.io/vega-lite/docs/selection.html#conditional-encodings

**Comment by jheer** [comment]
Looking over the 3.2 release notes and files modified, I'm guessing the new selection `clear` functionality is the most likely culprit: https://github.com/vega/vega-lite/pull/4720

Flagging @allenjlee!

**Comment by jheer** [comment]
Yup, found the root cause here:
https://github.com/vega/vega-lite/pull/4720/files#diff-76015606d4b117c2e2082fc707e94a07R47

It appears I can add `clear: false` to suppress the error, though I'd prefer not to have to do this. I'm not sure why we are using `mouseout` to _automatically_ clear `mouseover` interactions by default.

**Comment by allenjlee** [comment]
A temporary solution right now is to set `clear: false` in the Vega-Lite specification under `sel32` in your specification example. This will return to the appropriate behavior.

It seems like the problem is because we append the following to `on` in `_toggle`. 
```
{"events": [{"source": "scope", "type": "mouseout"}], "update": "false"}
```
However, this is needed for other examples, specifically: https://vega.github.io/vega-lite/examples/interactive_query_widgets.html. I'm not sure what the best way to resolve this bug is, one way is to flag it so that it doesn't automatically add `mouseout` upon seeing `mouseover`. What do you think @arvind?
