### ISSUE TITLE
tooltip breaks boxplot mark

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#4882]
Tooltip channel will brake example https://vega.github.io/vega-lite/examples/boxplot_minmax_2D_vertical.html .
I guess it's similar to #3220

In fact, my intention was to investigate outliners  
 
![visualization - 2019-04-16T235726 767](https://user-images.githubusercontent.com/11561581/56243495-6b70c880-60a3-11e9-8b00-895e64aa84e7.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A vertical 2D box plot showing median, min, and max in the US population distribution of age groups in 2000.",
  "data": {"url": "data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"field": "age", "type": "ordinal"},
    "y": {
      "field": "people",
      "type": "quantitative",
      "axis": {"title": "population"}
    },
    "tooltip": {"field": "year", "type": "quantitative"}
  }
}
```
[Vega-Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgquo-HRiwAJgAiYdtwAeYQmO54wsRG4Ad0YlajBUZE1GdCVVCND42M0I9E9QsBZkMABVAGUvbkJWMXQjZTBo2Dx9dlZypTBuADMwdGps6l1uVmIwDIcABmG6NQ1ITTLMHGBIVl0xbC0p0kIikrLjeUUVAF91CEgMXQBrJdm8AE9CZCXIN3dvXzUoZHc8ZCU8O9RQkQx3JB9uNPvBuNEwucNIdATNIM1GMgxJo7u1bvFIFcbnduLoIXYgQcIFBLlDicT4YjkXcbkUxOjoRSsbdTABHVixIx4TZUMbkw5pRiwc6Y5j0mnrUoNIGM4HkzHcbhiIyEEUIpEo0yXZDoXQvTHXFlQdmc5g8267DSW3ZAA)

**Comment by domoritz** [comment]
@chanwutk Can you look at this?

**Comment by chanwutk** [comment]
`year` is the field that is not present in `x` and `y` axes, so extracting transform from encoding also group by `year` when aggregating.

@domoritz But, I do not think it is possible to have a tooltip that gives different values of `year` in one `boxplot`?

**Comment by iliatimofeev** [comment]
Will be cool to see tooltips on outliners.

**Comment by g3o2** [comment]
"outliners"?

**Comment by iliatimofeev** [comment]
@g3o2, sorry I misspelled 
My original chart has outliers and I want to show an additional field on the tooltip.
![image](https://user-images.githubusercontent.com/11561581/56292159-4cb81380-612f-11e9-8e20-e51bf67661f3.png)

**Comment by domoritz** [comment]
Oh, you're right. The behavior is expected. I read this as a feature request to add tooltips to the outliers. That's a great idea.

**Comment by g3o2** [comment]
With whiskers reflecting min-max, rather than with 1.5*iqr±quartile 1/3, there will no be any outliers.
