### ISSUE TITLE
Selection initialization happens too late.

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4889]
- Open [this example spec in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQkCFQgz4cYANqbIkUOatbMAJwDWRy9ZcQo+AJ5EURqBwy26mauVlAIkkRG+LZsKBohLmE84jyBuFAAxCgyAOw5CABMQQnWUDxEGAgsHkYADPQ5wa4AvvElUHAo4igI+LyquM4lWp3dvU5Nw1qe3r5wTMo03cVTpQBmTF0AJnBGpqsJUB4oAVCTqwC6bQdaCywTN65HJ2lgAIwAHACstedTrX9hn4FlsHo9SgsiGxDOlbBhFj5ruCbAsjJ8fkjkdBMAAPIwFWqEzHIjr4FCRXBvX5Y5qAly04YAoHReFwNapNB7OnWIaPKAbcRk15QLYGNhoeidHFgAC8MrARW5ViZB15N35TEFKFeapJox6fRUcy6BrONKV5gZJSuSqgKGUui2CxoYNWUDxgwtiQ22183nKy2JbpmPnSAEc2PC+vgDExqCtwVAMDQaLYRGS5uKE3yMDimLtPVjzPyOQY5mbkSrE4gMMtC0W3FseJhUbh9g2rLUg0W3gTCf2vQkLoPld2gUpbDDoFsUIh7U7Ftn1dG69AAGLoWsoMAABXKbHEsaNI6rUyOrr5PvEoPSycRI+LId8qQXtaXBw6+lXusTcIRAGUyQpd4vjHD8mxbAYTAfEoAE4uxghJvjA8EPgQjsrByUDEJCHJ0IwyAADZsIIoj8NIr4SNIsAMRw1wABYqNI+jyIImQmLY1iMIKDjuK4js3l4gT+IbISG2pDthxpFCQiTPMCzAZQD3EE8lVPJ4AHcmC2Vh8R+P51IsW07Ecetgy8UNoH8QIZOLcImGA6JYlsrRdBSYUMjeNY8g4ej30OcpKmqOoGjUmT3D-NkOS5G4fzPAUhV8UV8HFSUUGlOV3grVZDISOKgQS7ULyxDoTV6fpjTGQwcKtHKlRtIF7UdZ1ivaD0wHy9orxvaB-SIQMcPcCzfAjKMWFjeMXNKZNU3TSyOizKbQlzfNWsTdlbEwKcOmyx5crPGtvzorQIIwVtoOosARJ7Pt+wkhspMrJbHxYVcoAAWS3Xd90PQ1VBPJbzzMy9NmvXw738s8n3SF8FjfZ6Ri-SzOrdP8aBQQDyTRMS+VO8721I+CEaQnGsTQ4ncNJ5E8Ip1xiNplxCOurFKIZ6xaMuxi2asFjufMdi+cgGRmeRHjBYgAlxZAqWqSlqnwXuotHvBfagRWhSUah17LKU8RxG59wmAQewFLWWtOhq1TGXCrSdKQPTFctYIGpOgwsGB4s2FscQkrdsgiB+o9lAUJR-stJE-B4NhlB2Xw1nENg4HtiO4AqKpF1wX5miAA)
- Remove the `"clip": true` directives for the two bar marks.
- Observe that the chart bounds are too large (scroll to the right to see the actual chart).

Expected behavior:
- The chart should look like it does in the clipped case, but without need of clipping. It looks like autosize `pad` is being invoked prior to any data filtering, which means that the initialized selection value is not being passed through to a filter in the first Vega dataflow run.

Ultimately, this may require Vega-level changes. It looks like the filtering is dependent on the selection store being populated. As this process is modulated by a `modify` expression call, it gets delayed to a secondary data flow run. I'm guessing that by that point it's too late and the layout has already done it's thing. I'm not yet sure, what, if any changes to Vega are feasible here. So if there is a way to address the issue with changes to the selection logic I think that would be ideal.

(Also, note that the issue only arises because I'm setting an explicit scale domain for the x-axis! If the domain is determined automatically it of course fits within the plotting region.)

**Comment by jheer** [comment]
Update after examining the output Vega: If I remove the `select_init` signal and instead directly pre-populate the `select_store` dataset, the bug appears to be resolved. Here is what I put into the store for the example linked above:

`{"unit": "concat_0", "fields": [{"type": "E", "field": "year"}], "values": [1850]}`

Note that if I remove `"unit": "concat_0", ` it also works. I'm not sure why the original `select_init` signal includes the `"unit"` key but the selection entries generated from subsequent interaction (via `select_tuple`) do not.

On a related tangent, it appears (at least for this example) there is really no point in including the `select_init` signal at all. By initializing `select_year` to a value, downstream signals such as `select_tuple` will already evaluate and call `modify` to populate the selection store. (For this reason, even with my fix above, I'm seeing a redundant execution of the dataflow upon initialization. It would be nice to prevent that from happening!)

**Comment by arvind** [comment]
Fixed with #4934 thanks to @djbarnwal!

**Comment by domoritz** [comment]
Fixed by https://github.com/vega/vega-lite/pull/4943, not #4934.
