### ISSUE TITLE
Adding a joinaggregate breaks the chart

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4894]
For example, this chart is broken even though the encodings do not reference the transformed value ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnChNhYA1vkgAHMlTbxIvCJBpsAxmWhSA5vlAR5ADy2R4ATzE1RARwyxpVRPCoUz3KADNaOaKICSAWQAiAEIA+gBKCBpccjqQRgbGphZWNnYOTq7unqiQIWTw8IpBACpkAvBk9KHhbJqcfDx8hljWdC5kWCT4ANp8ENo68kySbLDq6lg06ghmqN39-ehkYqIkNNay6TQeooQYJAy+gZX21euQsHTe-sEra7VzYAC6PWB3jyCcQA)):
```
{
  "data": {"url": "data/movies.json"},
  "mark": "point",
  "encoding": {
    "x": {"type": "quantitative", "field": "IMDB_Rating"},
    "y": {"type": "quantitative", "field": "Rotten_Tomatoes_Rating"}
  },
  "transform": [
    {
      "joinaggregate": [
        {"op": "mean", "field": "datum.IMDB_Rating", "as": "IMDB_mean"}
      ]
    }
  ]
}
```
![visualization (70)](https://user-images.githubusercontent.com/781659/56441764-fc61c280-62a2-11e9-9ed5-c121e1fb6eca.png)

Removing the transform makes the chart work correctly.

This bug appears to be currently affecting the final chart in the Join Aggregate section of Vega-Lite's documentation:  https://vega.github.io/vega-lite/docs/joinaggregate.html

**Comment by jheer** [comment]
Looks like the problem is a bad specification. The `field` property of the joinaggregate should be `IMDB_Rating` not `datum.IMDB_Rating`. If the datum-prefixed version is in the docs that is definitely an error!

**Comment by jakevdp** [comment]
Ah thanks. That explains my chart...

I guess the broken chart in the docs is broken for some other reason.

**Comment by domoritz** [comment]
Hmm, yeah, https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVNwqNkseYpXrDUAGbcTGPBeCQhOgmsMj+kABKyGLI6KEA+gAiOmE4kNp4yFgA5ACkmiK57IUAntmQAL4VGhVuUHgm6EqwXj4WANoaEAEejGKZJhbpOqyodACSALKJAELxETqMStRgAIQAvGBKrGLmtV1gBu6efQP+B+6QeIyoyACqSsxDJbGDdccn0ZpDUTFxyEkUmoLoZII1lqkwO1trtVGAAEwABgAjABOAC6IOq7n27iOlzk3CW6Go1BMwkyHRB3Ug3EIQ1uTTUnzE3zSU1m80Wy2ZkDiQwAglRGtRkAtrjzscdMTj3ocQZB4OgxPAdkC0hlRhNpnNxUsViIwJqxkLkCKxdzqMCPnzYD9LYlorpIAcpei6pAMCYANZDQhEpR+D3IJTwbiafXnS4AD3CvS+P2isQSyUpcKuJUIkKuaH9jT2csgJSjx0g8dZ9ol1Ed-UwcqMeEz2YAjqwmtddNcqNbS+ho4w7forswYpX9WAa86pRApdUKkA should work.

**Comment by jakevdp** [comment]
If you delete the ``data:format`` argument, the chart works: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVNwqNkseYpUaAvuqN4T6JbABm3CaoFgDaGhDAkP6MYnjIJhaQ2nisqHQAkgCyACIAQgD6AEo6jErUYACEALxgSqxi5h4RYAaGRjFxCRZt7V6MqMgAqkrMSQCeyOiJnn0dDmKaSUXIYlOwyAU5OshqLe2QPuW7OKH1japgAEwADACMAJwAuvtgbi3N7b2GkHLcZehqNQTMJ4mFXpFINxCElBr41FAYqsljhINl8sVSuUEZB0LAkgBBKg+ajIEp4MrUSDvOYvdqfQzfIzwdBieANHZJFJpTK5QrkylgERgbnpIkJQFkrFU2YHPHLaU5Va6SAfDRPWaQDAmADWSUI-yUeD2RmQSng3E0lJ6LUgAA8etEFiioCs1njNtswZdIHhxoQTlB4qgDT4mrKoOMbXMnciFRTykq4pgI15-YHIABHVi+Cm6ClUE19XF2xj4-S+5hreOCpMqmmGBvvNxAA

**Comment by domoritz** [comment]
We changed the format in https://github.com/vega/vega-datasets/pull/62. This should have been corrected.

**Comment by jakevdp** [comment]
Did that date format change lead to the incorrect years in the dataset, or were those there previously as well? (I hadn't noticed this before today):
([vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVNwqNkseYpUaAvuqMYTAawuRCbkYlPDUNSGQleG5NYOoLA0NIAA8EyAAzBzFNfwAlZDFkdFhkAH0AER1kNSg8AE9CapxIPDRAk3RzDw0jOoSepMyCnOaASQBZcoAhUtydOLDDJPrG-wBHVnQQ5nmqSAG3dxA3IA))

![visualization (72)](https://user-images.githubusercontent.com/781659/56452692-fc84b100-62e8-11e9-96f4-97d98478b3ac.png)

**Comment by jheer** [comment]
There are a number of incorrect elements in the dataset that have been left there (indeed created as such) on purpose for teaching reasons. Some of those years are off-by-one-century! There are also join errors where different films with the same name were joined between the IMDB and Rotten Tomatoes datasets. There is also some significant sample bias, various null values, and so forth. It's a useful crash course in dealing with "real" data. Always be skeptical :)

BTW many of these issues are uncovered and discussed in our curriculum notebooks.
