### ISSUE TITLE
impute key not allowed

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4898]
<img width="387" alt="Screen Shot 2019-04-19 at 21 46 14" src="https://user-images.githubusercontent.com/589034/56452877-9c900980-62ec-11e9-911f-c29301bc0dc0.png">

@invokesus Any explanation why?

**Comment by invokesus** [comment]
If the user sets the _impute_ property in the _x_ or _y_ position channels, it sets the other as the key.
Here's the relevant [code](https://github.com/vega/vega-lite/blob/88f132e041fbf31c6fd3572f511d8f0044372a0b/src/compile/data/impute.ts#L40). Hope that helps 🙂

**Comment by invokesus** [comment]
IIRC we decided on not adding _key_ and _groupby_ to the impute encoding to keep things simple and to use the impute transform for use cases requiring non-default values.

**Comment by domoritz** [comment]
Thanks for the clarification! I was looking at https://github.com/vega/vega-lite/issues/4895 and noticed that the `key` property wasn't accepted by Vega-Lite. I now see that we automatically add it.
