### ISSUE TITLE
Support Google Closure compiler by eliminating Array extension

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#4903]
The Google Closure compiler has many advanced features. The current minifier `terser` is good for general-purpose distribution and use, but the closure compiler is often used to bundle multiple libraries into a single page and perform some advanced optimizations like dead code removal and inlining. 

One feature that the Closure compiler does't have is extending native arrays; and it looks like it will never be implemented: https://github.com/google/closure-compiler/issues/2174

```console
17:20 js$ cat vega-lite.js | java -jar closure-compiler-v20190415.jar > vega-lite.closure-min.js
The compiler is waiting for input via stdin.
stdin:1876: WARNING - unreachable code
            return this; // @ts-ignore
            ^^^^^^^^^^^^

stdin:7055: WARNING - unreachable code
      } catch (e) {
        ^^^^^^^^^^^

stdin:8534: ERROR - This code cannot be converted from ES6. extending native class: Array
        constructor(...items) {
        ^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 3 warning(s)
```

Vega-lite extends a native array in only one place:

https://github.com/vega/vega-lite/blob/644b5d78180c8594d406de0822f938cac2616d86/src/compile/selection/transforms/project.ts#L27

And it doesn't look like `SelectionProjectionComponent` even needs to extend array; it looks like it could just be turned into a class that contains an array, and that would be sufficient to permit the Closure compiler work on the resulting code.

**Comment by domoritz** [comment]
Since this is an internal property, I think we can rewrite the code. Would you want to take a stab at it?

**Comment by domoritz** [comment]
Do we want to actually support closure compiler or close this issue now?

**Comment by marcprux** [comment]
Based on size alone, `vega-lite.js` only gets a 28k size reduction when compiled with the closure compiler vs. with the current terser minifier:

```console
16:19 vega-lite$ cat build/vega-lite.js | java -jar /Users/marc/Downloads/compiler-latest/closure-compiler-v20190415.jar -O ADVANCED --env BROWSER  --language_out ECMASCRIPT_2015 --strict_mode_input  > build/vega-lite.closure-min.js
…
0 error(s), 190 warning(s), 59.4% typed
16:20 vega-lite$ ls -la build/vega-lite.min.js build/vega-lite.closure-min.js 
-rw-r--r--  1 marc  wheel  190254 Apr 24 16:20 build/vega-lite.closure-min.js
-rw-r--r--  1 marc  wheel  218465 Apr 20 19:56 build/vega-lite.min.js
```

Personally, I don't think that is worth the extra dependencies (java) that would be added if the closure compiler is used by default. 

I do think that benchmarking the effects of minifying vega and vega-lite together into a single blob could yield interesting results, but I think that would be a separate project with a separate enhancement issue. So I'd say we should keep this issue closed.
