### ISSUE TITLE
facet remove empty axis value

### ISSUE THREAD

**Issue by troy351** [vega/vega-lite#4909]
Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior. 

- [ ] If you are proposing a new syntax, please provide at least one example spec, wrapped by triple backticks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/cars.json",
    "format": {
      "type": "json"
    }
  },
  "facet": {
    "row": {
      "field": "Origin",
      "type": "nominal"
    },
    "column": {
      "field": "Year",
      "type": "nominal"
    }
  },
  "spec": {
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "Year",
        "type": "nominal"
      },
      "y": {
        "aggregate": "count",
        "type": "quantitative"
      }
    }
  }
}
```

You are encouraged to prototype multiple alternative syntaxes for your proposed feature. Doing so often leads to a better design.

- [ ] If applicable, include screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working example (e.g. example Vega specification for the requested feature)

![image](https://user-images.githubusercontent.com/8372385/56494382-a00dd580-6524-11e9-9bcc-45ce38072745.png)

In the graph above, some X axis field doesn't includes any value, and I want to remove them.

**Comment by domoritz** [comment]
Just out of curiosity, why not drop the `column`? https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070peOhOx5ilesNQAZtxMY8Fg66h4AJ6EyBaQCsqQGhAAvhoxLu7o8Mg++tFQJtwA7r4ZRm6MyGKaYQDyJoxMzvkBwaE4kErcqIxK6OYZcbGJkLAh8HmukBgmANZh7HZqGZDISvDcmm3UQ-6QAB5r-u5FJWEAmsjTiTuQQSFhza3tnTsJtZCB2+vo1NQmwngNUIusSj5TusLj9IABHVjoAHMHSMKhRe5deIgGJAA

**Comment by troy351** [comment]
That is just an example
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/cars.json",
    "format": {
      "type": "json"
    }
  },
  "facet": {
    "row": {
      "field": "Origin",
      "type": "nominal"
    },
    "column": {
      "field": "Name",
      "type": "nominal"
    }
  },
  "spec": {
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "Year",
        "type": "nominal"
      },
      "y": {
        "aggregate": "count",
        "type": "quantitative"
      }
    }
  }
}
```
This one also has the same problem.
BTW, above code crashes in canvas renderer but works fine in svg renderer

**Comment by domoritz** [comment]
I see. What you want is scale resolve. See https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070peOhOx5ilesNQAZtxMY8Fg66h4AJ6EyBaQCsqQGhAAvhoxLu7o8Mg++tFQJtwA7r4ZRm6MyGKaYQDyJoxMzvkBwaE4kErcqIxK6OYZCRmQ8NxirKgq6f7uRSVhAJrIdmq1kEEhYc2t7Z2ucbGJkLAh8HmukBgmANZh7LOJRshKfZpt1Af+kAAeT6OQhcWljdOXtUZFg0oCs2h0oqNuh9Au9nuhqNQTMI8MDetxWEofFdnkCwgBHVjoTHMHSMKgQ-ybQxUqGZZCKMTkkaGHa2MTAvyHN6NNqaZAhJR8zEU2LxEAxIA

**Comment by troy351** [comment]
Scale resolve works, but it's a kind of ugly. I do like the apperance without scale resolve, which is aligned and only shows the x axis for the last row.
try
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/cars.json",
    "format": {
      "type": "json"
    }
  },
  "facet": {
    "row": {
      "field": "Origin",
      "type": "nominal"
    },
    "column": {
      "field": "Name",
      "type": "nominal"
    }
  },
  "spec": {
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "Year",
        "type": "nominal"
      },
      "y": {
        "aggregate": "count",
        "type": "quantitative"
      }
    }
  },
  "resolve": {
    "scale": {
      "x": "independent"
    }
  }
}
```
with and without
```json
  "resolve": {
    "scale": {
      "x": "independent"
    }
  }
```

**Comment by domoritz** [comment]
I agree but that's a separate issue.

What specifically would you like to be improved here?

**Comment by troy351** [comment]
I think I want x scale to be shared within a column but independent between columns.
like this one
![image](https://user-images.githubusercontent.com/8372385/56626123-fab54780-6672-11e9-9e4c-938c35e9ce7d.png)
