### ISSUE TITLE
Data merging logic merges datasets with same URL but different format parameters

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4910]
Vega-Lite's data merging logic is over-aggressive, leading to major errors.

To replicate:
- Load a TopoJSON file twice, once using the `feature` parameter and once using the `mesh` parameter.
- Examine the compiled Vega spec to discover that the two have been erroneously merged, like so:

```json
{
  "name": "source_0",
  "url": "https://cdn.jsdelivr.net/npm/us-atlas@2/us/10m.json",
  "format": {"type": "topojson", "mesh": "states", "feature": "counties"}
}
```

Expected behavior:
- Different format parameters should result in different dataset definitions.

**Comment by domoritz** [comment]
This is bad. We should be able to resolve the error by fixing the logic in https://github.com/vega/vega-lite/blob/875d772bf7dcd2cf9fc0616c998d32d7013d42df/src/compile/data/parse.ts#L58.

**Comment by domoritz** [comment]
This is bad. As far as I see it, we should be able to use the same source but since the format is different, we have to have a fork in the dataflow. 

@Saba9 do you have a few cycles to look at this?

**Comment by Saba9** [comment]
@domoritz I'll take a look at it. I'm pretty busy this week so I can't guarantee I'll be able to get a fix in until the weekend but I'll definitely give it a shot.

**Comment by domoritz** [comment]
In Vega, is it possible to load data only once but use `feature` and `mesh` in separate data sources? Or does Vega internally avoid loading the same JSON file twice?

**Comment by jheer** [comment]
It is not possible to load data only once but use separate formats in different data sources. Derived data sources do not accept format properties. Vega does not internally avoid double loading. We could add internal caching, but I wonder how much browser caching already helps us.

**Comment by domoritz** [comment]
I suspect that even though we do browser caching, we still get the overhead of parsing the JSON document twice. I don't think it's the most pressing issue but eventually it would be great if Vega supported different format properties for the same source file.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/4914
