### ISSUE TITLE
Broken link in box plot documentation

### ISSUE THREAD

**Issue by fedarko** [vega/vega-lite#4916]
Hi: first of all, thanks so much for Vega/Vega-Lite! These tools have been super useful.

I noticed that there seems to be a broken link in the Vega-Lite documentation [here](https://vega.github.io/vega-lite/docs/boxplot.html#parts). You can find the location of the broken link by ctrl-F-ing on that page for `"median" tick`—the second example spec in the `#parts` section is replaced with what seems like the HTML of a GitHub pages 404 page.

**Comment by kanitw** [comment]
Thanks, will fix this in the next version. :)
