### ISSUE TITLE
Boxplot missing/broken whiskers when using timeUnit

### ISSUE THREAD

**Issue by semiamaurotic** [vega/vega-lite#4925]
When I try to group data by weekday or month (or any `timeUnit`) and use `"extent": "min-max"`, whiskers are displayed, but when using the default 1.5 IQR, no whiskers are drawn. If I switch to `ordinal` or `nominal` types, detached whiskers are drawn in a new column. This seems to be related to issue #4524 

![image](https://user-images.githubusercontent.com/13118282/56909215-d2b05480-6a75-11e9-8c6c-e694606ff571.png)

![image](https://user-images.githubusercontent.com/13118282/56909955-5b7bc000-6a77-11e9-8db2-c5954ae84ba1.png)

![image](https://user-images.githubusercontent.com/13118282/56909195-c7f5bf80-6a75-11e9-99f9-0456a49af7b2.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.2.1.json",
  "hconcat": [
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": {"type": "boxplot",  "extent": "min-max"},
      "encoding": {
        "x": {"type": "temporal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    },
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": "boxplot",
      "encoding": {
        "x": {"type": "temporal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    },
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": "boxplot",
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    }
  ]
}
```

**Comment by mattijn** [comment]
Run into this issue as well:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/5186265/65900765-03930d80-e3b7-11e9-99be-46324d73211d.png">

I found out that when adding a `temporal` tooltip the outliers are placed on the right places and not on the Jan-1970.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.2.1.json",
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"
  },
  "mark": {"type": "boxplot", "extent": 0.5},
  "encoding": {
    "x": {"type": "ordinal", "field": "date", "timeUnit": "yearmonth"},
    "y": {"type": "quantitative", "field": "temp"},
    "tooltip": [{"type": "temporal", "field": "date", "timeUnit": "yearmonth"}]
  }
}
```

(had to reduce the `extent` to get some outliers)

[editor-url](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCY6ARjoArWNwB2kADTgoAE3R5MOUBAiRWAJzHZcBYmSG0GzNpx7PRh47GR5YUh90PmQjPDFkETw0Yjp4WApIPQBfXQsMKwBrO2BIPABPQmQ7SHZuAA9CMW48HShkCpiNOpwABjoAVjS9SGQNeG59Rg1qXL0LCtz8opKcSG4rYY10W20oADNGZDF9Up8S9fzGVGQAVQ1mUoKwq1RNFkge8ygC6cLi0oBHVnQW5iMjCo9UgWx2e3mMVQhCe6XM+W43DEeEYMJwAG08h85lAoYRFqsQWDdvsjIdcSdzpdWq9bvcWogngBdVIgFJAA)

**Comment by kpm-at-hfi** [comment]
Following
