### ISSUE TITLE
'valid' filter exludes all rows of ordinal/nominal data

### ISSUE THREAD

**Issue by WillMLumere** [vega/vega-lite#4928]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "transform": [
    {"filter": {"field": "a", "valid": true}}
  ],
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

The above spec renders no data, but I would expect it to render all 9 bars. 

The compiled vega:

```
datum[\"project_created_date\"] !== null && !isNaN(datum[\"project_created_date\"])
```

Presumably this calls JavaScript's global `isNaN` method which [first coerces to Number, potentially returning true for strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN). It may be `Number.isNaN` which is desired here, [returning true only for literal `NaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN). 

The `Number.isNaN` behavior can also be emulated with the following expression filter:

```
datum.field !== null && !(isNumber(datum.field) && isNaN(datum.field))
```

**Comment by domoritz** [comment]
This is expected behavior as described in https://vega.github.io/vega-lite/docs/filter.html#valid-predicate.

**Comment by WillMLumere** [comment]
@domoritz docs say "both not null and not NaN". In my example, the value "A" is both not null and not NaN, yet it is excluded by the valid filter.

**Comment by domoritz** [comment]
strings are not numbers (NaN = "Not a number").

**Comment by WillMLumere** [comment]
Strings are neither NaN nor Numbers, as NaN is a value of type Number.

**Comment by domoritz** [comment]
I think JS disagrees ;-)

```
> isNaN("hello")
true
```

**Comment by jheer** [comment]
Hmm, I don't know what exactly VL's `valid` filter maps to, but in Vega's case (for example, when counting `valid` values in an aggregate) we define invalid values to be:

`v == null || v !== v`

This removes `null`, `undefined`, and `NaN` values -- actual floating point `NaN`s, not "number-coerces to NaN", which is related but not the same. String values count as valid in this scheme.

Not sure what is preferable for the VL implementation, but in general VL tends to follow Vega's conventions!

**Comment by jheer** [comment]
p.s. JS disagrees with itself:

```js
> Number.isNaN('string')
false
```

**Comment by domoritz** [comment]
> p.s. JS disagrees with itself:

😞 

The idea of the `valid` filter was to use it for numerical data. We can adjust the behavior in Vega-Lite to make it useful for strings and dates as well. 

@WillMLumere Would you be willing to send a pull request? That would be fantastic. Thanks!

**Comment by WillMLumere** [comment]
@domoritz Thanks, I will prepare a PR.

For any who come across this thread in the future and are confused about the apparent disagreement between `isNaN` and `Number.isNaN`, there are links to documentation at the top, but this gist is that `isNaN` performs a type coercion to Number before comparing, conceptually it is like `x == NaN` whereas `Number.isNaN` is a strict comparison more like `x === NaN`.

**Comment by domoritz** [comment]
Thanks for the insight. JavaScript does not cease to amaze/surprise.
