### ISSUE TITLE
WARN Channel opacity should not be used with an unsorted discrete field

### ISSUE THREAD

**Issue by melissachang** [vega/vega-lite#4929]
https://test-data-explorer.appspot.com
Javascript console has:
```
logger.js:8 WARN Channel opacity should not be used with an unsorted discrete field.
```
A couple questions.

First, is it a bug that if I paste the vega spec into [vega editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSALJQBWENgDsQAGhBIGmNhBoAvOGhA4kAE2kbtWmuLJpQAGzgAzTGgAMMhTjQBGAOwyATjTJZbMpm2w2BGcANgBfGQB3Gi16NAAmEIBOSiSQmySAZhcAVhkITABPc3UoOFNTXS0kTBRUAG1QcSQENXQxBncygH0bXWIkUwY4CDRGkAskMsxugaG2kBsAIQBaJKXdKDYGcWtUJxycgRkDBFadVEnTCDh7OAAPPcXV9dQAAgOj3TZNAEdhtCYdzDCKgSbTWaDAHoJzLFZOdabba7Zw2ATHECnc5oK43O6PdSw1YIpbvWHo75-aFAkFSMFTOAzObQkDxOHxREyLY7Pbok40M5wC6424gTAPJ5s1Yc0lvCkyH5If5tGlwUETBlMqELTJwzKckDclGoTLxfmC4WDPFiiXqXWrfWy02UpXU4FqukaiHMhYCOECA1GvaZc3Yy5W0XignoP2rANOl3KwHu9XgxmQ+bqHJwnKB5F7OyYgVhkX4p7Z1a52V9BVUlUpz1prWZ9DpVbJDZc-O+IsWnERsvqNsrDvvGsgRVJ1Cq1OajMslxwlx5nkJUNC-vXSO29CL1bL2XxRNu2n073a9QADjhl5XxsLWI34a3g-Q19Wt+rx-rp696Z96hJHCSR3gW66Wi+NrRiAQEvK8bzjpOJ4eme-4XjCNhwrCoE9o+EHWlGTywlhGRfrWro-ihf7NiyThEvCJJIqu+zgZuBE7iAdFYSSZLfsmv5NvOCzAZ2hrdvshwYnhbHbtBIlkpJfHPjcs7ni2nFYThElHKxymyURmmyuSAhKSKqloepUorDKTHGp8UnFk+pZQZK7LwfKE51jJ5k0TqepafZunOYRdr+U6R7kVOZmNnOAExv6AWSUFA4ueosYrPG7yZKZEY+UJWY5olOm9iWKUhegFYrFWY45VueVxSAw4drZeyBSVTllRxTXwYhXl6fV6EgHuKwHi1zhJe1+H6eow0Hu8EWeRR3kxWpLLvisn5jdpDl9npr4gOtn41ZF0LRahvmAcBRU7aVkHlTBV1kYtUW5StFm0ZhxKkVtbXSXtqUYSRPW1Spb0XTC9F0ddyV3RxXHEjxHwg2qAC66rNK06jVLUvS6B0XQLPjPTjkCSDiBAFhsO4wQNKARQ4AslPUwwpgoDIDw4O4WM1AwCD1AAOtRQmCyjAC84uC-DDHrILbwAPwIW87zY7zAtCz6Ivi6LkuffCpGywrThK28Kt84LgkayAYsSw9cFLAbbzxMbptqxb2qazbh0yyA8tvJkzs82b6vu1bWuC7N3u+wIAeYKr5uxSH1va41cIdg7OQx3HwfzB7yeVVWDshJnQduznoc2+l8YOy4xeuwnZdJ4L9orI6DuXrX8erXAueC1ZMoO0kHfZ8MPcacSkeGzYQ+lyP5fJyJDt0cbTgLUgozoIU3Qz3A3RiO4MyGFoDwgGEaMo-kXjNNcYxNC0CybwUcCODIcWZE46N3+o8BeD4MgMDg2MFhMDJloCAmgygAAotBBCQIYCBAByQo8CACUlBzBGHoFIBClABBmmwSvZBbwABUbwH7ikcKfGQyB3AAGt17jAxgsahdDdD0wWO4OAUBrD5CKCUBoIBgFc3PhMdwQQTCYhqHUCROM+gRBAHAcQWwj7iP-oA8RUBOh73EQ1HAbBDDii5nIiwNAKg3xtAUbmscg5BhFm8LWbxxAs1MG8AAPi4t4NAIAADkkBeKgYHNWNirbIP6OhRxFR1TQEGAsLYpgqa6GMeUC4k0T7CMVFAOghRxFRL4YtDJRQEk0CSeoJCag5EKDYKYTANBHCoFAEoMgV91DwPgQAahdoLQiIsT4yHuNkqA0T1B9JkIk0wySgw9JAPcI8dSQA5IWMMkAcUbByKybM+Z6gskjKKWM9Q29Jnf28HsepAzclbIESA-iaowg3OEfM+ht9MboEWWw9QphDBwCQFzE4MDDDiOxlIgFuNtnFPQBMuR7gyZkDaPUOw9TL6DHUNEWIMBUkyHEDQMoVyZCqFEVcj+TyQDnNeegYB4gdA-OQH82ZALLFIGBRMHZyT9n5Cpsczy6gEB-JBbsjeW967DF3my7oh9j43I8FCto9TyHZIRZUPlj8KFyM0FoAwRgACS4hxBwC5qgGwOCzR6FVYYMgAB5eQOrbCUBXjIQYl9bAEpiZU+J9hCgMxKe4NViLKWwMkDSyRdKGWjOSdJVl+98USqMDCkAABiAQAymBaBMjIGNTALBwCcBYPoaNPSMJKeAzJrC3ULF0foqovy-WgFpegIF45g35qWmGvYM5I3QrGHYJwZ9bX3BGGYjZzzvieAUU8fwgRggyDIJ4KaMhWZMHKAAMQkJgAAyioNosIZ1IDnaYedQwICounO6Td27TWkHcKzWpqp7CYpoQAYXEvCxpiKwVwBMRA5F9ACB+hCXI5Qoq+n7EiachZg6inGgEQEBQ46QCTpiMu4DmzdCwYuFesUN773MUfU0l9b6P0wC-TYH9PrqXOVneUdezlkD3AAKKPGHT2Ll4haPinvNeqALD-p-vJcfPVQHBkb1A-R9A5grBIanTJY9C6l2rtUM4Q1ZHTAABkBR0Dk4WLjR8ANOHZootgyjZkKfXqAfROqpjVNINikAqiahSrFGwSp1TalYefdI3mlAfRvFaW8eB7x4GeZNpIhBRMd42BQfUdBZB6D+NqEF7YBNegoOQQQJ2KwPhvFS6InYWgIEQM8T4vxptWDcfuMguWNhUCFf-YQkhECItRYBbFzoxNEvJfSx8ZByCUaUHBTc25XZxDGOMLMpA9xPH-IrfeuJurY1IDgEwTIwCxMxEm-E9AMa5tCksLoBTK3psxsyAdiwOQFoKcXeBgAskum47hIXcJAKdpdAB1V9Ry0DZkLApgACvoE1aAkhsY49FWQo2IAAE1xGMeY0J3UvWgA), I don't see a warning?

![1](https://user-images.githubusercontent.com/10929390/57044805-9e2ccc00-6c20-11e9-9d2a-e5511e8118a0.png)

We use [opacity](https://github.com/DataBiosphere/data-explorer/blob/fed1dd7a95791db19262bf6e99f9ea400170f494/ui/src/components/facets/HistogramFacet.js#L64) to create transparent bars that show tooltip and are clickable. For example [see `110B-119B`](https://test-data-explorer.appspot.com).

The opacity is working fine. Can this warning be deleted?

**Comment by domoritz** [comment]
The warning comes from Vega-Lite. Try the Vega-Lite spec in the editor instead.

**Comment by melissachang** [comment]
Oops, thanks. I see warning with [vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCjxlAM0bVsYUBAiR0AD0awDR4yYAm3DIyUBhbmO4AnA5ADE6ZHZpdkx1WxNqT0Y7Nw9vHD9A5DtkbTUNW0gxdHZkMVivH19pEu0AVgAmdPCobNyxADFlPB8AWWbYZE9PdBaw8KycvKalPAB1ZD18AzKABln+zLq8gAV0OztnfRwATkXjSDxGeABrKxxtdDFOjLAAXw07-shkJS1NpW3DW8gtOOtbiZdHk7D5NqhUMlqgM8ABPQjIHxKRzOK7QzIIK6InDASA9T7YsAAbT8ABZ4Dk7KS1FBfOxtMgAIzaWaQAC6T0BtRor1BOCUrDEYlunMyeG47iOhGskGBYj5UDwyDMfUV8MJkGRqFRYkgooOZgBNVMFnOhkG9RGeAAyowAF6ExmzfWZOUK37cVijdEHOEInwAR1Y6FGzF6jCoPpMRzwYg1UagsDw6FOBgFQpF+0gsKNAzdPku8GQeAA+hQrqxEfto+qkSilGjq4rmHG04KxE3IIpPC0cCSGRhW6ooIPEWzO+ZLDLlo1mraHQZGRVhxa8gAZRja3tgJfOzuY1s4vEh6jIa1K6U4aSMleEdYfagASSUSi6BlmdFJy6gd42WwA8qwSrxGAH5Lg8tgulA3B3vAzA5jiXKyowII+DB6BBlWSF+hqWo6gmXYUoe5r4qeBhEgsO4cp2cankoCrpsKkGPM8GCeCcMo4T4ITeCu8CsJ43Y+IQ3DOMBerPL+D7Tqk26UYcMGLgA7CuUTUNMODyew3AEI4i4AGz6pAADu0QsAYFQABw7HQOyWWU0hlIyZT6RUZTPHYvSYIhmTlmIlZmkSXI2MahbFmWFYagOWIJiYWhetujJKfpCxcvYm6QgqlzXMgTbRsq26ymgWI4ElKWxdBd6YQYeCeJWXJQRAIV5im4V+ZWPijhVHoJcppKpTU6UQlCFxXJ0eWKgVnUlTuSn9d16HVTgtX1TUjXfINUBhaW7VRcVQ5pZonreqVyUDYNkDgplBjZeNh2HFNCTRXGp3lRNkCLR1o05Q1TbNa6rU7ZF00HZtPUnbNKXvVdI1gLduX3UqKog8gp3ze9n2EvDDW3GyjwgHcQA).

**Comment by domoritz** [comment]
The warning is expected. You can ignore warnings but they give useful hints.
