### ISSUE TITLE
Sort by encoding should have a short-form?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4933]
As I prep for the ODSC tutorial, I realize we should make shorthand for sort-by  encoding as  this will be way more convenient for Altair and VL-API:

`sort: {encoding: 'x'}` could become just `sort: 'x'`.  

`sort: {encoding: 'x', order: 'descending'}` could be `sort: '-x'`?

**Comment by g3o2** [comment]
Isn't `sort: {encoding: 'x', order: 'descending'}` itself already a shorthand for sorting by field? In addition, the minus notation seems appealing but is otherwise nowhere used in the vl schema, isn't it?

**Comment by iliatimofeev** [comment]
why not just `sort: 'encoding'`?

```json
"mark": "bar",
  "encoding": {
    "y": {
      "field": "age",
      "type": "ordinal",
      "scale": {"rangeStep": 17},
      "sort": "encoding"
    },
    "x": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative",
      "axis": {"title": "population"}
    }
  }

```

That will allow switching bar orientation just with renaming chanal.

:) But I think this it is a quite old conversation  https://github.com/vega/vega-lite/issues/1489#issuecomment-396470433

**Comment by kanitw** [comment]
Thanks for proposing, but `sort: 'encoding'` is too ambiguous, so I don't think it's a good idea.

**Comment by kanitw** [comment]
The discussion in https://github.com/altair-viz/altair/issues/884#issuecomment-496216592 also favors this issue.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/5134.
