### ISSUE TITLE
Incorrect axis labels when attempting to parse numbers as temporal

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#4937]
When specifying a numeric year value as `temporal` axis labels only show the last item and incorrectly represent it. For example:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {"year": 2016, "value": 1},
      {"year": 2017, "value": 2},
      {"year": 2018, "value": 3}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "year", "type": "temporal"},
    "y": {"field": "value", "type": "quantitative"}
  }
}
```

<img width="261" alt="temporalAxis" src="https://user-images.githubusercontent.com/1846999/57182082-26b2a300-6e93-11e9-9d94-189c30900624.png">

While specifying the years as strings gives rise to the correct scaling and formatting of axis labels, the labels for numeric values do seem rather confusing. This is something that has confused a number of my students who, understandably, assume that numeric year values should be interpretable as `temporal`.

**Comment by jheer** [comment]
The temporal type maps to Date instances. Numbers are thus interpreted as time stamps (ms since the UNIX epoch). So year numbers should be treated as ordinal or quantitative values. I realize this can be confusing. 

The other option is to provide a parsing format string as part of the data definition so the VL/Vega know to treat the number as a year.

We will take this issue under advisement when plotting possible modifications in the future.

**Comment by domoritz** [comment]
Here is the spec with manual parsing. 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {"year": 2016, "value": 1},
      {"year": 2017, "value": 2},
      {"year": 2018, "value": 3}
    ],
    "format": {
      "parse": {
        "year": "date:%Y"
      }
    }
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "year", "type": "temporal"},
    "y": {"field": "value", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/61170499-543e5b80-a56a-11e9-893c-7913adcec842.png)


[Editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkAJ7J0AJysAmAAwBGAGyqUCZmyFa+AL7q9hCOLu5efgDsQcam5l5RdoZxrh44Pr4AHKkhGTjSEdkAutGGkABm3G4YeFYGMZCE7rBh+tn2znlWkNp4yFgApACakANgVfaLC3WQGG4A1iPsCavISvDcmoxK1O3ZkAAe7Y2MyGKaI-EeqXhOhH1Q46iEzaaQWUGThuDTuDxGZTCr3en0gAEdWOglHhmDpGFQARoqhEgA)
