### ISSUE TITLE
Refactor Repeat as a Macro?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4947]
Our repeat should have the same behavior as using fold (unpivot) and then facet into row/column. We should investigate whether it makes sense to clean up the implementation and implement repeat as a macro.

**Comment by kanitw** [comment]
Implementing repeat as a macro of concat (not facet) might be reasonable. 

However, making repeat = pivot + facet is _extremely_ unintuitive and would produce unnecessary data transforms, so it definitely should NOT be done.  

Also, I don't think this is a "help wanted" issue since it's not even clear that it should be done.   It's also not an "enhancement"  to the language, but rather internal refactor.

**Comment by domoritz** [comment]
> However, making repeat = pivot + facet is extremely unintuitive and would produce unnecessary data transforms, so it definitely should NOT be done.

I don't know how bad the produced code would be. Therefore I'm not sure I agree.

**Comment by domoritz** [comment]
A related enhancement of Vega-Lite would be having something like repeat but for layering. The idea would be that you can make for example a multi-series line chart with three lines (`A` to `C`) for a dataset with columns `time`, `A`, `B`, and `C`. @tvst was asking for something like this in Altair.

**Comment by jheer** [comment]
Though I find the notion of `repeat = fold + facet` conceptually appealing (I don't think you mean pivot?), I should point out that using Vega's current implementation such an approach might induce a lot of additional, unnecessary processing and memory overhead.

**Comment by kanitw** [comment]
> A related enhancement of Vega-Lite would be having something like repeat but for layering. The idea would be that you can make for example a multi-series line chart with three lines (A to C) for a dataset with columns time, A, B, and C. @tvst was asking for something like this in Altair.

See https://github.com/vega/vega-lite/issues/1274 and https://github.com/vega/vega-lite/issues/1552

**Comment by domoritz** [comment]
> I don't think you mean pivot?

You are right, I meant unpivot or fold.

**Comment by kanitw** [comment]
pretty much done in #6002, pending a few minor issues left.
