### ISSUE TITLE
Condition doc is broken

### ISSUE THREAD

**Issue by djbarnwal** [vega/vega-lite#4952]
Condition documentation page is broken. See https://vega.github.io/vega-lite/docs/condition.html#value

![c296130d-197c-4620-ae67-c301985a2489](https://user-images.githubusercontent.com/4402679/57731639-1ce62800-7669-11e9-9ebb-acdcf642f64e.png)

**Comment by domoritz** [comment]
Looks like something went wrong in https://github.com/vega/vega-lite/commit/707e628c4bdf6875fa84f41ecb760fdb5509c92b.
