### ISSUE TITLE
Make `usermeta` a spec-level property

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4962]
See discussion in #4961 

cc: @domoritz

**Comment by domoritz** [comment]
@kanitw and I discussed on Slack that this is a bit tricky and we don't see the value right now so we are closing this until someone comes with a use case. 

One particular issue are unit specs inside layers, which in Vega get merged into a single group. It's not clear what we would do with the usermeta data in this case. 

Also see https://github.com/vega/vega/pull/1776#issuecomment-489255886
