### ISSUE TITLE
Bar Chart legend does not respect `symbolType` property

### ISSUE THREAD

**Issue by johnmdonich** [vega/vega-lite#4963]
The bar chart legend only renders as a square `symbolType` and does not respect `symbolType` in the `config` or directly within the color encoding.

### Example spec

```json
{
  "config": {
    "legend": {
      "orient": "bottom",
      "symbolType": "circle"
    }
  },
  "mark": {
    "type": "bar",
    "orient": "horizontal"
  },
  "encoding": {
    "x": {
      "field": "revenue",
      "type": "quantitative"
    },
    "y": {
      "field": "month",
      "type": "nominal"
    },
    "color": {
      "field": "company",
      "type": "nominal",
      "legend": {
        "symbolType": "circle"
      }
    }
  },
  "title": {
    "text": "Stacked Bar"
  },
  "data": {
    "values": [
      {
        "company": "Company 1",
        "month": "2016-01",
        "revenue": 99.74542441836121
      },
      {
        "company": "Company 1",
        "month": "2016-02",
        "revenue": 124.28320211965155
      },
      {
        "company": "Company 2",
        "month": "2016-01",
        "revenue": 64.77394629723233
      },
      {
        "company": "Company 2",
        "month": "2016-02",
        "revenue": 70.07675051264934
      }
    ]
  }
}
```

The above renders the following chart.

![image](https://user-images.githubusercontent.com/2266667/57798448-c802ea00-771a-11e9-87d2-5ca0acacaf3f.png)

[Link to the vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIBsBTVQ+AE023Fz1gCdlSAXSyAI1iadgFtIAaajUgBnAJ48O+ACpiADoVbRkdaEUhCwAX2pbBeHgEM6Aa0o5ckJvMVZ2xgZsj1G8FnYAWLgF4Imh-A0IPWpIUjgyZHh0LAs8AA9zTTwUQnwKOzpCADdSAFdFfRooawVWAEc8wzdkfyZkXKDcEOExJOKoVPTWHj8PRw6rG1Z4XiiApuCivDh8enbiyC6MqDgeOWq26ctS2yhRnnHA7bwiEnIFwfFJWBlhu2VVdWTtTR0p0PqmdVinJkJ4u4oABlfzQEyEMhgABCDl0RUgZEM-kuUGyAQKIkoAG0XnFFmsNvA2nYAMK8IliMAARgGHSgvTc-TsACYAAzUgBsAFoOXTBllcvACpQAJyigB0AHYACwAVhlLJlMupAA4AMyc6ks6kvFrFfHCQmbVjk9abGn8xaMpjMqDsrm8llW4SC-J7bUyiUsjXsnXU0WcuXUuVyvUnKj01YUk1kmPEsDOiMGPqsB08vnJqBu4V7TleqVS9WimWclmiqUs9VV9XhvEvGbxklQM2UxMuyw2u2QdNOjt4HMirBStkStlSzlSuVs4Ms-Oi9UyvWaAC6uhAWiAA)

Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:
- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by kanitw** [comment]
This is due to the fact that we had legacy code to determine default shape in the encode block ([here](https://github.com/vega/vega-lite/blob/master/src/compile/legend/encode.ts#L47) and [here](https://github.com/vega/vega-lite/blob/master/src/compile/legend/encode.ts#L115)) before `symbolType` is added to Vega-Lite.  This logic should be moved to the [`defaultSymbolType` function](https://github.com/vega/vega-lite/blob/master/src/compile/legend/properties.ts#L20) (with an additional `channel` parameter).
