### ISSUE TITLE
Number format for axis label and text mark

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#497]
Many cases to handle:

- [ ] raw
  - [ ] integer vs floating point
    - From Vega’s data parsing, we do not know the difference between integer and real, but they should have different numberFormat setting.
    - [ ] provide a syntax for distinguishing integer/discrete from real/continuous – maybe `numberType=discrete|continuous`
    - [ ] float: big number vs small number?
- [ ] aggregate 
  - [ ] avg (or other things with division)
  - [ ] min / max (semantic still based on raw)
  - [ ] sum (semantic still based on raw — but could be very large) 
  - [ ] count, distinct() -- always integer

**Comment by kanitw** [comment]
Actually, currently we only call `dl.summary`, which in turn only calls `dl.type()` but not `dl.infer.type()`.   

Therefore, we do not really know if a number field is an integer field or not.  
For vega-lite-ui, the question is whether we should call inferAll for each imported dataset.  
For small dataset, this should be fine.   For a large dataset, this could be dumb.   
Inferring type of samples might be a compromise but I'm not sure if that is the ideal solution.

**Comment by kanitw** [comment]
A bigger issue is how should the syntax look like if we allow users to provide both information about type as level of measurement (N, O, Q, T) and type as primitive data type (integer, number, string, ...)

**Comment by kanitw** [comment]
Using a better setting of numberFormat, this becomes less important -- so I'm closing this for now.

**Comment by kanitw** [comment]
#500 is a reasonable good step, but we should create a set of visual test to test this.

**Comment by kanitw** [comment]
![vega-lite_editor](https://cloud.githubusercontent.com/assets/111269/8818058/f2cf03d8-3009-11e5-8ac3-eac2045e021d.png)
For mean value in `TEXT` , `’’` is a bad formatter.   

```
{
  "marktype": "text",
  "encoding": {
    "row": {"name": "Name","type": "N"},
    "col": {"name": "Cylinders","type": "O"},
    "color": {"name": "Acceleration","type": "Q","aggregate": "avg"},
    "text": {"name": "Acceleration","type": "Q","aggregate": "avg"}
  },
  "data": {"url": "data/cars.json"}
}
```

**Comment by kanitw** [comment]
We are currently doing pretty bad with integer, so this property is definitely needed

<img width="820" alt="vega-lite_gallery" src="https://cloud.githubusercontent.com/assets/111269/12358569/bdfea8fe-bb62-11e5-91ef-ebfd1e85e239.png">

**Comment by domoritz** [comment]
A better solution would be https://github.com/vega/vega-lite/issues/512

**Comment by kanitw** [comment]
Hmm, #512 would require a full schema.   
When a schema is not presented, providing a property in `data` to describe number type (like we discussed the other day) is still useful.

**Comment by domoritz** [comment]
The more I think about this, the more I think the legend issue is a vega bug.

**Comment by domoritz** [comment]
Simple example 

```json
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 0.1},
      {"a": "B","b": 0.5},
      {"a": "C","b": 0.3}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a","type": "ordinal"},
    "size": {"field": "b","type": "quantitative"}
  }
}
```

**Comment by domoritz** [comment]
The vega issue https://github.com/vega/vega/issues/504

**Comment by kanitw** [comment]
Looks like the default that Vega has deal with integer vs float pretty okay, so let’s close this.

**Comment by kanitw** [comment]
From discussing #978, maybe we need to revise this issue.
I think we might not need rule based on numberType (`discrete`/`continuous`)
but maybe `aggregate` fn that involves division such as `mean` should have default format = `.3s`?
