### ISSUE TITLE
Link Issue

### ISSUE THREAD

**Issue by owendall** [vega/vega-lite#4972]
![image](https://user-images.githubusercontent.com/10927/57897651-d8eb5280-7823-11e9-8e1e-f6d6ce347a35.png)

Please:

- [ ] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [ ] Describe how to reproduce the bug / the goal of the feature request.
- [ ] Use the latest versions of Vega and Vega-Lite.
- [ ] Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "mark": "point",
  "encoding": {"x": {"field": "a"}}
}
```

- [ ] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
The spec needs at least a mark.
