### ISSUE TITLE
Support legends for FillOpacity & StrokeOpacity 

### ISSUE THREAD

**Issue by kobben** [vega/vega-lite#4982]
Vega bug #1513 (https://github.com/vega/vega/issues/1513) was closed, so I expected this to trickle down so that in Vega-Lite I'd get legends for strokeWidth, FillOpacity & StrokeOpacity. However they do not work at this moment. See here https://kartoweb.itc.nl/Vega-Lite/VL-loader.html?VegaLiteFile=overijssel_lines_proportional.json or try code below in online editor.

```json
{
"width": 700,
"height": 580,
"padding": 0,
"config": {
"view": {
"stroke": "none"
}
},
"data": {
"url": "https://kartoweb.itc.nl/Vega-Lite/data/overijssel_roads.geo.json",
"format": {
"type": "json",
"property": "features"
}
},
"projection": {
"type": "stereographic"
},
"layer": [
{
"mark": {
"type": "geoshape",
"stroke": "red",
"strokeCap": "round"
},
"encoding": {
"strokeWidth": {
"field": "properties.vehicles_per_hour",
"type": "quantitative",
"scale": {
"range": [5,25]
},
"legend": {
"title": "Vehicles Per Hour"
}
}
}
}
]
}
```

**Comment by domoritz** [comment]
[Editor Link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDuCWAmAXAFpAXGA7ABmwGnCmQFNYBzZRdMAVgA59DIAHAQ3nlgDszrGJIAYwD2XAGblqoCAIBusYtCmEZUAM6IATsIDWxapC6j9KsAF9CZggPitErZasgBXTQBsDlRMzVoA9H46rJqIwtDEAEYAdLCIglFcbn4AasRkrAC0ADKxxH629n7CssSasABWamrEbgD62uxqUWTEwlGVopDWMpBiwpoAtnaOqlCIAJ7M+hiQHVxdpgLM2lMh4wZixHauxGqQphYQVkzLwuXEgoiwnRjSPRNTBhqlrWSarMzIsIL7R92QblY41K1AA2qY7k4hpodCNRmNJtMoC1hGpkB99N14ZANNo9AZNMR4At4QJcbpiABhD4E4TOLjExbmLE9YhcEScHhw0Y4rQUgDqCBQ3OxEhqxJmp1WV12URKX0Ebl2tVWtWQdM0JNJAgeSMgAEdnKwuFd7FcSlrtTjBKwlSLSZB3jwkeDtfCaCy3WAAEw0JnwgC6-pkxy9ALSbIlYEhbsgprtM1SCqVajAAAVSmAABIa35uw6kguqIvmQhBsxAA)

**Comment by domoritz** [comment]
This seems like a bug. @kanitw are legends for strokeWidth supposed to work in the latest 3.3 release?

**Comment by kanitw** [comment]
IDK --  Why is it related to 3.3 specifically?  Sounds like a bug.

**Comment by domoritz** [comment]
I was just wondering whether this is something you looked at when you updated Vega and I think 3.3 was the first release after the latest Vega update.

**Comment by kanitw** [comment]
I've added support for strokeWidth legend in https://github.com/vega/vega-lite/pull/5030.  

We can't support fill/strokeOpacity yet as Vega doesn't have a support for it yet. I think it would be nice to have, but not a high priority thing to fix yet.  If you strongly wants this, please file an issue in the Vega repo.

**Comment by kanitw** [comment]
I'll close this since it's been stale and we probably won't fix it unless more people asks for it.

**Comment by kobben** [comment]
He Kanit,

Pity. Am I correct in thinking that StrokeOpacity in the legend in VegaLite will only be possible if the same is supported in Vega, and that is where people should ask for it...?

yours
--
Barend Köbben
Senior Lecturer – ITC- University Twente
PO Box 217, 7500 AE Enschede (The Netherlands)
Skype: barendkobben
+31-(0)53 4874 253

On 16/05/2020, 02:00, "Kanit Wongsuphasawat" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll close this since it's been stale and we probably won't fix it unless more people asks for it.

**Comment by domoritz** [comment]
Yes. I suspect that it's not a high priority for Vega either given the number of other things we are working on so the best way forward would be a feature proposal and a pull request.
