### ISSUE TITLE
Quantitative data from CSV is sorted alphabetically rather than numerically

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4988]
Reported in https://github.com/altair-viz/altair/issues/1531

Consider the following spec ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSBXATgGxSgAt54AHAZ2QHpqdYB3AOgHMBLeIrAIywoFMcAYwD2AO3j8JTUQFtqATxHiWReXETVZsCpJzUyIhoID6Q3ADd+MihcjgwAXwA0DyNpwBrQsEjwFZPyEkHhsYkHOUIZh8ITwOFj8Lm5SotBhLD4OmAAePn4BQaiQAI5YsBIcCGxWkJGQAGZs-HjQwQDqYdBgFIH83QAU8hQAlJDJGFAK+f6BwWUV8FVLtfVNLW3FAPJY5LtghsY4YAOe7WOODpeOQA)):
```json
{
  "data": {
    "url": "https://raw.githubusercontent.com/yoonghm/data/master/power_curve.csv"
  },
  "mark": {"type": "line", "point": true},
  "encoding": {
    "x": {"type": "quantitative", "field": "Wind speed (m/s)"},
    "y": {"type": "quantitative", "field": "Output power (kW)"}
  }
}
```
![visualization (94)](https://user-images.githubusercontent.com/781659/58298923-26bb0a00-7d92-11e9-8375-db6f92f3932e.png)

I would expect based on the quantitative encoding that the x-axis would be sorted numerically, but it is sorted alphabetically by the string representation of the number. This of course can be fixed by specifying an appropriate mapping for ``data.format.parse``, but I think this default behavior should be considered a bug.

**Comment by domoritz** [comment]
Oh, this is a fun one. A while ago we decided to not add an explicit parse for quantitative fields since it usually is not necessary. Arrgeates work without for example. However, for sorting we should add parsing as you point out. 

Seeing this case, I think we should go back and explicitly add parsing to numbers for all fields used in quantitative encodings. 

@Saba9 this is relevant to tracking.

**Comment by domoritz** [comment]
I don't think we want to add parsing for all quantitative fields (https://github.com/vega/vega-lite/pull/5157) as it adds a lot of parses that we don't need. It will just make pushing to backends more difficult. https://github.com/vega/vega-lite/pull/4993 is the cleaner solution, IMHO.

**Comment by domoritz** [comment]
I ended up going a different route and added parsing for the dimension field of path marks.
