### ISSUE TITLE
json-stable-stringify -> jsonify has no license

### ISSUE THREAD

**Issue by mpicard** [vega/vega-lite#4997]
Currently vega-lite is using an old library called `json-stable-stringify`, which depends on an unlicensed library `jsonify`. In order to use `vega-lite` many of it's user would require dependencies to include valid open source licenses. `json-stable-stringify` is currently preventing this and replacing it with something with licensed or no dependencies (eg. https://github.com/kikobeats/json-stringify-deterministic) would be an improvement, allowing a wider audience of `vega-lite` users :)

**Comment by domoritz** [comment]
jsonify is in the public domain: https://github.com/substack/jsonify#license

I'm not against switching but I would want someone else to send a pr ;-)

**Comment by mpicard** [comment]
Unfortunately in some countries (outside US) public domain does not mean anything :P So I will have a PR soon

**Comment by domoritz** [comment]
You should be able to compile for ie6 with Babel. We don't typically make releases for older versions.
