### ISSUE TITLE
trellis_barley example doesn't render in Safari

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#5002]
The `trellis_barley` sample stopped rendering in Safari on macOS and iOS, even through it continues to work fine with both Chrome and Firefox. https://vega.github.io/editor/#/examples/vega-lite/trellis_barley

Tested with both `svg` and `canvas` renderer. This seems to be very recent (around the time of the v3.3.0 release).

Removing the `facet` field makes it render (albeit without the faceting).

The Safari web console shows the following error when trying to render the plot:

```error
[Error] ERROR
TypeError: undefined is not an object (evaluating 'e.length')
i — quantile.js:4
a — quartiles.js:10
quartile — TupleStore.js:111
q2 — TupleStore.js:120
anonymous
celltuple — Aggregate.js:314
changes — Aggregate.js:337
evaluate — Transform.js:57
run — Transform.js:33
(anonymous function) — run.js:73
asyncFunctionResume
[native code]
promiseReactionJob
	r (vega.js:1:930745)
	error (vega.js:1:931060)
	(anonymous function) (vega.js:1:989880)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

**Comment by domoritz** [comment]
Could that be related to the bug @jheer found in https://twitter.com/jeffrey_heer/status/1128758642751074304?s=20?

**Comment by marcprux** [comment]
That's exactly it. It looks like this was seen in #4964 as well, and that it has already been fixed.

https://github.com/vega/vega/blob/d89ce009c53bf295fbf94a5e46670f28b2ce1553/packages/vega-statistics/src/quartiles.js#L7-L9

I assume this will be in the next Vega release, and the issue will go away.

**Comment by domoritz** [comment]
Sweet. 

#safariisthenewie
