### ISSUE TITLE
Tooltip incorrect in the connected scatterplot example 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5021]
[Spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlNRxhUZLq8xSoC+6iJAxGA1mYN4AT0JkM0gJJRDVKEJuezwzPCNWZCjIPG5uMTxGQjMAM3QxWGQ3DUhkJXhuTXtqPw0PAA96iFaoPMZkMU1Q1EYxZFg1KEDg0IBHVnQlbN1sqjUG1sgEQpD9SAAvZCNufMLilyXStsgAlrb2zu7Q2iHU0fWoSenZnVtIpY9Vgb8tnb2OAKRRKx3cy24Rk0Oz+HS6PRwZ2Q6CMajSQSeaTQMSMhUgRwgRyOQA). 

Tooltip shows the same value for data for all the points in the line, even when I disable tooltip for the line layer. 

![image](https://user-images.githubusercontent.com/111269/58756653-00901b00-84b2-11e9-8f47-b521d3018a85.png)

(Need further investigation why this is wrong.)  

This issue is quite important as it's showing up in the main gallery.

**Comment by PBI-David** [comment]
@kanitw I think this can be closed now, can't it? The example seems to be working fine, especially if you enable tooltip and change the year field type to ordinal.
