### ISSUE TITLE
Sequence start default value is not supported.

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5026]
According to the Sequence docs, the "start" argument should default to zero: https://vega.github.io/vega-lite/docs/impute.html#sequence-def

In practice, leaving it out results in an error ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuKAHA9gSwHYBdIAacKAU1wGNMATPAc1TFAgkgA8nhJ8BPdMk0gBHAK6wC2fLHzYAboKJQAZtjIAbGkM4BfEqyi8uPfoLQjxk6bIXEVazUKNLI2aOlH4zzSIjK85WHUAZ2Ng-Ex0JgBWPShA9VFvACYdHVI9UkgaGVguUjYEpNC0AG0C1m5ONAAGFyNa9IMAXQyQHSA)):
```json
{
  "mark": "point",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y", "impute": {"keyvals": {"stop": 5}, "value": 2}}
  },
  "data": {
    "values": [
      {"x": 0, "y": 0}
    ]
  }
}
```
```pytb
[Error] TypeError: o.map is not a function
```
If I'm interpreting the docs correctly, the above should lead to the same chart as when ``start`` is explicitly set to zero ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuKAHA9gSwHYBdIAacKAU1wGNMATPAc1TFAgkgA8nhJ8BPdMk0gBHAK6wC2fLHzYAboKJQAZtjIAbGkM4BfEqyi8uPfoLQjxk6bIXEVazUKNLI2aOlH4zzSIjK85WHUAZ2Ng6XhCNAAGF3DMdCYAVj0oQPVRbwAmHR1SPVJIGhlYLlI2dMzQtABtctZuThiXIxi8gwBdfJAdIA)):
```json
{
  "mark": "point",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y", "impute": {"keyvals": {"start": 0, "stop": 5}, "value": 2}}
  },
  "data": {
    "values": [
      {"x": 0, "y": 0}
    ]
  }
}
```
![visualization - 2019-06-02T144624 862](https://user-images.githubusercontent.com/781659/58767783-33cfba00-8545-11e9-9f35-4671b6bcb2de.png)

**Comment by kanitw** [comment]
Thanks, will fix in https://github.com/vega/vega-lite/pull/5031
