### ISSUE TITLE
Minus sign instead of hyphen for negative numbers

### ISSUE THREAD

**Issue by kirkpsmith** [vega/vega-lite#5029]
When displaying negative numbers, use a minus sign `−` (unicode 2212) instead of a hyphen `-`. There could be an option (like this one in [matplotlib](https://matplotlib.org/gallery/api/unicode_minus.html)) to specify either option (but defaulting to the minus sign would be optimal).

**Comment by domoritz** [comment]
We might need to do this in Vega or D3 since Vega-Lite doesn't see the data. 

Does copying a number with the minus sign into python work?

**Comment by kirkpsmith** [comment]
In IDLE, you can see the difference between a true minus sign and a hyphen with this:
`print(u'f\u2212f\nf\u002Df')`
or
`print(u'f\u2212f\nf-f')`
In a JupyterLab code output cell, I can't see the difference between the two.

Reference: [Unicode for "hyphens"](9jkorpela.fi/dashes.html)

**Comment by domoritz** [comment]
− seems to break python

<img width="586" alt="Screen Shot 2019-06-04 at 15 51 09" src="https://user-images.githubusercontent.com/589034/58918788-97dab580-86e0-11e9-9dc2-8f7606ea4b7f.png">

**Comment by domoritz** [comment]
Either way, we need − working in Vega first before we can add support for it in Vega-Lite.

**Comment by kirkpsmith** [comment]
Should I open an issue there? I initially opened one in Altair but they said to go to vega-lite first

**Comment by domoritz** [comment]
That would be great, yes. 

I would love to have a simple heuristic for where to file an issue in the stack but unfortunately it changes case by case.
