### ISSUE TITLE
Consider using husky / lint-staged

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5036]
Instead of relying heavily on Travis to lint / fix style, we could do use `husky` / `lint-staged` locally to reduce round trip time.

And only use Travis for examples updates / tests (or even only runtime test), which is more expensive.

**Comment by domoritz** [comment]
If it doesn't slow commits down, I'm okay. Do we still want Travis to check style for us?

**Comment by kanitw** [comment]
> If it doesn't slow commits down

Probably slow down a bit, but the question is how much is it "ok" to do so.

Slowing down a little may have a benefit too.  (It may encourage our junior collaborators to avoid sub-atomic commits. :p)

**Comment by domoritz** [comment]
A few (<5) seconds is okay for small commits.

**Comment by domoritz** [comment]
Added in #5390
