### ISSUE TITLE
Support syntax sugar to give legend text to calculation series

### ISSUE THREAD

**Issue by tmori3y2** [vega/vega-lite#5044]
Thanks for the support of the sequence generator.

https://vega.github.io/vega-lite/docs/data.html#sequence

I tried to modify the sample code to add legends, but it was difficult.

References:

https://stackoverflow.com/questions/35822062/how-to-define-json-for-multi-line-graph-data/36178568#36178568

https://vega.github.io/vega-lite/examples/bar_grouped.html

Results:

[View the sample in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAApjueWGHRgAZqyXwjysK1iMl1W2GrIlZF10PGRNMFhkAEdWAPhkMAB3ZkQwMRoAzTo1DUhkzRZsMGkABhL1CEgURmp8IoBGAFZy3M0QzBxQCErImLjkIq7unrx0XTwiluGR7kIGgCY6AHYK6chYULmcErp61eHIdFgiyFZIDQgAXw1L1cg8YKVYe25dVCKAbQuwIYP4dDE8FYYhCA1MniUAAo2nhWKg6KwAJQ5aZQI4nCjnYa3b6-bqQf6A4Ggk7wbiwaEhOEI5H7fHo0yJLHdHHDPGVQlAkGhE4AcghkIAHojeSi1gyoCD2MgxAB9THfVnddlQTnEnmmXlkinC0V0yoSyBSmWypmKjQAXTuIIAnkFPrjvpUMLoANYnCSBMUHOLcTReaiDJ34wVB1EHeyMGWaE5nfVrPA2whgqAxdBKIyjIxUb3h+7MdInUPBq7xyo2sPhyqR6MY3Oo+5JlOQNMZ5ghRg5sv4zOF0wVktgJUNsmWXSVquQGtiGOmY1yzHdyqJ5MnJTcVBeAH1tbpfxKWc-fN4PtQACigsIuh0nmUkGuVYf0yfpcdDZd7s6g8bq7nXgG3brA83Cus2kbXuw+jwO6wbDvivr+t4E5rKGX5VtWUYzrGO4HCuzatpmHY5oOcEHBWaHoVOmGHnkOE9k2JwEe22YAYOy4Fs2A6PoBo6vMhDbTjR86mnRy4MaY66bko24kbB5oQBaICXEAA)

I want syntax sugar like this.

```
    {
      "calculate": "sin(datum.u)",
      "as": "v",
      "title": "sin(x)"
    }
```

I can not judge whether the title is good because it is not xy data

Best regards!

**Comment by domoritz** [comment]
You can [use fold instead](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAApjueWGHRgAZqyXwjysK1iMl1W2GrIlZF10PGRNMFhkAEdWAPhkMAB3ZkQwMRoAzTo1DUhkzRZsMGkABhL1CEgURmp8IoBGAFZy3M0QzBxQCErImLjkIq7unrx0XTwiluGR7kIGgCY6AHYK6chYULmcErp61eHIdFgiyFZIDQgAXw1L1cg8YKVYe25dVCKAbQuwIYP4dDE8FYYhCA1MniUAAo2nhWKg6KwAJQ5aZQI4nCGQgAeyO+t2+v26kH+gOBoJO8G4sGhIThCOR+yJ6NMlOpOPOw3xw2AkBeYk0n3WXmxDKgrJFkAAutcIJK7hhdABrE4SQIoqBxbiaLzUQbfSBYvWo3mMZD8k5nRmVPAAT0IYKgMXQSiMoyMVHVB1d6ROhrxjMgNqNa3spvNpgoANinqJtvtJydLuYIUYHqtUG9DsDHO6XKJlMsumDB1DZoFpkVyCD6fudqzSm4qC8AJjlXS-iU5Z+92YPtMAFEsYRdDpPMpIDLczcQJcgA).

![image](https://user-images.githubusercontent.com/589034/59117780-773e7580-8903-11e9-8128-895e0a8bad28.png)


```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Plots a function using a generated sequence with legend.",
  "width": 300,
  "height": 150,
  "data": {
    "sequence": {
      "start": 0,
      "stop": 12.7,
      "step": 0.1,
      "as": "u"
    }
  },
  "transform": [
    {
      "calculate": "sin(datum.u)",
      "as": "sin(x)"
    },
    {
      "calculate": "cos(datum.u)",
      "as": "cos(x)"
    },
    {"fold": ["sin(x)", "cos(x)"]}
  ],
  "mark": "line",
  "encoding": {
    "x": {
      "field": "u",
      "type": "quantitative",
      "title": "x"
    },
    "y": {
      "field": "value",
      "type": "quantitative",
      "title": "y"
    },
    "color": {
      "field": "key",
      "type": "nominal",
      "legend": {"title": "Expression"}
    }
  }
}
```

**Comment by tmori3y2** [comment]
I did not notice using fold to generate the legend.

Everyone may be happy once the samples are updated.

Thanks a lot.

**Comment by domoritz** [comment]
I think the example above is a good one. @tmori3y2 Can you send a PR to add it to our docs and the example gallery?
