### ISSUE TITLE
Allow text in numeric format pattern.

### ISSUE THREAD

**Issue by tmori3y2** [vega/vega-lite#5045]
I want radian ticks like matplotlib.

https://matplotlib.org/gallery/units/radian_demo.html

My sample:

[View the sample in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAApjueWGHRgAZqyXwjysK1iMl1W2GrIlZF10PGRNMFhkAEdWAPhkMAAKVG5NRntGMIBuMG59JiV0MSx8IhJyKloGZjZOHiFacUlSTW54WBaQ+nxUMQBiSJi45ABKOjUNSAB3Rk0WbDBpAAYl9QhIFEZqfAWARgBWVcnNLoXQCHXB2OdkM40LqFg8dF08BaOHy7xuQgWAFjouzWn0gT2QvxwS0BwIekHQsAWkFYkHuYAAvho0cDIHhgkpYPY8qgFgBtVHnEHwIrwVhiEK3UwnPCsVB0VhgABUYDMAEkJp8oPDEboUQ8seTUesqWIaXTQojPEpEkyWXRdCN+SChaYKKKLuKHhTYdLZfTEfBuLBlSFVerNbDtVApnqIBiIABdbF0gCeQVJEoFkAwugA1oiJIF7RdIHFUl5qHcBesAB6JpPrDLIMSaRHImFJnHewgMqAxdBKIzPIxUKOBytiEuQZNgEnBNLl0iAAeB3S7PgaC960+nIJns4jdfm60XG2WK8wQowa5OQfXG4rEsnOxrJfqd279fmjdHg2GcEfYXhp+GvLdl19dNwQ42MrpkOx9PAw3vlzHnHHvEOIKpmeO6wqOOamHmoHRpexaIrOlYLjW0H9oGg4gemGaZGOpjOneMFXqYCHztWt7Qesq7mpaG5br2Yp7qi+7uiAaJAA)

I want to use a format pattern with text like printf format for field u but I get an error for numbers.

It may be convenient to use text even with numeric format patterns.

Support for radian scale for field r is also acceptable.

‘‘‘
      "scale": {
        "type": "radian"
      }
‘‘‘

**Comment by tmori3y2** [comment]
> I want to use a format pattern with text like printf format for field u but I get an error for numbers.

This means that the unit of `x` is ` radian` instead of `radian / π`, and the scale is ' 0.0π, 0.5π, 1.0π, ...' instead of '0.0, 0.5, 1.0, ...'

Text seems to be only allowed in time format pattern.

https://vega.github.io/vega-lite/docs/format.html

https://github.com/d3/d3-format#locale_format

**Comment by kanitw** [comment]
Thanks for filing the issue.  This is definitely a very interesting use case. 

For now I think you can use the `calculate` transform to divide the angle by 180 and set the title to "π radians".  

Note that this is still a linear scale.  It's just a matter of formatting the axis with π radians unit, not degrees.

**Comment by kanitw** [comment]
Since  ' 0.0π, 0.5π, 1.0π, ...'  is a desireable output, I'll rename this issue to focus on "Allow text in numeric format pattern".  

Vega gets around with this with expression in signal object.  The question is how should we allow expression for format and other similar properties in Vega-Lite.  

(Should we call it signal or expression?)

**Comment by domoritz** [comment]
`format: {expr: "datum + 'π'"}` seems reasonable to me. I don't think we want to use the `signal` terminology here.

**Comment by kanitw** [comment]
Well, that's what Vega used until `signal`s arrive and `expr` is removed. 

To proceed with this, we need to finish discussing #3338 first.

**Comment by domoritz** [comment]
How does this depend on #3338? An expression could still reference a signal.

**Comment by kanitw** [comment]
It depends on a decision in #3338 so we don't have to design a syntax that gets removed later.

**Comment by tmori3y2** [comment]
This problem seems to be solved with labelExpr. #5310

"labelExpr": "datum.label + 'π'"

**Comment by domoritz** [comment]
Yes, thanks for the comment. I'll close this.
