### ISSUE TITLE
The sequence generator requires to add the step to the end

### ISSUE THREAD

**Issue by tmori3y2** [vega/vega-lite#5046]
In my sample of #5045.

The sequence generator requires to add the step to the end.

```
  "data": {
    "sequence": {
      "start": 0,
      "stop": 4.1, <===============
      "step": 0.1,
      "as": "u"
    }
  },
```

**Comment by tmori3y2** [comment]
It is good to add clipping option.

```
  "data": {
    "sequence": {
      "start": 0,
      "stop": 4,
      "step": 0.1,
      "clipping": ”lt”
      "as": "u"
    }
  },
```

"lt": 0 to 3.9 (step: 0.1) [default]
"eq": 0 to 3.9 (step: 0.1), and 4.00
"gt": 0 to 4.1 (step: 0.1)


```
  "data": {
    "sequence": {
      "start": 0,
      "stop": 4,
      "step": 0.33,
      "clipping": ”lt”
      "as": "u"
    }
  },
```

"lt": 0 to 3.96 (step: 0.33) [default]
"eq": 0 to 3.96 (step: 0.33), and 4.00
"gt": 0 to 4.29 (step: 0.33)

**Comment by domoritz** [comment]
This is not a bug but a feature request, right?

We need support for this in Vega first so please file an issue there. As soon as Vega supports this, we can support it in Vega-Lite as well.

**Comment by tmori3y2** [comment]
It should have been mentioned clearly.
This is a bug.

Because {start: 0.0, end: 4.0, setp: 0.1} does not generate 4.0, the graph is missing one point.

To add one point,

If step = 0.01, end = 4.01
If step = 0.05, end = 4.05
If step = 0.1, end = 4.1
If step = 0.2, end = 4.2
If step = 0.25, end = 4.25
If step = 0.5, end = 4.5
.
.
.
Is it acceptable for many people?

If the results change, I fix it as follows.

{start: 0.0, end: 4.0, setp: 0.1}: 0.0, 0.1, 0.2, ..., 3.9, 4.0
{start: 0.0, end: 4.0, setp: 0.33}: 0.0, 0.33, 0.66, ..., 3.96, 4.29

Is this necessary to fix in Vega?

Best regards.

**Comment by tmori3y2** [comment]
> It is good to add clipping option.
> 
> ```
>   "data": {
>     "sequence": {
>       "start": 0,
>       "stop": 4,
>       "step": 0.1,
>       "clipping": ”lt”
>       "as": "u"
>     }
>   },
> ```
> 
> "lt": 0 to 3.9 (step: 0.1) [default]
> "eq": 0 to 3.9 (step: 0.1), and 4.00
> "gt": 0 to 4.1 (step: 0.1)
> 
> ```
>   "data": {
>     "sequence": {
>       "start": 0,
>       "stop": 4,
>       "step": 0.33,
>       "clipping": ”lt”
>       "as": "u"
>     }
>   },
> ```
> 
> "lt": 0 to 3.96 (step: 0.33) [default]
> "eq": 0 to 3.96 (step: 0.33), and 4.00
> "gt": 0 to 4.29 (step: 0.33)

This is a technique that does not change the result and should be ignored.

**Comment by tmori3y2** [comment]
It has been two weeks for me to know vega-lite.
It is good because it is easy to learn and beautiful.

I used this feature to simulate and visualize data with overlapping Gaussian peaks.

The sequence generator has an impact because it needs at least a few thousand points of data.

If natural scientists know vega-lite, many of them will use this feature to simulate and visualize data.

However, many scientists will soon be disappointed with this behavior when using this feature.
Many of them are unconvinced that one point is missing. And do the same post as me.

There is only one point of data missing, but I think it has more impact than you think.

Of course, there is also a way to generate a little more, and cut the extra part, but if that processing is necessary every time, it is not beautiful as a specification.

Now, even one point increase has little impact. If it changes, it is now!!

**Comment by domoritz** [comment]
Ahh, I see. The end value is exclusive by design. We borrow this behavior from Vega: https://vega.github.io/vega/docs/transforms/sequence/. 

Python has the same behavior so I would argue that the majority of scientists expect the end value to be exclusive. 

```
>>> list(range(1,4))
[1, 2, 3]
```
