### ISSUE TITLE
Default Stack Property Functionality

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega-lite#5073]
The `stack` property does not stack bars when an additional field by which to stack has not been specified (even when the stack is explicitly specified).  

**Example:** **[Link to Example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8ejUNSEd4AGtqXW5WJU1sKA9ESUiISFDwtNAIHIp0MVYdNIBtDSKwYEhMUzM1aLSAJgAOAF9VOoa08xb2NIBGNp6+xqgAISG0gFZ5iZqi+qnIAGE5nAAWaQm1gYARbbAAThGD-tMAUVOOy96ViEPTADFT+f3e16gP1VaOAA7Fd1gBxU5tR7PSYDCEA4Y4EZnUEDAAS9xBP2uUAAkp9xisALoaHpRDC6WIDRy6bJQZBKeDcTSMJTUAorSAADwKkAAZoxkGJUqZML1IHgAJ6EZADbi6FlKUqQMm1SCS3kCoUiqDDcVSmUDACOrHQSiM4SMVDUUFg4TiaTwunKqqK-MYYjEvJKZVlpjtyCF7F9KvUartiVifr6PvKAwyWS6pJAXSAA)**
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "background": "white",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "A","b": 12}, {"a": "B","b": 55}, 
      {"a": "C","b": 43}, {"a": "D","b": 91}, {"a": "E","b": 81}, 
      {"a": "F","b": 53}, {"a": "F","b": 7}, {"a": "G","b": 21},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "stack": true},
    "fill": {"value": "steelblue"},
    "stroke": {"value": "white"}
  }
}
```
In this example, there should be two bar segments for "A", "F", and "G", which overlap instead of stacking in the output visualization.

![image](https://user-images.githubusercontent.com/3392218/59375271-a4739500-8d02-11e9-9344-e493f083911c.png)

Notice that changing `"fill": {"value": "steelblue"}` to `"fill": {"field": "steelblue"}` produces the desired result (though "steelblue" is not a field in the data, so this behavior seems unintuitive).

![image](https://user-images.githubusercontent.com/3392218/59375396-e00e5f00-8d02-11e9-9302-d6d5a67763e6.png)

**Comment by kanitw** [comment]
One solution is to check for condition in relevant channel.

However, I start to think that may be bars and areas should always stack by default (basically equivalent to position=stack in ggplot2).

**Comment by domoritz** [comment]
I think always stacking makes sense since it would also simplify the dataflow merging for layered plots. See https://github.com/vega/vega-lite/issues/5013 for example.

**Comment by kanitw** [comment]
> I think always stacking makes sense since it would also simplify the dataflow merging for layered plots. See #5013 for example.

FWIW, the main issue in #5013 is not related to stack.  The off-topic comment in https://github.com/vega/vega-lite/issues/5013#issuecomment-500117994 is related to stack. However, stacking by default won't help with this issue.  Having a stack component that allows stack merging (#5078) would help.

**Comment by kanitw** [comment]
Just to simplify this conversation, I think the top plot in this issue shouldn't require explicit `stack: true`.

**Comment by kanitw** [comment]
I tried this.  However, there are just simply too many cases that we shouldn't stack by default 

- when the stacked scale is non-linear or is linear but excludes zero
- when the aggregation of the stacked field is not summative (e.g., mean)

The latter is not always detectable (e.g., when we extract transform).

Thus, I think this is just too complicated to derive a consistent rule.

**Comment by jhoffswell** [comment]
The cases you point out make sense as issues with a default (automatic) stacking functionality, but I'm still somewhat curious about the actual stack property itself and its relationship to this example. You had previously mentioned that the top plot shouldn't require a setting for `stack: true`, but would it make sense to revisit that as an option if they behavior is not actually part of the default/automatic functionality?

**Comment by kanitw** [comment]
> You had previously mentioned that the top plot shouldn't require a setting for stack: true, but would it make sense to revisit that as an option if they behavior is not actually part of the default/automatic functionality?

Yes, the spec on the top is now working correctly in master. (We haven't released a new version yet).  

It's just that always applying stack by default for bars seems to open a different can of worm that makes me feel like it's not worth doing anymore.
