### ISSUE TITLE
Github Actions does not run tests or builds examples/schema on forks

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5076]
This makes it really difficult for external contributors to change the schema or examples. We always have to copy the branch.

**Comment by kanitw** [comment]
Sorry, don't have time to fix this soon.

**Comment by kanitw** [comment]
Btw, this is a P2 to me.

**Comment by kanitw** [comment]
I also wonder why this is broken, I take a quick look and the only thing we check is whether it's a master branch.

**Comment by domoritz** [comment]
Ahh, so for example in https://travis-ci.org/vega/vega-lite/jobs/538017194, it was master. We should also check that we are on the vega master branch, I think.

**Comment by domoritz** [comment]
Hmm, I can't find a good way to check whether we are building vega or something else. Maybe someone else finds something.

**Comment by domoritz** [comment]
Should work after https://github.com/vega/vega-lite/pull/7078
