### ISSUE TITLE
Make step a property of view's top-level width/height instead of scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5083]
Setting width/height for discrete x/y-axes is currently one of the most confusing things in Vega-Lite. Basically, there are two modes: (a) fixed size and (b) flexible sizing based on (range) step. However, they totally have different specifications.   

To set a fix width/height, users can set the view's top-level `width`/`height` property. However, to make the width flexible based on cardinality, one have to dig deep into `encoding.x/y.scale.rangeStep`, which is quite deep in the spec and totally different from the `width`/`height` property.  

I have tried to explain this property to users multiple times and found that users have trouble understanding that they have to use `width` in one case, and `encoding.x.scale.rangeStep` in another. Due to this complexity, our ["size"](https://vega.github.io/vega-lite/docs/size.html) and [scale range](https://vega.github.io/vega-lite/docs/scale.html#range) docs are also overly complicated.  

Given that users would think about width / height together and that x/y's scale ranges should simply depend on width/height, I think that we better make `width` / `height` support either a `number` or a step object (`{step: number}`).  

Basically, instead of 

```
{
  "height": 100,
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "a", "type": "ordinal",
      "scale": {"rangeStep": 11}
    },
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
we can do:

```
{
  // we can set width step right here, next to the height, so the specifications of width and height are not separated
  "width": {"step": 11}, 
  "height": 100,
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

This simplification has multiple benefits:

- This would make it way easier to explain two modes of sizing for discrete axes within the `width`/`height` and to swap between the two. For example, in our scale docs, we can replace:

> The range is always [0, width]. Any directly specified range will be ignored. Range can be customized via the view’s width property or via range steps and paddings properties for band and point scales.

with 

> The range is always [0, width]. Any directly specified range will be ignored. Range can be customized via the view’s width property.

- Internal code will be much simpler as their will be only one-directional dependency namely that x/y scales can just read width/height and know whether to use a step or a full-width to calculate range. (Currently, the code involves a very complicated rule based on how width/height or scale.rangeStep are specified and need some conflict resolution logic when both are specified.  With the new proposal, there can be no conflicts there is only once place for width, which can be either fixed width or step-based width -- same for height.) 

- The name `rangeStep` is also a funny name (that naively derives from `range.step`), which has bug me for a while. 

- This would also make it more sensible for 1D plot.  For example, the width of a 1D vertical bar currently depends on `config.scale.rangeStep` even though there is no scale. It would make more sense if it depends on `config.view.discreteWidth` which can be either a fixed number or a step object. (dimension of 1D plot has no scale, but clearly has one step.) 

If we follow this proposal, we can deprecate `rangeStep` in 4.0 (by removing it from the schema and documentation, but still maintain backward compatibility)

cc: @jheer @domoritz @arvind -- any thoughts?

**Comment by g3o2** [comment]
Or you could keep the original `rangeStep` where it is and also allow it to be used in width/height as `{rangeStep: 11}`. Additionally, you'd need conflict resolution logic in case both were specified at the same time.

After all, `rangeStep` may not be clear to everyone, yet it is still more explicit than simple `step` in the context of width/height.
This would not be the first time in vega-lite that several ways lead to the desired result.

**Comment by kanitw** [comment]
> Not sure why is it more explicit than `step`. 

Basically, I observe that the task that users wanna do is simply changing plot size, no matter u use width/height or rangeStep. Both of them affect the x-y range. However, it's weird that the same task requires modification in two different places.  

In any case, if we proceed with this, we may (and probably will) keep `rangeStep` for backward compatibility. But we will remove it from the documentation as the goal is to make the syntax simpler to use, not more complex.

**Comment by kanitw** [comment]
Note: I just added a few more points to the top-most block:

- This would make it way easier to explain two modes of sizing for discrete axes within the `width`/`height` and to swap between the two. For example, in our scale docs, we can replace:

> The range is always [0, width]. Any directly specified range will be ignored. Range can be customized via the view’s width property or via range steps and paddings properties for band and point scales.

with 

> The range is always [0, width]. Any directly specified range will be ignored. Range can be customized via the view’s width property.

- Internal code will be much simpler as their will be only one-directional dependency namely that x/y scales can just read width/height and know whether to use a step or a full-width to calculate range. (Currently, the code involves a very complicated rule based on how width/height or scale.rangeStep are specified and need some conflict resolution logic when both are specified.)

**Comment by domoritz** [comment]
One sad thing about having either `step` or just a width is that users cannot specify both at the same time so that you can switch from ordinal to quantitative without also having to change the specification of the chart size. Maybe we can support `width: {step: 11, value: 300}`.

**Comment by kanitw** [comment]
> One sad thing about having either step or just a width is that users cannot specify both at the same time so that you can switch from ordinal to quantitative without also having to change the specification of the chart size Maybe we can support width: {step: 11, value: 300}.

Note that users can specify separate defaults in the config via `config.view.continuousWidth: number` and `config.view.discreteWidth: number | {step: number}`.  (Same for height)  Sorry I didn't mention that earlier. 

I don't think we should do `width: {step: 11, value: 300}` in the view's top-level `width` / `height`. It's just harder to read and understand what it means. 

If user specify `width: {step: 11}` for quantitative x-axis, then we'll just ignore the `step` for now.  This behavior is consistent with the current state of the Vega-Lite, which ignores `rangeStep` specified for quantitative x-encoding.

If we want to expand the feature further, we can consider counting number of ticks - 1 as the number of steps for quantitative.  But I don't think we need to do that for now as it's a bit complicated to do so.

**Comment by domoritz** [comment]
I'm supportive of this change. We should plan to remove rangeStep in Vega-Lite 4.x (x>=1) or 5.

**Comment by kanitw** [comment]
If we were to remove entirely without backward compatibility then it has to be either 4.0.0 or 5.0.0?  (That's a breaking change.)

**Comment by domoritz** [comment]
Let's just remove it for 4.0 then. It's easier that way.

**Comment by g3o2** [comment]
hmm, is `step` in such a context a self explanatory word then?

**Comment by kanitw** [comment]
It's for "setting width/height per discrete step".  

Step is also the term used for this in Vega and D3.  

 We simply called it rangeStep previously because it may not be clear if it is a property that affects range, but it's also awkward in that sense.) 

(In any case, the keyword "step" would match the figure we use to explain [the band and point scales](https://vega.github.io/vega-lite/docs/scale.html#band).)

**Comment by domoritz** [comment]
We decided to remove rangeStep in 4.0 but be backwards compatible by adding some code to normalize

**Comment by kanitw** [comment]
- [ ] Implementation
- [ ] Backward compatibility
- [ ] Revamp size docs

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/5138
