### ISSUE TITLE
Temporal type does not work with "HH:MM"

### ISSUE THREAD

**Issue by himahimahima** [vega/vega-lite#5098]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

The following spec does not work when I define the data "02:30" as temporal when the docs suggest that it does.
"Temporal data supports date-times and times such as "2015-03-07 12:32:17", "17:01", "2015-03-16". "2015", 1552199579097 (timestamp)."
```json
{
  "data": {
    "name": "dataset"
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "type": "temporal",
      "field": "collection_start_time"
    },
    "y": {
      "type": "quantitative",
      "field": "scats_offramp_volume"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",
  "datasets": {
    "dataset": [
      {
        "collection_start_time": "02:30",
        "scats_offramp_volume": 84
      },
      {
        "collection_start_time": "00:30",
        "scats_offramp_volume": 94
      }      
    ]
  }
}
```

- [ ] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

![image](https://user-images.githubusercontent.com/4336338/59815604-6ad30780-935c-11e9-8a7b-ecba415f2d02.png)

**Comment by jwoLondon** [comment]
You just need to specify the [format of the temporal data explicitly](https://vega.github.io/vega-lite/docs/data.html#format):

```javascript
"data": {
    "name": "dataset"
    ,"format": {"parse": {"collection_start_time": "date:'%H:%M'"}}
  }
```

In my experience anything other than a standard `yyyy-mm-dd HH:MM:SS` is worth specifying explicitly, as default parsing can vary between browsers.

**Comment by domoritz** [comment]
@jwoLondon is right. Bowsers only parse standard formats automatically.

**Comment by the21st** [comment]
For what it's worth, I've also stumbled upon this issue and thought it's a bug in VegaLite – mainly because [the docs](https://vega.github.io/vega-lite/docs/type.html#temporal) mention this format explicitly among the listed examples: "17:01"
