### ISSUE TITLE
Coerce field names to strings?

### ISSUE THREAD

**Issue by mbostock** [vega/vega-lite#5115]
When working with columnar data, it’s handy to use d3.zip to convert columns into rows for the benefit of Vega-Lite. But, it appears that the Vega-Lite API doesn’t support field names being specified as numbers, as when the input data is an array-of-arrays rather than an array-of-objects; it requires the field names to be specified as strings.

So this works:

```js
vl.markBar()
  .data({values: d3.zip(names, values)})
  .encode(
    vl.y().fieldN("0"),
    vl.x().fieldQ("1")
  )
  .render()
```

But this doesn’t work:

```js
vl.markBar()
  .data({values: d3.zip(names, values)})
  .encode(
    vl.y().fieldN(0),
    vl.x().fieldQ(1)
  )
  .render()
```

The latter throws an error:

```
TypeError: Cannot use 'in' operator to search for 'repeat' in 1
```

Related, it’d be great if Vega-Lite had first-class support for columnar input so that we don’t need to materialize an object (even a proxy object) for each row. But I figured it was an easier ask to just do the implicit coercion to string.

**Comment by domoritz** [comment]
Moved to Vega-Lite

**Comment by kanitw** [comment]
This is easy, so I just created https://github.com/vega/vega-lite/pull/5123.  

Note that I coerce it in the code, but I haven't include "number" as a valid type for "field" in our TS types / JSON schema.  I guess we probably shouldn't do that given object key is natively string anyway?  If you disagree, let me know. We can easily fix that as well.

**Comment by jheer** [comment]
I think we would need to update the types / schema. It is quite likely we will eventually want to include schema validation options as part of the Vega-Lite API.

**Comment by mbostock** [comment]
My two cents is that this coercion probably makes sense as a feature of the Vega-Lite API (the JavaScript API), rather than relaxing the underlying schema to allow arbitrary types.

If you’re using TypeScript or schema validation, you might want warnings or errors if you specify field names that are not strings. But if you’re using JavaScript, you expect the function to coerce whatever you pass it to a string for you, in the same way that you can call *element*.setAttribute(*name*, *value*) and expect it to coerce the *name* and *value* to strings regardless of the input type. For better or worse, type coercion is idiomatic JavaScript.
