### ISSUE TITLE
Should stats, layout, style become part of encoding?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#514]
Right now we pass `stats` around everywhere and have to call `stats[encoding.field(et).name]` to get stats for a particular field.  

- [ ] `encoding.fieldStats(et)`  might make things cleaner.  
- [ ] also make fieldStats throws the right error if field name doesn’t match the data file name (originally #165)

**Comment by kanitw** [comment]
@domoritz ?

**Comment by domoritz** [comment]
Sorry, was having a party. Makes sense. +1

**Comment by kanitw** [comment]
@domoritz 

After halfway through this refactoring, I no longer like this idea.
We should keep the encoding class simple.  

For example, to get a clean spec, we should be able to call
```js
vl.Encoding.fromSpec(scope.chart.vlSpec).toSpec(true)
```
rather than
```
vl.Encoding.fromSpec(scope.chart.vlSpec, Dataset.stats).toSpec(true)
```
(Why would we need stats for just simplifying spec!)

### Alternative

If we still want to retain the same goal — eliminate passing stats, layout, style around. 
Maybe we can make  `compiler` become a class and move help like `.cardinality` as it’s class method.

To avoid huge refactoring, we can use `function.call` to provide the compile instance as `this` value for different parts of the definition.  

`compiler.compileEncoding` would become  `Compiler.prototype.compile`
and inside `Compiler.prototype.compile` we can call: 

- `axis.def(X, encoding, layout)`  =>  `axis.def.call(this, X)`  
- `legend.defs(encoding, style)` => `legend.defs.call(this)`
- …

(Basically `encoding`, `layout`, `style` becomes a property of the compiler.)

Let me know if you have any objection on this before I spend a few hours refactoring :)

**Comment by kanitw** [comment]
Or if you don’t like messing with `this` and `call/apply`,   we can create a `CompilerState` object and pass that around —  but I don’t like this that much unless we come up with a better name than `CompilerState`.

**Comment by kanitw** [comment]
Maybe `model`?   (`model.encoding`, `model.stats`, `model.layout` isn’t too bad…) and we can shorten it with `m`.   Then we refer to these stuff as (`m.encoding`, `m.stats`, `m.layout` isn’t too bad…)

**Comment by kanitw** [comment]
Another alternative that might take less effort and isn’t too bad is add `stats`, `layout`, `style` as part of    `encoding.model`

```
encoding.model = {
  stats: …,
  layout: …,
  style: …
}
```

and we can still parse encoding around like before (but do not include stats as part of Encoding’s constructor?)

**Comment by domoritz** [comment]
I'm okay with either. Wasn't stats a hack that we wanted to rip out again with vega 2? Or is that not realistic more?

**Comment by kanitw** [comment]
I’m renaming the title to reflect this change better and let’s reconsider this once we are done with #648.

**Comment by kanitw** [comment]
Style is gone and we are removing layout object and stats as part of #648, #618.  So I’m closing this!
