### ISSUE TITLE
prettier breaks `{:.no_toc}` in the documentation

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5140]
(Prettier always add a line between the header and the `{:.no_toc}` tag.

**Comment by domoritz** [comment]
This has been a problem.from the beginning. We have to add a comment to ignore prettier for one line. See https://github.com/vega/vega-lite/blob/master/site/docs/encoding/axis.md

**Comment by kanitw** [comment]
Why didn't you add ignore comment to all doc files from the beginning then lol

**Comment by domoritz** [comment]
`<!-- prettier-ignore -->` only ignores the next line and I added it before all `{:.no_toc}`.

**Comment by domoritz** [comment]
I think we can close this.

**Comment by kanitw** [comment]
>  I added it before all {:.no_toc}.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/111269/60451081-180d1180-9be0-11e9-84f2-ac1bf9800fe2.png">


No, you added to before `- TOC`, but we still need to add it to `{:.no_toc}`.

**Comment by domoritz** [comment]
Oh, ups.
