### ISSUE TITLE
Doc issues in the 3.3.0 schema

### ISSUE THREAD

**Issue by DougBurke** [vega/vega-lite#5141]
I noticed several documentation issues in the 3.3.0 version of the vega-lite schema. Most looked like cut-n-paste issues. Unfortunately I didn't note them all down, and I wasn't sure whether there should be separate issues filed. If I see any more I can add them here (or is it okay to submit a PR for simple changes like the `labelLimit` case below?)

- `zindex` is confusing - I assume that `"non-positive integer"` should be something like "integer, 0 or greater" or "an integer, 0 or 1".

```
"zindex": {
          "description": "A non-positive integer indicating z-index of the axis.\nIf zindex is 0, axes should be drawn behind all chart elements.\nTo put them in front, use `\"zindex = 1\"`.\n\n__Default value:__ `1` (in front of the marks) for actual axis and `0` (behind the marks) for grids.",
          "minimum": 0,
          "type": "number"
        }
```

- In `Legend` and `LegendConfig` I assume `axis tick labels/titles` should read `legend labels/titles`

```
 "labelLimit": {
          "description": "Maximum allowed pixel width of axis tick labels.\n\n__Default value:__ `160`.",
          "type": "number"
        },

"titleLimit": {
          "description": "Maximum allowed pixel width of axis titles.\n\n__Default value:__ `180`.",
          "minimum": 0,
          "type": "number"
        },
```

**Comment by domoritz** [comment]
Thank you for the issue. We definitely appreciate pull requests. Note that the schema is generated from TypeScript so in order to change the schema, you need to change the comments in the code and then run `yarn schema`.

**Comment by DougBurke** [comment]
Unfortunately (for me) the need to install typescript/yarn is enough of a barrier to mean I'll probably just report the issues, and not fix them.

**Comment by domoritz** [comment]
Okay. Thanks for the report. 

Just to note, you don't need to install typescript. It comes automatically when you run npm install/yarn.

**Comment by kanitw** [comment]
Since it's just fixing comment, not the code logic, you can just fix them and submit a PR as well.

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega/pull/1862 and https://github.com/vega/vega-lite/pull/5146
