### ISSUE TITLE
Make channel type more specific

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5173]
In https://github.com/vega/vega-lite/blob/75cbdd52c19ebab8e2b55a101ca1aa782d0ed686/src/encoding.ts#L377, we assume that the channel is of type `Channel | string`. However, it should be of type `keyof Encoding<string>` and `isChannel` should also be a guard for `keyof Encoding<string>`. This way, we would know the type of `channelDef` in https://github.com/vega/vega-lite/blob/75cbdd52c19ebab8e2b55a101ca1aa782d0ed686/src/encoding.ts#L406. 

This is currently blocking https://github.com/vega/vega-lite/pull/5005.

**Comment by kanitw** [comment]
Why don't you submit a PR? :)

**Comment by domoritz** [comment]
Because I tried for half an hour and got lost. I need some help with knowing what the desired types are. Maybe we can do a peer programming session and I can show you?

**Comment by domoritz** [comment]
You can see the issue by switching to TS 3.5 (in bottom right of VSCode) and you will get errors in this file).

**Comment by kanitw** [comment]
@domoritz  Do we still need this?

**Comment by domoritz** [comment]
Maybe. I need to look at this a bit more.

**Comment by domoritz** [comment]
Okay, what I want to do here is to clean up Channel and ChannelDefs. I would expect `ChannelDef` to be the same as `Encoding<any>[Channel]`, right?
