### ISSUE TITLE
[safari only] Median Aggregation Fails if only 1 data point per bucket (Mean works)

### ISSUE THREAD

**Issue by jlewis91** [vega/vega-lite#5177]
The below plot fails to render if there is an bucket with only one data point; if you change `"aggregate": "median"` to `"aggregate": "mean"`, the plot renders without issue (similar, likely related issues with `q1, q3, 

# Working Examples

[Median, no plot](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMAvgGnCgBMBDAFxM20nhIFsBTKyUigWmgA5OBOE6ACycA7ACNoANgDMwngImIGUgAyjuAgKwMATNuUMekfIUh0SAJwDWVYJDIBPAA5MskADbJ4TYxEgN4cESe6FigEL4AHjaE4VAOzsxkDHSOsOYkbpAEsb4oDG5EzIwkAM4ArubJ-mQA+mTIjCUUKVkx4XYNDACq8MhkzPYMFnQIZAAWrExtPu32NnZOLlAAjmUk8PUU9QBuTHhQJKiolajkS6YMQetZUHkFzNsZZd6EM5AAJCXQY8mUrmNkMiOEoYAD0oN2pwAdKg+mMyqIochYKCvj8zBCGKc2B4khCpFCCcooQArEoIVq+VilBhkErRWIscgkDjcPiCETiaSyeSKFRqTiaHR6AxUADabQgYRyvmK5UqjA2dU6TXojmYegAjDw2MphLrOAAVZRSDDKZRm5QAanNlspMqgjzczyoyklYBwbQAuq8QDggA/view)

[Mean, plot](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMAvgGnCgBMBDAFxM20nhIFsBTKyUigWmgA5OBOE6ACycA7ACNoANgDMwngImIGUgAyjuAgKwMATNuUMekfIUh0SAJwDWVYJDIBPAA5MskADbJ4TYxEgN4cESe6FigEL4AHjaE4VAOzsxkDHSOsOYkbpAEsb4oDG5EzIwkAM4ArubJ-mQA+mTIjCUUKVkx4XYNDACq8MhkzPYMFnQIZAAWrExtPu32NnZOLlAAjmUk8PUU9QBuTHhQJKiolajkS6ZD8FlQeQXM2xll3oQzkAAkJdBjyZSuY2RkRwlDAAehBu1OADpUH0xmVRJDkLAQZ9vmZwQxTmwPElwVJIfjlJCAFYlBCtXysUoMMglaKxFjkEgcbh8QQicTSWTyRQqNScTQ6PQGKgAbTaEDCOV8xXKlUYGzqnSa9EczD0AEYeGxlMIdZwACrKKQYZTKU3KADUZotFOlUAebieVGUErAODaAF0XiAcEA)

# Vega-lite spec

```json
{
  "config": {},
  "data": {"name": "data-c889ac487bc637946fe30b8845e220e9"},
  "mark": {"type": "line"},
  "encoding": {
    "x": {
      "type": "temporal",
      "field": "measurement_timestamp",
      "timeUnit": "yearmonthdate"
    },
    "y": {"type": "quantitative", "aggregate": "median", "field": "value"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.3.0.json",
  "datasets": {
    "data-c889ac487bc637946fe30b8845e220e9": [
      {
        "measurement_timestamp": "2019-07-08T03:00:00+00:00",
        "value": 0
      }
    ]
  }
}
```

**Comment by jlewis91** [comment]
<img width="1080" alt="Screen Shot 2019-07-08 at 17 18 10" src="https://user-images.githubusercontent.com/4462211/60821715-62742c80-a1a4-11e9-9c8e-3390e87e509d.png">

**Comment by jlewis91** [comment]
Seems to work fine on chrome. 🤷‍♂

**Comment by domoritz** [comment]
This has been fixed in https://github.com/vega/vega/pull/1803. 

Read more about how @jheer debugged this issue at https://github.com/vega/vega-lite/issues/4964#issuecomment-492805310.
