### ISSUE TITLE
Confusing 3.3.0 documentation for ViewBackground/style - string or array of strings?

### ISSUE THREAD

**Issue by DougBurke** [vega/vega-lite#5181]
In version 3.3.0 of the JSON schema, the "style" field of "ViewBackground" is given as

```
"style": {
          "description": "A string or array of strings indicating the name of custom styles to apply to the view background. A style is a named collection of mark property defaults defined within the [style configuration](https://vega.github.io/vega-lite/docs/mark.html#style-config). If style is an array, later styles will override earlier styles.\n\n__Default value:__ `\"cell\"`\n__Note:__ Any specified view background properties will augment the default style.",
          "type": "string"
}
```

which is https://github.com/vega/schema/blob/master/vega-lite/v3.3.0.json#L12478

The description suggests it should be (taken from one of the other "style" fields)

```
"anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
],
```

but maybe it really is intended to only be a string?

**Comment by domoritz** [comment]
Good catch! That was indeed a mistake. I fixed it.

**Comment by DougBurke** [comment]
Out of interest, was the documentation wrong or the type (i.e. should it
support an array of strings)?

Ta, Doug

**Comment by domoritz** [comment]
No, the code (and therefore the schema since we auto-generate it) was wrong: https://github.com/vega/vega-lite/commit/0101f577defaef33fbe5f98ae433f430d701c9a0.

**Comment by DougBurke** [comment]
Thanks for the clarification.
