### ISSUE TITLE
Multi-Series Line Chart w/ Tooltips Example shows GOOG symbol legend only on hover

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#5186]
Looking at https://vega.github.io/vega-lite/examples/interactive_multi_line_label.html in Safari, Chrome, or Firefox, there is a second legend that shows all the tickers:

<img width="943" alt="Screen Shot 2019-07-09 at 16 52 52" src="https://user-images.githubusercontent.com/659086/60922123-0bd12600-a26a-11e9-9b6e-5dd4af5a2073.png">

However, when hovering in an area before when GOOG starts, GOOG is not included in the legend:

<img width="939" alt="Screen Shot 2019-07-09 at 16 53 00" src="https://user-images.githubusercontent.com/659086/60922127-1095da00-a26a-11e9-8a2c-181f0a54fe95.png">

Since the second legend is redundant, it should probably just be hidden.

**Comment by domoritz** [comment]
Good catch. We should disable the second legend.

**Comment by domoritz** [comment]
Fixes in https://github.com/vega/vega-lite/pull/5187

**Comment by marcprux** [comment]
There is unfortunately a further bug here that can't be fixed by simply hiding the legend: if you look carefully at the screenshots above, the first one has the text of the price annotation matching the corresponding line (red for GOOG and green for IBM). But in the second screenshot, the IBM line is green but its annotated text is red. The scales for the text annotations aren't matching the scales for the lines (as evidenced by the mismatch when both legends were being displayed).

**Comment by domoritz** [comment]
Please file a separate issue with a small example. Thanks!
