### ISSUE TITLE
BoxPlot failure to render on Safari

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5197]
The following spec fails occasionally on Safari, depending on the random seed:
```json
{
  "data": {"url": "data/population.json"},
  "transform": [{"sample": 100}],
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"type": "ordinal", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```
I have not seen it fail on Chrome.

First reported in https://github.com/altair-viz/altair/issues/1496

A less brief, but more reproducible version is [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMxIBcCeAHApqlAEYD2AHrgDamaQA0U+5m+AdnWjAJZsC0ccpAC+9cEzYBjUgBNeAcyKgIESELQYcBIpFLw5bWFQZQAZt3xUZO2PMKjxq7Eqx5CXAI4BXWB26ZYTG4AN0JGSHNLay4CUmp7cQdVGUDYJUcoYKMvfABnIgBtDIgMW3cwAEYAVnDY+KIAFiqANmbqhvDc5iIK8Ox8BB6ATgqABiSVEsgyogAOUdr8OKpygCYKjbHO7rRVvoH4YdXxsUmpmbQmxeXyseaqoYB2AGZt9Ur9wbQK2fmJydKdiIzwWUDqKzmj1GVVmzxqUC6716UH6X0qQz+pzOgPKQ1BkHB5XuzSGbyIexRBx6syqJ2K6GmQLQVXhBKW9UuGIqzShZO+n0O3yGeP+KhxPXxhLmLWeUPxiJ6AuGzTpZwZFzAq1ZUrQJNGIIayMgCt2SqFUNF5yZlUl7IhzIaINhrJNmrN6NplvV1q2YLt5QeKsNzT5H0paIqQwaquxjPK0euHMqFWexy1FONOzDkFRgs1owLXvFu1tNyIUeebV+oaNueGIqxALjEsT9rA0dGFUeDVJCKzGbrQsLjbFzeZpaTQ2aDQasw6faR7p+mPpxbAcNbtx+VWelZrS9mFpHVrWE7bMKqDVWq0eoYHVKFnuP3vKIM35NaVS788z73vEbxGMmw1LV311Z4u13DNXX-PNIyfVcx3XM9bhvFpVl7X9yQPI9EI1N8-TLXVRjxWZmmg-slynIDRw1R5tX9RpRmvTCYIPBC1TXPEwMqL9p33cM4MAoskN5QikwqVZ5mY14F0VQThmjET8IYoiwBaKdVjaO8qI42M6JQnopMeR4Nh0hShSU5812qHi2iGWVO3MnMH3RKy8OtBNxLbEEHno285NNCz0WOZTrQ3byA1+WcAqw-lgu3GiTyIWkeMNYVuR-V1a1c+CkpfOZDN2BoeVGWYBJcgCQTC3EivzQ1Zwqwd0RXTikLqiomn1R4Q0Ct0EppfKuI6uETKyyiEuomqUrq55Z1hKdnOayN3LajUWR45cSPoprcqGULrKQ+5Np7XcjWyg8VWmtBuMiohuy-Eqlr2hsPNqnjd2aEFZLi7NmuOYc3saVSkyqR4o0k+UsxygDcLW8K6sNMYTPO6GqIOoHxx49YtL43aALGa6wBpTauWqXrftg8kCyGpDQLutAyK1BpYouga9OAhGeJhIYv0ecq+qpx9afwuqWh65iKMXSaOdormGfbK8ZzK-GhOqw6NS8tk1KklUWNV4ZCY161jjSy8IdR6XKqEjH4bWEHz1aJXxr-KjVv08KHYDaFOyl7D2ZF+XtaTF5Ri+gXfphuDBqJ31g-PDF7gw56qsD8p5js2VTNZibreGWXkpLTaw86qMc9dybWo99OvYlfa47Yyb1cxm00vuUZu3L+S86FI2W5VNup06qGreWjE0+B7mSXox0U6EqvOduMXyKeGcDeFomtZ1dTeeeEYR-9nuWontAIvj+NwZ+Ei58Uk+wFu8+iFaa8b++Mi79shWp321pWNz-6aZEzFhhZosxVg-TZkfSMfc7bAlrrqGkxwSTr2PkTDaCs7glVTK-dEgNYHMnge2Ls0JZiW27mPK6xsiSEPAaRA+QUoGHjvlcBWlYzpVD9vFKBDk75iUfjdOcx0+pR2pJQluBF+HJmYoeSSKDIyvXwe2RGUltw4MSkTPh28tSXhfsIg8C85bpxGqsGcf8K7cLwdXHohDS4PGFGo9+sc6pRg4buCOkCx4GMLsTEaV5hQUw8S9O+6DJEpi7PcMhDCx4wKscRD6BYnigLUbzO+Z9t5OlmMKeh-VuExMXnAuyjoUyymSWIxRNCryCLMeQ3KTCib00kW4-aGc9GTUsfkouCtYSGlhNkoW6I4axPXIQ2UKZSF9PRnfAeGCYQz2qVwsetshkkwVvcGkZlBZUUGR05Cm1AwmU4Tk5avw76mwwXCDY6w5GOKoTNPZpl9TuLRm0u+LTGkPB6XIqMwS6q6xhBMgORM3nbxZleLuCzanbMMYVUmkYMKHP6ZGLxBVT4dQ2NCeiALuEKOWYQ8ijwGmN1yXfB+288Q9QCf-PaBcUXqV+QDHskSjl7SWTsiR29MksmvC6KlAFkU2Q6h3Fo0YIHPO4RaDIABdRIIBhBAA).

**Comment by domoritz** [comment]
This could be fixed by https://github.com/vega/vega/pull/1803

**Comment by kanitw** [comment]
https://github.com/vega/vega/pull/1803 is fixed and this is now rendering fine.
