### ISSUE TITLE
can't toggle initialized multi selection until it's cleared?

### ISSUE THREAD

**Issue by gordonwoodhull** [vega/vega-lite#5199]
I'm using vega-lite and react-vega for a biggish new project and have quite a few questions and suggestions. I'll start with the most straightforward one to warm up.

I'm using vega-lite 3.3. It's a dashboard with a server-side component. Think of it as a generalization on Nanocubes and crossfilter (and the earlier iPlots). It will be open source but it's not released yet.

The charts update each other a lot, and they go outside of Vega to get new data. This means the selection must be preserved and re-applied with whatever has changed about the data and spec.

Selection initialization with `init` works, but I find that any initialized selection does not toggle, whether or not I explicitly set `"toggle": "event.shiftKey"`. Shift-clicking something new will add it to the selection, but shift-clicking within the selection will not remove anything.

If I clear the selection, this enables toggling for that selection.

Example below with two selections. The behavior is the same with one selection but this makes it really obvious because you can shift-alt-click to toggle the purple selection, but you can only add to the orange selection with shift-click, not remove, until the selection is cleared.

(please excuse the content, I'm using Chicago Crimes as my test data)

I'm eager to contribute once I find my way around!

[vega editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhOtRpPAJ4AOhZkAcgIIBKAwgHkAKgEk+AZUgAaKnSjwAlgFs2qSACYADAEYAzAFpt6-TqGaAbMk2armgHTXNALWmy6kAMYB7fADt4ZNqaACwArG4QAL4ycrRyDCyqUHw8IgCyItwAMmAAIlxpXADiAKKucpiKKuxaeobGpha2tg7WLjEVnj7+ZAAc6roRYNFDce5MrOxCABIlAGJC5Z1VSRo6BkYm2maW1i2O7UOY3n4BqNoAnL3BQyOxR-KJ7ABCXEJCJTwAmkvxKzXrepbHbNaytZy-dwnHrnUK9bS3DrUMbUBKTNTPACqPCKWV4PyR42Uq1qGwa2yaezBB0hqOhZzAoTCiNGDzRqzSwgEPDAADUStMxFkSmAZvNFoTUf81KSgY1djZqW1afR6WRdMELiz7hVHuioAI5nMShxxCLMryBFleZkimA+IKsrkeCaVZViQC6pt5aD7DTJarugyAOw3OR3Ogo+gTVa5Ep8EoABVE-LAiZ4XD4ogTbvkHplgO9FIV+2VAeOQbIwXU4XDAajlSeah4Amez0+BLZ0qgsqLIKpfrLbLVqF0oVrdAjyK7TagXHE4i4mKyEq7+Z7hfJ-cVg4h5agI7AYXM2sjM-1kGEsx5huNprK+4Y67WXq3lJ34MOuq6pzI5k0wantO34xuwKTpJkXA5EILriIm86SI+3YvmSwLvqWe7DpWqA1r0QEYA2eqrAA6iUXCJgIpp8iIVpvDRHC5k+1QFq+aElkqmHfoevSAXWrIgbOkAANIiLk3CJomtqMchvZvuxu5fp0h5GPhNDnqsiaYs8WRiGmZEJtRtGiJR0nPrJbG+p+jHcWGk71up7CZB8PDGi6HAGcRIgzGmWk6XwYC3mInymcxG6sT6A5WY+h7BAifE6ssgngWkYBmgAGpiUFgAhS4riFJKbhZkX+lhv44bxdn8YlF46QAipi3JgHixGGXixkMUhZmFRFH4lVx2FgEEqloA5ajTAIGR8KJD5rqFKFysWll9UpA16MNhHsuw4hCFBIkcEU+WeqhPUYYp8SHhO1BTgRo1QOlAVGiaZqHSxx2LcVQ79WVYBaOtt2QOmAjbV5mLtS9YVvdup3WQNwS2Vd9kCRevDiCZnVzeZJ0cWdUKrXFlUJX8glORB+Rg+jBXhe9vWfSt32XRg11qUjqxFAU2lSRTR0LVD2Mw99+NXW4AC6VARjAJAeAATgozCKF4vjsAIUvQAovh4GAHgABawFLAQdJAhC+N4qu+AA5mQYyQAAHpbQyQAAZgohC4NA7BqgGm1qAAjvgsD+AoiCKFgbBuNdkCMHb8ROy7btqKBnugWoXgq2reCQGHhJdLgKdR+4OAEKsZtS4Qkee94viq-LiuoJQuqEZgxAu4QHjV+wTu4PAhBS9ouaYAXRDsAAxNAFyhA7mjqBnupMzduqN83rcKAr7cKJ33dT-u-d4IPahD8GoTBpoABGujTxUkRDKLQtRAbSi6wA1uwx+60skBN7gLdt6gwBgG4jtry7j3POUpBJKHwJ3BQKoGBeDNmbT+7BCAh38HYYgWsFAO3gEJUu0DCBKDlpHNQvgFZsE9ivNQSgfBN2gF4AA7r4cgABCJBRt4B2DwFg0uwtoEx1dqQWuDkr6ezVoHEB4xZx13npAZKkEcj5EKKUPuUBuD8GEGIRCDxMBXk+A9O8z0HjX0nJnf+HcgFTx-vbJOUBwGQOgfAWB8DVgsJQWgjBnCy72zwQQ9gxDfCkPtuQ6xVDCA0PoeQZxbCOHYMYNwz2vDoD8IoIIuQhiohixAJEIAA)
```json
{
  "data": {
    "values": [
      {
        "type": "NARCOTICS",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 1045
      },
      {
        "type": "CRIMINAL DAMAGE",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 823
      },
      {
        "type": "THEFT",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 1984
      },
      {
        "type": "BATTERY",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 1581
      },
      {
        "type": "BURGLARY",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 545
      },
      {
        "type": "MOTOR VEHICLE THEFT",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 349
      },
      {
        "type": "OFFENSE INVOLVING CHILDREN",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 74
      },
      {
        "type": "DECEPTIVE PRACTICE",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 425
      },
      {
        "type": "ROBBERY",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 355
      },
      {
        "type": "ASSAULT",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 456
      },
      {
        "type": "OTHER OFFENSE",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 607
      },
      {
        "type": "CRIMINAL TRESPASS",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 258
      },
      {
        "type": "WEAPONS VIOLATION",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 87
      },
      {
        "type": "KIDNAPPING",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 12
      },
      {
        "type": "PUBLIC PEACE VIOLATION",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 84
      },
      {
        "type": "INTERFERENCE WITH PUBLIC OFFICER",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 41
      },
      {
        "type": "CRIM SEXUAL ASSAULT",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 27
      },
      {
        "type": "LIQUOR LAW VIOLATION",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 10
      },
      {
        "type": "HOMICIDE",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 13
      },
      {
        "type": "STALKING",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 5
      },
      {
        "type": "SEX OFFENSE",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 20
      },
      {
        "type": "PROSTITUTION",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 44
      },
      {
        "type": "ARSON",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 11
      },
      {
        "type": "INTIMIDATION",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 5
      },
      {
        "type": "GAMBLING",
        "time": "2013-12-01T06:00:00.000Z",
        "count": 1
      }
    ]
  },
  "description": "Ordinal chart",
  "encoding": {
    "x": {
      "field": "count",
      "type": "quantitative"
    },
    "y": {
      "field": "type",
      "type": "ordinal"
    },
    "color": {
      "value": "grey",
      "condition": [
        {
          "selection": "filter1",
          "value": "#d95f02"
        },
        {
          "selection": "filter2",
          "value": "#7570b3"
        }
      ]
    }
  },
  "mark": "bar",
  "selection": {
    "filter1": {
      "type": "multi",
      "toggle": "event.shiftKey",
      "empty": "none",
      "on": "mousedown[!event.altKey]",
      "fields": [
        "type"
      ],
      "init": {
        "type": [
          "CRIMINAL DAMAGE",
          "NARCOTICS",
          "OTHER OFFENSE"
        ]
      }
    },
    "filter2": {
      "type": "multi",
      "toggle": "event.shiftKey",
      "empty": "none",
      "on": "mousedown[event.altKey]",
      "fields": [
        "type"
      ]
    }
  }
}
```

**Comment by domoritz** [comment]
A generalization of nanocubes and crossfilter 😲 Have you seen my https://github.com/uwdata/falcon project?

**Comment by gordonwoodhull** [comment]
Yes! It's really awesome and I'm sure I can't match that performance given the architectural constraints of my project (server-side humongous data).

I think my project also has a different focus in a couple other ways. I will be sure to compare notes and learn from what you're doing. Thanks @domoritz!

**Comment by gordonwoodhull** [comment]
To follow up: #5298 and #5304 point out that I should be using long-form initialization, e.g. 

```json
{
    "init": [
         {"type": "CRIMINAL DAMAGE"},
         {"type": "NARCOTICS"},
         {"type": "OTHER OFFENSE"}
    ]
}
```

instead of the above. It works and fixes the toggling issue.

For consistency, I also tried and failed to apply long-form initialization to a temporal chart.

This fails:

```json
  "selection": {
    "filter1": {
      "type": "interval",
      "clear": false,
      "encodings": [
        "x"
      ],
      "init": [
        {
          "time": [
            1387421181000,
            1389648861000
          ]
        }
      ]
    }
  }
```

But this works (short-form):

```json
  "selection": {
    "filter1": {
      "type": "interval",
      "clear": false,
      "encodings": [
        "x"
      ],
      "init":
        {
          "time": [
            1387421181000,
            1389648861000
          ]
        }
    }
  }
```

So I punted and I'm using short-form for the temporal chart and long-form for the ordinal chart.

I would open another issue, but I suspect that it might have to do with the fact that I'm not specifying the fields for the selection, for the reasons described in #5239.

Just thought I would document this inconsistency, in case it helps.

Since I was supplying the wrong data format, I'll close this.
