### ISSUE TITLE
Refactor: migrate init to normalize where sensible

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5211]
Right now some of the normalize calls happens after the main `normalize()` method. We should consolidate all of them to be in the main `normalize()` or rename them to have more appropriate name (e.g., "init..."). 

cc: @willium

**Comment by domoritz** [comment]
Why rename to `init...`? I think `normalize` is a good term since it's searchable. Why is this a bug?

**Comment by kanitw** [comment]
As stated: 

> Right now some of the normalize calls happens after the main normalize() method.


It's bad that we name our phases (normalize, init, parse, assemble) but some normalize methods happen during init (model constructor), not normalize -- so we better either move them or rename them.

**Comment by domoritz** [comment]
Ahh, I get it now. Totally agree.

**Comment by kanitw** [comment]
Currently we have renamed ones that happened after normalize to be "init".

However, some init (such as initFieldDef, which infers default type) should be moved to the normalize phase so that we don't have to init encoding inside composite mark's normalizer.

The other tricky part is that we may not want to generate normalized files for all of Vega-Lite specs with implicit types. We could solve this by having the normalizer call the core normalizer without normalizers that we want to snapshots (like composite marks).

**Comment by kanitw** [comment]
Actually let me close this issue since the original task is pretty much done. I'll file a new issue to focus on this migration (https://github.com/vega/vega-lite/issues/6653).
