### ISSUE TITLE
Better deal with facet for time unit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#523]
```
{
  "mark": "point",
  "encoding": {
    "x": {"field": "Acceleration","type": "Q"},
    "y": {"field": "Horsepower","type": "Q"},
    "column": {"field": "Year","type": "T","timeUnit": "month"}
  },
  "data": {"url": "data/cars.json"}
}
```

![data_voyager](https://cloud.githubusercontent.com/assets/111269/8764355/58eb2194-2da1-11e5-9293-a938ce6fdb14.png)

We should at least show some note for empty groups that there are no data for those.

**Comment by kanitw** [comment]
- [ ] in `time.ts` we should only fill domain with all values by default if the channel is `X` or `Y`.  
If the channel is `ROW` or `COL` - there is no point doing this.

**Comment by domoritz** [comment]
I'm happy to take this once we've merged https://github.com/vega/vega-lite/pull/751

**Comment by domoritz** [comment]
Works now. Although there is an odd padding.

<img width="285" alt="screen shot 2016-01-15 at 11 22 31" src="https://cloud.githubusercontent.com/assets/589034/12362981/0e8c4eb2-bb7b-11e5-9ce8-8a25cf79659d.png">
