### ISSUE TITLE
Docs for typescript users

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5247]
Right now we have types exported, but may need to document how to start using Vega-Lite with Typescript.  (People sometimes get confused which Spec to import, etc.)

**Comment by domoritz** [comment]
Yep, maybe we should rename the top level spec to `Spec` so that people can just import that.

**Comment by alexeypetrushin** [comment]
Is there any docs how to use it?

**Comment by domoritz** [comment]
> Is there any docs how to use it?

This issue is about adding the docs.
