### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#525]
It would be great to have non-angular tooltip so it works in the editor too.  
But the problem is that tooltips may go outside the canvas for vega, so this should be a plugin `vega-lite-tooltips`

- [x] understand [Vega Runtime](https://github.com/vega/vega/wiki/Runtime)
- [x] create plugin based on [`vlplot.js`'s `viewOnMouseOver()`](https://github.com/vega/vega-lite-ui/blob/master/src/vlplot/vlplot.js#L71) in vega-lite-ui's [vlplot](https://github.com/vega/vega-lite-ui/tree/master/src/vlplot)

------

- [ ] augment `tooltip` channel that is only read by the plugin.  This channel should accept array (similar to `detail`).

- [ ] create "Bar chart with details" example

-----

Step

- [x] create an html page.   Import Vega-Lite compile a spec (e.g., scatter plot ) to Vega.
Call run time to render.   Copy necessary part from `viewOnMouseOver()` (and `...Out()`) and the css file.  to produce a working tooltip in your html page.

- [ ] think about how do we make a library

**Comment by kanitw** [comment]
The simplest version of this could be another config called `tooltip` 

```
config: {
   tooltip: <template> | boolean
}
``` 

If the `tooltip` is `true`, then produce a template that contains all fields in the encoding like this   “<field_name 1>: <field_value 1>, <field_name 2>: <field_value 2>, …"

**Comment by domoritz** [comment]
The problem is that tooltips may go outside the canvas for vega.

**Comment by kanitw** [comment]
Yep.  Or maybe this should be a plugin ...  (`vega-lite-tooltips`?)

**Comment by kanitw** [comment]
Closing as we already extracted this as a separate project.
