### ISSUE TITLE
Support Google Chart Timelines-like graph

### ISSUE THREAD

**Issue by SuperShinyEyes** [vega/vega-lite#5250]
Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior. 

## What
Please provide a timeline graph API.

## Background
The following demo is created using Google Chart Timelines API(https://developers.google.com/chart/interactive/docs/gallery/timeline). I will explain what is happening in the GIF as the resolution is very poor.

- Bar plot over time axis. Each y-category contain multiple element categories.
- Google Timelines has select event listener. I can check which element is clicked.

![Image](https://user-images.githubusercontent.com/5738363/62122933-7e647d00-b2cf-11e9-89b3-836c7a874ad3.gif)

Video version is here: https://www.dropbox.com/s/ohpr5om8hv6yhq7/altair_timeline.mp4?dl=0

## What's problem with Google Timeline?
Google Timeline is *almost* perfect except,
- The select event listener is broken. Seems like the similar problem has been reported over the past 3,4 years.
- Time-series data is prevalent in machine learning research.
    - This kind of visualization is very beneficial in video/audio/any-time-series data.

**Comment by domoritz** [comment]
You can already build timelines. Have a look at our gantt chart example: https://vega.github.io/vega-lite/examples/bar_gantt.html.
