### ISSUE TITLE
Support boxplot along continuous scale

### ISSUE THREAD

**Issue by michaelaye** [vega/vega-lite#5263]
Currently, it seems that the orientation of boxes for boxplots is inferred via which axis is set to type `ordinal` (IIUC).

However, there are use cases for boxplots over irregularly sampled points in time, e.g. at Mars, we study ten-thousands of surface deposits with these distributions of areas, here, at 3 different points in time (time is called Ls = solar longitude for orbiting planetary objects):

![ithaca_histograms](https://user-images.githubusercontent.com/69774/62431691-bfe99380-b6e6-11e9-818b-b4c29f1fe23f.png)

resulting in plots that describe the development of these distributions over a range of time, like this plot, where we use error bars of interquartile ranges, to emulate boxplots:

![Figure 1 (1)](https://user-images.githubusercontent.com/69774/62431725-0b9c3d00-b6e7-11e9-8314-d46db6b6d0c6.png)

The current norm for boxplots is to do this:

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"type": "ordinal", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```
creating:

![visualization (1)](https://user-images.githubusercontent.com/69774/62419202-0b913400-b638-11e9-8cb7-451f30f963ea.png)

but in that case, when there'd be data missing over the x-axis, that void would just be filled, as x-axis isn't a quantity (as discussed here: https://github.com/altair-viz/altair/issues/1496).

Jake's work-around in that issue was to impose a domain scale with given bins like so:

```python
x=alt.X('age:O', scale=alt.Scale(domain=np.arange(0, 95, 5).tolist())),
```

but my proposed feature is to simply switch the x-axis type to `quantitative`, so that the boxes are being placed at given data points for x.

However, trying to do that currently, like so:

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"type": "quantitative", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```

creates an odd looking plot where bins seem to be merged:

![visualization](https://user-images.githubusercontent.com/69774/62419015-3e392d80-b634-11e9-8136-d75fe6ba6763.png)

because `vega-lite` doesn't know from where to infer the direction of the boxes.

I guess my feature request would then lead to an `orientation` keyword, possibly with a default of being drawn parallel to the y-axis.

My expected behavior/spec would be (note the `orientation` option for `mark`:

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max", "orientation": "y"},
  "encoding": {
    "x": {"type": "quantitative", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```
and a plot that could exclude missing data, treating the x-axis quantitatively, like here:

![61178556-f4fd3d00-a5a3-11e9-976a-9f864403b65f-1](https://user-images.githubusercontent.com/69774/62433015-ecee7400-b6ef-11e9-8f97-7e346901999b.png)

**Comment by domoritz** [comment]
Thank you for the feature request and the example. I agree that it would be nice to support boxplots at arbitrary positions. We can by default assume a vertical orientation but make it configurable.

**Comment by domoritz** [comment]
We already have an `orient` property (used for lines and are) so we would reuse that. 

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max", "orient": "vertical"},
  "encoding": {
    "x": {"type": "quantitative", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```

The issue with using a quantitative encoding for x and y is that we now have to group by a quantitative value, which is not good. I wonder whether we should instead just change the scale type. 

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"type": "ordinal", "field": "age", "scale": {"type": "linear"}},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/62477758-e91f2800-b7a9-11e9-9b53-7c22dc950fd2.png)

What do you think?

**Comment by kanitw** [comment]
Sounds like we have a bug.  

Using conflicting type and scale also looks like a hack to me.  

@chanwutk -- would you have time to look into this?

**Comment by michaelaye** [comment]
In my use case, we usually group by a logistic item (a string type) like image_id, and the end result is just being displayed at the times (here solar longitude angles) at which the images had been taken.

**Comment by domoritz** [comment]
Yes, using a linear scale would correctly treat missing bins. I discussed with @kanitw offline and we decided that the boxplot macro (under the hood we compile boxplot to a layer of rects, rules, and points) should support q by q with orient. 

This spec should do what you expect: 

```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max", "orient": "vertical"},
  "encoding": {
    "x": {"type": "quantitative", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```

**Comment by michaelaye** [comment]
How do you solve the issue of grouping on a float?

**Comment by domoritz** [comment]
We will just group by the values in the field of the x encoding (assuming vertical orientation). Is there something wrong with that?

**Comment by michaelaye** [comment]
well, only the standard problem of float equality. If values are close to each other,  I guess that could result in plots looking different on different machines, theoretically?
An alternative would maybe be to require a grouping column if the x-axis is of float type? Or, a grouping precision.

**Comment by domoritz** [comment]
I'm not too worried about float equality since the floats are part of the dataset and we don't usually do different computations on them. If the floats come in as different numbers, I would expect the user to correct the data before passing it to Vega-Lite.

**Comment by jakevdp** [comment]
For what it's worth, it looks like this is a problem with bar, but only when using both a quantitative scale and min/max limits. For example, this works as expected:
```json
{
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y"}
  },
  "data": {
    "values": [
      {"x": 1, "y": 2, "y2": 1},
      {"x": 2, "y": 3, "y2": 2},
      {"x": 3, "y": 1, "y2": 0},
      {"x": 4, "y": 4, "y2": 1},
      {"x": 5, "y": 3, "y2": 2}
    ]
  }
}
```
![visualization - 2019-08-05T204849 787](https://user-images.githubusercontent.com/781659/62510037-6fdfff00-b7c2-11e9-90d1-ca49ac870e71.png)

But adding a ``y2`` encoding breaks it:
```json
{
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y"},
    "y2": {"field": "y2"}
  },
  "data": {
    "values": [
      {"x": 1, "y": 2, "y2": 1},
      {"x": 2, "y": 3, "y2": 2},
      {"x": 3, "y": 1, "y2": 0},
      {"x": 4, "y": 4, "y2": 1},
      {"x": 5, "y": 3, "y2": 2}
    ]
  }
}
```
![visualization - 2019-08-05T204938 741](https://user-images.githubusercontent.com/781659/62510068-8dad6400-b7c2-11e9-9fb3-8f9ab73c47b1.png)

**Comment by domoritz** [comment]
Looks line our detection or orient is broken in that case. 

This works

```json
{
  "mark": {
    "type": "bar",
    "orient": "vertical"
  },
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y"},
    "y2": {"field": "y2"}
  },
  "data": {
    "values": [
      {"x": 1, "y": 2, "y2": 1},
      {"x": 2, "y": 3, "y2": 2},
      {"x": 3, "y": 1, "y2": 0},
      {"x": 4, "y": 4, "y2": 1},
      {"x": 5, "y": 3, "y2": 2}
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/589034/62521803-a05e8200-b830-11e9-8914-ed8ffac873e7.png)

**Comment by domoritz** [comment]
Ahh, that was it. We have an error in the default orient computation for bar marks. 

```json
{
  "width": 400,
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "mark": {"type": "boxplot", "extent": "min-max"},
  "encoding": {
    "x": {"type": "quantitative", "field": "age"},
    "y": {"type": "quantitative", "field": "people"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/62524758-76a85980-b836-11e9-9fd6-c44fe42a9e5a.png)

**Comment by domoritz** [comment]
Okay, https://github.com/vega/vega-lite/pull/5273 is not the right fix since range marks are often oriented the other way for prebinned data. I think we just need to set the orient manually.
