### ISSUE TITLE
One example broken in the gallery 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5269]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/111269/62499302-05fe3000-b797-11e9-9bf5-da7652121250.png">

**Comment by kanitw** [comment]
- [ ]  this page is also broken 
https://vega.github.io/vega-lite/examples/concat_layer_voyager_result.html

**Comment by domoritz** [comment]
I fixed the top-k plot in https://github.com/vega/vega-lite/pull/5349. 

vega.github.io/vega-lite/examples/concat_layer_voyager_result.html 404s (and so does concat_layer_voyager_result).
