### ISSUE TITLE
Enable test `should always be disabled if the stackby channel is aggregated`

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5285]
https://github.com/vega/vega-lite/pull/5005 disabled a test that was previously not actually testing different conditions since it used an undefined property.

**Comment by kanitw** [comment]
Why are you disabling it and assigning it to me?

**Comment by domoritz** [comment]
I don't know what the expected behavior is and need your help.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/5005/commits/eaa6cb11dc84656c2dd1e895549234f12964fed5

**Comment by domoritz** [comment]
Thank you
