### ISSUE TITLE
Binding scales failes for aggregate

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5308]
The following spec produces an error ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAB5kCMAvgDRXW0OovvU30yAJjYcMXMgGZR-NINQBWZmIC6VGVAC2sAE4BrMpAAOAewCWAO3iQ+UQhYDGJ6JYDmZdBnloxmAGZmhLjQhgy21JDwAJ5GhIYAjviwVmaI8GZYcWIamFEevlCwrq46hK4IcaiQTvhWNgWRMZVQicnpaRlZ1MoQGpDEQYQO6SYW+REAXiYmmuP8kABGliFVxA54JPWykPZOLhaupKjkgqxQeSrhXtGxhpbwhDo4uJDZ6iDMQA)):
```json
{
  "data": {
    "values": [
      {"x": 1},
      {"x": 1},
      {"x": 2},
      {"x": 3},
      {"x": 5}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  },
  "selection": {
    "zoom": {
      "bind": "scales",
      "encodings": ["x", "y"],
      "type": "interval"
    }
  }
}
```
```
[Error] Cannot read property 'length' of undefined
```
If you remove the ``"bind": "scales"`` it works as expected. First reported in https://github.com/altair-viz/altair/issues/1663

**Comment by arvind** [comment]
Yes, unfortunately for a variety of reasons, selections are currently broadly incompatible with aggregation.

**Comment by domoritz** [comment]
Can we add a warning with a link to an issue that people can subscribe to?

**Comment by g3o2** [comment]
does this limitation extend to aggregate transformed data as well?

**Comment by arvind** [comment]
We seem to have fixed this along the way (including adding a warning about projecting over an aggregate field). As of Vega 5.17.1, Vega-Lite 4.17.0, the above spec no longer throws an error and the plot can be pan/zoomed horizontally only.
