### ISSUE TITLE
Initial value for interval scales selection

### ISSUE THREAD

**Issue by saulshanabrook** [vega/vega-lite#5319]
I can't get "init" working for interval selection bound to scales:

```json
  "selection": {
    "selector062": {
      "type": "interval",
      "bind": "scales",
      "init": {
        "x": [-3650484.1235206556, 7413325.514451755],
        "y": [-5778161.9183506705, 10471808.487466192]
      }
    }
  }
```

[spec](https://vega.github.io/editor/#/gist/0154ac72c8207b996aff7d7ae4ca4f77/tmp.vl.json)

It errors with:

```
[Error] i.init.map is not a function
```

**Comment by saulshanabrook** [comment]
It looks like this feature was added by @arvind in https://github.com/vega/vega-lite/pull/4139. I don't see any examples in that PR for when the scales are bound

**Comment by arvind** [comment]
Thanks @saulshanabrook! Technically, this isn't a bug as we used to log a warning that `Selections bound to scales cannot be separately initialized.` However, I've lifted this restriction in #5352 (which also describes the reasons it used to exist, if you're curious!).
