### ISSUE TITLE
Filter out non-finite values (Infinity, -Infinity) by default from quantitative scales

### ISSUE THREAD

**Issue by fedarko** [vega/vega-lite#5325]
Derived from https://github.com/vega/vega/issues/1835.

`"NaN"` values are already filtered out by default (along with other non-numeric strings), but `"Infinity"` and `"-Infinity"` values are not filtered out by default—and they mess up the display, as demonstrated in the above issue.

Thanks!

**Comment by kanitw** [comment]
Sure, will be fixed in https://github.com/vega/vega-lite/pull/5415
