### ISSUE TITLE
sorting breaks for line and area marks

### ISSUE THREAD

**Issue by richardhundt** [vega/vega-lite#533]
Hi - you can observe this in Polestar as well - if you choose line or area types and try to sort, it breaks in visually interesting ways. It looks like the axes are sorted, but the vectors connecting the points aren't aware of the sorting.

I'm doing the following, and the axes are sorted correctly and for bar and point types it works (all my aggregations are done server-side, hence the `aggregate: 'max'`):

```JavaScript
        spec.encoding.x.sort = [{
           name: 'y',
           aggregate: 'max',
           reverse: true
         }];
```

The problem seems to relate to the `sort` attribute on the scales overriding the data sorted via a transform. It also looks like Vega itself sorts ordinal scales even if the `sort` field is not set, and since nominal maps to ordinal scales, it gets sorted lexicographically. While this makes sense for ordinal values, it's a bit arbitrary for nominals. In particular, when plotting quantitative against nominal, I think that what you'd normally want is to sort the nominal by the values of the quantitative scale.

**Comment by kanitw** [comment]
Thank you for reporting.  We plan to fix this after we migrate to use Vega 2 :)

**Comment by richardhundt** [comment]
I noticed some traces of the migration in the vega-lite code, thanks. Are there any blockers for the migration? If not then I can take a crack at it.

**Comment by kanitw** [comment]
@richardhundt  we wanted to create more tests, refactor code and fix some bugs before migrating.

**Comment by kanitw** [comment]
@richardhundt Do you have an example spec / data that I can test this?

**Comment by kanitw** [comment]
Sort property is totally rewritten based on changes in Vega 2.  So I do not think this issue is no longer applicable.  If you find similar problems with the current version of Vega-Lite, please re-create another issue.
