### ISSUE TITLE
xOffset/yOffset cannot be applied to static x/y markdef properties

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#5331]
If I want to place a circle mark just below the bottom of the view, I can do:

```json
{
    "data": {
        "values": [0]
    },
    "mark": {
        "type": "circle",
        "size": 250,
        "yOffset": 25
    },
    "encoding": {
        "y": { "value": "height" }
    }
}
```

which will yield the following correct result:

![visualization](https://user-images.githubusercontent.com/659086/63630365-eb75e480-c5e7-11e9-90d8-ad3cdceb1818.png)

However, if want to express the same thing statically in the markdef (without any encodings), I should be able to do:

```json
{
    "data": {
        "values": [0]
    },
    "mark": {
        "type": "circle",
        "size": 250,
        "y": "height",
        "yOffset": 25
    }
}
```

However, the offset is not applied in this case:

![visualization-2](https://user-images.githubusercontent.com/659086/63630443-adc58b80-c5e8-11e9-86fe-07bbaff4acb3.png)

It seems that `yOffset` is only applied to a `y` encoding value, but it should also apply to a static `y` markdef property, because otherwise there is no way to position a static annotation against the height of a container.

The same goes for `x` & `xOffset`.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5665
