### ISSUE TITLE
vega-lite interactive legend

### ISSUE THREAD

**Issue by kaplan6616** [vega/vega-lite#5357]
I am wondering if there is a way to do interactive legend in vega- lite ? I want to select a field on legend and show only which i checked on the graph.

**Comment by jwoLondon** [comment]
This may be the kind of question that is best asked on the [Vega-lite Slack](http://vega-js.slack.com), but for the record, here is an  [example of an interactive filtering legend](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCjxlAM0bVsYYFAqNkAdwNHIsPACduAa2QHIkAL5g36iJAAm6PEwcUAgfVlsxF3wiEnImeGQlO2QGZjZOHlJ-QNIzZBsAWUZfMXQlX1hc-LwiioBhW0ZUfIBBampbYTxkXzo8WApIDS8NSEQtJXgAgwBtDQgQ0J87MthtbltUWfmlwx3dqF0xbttLKFhkMWR4PB4VHEgr6kTfAGVL933Qty+AXW9dpBElpfIwlPpgl8fAAPSxQ0KQXSXXwuVDKFhqeHLACehGcD26qEIG3QkXhIwOPmxcMpCKRYhRD06xNs3V8DSa+UxtJxeJcAEdWGVboFblQhrSKZTIFoxBsaTzEaYGS54I1mgAVXHOAG0yB4bUuJTcVBg0ncxVPF4GJSsMRiclfKVLSAYWwOM76w0PCRKZw-JbOvYHayXa63ZQKkNW8rvSKQnlQA18h6oO23C164HcUHg2CzTTcOWnMC-R0HIM+bO5iHB6XUhOK+mMzTq5Bavm66XJ-FQY2mpTmrsh9DQxj5xuJ-XMK4uTOK3wm9BggzaUkXYfdxjwBwTsBrsQXLGecmbnyy+WT6UTUER+51qcXK43O4uGNvD5nwHN1Vtjs649eV7SB+zNSIvxdd8bTtB1E0rQEKFJVhgIkah8A6ZBqXLXZ4NddB3SjQEexcWBBXwgC9VgRgAC9ewARgAJgABi-SBuEIdB4GYBswDop0dgDUsQDcIA).

**Comment by kaplan6616** [comment]
this example not actually interactive legend. In this example there are 2 different graph with concat. I can't use it because concat is blocking the autosize in a page and i don't want it. Is there another way for interactive legend or can i use auto size with concat? I don't want to give width and height value hardcoded.

**Comment by domoritz** [comment]
We very much want interactive legends as well for for now the concat solution is the best we have. 

We are already tracking the feature in https://github.com/vega/vega-lite/issues/1657.

Draft pr is at https://github.com/vega/vega-lite/pull/5305.
