### ISSUE TITLE
Binning is empty when negative values are present

### ISSUE THREAD

**Issue by vivekratnavel** [vega/vega-lite#536]
The chart is empty when binning is applied to a scale having negative values.

**Comment by kanitw** [comment]
Thanks gor reporting -- posting example spec and screenshot is also helpful.

**Comment by vivekratnavel** [comment]
Sure.

Screenshots taken from charts generated by Data Voyager.

<img width="443" alt="screen shot 2015-08-02 at 11 37 03 am" src="https://cloud.githubusercontent.com/assets/1051198/9027477/3658a348-390b-11e5-8446-4a8ce4a865b7.png">
<img width="533" alt="screen shot 2015-08-02 at 11 37 33 am" src="https://cloud.githubusercontent.com/assets/1051198/9027476/3656dce8-390b-11e5-8137-f78e697a9c24.png">
<img width="535" alt="screen shot 2015-08-02 at 11 38 33 am" src="https://cloud.githubusercontent.com/assets/1051198/9027478/3659a6d0-390b-11e5-8e03-ca714db1fd7a.png">

This can be reproduced by replacing all the empty values with -1 in cars.json dataset.

**Comment by kanitw** [comment]
Could you please post your version of cars.json on pastebin?  That would be helpful for debugging.

**Comment by vivekratnavel** [comment]
http://pastebin.com/V2B5Aah3

**Comment by kanitw** [comment]
I was investigating.  This is probably due to the fact that vegalite uses bin from datalib, which has a newer version of binning function than Vega 1.5.4.    

So this should be fixed once we migrate to Vega 2, which uses datalib’s binning too.  

I’m moving this to 0.8 and will revisit this after the migration.

**Comment by domoritz** [comment]
@kanitw any updates on this?

**Comment by kanitw** [comment]
Testing with this spec:

```
{
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": -52}
    ]
  },
  "marktype": "point",
  "encoding": {
    "x": {"type": "ordinal","name": "a"},
    "y": {"type": "quantitative","name": "b", "bin": true}
  }
}
```

Binning is working fine with negative values.
