### ISSUE TITLE
Change default quotes to `"`

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5361]
I'm proposing to change the default quotes to `"` instead of the current `'`. The reason is that JSON quotes are always `"` and if we use the same quotes, we can easily use `'` to quote expressions that are just JSON strings and avoid having to escape with `\`. 

My hope is that it could clean up things like this:
<img width="640" alt="Screen Shot 2019-09-01 at 10 42 58 AM" src="https://user-images.githubusercontent.com/589034/64080168-d7944780-cca5-11e9-9dde-d17dcfa557f4.png">

Single quotes are better for sentences that use quotes themselves (`He then said "Hello World"`) but double quotes are better if you want to use ' (`Don't do that`). However, for our warnings, we often use \` anyway. 

Since we use prettier, this won't really be difficult to enforce. 

I am proposing to change the default here and in all other Vega libraries. For many projects, we can easily enforce this change via https://github.com/vega/vega-lite-dev-config/. 

Thoughts?

**Comment by kanitw** [comment]
‘ is easier to type, no need to press shift.

I’m voting against this change.

**Comment by arvind** [comment]
My preference would be to minimize the amount of churn unless absolutely necessary.
