### ISSUE TITLE
Change default projection type

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#5367]
Now that Vega includes the [equal earth projection](https://en.wikipedia.org/wiki/Equal_Earth_projection), could It be included in Vega-Lite as one of the built-in projection types?

VL4 might also be an opportunity to change the default projection type away from mercator as this is rarely the most appropriate for the kinds of mapping Vega-lite is used for. Personally, I'd argue that the identity projection makes most sense as the default as it is semantically closest to 'unprojected' when a projection type is not specified. But if that is not suitable, the equalEarth projection would be far superior as a default compared to the mercator.

**Comment by mattijn** [comment]
I created PR https://github.com/vega/vega-lite/pull/5368 to add the `equalEarth` as projection type in Vega-Lite. 

If you want to change the default you'll have to mention this upstream at Vega. Namely, if you don't declare any projection type in Vega-Lite there is no projection declared in Vega, but the map will show up in `mercator`, so the defaults in Vega is `mercator`. 

If it is changed there it is merely changing the docs of Vega-Lite to reflect this

**Comment by domoritz** [comment]
Vega-Lite already supports the `equalEarth` projection. I agree that it would be best to change the default in Vega. We can use a different default here if it's difficult to change the default in Vega.

**Comment by jwoLondon** [comment]
Ah - hadn't realised it was already there - thanks.

As for default projection, shifting the default in the Vega minor release cycle [could cause backward compatibility problems](https://github.com/vega/vega/issues/1985#issuecomment-527792028), so  perhaps given the VL4 major version release, this would be an opportunity to make the shift in VL independently of if/when it might happen in Vega?

**Comment by domoritz** [comment]
Yes, we could make it independently. I'd like to hear the intent to change in the next major version of Vega. 

@jheer @kanitw @arvind any concerns if we change the default for v4?

**Comment by kanitw** [comment]
I was going through the list of issues and seems like this one missed the train for v4.  We could still consider this for V5 though. :)
