### ISSUE TITLE
Support selection to set bin extent?

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#5370]
I would like to support smooth zooming (not filtering) within a histogram. As I zoom in, I'd like the data to re-bin to a smaller step size. In Vega I would use signals to do this, but that is not an option with Vega-Lite. We already allow the use of interval selections to set a scale domain. Could we do something similar for the `bin` extent parameter? This would affect both the `bin` transform and the `bin` encoding directive.

Here is an example of what that might look like (ignoring the selection definition for now):

```json
{
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "bin": {"extent": {"selection": "interval"}},
    "y": {"aggregate": "count"}
  }
}
```

When the selection is empty I would expect `extent` would default to the normal data-driven extent.

Of course, this approach might still have some wrinkles, for example if bin boundaries jump unexpectedly upon zooming. However, the default use of extent `nice`ing and snapping to human-friendly step sizes (1, 5, 10, etc) might go a long way towards keeping things stable.

**Comment by jheer** [comment]
Here is an [example Vega spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10BOAGwBmO1APo8TBwAbSUIYEgZdFQdHEg8RhiAfVg1ACcdAF9fcLCIKCiY3UhpVjT4ZCSABmN8-MgygBti-0DSADNGxmp8WABaUQBrSWk5HPr27jSMPF0IvABPQlioKVlIbLz7PDT0GVhJ6d1QurrQU9P4pZXIQ9RWRsxxi8hkAA9CNOLEbjLYAApWqxUHRWsgAJRgADUYFQllUyABQJBYMhpDAHhqz0u6FgxQSRS2+U2F1ypPqi2WxXeeGQMlm2Lqt0YyEaRjiBJ0jPqGmoUWacXgsngASSAEYkuxLEkMG8pfskl4qklOUkaXTZkSICTSedyVBKTd5bV9czWeyDYkuVr6rjjpB5TL0HLLLBFcrOQooI7ZfK3UqVVa1TIjABdbn2Xn84pCmQivDiyXS32u92B5J+k3kyAp-a6JURqDq+lzErdaMcq3BADknOrobAAB9G2BY-HEz7nX606ri7NMjadRc9dnDdS3rSS4WzWz8Vas6Sy3z0AKoG3RcrOy6FQG4ftaYRE72JxrIIPuSPF2O4sbp+0WbPK0Vp3aQjamVvu7vXQej-PC-Yn6pt++7IIeEq9iGZ76mA4bvlAUYrjGwobkmMhOtu-rKnuqRgX+GauguLy5niOAFvBOY-mBuhitOfalohq6QOuCabsmXbAdhVHgemlT0QO5ICacoZ5EOYCXvYhQ3K06DVERCG-OUNylEpcnYvEuz7Hcxw2hJlzXso1DUBktC0vJTLGb8hDsAs9pATuHr-t67GYT2QZ0mG07cMQ9pCqwJZwTBM4GKRYDBDIDyNIFpqvmFkBJEkfkBeeukUQZzKNLSXx0R8XxxMiwQADoOi5X6OTExUNgAhAAvDVYARY0jRgAAZC1YBVYwsAAHLoN1gIBMCRUlehJFuRVkChuC0GkkJdQiXUYl6ZE0TSQEslivJJSKRUxQqRUalEhpewHFMqA6eSelMul6BGSZATWkFlmsNZtlvjBgGlZxMrcfhj0fSNGFlT9oE8ZBRjwdF2beaFwTMb8AV3g+IXHI1UUvrD8WJQjswLbNF5pdcxT3plyDZRR7yfC0g2oMN9lYSDuFg1alUdXVDWRa17WdT1fUDXgQ3FfTaY4b+EEs5N02DkSePako0VLvysN5BEUnIXGqEoN0+BepAFArqwKxilUVRLStRSCihCYSlrPQMlA+uNIbNEm0tR1q3E-nMFtjvOzgwBifY6zvbqrxUPSoU5r8sBoNwVC6y9YLFF1AAqL2NMg-zPYQ-zgpCAD8YDZ7nYA4F7-Yy6J4yq6tc7PlAicPcUFCNAAyqyyDwAksgAEqItwjRUP8xWqqkUzIMV01CQrjwLL8sz+6YhgWFYugAExVPIa4D8CeY4LR3oIyjcTtJFusruW1LoEgGy+Dm6BpIMytnEd6XZ1tHvbxrrFJO-6mpAsDOMZWTNHUnSIUBgVhXQboQJO-sKJOBcIgBi5YkJxEQa4QOlxbY60XoxdW7ZlQ4IroJIkWDFYrmfrqCin94hBjeOZeovsVjBChouYOYV4Jkg+vYZA4c8ChWgdmfaykhRUgAvpImcRUDR2QAYbgDgxhcMuCTLKF0eGXCqnwjUXBaSoCbC2bR9JdFoDoBgR+dApJs3qiPIM7A0isFgIgYqM0NGwWUdqCR9hG5mTiMEN4-xy7gi3gEoJoZXH6iwcODxRZ+GCJiZGHaNwnAhgUYw0cUioAyMcbHeOXj6ixlgMCFYOxDb5MAsgPADhkB0nUW47h9SeRJL2mI-6jTtiZKjjk+Rij0kA1UWTOp7T7BaP4SY-RzYwBGLwOMsxD9hhWNqjYuhGYHFOJcQk4SmzPHbPEttMou10GWB6brdK2SY4vQ2Js2WH0omLh8TcYIqo3jBCqOGVsjxUA51CTIZgwSwCbzABgxA4JwnKLuS-NxYcNSCIoUxUeIoM4qjSN0aggyIWXAecUYICAVyZ2KixaoSQ3jFS3qqTkryppb1xRnYe8Nv5EpJV6clVYxRTTBTwjFDSAbTNhfgp8lQdgnUeLSJIkDMqYC5fULFgpPmEB7nsNF-x9AyAADKWGQA-f45LNKwBFZUPYSAph0D7MSslQYhX7H1WK1kgQ6BvDAOiWAKrtUWt1daw1Pw0gmpPPSYlect6AuBVLTlEihGXF5Sg5c8KgyaG4NwVANqJW3xiQ0WBTdZXRHlYqzOcaE3qpkJqtIrrkhvHNckPNibPXGrLWAVUlak2BH+UG5wLAQ23LDamyNIQIgiJad5LkBpOkGHYI0eAXR4CDA2GwoKMqoCvMDRy25kMUqXRobXAVvE+mQA4ScD64amTdr2fyy0paU1QrnSsyoLy3lgDqvVZ5wQ2VgELmjUuYBLBUDSHgOlhLlRMvLde9tME5qkhuYtAmQVaEIrxci1FgzpzMLmBindcgQ4wQPfUI9wRe2IpuH+4l078lprgVAf4PMACCaRdgLBLYKq0kJJn-ChJ+smP6CVW0ZaSut9DwSUrvezKELKYj8batCVj37f2cf-dx55fHn33uhMJ5AT6poFx48kGlgqUVGTJu+gOETSEwXA8SSDppoMWvTm09haHOE8Mw7wuJxxe2oJjckT0mQZ2mkvcpl94ly44A4wyqo3H7zmhIBpwVVmkhhbZLALezCItPItVaUMmR31o0M7NFdgkzPZgs+56LsWUaIYNiwiIxW66DuYogPYhamIMK3lcKkcQe7TtXdQqDG7T3aeFQ9JI1byZBSQ-7FDu7lEOdiTCoZ9ndn7KUv28Rc2zmyJ6Uo4Z99H4FcqPYxxyDNmgeM8Ry9wA3g4B+X8reCwcC0aCVvU1Z2wB6sYBUOj-rMhZYuIdrZuXUpdYtj15FfXRXisCNukb4kxu2b3RhrtTn0MaMm0yPtRzUkOD6RklrWTZEyLyXNwpxTdClOQOU+o7BKnVNqQjxpSPFwo4Qq0jHAMVvdIUet4Z9RzGDG25KNZ+2OdgClZdebhyoApJOU1lnFzCBXOGSZkDMSvPZhO49nVwODVxi9fasAfQwAXbwP867kWgdWv64NugCwddgFu78g3H3wU5fxn98z3Wr1JAbYN7d43ZtQuw5s2niSDmiIHUzl46UHAoFZKHy4BOAfE9J-YLnPPdtOM+5ExXx302+KgKd87gTbeG5u-nv59vOWO6+3lxcPOG2g6eBRb3+64fTep43jb9OSiM4T0OrHjhI+gPx7IIpceHEk7m0n13qoU-8-qd98kSvFyHFF-H1Nl7CAKP+GKOgJsD7TNBLa9AABNMAAAqMAa+HAb48PdsZteACy3BIF5zT4tcvpw7nhvNjcVUMiLDtFstOS9H-RgP-OlUedICeZlSzQgDOMlEfYDN-GWdSLnKhaJf7L-OxPnSUawacdKDILubdcdRgGXHAZfIKcBB-KBZRV4ekQZeBKFEmVcCICHSAAAYi8HYPPQ0QykaAAHl9B4BmA3o9kIcqg6AxQ15RBZ838JESMM1xJU0GEW9YcNtaRUhqZAhQCgwx4MhJ46AM4rAWAuYwAZJNDNNwDJ5KU6By4BNlk-0XEu84UqtiVKVn8ncac9YytdBTYM9U0hCYdEdltEQF4-B1pTDKhtCIDwQ9C6RqBDCxMTDbEzDx4LC3krDbcbCwAgtCF7C5sRCDtScmDPCcBvC3F58Xg3g14ZtW92l4ggj1D0AwiUhzDIAoj9DYjEAjCEi3cIiUjQw0jmAMisiNwci29XMnCXk2VXCK9-cPCnYVgSiNEyjLgFhKilD9QA8DQ6j8pQjEjwjmjWiYi4j2ouiwDkiWjLDrDFMhjWIRiajKtF5344hiFZcZ8CjZi-YAUpCLh5cECFdfs100CCFUJkDt1cDO4GQKIAEgEQgHQH5Jo7w0gE1SwZJ6jxRODsxyDIE5gqC51JtuDSxmCWCAAWeAAAdgAA50ByT0SAYKiqjlCajVDgjIACohYvoHJGYxZeJWZFM31Jkupep+pWTAYxoQImY-pKppoHC8jGkhd8gNiO88UgSf5Gs5t7jnJRoOIOTRY8JxZnw5tuB2h2gY5gixQDsfCoVFC7N6kFSmT1DBYRStSGYdTmYJoGxeTOZ+TeYhSaY6Z2TnTfo9SICppo8mQZTXj-c5stNlTGVQyJhkZihhYxSuTwYpjfjFjiMhDcMlTLZgskh-8oB1SsYkp+xMzVjj08MYzlQCz3j5ivjiR4IpD3910Ac3cp9QTOk8CISgpCDiC60R86I4wKDsSeFqC1FF4GCCSiiDRdV9AMgSxMgpVZDs88SrT-CfdGStiQiNDdimiziDiDCOj4idjuj9iLj0irj6VsjIA4zIwxjN0b0l03E5TwhayvD6z5pMz6T1jAi1DtidzTz9zojDzOiTzTidDzjUjLj2ZrjqhbjGk3zij8iZiRCPz8glimQ6S1iATNy-ztyGjdyeiWjgL2jQKALwLIjzyBjLy7CbyHCT03cJinyNEXzhDpyFieEML6gVjvycKEK7T-yCLAKIKDzSLjzyKtCzyoKLyYKrzhi6K1SEyHjETLknjkBtYSEIz3DUKLSuDUhETBgWEZiBLAdHzrFjcmLdZmCI9mAsg3iIc0Y0KIAfiX8-jstvj1JnRERvyP9ozczCFCMvIUVTwbxuACAkTpxjJnBdB2hKFR8goEg8BoSett07gAgWhQTmAM4KNNcpg9pAhv1t1HhydGgAAxJ2VPEggciiYq1kHgr9R4Ps0g00BISdAAYRxijQrDXHUsaH+GBVIGNinmnE0GOXeC8Olm+KrhVlfk6T-ndld0JQlHmpeChPwxAS2kxMoOVyz22tNGBS6rQTF1bWQRQ2eLwXvK-nbBtnUrtheK+zISQPmRQNOA-1oSWqdEfjxBwM7PBIIK6CauqqCjWrsjhKWNuERPOkXhRMErkhQy2pHIBlxNTUnMXkJJJIpKpJpKCiwutLcVtK3JZN9LZM1NcgDE5B5PZj5JbAFL5mFKTPKmDKlNyPYuQppyjMrP8tFAlFVI2yLIZq3QcMNONMqRonNNKOIzXMjJUMJvpv9PGmDIyOpo-W9P5gdIFopsllvIdlZtlLeL8quu5sCsLKUo1KBm+lTKctgi-LwU5sNutnzN1iLIShLOxtNB4ttpzPtsTBrJ0rLzcoeo8qOi8peshVNANrkodt5tNCmBZBLFCvCvOkipRQtFisaBjhwKyvQP1ISqzpyqNTygQgKu7NNFqrKoquQSqrKRqvQBKvqrJkaqJyBpape0GA6v8mCJc2jWAUYD6oGqGrdqZFGpDHGqQqMx+wbOcrvi0xeuWneuk0Ctmp7y6ELThPUnkQwEsERtWsusgGCAIwFpdL+jQlgDoFSAfjwC3gPvluTN1N4hPrPrUEIGYp2ReE0jRWOEBS7u6scBOqIyOkzAuu7q5p-kPsDPvszHIW0ERJiriumrDqZHnrzP-yXpuBXqLS2g3vQC3uhvWlRM2ia2duxg7rdsgHfvK0cJAaJWeOyABS80iBexKWbqHrJm4CbsNngflIWtbI+ujuuk6XQbXqOiwZwfkOEV3v3s4wlA1rsVdEfovqvqkbQnNo5MnzkbHmfqy3IREZkAVXRyAZ-opV2MqlIfIc-q3m-qOt-qQX-peEAePV3o+pkYIjzCgdYdgfTuQE4e5UkkWqUZQbDwEY1SEZeB0eRLwdhqxBNvNGKBds6vITMZ7Uoe9puo0tvjofUl+SX2YfqGgbYarq8dcutpMFjHvGsDwUWGSoiAqCagYh2G4EMt0EcsXJAEyCAA) that tests using the interval selection domain as the bin transform extent. The logic works, but the result produces undesirable axis scaling and tail aggregation due to the semantics of Vega's binning operator, which clamps values outside the extent.

Here is [an alternative Vega spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10BOAGwBmO1APo8TBwAbSUIYEgZdFQdHEg8RhiAfVg1ACcdAF9fcLCIKCiY3UhpVjT4ZCSABmN8-MgygBti-0DSADNGxmp8WABaUQBrSWk5HPr27jSMPF0IvABPQlioKVlIbLz7PDT0GVhJ6d1QurrQU9P4pZXIQ9RWRsxxi8hkAA9CNOLEbjLYAApWqxUHRWsgAJRgADUYFQllUyABQJBYMhpDAHhqz0u6FgxQSRS2+U2F1ypPqi2WxXeeGQMlm2Lqt0YyEaRjiBJ0jPqGmoUWacXgsngASSAEYkuxLEkMG8pfskl4qklOUkaXTZkSICTSedyVBKTd5bV9czWeyDYkuVr6rjjpB5TL0HLLLBFcrOQooI7ZfK3UqVVa1TIjABdbn2Xn84pCmQivDiyXS32u92B5J+k3kyAp-ZzErdaNxJVgABUYH+nOCAHJOdXQ2AAPxgWD6GT-WPxxM+51+tOq9X08Ho1t7StWmt10PgnBi8EbCNQQezHARKPoAVQTuiiU9l0KgMDt60+kbG06i567OG6nHjVZ0lmtn4q0Pl7rzeQbcJ5V7vsBuF9lpQhEyPE9NXJC9TivR8bziY1FyfC14lfRC7RCG0mT-VMANdYDQNQzD6mwg9lUA1JkBAiUBxDSAiPDIiCz5DcY2FUVf2TXscLIvDKIIjNXTfS5czxHAlUQ8jgN0MVEOXfMP1YuN2KTGQnX3f0eKAvjqKDOTMnPIlQzyKCYPsQobladBqiEkpfnKG5Sns6zsXiXZ9juY4bVMy44OUahqAyWhaSEpkAt+Qh2AWe0SI09MuW9Tj1P7XTaIY-UoG4Yh7SFVhTzS012hZNlRLAYIZAeRp8uzdDSsgJIkhyvLz25bymV85lGlpL5ZI+L44mRYIAB0HUS-8PStYaGwAQgAXhmsBysaRowAAMhWsApsYWAADl0G2wEAmBIaRtUkTkpiSb5wMi4jLqEyiUiaILICKyxRsxyKmKD7KixB6dj2A4plQTzyVailrmKdB-MCgJrXSyAwtYCKoow9L7BitNJO0uKQsuDHcK0qi4uDIx6MQzKSuCL9fjyxDCvNSnFsqtDKbqhqadmW7SSgs5GPawrOuQbrGPeT4WkO1BjvxzSKKJzlJo2uaFoq1b1s2na9oOvAjuG6WZV4uWJsgac6MgwzjKUfKmP5Sm8giczFK7ZUUG6fAvUgCgN1YFYxSqKoTMeopBTYhMJRdnoGSgT3Gm96S-ful4HbiXLmBs6PY9XHmMrkVHdVeKh6RKnNflgNBuCod2kbBYotoAFSRxpkH+RHCH+cFIWbFu27AHAU9mfSbuM8Z7ael8inkKAq9h4oKEaABlVlkHgBJZAAJURbhGiof5htVVIpmQYb5wHsArceBZfhXMAIjMCwrF0AAmKoJ+pmPUDzWcX-YGmDCL9oKvdhuQs1J0BIAXCYDAaRBi215i8dqLcbJJy3CHaoSQEEuVSAsRuMZWTNBcnSIUBgVhgwaIQauq5GJOBcIgeShYWJxCoa4LOTJw5u1XNbehyClI-iSKw-u11ThZw4Y0GBupGJIJQskN4uN7DpxWMEKqj51i53SmDF4yAC54BKmox830vpCipIuOBEM4ioBLsgAw3AHBjCIi8AWXUQZoxeFNDRGouC0lQGAAAPl4sArj6TuLQHQSBwxzKK3mrvIM7A0isFgIgYapsnH5C5k45hj4p7BTiMEN4-w+7ggnjkvJoZEnpTSbApJ+cNTaNsZcPRDDLCWIcDI2CJioBmNiWXCuRjLixlgMCFYOxvbdKwsgPADhkB0kcUk-IOj4Z1KgAgTKcNpk+VacXDpjSbErMuPYoWUztn1BcZowJnifF+OOcwIJIS6BhNmhEyRlRomxPiZAEpByUkrLKfqNcdlPr1JDFY927V2mlyRmebZHzSnDMnmQ6eWTVRvGCFUcMYB4CPFQK3QpMhmD5LAM-MAjDEDgmKTUr5ZIKn+K0bQ5in494ikbiqNI3RqB7LJfUDJNxggIA3E3Ya35UFvGGhPVUVZkW4u5Y3He1NuECqFWAEVE4xTThJak7psz6iUu0cIselR-r7EeLSJIRDOqYDZfYDlMZ0WEFXnsFl-w2wABlLDIHQGkccyQ9WwANZUPYSAph0GXEkN4wqgyeu9Ua1kgQ6BvDACONs7rdVuS9bDJIvqfhpADXeekQb24T3xYSq6qqanqvsJq6lRZLTJE0NwbgqAI0mvAdM0h5CtxWptVYJu1ba1OpkC6t1CKQ1VprXWtN-rg3yqDF2utxrAi4vzc4Fgha0ZspLUuTRlMfllD+Qsgx8UrhUn6uwRoaLGDwEGBsRR8MLVZPxcit5Zt0qQuJC1cRo8OShsIvDZRpVi01NLeu8tnCHlBsbRU69lbKiIuRWAOa80EXBCVU2ZWS0e5gEsFQNIeApX8uVIKr0CKl2lPos1Lyr6g4QZSPSxNzK9mITkXML5kBv0nDRquyphdjhrio47ZS0jMiXtNOByA-x1YAEE0i7AWAmuKkIzn-ChOhoWWG+UoNw3KgjSKGywehAqmImnVbQkU5h7Dqmg3qaDG8cECGtNKyhLp5A1n25IbpTyxlNG0ioeAJke93NiOQRffDCRIqG7LOzMx39Tay0hDXHQ2lH6ij8ehc2uFFHORIeAH3HAKmZVVDlfTYqOBguEAZfl3+E85EkFKvZ0MmRUNMx8xcE+5In3agC6aILoaQtJFK3iOjXt5ERFKzq92SA9i9s-NIl+7VV4XpI6DMjNwRVJvDaO4W8N6OZ3JjnH9Ti2NRZ2ys1dTJ5klF3c068ayQUWKsVsg5OZXWDA6xmGJcSGv6ia2jAT2YhPADeDgLFOKJ4LBwFJvJE9A1-ZbF0Co0nLPedJX57mbXsxPcTQDcNM6niMQ29fRj4Xdt-rXVU-ZBODkLN+TcJwAKmnQrapd8xZiumE6ZL0-puhBnIFp8RUZ4zJkqIOUd3RFP9FLPO2jfdNwrubLF-DEJqPJQvZoczwRXOzi2S3ZThpgKpv046WCj70yWvvcJ199JsLMlQF+4V0Ny2U2rejWAPoYAAd4FxcDidHrbeGvtwsR3YBQfYtd-D1JiPGvI8fPLqdqa4zpuaUx7bLHVGE-Y1S-npO7sncWYY5X2w1kOBQKyGXPTZB9PIxz1XbSHvy6ea95XBv9Sm5eD9yHLu3cg9yYH8Ewfl2h5V6RwLb6KNR8x3H-HrHk-7cT0kwXkZhdxCz6FlZEvij54mXgnPXDS8DJiZzjf92oHV8V29h9STG87KmNu8vyehOECsf8MUdA-YyXOW4zHABNMsYBb8OHvx4cHxzMcABZbgIhduY-YkXvO6cPROQfYDMxCwdoKKRCITeAxgRAqVPedIQ+fDTrYrTneVHfQjQRQyFyEJURS8BbHVBXZ5SUawRCdqDIZeOPE9QgdnHfWSOMEA4hGpV4ekPZChJtAWTcCIHHSAAAYi8EkNAycQ6kaAAHl9B4BmAUZr4PZ+tdAqg6AxQH5RB68w8eDwM2NpE09x8yd4hEQr5IBLIMCgx94Mgj46BG4rAWADNrDIlkg7DsCrNkU6A+4YMlZssnYEkK9tV30pFNNwD9DtkRD1CcB-YTcksVCp909tlzDUhxZAgbCPCsCHCnDqAXC1owA3DgNPCj5NNfDA9-D7kcNgi98ccqg68ucYiY4Vh4jDcks3gH4SdTC7taR0j+oXosjKhSjIBwRHC6R8jEBXDBj3DhicjRjyi-DtNAj2JaizCFIwjINrNIi+9oi1CWiNC9DSQz8mQFguiTCk8zC+jLDijMCD5ciJiCj1pbjbD5jvDQwKjmAqiwAVifw1i7sht2EEE4g+FwVPkmj9iM48UjjB4Q8iN-N+92tYCcMnQoFes+Y1lGCGRGJMFsEQgHRXVjY6Y0ha18xLIMjXppDHwCEuC5gDDzduDBDGAlp8xRCxCAAWeAAAdgAA50AeSqT4ZOjujLjeiLCMidYTo1Ixp9ZCZ+JsCbN5omZvFfEtpdp9oBpdZRpuJZTZZ5TLoi8mR6jGjlcZ8d0eUeMeFJs99ASEpTouJSJdT8IdJx499uB2h2hS4r4xQ68Ejk9jCDtpkzS0ibiJYpZtTHSsZDYLpjZvjlSzk1TNZNSpSzoCY9SXSFT5wQjjTtkzUZk98JUbgUTrSzDbSUyHTYooz5SSYdi7o-Sm0VCuMLTg4cskgkCoAyz6pGp+5EjzjVDCzLTUF2zITWiYSID4SkdESUdYDVQa8aF6DMSl5sT4YWC2ChkRZOCiE6SZCNR+DVChDWTYiDQk19AMhTxMg2VksLcjCRTvk99riKShiUg3jxjnCpjCiXjsj7iFifCliAjpUgjXkQiNiKMoMVVwTTSRzDj6yKkkjTT7zxSBjMjZjnzvyxi8iniiiZiSi3jFjKjliALVigK6ijyGjcyIT6ixy6gTj6hhSLi7yrjEK-BsK7j7DRjXzJjpjkKcK0K8KviCKajiL1jYsqDEUlVazn1ILKKYKZCzjbz5tGL+jmLuLWKvCOLMLPy5jeLfz8L-zBLDSJgioLQIhgTcBkBXZ+FyKpLSKqLkkktUgSTBh5FIKHzNig19M7kPctjxKX5RD89LlBTWMoKcAmZbKIAjc6yJzGsSCHpnRERbydFTtmyuEnYQNyYmV7x4JuACBSTEIApnBdB2gNxS56DmA8SIM487gAgWg48Eg8BG5RMY8pgvpAhMM49Hh2BWQAAxGOV7QrdgxiDq1kOQjDR4Vg-q9c+GBIM9AAYQ5kA0-AqGZP+EJVIF9mPkQk0AaXeA0IEWoqHjtj+jWXQQegkX5QlBOvfEWHKq-FwRshpK3IELNxbUSsJQWpXwXRoUY1BPYRAsItDl4XMojjBOiqiOEge3IOgkoJbK7AlDINqsXKYMQlXImt3zmWuvkQJK+DP1uBJOBnYXJKQqshqEYwesZPF0MOTwPPYTZM5N5P5MCuzDosDOnwQqUqsLDK1PtKSkPCNkVOQ2WgTI1g1M5vLJ5vGhjJNmzNIpNOiILO4xhp3DSptKMuKD1k9BCPdM9NGWkl9PaP9PkrEUUtDO1kli5ulJ1PlljO03jNVOFq1klPVr5qzJIoOLiNlsOySpuvOrSo7NVvggjNihoiMDCtPkSPkgVpSqVuHM7PZlyh7OTzkt+sjv+sTGHOkrhONxP2opcjishvKWzAHMVoBpLNNCmBZFPCypyuBjyqZQtCKpETRtNDqpuo1r5jKuQEar9T6gWVauXNNCGsaB6ueTXKbuzEHpGqFjGtHtKtmvmt+pEsFHMsaBWs+rWqqA2sYi2pDB2vduzuSQtnCt8C9viv528kDiLNM1LrpwPSgC6F7UJJcksQwEsG3N0UXqgGCBRL1irIzJUlgDoFSFdTwAnm-sDsxgNmrL9EAbUEIHAqgIejchZWOHxRixpQ+uoQvRckzAXvQeLtQR-sgb-szCEW0BJMKuKuQAOoLvqDOtMyQKOtvsgHvr7RsmfvQFfoJpegpPFHdlju7MCsgCQYG1CKjp4VBOyDxQE0iFPW30msuDIe4FHuofzJgPI1TolGvvBiYZYcfoenYc4evhtFEcgC-pQV3HAd5oEn2BgeAdAfMZUgtsdNnNdBgcyngckpeAMZkBtSaVwYrQeWOituKSEWEZQYnjQYCbesSwehwf7I-o0ccdTIlseUElIaFiUZwAbtLhUfJSZDoZlQlAYeMR0edT0a8drQ4e2wiEJuUuJr4f9qgC7PmtCdtREb+p9okbzWkexUvwGpeEUeUcirDpMFjEKmsF+oxvzAqBZMmccpWFCovJAEyCAA) that instead scales the `maxbins` parameter and achieves a nicer result.

That said, we could consider an additional parameter to the Vega bin transform (perhaps a `rawExtent` akin to the `rawDomain` we use for scales?) to keep the VL-generated logic simple and general.

**Comment by domoritz** [comment]
@saulshanabrook asked for this as well.

**Comment by arvind** [comment]
To confirm we're on the same page, if we had a `rawExtent` property, would the Vega specification for the bin transform in the example be as follows:

```json
        {
          "type": "bin",
          "field": "time",
          "as": ["bin_maxbins_30_time", "bin_maxbins_30_time_end"],
          "signal": "concat_1_bin_maxbins_30_time_bins",
          "maxbins": 30,
          "extent": {"signal": "concat_1_bin_maxbins_30_time_extent"},
          "rawExtent": {"signal": "time['time']"},   
        }
```

And Vega's Bin operator would do the necessary `maxbins` scaling to achieve the smoother result? If so, and at the risk of saying it, this would be imminently feasible and yield simpler, more general code paths in the VL compiler.

**Comment by arvind** [comment]
A draft implementation is in #5372. It requires `rawExtent` as well a `keys` function to be exposed in vega-expression.

**Comment by jheer** [comment]
Thanks! I took a closer look at Vega and I think the simplest and most general way to support this is to expose a `span` parameter for the `bin` utility (in vega-statistics) and `Bin` transform. This parameter is the value span (max - min) to consider for bin step size determination. Previously this value was computed from the extent; if the `span` parameter is defined it will preempt the extent calculation.

In terms of Vega-Lite selection, I think this should be about as easy as a `rawExtent` parameter. (I will also update vega-util to ensure that `span(...)` returns `0` for a null/undefined input.)

```json
{
  "type": "bin",
  "field": "time",
  "as": ["bin_maxbins_30_time", "bin_maxbins_30_time_end"],
  "signal": "concat_1_bin_maxbins_30_time_bins",
  "maxbins": 30,
  "extent": {"signal": "concat_1_bin_maxbins_30_time_extent"},
  "span": {"signal": "span(time['time'])"}
}
```

Sound good?

**Comment by arvind** [comment]
That works! #5372 updated in https://github.com/vega/vega-lite/pull/5372/commits/aca93004f7fcf8ad700547ce16a6ef9f5afe2323.
