### ISSUE TITLE
Simplify releases

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5379]
As a developer, it would be great if all we had to do was push a tagged commit. Travis should then:

1) update the versions file
2) Build the TOC
3) Release the website
4) Release the schema

We will lose the ability to add the compiled bundles to the tagged commit but I believe that's not needed in most cases anyway.

**Comment by davidanthoff** [comment]
Check out GitHub Actions, might be easier for that kind of thing!

**Comment by domoritz** [comment]
Will do! I've been using GitHub actions to make releases for https://github.com/vega/scalable-vega. I have to get used to their new YAML syntax but it looks very promising (everything happens on GitHub). It would be nice to parallelize some of the things we do (run tests, linting, releases, ...).

Travis supports caching of node dependencies, which makes our builds much faster so I have to evaluate the options. I am already using Travis to make releases for Vega Embed (https://github.com/vega/vega-embed/blob/master/.travis.yml) for example and it was very easy.
