### ISSUE TITLE
Wrong data path

### ISSUE THREAD

**Issue by Eiskasten** [vega/vega-lite#5380]
I am using the latest version of Vega and Vega-Lite. Vega-Lite is unable to find my CSV file. If I run `vg2svg beer.json` the following warning occurs:
```
WARN Loading failed beer.csv [Error: ENOENT: no such file or directory, open '/dev/beer.csv'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/dev/beer.csv'
}

```
I don't know why Vega-Lite tries to open `/dev/beer.csv` which I never advised. I only want to open `./beer.csv`.
This is my `beer.json`

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "beer.csv"},
  "mark": "line",
  "encoding": {
    "x": {"field": "time", "type": "quantitative"},
    "y": {"field": "temperature", "type": "quantitative"}
  }
}
```

**Comment by domoritz** [comment]
Can you try just vl2vg? If it works, this is an issue with Vega.

**Comment by Eiskasten** [comment]
Yeah works, sorry for that, i will report that to the vega repository.

**Comment by Eiskasten** [comment]
Ok, it seems to be an issue within the `vl2svg` and `vl2png` scripts because when I run `vl2vg beer.json | vg2svg` everything works fine.

**Comment by domoritz** [comment]
Thanks for the report. We'll look into it.

**Comment by cldwalker** [comment]
Hi. I'm on osx and am using vega-lite@4.12.0. I experienced the same failure with the following spec named type-counts-histogram.json:

```js
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "type-counts-data.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": true,
      "field": "count",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```
When I process the spec:
```sh
$ vl2png type-counts-histogram.json output.png                                                                                                                                                                [1:38:33]
WARN Loading failed type-counts-data.json [Error: ENOENT: no such file or directory, open '/dev/type-counts-data.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/dev/type-counts-data.json'
}
WARN Infinite extent for field "count": [Infinity, -Infinity]
WARN Infinite extent for field "__count": [Infinity, -Infinity]
```

The suggessted workaround of `vl2vg type-counts-histogram.json | npx vg2png > output.png` works. `vl2vg type-counts-histogram.json | npx vg2png '' output.png` also works.

Interestingly enough, if I mimic [vl2png](https://github.com/vega/vega-lite/blob/60fb5192a8788e2078532efff178e9fdeb42fc2d/bin/vl2png#L9) with `vl2vg type-counts-histogram.json | npx vg2png '/dev/stdin' output.png `, the same failure occurs. It seems that '/dev/stdin' is causing the issue. Looking into this vega issue, https://github.com/vega/vega/issues/1276, it seems that /dev/stdin may be a deprecated way of conveying that the first argument is stdin and is thus causing the issue.

@domoritz Would you take a PR that fixes vl2png, vl2svg and vl2pdf with either of the workarounds?

**Comment by domoritz** [comment]
Yes, I would happily take a pull request that fixes this issue.

**Comment by domoritz** [comment]
Thank you @cldwalker
