### ISSUE TITLE
Field name doesn't accept two or more dots

### ISSUE THREAD

**Issue by juanfkt93** [vega/vega-lite#5392]
I am having trouble with field names that have two or more dots.

According to the field documentation (https://vega.github.io/vega/docs/types/#Field), _To specify field names that contain dots but are not nested lookups, escape the dot inline ("my\\\\.field") or enclose the field name in brackets ("[my.field]")._

I can do this only with one dot. The following example (**a.b**) works well in the Vega Editor:

```json
{
  "data": {
    "values": [
      {
        "color": "default",
        "a.b": 28
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "color",
      "type": "nominal"
    },
    "y": {
      "field": "[a.b]",
      "type": "quantitative"
    }
  }
}
```

However, I can't get something like **a.b.c** working, neither with
```json
"y": {
      "field": "[a.b.c]",
      "type": "quantitative"
    }
```
nor with 
```json
"y": {
      "field": "a\\.b\\.c",
      "type": "quantitative"
    }
```

Is this how it is supposed to work, or is this a bug? 

Hope I was clear, thanks!

**Comment by fgario** [comment]
I have the same issue

**Comment by domoritz** [comment]
I'll take a look. Can you make a small example and illustrate what doesn't work?

**Comment by juanfkt93** [comment]
Thanks @domoritz! 
Well, for example the following doesn't render a bar, like the first example.
```json
{
  "data": {
    "values": [
      {
        "color": "default",
        "a.b.c": 28
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "color",
      "type": "nominal"
    },
    "y": {
      "field": "a\\.b\\.c",
      "type": "quantitative"
    }
  }
}
```

I also tried the following, with no luck. ```json
"field": "[a.b.c]",
```

**Comment by domoritz** [comment]
Ahh, looks like we only replace the first `.`.

<img width="435" alt="Screen Shot 2019-09-18 at 13 35 47" src="https://user-images.githubusercontent.com/589034/65183896-45b46a80-da19-11e9-8178-7e4903e24c6b.png">

```js
> 'a.b.c'.replace('.','\\.')
"a\\.b.c"
```

We need

```js
> 'a.b.c'.replace(/\./g,'\\.')
"a\\.b\\.c"
```

**Comment by juanfkt93** [comment]
Great, thanks!

**Comment by domoritz** [comment]
Thank you for the bug report.
