### ISSUE TITLE
[docs/embed] vega-lite@4 is not shortcut  for the latest pre-release version

### ISSUE THREAD

**Issue by tmori3y2** [vega/vega-lite#5401]
# Embedding guide should be fixed for pre-relese version

The latest notation for beta is wrong.

NOT CORRECT #5347 for pre-relese version

The following topics need to be fixed.

* CDN
* NPM
* Requiring Modules (Observable) <= New Topics !!

----

# Related topics to consider this issue
## npm install

Related Contents: [npm-install](https://docs.npmjs.com/cli/install)

### npm install [\<@scope\>/]\<name\>@\<version\>

vega-lite@4.0.0-beta.2 does not match vega-lite@4 because it has a pre-release Identifier.

MATCH: 4.0.0, 4.0.1, 4.1.0

NOT MATCH: 4.0.0-beta.2, 4.1.0-rc.2

```
>npm install vega-lite@4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vega-lite@4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### npm install [\<@scope\>/]\<name\>, npm install [\<@scope\>/]\<name\>@\<tag\>

```
> npm install vega-lite
```

is same as

```
> npm install vega-lite@latest
```

Related Contents: [npm-dist-tag](https://docs.npmjs.com/cli/dist-tag.html)

The latest vesrion depends on whether it is marked with the latest tag, regardless of stable / unstable (pre-release).

---

# Usage > Embed > [Embedding Vega-Lite](https://vega.github.io/vega-lite/usage/embed.html)

### NOT WORKING

```html
<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@5"></script>
```

### WORKING

```html
<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@5"></script>
```

or

```html
<script src="https://cdn.jsdelivr.net/npm/vega@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@latest"></script>
```

## NPM

```
If you prefer to host the dependencies yourself, we suggest that you use npm to install the libraries (Vega, Vega-Lite, and Vega-Embed) to 
get the latest stable version. To install with npm, simply install it as you would any other npm module.
```

NOT CORRECT: to get the latest stable version

CORRECT: to get the latest version

vega-lite@4.0.0-beta.2 is unstable (pre-release) but latest.

## Requiring Modules (Observable) <= New Topics !!

Related Contents: [Hello Vega-Embed](https://observablehq.com/@vega/hello-vega-embed)

```
embedLatest = require.alias({
  "vega": "vega@5.6.0",
  "vega-lite": "vega-lite@4.0.0-beta.2"
})("vega-embed@5.1.3")
```

or

```
embedLatest = require.alias({
  "vega": "vega@latest",
  "vega-lite": "vega-lite@latest"
})("vega-embed@latest")
```

"embedLatest: 5.1.3, Vega: 5.6.0, Vega-Lite: 4.0.0-beta.2"

**Comment by tmori3y2** [comment]
It may be a good idea to change the next release version to a version without pre-release id such as 4.0.3 so that we can use vega-lite@4.

In that case, there is no need to modify the document.

In fact, it seems recommended to keep the latest tag on vega-lite@3 and to add the beta tag to vega-lite@4 so that users can continue to use stable version (vega-lite@3) by default.

**Comment by tmori3y2** [comment]
Because we can use the stable version (vega-lite@3) at any time, so, if I can use the vega-lite@4, no problem vega-lite@4 is latest, I think.

**Comment by domoritz** [comment]
Thanks for writing this up. We're hoping to have a v4 release soon and we will consider following your suggestion for the next major release.

**Comment by domoritz** [comment]
Vega-Lite 4 is released so this issue is resolved. In the future, we plan to have faster turn around for new versions.
