### ISSUE TITLE
Boxplot mark does not respect explicit scale domain.

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#5406]
Given a [simple boxplot spec with explicit scale domain](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgYATgGtsYYJDwBPQsn2R23AB6Ex3PJAC+6iJAAm6PJhyHWWsQt8IhJyKloGZjZOHiFaEU9vWGQ8WFJE9FJUbgpGZFh5RRUXDUhkJXhud0Ylan1QCDdreo1GqAAzPLF3CwBJAFkAEQAhAH0AJS8autc2qBMzCwBHVnQlPGYpqjVWxsgEdDFzXw9uDBr9AG0ARlUwa4AGAF0nXdeIV6cgA), Vega-Lite does not respect the given domain. If I add `zero: false` the scale then behaves as desired; however, this is not necessary with other mark types (e.g., trying changing the mark type to `tick`) and so is inconsistent.

It appears that the boxplot mark does respond to explicit domains in general, except for the application of the `zero` flag.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5411
