### ISSUE TITLE
Set default background color to white

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5442]
* Guarantees that charts are legible on any background
* Marks charts usable on slack and twitter (the default background isn't good)

**Comment by davidanthoff** [comment]
Yes, that would be great, I'm running into problems with that constantly!

**Comment by gordonwoodhull** [comment]
Stupid question: how do I override this to restore transparency? I tried `background: null`, `background: undefined`, `background: 'none'`, `background: {fill: 'none'}`, `background: {opacity: 0}`, etc.

Everything causes the background to go black or white.

The [vega-lite docs](https://vega.github.io/vega-lite/docs/spec.html) point to the [vega docs](https://vega.github.io/vega-lite/docs/spec.html#view-background) but the object form doesn't seem to be accepted, only strings?

**Comment by domoritz** [comment]
`background: 'transparent'` works for me.

**Comment by domoritz** [comment]
We should be accepting the object form. Good catch.

**Comment by gordonwoodhull** [comment]
`background: 'transparent'` is much cleaner than the alpha-zero colors. Thanks @domoritz!

**Comment by domoritz** [comment]
Actually, the object notation doesn't seem to be support for the object notation of colors. 

See https://github.com/vega/vega/blob/e3efe7b76924baa939e1a115275067bc35e60556/packages/vega-schema/src/background.js#L3

@jheer is this expected?

**Comment by gordonwoodhull** [comment]
I was confused between the top-level background property and the "view background", which does have an object form. The docs are clear now that I understand the terminology.
