### ISSUE TITLE
Graph suddenly renders 16,000 pixels wide

### ISSUE THREAD

**Issue by rgrannell1** [vega/vega-lite#5462]
Hi,

I suddenly ran into a problem with a graph that previously worked; it rendered as ~16,000 pixels wide. I'm unsure how to fix this, but this occurs with the most recent version of vega.

How do I fix this? Is this a problem with vega, or just the embedder? If it's the latter, is there a way of attaching `vega-lite` graphs without using `vega-embed`

---

Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

## Example

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAZ5I9sjz0AnHQBWsbgDtIAGnBQAJulXYwoCBEgV0Y1sliWA2sZtWPnqKm7cTS0gAEWR4ZF08Q29PSDwAT0JkINgIkxE-AOifG0hGQJwQsIi8MABGAFYAdjkytQAmMrkKsoA2AGZsnKg8RlRnVVRCS0qausbmtvaYsABfIxzrbryCqFDwyPLq2oay+orpBq6cuL6B9CGR7fG9g4aF5czVoo2oh5OEpJS0jP9AmfmMyWJ3yQXWJS2Y129VadTUxx8p36sEGwxwox2jRhcPeiKeYOKkQRsU+yUKqV06XxANxEGBiN6yNRVyhWKqo1puXxhXBRM5tlJ30pvyy-KgoJ5hNKGJu9XZ1UgNKBM1sErWUshmL2VQarWJuUZ50u6Ou0J1MLFkG56te+oFiTJUApVL+ipygMWKp6ZxRFzRmtlAA5pNJ6pbrS8Snaeg6hS7RV6VgTXgHocHQ26fB6fPTYhHeW9E4LyT98Za1ZHNjLoWo5GoKtGkUb-dWsbX60rPd1xc8C6m21UOo3Db7jf29mpB+1w67JbbLcWnaXXZ2c0WfcyTaz6vVJ7UZ1k51GF7GS8Ky4mK33Wzu92VM55s55cwaN36WZj6u0OmVAwfe1Kw6nku56uuWAEpje37tL+D42E+NgvvaXxnvGgTgcmEJQVUMHSMOb5jthuH-phRKrs+l4QVhpo7lUhy1PhTLvlun50bWZQkUefJFsBkDOiK-zupySE9qR0o0fUgZlHseELgRLYSVJMmcTax48ShIFoXBEAIXSib5oBJ4aXxy4Jt2SZceJNS7nU7TSO0FTwnJTGEdsNlqHZDlqORiGUWJmruR0u6yeuLkKdZah1EFajSCplaFuZi4maBWQ+Xp5kVgAkroYCEOgjA5Ri7RyIOjkeU5oXNh+xWlWo5VxdluX5foRmOslWlpV4iXydVJWtK0NRyHIDU5XlBVAcZ-EXhlzyNWNhXbDV-WDXI2lzMJlWjuFcg1WogZ7Y0I1NeNrVxgJjZZaNzWart+2Bo0a26V1yxJVNYF+YUc3XUVciBsVrQHA2zlVSxxV-XIAPSBUR3zY9G3mRGX0nepbVvWZyyXcdC01MV9aRUNIXdWFvV400cjSJ1IlxLxaPoR9UAAIJ4AATtw8A8KwsA3U0kmRUOwNbdVPP7VMcVM6z7PcJzcPKkTIPczC+zSE0cUAKK6LorCMBNqOmXTM1BOrmuMArrRK00MtdhjzxG1rpvtJFjmMfLRV7B0jtqGrGtazrZ3UkJssvT1oO-o5LRqK0MPNb7qHnRhn1XQV3OBmHUWW2ucuC6D9R1hULT1LF+mzlASMtSjfvvQbCdYzdOf1vneGU+XsfTdbQSl7XZQ1PtEfO1nnfd3VkdF4eJeJ-oTdV1AABC6AmDdVQVIG932VUfebgvS8r+0VRxbP+svTTevpxRU+QPvN3BvddWBmvAsb0VV+7ntu8j88+8x5p52T0HxOgynrRpB0S-HvOen92px3pufOel8KiAOAZ0H+Hxg6wIaHZaocUAByyBWAswcOA2mF1njYNwczBwqCvxQzXkgxEFYSF4LEJfVofMqi7nXsxJhLDdxYJwQwghx8aF5mLtAg+Hwj4pVEbQ9+MDH7MOKocIGm0H6LUDHI8mHYA5WxOBGD+p0W6VzboUC+j9BoF3aPUdhrkca3yGmY+ogjcgVmMYtfGZRvxyAsffDhRVXHuLDG-IIujm5f39lmeGhiZ4yJcXUKS35AyWO2g7GJbjWh-gCUYsBeiQkrk0RnQ+k1j7xygAAZTwMgMQYh0DMxug0aQ+1cYJOqrU+pdY4qlPKZU5mJ9fKZ2UTjesg5Dj1lAZIkk4itJFJETU6ogC6oNgcaqaR88MTK1-A5IaeovFWPJtJP6FQNkjP4RI7p6VHjCKCYlcZkCz7OJqKs4MrDVGNJYvcoBklWgLNEhk5Z2wgqANhIA55mo-nSABYXBG5zMnBIgaEx84TkF-2BTMuo9l-EQtHiIo5EyoG3IhsimK5iTnPTEQU45kzrzbEXtJCO7QU5AoxFSqKtLobpNUmRXJp8zkYoLFi65ET4qaipTnVotRNlKO8ZS-OENRWfIsmyqydZ7plFWXZel2wDrKuknZOKPKskwpyVmbwABdYw2YrRVIANZBGZmEBKUAADu+QWCWGKsNYwkAUCMGoPgSwOc3W2AiPAAIBVqCWHpJAeIYaZiQAAGaMHKc8VuYzjK6G4KgAq+DOR8W4MzKIOB3DmXaRUqpjYABiBVkiWl1YmehZCxCNgucsW22tLSl0bOLNmHMXAzBNXC7wkAAAeUaTjsHGjgFmTgs2GgAKq6GYEEPwkREBmDKfqWN8axDPBHMyKdvEylDBzfg7wCFIBBrEDm4diJ0DUGoDa2gq7ChBtYNxE4caE0LoMbEBADhHTAEgGQ3Q1BHSuEgGAAAxDG5AMaygxrvlAcDMb4CDnQDGyARqnrU2MgAR1YOgSIzBzCMCoHBWYpqQCzCAA

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
You have to pick between binning or time unit. [This solves the issue](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAZ5I9sjz0AnHQBWsbgDtIAGnBQAJulXYwoCBEgV0Y1sliWA2sZtWPnqKm7cTS0gAEWR4ZF08Q29PSDwAT0JkINgIkxE-AOifG0hGQJwQsIi8MABGAFYAdjkytQAmMrkKsoA2AGZsnKg8RlRnVVRCS0qausbmtvaYsABfIxzrbryCqFDwyPLq2oay+orpBq6cuL6B9CGR7fG9g4aF5czVoo2oh5OEpJS0jP9AmfmMyWJ3yQXWJS2Y129VadTUxx8p36sEGwxwox2jRhcPeiKeYOKkQRsU+yUKqV06XxANxEGBiN6yNRVyhWKqo1puXxhXBRM5tlJ30pvyy-KgoJ5hNKGJu9XZ1UgNKBM1sErWUshmL2VQarWJuUZ50u6Ou0J1MLFkG56te+oFiTJUApVL+ipygMWKp6ZxRFzRmtlAA5pNJ6pbrS8Snaeg6hS7RV6VgTXgHocHQ26fB6fPTYhHeW9E4LyT98Za1ZHNjLoWo5GoKtGkUb-dWsbX60rPd1xc8C6m21UOo3Db7jf29mpB+1w67JbbLcWnaXXZ2c0WfcyTaz6vVJ7UZ1k51GF7GS8Ky4mK33Wzu92VM55s55cwaN36WZj6u0OmVAwfe1Kw6nku56uuWAEpje37tL+D42E+NgvvaXxnvGgTgcmEJQVUMHSMOb5jthuH-phRKrs+l4QVhpo7lUhy1PhTLvlun50bWZQkUefJFsBkDOiK-zupySE9qR0o0fUgZlHseELgRLYSVJMmcTax48ShIFoXBEAIXSib5oBJ4aXxy4Jt2SZceJNS7nU7TSO0FTwnJTGEdsNlqHZDlqORiGUWJmruR0u6yeuLkKdZah1EFajSCplaFuZi4maBWQ+Xp5kVgAkroYCEOgjA5Ri7RyIOjkeU5oXNh+xWlWo5VxdluX5foRmOslWlpV4iXydVJWtK0NRyHIDU5XlBVAcZ-EXhlzyNWNhXbDV-WDXI2lzMJlWjuFcg1WogZ7Y0I1NeNrVxgJjZZaNzWart+2Bo0a26V1yxJVNYF+YUc3XUVciBsVrQHA2zlVSxxV-XIAPSBUR3zY9G3mRGX0nepbVvWZyyXcdC01MV9aRUNIXdWFvV400cjSJ1IlxLxaPoR9UAAIJ4AATtw8A8KwsA3U0kmRUOwNbdVPP7VMcVM6z7PcJzcPKkTIPczC+zSE0cUAKK6LorCMBNqOmXTM1BOrmuMArrRK00MtdhjzxG1rpvtJFjmMfLRV7B0jtqGrGtazrZ3UkJssvT1oO-o5LRqK0MPNb7qHnRhn1XQV3OBmHUWW2ucuC6D9R1hULT1LF+mzlASMtSjfvvQbCdYzdOf1vneGU+XsfTdbQSl7XZQ1PtEfO1nnfd3VkdF4eJeJ-oTdV1AABC6AmDdVQVIG932VUfebgvS8r+0VRxbP+svTTevpxRU+QPvN3BvddWBmvAsb0VV+7ntu8j88+8x5p52T0HxOgynrRpB0S-HvOen92px3pufOel8KiAOAZ0H+Hxg6wIaHZaocUAByyBWAswcOA2mF1njYNwczBwqCvxQzXkgxEFYSF4LEJfVofMqi7nXsxJhLDdxYJwQwghx8aF5mLtAg+Hwj4pVEbQ9+MDH7MOKocIGm0H6LUDHI8mHYA5WxOBGD+p0W6VzboUC+j9BoF3aPUdhrkca3yGmY+ogjcgVmMYtfGZRvxyAsffDhRVXHuLDG-IIujm5f39lmeGhiZ4yJcXUKS35AyWO2g7GJbjWh-gCUYsBeiQkrk0RnQ+k1j7xygAAZTwMgMQYh0DMxug0aQ+1cYJOqrU+pdY4qlPKZU5mJ9fKZ2UTjesg5Dj1lAZIkk4itJFJETU6ogC6oNgcaqaR88MTK1-A5IaeovFWPJtJP6FQNkjP4RI7p6VHjCKCYlcZkCz7OJqKs4MrDVGNJYvcoBklWgLNEhk5Z2wgqANhIA55mo-nSABYXBG5zMnBIgaEx84TkF-2BTMuo9l-EQtHiIo5EyoG3IhsimK5iTnPTEQU45kzrzbEXtJCO7QU5AoxFSqKtLobpNUmRXJp8zkYoLFi65ET4qaipTnVotRNlKO8ZS-OENRWfIsmyqydZ7plFWXZel2wDrKuknZOKPKskwpyVmbwABdYw2YrRVIANZBGZmEBKUAADu+QWCWGKsNYwkAUCMGoPgSwOc3W2AiPAAIBVqCWHpJAeIYaZiQAAGaMHKc8VuYzjK6G4KgAq+DOR8W4MzKIOB3DmXaRUqpjYABiBVkiWl1YmehZCxCNgucsW22tLSl0bOLNmHMXAzBNXC7wkAAAeUaEXIAAKq6GYEEPwkREBmDKfqWN8axDPBHMyLNSUylDBzfg7wCFIBBrEDm4diJ0DUGoDa2g87ChBtYNxE4caE1ToMbEBADhHTAEgGQ3Q1BHSuEgGAAAxDG5AMaygxrvlAQDMb4CDnQDGyARqnrU2MgAR1YOgSIzBzCMCoHBWYpqQCzCAA).
