### ISSUE TITLE
The background color should only be set in the config or at the top level

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5466]
We are currently setting it both at the top-level and in the config that is part of the compiled spec.

**Comment by domoritz** [comment]
@kanitw Which one do you think we should do?

**Comment by kanitw** [comment]
Depending on where users specify it?  

- VL top-level -> Vega top-level
- VL config -> Vega config

**Comment by domoritz** [comment]
I'm talking about the default VL config. Where should that go? Probably in the VG config.

**Comment by g3o2** [comment]
which one wins in case of conflict?

**Comment by domoritz** [comment]
The top level property.

**Comment by domoritz** [comment]
We introduced white backgrounds in https://github.com/vega/vega-lite/issues/5442.
