### ISSUE TITLE
Chrome not rendering marks in vega-lite editor

### ISSUE THREAD

**Issue by lelandwilkinson** [vega/vega-lite#5478]
Using Google Chrome browser (up to date and refreshed)
Version 77.0.3865.120 (Official Build) (64-bit)

This picture shows the problem. This example was taken from 
https://vega.github.io/vega-lite/examples/point_2d.html

Works fine in Safari. Same problem rendering SVG or Canvas

![image](https://user-images.githubusercontent.com/19478753/66932705-a1b0e580-effd-11e9-88c3-741934998087.png)

**Comment by domoritz** [comment]
The example at https://vega.github.io/editor/#/examples/vega-lite/point_2d works for me. Can you try to clear your cache with SHIFT + CMD + R?

<img width="438" alt="Screen Shot 2019-10-16 at 08 56 26" src="https://user-images.githubusercontent.com/589034/66936624-e1260480-eff2-11e9-83c0-efeebc93ed7e.png">

**Comment by domoritz** [comment]
It was probably some version mismatch in a cached version of some file on the page. I'm glad we could resolve it. 

Happy plotting!

**Comment by gordonwoodhull** [comment]
I have found that sometimes my last-edited spec gets "stuck" in the editor, so it's not parsing/viewing the same thing I asked for. 

In fact, this happened to me when clicking the above link - I got parsing errors on a spec I was looking at earlier and the page didn't display at all, due to an error in error handling.

You can clear the editor state in DevTools Application/Local Storage. Select "redux" and press <kbd>delete</kbd>

**Comment by lelandwilkinson** [comment]
Nope. I even tried "Clear Site Data"  However, going back to 
https://vega.github.io/vega-lite-v1/examples/ <https://vega.github.io/vega-lite-v1/examples/>
and clicking on the scatterplot example launches
https://vega.github.io/vega-editor/?mode=vega-lite&spec=scatter <https://vega.github.io/vega-editor/?mode=vega-lite&spec=scatter>

and it renders just fine. But if I click on the "new editor" link at the top of the page and paste in the same JSON, it fails to render the marks again.

I think you're right that it has something to do with caching, but I'll have to investigate in more detail.

Thx,
L

**Comment by domoritz** [comment]
That's odd. Can you try to open the editor in incognito mode? You can also go to https://vega.github.io/editor/#/reset to reset the saved state.

Could there be an extension that blocks some data (such as an adblocker)?

Can you try to open https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxgSFZdMWwtCtIC33lFFQBfdQhIDF0AawbIAI88Ep7kJXhuTQ9qBtAIHoAPBcgUxmQxTSGACXS-ANdbNSg8AE9YoYBHVhCjPGtGKkgujR7ztY2tndMAWUiOgA+rFdECAOLoBLKU6QC5XUy3e7MJ4vDoadHooA directly?

**Comment by lelandwilkinson** [comment]
That link opened with the same problem. I don't have an ad blocker. I'm going to take a look at what might have changed, because I've used the editor with no problems as far back as last April and as recently as June 20 (perhaps even through September).

L
