### ISSUE TITLE
Quick start guide, tutorial

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#548]
We need a simple tutorial for how to use vl. Users shouldn't have to read the code to figure it out. 

This is about how to use vl (what functions to call with what inputs/ outputs) and **not** the format of vl. That's a different issue.

**Comment by amitkaps** [comment]
Yes this would be helpful. Including having vega-lite.js available in the repo without needing to compile using npm. Here is the bare minimum html file to get vega-lite working in a webpage

```html
<!DOCTYPE html>
  <meta charset="utf-8">

  <script src="../lib/d3.min.js"></script>
  <script src="../lib/vega1.5.js"></script>
  <script src="../lib/vega-lite.js"></script>

  <div id="vis"></div>

  <script>

    function parse(spec) {
      vg.parse.spec(spec, function(chart) {
        chart({el:"#vis"}).update(); });
    }

    var vlspec =
      {
        "data": {
          "values": [
            {"a":"A", "b":28}, {"a":"B", "b":55}, {"a":"C", "b":43},
            {"a":"D", "b":91}, {"a":"E", "b":81}, {"a":"F", "b":53},
            {"a":"G", "b":19}, {"a":"H", "b":87}, {"a":"I", "b":52}
          ]
        },
        "marktype": "bar",
        "encoding": {
          "x": {"type": "O","name": "a"},
          "y": {"type": "Q","name": "b"}
        }
      }

    var vgspec = vl.compile(vlspec);
    parse(vgspec);

  </script>

```

**Comment by kanitw** [comment]
Thanks.  By the way, we include compiled vega-lite.js in our [releases](https://github.com/vega/vega-lite/releases). Including compiled files in the `master` branch makes pull request unnecessary lengthy so all vega projects do not include them.

Also, FYI, starting from 0.8, we will update the releases page with changelog for each version.

**Comment by kanitw** [comment]
@amitkaps   I'm putting your example as a placeholder in our [Documentation page](https://github.com/vega/vega-lite/wiki/Documentation).  We will write a more detailed documentation after finishing some high priority issues.

**Comment by amitkaps** [comment]
Thanks. It took us half a day to figure it out. Also, this only supports embedded json data and not url json for data. Also, the stat part is ignored in this trivial example but would need to factored in for larger data urls.

**Comment by kanitw** [comment]
@amitkaps Yep, we are aware of that and will try to have a proper documentation within a few weeks.  
We want to make stats optional for both cases after migrating to vega2.

**Comment by kanitw** [comment]
We now have basic version of the tutorial at http://vega.github.io/vega-lite/docs/index.html.
Further improvement is logged in #656, so closing this.

**Comment by QuantumInformation** [comment]
I have the opposite problem:

On the home page there should be a guide on how to use with npm.

eg I have inferred from the quick start that I need these:

![image](https://cloud.githubusercontent.com/assets/216566/23018597/7dabd098-f436-11e6-80e5-8e0cac8bc06d.png)

but what do I need to import into my js file to use with typescript and get typing?

From the quick start there is some var call vg which does the rendering, but I don't know what is being imported for that.

![image](https://cloud.githubusercontent.com/assets/216566/23018740/0e25d696-f437-11e6-9f21-0174b6dad627.png)
