### ISSUE TITLE
can't initialize selection on faceted chart

### ISSUE THREAD

**Issue by gordonwoodhull** [vega/vega-lite#5483]
By the title alone this sounds similar to #5120, but it's a simple multi selection on a single chart.

My app allows switching between stacked bars and grouped bars (row facets). When switching, there may be a selection already active, which is applied via `init`.

When the selection is restored on a stacked bar chart, it comes through correctly:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/1366709/67306543-251e7b00-f4c5-11e9-8874-1f3bfc12cd3d.png">

[(editor link)](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhOtRpAMYD2AtgA6wBOhZkxhuQg3gBLJgDsAjJAA0VOlHgBPNj1SQAcgEEASgGEA8gBUAknoDKs+XUZN84+GQAcAThfWIAXzkLaC2+xcalD8gsJiUlYKmMqqvHo6JgCyJtoAMmAAIlpJWgDiAKJR0bb2jqiuAGweYN41fjbMgdy8oUKiEtI+JbHBkEYAEgUAYkbF-sxlZABM05IALDV1vjWYTRwt6m3hneM2vbwAQlpGRgU6AJp71KUOZJIA7C7VCst0DTfrQa0C7RFdq0UKj6hwAqjo8mldFduhM7HdUJVpotXrCMB96F9NiFfjtImibgd1EljAYdGAAGoFAZmNIFMCDEZjAmY+HlMDzACsTiWLIxa1YGz62w6+MBkCJUAMw2GBQ05npqQpBjSFNSeTAehpaUyOjl11ZU1Qbl59XFWOFuNFAOiQLi6kyBT0BQACqYqWAXTotHpTM6DQKjWAAMwuB6mla2gJCn5ha0Bu19HQGQ6Hc4w81ssic+bBiPvTPNS1x-4JiXA3haczmLSgtLMzNB3PTfPUflQC2xv67FkxCvqYxDcnS2Xyoq9jtZ1Cck2os1RztbK2lifl+1QBLJVJaDJGPXmF1VyyryYIsDTAAMebnkZKi5xJZ74slkAA6gUtC6DPLKSYVSc-w0MtT3ZFxOVbdFCxjJdHzFKMXwAaRMTJtBdF11WAqcwHcG8CwXQVvhg7s4J6fsoBdUFDjSMxPQ-Z1f3-Uxv0woMHgvCCaCgwiH2Im1SPXSBUjOHRZT1DR6NfExBk9SjqL0MARzMc4WLPeYW1wtsuOxPhlyfeCyMgTckjABUAA1QR3MAj1resVPZXMOLQLTi14ssX2ogBFUEyTAKFXwYqEmKAk8sMkdiNMg-Ciy7PE+P8F8BgMFI9GQ8dGzPSQXjoN5NKi6CeNityDPMIwdyQjQ8jsshr2yvlnJi+NVxfMyFJlOUFSq1BHkc9to24nTYLi-YDK9AwSqk0Egs6sBJEkHr6qIwqmoM3RzGYkKg0kdTavnO8CO0kUV2fAyhK3bIpo2s8suoHLIr26LFtFaYioE7R9GMMxj3S9lZqca6MFuzi8v6w6JGe5aBKM7cMmyXJCmm54apuurgYO3TxHB46BMZUZptmTlwIioH7vygbiMx-SBOOU502mx4Hm25HdrhB6Cqel6QXBSFoWmzkGfm1GXLxCn+L6EkjB8qkaT0OkGSGXHLvsrkBZJkH0ZF+KDJHdrFQ0ZVVXVTVtV1fVFbIFw5qJpzBYaiINeGgTHWdN0TA9L0fT9NL8KbeYeSt3r7zJ4WOd4ZNU1ps3UFzJGAZR1W0dg+3CRW6sbIbb2zwJy2dtvFnSdBjGQ4HRlhzasdpoeB4URzvD46F9mIb6KH0gZfdD2rabgwvHCa9yuvbbBouoHfT9v3MAKAPW77zcJ3u7rztXE6HyAkJQz90Iq6b-q8OOF4T8nl4oqiaJdOj6TVRjAIRv25+Jvf67t5ehPOUS5QkqSBhk4-5MU50dGm+Y1cma50aPtB+g9G7xESMZMyFkMjWTrOnPaQZgzZ2AbXe+A9C6QPUJ5by5I-ITwutPLqN90F90wY9R+OCoCJWSqlOmaDY7M1AazIODcsZ9BKmVDCkcQwq0oWzahnDeAtW1uXPhwZwz+wWkIiBIj1CjXGkYSaV9JFMJ3iwz4YCsFJ3oC+VaU8M4-UZswkB2i2EFz0X2ASp0UjnTUSQ-hrxrAAF0qBvEgAAEmIAwAAFoQFgSB1B+PgPANgxBkAAHoolYEIAAc1gAAOniSIeAfj8AACMkliCib4gJQTYkJNgAAWlwGkwgsT5hJIvDUkpmTCCICSWFJJAArYgEhiiQEybABgABreJnB4TQF4PATgsBxDECFHcboMASAME4CINgop4gIASUwRZDA8BgH8VwRwszCDiGYNAEQ4h4lkAaJAAAHhcmokBYBXJEKQVAvVBkiBGagAAZngfgjlICfJEAID5k4pgsjXH0AAjvgCZohECiDiZAawt1IBKFuf4B5Ty0U9BEP055YBvm4F+Vbf5gLcDAvBQaCl6gNknPEHgRF5DJy4A2Vim4gh4mHOBeIfAuBcBgpwAQPogzCCorBcwcQJyVkvPFACoFvBOw0MgDS059LVy+LwMEdsmBoCsFgKcsglBbQ3ALkNKMViGVGtcROTA4yznBENUazAABiSQnzK6ZPmAmG4TrPlus+ReHggIIDuNtIDeg7LOVkG5bytV6MsHSCWEitESrODQEIJwVl9BZVkvlTosFL5lV0twJS9VghM03B1UE-VqAHVmvRqamw5rARWvFLajlBqg1QBdW6h4HqvVdt9Q8f1gbbQhuykijxsygmcD6bwHpGbZnioBec6VNwsCAoAO7lpCGMpgfS+hjImVMoIdwk3WH+b0xp26+AcAYKcldYBwoA0nVQdhERM1vt2Kuh2fQWA8tEJSwJyzUXqDwMWsFnT1AsDsPwHVG7xDkAAISEDiQ4JJeB4AIRFWAAAZDhsAyHUPwCSSwRpsAsNKFcZS7N0A8W1p-Ra6gLaJiCC4GQAl-AwWnLSR220WrExQK3C3WG+QiiAjDXfUWvA3qGD9JYcTE5+NUqgDjMY4mahjq8B4kAnggA)

However, the selection is lost when restoring a grouped bar chart:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1366709/67306617-48e1c100-f4c5-11e9-9004-c24fe830e4a8.png">

[(editor link)](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhOtRpAMYD2AtgA6wBOhZkxhuQg3gBLJgDsAjJAA0VOlHgBPNj1SQAcgEEASgGEA8gBUAknoDKs+XUZN84+GQAcAThfWIAXzkLaC2+xcalD8gsJiUlYKmMqqvHo6JgCyJtoAMmAAIlpJWgDiAKJR0bb2jqiuAGweYN41fjbMgdy8oUKiEtI+JbHBkEYAEgUAYkbF-sxlZABM05IALDV1vjWYTRwt6m3hneM2vbwAQlpGRgU6AJp71KUOZJIA7C7VCst0DTfrQa0C7RFdq0UKj6hwAqjo8mldFduhM7HdUJVpotXrCMB96F9NiFfjtImibgd1EljAYdGAAGoFAZmNIFMCDEZjAmY+HlMDzACsTiWLIxa1YGz62w6+MBkCJUAMw2GBQ05npqQpBjSFNSeTAehpaUyOjl11ZU1Qbl59XFWOFuNFAOiQLi6kyBT0BQACqYqWAXTotHpTM6DQKjWAAMwuB6mla2gJCn5ha0Bu19HQGQ6Hc4w81ssic+bBiPvTPNS1x-4JiXA3haczmLSgtLMzNB3PTfPUflQC2xv67FkxCvqYxDcnS2Xyoq9jtZ1Cck2os1RztbK2lifl+1QBLJVJaDJGPXmF1VyyryYIsDTAAMebnkZKi5xJZ74slkAA6gUtC6DPLKSYVSc-w0MtT3ZFxOVbdFCxjJdHzFKMXwAaRMTJtBdF11WAqcwHcG8CwXQVvhg7s4J6fsoBdUFDjSMxPQ-Z1f3-Uxv0woMHgvCCaCgwiH2Im1SPXSBUjOHRZT1DR6NfExBk9SjqL0MARzMc4WLPeYW1wtsuOxPhlyfeCyMgTckjABUAA1QR3MAj1resVPZXMOLQLTi14ssX2ogBFUEyTAKFXwYqEmKAk8sMkdiNMg-Ciy7PE+P8F8BgMFI9GQ8dGzPSQXjoN5NKi6CeNityDPMIwdyQjQ8jsshr2yvlnJi+NVxfMyFJlOUFSq1BHkc9to24nTYLi-YDK9AwSqk0Egs6sBJEkHr6qIwqmoM3RzGYkKg0kdTavnO8CO0kUV2fAyhK3bIpo2s8suoHLIr26LFtFaYioE7R9GMMxj3S9lZqca6MFuzi8v6w6JGe5aBKM7cMmyXJCmm54apuurgYO3TxHB46BMZUZptmTlwIioH7vygbiMx-SBOOU502mx4Hm25HdrhB6Cqel6QXBSFoWmzkGfm1GXLxCn+L6EkjB8qkaT0OkGSGXHLvsrkBZJkH0ZF+KDJHdrFQ0ZVVXVTVtV1fVFbIFw5qJpzBYaiINeGgTHWdN0TA9L0fT9NL8KbeYeSt3r7zJ4WOd4ZNU1ps3UFzJGAZR1W0dg+3CRW6sbIbb2zwJy2dtvFnSdBjGQ4HRlhzasdpoeB4URzvD46F9mIb6KH0gZfdD2rabgwvHCa9yuvbbBouoHfT9v3MAKAPW77zcJ3u7rztXE6HyAkJQz90Iq6b-q8OOF4T8nl4oqiaJdOj6TVRjAIRv25+Jvf67t5ehPOUS5QkqSBhk4-5MU50dGm+Y1cma50aPtB+g9G7xESMZMyFkMjWTrOnPaQZgzZ2AbXe+A9C6QPUJ5by5I-ITwutPLqN90F90wY9R+OCoCJWSqlOmaDY7M1AazIODcsZ9BKmVDCkcQwq0oWzahnDeAtW1uXPhwZwz+wWkIiBIj1CjXGkYSaV9JFMJ3iwz4YCsFJ3oC+VaU8M4-UZswkB2i2EFz0X2ASp0UjnTUSQ-hrxrAAF0qBvEgAAEmIAwAAFoQFgSB1B+PgPANgxBkAAHoolYEIAAc1gAAOniSIeAfj8AACMkliCib4gJQTYkJNgAAWlwGkwgsT5hJIvDUkpmTCCICSWFJJAArYgEhiiQEybABgABreJnB4TQF4PATgsBxDECFHcboMASAME4CINgop4gIASUwRZDA8BgH8VwRwszCDiGYNAEQ4h4lkAaJAAAHhcmokBYBXJEKQVAvVBkiBGagAAZngfgjlICfJEAID5k4pgsjXH0AAjvgCZohECiDiZAawt1IBKFuf4B5Ty0U9BEP055YBvm4H4E1NJgheBllwLABphKyAEt+Vbf5gLcDAr6i0MFL4NknPEHgRF5DJy4A2Vim4gh4mHOBeIfAuBcBgpwAQPogzCCorBcwcQJyVkvPFACoFvBOw0MgBy053LVy+LwMEdsmBoCsFgKcsglBbQ3ALkNKMVieV2tcROTA4yznBFtXazAABiSQnzK6ZPmAmG4frPlBs+ReHggIIDuNtIDegwrRVkHFZKo16MsHSCWEitEkAhkAHdBX0ACbAaAhBOAlqFZSgQWgzmktQBeVcFKqVaHKfE8QvBBCfP2eKVtAg0giBYGk+4DxOTEvgIIF05bOXnOnH8zVTLRkVjZQZfVXLcAuq8B42ZQTOB9N4D0qtszlUAvndbegWBAXFvVf4YgYymB9L6GMiZUygh3DzdYf5vTGnVpCBwBgpyL3hTMfQY9-6YBPIWY0wghwJnQHMCIAAXsEHuO7NGYALiW9hpY70Oz6CwCVogDSQECcs1F6g8BbrBZ09QLA7D8AtYW8Q5AACEhA4kOCSXgeACEFVgAAGSCbABxrj8AkksEabAfjShXGkaXdAPFPrNZxBqG6u5DBBBcBpT8wgYLTmjtQCpjBosoFbhbrDfIRRARJrvmZ9Qb1DB+ksLZicZrEy8BxmMWz6mkW7qoJAAJIh4mhJww+wgbBzYeJAJ4IAA)

It's possible/likely that I have bugs in my spec, but everything else seems to be working properly. (I was pleasantly surprised to see that selection does work correctly in both views, with no special cases.) 

I get the same ten schema warnings either way, and the signal viewer indicates that the selection is empty in the grouped case. (The `selection1_*` signals are also missing - I don't know what these mean yet!)

It's a minor glitch but I thought I would send it in. Hope to contribute some fixes when I get past 1.0 on this thing.

**Comment by gordonwoodhull** [comment]
For completeness, here is the expected result, obtained through interaction:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1366709/67309072-3d909480-f4c9-11e9-8c62-89d05802a26c.png">

Interestingly, the signal `selection1` is populated, but the `selection1_*` are still missing - may hold some clue to the difference for this chart.

**Comment by arvind** [comment]
Fixed with #5573.

**Comment by gordonwoodhull** [comment]
Thanks @arvind, I've confirmed the fix.

This really helps my app a lot.
