### ISSUE TITLE
Slanted error bars when data is binned

### ISSUE THREAD

**Issue by hannahburkhardt** [vega/vega-lite#5489]
When plotting error bars on quantitative data that is binned, the error bars show up slanted.
Here's a minimalist reproduction that I've tested in the Vega online editor (this is the barley yield error bar example, just that the y-axis shows binned years rather than variety):
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/barley.json"},
  "encoding": {"y": {"field": "variety", "type": "ordinal"}},
  "layer": [
    {
      "mark": {"type": "errorbar", "extent": "ci"},
      "encoding": {
        "x": {
          "type": "quantitative",
          "field": "yield",
          "scale": {"zero": false}
        },
        "y": {"type": "quantitative", "bin": true, "field": "year"}
      }
    },
    {
      "mark": {"type": "point", "color": "black", "filled": true},
      "encoding": {
        "x": {"type": "quantitative", "aggregate": "mean", "field": "yield"},
        "y": {"type": "quantitative", "bin": true, "field": "year"}
      }
    }
  ]
}
```
In this example I'd like to plot the barley yield for binned years. (It's binning only over single years, which doesn't really make sense, but illustrates the problem).
Here's the chart this specification produces for me:
![image](https://user-images.githubusercontent.com/4624654/67533586-6f4b5c00-f67f-11e9-9dc1-3b94a6d5d833.png)

Is there a way to work around this issue?

**Comment by domoritz** [comment]
Here is an even smaller example to demonstrate the issue.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/barley.json"},
  "layer": [
    {
      "mark": {"type": "errorbar", "extent": "ci"},
      "encoding": {
        "x": {
          "type": "quantitative",
          "field": "yield",
          "scale": {"zero": false}
        },
        "y": {"type": "quantitative", "bin": true, "field": "year"}
      }
    }
  ]
}
```

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6106
