### ISSUE TITLE
Applying transforms in layers breaks sorting in ordinal fields

### ISSUE THREAD

**Issue by donghaoren** [vega/vega-lite#5496]
Bug: applying transforms in layers breaks sorting in ordinal fields.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "encoding": {
    "x": {"field": "b", "type": "quantitative"},
    "y": {"field": "a", "type": "ordinal", "sort": "x"}
  },
  "layer": [
    {
      "mark": {"type": "bar"},
      "selection": {"hover": {"type": "single", "on": "mousemove"}}
    },
    {
      "mark": {"type": "text", "align": "left", "dx": 5},
      "transform": [
        {"filter": {"and": ["hover._vgsid_", {"selection": "hover"}]}}
      ],
      "encoding": {"text": {"field": "b", "type": "quantitative"}}
    }
  ]
}
```

The correct chart should order the bars by `b`. However, this is what's rendered:

![image](https://user-images.githubusercontent.com/1595237/67705827-f8f77400-f974-11e9-8909-d8a6a14eb5d1.png)

**Comment by domoritz** [comment]
You get a warning `[Warning] Dropping sort property {"field":"b","op":"mean"} as unioned domains only support boolean or op "count", "min", and "max".`. This is an instance of https://github.com/vega/vega-lite/issues/5048. We might be able to fix this by optimizing the dataflow better.

**Comment by kanitw** [comment]
@domoritz Linking to #5048 only makes it more confusing given #5048 is a confusing / ill-defined issue (that's why it's closed).

**Comment by domoritz** [comment]
Looks correct in the latest version.

<img width="1072" alt="Screen Shot 2020-08-14 at 15 52 45" src="https://user-images.githubusercontent.com/589034/90298221-34045e80-de46-11ea-900b-1b68fd521a81.png">
