### ISSUE TITLE
Share option in online editor broken?

### ISSUE THREAD

**Issue by lrq3000** [vega/vega-lite#5498]
I can't find how to share a URL with the online editor. Here is what I get when I click on "Share":

![image](https://user-images.githubusercontent.com/1118942/67740344-c05ba700-fa15-11e9-9981-fae1259bd0ab.png)

I tested this on Windows 10 x64 on both Chrome and Firefox.

Maybe I'm dumb but honestly I can't find how to make it work. Any help?

**Comment by lrq3000** [comment]
Ok found the culprit: Adblock Plus is blocking the buttons, I'm not sure why. Disabling Adblock solves the issue. It's weird that Adblock would block such buttons, they are not ads.

**Comment by domoritz** [comment]
Looks like a bug in the filter list. You can report the issue with your adblocker.
