### ISSUE TITLE
Inconsistent binning

### ISSUE THREAD

**Issue by coballester** [vega/vega-lite#5503]
The following two examples with two datasets X1 and X2 are essentially equivalent because:
X2 = 2.5*X1 + 50. The domain of X1 is [0,100] and the domain of X2 is then [50,300].
In particular,
```
dataX1 = [{"x":0, "q":0.3}, {"x":50, "q":0.6}, {"x":100, "q":0.1}]
dataX2 = [{"x":50, "q":0.3}, {"x":175, "q":0.6}, {"x":300, "q":0.1}]
```
I try to draw two respective histograms using 4 bins in each. With X1, everything is easy by setting the bin step to 25=100/4:
![visualization-7](https://user-images.githubusercontent.com/37000134/67814718-19bee700-faa5-11e9-8dc0-8e185f2aa616.png)
But with X2, setting the bin step to 250/4=62.5 doesn't work. This weird histogram is what I get:
```
{
  "title": "Example",
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [{"x":50, "q":0.3}, {"x":175, "q":0.6}, {"x":300, "q":0.1}]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "x", "type": "quantitative",
          "bin": {"maxbins": 100, "step": 62.5}, "scale": {"domain": [50,300]}          },
    "y": {"field": "q", "type": "quantitative", "aggregate": "sum", "axis": {"title": "Frequency"}}
  }
}
```
![visualization (1)](https://user-images.githubusercontent.com/37000134/67814471-6b1aa680-faa4-11e9-9b31-872784232cf1.png)

Is there a way to have my 4 bins well-positioned?

**Comment by domoritz** [comment]
How about just this:

```
{
  "title": "Example",
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [{"x": 50, "q": 0.3}, {"x": 175, "q": 0.6}, {"x": 300, "q": 0.1}]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative",
      "bin": {"step": 62.5}
    },
    "y": {
      "field": "q",
      "type": "quantitative",
      "aggregate": "sum",
      "axis": {"title": "Frequency"}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/589034/67816251-9b435480-fa66-11e9-850a-3ac8d0b2c4ae.png)

Step and maxbins cannot be used together. If you set the scale domain, you also have to make sure it is compatible with the binning. Have a look at the generated Vega code to see how we do binning.

**Comment by coballester** [comment]
Thanks, but this does not look correct. The data of X2 is ESSENTIALLY THE SAME than X1 (it's just an affine transformation of X1) So the histogram should look exactly like that of X1:
![visualization-7](https://user-images.githubusercontent.com/37000134/67836837-ec4a5b80-faed-11e9-8484-2d6cbec3b398.png)
In your example, the domain of the x-axis is not 50-300. It seems that when the lower bound of the domain is not zero, Vega scales in a weird way.

**Comment by coballester** [comment]
I mean, I think I should get this histogram:
![67836837-ec4a5b80-faed-11e9-8484-2d6cbec3b398](https://user-images.githubusercontent.com/37000134/67853027-e6fd0900-fb0d-11e9-8f84-d1d49a87bd9a.png)
If this is not a bug, can you guide me to a solution?
Thanks

**Comment by coballester** [comment]
Thanks! I see now!
