### ISSUE TITLE
Selection is not properly communicated between concatenated views.

### ISSUE THREAD

**Issue by haldenl** [vega/vega-lite#5512]
In the following spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/cars.json"},
  "hconcat": [
    {
      "selection": {
        "focus": {
          "type": "single"
        }
      },
      "mark": "point",
      "encoding": {
        "x": {"field": "Horsepower", "type": "quantitative"},
        "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "color": {
          "condition": {
            "selection": "focus",
            "field": "Cylinders",
            "type": "ordinal"
          },
          "value": "grey"
        }
      }
    },
    {
      "mark": "point",
      "encoding": {
        "x": {"field": "Horsepower", "type": "quantitative"},
        "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "color": {
          "condition": {
            "selection": "focus",
            "field": "Cylinders",
            "type": "ordinal"
          },
          "value": "grey"
        }
      }
    }
  ]
}
```

[editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIieMut4zAbQ0RQCCCoWGQxZHg8HhV9f2CoADNueFZYM0D44Mg8AE9CZDNIWEYlanDIOODHSrBnGsgMIwBrQsJuEu8XeMhkJQ9NEup0mtcAD3TIBMYwzUKACW5bZDaAd2QjNShc-MKAR1Z0JSjdKKpIOszXHImpmcKAWUZw2AB9fKMXgHF0MTFlTeyeQKOEg+0Oxx0jDOF0ukA8fw2sUuQThygGUX+SORKNC4Ui0UKSRSaS62MS0zEsxBAGEchIlJp1iSRt1tsCoIsBkofhUyTDkZAKD9WOzINQjMhrizqpkZUF+WAMllGi0QW0Omp6r1+oNhgLxvpJhSqVAFktVusAWy9gcjsxIdDSd1robbpSHk9kK93l8fn8VKotkCbeD7acCgqsvDFnrsaiGcwCViyUUwhEMTFEslUpqya43SbILT6YzbLm84CdiDOSUeSyIJHukKxCLCuLJbzLnKqnE5QBdECOIA)

Clicking on the points in the left plot does not update the view on the right as expected (the two should be identical). No errors in the console.

Funny enough, adding an `init` fixes the issue.

[with init](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIieMut4zAbQ0RQCCCoWGQxZHg8HhV9f2CoADNueFZYM0D44Mg8AE9CZDNIWEYlanC1OMzIEuZ0ysyoAAluW2RCbgB3ZCMzAEYAZgAGFwasgFlGcNgAfXyjaYBxdDExZT6ADnrgxy2wHcznesgMIwBrQvaS7xGs5CUPTRLqOtHIAA90yATGMM1C5ta7S6PVUUFy+UKAEdWOglFFdFEqJBDq8cp9vr9ChMprNuotlqsVKDsnkCjhINDYfCdIwkSiGpAPKserFRq4PEpHlE1qy2a5QuFItFCkkUmkbmyvj8xH9yQBhHISTndcW7LLgslQFqPJTLSBqvYSqoUZasTWQahGZBo3b7eJ2iD0gJHE7ncmXOEVKp3B5PF4Mj76KWY8kA0JA7pqMGkqEwuHMGl0o1BSBooMYmVYybIGZzfErNbEjWxqkJxEFJ3xRncZn+14crnC3l8ophCLcmKJZKpL18xLS2VQBVKzQq3st4vk7UlPUGyvG03my3W-WjB1Bdd2gC6IEcQA).

**Comment by arvind** [comment]
Ah, so what's happening here is that single/multi by default are projected over a `_vgsid_` field that is calculated via an `identifier` transform. In the spec above, the transform is being applied to the first view's dataset (`data_0`) rather than in the source. As a result, the `_vgsid_` field is not available in the second. 

The `IdentifierNode` is currently added as part of data parsing. Perhaps a fix here would be to push identifiers up to follow a `SourceNode` as an optimization step? Not entirely sure. What do you think @domoritz?

The reason the second spec works is because `init` automatically projects the selection over the given fields (`Horsepower` and `Miles_per_Gallon` in the above case).

**Comment by domoritz** [comment]
Ideally, we don't rely on optimization to get the correct behavior. Can you think of a way to add the identifier node earlier in the dataflow? If not, I can write the optimizer rule.
