### ISSUE TITLE
Support different cornerRadius for different rect corners

### ISSUE THREAD

**Issue by donghaoren** [vega/vega-lite#5520]
Option 1: have a struct for corner radius. 

```ts
interface CornerRadiusDef {
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
    topLeft?: number;
    topRight?: number;
    bottomLeft?: number;
    bottomRight?: number;
}

cornerRadius: number | CornerRadiusDef
```

In this case we would specify: `mark: { type: "rect", cornerRadius: { top: 10 } }`

Option 2: have separate properties with some priority order:

```ts
cornerRadius?: number;
cornerRadiusTop?: number;
..
cornerRadiusTopLeft?: number;
...
```

In this case we would specify: `mark: { type: "rect", cornerRadiusTop: 10 }`

Is there a config entry for cornerRadiusLeft in Vega? If yes what should be the right config for VL?

I don't see there is a use case for making corner radius an encoding channel.

**Comment by domoritz** [comment]
I think we should just support directly what is supported in Vega marks. Unless there is a strong reason to differ.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/5544
