### ISSUE TITLE
Bump versions in usage documentation

### ISSUE THREAD

**Issue by keckelt** [vega/vega-lite#5526]
Documentation uses vega-embed v5 instead of v6:
I think the documentation needs an update of the vega-embed version from v5 to [v6](https://github.com/vega/vega-embed/releases/tag/v6.0.0):

![image](https://user-images.githubusercontent.com/10337788/68369397-8045a400-013a-11ea-966b-83e82d076e89.png)
Page: https://vega.github.io/vega-lite/usage/embed.html

The Vega version is also 5.7.2 instead of [5.7.3](https://github.com/vega/vega/releases/tag/v5.7.3)

I'll make a PR.

**Comment by keckelt** [comment]
Please see #5527

**Comment by domoritz** [comment]
We will do this automatically with the next release. I’m planning to make one on the next few days.

**Comment by keckelt** [comment]
Alright!
