### ISSUE TITLE
Color and Shape Legends Not Combined in Multiple Charts

### ISSUE THREAD

**Issue by dovahcrow** [vega/vega-lite#5543]
This is a bug from altair-viz/altair#1785

Using the following json, the legends for the shape and the colour are not combined.
```json
{
  "config": {"view": {"width": 400, "height": 300}, "mark": {"tooltip": null}},
  "layer": [
    {
      "mark": "point",
      "encoding": {
        "color": {"type": "nominal", "field": "c"},
        "shape": {"type": "nominal", "field": "c"},
        "x": {"type": "quantitative", "field": "x"},
        "y": {"type": "quantitative", "field": "y"}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "color": {"type": "nominal", "field": "c", "legend": null},
        "x": {"type": "quantitative", "field": "x"},
        "y": {"type": "quantitative", "field": "y"}
      }
    }
  ],
  "data": {"name": "data-e9520296bae9bcaae59242382d418763"},
  "$schema": "https://vega.github.io/schema/vega-lite/v3.4.0.json",
  "datasets": {
    "data-e9520296bae9bcaae59242382d418763": [
      {"x": 0, "y": 10, "c": "a"},
      {"x": 1, "y": 20, "c": "a"},
      {"x": 0, "y": 15, "c": "b"},
      {"x": 1, "y": 25, "c": "b"}
    ]
  }
}
```

The current workaround is making shape and colour resolve independently (line 23 in the editor).

Vega editor [link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgoS8QE8Ck0gG1DEUBHtQJM0pDWxk8Xqxv3IBeHCUHuhYdg6+cEqwFqGQ1CZqBC7wsKIe4kqQIigESpQu0JAG4b4AzrTiiXJxCUlYkClp8BlZUDl5BUXeJRCQAB7V8VX1AI5a4p7I1OKquEnZhB31A8U9kCaDtS5jE6rTs-Nti-n1G4I+EOcOq7YXjlKy9Uoe83d+AbBB8CHYd72R0U2wygjXSmQWuROUEKIiUBFQ-ih2l0N3C-SBdSgO0m+2Qc1akHaUPRqIc6wx23GOJmeMOhOOLjOdyu9hZAF1ulBKDNxNVmqJMZBudMALQEACcAFYAExMaXigBsACNxBKldBxKrJeLpQxpXwABzSygMACMBoA7Aq+F1DJBJARSsp8bFShq4dUATEoB5KAREvA-Z4CeVKoLff7Ef5ePp2HaACRuzgSFw8ahqUoYAD0WbmqHEADpUFNaFolQXkLAs0mCBJc-DxCLntQCLm+AWGAWmAWAFZO+BZO3C8SlAjUUpyHxCnliqWy+XK1Xi9Wagja3X6o0m81Wm1YawlHADLBsKAbLCm08wFy80lkY9gU0ic9gWUiQr1W+chxH0hXl+mpK74uEqtqHuiF7PqQ0pAdCIFFD4bKGOcghAA)

**Comment by domoritz** [comment]
Thanks for the report.

**Comment by domoritz** [comment]
Consolidated in https://github.com/vega/vega-lite/issues/5996
