### ISSUE TITLE
TypeScript types not accessible

### ISSUE THREAD

**Issue by danmarshall** [vega/vega-lite#5550]
Hello, 
I would like to traverse a Vega-lite spec to reason about it, using TypeScript. Not all types seem to be exposed. For example, I would like to get the `encoding` of this spec:

```js
import { TopLevelSpec } from 'vega-lite';

const spec: TopLevelSpec = {
    $schema: "https://vega.github.io/schema/vega-lite/v4.json",
    description: "A simple bar chart with embedded data.",
    data: {
        values: [
            { "a": "A", "b": 28 }, { "a": "B", "b": 55 }, { "a": "C", "b": 43 },
            { "a": "D", "b": 91 }, { "a": "E", "b": 81 }, { "a": "F", "b": 53 },
            { "a": "G", "b": 19 }, { "a": "H", "b": 87 }, { "a": "I", "b": 52 }
        ]
    },
    mark: "bar",

    //no problem setting it here
    encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" }
    }
};

function getEncoding(s: TopLevelSpec) {
    //problem getting it here
    return s.encoding;  //error: Property 'encoding' does not exist on type 'TopLevelSpec'.
}

const encoding = getEncoding(spec);
```

**Comment by domoritz** [comment]
Not all TopLevelSpecs have an encoding so it is not always possible to access it. This works as intended.

**Comment by danmarshall** [comment]
So, how to access the other types of specs?

**Comment by domoritz** [comment]
You can import `TopLevelUnitSpec` from `src/spec` for example and `Encoding` is in `src/encoding`.

**Comment by danmarshall** [comment]
Thanks. Is there any way to use the types and *not* refer to `src` files? These `src` files end up being compiled in my TypeScript output folder.

**Comment by domoritz** [comment]
Hmm, not right now. We only expose the main spec type in https://github.com/vega/vega-lite/blob/master/src/index.ts. We use this to indicate that other types might disappear or change dramatically even in patch versions. I don't know whether it would be better to still export a set of useful types from the index file. I'm happy to consider a pull request for this.

**Comment by eaton** [comment]
I'm having similar challenges building a handful of customizable charts in Vega Lite; I'd love to start with a basic spec, and provide users with a handful of methods to change the data and alter (or examine) the Encoding in a controlled fashion.

I'm still wrapping my head around some aspects of the library, but it does seem that making 'encoding' an optional property of TopLevelSpec would make sense if some specs have it and others don't?

**Comment by domoritz** [comment]
It looks like encoding is optional. 

<img width="251" alt="Screenshot 2022-12-13 at 17 42 01" src="https://user-images.githubusercontent.com/589034/207460504-fc214b18-641b-4776-b811-4c01efbf720a.png">
