### ISSUE TITLE
setting "width":"container" is not working on Edge

### ISSUE THREAD

**Issue by learnwithratnesh** [vega/vega-lite#5574]
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "width":"container",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}

Above code giving strange behavior in Edge. It is expanding on each resize event

**Comment by domoritz** [comment]
Hmm, I don’t have edge. Can you try to reproduce this in another browser?

**Comment by learnwithratnesh** [comment]
It is working fine in other browsers IE,Chrome,Safari,Firefox except edge.

**Comment by domoritz** [comment]
Then please make sure to have the required polyfills to ensure it's compatible. https://vega.github.io/vega/usage/internet-explorer/. Unfortunately, I cannot help with problems in Edge or Internet Explorer.

**Comment by jheer** [comment]
It is important that we properly support Edge (as opposed to IE). Unfortunately, I don't have convenient access to an Edge instance either in order to test... That said, the newest version of Edge (slated for January release?) will be Chromium-based so this should be less of an issue in the future.
