### ISSUE TITLE
Rect mark cells have sometimes transparent borders

### ISSUE THREAD

**Issue by wildmichael** [vega/vega-lite#5596]
When creating a chart with `rect` marks, `ordinal` axes and `quantitative` color scale I get the strange effect that some transparent grid lines appear at the cell borders, but not for all cells:

![image](https://user-images.githubusercontent.com/46470/69859479-868bf380-1294-11ea-95b7-0f049bde637a.png)

See below for the JSON producing this image.

### Checklist and Sample Data:
- [X] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [X] Describe how to reproduce the bug / the goal of the feature request.
- [X] Use the latest versions of Vega and Vega-Lite.
- [X] Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "config": {"view": {"width": 700, "height": 500}, "mark": {"tooltip": null}},
  "data": {"name": "data"},
  "mark": "rect",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "z",
      "scale": {"scheme": "viridis"}
    },
    "x": {"type": "ordinal", "field": "x"},
    "y": {"type": "ordinal", "field": "y"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.4.0.json",
  "datasets": {
    "data": [
      {"x": 1, "y": 15, "z": 0.10135037039616747},
      {"x": 2, "y": 15, "z": 5.65258707356966e-8},
      {"x": 3, "y": 15, "z": 0.005624819542769523},
      {"x": 4, "y": 15, "z": 0.0028978968911497526},
      {"x": 5, "y": 15, "z": 0.0001863647640928673},
      {"x": 6, "y": 15, "z": 0.0003107288902867169},
      {"x": 7, "y": 15, "z": 0.00005697379626935445},
      {"x": 8, "y": 15, "z": 0.056530771380296226},
      {"x": 1, "y": 45, "z": 1.3150825995666335e-12},
      {"x": 2, "y": 45, "z": 0.003338745873418586},
      {"x": 3, "y": 45, "z": 0.000001594117064382551},
      {"x": 4, "y": 45, "z": 0.0000010179490199280242},
      {"x": 5, "y": 45, "z": 0.11055406959378856},
      {"x": 6, "y": 45, "z": 3.6792614894258164e-8},
      {"x": 7, "y": 45, "z": 5.938137469511175e-12},
      {"x": 8, "y": 45, "z": 0.0000011491238033670772},
      {"x": 1, "y": 75, "z": 1.6138637403156763e-8},
      {"x": 2, "y": 75, "z": 0.00017622656045297632},
      {"x": 3, "y": 75, "z": 0.08384923231216922},
      {"x": 4, "y": 75, "z": 0.005328039945279897},
      {"x": 5, "y": 75, "z": 0.006452315678699291},
      {"x": 6, "y": 75, "z": 0.012946402271808901},
      {"x": 7, "y": 75, "z": 0.23524536910774504},
      {"x": 8, "y": 75, "z": 0.00530497568350161},
      {"x": 1, "y": 105, "z": 1.7040780818167358e-8},
      {"x": 2, "y": 105, "z": 2.218037745211045e-11},
      {"x": 3, "y": 105, "z": 0.011627862189996606},
      {"x": 4, "y": 105, "z": 1.2893185496903927e-8},
      {"x": 5, "y": 105, "z": 0.003329330556082995},
      {"x": 6, "y": 105, "z": 1.09058144887414e-7},
      {"x": 7, "y": 105, "z": 0.009215578965809847},
      {"x": 8, "y": 105, "z": 0.0018584963266465794},
      {"x": 1, "y": 135, "z": 1.9965226977691554e-8},
      {"x": 2, "y": 135, "z": 0.00044086435909967834},
      {"x": 3, "y": 135, "z": 0.00560648303246627},
      {"x": 4, "y": 135, "z": 3.319758283719932e-22},
      {"x": 5, "y": 135, "z": 4.0044204497346827e-8},
      {"x": 6, "y": 135, "z": 0.008114902644327513},
      {"x": 7, "y": 135, "z": 1.7796125687494778e-7},
      {"x": 8, "y": 135, "z": 7.34124767984211e-14},
      {"x": 1, "y": 165, "z": 1.1016106972436478e-10},
      {"x": 2, "y": 165, "z": 2.949710641973666e-7},
      {"x": 3, "y": 165, "z": 0.010391287772167097},
      {"x": 4, "y": 165, "z": 0.07152136697973513},
      {"x": 5, "y": 165, "z": 0.00018809992547220522},
      {"x": 6, "y": 165, "z": 0.011440566699933203},
      {"x": 7, "y": 165, "z": 1.1029479756367246e-7},
      {"x": 8, "y": 165, "z": 0.07790988406803045},
      {"x": 1, "y": 195, "z": 7.474794959347655e-10},
      {"x": 2, "y": 195, "z": 4.6477391165125277e-10},
      {"x": 3, "y": 195, "z": 0.0038348259287524287},
      {"x": 4, "y": 195, "z": 0.0014054492489479471},
      {"x": 5, "y": 195, "z": 0.0008959712115025476},
      {"x": 6, "y": 195, "z": 7.37896556188056e-12},
      {"x": 7, "y": 195, "z": 7.266609689090038e-7},
      {"x": 8, "y": 195, "z": 0.0000040768598137559774},
      {"x": 1, "y": 225, "z": 9.684276604460179e-9},
      {"x": 2, "y": 225, "z": 0.000014830600337132322},
      {"x": 3, "y": 225, "z": 1.3046959420982602e-12},
      {"x": 4, "y": 225, "z": 0.0000010584991731210099},
      {"x": 5, "y": 225, "z": 0.000004568343655584576},
      {"x": 6, "y": 225, "z": 0.000013961180592658636},
      {"x": 7, "y": 225, "z": 5.7044117167846e-8},
      {"x": 8, "y": 225, "z": 0.04449344275484404}
    ]
  }
}
```

- [X] [Vega Editor sample](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakDsADEwDRS0Fq3WkCsLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx05AMQxU2VkiSC0Xq0OQC8HCUyPDoWKAQznBKsJJyhpFQ1ACeajbuAI5a4vCqpqq4Nr6JzigESpS2AF6QxSWQAM7Q4krpZE2c1rb4klTIDY4JYE6RkAAe5ilptrHBlkq1UGUVthMjzsmTqW2QsyEti5DLle6bgoYjkAAkHQQStjzUag0YAPSvhajiAHSoyHRaABG32QsFetwkHwIXwAtEp-gQPgBmb4AFm+TG+ACsGghan57OIGgRqANwkM7CYzFgANpDCA4CZYACMIk2LL4IhqWExzKYzKRAiRzCRAE4AGzM8UMVEMdaRRmkABMbNIzM5UG5YD433FfCVfAAHMwGILxRLxQQYYb5QzxqQkaqOVzSJiWHxxUrUYbmaK+KilQxzfqkbayEywKinWB1S6eRimErDaKGMnxcnmczUSn9eKw4qsBrIOyY0WtW6WMzDeKkeLZXWmKKk9LQ3VEgWwOLo7HNa6E0wkXyGEnk4nqwwpaL8-asAxu2W+yx3ebTQwJUrzYLUai+NOI4b53GwG6PXwkUwGBOkYbE+uN3u1dGd0fmd9BwJDQbRX7xb+kYKrWZJUHywFUoBLZ9e3jFh-2vGUjVNVEqyNPM2wVGcwEdcDSEgyBy37Ss+FFJDmWYOtrwNPhmRAyMnwXaCl35fk12zflvyTRMAxoosIPo49vkzJg+H9Jhg1FYVDUND0aK7bCsFwrUUWlJtJW9YiDR9OsrRtNC7QjOc5MjPidXEn1hVRYNM1IvhAOA3Tw1IA9DIUxdGMzbMgOvAdaxNYcaNZQyGD419JWvGsZQHdVpRrbSaLA4tGD4itmM9DcPSYHclRTGs7PpBysCwhLZySjFDWvbMlSRSqgMnJVcpKfLaMCkr3Sqm8xWI-U12TOV7I7HjEqPCs6xDKLU3NJtRWovqMNkoqwCCoaMSA4iGzqicb1Haa8o7Az5sWqD+Mq-Ud1rKaL3gjKaKc-aWqE89syC9NBX5SV-O7ISX2+ZhUQvTaqylU0jVimaI3iks+T4pVviVKsB0vTLBJ3QDtoajtCohz7DrdTNPXG2Hk2-X9RJoqNDMhr6k3E5Ds3NAcmwYEGdowgaWSxvDXP-LL-yE9LP2-XdQdIObMeCjFRSEn1t0kmUsytXrmf0j67qbdU+FTCUjUbQ1ZWu5WlsrKSdYlKrfws9XiPe8nBS+on9Q3FMgym4TUSZtGMPBtUbex-ttyYatUUFCWidTJFURojGvbu9K6zKgcvV-QNSe7b2OYKt9fSCz8yonb8qqtOruJTvj0RYbclQyx6w-TQM3ZKDsRajg3-fciWN23KqgoFGi9oh1OtVfS8JSAj1jWzWVU3lvXrb4hg3yQr0g26gNM0A8OhZZbs9S+vkpT5FcvVrWVDUApg4q3qHvmIlN96QlNa1-KeN8wi+Db5MUgONS9YelRsFfdiMZN5pShahOfUApfwpnvlRVsit+Cvx9kuKsN5vxNn9MOCu9sZIILTvxfkWZfoekgXnKqA4e44IHgJW8socw1mlAnJ+cCsA3QhtvRBQ9tY61Eu1DKgsmExm7H6I8c9ZQ0OzERMOQZhKn3PuTIRh10R1kvB-EBI9AyMxhHyCOgi7rXjDp+IiSYgpeiMcnORd0sxCW3E2NSYiJxF3Mc3f2fob6w3VImdBqF+GNxZPI3Bc8JKaw9MgoSlpNH1XrhhXuao-FajnhuYmEpRwSwHCfGE-9In7h0U4suF50xETMkFIiCMrbzTqnxUUuodaBmJtucUzFRRWinM-T2oEDQ5KzHHep3kryVULs-SObSxYPTEgGbWG5Ey2TMWU9piC3KS2zFNU0NUWDfgcTMu6S4dzPUDnqYSOt1ZeIAcLaM5SOliklHDQxepqy1nIYZM5h0dQ-RIhOaUOswk6X4Sw5UszcFum3NmMOAYgrej9uHIYABdC4IBBBAA)

**Comment by domoritz** [comment]
I can't actually reproduce this in Chrome on MacOS with the canvas or SVG renderer. What are you using?

<img width="821" alt="Screen Shot 2019-12-02 at 22 25 37" src="https://user-images.githubusercontent.com/589034/70025750-c67ffe80-1552-11ea-859a-0083b620f0ce.png">

**Comment by wildmichael** [comment]
I don't have access to my computer right now, but I was using the canvas renderer on Windows with Firefox and I am pretty sure I also used Chrome. But I'll check first thing tomorrow morning.

**Comment by domoritz** [comment]
I see it on my iPhone as well but not on desktop. I assume this is a browser issue that we have to control over. If you find something else, please share your insights.

**Comment by fkjogu** [comment]
I have the same (a similiar issue). Tested with Firefox 86 and Chrome 88 on Windows 10.

![image](https://user-images.githubusercontent.com/13063485/110765388-69462300-8254-11eb-8de4-02df619e6090.png)


[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlAZzAQwDYFMWgBGmUAJgAqamlxQICSUUuATigAwA0IxZl1tBAHkArgBdWHAL5TupTGMwEQUTAFt8yEPMUBaAGwAmMAE5DmABzswFzGDCGAzPscn9Adky4ALDFL7-AEZHGG8QWRA1TBYAa2UxAE8AB00QFlwwMRBuNDEWCBjcAHU4UjEAC2luXChIGjplSGwINlQQRJSUEABHERIxOEUBgDd8bnhcbFIutBTcaZysPGVSCCjaFABtLidAgDpAiwBdbg7U7FpcaPCIsQgIbAGkrdAzrt7+wYU4UeyQCamMzm0ykJxAAA94slUi16jg-phwXA0MoECxSigYDg0LgIgDploBho-kTcABVKCDLoJK4sNTQCo6XDlCAiFhoNS0cS4FERBJQzpaWG0eHcRHI1HoglY7A47jDHAiHlbQLsPaGTjeNUa9zaziqvXBQ269WcQzsPVOS36S0mbVHPFwSYEkA4hAaKBZGTcADupQqKBtXBA5VwiHKWWQjgt3AAJBhQ1EuhGxEk0MgAPQZ0YITB7BCDcoiQh7OAQDMJ3BRbO4XO6C4SbPePYWA57ABWaGgfx0mBxYhRbV7BmMZks1ls9icLjcnh8fgC+mCoRe7TgxK05sCJl0gUMukcgQAKux9MgLef2H83R7I4F3HsAKw5YEoKAibDYWSvdepLc7vcD2PU9L0va9a1vFBDAfZ9XVfZB30-b81w3EB-13fdDxPM8LwtcD3RqSNHBgl9cHmN8Py-Tgf1Q9DAKwkDcKvHIIMIlBvBIuCyIJRCqJov92G3DCgOw0C8JYgjPRQR9ONmbiKKQ6iUIEoT6OAnD2DAiTIOQDwn1I8iEMo5DSS6OjMPUsTmNdVipOQdxZPg3iTN-MzBIAizRKY-CdIsRz5KMxT+Lc1TPMYzTxJsyTIxMfzDOcpTTM3dzhIYjStKinTVTinjjMS1zktCkTwoym82OQQJ730rj4ry4LCo84r0sisq7L3HKFL45SQsatKrJ88rgg6wKuqStCUrUryIus1q7w46q5NqoLuoa1LLO87TBpkhanLqlbxqKvqNsywa9NgxbcuWsbzKa-rNrahydoChL6oO3r1umga2r8p6ltGgq3rWqbStsu9Yt+y7-toiawuambQag9hhpe-abqOz77sjQwqvO3aroBtGPpB6KoOgiHOpc6HDqJlqEeQJxkb266Ydu47Zqg+bceepmCZZ9HiZ0wxtq5v7KZU97gdpkn6bOgzIbFnqgZKqXBcekX5fyqmJeV+HpcMH71YpzXxaBwJvDuk6HvJkaFdWyazYt9n6cZ-GtdN822bp4jrZR5nqaPB3Pelzm5aN17CYDj2MctyNhdDm3jcV+2o4F8rZZqjXw7549A+jp21fj33ef93PU7sg3C55t3k8dunwcNhOs5LlOVcGpGfark2a6DrKccr12u880vW7asmG6L6uh5b3Wsu98fO6Tqfa+ls2XahweROHmetrX23Ae7vO6cCdOLrD1Hs8j5esoLjOz79iWt6+u8K9vxvz+bq-Bvr-v18Xzfp6fojXeic7ZLx7uVbGwCm4PwAZjUmUD34wM-nZBmHcB5-ywo-OB9MQ6vwnhvTBsCY5QTjngheoD-7IKxifPGv8KGEKoVBG+p83733dow+mL8WH4LcuaXQgl+E023m1PUr9gj7EMCYPe5o+ECMEpLYRd4EHM1kYEQRCjAH01ESw+8hg9jsG8I+fQxiTGmMfNI9gqj1E600WPH+FirHyJsdg6MpoxEmBMHsBybhTG+KkSA8ajihGaLnvYgJMj2CCOsXDTRWo3EsMMJIp8j5iLmPCZYyJcjgnYNwdw8hgTMlqKcTE7Bj5tHwWxvsJcaSs5BI0aU5RvM6nOOIbpcpAVzQwRkiYY+vjjHuAcYU6JHCaHc3QclZpJTWkmg1K-c0niDEWBqefSZHDmG0MGVE4pHCrDxIqewVsWpvCbKyfU1pXCNnpNWeAuydo9kdP1nsQx+hvD6xkmbN5AyrlDO2TcmKjTobXMPivC09zDKJL0dGEwj4LCODhfCuFxzvlbOya07KaC6EFJRWcp2lV2mGW3PoPYxiLAnKKai3FfcyHjKxaclpuLzRgoJIk9gZLhl-JQO1DFbLfnAtnvigk25WzsBMM4PpJjSXIrpVM3FoTqWYoidi+lR84mzISYYZskrak-IpSqgFAkgVlzvGUplpNHAHEMPoHluqV6kLyTSxV0qOHHwFYjZsRjHzLJUTqnFR9RmiyleS31K8Znx0CI+TxiSLB7i9U0n1yqQ36t4fGmVR9dlqoqaqYlrgEW5scLGwFKbnUXLGQqjJSrU0rzuRmgKhKnkcQ8Y2ptJgtUrKLRyiq395XWuDYLUFNbwVm2JdCiNzbG2tu9RWjhnTuWBvZXyiBWaB3MtcTCwwPaE2CypfasthqR5Y0Zcu0mEiRVjqbROuNU6O2JKTRM9tC6UGuKPZ21s7gPEFoNfeo1UE5U7o3ZWwWqqw0tqeS8s9javnaqvQ+rGuTLlQaddek1z6hX6MSR+5N0Hv30ztfBttWH91QRtKal9T52AYbvQRxRRHb20qDZuiBoaxHeHNe4IWFoOOccsf+6d6zS08evemsNhiWzYwEzBqCJaA0IfowBiB1b44uHVOR8Djae1YLRa6iqh4LXuAo3R9RGncW0cdUGozdND1htheqQ46653yPM3rEz5bTmOZ0k++OMiDjeCDFxjjdmZOGaIU7X9eHJ2ueC3TIDcykl+UEq8pZ7gPkWCRYFhzkXg7ObqW58qyHPOxacKplt6mMs6Vw-x+zOdStpy04kzxS5dR+f8yVkZWWfU5bskx9VkbTzuES8lmSjgWsdr49J-DEWdm1cqgcdgQ3KuXw7VJzO42zPVdubVpJqpAjDYk8gLtf75sdbvP2-Lj4nyvJ29h9F88HUudW86pd+XPFvpFS8z5HzIMraCw9tr2Kjucss3M7c3mPD6dM99jtXKbu7va2tu8Hm5kGK8RaDV4GL2Fr+3DzloWKtpaq866L3XiWVV6X0z74X7uQ7g7jr76XnV5Zi54iw0L81JYS+8q1h2scVXK2NinEPdsupIxCvY0LRV5vhQF2n+PIf+uW-zunkOuvwXDc9swRX0efsx860b8vL0Tch0JmLrYLAMwG2zubeOFuC6W3ffXlPBcKfcQs7w3hSd9LB3dgXV39thft97wjWiputlcJdwPM7odh+o-TR7jOWxGKa81rn07t1+4xwb3bLLhdDpSRL3NUfbF2O7cn69CP1Vqhbebgbnvsvc9QZHkvmfCcVKcKL4i-X2dJZr7D6d1O+f+8V5nhnOiPGi89bCvP3ftdId+xn7DlqtPbk8Qlgv2DLWz4d-P5XtbXd7HhRPvPq-WnQQ3wH6P+tF+77Yz08Vxj-FW-+5w0-g-59O5YUubzQseWGF7W3Eje4iUpcFcf8GMrYG80sQC5MUFF81YzZv9f8UFn9ICOEy8VdR9HBsZb8TF4DQCiIkCEDIxm8OlXErAv97NkCO0+89d08ikKDdth8KlXF9ALBNdMM5E6DsNedqCtd2CCDAxasmCbQD8JccCoDIw5c7caD+EODA9t9wUSCjAO93tUtacZDo9ddJCeDaC+DkAjcEks1nB3c+lWDKNeDcCUBbdWEB81DNE39M1zUzBfMmsgDrCdDfcadgCdCDRhcNUDglwRVHwnArBoUNVRDnV25wDVCvDY8idRUfMsDOcIDoj8DzCKpAd9C9FHx4isCTCDNLEvCi8DskjUijRhdLFiVTwEjcjwd8iSicd+8pDaixDOUiD5DtQlw89EUwiqcUjmiecBCK8VDPCSiuDNC2DtCSjiNn0rR9FoVujBcJCrDGibDsF7xF8P9Qd5irsNClitDpCvC9CW8Hxggp8zC+jDhejnU7COlQVTiJjzj3CGi9imjp0TsgcztKpydXDUiI8wlii+jsYBiDgrBOiMCtjw9U8PDviAT0ijj1RiJwTz9Ci09niVjj9UCHk9FDFDwcjETbF6juDxj9ifjWjmVLUWx808S18qCxjTD7jp0GCbj9g+sqTj9RjdiiSXjr0pjgN6ssijCTEvjlidD19Z1-jeNL8HxvBRVJEBTjFWSnYT8xSoifjDja1AiDhLcVSATLCeE6TiSATrjDJiN3BoxE8OMhjXDH8YiVchYLV4DrT8DH9YTa1o098lwEi7j9jnSnTucMSCUTBNU4V3BpSz1qivd8jH8CTaS8if9H9SSf19hDgHTucaSOT9TIzudGTwUklyM3csChTUTrdODfSRkNsHwWCyCkjH9Fi9TYzizZCNsiU9wlCO8tTPDH8di6yai4zuc1TwVTxiVzQEjEiojH9dT8keyGzo8jTmVgh9Fw1zTBIUyOFHjCSMzezwiNt9gMCbQOIlw7R9yVzIcIi-ixzuc8UfDWwPFvBhC81jzBdISnjOTNzIcXScyiUI0DlOjLThTrTkSoS-yLz-TBUQNj5DgILo0oLkzyDpzNEhplSOyLyEz6YkktRQTHBfyizrS0zuyIzXzBdsyyTWxPU2dlC3kHyrt2S8LHECKrseS48ksMKsKXy4LVjazJz8K2K0U5DBUYV1QPBKLA97xSzDcNtmwOIjEsCvTMzi1RLHdF9R8ks+t3lO9gghLo9tx5L583j9DNVYV9BVNwzaLuLFTTzi9qy68bSHlPEUklkNLbEnz1z6znT3yyT6stQkYq9DEHK18ALnyNzTKLMQKoJj4nlYpvKKLYLnToz0yXK68ULElmwbzfLj9cLOKTLnSiLEYdyDEXBOjUrFTqKMqfk6Lw8GKElBIDgzYRzCqLMOLbtMq69eKWjmzCzWKfTtLw9+zBVbz9F3BRykLp0JzGrSqgq9ZZz+Dwq9NQQZAgA)

**Comment by fkjogu** [comment]
I also can reproduce the issue with the original plot

Firefox 86
![image](https://user-images.githubusercontent.com/13063485/110765578-9eeb0c00-8254-11eb-8940-fc34024f30a0.png)

Chrome 88
![image](https://user-images.githubusercontent.com/13063485/110765638-add1be80-8254-11eb-86da-8aa2ee7374ff.png)

**Comment by fkjogu** [comment]
This seems to be a known rendering issue with SVGs as well and seems to be related to anti-aliasing. The effect is also visible for example in Inkscape. One way to fix it in Inkscape is to use the 'pixelate' filter in the rects. In XML this reads:

```
    <filter
       style="color-interpolation-filters:sRGB;"
       id="filter2415">
      <feColorMatrix
         values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1000 -500 "
         id="feColorMatrix2413" />
    </filter>
```
and a corresponding `style="filter:url(#filter2415)"`in the rect group. Maybe that would be a way to fix this in the export for SVG?

@domoritz Can you tell me, where in the pipeline the translation to SVG happens?

**Comment by fkjogu** [comment]
An even more elegant solution could be to add `shape-rendering="crispEdges"`to the rect group!

**Comment by domoritz** [comment]
The SVG Generation happens in the Vega scenengraph package in the Vega repo.
