### ISSUE TITLE
Selection initialization fails in concat charts

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5599]
Initializing a selection this way works as expected ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnChNhYA1vkgAjQZF4RINNgGMy0KmwDm+UBBmKcZLBr5aoitsvhV2GyHRo4a885dSR5OKvJHcoFWDgw1ROngaWzE-AJ5DLUgfcNFVLBoAT0goyKNIAA8reCSABwDnNjISFV8pKAAzWhxoUQBZWCY9AH0AcTlErmlolNR0XILRAEcMWDZzRHMKAK9IWFUEmlUEQuMyDAmuPnSoGzsHCw5+qJc3DwMjGUG16xVVOykomWrbaDp8AG1IRuasds6AQAuj0MioqPArL9Wh02F1nABhEo0aApThpHYgThAA)):
```json
{
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "encoding": {
    "color": {
      "condition": {"selection": "click", "value": "steelblue"},
      "value": "grey"
    },
    "x": {"type": "nominal", "field": "Major_Genre"},
    "y": {"type": "quantitative", "aggregate": "count"}
  },
  "selection": {
    "click": {
      "type": "single",
      "fields": ["Major_Genre"],
      "init": {"Major_Genre": "Comedy"}
    }
  }
}
```
![visualization (49)](https://user-images.githubusercontent.com/781659/69876925-a829b280-1275-11ea-9476-7a434614d04d.png)

However, when the same spec is wrapped in a concatenated chart, the initialization fails ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnCgoDG7AQnwBtPhFAQZUErCwBrfJABGCyL1kRINNkOhU2Ac3zTtOoTjJYzki1CFtD8KuzOQ6NHDQGv3qJACOFQCytz8sDgYNCp08DTeqtGxPPYWkBRRMSrGWDQAnpDpMmkOUAAeHvAFAA6xgWxkJEZRmlAAZrQ40CoAsrBMNgD6AOJ6+VxaDpBFqOg19SoAjhiwbK6IrhSxEZCwxnk0xggNjmQYG1wlZdqe3r7+HPMlliFhduU6i2eeRsY+TSvGSQLreaB0cSQAZDLBjCaxAC603KkCMVHgHhhI3GbEmgQAws0aNAipxgeSLJTSnxESBOEA)):
```json
{
  "data": {"url": "data/movies.json"},
  "vconcat": [
    {
      "mark": "bar",
      "encoding": {
        "color": {
          "condition": {"selection": "click", "value": "steelblue"},
          "value": "grey"
        },
        "x": {"type": "nominal", "field": "Major_Genre"},
        "y": {"type": "quantitative", "aggregate": "count"}
      },
      "selection": {
        "click": {
          "type": "single",
          "fields": ["Major_Genre"],
          "init": {"Major_Genre": "Comedy"}
        }
      }
    }
  ]
}
```
![visualization (48)](https://user-images.githubusercontent.com/781659/69876933-aa8c0c80-1275-11ea-9982-c13e1eba8409.png)

**Comment by arvind** [comment]
Thanks @jakevdp! This should be fixed by #5573 which I don't believe has landed in a 4.0 pre-release yet.
