### ISSUE TITLE
Sort not working with multi layers

### ISSUE THREAD

**Issue by nedalhardy** [vega/vega-lite#5605]
Hello,
I'm having an issue trying to sort a vega chart with two layers , it sort with the alphabetic order instead.
Thank you

`{ 
   "$schema":"https://vega.github.io/schema/vega-lite/v4.json",
   "data":{ 
      "values":[ 
         { 
            "contry":"FR",
            "count":500,
            "layerIndex":0
         },
         { 
            "contry":"BEL",
            "count":350,
            "layerIndex":0
         },
         { 
            "contry":"LUX",
            "count":150,
            "layerIndex":0
         },
         { 
            "contry":"AR",
            "count":250,
            "layerIndex":0
         },
         { 
            "contry":"GET",
            "count":1000,
            "layerIndex":0
         },
         { 
            "contry":"FR",
            "count":-500,
            "layerIndex":1
         },
         { 
            "contry":"BEL",
            "count":-950,
            "layerIndex":1
         },
         { 
            "contry":"LUX",
            "count":-550,
            "layerIndex":1
         },
         { 
            "contry":"AR",
            "count":-650,
            "layerIndex":1
         },
         { 
            "contry":"GET",
            "count":-650,
            "layerIndex":1
         }
      ]
   },
   "transform":[ 
      { 
         "calculate":"datum.count < 0 ? -1*datum.count : datum.count",
         "as":"field"
      }
   ],
   "layer":[ 
      { 
         "transform":[ 
            { 
               "filter":{ 
                  "field":"layerIndex",
                  "equal":"0"
               }
            }
         ],
         "mark":"bar",
         "encoding":{ 
            "y":{ 
               "field":"contry",
               "type":"ordinal",
               "sort":{ 
                  "field":"count"
               }
            },
            "x":{ 
               "field":"count",
               "type":"quantitative",
               "axis":{ 
                  "title":"population"
               }
            },
            "color":{ 
               "value":"green"
            }
         }
      },
      { 
         "transform":[ 
            { 
               "filter":{ 
                  "field":"layerIndex",
                  "equal":"1"
               }
            }
         ],
         "mark":"bar",
         "encoding":{ 
            "y":{ 
               "field":"contry",
               "type":"ordinal",
               "sort":{ 
                  "field":"count"
               }
            },
            "x":{ 
               "field":"count",
               "type":"quantitative",
               "axis":{ 
                  "title":"population"
               }
            },
            "color":{ 
               "value":"#ff9900"
            }
         }
      }
   ],
   "resolve":{ 
      "axis":{ 
         "y":"independent",
         "x":"independent"
      }
   }
}`

**Comment by domoritz** [comment]
The warning explains the issue here `[Warning] Dropping sort property {"field":"count","op":"mean"} as unioned domains only support boolean or op "count", "min", and "max".`

For more details, please read https://github.com/vega/vega-lite/issues/5048.

We may fix this in 4.1 but for now, this is a limitation.
