### ISSUE TITLE
Make number range in legends consistent with Vega style

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5622]
https://www.grammarly.com/blog/en-dash/

**Comment by kanitw** [comment]
Currently some of the charts look inconsistent:

![image](https://user-images.githubusercontent.com/111269/70182364-8c207980-1698-11ea-9c10-1daeec012702.png)

**Comment by kanitw** [comment]
Or use "to"  since `-10 – -5` reads confusing.

**Comment by domoritz** [comment]
Sounds good. This is an easy change.

**Comment by kanitw** [comment]
Let's see what we agree on in https://github.com/vega/vega/issues/2231.
