### ISSUE TITLE
please document the "data" format(s) that vl wants

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#566]
My use case will be producing data in another tool and then attaching that data to a VL JSON file. The question I would like you all to address in documentation is "what format does vl want for 'data' "? For instance, in a bar graph, it appears that data should be in an array, and each element in the array is {"x": "xlabel", "y":yval}, where each "xlabel" is text and each yval is a numeric value. Is this documented anywhere?

It is NOT a problem for vl to want data in a particular format. Pick the format that works for you! I can produce data in any format (in my case, it's taking a pandas DataFrame and exporting it to JSON, and I can fold/spindle/mutilate the data I have arbitrarily). It's a question of understanding the formats that *you* want.

It would be beneficial if you did this in two ways:

- What's the philosophy behind the formats that you want? "Array of data points, where each point is a dict" is perfectly fine, for instance. What should a data point look like? If I move from a bar graph to a category-bar graph, though, I should have a good idea of what I need to add to each point ("category":"categorystring" ?).

- For each graph type, specifically what it expects in terms of "data" input format, maybe with a small example. In theory, I ought to be able to figure this out from the philosophy, but the examples will be helpful.

**Comment by jowens** [comment]
Just to demonstrate the kind of issue that I'm running into, which surely other folks will also run into:

@domoritz nicely gave me an example (https://github.com/uwdata/ipython-vega-lite/issues/4) of a bar graph, which had the following ```data``` field:

```
  "data": {
    "values": [
      {"x":"A", "y":28}, {"x":"B", "y":55}, {"x":"C", "y":43},
      {"x":"D", "y":91}, {"x":"E", "y":81}, {"x":"F", "y":53},
      {"x":"G", "y":19}, {"x":"H", "y":87}, {"x":"I", "y":52}
    ]
  },
```

He suggested I use pandas's to_json command on my DataFrame to generate something similar. What I appear to need is a list of data elements, where each element of the list is a dict with x and y elements.

pandas's [DataFrame.to_json](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html) call has 5 'orient' options that control how the JSON is output, namely {'split’,’records’,’index’,’columns’,’values’}. None of them match what vega-lite wants. (Not your fault! Of course I can munge it in python. But it underscores that being precise about what you can input and why it's chosen that way is important.) For the record, here are the 5 outputs from to_json for each of those options (for my dataset, which has pairs of {dataset_name, m_teps value}).

```
{"name":"m_teps","index":["ak2010","belgium_osm","cit-Patents","coAuthorsDBLP","delaunay_n13","delaunay_n21","delaunay_n24","europe_osm","kron_g500-logn21","road_usa","soc-LiveJournal1"],"data":[33.5330810547,21.4583587646,1023.6077880859,502.1638793945,10.4102706909,187.3587799072,443.104888916,55.0969276428,3530.5595703125,79.4251251221,2050.32421875]}

[33.5330810547,21.4583587646,1023.6077880859,502.1638793945,10.4102706909,187.3587799072,443.104888916,55.0969276428,3530.5595703125,79.4251251221,2050.32421875]

{"ak2010":33.5330810547,"belgium_osm":21.4583587646,"cit-Patents":1023.6077880859,"coAuthorsDBLP":502.1638793945,"delaunay_n13":10.4102706909,"delaunay_n21":187.3587799072,"delaunay_n24":443.104888916,"europe_osm":55.0969276428,"kron_g500-logn21":3530.5595703125,"road_usa":79.4251251221,"soc-LiveJournal1":2050.32421875}

{"ak2010":33.5330810547,"belgium_osm":21.4583587646,"cit-Patents":1023.6077880859,"coAuthorsDBLP":502.1638793945,"delaunay_n13":10.4102706909,"delaunay_n21":187.3587799072,"delaunay_n24":443.104888916,"europe_osm":55.0969276428,"kron_g500-logn21":3530.5595703125,"road_usa":79.4251251221,"soc-LiveJournal1":2050.32421875}

[33.5330810547,21.4583587646,1023.6077880859,502.1638793945,10.4102706909,187.3587799072,443.104888916,55.0969276428,3530.5595703125,79.4251251221,2050.32421875]
```

**Comment by domoritz** [comment]
The 3rd and 4th look like what we expect. 

I'm surprised that pandas doesn't output the format we use. It's a a very common (if not the most common) way to encode data in json. I agree that we need to be clear about what we expect (documentation issue) and we should probably support a column based format as well.

**Comment by domoritz** [comment]
I created a new label for documentation.

**Comment by jowens** [comment]
I'm unclear on the dichotomy in your reply between "what we expect" and "surprised that pandas doesn't output the format we use". For VL, It's the "x" and "y" that appear to be the odd bits. You want ```{"x":"B", "y":55}``` and pandas.to_json()'s ```index``` and ```columns``` both would output ```{"B": 55}```. Yours is probably most flexible since it would deal nicely with any tuples of size > 2.

**Comment by jowens** [comment]
I'll put in a pandas request to output in your preferred format, which I would describe as 'zipped'.

**Comment by jowens** [comment]
Within pandas, the following appears to generate a format that vega-lite accepts:

```
df.index.name = 'x'
df = df.reset_index()
df.rename(columns={'old_y_name': 'y'}, inplace=True)
bar_chart["data"] = {"values" : df.to_dict(orient='records')}
```

**Comment by domoritz** [comment]
Not really. You can also just change the name in the vl spec to be consistent with what the column names in pandas are. Look at the barleys example https://github.com/uwdata/vega-lite/#barleys

**Comment by jowens** [comment]
True! I don't have to do the ```rename``` call if the vega-lite spec does this:

```
    "encoding": {
        "y": {"type": "Q",
              "name": "actual_pandas_column_name",
        },
```

**Comment by domoritz** [comment]
@kanitw We should rename the variables in our example. It's confusing to have x in two places with different meanings.

**Comment by kanitw** [comment]
@domoritz  you have already rename the example. 

I also documented the data requirement in the [wiki](https://github.com/vega/vega-lite/wiki).  So I think we can close this issue :)
