### ISSUE TITLE
Legends don't merge if a sort is defined

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5695]
I tried to set the same sort option on 2 channels defining a legend (color & shape) but the 2 legends don't merge (it works if there isn't this 'sort' option)

### Working example
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYOjUNSE1rTBxgSFZdMWwtTNJ4dF95RRUAX3UISAxdAGtCyACPPFS65CV4bk0PakLQCDqADyHIADNGZDFNFoAJbl9-QN01KDwAT1iWgEdWEKM8a0YqSBqNOq2J6dn50wBZSJ0AfVjdV4BxdATlDcg212pgOR2Yp3OlxGUF6DnW2SmMzmLQA8vomCpVJsdsgWkpuBElL8AYpdB0cABtSAAKXQhBCAIAonluLssZAAKoAZTMkAAulCRpBYIg6biEXdkaY0YwMQCgeKoPjCcT2aTyWAqbT6ZioMzdKzcezubyBRoqiAqkA

### Spec
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A scatterplot showing horsepower and miles per gallons.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal", "sort": ["Japan", "Europe", "USA"]},
    "shape": {"field": "Origin", "type": "nominal", "sort": ["Japan", "Europe", "USA"]}
  }
}
```

**Comment by domoritz** [comment]
Thanks for the issue. We will look into sorting issues soon.

**Comment by domoritz** [comment]
Consolidated in https://github.com/vega/vega-lite/issues/5996
