### ISSUE TITLE
Single column / empty field support

### ISSUE THREAD

**Issue by vadimkantorov** [vega/vega-lite#5700]
I'm trying to use Altair/Vega-Lite as a simple way to save charts in JSON format for further visualization in an HTML dashboard.

I tried to do a simple histogram (without Pandas), and used sth like:
```python
import altair
data = list(range(10)) + [4]*5
print(altair.Chart(altair.Data(values = data)).mark_bar().encode(altair.X(":Q", bin = altair.BinParams(extent = [3, 5]) ), y = 'count()').to_json())
```

This produced no error, but a very strange chart:
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAZ5dAFaxuAO0gAacFHjqAZo2rYwoCBEgVGyAO4mz5i3rV5Ga1t1awAEsiP4TAGY5OW1HJ3VXd09YAHVGABMWE2kQnQgAXx0MsKgE9DxMHAcLCnQxVmRYEwBtUIBGTQAmTUDNaU0AVk0ANk0Adk0ADk0ATnaJjukAXWzcyGQ1PQS3Y2L0qAAPew2Ldjcd8PMFzbxFvFrd8Larx07bsFmjnKvIQ2QxBJNILVe8AE9CMhvgBHVjoFzMAqMKiQDYvRyQf6HcKQdDUagAJ2EZ2+elYLl+R0gAKBoPBkMKrlh8LmOkgGExAGtvux0Ji4RkgA

If I create a column `x`, then it works fine: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAZ5dAFaxuAO0gAacFHjqAZo2rYwoCBEgVGyAO4mz5i3rV5Ga1t1awAEsiP4TAGY5OW1HJ3VXd09YAHVGABMWE2kQnQgAXx0MsKgE9DxMHAcLCnQxVmRYEwBtdPMS8MgADxM5eszcx0bHFpMARg6wHKGe8z6cACYhkfDTIYtWnECZroaFqCWwaVXRjYmwAFZdubHFkwA2E-CzzZMAdmvu-a2ADif1ufOcAE4PiFuBx2c1mNxeKX+8y+dxwwPCoOe0KBM3qAF1srlIMg1HoEm5jMV6gcxpB2G57PtkM08Ni8LUNhBAms5sdoeiQcyoIZkGIEiY+pzIHgAJ6EZD8gCOrHQLmYBUYVEg9QRUGFFLmkHQ1GoACdhDT+XpWC4tEMhaLxThIFKZa5Cq5FcqMTpIBgdQBrfnsdA6pUZIA

I don't know much about design/architecture of Altair and I wondered if this can be supported as well. It makes sense when one strives for concise and compact JSON outputs. This is important if they are embedded in large counts in some single HTML page (that can be copied or deployed to a 
 static GH pages site) 

(The data I'm using are not coming from some saved external data frame - instead they are a stream of loss values that I get from my training loop)

**Comment by jakevdp** [comment]
What's happening here is that each entry in ``data.values`` is expected to be a JSON dict mapping column name to value. You instead passed an integer, which leads to an error for any encoding that refers to column names (because the column names must match keys in the entries of the data source). However, a ``count()`` aggregate does not refer to any column names, and so it properly tells you that there are 14 entries in your data.

As you note, the way around this is to change the invalid input to valid input by adding a column label to each entry.

In Altair, you can accomplish this by creating a dataframe:
```
data = pd.DataFrame({'x': list(range(10)) + [4]*5})
alt.Chart(data)#...
```

**Comment by jakevdp** [comment]
If you really want to avoid pandas for some reason, you can construct your chart like this:
```python
data = list(range(10)) + [4]*5
alt.Chart(alt.Data(values={'x': val for val in data}))
```

**Comment by jakevdp** [comment]
If what you're after is a way to make the chart spec more compact by not having to repeat the field name for each data entry, you can do this via a flatten transform; e.g.
```
{
  "data": {"values": [{"x": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 4, 4, 4]}]},
  "transform": [{"flatten": ["data"]}],
  "encoding": {
    "x": {"bin": true, "field": "data", "type": "quantitative"},
    "y": {"aggregate": "count", "type": "quantitative"}
  },
  "mark": "bar"
}
```

**Comment by vadimkantorov** [comment]
> If what you're after is a way to make the chart spec more compact by not having to repeat the field name for each data entry

Yes, that's what I was after! Thanks for replying so quickly!

**Comment by jakevdp** [comment]
Cool - here's a function that will compactify the data in a simple Altair chart:
```python
def compactify_chart(chart):
  assert isinstance(chart, alt.Chart)
  assert isinstance(chart.data, pd.DataFrame)
  chart = chart.copy()
  data = chart.data
  chart.data = alt.InlineData(values=[data.to_dict(orient='list')])
  chart = chart.transform_flatten(list(data.columns))
  chart.transform = chart.transform[-1:] + chart.transform[:-1]
  return chart
```
Not super well-tested, but it worked for a few charts I tried.
