### ISSUE TITLE
Provide non-minified distribution

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-lite#5709]
The current [way VegaLite distributed](https://vega.github.io/vega-lite/usage/embed.html) is by including minified version only

```
<script src="https://cdn.jsdelivr.net/npm/vega@5.9.0"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.2"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6.2.1"></script>
```

If error thrown (like example below), it's very hard to figure out what's went wrong

```
ERROR TypeError: Cannot read property 'length' of undefined
    at vega-5.9.0.js:1
    at Array.reduce (<anonymous>)
    at vega-5.9.0.js:1
    at Array.forEach (<anonymous>)
    at Mt (vega-5.9.0.js:1)
    at Lr.Ur.visit (vega-5.9.0.js:1)
    at nu.ot.transform (vega-5.9.0.js:1)
    at nu.Kr.evaluate (vega-5.9.0.js:1)
    at nu.Kr.run (vega-5.9.0.js:1)
    at wB.Jr.evaluate (vega-5.9.0.js:1)
```

**Comment by domoritz** [comment]
Jsdelivr also has unminified bundles at https://www.jsdelivr.com/package/npm/vega-lite?path=build.

**Comment by g3o2** [comment]
@domoritz Can you please formulate your answer in terms of a `<script>` code line?
In addition, would this be a useful point to add to the vega-lite docs? (e.g in a debugging vega-lite section)

**Comment by domoritz** [comment]
Sure. I’ll do that when I get back to my computer.

**Comment by domoritz** [comment]
For example, you can load non-minified Vega-Lite with:

```
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.2/build/vega-lite.js"></script>
```

I'll add a debugging guide in a follow-up pull request.

**Comment by domoritz** [comment]
Guide is in https://github.com/vega/vega-lite/pull/5725
