### ISSUE TITLE
please add a "grouped bar" example to the gallery

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#572]
Also perhaps useful: show both a grouped-bar and a grouped-point graph showing the same data, simply so users can see how the two vega-lite specs differ.

**Comment by domoritz** [comment]
Great ideas. We will add some more examples. Maybe you can send a pr for some of the examples you mentioned.

**Comment by jowens** [comment]
If I had a grouped-bar working, which I don't, I would. :)

**Comment by domoritz** [comment]
Like this (created with polestar)

```json
{
  "marktype": "bar",
  "encoding": {
    "x": {"name": "Acceleration","type": "Q","aggregate": "median"},
    "y": {"name": "Origin","type": "N"},
    "row": {"axis": {"maxLabelLength": 12},"name": "Cylinders","type": "O"},
    "color": {"scale": {"quantitativeRange": ["#AFC6A3","#09622A"]}}
  },
  "data": {"url": "data/cars.json"}
}
```

**Comment by jowens** [comment]
Yes! Like that! Thank you! I'll play with my examples later this week.
