### ISSUE TITLE
provide the HTML code that can wrap a vega-lite plot

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#573]
Once I generate a vega-lite JSON description, how do I wrap it in HTML to actually display the result? Kindly document this.

**Comment by domoritz** [comment]
We are clearly lacking documentation of even the basic functionalities here. It is a top priority and will be addressed shortly. In the meantime, have a look at how we rendered the gallery at https://github.com/vega/vega-lite/blob/master/gallery/gallery.js#L160

**Comment by jowens** [comment]
Thanks. Please supply the HTML as well (not just the JavaScript). (One of the nice bits about Vincent was that it output an HTML wrapper automatically, you might start there; but I think it's also nice to separate out "the stuff that renders a particular graph" from "the stuff that needs to be in the HTML headers", so that it's straightforward to draw multiple graphs on one HTML page.)

**Comment by domoritz** [comment]
vega-lite itself generates a vega spec and the you have to do with it whatever vega requires. Nonetheless, we clearly need an end to end example.

**Comment by jowens** [comment]
This is much less than ideal, I'm sure, but here's what vincent does, which works for me for a single graph:

```
<html>
  <head>
    <title>Vega Scaffold</title>
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="http://d3js.org/topojson.v1.min.js"></script>
    <script src="http://d3js.org/d3.geo.projection.v0.min.js" charset="utf-8"></script>
    <script src="http://trifacta.github.com/vega/vega.js"></script>
  </head>
  <body>
    <div id="vis"></div>
  </body>
<script type="text/javascript">
// parse a spec and create a visualization view
function parse(spec) {
  vg.parse.spec(spec, function(chart) { chart({el:"#vis"}).update(); });
}
parse("vega_description.json");
</script>
</html>
```

I certainly will benefit by having a JS ```<script>``` that takes the JSON file as an argument, and then I can call that instead of using the wonky ```<div id="vis"></div>``` bit, but at least this will suffice for now.

**Comment by jowens** [comment]
I'm also trying to figure out how to make this work in github pages, fwiw, since that's where we put our docs. (Also, doxygen, but if it didn't work there, I'm still happy.)

**Comment by jowens** [comment]
Oh! There's a nice runtime page about this.
https://github.com/vega/vega/wiki/Runtime

**Comment by kanitw** [comment]
Duplicate with #548
