### ISSUE TITLE
Add "cursor" property in config.view schema

### ISSUE THREAD

**Issue by keckelt** [vega/vega-lite#5749]
I'd like to change the cursor on a chart that allows interval selection to indicate that there's interactivity to it (e.g. `text` or `crosshair`).

When I set it via CSS the cursor already changes outside of the chart area, e.g. on axis labels, where you can make a selection.
I managed to set the cursor to `text` with config.view.cursor:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  ...
  "config": {
    "view": {
      "cursor": "text"
    }
  }
}
```

But with the following warning: `[Warning] Validation: /config/view should NOT have additional properties` . You can try it with this spec: [Example 1](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAOLdu1McgDksMLDzd4AazCF98ZGG5VdYEaoyHRqGpCa6HiYOMCQrLpi2FpR6HzObrB08LAUkAC+6hCQeLroSrAAZty6qMkA2nGVjGJ4yLrJEVGsqHSwAJ6o7NxiALzjtmYA8lNmtgUAukVQGLqunRJKyGHFyErw3JqMStTJoBDFAB5nkM3IYpqdkW1qUHj9hNumbaiENehJQoaYr9G53B6dTyMbyvEofL5QACOrHKRmiRioBQ0QOKsHuyHgRmUZ2BUDKJwR5wuxXen06xzaugoAJ21KgewORxOsAakGuC1J+Wxy0gByUzVOsVJkAojGQAHcSWyoPAEooOt9kJc8JBBdiQEKgA)

I assume the schema does not contain specifying a cursor there, thus this issue :)

~~Bonus question: How would i change the cursor when the mouse is over the interval?~~ (selection._name._mark.cursor (_same warning here_) or config.mark.cursor) : [Example 3](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAOLdu1McgDksMLDzd4AazCF98ZGG5VdYEaoyHRqGpCa6HiYOMCQrLpi2FpR6HzObrB08LAUkAC+6hCQeLroSrAAZty6qMkA2nGVjGJ4yLrJEVGsqHSwAJ6o7NxiALzjtmYA8lNmtgUAukVQGLqunRJKyGHFyErw3JqMStTJoBDFAB5nkM3IYpqdkW1qUHj9hNumbaiENehJQoaYr9G53B6dTyMbyvEofL5QACOrHKRmiRioBQ0QOKsHuyHgRmUZ2BUDKJwR5wuxXen06xzaugoAJ21KgewORxOsAakGuS1JxVW61igoukHgCUUHVMfwZ7UgYvypOVEBxUAOSmap1F1MgFEYyAA7iS2RqpTVOm1LnhFdTVWBlcqgA)

---

I also tried setting the cursor with config.style.cursor.cursor but that didn't work: [Example 2](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAOLdu1McgDksMLDzd4AazCF98ZGG5VdYEaoyHRqGpCa6HiYOMCQrLpi2FpR6HzObrB08LAUkAC+6hCQeLroSrAAZty6qMkA2nGVjGJ4yLrJEVGsqHSwAJ6o7NxiALzjtmYA8lNmtgUAukVQGLqunRJKyGHFyErw3JqMStTJoBDFAB5nkM3IYpqdkW1qUHj9hNumbaiENehJQoaYr9G53B6dTyMbyvEofL5QACOrHKRmiRioBQ0QOKsHuyHgRmUZ2BUDKJwR5wuxXen06xzaugoAJ21KgewORxOsAakGuC1J+Wxy0gByUzVOsVJkCc-RsJLZUHgCUUHSliuKyt0qsh3AZ7UgpIgQupJrAQqFQA). I also wondered why config.style.cursor needs to be an `object`.

**Comment by domoritz** [comment]
The schema is automatically generated from the typings so you'd need to change the source code somewhere. Do you like to take a stab at a pull request?

**Comment by keckelt** [comment]
Yes 👍

**Comment by keckelt** [comment]
Should i provide [the example from above](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAOLdu1McgDksMLDzd4AazCF98ZGG5VdYEaoyHRqGpCa6HiYOMCQrLpi2FpR6HzObrB08LAUkAC+6hCQeLroSrAAZty6qMkA2nGVjGJ4yLrJEVGsqHSwAJ6o7NxiALzjtmYA8lNmtgUAukVQGLqunRJKyGHFyErw3JqMStTJoBDFAB5nkM3IYpqdkW1qUHj9hNumbaiENehJQoaYr9G53B6dTyMbyvEofL5QACOrHKRmiRioBQ0QOKsHuyHgRmUZ2BUDKJwR5wuxXen06xzaugoAJ21KgewORxOsAakGuS1JxVW61igoukHgCUUHVMfwZ7UgYvypOVEBxUAOSmap1F1MgFEYyAA7iS2RqpTVOm1LnhFdTVWBlcqgA) in `examples/` with the PR?

**Comment by domoritz** [comment]
Sounds good. But instead of setting the view config property, set the view property directly.

**Comment by keckelt** [comment]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  },
  "selection": {
    "range": {
      "type": "interval",
      "encodings": ["x"],
      "mark": {
        "cursor": "pointer"
      }
    }
  },
  "view": {
    "cursor": "text"
  }
}
```

Locally, it already works without errors. The setup with yarn worked was so easy. Really nice!

**Comment by domoritz** [comment]
I'm glad you found the setup easy.
