### ISSUE TITLE
combination of graticule labels with identity projection not supported

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#5755]
Geographic data and graticules do support the cartesian-like projection of `"projection": {"type": "identity", "reflectY": true}`:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/5186265/72665030-ec7b3880-3a04-11ea-9fd7-28fe828ed7fb.png">
Spec in vega-editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81DHoAnsgBOBgNoQNEUBCBUDroeJg4AUGBkKzuYgaQIWGkYso6ygBC3O7crDaw8ooqjlFQAGbZGHgGkaUWeC6EyAl43ITcCspqfnWQZcihsc04kOzZufmQPUEAvtNgMyXRhDlyyPB4PCpYwJANTQm6yEqbDWpQ7shlYut4AJoGeO6syIvzkBjuANY18-WNwyg1GQ3FgiHQByWQUgsCe3C+yAA6rp9DgAExQ6LwbipTwjADEyCJU1Kc1mS1q0SS4TAlOh1HcoUY8FYN1+dWiyAAHnhjngALLoOTZbxeETGOgmVRGACMAF1pV4JYZpYY0XKFX9orDkIRvMrpcq5VqyVE3qUPuhvjU9gCEsDQeCDqaIDMORpjTMgA)
But upon including graticule labels the map changes to:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/5186265/72665049-2ea47a00-3a05-11ea-9dc1-a7e325dfc027.png">
Spec in vega-editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81DHoAnsgBOBgNoQNEUBCBUDroeJg4AUGBkKzuYgaQIWGkYso6ygBC3O7crDaw8ooqjlFQAGbZGHgGkaUWeC6EyAl43ITcCspqfnWQZcihsc04kOzZufmQPUEAvtNgMyXRhDlyyPB4PCpYwJANTQm6yEqbDWpQ7shlYut4AJoGeO6syIvzkBjuANY18-WNwyg1GQ3FgiHQByWQUgsCe3C+yAA6rp9DgAExQ6LwbipTwjADEyCJU1Kc1mS1q0SS4TAlOh1HcoUY8FYN1+dWiyAAHnhjngALLoOTZbxeETGOgmVRGACMAF1pV4JYZpYY0XKFX9orDkIRvMrpcq5VqyVE3qUPuhvjU9gCEsDQeCDqaIObAnTgqEaR6LLBkABHF5KeCA3awq3VHCGGXSmGtPVRtF0GNQHUJsAGqDoWAJZx4HMuwKLUrvT4-CJa20HEa8nndDmQdASajbC7WWyYizsbPICRKQEfXQ6Nmd4IuAwiGXzN3Q47YnSMJTUdm9PPMVg6UN9Ri9nS50I52P7AeB9AnZhMqiQGdRSCpJfrzc2ihNl4T5U36G1yO0qsDpTcKgi5Nuc267vu+agRU7hVAkyZlNe049DeHqJF6Np+oGc5buG7g-uKkqxrCbQGMqKZxrqpGEVmOYjPeBaflAZYrhax4tNy1Sjo2zatpA7jtpxlbdn6fYDkBOjDs0XE6FyBgymYlY6OOUbTpikBztwC5Lixt5rngG5bi+YhvlGMqMRY95MPpT4RGBYh7nRyiHlAbEjKe55hJsV7mS5HE2q5UAAUBSggbGZQ7vZuZOVBlShHBMoIYWrrIRyGjGjMQA)
Where there is no problem when changing to a projection like `mercator`
<img width="444" alt="image" src="https://user-images.githubusercontent.com/5186265/72665065-5c89be80-3a05-11ea-8926-691e5fdb523e.png">
Spec in vega-editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81DHoAnsgBOBgNoQNEUBCBUDroeJg4AUGBkKzuYgaQIWGkYso6ygBC3O7crDaw8ooqjlFQAGbZGHgGkaUWeC6EyAl43ITcCspqfnWQZcihsc04kOzZufmQPUEAvtNgMyXRhDlyyPB4PCpYwJANTQmoHvCh2ZCL85AY7gDWNfP1jcNQ1MjcsIjoB0tBkLB4ORuyAA6rp9DgAEw-aLwbipTwjADEyBRU1Kc1mS1q0SS4TA2N+1HcoUY8FYYmeBKikGQAA88MglHgALLoORnHBeLwiYx0EyqIwARgAugKvLzDALDBDhaKHtF-shCN4JQKJcL5RiohdSld0LcansnglXu9PgctRAdYEqYlQniqRZYMgAI6sRnwSl-MLuao4QyCgXetoGaV0QNQRXKnCqqDoWAJZx4BOWwKLUqXa53CLyo0HEYM+ndOpxiTUbZQdzWWzQizsePICRKZ5XXQ6CnF3o6FwGESC+bW34e7g6RhKaj3EuQJPMVg6L1lRiNnSJ0IJoP7Ftu9BM5gkqjnWtOZRMPBzr0UdBid29iWD6mFv34vMtpTcVBjq9qcpLsQrkZJuu5SVKECThmU5wDj0962rihrOm6Hpev8+pPjyfJBv8IYxnyEbekqBixpA8aJsoKb3hYWaTr0m4tHS1RHsRZYVpAVY2Axub1s6TYth+Ojts0jE6LSBiCmYubdqGA7QjSSiwqO47UbqM5nvOhqXtezwBhR0SpOOs5qREfS-v+x5KEBL4JNuu5hJsB46fU9GGrRIxvh+ShfkGi7LqR5nfn0IFPpA4GQei0ElhoGozEAA)

Given the vast majority of geographic data that comes in meters instead of degrees, this is currently quite cumbersome.

**Comment by mattijn** [comment]
I think I got a _minimal_ example that reproduces this in Vega. The `geopoint` [transform](https://vega.github.io/vega/docs/transforms/geopoint/) seems not capable of supporting the `identity` projection.

The following spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 300,
  "height": 100,
  "data": [
    {
      "name": "longitude",
      "transform": [
        {"type": "sequence", "start": 0, "stop": 10, "step": 1, "as": "lons"},
        {
          "type": "geojson",
          "fields": ["lons", {"expr": "0"}],
          "signal": "lon_geojson"
        },
        {
          "type": "geopoint",
          "projection": "projection",
          "fields": ["lons", {"expr": "0"}],
          "as": ["lon_x", "lon_y"]
        }
      ]
    }
  ],
  "projections": [
    {
      "name": "projection",
      "type": "mercator",
      "reflectY": true,
      "size": {"signal": "[width, height]"},
      "fit": {"signal": "lon_geojson"}
    }
  ],
  "marks": [
    {
      "type": "symbol",
      "from": {"data": "longitude"},
      "encode": {"update": {"x": {"field": "lon_x"}, "y": {"field": "lon_y"}}}
    },
    {
      "type": "text",
      "from": {"data": "longitude"},
      "encode": {
        "update": {
          "x": {"field": "lon_x"},
          "y": {"field": "lon_y"},
          "text": {"field": "lons"}
        }
      }
    }
  ]
}
```
Renders as:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/5186265/72670554-c3779980-3a3e-11ea-8190-a034a25076de.png">

But when changing the projection type to `identity` it draws an empty map where the results of the data table is empty:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/5186265/72670564-f752bf00-3a3e-11ea-924a-52a4404ec7a9.png">

Editor-spec [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAZgAMuxREgpG1fFoCM+w1DXo8mHAG0lEUBA9QZ6VMi2QAG1kmPFY1PxtPSDwAJ3QZWAAzbhjULRdPT2BogE9CPxxIWGQAR1ZkGXgIqFgHGLwtAxq8bkJLJqK8ZDacC3kodFh-IITIAF9IzPdMqLw8gqhqZG4pWQVXGahExmQAtSHnQNkh-uzkAA9CGP9dcYBdSZmi028A4dkAfSWV6TkNzwm-w8002UDm+X830I3EYMgaj0ykCuK2Q8DwPDkhWRElR6LWCKi212+3SR1Gp0gFyuN3uBI8kEGpJGH3OCigzJykDuQIgYyB3IBSgeSiRMRRaIxBzAGWBQMg3l8-mxuIx6ye4IWkF8MXg9hSasRMWQiQCuIAmlpYuUEc8AF4LbKwF7oN6FJyqDSIfomMx4O7jG3bBo4R3O13sz7fVZyPmCiDCowYGIAaylMrcco1-lgOVQ7G4b0DYrSIcgdgc7xkITCfkBTwq8G44S02VYhHLDsgrNLRL2lZZAagnJ7Oz7hQ54zGsY8ddl6vm-i653hcsSxZbZfsjgjVeYNYDcobTYdPKgbY7LdPRm7YGyvbU-dZs9BkGHt8g9-7nOfm2iF2D76fuOxzjKe05xjOQogGMQA)

**Comment by domoritz** [comment]
Do you think this is a Vega or Vega-Lite issue?

**Comment by mattijn** [comment]
My last comment showed a Vega spec and I've raised subsequently a feature request at the Vega repo: https://github.com/vega/vega/issues/2315.

If you move this issue to the Vega repo and close the other than there are no duplicates.

**Comment by domoritz** [comment]
Since you link here from https://github.com/vega/vega/issues/2315, let's close this issue.
