### ISSUE TITLE
support for geojson-like features in the shape channel

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#5756]
Not sure if this is possible, but when looking to this [example](https://vega.github.io/vega-lite/docs/point.html#color):
<img width="693" alt="image" src="https://user-images.githubusercontent.com/5186265/72665224-88597400-3a06-11ea-9457-c592eeafb4a7.png">

in combination with this [example](https://vega.github.io/editor/#/examples/vega-lite/isotype_bar_chart):
<img width="693" alt="image" src="https://user-images.githubusercontent.com/5186265/72665256-cce50f80-3a06-11ea-8ae8-18293fe2808a.png">

I see that custom shapes can be drawn on certain cartesian `x`/`y` locations given svg strings in the `range` part of the `scale`. 

Would it be possible to also draw geojson type geometries as `shapes` instead of svg strings?

**Comment by kanitw** [comment]
I think you can use `geoshape` for geojson data.  If you have specific request, please feel free to reopen this issue.
