### ISSUE TITLE
Order channel does not support conditional

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5764]
The order channel cannot be conditional but we use it in an example. This looks like a regression in Vega-Lite 4. It breaks the example tests in master. 

Check out [this example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkdPDytTVyAEE1UQgCdkTUYXQI9vVSh4blYlPCsARgBmAF91ewhHZ1d3HC8fSH9A4LxQ3IAhfKiYuJwABlS7Q0yXNzEw-MKgkM0PAGFK6NirerT05uy28o6ArpKe3PDIwZqwEcaMpxacqAqIgpni0p2B6oS19IdNiY9d3wPuvpOhnAA2Bovx1se9zsP5qEWkCqz1W7zGVy+uX6P3ucxuTxW53BWUhUGhdyKDyhCKsAE5ko0ALoaMGQWDIMTIFw8FT6SCIRjURASJkrRx4ACehGQHlgjCU1EpkGSpIwfgA1lZ2VyebkAi58rA8H5uOLkAB1RiaFhWABMpOQSiiQQFUsakA5UsgADNGBT-hD3HtOdyPEpuKh+e4wUYAB5W232jy-B7OmVuj1eto+qC2sSTS6BsQO4FxMOu3IARzcsWYOkYVGFoyMSpVarNFyByiCeBpFYuUBKSvrDag6CU-1srfsjnJlOpyg8DKZLPwRfWDcglIFLAAFNpdLOADr0xnMtd4AD6Su4ARXAEp95AJ-Zia2Y-ZjKZzB52GJnJKJxeoCYzLKwEpWPHGjHINxCM4zCWvoE5Vh2zB1nSfZUrWg65MO66svkr43jg8TPleb7DHQACsP7FlAu6aMgfhWlE4GwbSlzQQOVGriOG7Ide77oXsKHvvUJKjGBtrUC2UAIKY76OOw7aaAACugmgmtQACSShKCRwx7KJHaSdJ-LUAA8qwJSkXUv4UHaADuVpKsghBWNISJGH47bUMJkB2agllQUgaDvhaFJiNwxnUAEhp3jeIoEU4vqMJYdKaB66D8lY1qmOSewAF78sR-oGSSIDJEAA) (selection_heatmap with schema). 

Related issue: https://github.com/vega/vega-lite/issues/4864

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6632
