### ISSUE TITLE
Autosize not working with facet

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-lite#5778]
Blank screen displayed If `autosize` property added to faceted chart. Remove that property and the chart will be visible.

UPDATE:

Just found out that `autosize` doesn't work with faceted views :(. I'm keeping the issue opened as it seems like displaying nothing is still a bug.

[Playground](https://vega.github.io/editor/#/url/vega-lite/N4KABGBECGCuAuB7AzgSwF4FNIC4yggkngE8AHbPSAM1XgFoAPSAGnEMgGNEA7eaVD2S4oZaABNxggOaR2AXzZEA7qnHwAFiIAsATgAMSqNWidM8EQQ7cANrAC2PS+0LHUmG+JGRxsAE7Q8Ki8rC4cpBTeiH5SPNA2cq7yCkaQyBSczq6QmDzcsbJ4VtnMRWHZtB5eVABGggD6qKGu2RGUUNGx8c0tRDaY0rnVYCY2yJhGvTCMqMJlva10-SI8sDY25YTJvYqbXIg20VkLNO6e3nU8jT1Tbd4AjrDQfHSBqABu2JMtkP2DPMNRuNvtloDM5vhNot4Ms8Kt1lCwLsFlBkJx4u1iic0RpMPZ2pB3qg-GpZjcTn5MJ8-OMRPA-LBMIjti0WRBkRwbNASJg-CIANqbLHZezQPwAa2OKOI5AJNTF5KmaCwIgAjMyQRxcvkZFKTiQ9dKwWT5iifvZBABRRjwXIWPAAJkMiNuS3a8I2Zq2mqmlXOVAtTh9PzuVEezyC-CCn0VJz+QxEQImLo4aIxhrNMsiVEOshT7JTHOlJAdGamxohwszgettr4IidwddMPda09XqRTY4fuGkFFzC7RFDUHDLyjHy++ag8YBifiwKnaXRsMhHfCsu8ucSHbZC13SU2RcIVaIoolZfX2ag8r5XbSGHaADYNYicnlEAUL0QDaavdMTaua5QDWNp2g2zpAVAkYrh6U5HtKPYPA6ACssa3BuYZPGObwxoO04DAmeBJnhS7pr+HZZgSW5wYWd4ll+HAVgxIpWqB9aOhBQHEG6KxtnBJGIWGADsqEkcOkCjpGOGTmuvwEbORHzsmslpiuJ4nOJ1FrvurLMoemrqX2YqSuR6FXtxnCSneyrtI2KbEBoqCWTwmDIBCDovtK2ofrqpk-D+gF-kxfnSiBdb2mAdmQdxLa8Qi2kCWcvb4s8aEhhhI5YVJ0YyRRM6AkpJGqZiU5DhlvyIHm2mFnpOxhAAuik7A+IE0B6oS8SMhCgq9IZlzXHgqrBj4-hvCEg3Df2aoAHS6I+2gOgAHAAzMhQm6MtQmqotqqPshk2YKlg3TfoQk7ctj5bY+i1zQ6DrXZNggiPo03Laq707Yti3zboDpCdo2iLfpQqvv1TSOsNvgBEE41gENr5TcdZ0oTdi3Ib9e3IQty0HUdcMnRdu3aMtJMOu9yF-fDoVPXgL0k+jujaPoy1LYt+h3fNyHA71oMNODYA46+UNjU4E0I2CM2Phtj70w6APaMh+iLUJuOi2AL26It2i7foe13aqDq-Utj1qy9FNCX9LPfRtqro3L3MtH1fM6JDo0w2rVMnIj+PIWtVvm+9+j6NoFuqzN7NCezuiqtryF7bHj4m8901x8tgPK8zyvoyT2gO64TtXPz+1C27wQe5NEvHaqZ2Puze3LezqrM2HtPTTdyE7YD116Pdu2JwjNPqynv3If71coYzj7PjsBm84Xaqu9DZciILoWV5FKffQDX0h8t53aP3oWHR702G4z62M-oujozHd1J631fM9HC26JHZ1vfNefHnPA2RYvIsrwrqUAWr0hKrXZmzdOBtV5e2PjNC6e9AZbV1gteanspiBmTttQG+hq43WWtHC22shJfwgAXX+MCpjC3doA8WwCHSvVHm9SOm005K0BpQ80cDW4ZxJqqTWK1WEd20PfIeMdHxyxDo+Xa21toGGnqyWe0owYuxLkvWGnCRTr1VCnUeFtfavyEv9Y2CNuFD0vpHBWRiJG20ZqIs2Tcbqqk2sTfQitroKKSEok4Ki8DF2lNQ5eeBNEcG9hrXWYClr8OZnHf6i0W5DzWgtK+bir78Nfmjex00D4EIdHvNxqNVrV1IYFH4vi4b-xoX4oBOhT5x2STtaRBDnHoK4XjHRvsY7VxlkHVaK0FpZL+mjIxu08kRKDp470INlHOwhmogB1S6G1LAezBaxNkLOOJl9BJOibaG1tkrJaQcNq6EGetbu30sY4INlzGe0yfGzIFpUoJYB-Fe20W3U6ZN9EWzyVLIxCSzYSM2ijf6xMjYOkGXHOaU88n3SucHW5ij7lTHKSI+ZVTXk1J4etEmkdCELTjotSFpi8YvU5gDA2c1+FvSzlk2O6MbpnTARTQ2JTyFF2ebDN5GD17koBhM5xxKG5-UPrAslKc8kky1mTXaW8tZZJcVtNOJMfqvwVpMgsrhGoFnkEAA)

```json
{
  "autosize": {
    "type": "fit-x",
    "contains": "padding"
  },
  "width": 490,
  "facet": {
    "column": {
      "field": "duration",
      "type": "ordinal"
    }
  },
  "spec": {
    "encoding": {
      "x": {
        "field": "bin_i",
        "type": "ordinal",
        "legend": false,
        "axis": {
          "title": null
        }
      },
      "color": {
        "field": "bin_i",
        "type": "quantitative",
        "legend": false,
        "axis": {
          "title": null
        },
        "scale": {
          "scheme": "viridis",
          "reverse": true
        }
      }
    },
    "layer": [
      {
        "mark": {
          "type": "bar",
          "size": 1
        },
        "encoding": {
          "y": {
            "axis": {
              "minExtent": 20,
              "title": null
            },
            "field": "min",
            "type": "quantitative",
            "legend": false,
            "scale": {
              "type": "log"
            }
          },
          "y2": {
            "axis": {
              "minExtent": 20,
              "title": null
            },
            "field": "max",
            "type": "quantitative",
            "legend": false,
            "scale": {
              "type": "log"
            }
          }
        }
      },
      {
        "mark": {
          "type": "bar",
          "size": 6
        },
        "encoding": {
          "y": {
            "axis": {
              "minExtent": 20,
              "title": null
            },
            "field": "q25",
            "type": "quantitative",
            "legend": false,
            "scale": {
              "type": "log"
            }
          },
          "y2": {
            "axis": {
              "minExtent": 20,
              "title": null
            },
            "field": "q75",
            "type": "quantitative",
            "legend": false,
            "scale": {
              "type": "log"
            }
          }
        }
      },
      {
        "mark": {
          "type": "tick",
          "size": 20,
          "thickness": 2
        },
        "encoding": {
          "y": {
            "axis": {
              "minExtent": 20,
              "title": null
            },
            "field": "mean",
            "type": "quantitative",
            "legend": false,
            "scale": {
              "type": "log"
            }
          }
        }
      }
    ]
  },
  "data": {
    "values": [
      {
        "bin_i": 1,
        "duration": 1,
        "max": 1.9642835793718165,
        "mean": 1.0781367168962268,
        "min": 0.3111818864927448
      },
      {
        "bin_i": 2,
        "duration": 1,
        "max": 1.7825898592655423,
        "mean": 1.0361643332115271,
        "min": 0.33599403288022645
      },
      {
        "bin_i": 3,
        "duration": 1,
        "max": 1.693633524445087,
        "mean": 0.9841606522129228,
        "min": 0.5272732869315924
      },
      {
        "bin_i": 4,
        "duration": 1,
        "max": 1.5573285271100472,
        "mean": 1.0270291415654156,
        "min": 0.5634887038759334
      },
      {
        "bin_i": 5,
        "duration": 1,
        "max": 1.17860265302103,
        "mean": 0.8958148684926166,
        "min": 0.5925328517259466
      },
      {
        "bin_i": 1,
        "duration": 3,
        "max": 2.586448847381346,
        "mean": 1.2994799409591422,
        "min": 0.17039142970783164
      },
      {
        "bin_i": 2,
        "duration": 3,
        "max": 3.37350280488123,
        "mean": 1.363848710642641,
        "min": 0.18480178939172417
      },
      {
        "bin_i": 3,
        "duration": 3,
        "max": 2.3533170373408483,
        "mean": 0.8703319883373584,
        "min": 0.14624476161818906
      },
      {
        "bin_i": 4,
        "duration": 3,
        "max": 1.55372559777428,
        "mean": 0.940704577621594,
        "min": 0.5108913743050686
      },
      {
        "bin_i": 5,
        "duration": 3,
        "max": 0.9067328190356748,
        "mean": 0.5742090509199785,
        "min": 0.4639238058983517
      },
      {
        "bin_i": 1,
        "duration": 5,
        "max": 4.256420816139131,
        "mean": 1.5514176300358342,
        "min": 0.2785771623067006
      },
      {
        "bin_i": 2,
        "duration": 5,
        "max": 4.730242435134388,
        "mean": 1.9312915082800939,
        "min": 0.2796848654480125
      },
      {
        "bin_i": 3,
        "duration": 5,
        "max": 1.8072172572236977,
        "mean": 0.5623725874439222,
        "min": 0.25696662326544045
      },
      {
        "bin_i": 4,
        "duration": 5,
        "max": 0.8793370917425682,
        "mean": 0.6454412961931875,
        "min": 0.415598978735229
      },
      {
        "bin_i": 5,
        "duration": 5,
        "max": 0.644006138230276,
        "mean": 0.5233384211686484,
        "min": 0.37471343364997456
      }
    ]
  }
}
```

- [ ] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
Closing since we already have this tracked. Yes, we could improve the error handling here. Feel free to send a pull request.

**Comment by domoritz** [comment]
@alexeypetrushin Can you file a new issue about the empty chart with a minimal example?

**Comment by alexeypetrushin** [comment]
I added the new issue with the minimal example https://github.com/vega/vega-lite/issues/5783
