### ISSUE TITLE
Decouple shorthand from Vega-lite 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#578]

**Comment by domoritz** [comment]
And potentially move it to a separate repo.

**Comment by amitkaps** [comment]
This would be awesome... And would make it easier to write to ggplot2 like syntax to write visualisation without needing to know javascript. @nischalhp, @raghothams and I were hacking to get vega-lite working in ipython notebook. We got a simple bar chart working in an ipython notebook - see link below. The shorthand would make it very easy to write this stuff. Would be happy to help to make this happen if you can point us towards the best way to contribute for this.

http://nbviewer.ipython.org/github/nischalhp/python-devsprint-viz/blob/master/Vega%2C!Las.ipynb

**Comment by domoritz** [comment]
@amitkaps Also note that we are working on IPython integration in https://github.com/vega/ipython-vega. Do you want to join forces and work in the same repo?

**Comment by amitkaps** [comment]
Yes we did see that. We could take a stab at https://github.com/vega/ipython-vega/issues/10 and try to get ivegalite working with tools.py. Your solution is more elegant. Be warned, that at least I am a newbie at python / javascript / open-source development, so it may take time to figure it out. Can we send you a pull request if we get that working?

**Comment by domoritz** [comment]
Of course. Send a pull request and I'll review it. For the first iteration, I was hoping to just have a function that takes a divt that is equivalent to the vl json spec.

**Comment by amitkaps** [comment]
Ok. Done. It took less time than I thought. 

http://nbviewer.ipython.org/github/amitkaps/ipython-vega/blob/master/Example.ipynb

**Comment by kanitw** [comment]
Note:  we were brainstorming the project name for the extracted Vega-Lite shorthand:

- Diet Vega-Lite  (It’s even lighter than Vega-Lite)
- Vega-Line (producing Vega code in a single line)
- Vega-lite shorthand (old boring name IMHO)

(Other ideas are welcomed!)

**Comment by raghothams** [comment]
On the same lines of diet-vega-lite, maybe vegan-lite?

**Comment by domoritz** [comment]
I really like Vega-Line. It is very similar to Vega-Lite though and we have to make sure that there is no confusion.

**Comment by kanitw** [comment]
> vegan-lite

Maybe just vegan? :p 

> I really like Vega-Line. It is very similar to Vega-Lite though and we have to make sure that there is no confusion.

Agree.  I like it too but potential confusion worries me a bit.

**Comment by arvind** [comment]
-1 for Vegan/Vegan-Lite, I'm not sure I understand its provenance from Vega (i.e., celestial objects)? I also agree with the concerns about Vega-Line/Lite being too similar. So although I like it, I would not vote for it. 

I don't think it's necessary to tie the name of the shorthand to Vega-Lite directly. The name should imply that it's a much smaller subset of Vega/Vega-Lite. Here are some other ideas:
* Vega Shorthand (as opposed to Vega-Lite Shorthand)
* Mini Vega/Vega Mini
* Micro Vega/Vega Micro/μVega
* Nano Vega/Vega Nano
* Vega Jr. :stuck_out_tongue:

**Comment by jeffbaumes** [comment]
FWIW I like Vega Nano - the progression Vega, Vega Lite, Vega Nano makes sense to me. Of course hopefully you don't come up with an even more compressed language or you will have to call it Vega Shuffle :) I think Vega Shorthand is fairly clear also.

**Comment by kanitw** [comment]
From a conversation with @jheer @domoritz, we decided to stick with "Vega-Lite Shorthand".  

It's not that "much smaller subset" of Vega-Lite.  While originally developed to serve as a filename/encoding id in Compass, it will eventually become an alternative way for expressing the core of Vega-Lite with a slightly shorter syntax.

**Comment by kanitw** [comment]
In branch `kw/api`, all shorthand methods are in `vl.shorthand` in `shorthand.ts` and should be ready to be extracted — if we still want to do it. 

I think at some point, we would want to re-design it to make it a little more expressive.

**Comment by kanitw** [comment]
We'll remove from core Vega-Lite API in 2.0 (See #1509)

**Comment by domoritz** [comment]
The shorthand now lives in https://github.com/vega/vega-lite-shorthand/tree/kw/init but we haven't put any work into it recently so consider this functionality non-existent for now.
