### ISSUE TITLE
Improve how unsupported autosize handled with facet

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-lite#5783]
An empty plot shown if `autosize` and `fit-x` used along with `facet`. If `fit-x` replaced with `fit` the chart will be visible.

There's a warning in console that fit is not supported with facet, but maybe error handling of this case could be improved further. Showing at least something or throwing an explicit error.

The chart without autosize

<img width="190" alt="Screen Shot 2020-01-22 at 5 52 45 am" src="https://user-images.githubusercontent.com/94196/72861786-f7bbb600-3cdb-11ea-967e-dce5a42401f8.png">

Empty page if autosize added

<img width="186" alt="Screen Shot 2020-01-22 at 5 52 53 am" src="https://user-images.githubusercontent.com/94196/72861802-030ee180-3cdc-11ea-90ab-707ab18ad1d0.png">

The spec and [playground](https://vega.github.io/editor/#/url/vega-lite/N4KABGBECGCuAuB7AzgSwF4FNIC4yggkngE8AHbPSAM1XgFoAPSAGnEMgGNEA7eaVD2S4oZaABNxggOaR2AXzZEA7qnHwAFiIAsATgAMSqNWidM8EQQ7cANrAC2PS+0LHUmG+JGRxsAE7Q8Ki8rC4cpBTeiH5SPNA2cq7yCkaQyBSczq6Q9tB+ANbeZIiCFkZEmDzcsbJ4VtkkWa4ctB5eVPaY0E7lzcTklFAAjrDdQfxBAG7YYRDJSSnsPoHQTUST8bCYwngA2rP4B0S+AUEheACMvdmd3SIXB4oH9X0ngcFOeABM1xy3n2Avl9Hr8Xtk3mcAQBmX5Ef73fSPMIAXQUIHkQA)

```
{
  "autosize": {
    "type": "fit-x",
    "contains": "padding"
  },
  "width": 490,
  "facet": {
    "column": {
      "field": "duration",
      "type": "ordinal"
    }
  },
  "spec": {
    "mark": "point",
    "encoding": {
      "y": {
        "field": "mean",
        "type": "quantitative"
      }
    }
  },
  "data": {
    "values": [
      {
        "duration": 1,
        "mean": 1
      },
      {
        "duration": 2,
        "mean": 22
      },
      {
        "duration": 3,
        "mean": 10
      }
    ]
  }
}```

**Comment by willium** [comment]
IMO this should be a "wontfix" in favor of https://github.com/vega/vega-lite/issues/5219. Neither type of fit is supported by faceting.
