### ISSUE TITLE
cornerRadius doesn't work for stacked bars with timeUnit

### ISSUE THREAD

**Issue by donghaoren** [vega/vega-lite#5800]
Failing spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "mark": {"cornerRadiusTopLeft": 2, "cornerRadiusTopRight": 2, "type": "bar"},
  "encoding": {
    "x": {"field": "date", "type": "temporal", "timeUnit": "year"},
    "y": {"field": "price", "type": "quantitative", "aggregate": "average"},
    "color": {"field": "symbol", "type": "nominal"}
  }
}
```

Symptom: bars don't show up at all.
Note: If we remove the cornerRadius, the spec will work properly.

**Comment by donghaoren** [comment]
We can fix the generated Vega spec as follows:

1. Add `year_date_end` to the generated `aggregate`:
```json
        "aggregate": {
            "fields": [
              "average_price_start",
              "average_price_start",
              "average_price_end",
              "average_price_end",
              "year_date_end"
            ],
            "ops": ["min", "max", "min", "max", "min"]
          }
````

2. Change `{"scale": "x", "field": "year_date_end"}` to `{"scale": "x", "field": "min_year_date_end"}`

The problem is that `min` is not the correct transform for `year_date_end` in general, I would expect to use something like `first` or `firstValid`, which isn't supported yet.

**Comment by donghaoren** [comment]
Actually if we change `groupby` to `"groupby": ["year_date", "year_date_end"]` it will work

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5803
