### ISSUE TITLE
only "barley" works in online editor

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#582]
Attached video shows me trying the online editor for anything except "barley" on OS X for {Chrome, Firefox, Safari}, same behavior for all: only "barley" ever displays anything.

http://www.ece.ucdavis.edu/~jowens/tmp/tmpnrBX9H/only-barley-works-in-editor.mov

**Comment by domoritz** [comment]
The UI is super confusing. The dropdown is the dataset selector for the shorthand and not different examples. I added a label, which should make it less confusing. 

The way to sue the editor is to put in a vl spec (or write one) with a data property. If you don't provide a data property, we take the dataset that is selected in the dropdown. 

We will soon move the editor to the vega editor. See https://github.com/vega/vega-editor/issues/11
