### ISSUE TITLE
Undefined values resulting from aggregates are shown on the chart

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5837]
First reported in https://github.com/altair-viz/altair/issues/1944

Minimal repro ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgN1gGwK4FMBnFMAbXQA8SAGAGigE8aBfeykgRnsidQDtc2bMwC6rcFAC2sAE4BrEpAAOAewCWfeJFoTI+PgGMV0DQHMSoCBEhVU6eAyX5FAR1yxNaxPDUZn3ADM1fGxoRSpxK0YLSAcnV3dPb19-KFhTUxl8UwRnVEhJfA9tKCCQsPymZglq5iA)):
```
{
  "data": {"values": [{"x": 0, "y": 0}, {"x": 1, "y": null}]},
  "mark": "point",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "aggregate": "mean", "field": "y"}
  }
}
```
![visualization - 2020-02-01T232902 091](https://user-images.githubusercontent.com/781659/73604757-a5379080-454a-11ea-869e-444120a7d3a3.png)

Looking at ``marks`` in the data viewer shows that the y-value is undefined, which leads the renderer to draw it at y value = 0 (i.e. the top of the chart):
<img width="760" alt="Screen Shot 2020-02-01 at 11 29 43 PM" src="https://user-images.githubusercontent.com/781659/73604770-e760d200-454a-11ea-815c-855e1366ab5b.png">

When no aggregation is specified, the undefined point is automatically removed from the chart ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgN1gGwK4FMBnFMAbXQA8SAGAGigE8aBfeykgRnsidQDtc2bMwC6rcFAC2sAE4BrEpAAOAewCWfeJFoTI+PgGMV0DQHMSoCBEhVU6eAyX5FAR1yxNaxPDUZn3ADM1fGxoRSpxK0YLSAcnV3dPb19-KCCQsNQeSGYJXOYgA)):
```
{
  "data": {"values": [{"x": 0, "y": 0}, {"x": 1, "y": null}]},
  "mark": "point",
  "encoding": {
    "x": {"type": "quantitative", "field": "x"},
    "y": {"type": "quantitative", "field": "y"}
  }
}
```
![visualization - 2020-02-01T233217 425](https://user-images.githubusercontent.com/781659/73604783-22630580-454b-11ea-803c-aefa4d8d0f2f.png)

It seems that the version with the aggregate should behave the same way.

**Comment by domoritz** [comment]
@jheer Just to confirm, Vega is supposed to return undefined as an aggregate value rather than removing the whole entry, right?

**Comment by jheer** [comment]
Depends. If a group is empty, it should not have an output record by default, though this can change depending on the transform parameters (such as `drop` and `cross`). If an record is created for an empty group, then yes, by design some of the values may be `undefined`, such as for `mean` and `product`. In addition, variance and std. dev. can be `undefined` if there are insufficient data points.

Implementation of aggregate ops is here: https://github.com/vega/vega/blob/master/packages/vega-transforms/src/util/AggregateOps.js

**Comment by jheer** [comment]
In the case above, it looks like the group is not empty, but there are no valid values being input to the aggregation. In which case, yes, the intended result is `undefined`.

**Comment by domoritz** [comment]
Thanks for confirming the expected behavior. Vega-Lite then needs to filter out tuples that have undefined aggregated values.
