### ISSUE TITLE
Vega-Lite 4.1.1: ref names url-encode special characters

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5838]
This means that automated schema validation tools like Python's ``jsonschema`` package do not work correctly.

Example:

Here is a reference:

https://github.com/vega/schema/blob/34f2d40982b3b2dd3ae69322d49487a50f61fe8f/vega-lite/v4.1.1.json#L2223

Here is the definition that should match in a string equality sense:

https://github.com/vega/schema/blob/34f2d40982b3b2dd3ae69322d49487a50f61fe8f/vega-lite/v4.1.1.json#L5630

**Comment by domoritz** [comment]
That’s unfortunate. The RFC says that references need to be URIs but many schema validates don’t support it. I’m inclined to revert this change but then we have a schema that’s invalid according to the standard...

Anyway, I think I’ll revert until at least VSCode catches up (they don’t support encoded references either).

**Comment by domoritz** [comment]
We should file an issue with the json schema python package, though.

**Comment by jakevdp** [comment]
Oh, OK I'll double-check. I didn't dig into precisely why it broke Altair (it may be my code not jsonschema) but this URL encoding of references definitely has not been part of the schema prior to 4.1.

Was it an intended change, then?

**Comment by jakevdp** [comment]
Ah, looks like jsonschema itself is fine, I just need to change how Altair handles this:
```python
import jsonschema

schema = {
    "definitions": {
        "Foo<hello>": {"type": "string"}
    },
    "properties": {
        "x": {"$ref": "#/definitions/Foo<hello>"},
        "y": {"$ref": "#/definitions/Foo%3Chello%3E"}
    }
}

spec = {"x": "x value", "y": "y value"}

jsonschema.validate(spec, schema)
```

I'll wait until you confirm this was an intended change before I start adapting Altair to handle this.

**Comment by domoritz** [comment]
I mentioned this a few weeks ago on slack. It’s a fix since the schema previously wasn’t valid. We can roll this change back for now if it’s causing issues.

**Comment by jakevdp** [comment]
Turns out this is pretty straightforward to accommodate within Altair now that I know what's going on.

Sorry for the noise!

**Comment by domoritz** [comment]
Thanks for updating Altair.
