### ISSUE TITLE
Document (in pseudocode) binning/aggregation/groupby logic

### ISSUE THREAD

**Issue by ellisonbg** [vega/vega-lite#584]
We are working on rendering the vega-lite spec in various Python based vis libraries (matplotlib, Bokeh, Plotly). One of the main questions that has come out of this work is how exactly binning/aggregation/groupby work together on the initial data set to create the final derived data set that is send to the markers on each subplot.

I talked with @jheer today at Strata about starting to document this logic in pseudocode to make it easier for other, non-vega projects to render the spec. @tacaswell (Matplotlib) had some specific questions around this:

* If multiple columns are aggregated what is the order in which the aggregation is computed? How does aggregated data re-enter the computations?
* If any data columns are binned, do you always group against the binned versions for the columns?

But more important than that is to sketch the overall computational part of the spec in pseudocode that can easily be translated to SQL, Python, R, etc.

**Comment by kanitw** [comment]
> If multiple columns are aggregated what is the order in which the aggregation is computed? How does aggregated data re-enter the computations?

Vega-lite always produce at most one Vega aggregate transform.  Thus, aggregation is only computed once (but multiple fields can be aggregated at the same time).   This is equivalent to produce one SQL aggregation query without nesting.    

> If any data columns are binned, do you always group against the binned versions for the columns?
Yes. 

> Sketch the overall computational part of the spec in pseudocode that can easily be translated to SQL, Python, R, etc.
This will take a little more time.  We will write pseudecode (and eventually real code) for producing SQL from a given Vega-lite spec -- and I guess people can take it from there to produce equivalent data transformation in Python / R.   

- [ ] Write Pseudocode for logic that translate Vega-lite spec to a corresponding SQL.

**Comment by ellisonbg** [comment]
One important point. For people implementing non-vega renderers, it isn't
very helpful to vega-lite in reference to vega specific abstractions.

But your comment about aggregation may still be helpful for us.

Also, even simple narrative descriptions of the data reduction model would
be *very* helpful. We are trying to implement other renderers for vega-lite
on a pretty short time frame (a few weeks).

Thanks!

On Sat, Oct 3, 2015 at 3:58 AM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> If multiple columns are aggregated what is the order in which the
> aggregation is computed? How does aggregated data re-enter the computations?
>
> Vega-lite always produce at most one Vega aggregate transform. Thus,
> aggregation is only computed once (but multiple fields can be aggregated at
> the same time). This is equivalent to produce one SQL aggregation query
> without nesting.
>
> If any data columns are binned, do you always group against the binned
> versions for the columns?
> Yes.
>
> Sketch the overall computational part of the spec in pseudocode that can
> easily be translated to SQL, Python, R, etc.
> This will take a little more time. We will write pseudecode (and
> eventually real code) for producing SQL from a given Vega-lite spec -- and
> I guess people can take it from there to produce equivalent data
> transformation in Python / R.
>
>
>    - Write Pseudocode for logic that translate Vega-lite spec to a
>    corresponding SQL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/584#issuecomment-145213105>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
@domoritz  I’m thinking about adding `transformation.md` to document about order of execution for all data transforms.  

These currently include:

1. [Null Filter](#null-filter)
2. [Calculating new fields with provided formula](#calculate)
3. [Derive new time unit for temporal fields](#time-unit)
4. [Binning](#binning)
5. [Filter](#filter)
6. [Aggregation](#aggregation)

The null filter is currently a config. (I’m considering moving it #597).
Calculate and filter are inside spec's `data` (and thus is in `data.md`).
The rest are field transformations and currently are in `encoding.md`.

I’m thinking about moving details of all these transforms to `transformation.md` and provide links from `data.md` and `encoding.md`.  Do you have any objection?

**Comment by ellisonbg** [comment]
Sounds great!

On Sat, Dec 26, 2015 at 6:32 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> @domoritz <https://github.com/domoritz> I’m thinking about adding
> transformation.md to document about order of execution for all data
> transforms.
>
> These currently include:
>
>    1. Null Filter <#151e1478818f66df_null-filter>
>    2. Calculating new fields with provided formula
>    <#151e1478818f66df_calculate>
>    3. Derive new time unit for temporal fields
>    <#151e1478818f66df_time-unit>
>    4. Binning <#151e1478818f66df_binning>
>    5. Filter <#151e1478818f66df_filter>
>    6. Aggregation <#151e1478818f66df_aggregation>
>
> The null filter is currently a config. (I’m considering moving it #597
> <https://github.com/vega/vega-lite/issues/597>).
> Calculate and filter are inside spec's data (and thus is in data.md).
> The rest are field transformations and currently are in encoding.md.
>
> I’m thinking about moving details of all these transforms to
> transformation.md and provide links from data.md and encoding.md. Do you
> have any objection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/584#issuecomment-167375812>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
Will be done as part of #656
