### ISSUE TITLE
Encode channel for dashed lines

### ISSUE THREAD

**Issue by envirodatavis** [vega/vega-lite#5857]
Hi, wondering if it's possible to add encoding for dashed or continuous lines. A line that changes between dashed or continuous based on the data.
There are some hacks around but they're not as elegant and it would be a great feature. 

Thanks!

**Comment by envirodatavis** [comment]
![ExampleDashedLine](https://user-images.githubusercontent.com/49455878/73858432-6170af80-4806-11ea-87ee-c1babfa4f90a.png)

**Comment by kanitw** [comment]
This is a timely request, I just put the https://github.com/vega/vega-lite/pull/5860 up. 

Once that's merged, you can create this figure by making separate (but joined) lines (one for observed and another one or two for modeled).

I'll close this for now since there is no additional action item.
