### ISSUE TITLE
Rename Generated “raw” and “aggregate” tables.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#587]
Currently Vega-lite produces up to two data tables in the output Vega specification.

- source data table (`raw`) — the original data table, augmented by derived fields (binning, timeUnit conversion, and the planned calculated field – #451) and filtered.   

- summary table (`aggregate`)  – the additional table, produced by adding Vega’s aggregate transform. 

### TODO

`raw` is a rather confusing name since the table is augmented with derived fields and filtered.  
Maybe `source` is a better name, because it is a source table for other part of the spec. 

`aggregate` table should be renamed to `summary` for consistency as we plan to rename `aggregate` property to `summarize`-

**Comment by kanitw** [comment]
@domoritz – any opinion on this?

**Comment by kanitw** [comment]
Another option — we can name the source data table “data”.  This is actually the original name.   But I like “source” more than “data” because naming data table name as “data” looks a bit weird for me.

**Comment by domoritz** [comment]
Can't we rid of these in vega 2?

**Comment by kanitw** [comment]
We obviously cannot get rid of the source/`raw` table.  

The ones we can get rid of are the sorted-field-name tables in sort.js.  

Meanwhile, the summary table depends on if we keep `useRawDomain` scale option.  
(We need to keep the source table to provide domain.)
Also, if we implement layering and users want to overlay a summary plot on top of a raw plot, 
then there should be one table for the pre-summary data and another for summary data.
(Consider a box plot on top of dot plot for example.)

**Comment by domoritz** [comment]
`raw` -> `source`

**Comment by domoritz** [comment]
`aggregate` -> `summaryTable`

**Comment by jheer** [comment]
Why bother to include "Table"? It could just be "summary". In any case I
would use consistent naming schemes across data set definitions.

**Comment by domoritz** [comment]
Okay, summary it is.

**Comment by kanitw** [comment]
+1 for `summary`

**Comment by kanitw** [comment]
Fixed in #702
