### ISSUE TITLE
Removing empty groups from SVG output

### ISSUE THREAD

**Issue by mathisonian** [vega/vega-lite#5872]
Hi all,

_Apologies if this has already been discussed, a quick search didn't turn anything up._

I've been using Vega-Lite via Altair to quickly make some charts and it is a great experience overall, so first off thanks for that. Most of the charts that I make require some post-processing in a vector graphics editing tool (my tool of choice is Sketch, but same thing applies to XD, Figma, Illustrator, etc.); see [this article](https://onezero.medium.com/leak-of-microsoft-salaries-shows-fight-for-higher-compensation-3010c589b41e) for an example of charts created with this workflow. 

Now, this isn't a problem itself, I wouldn't expect a general purpose charting tool to give me pixel perfect output. The problem is that when I download the SVG created by Vega-Lite, it is _very tedious_ to edit because of all the empty groups that are included in the markup. Essentially I have to go and find all of these groups manually and delete them before I can make the changes I actually care about making. This isn't a big deal if you have to do it once, but if you're making many charts, or if you are iterating both on the chart as specified in VL and the post-processing design tweaks you want to make, it becomes a real pain. 

One way to solve this could be to run a filter over the SVG before it is downloaded which simply removes all of these extra nodes. There are likely other ways to do it as well but that seems easy to implement.

**Comment by domoritz** [comment]
Can you give some examples of the empty groups? Is this something that can be addressed in Vega alone or do we need to change Vega-Lite?

**Comment by mathisonian** [comment]
Hold on this might be something funny with Sketch's SVG parser, but I also see the same thing in MacOS's preview window. Illustrator seems to parse it fine. Will reopen once I have a better idea if its actually a vega issue.  🙏
