### ISSUE TITLE
timeUnit maxbins doesn't appear to have any effect

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#5876]
I've labelled this as a bug, but perhaps if I've misunderstood, it is a documentation issue (or I'm just being dumb)...

Documentation suggests the new 4.1 [timeUnit object](https://vega.github.io/vega-lite/docs/timeunit.html#params) allows the binning time unit to be specified indirectly by setting the `maxbins` value. Yet when I try changing to different `maxbins` values, it appears to have no effect. For example, I would expect setting `maxbins` to 3 in the example below (spanning 3 years) to be equivalent to `"timeUnit" : "year", 36 to `month` etc. In fact any value seems to result in the same output.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 400,
  "data": {
    "url": "https://vega.github.io/vega-lite/data/seattle-weather.csv",
    "format": {"parse": {"date": "date:'%Y/%m/%d'"}}
  },
  "transform": [{"timeUnit": {"maxbins": 12}, "field": "date", "as": "tBin"}],
  "encoding": {
    "x": {"field": "tBin", "type": "temporal", "axis": {"format": "%b"}},
    "y": {"field": "temp_max", "type": "quantitative", "aggregate": "max"}
  },
  "mark": {"type": "line", "point": {"fill": "black"}}
}
```

**Comment by domoritz** [comment]
I think there may be a Vega issue. @hadenl will know.

**Comment by haldenl** [comment]
Yes! This is a bug. I have a PR up in Vega to fix this. Maxbins isn't being piped through the Vega parser.

https://github.com/vega/vega/pull/2353

**Comment by haldenl** [comment]
I should have filed an issue in Vega-Lite the same time—sorry. Thank you for raising this @jwoLondon .

**Comment by domoritz** [comment]
Since this is a Vega issue, we can close the issue here.
