### ISSUE TITLE
mismatch literal type "cornerRadius" in base.ts

### ISSUE THREAD

**Issue by kristw** [vega/vega-lite#5892]
Please:

- [X] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [X] Describe how to reproduce the bug / the goal of the feature request.

Build `react-vega` with latest version of `vega-lite` and `vega-typings`

- [X] Use the latest versions of Vega and Vega-Lite.
- [X] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

```
../../node_modules/vega-lite/build/src/spec/base.d.ts(98,70): error TS2344: Type '"opacity" | "fillOpacity" | "strokeOpacity" | "strokeWidth" | "strokeDash" | "strokeCap" | "strokeDashOffset" | "strokeMiterLimit" | "strokeJoin" | "cornerRadius"' does not satisfy the constraint '"baseline" | "color" | "size" | "text" | "fill" | "stroke" | "x" | "y" | "filled" | "tooltip" | "shape" | "opacity" | "fillOpacity" | "strokeOpacity" | "strokeWidth" | "strokeDash" | ... 28 more ... | "timeUnitBand"'.
  Type '"cornerRadius"' is not assignable to type '"baseline" | "color" | "size" | "text" | "fill" | "stroke" | "x" | "y" | "filled" | "tooltip" | "shape" | "opacity" | "fillOpacity" | "strokeOpacity" | "strokeWidth" | "strokeDash" | ... 28 more ... | "timeUnitBand"'.
../../node_modules/vega-lite/build/src/channeldef.d.ts(1,10): error TS2305: Module '"../../../vega-typings/types"' has no exported member 'Gradient'.
```

**Comment by domoritz** [comment]
We need a Vega update. Vega depends on a specific version of its typings but Vega-Lite relies on a never version. For now, import the Vega type from Vega typings directly until @jheer makes a new Vega release.
