### ISSUE TITLE
View properties are not propagates to charts with row/column

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5908]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "view": {
     "stroke": null
  },
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "width": {"step": 17},
  "mark": "bar",
  "encoding": {
    "row": {"field": "gender", "type": "nominal"},
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"}
    },
    "x": {"field": "age", "type": "ordinal"},
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#675193", "#ca8861"]}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/589034/74482151-d8422400-4e68-11ea-9b2c-2b9a0fe04602.png)

See https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgVGyAO7YwoCEciw8AJ24BrZPqWsxYjQF91ESABN0eTDmBRWZmL6Hl7opITchPZePEryiiouGpDm6EqwAGbcZqj6ANoaEMCQGYxieMhmwZ54rKh0AJ7I6GZgALxtYABMAAx9kElGBpDw6GLw0RXVXnV0sMgAHu2dXWAA-GAA5ABiaGPIm2A4mwCy+5tqUOiwwdTISu6VAxoAuq5QOozuLPrFpsiEfQARgA7IMoBgzJZguwWmpkvd4Nx3IwlNRfoUoBY9L4StoxO5bvdHlVVFA8A1CDYcJAlNxUKixgN3m4Ghihm50NRqGZhFMabA6pc8cgCcEqZExDYySlKdSoABHVhpPDMGJUeEcq4LRg3XGqvBS8WRSaxZ5DcFuBa-EVimlc6XkuXBbIopRMy1QJFibLsjm2wk0u4PJ4yilU4J0hnuoIs4wIfY2sxpO75SAAYgAbCCAKxAgCcAGZhenRgAOMuZoGQF5OTF1iB1utAA

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/5915
