### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#592]
- [x] Basic index.html
- [x] Update / Refine Examples (both for gallery and vega-editor) #770

**Comment by kanitw** [comment]
This should be done after we migrate editor (#487)

**Comment by kanitw** [comment]
We now have index.html, but still have to 

- [ ] Include vega-based gallery in the index.html.

**Comment by domoritz** [comment]
Why include a vega-based gallery? Why not just a list of vega-embed?

**Comment by kanitw** [comment]
Sorry I mean vega based show reels like vega.github.io/vega
