### ISSUE TITLE
Missing required version of bundler to be installed in Development Guide

### ISSUE THREAD

**Issue by adrijshikhar** [vega/vega-lite#5931]
The Development Guide mentions `gem install bundler` to install bundled but this installs the incompatible version of it. This can be resolved by replacing it with by `gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"`

Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:
- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
Hmm, I've never had problems with the bundler and it seems to be working on the CI. Can you explain what the issue is here?

**Comment by adrijshikhar** [comment]
I use rvm(ruby version manager) and `gem install bundler` installed the latest version, but it was not compatible with vega-lite

**Comment by domoritz** [comment]
Can we make it compatible? This doesn't seem to be a problem on the CI so I'm not sure whether this is a general issue.

**Comment by adrijshikhar** [comment]
to make it compatible, we have to update the dependencies and test with it.

**Comment by adrijshikhar** [comment]
> to make it compatible, we have to update the dependencies and might test with it.
