### ISSUE TITLE
Applying cornerRadiusEnd in a theme can break candlestick plots

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5942]
When the bars does not touch zero, `cornerRadiusEnd` should be applied to both corners.

**Comment by domoritz** [comment]
Can you explain the issue a bit more? Maybe with a screenshot?

**Comment by kanitw** [comment]
For now, you can add cornerRadiusEnd to the candlestick example and see.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5968
