### ISSUE TITLE
Legend Bottom alignment has some issue when we have more number of the legends.

### ISSUE THREAD

**Issue by jerinjjose** [vega/vega-lite#5944]
Legend Bottom alignment has some issues when we have multiple legends. It is going out of the screen instead it can move to the next line.

Please see the following screenshot for more details.
![image-2020-02-19-10-56-11-427](https://user-images.githubusercontent.com/10355174/74925409-2a032500-53fa-11ea-9b97-dfe70f90de87.png)

Following is my configuration.
`
            color: {
                field: 'Label', type: 'nominal',
                scale: {
                    range: data.viewConfig.colors
                },
                legend: {
                    orient: 'bottom',
                    offset: 0,
                    padding : 0,
                    zindex : 1,
                    labelLimit : 80,
                    labelAlign : 'left',
                    title: null
                },
            }`

Following are the versions of the package.

    "vega": "^5.9.1",
    "vega-embed": "^6.2.2",
    "vega-lite": "^4.4.0",
    "vega-typings": "^0.12.4",
    "vega-util": "^1.12.2",

**Comment by domoritz** [comment]
Thanks for posting the issue. Can you please provide a minimal example that demonstrates the problem?

**Comment by kanitw** [comment]
You can use the legend's [`columns` property](https://vega.github.io/vega-lite/docs/legend.html#symbol-layout), to limit the number of items per entries for now. 

Making the legend automatically wrap items is much harder and would require modifications in Vega, 
so I don't think we will fix that soon (and the issue should be considered a Vega issue).  If you would like have to such feature, please file a separate feature request in the Vega repo.
