### ISSUE TITLE
Zoom/Click functionality on ipadOS

### ISSUE THREAD

**Issue by saptarshiguha** [vega/vega-lite#5945]
Not sure if this feature or bug, but it would be nice to have 

a) zoom like functionality working in ipadOS
b) being able to click on points for tooltips in ipadOS (it works just _sometimes_)

For reference, see this website: https://metrics.mozilla.com/public/sguha/mc2/missioncontrol_v2.html

On the desktop, i can click on points to see the tooltips, and I can click on an OS legend and then zoom in to see the dots (and error bars) on a finer scale.

I can’t do any of those interactions (except clicking on a legend to show only one OS) on ipadOS.

Many thanks for the excellent tool, vegalite.

**Comment by domoritz** [comment]
Hi @saptarshiguha. It's awesome that you are using Vega-Lite. This issue is already covered by https://github.com/vega/vega-lite/issues/4661, I think.

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/issues/4661 is fixed now. Not all interactions work yet but we added support for touch events in addition to click.
