### ISSUE TITLE
Axis domainWidth should be included in labels padding

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#5946]
When the axis baseline is thickened due to `domainWidth` being set, the axis labels are not moved out beyond the line, which can lead to label occlusion. The labels should be offset by `domainWidth`/2, similar to how the `tickSize` factors into the label padding.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal", "axis": { "domainColor": "green", "domainWidth": 20 } },
    "y": {"field": "b", "type": "quantitative", "axis": { "domainColor": "red", "domainWidth": 60 }}
  }
}
```

![visualization-2](https://user-images.githubusercontent.com/659086/74980663-e0690900-53fe-11ea-8fe8-bfea2ef33d53.png)

**Comment by domoritz** [comment]
Is this a Vega or Vega-Lite issue?

**Comment by marcprux** [comment]
Vega. Sorry about that … I'll make a new issue there.

**Comment by domoritz** [comment]
Thank you. No need to apologize. I appreciate the effort you put into tracking down the issue.
