### ISSUE TITLE
Escape field doesn't work when type is quantitative

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5950]
When I create this chart : 
```
{
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\\\' Name", "type": "nominal"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}
```

it works :
<img width="103" alt="image" src="https://user-images.githubusercontent.com/354149/75020582-515a0080-5493-11ea-898a-d699c2c84ec2.png">

But if I change type to 'quantitative' : 

```
{
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\\\' Name", "type": "quantitative"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}

```

it doesn't work anymore: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/354149/75020686-7fd7db80-5493-11ea-9fb8-b4c9fad241b6.png">

And the axis label should be unescaped : 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/354149/75020925-e6f59000-5493-11ea-8c3e-b525482c97dd.png">

**Comment by domoritz** [comment]
Interesting bug. Thanks for finding the small example. I wonder where we are not escaping/unescaping correctly.

**Comment by domoritz** [comment]
Shouldn't the spec be

```json
{
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\' Name", "type": "quantitative"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}
```

You only want to escape the ' but not the \, right?

**Comment by domoritz** [comment]
Or 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class' Name", "type": "nominal"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}
```

Since ' is not an indicator for nesting (. or []).

**Comment by domoritz** [comment]
Which leads to `Access path missing closing quote: Class' Name` but that's a Vega issue. 

Can you confirm that my hunch is right?

**Comment by christophe-petitjean** [comment]
According to the doc https://vega.github.io/vega-lite/docs/field.html, I have to escape 4 times the '. And it works but not when encoding is of `quantitative` type.
```
{
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\\\' Name", "type": "quantitative"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}

```

> Since ' is not an indicator for nesting (. or []).

I believe it is (still from the doc), you can type `"foo['bar']"`

**Comment by domoritz** [comment]
Ahh, I take back what I said. I'll take another look.

**Comment by domoritz** [comment]
Ahh, here is the issue. `'` does not actually need to be escaped because we use `"` to quote strings. 

If I change 
```
"expr": "isValid(datum[\"Class\\\\' Name\"]) && isFinite(+datum[\"Class\\\\' Name\"]) && isValid(datum[\"Survived\"]) && isFinite(+datum[\"Survived\"])"
```

to

```
"expr": "isValid(datum[\"Class' Name\"]) && isFinite(+datum[\"Class' Name\"]) && isValid(datum[\"Survived\"]) && isFinite(+datum[\"Survived\"])"
```

in the generated Vega, it works. 

However, you cannot not escape the quote in Vega-Lite or you get `Access path missing closing quote: Class' Name`.

**Comment by domoritz** [comment]
Since we escape `]` like

```
{
  "data": {"values": [{"Class] Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\] Name", "type": "quantitative"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}
```

we also need

```
{
  "data": {"values": [{"Class' Name": 13, "Survived": 78}]},
  "mark": {"type": "point"},
  "encoding": {
    "x": {"field": "Class\\' Name", "type": "quantitative"},
    "y": {"field": "Survived", "type": "quantitative"}
  }
}
```

See https://github.com/vega/vega-lite/pull/5966 for the fix.
