### ISSUE TITLE
Merging scales for different marks may lead to unexpected results

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5952]
I got a warning `[Warning] Conflicting scale property "range" ([1,10] and [1,100]). Using [1,10].` on this spec : 
```
{
  "data": {
    "values": [
      { "Month": "January", "Temperature": 14.7, "Count": 100, "Fatalities": 1300},
      { "Month": "February", "Temperature": 16.4, "Count": 10, "Fatalities": 102},
      {"Month": "March", "Temperature": 18.7, "Count": 1980, "Fatalities": 300}
    ]
  },
  "encoding": {
    "x": {"field": "Month", "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  },
  "layer": [
    {
      "mark": "bar",
      "encoding": {
        "size": {
          "field": "Count",
          "type": "quantitative",
          "scale": {"range": [1, 10]}
        }
      }
    },
    {
      "mark": "point",
      "encoding": {
        "size": {
          "field": "Fatalities",
          "type": "quantitative",
          "scale": {"range": [1, 100]}
        }
      }
    }
  ]
}
``` 
But these 2 scales are on different mark types and shouldn't conflict each other

**Comment by domoritz** [comment]
Good catch. I see two solutions here. One is that we somehow figure out in what cases a scale should be independent. Do you have an idea what the rule should be? Second, we could always make scales independent when scales conflict.


Anyway, I’m not sure whether this is really a bug. You can set the size scale to independent and Vega-Lite won’t merge them. 

I’ll mr, this as an enhancement but we need to know what the rule for keeping scales independent should be. I don’t think that size scales should always be independent.

**Comment by christophe-petitjean** [comment]
Oh I didn't think of making scale independent! Thanks, it should solve a some of my issues. 

But it makes me think about something related : if I have 3 marks (3 layers) with 1 size encoding for each, how can I make 2 size scale shared and the other independent ? Simply put, how can I group scales (or axes) ? 

I don't know how to make scales independent or not automatically. I didn't give long thoughts to it but shouldn't we try to merge positional axis (x, y, latitude, start, ...) and don't merge 'legend' axis (color, size, opacity, ...) ?

**Comment by domoritz** [comment]
> Simply put, how can I group scales (or axes) ?

You create a layer with one spec and a layered spec which itself is two layers. 

>  I didn't give long thoughts to it but shouldn't we try to merge positional axis (x, y, latitude, start, ...) and don't merge 'legend' axis (color, size, opacity, ...) ?

Color should be merged by default, I think. Imagine a line with points over it. It would be odd not to merge.

**Comment by domoritz** [comment]
I think in your particular example, using size for bars is highly discouraged anyway so I'd need to see some other examples where scale merging by default leads to bad results.

**Comment by christophe-petitjean** [comment]
We tried in this example to have size scale for the bubble bound to fatalities and size scale for the bars bound to number of operational_count by year: 
![image](https://user-images.githubusercontent.com/354149/75052293-a3b91280-54cf-11ea-9676-bccda286b624.png)

But it will work with independent scales :)

> You create a layer with one spec and a layered spec which itself is two layers.

Thanks for this, I have to try it

**Comment by domoritz** [comment]
Okay, sounds like we don't know what to change here so I'll close the issue. Feel free to add comments.
