### ISSUE TITLE
Tooltips not showing for rounded bars

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5956]
Tooltips fail to display on rounded bars. Here is an example ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBnAUwXhzIFoB3C+ACzKwDoBjEgN0gF8ANOCgcA9gDsOCfAG1hEUBCVQAtrCwBrfIuVLI8AJ4AHMvkgAjdZCG69YrONYAlWNACWGEgBVRRgDJkAGbw+ADMNrYiog7Orh7evk5uAOZMIaih8kqCWRCQZJKi7uLJ2rl6AB7a+samqJDRxbB4AlCBbmQ40GaEpq36bipkAKribumqEsz8EbaQBtWGJmYAjhiw4vDjCG7cfVCwyclYZMkIdVEYmzPleWI40Yu1ZuKiKm7izdZtHV1mDAgWFgbpEoPBRKIcFsjE9lvVXu9Pi0fp1uvUAcxWPxynwsjllDplJA1JozJZgbM9AUxMVSqhCbpIFV6TU4VBGh8vv12qieudvgMhqNxmYVFMmCDIvNYRdIGsNltEFs9gLDsdTvz6mIriF8VL7o8WUtZQjOcjIDy-ujGEDJXNwZDoTKXm8zQLLWioBjbbjbL7ssIALogPhAA)):
```json
{
  "data": {"url": "data/seattle-weather.csv"},
  "concat": [
    {
      "mark": {
        "type": "bar",
        "cornerRadiusTopLeft": 3,
        "cornerRadiusTopRight": 3
      },
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "aggregate": "count"},
        "color": {"type": "nominal", "field": "weather"},
        "tooltip": {"type": "nominal", "field": "weather"}
      }
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "aggregate": "count"},
        "color": {"type": "nominal", "field": "weather"},
        "tooltip": {"type": "nominal", "field": "weather"}
      }
    }
  ]
}
```
![visualization (59)](https://user-images.githubusercontent.com/781659/75073777-0817aa00-54af-11ea-8011-644e4f1a3e68.png)

In the left panel, tooltips fail to display. In the right panel, tooltips display as expected. The only difference is the specification of ``cornerRadiusTopLeft`` and ``cornerRadiusTopRight``.

**Comment by donghaoren** [comment]
If you use the SVG renderer it works. It won't work in the canvas renderer. The issue could be in Vega's canvas handler.

Related to #5841

**Comment by PBI-David** [comment]
@domoritz - I believe this can be closed
