### ISSUE TITLE
Nested facets invalid in Vega-Lite 4.4

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5960]
I'm attempting to upgrade Altair to Vega-Lite 4.4, and am blocked by the fact that some specs that were valid under 4.0 are now invalid under the 4.4 schema.
```python
import jsonschema
import json
import urllib.request
with urllib.request.urlopen('https://vega.github.io/schema/vega-lite/v4.0.0.json') as f:
    schema4_0 = json.load(f)
with urllib.request.urlopen('https://vega.github.io/schema/vega-lite/v4.4.0.json') as f:
    schema4_4 = json.load(f)

spec = {
  "data": {"url": "data.csv"},
  "facet": {"column": {"field": "B", "type": "nominal"}},
  "spec": {
    "encoding": {"row": {"field": "A", "type": "nominal"}},
    "mark": "point"
  }
}
jsonschema.validate(spec, schema4_0)  # pass
jsonschema.validate(spec, schema4_4)  # fail
```
It appears that encoding-based facets can no longer be nested within facet specs. Is this change intended? If so, we will have to rework a number of Altair examples, tests, and documentation in order to move beyond Vega-Lite 4.0.

**Comment by domoritz** [comment]
Thanks for flagging this. Even though I would encourage 

```json
{
  "data": {"url": "data.csv"},
  "facet": {"column": {"field": "B", "type": "nominal"}, "row": {"field": "A", "type": "nominal"},
  "spec": {
    "mark": "point"
  }
}
```

we should not break the example. To me, this is an unintended regression.

**Comment by jakevdp** [comment]
The regression appears to have been introduced in version 4.1.

Regarding the alternative specification: the outputs of these two approaches differ in the presence of ``resolve_scale``, so it's not entirely identical.

**Comment by domoritz** [comment]
Good point. I'll look into this.

**Comment by domoritz** [comment]
Hmm, odd. Typescript accepts the spec happily.

<img width="429" alt="Screen Shot 2020-02-22 at 18 14 52" src="https://user-images.githubusercontent.com/589034/75102376-44c2ce80-559f-11ea-99da-0fddf46d1ce2.png">

**Comment by domoritz** [comment]
But it also doesn't work in the editor.

<img width="783" alt="Screen Shot 2020-02-22 at 18 16 11" src="https://user-images.githubusercontent.com/589034/75102389-75a30380-559f-11ea-99ad-564a834cc3f2.png">

**Comment by domoritz** [comment]
I know we have some issues with facet of facet that require some attention but I'm puzzled why the schema doesn't allow this spec. We improved the schema generator in the last few releases so maybe this regression came in through that. Or this issue is caused by the refactoring UnitSpecWithFrame.

**Comment by domoritz** [comment]
😕 What type is typescript using?

<img width="445" alt="Screen Shot 2020-02-22 at 18 28 23" src="https://user-images.githubusercontent.com/589034/75102490-25c53c00-55a1-11ea-8e79-773d55b5c54f.png">

**Comment by domoritz** [comment]
I'm not sure why ts didn't flag this but I submitted a fix.

**Comment by jakevdp** [comment]
Thanks!

**Comment by domoritz** [comment]
Thank you @jakevdp for maintaining Altair and writing up this clear issue report.

**Comment by kanitw** [comment]
This was intentional since there are many cases that facet of facet are broken, and thus should not be counted as officially supported yet -- see https://github.com/vega/vega-lite/issues/2760#issuecomment-320377512.  

Facet spec are not allowed inside facet spec, either.  So I don't think facet encoding should be allowed.

**Comment by domoritz** [comment]
Since 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data.csv"},
  "facet": {"column": {"field": "B", "type": "nominal"}},
  "spec": {
    "facet": {"column": {"field": "B", "type": "nominal"}},
    "spec": {"mark": "point"}
  }
}
```

Is also not allowed right now, I agree that this is expected. 

I don't think we can fix facet of facet in the next release but will support it eventually. Until then, Altair needs to be updated. Sorry for making this difficult.
