### ISSUE TITLE
Version 4.4 schema contains empty "Conditional" definition

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5965]
https://github.com/vega/schema/blob/eb980f76b33e80c885e18fcd1f697ae1cc51b911/vega-lite/v4.4.0.json#L3173-L3174

I discovered this because it happened to exercise an unhandled corner-case of Altair's schema processing.

I'm not sure whether this is intentional, but it seems strange, particularly because ``"definitions/Conditional"`` only appears within ``anyOf`` statements: this means that it completely negates the validation of other condition options, because regardless of what you put in the condition field, it will be valid under an empty schema definition.

**Comment by kanitw** [comment]
Thanks Jake.   That was  a bug.  We fixed this in https://github.com/vega/vega-lite/pull/5958/files#diff-981efb90b1f4dd2524f166fa00580869L17198.  The next version should clear this.
