### ISSUE TITLE
Make domain properties AxisConditionable

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5976]
Like there are grid, label or tick properties that can have conditions, it would be interesting to be able to add conditions to `domainOpacity`, `domainWidth` and `domainColor`.

I don't know if it's possible though

**Comment by domoritz** [comment]
Can you provide some more details? What would these properties be conditioned on? There is only one domain per axis so I’m not sure what the conditions should be. What are the use cases?

**Comment by christophe-petitjean** [comment]
Yes I know there is only one domain, that's why I'm not sure it's possible but I'd like something like the trail mark for domain where width/opacity/color can be different all along the domain.

The use case will be to highlight a part of the domain : for example when you do a rectangular selection, we could show on the domain which part of the x/y axis are selected. It could also be a replacement for a full height `rect` mark to highlight a part of the chart

**Comment by domoritz** [comment]
Hmm, I don’t think that should be part of the domain. Maybe instead just put a mark on top of the axis. That would already be possible.

**Comment by christophe-petitjean** [comment]
But is it always possible to put a mark on the axis ? For example, will I be able to put a mark on the axis if I add some offset to the axis, like this: 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/354149/75272409-21e22580-57fe-11ea-8b8e-797525a5d4ed.png">

**Comment by domoritz** [comment]
Sure, you can draw outside the main chart area with negative values.

**Comment by christophe-petitjean** [comment]
Ok. Thanks for the advice. I'm closing the request

**Comment by domoritz** [comment]
Thanks for posting the idea!
