### ISSUE TITLE
labelExpr not recognised when used in config

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#5983]
Vega-lite 4.4 now supports `labelExpr` as part of an axis configuration, but it appears not to be honouring the config.

Here's a minimal working example. `TickCount` does work, but `labelExpr` is ignored. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "config": {
    "axisY": {
      "labelExpr": "datum.label+'%'",
      "tickCount": 20
    }
  },
  "data": {
    "values": [
      {"x": 1, "perc": 10},
      {"x": 2, "perc": 20},
      {"x": 3, "perc": 30},
      {"x": 4, "perc": 40}
    ]
  },
  "encoding": {
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "perc", "type": "quantitative"}
  },
  "mark": {"type": "line"}
}
```

When the same `labelExpr` is applied directly to the axis spec (i.e. `"y": {"field": "perc", "type": "quantitative", "axis": {"labelExpr": "datum.label+'%'"}}`), it does behave as expected.

**Comment by kanitw** [comment]
Thanks! 
Will be fixed in https://github.com/vega/vega-lite/pull/6016.
