### ISSUE TITLE
labelOffset incorrectly typed as String in schema

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#5985]
The VL 4.4 `labelOffset` is currently typed as having a `string` parameter. Presumably this should be `number`.

I realise the implementation is temporary pending the next Vega release but presumably the API will remain unaffected. Possibly related, but is there a reason why there is currently no config option for `labelOffset` (there is, for example, for `tickOffset`)?

**Comment by domoritz** [comment]
Thank you. Fixed in https://github.com/vega/vega-lite/pull/5991.
