### ISSUE TITLE
Add text to the view (or: multiple titles)

### ISSUE THREAD

**Issue by dechamps** [vega/vega-lite#5997]
I would like to add some text to an existing chart. The text is not part of the data and just provides additional copyright/attribution information. I would like to position it at the bottom of the *view* (not the plot area).

It doesn't look like there's any way to do that in Vega-Lite. One obvious approach is to use `title`, but the chart already has a title and I don't want to change it. I tried using `layer` with different titles in the outer spec and the inner spec, but the one in the outer spec just overrides the one in the inner spec. I also tried using `layer` and text marks with static data but couldn't really get anywhere (and that felt very wrong, anyway).

I guess what I'm looking for is a way to set multiple titles, with different style and positioning.

**Comment by domoritz** [comment]
Thank you for the idea. You can already use concat to add another chart with only text. We could make it easier to create marks without encodings. If you think that's necessary, please file another issue. Closing as we would need a more concrete proposal about the spec design.

**Comment by dechamps** [comment]
Thank you so much! It didn't occur to me to concatenate with a "dummy view" with a title. It works pretty well - I had to hack around a bit to set the width, height and opacity of the dummy view to zero, but I did manage to obtain the desired end result.

**Comment by domoritz** [comment]
Great. I think spec with only a single mark (and no encoding) could also be useful in the future. 

Btw, I think Vega-Lite would benefit from a source footer in addition to a title but I have not had the cycles to think how/implement it.
