### ISSUE TITLE
Remove Max Length calculation 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#600]
Vega-lite use a `maxLength` method to calculate `axisTitleOffset` in layout.js 
We need to make sure that maxLength calculation is always correct.  

## Time Field 

Current we only correctly calculate max length for temporal field if the default timeFormat (`'%A %B %e %H:%M:%S %Y’`) is used.  

We have a `LONG_DATE` variable for 'Wednesday September 17 04:00:00 2014'
as Wednesday is the longest date and September is the longest month.

## Other

**TODO** revise `getMaxLength` in layout.js and write more detail about this

**Comment by kanitw** [comment]
From our conversation with @jheer & @domoritz , this will be fixed at the Vega level.

**Comment by domoritz** [comment]
Closing as it has been addressed.

**Comment by kanitw** [comment]
Hmm, I think there is still the method to be removed in layout.ts

**Comment by kanitw** [comment]
closed as of #800
