### ISSUE TITLE
Remove concat type from concat model and use only column instead

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6023]
vconcat and hconcat are just concat with different numbers of rows

**Comment by kanitw** [comment]
I don't see why we need to move this to normalizer yet?  
Moving everything to normalize also means we will generate many more normalized specs, bloating our PRs. 

Since there is already only one ConcatModel, I don't see why this is gonna be useful.

**Comment by domoritz** [comment]
We have some code that distinguishes in assemble and it is probably not as clean as it could be. But maybe some refactoring is enough. I’ll take a look at some point to see what makes sense.

**Comment by kanitw** [comment]
> We have some code that distinguishes in assemble and it is probably not as clean as it could be.

This sounds pretty vague, can you point to a specific problematic line?

**Comment by domoritz** [comment]
I will remove the concat type from the model and instead only use column. That should simplify things enough.
