### ISSUE TITLE
Update add Vega 5.10 features

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6032]
-  [x] Top-level properties (`autosize`, `background`, `padding`, `width`, `height`) accept signal references, such as `{"signal": "<expr>"}`, which map to a signal definition's `update` property. If the top-level `signals` array contains an entry that matches one of these properties, the definitions will be merged, with precedence given to the properties defined in the `signals` array.

- [x] Vega views now include [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) attributes on the view container DOM element. The [`role` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques) is set to [`"figure"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role), and the [`aria-label` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) is set to the specification `description` property. 

- The `aggregate` and `window` transforms support the `product` operation to multiply values.
  - [x] fix vega-typings
  - [ ] update to the latest vega-typings 

- [ ] The config supports a top-level `lineBreak` option for setting a global default for text line breaks. This property should be a string or regexp value, or a corresponding signal reference.
- [x] Support for text `baseline` values `line-top` and `line-bottom`. These values are similar to `top` and `bottom` baselines, but calculated relative to the `lineHeight` rather than `fontSize` alone.

- Support for color blend modes via the new `blend` encoding channel. The allowed values are: `multiply`, `screen`, `overlay`, `darken`, `lighten`, `color-dodge`, `color-burn`, `hard-light`, `soft-light`, `difference`, `exclusion`, `hue`, `saturation`, `color`, `luminosity`. For Canvas rendering, the blend is set via the context 2D `globalCompositeOperation` property. For SVG rendering, the blend is set via the CSS `mix-blend-mode` style. The default Vega value is `null` (or `undefined`), which maps to the default values `"source-over"` (for Canvas) and `"normal"` (for SVG). For more, see the [Canvas `globalCompositeOperation`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) and [CSS `mix-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) documentation, including limitations in cross-browser support.
  - [x] fix vega-typings
  - [ ] update to the latest vega-typings 

- [x] Add axis `labelOffset` property to adjust axis label position in addition to `tickOffset`, and `labelLineHeight` to set the line height for multi-line axis labels.

**Comment by jakevdp** [comment]
Does this mean Vega-Lite 4.5 should not yet be used with Vega 5.10?

**Comment by domoritz** [comment]
> Does this mean Vega-Lite 4.5 should not yet be used with Vega 5.10?

No, you can use it. With this pull request, we will leverage/support the new features of the Vega release.

**Comment by kanitw** [comment]
Yep, I'm changing the title to be "Update add Vega 5.10 features"

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/6033
