### ISSUE TITLE
header.labels throw an error when set on a column facet

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#6044]
This spec will throw an error: 
```
{
  "data": {"url": "data/population.json"},
  "mark": "bar",
  "encoding": {
    "column": {
      "field": "sex",
      "type": "nominal",
      "header": {"title": null, "labels": false}
    },
    "y": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative"
    },
    "x": {"field": "age", "type": "ordinal"}
  }
}
```
But the same on a `row` facet will work. And if you change `labels` to `true`, it works too.

**Comment by domoritz** [comment]
What’s the error?

**Comment by christophe-petitjean** [comment]
`TypeError: null is not an object (evaluating 'e.role')`

**Comment by domoritz** [comment]
Ahh, this is no bueno

<img width="445" alt="Screen Shot 2020-03-12 at 11 12 09" src="https://user-images.githubusercontent.com/589034/76553999-525ace00-6452-11ea-97c2-bcf6ff52e5f0.png">

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6078
