### ISSUE TITLE
Incorrect tooltip in Normalized Stacked Area Chart

### ISSUE THREAD

**Issue by syntagmatic** [vega/vega-lite#6052]
The area chart appears to show underlying data values, formatted as a percentage.

<img width="585" alt="Screen Shot 2019-09-24 at 10 56 47 PM" src="https://user-images.githubusercontent.com/156229/65573011-a9113180-df1e-11e9-9022-1f303bd23bcd.png">

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6108
