### ISSUE TITLE
Temporal scale domains broken in vega-lite 4.5

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6060]
First reported in https://stackoverflow.com/questions/60623578/how-do-i-set-the-max-and-min-of-the-x-axis-of-vega-lite-time-series-chart/60623883

Here is an example spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"ts": 1500400000000, "v": 1},
      {"ts": 1500500000000, "v": 2},
      {"ts": 1500600000000, "v": 3},
      {"ts": 1500700000000, "v": 2}
    ]
  },
  "width": 800,
  "height": 300,
  "mark": {"type": "line"},
  "encoding": {
    "x": {"field": "ts", "type": "temporal", "scale": {"domain": [1500000000000, 1500900000000]}},
    "y": {"field": "v", "type": "quantitative", "scale": {"domain": [0, 5]}}
  }
}
```
In Vega-Lite 4.4, the result is this:
![visualization - 2020-03-10T113016 527](https://user-images.githubusercontent.com/781659/76347010-252be580-62c3-11ea-8e36-e92530bb7381.png)

In Vega-Lite 4.5, the result is this:
![visualization - 2020-03-10T113440 545](https://user-images.githubusercontent.com/781659/76347026-29580300-62c3-11ea-9042-911587cab756.png)

**Comment by kanitw** [comment]
@domoritz  Looks like https://github.com/vega/vega-lite/pull/5957 is wrong. 

Currently the spec outputs:

```
{
        "fields": [
          {"signal": "datetime(1500000000000)"},
          {"signal": "datetime(1500900000000)"}
        ]
      }

```

But if we revert to:

```
 [
          {"signal": "{data: datetime(1500000000000)}"},
          {"signal": "{data: datetime(1500900000000)}"}
        ]
```

It works correctly.

**Comment by SyntaxRules** [comment]
Here is a another use case for the same bug: [Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4AgUCIEQCYKYGcDGAnAlgBwC5oPYDsoAuaAQRATQFsMAbOEAIwEMUQkALVrEAdzSwcQKZvgDmcGCBjMszEAApmAa3kBxUVh4BhLiiwBKAHRQANBGgy5xEMAuQoAN2a0ArohsBte5FtQ5CMo2UKRmUAhy+sEATAAMAIwAHAC0CanxZtBw+DAxCSlpsQDMUAC+5r6+wP7MgcEAQmER3HlJ6anRmVDZuSRQcW2FiWUVlX4BQX3aTZFYrQXxqQCsXT3z7fGxZT4AuhblFlBUrJPQLChmh9lIuDBo4jZ2lVAAno9QAGZocLS90BNdLAvDBwYK4FB3fAuEY+KAAD0ePgcXx+f3Cs0ySP+wNBfSwcBo4Oho2eyBcuL8MFwx3uXn6sTi7WinVM0Di0QA7O0ElAdgcxtBmHC0AhEQKBZ9wcc5n0AKQATUu4rGUHB33wMrOuC01KVyt8-gE9GC2kVWNK5pJ0DhnRI1RRv2Ca1Z-hxwXxhJEtG2kAtpSAA)

**Comment by domoritz** [comment]
Looks like it's not the same. @SyntaxRules can you file a separate issue?

<img width="1138" alt="Screen Shot 2020-03-10 at 14 03 24" src="https://user-images.githubusercontent.com/589034/76359164-f0765900-62d7-11ea-9352-77f29a6412e5.png">

**Comment by kanitw** [comment]
I think it's the same.

**Comment by domoritz** [comment]
Hmm, the screenshot above is from master just now.

**Comment by SyntaxRules** [comment]
@domoritz Issue created per your request. Testing this on the version 4.6.0 online editor produces the same error state.

Issue here: https://github.com/vega/vega-lite/issues/6068

**Comment by domoritz** [comment]
Thank you
