### ISSUE TITLE
Add Texture to Charts

### ISSUE THREAD

**Issue by katykoenig** [vega/vega-lite#6062]
Hi All,

I was wondering a texture/patterning channel could be added to the encoding object as a way to provide alternative/redundant encodings of data. I noticed a related issue regarding accessibility, #4244, so I hoping you could add this feature as well to ensure more accessible visualization are made using this library.

Doubly encoding variables with texture/patterns in addition to color allows data visualizations to be more easily comprehended by viewers with visual impairments. Some [prior](https://uxdesign.cc/designing-for-accessibility-is-not-that-hard-c04cc4779d94) [works](https://keen.io/blog/accessibility-in-data-vis/) have highlighted re-encodings of this type as a best practice for increasing the accessibility of plots.  There is some [additional work](https://psycnet.apa.org/record/2017-16724-001) that suggests that redundant encodings of data are also beneficial to viewers with no visual impairments (what's good for the goose is good for the gander if you will). 

Several other charting libraries feature similar features (such as [semiotics sketchy-painty-patterns](https://semiotic.nteract.io/guides/sketchy-painty-patterns) or [matplotlib's hatching](https://matplotlib.org/3.1.1/gallery/shapes_and_collections/hatch_demo.html)). On a sketchy note: patterns could be implemented as both categorical/nominal variables as well as quantitative variables (ala wood & co's [sketchy rendering](https://openaccess.city.ac.uk/id/eprint/1274/1/wood_sketchy_2012.pdf)). At the very least it seems like it would be good to expose a pattern attribute for some mark types, just for like, styling purposes.

It appears from [this](https://groups.google.com/forum/#!msg/vega-js/_3JwxvraWCQ/WGERWhqfBgAJ) post that vega supports patterning? Although playing around with the example from that link I had a somewhat difficult time getting the chart to run 😅.

**Comment by domoritz** [comment]
Is this issue already covered by https://github.com/vega/vega/issues/1372?

**Comment by katykoenig** [comment]
> Is this issue already covered by vega/vega#1372? It would make using patterns much easier.
I'm not sure! I'm not much of a vega user, so I'm not really sure how to comment?

> Yes, you can add patterns already but it'snot intuitive and doesn't work with the Canvas renderer.
That sounds great! Can you point me to an example of how to do that?

**Comment by domoritz** [comment]
Okay, I'm going to close this issue since we would need to implement patterns in Vega first. 

If you want patterns now, use the SVG renderer and modify the generated SVG to use linked patterns as hinted at in https://github.com/vega/vega/issues/1372. Not that we are only giving a hint towards implementing patterns and most of it would be up to you. Again, I would not recommend using patterns right now and instead, we need someone to take on the task of implementing patterns properly.
