### ISSUE TITLE
Right-aligned legend label overlaps symbol

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6063]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.5.1.json",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
      "field": "Origin",
      "type": "nominal",
      "legend": {"labelAlign": "right"}
    },
    "shape": {"field": "Origin", "type": "nominal"}
  }
}
```

<img width="313" alt="Screen Shot 2020-03-10 at 21 08 05" src="https://user-images.githubusercontent.com/659086/76372269-3e5c8280-6313-11ea-8869-b5b8ef5e48a2.png">

One solution might be to move the symbol to the right of the label when it is right aligned. However, the issue also occurs with `labelAlign` set to `center`.

**Comment by domoritz** [comment]
I think this is working as expected. You need to add some offset to the labels. 

If you disagree, please file this against Vega.

**Comment by marcprux** [comment]
Actually, it looks like I already did (over a year ago). https://github.com/vega/vega/issues/1751

**Comment by domoritz** [comment]
Ahh, sorry that nobody has taken on the issue yet but I think going through Vega is the right thing. Thanks for finding the issue!
