### ISSUE TITLE
Regression: Axis->Scale->Domain no longer accepts isoformat date strings (i.e "2020-03-11")

### ISSUE THREAD

**Issue by SyntaxRules** [vega/vega-lite#6068]
See this example in the [Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4AgUCIEQCYKYGcDGAnAlgBwC5oPYDsoAuaAQRATQFsMAbOEAIwEMUQkALVrEAdzSwcQKZvgDmcGCBjMszEAApmAa3kBxUVh4BhLiiwBKAHRQANBGgy5xEMAuQoAN2a0ArohsBte5FtQ5CMo2UKRmUAhy+sEATAAMAIwAHAC0CanxZtBw+DAxCSlpsQDMUAC+5r6+wP7MgcEAQmER3HlJ6anRmVDZuSRQcW2FiWUVlX4BQX3aTZFYrQXxqQCsXT3z7fGxZT4AuhblFlBUrJPQLChmh9lIuDBo4jZ2lVAAno9QAGZocLS90BNdLAvDBwYK4FB3fAuEY+KAAD0ePgcXx+f3Cs0ySP+wNBfSwcBo4Oho2eyBcuL8MFwx3uXn6sTi7WinVM0Di0QA7O0ElAdgcxtBmHC0AhEQKBZ9wcc5n0AKQATUu4rGUHB33wMrOuC01KVyt8-gE9GC2kVWNK5pJ0DhnRI1RRv2Ca1Z-hxwXxhJEtG2kAtpSAA)

![](https://user-images.githubusercontent.com/589034/76359164-f0765900-62d7-11ea-9352-77f29a6412e5.png)

This affects versions 4.5.x and 4.6.0. Works in 4.4.0.

When strings are passed in axis->scale->domain, the chart no longer functions. For example: `"scale": {"domain": ["2020-01-22", "2027-01-01"]}`. Removing this line makes the chart work again. 

Initial discussion: https://github.com/vega/vega-lite/issues/6060

**Comment by domoritz** [comment]
<img width="429" alt="Screen Shot 2020-03-11 at 21 18 29" src="https://user-images.githubusercontent.com/589034/76486862-dcb51a80-63dd-11ea-8523-2757e6728f2b.png">

**Comment by domoritz** [comment]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with ranged data (aka Gantt Chart).",
  "data": {
    "values": [
      {"task": "A", "start": "2018-01-01", "end": "2019-01-03"},
      {"task": "B", "start": "2018-01-02", "end": "2019-03-08"},
      {"task": "C", "start": "2018-01-05", "end": "2019-01-10"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "task", "type": "ordinal"},
    "x": {
      "field": "start",
      "type": "temporal",
      "scale": {"domain": ["2016-01-22", "2020-01-01"]},
      "axis": {"format": "%Y", "orient": "bottom", "title": "CY"}
    },
    "x2": {"field": "end"}
  }
}
```
