### ISSUE TITLE
rename `encoding` property to `mapping`

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#607]
To avoid confusion with the whole spec, which is also an "encoding" -- let's rename `encoding` property to `mapping` as it is the "encoding mapping" part of the encoding.  

- [ ] rename `enc.js` => `mapping.js`
- [ ] rename internal `_enc` => `_mapping`
- [ ] rename `encoding` property in vl spec => `mapping`

**Comment by kanitw** [comment]
@jheer – I discuss about this with @domoritz yesterday.  Any opinion on this?

**Comment by domoritz** [comment]
We discussed that we actually don't want to rename because 1) we want to keep the spec consistent 2) we should call our internal Encoding object Spec.
