### ISSUE TITLE
Header label/title positioning

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#6085]
Nice to have request: more control over the label positioning of the header. Given the following example:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/5186265/76571402-ae0b7280-64b7-11ea-9920-8ccdca3038c2.png">
[Editor-URL](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJg8u5GImww7dLrBIneMLETcA7oyXVLFDAAVQBlMEJuQlYxdCNlME1GWCtGdlZ4pTBuADMwdGpkMGpdblZifKVNYuQq5Gc-MAAmAAY2ujUNSE04zBxgSFZdMWwtXtJI6NjM+UUVAF91CEgrdCVYHO5dVFGAbQ0IAZzGMTx60e641lQ6AE9kJzAAXifmtpbIRYOwAfh0MXgMTiyAuPTw1zosGQAA9nq8mmAAPxgADkADE0P9kCiwDgUQBZLEotRQdCwC6FOq6T4aAC6Sygvk0LFGAxSyEIowAjAB2L7LDC6ADWF0c1IZkFq8G4SX8rO+kFK3nlEFVUGONk0FNq2nF32WeFuhBBpiU3FQfn+nTVyxQ6F1Kpty1i7BsZn8YhNYBaDKdkBdbok1BMUE9OTw1qdofQrrE7qQWwuOsjfoDYgACvbZdRRiIuVyWvqwPNvvzVZBbo61ZACiVhGcLrBrinyxqxFrTMaop6WwajV7IABHVhrIx4OKMKi90nQ5KslbMHudqJAzI0tVl5bQ+dtjukwoklb9i5bWVWzdQaViRP9IuQXfaqnTo-Gi5mi1KK2+8sILHz3RrAeOC7JAADEABsPIAKxcgAnAAzIeoF-AAHCh4FcpAtIlhuGglvMQA)

I'm currently not able to put the label of the row header on top of the chart. As can be seen the `Female` and `Male` labels are drawn below the grid. It is currently defined as such:

```
    "row": {
      "field": "gender",
      "type": "nominal",
      "header": {
        "labelAngle": 0,
        "labelAlign": "left",
        "labelAnchor": "end",
        "labelPadding": -110
      }
    }
```
Not sure if `labelPadding` should have an `x`, `y` option or if the upcoming `labelOffset` would be sufficient to solve this request.

**Comment by domoritz** [comment]
Can you explain what the Vega output should be?

**Comment by kanitw** [comment]
Hi, 

You can do this with `labelOrient: "top"`

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A trellis bar chart showing the US population distribution of age groups and gender in 2000.",
  "data": {"url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "width": {"step": 17},
  "mark": "bar",
  "encoding": {
    "row": {
      "field": "gender",
      "type": "nominal",
      "header": {"labelOrient": "top"}
    },
    "y": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative",
      "axis": {"title": "population"}
    },
    "x": {"field": "age", "type": "ordinal"},
    "color": {
      "field": "gender",
      "type": "nominal",
      "scale": {"range": ["#675193", "#ca8861"]}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/76696866-64549080-664d-11ea-9e56-07208fb3ec6d.png)

**Comment by mattijn** [comment]
Perfect! `"header": {"labelOrient": "top", "labelAnchor": "start"}` did the job. No idea why I didn't find `labelOrient`, since it is just in the docs. Thanks again!
