### ISSUE TITLE
Explicit legend title: null gets overridden by multi-view resolution.

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#6087]
According to the encoding docs, setting the legend `title` property to `null` should cause no title to be shown. This works fine with a single view. However, in a multi-view setup with a shared legend it seems that *all* participating encodings need to have `"title": null`, otherwise a default title is used. 

Is the current behavior by design, or a bug? My expectation was that a single *explicit* setting would disable the title, assuming no other participating encodings specify the title.

**Comment by domoritz** [comment]
That sounds like a bug. Explicit titles should override implicit titles.

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6096
