### ISSUE TITLE
Move encoding property definition's `sort` to be `scale`’s property

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#609]
The `sort` property in encoding property definition is similar to scale’s `sort` property in Vega 2 — so we should move it to be a part of `scale` property in encoding property definition for consistency.

**Comment by kanitw** [comment]
@domoritz  any objection?

**Comment by jheer** [comment]
I don't have a strong opinion on this issue, but I would just note that consistency with Vega 2, while important to consider, shouldn't necessarily win the day. If we think keeping `sort` in top level of an encoding leads to a better JSON syntax then we can stick with that.

**Comment by domoritz** [comment]
I don't have strong opinions either although I tend to like a more flat spec and think that sorting can be its own thing.

**Comment by kanitw** [comment]
@jheer That's true.  I could go either way too.  

It was a top-level property partly because we thought that users might not think about the existence of scale when they want to sort.   Given this reason and @domoritz's opinion, let's keep it a top-level property of an encoding definition object unless we get strong objection from the community.
