### ISSUE TITLE
trellis_area_seattle example has broken "view in editor" link

### ISSUE THREAD

**Issue by DougBurke** [vega/vega-lite#6099]
The "view this example in the online editor" link for https://vega.github.io/vega-lite/examples/trellis_area_seattle.html takes you to https://vega.github.io/editor/#/examples/vega-lite/trellis_area_seattle **but** instead of JSON you see a bunch of HTML (saying it can't find the file).

![wrong](https://user-images.githubusercontent.com/224638/76704618-a236d080-66b0-11ea-90b4-eb6aa344cee1.png)

**Comment by domoritz** [comment]
Will be fixed with the next editor update. For now, just copy the spec.
