### ISSUE TITLE
Add Index Transform

### ISSUE THREAD

**Issue by mcnuttandrew** [vega/vega-lite#6110]
There are number of vega-lite examples that require manual modifications of the data in order to work, usually involving special marks for either the end and start (such as in the [waterfall example](https://vega.github.io/vega-lite/examples/waterfall_chart.html)) or the addition incrementing counter (as in this [waffle plot](https://bl.ocks.org/amitkaps/d6648bd8ddb1c1e3706d7530126d1e2b)). I think it would be helpful to introduce a a simple transformation that could push some of those manipulations into the vega-lite and out of whatever containing system was preparing those features.

This transform would simply add an incrementing index across the data. There are few possible arguments that can be added here, such as offset (a numerical offset for the incrementer), special values for the start and end of increments, and a way to indicate the newly created column name. While i'm not especially wedded to any of those properties, using all of them in a transform might look like

```json
{
   "index": {"offset": 0, "markStartAs": "start", "markEndAs": "end", "as": "myIndex"}
}
```
Which given an initial data set like:

```json
[
{"country": "usa"}, 
{"country": "usa"}, 
{"country": "usa"}, 
{"country": "usa"}, 
{"country": "japan"},
 {"country": "japan"}, 
{"country": "japan"}, 
{"country": "europe"}
]
```

would transform it to be

```json
[
{"country": "usa", "myIndex": "start"}, 
{"country": "usa", "myIndex": 1}, 
{"country": "usa", "myIndex": 2}, 
{"country": "usa",  "myIndex": 3}, 
{"country": "japan", "myIndex": 4}, 
{"country": "japan", "myIndex": 5}, 
{"country": "japan", "myIndex": 6}, 
{"country": "europe", "myIndex": "end"}
]
```

**Comment by jakevdp** [comment]
Related: https://github.com/vega/vega-lite/issues/5975

**Comment by mcnuttandrew** [comment]
oo that's a total duplicate! I'll close this in favor of that
