### ISSUE TITLE
Cannot set month as expression in a DateTime definition object for scale domains

### ISSUE THREAD

**Issue by mcadams92** [vega/vega-lite#6128]
I am trying to set a default zoom for a chart using the scale-domain method like in [this](https://vega.github.io/vega-lite/docs/zoom.html) example in the documentation. However my x-axis is temporal and I want the domain to change over time so that the chart always shows the last 12 calendar months of data on first load (users then can look back and forward by interacting with the chart). 

I have no trouble setting the year and date values as expressions, but when setting `"month": "month(now())"` I get this error: `Invalid month: "month(now())".` The expression works fine when I put it into the year or date value, but something seems to be going wrong for the month value.

[Vega editor link to reproducible example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAY6AK1jcAdpAA04KABN0eTDlAQIkCujGtksbGADa2k2GCRWeRhIBe+nupwKANgB2OQBOaQBWAEYIgA4NKEJkACceHVtIACY5KNiROQBmEQKogBU5OSwKqoUKuQAtSABfLScIFzcPRm93NVtA0NyY2IighMgk1O50nCycvLlpYrlyyuqK+QrGlscTDvcvHz7-OiCogtHpMLHElLSM7Nz8iOKy9bXarebWtv2unt8-TowSCBTB4PGk3us0eCwCy1WNRqmwa3127VcB26Rz8YECQUymTicgCEUhd2mD3m+SCr0R7xR2x+Tj+h16uMCJMiUQC53JUxmUFh+TyJXpH0ZaLazkx-xxQICYUWRIiBX50KF1LCCPeyLqTPRMs6bMBJ2C4Qi2QiZNuAqpTyicjpuo2+qlv1lJuOeNOBWkQVimUVoXVlJh1KiUR1Hz1Xx20tZ2PZQNBcjOlti8VtGrmDsyzpjrrjzL2nqTpp9QWkgZy0gKIezYc1UVC+SjYpdn1R8Y9xvL3oUQQCmYuvICocFudbcnzmVi4tj3ZLGL7AIHp2kAX9mdBE-t06KHcLXYNCbLa45pzO0jnoyie-DLfySwKK07kp7LPP8pOQSCoUGc4qwfZtpxeI8kSLJdDUTC8UyuKJIlCEYQKnfJ4VfBcoNPXssTg38eUKIMwlQx5p1pCCGTdT9S1XH9KwCACRlCIIbQmClJzIkUC0gk93S-Ojk1-blMirApx0bTicmnVtMPfajlyNPD6MHCJpFCaTeVI6SREdHiqOLGDvyEn1YlfOttzVST9109s32PD9FNglS6FiBCokJGdtKfDz9IlBSjMEisFFCcSwoCcTtOyNs-MXHCBOUkyQo8ljshQ6zw2imcREyUIsL4miV0S4LgTc1UJPYu1MqdQpYuw5pdgAXW0HtIAwZIAGtbBcPAAE8kgyCRVGQTQoHgbgxG4ZIMmSZB0la2BkDEZB4BMlxqFSQUev6kbZkYVQ8BScwxFGyB2H2ycEAsaxmla5BVHGnR9uobrdkgAAPV7pUgAAzRglsnKFKUUyA+oG2ZDtQQgposTRDUgK7lq+6UoDB3bUcYVARsU0wdG4DB9tsBwUdLXrkHQabZjJimAApVG4AB3GmAEpmbAEQwCiU7UDUFgMh5g7EDpxmWeZ069EOjIJeQYWmdZ-iUZcanKagZXZdF7necQfmtfV+XxmlqX9Bl+m5bFppDQgZrpQtpwaMgXrut+-6xEnIK+nGNGMgAR1YdADuYHwqAaiALaaIA)

```json
{
  "mark": {"type": "line", "color": "red"},
  "selection": {"grid": {"type": "interval", "bind": "scales"}},
  "encoding": {
    "x": {
      "field": "period",
      "type": "temporal",
      "scale": {
        "type": "time",
        "domain": [
          {"year": "year(now()) - 1", "month": "month(now())", "date": 1},
          {"year": "year(now())", "month": "month(now())", "date": 1}
        ]
      }
    },
    "y": {"field": "utilization", "type": "quantitative"}
  }
}
```

[Setting month to `3` works fine but is not a good solution for my app](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgAY6AK1jcAdpAA04KABN0eTDlAQIkCujGtksbGADa2k2GCRWeRhIBe+nupwKANgB2OQBOaQBWAEYIgA4NKEJkACceHVtIACY5KNiROQBmEQKogBU5OSwKqoUKuQAtSABfLScIFzcPRm93NVtA0NyY2IighMgk1O50nCycvLlpYrlyyuqK+QrGlscTDvcvHz7-OiCogtHpMLHElLSM7Nz8iOKy9bXarebWtv2unt8-TowSCBTB4PGk3us0eCwCy1WNRqmwa3127VcB26Rz8YECQUymTicgCEUhd2mD3m+SCr0R7xR2x+Tj+h16uMCJMiUQC53JUxmUFh+TyJXpH0ZaLazkx-xxQICYUWRIiBX50KF1LCCPeyLqTPRMs6bMBJ2C4Qi2QiZNuAqpTyicjpuo2+qlv1lJuOeNOBWkQVimUVoXVlJh1KiUR1Hz1Xx20tZ2PZQNBcjOlti8VtGrmDsyzpjrrjzL2nqTpp9QWkgZy0gKIezYc1UVC+SjYpdn1R8Y9xvL3oUQQCmYuvICocFudbcnzmVi4tj3ZLGL7AIHp2kAX9mdBE-t06KHcLXYNCbLa45pzO0jnoyie-DLfySwKK07kp7LPP8pOQSCoUGc4qwfZtpxeI8kSLJdDUTC8UyuKJIlCEYQKnfJ4VfBcoNPXssTg38eUKIMwlQx5p1pCCGTdT9S1XH9KwCACRlCIIbQmClJzIkUC0gk93S-Ojk1-blMirApx0bTicmnVtMPfajlyNPD6MHCJpFCaTeVI6SREdHiqOLGDvyEn1YlfOttzVST9109s32PD9FNglS6FiBCokJGdtKfDz9IlBSjMEisFFCcSwoCcTtOyNs-MXHCBOUkyQo8ljshQ6zw2imcREyUIsL4miV0S4LgTc1UJPYu1MqdQpYuw5pdgAXW0HtIAwZIAGtbBcPAAE8kgyCRVGQTQoHgbgxG4ZIMmSZB0la2BkDEZB4BMlxqFSQUev6kbZkYVQ8BScwxFGyB2H2ycEAsaxmla5BVHGnR9uobrdkgAAPV7pUgAAzRglsnKFKUUyA+oG2ZDtQQgposTRDUgK7lq+6UoDB3bUcYVARsU0wdG4DB9tsBwUdLXrkHQabZjJimAApVG4AB3GmAEpmbAEQwCiU7UDUFhbCsyA9EOjIheQOnGZZ5n+JRlxqcpqA5fFpnWe53nEH58ZRZF-Qxfp5WpaaQ0IGa6VDacGjIF67rfv+sRJyCvpxjRjIAEdWHQA7mB8KgGogQ2miAA)

**Comment by domoritz** [comment]
Have a look at the generated Vega. I think you’re using an undocumented behavior that just happens to work in some cases. The better alternative would be to use the experimental signal support.

**Comment by mcadams92** [comment]
Ah I see, that would explain it, thanks @domoritz . 

I think #3818 would also also be a viable solution here if/when it gets implemented, as I could define the min and max domains as calculated fields and then reference them. 

In the meantime we'll look into another way to implement the feature, feel free to close the issue.

**Comment by domoritz** [comment]
Here is the solution (I think)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "mark": {"type": "line", "color": "red"},
  "selection": {"grid": {"type": "interval", "bind": "scales"}},
  "encoding": {
    "x": {
      "field": "period",
      "type": "temporal",
      "scale": {
        "type": "time",
        "domain": [
          {"signal": "datetime(year(now())-1, month(now()), 1)"},
          {"signal": "datetime(year(now()), month(now()), 1)"}
        ]
      }
    },
    "y": {"field": "utilization", "type": "quantitative"}
  }
}
```
