### ISSUE TITLE
Support labelFontWeight for facet header guide

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#6129]
According to the [`header` docs](https://vega.github.io/vega-lite/docs/header.html) there is no `labelFontWeight` option for header labels, while there is a `titleFontWeight`. FWIW I recently ran into a use case where I wanted to change the label font weight, but couldn't do so easily (I think I would need to change the style config). It would be helpful to make this configurable.

**Comment by kanitw** [comment]
Thanks @jheer  -- will be fixed in https://github.com/vega/vega-lite/pull/6130
