### ISSUE TITLE
Validate Vega-lite output against Vega’s Json schema

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#613]
(forked from #459)

Validating vega-lite output against Vega’s Json schema will help us catch our migration bugs.  That said, validating this everytime vega-lite is used might be an overkill — so we should find a middle ground.  

Maybe enable that just in `0.8` branch and then we remove it before we merge `0.8` to `master`?

**Comment by jheer** [comment]
Sounds like this should be part of the test suite, not normal Vega-Lite use?

**Comment by domoritz** [comment]
I agree with Jeff. Let's make it part of the tests and maybe the editor.

**Comment by kanitw** [comment]
That makes sense to me.  Maybe we have to refactor gallery.js and verify that all example specs produced legitimate vega specs.

**Comment by domoritz** [comment]
Not fixed in da4198b

**Comment by kanitw** [comment]
Partially addressed in #628 -- we should add a unit test that loads all the examples and verify if it produces sensible vega spec too.  Therefore, whenever we break the output a test is failed -- rather than having to rely on obscure `console.error` in the gallery.

**Comment by kanitw** [comment]
Done in #641
