### ISSUE TITLE
Eliminate fixed domain value for binned field 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#614]
Currently the output vega spec will have fixed domain computed in `scale.domain()`, instead of having fixed domain — output vega spec should dynamically calculate correct domain the bin scale. 

This might require a special transform / modification to the Vega’s  `bin` transform.

**Comment by kanitw** [comment]
Reading the code, we actually hard code the bin scale so that we have a spot for empty bin values. 
For example, if the bin transform output min = 0,   max = 10, step 2 — but there are no records with 4 values.   

If we just feed in the transformed field as domain we won’t get 4 in the domain.  Therefore, we need some extra output from the bin transform for the `min`, `max`, `step` …

**Comment by domoritz** [comment]
Maybe that should be an option in the vega bin transform. Something like `emptyBins: true`

**Comment by kanitw** [comment]
Given changes to the bin transform in https://github.com/vega/vega/pull/388#issuecomment-148226265, we can reimplement binning and eliminate constant value in the scale.

**Comment by kanitw** [comment]
Done in #693
