### ISSUE TITLE
Lat/Long shouldn't support ValueDef

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6154]
(only datumdef make sense and it's now supported in #6150)

**Comment by domoritz** [comment]
Why Vega-Lite 5? Is this a breaking change?

**Comment by kanitw** [comment]
It removes a feature that's previously working, though we could argue that this is a bug.  No rush to do it though.

**Comment by domoritz** [comment]
I'm okay with doing it pre 5 since it's a bug right now.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/6993
