### ISSUE TITLE
Missing documentation for lineHeight, titleLineHeight, labelLineHeight etc.

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6162]
`lineHeight` for text marks and equivalent for title, subtitle and labels is part of the VL 4.8 schema but not included in the API documentation. Needed in order to make sense of the VL 4.6 `line-bottom` and `line-top` baseline options.

(and as a meta issue, it would be good to allow issues to have a `documentation` tag option as this is falls somewhere between a bug and feature request.)

**Comment by domoritz** [comment]
We have a docs label but maintainers have to assign it. I invited you to be a member of the Vega org since you work with us regularly.

**Comment by kanitw** [comment]
will fix in https://github.com/vega/vega-lite/pull/6167
