### ISSUE TITLE
How to place gridlines between ticks for ordinal data

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6171]
When using an ordinal encoding, I might still want gridlines to make it easy to see what marks belong together. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/cars.json"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {
      "field": "Cylinders",
      "type": "ordinal",
      "axis": {"grid": true}
    }
  }
}
```

But rather than having lines behind the marks, I'd like the lines between marks. 

![image](https://user-images.githubusercontent.com/589034/77704428-44409d80-6f7a-11ea-933f-80589c750bdd.png)

Similar to binned data

![image](https://user-images.githubusercontent.com/589034/77704445-4b67ab80-6f7a-11ea-839b-7b8cf5a5753d.png)

cc @ldegreef

**Comment by kanitw** [comment]
If you use `band` scale, then you can set tickBand to "extent"

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/cars.json"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {
      "field": "Cylinders",
      "type": "ordinal",
      "scale": {"type": "band"},
      "axis": {"grid": true, "tickBand": "extent"}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/77724117-66a0de00-6faf-11ea-9119-e88cbd840f1b.png)


That being said, I see a few issues here: 

- [ ] tickBand docs doesn't indicate its possible value yet. 
- [ ] there is no example, making it really hard to discover this option.

**Comment by domoritz** [comment]
Added docs in https://github.com/vega/vega-lite/pull/6181 and https://github.com/vega/vega/pull/2481
