### ISSUE TITLE
Eliminate constant values produced in layout

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#618]
Use vega’s more powerful transforms and reactivity so that the output vega spec is more dynamic. 
- [x] Use facet’s `summarize` property to produce statistics and use this to dynamically calculate layout — rather than producing static layout  
- [x] use signals to reference constants
  - [x] range step
  - [x] width/height

**Comment by domoritz** [comment]
@arvind wanted this

**Comment by arvind** [comment]
The other cases I recall:

* [ ] Scale ranges that hardcode their enclosing group's width/height rather than using the preset `width`/`height`. 
* [ ] Rect mark span (width/height) hardcoded rather than using `"band": true`

**Comment by jheer** [comment]
Avoiding hard coding is a good goal. Where feasible, we should let Vega
calculate the appropriate values from the data, etc. If not feasible, at
minimum it would be useful to move constant values to named signals and
reference those consistently through out the spec!

**Comment by mprudhom** [comment]
Is this something I can help with? Ideally I'd like to be able to have a flexible vega spec output so the user can resize their frame and the spec will automatically fit in the viewport regardless of faceting.

**Comment by kanitw** [comment]
Now that we use signals to calculate layout, this should be simpler.  
We could further extract scale padding and rangeStep as signals, but I'm not sure if we want to do that anymore.

**Comment by nyurik** [comment]
This is probably the most important issue for our VL adaption. Given an arbitrary `<div>` container, Vega spec should use up all of the given space, and the host should be able to adjust the size of it on the fly, as users change the layout. Most of the time, the person designing Vega/VL spec, the person developing the host code, and the person arranging multiple pre-made Vega/VL graphs are three different people.

I tried to figure out where in VL codebase the scales are generated, but got a bit scared :)

**Comment by domoritz** [comment]
@nyurik What you are describing is certainly the ideal case. However, Vega uses a bottom-up layout so what you are describing won't be possible with Vega right now. However, with a combination of changing the size of a spec, leaving space for axes and legends, and resizing canvas/svg dom elements, we get pretty close. I also think that we should use the width and height signals sooner, rather than later.

Later this year, I might have some time to look into using a constraint layout solver to add bottom up layouts to Vega/ Vgea-Lite.

**Comment by nyurik** [comment]
@domoritz,  I was simply referring to replacing `"scale": {... "domain": [0, 200]}` with ``"scale": {... "domain": "width"}`. I only saw one or two more places like that - and that would solve the majority of the usecases for all the basic graphs.  It doesn't have to happen all at once - but even this baby step would be huge :)

**Comment by domoritz** [comment]
Agreed! (You mean `range`, I suppose).

**Comment by kanitw** [comment]
According to [Vega scale docs](https://vega.github.io/vega/docs/scales/), `range: "width"` sets range to the "width" signal, which refers to the top-level width by default.  

Thus, it would not naturally work with composite plots unless we provide nested "width" signals for inner group marks to override the top-level width signals.  (Doing so would lead to quite a confusing spec).   Thus, I think we should stick with the original plan to replace constant value (e.g., `200`) with signal references rather than the special `"width"`/`"height"` range. 

cc: @jheer (Please correct me if I misunderstand anything.)

**Comment by nyurik** [comment]
@kanitw scales could be top level or part of a [group](https://vega.github.io/vega/docs/marks/group/), in which case the width would be local (group's), instead of the global.

**Comment by jheer** [comment]
@kanitw Sounds good. If you already have a signal defined, it is fine to use it directly, rather then generate (otherwise unused) nested width/height signals. The important piece is replacing the in-line constants with adjustable top-level parameters.

**Comment by kanitw** [comment]
Fixed in #2676  (using signals).   

@nyurik: Note that "width" and "height" also do not work with faceted plot with shared scale. 
So I prefer to use one method that always work.

**Comment by kanitw** [comment]
For further support for fitting plots within a specified container, please follow https://github.com/vega/vega-lite/issues/2503 (which I don't plan to include as a part of 2.0).
