### ISSUE TITLE
Make signal/parameter an official feature

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6189]
From experiments with signals as an experimental features, we found it's extremely useful for:

1. Parameterization -- we can define signals and refer to them
   - In some cases, we have chain of signal parameters that depend on other paramters
      - For example, in my own use case, I define a `color` signal that define _color names_ (e.g., `color.red`) which may vary based on the color scheme.  I then define another `chartColor` signal that sets _semantic colors_ (e.g., `chartColor.grid` to named color (e.g., `color.gray`).  
     - Similarly, one may define chains of paramaters for spacing, padding, step. 

2. Express custom rules for certain properties -- for example:
    - `values` for tick mark -- as we don't have complete power over D3/Vega's `tickCount` (which is just an approximation, not actual `tickCount`)

3. Provide custom text labels / aria-label for certain data 

4. Refer to math constants such as `PI` (for scale ranges of arc marks / pie charts)

5. Create examples where we can demonstrate various properties of Vega-Lite, like in vega's mark docs (e.g., https://vega.github.io/vega/docs/marks/path/)

So we should consider making it public, esp. once we have a clear plan for how to revise the selection syntax.

**Comment by 20after4** [comment]
Was this closed for lack of interest?

I'm interested in using the experimental signal support if it's still possible.

**Comment by domoritz** [comment]
Params are implemented although there are some details we need to iron out to make it work in more places.

**Comment by tttgm** [comment]
@20after4 I find it most clearly explained in the release notes here: https://github.com/vega/vega-lite/releases/tag/v5.0.0
