### ISSUE TITLE
Data Studio Documentation

### ISSUE THREAD

**Issue by ivanMSC** [vega/vega-lite#6195]
I don't seem to find VegaL-lite + Data Studio documentation anywhere here or on the website. I'm actually struggling to have a topojson map show in data studio, so some documentation would definitely help.

For example, what is $dimension0" or "$metric1"? can you load json files? Why doesn this code work?

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 300,
  "data": {
    "url": "https://raw.githubusercontent.com/vega/vega/master/docs/data/us-10m.json",
    "format": {
      "type": "topojson",
      "feature": "counties"
    }
  },
  "transform": [{
    "lookup": "id",
    "from": {
      "data": {
        "url": "https://raw.githubusercontent.com/vega/vega/master/docs/data/unemployment.tsv"
      },
      "key": "id",
      "fields": ["rate"]
    }
  }],
  "projection": {
    "type": "albersUsa"
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "field": "rate",
      "type": "quantitative"
    }
  }
}
```

**Comment by kanitw** [comment]
I think you're talking about 3rd party integration of Vega-Lite into data studio. 

We're not responsible for such integration. 

Plus, `$dimension0` / `$metric1` is probably specific to the integration (it's not a standard Vega-Lite terminology). Thus, please consult the author of the integration / data studio documentation and support for more information.
