### ISSUE TITLE
Add lookup function

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6224]
We have a lot of places in the code that look like

```ts
const a = markDef.align ?? getMarkConfig('align', markDef, config);
```

Wouldn't it be nice to have a `lookup` function that looks in the mark def and then the correct config? Vega has something like that e.g. in https://github.com/vega/vega/blob/master/packages/vega-parser/src/parsers/axis.js#L23.

```ts
const _ = lookup(markDef, config)
const a = _('align')
```

or 

```ts
const a = lookup(markDef, config, 'align')
```

The advantage of the first one is that we could pass the function around.

**Comment by kanitw** [comment]
Use `getMarkPropOrConfig`

**Comment by domoritz** [comment]
Let’s use it then. There seem to be a lot of places that don’t use it.
