### ISSUE TITLE
Place selection drowdown above the chart

### ISSUE THREAD

**Issue by Juan-132** [vega/vega-lite#6225]
I currently have the chart below (minimal example).

Is it possible to put the selection box at the top of the chart instead?
I've not found any option to do so in the API documentation so far. By default it's placed at the bottom of the chart.

The main benefit for me would be that the selection box is more easily discoverable.
From practical experience, I noticed that end users overlook the ability to make a selection when the selection box is placed at the bottom of the chart.
Currently this requires extra oral/written instruction from my end. It would be nice if this is more self explaining/discoverable.

![image](https://user-images.githubusercontent.com/59505296/78026416-e0dcb400-735b-11ea-95bf-4ebf7c3cd824.png)

```python
import altair as alt
from vega_datasets import data

source = data.barley()

selectSite = alt.selection_single(
    name='Select',
    fields=['site'],
    init={'site':'Waseca'},
    bind=alt.binding_select(options=source.site.unique().tolist())
)

alt.Chart(source).mark_bar().encode(
    x='variety',
    y='sum(yield)',
    color=alt.Color('site',
                    legend=alt.Legend(orient='top')),
    tooltip = ['site','sum(yield)']
).add_selection(selectSite).transform_filter(selectSite)
```

**Comment by domoritz** [comment]
You could place it there with CSS using something like flexbox. 

If that’s not sufficient, please file an issue with Vega as we are just passing options through to there.
