### ISSUE TITLE
Arc mark documentation needs minor corrections

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6232]
- [x] Description of cornerRadius incorrectly refers to "rectangle corners", should be "outer vertices" or similar.

- [x] Documentation refers to `padAngle` but this is not in the schema.

- [x] Perhaps mention that `radius` and `radius2` are synonyms for `innerRadius` and `outerRadius` in the API doc. Personally I'd recommend good practice is to use `innerRadius` and `outerRadius` for arc marks and listing them before `radius` and `radius2` in the API table to avoid confusion with text mark radial offset

**Comment by kanitw** [comment]
Thanks.

These will be fixed in various PRs + pending vega-typings release and upgrade.
