### ISSUE TITLE
Unpredictable behaviour with arc encoding

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6238]
I am seeing unpredictable behaviour with the new arc encoding. Some examples below:

For reference, here is a 8-category dataset encoded with Cartesian bars:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"dir": "1N", "strength": 1},
      {"dir": "2NE", "strength": 2},
      {"dir": "3E", "strength": 3},
      {"dir": "4SE", "strength": 4},
      {"dir": "5S", "strength": 5},
      {"dir": "6SW", "strength": 6},
      {"dir": "7W", "strength": 7},
      {"dir": "8NW", "strength": 8}
    ]
  },
  "encoding": {
    "x": {"field": "dir", "type": "ordinal"},
    "y" : {"field": "strength", "type":"quantitative"},
    "color": {"field": "dir", "type": "nominal"}
  },
  "mark": {"type":"bar"}
}
```

To simplify ordering issues, I've made the clockwise direction categories lexicographically ordered. As we would expect, this yields 8 bars of increasing height:

<img width="268" alt="Screen Shot 2020-04-02 at 06 43 45" src="https://user-images.githubusercontent.com/1846999/78214520-5dcb7300-74ad-11ea-8d3f-6c4024b4c052.png">

Intuitively, to encode using arcs, we might expect to do the following as an equivalent to the Cartesian encoding:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"dir": "1N", "strength": 1},
      {"dir": "2NE", "strength": 2},
      {"dir": "3E", "strength": 3},
      {"dir": "4SE", "strength": 4},
      {"dir": "5S", "strength": 5},
      {"dir": "6SW", "strength": 6},
      {"dir": "7W", "strength": 7},
      {"dir": "8NW", "strength": 8}
    ]
  },
  "encoding": {
    "theta": {"field": "dir", "type": "ordinal"},
    "radius" : {"field": "strength", "type":"quantitative"},
    "color": {"field": "dir", "type": "nominal"}
  },
  "mark": {"type":"arc"}
}
```

But this generates the following:

<img width="275" alt="Screen Shot 2020-04-02 at 06 47 23" src="https://user-images.githubusercontent.com/1846999/78214742-dcc0ab80-74ad-11ea-92bc-daee048e5d97.png">

While this might not be a bug as such (presumably the ordinal specification of `dir` is not yielding an interpretable theta value), it would be nice if this could be interpreted as it is with Cartesian coordinates.

But if, instead, we use encoding as we might for a pie chart by creating a numeric field to be encoded with theta, we still get unexpected results:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"dir": "1N", "strength": 1,"t":1},
      {"dir": "2NE", "strength": 2,"t":1},
      {"dir": "3E", "strength": 3,"t":1},
      {"dir": "4SE", "strength": 4,"t":1},
      {"dir": "5S", "strength": 5,"t":1},
      {"dir": "6SW", "strength": 6,"t":1},
      {"dir": "7W", "strength": 7,"t":1},
      {"dir": "8NW", "strength": 8,"t":1}
    ]
  },
  "encoding": {
    "theta": {"field": "t", "type": "quantitative","stack":true},
    "radius" : {"field": "strength", "type":"quantitative"},
    "color": {"field": "dir", "type": "nominal"}
  },
  "mark": {"type":"arc"}
}
```
<img width="278" alt="Screen Shot 2020-04-02 at 06 51 40" src="https://user-images.githubusercontent.com/1846999/78215008-725c3b00-74ae-11ea-8529-d6b6ef9a4808.png">

This looks like a bug to me as removing the `radius` line above generates the expected pie chart.

I also tried explicit encoding of theta and theta2:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"dir": "1N", "strength": 1,  "t":0.00,"t2":0.79},
      {"dir": "2NE", "strength": 2, "t":0.79,"t2":1.57},
      {"dir": "3E", "strength": 3,  "t":1.57,"t2":2.36},
      {"dir": "4SE", "strength": 4, "t":2.36,"t2":3.14},
      {"dir": "5S", "strength": 5,  "t":3.14,"t2":3.93},
      {"dir": "6SW", "strength": 6, "t":3.93,"t2":4.71},
      {"dir": "7W", "strength": 7,  "t":4.71,"t2":5.50},
      {"dir": "8NW", "strength": 8, "t":5.50,"t2":6.28}
    ]
  },
  "encoding": {
    "theta": {"field": "t", "type": "quantitative", "stack":true},
    "theta2": {"field": "t2"},
    "radius": {"field":"strength", "type":"quantitative"},
    "color": {"field": "dir", "type": "nominal"}
  },
  "mark": {"type":"arc"}
}
```

This yields segments of increasing length, but the first category (`1N`) has a tiny, effectively invisible, theta. This too looks like a bug.

<img width="278" alt="Screen Shot 2020-04-02 at 06 57 00" src="https://user-images.githubusercontent.com/1846999/78215342-32e21e80-74af-11ea-9391-d05c3bf7305a.png">

I note also that an incorrect warning is generated when encoding with `theta2` saying `Missing type for channel 'theta2'` (and adding the type generates an `encoding should not have additional properties` warning).

**Comment by jwoLondon** [comment]
In case it is any help, it would appear the problem occurs once a data-driven radius is defined that uses a different field to that used for theta. In the example below, try changing the radius field from `t` to `v`. Even though the values are identical, this appears to corrupt the placement.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"t":50,"v": 50,"cat":"A"},
      {"t":10,"v": 10,"cat":"B"},
      {"t":15,"v": 15,"cat":"C"},
      {"t":25,"v": 25,"cat":"D"}
    ]
  },
  "encoding": {
    "theta": {"field": "t", "type": "quantitative", "stack": "zero"},
    "radius": {"field": "t","type": "quantitative","scale": {"zero":true}},
    "color": {"field": "cat", "type": "nominal"}
  },
  "mark": {"type": "arc", "stroke": "white"}
}
```

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6268 and https://github.com/vega/vega-lite/pull/6270
