### ISSUE TITLE
Add tags to gallery and allow filtering by tags

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#625]

**Comment by domoritz** [comment]
where tags = features? use case?

**Comment by kanitw** [comment]
That should be it.  But I start wonder if a gallery should be a feature of the vega-editor instead ...

**Comment by domoritz** [comment]
> But I start wonder if a gallery should be a feature of the vega-editor instead ...

That's a good idea. A gallery of vega (-lite) visualizations taken from the existing list.

**Comment by kanitw** [comment]
The format of current vlexamples.json contains grouping so this is sort of supported.  Just need to provide parameter for filter specific categories.

**Comment by kanitw** [comment]
Probably will never happen.
