### ISSUE TITLE
Selection `on` doesn't work as expected

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6253]
[Here](https://github.com/vega/vega-lite/blob/a152eb1fcb26773b98905500547fd9749bc1436f/src/compile/selection/index.ts#L40), the type of events is expected to be an array. (Note that this allowed `events` property, is not documented).

However, as you can see [here](https://github.com/vega/vega-lite/blob/master/src/selection.ts#L36), the `on` property is either a Vega `Stream` object or a string. If you set `on` to be a `Stream` object (as allowed by the type system and documentation), Vega-lite fails, as we set events (an array) to that `Stream` object (which is, well, not an array) [here](https://github.com/vega/vega-lite/blob/a152eb1fcb26773b98905500547fd9749bc1436f/src/compile/selection/parse.ts#L47).

**Comment by willium** [comment]
Here is a minimal reproduction: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnCgHcq0eAAt8kAMbtEVNjSyReESCJpUA5iPjipbGXIVKoNNlOiz1+UBGUAPK3xtR4ATwAONcQEcMsPVUR4KgpPIydIIPgcT1RIAEkAWQARACEAfQAlBAtFRxtIADNaHGhxRNTM7LZLPJ48yBcrCPcYqB8-SOyQxWcA6PEAYTIMPR7IWHV1LBp1BFbJYdHOPjrlHFgXeXwAbTzrJygSWCwAaybXD3FjmiRuKAlsVgVYtzJZeC3Vg8gTMxzUdBkNywCQBRoAyAUWA4DCtAAMDAAzJwvuE6DRohIguwHAd8ujMdiOAC8njmpdYu95FC8GE8VAcahSfT9vTvhd5uQMOjyN06WzlAAjGjwfg0Ew7ZkCtDkznDdHQMj8Dh3QpUHAfZ7GEJ6Bh0ERUArwADSNEaqOlNnQHPEXPRGDcXCl9IAus6nMtpfz2Vg-HR1h9xNtqDR+Mg7TRFcrtjQdfA9QajaaXC67iGwxGHS6wAA+MDp8Pymi80LuqAALzIZBI4n4qgxAEIY3GE4aTWaXZBnZ6Dj2IBbWfkjqcrtMkLU+G7OEA

**Comment by arvind** [comment]
Fixed with #6917.
