### ISSUE TITLE
Stream object syntax for selection produces incorrect Vega

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6254]
[This spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnCgHcq0eAAt8kAMbtEVNjSyReESCJpUA5iPjipbGXIVKoNNlOiz1+UBGUAPK3xtR4ATwAONcQEcMsPVUR4KgpPIydIIPgcT1RIAEkAWQARACEAfQAlBAtFRxtIADNaHGhxRNTM7LZLPJ48yBcrCPcYqB8-SOyQxWcA6PEAYTIMPR7IWHV1LBp1BFbJYdHOPjrlHFgXeXwAbTzrJygSWCwAaybXD3FjmiRuKAlsVgVYtzJZeC3Vg8gTMxzUdBkNywCQBRoAyAUWA4DCtAAMDAAzJwvuE6DRohIguwHAd8ujMdiOAC8njmpdYu95FC8GE8VAcbFttQaPxkOQMOjoGR+GxtjQQnoGHQRFQCvAANI0FwAXTuLLZHPRGDcMrAAD4wAr2cN0eRunSyfAsH46OsPuJmbRFbqaNzefzBfBhaLxVLZfLrTrOTQVWrNdqlTR9aFSd8AF5kMgkcT8VQYgCEjpMzpFYsl0plkDDEGWeLzNlRaDDkCOpyu0yQtT4MpAnCAA) uses the syntax for `on`, we produces a **valid** chart that only allows interval selections while holding shift.

[This spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnCgHcq0eAAt8kAMbtEVNjSyReESCJpUA5iPjipbGXIVKoNNlOiz1+UBGUAPK3xtR4ATwAONcQEcMsPVUR4KgpPIydIIPgcT1RIAEkAWQARACEAfQAlBAtFRxtIADNaHGhxRNTM7LZLPJ48yBcrCPcYqB8-SOyQxWcA6PEAYTIMPR7IWHV1LBp1BFbJYdHOPjrlHFgXeXwAbTzrJygSWCwAaybXD3FjmiRuKAlsVgVYtzJZeC3Vg8gTMxzUdBkNywCQBRoAyAUWA4DCtAAMDAAzJwvuE6DRohIguwHAd8ujMdiOAC8njmpdYu95FC8GE8VAcahSfT9vTvhd5uQMOjyN06WzlAAjGjwfg0Ew7ZkCtDkznDdHQMj8Dh3QpUHAfZ7GEJ6Bh0ERUArwADSNEaqOlNnQHPEXPRGDcXCl9IAus6nMtpfz2Vg-HR1h9xNtqDR+Mg7TRFcrtjQdfA9QajaaXC67iGwxGHS6wAA+MDp8Pymi80LuqAALzIZBI4n4qgxAEIY3GE4aTWaXZBnZ6Dj2IBbWfkjqcrtMkLU+G7OEA) should be equivalent to the string syntax but in Vega stream syntax. This fails because during compilation, Vega cannot reduce an object. This bug was filed as an issue [here](https://github.com/vega/vega-lite/issues/6253).

If I shortcut that issue and just encode "events" directly (this is undocumented and is technically invalid per the schema), [it successfully compiles](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBbAewDcBLAUwGcA6AKzrIDtIBfAGnCgHcq0eAAt8kAMbtEVNjSyReESCJpUA5iPjipbGXIVKoNNlOiz1+UBGUAPK3xtR4ATwAONcQEcMsPVUR4KgpPIydIIPgcT1RIAEkAWQARACEAfQAlBAtFRxtIADNaHGhxRNTM7LZLPJ48yBcrCPcYqB8-SOyQxWcA6PEAYTIMPR7IWHV1LBp1BFbJYdHOPjrlHFgXeXwAbTzrJygSWCwAaybXD3FjmiRuKAlsVgVYtzJZeC3Vg8gTMxzUdBkNywCQBRoAyAUWA4DCtAAMDAAzJwvuE6DRohIguwHAd8ujMdiOAC8njmpdYu95FC8GE8cYQno6DswKT6ft6d8LvNyBh0eRunTOcoAEY0eD8GgmHZs4Vock84bo6BkfgcO6FKg4D7PBkmeAMOgiKgFeAAaRojVRcps6G54l56Iwbi4svpAF03U5lnL3UKuVg-HR1h9xNtqDR+MhHTQVWrtjRGQajSbzZa-WAI1GY873WAAHyZ2jZpU0AWhL1QABeZDIJHE-FUGIAhAmk4bjaaLS53ZA3T6DgOINaOfkjqcrtMkLU+J7OEA). However, while it successfully compiles, it produces the incorrect Vega spec. You can observe this by noticing that it allows for interval selection without holding shift.

[Here is the diff](https://www.diffchecker.com/r0ICvoXk) (left side is expected Vega spec as generated by the stream string notation, right side is the Vega spec generated by the object notation). Note specifically the missing shiftKey filters on line 65 and 80 in the diff. Also note that the `source` property doesn't seem to obey the default value which should be `view` according to the documentation. Oddly enough it also seems to have added `consume: true` where it wasn't specified.

**Comment by arvind** [comment]
This is not a bug. `events` is not a valid property to set on a selection (it is a property of a `SelectionComponent` which is an abstraction used internally by the Vega-Lite compiler, but isn't something that can be directly defined in the specification). Instead, what is happening with the three specification is that the compiler does not see an `on` property and thus uses the default events for interval selections (drags w/o shift). 

The linked issue #6253 has been fixed as part of #6917.
