### ISSUE TITLE
Cannot define default theme color for point charts without overriding color of shape charts

### ISSUE THREAD

**Issue by dantman** [vega/vega-lite#6257]
I am trying to define the default colors for a custom `config` theme.

For most chart types, e.g. Area charts defining `area: { fill: color }` works. A [single category area chart](https://vega.github.io/vega-lite/examples/area.html) will use `color` and a [multi-category stacked area chart](https://vega.github.io/vega-lite/examples/stacked_area.html) uses the colors from `range` instead.

However scatter plot points don't work the same. If I define `point: { stroke/fill: color }` then this applies both to [single category `mark: 'point'` charts](https://vega.github.io/vega-lite/examples/point_2d.html) and [multi-category point charts](https://vega.github.io/vega-lite/examples/point_color_with_shape.html) that use separate colors and shapes. So the stroke/fill of a shape chart is overridden.

It would be very good to have a way to define theme colors for points just like area, bar, etc... charts which only apply to single-category points and not points when the spec defines a nominal color/shape.

**Comment by domoritz** [comment]
I can't reproduce the issue. 

<img width="1159" alt="Screen Shot 2020-04-03 at 20 51 21" src="https://user-images.githubusercontent.com/589034/78417987-ebfa4300-75ec-11ea-8283-647b9926c410.png">

Can you send the spec you used?

**Comment by dantman** [comment]
Ok, I think I understand the underlying issue now.

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYOjUNSE1rTBxgSFZdMWxcAmIyIVoGZjZOHjLRCTwpZAAPdFR7HVIMvHRSeHRfeUUVAF91CEgMXQBrQsgAjzxU8eQleG5ND2pC0Ahxpu3IADNGZDFNWYAJbl9-QN01KDwAT1jZgEdWEKNuoypIUY04yeB2Op3OpgAspEdAB9WK6GEAcXQCWUD0gz1epg+X2Y1kYfwBuygawc92yRxOZ1mAHl9EwVKpHi9kLMlNwIkoUf8xrtILBEOgsWAcqDqaY6YwGejMazTOzOdzhhplcMgA

I specify both a stroke color and a fill color, because this is a general theme and `filled` can be set by the user to specify either filled or stroked shapes.

However Vega only overrides `fill` when `filled: true` and only overrides `stroke` when `filled: false`.

So I guess my actual issue is there is no way to specify the default color for a point like in a way that works for both filled and non-filled points.

**Comment by domoritz** [comment]
Okay, can you update the title, the first message, and add an example that explains your feature request with this update?

**Comment by kanitw** [comment]
You can use `config.point.color`

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A scatterplot showing horsepower and miles per gallons.",
  "data": {"url": "https://vega.github.io/vega-lite/examples/data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "shape": {"field": "Origin", "type": "nominal"}
  },
  "config": {
    "point": {"color": "green"}
  }
}
```

Add color encoding `"color": {"field": "Origin", "type": "nominal"},` in this spec would work.
