### ISSUE TITLE
Arc theta2 field raises warning: Missing type for channel "theta2"

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6263]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.9.0.json",
  "data": {
    "values": [
      {"category": 1, "value": 0.0, "value2": 3.14159},
      {"category": 2, "value": 6.0, "value2": 6.1}
    ]
  },
  "mark": {"type": "arc", "innerRadius": 50},
  "encoding": {
    "theta": {"field": "value", "type": "quantitative", "scale": null },
    "theta2": {"field": "value2"},
    "color": {"field": "category", "type": "nominal"}
  }
}
```

<img width="282" alt="Screen Shot 2020-04-04 at 15 34 42" src="https://user-images.githubusercontent.com/659086/78459820-cff8af00-7689-11ea-81d2-7d3a5e91520f.png">

Results in the following log message:

```console
[Warning] Missing type for channel "theta2", using "quantitative" instead.
```

However, "type" is not value for the "theta2" channel according to the schema.

The same issue happens with the "radius2" channel.

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6262
