### ISSUE TITLE
Tick, square, and image marks should support angle channel

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6267]
Angle is useful for (non-circular) `point` marks, and useful for `text` when it is used as adornment. Other non-anchored shaped marks, such as `tick`, `square`, and `image` could benefit from being able to represent different angles.

**Comment by kanitw** [comment]
Square does support angle. Try:


```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "square", "angle": 45},
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"}
  }
}
```

For tick marks, we won't plan to support angle, since we use Vega rect marks under the hood and it would be hard to add such support.

For image marks, it's currently not possible in Vega, so we don't plan to add that either.  

If you really think we should have this, please file a request in Vega. 
Once Vega has such support, we can easily adopt them in Vega-Lite.

**Comment by marcprux** [comment]
I'll file a vega enhancement for `image` `angle` support.

However, while `square` supports `angle` in the mark def, it is not supported as a channel:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": {"type": "square"},
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "angle": { "value": 45 }
  }
}
```

yields the following warning:

```console
[Warning] angle dropped as it is incompatible with "square".
```

I'll re-open this for the `square` `angle` channel issue, but I understand if it is put on ice since it is a fairly small feature.

**Comment by kanitw** [comment]
Oh got it,  will fix in https://github.com/vega/vega-lite/pull/6271
