### ISSUE TITLE
Cannot make rule translucent due to overlapping lines

### ISSUE THREAD

**Issue by dantman** [vega/vega-lite#6296]
Using the "Multi Series Line Chart with Labels" example, it is not possible to make the rule line that shows up on hover translucent.
https://vega.github.io/vega-lite/examples/interactive_multi_line_label.html

It is possible to change the color of the rule line by changing `layer.mark.color` on the `"type
: "rule"` layer mark. However if you set it to an `rgba` color or use `strokeOpacity` the rule line is still opaque unless you use an extremely low opacity like `0.1` in which case it becomes translucent but darker than what an opacity of `0.1` would look like.

I did some investigating of the svg to debug this and I discovered that it appears that in this example which uses a single rule line, there are actually multiple rule lines that overlap each other. I think, but cannot confirm, that there is a separate rule line for each category; even though all the rules are for the same line.

I can think of two possible solutions:

1. Vega Lite should be smart about when multiple rule lines for different categories of the same rule are duplicates and omit them
2. The Vega Lite rule should have an extra property to mark a rule as only having 1 line so the additional lines are omitted

**Comment by domoritz** [comment]
Good catch. You can add aggregation to the rule to only get a single rule. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "url": "data/stocks.csv"
  },
  "width": 400,
  "height": 300,
  "layer": [
    {
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {"field": "price", "type": "quantitative"},
        "color": {"field": "symbol", "type": "nominal"}
      },
      "layer": [
        {"mark": "line"},
        {
          "selection": {
            "label": {
              "type": "single",
              "nearest": true,
              "on": "mouseover",
              "encodings": ["x"],
              "empty": "none"
            }
          },
          "mark": "point",
          "encoding": {
            "opacity": {
              "condition": {"selection": "label", "value": 1},
              "value": 0
            }
          }
        }
      ]
    },
    {
      "transform": [{"filter": {"selection": "label"}}],
      "layer": [
        {
          "mark": {"type": "rule", "color": "gray"},
          "encoding": {
            "x": {"type": "temporal", "field": "date", "aggregate": "min"}
          }
        },
        {
          "encoding": {
            "text": {"type": "quantitative", "field": "price"},
            "x": {"type": "temporal", "field": "date"},
            "y": {"type": "quantitative", "field": "price"}
          },
          "layer": [
            {
              "mark": {
                "type": "text",
                "stroke": "white",
                "strokeWidth": 2,
                "align": "left",
                "dx": 5,
                "dy": -5
              }
            },
            {
              "mark": {"type": "text", "align": "left", "dx": 5, "dy": -5},
              "encoding": {
                "color": {"type": "nominal", "field": "symbol"}
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6297
