### ISSUE TITLE
Console error with secondary channel field definition with primary channel value

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6301]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.10.1.json",
  "data": { "values": [{ "Q": 1 }] },
  "mark": "bar",
  "encoding": {
    "x": { "value": 0 },
    "x2": { "field": "Q"}
  }
}
```

This raises the console error:

```console
[Error] undefined is not an object (evaluating 'r.type')
```

This seems to happen for any secondary field encoding declaration when the primary channel is not present or is not a field (i.e., is a value or datum). This should probably instead be a warning that the encoding was dropped because the primary encoding does not allow for a secondary encoding.

This seems to also affect `theta2`, `latitude2`, etc.

**Comment by kanitw** [comment]
One can always use x2 = 0 and set x to field: Q with its type.  

Since this seems to be a rare use case, I'll close this for now.

If anyone has a convincing use case, please feel free to re-open with more explanations.

**Comment by marcprux** [comment]
Note that my report wasn't an enhancement request that this encoding combination be permitted, but rather it was a (minor) bug that an exception is thrown rather than the console reporting a nice warning that it is illegal (like it does for other invalid encoding combinations).

**Comment by kanitw** [comment]
@marcprux  -- Thanks for the explanation. 

Actually we can easily fix this in `initEncoding`, so I'll make it open for now.
