### ISSUE TITLE
fillOpacity & strokeOpacity channels raise Error: Missing valid scale for legend

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6303]
The following spec raises a console error "Error: Missing valid scale for legend" when `fillOpacity` or `strokeOpacity` is set to a field:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.10.1.json",
  "data": {
    "values": [
      {"a": "A", "b": 10}, {"a": "B", "b": 20}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"},
    "fillOpacity": { "field": "b", "type": "quantitative" }
  }
}
```

This works as expected for the "opacity" channel. It also works if "scale" is set to "null" for "fillOpacity", so it seems to be erroring out when it is trying to create a legend. If legends aren't supported for these channels, they should probably just be skipped (perhaps with a warning) rather than causing the whole spec to fail to compile.

**Comment by kanitw** [comment]
Thanks, will be fixed in https://github.com/vega/vega-lite/pull/6304
