### ISSUE TITLE
Large astronomy data breaks vega lite

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#632]
Try https://dl.dropboxusercontent.com/u/12770094/test.csv in voyager

<img width="536" alt="screen shot 2015-10-09 at 11 57 29" src="https://cloud.githubusercontent.com/assets/589034/10402917/022f95de-6e7d-11e5-9d79-82ed270e2fbb.png">

**Comment by kanitw** [comment]
@domoritz Can’t access that file on dropbox anymore

**Comment by kanitw** [comment]
I’m closing this as the data is no longer accessible.  Please re-open this if you still have it.
