### ISSUE TITLE
Inconsistency with thetaOffset and theta2Offset for arc mark

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6320]
The Vega-Lite 4.10 schema has (as yet, undocumented) `thetaOffset` and `theta2Offset`. This is certainly useful, and behaves as I would expect when just `thetaOffset` is specified for radial charts where the segment angle is equal for all marks but radius varies:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"dir": "1N","strength": 10},
      {"dir": "2NE","strength": 12},
      {"dir": "3E","strength": 10},
      {"dir": "4SE","strength": 12},
      {"dir": "5S","strength": 10},
      {"dir": "6SW","strength": 12},
      {"dir": "7W","strength": 10},
      {"dir": "8NW","strength": 12}
    ]
  },
  "encoding": {
    "theta": {"field": "dir","type": "ordinal"},
    "radius": {"field": "strength","type": "quantitative"},
    "color": {"field": "dir","type": "nominal"}
  },
  "mark": {
    "type": "arc",
    "stroke": "white",
    "thetaOffset":-0.39
  }
}
```
<img width="237" alt="thetaOffset1" src="https://user-images.githubusercontent.com/1846999/79067468-6c890580-7cb7-11ea-8a14-142d0282e635.png">

Its behaviour is analogous to specifying `xOffset` in a Cartesian vertical bar chart.

However, when the segment angle varies, such as a pie chart, to apply an offset we have to supply both `thetaOffset` and `theta2Offset`. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"category": "A","value": 4},
      {"category": "B","value": 6},
      {"category": "C","value": 10},
      {"category": "D","value": 3},
      {"category": "E","value": 7},
      {"category": "F","value": 8}
    ]
  },
  "encoding": {
    "theta": {"field": "value","type": "quantitative"},
    "color": {"field": "category","type": "nominal"}
  },
  "mark": {
    "type": "arc",
    "thetaOffset": -0.3,
    "theta2Offset": -0.3
  }
}
```

<img width="241" alt="thetaOffset2" src="https://user-images.githubusercontent.com/1846999/79067497-98a48680-7cb7-11ea-9625-600ea2deb528.png">

Needing to provide both seems inconsistent given the data-driven specification only identifies `theta` encoding. I think a more consistent approach would be apply `thetaOffset` to both the start and end angles unless (a) the main encoding uses both `theta` and `theta2` channels; or (b) both `thetaOffset` and `theta2Offset` are supplied. This would be more consistent with the Cartesian equivalents.

I note also that if only `thetaOffset` is applied (try removing the `theta2Offset` line above), it would appear that it is actually `theta2` that is offset :

<img width="244" alt="thetaOffset2" src="https://user-images.githubusercontent.com/1846999/79067580-3d26c880-7cb8-11ea-988c-9b65da12d416.png">

And if only `theta2Offset` is supplied, we get a misleading overlapping of later segments on earlier ones (set the mark opacity to <1 to confirm this happens):

<img width="245" alt="thetaOffset3" src="https://user-images.githubusercontent.com/1846999/79067669-056c5080-7cb9-11ea-9633-fe2492128ce4.png">

**Comment by kanitw** [comment]
Thanks @jwoLondon.  I'm fixing it in https://github.com/vega/vega-lite/pull/6322

Note that rect's Cartesian position and Arc's Polar position share the same code path.So this was similarly problematic for x/y offset for range marks (e.g., rect) -- try this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkeDprcATgE8rkAIJrjpuZW0gC+6vYQjs54rp7eAEL+JmbIVgBsYXaGUS7U7l44kADCSYGpOACMAAyZEQ5OufneACKlKVYAzLUROTF5cYUAom1BOADs3fa9sQVQAGIj5WAAHCFZALoa3ZDISvDcmoxK1FYGhpAAHqeQAGaMyGKa3slBqpB4HoRLkACOrOhKPDMHSMKhqKCwXTwADWVjwbnMkyg+zE7mudweT0K0Rm-g+X28Sm4qCOpkgawg2wwblh+iy70+33Y6DcanpFwA8jcbrBkHhOlVwucLgAmLk8vkCrYgEJAA)).
