### ISSUE TITLE
Axis & Legend config "disable" property has no effect

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6321]
config.legend.disable=true and config.axis.disable=true does not disable legends and axes. They still show up with this spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.10.2.json",
  "description": "A chart trying to disable axes and legends.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": { "field": "a", "type": "nominal" }
  },
  "config": {
    "axis": {
      "disable": true
    },
    "legend": {
      "disable": true
    }
  }
}
```

<img width="160" alt="Screen Shot 2020-04-12 at 13 53 06" src="https://user-images.githubusercontent.com/659086/79076045-f25f7d80-7cc4-11ea-8b26-c90d92825ca7.png">

**Comment by marcprux** [comment]
Never mind … the issue was just that the online editor is still at 4.10.1 (and the config disable is new in 4.10.2).

**Comment by marcprux** [comment]
Actually, axis.disable works, but legend.disable doesn't disable the legends. With the 4.10.2 editor, the above spec renders:
![Untitled](https://user-images.githubusercontent.com/659086/79077518-56d40a00-7cd0-11ea-94af-591d96c3880d.png)

**Comment by kanitw** [comment]
Thanks, will be fixed in https://github.com/vega/vega-lite/pull/6317
