### ISSUE TITLE
Use stack’s `sortby` property to order values in the stack

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#634]
forked from #39

**Comment by kanitw** [comment]
@jheer  @domoritz   One question here:

I add `-` to the `sortby` property by default so that we can have the stack’s order consistent with the legends.  However, users might want to reverse this. 

How should we add this reverse property?  

One option is making stack either boolean or object akin to `bin`.  
If `stack` is `true`, we use default properties.  Or properties can be specified using `stack` object. 

We can also add `offset` for modifying stack transform’s `offset` here as well.

**Comment by jheer** [comment]
This sounds reasonable to me. I assume stack would be true by default and
using false would disable stacking?

**Comment by domoritz** [comment]
> This sounds reasonable to me. I assume stack would be true by default and
using false would disable stacking?

We this this is the right behavior for `bin` and also for `stack`.

**Comment by domoritz** [comment]
The other options are

* add an additional property `reverseStack`
* have three options for stack: `true`, `false`, `"reversed"`

**Comment by jheer** [comment]
Yes, but having the ability to override sortby and offset might enable some
useful plots. The trade-off is a more complicated spec language... can
stack sorting be achieved by other means?

**Comment by kanitw** [comment]
To simplify the conversation, I think there are a few decisions to make here:

## 1. What properties should we add for stack

- `offset` should be added on its own.  This should be straightforward.  (Just add it!)

- Should we add `sortby` or `reverse` or both?
   - add `sortby` just like `sortby` in stack transform to let user specify how they want to sort the stack group (this way they can sort the stack by another field that doesn't have to be the color field).  If not specified, sortby is set to `'-' + <color|detail field>` by default. 
   - or add `reverse` to exclude the `'-'`.  `'-'` is included/excluded if `reverse` is `false`/`true`. 

__I vote for adding only `reverse` for simplicity.__

## 2. How to specify stack's properties

Here are a few alternatives:  (What we decide here should be consistent with `bin`.) 

#### a) Making stack either boolean or object akin to bin.

- If `stack` is `true` --> use default property
- If `stack` is `false` --> do not stack
- If `stack` is an object (e.g., `{offset:..., reverse:...}`) --> apply stack's properties to the stack transform in the output Vega spec.  If any property is not specified, applied default value.

This is my preferred method as stated earlier. 

#### b) Add additional properties

add `stackOffset`, `stackReverse` property to the encDef.  
I do not like this as it is adding too many  top-level properties to encDef. 
Also, this is somewhat inconsistent with the field's `scale`, `legends` and `axis` properties.  


#### c) Multiple options for stack
> have three options for stack: true, false, "reversed"

This is not scalable as we cannot add `offset` property easily with this method.  
This has to be combined with b) to add additional property, therefore this is the worst method in my opinion. 



__I vote for a)__

**Comment by jheer** [comment]
I vote for (a) too.

**Comment by kanitw** [comment]
Fixed in #644 – only need to be merged.
