### ISSUE TITLE
Conflicting axis property warning no longer raised and default behaviour has changed

### ISSUE THREAD

**Issue by trubens71** [vega/vega-lite#6340]
Up to and including 4.10.1, Vega-lite was being charmingly forgiving of my poor spec, where I had different axis between layers and was mistakenly resolving as shared, giving me this warning and covering for my mistake by displaying the first axis.

```
WARN Conflicting axis property "disable" (false and true). Using false.
```

With 4.10.2 and 4.10.4, there is no warning and no axis is rendered, hence less forgiving.  Not a major issue but I thought worth raising in case unintended change or has broader implications. I see other issues related to axis disable, but believe this is a somewhat nuanced extension.

Simple test case follows...
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "y": 1
      }
    ]
  },
  "layer": [
    {
      "mark": "circle",
      "encoding": {
        "y": {
          "field": "y",
          "type": "quantitative",
          "axis": {
            "title": "Y"
          }
        }
      }
    },
    {
      "mark": "square",
      "encoding": {
        "y": {
          "field": "y",
          "type": "quantitative",
          "axis": null
        }
      }
    }
  ],
  "resolve": {
    "scale": {
      "y": "shared"
    }
  }
}
```

**Comment by kanitw** [comment]
fixed in https://github.com/vega/vega-lite/pull/6360
