### ISSUE TITLE
Setting label angle removes label flush

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6341]
Setting the label angle removes label flush. We could say that this is by design but it's a bit jarring. Not sure whether this is a regression either. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8ejUNSFDw7DBQCAhICnQxVh04gG0NRPjITFMzNSh2OIAmAA4AX1U8gqgAIWLIUpwAVjaaurjIAGFm1rBpAGYanMTgfJ6AEQG4gE4ARi7J+sgAUTmcCuXa1Z6AMS2wNtH1XIh90wBxY8X5lanTAAljioB2R7WASWO2sqq4wAuhoxkkMLoANY9Ry6SJJZBKeDcTSMJTUOIJRKQAAemMgADNGMgxJoYc08ABPQjIHoAR1Y6CURnCRiozXQOMYsHxYnQ-jEZnRdjiAAYqoCIIDAUA)

**Comment by domoritz** [comment]
Looks like it was the behavior in 4.9 as well.

**Comment by kanitw** [comment]
>       "labelFlush": true,

It's still true in the Vega output, move to Vega?

**Comment by domoritz** [comment]
No, the problem is that we are setting label align to `center`. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KO3TwA1tQBO3VjIAm2KAHdEzZAqWRC6PXsYzqh0YoiQjjPS0MAmAAy+XKAR0ABtkWEMAbSUIUAh4qBl0VHMcSAAPCwTXPABPQlSoEPtkdE0s7Mg9bgx7KICwAEZ-AF1AhMhNdAdCyIbgSFhGaiSQwzcPLwBfFpiwKaU2y3R08Ki5uMrgsPHM9vjIbk1GZBk8cfZuAhqKjpD0dmQQgEEHHZwAudd7x5fikfG8FOeGQ5X23weTwAYiFWLBEIY8JpWMhwUVISEAPJUTT3QiI5Gor5QPCMdQAYR0Z0MAyGI1CgOQjBCAAp3J5EKQACy+ACUkCmaMgAC97HpkJkPnMFhBZlMgA)

**Comment by domoritz** [comment]
Fixed in #6344

**Comment by kanitw** [comment]
We should double check if labelBaseline has a similar issue.

**Comment by kanitw** [comment]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "b", "type": "quantitative", "axis": {"labelAngle": 0, "labelFlush": true}}
  }
}
```

It's actually similarly problematic.

**Comment by kanitw** [comment]
The baseline case will be fixed in https://github.com/vega/vega-lite/pull/6370
