### ISSUE TITLE
bind='legend' selector won't respond to click

### ISSUE THREAD

**Issue by makmanalp** [vega/vega-lite#6347]
coming here from: https://github.com/vega/vega-embed/issues/351

Reproduced this in the latest version of jupyterlab as well as the online editor:[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIDdkBTAd02xgQBdl4BXWOgZwHVkATKgC3IBYAGfgBooceDXqMmACSJouVcgGZBAXyHhckADZFUReO3LBIsAE7Fx5HUUSLVm9ZsjsAhlVfHI8VwFsi1m4eALQA7ABMvACM4QBsofyIAJwAHESp0EREsfyhSohKrrzhSbz54QCskE54vq5mANbWAEb1kBp4BnDstOhYOFpw2uZeVACeAA4BWN6wvrSu2u1QKETaRjNDIzVasBOu0Mjjxpq4ogg9NAhe+It002BRIpBMa0TQV-DWr7of5oLhaodM5QW7ae7kfgAOnCpzAOzwVFgsG0NAm5AA2nCICZxlNrABHOiucRHdzIfABZ6rdbWOBMezAs64yYPWbzHxLanEWkzBpEMZMfaZIHYih4tnwOYLLkrHkbKBS9hEAD6XFgDJ8-mqcIAukyoAAPUas6xSjmLZaQGkK2bKtUaqhaqlQJjmRQzYJjUVnSDe-qQCWE4mkjw0SlWm10x1WhkHJozABeRDMsB1EB2LzeH2Q136cKzvyRZgBJvxMyYvV0kflTExkH5guFAX1UGatFtun0hnT8OBkAAJExoFwiHVrAoqBMmBgAPSzymoVxQ1BHLh0ZpQ3Oz4ejuoLvSuYLaI5EBe8KFRaEXgBWbq+-aCrleVDr+d9T7CkRi8USqXSKSZNkuT5IUxSlOUVRYFiZxigMIKKrA9rqpqfhsp4Bq+o2QoHGyxqYYMMZYNC-AVLEUQVKEoQVIItF0bEBF4FsZjWMaYoIrg8EgnaqooU6aEtO0Yp4NhzasUJCFMURYAkWRFFUTRdH0Yx5zDCxMxsQhCJwcJiHIY6zp0hJkkNgKOEijM3oqZQDKQlCgihDksSVNZzHWN67EEVxvpKrxBkCTMRjWaJuHWImxkITZHoyfZuROS5umUGp1gAPLcCmkCeTpkl6X5qHajMVKJSFFlGhhiX0tFJFxfwzkVK5KIjDMaWjixWUId5Wi+Q6+VskVOWmU2oUac0EXcZVdkOfF9UVY16lQC1GXtSCnV4N1fGGYVY1YWZYkadA22EbZxGxY5tUJQNbnNelbVaV5iXrf5BVQP1JklXhQWzcdMVTedM2XXNqU3ZlWl6o4ICqEAA)

expected behavior: clicking legend updates selection
actual behavior: selection / selectorxyz_store and chart seems unresponsive

**Comment by makmanalp** [comment]
For folks running into this: I was able to work around this by making a mini chart with mark_bar and only a y axis to form legend-like squares, adding the selection to that too, and then concatenating that to the left of my chart to look like a legend.

**Comment by arvind** [comment]
Hi @makmanalp, apologies for the slow response here. This doesn't look like a bug. When a selection is bound to a legend, the selection's field/encoding should match the legends. For your spec, the legend corresponds to the `color` channel and field. So, if we switch `"fields": ["keyspace"]` to `"fields": ["color"]` instead, clicking the legend works as expected. Hope that helps!
