### ISSUE TITLE
Feature request: "day of year" timeUnit

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6348]
It would be nice if it were possible to compute the day of year as a timeUnit. Here is how it can be calculated using a series of transforms:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/seattle-weather.csv"},
  "transform": [
    {"timeUnit": "yearmonthdate", "field": "date", "as": "date"},
    {"timeUnit": "year", "field": "date", "as": "start"},
    {"calculate": "round((datum.date - datum.start) / (24 * 60 * 60 * 1000), 1)", "as": "dayOfYear"}
  ],
  "mark": "rect",
  "encoding": {
    "x": {"field": "dayOfYear", "type": "ordinal", "title": "day of year"},
    "y": {"field": "date", "timeUnit": "year", "type": "ordinal", "title": "year"},
    "color": {"field": "temp_max", "type": "quantitative"}
  },
  "width": 800
}
```
![visualization - 2020-04-17T061237 583](https://user-images.githubusercontent.com/781659/79572827-75d8f000-8072-11ea-9dfe-2c175d83013c.png)

It would be nicer if the above chart could be expressed as something like this:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "rect",
  "encoding": {
    "x": {"field": "date", "timeUnit": "dayofyear", "type": "ordinal", "title": "day of year"},
    "y": {"field": "date", "timeUnit": "year", "type": "ordinal", "title": "year"},
    "color": {"field": "temp_max", "type": "quantitative"}
  },
  "width": 800
}
```

**Comment by jwoLondon** [comment]
Yes - that would be great. I frequently have to resort to the manual calculation approach, which is a bit of a hassle and clutters code.

**Comment by jakevdp** [comment]
More generally, it might be useful to have the notion of a complement timeUnit... For example, if I want to draw a heatmap with dayofweek on the y-axis and week on the x-axis, there's currently no easy way to do that. The closest you can get is a ``yearmonthdate`` with a step of 7, but this starts each week at the beginning of the month, so it results in gaps in the chart:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/seattle-temps.csv"},
  "mark": "rect",
  "encoding": {
    "y": {"timeUnit": "day", "field": "date", "type": "ordinal"},
    "x": {"timeUnit": {"unit": "yearmonthdate", "step": 7}, "field": "date", "type": "ordinal"},
    "color": {"aggregate": "mean", "field": "temp", "type": "quantitative"}
  }
}
```
![BiG6l](https://user-images.githubusercontent.com/781659/79576588-652b7880-8078-11ea-89dc-e4e979e10a59.png)

You can achieve a better result via a series of transforms, but every time I encounter it I wish there were a cleaner approach. What if it were something like
```
{"timeUnit": {"complement": "day"}}
```
which would basically return all time info dropped by the ``"day"`` timeUnit?

**Comment by jheer** [comment]
I just added a `dayofyear` unit in this Vega PR: https://github.com/vega/vega/pull/2530

Also, Vega supports both week (`week`) and day of week (`day`) units that I think you should be able to use for a nice cross-tab, assuming Vega-Lite exposes those.

I don't think we'd support a complement, in part because as I don't know how that should handle all the fields of full date-times (with hours, milliseconds, etc).

**Comment by jakevdp** [comment]
Is the week timeUnit available in vega-lite? I haven't seen it listed in the docs or the schema.

**Comment by domoritz** [comment]
@jakevdp https://github.com/vega/vega-lite/issues/6349

**Comment by domoritz** [comment]
We can add this once vega/vega#2530 is released.

**Comment by kanitw** [comment]
This is now no longer blocked in VG 5.11

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/6526, pending Vega fixes.
