### ISSUE TITLE
Add week Time Unit

### ISSUE THREAD

**Issue by aborruso** [vega/vega-lite#6349]
Hi,
it could be very useful to be able to aggregate by week, or to have a generic step definition aggregation.

Thank you

**Comment by domoritz** [comment]
I think that needs to be done in Vega similar to https://github.com/vega/vega/pull/2530.

**Comment by jheer** [comment]
Vega already has a week time unit.

**Comment by aborruso** [comment]
Thank you @domoritz and @jheer .

I have asked in [mailing list](https://groups.google.com/d/topic/vega-js/qkRUUzE9jiM/discussion), they told me that there is no way to do it in vega-lite and to open here a feature request.

Can I use Vega time unit to aggregate in example [this](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvR9kOvGOQi8aYnXiwKkAL7qIkDEYDWZgZ4AJ6EyGaQEkoRqlCMSo5GhNxiOhE4vsrceMoRXhqQyErw3JoJ1EEaPgAeQZB4jKjIAKpKzJGoyixqUABmjMhimpHajr0NYRlQjqgpRuimBRA+IfXo1NRGwuOZzegqcZADQyOZs4QToeGRAI6sB426jVSeGh4gHkA) by week? How to do it?

**Comment by domoritz** [comment]
Looks like its just missing from the docs and schema. I'll add it.

**Comment by domoritz** [comment]
Was there a reason we didn't add week in https://github.com/vega/vega-lite/pull/5577 @haldenl @arvind?

**Comment by aborruso** [comment]
I have a great reply from Jake VanderPlas. I have [edited it](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvR9kOvGOQi8aYnXiwKkAL7qIkPEfRKsABm3EaoZgDaGhAGeIyoyACqSsxmkACe1mHKLNqOalBBjMhimml5yAWQ6LDlOpVe0WCgEK1Q6NTURsL5OBEG3IRpCQFVRSVlOL5OVTVpjqhDHgC63m1QXdyshOzpkZAVkMtNjW0G8Ohi8Kxi9XXpABR5rKh0FQCUYAC8X2AATLNalNYKwlNp0rVTq0WutIAB3Rhg7hwyIDIbAl5jYqlNIgsHoCGAtJw5DIADWnlWTR8iiMeDq+ROaxi1PanW6tF6YH6rKgg2G1hUzLakHGOKmCyGwta1SBUElkFZK2lGyMWx2ez68NJFOObQ8GlWEA0kAwRgpUwkSkqa0gyCU8G4mkR1DMMJ8muaouxk3lM1U8vShEqUwAjqwAnFdHEqJ5hZAAB5u70TYk6qp4IMhvlGZ1KS4Z5h2NIAdR1YG4QTAmXQRk8GgNHiAA), I still have to understand it well (I'm still a beginner); I have to understand for example why `day(datum.date) == 2` is monday, but it seems to me a good solution

**Comment by kanitw** [comment]
> Was there a reason we didn't add week in #5577 @haldenl @arvind?

I think it's simply because we didn't notice that Vega's new timeunit support week, which Vega-Lite's old implementation did not.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6354

**Comment by kanitw** [comment]
## temporal type

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Using `labelExpr` to show only initial letters of month names.",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "timeUnit": "week",
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "aggregate": "mean",
      "field": "precipitation",
      "type": "quantitative"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/79804341-b0fc4d00-8318-11ea-9061-c22861898c06.png)

- the tick doesn't really start at the first one.
- The last week is somehow 00.

## Ordinal type


```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Using `labelExpr` to show only initial letters of month names.",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "timeUnit": "week",
      "field": "date",
      "type": "ordinal"
    },
    "y": {
      "aggregate": "mean",
      "field": "precipitation",
      "type": "quantitative"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/79804489-ffa9e700-8318-11ea-98fd-feb80f79fe12.png)


- There are two W52 (one at the beginning)

**Comment by kanitw** [comment]
Since this is broken, I'm reverting them in https://github.com/vega/vega-lite/pull/6376. We can revert the PR later to re-enable them.

**Comment by domoritz** [comment]
The first week is 52. That's odd and the spec looks right. Maybe this has to do with the fact that the week number is defined such that the first week of the year is the week that contains that year's first Thursday.

<img width="308" alt="Screen Shot 2020-04-20 at 16 16 47" src="https://user-images.githubusercontent.com/589034/79808327-57008500-8322-11ea-9f80-53b1ee38e7bc.png">

**Comment by domoritz** [comment]
Spec to play with

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"date": "2020/01/01"},
      {"date": "2020/01/02"},
      {"date": "2020/01/03"},
      {"date": "2020/01/04"},
      {"date": "2020/01/05"},
      {"date": "2020/01/06"},
      {"date": "2020/01/07"},
      {"date": "2020/01/08"},
      {"date": "2020/01/09"},
      {"date": "2020/01/10"},
      {"date": "2020/01/11"}
    ],
    "format": {"parse": {"date": "date"}}
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "date", "aggregate": "count", "type": "quantitative"},
    "y": {"field": "date", "timeUnit": "yearday", "type": "ordinal"}
  }
}
```

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/6526, pending Vega fixes.
