### ISSUE TITLE
Do we need to support UTC in valueExpr?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6350]
See here: https://github.com/vega/vega-lite/blob/c031e232fc8495e54be2fe28118128b8e30a099d/src/channeldef.ts#L1244. Why are we not using isUtcSingleTimeUnit?

**Comment by haldenl** [comment]
The `normalizeTimeUnit` call at the beginning of the function removes any `utc` prefix so there is no need to check for a `utcSingleTimeUnit`.
