### ISSUE TITLE
Cannot derive new field because stats are missing

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#636]
You cannot derive a field with the formula transform that doesn't exist yet because we don't have updated statistics. 

Options are
* get rid of stats in vl
* similar to above but we still internally collect stats using vega itself
* require users to provide stats for all derived fields

**Comment by kanitw** [comment]
Since we plan to get rid of stats (if possible) anyway #618, we should try that first.

**Comment by domoritz** [comment]
Well, this issue still remains as of now but since it will be fixed I'm fine with closing.
