### ISSUE TITLE
Throw a warning if `customFormatTypes` is not enabled

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6382]

**Comment by domoritz** [comment]
The warning should appear when a custom format type is dropped. I think this would greatly improve debugging. Should we bump the priority?

**Comment by kanitw** [comment]
Let's also drop it properly (https://github.com/vega/vega-lite/pull/6400#discussion_r415105388).

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6448
