### ISSUE TITLE
If the legend size is big, there is no way to see the full legend

### ISSUE THREAD

**Issue by jerinjjose** [vega/vega-lite#6385]
If the legend size is big and my limit is 100 means, it is creating the ... after the 100 sizes. But I don't see any way to see the full legend name after that.

It will be helpful if the user can see the full legend while hovering as an HTML title attribute.

Please find the below screenshot for more info. 

![image](https://user-images.githubusercontent.com/10355174/79832838-e613a880-83c7-11ea-96ca-a55d05445d77.png)

**Comment by domoritz** [comment]
That's by design. I think Vega could add a little tooltip to show the full title. 

Please file a feature request against Vega with a small example spec.
