### ISSUE TITLE
Refactor LegendScales

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6390]
We should use https://github.com/vega/vega/blob/cab71ae62b0a6a68d00cb9ea72571838d814b972/packages/vega-parser/src/parsers/guides/constants.js#L32 instead of https://github.com/vega/vega-lite/blob/2edc6bc71704799fce316add68ad461573be87e2/src/legend.ts#L16. However, we cannot import it right now because Vega parser does not have typings yet.

**Comment by kanitw** [comment]
I'd rather not add a dependency to vega parse simply for a single constant array. 

Close?

**Comment by domoritz** [comment]
Ideally, rollup would only import one value but I suppose that may not be true.
