### ISSUE TITLE
log scale breaks stacked bar plot

### ISSUE THREAD

**Issue by tbenst** [vega/vega-lite#6396]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

When using log scale + color, nothing gets plotted. Either works on its own.
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "timeUnit": "month",
      "field": "date",
      "type": "ordinal",
      "axis": {"title": "Month of the year"}
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {"type": "log"}
    },
    "color": {
      "field": "weather",
      "type": "nominal",
      "scale": {
        "domain": ["sun", "fog", "drizzle", "rain", "snow"],
        "range": ["#e7ba52", "#c7c7c7", "#aec7e8", "#1f77b4", "#9467bd"]
      },
      "legend": {"title": "Weather type"}
    }
  }
}


```
Note that without the scale line, this plots. Likewise, this works without the color block.

**Comment by domoritz** [comment]
You cannot use a log scale with count because count needs a 0 baseline but log(0) is not defined. This is not supported by design.

**Comment by tbenst** [comment]
@domoritz I don't think that's accurate.

```

{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"x": 1},
      {"x": 1},
      {"x": 1},
      {"x": 1},
      {"x": 1},
      {"x": 1},
      {"x": 10},
      {"x": 10},
      {"x": 20},
      {"x": 50},
      {"x": 50}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": true,
      "field": "x",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {"type": "log"}
    }
  }
}
```

![visualization](https://user-images.githubusercontent.com/863327/80172528-1151ef80-85a2-11ea-953d-0e82785ccd90.png)

**Comment by domoritz** [comment]
You're right. I wasn't very precise in my response. What I meant was that while some charts may work (like the not stacked version), we don't officially support using a log scale when 0 is a meaningful value (a bar chart encodes length and therefore has a zero). Therefore, we are not going to fix any issues with charts that use a logscale with meaningful 0. Does that make sense?

**Comment by tbenst** [comment]
Ah ok. What’s the beat approach then, that of https://github.com/vega/vega-lite/issues/4792 ?

**Comment by domoritz** [comment]
Instead of a bar chart, I would use point or line marks if you want to use a log scale. The chart in #4792 uses a log scale on the axis orthogonal to the bar length.

Thank you for filing the issue by the way and questioning my response. I may miss some relevant detail sometime.

**Comment by tbenst** [comment]
I’m plotting a distribution (where the samples come from different experiments, hence need for stacking) so the only options that make sense, IMHO are bar/histogram or density. Unfortunately, density also works with a log scale but does not work with a log scale and color stacking. This occurs even if there’s no 0 in my data.

I very much appreciate your work on Vega Lite, and it’s a great project. I’d love to see support for log scale + color added. ggplot2 supports this for example. Do you think this something that you’d consider?

**Comment by jwoLondon** [comment]
You can use `symlog` instead, which will work even if your data contain meaningful 0s.

**Comment by domoritz** [comment]
@tbenst we definitely consider it if there is a compelling use case. Of course, we have assign priorities to all feature requests. Can you post a few examples from ggplot (the charts)? Can you give `symlog` a try?
