### ISSUE TITLE
Vega-Lite v4: concatenation breaks faceted chart

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6397]
Consider the following faceted chart ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBnAUwXhzIFoB3C+ACzKwDoBjEgN0gF8ANOCgBbWFgDW+SDgCWAOzKQhESGXkcA9tAUBzfKAiqAngeFGoAM1lkc0aQAcsZDrIezE8WZvnLzRyHhjByVUSABHDFh5L09ZbiUVCyhYXV1nXQRQ0QpfJItAj2p8eQwcHH9Bf0gADwNIa1t7MMJEqC8RMgBVeQ9pER9mZXbg7MhNLB15WDwqgqxNOnrGu2lW4cLOnr6w4wosDaCQ6Qmpmf5hOagWWV0meHwAZgAGJMgteWt9VHRLWA4yA8fpASA5-np8M8+HwQHwgA)):
```json
{
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "line",
  "encoding": {
    "y": {
      "field": "precipitation",
      "type": "quantitative",
      "aggregate": "mean",
      "title": null
    },
    "x": {"field": "date", "timeUnit": "month", "type": "ordinal"},
    "row": {"field": "date", "timeUnit": "year", "type": "ordinal"}
  },
  "height": 30,
  "config": {"facet": {"spacing": 0}}
}
```
![visualization - 2020-04-24T051650 334](https://user-images.githubusercontent.com/781659/80211576-d32cee00-85ea-11ea-86b7-50f6765d15ea.png)

This works as expected. But when the same specification is concatenated with another view of the data, the faceted chart breaks ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBnAUwXhzIFoB3C+ACzKwDoBjEgN0gF8ANOCgBbWFgDW+SDgCWAOzKQhESGXkcA9tAUBzfKAiqAngeFGoAM1lkc0aQAcsZDrIezE8WZvnLzRyHhjByVUSABHDFh5L09ZbiUVCyhYXV1nXQRQ0QpfJItAj2p8eQwcHH9Bf0gADwNIa1t7MMJEqC8RMgBVeQ9pER9mZXbg7MhNLB15WDwqgqxNOnrGu2lW4cLOnr6w4wosDaCQ6Qmpmf5hOagWWV0meHwAZgAGJMgteWt9VHRLWA4yA8fpASA5-np8M8+HwQHwgA)):
```json
{
  "data": {"url": "data/seattle-weather.csv"},
  "vconcat": [
    {
      "mark": "line",
      "encoding": {
        "y": {
          "field": "precipitation",
          "type": "quantitative",
          "aggregate": "mean",
          "title": null
        },
        "x": {"field": "date", "timeUnit": "month", "type": "ordinal"},
        "row": {"field": "date", "timeUnit": "year", "type": "ordinal"}
      },
      "height": 30
    },
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "date", "timeUnit": "month", "type": "ordinal"},
        "y": {
          "field": "precipitation",
          "type": "quantitative",
          "aggregate": "mean",
          "title": "All years"
        }
      },
      "height": 50
    }
  ],
  "config": {"facet": {"spacing": 0}}
}
```
![visualization - 2020-04-24T052109 564](https://user-images.githubusercontent.com/781659/80211921-6f56f500-85eb-11ea-9a14-711181c6ed66.png)

This appears to not be the case in previous versions of Vega-Lite; for example, here is the chart viewed with Vega-Lite version 3.3:
![visualization - 2020-04-24T053044 062](https://user-images.githubusercontent.com/781659/80212671-c610fe80-85ec-11ea-90b8-e7c48ecd7a62.png)

**Comment by domoritz** [comment]
The issue is that the top chart uses `source_0` instead of `data_2` as the scale domain. [Open simplified spec in the Vega Editor](http://0.0.0.0:8080/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVJOcNZkFx+AdxP042ylAjEQAXyXEocqGrQBtUMjaANb6wrJwiiBwsp7KNLJkaKAAnkkgAGY0cILK+jjacFA0OHRq7PJKmMk4EegAjgxIspilLaSRSGRkBRSYtSAIJvJuIAAeaZnZueiqfZEtgwCqsnT6CHL089X9bNpxskh6I9pslhNZOfqzEZU0SyuY+skm2ls1+rv7h64ubgFIwVC8RuURibH2iU0Y3OUyuahBCzgy1W6HWzRgbx2e3i3xGqShk0u6HyhWKrXKmP0DSaLXUbRBnW6fDmqKGPxcAF0XEA)

**Comment by domoritz** [comment]
Looks like the issue is in the optimizer. When I reduce the number of optimization runs to 0, we get the right chart.

**Comment by domoritz** [comment]
Before optimization

![image](https://user-images.githubusercontent.com/589034/80898230-f5db9880-8cb5-11ea-9c93-2a498c7c5613.png)

After optimization but without MergeOutputs

![image](https://user-images.githubusercontent.com/589034/80898247-186db180-8cb6-11ea-8a89-2fd5d57c1c5e.png)

After optimization with MergeOutputs

![image](https://user-images.githubusercontent.com/589034/80898252-30453580-8cb6-11ea-95f3-edfa618dd934.png)

**Comment by domoritz** [comment]
With only some optimizers on

<img width="819" alt="Screen Shot 2020-06-10 at 22 38 51" src="https://user-images.githubusercontent.com/589034/84348972-293dfc80-ab6b-11ea-9dc1-abf7dd3b9a2f.png">

Before Optimization

![image](https://user-images.githubusercontent.com/589034/84349080-6acea780-ab6b-11ea-98aa-dc7c704df746.png)

After Optimization

![image](https://user-images.githubusercontent.com/589034/84348999-378c1880-ab6b-11ea-8a1b-c63d2436b2c7.png)

Without merge output

![image](https://user-images.githubusercontent.com/589034/84349185-a2d5ea80-ab6b-11ea-830b-e2d6a15c8063.png)
