### ISSUE TITLE
Fix vl and vg schema validation errors

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#640]

**Comment by kanitw** [comment]
Hmm.  Unclear what needs to be fixed?   Is it "make validation errors more readable"?

**Comment by domoritz** [comment]
I just pushed a branch where we have tests that a bunch of examples against the vl and vg schema. We have a lot of tests failures when I uncomment one line. Hence this issue.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/pull/641

**Comment by kanitw** [comment]
Fixed in #643
