### ISSUE TITLE
Throw error or gracefully warn if incompatible time units are used

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6401]
According to https://vega.github.io/vega/docs/api/time/#timeUnits,

> the 'quarter', 'month', and 'date' units can not be used in conjunction with the 'week' or 'day' units.

We should make sure to surface error in Vega-Lite (or drop incompatible units and warn). 

cc: @haldenl @domoritz

**Comment by kanitw** [comment]
We actually do not support array. The question is whether the string parsing we have should deal with this.

**Comment by domoritz** [comment]
We only support a short list of time units right now so I think we are good, no?

**Comment by kanitw** [comment]
Yeah, the schema would warn already if a specified one is invalid.
