### ISSUE TITLE
Escaping brackets in field inconsistencies

### ISSUE THREAD

**Issue by saschahofmann** [vega/vega-lite#6422]
I am observing what I think is inconsistencies when escaping brackets between fields in a bar and pie chart. Very similar to #5660 and #4123. 

This bar chart works despite me not escaping the `(` and `)` in the y field.
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "mark": {"type": "bar", "tooltip": true},
  "encoding": {
    "x": {"field": "x", "type": "ordinal", "axis": {"title": "[Owner]"}},
    "y": {
      "field": "SUM(\\[salary\\])",
      "type": "quantitative",
      "axis": {"title": "SUM([salary])"}
    }
  },
  "autosize": "fit",
  "height": 295,
  "width": 661,
  "data": {
    "values": [
      {"x": "Alex", "SUM([salary])": 31},
      {"x": "Thomas", "SUM([salary])": 12},
      {"x": "Peter", "SUM([salary])": 18},
      {"x": "Paul", "SUM([salary])": 18},
      {"x": "Hugo", "SUM([salary])": 41}
    ]
  }
}
```
However when I try turn the same data into a pie chart like that:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "mark": {"type": "arc", "tooltip": true},
  "encoding": {
    "color": {"field": "x", "type": "ordinal", "axis": {"title": "[Owner]"}},
    "theta": {
      "field": "SUM(\\[salary\\])",
      "type": "quantitative",
      "axis": {"title": "SUM([salary])"}
    }
  },
  "autosize": "fit",
  "height": 295,
  "width": 661,
  "data": {
    "values": [
      {"x": "Alex", "SUM([salary])": 31},
      {"x": "Thomas", "SUM([salary])": 12},
      {"x": "Peter", "SUM([salary])": 18},
      {"x": "Paul", "SUM([salary])": 18},
      {"x": "Hugo", "SUM([salary])": 41}
    ]
  }
}
```
I get an empty chart. Even if I remove the the round brackets (of course also in the data) nothing changes only if I remove the escaped square brackets, I get the expected pie chart.

**Comment by saschahofmann** [comment]
Also if I escape the round brackets like this `"SUM\\(\\[salary\\]\\)"` I get an `Access path missing closing bracket: SUM\(\[salary\]\)`. Am I missing something?

**Comment by domoritz** [comment]
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgkKqIpCY2bQZho40mFQzgBfJXFlQ2AExqyymkB6CbCr+AGY0cIKeBgAepjp6BsHeskiCIC5m8JgoqKDhkdHoAMoAqgCyABQAOtUA2hBpRtq1ALoAlPG6+ugAjgxIstY51qQZmUgM5hA0AF49IOGYpvA0ZFhoAEwAnACsSgDuNJ70aABsZwCMSp5IOf7EaY4QaHWgcegAgoJwcUplVQaTRU2g6aAAzJcXO8DAAVGBsZAvf4VSpAwTNMGoS6baEgD4gAAKcEwcBCKMBjQxIKxlwAHHiCYTJukKWiqZjOtiGQoYegABIMMhsUwA9nA0FcsRQ1pOJxAA)

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6444
