### ISSUE TITLE
Revise syntax for using signal in an encoding constant `value`.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6433]
Seeing  datum signal in https://github.com/vega/vega-lite/pull/6432 as   `encoding.color = {datum: {signal: ...}`

I think we should revise `encoding.color = {signal:...}` to be `encoding.color = {value: {signal:...}}` so it's consistent and easier to teach, though a bit more verbose.   

Basically, once we have signal as an official feature, we can just say `value` is a constant value in visual domain and `datum` is constant value in data domain, both of which support signals as their values.  (Instead of saying value signal use `{signal:...}` but datum signal needs nesting.)

**Comment by kanitw** [comment]
So I'm no longer sure if we should 100% do this.

Basically we also have conditional properties in axis.

For example, `gridColor` can be `"red"` or `{"signal": "gridColor"}`.

We also support previously support conditional: 

```
gridColor: {
  condition: {
    test: '<is major grid>',
    signal: 'majorGridColor' // this can also be `value: "#ddd"`
  },
  signal: 'gridColor'  // this can also be `value: "#eee"`
}
```

I'd argue that for grid color, this conditional structure makes more sense because it's a smoother to go from non-conditional signal to conditional signal.


cc: @haldenl

**Comment by kanitw** [comment]
One possibility is to do the change only for encoding, so encoding channel definition must have only one of (1) `field`, (2) `datum`, and (3) `value`, instead of 4 options.  This simplify the possible cases for possible conditional combination as well. 

Meanwhile, conditional axis properties could stick with the same structure.

-----

If we haven't added `datum`, the other way to consider this is to drop `datum` and instead allow `value` to use `scale`.

For example, `datum: 5` could become `{value: 5, scale: true}` where `scale: true` already derives scale type based on the value's data type. 

Then we can consistently use `signal` with scale as well.

**Comment by domoritz** [comment]
Hmm, since `value` is the only allowed property in value encodings, I am also not convinced anymore. I'm okay with leaving the syntax as is for now until we discuss a revision of selections with @jheer and @arvind.

**Comment by domoritz** [comment]
`{value: 5, scale: true}` makes sense to us but I think is a lot more confusing compared to `datum`.

**Comment by kanitw** [comment]
Yes, but the good thing about doing this just for encoding is that it will simplify the encoding types a lot, which is a sign for a right solution. 

However, it doesn't make much sense to do the same for conditional axis property.

**Comment by domoritz** [comment]
I'm good to do whatever makes things easier. To me the encodings really were the ones where I liked just having three options: field, datum, and value encodings (+count aggregates).

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6438
