### ISSUE TITLE
signals do not work in predicates

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6436]
I would expect this to work

```
        opacity: {
          condition: {
            test: { field: "x", lte: { signal: "'10'" } },
            value: 0.5,
          },
          value: 1,
        },
```

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWgArKW5+egAwiWoYgDMlSBJACJ1AJwAjM1JAKJ1mT15LQUAYnWlTSNJAOJ1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBdbqwXCyUGzKNLJkaKAAHq8gAGY0cILKBRQSkwAE8cHACmx1I9ZFFgkg3jQIJ9BEhPIJ9M8LGgAAzZY4gz4-P4A9BpYFgiHoACODCQsh0gR0pBAxzYOCQUDohPCIHuskeOjkn0wakwRN+-0uwUEos+JjIsMEaDEeOOkWiVJxlAqSg1MTQPXxQA)

**Comment by kanitw** [comment]
Is it conditional encoding specifically or all predicates?

**Comment by domoritz** [comment]
Oh, maybe it's all predicates.

**Comment by kanitw** [comment]
This is a bug, we shouldn't output `datum[\"b\"]<=isDate(40) ? time(40) : 40`. 

I'll fix it.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/6439
