### ISSUE TITLE
Should we move documentation from wiki to the repo?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#645]
@domoritz  and I were discussing that putting doc in wiki has a few cons:
- it's hard to review modification by external (there is no pull-request mechanism)
- it's hard to document properties for different version

By having documentation as markdown files in the repo
- docs are attached to each version
- people can send pull requests to update the docs 

Alternatively, we can consider creating a separate vega-life-docs repo, but having the docs here would be simpler in terms of syncing version.   

@jheer  any opinion on this?

**Comment by domoritz** [comment]
+1 for docs in repo but not a separate repo
