### ISSUE TITLE
unselectedOpacity should be a legend property, not just a legend config

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6464]

**Comment by kanitw** [comment]
Why?

**Comment by kanitw** [comment]
(FWIW, I think unselectedOpacity is kinda different from other legend property, so I'm not sure if I like it.)

**Comment by domoritz** [comment]
What if I want different opacities for different legends?

**Comment by kanitw** [comment]
Then you can override? Just like you can override any config?

**Comment by domoritz** [comment]
That's the point. I cannot override the opacity for one specific legend only. 

<img width="1199" alt="Screen Shot 2020-05-10 at 10 02 27" src="https://user-images.githubusercontent.com/589034/81505604-5e71d900-92a5-11ea-8861-dc02c967df2c.png">

**Comment by kanitw** [comment]
Ok got you know.  This is a dupilcate of https://github.com/vega/vega-lite/issues/5921, but I think the description in #5921 is better so I'll close this one.
