### ISSUE TITLE
Errorband doesn't work on X axis

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6491]
[Works](https://vega.github.io/editor/#/examples/vega-lite/layer_line_errorband_ci)
[Doesn't work](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5K4sqG2U1ZZNKACebkADMacQcr6AJpwpoogmO44cPqYiDhs2kh6Spg0CHAAqrJ0+u6h2iBWNiCCSPmFqADaoMjaANZekdH6cNraiUxIsoG2AB5xspj6UDRFtvaOzq6aIH1evv6B6ACyNIJwEAD60dpbAOLJgnLhzTHoAI4M3WnqaaSndBv6K6GyAARs3u9rGxDvu3eh0Exw+AAoAJwAVgApO8AMIASQgAEoisUFLVTI10MJZDEJg4nC4vPNZkgyGRtHw4voMt1wosAi91psdm0DkcTqkoucQFcbnQ1DQHsUrABdKxAA)

**Comment by willium** [comment]
if you agree this is a bug, happy to work on a fix

**Comment by willium** [comment]
It does seem to work for [1D errorbands](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SoJIAJ7maADaoMjqANblXk6YeXCyUGzKTmRooAAesyBxNHCCyuUAEokeXvYdSpit4eUAjgx+OpU6pCBNIK2Ly6vr6ACywWoA+uHqnwDiSCicjyh2O6DOFzophoNwacIUPVSAyKIFBcHK5nUiSYfnWSjgc0wYxG6AgmFUxDybBwSCgdAeqAADJQAEx3MYTKbORYLFFPNabbaebzqEFHdHg86yS7Q2HwxH9crqBghUbjSbTHmPFYC9BbdzCvaig7i05SmXXdFKJBkMjqPhE8oIOB+W7ykC9ZGgNEY9RY9Q4-yjQnE8pkilUml0w5oZls-HqrkzFEM0D8l4gd4hCDfcz-QHRMVgkAQ6VQy1upoK5EgZWqhOczUp7XPcpZr4-fNA+Qm4uli0wq0gG12h0Sj0uxpwgC6DSAA)

**Comment by domoritz** [comment]
Even smaller example [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5Lk2gNZpQmAJ444+uNu1ttTJLLKiiBwAB6YcLKY+lA0IDYhslBsyjSyZE4gLpkAZjRwgkHoAJpwpsGu7voRCDi+SHpKmDQIcACqsnT6LmXa8UqhufmF+gCyNIJwEAD67trTAOINgnIVbh7oAI4MAc3qzaQVdJNjZbIABGw55+OTEOdz50uCKxcAFACcAKwApOcAwgBJCAASniVisQA). Yes, looks like a bug to me. Probably something small in the normalizer.

**Comment by chanwutk** [comment]
The default orientation of `errorbar` and `errorband` is `"vertical"`.
For a quick fix, you can add `"orient": "horizontal"` to the mark definition. Here is the [spec](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5K4sqG2U1ZZNKACebkADMacQcr6AJpwpoogmO44cPqYiDhs2kh6Spg0CHAAqrJ0+u6h2iBWNiCCSPmFqADaoMjaANZekdH6cNraiUxIsoG2AB5xspj6UDThiX5D+jATAF5y6noldg5OLl59Xr7+gegAsjSCcBAA+tHaJwDiyYJy4c0x6ACODN1p6mmk93RH+nuhsgABGxvICDkcIIDzoDroJbkCABQATgArABSQEAYQAkhAAJRFYoKWqmRroYSyGK2eyOZyuTQgTYMpBkMjaPhxfQZbrhbYBP6HY5nNpXG53VJRR4gF5vOhqGhfYpWAC6ViAA).
@domoritz @kanitw should I make change to this behavior? I think the `"orient"` of the `errorbar` and `errorband` can follow `temporal` axis?

**Comment by kanitw** [comment]
Yes we should adapt orient so that this works by default.

**Comment by domoritz** [comment]
I think it would make sense to orient along time before orienting along quantitative. Line already behaves like that [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5Lk2gNZpQmAJ444+4bI82QcWVBsyjSyZE4gLuEAZjRwgsr6AJpwpoogru76mIg4bNpIekqYNAhwAKqydPouKdogvgAe0bHx+gCyNIJwEAD67to9AOIFgnJpGR7oAI4MSLLF6sWk43Rd7SmyAARsUZsdXRCb-ZvDgqNbABQAnACsAKSbAMIAkhAAlPVWVkA).
