### ISSUE TITLE
Setting size of errorbar removes the ticks

### ISSUE THREAD

**Issue by rikardn** [vega/vega-lite#6495]
I am trying to make errorbars a bit thicker. Using ```size```in ```encoding``` works, but removes the ticks. The json below (modified from https://vega.github.io/vega-lite/docs/errorbar.html) gives no ticks as expeced when testing in https://vega.github.io/editor/

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/barley.json"},
  "layer": [
    {
      "mark": {"type": "errorbar", "ticks": true},
      "encoding": {
        "x": {
          "field": "yield",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "y": {"field": "variety", "type": "ordinal"},
        "size": {"value": "2"}
      }
    },
    {
      "mark": {"type": "point", "filled": true, "color": "black"},
      "encoding": {
        "x": {"field": "yield", "type": "quantitative", "aggregate": "mean"},
        "y": {"field": "variety", "type": "ordinal"}
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJYKTm42tAG1QybQGs0oTOZw4fWdtNm0TFyVMGigvCDRMbQY4OxA4WSg2ZRpZMl8QAA98gDMaOEFlfXMyisUQf0D9AEcGJFlo9WjSOugkQSDNEAAvZzY0Yr6IFNTzEprK9GJTMv86hoGQMOzZPpBUiBoR-KXBZLQAJhsrhQ9TH0H1-Rw2HMw60sF+hcTkpUzBML6JgOWJ7JTpTLbPKDIqDUrlBYgaoItYBDYtNodNQ0bpKJBkMjaPiYDYIOBtMFIuYoxbLOCrKJo-RbHK7K42AC6NiAA)

**Comment by domoritz** [comment]
Thank you for reporting the bug. This looks like a bug in the normalizer.

**Comment by domoritz** [comment]
@chanwutk do you want to fix this one?

**Comment by chanwutk** [comment]
Right now, setting `size` in `encoding` also set the size of the ticks.
[Here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJYKTm42tAG1QybQGs0oTOZw4fWdtNm0TFyVMGigvCF8QKDZBMP1tOGUQGzsQOFkk5RpZMgSADwSAMxo4QUz0c2raxRB-QP0ARwYkWWj1aNJm6CRBIM0QAC9nNjQK4Yg4bKVzSsa6kGJTav9m1tGQMMLZYaylCBpJhI3BBlGAJmy7D1MfMd39HDYizGaqwRG6zDaG5KJIpFzoJgOWInXL5NiHEpjcpjKo1NYNNE7AJ7TrdXpqGgDJRIMhkdIUTB7BBwbow5Yo1b6DbaLbLKLY-QHIrHB4AXRsQA) I change the color of ticks to red.
Should setting `size` in `encoding` only affects the bar width or should we add other property to only set the size of the bar?

**Comment by domoritz** [comment]
I think it should set the size of the ticks and the rule between the ticks.

**Comment by chanwutk** [comment]
Do you mean the thickness of the ticks?

**Comment by domoritz** [comment]
Yes, thickness of both of them.

**Comment by kanitw** [comment]
See https://github.com/vega/vega-lite/pull/6502#issuecomment-631653916, I think it's better to add `thickness` as mark property.
