### ISSUE TITLE
Errorbars alone causes incorrect scale

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6497]
In [this chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJXFlQ2ymrLJpQ5jyABmNOILK+sSm-pheSuE4cPps2i6ySHo2diCCSOZw2mgA2qDI2gDW3lEx6FnacSbZ9gAemA6Y+lA0IKkOTgnumiC13n4BQejm-oGKIKX6AI4MSLKYdGo0pOMLmIJlIABCphvmAAQAmqNBKTYAujZAA), we'd expect the x scale to more similar to how it is in [this chart](https://vega.github.io/editor/#/examples/vega-lite/layer_point_errorbar_ci)

**Comment by kanitw** [comment]
In one of them, you have `"scale": {"zero": false}` and not in another.
