### ISSUE TITLE
Revisit params' hoisting/scoping

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6499]
A selection has two parts of its scope.  A selection can referred anywhere globally, but the inferred event streams are only applied locally. 

This has been limiting.  For example, we can't define a selection as a part of multi-view spec (https://github.com/vega/vega-lite/issues/4268).  

We should revise if we can allow some kind of decoupling here.  For example, can we define selection at the top-level, but capture event streams for certain specific unit views?

**Comment by arvind** [comment]
Fixed with #6926 — selections can now be defined at the top level of the specification, with an optional `views` property to constrain event handling to specific subviews.
