### ISSUE TITLE
timeUnit step does not respect cross month bins

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#6505]
See the following animated gif:
![timeunit_step](https://user-images.githubusercontent.com/5186265/82198367-7fb57380-98fc-11ea-8392-06887b0d0e94.gif)
With a new month it starts a new bin
The first bin (not sure if it still called bins with timeUnit steps), goes from 31 dec to jan 3 and the 2nd bin jan 1 tot jan 4. 

This leads to overlapping bins. I'm not sure if this is intended.
The used spec (derivitated from https://vega.github.io/vega-lite/docs/timeunit.html#example-customizing-step)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"date": "Sat, 31 Dec 2011 00:00:00", "distance": 1},
      {"date": "Sat, 31 Dec 2011 00:01:00", "distance": 1},
      {"date": "Sat, 31 Dec 2011 00:02:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:00:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:01:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:02:00", "distance": 2},
      {"date": "Mon, 02 Jan 2012 00:03:00", "distance": 1},
      {"date": "Mon, 02 Jan 2012 00:04:00", "distance": 4},
      {"date": "Mon, 02 Jan 2012 00:05:00", "distance": 2},
      {"date": "Tue, 03 Jan 2012 00:06:00", "distance": 5},
      {"date": "Tue, 03 Jan 2012 00:07:00", "distance": 2},
      {"date": "Tue, 03 Jan 2012 00:08:00", "distance": 6},
      {"date": "Tue, 03 Jan 2012 00:09:00", "distance": 4},
      {"date": "Wed, 04 Jan 2012 00:10:00", "distance": 1},
      {"date": "Wed, 04 Jan 2012 00:11:00", "distance": 1},
      {"date": "Wed, 04 Jan 2012 00:12:00", "distance": 3},
      {"date": "Thu, 05 Jan 2012 00:13:00", "distance": 0},
      {"date": "Thu, 05 Jan 2012 00:14:00", "distance": 2},
      {"date": "Thu, 05 Jan 2012 00:15:00", "distance": 3}
    ]
  },
  "mark": "bar",
  "encoding": {
    "stroke": {
      "condition": {"selection": "HOVER", "value": "black"},
      "value": null
    },
    "x": {
      "field": "date",
      "type": "temporal",
      "timeUnit": {"unit": "yearmonthdate", "step": 3}
    },
    "y": {"field": "distance", "type": "quantitative", "aggregate": "sum"},
    "tooltip": [
      {
        "field": "yearmonthdate_step_3_date",
        "type": "temporal",
        "title": "Datum start"
      },
      {
        "field": "yearmonthdate_step_3_date_end",
        "type": "temporal",
        "title": "Datum end"
      }
    ],
    "color": {"field": "distance", "type": "quantitative", "aggregate": "sum"}
  },
  "selection": {"HOVER": {"empty": "none", "on": "mouseover", "type": "single"}}
}
```

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoVZjhoQAZTUKABAGYAjLYAicKLYBMABkfPv3qgBQd6KKjQQ6rJQ5qiOAL4KJmqxVjYOzm4ePn62wb4hYcoRUTFoCUkqKRbWmHZOru5evv6B3p6FSsWRSNGxnonJZjUMsna+tgBSvc2Onnlti0UlvWVxg1XD6Jaj487TsrPz+Y6d4T195RumqTtjefszOcdtHQHLF2sDlTcWALJycbzA5HBZBexnbqlWIVIapAH3dpTJ6+F5BMSQlaXVBia7VdAIoHIw7PMHeACsmM+-TxWxAABU9ON7MTQfkAGxU6Focm01KMuDM1mk-IAdi5qxpP3xDKZeRZIJFbQAHBLsey+RYBULFaiyQBONVrXHSukAdTgynGYmFeuCjiWXSxa1hm1SFqteRturmYL8RphmvQHuttt99reoSd1LQ9iDDMY43JYbRjgh72j3KC8fpibyyZ9qYxGfOWe+cK1eYpKb9lJLUMlsfiAF1EiBkAAnADWFiYSA7YTg0TYxVkZDQoEiHbYXdioCgcmKmHY8k0IAgcEE7mXcgsAAkAPIANQAogAlMLaXSpJiCJBQHttq96NCyBiCQRtgAeE5AADMaE3ZQLF+JRMAATxwVIzAQHA2A7HQwmXBA4AAVVkOhf1GTD0HAuB+wQOR6FA9czBwJs23A38AKAkDnXMMDINSABHBhemXdRl1IMIkDIMgOz4OkIAYBAQDbTA2DYQRl3I1BjH-QDBGA3D8I7QjZGIlIAH1IjgHAtPsLSSIgqCLBguCEMEJC6C3CwXDUETbB6DtMDEyoaKUiw8IIoiYBuHSyIMoztKHYDGNM9BzPgxCwJs1J7MwRzQrE5slAXQR4OoxTlNLRtwpYtiNLoNQaG4pReP4wTUmE0T4jbDctygHdV1AQ9TwvNdEBwCCLFkOQGJAXd0EIhgNzYUgB3yiwIBoMdbLq+IgA)

**Comment by mattijn** [comment]
I can reproduce this with Vega only:
<img width="400px" src="https://user-images.githubusercontent.com/5186265/82253822-fc267180-9951-11ea-99c0-d1511b8b514c.gif">

Using this spec:
```python
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "padding": 3,
  "width": 200,
  "height": 20,
  "data": [
    {
      "name": "SOURCE",
      "values": [
        {"date": "30 Mar 2020"},
        {"date": "30 Mar 2020"},
        {"date": "31 Mar 2020"},
        {"date": "31 Mar 2020"},
        {"date": "01 Apr 2020"},
        {"date": "01 Apr 2020"},
        {"date": "02 Apr 2020"},
        {"date": "02 Apr 2020"},
        {"date": "03 Apr 2020"},
        {"date": "03 Apr 2020"},
        {"date": "04 Apr 2020"},
        {"date": "04 Apr 2020"}
      ]
    },
    {
      "name": "DATA",
      "source": "SOURCE",
      "transform": [
        {"type": "formula", "expr": "toDate(datum.date)", "as": "date"},
        {
          "field": "date",
          "type": "timeunit",
          "units": ["year", "month", "date"],
          "step": 3,
          "timezone": "utc",
          "as": ["bin_start", "bin_end"]
        },
        {
          "type": "aggregate",
          "groupby": ["bin_start", "bin_end"],
          "ops": ["count"],
          "as": ["bin_count"]
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": {"data": "DATA", "fields": ["bin_start", "bin_end"]},
      "range": [0, {"signal": "width"}]
    },
    {
      "name": "color",
      "type": "linear",
      "domain": {"data": "DATA", "field": "bin_count"},
      "range": {"scheme": "viridis"}
    }
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "DATA"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "bin_start"},
          "x2": {"scale": "x", "field": "bin_end"},
          "height": {"value": 20},
          "fill": {"scale": "color", "field": "bin_count"}
        },
        "update": {"fillOpacity": {"value": 0.5}, "stroke": {"value": null}},
        "hover": {
          "fillOpacity": {"value": 1},
          "stroke": {"value": "red"},
          "strokeWidth": {"value": 3}
        }
      }
    }
  ]
}
```
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhA4kAE3k1xZNAGYZAdxrz6aAEwAGQzPg0yWAyZDykmFKgDaocUgRw0IAMoB5AKoASgDCAKLSIMRIADYMcBBozjZ2HuhqhgAEALJIAE7pRkYgAL5SoLaYKSBpWbn5hoUlZcmeagCMNXkFhsWlSRUt7dmd9d2NfZWG7QCCOMMNveUT07N180396PXpM3OjC82b+tsrXT3rE2rHu2fjnoaXO6t753cALFdPN4tvH6dFALpjVzuTwAESmABUpuExAwclBKr5AqFwpgckhxBAAGZsHIIBKgTAATxwlRxeIYURQMjgAA9Zp5MGxQckABTlBgISiLACU4SQ8XQ3zGWJocCi8k83xkxNJjJo7gY4jo4SVdEFjhARLguXCCAkehk33+MggFRw6hlCrgAC8JJUGJgoPyNSAmMoAPpm3KYcLu8QeuDiSWA3qyypIMhkHJ8foyaNsBg4JhEhJuz3enK+mT+wPBkAmkBsPBpqCJ8S+wsCtO5stKysAgGmqDROIEkDAyq01EkyqYa3heRsZDKNDrBwgcFQ8Ki8XyV25zPZ9MBoMhkogdEqFKOEygCDmVxRTzaXQwYqhlxuSplqK4nty9BRZQ6nKD4dIUeocdgyHQmSzhKni1uWvobluZApPusCIJUxA0DkOg0PERRNiAyA5AA1hqhK9p4MZQMuWI5MOY59BOU7QhuQZlvIUEgEGFRvt+IDdix0Ctp43YAWKQHoIu9hZj0rH6GRHFRF2M68ZK-GemuwlmBYvosZEMQpEYG6ilEx7sS2EmeLe948XOwGenWFbFBuSbfCxWlRD4chQHQqYqdEsRoIYlACBuZokZh9Gqe5qDiJSUSoaYbCkMxoB2Q5SBOcSZGBSkrQ+WibD+UlbmVDGkppX5cAAOo6HorlqeoqGoYCQA)

Somehow I was expecting here two bins with each 6 records. 
Maybe this is a feature of the [timeunit](https://vega.github.io/vega/docs/transforms/timeunit/) transform? By the way, even though the bins overlap, the count within the bins are not counted twice (4+2+6 == 12 data records).

**Comment by domoritz** [comment]
Should we move this to Vega then?

**Comment by mattijn** [comment]
Yes, I guess so. Now looking to the Vega I see it use: `"units": ["year", "month", "date"]`

And for Vega-Lite it is `"unit": "yearmonthdate"`.

For VL I did expect a group by on dates and not a separate group by of first year, then month, then dates within month. Which seems what’s happening if I read vega right. 

But I also can not see how it should be done different using `timeunit` transform

**Comment by domoritz** [comment]
> For VL I did expect a group by on dates and not a separate group by of first year, then month, then dates within month. Which seems what’s happening if I read vega right.

Where do you see that? `"groupby": ["bin_start", "bin_end"],` is grouping by two fields only. 

For the Vega issue, can you reduce the Vega to the minimum specification that shows the issue?

**Comment by jheer** [comment]
The current implementation of timeunit applies flooring functions by extracting the requested time unit components. The step is then applied only on the "least significant" unit.

So, for `[year, month, date]`, the transform extracts the year, extracts the month, and then extracts the day with any step specification. This means that Feb 2, 2013 with step value 3 is translated into a new date instance with year=2013, month=1 (Feb), and date = 1 (month-based date value is floored to match step=3).

If you want the step to operate on different units (e.g., dayofyear rather than day of month), you can specify the time unit differently. For example, [year, dayofyear] will work better, but note that you can still have step-rounding artifacts at year boundaries.

**Comment by domoritz** [comment]
I see. So let's close this as working as expected then. Please file an enhancement request with Vega.

**Comment by mattijn** [comment]
Thanks for the update. 
The `["year", "dayofyear"]` for Vega works as described. This solves cross-month bins. 
Great and perfect for my uses-cases, except.. its not possible by Vega-Lite yet:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/5186265/82365870-96012380-9a11-11ea-9749-0f45294fde17.png">

(where this is currently wrongly compiled into `["year", "day"]` in Vega)

For Vega it might be interesting to have one of the following transform units:
- days since 1900-01-01 (like Excel `Day()` function) 
- days since 1970-01-01 (unix epoch)
- days since 0000-00-00 (like mysql `TO_DAYS()` function)

**Comment by domoritz** [comment]
Coming soon: https://github.com/vega/vega-lite/issues/6348.

It should be pretty straight forward but I haven't had cycles for it yet.

**Comment by mattijn** [comment]
Oh perfect! I missed that issue. You (plural) are doing great, take it easy!
