### ISSUE TITLE
Scale range is not ignored for x/y channels

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6517]
The documentation for scale ranges for `y` at https://vega.github.io/vega-lite/docs/scale.html#range reads: “*The range is always [0, height]. Any directly specified range will be ignored. Range can be customized via the view’s height property.*”

However, it doesn't appear to be ignored:

<img width="247" alt="Screen Shot 2020-05-19 at 14 22 15" src="https://user-images.githubusercontent.com/659086/82363673-24f34900-99dc-11ea-9073-c785fe4f1c36.png">

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.12.1.json",
  "description": "Demonstration of scale range for y field.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative", "scale": {
      "range": [50, 150]
    } 
    }
  }
}
```

Naïve triage shows that `parseScales(model, {ignoreRange: true})` is only ever called from `parseUnitModelWithScaleExceptRange`, which in turn is only ever called from the `range.test.ts` test case.

**Comment by domoritz** [comment]
Ha, interesting. Why do the docs say that we ignore custom ranges? I feel we should not. I'm making this as a documentation issue.

**Comment by marcprux** [comment]
I'm guessing that the issue with positional channels is that there isn't any way to express "width" and "height" as components of the range, which makes it impossible to have the range apply to the positional span. Personally, I'd like the ability to specify the range as a percent of the span (e.g., 10% - 99% of the width or height), but that's more of a feature request.

**Comment by domoritz** [comment]
We are working on a proposal to bring something like signals and expressions to Vega-Lite, which should allow you to do what you want. 

We have experimental support for signals already (not exposed in the schema but it works) but it might go away in the future.

**Comment by marcprux** [comment]
Fun! Are there any examples of how it might work?

**Comment by domoritz** [comment]
I just put this together. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWgArKW5+egAwiWoYgDMlSBJACJ1AJwAjM1JAKJ1mT15LQUAYnWlTSNJAOJ1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBdbqwXCyUGzKNLJkaKAAHq8gAGY0cILKBRQSkwAE8cHACmx1I9ZFEQMcQZ8fn8Aeg0sCwRD0ABHBhIWQ6QI6UjBaBRLGgdT4sgUkAmMiwwQFOLwGhkLCGABUhgADJQOgpeQd4dlRdkgA)

**Comment by marcprux** [comment]
That's fantastic! Looking forward to it…

**Comment by domoritz** [comment]
Again, experimental and might go away but our current plan is to have something very similar but using slightly different terminology.

**Comment by kanitw** [comment]
Re: this issue, the docs for x/y range is simply outdated.

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6523.
