### ISSUE TITLE
Tooltips don't work in Firefox

### ISSUE THREAD

**Issue by carderne** [vega/vega-lite#6521]
Previously reported at [altair-viz](https://github.com/altair-viz/altair/issues/2164).

The [altair-viz scatter plot tooltip example](https://altair-viz.github.io/gallery/scatter_tooltips.html) doesn't seem to work properly in Firefox (but fine in Chrome). No matter how hard I hover no tooltips show up.

OS: Ubuntu 20.04
Browser: Firefox 76.0.1 with all addons disabled

**Comment by domoritz** [comment]
Works fine for me in 77.0b7 on MacOS. Please try the beta version and see what happens. 

Do you get any errors on the js console? Do you have a scaled screen? Do you zoom in in FF?

**Comment by carderne** [comment]
Thanks for the suggestions. Turns out it's because of Firefox blocking canvas data access. If I allow access then the tooltips work.

Specific console message: `Blocked https://altair-viz.github.io/gallery/scatter_tooltips.html from extracting canvas data because no user input was detected.`

Interestingly, all of [these examples on the vega-lite docs](https://vega.github.io/vega-lite/docs/tooltip.html) worked straight away. Not sure why FF blocked on altair's page, nor do I understand why it says 'no user input was detected.'

**Comment by domoritz** [comment]
We use SVG on the website. I would recommend switching to the SVG renderer.
