### ISSUE TITLE
Support expression as references

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6527]
Based on discussion for https://github.com/vega/vega-lite/issues/6189, we'd need to change SignalRef to Expr (`{expr: string}`) 

- [ ] mark properties
- [ ] mark config

- [ ] axis properties
- [ ] conditional axis properties
- [ ] axis config

- [ ] legend properties
- [ ] legend config 

- [ ] scale properties
- [ ] scale config 

- [ ] header properties 
- [ ] header config 

- [ ] Predicate 

- [ ] projection

**Comment by domoritz** [comment]
Done in master
