### ISSUE TITLE
domainMid of diverging color scheme ignored when it falls outside data range

### ISSUE THREAD

**Issue by sacundim** [vega/vega-lite#6544]
I have a heatmap where I use a diverging color scheme with `{"domainMid": 0}` with the intent that negative values will stand out from positive ones.  However, today I ran into an edge case where, because all of the values are positive, the libraries apparently choose to just ignore my `domainMid` setting:

```
WARN Scale domainMid exceeds domain min or max. 0
```

Adding `"domain": [0, 30]` works around the issue, but it seems to me like a case where the libraries are counterintuitively ignoring a reasonable chart spec with sensible semantics. It also requires me to bind my chart spec more tightly to the actual data—I must compute the domain from the actual data, which means that having the data at hand becomes a prerequisite for generating the spec. In Altair I implemented my workaround this way, which might be a candidate solution to adopt in the library itself:

```python
heatmap = base.mark_rect().encode(
    color=alt.Color('value:Q', title=None, legend=None,
                    scale=alt.Scale(scheme="redgrey", domainMid=0,
                                    # WORKAROUND: Set the domain manually to forcibly
                                    # include the domainMid or else we run into
                                    # https://github.com/vega/vega-lite/issues/6544
                                    domain=[min(0, df['value'].min()),
                                            max(0, df['value'].max())]))
)
```

Here's the example that ran into the issue:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIEMAPZAZ020gBt8AjAU0oDEEAXAZWQC87yBGAFgA0UFshaU6zeOy48sAgL6DwuSAAs6+ACZ0ATuWBVaDKTO58hIsRNMdz8-kpV4JqOvC0Gj9JqztywAWFIUXFJP1kLJ1wrMK98SjR4chh3Fj1IYMQI+zAAJgAGYNhERBI6Fj4AVgUVaKgtfBZ8L3h8AFsAyEbmgFo8qq1eADZofgB2fgBOAoBmKaqq6AGtKZopul58ATp1-CrIeshEfGgKg2coXVgAdwuYvBYATwAHLvhYduQ2ykzLvBQDE8WEgADd8LpkLQJH8HlASLBdJUsABtSAAYQQKF07W0sDIwQACtcaNC6ASoABZACuenSZAAuso4SFrAF4NTKJRLrUIEcSG9oPdVNQnhlUf9sJK8LjdABrFK6OjQSrMuFQdxwLTfdBYHDqvBwSiI4UGx6vLoAR2p+GkYiayFBPDVZqggMowKg4MotNhrqgrncno5XJdZsgJGgCQChi0n3w30pyE9RXh0A0nUVdC0qCVT0OYYNrLiWBD3Nd9SLLFgsEoohe5BR0oehmebxS6XaL0RCUybuQQJSPWp7QA+j0eJWza2LSlrbbQg6nX3jgOPSlvb7eWamc28IRTeG211Edqfn7XQRiGQ9cdEbjkVAAKSeKdF92e7pNEfjprOveqKInQAKrwGIQ5-heR5sikAAiAC3+BgDolBgJ0ZAAW+DyQPmeoAea7Ygqe3y9oW6pXqQXjZDiTQpE+ABCBb4f2g4gsOY4TlBRYIkiQ7kmcHg6lx5FAXQoHgSC7SsGowksqEMKlpy5ZmtucKqbgWH6iysoKrex4dnQhCqm6OQBFMWF4JqsBnrqUqXkaJp4f6UBwIJogIIel6bl0NxqGI-7OY85KPlpgWQI5YBNoFLarqxXoJL6wR1gEBQWf6hgfhuCXOlAqDpNU6nOQyzF8sxaUxGC2UpDQ1DQAqmFkRV6RGV4+kgvOdrNKIy5ZGun7eUxl7VrW9aNsxM6ESIdBdj2vy9XFX4sD+nHlbgE1WjanVLjlsXriCA2FQ8u6XgeTn+iEs5EboZ6kcxFE3hQ1EPnRr6NdhmVsd+HGQW9TXICBYGPotAXnfJXQIUhKFoeSkANQBOGeSJl1QMR56-aoRCUbeT20SCDGDedH0NF9v75ejeA8UDOiRkGQnk1YAMSVAUnSDJ9PFgpYBlphzaHepx2qBoaBqI+4xFJckA3MmLAyVgVQABxVHUaqQAAJJGGYtCCIssC8JAYAA9AbTqoPgAB0qBiGo1I0GbyCwAbGvTfgxt0KbvSJOkxv8Gb8tm7wZsAFYIskKs9Pg5QsA9oWLfg-SDCMYyTDM8yLMsgxrBsWw7HsBwSnCoUVTQSkVN8pNdIUhS9AUVTxwAKgUBQYI3zcFLJxNLd9+UgpXBTV7XAgN03LeN+3lWQmSKSYkgyA0XGBLNpVPoBLwkqaYvxdcqX8Dlykvf9-XI-D23b2LctkE9wUVcFPw-QFEPret2P4ITzVXTErApJvwvRYDfIa9kULqoTeEhRA704pfa+tcBgPyPmPdiu9IF9xrtXXgsDj7PwhFCN+KQP5fwkD-cif98gAMlEAvAIDt6IKgPvFBMCj5P1PggiBNCr7IIHmghho9T4v2wZzSAeCySEJZMQ1ealAEbxLmA6hkBaHQKqOgxhi9mEX1YVA3ovA8iKO4YvXhk8QSCO-pg5efBSEF0kVvaRLDZFsIPvQ4+SiiwqO7mo9hGjZjaJProrB+ioCGIIcY30WBZhmJbBY0BZdrFyMPg4nRTiSZRNsSg3gCiuFeN-j4nBBiSRCMCQEPIoSYjkKgJQqxqibHqPsY-OJ5FnEVySQPeWnjMGv34f4mGPCqpYHloUta4SqGJMqak2J6TakJPKdE3gUxmmdNae-HJRjOkmOCQUXpEBimQFKZEiZDSYnVNGSyOpe9dmFBmd4uZuCFkBKWUEwISs1KXGKqVBQQA)

```json
{
  "config": {
    "axis": {"labelFontSize": 14, "titleFontSize": 14},
    "header": {"labelFontSize": 14, "titleFontSize": 14},
    "legend": {"labelFontSize": 14, "titleFontSize": 14},
    "title": {"align": "center", "fontSize": 20, "offset": 15}
  },
  "data": {"name": "data-25d16c474903955c25d9b9e1a14eb9a5"},
  "facet": {
    "row": {
      "type": "nominal",
      "field": "variable",
      "sort": ["Confirmados", "Probables", "Muertes"],
      "title": null
    }
  },
  "spec": {
    "layer": [
      {
        "mark": "rect",
        "encoding": {
          "color": {
            "type": "quantitative",
            "field": "value",
            "legend": null,
            "scale": {"domainMid": 0, "scheme": "redgrey"},
            "title": null
          },
          "tooltip": [
            {"type": "temporal", "field": "datum_date"},
            {"type": "quantitative", "field": "value"}
          ],
          "x": {
            "type": "ordinal",
            "axis": {"format": "%d"},
            "field": "datum_date",
            "timeUnit": "date",
            "title": "Día del mes"
          },
          "y": {
            "type": "ordinal",
            "axis": {"format": "%B"},
            "field": "datum_date",
            "sort": "descending",
            "timeUnit": "month",
            "title": null
          }
        }
      },
      {
        "mark": {"type": "text", "fontSize": 9},
        "encoding": {
          "color": {
            "condition": {
              "value": "white",
              "test": {
                "or": [
                  {"field": "value", "lte": 0},
                  {"field": "value", "gte": 15}
                ]
              }
            },
            "value": "black"
          },
          "text": {"type": "quantitative", "field": "value"},
          "tooltip": [
            {"type": "temporal", "field": "datum_date"},
            {"type": "quantitative", "field": "value"}
          ],
          "x": {
            "type": "ordinal",
            "axis": {"format": "%d"},
            "field": "datum_date",
            "timeUnit": "date",
            "title": "Día del mes"
          },
          "y": {
            "type": "ordinal",
            "axis": {"format": "%B"},
            "field": "datum_date",
            "sort": "descending",
            "timeUnit": "month",
            "title": null
          }
        }
      }
    ],
    "height": 70,
    "width": 585
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "datasets": {
    "data-25d16c474903955c25d9b9e1a14eb9a5": [
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-14T00:00:00",
        "variable": "Confirmados",
        "value": 1
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-04-20T00:00:00",
        "variable": "Probables",
        "value": 1
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-01T00:00:00",
        "variable": "Probables",
        "value": 2
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-11T00:00:00",
        "variable": "Probables",
        "value": 1
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-12T00:00:00",
        "variable": "Probables",
        "value": 1
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-13T00:00:00",
        "variable": "Probables",
        "value": 3
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-15T00:00:00",
        "variable": "Probables",
        "value": 2
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-18T00:00:00",
        "variable": "Probables",
        "value": 8
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-19T00:00:00",
        "variable": "Probables",
        "value": 30
      },
      {
        "bulletin_date": "2020-05-25T00:00:00",
        "datum_date": "2020-05-20T00:00:00",
        "variable": "Probables",
        "value": 15
      }
    ]
  }
}```

**Comment by domoritz** [comment]
You could use `domain: {unionWidth: [0]}`

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlAQwB5wM4tAGzQCMBTfAMWgBcBlOALxJQEYAWAGhCrivxMqi0GTZGwC+nABYk0AExIAnPCEKkK1OoxYcuPPgKFbRrCSpIISUWctVkDmkW07de-DcO2mXfZWnyIoFHBLKkUQThh3IwAmAAZOCBgYbBIqFgBWMVNZNCo0ZSg0AFsREBy8gFpo9NlmADYwVgB2VgBOWIBmVvT0sGrZVqJWkmY0NhIhtHSQUxg0MFTlBQgAd2UqAE8AB1KoCCK4QvxwkHgya2QQADc0BThiH05sCAU05ABtEABhaHgFIrkEFwnAACssiA8SMCQABZACuilCuAAus49CIoHD8Pgsk8dmAbGgNmEPqAAQoANZBBQkMBpTiWSCyQ5IVDgCD4F7rbalACOcLQgh4uTgVyYETg5yCN3wCJOfAsVhQmOxTzAfhEoFk+zQhxhcAu8RA2DA0hK1JIsgQNI2J21AMOyjhUDg0AA6jxJCh3rFkbjdK5lVicc4IBzuFtvaBNjsgqEilsXn4Tmd8Bcyrk4UUAPrlJgSaM8oL8wUuEVilOStPSvxysSokAYbmxy4vZlHE6YHDKSL-XJBACk1lmVfT5Szudy4t0JQAqi63hnQidvKUACIAW7QAAJ5PhtyVcKZbWyY6U24dk5wu7g2b2AYuBwAhGYSqWXcc5vMnZ6vILyE1LHbJA0TnBcgiKagvTRQNkBVHFcTJW4qVPItLlCDB6VOKIRFaUxGQgYDlEgTklDZSArB4V1AjZGU5UuFZJB4ackTeUAuVJU5RxrWVp3wZdkFiAsuPfa5a2nBABOYTI-VMOjSiIQgwCpLwSEw5s+QFIU8m4Cs32rS55NfLgw34uBI04s84xIBMk2OfSx0zL8p1fQsWxAEttPLadU3TIz604JtUPci8O2vLBb1Ae9+0uIdjN8-8nMnZdQJIeceESlKAx8S5Nx3PcDyhYyTzc88FHbK8QBvHsXgfQcXxHUTP2S6df0XACFkoqAQJnNLwMuSDBGg7KMWDLIApAaREEkN4miNFYDSoL1kHSAAOTJOAAEhNM18kuGaqC2bBkAAehOsUEDQAA6BBPThIgrtdE6dpstBzvMNAKn8UJztYK7Vqu5groAK2eQJOHKNAUioSKl0+-p6kaFp2i6Ho+hqQZhlGcZJmmTiiGDVJDhaoI4jiCpYnSKp0gAFViWJBIZ+m7SS79LjJ2IKaptg6aZvmThuO5ISCH5YDgPttWhIzRGEgnsSJqASfZ2Jycp6necZxmWaoCc2ZADmKdYKpYg1+mtc4QX7kU0owQgCFral8SWFlwnuEVvWDbV6pTf5iHWZc5XVap2JmB982xKF62glt+2+Ed3iUGiF35bdpX9ZVzmvdps2c9ibXdYD9Og4qZhQ9z8PLeFy4Y8heP6OYZO+FTj2M659Xy+Zv2decgSi8z7nojDzuI6tnKQBrh2BadmX2FAOWm+Jlvi+9ju867gve897mOiHteR6r8fwVrqeE+QDpG4VtOt-bvnw+apf+5L7Pb+Hyuo+ro-J4t6ek9nkB58vg-NuK8X573voXa+zBVq7ynpHMeE844n3oqtC+zcIGtyzjA9ePdSiQNaFg-e79D522Pt-U+HQhJ-wAWgzeGCqYgM1sPcBtDl4m1XrA0eNtP6ILIfXGSWQgA)

What do you expect the behavior of Vega-Lite to be? If the middle is outside the domain, I think it's not totally unreasonable to drop the mid value.

**Comment by sacundim** [comment]
If I use a diverging color scheme and set the domainMid to zero, I expect that the lower half of the color scheme will used with and only with negative values.  If there aren't any negative values in the data, then that part of the range would not be used.

Thanks for the alternative workaround, that's indeed better than mine!

**Comment by domoritz** [comment]
I looked a bit more into it. Vega-Lite actually just passes the domain mid to Vega and the warning you see comes from Vega. I think that's where we should fix it. 

I'm closing the issue here. Can you file an issue at https://github.com/vega/vega/issues/new/choose with a small example and the description of the issue so it can be addressed at the Vega level?

**Comment by sacundim** [comment]
I'm happy to help, but I could use some guidance on whether the pared down example:

1. Can be Vega-Lite or its compiled-down counterpart;
2. Needs to be hand-written Vega (which I don't know if I'd be able to produce).

Here are some pared-down Vega-Lite versions:

* [Just domainSize = 0](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgA46ARjoArWNwB2kADTgoAE3R5MOYJA3pUybAaOiATAFZ9igGzxpAdmkBOAAwAzD6OjvBO+j7sPsiK6IrSyFHojpAAvroQkBgATgDWNpDZyPB4OnqQyBrw3PqMGtQ2oBCZ1WLc2Y16zVB4AJ6E1jiQAI6s6Bp4zEaMVGXdmQBmjMhi+gUU6GKs1hnzkAibg2BN85n63Bh1ALKMazh+2mBde-xoR4XI+tRFvZDPEKlnulnpA8NxuGJJoQbABtf7HUH9d54NCEdqbHRQJYrO62PCsVAAfUMKLSu26Zj6AwKo3Gk2Mk1mj0g2NW6022zSzwAuuSoAAPTqnRHUobtWoWMRzPbofmMWCNFntDClIYAUjWwOFrNxkBJBOJRh28NBjCsAFUNMwCiTrEC+ZBfqYTVT3uK6hi+Ytlmyhvqibbpd1ILL5YqFsqjAU1QAhMkus3IS3WoaoTQsP7dQEA3Z6uywZB4BXO4MkhzONwebz+IIhMLOSLRWLxRI+ZKw+EnYX+w2kob2PwDkR+aQiAcAFT8fiwU5nfiDew2WyOinhWvmXb2PcD-cHfmHjmHikn09nU4XwaXnJw9jXXuO8LORgNO6gA6HfkPinsJ7nc4vzSQFeK53p2j54i+RoFO++6fiIigBL+Z7zvemTATYASgacm6ls+AZQbuH5fo4SGnih4FARyRy3qc64UhR24EW+e4HvBcikf+qFQOhOByFhG4MXhvbvDBrGKD4HHnlxlHLhhfj8fRpxPvi+F9sxRFjn4knkUp3FUTYiiOGuPJ6ICqRAA)
* [Adding domainWith = [0]](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgA46ARjoArWNwB2kADTgoAE3R5MOYJA3pUybAaOiATAFZ9igGzxpAdmkBOAAwAzD6OjvBO+j7sPsiK6IrSyFHojpAAvroQkBgATgDWNpDZyPB4OnqQyBrw3PqMGtQ2oBCZ1WLc2Y16zVB4AJ6E1jiQAI6s6Bp4zEaMVGXdmQBmjMhi+gUU6GKs1hnzkAibg2BN85n63Bh1jZCsGjwaAOrMiDYA2n4Auulde+eXGgBZRhrHB+bRgH7dfZINBHQrIfTUIq9SCQsCpH7fKF4bjcMSTQhvNFmPoDAp4NCEdqbHRQJYrEG2PCsVAAfUMFLSu26JP6cNG40mxkms3BkHpq3Wm22aR+H25UAAHp1TpBSXD2rULGI5nt0IrGLBrgt2hhSkMAKRrLF7CWMyAclnsow7NFqxhWACqd3NTOsmIVkBRpjd6oKmrqNIVi2WkqGjrZHNdqv1huNpqMBQtACEuaGPchvcwCqhNCxUd0MRAbQ67LBkHgjSGoRyHM43B5vP4giEws5ItFYvFEj5kkTTidVQnnZyhvY-PORH5pCJ5wAVPx+LCb7d+XWqjZbI6KNE2nlos5GJ1Jgrzxd+RxLxQbrc7zf7vaHmU4eyn6PHC8mWvF1bwXPwl0fRR7BfXddw-KEv2PP9iUA2tmUTEC5zAiCREUAIYLfPd-0yRCbACZCJ1Q6cbyw+9IMcAjXyI1DSJ-Cj5knX4rww2coDvcCH1wuRGLg4ioFYsA5HY89TkvdCZzhficMUHwRPfMTIAkgI-Gk5pOJbbiFNAujVz8NTmNk8TpWPRxTzlPQMVSIA)

**Comment by domoritz** [comment]
Ideally, it would be a Vega specification stripped down from a spec generated by Vega-Lite but a Vega-Lite spec is fine if you don't have much experience with vega yet. We really appreciate you writing up the issue so anything that you can do in a few minutes will help.
