### ISSUE TITLE
Improving / Writing Missing Docs

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#656]
## Important
- [x] How to use Vega-Lite
  - [x] Embed in Applications (1) inline data (2) url data (3) runtime data
  - [x] Vega-editor
  - [x] Polestar, Voyager 
- [x] area mark
- [x] `order`, `path`
- [x] scale
- [x] bin
- [x] sort
- [x] axis
- [x] legend
- [x] mark config
- [x] config.unit & Adjust Size 
- [x] facet
## Lower Priority
- [x] clean up README.md 
- [x] JSON Schema
- [ ] Twitter and Facebook metadata
# Post 1.0
- [ ] orientation
- [ ] when is stacking enabled
- [ ] aggregation intro
- [ ] Decide if we should write about custom domain for ordinal scale.
- [x] Piecewise Scale
- [ ] Quantize / Threshold Scale
- [x] useRawDomain

**Comment by kanitw** [comment]
- [ ] Add detail about what file get produced in release in contribute.md or somewhere else

**Comment by kanitw** [comment]
- [ ] Maybe link from data.html to the tutorial?

**Comment by kanitw** [comment]
- [ ] list all default properties

**Comment by kanitw** [comment]
- [ ] data.md  -> mention what happens when the input data is array of primitive, not object.  (Data got injected into `data` property)

**Comment by kanitw** [comment]
- [ ] need to make note parts more distinguishing

**Comment by saulshanabrook** [comment]
The docs say that "Alternatively, if the data property is not specified, the data source can be bound at runtime." However, the link leads to a non-existent ID on that page: https://vega.github.io/vega-lite/docs/data.html#runtime

**Comment by kanitw** [comment]
Consolidated as a part of #1690
