### ISSUE TITLE
No visualization in vega editor, although there are no error messages

### ISSUE THREAD

**Issue by danielp3011** [vega/vega-lite#6563]
Hi there,

I recently had multiple problems with the vega editor not showing the visualization, although it didn't give errors. 
I have a visualization running on a website, this visualization works, however it is not possible to test it in the vega editor anymore, because this one won't react.

Another problem I found right now, is with this part of the documentation: https://vega.github.io/vega-lite/docs/bind.html
When I try to replicate the first visualization with the code from shown in the documentation, I don't get errors, however I also don't get any visualization.
I have not tried this code shown in the documentation on my website yet.

![image](https://user-images.githubusercontent.com/40362058/83352034-0761a000-a349-11ea-9dbf-e7c7aded3f33.png)

**Comment by danielp3011** [comment]
seems to be a browser based issue. For me it does not work in the new Edge (Canary version) and not in Brave browser, however it works in Chrome

**Comment by domoritz** [comment]
Which OS? Do you see any errors in the browser console? Do you also see the issue if you use an incognito window?

**Comment by domoritz** [comment]
Closing as we need more details to reproduce the issue. Please file an issue against the Vega editor repo if the issue only happens in the editor.
