### ISSUE TITLE
Binned color should interpolate ramp color scheme

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6576]
If you [provide a custom ramp scheme as a color array](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqQgTSAbE1Mzc+gAssFqAPrh6o8A4khRcutbcLv7skOphoJzO-Ss6ku01m5X0UCgM3MwO+Sk223QewOdGBJyUTCcaEw6gYcCUJhCEy65i8glMf3QMCgZSU6j8ZHpAG0QExBCS8uo4HMALoNUUNIA), I think Vega-Lite (or is this a problem with Vega's `bin-ordinal` scale type?) should interpolate that into a continuous scheme, _then_ discretize it. My expectation would be a quantized scale respective of the bins, based on a continuous interpolation from "blue" to "red"

Upon further investigation, I think this is a trade-off due to Vega's [bin-ordinal]( Input domain values are discretized to the appropriate bin, which is then treated as a standard ordinal scale input.) type. Is there a straightforward way to accomplish this in Vega?

**Comment by domoritz** [comment]
It actually works but it's not supported by the schema: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqQgTSAbE1Mzc+gAssFqAPrh6o8A4khRcutbcLv7skOphoJzO-Ss6ku01m5X0UCgM3MwO+Sk223QewOdGBJyUTCcaEw6gYcCUJhCEy65i8glMf3QMCgZTJsEQ9IA2iAmIISXl1HA5gBdBoihpAA).

**Comment by domoritz** [comment]
Done in #6577

**Comment by domoritz** [comment]
Moved to Vega https://github.com/vega/vega/issues/2704
