### ISSUE TITLE
Add domainDash property to config

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6578]
It would be great to support the properties for the axis [domain](https://vega.github.io/vega-lite/docs/axis.html#domain) as are allowed on the grid. In this case, an analog for `gridDash`

**Comment by domoritz** [comment]
Already works. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWgArKW5+egAwiWoYgDMlSBJACJ1AJwAjM1JAKJ1mT15LQUAYnWlTSNJAOJ1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBTpQF0pwslBsyjSyZGigAB5vIABmNHCCygKKCUmAAnjg4AU2OonrIoiBjqCvr9-oD0GkQeDIegAI4MJCyHSBHSkBHHB6yX6vcItd40CBfZRsZDPVpICAweLpBTpI7ZbJAA). The docs are missing. Can you fix it?

**Comment by willium** [comment]
yep
