### ISSUE TITLE
Conditional grid and tick dash offset not applied correctly

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6591]
The following creates dashed grid lines as expected (here with a zero dash offset):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
 
  "data": {
    "values": [
      {"x": 1,  "y": 1},
      {"x": 10, "y": 10}
    ]
  },
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative"
    },
    "y": {
      "field": "y",
      "type": "quantitative",
      "axis": {
        "gridDash": [8,8],
        "gridDashOffset": 0        
      }
    }
  },
  "mark": {"type": "point"}
}
```

<img width="261" alt="dashValue" src="https://user-images.githubusercontent.com/1846999/83943445-18e8f300-a7f4-11ea-8710-11fa7f4fa4fd.png">

However, if the offset is made conditional, the dashes are not rendered correctly (here with 0 offset for both conditional results for comparison):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
 
  "data": {
    "values": [
      {"x": 1,  "y": 1},
      {"x": 10, "y": 10}
    ]
  },
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative"
    },
    "y": {
      "field": "y",
      "type": "quantitative",
      "axis": {
        "gridDash": [8,8],
        "gridDashOffset": {
          "condition": {"test": "datum.value < 5", "value": 0},
          "value": 0
        }
      }
    }
  },
  "mark": {"type": "point"}
}
```

<img width="260" alt="dashConditional" src="https://user-images.githubusercontent.com/1846999/83943448-21412e00-a7f4-11ea-8d09-c8fb7af010c0.png">

The same problem applies to conditional tick dash offsets.

Looking at the compiled Vega it would appear the problem is caused because the Vega-Lite is generating a `strokeDash` rather than `strokeDashOffset` in the update encoding.

**Comment by domoritz** [comment]
Good catch. We didn't redirect the offset properties correctly. Fixed in https://github.com/vega/vega-lite/pull/6599.
