### ISSUE TITLE
Remove legend from config

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6602]
One can set the `legend` property on an encoding to `null` to remove it, but it would nice if it were possible to remove all legends from the config. My use case: we're creating a minimap and sparkline where the legends are either irrelevant or will be rendered outside of Vega.

**Comment by kanitw** [comment]
Axis and legend configs do have `disable` property.  However, I just realized we forgot to include them in the docs. The docs will be included in https://github.com/vega/vega-lite/pull/6607.
