### ISSUE TITLE
Layered Chart: Binning a calculated field causes "Infinite extent for field"

### ISSUE THREAD

**Issue by shabbirahussain** [vega/vega-lite#6606]
# Steps to reproduce:

1. Add a transformed field with transform_calculate (a simple `new_x = 'datum.x'` will do). 
2. Create a layered chart with one layer using the newly transformed field.
3. Thing should look good so far.
4. Now use bins on the newly transformed field. This will cause "Infinite extent for field".

Note: Using bins on original `x` field works just fine.

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "layer": [
    {
      "mark": "rect",
      "encoding": {
        "color": {"type": "quantitative", "aggregate": "count"},
        "x": {"type": "quantitative", "bin": true, "field": "x"},
        "y": {"type": "quantitative", "field": "Horsepower"}
      },
      "transform": [{"calculate": "datum.Displacement", "as": "x"}]
    },
    {
      "mark": "circle",
      "encoding": {
        "x": {"type": "quantitative", "field": "Displacement"},
        "y": {"type": "quantitative", "field": "Horsepower"}
      }
    }
  ],
  "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json"
}
```

https://vega.github.io/editor/#/gist/cfdf00ecbbed9187a32f5488ffe356fd/spec.json

**Comment by domoritz** [comment]
Note that this is only a warning and can be ignored. I wonder what exactly is causing it, though. 

Also related https://github.com/vega/vega-lite/issues/6266

**Comment by shabbirahussain** [comment]
I think I know the issue. This is being caused during vega-light -> vega schema translation. 

The transformation order being generated have an 'extent' and 'bin' transformations (which uses the newly calculated field) before the 'calculate' transformation which actually generates that field.

Current Vega schema being generated [Not-Working]: https://vega.github.io/editor/#/gist/7c5350f9a6da919ceee71ecb8eb59eaf/spec.json

Expected [Working]: https://vega.github.io/editor/#/gist/392d8d0d20e8bb738664812ac508f7f7/spec.json

**Comment by domoritz** [comment]
Right. The bin is supposed to come after the calculate.

https://github.com/vega/vega-lite/blob/master/src/compile/data/parse.ts#L261

But this is the dataflow we are getting here.  

<img width="353" alt="Screen Shot 2020-06-15 at 16 08 46" src="https://user-images.githubusercontent.com/589034/84714435-7f6fbe80-af22-11ea-865a-d436ed349dbe.png">

**Comment by domoritz** [comment]
I think this could be related to https://github.com/vega/vega-lite/issues/2270.

**Comment by shabbirahussain** [comment]
Seems like. 

Considering this only happens for layer charts, which means [L334](https://github.com/vega/vega-lite/blob/67a9e712c1b8650850e6d2aa67ea19a647e9ddd2/src/compile/data/parse.ts#L334) should be below [L339](https://github.com/vega/vega-lite/blob/67a9e712c1b8650850e6d2aa67ea19a647e9ddd2/src/compile/data/parse.ts#L339).

Not sure how that would interact with #2270.

**Comment by domoritz** [comment]
Yep, I'm trying to remember what we meant when we wrote https://github.com/vega/vega-lite/blob/67a9e712c1b8650850e6d2aa67ea19a647e9ddd2/src/compile/data/parse.ts#L329 (came in in https://github.com/vega/vega-lite/commit/66754c84a53aa1d7ea7d7378edf35394bd2823d8#diff-6ff9ac68ad5af5ba27bd1c51a6d58548).

**Comment by domoritz** [comment]
Part of https://github.com/vega/vega-lite/issues/2270

**Comment by shabbirahussain** [comment]
Thank you for the quick fix!

**Comment by domoritz** [comment]
As a workaround, you can add a bin transform manually.
