### ISSUE TITLE
Should we add `order` property to `encDef.sort`?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#663]
Currently Vega-lite’s `encDef.sort` looks exactly like vega Scale's `DataRef.sort`, which only contains `aggr` and `op` properties while the `order` field is deprecated as same mechanism can be achieved by using `reverse` property of the scale.  

However, in vega-lite’s encoding definition, `sort` is another top-level object, not a part of `scale`.  If we do not have `order` property.  Specifying descending sort would require specifying both `sort` and `scale` like the following Barley example, which is kind of miss the point for extracting `sort` from `scale`. 

```js
{
      data: {url: 'data/barley.json'},
      marktype: 'point',
      encoding: {
        x: {type: 'Q',name: 'yield'},
        y: {
          name: 'variety',
          type: 'O',
          sort: {field: 'yield', op: 'median'},
          __scale: {reverse: true}__
        },
        row: {
          type: 'O',
          name: 'site',
          sort: {field: 'yield', op: 'median'},
          __scale: {reverse: true}__
        },
        color: {type: 'N',name: 'year'}
      }
    }
``` 

By having `order` property, the spec can be a bit nicer:

```
{
  data: {url: 'data/barley.json'},
  marktype: 'point',
  encoding: {
    x: {type: 'Q',name: 'yield'},
    y: {
      name: 'variety',
      type: 'O',
      sort: {field: 'yield', op: ‘median’, __order:’desc'__}
    },
    row: {
      type: 'O',
      name: 'site',
      sort: {field: 'yield', op: 'median', __order:’desc’__},
    },
    color: {type: 'N',name: 'year'}
  }
}
```

**Comment by domoritz** [comment]
What if you don't sort by an aggregated value? I think an ordered scale is different from sorted data.

**Comment by kanitw** [comment]
You have to sort by aggregated value because one ordinal value can have multiple quantitative values in other fields.  Thus, you __always__ have to sort by aggregate value for guaranteed behavior.  Or at least we need to define default behavior to be something like min or max.  

(For a dataset that have 1:1 mapping between ordinal and quantitative value, `min`, `max`, `mean` all lead to the same result.)

**Comment by domoritz** [comment]
How would you sort by the name of the ordinal value itself?

**Comment by kanitw** [comment]
Great point.    

In vega, `sort` is either undefined, boolean or object.  
- `undefined` or `false` - sort by order of first occurrence of the value
- `true` - sort by natural order  (descending sort is done by specifying `reverse:true` in the scale. 
- `{field:…, op:…}` is for when you want to sort by other field and boolean is sorting by the field itself.  

I propose that for Vega-Lite we make it either String or Object  
- `ascending` (default) — this is equivalent to `{sort:true (, reverse: false)}` in vega. 
- `descending` — this is equivalent to `{sort:true , reverse: true}` in vega. 
- `none` — this is equivalent to `{sort:false}` in vega. 
- `{field:…, op:…, order:...}`  where `order` will modify the scale’s `reverse` property.  


So the schema will look like this:

```
var sortMixin = {
  type: 'object',
  properties: {
    sort: {
      default: 'ascending',
      supportedTypes: toMap([N, O]),
      oneOf: [
        {
          type: 'string',
          enum: ['ascending', 'descending', 'none']
        },
        { // sort by aggregation of another field
          type: 'object',
          required: ['field', 'op'],
          properties: {
            field: {
              type: 'string',
              description: 'The field name to aggregate over.'
            },
            op: {
              type: 'string',
              enum: VALID_AGG_OPS,
              description: 'The field name to aggregate over.'
            },
            order: {
              type: 'string',
              enum: ['ascending', 'descending']
            }
          }
        }
      ]

    }
  }
};
```
One note for this proposal — Should `sort`’s default be `ascending`?  I think it makes sense from user’s perspective, but this is slightly different from Vega.  If we prefer consistency, we remove `none` and make the default means no sort.

**Comment by domoritz** [comment]
I agree with the proposal and think that the default should be not sorted.

**Comment by kanitw** [comment]
Another question, right now this is only for ordinal scales. 

For quantitative and temporal scale, although we cannot specify sort property in Vega.  
`reverse` is still specifiable.  

However, since we introduce sort here, should we make `sort` __Object | String__ for nominal/ordinal and __String__ for quantitative|time.  
So that we do not need to introduce `encDef.scale.reverse`, which could be confusing as there will be two ways to specify descending order.

**Comment by kanitw** [comment]
I just went ahead and remove `encDef.scale.reverse` and only support `encDef.sort`.

I’m closing this and please look at #671 for further discussion.

**Comment by kanitw** [comment]
I wonder again if `sort` should be unsorted by default.   
This will make legends and axes awful by default.  

Consider `stacked_bar`for example.
<img width="434" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/10622885/088f988c-773f-11e5-9343-80ea84f88750.png">

I think we should make `undefined` = `’ascending’` and add another property name for explicitly specifying unsorted.   

Maybe `’unsorted’` or `’none’` (like originally proposed?)
