### ISSUE TITLE
Default encoding types

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6636]
Encoding types are currently a required property but I think we can often infer a reasonable type.

e.g.

- [ ] when the aggregate is count, use quantitative (can't think of a reason not to do that)
- [ ] when there is an aggregate, use quantitative
- [ ] binned could be quantitative by default (although there are exceptions)

**Comment by davidanthoff** [comment]
It would be especially cool if this worked for fields that come out of transforms. We are currently augmenting types for direct fields in VegaLite.jl, but we give up for computed fields.

**Comment by kanitw** [comment]
- [ ] when sort is an array for custom sort order, use `"type": ordinal`

**Comment by jwoLondon** [comment]
And for geo data, longitude and latitude position encoding will always require quantitative data. 

Theta and radius for polar coordinates would sensibly default to quant, although the option for ordinal theta should be allowable.

**Comment by kanitw** [comment]
> And for geo data, longitude and latitude position encoding will always require quantitative data.

Yep.

> Theta and radius for polar coordinates would sensibly default to quant, although the option for ordinal theta should be allowable.

For this one, I think the default should be consistent with x and y. 
Given that Vega-Lite never knows the data schema and all kinds of fields can serve as nominal, we'll use "nominal" as the default because it will always works (in the sense that at least the framework will render something instead of throwing error).  Users can always explicitly specify quantitative.

**Comment by kanitw** [comment]
While better invalid value handling (#2544) may help resolve this, another benefit to set nominal as the default in general is that we can make specs with aggregate quite lean by omitting the group by type for the most cases like:

```js 
{
  "mark": "bar",
  "encoding": {
    "y": {"field": "age"}, // if N is default in general, then we can omit here too
    "x": {"aggregate": "sum", "field": "people"} // aggregate is Q by default
  }
}
```

**Comment by kanitw** [comment]
Default type will be added in https://github.com/vega/vega-lite/pull/6638.  

For tracking type for derived fields, we should do that as part of https://github.com/vega/vega-lite/issues/2862.
