### ISSUE TITLE
Change the project name from vega-lite to something else

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6656]
vega-lite is a project distinct enough from vega to deserve its own unique name. It feels like its current name was just defaulted in during the early stages of the project and then stuck around through inertia.

The problem with the "vega-lite" name is that it suggests the project is somehow a more simplistic form of "vega", and that if you want to use something serious and powerful, you should choose vega itself over some "-lite" version. While it is true that there are many visualizations that can be expressed in vega that are difficult to express in vega-lite (although often not impossible: recall the heroic effort to implement pie charts in vega-lite before the arc mark was surfaced), "power" is not a single-dimensional quantity in software, and one package is not more "powerful" than the other: vega's power comes in it's flexibility, and vega-lites's power lies in its ability to express a user's intent very quickly and concisely, with sensible defaults and aesthetically pleasing output. 

vega is not as expressive as lower-level libraries like d3, but we don't call it "d3-lite" (which would turn vega-lite into "d3-lite-lite"). The fact that vega-lite is implemented as a transpiler to vega JSON shouldn't be something that an end-users need to think about in order to benefit from the grammar and model: in fact, users might be turned off by the prospect of having to learn about *both* vega-lite *and* vega in order to make sense of the ecosystem, which is not an unreasonable interpretation of the project names. While many of vega-lite features are based on vega-specific details (such as the expression language), one could envision an implementation where vega-lite specifications are actualized through an entirely different pipeline, perhaps one that is implemented in another language and rendered in a non-browser environment: in such a `vega-less` use case it would be especially odd for the project to be called `vega-lite`.

I don't propose this undertaking lightly: renaming any software package, let alone a popular open-source package, is always a huge undertaking. Aside from the obvious s/vega-lite/végalité/g replacement, there are external URLs that refer to the name, blog postings to update, published papers to consider, package dependencies to update, and many other things that won't become apparent until after a downstream dependency breaks. To make a smooth transition in a responsible way takes months.

But if a rename is ever to be done, the time to do it is now. vega-lite 4.x is quite stable. Perhaps vega-lite 5 could be the compatibility-breaking release, and we could call it "v5". To be honest, I don't know what to call it, but if the will is expressed that the effort should be made, then we can open up the floor for suggestions.

The vega-lite specification could be a standard interchange format for high-level grammars of graphics, but I believe it will not be perceived as its own unique format unless it has its own distinct and memorable name.

**Comment by kanitw** [comment]
I agree that this name can be somewhat misleading how powerful Vega-Lite can be.

However,, I think the ship has sailed. Vega-Lite has been too popular and widely referred in many places including in data visualization curriculum.  
At this point, the benefits of renaming won't outweigh its cons.

**Comment by kanitw** [comment]
Instead, maybe we should address the concern re: Vega vs Vega-Lite by writing an article to explain when they should use Vega.

**Comment by mattijn** [comment]
I agree on the _brand confusion_. I tend to avoid the name vega-lite as well and explain it more it as a compact, non-verbose form of vega. But change is hard. It’s brave to raise the issue at least!

**Comment by domoritz** [comment]
I agree with everything said above. Vega-Lite is a confusing name but the ship has sailed. Originally, we created Vega-Lite for use in Voyager and never intended it to become its own library. Well, and here we are now years later. A change to the name would be too disruptive for too little benefit. We don't think that we can change the name at this point.

**Comment by kanitw** [comment]
FWIW, I think it's worth revising Vega-lite docs to clarify its current strength. Let's further discuss that in https://github.com/vega/vega-lite/issues/6657.

**Comment by kanitw** [comment]
Btw, I don't think the statement is true though

> Originally, we created Vega-Lite for use in Voyager and never intended it to become its own library.

I'm pretty sure we wanted it to be its own library from the beginning.

**Comment by kanitw** [comment]
The revision of the framing in the homepage in https://github.com/vega/vega-lite/pull/6658 should address many of the concerns here. 

@marcprux @mattijn  Thanks again for raising these concerns!

**Comment by domoritz** [comment]
> I'm pretty sure we wanted it to be its own library from the beginning.

Fair.
