### ISSUE TITLE
Use Vega-Lite with Capital L for consistency

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#667]
- [x] update all docs
- [x] update all UI that mention Vega-lite

**Comment by domoritz** [comment]
You mean "Vega Lite"?

Also

- [ ] update readme files

**Comment by kanitw** [comment]
Yeah, I was thinking about "Vega Lite" after creating this issue, but haven't updated the issue. 
Let's wait for @jheer 's input.  

Also
- [ ] vega.github.io

**Comment by jheer** [comment]
I like "Vega-Lite"

**Comment by kanitw** [comment]
Cool.  "Vega-Lite” it is :)

**Comment by kanitw** [comment]
I just renamed all occurrences of Vega-lite in all `src/` and `readme.md` files of all relevant projects.

**Comment by domoritz** [comment]
Follow up for gallery 1ba1400b49e7 :-P
