### ISSUE TITLE
Rendering Vega-Lite charts as SVG misaligns domains

### ISSUE THREAD

**Issue by alaa-ayyad** [vega/vega-lite#6677]
Changing my charts to SVG misaligned domains although no offset is set to labels, ticks, domains, or legends.

See difference between canvas and svg:
![S1uxL](https://user-images.githubusercontent.com/12691011/85519194-fad20f80-b5b5-11ea-8c8e-dd4453512682.png)

Here's how I set the rendering:
```
  vegaEmbed(chartDivId, chart, myTooltip).then( function(result) {
    var view = result.view;
    view.run();
    view.logLevel(vega.None);
    view.renderer('svg');//<-- render as SVG
  }).catch(console.error);
```

However, I'm not sure this is the proper way to change the rendering for Vega Lite, I looked at the documentation and posted a question on [Stackoverflow ](https://stackoverflow.com/questions/62482831/is-it-possible-to-render-vega-lite-charts-as-svg)with no resolution. Thus I couldn't tell if this my code or Vega Lite doesn't support SVG off the bat, appreciate tips!.

**Comment by domoritz** [comment]
You can pass the renderer as an option to embed. Please refer to the Vega embed documentation. 

Do you still see the issue after changing?

**Comment by kanitw** [comment]
Also, if you want us to help debug, please provide minimal code to reproduce the issue.

**Comment by alaa-ayyad** [comment]
@kanitw  yes please, here is the specs:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/?#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAdxoATemhBQ5mJDVlwATopBqketKGJJBDOBC0BtYAB0QAD3ep3AJgAMAQSBBL4AnO4K7gCe3gCs-gC+Cm6e3n6B-sEAzMEAjJEx3gBsSSnuXmgZQf65gYUgsWgA7GLJqZU+IAE1ddkNTail7RXp3Zk5wWIDJW0AuiDJIIJI0cZoLiDIRgDWViCY0ThwWkxIJkpsOEhQdNFoeUsQcIJwUJjs8qigEDBsygBhNgMWSYfaHY5aCAGMivUxyLRQYRQPZKRA4Q5aWRyE5KJFwc5oTBGeyJJZwWQ6NQw-Y6QRsEzfEA2OwndAAYgAZpyABz+fmmHSyakfBFM56vd6fKF-QHA0GmFn2KGYOAvJisxZLe5Mzk0F5qLT3JQQtkgACODCQoLoFhopFM0FsbNApqh5qMYKWSA8NEcTI+mDh6CBILBJpoKP9nNszyUajYyAMaBjgmeZKUHn2eoNWizShknrQsgYgkEJqOZoZ1NktlMPr94LowZAABELLjlkgmC8AIKyWFs3zNfzxxP6L6p9Nk9pbc57AOVrSqjzhkAQQ4tlY9wSmNQ6-hxJbE60QTkMhAbUB6wSqxk-F5vUVfdey0MKslzNGUtg1sj7LNdX1QRDXQfMDiXdBVQQHAGTrAsGTBVASzLJQG39a8LwsLQAFImAAAhww0M0abNgNA0iK0hdBLWtQM7QdY84FXMjc3QY0IOoi0rRtPQPkYz88TkPV-yZYh9WUfYNyMNgdjNE9ZAga4jApL0ySAA)

And this is how I ran the chart:
```
var toolTipOptions = {theme: 'custom'};
var myTooltip = {tooltip: toolTipOptions};

var chart = { 
//specs in the link above
 };

  vegaEmbed("#mychart", chart, myTooltip).then( function(result) {
    var view = result.view;
    view.run();
    view.logLevel(vega.None);
    view.renderer('svg');
  }).catch(console.error);
```

imports:
```
<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-tooltip"></script>
```

**Comment by alaa-ayyad** [comment]
> 
> 
> You can pass the renderer as an option to embed. Please refer to the Vega embed documentation.
> 
> Do you still see the issue after changing?

@domoritz 

I tried the passing the renderer as an option and got the same result as in the screenshots above:

```
  var opt = {
    renderer: "svg"
  };

  vegaEmbed(chartDivId , spec, opt);
```

**Comment by domoritz** [comment]
Please try to reproduce the issue in the editor.

**Comment by domoritz** [comment]
Please let us know if this is still an issue.
