### ISSUE TITLE
Eliminate dependency Footprint — 20% of the code is dl, d3-color and d3.format

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#669]
I wonder whether we need to compile all of them into our source code.

d3-format is only used to determine the length of a string. We can probably use vega. d3-color is used for interpolation where we can probably leverage vega as well. 

this would reduce the code size (from 1MB!!! uncompressed right now).

**Comment by kanitw** [comment]
`d3-format` can certainly be removed and is on the plan to be removed. 

`d3-color` requires more investigation and might require slight modification to vega, but I think should be possible too.

**Comment by kanitw** [comment]
I'm moving this to 0.10 as it's not that pressing.

**Comment by jheer** [comment]
datalib uses d3-format, so it should already be bundled. It shouldn't
increase the browserify bundle size if built correctly.

**Comment by kanitw** [comment]
The following lines from `util.ts`

```ts
export * from 'datalib/src/util';
export * from 'datalib/src/generate';
export * from 'datalib/src/stats';
```

imports a number of stuff from datalib. 

From checking, we only use the follow methods from util:
`duplicate, extend, error, isArray, isObject, keys, range, reduce, roundFloat, toMap, truncate, vals 

(`getbins, summary` are also used, but will be removed soon.)

**Comment by kanitw** [comment]
Solving https://github.com/vega/datalib/issues/60 would help!

**Comment by kanitw** [comment]
Now that https://github.com/vega/datalib/issues/60 is solved, the dependency footprint is now ~1000 out of 5000 lines.

Not sure how can further improve this without shimming, but I would say I’m okay with the current status for 1.0 so I’m moving this to `1.x patches`.

**Comment by kanitw** [comment]
No longer the case.  The only duplicated part is data lib's util.  (Which should be replaced with Vega Util in #1569)
