### ISSUE TITLE
legend's symbolOpacity does not work

### ISSUE THREAD

**Issue by swanderz** [vega/vega-lite#6719]
### background

I can't pass a different opacity to the legend symbols than what is given to all the marks. I want the legend symbols to have 100% opacity. On [SO](https://stackoverflow.com/questions/62768337/set-opacity-for-marks-but-not-in-legend),  @jakevdp pointed me here!

### reprex ([Vega Editor link](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA28QAspQA4Gc4B6IgNwFMBzCAOkoEspNEAjG+gezKogFpIY+clHxEBEIgGMIyfDQBW+DgDsQAXwA0IALYyA1vFBQAnrnIZJ9ZJNTmtHXBEsn4ABhoBGTSHLLJHMHplSkMQf1QOZFCAM3pyVDAMAHlkegZVLRMzDGUObSCIdC1bSl9EhBB8Y20WDlQkx2djeC9vAA8YuISMAAlIoVwOAHdyKMzTczgQAEdECGUoRmh6CnUtZorY+PKQAFl6W3wAfTNkI4BxQoiMkCzJmbmFpcXVtTegA))
```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
  "mark": {"type": "circle", "opacity": 0.1},
  "encoding": {
    "color": {
      "field": "Origin",
      "type": "nominal",
      "legend": {"symbolOpacity": 1}
    },
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"}
  }
}
```

**Comment by domoritz** [comment]
`symbolStrokeColor` also doesn't work as expected. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A bubbleplot showing horsepower on x, miles per gallons on y, and binned acceleration on size.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "size": {"field": "Acceleration", "type": "quantitative", "legend": {
      "symbolStrokeColor": "red"
    }}
  }
}

```

**Comment by domoritz** [comment]
Thank you for the bug report @swanderz. Fixed in https://github.com/vega/vega-lite/pull/6724.

**Comment by domoritz** [comment]
![image](https://user-images.githubusercontent.com/589034/87235800-0afb3480-c395-11ea-8177-85a8cb3e1f9d.png)

**Comment by swanderz** [comment]
I <3 ‘vega-lite`! Thanks @domoritz
