### ISSUE TITLE
Tooltip don't work with size property

### ISSUE THREAD

**Issue by AlasDiablo** [vega/vega-lite#6721]
Hello, i need use the `size` property from the encoding but this property break the tooltip when i add it, in my project i can't use `"width": {"step": "20"}` because i need to fill a container with a custom bar size.

![Capture du 2020-07-10 10-11-30](https://user-images.githubusercontent.com/25723276/87132167-c3da4a00-c295-11ea-9e17-ecc93181bbf3.png)

[Vega-Editor (with size)](https://vega.github.io/editor/#/url/vega-lite/N4IgtghgTg1iBcoAuBPADgUwSARtEAvgDQgYB2AxgPYAmAlmQOYKgAeLIAZnRgDY3YA+nQElUmbGSpgGEXiBIRWdAM4deEHHwCCTXlngAGMXQowAsgwDKSDGgQBGYiCR0k+7ApAqqUJNhRCEkDELh5+bAA3OQBXLDF0AxAARxiIMlckCFdI+JAlVXVNHT0DYxdTC2tbe3gnEhUKOQNkROxeBgx8Z0yPeBAgkGpeXw5uPgF+4VFvJr7QKHTGAwBtEABiGgB2BwBOBwovdc4aCAwANgcjzhvOHE4jzRpTgBYjgCYcAA4AZjwQAC6PTa-SkMjIci8+mWZEmZBivF4PSoVF4rlqK1A4wiUxEXnESTBsnkJncSQAwtkMIxfIFiFjwpMQNFeHF8SCUmkMm5snRcvi3H0QAA1WJYAgAhp0ABeLWZYuwP0MhGcaAgzwYzFC+k4-n672VJCgdEYAAs9eUkFRag5yjgqEgrWBsAbBqcshwWXE1PBMSBpi7DA43iQvQYtj96f68fqg1svGGELsvlGA7GHABWBMKuqGd6pmMgA0Oc7Z1kGW2RoigNNFoNfMts3MpoEkADuIiQpoQL3OLwAdA4fiRTRgTeaEErDAQgA)

[Vega-Editor (without size)](https://vega.github.io/editor/#/url/vega-lite/N4IgtghgTg1iBcoAuBPADgUwSARtEAvgDQgYB2AxgPYAmAlmQOYKgAeLIAZnRgDY3YA+nQElUmbGSpgGEXiBIRWdAM4deEHHwCCTXlngAGMXQowAsgwDKSDGgQBGYiCR0k+7ApAqqUJNhRCEkDELh5+bAA3OQBXLDF0AxAARxiIMlckCFdI+JAlVXVNHT0DYxdTC2tbe3gnEhUKOQNkROxeBgx8Z0yPeBAgkGpeXw5uPgF+4VFvJr7QKHTGAwBtEABiGgB2BwBOBwovdc4aCAwANgcjzhvOHE4jzRpTgBYjgCYcAA4AZjwQAC6PTa-SkMjIci8+mWZEmZBivF4PSoVF4rlqK1A4wiUxEXnESTBsnkJncSQAwtkMIxfIFiFjwpMQNFeHF8SCUmkMm5snRcvi3H0QAA1WJYAhAkhoCDPBjMUL6Tj+frvQxeKB0RgAC2V5SQVFqDnKOCoSH1YGwqsGpyyHBZcTU8ExIGmlsMDjeJHtBi2P3pLrxKvdWy83oQuy+-tdQYcAFZQ2LHIZ3lHAyBVQ5zgnWQYjX6iKBo+n3V9s2y6oZI5KQAB3ERILUIF7nF4AOgcPxIWowmp1CB+hkMBCAA)

**Comment by domoritz** [comment]
It works if you make sure to use numbers, not strings. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgmSFSAC+SuLKhsAJjVllNIAB5OAZjTiCbBgPo0fJR09A1k2BHskQUUQJGcaCCdBJCYvAEEHQX1UAAYgmig1AFl7AGVMOBw0AEZzEEw6LIMYmRVMA20zJU7UUA8vH3RiKIZ9IN1skABHBiRZBswkBtIYuISklPTM7Lz6guKyiqrUWqVoKOytCYNhWThjLr3MJvRH60E2E16Qfu8-AJaUAuThUczI2QA2iAAMQ2ADs1QAnNUoDFoW4bEg4AA2apotwEtxMNxolI2TFiNEAJiYAA4AMxGEAAXTqwUmYQisiiMSy4Nkg1kDEEgjZbDYggaxwhfU8f3Q-kC9Wu6E5kWi+WekwAwktyJ9OuZZQMDMNBKMYuyDDM5gsljQVpqXiAAGojfSmZlnGgAL0uIDNFtQ9JypjqmMWTkDcESqBlIEVBipOWqlKU0bQcPpRoTAPQyeqcJiGdQiNpOcT+ZTAFZi+6ajkqRW8yAC9i6+bstUctmFKBK62U7SO0Hu+XWUoAO4BehoMTYiTVelKeA0MhYNAh0NAA)
