### ISSUE TITLE
Error with no name "id" in map

### ISSUE THREAD

**Issue by eeyshen** [vega/vega-lite#6764]
I found if we change "lookup" key in map as following, error happens.
Steps:
1. Change string "id" to something else like "newID" in us-10m.json
2. Change map json as:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 300,
  "data": {
    "url": "data/us-10m.json",
    "format": {
      "type": "topojson",
      "feature": "counties"
    }
  },
  "transform": [{
    "lookup": "newID",
    "from": {
      "data": {
        "url": "data/unemployment.tsv"
      },
      "key": "id",
      "fields": ["rate"]
    }
  }],
  "projection": {
    "type": "albersUsa"
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "field": "rate",
      "type": "quantitative"
    }
  }
}
```

**Comment by jwoLondon** [comment]
But wouldn't you expect there to be such an error? There is no `newID` in `us-10m.json`, so it cannot be linked with the `id` field of `unemployment.tsv`.

I think more significant is when looking up with the geo file as a secondary data source, where even a single unmatched feature kills the entire lookup – see https://github.com/vega/vega-lite/issues/6163

**Comment by eeyshen** [comment]
I mean simply replace string "id" with string "newID" in us-10m.json. It is expected that it could work by changing "lookup" keyword from "id" to "newID", which will match value of "newID" in map data with value of "id" in unemployment.tsv. Is there something wrong? Thanks.

**Comment by domoritz** [comment]
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAdxoATemgCsABh1L4NMljQBmPUrVJMKVKAYAnQWgzY8hArQiZqdRkwYIOAcoOUw4WR9QhAI1NgQ2BzoALwJTAA4mUzEAdiQATnyoADYdACZ8sSgARjz06rLTJiyxaobqtQIHJGUCEp1i8y0mHQAzdLUtUanR6rEdebKypDKsrSh8vJyFwqgdAkD+ap0EKRl5JVHE5Ew0UEwATxw4F0w2HDZpOUUQUbhrRwvdChBiRGhwCAgAC+UKUmG6sggVwcCDQAG1QII2GwANYMHAuWRwZQASQAIj9Rg54ncQFYbLTHM50PSkAciQgcFiHggIj5MBBiNClDi4A8XOpKeDBGpIag0SBuuEQABdGEqpQ4amSOBQTDseR2ECPZ4uJCCJjBCAAVQgKFhIGQDhxLjIcDYEBgSFNSgioTUNFkZFpoSxDlpo2lahcSpecKeQJAAEcGEgwTZ9aRoTCgA)

**Comment by domoritz** [comment]
I am getting a warning when I load this spec.

<img width="495" alt="Screen Shot 2020-07-30 at 21 30 10" src="https://user-images.githubusercontent.com/589034/89000286-da2f6080-d2ab-11ea-8f57-fa3eb1175fd9.png">

Same with an even simpler example [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATJJhSoA2qHFIEcNCDEMATlDgB9AAzSQ+gDbasufEVoRM1OoyYMIcAxMxxxzqDYEAlkgtj06AC8CAGYADiYYgBYAdiQATnSoADYTACZ0pKgARjS44ryYpkSk4ori2QI9JAB3AhyTbJiTASYTADM42QF+kf7ipJNJvLykPMSBKHS0lKnMqBMCDwBaYpMEETFJGX7w5Ew0UEwATxwtdEw2HDZRCXN+uAV9e5BAhn8aHAICAAL4ggC6IKAA). 

Maybe we are expecting identifiers. See https://github.com/topojson/topojson-specification#22-geometry-objects.

**Comment by jwoLondon** [comment]
Ah, I see the problem now - apologies for misunderstanding your original question.

`id` is a reserved and specific name in a topojson file and is used as a shorthand for single attribute associated with a feature. It cannot be any other name, so Vega-Lite is correct in failing to load it when given another name.

To provide arbitrary custom attribute names the topojson should use _properties_ instead, for example, `properties: {"newId":1, "myOtherProperty:"elephant"}` and then the Vega-lite spec can refer to it as `properties.newId` etc.

One Vega-Lite issue though: There is no warning of `loading failed` in @domoritz examples when viewing in Safari, but there is in Chrome. Not sure why there should be a browser-specific variation here.

**Comment by domoritz** [comment]
I'm going to close the issue here then since Vega-Lite is correct. The problem with the missing warning is either in the Vega loader, topojson, or even the browser.
