### ISSUE TITLE
Pie chart not working as intended

### ISSUE THREAD

**Issue by TheGreatBrutus** [vega/vega-lite#6765]
JSON:
```
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-2a421566ef06e9216711d34fa2433a8f"},
  "mark": "arc",
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "Status",
      "scale": {"range": ["#2ca02c", "#d62827"]}
    },
    "column": {"type": "nominal", "field": "Entry"},
    "tooltip": [
      {"type": "quantitative", "field": "Amount"},
      {"type": "nominal", "field": "Status"},
      {"type": "nominal", "field": "Entry"}
    ],
    "theta": {"field": "Amount", "type": "quantitative"}
  },
  "height": 250,
  "width": 100,
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "datasets": {
    "data-2a421566ef06e9216711d34fa2433a8f": [
      {"Status": "mislukt", "Entry": "test", "Amount": 2},
      {"Status": "gelukt", "Entry": "test", "Amount": 4},
      {"Status": "mislukt", "Entry": "test_1", "Amount": 1},
      {"Status": "gelukt", "Entry": "test_1", "Amount": 6}
    ]
  }
}
```
Screenshot: https://imgur.com/a/9KdOSdw

What seems to be happening is that the graph that has the highest amount determines the division for the other graphs, as seen in the screenshot.

- Entry test has a total amount of 6
- Entry test_1 has a total amount of 7

**Comment by jwoLondon** [comment]
The two charts are using a common scale for `theta`, which is also what they would do if using a Cartesian scale.

Can be solved by specifying independent scales:

```json
"resolve": {"scale": {"theta": "independent"}},
```

I guess a question remains as to whether the default for radial plots should be to have independent or shared scales, but I know that previously there has been the intention to treat defaults for polar and Cartesian positioning in the same way.

**Comment by TheGreatBrutus** [comment]
Thanks for the quick response!

Cheers
