### ISSUE TITLE
formatting of header labels for faceted charts (facet as an encoding channel) yields wrong output for "year" - always 70

### ISSUE THREAD

**Issue by armsp** [vega/vega-lite#6769]
I think header labels for faceted charts where facet is specified as an encoding channel have some issue with the `format` parameter. 

For example:
Using the population dataset, faceting by `year` and making the headers show the last two digits of the year using `%y` as value for `format` and `time` as value for `formatType`, makes all the years as 1970 and thus outputs 70 for all the headers.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "title": "US Age Distribution By Year",
  "width": 200,
  "height": 80,
  "data": {
    "url": "data/population.json"
  },
  "mark": "area",

  "encoding": {
    "x": {"field": "age", "type": "ordinal", "title": "Age"},
    "y": {"field": "people", "type": "quantitative", "aggregate": "sum", "title": "Population"},
    "facet": {"field": "year", "type": "quantitative", "columns": 3, "header": {"format": "%y", "formatType": "time"}}
  }
}
```
![year_issue](https://user-images.githubusercontent.com/12681262/89257794-81ade980-d644-11ea-850c-a7e74427d9d9.png)

**Comment by jwoLondon** [comment]
I don't think the problem is with the header, but rather you need to specify that the data field, comprising of a single integer, is to be treated as a date. Using the following seems to solve the problem:

```json
"data": {
    "url": "data/population.json",
    "format":{"parse":{"year": "date:'%Y'"}}
  }
```

**Comment by armsp** [comment]
Yeah, this fixes it. Thank you @jwoLondon !
