### ISSUE TITLE
trim axis in vega-lite v3

### ISSUE THREAD

**Issue by kirisakow** [vega/vega-lite#6771]
How can I "trim" the axis and get rid of that padding on both sides beyond `[-101, 225]` ***specifically in Vega-Lite v3*** ? 

(I am opening an issue because I have come to believe that is not feasible at all, let alone in v3. Also, [freshly asked about that on StackOverflow](https://stackoverflow.com/questions/63268181/trim-unused-outer-parts-of-the-axis-in-vega-lite-v3))

![](https://user-images.githubusercontent.com/11773604/89426563-966ca900-d73a-11ea-87ef-3fa226fa652f.png)

**Comment by domoritz** [comment]
You can set the scale domain or disable scar nicing. 

Also, we reserve the issue tracker for bugs and feature requests.

**Comment by kirisakow** [comment]
Many thanks @domoritz 

**Result:**

![](https://user-images.githubusercontent.com/11773604/89508773-a7ff9080-d7ce-11ea-837e-6e83ded060aa.png)

**For whomever shall tread on this path in the future:**

    ...
    "encoding": {
      "x": {
        "field": "field_name",
        "type": "quantitative",
        "scale": {
          "domain": [lower_limit * 1.05, upper_limit],
          "nice": false
        },
        "axis": {
          "domain": false,
          "grid": false,
          "title": ""
        }
      },
      "y": {
        "field": "another_field_name",
        "type": "nominal",
        "sort": {"order": "ascending", "op": "sum", "field": "sorting_field_name"},
        "axis": {"title": ""}
      }
    },
    ...
