### ISSUE TITLE
Can't generate SVG

### ISSUE THREAD

**Issue by fiducioso-sanjith** [vega/vega-lite#6803]
I am migrating from vega 2.x to 5.13.0 version. I am trying to generate chart SVG, so I can use as per my requirement in my HTML page. For that I am using toSVG(). While using that either success or catch method both are not firing.

```
var view = new vega.View(vega.parse(chartJson), {renderer: 'none'});
view.toSVG().then(function (svg) {
  console.log(svg)
}).catch(function(err){
  console.log(err)
})
```

**Comment by domoritz** [comment]
You can find a working command line tool in vega-cli (https://github.com/vega/vega/blob/master/packages/vega-cli/src/render.js#L46). I hope that helps. 

Also, this is Vega-Lite, not Vega.
