### ISSUE TITLE
Box plot outliers are not colored

### ISSUE THREAD

**Issue by keckelt** [vega/vega-lite#6818]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks

---

Hi!

According [to the docs](https://vega.github.io/vega-lite/docs/boxplot.html#color-size-and-opacity-encoding-channels) of box plots 
> The color is applied to only the box, the median tick, and the outlier points. 

First, the outlier points are not colored, but probably should be to directly see where they belong to (orange here):
![image](https://user-images.githubusercontent.com/10337788/91151196-a7676500-e6bd-11ea-99a8-8a77d36edaee.png)
https://vega.github.io/editor/#/examples/vega-lite/boxplot_2D_vertical

Second, the median tick is not colored like the box (or the outliers) as described - but shouldnt be anyway imo.

**Comment by keckelt** [comment]
When opening the generated Extended Vega Lite Spec, the outlier part just needs the color encoding added:
![image](https://user-images.githubusercontent.com/10337788/91207311-db1bac80-e708-11ea-96f3-fe984641cdfb.png)

[Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABKXU6oSQYaZsAHoZyC2mQxBhsA7jVllDCOMpokWUMg5UNHdzh1ENkwhhwcKMMARwYkUxpBNUM2ADNDejhDAIhMTSYGHTkc-OtlAE9fJAgIGvs4bwYvCEpFFSRMFFRQBnVBNH7BgkTO7qkZeQBfJUEkeqi0AG1QMqCIXLZ1BC3QSTYvJDIydT5MOBOQNhwJ5IBGPtyaOEFlCYAhNgNQwAWWarQAFGQAJR9ZoTCJRAD61hsiIBQNBLUMkJhy1ATxeAGYPl8fv9AY1MRDobCIBN4ol1MjbGiKSCwdiaYsALpKa5seJMepbEAAZUSUC+dKU4rgkrUIG5PJWaw2qG2IF2sn2h2O6tAn0Ed3UE3BygGDAQmwAOiB0ZSOTjbdzDAAeYoWq22hFMlGsjGO6HOwz8QyvSgAVkMACpsebMJabSAGUi-fb2VinYqQx6E16QD7maj01TOVDnVCoYYAD7VuOepMlwPl7MAPlzidtKd9LKbmaD2YA1GHIzH63mk92i-6Hf2Wy7Q-HOwWPKne2zS1nuZWQMqQMh1ABrNA7eqJCY4c6yTB9Ur1LITFEOJz8AWYYRROnLEAdKCArxkCeIDCsMICfN8vzoH21IwkomBnvc6CpEEOiDDopB9KhD5QRuza3uY2GgAAXlEbBoLkFgQHAizfjYQHgWS6CyvK0qaghEyyGwCAXOM35-o4JqgQxkFihKUqYex6CcdxsgWLuNEKDs6h7AcRwPIaxqmku+aFmmuFzsGobhlGsZmg2XYJGuxb6TBhkdjpq49tZAYGYqVaugAvPZjY2WWFaGAAZAF47LtBfnZp53kWYy05hVuhjDsZY5mRO0VWTOGa2dmi7mSukRORlm4DtuuKKSAlzXLciEagS6AySSEHki5MG0vCjmIu4MA0BAh5InFXJlbV+5IHRSjCU1s4tUocLoFOnXdb1TL9aV+LPHVXgNYxeXpctrXoLp67NWWu6DWtw2jWBpIiVOelHTie3JpZBW7Xu-KCiBmyiXK4kymJCpKryBaqoJGoHseoHwee6DqAwD5KF4xAWDQkGyLDgjTZoQwUYIVFKHe2EgE+jiYPwMMPt+v7-t4QEgQaV1tflHVdT1fW+fdcGSSAyHXnQAw0BhcF0ATu14wRiHEaR5GUdR371AATPR9P7e1t2TcdtGK41TF-axkOISA0k8SdmpsGwRpaOpSuPTF80s0tbM0hzUNc2kPNofz9yC+++sAKpPYYADqzOLW0L1leNyuM7bi2FXhTv69zqF8wLmpC-rAAyjmB8HSR5IYYd01rX0sRJzuG7JvFKniw1HkBesTGTnsgAjSMo2jGOBFLONwHj8EE0TL6N8blMBNToG05dRc3Ydavs2xzuJ7z6FN1h+siyA0AWOLIAkeoZGoNjVEKcBCtCVbc05-bd0DSAdFn0XzE-fP+vl3J36YKb5trRqEfW0i0es2vrBZ+LxXZJ2XphNOEw-aMmzgtXO+QC6Ty2oWABV9Z6OxAUhMBS8PaQO9hMTO+U4F21Dg7FayCRKPwVPHDiXEjY8hogDauWodRqX1OVK4NwKB3AeENN4m0RLrxmttZ65CTqrSJIIiamVjrTTpLNJ6sVxHVyGn4AIQRpE4SAQ9biyhlE6NUWdeqY0rbCIUfuLwsc5wSMeMYkaWi7TiPkRMZAzkMG4kBm9HAQoRTUNYv4xUe5VjrBBqAMGddOZMHSLeGgJE0CvDEEoQ4XxrwTBMGYOS8NZCI2EG3QQ6NyqYwAEpmzgAAETUFATQ2hdCPlsLePu+sB4kxRMPWQf5R6AXHprFBKsZ6yLnvXbBKFcEp1XjIoqwDN6ER3pLA+0tj7y16ddJRqtBk3zvoXLagTaFSXoRXY2-FDgrImLsrBBsDlZILOQDo+TBDv0-job+2yRJuOsVNC5i93bjKgegUEdg85IN-tPdxGzgHDJdqMn5K8-kgAAIqEjIYY8OVs9EGI8aXBOOCYX4IJsCfwgRghApUaiouB0wVTKxaA6FydYUEPQPC14yLMXV1-jJD5civk4rpXi-WwIvAsvBbY3+5zIWv0rgpcJ6RwagGOYJEA81eF7NTlAY82TcnIzQKjApeM4mIUSckzQHQbzoDcJoIichBjjA7ljaWvd7zNNsM+Em6iiXtM6QBGmpz1r6PWVSlV3zeVe2Fs4jeYsgK733ofGWSgtmULOTral+yZJvzgk8i2HD2UjU5UMzmQaIEhv5SNIVVK2XnzWQMgN3LaWFtTgyhFSKSUotea45GGLhWBp5XWiZ-zCVBFLXhct5L+mUrjjWt2wb60EyZYOmxw6tocvXpCgteCi0TAFcSxBpLW3a2+jQi5ErdxV2YUAA)

**Comment by domoritz** [comment]
This is a problem in the boxplot normalizer.

**Comment by keckelt** [comment]
Because it's adding the `encodingWithoutSizeColorContinuousAxisAndTooltip`, right?

I assume the color from https://github.com/vega/vega-lite/blob/4b34ce48e5ff1df6d361831ceca4236a79995271/src/compositemark/boxplot.ts#L120 should be there too.
