### ISSUE TITLE
Use local vega, vega-lite and vega-embed JS files

### ISSUE THREAD

**Issue by iarabadjiev** [vega/vega-lite#6827]
Hello,

I want to be able to view some vega-lite plots embedded in a html page, on a computer without internet. I first saved the the vega, vega-lite and vega-embed javascript files locally. I then replaced the script urls

```
	<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
	<script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.2"></script>
	<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
```

 with local files location

```
	<script type="text/javascript" src="vega@5.js"></script>'
	<script type="text/javascript" src="vega-embed@6.js"></script>
	<script type="text/javascript" src="vega-lite@4.0.js"></script>


```

but the plots disappeared, and I got this error message in my browser console:

```
vega-embed@6.js:26 The input spec uses Vega-Lite v4.0.2, but the current version of Vega-Lite is vundefined.
(anonymous) @ vega-embed@6.js:26
TypeError: mr.compile is not a function
    at Object.vega-lite (vega-embed@6.js:26)
    at vega-embed@6.js:26
    at Generator.next (<anonymous>)
    at vega-embed@6.js:16
    at new Promise (<anonymous>)
    at i (vega-embed@6.js:16)
    at vega-embed@6.js:26
    at vega-embed@6.js:26
    at Generator.next (<anonymous>)
    at a (vega-embed@6.js:16)
```

I use altair to generate the plots, in a similar fashion as here: [https://github.com/altair-viz/altair/issues/1422](https://github.com/altair-viz/altair/issues/1422)

I downloaded the js files directly from the links that produced a working chart. Does anyone have any idea how to make this work? 

Thanks,
Ivo

PS: I found a similar javascript warning in this issue: [https://github.com/vega/vega-lite/issues/5374](https://github.com/vega/vega-lite/issues/5374), but the bug is different.

PPS: here are all the files. Replace the vega files file format by .js and the charts by .html if you want to test them.

[charts_with_links.txt](https://github.com/vega/vega-lite/files/5149696/charts_with_links.txt)
[charts_with_local_files.txt](https://github.com/vega/vega-lite/files/5149697/charts_with_local_files.txt)
[vega@5.txt](https://github.com/vega/vega-lite/files/5149698/vega%405.txt)
[vega-embed@6.txt](https://github.com/vega/vega-lite/files/5149700/vega-embed%406.txt)
[vega-lite@4.0.txt](https://github.com/vega/vega-lite/files/5149701/vega-lite%404.0.txt)

**Comment by domoritz** [comment]
It works when you change the order of the script tags

```html
		<script type="text/javascript" src="vega@5.js"></script>
		<script type="text/javascript" src="vega-lite@4.0.js"></script>
		<script type="text/javascript" src="vega-embed@6.js"></script>
```

The issue is that the browser can load the scripts somehow faster. Not sure exactly.
