### ISSUE TITLE
Permit marks to contain secondary marks

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6842]
Currently, some of the marks have secondary marks they can specify in their config. For example, the `area` config can enable a `line` and `point` mark:

```json
{
  "mark": {"type": "area", "point": true, "line": true},
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

The current method makes configuring the embedded point and line marks tricky, since their mark configs need to be embedded in the parent's mark config. As well as causing some issues (e.g. #6841), it isn't intuitive that some marks can have specific secondary sub-marks but others don't. For example, why can I add a secondary `line` to an `area` but not to a `bar`?

I propose that vega-lite should allow this same expression using child marks, either by overloading the current `layer` array, or adding a new grouping `submarks` array. The above spec would then look like:

```json
{
  "mark": "area",
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  },
  "submarks": [
    { 
        "mark": "line",
        "encoding": {
          "strokeWidth": {"value": 2}
        }
    },
    { 
        "mark": {"type": "point"},
        "encoding": {
          "size": {"value": 100}
        }
    }
  ]
}
```

As with group layers, child marks would inherit the encodings of their parent mark.

One immediate advantage of this mechanism would be to simplify adding annotations to existing visualizations, which is currently cumbersome (since the entire visualizations needs to be re-factored to use groups). So text labels could be easily added to a line chart like so:

 ```json
{
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  },
  "submarks": [
    { 
        "mark": {"type": "text", "dy": -25},
        "encoding": {
          "text": {"field": "price"}
        }
    }
  ]
}
```

**Comment by marcprux** [comment]
I also wonder if this could simplify the implementation of new compound mark types. For example, the extended vega-lite spec for a `boxplot` is simplified by expressing some of the encodings in a mark layer hierarchy (rather than putting them all together as siblings under a single parent group, which is what it currently does).

**Comment by domoritz** [comment]
Just a quick check, how does this proposal differ from layering?

```
{
  "encoding": {
    "x": {"field": "date", "type": "temporal"},
    "y": {"field": "price", "type": "quantitative"}
  },
  "layer": [
   { 
        "mark": "area"
    }, 
   { 
        "mark": "line",
        "encoding": {
          "strokeWidth": {"value": 2}
        }
    },
    { 
        "mark": {"type": "point"},
        "encoding": {
          "size": {"value": 100}
        }
    }
  ]
}

```

**Comment by marcprux** [comment]
It would essentially be shorthand for layering – you'd just be able to keep the top-level mark as "area" and not have the initial "area" sublayer, but everything else would behave the same way.

**Comment by domoritz** [comment]
I'm worried to have more shorthands ;-) As you can see, it's already difficult to get all the edge cases of marks with submarks right.

I would vote for closing this and suggest to support this kind of shorthand it higher-level tools.

**Comment by marcprux** [comment]
Point taken. In an ideal world I'd prefer this shorthand over the current `{ "type": "area", "point": "true", "line": "true" }` shorthand, but we'd want to keep the old one for compatibility, and I agree that having multiple separate shorthands does complicate things. I'll close this suggestion.

**Comment by domoritz** [comment]
You know that you can customize submarks, right? [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVJOmNlADWESlAjEQAXyWZtSWRABmbbQjQBtUG5pBTDhtfVVMBgRKCABPBCY2QQBeFIByAHEAeUz01PsAXSVkbTM0UEwYnDh9YVlqpRw2GllMMpAAwT10bThlewcQOFkoNmVmsjaADzaAuEE+9HD6kAqq-WCERuc9AZiZmjmFkBxtGihl1er0AEcGF0w6NRpSfrsgA)

![image](https://user-images.githubusercontent.com/589034/91927479-7a531d80-ec8e-11ea-95dd-4665c9da6d95.png)

**Comment by marcprux** [comment]
Yes, but you can't add encodings or transforms to them. Having the submarks represented as first-class mark children would allow this (as is also the case when the visualization is re-factored so these submarks are all siblings in a group's "layer" array).

**Comment by domoritz** [comment]
Cool. I'm happy to revisit your proposal at some point in the future when we have cleaned up the mark compiler a but more.
