### ISSUE TITLE
Externalize Vega packages like vega util

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6857]
Almost always, users load Vega when they load Vega-Lite so I think we should externalize Vega in the Vega-Lite bundle.

**Comment by keckelt** [comment]
I did not realize that this is not necessary.

**Comment by domoritz** [comment]
That what is not necessary?

**Comment by keckelt** [comment]
I'm using vega-embed and from the [README](https://github.com/vega/vega-embed#basic-examples) I just assumed that I have to have Vega as dependency when I want to use Vega lite. As it is compiling to Vega that made sense to me.

**Comment by domoritz** [comment]
Ahh, let me clarify. Vega is required to render a compiled vega-lite spec. The vega-lite bundle includes some specific Vega packages like Vega util.

**Comment by domoritz** [comment]
I'm marking this as a 5.0 issue since it's a breaking change (although I don't expect this to be an issue for almost everyone).
