### ISSUE TITLE
Move all CLI scripts to be just node scripts instead of shell scripts

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6863]
This way, we can avoid npx. See https://github.com/vega/vega/tree/master/packages/vega-cli/bin for how Vega does things.

**Comment by MMesch** [comment]
This would be great for packaging vega-lite with systems such as Nix. Currently `npx` has to be overwritten manually which is not great for maintenance, see https://github.com/NixOS/nixpkgs/pull/97908 .

**Comment by domoritz** [comment]
@MMesch do you want to send a pull request?
