### ISSUE TITLE
Bar/area chart should stack by default

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6864]
I have thought about this for a bit. 

Currently our bar chart overlaps by default and only add stacks when users add color encoding.

This is quite "magical" and can be surprising because coloring marks shouldn't modify their position layout (which is a different concern). 

By stacking bars by default, we can 
1) Make adding color really only add color
2) Avoid misleading plots that hides overlapping bar behind another like [this bar chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoyaloAIxiufnoAEJFqACsteUgSQDCNWIAzNkAurkgyOoA1gXW6sFwslBsyjSyZGigAB7zIABmNHCCygUoSpgAnjhwBbJsCDNRwUgLNBDLgkiegvqzFmgADNm9e8trG1voaV2ByO6AAjgwkLIdIEdKQQJ9skA), or [this area chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoyaloAIxiufnoAEJFqACsteUgSQDCNWIAzNkAurkgyOoA1gU2cChKcLJQbMo0smRooAAeCyAAZjRwgsrDwZgAnjhwBbJsCLNRwUiLNBArgkiegvpzFmgADNm9eyvrm9voaSU+0OBQAjgwkLIdIEdKQQJ9skA) (which totally ignores one data point).

Doing so would simplify a lot of complexity we have in the stack inference logic as well.

**Comment by domoritz** [comment]
I am in favor of this.

**Comment by domoritz** [comment]
Area chart without stack


![image](https://user-images.githubusercontent.com/589034/101475685-8d1a6580-3901-11eb-8321-ced4b328e55d.png)

Area chart with stack

![image](https://user-images.githubusercontent.com/589034/101475651-84c22a80-3901-11eb-8685-0ae385ca7e59.png)

Not sure the stacked version is much better, tbh.
