### ISSUE TITLE
Switch from default bandScale padding to default bandWidth ratio

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#6865]
This way we don't have to make default scale config depends on mark type

**Comment by domoritz** [comment]
That would be a great improvement. I like fewer dependencies in the compiler.

**Comment by kanitw** [comment]
From discussion with @domoritz, let's not do this since this will add complexity to the output Vega code for bars.
Basically, we need to replace `x: {scale: 'x', field: ...}` with `xc: {scale: 'x', field: ...band: 0.5}`. The latter is more complicated and adding unnecessary extra computation.
