### ISSUE TITLE
Provide a simple way to customize guide label texts

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6875]
The labels for axes and legends are derived from the scale domains. However, it would be nice if there was a simple way to map values -> labels without having to modify the data. This is especially useful for multiline labels or descriptions. I think this feature could give a huge boost to customizability.

**Comment by kanitw** [comment]
We have `values` property for axes and legends, which I believe is exactly for this purpose. 

If you mean something else, feel free to re-open this issue.

**Comment by domoritz** [comment]
With `values`, you can override which labels are shown but you cannot change them, I think. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [{"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43}]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"values": ["A", "B"]}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/103453834-e3758c80-4c92-11eb-9d9f-401155b6086a.png)

What I am asking for is a mapping from existing labels to new labels (e.g. map "A" above to "Apple").

**Comment by kanitw** [comment]
If that's what you want, you can [use `labelExpr`](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSACCikEzQAmABwBfBSbQgAQpeuoArN6cv0AGFPNDEAZgcAXScQZAAnAGtXJiQ4yzhZKDZlGlkyNFAADwKQADMaOEFlVxQlTABPHDhXWTYEXJ1LJEKaA00QQSQmSoBRQpw09GAAcjNp1AACaZ0cGCRphSW3eaXh9Q2lwJ3p2FThOGmHQ1VMBgRKbV04SJAHGPqS8srq9Gs6xua6AAjgwkLJMHQ1DRSK83kA):

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [{"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43}]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelExpr": "{'A': 'alpha', 'B': 'beta', 'C': 'charlie'}[datum.value]"}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/103470058-cd092700-4d9f-11eb-86c6-bc3ece72085c.png)

**Comment by domoritz** [comment]
I see. It even works with multiple lines: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSACCikEzQAmABwBfBSbQgAQpeuoArN6cv0AGFPNDEAZgcAXScQZAAnAGtXJiQ4yzhZKDZlGlkyNFAADwKQADMaOEFlVxQlTABPHDhXWTYEXJ1LJEKaA00QQSQmSoBRQpw09GAAcjNp1AACQ2mdHBgkaYUFlcE1jcit6bd57eH1Te3Ak+nYVOE4aYdDVUwGBEptXThIkAcY+pK5Uq1XQ1jqjWa6AAjgwkLJMHQ1DRSL8-kA).
