### ISSUE TITLE
Scale binding fails with nested attributes

### ISSUE THREAD

**Issue by john-guerra** [vega/vega-lite#6882]
Scale binding fails on this example

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "mark": {
    "type": "point"
  },
  "selection": {
    "sel11": {
      "type": "interval",
      "bind": "scales"
    }
  },
  "encoding": {
    "y": {
      "field": "p.x",
      "type": "quantitative"
    },
    "x": {
      "field": "p.y",
      "type": "quantitative"
    }
  },
  "data": {
    "values": [
      {"p": {"x": 1, "y": 1}},
      {"p": {"x": 2, "y": 1}},
      {"p": {"x": 1, "y": 2}},
      {"p": {"x": 3, "y": 3}},
      {"p": {"x": 3, "y": 2}}
    ]
  }
}
```

The reason seems to be the nested attributes. Here it is in the [vega editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgcbGrMwgAvkohxBcKJnbzUoa4ICMbzSB16DJzHAqxEiCiiBMJgAmBtAhcBAWliBwslBskSZkXtpeAGY0NtHoOJQAHmE++ugAjgxIpnRIDqQWSuXOIPmFBiU5SpUGtfUOmE00LeZJkU0oHcGCDPFoANqgOF7tbko5qG6TCmsbaABM22h7locdm2eox-tXoO0AzLfPD4ZHqK8gO-fmAF1JkA)

I wonder if it is related to #6107 

And [here are different configurations tested in Observable with the Vega-Lite-API](https://observablehq.com/d/63d0d3397a45ec2d)

My goal was to make a zoomable map, but it seems like scale binding doesn't work with latitude/longitude am I right?

**Comment by arvind** [comment]
Fixed with #7159
