### ISSUE TITLE
Tooltip dates are off by one

### ISSUE THREAD

**Issue by matthewcornell** [vega/vega-lite#6883]
Hi Folks. Thanks for your awesome work. I'm integrating vega-lite into our [COVID-19 work](https://www.zoltardata.com/project/44/forecasts) using vega-embed, and I'm seeing tooltip behavior that seems like a bug. I created the JSFiddle [vega-lite date one off](https://jsfiddle.net/matthewcornell/Ljmhe3bg/6/) and I've included the JSON config below too. I had a look at https://vega.github.io/vega-lite/docs/timeunit.html#encoding , but didn't find anything that seemed relevant. I'm guessing it's an error on my part, but I'd really appreciate your help. Thank you.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "model": "docs forecast model",
        "timezero": "2011-10-02",
        "# rows": 62
      },
      {
        "model": "docs forecast model",
        "timezero": "2011-10-09",
        "# rows": 62
      }
    ]
  },
  "mark": {
    "type": "rect"
  },
  "config": {
    "legend": {
      "titleOrient": "right"
    }
  },
  "encoding": {
    "x": {
      "field": "timezero",
      "timeUnit": "yearmonthdate",
      "type": "temporal",
      "axis": {
        "orient": "top",
        "format": "%Y-%m-%d"
      }
    },
    "y": {
      "field": "model",
      "type": "nominal"
    },
    "tooltip": [
      {
        "field": "model"
      },
      {
        "field": "timezero",
        "type": "temporal",
        "format": "%Y-%m-%d"
      },
      {
        "field": "# rows"
      }
    ],
    "color": {
      "field": "# rows",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
Did you read about how times can be in local and UTC time? This sounds like one of those instances where data is parsed differently from how it's interpreted.

**Comment by jakevdp** [comment]
You can see the issue directly in your javascript console:
```
> new Date("2011-10-02")
Sat Oct 01 2011 17:00:00 GMT-0700 (Pacific Daylight Time)
```
You need to use either a full ISO 8601 date string, or it will be parsed as UTC.

**Comment by matthewcornell** [comment]
I had a look, but not carefully enough - sorry about that. I'll study it more carefully. Thank you.

**Comment by domoritz** [comment]
No worries. I also have to look up how dates work in browsers every couple of months. The last section in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Description is especially helpful. 
<img width="730" alt="Screen Shot 2020-09-21 at 14 15 31" src="https://user-images.githubusercontent.com/589034/93822328-e9c88700-fc14-11ea-8db4-54b7f7ca3a97.png">

**Comment by matthewcornell** [comment]
Thanks for that pointer, @domoritz . I see that they call what I'm working with "date-only form" dates, not datetimes. I see that the browser converts dates to datetimes, and therefore needs to be passed a timezone or infer it, and that:

> When the time zone offset is absent, date-only forms are interpreted as a UTC time

That's surprising to me. After some research I learned that Python `date` instances (which is what comes from the our Postgres database) have no timezone information, and that, in fact, dates as a concept don't either. From https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/#troubleshooting :

> A datetime represents a **point in time**. It’s absolute: it doesn’t depend on anything. On the contrary, a date is a **calendaring concept**. It’s a period of time whose bounds depend on the time zone in which the date is considered. As you can see, these two concepts are fundamentally different, and converting a datetime to a date isn’t a deterministic operation.

That's why I was confused about vega-lite's behavior: A date is a box on a calendar that should require no interpretation.

Actually, I still feel that way, but I now need to figure out a work-around. Do you have any suggestions? I'm still working this out... Thank you.

**Comment by jakevdp** [comment]
I spent a **Lot** of time in Altair trying to make the interaction between Pandas dates and Javascript dates sensical from the perspective of the user. If you're generating data in Python and figures in Vega-Lite and are getting hung up on timezones in date conversions, Altair might be the remedy you're looking for.

**Comment by jakevdp** [comment]
But concretely, if you serialize your dates in full  ISO 8601 form (e.g. `'2012-01-02T00:00:00'`), javascript will treat them as local dates and your code will work as expected

Alternatively, if you don't want to change the format of the input dates, you can use the UTC equivalent of your time units; i.e. change ``"timeUnit": "yearmonthdate"`` to ``"timeUnit": "utcyearmonthdate"`` and it should work as expected.

**Comment by matthewcornell** [comment]
Thanks, @jakevdp . I tried your two suggestions but got the same off-by-one results. Here's a screen shot where I show the actual string passed to vega-lite in the tool tip as "timezero_str". "timezero" is what vega-lite is working with after reading the data.

![tz](https://user-images.githubusercontent.com/1034007/93910162-b5190600-fcce-11ea-9e0f-d21f1e16d21e.png)

I gave this problem some thought last night, and I think that being required to add a timezone to a date-only date is artificial, which is leading to incorrect results. (I mean this with no disrespect!) UTC or timezone information is simply not in my data, and should not be relevant. As an example, here's a GitHub profile activity chart:

![github](https://user-images.githubusercontent.com/1034007/93910202-c104c800-fcce-11ea-9603-4076e2a671b2.png)

Hovering the mouse shows a date, which is independent of any timezone. The source data looks like this:

```html
<rect class="day" width="11" height="11" x="16" y="0" fill="#ebedf0" data-count="0" data-date="2019-09-22"/>
```

Just ymd, no UTC. My current (possibly naive) thinking as a user is that, like Python and Postgres, vega-lite should treat dates and datetimes differently, independent of JavaScript's `Date`'s requiring date-only concepts to have timezones. I'm not the only one to discover this problem. For example,

- [How to represent dates (without time) and times (without date)? #3455](https://github.com/moment/moment/issues/3455): This question has sort of been asked before many times. We've never really had a good answer. The API simply doesn't model the JodaTime sort of thing that you are asking for. ... But fundamentally, a moment is tied to an instant in time, in the same way that the JavaScript Date object is. If you want a JavaScript API that models the entire domain of date and time, look to the js-joda project.
- [Manual | js-joda](https://js-joda.github.io/js-joda/): Popular javascript date libraries like moment or date-utils are wrappers around the native javascript Date object, providing syntactic sugar. The native Date object always consist of a date, time and a timezone part. In opposite to that, js-joda is a standalone date and time implementation. .. LocalDate represents a date without a time and time-zone in the ISO-8601 calendar system, such as 2007-12-24.

Am I missing something?
![tz](https://user-images.githubusercontent.com/1034007/93910134-ab8f9e00-fcce-11ea-88a7-5100568716f8.png)

**Comment by jakevdp** [comment]
Two things:
- If you're going the route of using a full ISO 8601 date string, I wouldn't add a timezone. I'd just use the full string (like `2012-01-02T00:00:00` instead of `2012-01-02`. Javascript will parse this as local time, and vega will display it as local time unless you explicitly specify UTC.

- If you're going the route of using utc time units, you'll need to use them everywhere, including the tooltip.

**Comment by jakevdp** [comment]
Here is my first suggestion working properly, showing the correct tooltip: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoBG2VxBaFWygQABADM2AJzhQkETHdPnLSzDQIcABecM5sVgBMAAwAjLH8sdH80ZEAKtHRqJnZ0YogAMR24QDuBqgAbJEAvgomZhZWyjb2Tq7unt4NfiABQaHhUXEJSSkAnBlZOZn5RaXlVdUAurUgyM4A1migmACeOHBW7Zggq1ByDjRk2yCC5HCyyjcBmHcA8s40Dyfon2RYp1WD3OyhosmumhAAA8bpcLE90H0QmEIv5AnAAKqyOhWXZwJDOUyyeiqTCHfz7Q6IxA4Fw6fJIKE0cqgFxfYlWTBsHD5NrIH4gACkAE1+IKEGKntVVrtYV9BAi1t18nsDlZZGwEGD6asuWxBAEeahjCA4QqrD5GrVQGbFUiBqjepTOTS6T0+WorCKxRLBVK6qb5Yq5mwyqclkpzoIXHL4VYQ2GKWr0ABHBhIYl0NQ0UiA6pAA)

**Comment by matthewcornell** [comment]
Aha: Leaving off the "T" makes it work - much obliged. I appreciate the remedial tutoring 👍 . Apologies for not creating a demo first thing.
