### ISSUE TITLE
Repeated layers (areas or lines) can't be stacked

### ISSUE THREAD

**Issue by john-guerra** [vega/vega-lite#6891]
The following will produce a non-stacked area chart, even if we explicitly add the stacked property. 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "url": "data/movies.json"
  },
  "repeat": {
    "layer": ["US Gross", "Worldwide Gross"]
  },
  "spec": {
    "mark": {"type":"area", "opacity": 0.5},
    "encoding": {
      "x": {
        "bin": true,
        "field": "IMDB Rating",
        "type": "quantitative"
      },
      "y": {
        "aggregate": "mean",
        "field": {"repeat": "layer"},
        "type": "quantitative",
        "title": "Mean of US and Worldwide Gross" ,
        "stack": true
      },
      "color": {
        "datum": {"repeat": "layer"},
        "type": "nominal"
      }
    }
  }
}

```
[Vega editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S7XBxw1aUIKQBPONrQBtEACqAMoABADi2mwQEIogAOpsusoA7jTKcOGR0SAAunYgEE5QriDI2gDW+kgOKEpwslBsyjSyZCUAHiVMLWiY2gxwSgBm5oLK+gCSALIAIgBCIQBKai1tSpgeTvoAjgxIsph0K6Qg+R4lSGRkDhSYcPoIzvLDo+OaIA5OLujuXj75Gy26F2+0O6kOJ3WdEE93QUyeITYQxCwRC+2UIQSSVS6UyURi+UagkSJVUmAYCBKn2cmH0v28p3Wm1hIFkbAQLSQehsPJsQA)

[See here an example with the Vega-Lite API and without binning](https://observablehq.com/d/fd8c0c1acf1144f8)

```
vl
  .markLine({ tooltip: true })
  .encode(
    vl.x().fieldT("fecha"),
    vl
      .y()
      .fieldQ(vl.repeat("layer"))
      .stack(true),
    vl
      .color()
      .datum(vl.repeat("layer"))
  )
  .data(data)
  .repeat({
    layer: [
      "pruebas_por_dia_positivas",
      "pruebas_por_dia_negativas",
      "pruebas_por_dia"
    ]
  })
  .render()
```

**Comment by domoritz** [comment]
As noted in https://twitter.com/kanitw/status/1308442961730916352, this is by design. The layer docs mention that layered are superimposed (https://vega.github.io/vega-lite/docs/layer.html). You also don't get a legend when you layer, which is why the long form is preferred when mapping to color.

**Comment by john-guerra** [comment]
Thanks for the clarification. If anyone faces this, try folding the data first:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "mark": {
    "type": "area"
  },
 "data": {
    "url": "data/movies.json"
  },
  "transform": [
    {
      "fold": [
        "US Gross",
        "Worldwide Gross"
      ]
    }
  ],
  "encoding": {
    "x": {
      "field": "IMDB Rating",
      "type": "quantitative",
      "bin": true
    },
    "y": {
      "field": "value",
      "type": "quantitative",
      "aggregate": "mean"
    },
    "color": {
      "field": "key",
      "type": "nominal"
    }
  }
}
```
