### ISSUE TITLE
exported types for 4.16.2 are missing some files

### ISSUE THREAD

**Issue by alexwizp** [vega/vega-lite#6900]
After updating `vega-lite` lib to version `4.16.2` I see the following issue during types checking

![image](https://user-images.githubusercontent.com/20072247/94248730-86e23300-ff27-11ea-92c6-bb12b13020cc.png)

It looks like the file being imported is only types, which probably means that the ./impute import should be removed from the file or the module should be left on the file system.

![image](https://user-images.githubusercontent.com/20072247/94249042-fbb56d00-ff27-11ea-9a16-bed4096db171.png)

**Comment by domoritz** [comment]
I am aware of this issue. The problem is a bug in https://github.com/ezolenko/rollup-plugin-typescript2. For now, please hold off on updating while we work out this issue.

**Comment by alexwizp** [comment]
@domorirz 
We still have some issues on `vega-lite` side on `v4.16.7`

![image](https://user-images.githubusercontent.com/20072247/94416882-11c16880-0188-11eb-8782-f695a48b944b.png)

**Comment by alexwizp** [comment]
Yep, vega-lite: **4.16.7** and **Typescript** version: **4.0.2**

**Comment by domoritz** [comment]
Did you enable `"resolveJsonModule": true`? I am not seeing any problems in the Vega editor (https://github.com/vega/editor) anymore. Do you have a simple repro?

**Comment by alexwizp** [comment]
@domoritz sorrry, my question was more about 

```
node_modules/vega-lite/build/src/vega.schema.d.ts:34:19 - error TS2344: Type 'null' does not satisfy the constraint 'SignalRef | ExprRef'.

      34     value?: Value<null>;
```

**Comment by domoritz** [comment]
Do you have strict null checks enabled?

**Comment by alexwizp** [comment]
`"strict": true` property is on
our config: https://github.com/elastic/kibana/blob/master/tsconfig.base.json

**Comment by domoritz** [comment]
I see. That could be it. We don't have it enabled (https://github.com/vega/vega-lite/blob/master/tsconfig.json#L13) but we could (and should) fix the problem you are seeing.

Let's move that discussion to https://github.com/vega/vega-lite/issues/6912.
