### ISSUE TITLE
helpful error/warning logs for choropleths when a `transform` `lookup` fails or `feature` not found in `topojson`

### ISSUE THREAD

**Issue by eflister** [vega/vega-lite#6904]
raw `topojson` is hard to look at and there aren't a lot of tools/docs available.  right now you do issue a warning if one tries to use a `feature` that doesn't exist in a a topojson file, but it would be helpful if the warning also listed the available `feature`s you did find when parsing the `topojson`.

similarly, right now, a `transform` `lookup` to join a `topojson` feature with some data fails silently if the field is not found in the `topojson` -- the error or warning should list the available fields.  include nested fields (under `properties` for example).

for example, this is the only `topojson` of oregon zip codes i could find:
https://raw.githubusercontent.com/OpenDataDE/State-zip-code-GeoJSON/master/or_oregon_zip_codes_geo.min.json
but i can't get any helpful log info telling me why it is failing.  afaict, it doesn't explicitly list its single "feature" (zip codes).

also, include default data sources for common features including zip codes, and properties including population and elevation.  finally, include basic map navigation features (translation, zoom).

i know i'm getting expansive, but it would sure also be helpful to offer basic+common geo computations -- `area` and `population` being most obvious, and best practice normalizations (eg by area and population).  building in these 80% use cases would go a long way to making `vega-lite` the obvious go-to choice for online interactive choropleths.

**Comment by domoritz** [comment]
Should be moved to Vega since Vega-Lite never sees the data.

**Comment by eflister** [comment]
ok thanks i moved it to `vega` (see mention above), closing...

**Comment by domoritz** [comment]
Thanks!
