### ISSUE TITLE
tooltip causes aggregate fail

### ISSUE THREAD

**Issue by eflister** [vega/vega-lite#6920]
i made a line graph following the method from https://vega.github.io/vega-lite/examples/interactive_line_hover.html to label each line.  

![image](https://user-images.githubusercontent.com/366563/94880156-12bbf980-0417-11eb-9579-59953b0749f9.png)

it works as expected until i add a field to the tooltip.  then, instead of the aggregation eliminating all but the last label for each line, labels show up for every datapoint.

![image](https://user-images.githubusercontent.com/366563/94880029-bce75180-0416-11eb-9316-8eb19fbdf71d.png)

https://gist.github.com/eflister/d743fa9ef6641d26a1d09c41265aba1c
note that removing the `pct` field from the `tooltip` in line 4611: `{"field": "pct"}` yields the expected aggregate behavior.

**Comment by domoritz** [comment]
Tooltips add another aggregate dimension. If you don't want that, you need to provide an aggregation function.

**Comment by eflister** [comment]
is this documented anywhere?  i don't see anything on https://vega.github.io/vega-lite/docs/tooltip.html

>  If you don't want that, you need to provide an aggregation function.

i'm new, i don't know what you're referring to.  is it this?  https://vega.github.io/vega/docs/api/view/#view_tooltip

i'm using `vega-embed` so i guess that means i'm already using `vega-tooltip`...

**Comment by domoritz** [comment]
A tooltip will be categorical by default and therefore be used for the group by. The aggregate I was referring to is https://vega.github.io/vega-lite/docs/aggregate.html. That page also mentions that "all fields without aggregation function specified are treated as group-by fields". I hope that clears things up. Let me know if I misunderstood your questions or issue.

**Comment by eflister** [comment]
the aggregate page doesn't say anything about tooltips.  would you mind pointing me to a worked example of what you're describing?  i don't see how to "provide an aggregation function" other than what i did normally (`max`/`argmax`).  it seems like it would be a really common situation that people would run into tooltips breaking their aggregations, shouldn't the docs have to discuss it specifically?

**Comment by domoritz** [comment]
You are right that the docs don't explicitly mention that tooltips. "all fields without aggregation function specified are treated as group-by fields" says that all fields without aggregate (which includes tooltips) are treated as group-by fields. 

Here is an example to demonstrate the difference. 

Example without tooltip: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqR5SGRk6nyYcOUIcH4gTSAbE1Mzc+gAssFqAPrh6l+AHEkFE5Ostjd0HsDnRTDQTkozhcrlCQHcHg0sUA)

Example with tooltip without aggregate: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqR5SGRk6nyYcOUIcH4gTSAbE1Mzc+gAssFqAPrh6l+AHEkFE5Ostjd0HsDnRTDQTkozhcrlCQHcHk9MGw2IIdDhXtNZgslp5vOpHg0GkA). Notice how the point is now grouped by the `Horsepower`. 

Example with tooltip with aggregate: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqR5SGRk6nyYcOUIcH4gTSAbE1Mzc+gAssFqAPrh6l+AHEkFE5Ostjd0HsDnRTDQTkozhcrlCQHcHk9MGw2IIdDhXtNZgslp5vOpTudLhRrrd7o0Gg0gA)

I agree the tooltip docs could be more explicit. I'll change https://vega.github.io/vega-lite/docs/tooltip.html to address the issue.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/pull/6921

**Comment by eflister** [comment]
thanks for all your attention on this.  sorry if i'm being dense, i'll have to sleep on it and see whether i get it in the morning.  but right now the updated doc still doesn't make sense to me.  i would: 

- add sections in both the tooltip page and aggregate page, containing the example you sent showing that to have a tooltip on a mark representing an aggregate, the tooltip has to restate the mark's aggregate encoding, or else it will override/destroy the aggregation.  also explain why this design was chosen -- as it stands, i don't see why it is acceptable -- it seems obvious the tooltip should reflect the mark's encoding, and totally unexpected that it would override/destroy it.  marks and their encodings feel much more fundamental -- a tooltip is just info you can get about an encoded mark, not something that should alter/override/destroy it.  if there's a good reason for the design, it would help users a lot to understand it.
- clarify that sentence on the aggregate page ("all fields without aggregation function specified are treated as group-by fields"), to explicitly mention that this includes _fields in tooltips_, _even if_ those fields _are_ aggregated in the encoding.  when i read it as it stands, i see "all fields without aggregation function specified," and i think "that doesn't apply to me, i have specified my aggregation function for the field in my encoding" -- it doesn't even occur to me that it could be suggesting _restating_ it in a _tooltip_.  and the preceding sentence isn't true:  "If at least one fields in the specified encoding channels contain aggregate, the resulting visualization will show aggregate data."  if a tooltip comes along and does not restate the aggregate for that field, then we will _not_ show aggregate data.  again i think an explanation of why this design was chosen would really help.
- the new text: "encoding a field without an aggregation as a tooltip will result in the field being treated as a group by field." -- when i read this i think "that doesn't apply to me, my field does have an aggregation, right there in my encoding" -- it doesn't even occur to me that it's trying to tell me to _restate_ the aggregation _in the tooltip_.  and it would help to emphasize that being a group by field is mutually exclusive with being an aggregate, despite the encoding having specified aggregation.  so i would write "unless the tooltip restates the aggregation specified in the encoding, it will override and destroy the aggregation."

anyway, i don't think this actually clears up my original problem: my tooltip is defined on an outer encoding, intended to show the zip code and infection rate on any given date (equivalent to the ticker symbol and stock price on any given date in the example).   in a separate, inner layer, i add the aggregates on date and infection rate to find the location to put the label.  so my outer tooltip encoding is destroying the inner aggregate, but it can't itself be aggregate because i want tooltips to show date-specific infection rates, not the latest infection rate.  my understanding and expectation is that inner encodings override outer ones, not v/v.

so the best example to use would be how to add tooltips that show stock price for each date in the ticker example.

again, sorry if i'm totally missing something.  i really appreciate your help clearing this up.

**Comment by eflister** [comment]
> so the best example to use would be how to add tooltips that show stock price for each date in the ticker example.

alright, i played with this.  i think the doc (on both tooltip and aggregate docs, perhaps layer and encoding docs) should include the following example.

consider placing the `tooltip`

```json
      "tooltip": [{"field":"price"},{"field":"symbol"},{"field":"date"}]
```

in one of the positions `<A>`, `<B>`, or `<C>`:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/stocks.csv"},
  "encoding": {
    "x": {"field": "date", "type": "temporal", "title": "date"},
    "y": {"field": "price", "type": "quantitative", "title": "price"},
    "color": {"field": "symbol", "legend": null}
    <A>
  },
  "layer": [
    { 
      "mark": "line", 
      "encoding": {
        <B>
      }
    },
    {
      "mark": {"type": "text", "align": "left", "dx": 4},
      "encoding": {
        "x": {"aggregate": "max", "field": "date"},
        "y": {"aggregate": {"argmax": "date"}, "field": "price"},
        "text": {"field": "symbol", "type": "nominal"}
        <C>
      }
    }
  ]
}
```

only `<B>` currently works as expected.  `<A>` does entail `<C>`, but the natural expectation of `<C>` is not the current behavior -- that `tooltip` silently overrides and destroys the `aggregate`.  instead, its only interaction with the `aggregate` should be the information displayed in the tooltip, which should be aggregate.  i consider this a design bug, but if an argument can be made that this design is correct, it should be explained in the docs, along with this example.  

furthermore, when specifications contain contradictions that are currently resolved by silently overriding/destroying, there should be compile- or run-time errors or warnings.

**Comment by eflister** [comment]
?
