### ISSUE TITLE
Symlog scale should use greedy label overlap

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6934]
See https://github.com/vega/vega/issues/2914. When the scale type is symlog, we should set label overlap to greedy as well.

**Comment by baogianghoangvu** [comment]
Hi @domoritz . Thanks a lot for sorting the original issue so quickly.

Regarding this issue, would you mind if I give it a try?

**Comment by domoritz** [comment]
I would be delighted. We are always happy about contributions from the community.

**Comment by baogianghoangvu** [comment]
Thanks a lot for your kind words. I was a bit worried since I'm not familiar with typescript.

I've made a PR for this. Hope it helps!
