### ISSUE TITLE
Parsing dates can fail for per-view data

### ISSUE THREAD

**Issue by simonchatts** [vega/vega-lite#6944]
Thanks so much for Vega-Lite!

If I use a date parser like `"date:'%y%m%d%H%M'"` with per-view data, then the parsed dates end up very close to 1 Jan 1970. The same parser and data works fine it it's just the main data.

[Here's a Vega Editor example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQgpAE84AJzQBtUMg0BrNCCZItSuLKhsAJjVlk0oAB5OQAMxpxBN4zaSYcIogmKo4QeiBCDhsGkiCIAC+Sqpunt6+6MTxAIzBoeHGAI4MSLKYdAE0pElK1oKxbv6YDAjG2YJ5id0KemZG6KbmIJbWdg5urqig6T5+AUFKBREhiDFxCckgqdMeXnNZ8QBM+WErJWUVmFU1W-WNu82t7cdJW80oux0McBA6oM0VkcAAw5YHAgAcRxBJyUHROqBByQBC2MILBkOhwIAzMF4WgjtjkSBAWjQeCoSCxHjXoiAKyJAC6SncsWQmDcODMEAiKMC80CqAA5ABSVQihAimwigASIoAskK3t1mSSAp9QN9fv81fz0OiKVjYSAOnlUGDiaT9eTMSDcXDcmgckTerqgTbKcDqQ7Ok6GarWRp2Zzuby3QK4MKxRKpbKFUrut0gA) - there are two layers, both with data around 8th October 2020. But the layer-specific data ends up being parsed back near the epoch. (If you [isolate just that layer](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQyAE4BrNCCZIVikHFlQ2AExqyyaUAA9LIAGY04g45uNJMcPZgCeOT+g8EHDYVJEEQAF8lb1sHJxd0YjCAJi9ffxAARwYkWUw6dxpSSKUjQRDbN0wGBE0kwVSIqJAqlFRQeoY4CDQAbVAqjOSABgBGYeGADmSR1KV61NQRqIH3IbGJ6ZGAZj0FtGTtlZa1zRHxqZnhsT2Ug4BWCIBdJTsQ5ExbHB0If1WPVxrVAAcgApN5QQhQcZQQAJUEAWWBkSaESAA) then it parses and displays correctly.)

**Comment by domoritz** [comment]
In the Vega spec, I found that data_1 doesn't add the parsing. It must have gotten lost in optimization of the dataflow somehow. 

<img width="802" alt="Screen Shot 2020-10-08 at 14 40 35" src="https://user-images.githubusercontent.com/589034/95516536-3bdb0d80-0974-11eb-8e39-4f685a570e73.png">

**Comment by domoritz** [comment]
Moving the data into the first view of the layer also seems to work. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQgpAE84AJzQBtUMg0BrNCCZItSuLKhsAJjVlk0oAB5OQAMxpxBN4zaSYcIogmKo4QeiBCDhsGkiCIAC+Sqpunt6+6MTxAIzBoeHGAI4MSLKYdAE0pElK1oKxbv6YDAjG2YJ5ickgzSiooB0McBA6oM0RIABMAAw5MzMAHFOzU8EdeajzyeMBk7PzSyszAMzruWg5Jzu9e8YHC8uzYuedlwCsiQC6Su6xyJg3DgzBAIrtAn49qgAOQAUlUsIQsJssIAErCALLQpLdG76IzoUzmECWax2BxuVwDDxeHyQiFKAqTKIxOIJHqpanpOlZeJrRlhSYlMoVTBVGo9eqNanNVrtPk4pR9NxDEZjW4Q9API6rV5rVCzG4Te5zR7HM5KDr6qbXBTg-amnUzF6WhUGz4-Dz-AJAkFgjWTCYw+GI5FozHY3HfRJAA)

**Comment by simonchatts** [comment]
Thanks for the super-quick comments!

**Comment by domoritz** [comment]
in a debugging session with Donghun Cho, we found the issue and fixed it in #7498.
