### ISSUE TITLE
possible bug - header orientation not working unless specified in config

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega-lite#6960]
Hello all,

In the current version of VL (or the version that the editor uses), headers do not move to the bottom of a chart by specifying the following in the column encoding:

[VL example
](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLRsAnBMxhMADjASArACM7AJjosAjMZZgYdgGyuJFmYW7nYgciAaCgBOANY6dtEg3JhQkHQkSKg8ADYQUaqEAJ4ADtrIahAaJArZSSDwmNl0OoWYieGQ2aQaUAUlZRVV6rXcDU06lHCE2tyMbXSY+VnEhNmYAPJRWETxEISElXXZCnaNm9vi5XZ7Bxph4QAefaU6eenDdWPN5a2J3AoPOCUFBkbLZcKFZ4DACOpAURCmSjgaBmIAUCAQUUwCCUA0o3U+WHGPyJzVk3AAJJQwHNIjoxIRipRkAB6FkonEAOgQU0YpDsnLgEBZ1NpCnZ2IU+myU0w7JYnIsnNcnIAVpRoHU9ApKJhCMCstrDCYzJZrPYnC53EZPN4-AEgiEUABtUCFUkoRwAdm4aGiWCKOgAsvCaaQtipuL8lq4TK5uJNpjoAKpQZGLROFAAEADFonc5G6PcgWEqLD4Kz6QH6tnrIeUQ6k+RG6tGULGJPGQImBtQdWYVIWQO7Gt9vZyWBIpyxff668HQ824JHh20Y3GE7Lg3ktsChyPiRIjJyTFOJLPa4GG4vw8vW2v2xvu1vygBhKIQCAxSgHXr74sSI4J4Vj4VY1gG9YgI2YYtlGD7IB2XY9joADiUTwnQWYAEoKMU9B7pwRajp6SpGCBYFzleUE3rBq6JAhT7IeUAAipBdEwYSEcOxaTpybAgT4F4Qahxx2B+vRwfRiGbkm5SpumUSZrm+acURxI2DYnKOEJ87lChonifeUmMS+IB9rqYCDlxB5jkqXrkTpVH6SchmSeunYyQMQY7kCqnccRyABMqZ7ntWlGQc5Ymam5j4ec+skgO+n7fr+fk2Z6x7+GejkRQZ0V0e5SGmWhGHYbh+FpcWjjHgJFGXrlLn5W2DFxUxICsexzD-gFtjBdlYX1ToADKfpQBqyhGYVnkpmmKKKVM2Z5lEBbWTxXqciFoXgbpIAjfC40rs10nxb2-aWZVAWOJp9mVjlw2jQdk2xUVCXeVEu4XcS7ATg5A3CeUe1jXsh3wcdbVJV+P6at1xLVZytV3QDD3A09LUvQMJVQJhOF4XQBFqWO12I7tyMTTFaPTSxbGkBxMPfEeJ7EwAao0KLiOTYOmfJc1KUtK0EygNhsFpIXM6zeqo5zCXmQOn1jj4fVTmL2Rs5LJmvT5+P+V9Kqbcrqsc+rAwQyl0OrZdEh8aLf07SzKsS4brXFehWNlbjWvpcgjgK1t4U6HbBsFc9lPtdTtPm4eCs2AJxMACpYnYcBq07CXcxmC3KctcsoD4lsWP121UfHmCJ8n6M6DL5106wls3aBccJ0njvlw2mvZyWCunkrNtF43ZchybUN-hHY7HnXdX-SAxel83IeY9j5V4+3U4ntbheQdPTdBxTJ06B1NNdSPNdab9686AAchAnJZiwNhev3u9ybN6dFJn-Pa98NhKl2Z-lJf1+33vrPR+ZkzpWQFl7OyxN-43zvg-Nqb0PrVxLJpBGPdIIwMAfA0yg9UrIMAsqU+fs-5X1gUA7eUsMYuwXu7ZeltBLoIvqQrBwC2r73DhAiQCsGG-xAJgnwjhsGp2fvNV+fN24+GurdRhJCAECKEadCy4CP6SGFlw6RvD+GCNYaZRBvlkGlk5NHEC0DmHyJ0QlXBZsIGOAVF3GcMi+FmO0RQo2qFqFuwqsgxw39TFyJcUdNxVNOrLyAuPYmAAFNoqwMIKJmgpXmKkDFKmMRWSJ0TjhYzieUSuyjPZw3LBo4hIAolKEyc0CxXk24GJVDw4ppSYlZMqToKxw9OEKgnjtBp5TskgHnp4pe+DtKOO6bE5pwSD7t1sfDIhg1ZE3y9DYXpadRGLSSUfDunJwmOMwYs3puSplATqXMpxAC9njKgtUjZLAFQ-2KbspZFzWnt1jFsvxCzHmuJTlQ0qOMvEbJXvxExOzmHnK+S3UOIT8HHl9ic2g1JoCTCgFmGBARlkiMSVnZBX9FTE3hQQJFKLSFoouQc7xx4WCzMnvixFJAiXXxJeCkOeiPY8WPIU+ujiaVjTpaiiwvTnn4IVJSopcKgQEt5cS-lFz+l-MGQC2peLxW0uRXy3p7DD42M7sTaCS4QbGUAiHFZmL36exXiKzlvDdW3n1e5YZbUyUAoVOotJjjrW0UCYakBLLQnAVFZPd1d5Hb2pwR+SGeCNmOCAllbuVqaJBq+SGhKsrF6ssukBVJnSqKBttbFJNAwNXLwVhYYmkVXKJqNRijO4j8HrS9GvYpZamqgxMPmiuYDl6aRjbCyeTaJIVu9VcrVhD-U7T7cnNtb4w2mzaSohCwqG0nPHcGueHi5VpthppDlWaGpRX7Z6ydkLJnePWpOacxNAaPRXSA411b1mcJSRe0muaWqHsdZwzSbBF2T0vSja9CCh1zscMLXOBdim-rJgO8G06h4vO4d+naEGX0dkPSm2h3igKOAQ1RJDE6Q6Fu8cW-WDsoNcyrWI+9c6JCnuI+zUj0sO34LLNhyCAcSMHuZYBs1QEgWut4WxujHGQGCoBZhlj-txaCZbV6tqaH-k2KAhandEn7ZSYNYegjkbjy8eU+UTeeGb3kbWVi65x4sOxuKfp-9pl31zspfDcTem+7WY1u9fR1yVT5zAycqz9HjYwYjTYkDjmp7Ob8+435qbl4gYbiXLeQm2Fh01UBhWZ6JAOM0cwuBLmBi3ooyZiBLBMPvJYeFnJjHrmWxsGeDL9ysvkIS7orjAFnUhcwdlsriUAvWLna8pTJWOuNeTWuqLGG3kgoAYN6TGmktTM0pmkr5jOt5eM6aniHTFsBOmyHWznsWC6dOTfJbQ2qluY3fTYW1XvOTy0QZ6DyVYPINeUYTbd3naRfQ5GjNr2ct71m94pUOn0llLGctozb8i1W2u10jJoOTvtqUe3XiwzeGjKaZ1n13jNLmYsyctHFTOsieHds1HsP0fw70iNz7nDdZUphyD8n22QGac4VwCbHy3vCISXegrdmVTe1HVRB5nPFGywMQqHHPadrC9+63M7vru0lbBRTrrD3Au9ex210FnyVdyflTY9aLqDsy86yzqjJauXKp5aqqVIv4k8x52tgKOLXB06otywlarZegMRwY9arvBeQQ95Khl0qMfNZ6ppF7luEXW-pVmRlKuidAZA27oPVvPe2+93r87GUNoheDzb0PduJm0wALqyCAA)

```json
"column": {"type": "nominal", "field": "site", "header": {"titleOrient": "bottom", "labelOrient": "bottom"}}
```

This is described [here](https://stackoverflow.com/questions/64357120/recommended-way-to-move-headers-to-the-bottom-of-subplots-for-grouped-bar-charts) on SO. If `labelOrient` is specified in the config, everything works as expected (thanks to Klaus Eckelt for discovering this)

**Comment by kanitw** [comment]
Thanks for reporting -- Fixed in https://github.com/vega/vega-lite/pull/7150
