### ISSUE TITLE
Consistent application of parameter expressions for axis (and other) properties

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#6962]
Since 4.16, it has been possible to provide expressions for many properties, but not all of them. For example, for almost all  [general axis properties](https://vega.github.io/vega-lite/docs/axis.html#general), an expression may be provided. 

However some, such as `offset` and `zIndex` do not have `ExprRef` options in the schema. It would be good to be able to apply expressions to all these properties, not least so it does not require consultation with the API documentation to discover whether it is possible or not.

Note also that the axis `offset` is actually implemented, but not recognised in the schema or documentation. Not sure if this is because it is still at the testing stage, or it was overlooked when adding experimental expressions to the schema.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "params": [
    {
      "name": "axo",
      "value": 0,
      "bind": {"input": "range", "min": -10, "max": 10, "step": 1}
    }
  ],
  "data": {"values": [ {"a": 1},{"a": 2}]},
  "encoding": {
    "x": {
      "field": "a",
      "axis": {"offset": {"expr": "axo"}}
    },
     "y": {
      "field": "a",
      "axis": {"offset": {"expr": "axo"}}
    }
  
  },
  "mark": "circle"
}
```

**Comment by domoritz** [comment]
Thanks for the issue. Yes, the feature is pretty new and we are working on ironing out the kinks over the next few releases. In general, there are some limitations in Vega for what can be a signal and we may also have overlooked certain types so that the schema isn't correct yet.

**Comment by kanitw** [comment]
Offset should support expression like you mentioned, I'm fixing this in #7148.

Given the limitation in Vega, I don't think we can make all properties support expression. 

I'll close this issue since the fixable part is now fixed.
