### ISSUE TITLE
Selection filter does not work with and predicate

### ISSUE THREAD

**Issue by Cheryl-Neoh** [vega/vega-lite#6981]
```
      "transform": [{"filter": 
        {"and": [{"selection": "select"}, {"selection": "slider"}]}
      }]
```

This does not work, it only works with one selection, like so 

```
      "transform": [{"filter": {"selection": "select"}]}
      }]
```

I've seen a post on StackOverflow that encountered this as well, but there was no update.
https://stackoverflow.com/questions/54295345/multi-cross-filtering-in-vega-lite

Edit:  I had this issue when creating a choropleth map, where I created two categorical filters (slider and options menu). The selection of the filters only works for the data that is all the way below in the dataset. The choropleth map shows for that selection only and not others. In the data viewer, other selection shows that the table is empty, although it's supposed to contain the filtered data.

**Comment by arvind** [comment]
Thank you for filing this issue @Cheryl-Neoh, and apologies for the slow response. Yes, we appear to have had bugs with how selection predicates were being generated when composing selections together. This will be fixed as of #7155, which I've verified addresses your issue as well.
