### ISSUE TITLE
Disable header like axes/legends

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6985]
One can remove an axis by just setting it to `null`. The same should work for headers. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABJnVxBwiIaZJ1h2DcyGIMNgHcasssfiGAqgGVDHDYcBkEkHTlDZRoIExomBkjZQzYAM0MkMjhDMnU2BjxM2WVcuBK4Ww9DACYABgbKRRUIlFRQBnVBNBbMJAJg0PDkqRl5AF8lEyRZCDS2dQQ0AG1QNJpBTEqe5QiGBEoATzgbQwBeM9qGupBJ0CgkQSgwiLgdvYOIOAAPc8uawwAfkMAHIAGKIR5wEGGVCggCyUJBzSQEB62Qq6luAF0lO5lPQ0KA4nAcGgAIwAdkmIGQ6gA1j1rFilOUoGwYp4iSB8q5ueszMp0eVVCyMCdRWhZGFBDTDtysnk+FsehB9s0BYIhegcHAQoI3lM6AaeoMXslbkpvvyaIKelk3jT2YIFja7egMZKlNAodz1DNsisQABiABslIArOSAJwAZmawYeAA4k6HySBseMs+MgA)

**Comment by kanitw** [comment]
Duplicate of https://github.com/vega/vega-lite/issues/5033
