### ISSUE TITLE
Pie chart - labels misaligned

### ISSUE THREAD

**Issue by mattlangeman** [vega/vega-lite#6987]
When creating labels for a pie chart, I am having issues with label alignment. It seems to work for nominal values, but not for quantitative values. I ran into this issue when trying to add percentage labels to the chart.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A pie chart with attempt at percentage labels. Labels are misaligned",
  "data": {
    "values": [
      {"category": "Category 1", "value": 4},
      {"category": "Category 2", "value": 12},
      {"category": "Category 3", "value": 8}
    ]
  },
  "transform": [
    {
      "window": [{"op": "sum", "field": "value", "as": "TotalValue"}],
      "frame": [null, null]
    },
    {"calculate": "datum.value/datum.TotalValue", "as": "PercentOfTotal"}
  ],
  "encoding": {
    "theta": {"field": "value", "type": "quantitative", "stack": true},
    "color": {"field": "category", "type": "nominal"}
  },
  "layer": [
    {"mark": {"type": "arc", "outerRadius": 85}},
    {
      "mark": {"type": "text", "radius": 100},
      "encoding": {
        "text": {
          "field": "PercentOfTotal",
          "type": "quantitative",
          "format": ".0%"
        },
        "color": {"value": "#000000"}
      }
    }
  ],
  "view": {"stroke": null}
}
```

[Here is the above example in Vega Editor](https://vega.github.io/editor/#/gist/b966b71fdf6dbab888c6dd46b7a25811/vega-lite-pie-with-percent.json)

[Another example of misalignment with 4th category added](https://vega.github.io/editor/#/gist/78874c0da01b2e267707479d6475eff5/vega-lite-pie-chart-misaligned-lables-2.json)

[An example that works with nominal values](https://vega.github.io/editor/#/gist/cc5b9ea00e1f2df4428a380653b8f468/vega-lite-pie-chart.json)

**Comment by domoritz** [comment]
Thanks for the bug report. Could you look into how we might have to change the generated Vega to fix this issue?

**Comment by mattlangeman** [comment]
I was able to track this down a bit. It seems the issue is with using a color encoding with the label text while having a quantitative field. If you remove the color for the text, the labels align properly.

Note: This is my first time digging into Vega code, but here is my diagnosis:

The misaligned labels is related to sorting. Vega creates two dataset from the same source. One is used for the arc mark and one is used for the text mark. When they are sorted differently the labels become misaligned.

**data_1 sort is by category**
```
    "sort": {"field": ["category"], "order": ["ascending"]},
```

**data_2 sort when not working**
```
    "sort": {"field": ["value"], "order": ["ascending"]},
```

**data_2 sort when working**. Note: Also works by just sorting by category and not both category and value. This probably depends on the dataset. Presumably your categories should be unique.
```
    "sort": {
        "field": ["category", "value"],
        "order": ["ascending", "ascending"]
    },
```






Here are the two example I've used when digging into the issue.

**Example 1:**
Show a pie chart that has properly aligned labels when using quantitative field as text label that breaks when adding a color to the text label.

[Aligned Quantitative Text Labels - No color encoding - Vega Editor](https://vega.github.io/editor/#/gist/01eabee4d1a2dc99eb617dbca2c62323/vega-lite-pie-chart-aligned-labels.json)

[Misaligned Quantitative Text Labels - Added color encoding - Vega Editor](https://vega.github.io/editor/#/gist/af098f023aae712b6ce8b5739d18aaa6/vega-lite-pie-chart-misaligned-labels.json)

[A diff of the Vega-Lite code](https://github.com/mattlangeman/vega-schemas/commit/7e89948e0bcfd6be930fe0b839db4e0a62277327) the corresponding [diff of the Vega code](https://github.com/mattlangeman/vega-schemas/commit/0560c3369884bb18186b35fbfd0d712fc8f2c1ea#diff-84b57261898ec37acecfc8c085b045f2e2352f066c2e112e3138751bba7c990a).

**Example 2:**
Show properly aligned labels when using a color encoding on text label with nominal values that breaks when changing to a quantitative field.

[Aligned Nominal Text Labels - With color encoding - Vega Editor](https://vega.github.io/editor/#/gist/0d62ecc9f11c666a0ff2bb78c44ff93d/pie-chart-aligned-nominal-labels-with-color.json)

[Misaligned Quantitative Text Labels - With color encoding - Vega Editor](https://vega.github.io/editor/#/gist/94447f9b28d99789503527749e91e65f/pie-chart-misaligned-quantitativel-labels-with-color.json)

[A diff of the Vega-Lite code](https://github.com/mattlangeman/vega-schemas/commit/8385db56765daa947c929b8b74aeb8a4c55bf7c4) the corresponding [diff of the Vega code](https://github.com/mattlangeman/vega-schemas/commit/b5daca5de71577e2cf2fad8c12bce46bb4f0ecde).

**Comment by kakinouchi** [comment]
I am having the same issue.

My guess is that this issue happen only when you use theta field or computed value from theta field as text field.

In fact,
I don't get the issue in the following json:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple pie chart with labels.",
  "data": {
    "values": [
      {"category": "a", "value": 4,   "value_2": 1},
      {"category": "b", "value": 6,   "value_2": 2},
      {"category": "c", "value": 10,  "value_2": 3},
      {"category": "d", "value": 3,   "value_2": 4},
      {"category": "e", "value": 7,   "value_2": 5},
      {"category": "f", "value": 8,   "value_2": 6}
    ]
  },
  "encoding": {
    "theta": {"field": "value", "type": "quantitative", "stack": true},
    "color": {"field": "category", "type": "nominal", "legend": null}
  },
  "layer": [
    {"mark": {"type": "arc", "outerRadius": 80}},
    {
      "mark": {"type": "text", "radius": 90},
      "encoding": {
        "text": {"field": "value_2", "type": "quantitative"},
        "color": {"value": "red"}
        }
    }
  ],
  "view": {"stroke": null}
}
```
Then we get:

![image](https://user-images.githubusercontent.com/32264080/115031333-fee36b00-9f02-11eb-9473-7e00736dfe69.png)

hope this help.

**Comment by kanitw** [comment]
This is due to the fact that the text layer has `color =  {"value": "#000000"}` thus it won't have the same stack `sort` anymore. 

For now, one potential workaround is to add  `"order": {"field": "category", "type": "nominal"}` to encoding like [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABDhpxDsJOsyGA7nRiGk2RNsfWccdVDizMSMmaCSExwghCUhgAywaEQjupmCDQQSMJksnDKiipOKKigxKkMamgA2qBQTuRs6gCeaCAAwlVkNbWGAIzZhYLFaGIAvgoVLW0NzZjVdYYATN1FcGgdM0Mjk61146PTAMzzvYuoABwDALpDIJjqSLIQAGY1CGWgdrLKbDbPIGw4DRAMTyUd1Mgiy6B6fSUSAgDQAKmw-IIAGoLEBnIHXBCHUqyBiCQQKXH487DECVQRQPFVBrKJwAygQ0S0zD0+GIlEHbLQhoABU83l8AHk7mzUmjTkofFA2MoaLIyGhQPQ4H5FSBgaEwSBGdlMLUPA0AI4MG46Pw6UjZCB+KAAazQV2KF2lghqao1oIalXWYyUeoN6FkbCSsjFAwuQVqni+yHU9vyl31hxAlig2TYDEm6gASkhZQwYccAKzh0mx+NKpMNSYAD0w2Wu+cLHQADC2LlKZXKFQna-WEx6tXyvD5MMLRYJdVX0MbTXQnDRLUDHk4GpQWwBSNFKF1uhM69AAYjbJ5b2++6lU6ndIK13qm9T905AQZDYfDEu1pk+Cet6jYtqHESgjhkAA). 

Having a property stack component probably will solve this in the longer term (https://github.com/vega/vega-lite/issues/5078). 

I'll close this since it should be a part of #5078.  

Also the `label` encoding, which will be available soon once https://github.com/vega/vega-lite/pull/7378 is merged, will make labeling simpler and might lower the priority for this issue.

**Comment by kakinouchi** [comment]
Thank you!
The problem I had been facing is resolved by the workaround!
