### ISSUE TITLE
Easier control over chart font size

### ISSUE THREAD

**Issue by Timmmm** [vega/vega-lite#6988]
This is a reopening of #1714, which was never fixed. The default font sizes are quite small and it is rather tedious to change all of them. It would be good to have a global option to change the scale. Currently you have to change all these:

```
  spec.config.axisY.titleFontSize = 14;
  spec.config.axisX.titleFontSize = 14;
  spec.config.axisY.labelFontSize = 16;
  spec.config.axisX.labelFontSize = 16;
  spec.title.fontSize = 20;
  spec.encoding.color.legend.titleFontSize = 15;
  spec.encoding.color.legend.labelFontSize = 15;
```

A workaround is to make the graph smaller and scale it up but that is not a very good workaround because it will lead to pixelation.

**Comment by kanitw** [comment]
Closing since the way to best support this in to do it in Vega.  Hence, please follow https://github.com/vega/vega/issues/2946 instead.
