### ISSUE TITLE
possible to make small-multiples of heatmaps?

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#699]
I can make small multiples of most things, say bar graphs, using "row" and "col" in vega-lite. But "row" and "col" mean something different in a heatmap. Is it possible to have rows and cols of heatmaps?

**Comment by kanitw** [comment]
Yep.  That's the limitation of current approach to describe faceting. We plan to support small multiples of table heatmap in the future.

**Comment by jowens** [comment]
Thanks. Yeah, that'd be useful!

**Comment by domoritz** [comment]
Closing this specific issue because it is part of composition.

**Comment by kanitw** [comment]
@domoritz   this is not a part of composition.   If we allow using TEXT with X, Y.  Then using TEXT with X, Y + ROW or COLUMN would enable this.  Therefore, this is not a composition issue.

**Comment by kanitw** [comment]
Actually I was wrong.  This should be supported as part of composition.

**Comment by longouyang** [comment]
Do you have an idea of what the syntax for doing trellis heat maps would look like once composition is finished?
