### ISSUE TITLE
Point sizes on charts with binned data are NOT updating properly

### ISSUE THREAD

**Issue by jpkli** [vega/vega-lite#6997]
Chart with binned data - [link to Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQyAE4BrNCBxsaszIpBxZUNgBNdZNKAAeVkJgCeOOJoCODJHrpJMNUgd9MQRd0AHU2FUFTAHcaUzgAAgBxFTYICASACiZdWThTAEoDADMaOCjNHNkAfWRrKohqgEYABlrdCEw4HGbq8MiYuLhqlLSIAyq7KrzTNEwVBjglTu60AFYWza3NgF8dpQc7R2c3Dy9MHz8XJUDgzQBVAGVk1PSs6fyipVLy2fQq2pIeodZptBAdLo9JrVJ4jV7jJSTVCgD5-eaLZaQtCtbZbPbLGgALxCoGOIRA7k8gUu-hudDu6AAwmwGHoSmUKuhqtUTKz9PsQNYAEx2H6ckAAuoNUHtWQrKF9CJRWLxOFjapGWYChwi5EgMV-CW6QHAuUy8FyyG9WGjdIa2RagWmHwoPWyJAIcnOi4GYhIQSLcaoADaKONUpBrVl8t6-WVQzV6TQLUR4aB0qjFpj0Ljg1VtsamvWuK2qZqEbNmYh3Wtj0TQZTRvL6cjYOrCpt8PtfxxJaU3N5bNQQoA7AAOIX7MPN02NKuWms5pV54YF5Nlk0ZtsLhW5lWrrtF1AbEuNyUtyvb7Mwutr1C93Ebitzq9W6Gd9VHoWnxsDllDoUAE5AKnJtN1baM30VAZ93rdcwOfc121jZdYILbti1PJ8LxfSDFxvODhx-bDZyQnda3rDDUAAZmIkA-z5NBqJHUDz1I+drz3BM7xPPsEJwsjONQ7jDwdbEfzPNN2NffCPyTIisP46S8I7W9RL+WjFIYodqKaVipK3FSUJgkSxkwvi2MMrMoK4-N1PEujLIg6zZLUszUDERyDOc5D3zcu0j14x96J5f99FQAA2fSZys3zoPjOz3KC7YSNi8ilxMxKArE+8JNSnz0oIu9NIs7zLyMvzKKPTytNCxjh2o6LwPKlzd2ErKg2S0slLSoTMoPT8cofYKnJauK5KDYbutG3DWoo9Cvzo7TwpAhRp2a2a4tsgb5Km6ays2wrtqqoaus2fKxsKiamK8mKCuvCaqJqvjlrQSc1p6+6bPanagyFM7JLuy6+oS36qJK0qgcOh7-KDEdbo2wSoMeo8xyWuqhz0j6ZqR-DjrvPbzs+4Hvv6k6ewBi7oeR2HzJGg7cdU8m0Ai9HB3CrH1sQjjSdBwjCcBxGebxn7mfvSniep1zCOe+mocZ+b7OPNmwrepruZktqyYJiWceFrW+YWnLvwRjWKqK+EWdNgT9cVwa-nh2r2exHYAF0BSQBhMDSIkSXsJxyVKfQlBMPQkA6TQcCQUxzFkSwlBUOAIF9uYFjgAUVXoTRQ4uXQ4BUAx4BoMgsGzuRc7yAudiAA)

Chart with the original data - [link to Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqULKQI4aFWpRKGAJ0H7V6ggjbEacCFJnylAMzYnkmNKEwBPHD10aTkQAF8wpWQTAGt9HDYaWW8lOFkoNmUksh8QAA9c-0D9AEcGJGS6NRpSRRBMOkEgkAB1D0FlAHcaZTgAAgBxEzYICD6ACiYk2ThlAEo613sO-TazLp7+oZGIOqn5TRBkPP3d1ABGAAYopIhMOBw0c4ilP0KA5rKKhvUG2qUfk19ABVADKg2Gowm+xm80Wy2UIPB21GeySuWOpye1yOt3ujwuLxAEBoAC8gr4PqVypVfjU9ADGs0AMJsBjJOpIMhkEx8e76DLs7wRMJAA)

The signal in the compiled Vega Spec for setting the range of the point size: 
```    
{
      "name": "size",
      "type": "linear",
      "domain": {"data": "data", "field": "__count"},
      "range": [
        0,
        {
          "signal": "pow(0.95 * min(width / ((bin_maxbins_10_minstep_1_Worldwide_Gross_bins.stop - bin_maxbins_10_minstep_1_Worldwide_Gross_bins.start) / bin_maxbins_10_minstep_1_Worldwide_Gross_bins.step), height / ((bin_maxbins_10_minstep_1_US_Gross_bins.stop - bin_maxbins_10_minstep_1_US_Gross_bins.start) / bin_maxbins_10_minstep_1_US_Gross_bins.step)), 2)"
        }
      ]
```

**This signal is missing on the chart with binned data**, which cause the points are not sizing properly - [See this example with grid lines](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0xGhAZIANjQBeSNRID6AMwsAGKAGYLANgCcZgXDt2zAFmfyzTEiysmZIcNaOABzWFvJwAEze0iBIDJhsEEZwaKCYAJ442egWdMlQEphINOIQaCA4QbLVZMmKCllomIoMcAC+MoFQANZkimwM4rJ1AMQAYvMLyQ3BzWgAjAIyEPl6RSBQcHp6ybImKKgA2qDiSAh7p5Vm1snE+j21l6BM1WbIAB7fGpmNbWX7VbZwHDAswAdTYij0sgA7jR-ABxMYQD7WAY-f6AiDA0EIcGYSHQuEI5GouBmDEZQlwSZoATWNnstm48S-JAA8FEsE1MlQtZmACqAGU6ZjsVyeXygSDBRCReKpfSsWYmVNUCCOeyZGYzOUJpg0PEAOyReL9L543kEgUkoXk0WUxEo9EytA4kCA+WOpXOlUU+EemnShla5moVn6zl++0KwlB0mutWRrHreMJ-34-mpl2qyWZxkx+I531Gk3iM2oeLOZy2xPc-OK4lp1Xu6lehk+uVtlMdouhqme2kass6uPxgcOgvDkOikuT82VufJp2d6ErmXRnV2dcgavjWtoOwW5t5+ft5XC0fh3tZ2NH6+bwtL2FhnsTvfa7OvkmgaLvey7qt69aAa2N5Dne6a7lG-6oIeOaGsap51nYaxXkBC5wV237jqWLJQQGeHBqBX5jhGk77gBqEtmRt4UfB4F9qg3ikYOW4jmBpZ0S+DEnqaaCODh0HviB6bdkRq6CbOjHcR+lEyTRf4xnqDFvsB+E7mxz4oQp2nkdufG0UhnFCehIn1nY4lMbBLEEdRT4fDO+objpTkPj+-FIZpRm4cxpkZnJAUcp5Jm8aF6k6hWVk1nWTZSHaEleSFqmufRgVpVFn6Zb+iEae5EWKTBPGfghBlceVymsX5MaWQpwlnvW9lKVJzmPoVz7xCVBplZJuluoRalFQela+sZwXRVVHwWjVQ3eWZsVoNECUYes7W1Z1PmyRB4WldNjkZaNrkCRsi3pbN+luVdeWUXNAmOEeLV1thKWDdd+VnT1HyHQNx0VSpv0NTql1aUFJ03cRHH3TNlW3QJ-UJm95rbUtp0uX96wo1NUPA9JoPmeWk2RQjj23aJ8PQ4jYNoAtG02dhAC6vQs1sNBkDcegfFcIA3HcdSevQyTVKU6DaLM4tkgAFOUtZVOIcCKBKWSywAlBc1gsxrAAEAD8esK5U1Qq2rhhwJr2ss3rqB63GyQSGg-MMDgDx7FLMtWybSvm+rWs6-rRu+2bqsBzbdsO2yyRwKQtYfCAKKTGwSKoG0mSWyA7PNoLezwFzWBi+IEsgF7Jdy6Hyvh5b1trLrhvGxUfs11bWv11H8VOxorvuyYnsQNLFc+83YcW23Fz18HTeK2PEcd-bXcyHHTKYInyeyKn6ftFnOccyAyCKEMfPXLceyH8fyT5IUdQQHkCBMGwxxbDsRQXPUbDVGa+8WGMCA5HIM4dQHhICeNnZe4hyjyAAW7D2ACShHAAa8PQPQ6hdCQDUBobQzz9BANsMYQwiigGQag9A0xvBQCtEgSI4CQDpCfmoHAADMjc30HUYAAAdEAc09ay0BMrWQGsuH2wAITaAAGr6FRLLB4DAEAXC4UDOqxZbpcIbgAH3UXrMRg9vaywANSyPkYogmyi9KljUdPLh4gGBHC4VHCw8JkCYBkSYORCivoPXqpONRUg9ZcKkFw-W+j-EgD1oAZAJQl6xCY4xQzjXGYHcSY3KFNvGxV8aEwJIANZ+K4QVUsvD+FwEEcI7REipGyASUkzxqSuq+R8SADRWidFDzoFbQxbjjE1NpiDbGFjGlWIFrYvQ9j7axPiUYjxSjdojT6Q0jmmSgnRKiZE+xMSnEmCqV06Zw0qLdTBhkgJQTckgAAMIYVKeMzZkyuFvUOdIIJvRaF-BdrkBQdYQA6MkQYSpNzumEzqftBkli9aaLKbo4eBi-k7OWns+pMpLEvDeEUawzYWE81vlAfQVsuF-ACXrawlABB6wAFR62haYmZcKgVYjUcswlxKyUUpST0omcz0kDOzvvPIry6HvLqF8ipWypmUt2XNEFYKWl6I6Yk7ZorYXis5TIEohwdSgFGOMJh6AC5kCLr0NFXMMXoGgNi2WXC8j4oZaS8lnSRUsoBeY+Z9KiXWuZQ5B1K1xqIvZpzLOqBQAmt2LfDoyqaCqrqGjfV+r96BoULyvOdQXkyGvnsAwyskCKBOGwZA1QAEgOAWcMBobVV83+WY2Z+zVzk1ZYCsamp-xsxkIoDBZA344gDYath6ARYwC5VyD4AbhQkRzLgy2Yw0AWH0BAPon0E3oB5cmgoqazYZqzTmjQoB83oBAUWkAKrESlphSFOayQj0wxJlMRtIBm3iFbby9FXaMBwELmafoOt+3MKHbqSso6VZsAnVOmdp8hbGpDXQpddQ01wFXTITe6681AO3YW54xbEQRusjgptLa21SHiH1RwlA+r7zHf+1AXQeg+pSH8ONnw8FYqDegJNIB4Rhtan6Ng2Bs3JFGKiCU9G9gLpADxnU5G4DJpoMMc5NlNhyGzUrADvMxMgD0EgJghwPiTsUzIf4ABRP4ZJWq+mdHpgzdZfRqGGBpwDMhDDVHkC81AqLPqxrqIJljq9INwAsGaGQwm+PYsTdx5QInuhKYs0MKTrUZNwfk6gTT06ZAqbU7zBTCWD68hMx5xz2nqiZcM+JyzqWlO2cmHABzTmA38cCzIdzbHH6cf-r54LRXxOYAYyAAqetJyFOqAIjWyQkuHFmCgiAvayOhcS6pw4AB5UgCIkBatEwViLm1Yw2bs2Vn0aKqvzqdsoLLymvM+aE81uL1m6F0Ha5KLrMoeviD6wNqbehZsqxU4tibF3JOrZkyV+zW3967FbZME+F22t7Ei8dzOewodBaCKxzAAAZJkZBRb+rwZ2446AoAqYQDgWWOqsB+McN4Px8V+u4Lvg-J+AAVCDWOaCKGx9kCBUCiF4Pvo-FLaPYH93gTQRBaOSF7HQZgjNHmKddDYIQpByKZgUKoTQqN0aZAKxKC0NHvJtB5rk7ms7WnlNPfOXoeEcuLACDsAIGhk3kuzAqOPdY8RreHAR2bAAEs+3V707BO70AABUaKsb9y2rP67UGDo3JuyHxivpduAtvaz291N70Hux4+YBhB7ou6BOdTFa7sF3yt3cvvWBaPPcB-crFvbjJrqIAAiSBRsuzWFIbw+9hMR8zWQxw3emAWjWDH4Y02rDTrM7gwHSFcix7T4ntYyew+7Ar00KvuoZNjCRIvwPGwVdPzkeIDfy+t-MeH3Ad6MnKec4lJLwhMJUSo7n7H6b+22PpCYTVp-HzlCe8e8ljvpvzeW+-yGztw6F1BtBkHgCCBViN13wAUG2e3fzQTYFfxTzgEf3h0QOQPnzgAAEFIEYBI8D5URZAg0fdcDYACDtgM1X1wDoN5BFAAAlVOWAp7NAg7F-GPMHVg5-JAwAvQMg-AzvPBSoRQagoQvIBjdVBgGkAAWjgPgQqDqF9z+Buw4wUCGD8QAElawVY-EIAMFpDp1lALBaEyApD5BpCsD5C2MlCVCyQIB1C9YtCyRFBdD9DDCaBjDcENU3YLDY8rCPkbD6Q7CHCnCdC9Y9DxADCVYPDkhHEE8QDEgZApFuZPNvMTCxgfCdAmBLC0c4iAjlCgi1DNDtCXDwi3DojPCVdDhMdB0CEigbEjhcExdzhQAEFnsGgoA6AeVHMiVcEcBP5WpQAkCkBOj8gfQiVfUihWRcEyR9N-DFCCixhgjijnDXDIj3DKjr04AoA6xaipc9g5gFh5hs4Zi-C0csisDf8yFvAzcLcrc8FmAsDp8QC1hHAthHjY9991cQRcEb0700csUyQyB4RujKtuA34QBpgXBzdwhkhpgzcmALB4hc9ITvALQkA1g+84SLRoMoALALQ4SMS1gmA1gUT4TIhnBrABBnA4SmBIhPBIhjCZBphIgmBnA1hGw4SBASS4ALQBA4S7BIgLQ0S7BCTAh4gbBaTBSeS4T4hHABB7AmTIS1h4g7AoAXA4SLBvB3AXpCTtSBA1glT4TuS7BTg4Sbj-97jphnAPARiaTmSBBZBAg6TGlcEmg5taBl8wTEAITpgOTvA7BkSBSLw+TRSHTuSLBIhHA4TwgPA4B+TmTVMkAJSUNIToS7BYTmS7BkyGwmBXSaCTBkAtVvSQN35jTESgzmTZhsCAAhawOwWYOE2YC0Zwek+0yE4IYU+IZnSE05HTAQHTeIK02suwGstYHTbEvvNYWffM5jRQJfLtEs309UqAQ0hMyEpMlMuEyk+kuAPM5k9MzMyEg0rCWQVM6YbMvDZwfc5UpgawWQAQeIWc5tXHZhWAH0l2DsnEhwKAOE05f85wWYdc6YbA6s6wHTCc5kyIZs5wHTK0w888k80k88y83M10qNIAA).

**Comment by domoritz** [comment]
Which sized are not updating properly? 
> This signal is missing on the chart with binned data

Which signal is missing?

**Comment by jpkli** [comment]
The circle sizes. 

When using the original data with bin transform, the compiled Vega spec has the following signal in the scale for size:
```
{
      "name": "size",
      "type": "linear",
      "domain": {"data": "data", "field": "__count"},
      "range": [
        0,
        {
          "signal": "pow(0.95 * min(width / ((bin_maxbins_10_minstep_1_Worldwide_Gross_bins.stop - bin_maxbins_10_minstep_1_Worldwide_Gross_bins.start) / bin_maxbins_10_minstep_1_Worldwide_Gross_bins.step), height / ((bin_maxbins_10_minstep_1_US_Gross_bins.stop - bin_maxbins_10_minstep_1_US_Gross_bins.start) / bin_maxbins_10_minstep_1_US_Gross_bins.step)), 2)"
        }
      ]
}
```

When using the binned data, the scale for size in the compiled Vega spec is the following: 
```
   {
      "name": "size",
      "type": "linear",
      "domain": {"data": "data_0", "field": "__count"},
      "range": [0, 361],
      "zero": true
    }
```
Should Vega-Lite also generate a similar signal for binned data?

This seems to cause some sizing issues
