### ISSUE TITLE
unencoded text mark replicated for every data point (terrible svg performance when font is large)

### ISSUE THREAD

**Issue by eflister** [vega/vega-lite#7011]
https://vega.github.io/editor/#/gist/15dbd1f394ce904f1285bf93a4b00968/spec.json

shouldn't a text mark with no encoding only have a single copy?

also wondered whether it would help to expose svg's text-rendering options `optimizeSpeed | optimizeLegibility | geometricPrecision`
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-rendering

**Comment by domoritz** [comment]
That's by design right now. Do you have specific design suggestions that work with the rest of the design space?

**Comment by eflister** [comment]
i hadn't run across an indication it should be replicated in this situation.  can you point me to the relevant doc?  what is the purpose, won't copies always be identical/redundant if not encoding anything?  how is one supposed to express placing a single mark for annotation/labeling?  a layer specifying empty data?  thoughts on svg's potentially slow text rendering?

**Comment by domoritz** [comment]
The general principle in Vega-Lite and Vega (like in D3) is that each data row gets mapped to one mark element. You can aggregate data to reduce the number of rows and also the number of marks.

**Comment by eflister** [comment]
i was trying to follow https://vega.github.io/vega-lite/examples/layer_bar_annotations.html
there they get around this with a layer specifying empty data.  so it's not a 1-1 mapping between data rows and mark elements.  there's no aggregation operation that corresponds to placing something at an arbitrary position in the encoding space, which may correspond to no particular data row.  aggregates are unnecessarily complicated for this job.

i think the current design (requiring every mark, including unencoded ones, to have an element for every data row) is unexpected and undocumented, and i see no use case it serves.  it took me a long time to debug why it was performing so badly, and i suspect would take other users (at least noobs) by surprise as well.  

my specific design proposal is to only replicate marks when they are encoded, as there is no possible way unencoded marks can be anything but identical and redundant.  i also propose exposing svg's text quality options.  i don't see how these performance enhancements could disrupt any current intended behavior.  i could easily be wrong, i'd just like to know how, and if so, for the docs to cover the intended way one is supposed to express placing individual marks for annotation/labeling.  "set the data to empty" is not a very direct expression, but "don't encode the mark" is.

**Comment by eflister** [comment]
i like #6157 thanks for the link, but why shouldn't a mark without an encoding to a datasource be equivalent to a mark without a datasource?

**Comment by domoritz** [comment]
]So you are suggesting that if we didn't have an encoding at all (no `encoding` property directly or through a parent view), then the default data should be `null`. I think that makes sense and we can do that as part of #6157.

**Comment by eflister** [comment]
Yes, I hadn't explicitly thought about inherited data/encoding but that makes sense
