### ISSUE TITLE
piecewise scale doesn't work

### ISSUE THREAD

**Issue by eflister** [vega/vega-lite#7013]
https://gist.github.com/eflister/f34b85ac7b95a039283c060f0b450123

my `y-scale` is `symlog` (also `color` in an associated choropleth), but that overemphasizes some rare negative values in the dataset.
![image](https://user-images.githubusercontent.com/366563/97391986-c9d45500-189d-11eb-955d-f7fbc949fbfa.png)

i can't find documentation for piecewise scales, but i'd expect them to work by mapping data domain values to a new range of values that are input to the scale, allowing me to give less magnification to negative values, even with nonlinear scales.
when i add the following to my y-encoding scale, it collapses the data to a single y value.
```
{ "domain": [-0.2 , 0, 1.4]
, "range" : [-0.05, 0, 1.4]
}
```
![image](https://user-images.githubusercontent.com/366563/97392071-0f911d80-189e-11eb-8533-68cf1f700288.png)

**Comment by domoritz** [comment]
I don't quite follow your example but here is a piecewise linear scale example: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWgArKW5+egAwiWoYgDMlSBJACJ1AJwAjM1JAKJ1mT15LQUAYnWlTSNJAOJ1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBdbqwXCyUGzKNLJkaKAAHq8gAGY0cILKBRQSkwAE8cHACrI2AgnlFgkg3jQIJ9BEhPIJ9M8LGgAAzZY4gz4-P4A9BpYFgiHoACODCQsh0gR0pGC0CiVNAymhSCe8RxClK-PSOJxByU6npZCpcWF-K6IoUovx+KAA).

**Comment by eflister** [comment]
the whole bottom half of my chart is used up on unimportant negative values.  i want to shrink their representation so most of the dynamic range is used for the important values, without completely neglecting the few negative ones.  why does my `domain` & `range` collapse everything to one value instead of doing what i expected?  can you add doc explaining how to use piecewise scales?  i don't follow the example you sent -- i read `{"domain": [0, 50, 200], "range": [200, 100, 0]}` as "make values 0-50 take up twice the space as values 50-200" but that is clearly not what it is doing.

**Comment by domoritz** [comment]
What it does is map data values 0-50 to 200px-100px and  50-200 to 100px-0px. 

![image](https://user-images.githubusercontent.com/589034/97479909-f1640580-190f-11eb-9ea2-067c9b817a1c.png)

**Comment by eflister** [comment]
sorry i just don't understand what you're saying.  the graph shows values 0-50 taking the same number of pixels as values 50-200.

**Comment by eflister** [comment]
oh "0 px" is from the top?

**Comment by eflister** [comment]
then mine collapses to one value because range is supposed to be monotonically descending?  this needs some doc :)

**Comment by domoritz** [comment]
Yeah, we inherited this from Vega/D3/Canvas/SVG. I'm not sure where the best way to document this is. 

I'm glad we found the solution for your question.

**Comment by eflister** [comment]
https://vega.github.io/vega-lite/docs/scale.html#piecewise

"`range` specifies the location (in pixels -- for y, 0 is at the top, positive going down) corresponding to each value in `domain`."

but why are we talking about pixels?  what does this mean for non-positional encodings?  it doesn't work as an abstract scale concept.  in my example, i want to use the same (piecewise symlog) scale for both y-position (in the line graph) and color (in the choropleth).  but the piecewise spec that works for the y-encoding on the line graph eliminates the dynamic range in the color encoding.  the piecewise domain/range specification should be in abstract units, not pixels, and apply before the nonlinear part (eg, symlog), not after.

**Comment by domoritz** [comment]
> shouldn't it be here? vega.github.io/vega-lite/docs/scale.html#piecewise

I don't think so since piecewise scales are a general concepts and the fact that y goes from top to bottom is a property of the y encoding channel (and depends on the renderer).

**Comment by eflister** [comment]
so how do i use it for color?

**Comment by domoritz** [comment]
You can map piecewise segments of the domain (data) to piecewise color ranges. An example is a diverging color scale.

**Comment by eflister** [comment]
yes, we agree on that in abstract.  i mean what actual values for `range`?  do you see my point that it shouldn't have to do with concrete units like pixels, and shouldn't sometimes be in reverse direction for some encodings (y) compared to others (color)?  should the user have to know the pixel positions of the top and bottom of the y axis?

**Comment by domoritz** [comment]
The range are the concrete values like pixels and colors. So I disagree in principle. However, I agree that for piecewise scales it would be nice to have some intermediate between scale and domain you can map from the domain to. You can raise this issue in Vega or D3 scales.

**Comment by eflister** [comment]
but wouldn't it be more useful to apply the piecewise first, then the nonlinear?

data domain 
  -> piecewise range (expresses relative proportions in abstract units) 
  -> nonlinear (symlog, etc -- input to this layer automatically matched to range of outputs of previous layer, user only cares about shape, not units)
  -> concrete presentation (pixels, colors, user doesn't know or care about units cuz again the input to this layer is automatically matched to output of previous)

what disadvantage would there be compared to the current design?  this way i can share a single set of distortions between the y scale and color scale i use to represent the same data field, i wouldn't have to know how many pixels tall the graph is, nor how the color scale is indexed.

**Comment by domoritz** [comment]
Agreed. The pieces should be defined over untransformed data.
