### ISSUE TITLE
allow tooltip along line marks, not just at datapoints

### ISSUE THREAD

**Issue by eflister** [vega/vega-lite#7015]
https://gist.github.com/eflister/f34b85ac7b95a039283c060f0b450123
![image](https://user-images.githubusercontent.com/366563/97399386-508f2f00-18aa-11eb-9ae9-7b2fdaf2574b.png)
it's confusing that the tooltip only appears at datapoints, not along the line.  in the segment between points, if those point's entries for a tooltip field agree, just show that value.  if they disagree, maybe show `value 1 - value 2`.

**Comment by domoritz** [comment]
I think https://github.com/vega/vega-lite/issues/6851 covers this.

**Comment by eflister** [comment]
oops sorry i missed it thanks for link

**Comment by domoritz** [comment]
No problem. It's hard to find the right keywords.
