### ISSUE TITLE
please make sure the fieldT always include year number when dates span multiple years

### ISSUE THREAD

**Issue by t829702** [vega/vega-lite#7016]
I'm using vega-lite-api to visualize a very simple dataset, and very simple x fieldT `date` and y fieldQ `count`:

```json
  "data": [ {"date": "2020-10-16", "count": 238}, ..., {"date": "2018-10-16", "count": 23}, ... ],
```

```js
vl.markArea()
  .data(data)
  .encode(
    vl.x().fieldT('date'), // .timeUnit("utcyearmonthdate"),
    vl.y().fieldQ('count'),
    vl.tooltip().fieldQ('count'),
  )
  .render()
```

it got this graph, it is good, but from the x axis, it doesn't clearly show the months' of which year, is it 2020 ? or 2019 ? or 2018 ?  have no idea;  it is better to always include January of the year, like D3 does that

![image](https://user-images.githubusercontent.com/49542456/97405468-edef6080-18b4-11eb-8dae-6d796b2e6acb.png)

Please:

- [ ] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [ ] Describe the feature's goal, motivating use cases, and its expected behavior.
- [ ] If you are proposing a new syntax, please provide at least one example spec, wrapped by triple backticks like this:

```json
{
  "mark": "area",
  "data": [ {"date": "2020-10-16", "count": 238}, ..., {"date": "2018-10-16", "count": 23}, ... ],
  "encoding": {"x": {"field": "date"}, "y": { "field": "count" }}
}
```

You are encouraged to prototype multiple alternative syntaxes for your proposed feature. Doing so often leads to a better design.

- [ ] If applicable, include screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working example (e.g. example Vega specification for the requested feature)

**Comment by domoritz** [comment]
You can customize the formatter string to include the year. Internally, we use d3 format.

**Comment by t829702** [comment]
when it can't show all months' name, D3 would always choose January, March, May, July, ... all the odd number months', and at each January it always replace `January` to the actual year number;

the question is why don't you make it default?   that is the point of using Vega-lite

**Comment by domoritz** [comment]
We use Vega's default. You can raise the issue there.
