### ISSUE TITLE
Sort by multiple fields in Vega-Lite's "sort" marks properties channel?

### ISSUE THREAD

**Issue by roger-schaer** [vega/vega-lite#7017]
I tried to find similar issues and didn't find exactly what I need.

I have read all the documentation about Vega-Lite's "sort" property (https://vega.github.io/vega-lite/docs/sort.html) and it seems as though it isn't possible to have multiple fields in this property (multi-criteria sort), the way it can be done in Vega's "collect" transform (https://vega.github.io/vega/docs/transforms/collect/).

As far as I understood, the "collect" transform is not available in Vega-Lite, so it would be great if multiple fields could also be specified in the "sort" property of Vega-Lite, like so:

```json
{
  "mark": "rect",
  "encoding": {"x": {"field": "a", "sort":{"field":["b","a"], "order": ["descending", "ascending"]}}}
}
```
The reason I need this is to be able to sort data on the x axis by two criteria: first by a binary "outcome" column that is either 0 or 1, and second by an "id/name" value like "Person1", "Person2", etc.

Perhaps I missed something, but I wasn't able to find any example that shows that this is possible.

Thank you in advance for your help!

**Comment by jwoLondon** [comment]
As far as I am aware you can only sort by a single field. However you can use `calculate` to create concatenated fields that would allow you to effectively sort by multiple fields:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      { "a": "fish","b": 1 },
      { "a": "cat", "b": 2 },
      { "a": "mouse","b": 2 },
      { "a": "dog","b": 3 }
    ]
  },
  "transform": [
    { "calculate": "999 - datum.b","as": "bReversed" },
    { "calculate": "datum.bReversed + datum.a", "as": "combined" }
  ],
  "encoding": {
    "x": {
      "field": "a",
      "sort": { "field": "combined" }
    }
  },
  "mark": { "type": "rect","stroke": "white" }
}
```

**Comment by domoritz** [comment]
Hmm, I wonder where that limitation is coming from as we should be passing the fields down to Vega. 

Thanks for the enhancement request.

**Comment by domoritz** [comment]
We sort domains in Vega. The docs are at https://vega.github.io/vega/docs/scales/#domain and it looks like it only supports sorting by a single field. 

We could make the collect transform available in Vega-Lite. I added it to https://github.com/vega/vega-lite/issues/3264.
