### ISSUE TITLE
Add Vega-Lite API to dropdown

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#7020]
Should we add Vega-Lite API to the dropdown below Altair? We should do this consistently across the Vega-Lite and Vega websites. 

@kanitw @arvind @jheer any objections?

**Comment by jheer** [comment]
No objections. I think this is a good idea!

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/7143 and https://github.com/vega/vega/pull/3036
