### ISSUE TITLE
Split Schema.js and consider TypeScript

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#703]
Right now schema.js is almost 1000 lines, we should 
- [x] at least split them off into multiple files
- [ ] consider if we would like to migrate to TypeScript.   Basically, the schema is describing the Vega-Lite object and if we’re doing that anyway, why don’t we declare these using Typescript’s interface and leverage it to prevent type error in the whole code base?   
  - There is a tool for generating JSON schema from TypeScript interface. However, we need to handle
    - `default`: Currently we generate default values by augmenting json schema with `default` property and used in our instantiate method.  
    - `role`: Currently we add `role` property to guide how UI can be automatically generated in Polestar.

**Comment by domoritz** [comment]
We use typescript and split the schema.

**Comment by kanitw** [comment]
we haven't declared interface...

**Comment by domoritz** [comment]
The issue is not clear about that. Also, we have the same in #723.

**Comment by kanitw** [comment]
Fair enough.   Closing then :)
