### ISSUE TITLE
Add doc example of replacing tick labels with custom strings

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#7045]
Occasionally it is useful to att a string label to explain numerical tick values on an axis while still using the numerical value for calculating an average, e.g. in ratings or survey responses. I couldn't find an example of this in the docs, and only after much tinkering I was able to use `labelExpr` and `tickCounts` to figure out a way to do this. I am not sure if this is the most convenient way and maybe I missed a more convenient approach. One thing I have not been able to figure out is how to set an exact number of ticks instead of it being rounded to a nice value, but would you consider adding an example similar to this in the docs (I can PR if desired)? 

![image](https://user-images.githubusercontent.com/4560057/99450854-34454780-28d6-11eb-9ba7-3ba6aa382ea1.png)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEABMkmFKlDKkCOGi06BMsQFYAZrYBsAJhuPJVq44DscAAwBOSUcAZj8mTUD7KBkkPx8QAF8NbV0IOEwINFBki2s7GycXNw9vf0CQsIiomLjUAG1QAEkAWQARACEAAgAlHRplMjQrSjENJqR5NgAnDoBxOGVJk3QAQShMdlVExtbOnvX+tHtKR1Hxqdn5xdNV9ZUEtW327t6D1E8pU4npuYWlkBuNvdHrsXgNUEMrJ9zj8rugAMJsYyaACeQJAzSeez6YIhUO+lz+CKRqK26J2z32YPeQTxF1+piJcBRaIxIMpg0oNJAYy+dNh-zWgNJrIp2I5I25Z3x9JWgruwvJWNe0j8tJhfwB8oeZMxoLQkjVBOucs2AF1EiB5lA2JoxfoQAAPTIgJBkMiLCiYP7GJCqDRIB00DL2wRIJhwQQAUQdOEmpmSDAQlFD4cEHQAvOmOj4OgB+DoAcgACmwpgWOqgOgmkymIxms1Y84WAHJwBiYSZIQTlysFmaLHQF9QgWuCABiggYEBgaBsXdSGnWUAA1giGMpMGgghabDQI5pTCKlQMNNAu0ssoikH00LUfGoZD5zYu6II-sPMMicH8AI4MX3rLo6ykPcICovau77qYPLQkap5TJu6BOi+mBvqYH5fn8yiIn0XYJBayCTMuzoQDQABeSySPeICft+phQDQkxQGh8TxEAA)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "data": {
    "name": "data-145f5f62f285527e098239bd826c1a90"
  },
  "datasets": {
    "data-145f5f62f285527e098239bd826c1a90": [
      {
        "IMDB Rating": 5.4,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 6.2,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 7.8,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 5.5,
        "Major Genre": "Comedy"
      },
      {
        "IMDB Rating": 5.5,
        "Major Genre": "Comedy"
      },
      {
        "IMDB Rating": 7.3,
        "Major Genre": "Comedy"
      },
      {
        "IMDB Rating": 5.3,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 5.4,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 8.9,
        "Major Genre": "Action"
      },
      {
        "IMDB Rating": 8.0,
        "Major Genre": "Action"
      }
    ]
  },
  "encoding": {
    "x": {
      "aggregate": "mean",
      "axis": {
        "labelExpr": "datum.label == 0 ? 'Poor' : datum.label == 5 ? 'Neutral' : 'Great'",
        "labelFlush": false,
        "tickCount": 3
      },
      "field": "IMDB Rating",
      "scale": {
        "domain": [
          0,
          10
        ]
      },
      "title": "",
      "type": "quantitative"
    },
    "y": {
      "field": "Major Genre",
      "sort": "x",
      "title": "",
      "type": "nominal"
    }
  },
  "mark": {
    "size": 80,
    "type": "circle"
  }
}
```

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior.
- [x] If you are proposing a new syntax, please provide at least one example spec, wrapped by triple backticks like this:
- [x] If applicable, include screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working example (e.g. example Vega specification for the requested feature)

**Comment by domoritz** [comment]
I like the example. Here is a slight cleanup ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S5NoDWaUBBoAvOGgAcABiWYAJ44XuhQNNpQgl52IHCyUGzKNLJkLiAAHulIZGTafJihIAhwSPJKSBk0EOmCSExwggCiGTja+qqYDAiUdQ2CAAQAvEMDvgMA-AMA5AAKbGza0wOoA53dvfWNw6MArJMzAHJwDJjaSILLq9MA4vlq04ogfY0AYoIMEDBoAGYXEHAlMQLgwLGgANr+XYKACMvgAurEfuZBMp9ABJACyABEAEIDABKahSaSU0AuoVAyjYyBSEP8cMRATo0TQsgYgkEsUC6WRjTR6ExSEkiwGN3i+SeMm0mH0WWZmFZqHZnJsaqAA)):

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "url": "data/movies.json"
  },
  "mark": {"size": 80, "type": "circle"},
  "encoding": {
    "x": {
      "aggregate": "mean",
      "axis": {
        "labelExpr": "datum.label == 0 ? 'Poor' : datum.label == 5 ? 'Neutral' : 'Great'",
        "labelFlush": false,
        "values": [0, 5, 10]
      },
      "field": "IMDB Rating",
      "scale": {"domain": [0, 10]},
      "title": null
    },
    "y": {"field": "Major Genre", "sort": "x", "title": null}
  }
}
```

Yes, please send a pull request!

**Comment by joelostblom** [comment]
Great, thank you for the cleanup @domoritz ! I opened PR https://github.com/vega/vega-lite/pull/7047
