### ISSUE TITLE
Improve typescript performance

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#7069]
Not a big deal but we can improve typescript performance by using interfaces rather than unions and adding some return types where it makes sense. See https://github.com/microsoft/TypeScript/wiki/Performance.

**Comment by holdenmatt** [comment]
We're using Vega-Lite in a Typescript/React app, and it's generally working well (thanks for the great library!).

The most painful thing I've found about using it is interacting with the Typescript types for the various parts of a Vega-Lite spec.

More specifically, we often want to construct "partial" Vega-Lite specs using various logic, before having a complete spec to hand off to Vega-Lite. It's hard to navigate the Typescript types for subobjects in the TopLevelSpec. I can give more specific examples/details if it would be helpful.

Curious if there are any plans to improve Typescript support?

**Comment by domoritz** [comment]
If you have specific suggestions, we can consider them.

**Comment by holdenmatt** [comment]
Thanks!

From my perspective as a Typescript library user (not expert), I'm usually wanting to interact with some top level object from the Vega-Lite docs (like an Encoding, Mark type, or Axis) to construct a spec in parts, and it's quite hard to drill into the exposed `TopLevelSpec` type to find where the right subtype is, given all the different unions involved. If these "top level spec" objects like Encoding could be exported or more discoverable, that would help me a lot. For example, just adding a few examples here of how to interact with common spec subtypes would help:
https://vega.github.io/vega-lite/usage/typescript.html

My lead engineer (@ian97531) knows much more about Typescript than I do, so he may have more color on what could make Vega-Lite more ergonomic for others to use with Typescript.

**Comment by domoritz** [comment]
Okay. Just to note, this is different from the original purpose of this issue. I'd be happy to review a pull request to clean up our types. Please submit small prs.

**Comment by domoritz** [comment]
Related issue: https://github.com/vega/vega-lite/issues/9222

**Comment by domoritz** [comment]
TS performance hasn't been an issue so I'll close this.
