### ISSUE TITLE
Scale domain for "bar" mark rounding to automatic value, ignoring the actual setting

### ISSUE THREAD

**Issue by sairus7** [vega/vega-lite#7070]
When `"scale": {"domain": [100000, 900000]}`, it works fine, but if domain is set to the exact data bounds `[20000, 920000]`, it rounds instead to some automatic value `[0, 1000000]`:

```json
{
  "data": {
    "values": [
      {"w_start": 30000, "w_end": 320000, "h_start": 0, "h_end": 838},
      {"w_start": 330000, "w_end": 620000, "h_start": 0, "h_end": 736},
      {"w_start": 630000, "w_end": 920000, "h_start": 0, "h_end": 773}
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "encoding": {
    "x": {
      "field": "w_start",
      "type": "quantitative",
      "scale": {"domain": [20000, 920000], "padding": 0}
    },
    "x2": {"field": "w_end", "type": "quantitative"},
    "y": {"field": "h_start", "type": "quantitative"},
    "y2": {"field": "h_end", "type": "quantitative"}
  },
  "height": 150,
  "mark": 
  {
    "type": "bar",
    "clip": true
  },
  "width": 500
}
```

![image](https://user-images.githubusercontent.com/20798349/100474014-b9a7d380-30f0-11eb-86c2-b8708ee56e9d.png)

See this example in [Vega-Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUA7gPpYwBOU8AzAAx00A0IxGAdmNQEz2MgAWJcpTi8BbDnAAcVSQF8GhQRArVa9Ji3bwAbN3X8lKkUzFa4Adirb5i0suHa1dDUXHwAnHucG7R0a7NzS1kAXXkQABIsAGM+DABbWDh+KCgAByw4AHosxAwAcwgAOnyASyg+NAAjItKAeyyYuMTcgogAWhRyjFyAFiKAKyw61hAmNmi6sFLWfPhQAA95kAAzUowUCWZDSiYoAE80jHgQAEc0CFYocuhSvLGQGNRjhHA6xJm8L0ZPHhCmNIQMDTWbwGiycILTjLNYbLaaDh7Q4vM4XK43a73cL7GHrTYnAS+XYgA5HE7nS7XGCY47Y6GvWH45KmREk5HktFU25Y8JxUr5PjCACMAFZeIkyABrZaklFVZQPaJdNLwKBkTDhAilMAVeBi8FAA)

Solution with padding does not work here: https://github.com/vega/vega-lite/issues/5295 (added padding to the example above, but nothing changed)

**Comment by sairus7** [comment]
Finally, found solution:
`"scale": {"domain": [20000, 920000], "padding": 0, "nice": 0}`

This is very strange default behaviour... 
Also, it has poor discoverability from the docs (I've noticed this only third time looking to that [page](https://vega.github.io/vega-lite/docs/scale.html)).

**Comment by domoritz** [comment]
Thanks for providing the solution here. Note that the value should be false, not 0. We inherit the scale nicing from Vega and D3.

**Comment by sairus7** [comment]
Thanks. I have changed previous post from 0 to false.
