### ISSUE TITLE
Combine transforms with repeating charts

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#7071]
It would be quite useful if charts that use a transform could be repeated over different columns in the data. Examples of this include adding a regression line to multiple scatter plots or creating a density plot for all numerical columns in the data (without melting the data first). I couldn't find any example of this combination in the docs and when I tried myself in both altair and vegalite, it seems like it is unsupported as far as I can tell, but apologies if it exist and I just didn't figure out the correct syntax.

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by willium** [comment]
Do you have an example of a Vega-lite spec you're trying to macro or the Vega spec you'd like to create?

**Comment by joelostblom** [comment]
For example adding a regression line to each plot in the scatter matrix example in the docs https://vega.github.io/vega-lite/examples/interactive_splom.html. Or extending this density plot example so that it repeats over a few of the numerical columns in the movies sample data frame https://vega.github.io/vega-lite/examples/area_density.html

**Comment by domoritz** [comment]
You want something like [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S7XBxw1aUFDaCGCeagDaIAFUAZQACAHFtNggIRRAAdTZdZQB3GmU4cMjokABdOxAIJyhXEGRtAGsSzABPJ31hWThY90FE-QAzGgcmbRooSvzMbSRZCHbEhDRfUAcyB2j2HxnHZ0x9Fq9bJTl9ACU2bDhZEIAVNmRMNgsQ3bUaWTIQGxylI-dle8fNEAAPEs64IJlHsDpgjqdzmorhAbncHrEanV0ABHBgjTB0O6kJ5Kar-cxAkoOJwudAbbw4kCIpootGyDHqDHYmwsmxAA)? 

That should be fairly easy to add. You need to modify the normalizer code to replace the repeat reference with the field. Wanna take a stab at it?

**Comment by joelostblom** [comment]
Yes, something like that is what I tried and I ran into the same syntax error. I am a bit swamped currently but can try to take a look during the break maybe if no one else picks it up before me. Would the fix be to add something like a `replaceRepeaterInTransform` function in this file https://github.com/vega/vega-lite/blob/master/src/normalize/repeater.ts?

**Comment by domoritz** [comment]
Yes, that's the right place.

**Comment by kanitw** [comment]
I think this issue is a special case of https://github.com/vega/vega-lite/issues/2518#issuecomment-753225620

**Comment by domoritz** [comment]
Agreed
