### ISSUE TITLE
scale independent conflicts with height

### ISSUE THREAD

**Issue by krlng** [vega/vega-lite#7075]
I use altair (see [issue](https://github.com/altair-viz/altair/issues/2353)) to render a vega_lite Chart with two figures that have independent y-axis and different heights. How ever, the second height does not have an effect. The vega-lite JSON looks like:

```json
{
	"config": {
		"view": {
			"continuousWidth": 400,
			"continuousHeight": 300
		}
	},
	"vconcat": [{
		"layer": [{
			"mark": "line",
			"encoding": {
				"color": {
					"type": "nominal",
					"field": "symbol"
				},
				"y": {
					"type": "quantitative",
					"field": "price"
				}
			},
			"width": 850
		}, {
			"mark": {
				"type": "area",
				"opacity": 0.4
			},
			"encoding": {
				"y": {
					"type": "quantitative",
					"aggregate": "average",
					"field": "price"
				}
			},
			"width": 850
		}],
		"encoding": {
			"x": {
				"type": "temporal",
				"field": "date"
			}
		},
		"height": 260,
		"resolve": {
			"scale": {
				"y": "independent"
			}
		}
	}, {
		"layer": [{
			"mark": "line",
			"encoding": {
				"color": {
					"type": "nominal",
					"field": "symbol"
				},
				"y": {
					"type": "quantitative",
					"field": "price"
				}
			},
			"width": 850
		}, {
			"mark": {
				"type": "area",
				"opacity": 0.4
			},
			"encoding": {
				"y": {
					"type": "quantitative",
					"aggregate": "average",
					"field": "price"
				}
			},
			"width": 850
		}],
		"encoding": {
			"x": {
				"type": "temporal",
				"field": "date"
			}
		},
		"height": 60,
		"resolve": {
			"scale": {
				"y": "independent"
			}
		}
	}],
	"data": {
		"url": "https://vega.github.io/vega-datasets/data/stocks.csv"
	},
	"$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json"
}
```

**Comment by domoritz** [comment]
Can you simplify the test case? I don't see a problem in a simpler chart: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoMcGmSxoAjAAYtSgCZJMKVKGJJBDOBDQBtUMZABBRSCZoATAA4AvgvtoQACEXN1QAVjDff3QAYRC0MQBmKJAHABF41ABODRSHAFFMz1y-VICAMUyw5NKHAHFMjSy8gIAJIoB2FvQASSr3bwBdXxA4WSg2PRpZMjRQAA85kAAzGjhBPQCUJUwATxw4ANk2BGnzFyR5mmsTEEEkJnXHGcFD1C1vEd2l1fXN9DcO32bxAAEcGEhZJg6IYaKQQJ8lPddnAAE62UDIVEAawCODY00wCNKWNx6GEskOQyUqKsbEE8Nu0HMb1A33Q0z0cAOsi5UIRnyAA).

**Comment by krlng** [comment]
I don't think so. I actually do not know much about vega-lite, the altair example is already as minimal as it can get to produce the error. 

The test case is definetly to minimal, since the root of the problem seems to be the `vconcat` combined with the differing `height` attributes

**Comment by domoritz** [comment]
Ahh, here: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSACCikEzQAmABwBfBSbQgAQpeuoArN6cv0AGFPNDEAZn8QUwARENQATgBGSNMAUTi7ZOco1wAxOO8I7NMAcTjE+JTXAAkMgHYq9ABJApsHAF0nEGIoOSg1I1B4GjIsNESABgmlOFle5RpZMjRQAA8VkAAzGjhBZVcUJUwATxw4V1k2BEWdSyRVmgNNEEEkJl2zJcFz1AmHLuOG22u326GsR1OPxAAEcGEhZJg6GoaKQQP8lK9jnAAE6DEDIbEAa1cODYi0waPaSmx+jYglRz2gOh+oEB6EWyjgZ1knIRaPRQzgIzGqBsUxmczYCyWG3Wz2BewOlhOZwuVxugjuDyeoFe70EnzI3zQfwBQJ2irByshrlh8MR6kRqPRLyQWNxqGM+KQRJJZL5HWptPpLJATONzzZIA5XNmvIp-w6DiAA).

**Comment by krlng** [comment]
Yes, thats the bug
