### ISSUE TITLE
Legend Coloring with Condition Test

### ISSUE THREAD

**Issue by jkahn521** [vega/vega-lite#7117]
I have a small feature request to allow legends to parse and display colors based on `conditions` set in the `color` vega configuration. For this use case, we want all line colors to hit the dynamic scale range color, except for one specific `id` value (`red` in this example). Is it possible to mix the dynamic and fixed colors in the legend? This works fine in the plot itself. 

In the example below, I am having trouble getting the legend coloring to update with the color red, which is not in the color scale range, but rather is set through a condition. Is it possible to tell the legend to respect the `condition` `test` clause (red) rather than just always showing the color from the color `scale` `range` (green, yellow, orange)?

Put together an example, where you can see the color misalignment between the legend and actual plot.

```
"color": {
          "field": "id",
          "condition": {
            "test": "datum.id == 'red'",
            "value": "red"
          },
          "scale": {
             "range": [
                   "green",
                   "yellow",
                   "orange"
                      ]
                   }
         },
...
```

[Sample vega link](https://vega.github.io/editor/?#/url/vega-lite/N4IgJghgLhIFygHYQLYFN4hgIwDYYBoQA3CXAVzQGd4BtUASzEwHMAnNNREIyKDOCABMABlEBaAIyTxQyTxJlK8EQDpJAVgC+BRs0HtO3XtAHCxIqUKsLSFAWqE69mDsxP9MoiZOuSAnLZKAuKO2rogTJgA9mwQiCyE4KZeFlY2RHbKcI7OkfogsfGJCnxm3pa+oRpB9irqeVEGHFylKYIVUjIiAOy12aGqIuEuzUZtnh1p0rIAHP0huRFNhXEJSWWpPjKSACwL8IO9I-msLcbJk+bbUvuZwfViJytuE+XTfkIHOapOywWvDzvHzWYbfNSSRoFQytIFbSp+QL3Oo-TRQ1xodyXYGVGRycFDZ4FIrrN7wrqhPrIgZqJ7owQkkpwqY3fHUhzqIREjFYzYs3GU75HHrcwSA7HkmZCebsw5hekgcV864CvZC2kihUwi7KzpVMGyn7DBWMjbtFXpALq9Si1bFM1XPV4mWKFGDJwAXR0IAA7kwoAALTAAY2iiBgDEQaDYCgDaAYLADUBDYYjUZjRCgDCg+HgoH4AA9k4IFFRyNgszmzCBvbgIABPaN0UBcUNgSMsPMgAtdgBmDDQuAKm0z9YADmZ+Cgx0VcAoIAWGDQECBe7EUNBMABSFAAei3YH39YUldzcEQ5FwuCI7CavbIVDQ3qz6AAqohs13yB-iyBGxA2BQVMAxHEByCgYN4CgNhKC0b1jxXftBwKLIkigcczAAR3IeJK2gBhiCSBclz7ddN0EVQNAAPzHE9szPC8rxvNgmmgyhmKYABhaJcFiTAAGJexEIShJrb1Q14mNEIHIdMCiIhQ0QdsszDLt+CoX8+HIFBVCYAACABeAy9IAcjcEzvkVTEayIKhgzIARQDWEo4FoEBtQUU0FEbK9oh9EAvSIfBEiUtT6LMABJZg4MzaIeKzWjXNAJDZMEeSsHCzAops5KZOHFJM0ywQABECqwDDMCnGc4jnIg10A8iQB3fdDy3Y9bPss98wqwRwMgmLcuQzBULoqtMAANQeUcJ0wbDcOzfDCIUeqN1-IYtxrQKQDrRspPoEBH3wYMVO4FcAwTANcAu-gpO6mbBBQS8s2WvLlzcqIPSIbBIwKYKuGi70NzYABrNSeu2yMkhnSNi3vXBHwUni+MEfjJBEXYNAANkxmyQFbaJ2wSLtojHCBg2zBDQEU5SGFUldDrQY7adOkBzsTK7Exu75IUNXIBoOwdGZOrs62wQcwfug6O1zIgowA6hizYtAiDpkAgPIR9okIjM8cQNsOze7tvICog0GndDMEQMMMBitWANBld0Ml6HwwUYMrsSpXvXxwnOxXEmyYprtqezZmuwZpnVdF8XDR511shEOCtEC-M1ioFbm1XBhcC5+nBcjlno7nODPu2hsmySu2QYlswYJlkAJOR9y4nawpSfJi2cm9vWCY7Lse2kobBFAp3JzN6qyHnFhDBYc0UEjMS8h9vvHbQIs+zy4apvKyW5vDBasyWuqyLWkQNu9AfBtSiVprH6dZ1xyms6H+O0PBve8MPm3a3LvbQCBh2d0x7r1stBaIwMzA+nOp4UBbBwFoAAOr+iDHAIQRAyAJkLmgXsyZeADw0LwBC4htB5AATXSqa9cEgAwSwLBODSj4MIYccIut9ZExXI3W6z9r7pVHpbaI89kC1QbmGGmdN8wK0wFpHS+kjKmXMpZV4Sdk4qK9EAA)

**Comment by kanitw** [comment]
Legend is a visualization of the scale. 

If the color "red" is not a part of the scale, then your suggested behavior violates the abstraction. 

You can get round this by setting both domain and range of the color scale and make sure that domain value "red" maps to range value "red".
