### ISSUE TITLE
Unintuitive typescript API for boxplot

### ISSUE THREAD

**Issue by willcrichton** [vega/vega-lite#7126]
I'm using react-vega and vega-lite to create a boxplot in my React/Typescript codebase. Here's the program I arrived at:

```typescript
import React from 'react';
import {VegaLite} from 'react-vega';
import {Mark} from 'vega-lite/build/src/mark';
import {BOXPLOT} from 'vega-lite/build/src/compositemark/boxplot';
import {Type} from 'vega-lite/build/src/type';

import {PROGRAM_DATA} from './data';

export let AnalysisRoute = () => {
  let spec = {
    mark: BOXPLOT,
    encoding: {
      x: {field: 'language', type: Type.nominal},
      y: {field: 'ntokens', type: Type.quantitative}
    },
    data: {name: 'data'}
  };

  return <div>
    <h2>Analysis</h2>
    <VegaLite spec={spec} data={{data: PROGRAM_DATA}} />
  </div>;
};
```

The issues I encountered:
* Import paths are weird and not documented. If it's not exported from `index.ts` then I have to search around for the appropriate place to import.
* Finding the right type to use is hard. I sadly can't just put `mark: "boxplot"`. I had to search through several files to find the right incantation of `BOXPLOT`.

These issues are partially API design, partially documentation (#5247). Re-exporting more utilities from `index.ts` and additional documentation can help.

**Comment by domoritz** [comment]
You can use strings.

```ts
const spec: TopLevelSpec = {
  mark: 'boxplot',
  encoding: {
    x: {field: 'language', type: 'nominal'},
    y: {field: 'ntokens', type: 'quantitative'}
  },
  data: {name: 'data'}
};
```

I haven't run the code above but I think the problem is that Typescript infers `'boxplot'` as `string` when you create `spec`. To fix it, you can try to either set the type of `spec` to `TopLevelSpec` or append `as const`.

Let me know if that works. If yes, then I would say the issue is only documentation, not API design.

**Comment by domoritz** [comment]
@willcrichton I just created https://github.com/vega/vega-lite/pull/7127 to add some docs to the website. Can you take a look and suggest improvements?

**Comment by willcrichton** [comment]
Ah ok that was correct. The specific issue was that I'm using `react-vega` which goes through `vega-embed`. `vega-embed` expects a type `VisualizationSpec` which is either a Vega spec or a Vega-Lite spec. For whatever reason, TS assumes a Vega spec instead of a Vega-Lite spec by default, and hence the type error.

Thanks for the quick response + docs change. I'll add a few notes.
