### ISSUE TITLE
x-axis label overlaps long bar graph item labels

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#713]
Latest build as of this morning. I like that you're tightening up label placement! This might be a little over the top, though.

![vega_scaffold](https://cloud.githubusercontent.com/assets/976970/11040682/603b5d68-86c2-11e5-82d1-47c1dff0fb19.png)

```{"marktype": "bar", "data": {"values": [{"m_teps": 33.5330810546875, "dataset": "ak2010"}, {"m_teps": 21.458358764648438, "dataset": "belgium_osm"}, {"m_teps": 1023.6077880859375, "dataset": "cit-Patents"}, {"m_teps": 502.16387939453125, "dataset": "coAuthorsDBLP"}, {"m_teps": 10.410270690917969, "dataset": "delaunay_n13"}, {"m_teps": 187.35877990722656, "dataset": "delaunay_n21"}, {"m_teps": 443.1048889160156, "dataset": "delaunay_n24"}, {"m_teps": 55.096927642822266, "dataset": "europe_osm"}, {"m_teps": 3530.5595703125, "dataset": "kron_g500-logn21"}, {"m_teps": 79.42512512207031, "dataset": "road_usa"}, {"m_teps": 2050.32421875, "dataset": "soc-LiveJournal1"}]}, "encoding": {"y": {"scale": {"type": "log"}, "type": "Q", "name": "m_teps", "axis": {"title": "MTEPS"}}, "x": {"type": "O", "name": "dataset"}}}```

**Comment by kanitw** [comment]
Please use Vega's latest `dev` version in the `master` branch and "dataset" will be nicely placed.

**Comment by jowens** [comment]
OK cool. I'm generally trying to stay on released-vega and trunk-vl (that's been successful so far). If vega releases relatively often, I'll stick with it (this blip is no big deal), but if you suggest I really should move to dev-vega, I can do that.

**Comment by kanitw** [comment]
Right now, our convention is released Vega-Lite would work with released vega.  
Same for dev Vega-Lite with dev Vega.  

But that said, we will try to avoid requiring Vega’s master in Vega-Lite’s master in the future.

**Comment by jowens** [comment]
Your convention makes sense. Do whatever makes sense for your development. I'm actually on master vl and master vega, it appears, but also ```<script src="http://vega.github.io/vega/vega.min.js"></script>```, which is probably not congruent with my vega.

**Comment by jowens** [comment]
This now looks good with latest {vega,vega-lite} master, thanks.
