### ISSUE TITLE
Should scale nice be true when domain is specified as exact values?

### ISSUE THREAD

**Issue by donghaoren** [vega/vega-lite#7156]
Consider the following spec:

```json
{
  "data": {"values": [{"a": "A", "b": 28}]},
  "mark": "bar",
  "encoding": {
    "x": {"field": "b", "type": "quantitative", "scale": {"domain": [0, 150]}}
  }
}
```

![image](https://user-images.githubusercontent.com/1595237/103718663-2463ee80-4f7c-11eb-810c-da9a51e29e7a.png)

I would expect that the domain is exactly `[0, 150]` as explicitly set.

**Comment by jwoLondon** [comment]
I agree this would be helpful default behaviour for an explicit domain to override any nice settings.

**Comment by domoritz** [comment]
Good idea. Done in https://github.com/vega/vega-lite/pull/7157.
