### ISSUE TITLE
header: {"labelOrient": "bottom"} does not work on columns 

### ISSUE THREAD

**Issue by ChiqueCode** [vega/vega-lite#7161]
Hi, I came across the bug and was advised to report it. Here is the code:
```
vegalite({
  width: 50,
  data: { values: StackVega },
  mark: 'bar',
  encoding: {
    column: {
      field: "new_name",
      type: "nominal",
      spacing: 2,
      title: "Name",
      header: {"labelOrient": "bottom"}
    },
    y: {
      type: "quantitative",
      aggregate: "sum",
      field: "new_rate",
      title: "Rate",
      axis: { grid: false }
    },
    x: { type: "nominal", field: "stat", axis: { title: "" } },
    color: {
      type: "nominal",
      field: "stat",
      scale: { range: ["#675193", "#ca8861"] }
    }
  },
  config: {
    view: { stroke: "transparent" },
    axis: { domainWidth: 1 }
  }
})
```
I needed to move the name labels to the x-axis and `header: {"labelOrient": "bottom"}` didn't work.

**Comment by domoritz** [comment]
Thanks for the bug report. Here is an example in the editor: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJcm0BrfSe2KQcWVDbKassmig3oIMCPKaIABmNHCCyvrmcKbu8EjKcG4RgkhMsQDy2jGymC5s2GwIIDZ2IAAegVExcQlN8UqY5jhw+gCODEjFdGo0pO5IZGTafJjd6BChVUrmDdGx8ejEpjEd7h1d+rIVfkh6NcFsmaCrzXMiu52zIIcIx6fVQA).

**Comment by ChiqueCode** [comment]
@domoritz Thank you for providing the example, however, this doesn't move the labels still. And if you check the code I posted, your example shows exactly what I have for the column already... This just doesn't work for whatever reason.

**Comment by domoritz** [comment]
Indeed already fixed in master. 

<img width="648" alt="Screen Shot 2021-01-07 at 16 20 38" src="https://user-images.githubusercontent.com/589034/103909687-db658480-50b8-11eb-9a6f-38ac776ca18a.png">
