### ISSUE TITLE
Threshold scale does not work with shape channel

### ISSUE THREAD

**Issue by tuner** [vega/vega-lite#7167]
Hi,

Vega-Lite seems to output an incorrect Vega spec when threshold scale is used on the shape channel.

Vega-Lite snippet:
```json
"shape": {
  "field": "b",
  "type": "quantitative",
  "scale": {
    "type": "threshold",
    "domain": [30, 70]
  }
}
```

Compiled Vega snippet (the scale type has changed into `ordinal`):
```json
{
  "name": "shape",
  "type": "ordinal",
  "domain": [30, 70],
  "range": "symbol"
}
```

Here's a full VL spec modified from the example in the documentation: https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscIAgiADQgBG8ATABwC+ZB8IAQuVfAKzdMtEAwp2pwALAGZ+IQiAAiI+AE4AjNNkBRRXDprmM1gDFt3KftkBxbSqXrWACW10A7HaIBJEzQYBdJiABbCAAnAGtWAAcAewBLADsoTgw4gGMosHiAc3hQAE8ckAAzGIwUMFZqCihciIxWOKiA+NROLCjgxLg4tBQUCggADxicBBAoGJTQkcLULAwKMEaIePgZlDmqmKgUOq6elAZ-LBiAL13QYtLyokqxmt2QAEc0CASt6BjEOoosFNRzu61VhQAAWwWwIKiZU4iyCKzguAkAAYyM4kT4KMFXpldrg6CiaEiURJCX5-GkUO0CpdoTdONUgURnq9xjBxl9Wn8dgUGQ9QeCsJDoQslvDESi0RiQL8QRgAg9EDFgjEMjh-DscXFrqBWdyiAAVMEQqHlQ4-EEQRkXEq0rhVe6sZlvNmfb7SrkA3nAo2Ck0w0VxPDI1How6HIA

Threshold+shape appears to have been functional at some point: https://github.com/vega/vega-lite/issues/4161#issuecomment-421424788

I can try to fix this issue if it is indeed a bug and not a feature.

**Comment by domoritz** [comment]
There are a couple of warnings in the editor console so I think this is working as intended. 

```
[Warning] Shape channel should be used with only either discrete or geojson data.
[Warning] Using discrete channel "shape" to encode "quantitative" field can be misleading as it does not encode magnitude.
[Warning] Channel "shape" does not work with "threshold" scale. We are using "ordinal" scale instead.
```

If you think this is a mistake, please file an enhancement request with what Vega code we should generate. Thanks for helping us with improving Vega-Lite.

**Comment by tuner** [comment]
Ah, ok.

My web browser (Chrome) appears to swallow all warnings. I only see "[Info] No error, infos, or warnings" on the console. Firefox and Safari appear to display those (and other) warnings. Have to check this on another computer...

**Comment by domoritz** [comment]
I think there is a bug in the editor where the warnings don't show up if you open the URL. Also, make sure to add the schema URL so that you get warnings about other validation issues.

**Comment by domoritz** [comment]
If I support threshold scales with this changes
<img width="890" alt="Screen Shot 2021-01-11 at 16 08 30" src="https://user-images.githubusercontent.com/589034/104199053-d1ef5b80-53db-11eb-88dd-ded129534c54.png">

You get this chart, which I would argue is misleading and therefore I think it's right not to support threshold scales for now. 

<img width="147" alt="Screen Shot 2021-01-11 at 16 07 36" src="https://user-images.githubusercontent.com/589034/104198942-b1bf9c80-53db-11eb-9486-3c6bc3f260b4.png">

If you have a compelling example, we can easily add support for threshold scales.

**Comment by domoritz** [comment]
Actually, this should be the diff. However, I think we intentionally limited shape to only support nominal data since shape only supports effective lookup. I could maybe be convinced that shapes can be used to encode ordinal data but there are better encodigns (color and size). 

<img width="797" alt="Screen Shot 2021-01-11 at 16 10 51" src="https://user-images.githubusercontent.com/589034/104199362-327e9880-53dc-11eb-83ab-623ce8df1c4c.png">

**Comment by tuner** [comment]
I stumbled upon this issue when trying to sketch a decorated lollipop plot:
<img width="554" alt="lollipop" src="https://user-images.githubusercontent.com/399972/104203979-69cd6380-5435-11eb-965a-607b1462e69e.png">

This example is quite an artificial one, and I agree that shape should generally be used only for encoding nominal data. However, use cases may exist, and perhaps artificial restrictions are not necessary(?). Of course, this particular example could be worked around by calculating a new "sign" field.

A more practical use case could be highlighting extreme values together with color (redundancy).

**Comment by domoritz** [comment]
Enabled support in https://github.com/vega/vega-lite/pull/7170.
