### ISSUE TITLE
include an example of a comet chart for trail mark

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#7188]
In this Altair issue https://github.com/altair-viz/altair/issues/2395, Zan Armstrong's [comet chart](https://www.zanarmstrong.com/infovisresearch) was introduced by @dkapitan. 

Given the limited examples at the trail mark [page](https://vega.github.io/vega-lite/docs/trail.html) the following Vega-Lite specification might be of interest.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/5186265/106204040-9c5cb780-61bc-11eb-9186-026072ee6318.png">

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJZjqC4+gEKmn5gAQBNGnEHKnlBsCDimNNaeTHCYAO5wcLKeAIwAnADMAEyeSLKBaenJiiCY2rkQAGZs2ghoANqgODTEbJj65nCmxcRIggzO6OZ+AcVk2mwMOEzm9SA92n6YM0oQIiAAunagVSOodSAFRUoFmRtKSBCzHV1KQ-7KG1sgUL1QDIJqAyVsAHIMCNFtAAKVSYf6Ua7aACUxQu7U62hATxegjeH0wX1B-zqAHITjj1p5+J4sQhcYcCbDLuhlP51Ej1kpkNoANb6UpIGh6JSJYLKGiyMhoUAAD2FIAqwwegwRxSWOC+1X5sl6cscA1k70EdhAM00Eql+nmi2WJXMCv0shCAtVOtp6i54sl9yN4RipvlXytCBteh1qwAXgNtobBob7OavgBHBi5BzqBykYrQXrBkBlQUDOoABgUyWzmyUTjIiWloB6fTg1LqmVzADYCzr405XO4LD4pZ4gUwGBB4IIIAQkFBtHAYU22GxBA4cPUQy6ZTczRb0DG43Q1M1nE9nbtdeHl17rSq-YznlPqk7Qyo6SgIyuQGvZPHN0mVii08oQpzZABZGjStmTbqvovj3J4AAit5dgApOOSjBH0CDyPqu7SiAqwYnKkb6EqvpIjqwSyJKQr6sWpbitUfjPvoTCtJgITFPyo5QA4cj6DAVEBnI6h+jYNhAA)

**Comment by domoritz** [comment]
Thank you. This is a great chart. I made a few improvements: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJZjqC4+gEKmn5gAQBNGnEHKnlBsCDimNNaeTHCYAO5wcLKeAIwAnADMAEyeSLKBaenJiiCY2rkQAGZs2ghoANqgODTEbJj65nCmxcRIggzO6OZ+AcVk2mwMOEzm9SA92n6YM0oQIiAAunagVSOodSAFRUoFmRtKSBCzHV1KQ-7KG1sgUL1QDIJqAyVsAHIMCNFtAAKVSYf6Ua7aACUxQu7U62hATxegjeH0wX1B-zqAHITjj1p5+J4sQhcYcCbDLuhlP51Ej1kpkNoANb6UpIGh6JSJYLKGiyMhoUAAD2FIAqwwegwRxQcmCcaFk70EdhAM00Eql+nmi2WJUcXwAauEYjM1asAF4Dbbawba+zmHBfACODFy8rUzWcKxRNpAZUFAzqAAYFMlMpslE4yIlpaAen04NS6pkwwA2ENRg0Kr5uMxeXz3TxApgMCDwQQQAhIKDaOAwtWYNhsQQOHD1W33eE3EpO13u2SehykJEKLu7dXamyM56t6riyXdml0lCO536N0euhe0e+3r+5QhTmyACyNGlIabhv0RYCngAIquSwBSRtKYJ9BDyTVLyerDE5RvdAAGU1hsNViD8WJxQgUo2BZAZlUEVUPzkSUhU1GM43Fao-CHfQmFaZtaiUfl6ygBw5H0GA8MtOR1D0CCbCAA)

**Comment by mattijn** [comment]
Nice! +1

**Comment by morberg** [comment]
Nice as this example may be I think it is not correct to call it a comet chart. See https://research.google/pubs/pub42901/

**Comment by domoritz** [comment]
Why not? Does the chart need to use a quantitive positional encoding to count as a comet chart?

**Comment by domoritz** [comment]
Why not? Does the chart need to use a quantitive positional encoding to count as a comet chart?

**Comment by mattijn** [comment]
Mea culpa. I thought a comet is just a comet, but when reading the paper in a bit more detail, it is about the combination of aggregate stats together with the variation in underlying subgroups. Since there is no aggregate stat here, its not really a comet chart indeed. 
Can we consider it a _tadpole chart_ instead? I was surprised, but this chart-name exists. See [here](https://public.tableau.com/profile/mtedw#!/vizhome/TadpoleCharts/TadpoleCharts).

**Comment by mattijn** [comment]
Apparently, this has been discussed before, see end of page [here](https://www.datarevelations.com/resources/showing-now-versus-then-consider-a-comet-chart/). 

> Update: There’s been a lot of discussion about this chart type on Twitter as well as uncertainty as to who came up with the term. See Van Armstrong’s paper about Visualizing Statistical Mix Effects and Simpson’s Paradox from 2014, Andy Cotgreave’s [2013 Information is Beautiful Awards submission](https://public.tableau.com/profile/acotgreave.tableausoftware.com#!/vizhome/infoisbeautifulmovies_0/Moviesandstories), and a Tableau forum discussion from 2012 where Andy first coins the term.

I leave it up to others to decide!

**Comment by morberg** [comment]
My bad, I thought Zan Armstrong had coined the term in 2014 for his specific chart type. The link you provided shows that the term comet chart had been used before that. I think comet chart would be fine to use here as well. Sorry for any confusion I might have caused.

**Comment by mattijn** [comment]
No problem whatssoever! It's good the fuzz is cleared. In the corresponding PR is also no reference to Armstrong's paper or Armstrongs-comet chart, the filename is just _trail_comet.json_. All safe I think.

**Comment by dkapitan** [comment]
thanks for digging into this @mattijn and @morberg. So we will leave it as it is, then?

**Comment by domoritz** [comment]
Thanks for looking into this. I'll leave the name as is then.
