### ISSUE TITLE
Shared projection with hconcat option

### ISSUE THREAD

**Issue by ebocher** [vega/vega-lite#7223]
The following json display two maps with the same projection properties : 
  "projection": {"type": "identity", "reflectY": true}

If I put the projection properties on top of hconcat the maps cannot be rendered (first json). If I add the projection in each encoding, it works (second json).

Not rendered

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [679628.6836060114, 5256518.895729772],
              [680451.4999805037, 5256544.166557725],
              [680421.0715927881, 5257532.580740529],
              [679598.3941120687, 5257507.310576666],
              [679628.6836060114, 5256518.895729772]
            ]
          ]
        },
        "properties": {
          "ID": 0,
          "ID_COL": 1,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.002561490885101728,
          "BUILDING_FRACTION": 0.09792132611937712,
          "HIGH_VEGETATION_FRACTION": 0.01331252086735109,
          "LOW_VEGETATION_FRACTION": 0.010311371954982747,
          "ROAD_FRACTION": 0.08464712031769843,
          "IMPERVIOUS_FRACTION": 0.003965912351941707,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [680451.4999805037, 5256544.166557725],
              [681274.3158018943, 5256569.5530019],
              [681243.7485184671, 5257557.966517513],
              [680421.0715927881, 5257532.580740529],
              [680451.4999805037, 5256544.166557725]
            ]
          ]
        },
        "properties": {
          "ID": 1,
          "ID_COL": 2,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.17544036649206088,
          "BUILDING_FRACTION": 0.011331706257638713,
          "HIGH_VEGETATION_FRACTION": 0.15674413805621407,
          "LOW_VEGETATION_FRACTION": 0.15256168248442295,
          "ROAD_FRACTION": 0.015442486920709242,
          "IMPERVIOUS_FRACTION": 0.0017577204111186863,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [681274.3158018943, 5256569.5530019],
              [682097.1310676043, 5256595.055063915],
              [682066.4248865184, 5257583.467909238],
              [681243.7485184671, 5257557.966517513],
              [681274.3158018943, 5256569.5530019]
            ]
          ]
        },
        "properties": {
          "ID": 2,
          "ID_COL": 3,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.028418585201792686,
          "BUILDING_FRACTION": 0.023351157075715737,
          "HIGH_VEGETATION_FRACTION": 0.06676092325423087,
          "LOW_VEGETATION_FRACTION": 0.5222017051773314,
          "ROAD_FRACTION": 0.010971330994183364,
          "IMPERVIOUS_FRACTION": 0.005212241598419751,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [682097.1310676043, 5256595.055063915],
              [682919.945775056, 5256620.672745398],
              [682889.1006943565, 5257609.084917326],
              [682066.4248865184, 5257583.467909238],
              [682097.1310676043, 5256595.055063915]
            ]
          ]
        },
        "properties": {
          "ID": 3,
          "ID_COL": 4,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.0008274015733299103,
          "BUILDING_FRACTION": 0.048175081344653425,
          "HIGH_VEGETATION_FRACTION": 0.04819217476513265,
          "LOW_VEGETATION_FRACTION": 0.048693969061799056,
          "ROAD_FRACTION": 0.03393907453919199,
          "IMPERVIOUS_FRACTION": 0.00000522088905662629,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      }    
    ]
  },

  "description": "A Map with unique values",
"projection": {"type": "identity", "reflectY": true},
  "hconcat": [
    {
      "encoding": {
        "color": {
          "field": "properties.WATER_FRACTION",
          "legend": {"format": "%", "title": "Fraction of area in percentage"},
          "scale": {"domain": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]},
          "type": "quantitative"
        }
      },  
      "height": 400,
      "mark": "geoshape",
      "title": "Building",
      "width": 400
    },
    {
      "encoding": {
        "color": {
          "field": "properties.BUILDING_FRACTION",
          "legend": {"format": "%", "title": "Fraction of area in percentage"},
          "scale": {"domain": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]},
          "type": "quantitative"
        }
      },  
      "height": 400,
      "mark": "geoshape",
      "title": "Water",
      "width": 400
    }
  ]
}
```

Rendered
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [679628.6836060114, 5256518.895729772],
              [680451.4999805037, 5256544.166557725],
              [680421.0715927881, 5257532.580740529],
              [679598.3941120687, 5257507.310576666],
              [679628.6836060114, 5256518.895729772]
            ]
          ]
        },
        "properties": {
          "ID": 0,
          "ID_COL": 1,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.002561490885101728,
          "BUILDING_FRACTION": 0.09792132611937712,
          "HIGH_VEGETATION_FRACTION": 0.01331252086735109,
          "LOW_VEGETATION_FRACTION": 0.010311371954982747,
          "ROAD_FRACTION": 0.08464712031769843,
          "IMPERVIOUS_FRACTION": 0.003965912351941707,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [680451.4999805037, 5256544.166557725],
              [681274.3158018943, 5256569.5530019],
              [681243.7485184671, 5257557.966517513],
              [680421.0715927881, 5257532.580740529],
              [680451.4999805037, 5256544.166557725]
            ]
          ]
        },
        "properties": {
          "ID": 1,
          "ID_COL": 2,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.17544036649206088,
          "BUILDING_FRACTION": 0.011331706257638713,
          "HIGH_VEGETATION_FRACTION": 0.15674413805621407,
          "LOW_VEGETATION_FRACTION": 0.15256168248442295,
          "ROAD_FRACTION": 0.015442486920709242,
          "IMPERVIOUS_FRACTION": 0.0017577204111186863,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [681274.3158018943, 5256569.5530019],
              [682097.1310676043, 5256595.055063915],
              [682066.4248865184, 5257583.467909238],
              [681243.7485184671, 5257557.966517513],
              [681274.3158018943, 5256569.5530019]
            ]
          ]
        },
        "properties": {
          "ID": 2,
          "ID_COL": 3,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.028418585201792686,
          "BUILDING_FRACTION": 0.023351157075715737,
          "HIGH_VEGETATION_FRACTION": 0.06676092325423087,
          "LOW_VEGETATION_FRACTION": 0.5222017051773314,
          "ROAD_FRACTION": 0.010971330994183364,
          "IMPERVIOUS_FRACTION": 0.005212241598419751,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [682097.1310676043, 5256595.055063915],
              [682919.945775056, 5256620.672745398],
              [682889.1006943565, 5257609.084917326],
              [682066.4248865184, 5257583.467909238],
              [682097.1310676043, 5256595.055063915]
            ]
          ]
        },
        "properties": {
          "ID": 3,
          "ID_COL": 4,
          "ID_ROW": 1,
          "WATER_FRACTION": 0.0008274015733299103,
          "BUILDING_FRACTION": 0.048175081344653425,
          "HIGH_VEGETATION_FRACTION": 0.04819217476513265,
          "LOW_VEGETATION_FRACTION": 0.048693969061799056,
          "ROAD_FRACTION": 0.03393907453919199,
          "IMPERVIOUS_FRACTION": 0.00000522088905662629,
          "AVG_HEIGHT_ROOF": 3,
          "STD_HEIGHT_ROOF": 0
        }
      }    
    ]
  },

  "description": "A Map with unique values",
  "hconcat": [
    {
      "encoding": {
        "color": {
          "field": "properties.WATER_FRACTION",
          "legend": {"format": "%", "title": "Fraction of area in percentage"},
          "scale": {"domain": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]},
          "type": "quantitative"
        }
      },  "projection": {"type": "identity", "reflectY": true},
      "height": 400,
      "mark": "geoshape",
      "title": "Building",
      "width": 400
    },
    {
      "encoding": {
        "color": {
          "field": "properties.BUILDING_FRACTION",
          "legend": {"format": "%", "title": "Fraction of area in percentage"},
          "scale": {"domain": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]},
          "type": "quantitative"
        }
      },  "projection": {"type": "identity", "reflectY": true},
      "height": 400,
      "mark": "geoshape",
      "title": "Water",
      "width": 400
    }
  ]
}
```

**Comment by domoritz** [comment]
Thank you for filing the issue and providing this great example. 

The specification is invalid and you can see warnings in the editor. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoTAE8ccNCABicNQwBOlpWThsEcTA9NoT5y+gACmyCpmRyiiBQbGwOyjSyavpGhoYAbADsAJxpAEwAHJRp+QDMaQAMFQCMVWIKAKy59Wn1VYX5WfUZuVkZ3QC6Cun55WKtlGJZUyP15SUZDU0tYhJVaS1d3fWDw6O5VZTlGVX1WbkZ+flVi131JbmU9SMZYuWNWTuZnVmFJVliNVylXyC0atyOlBKVTeGXW60+2TyhWKZUq5RqdTBLTalA6XR6fVy-WJAF8lDgHGwLA5MDRkpoQABJAAiaHKShZAH0AMIAeQAMmhrkzmZyAEq8gDqQqUkoAggAVACiYs51jFcu5CsZvIAcmzDuUlrUsuVLq10d18koAEIAVUZ-OZjN1AHE1RqtTr9ahyodemcqvc0jUsvNjrklAAJRmuqOcgBqStdSoViu9Hs12r1BvRJShTSB+UyJQtWSU-KlieTqfTeszXpzvsO0KhQeOnUm+XOYgWIAlctF6qz3tz+TEaV7VSBUNhPzEJQ5AFlAiqEzq7QBlBvZn1+8pzHKnaelqr-KoZI5KOUJ91RpWxqMK8W83nWNCLkCbhWi++P58Sm+bIkmSfgWFYtj2E4kSuO4njeL4IBmOBQQhGEERKNEsTxIkmD0qkuxjAckzTG8cygks9QrJQawbIS2xDMU04vJCJwjG0-yLlizRZI8dwHmenxXLkC6UC8+StOOmTXGCGT1F0lA5NiclBkJewHEcJxnBcVw3HJ9yPM8rzvGpRETFMPxkfMNzLKs6zyfRxL9GSIAUlScA0nSBgMiyMoijyApoJG-kStKqDCvKyqqsOjZ7jRckrHM6yTECFSXLaDpOi67oxbuuY1PmF6VE0sIlCCQbRo+1Ypmmu47qOzYnJkKxBjMeS1FeICVpK1W1nVuUNX6JzGsUInjmIuQ9PUSgDkOnp5c26JURNYjFmcRzlGcE3LquYrrryW71U2+6WpsQIAjUbTFGkn43neD5xgBr7vqgn7fr+D1Pi+QG+iBChgQENh2JgjjOCAsEeF4PgMshgPBKE4TyJhMRxAkSTeQRTE9qxTzoh0C42TxfElAJHyMd2m0ZDRUKVLCoxcZRnSHPJlR-CcQmpWkExjcWkmYiVTwlBMXybbkZVCdOoniXz0l6Q5in2RerQlBL2NQrjHEE9xaS8fJJPoh8pLkpS1K0vSoC+agwVcnygqvRyoqhX5kUqkdcVGuObRPI0lpnNdGWOs6bpu7mYunicl5yccXTWSAMZxr1tUZgNx2HOsdNnPcVFi2afbdYnda6iHzaNJNlpvBeGSFXU-a8oOxf7tCvRBiTUwAqUZQ14yK5rhu24p+7bz7JNAKnJ7vStNet6cn+j3fS9b0-jPn1PT95R-QDEHA6DMFuJDCEw-4Vjw+hSNRCjOHoykwxAr01PQpkFRa4z9TM7MN1ZOz5M9GeiljH0sxmg2TyH6TIPY7g-A5pcXi0JKicWaNNWSFReJmkmBeYMHNKhcxWpcbE445alGFtkUW4tv6U3vrTJ+DMEFMzeO-Nm2wjauRNh5M23kLasntv5W2aAu6OylM7RUrsB65gPN2F4S0q73CmK2AOWVg4iMWqtJWZogwrBaCUCa0045VSTDVQuDdDjKMDC8WEytcgtArFWPRfVk7zUGkYtafwdaVAvFMN4aQZp1zmiOVOcw-h-COGMNmn8pg7V7gdfu9i-EHgPKXM0HQPF5DyOWEAd1l7-nnh+JQ70Mlz0Ai9deJJnJKGUPoKADgaA4FpBEdAcoAAES4kA4HqQAdzoDAepDBZA0AAI56HqdoXQyRjZsEkHAKANT5CHxQiAGgZTZC0jMJEJwAAzQQEzMAAE00BeD0C5GA0RZBQDUEYUAcBjlsBwmQRC0RBCxEQqsukghlBWDcqbLylAXbRWifqJQGzXCyFeQyVZsRkCYCsAAUkiEsjZEEHBIEmewWQ9S2CrPqUgJwSB6kJHqdSKAFz1CuBAC5aAOgAigGUO4JACQjDsiGgoP0kY-SLj9HUP001QElKQkfdA-SkCLLoGoGgpASUHLgDQMgWBeEHiUMgBwABrKwsEIAwGaWDWFgMbQMBoC8hINylDtOUPQGV69-ogAudEa5tyQgPJBc84FzD3KeX0JQe0gdsoh3+eQC5wLQCgocOCqFMK6BwvQNYBFSK5CovRZiuwOKUX4sJUgYlpKTlhspdS2lqBDD0pooyygzLIQFvZY8AtaRuWwysPywV6haSir+hgCVUqIWoFeOyEA8qlXoBVWq8CShNVWElEkBwkQjUmrbQeYpJIgA)

Vega-Lite does not support projections in concats right now. 

You can use a config as described in the docs. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoTAE8ccNCABicNQwBOlpWThsEcTA9NoT5y+gACmyCpmRyiiBQbGwOyjSyavpGhoYAbADsAJxpAEwAHJRp+QDMaQAMFQCMVWIKAKy59Wn1VYX5WfUZuVkZ3QC6Cun55WKtlGJZUyP15SUZDU0tYhJVaS1d3fWDw6O5VZTlGVX1WbkZ+flVi131JbmU9SMZYuWNWTuZnVmFJVliNVylXyC0atyOlBKVTeGXW60+2TyhWKZUq5RqdTBLTalA6XR6fVy-WJAF8lDgHGwLA5MDRkpoQABJAAiaHKShZAH0AMIAeQAMmhrkzmZyAEq8gDqQqUkoAggAVACiYs51jFcu5CsZvIAcmzDuUlrUsuVLq10d18koAEIAVUZ-OZjN1AHE1RqtTr9ahyodemcqvc0jUsvNjrklAAJRmuqOcgBqStdSoViu9Hs12r1BvRJShTSB+UyJQtWSU-KlieTqfTeszXpzvsO0KhQeOnUm+XOYgWIAlctF6qz3tz+TEaV7VSBUNhPzEJQ5AFlAiqEzq7QBlBvZn1+8pzHKnaelqr-KoZI5KOUJ91RpWxqMK8W83nWNCLkCbhWi++P58Sm+bIkmSfgWFYtj2E4kSuO4njeL4IBmOBQQhGEERKNEsTxIkmD0qkuxjAckzTG8cygks9QrJQawbIS2xDMU04vJCJwjG0-yLlizRZI8dwHmenxXLkC6UC8+StOOmTXGCGT1F0lA5NiclBkJewHEcJxnBcVw3HJ9yPM8rzvGpRETFMPxkfMNzLKs6zyfRxL9GSIAUlScA0nSBgMiyMoijyApoJG-kStKqDCvKyqqsOjZ7jRckrHM6yTECFSXLaDpOi67oxbuuY1PmF6VE0sIlCCQbRo+1Ypmmu47qOzYnJkKxBjMeS1FeICVpK1W1nVuUNX6JzGsUInjmIuQ9PUSgDkOnp5c26JURNYjFmcRzlGcE3LquYrrryW71U2+6WpsQIAjUbTFGkn43neD5xgBr7vqgn7fr+D1Pi+QG+iBChgQENh2JgjjOCAsEeF4PgMshgPBKE4TyJhMRxAkSTeQRTE9qxTzoh0C42TxfElAJHyMd2m0ZDRUKVLCoxcZRnSHPJlR-CcQmpWkExjcWkmYiVTwlBMXybbkZVCdOoniXz0l6Q5in2RerQlBL2NQrjHEE9xaS8fJJPoh8pLkpS1K0vSoC+agwVcnygqvRyoqhX5kUqkdcVGuObRPI0lpnNdGWOs6bpu7mYunicl5yccXTWSAMZxr1tUZgNx2HOsdNnPcVFi2afbdYnda6iHzaNJNlpvBeGSFXU-a8oOxf7tCvRBiTUwAqUZQ14yK5rhu24p+7bz7JNAKnJ7vStNet6cn+j3fS9b0-jPn1PT95R-QDEHA6DMFuJDCEw-4Vjw+hSNRCjOHoykwxAr01PQpkFRa4z9TM7MN1ZOz5M9GeiljH0sxmg2TyH6TIPY7g-A5pcXi0JKicWaNNWSFReJmkmBeYMHNKhcxWpcbE445alGFtkUW4tv6U3vrTJ+DMEFMzeO-Nm2wjauRNh5M23kLasntv5W2aAu6OylM7RUrsB65gPN2F4S0q73CmK2AOWVg4iMWqtJWZogwrBaCUCa0045VSTDVQuDdDjKMDC8WEytcgtArFWPRfVk7zUGkYtafwdaVAvFMN4aQZp1zmiOVOcw-h-COGMNmn8pg7V7gdfu9i-EHgPKXM0HQPF5DyOWEAd1l7-nnh+JQ70Mlz0Ai9deJJnJKGUPoKADgaA4FpBEdAcoAAES4kA4HqQAdzoDAepDBZA0AAI56HqdoXQyRkayAAGY0DIIhNykg4BQBqfIQ+KEQA0DKbIWkZhIhODGYIOZmAACaaAvB6D+hgaIsgoBqCMKAOAFy2A4SmQyaIghYiIQmXAQQygrBuVNl5SgLtorRP1EoXZrhZBfIZGM2IyBMBWAAKSRA2bsiCDgkDzPYLIepbAxn1KQE4JA9SEj1OpFAW56hXAgBctAHQARQDKHcEgBIRh2RDQUH6SMfpFx+jqH6aaoCSlISPugfpSB1l0DUDQUglKXLwEmVgXhB4lDIAcAAaysLBCAMBmlgyRYDG0DAaCfISFMpQ7TlD0AVevf6IBbnRAeYhZ5rzIV0k+d8lhnl9CUHtIHbKIcQXkFuRC0AUKHAwvhYiugyL0DWFReiuQWKcV4rsISzFJKyVIApVSy5Ua6UMqZagQwLKaJssoByyEJaeWPBLWkAVsMrAirFeoWkUrTmyrIPK1Arx2QgGVWq9AGqtXgSULqqwkokgOEiGai1naDzFJJEAA)

If you think we should support projections in concats (and essentially do what the config does), please file an enhancement request.

**Comment by mattijn** [comment]
You also can use a `repeat` and keep the `projection` in the `spec`: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABAFkkOQwHc6MQw1k0AjgziHiSQc4iKVSTClSgbh5qaADaoJgAnjhwaCAAYnC+DOqxSmRwbAhwmOqRaBHRsegACmyCkWRy3lBsbOrKNLK+Iaih7QBsAOwAnB0ATAAclB2DAMwdAAxTAIwzYgoArP2LHYszw4M9i139PV27ALoKoaOTYuuUYj03g5OLk2NdSytrYhIzHWs7u4vHp3cxP0ZpRJl0Zosev0uoNBjMXjtFmN+pRFncumJ7nt-t1tj1hmMemI5v1poNnstEWDKGMZvcul8vjjegNhqMJtNJnMFpS1htKFsdnsDv1DmKAL5KHDqNgxdQ6VqgACSABE0JMlKqAPoAYQA8gAZNDwkDagBKeoA6salJb9AAVACiZq18TN+h19qVeoAcurQZNXvMepNYesubtBkoAEIAVSVBpVSp9AHFXe7Pd6-ahJqD9lCZsiOnMek9wf0lAAJJUpytagBqjpTjvtDqz6Y9Xt9-q5Y1pK1Jg26Y3DPSUBqtDabLbbvo7me7OdBdNphfB22ug2hYmeIAt+hV8672dzobEHR3M1JtIZ+LEY01xhKzvr3tjAGUj1me48+pCryOMxEjMXRgko+j1mmlaOjWlb2lqFp6vEaAPiA772oe0GwfBiHITm4qSoUMRxIkySpN4GRZDkeQFCAUTEaU5SVNUSi1PUjTNJgrTtAC5yXNctz3I8FKvIs7yUJ83win8JyjFeGI0hCdwbESD68qsPSokikxcj0OJwv096UBigzrIM57ggiXSLDslB9Hy1mFvp5zAqC4KQtCsLwpS1nIqi6KYssemyYC-E3PiQlPAibwfF8NnSWKhySiA0qynA8o0IqppqqgJravqRqoBW2UIVaNogHaToum6nbfkuIFiZiEwXlCnKwjG8aJsmaY1QuJ7LoWN7TCsDJjOShZVrBU7Nq2x5fouuYQt07yFncqzApiu4Tpa00znNvXHv6EJBqMhnmUCeyLEo+6HgddWnhC7xnR0rWgVCQKPs+ZqvnqH7zf1OkNSK5xzHMQ5DqhEFQTBtY4XqSEoUo6GYTDcGlQj+GEXRRQkUkmApGkICUdkuT5AE2MMSAZQVFU8isXUDRNC0XhtJ0BkKbSaJcls97RRpWljIDwUAqS+wSbS0wMucamidsoI2dMhIQvppJfFcZ1DmZPIjWiYxXLikxQmN+lXkZJla903k67Z9nrI5Ywm9uilcypvPqS9AtC4lyWpXKCos8qOXFflhqIyVFrWrltoOs6-09kMxKmaZpIgVCowdB1CZJqmcdLoGfbrBCoHWe5XRRSA1a1rts3tndC2gl8UtGysQKC+S46To2M2zj6ue5ss-Qp6Bdtl7SCx7nqB598uhvgn2hvAeMEzj0qT4vm+n51wDWJXoZEJ3kBjngZBWpYbD6N4ahyOn6jcMY5MBEKERxQJHjBMUZkJM0eT9Ev9TzF0xAGxRmnFuJs1Fl0cWdJuhTDdrLRY8sHgdCVjJEWPQgJ2QuAcB4qxooDFzN0bcSJ8Qq1hJpOk0xVKrCuj5KYmkzzoLLv0DoKtpgdHVmIWEfJzJWV1vrXoht+jGxChAqBktYEy2oXLe4SCUHeylDKP2mUA7ZTDiHQqK9DwR3KpVWOW8fyhm3FyHYfY9joMeJnLqOd9F504Q1UMhZ3hrDGECK6Fcppdz2rXDMh1bFwgLBiBk6wixuO2tXHu09zhDlLH0EMxZeghlwRPKeNjTx9hiWCC4St0E3E+uvX6m8fH3QDDpLEg4tj3C+MwvYx9obYQvmHa+Z80a4XVARJKShchIFkBAAAZvUBAYRQBQHcFABgggWhxGUMkBAlBfbpX9pQXR1UindiUEgFmCR1BICgDoOQlgWjqBAFjEZggxkTK4lMmZczFELOUZQOMWdupx3WZs+I2zdm6EMEwBgNBBAcTIMc44IBUgxF8LRGUFgwhbJ2Xs2QByuJHKUO82FXyfl-IBSADpIK1DlFILRaA7hijDPKPUOITRVAxFkKoWQmBjnJR0JgQQxK6JwAAB50vQGQQQbAmDuEMIy5lxylAQBiFAWiVhlD0BQjpJQ8AaBkCwMaWVKUZSSDgJ86oP8cboBoDSxl+QlCpF6cy3ZABNNAuRnAMroEKn+7LOU4rBVxZQArbWxGSsgdQABrOIlEIAwDMITOAshaiYvJrUHlRzya9Myv8iFcBnVxEhcKimL8nDdMZb4Gg+KlDMoyNS2i-T1DIEdQAUlTYSu1oBlBZCQE0MIGpFoKFzBWXMD5cwLH7i2kYSUCIESAA)
Only thing I cannot manage to do is to encode a `title` to the repeated `row`. Currently the title is the same for all repeated views, and only the legend-title reflects the row-parameter.
<img width="363" alt="image" src="https://user-images.githubusercontent.com/5186265/107433181-4e837000-6b29-11eb-8fab-e943ebf69bc4.png">

Not sure if `title` also should be an encoding channel.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A Map with unique values",
  "data": {...},
  "transform": [
    {"calculate": "datum.properties.WATER_FRACTION", "as": "Fraction water"},
    {"calculate": "datum.properties.BUILDING_FRACTION", "as": "Fraction building"}
  ],
  "repeat": {"row": ["Fraction water", "Fraction building"]},
  "resolve": {"scale": {"color": "independent"}},
  "title": {"text": "global title"},
  "spec": {
    "width": 300,
    "height": 100,
    "projection": {"type": "identity", "reflectY": true},
    "title": {"text": "repeated title"},
    "mark": "geoshape",
    "encoding": {
      "color": {
        "field": {"repeat": "row"},
        "type": "quantitative",
        "legend": {"format": "%"},
        "scale": {"domain": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]}
      }
    }
  }
}

**Comment by ebocher** [comment]
Other interesting modeling thanks @mattijn
