### ISSUE TITLE
Typescript Refactor 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#723]
- [x] setup TS with istanbul code coverage 
- [x] Describe the schema in TS

- [x] enable more tslint rules (and fix issues)
  - [ ] replace `var` with `let` and `const`

**Comment by kanitw** [comment]
- [ ] rename `schemautil.merge` => `mergeDeep` ?

**Comment by kanitw** [comment]
- [ ] refactor `vl.ts` — there should be a better way to declare `vl` namespace

**Comment by kanitw** [comment]
- [ ] Using enum?

**Comment by kanitw** [comment]
- [ ] missing source map for the compiled file

**Comment by kanitw** [comment]
- [ ] `schema.test.ts` and `validate.test.ts` still use `require` style import, which is inconsistent

**Comment by kanitw** [comment]
- [ ] add compiling individual files to the watch?

**Comment by domoritz** [comment]
For code coverage, we could use https://github.com/SitePen/remap-istanbul but it doesn't seem worth the effort. We get code coverage on js and that's sufficient.

**Comment by kanitw** [comment]
I read it and I'm still not sold.  The answer is dated.  If the tool isn't too hard to setup, I don't see why we should not use it. 
That said, I think it's a lower priority so let's ignore it for now.

**Comment by domoritz** [comment]
Pretty much done. The deepMerge rename is not really necessary and I don't want to do a big var -> let/const rename right now.

**Comment by kanitw** [comment]
Shouldnt we only close thing when we no longer plan do it at all?

In this case, moving to later milestone or unassign might be a better
option.

**Comment by kanitw** [comment]
Re deepMerge -- maybe move it to the general refactor issue?

**Comment by kanitw** [comment]
fixed in #905 and the rest is forked to #907
