### ISSUE TITLE
Removing "point" mark results in incorrect "href" target link

### ISSUE THREAD

**Issue by runeksvendsen** [vega/vega-lite#7243]
When I click on a point in this [Vega Editor chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAI6YAnmgDMVsQA4rSgE4N5mkJhoI4AfQjqnTDQQACYABgBGAE5+MJiQsQAVCLtUAFYw1DCANko7BOyQgHYALUUQGmU0bKVPbx84WSr0cOjY+KTo1C6rCMorbLEootKQAF8lKAYnJ0aoS3QADUSy51cfSuqJ0wtq7LCRtbdQOt9-JEDg1pi4-gTk1JzUe0psqzsP0aVN9NqvX0azVCkRuHQeqAG3Ssr2GYRC2TKExAUxmcwWIGWqxALlkG2aaW2IDMCxCdjCQzsRzQJ3+fgCQRaIPad06UQhIXSdkoaSiOTEISxPyKf3qgKuTNu93CWQ5CX6ESKYTSoyRKNmsnmwUWACUAArlHF4tBFQnEtAREJRbJFCI1bGuakeWnnS6MtqSpIhDlpNJZaH5MRWKIRQXNCIREUApri91gkJWVAJRO5NIRMRiFWTabqzVLPUG9Y-cOm3aoKJpQZRKnuU50i4M4GxlnJIrdVupygJMl2NKhtBiSMNaNu0HNhXPVsKyjlkLRAXjLOojXozEF3E-MQlhZpKxFEJpas0+ouhvXZlSzLFCFFbnZNJ2KJ2PuoSlO0XDxuji-pVvkvI5DIrERRccxXFY1yNF8t3NIoHCKKJHHtY43zOekYy-TpfSsb1cnsQZ72fEJBzFEdz06bIZUTCQomDXpewXZFszRLV8yOSCQmg7oogzHlXxxR1axPdCyJbNt0j6Lswh7Z8BxQocgTPD1RIzNtpzSWconnVUmOXFj9TYjdOLEO9yUPOShNIpTbS4zlKBGbCFWfRDaxIz8ROsoZE2hFIrVtYDGKXXMMXAgzmisTi5wQ-kzMEtDLLBayunvOyigcr4KjC4iP0UhKKM8+NKB87I-IYtVmLzfSkMg8KFB2BYrBBA8kIE504rcpSvT9LIwkock7zeZ8IjCLKFIlOMOWwxMQn6Aod38srdKWEKqqLMJOPeNIxGG5qa1a+thI6iJugolJOyKewaOfKs5NcnLm1nZ5fTEPoGreXp5p0oLV1CtAok4-Ziu2-jduPNq7vuCIsJwyg8LEAjyh+IibuysaxwouEqOnWjIY+wKwKxQ1EfWwpZxivbXXahK2Um5KeT5edvmaYVkdGptvwxuVekVZVcdArVlsJpnOLsc7hiR4Gj1Q-b4vujkwgTMIer6isgIRsNtpclG2c9CbZWm7DjLm0rPpXViVvViLhl6OIydB6XKbHR48q5N4PhF58ms11mMPBSEImhbJYXhXnyoxM3BbQAlaqJUtBgfexbalinwasRJpXeCEoleKTucGkaDviVOHoe9T+kDbiEWNvG9IgotONg+NH0Tutk9RqUjsSrliguqIrvzmX28e54XpyGwQyrvmKtr5o-ujs10i9eXmYl8ywbbz1L1bXdb3vR9n1fL2C-uzJlSyCQyRM1XtOrqefqgufSzTfI7RX2L7fBnX0l9eW8gSINx8ZuaCMLMj5SgTEmeE3I0wZhDotYKBNCxhgiBFW0gYhjNwsg7CGqQMhZFyAGQo6Ufh2kPgPVkNlej9ErCMWBX1w6IK2AAXSRAAd0qPQfsGQlDwBoGQLA1hFa1CcEgWQEAABmbAnAICMKAMRNBBCYDgE4YIqhMAMAQJQQWAACAAhAAXi0REBcoAoA6CmIINQcBggRDgPwbIWiABUWjVHqMoGaJQSADDoGJD4BA0jCSmMEOYyxwQADkABiRR-hUChK0QAamcWoVxEcPFeJANMQQ4xGFKDmGwZQNBZBkEdAAD0dHIuAgggQ4koG-S4tRzA4CsegRRCAcCSJ0OUTwmBBBNJAIkf4DFMBsDYAomgOAZEgHKZU4IC1NR-G6b0gAwibTpDTemyDYAgApHTCRTKBD4vxnS6A9OCAARQYCIrp5gtEAAoACydytEAFUADKAARAAlKsxpwQTAXNkF0tQNBSDGMmTQCpVTXA1PJkEeZJz0D9O8N83pLS2nCMybs8F0z0ApKdAs4I2pXBaIAJJvORcEDZWzZA7Ojns4IGSjn4vQE87UAAZcl6BKXbIxdkjAswxFlKxUCBlYwkQWPMEoiZuT8mFMdFAEZkjBUQpmSs+pPzOWbO5Yy+FIBll41uQATS+UiBYsihW-IsL46Rarel-MuXQIFIK4W9POfaiwtyHnPPecasVSAJXKNQMYEAyAnAAGtgjCFkFYwkIbw3oDaQUoIhJMDCNERIqREy5EKMle4CAFS4BQE8HIYIMA2CkGUaK3lsaI0FOjcw6OKaRHiMkdIwNoAcDArYA2WZlglDaF0Lay1hylBkCcGwBgOAmALEMEhaFdtLjMKrRcON9oTk5I1HkgpRT3BsBwEgKAdBTXIjkPkotyF+16DQD1RCeaemFvYG4DAZbJVIgvU0taSJb0FrPY6Ut5aBJrOCBALda6wUQq8TO6ptSgi8qjRcfQDIU16CUMW9ACBx15ufconJrTSwgA2VG8oUAekXGCOhhgmGGBJsrWMIAA) the URL successfully changes to `#/test:<run_id>`. E.g. when I hover over a point with a **Run ID** of **7** then the appended URL hash is `/test:7`. 

However, when I remove the `"point"` mark, clicking on a point always navigates to `/test:2`, regardless of the **Run ID** of the point that is clicked.

Spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "qty": 33483,
        "run": {
          "time_start": "2019-09-24T18:50:06.824627Z",
          "id": 6,
          "time_end": "2019-09-24T19:19:31.364977Z"
        },
        "currency": "XTZ",
        "run_id": 6
      },
      {
        "qty": 66077,
        "run": {
          "time_start": "2019-09-24T18:06:48.638887Z",
          "id": 5,
          "time_end": "2019-09-24T18:36:13.697026Z"
        },
        "currency": "XTZ",
        "run_id": 5
      },
      {
        "qty": 280498,
        "run": {
          "time_start": "2019-09-24T19:32:58.590642Z",
          "id": 7,
          "time_end": "2019-09-24T20:02:24.317057Z"
        },
        "currency": "XRP",
        "run_id": 7
      },
      {
        "qty": 1296716,
        "run": {
          "time_start": "2019-09-24T22:55:03.824391Z",
          "id": 11,
          "time_end": "2019-09-24T23:24:26.51447Z"
        },
        "currency": "XRP",
        "run_id": 11
      },
      {
        "qty": 95649,
        "run": {
          "time_start": "2019-09-24T17:17:51.248085Z",
          "id": 4,
          "time_end": "2019-09-24T17:47:17.952192Z"
        },
        "currency": "XTZ",
        "run_id": 4
      },
      {
        "qty": 53725,
        "run": {
          "time_start": "2019-09-24T20:27:37.565898Z",
          "id": 8,
          "time_end": "2019-09-24T20:57:04.806503Z"
        },
        "currency": "XTZ",
        "run_id": 8
      },
      {
        "qty": 1783793,
        "run": {
          "time_start": "2019-09-24T15:32:56.486458Z",
          "id": 2,
          "time_end": "2019-09-24T16:02:24.991315Z"
        },
        "currency": "XRP",
        "run_id": 2
      },
      {
        "qty": 1947598,
        "run": {
          "time_start": "2019-09-24T17:17:51.248085Z",
          "id": 4,
          "time_end": "2019-09-24T17:47:17.952192Z"
        },
        "currency": "XRP",
        "run_id": 4
      },
      {
        "qty": 46504,
        "run": {
          "time_start": "2019-09-24T16:19:58.773217Z",
          "id": 3,
          "time_end": "2019-09-24T16:49:23.189616Z"
        },
        "currency": "XTZ",
        "run_id": 3
      },
      {
        "qty": 1929342,
        "run": {
          "time_start": "2019-09-24T16:19:58.773217Z",
          "id": 3,
          "time_end": "2019-09-24T16:49:23.189616Z"
        },
        "currency": "XRP",
        "run_id": 3
      },
      {
        "qty": 30195,
        "run": {
          "time_start": "2019-09-24T22:03:00.046563Z",
          "id": 10,
          "time_end": "2019-09-24T22:32:22.324653Z"
        },
        "currency": "XTZ",
        "run_id": 10
      },
      {
        "qty": 38540,
        "run": {
          "time_start": "2019-09-24T21:16:18.274899Z",
          "id": 9,
          "time_end": "2019-09-24T21:45:41.306331Z"
        },
        "currency": "XTZ",
        "run_id": 9
      },
      {
        "qty": 60610,
        "run": {
          "time_start": "2019-09-24T15:32:56.486458Z",
          "id": 2,
          "time_end": "2019-09-24T16:02:24.991315Z"
        },
        "currency": "XTZ",
        "run_id": 2
      },
      {
        "qty": 36221,
        "run": {
          "time_start": "2019-09-24T19:32:58.590642Z",
          "id": 7,
          "time_end": "2019-09-24T20:02:24.317057Z"
        },
        "currency": "XTZ",
        "run_id": 7
      },
      {
        "qty": 874972,
        "run": {
          "time_start": "2019-09-24T22:03:00.046563Z",
          "id": 10,
          "time_end": "2019-09-24T22:32:22.324653Z"
        },
        "currency": "XRP",
        "run_id": 10
      },
      {
        "qty": 1973109,
        "run": {
          "time_start": "2019-09-24T18:06:48.638887Z",
          "id": 5,
          "time_end": "2019-09-24T18:36:13.697026Z"
        },
        "currency": "XRP",
        "run_id": 5
      },
      {
        "qty": 648948,
        "run": {
          "time_start": "2019-09-23T20:38:39.608705Z",
          "id": 1,
          "time_end": "2019-09-23T21:21:52.343946Z"
        },
        "currency": "XRP",
        "run_id": 1
      },
      {
        "qty": 782398,
        "run": {
          "time_start": "2019-09-24T21:16:18.274899Z",
          "id": 9,
          "time_end": "2019-09-24T21:45:41.306331Z"
        },
        "currency": "XRP",
        "run_id": 9
      },
      {
        "qty": 522037,
        "run": {
          "time_start": "2019-09-24T20:27:37.565898Z",
          "id": 8,
          "time_end": "2019-09-24T20:57:04.806503Z"
        },
        "currency": "XRP",
        "run_id": 8
      },
      {
        "qty": 14826,
        "run": {
          "time_start": "2019-09-24T22:55:03.824391Z",
          "id": 11,
          "time_end": "2019-09-24T23:24:26.51447Z"
        },
        "currency": "XTZ",
        "run_id": 11
      },
      {
        "qty": 1164349,
        "run": {
          "time_start": "2019-09-24T18:50:06.824627Z",
          "id": 6,
          "time_end": "2019-09-24T19:19:31.364977Z"
        },
        "currency": "XRP",
        "run_id": 6
      }
    ]
  },
  "width": 450,
  "height": 300,
  "transform": [
    {"filter": "datum.run_id != 1"},
    {"calculate": "1e-6 * datum.qty", "as": "qty_mm"},
    {"calculate": "'#test:' + datum.run_id", "as": "url"}
  ],
  "encoding": {
    "x": {"field": "run.time_start", "type": "temporal", "title": "Time"},
    "tooltip": [
      {"field": "currency", "title": "Currency", "type": "nominal"},
      {"field": "qty_mm", "title": "Quantity (MM USD)", "type": "quantitative"},
      {"field": "run.time_start", "title": "Time", "type": "temporal"},
      {"field": "run_id", "title": "Run ID", "type": "nominal"},
      {"field": "url", "title": "URL", "type": "nominal"}
    ],
    "href": {"field": "url"}
  },
  "layer": [
    {
      "encoding": {
        "color": {
          "field": "currency",
          "type": "nominal",
          "title": "Currency (Y)"
        },
        "y": {
          "field": "qty_mm",
          "type": "quantitative",
          "title": "Quantity (MM USD)"
        }
      },
      "layer": [
        {"mark": "line"},
        {"mark": "point"},
        {"transform": [{"filter": {"selection": "hover"}}], "mark": "line"}
      ]
    },
    {
      "transform": [
        {"pivot": "currency", "value": "qty_mm", "groupby": ["run.time_start"]}
      ],
      "mark": "rule",
      "encoding": {
        "opacity": {
          "condition": {"value": 0.3, "selection": "hover"},
          "value": 0
        }
      },
      "selection": {
        "hover": {
          "type": "single",
          "fields": ["run.time_start"],
          "nearest": true,
          "on": "mouseover",
          "empty": "none",
          "clear": "mouseout"
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Thanks for the report @runeksvendsen. This is unfortunately a limitation with how the lower-level Vega library enables interaction on multi-element marks. Namely, with line and area marks, the constituent points aren't exposed as interaction targets; only the overall line/area is as a single target.

As a workaround, I suggest keeping the `point` marks around but setting their `opacity` to `0` [like so](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAI6YAnmgDMVsQA4rSgE4N5mkJhoI4AfQjqnTDQQACYABgBGAE5+MJiQsQAVCLtUAFYw1DCANko7BOyQgHYALUUQGmU0bKVPbx84WSr0cOjY+KTo1C6rCMorbLEootKQAF8lKAYnJ0aoS3QADUSy51cfSuqJ0wtq7LCRtbdQOt9-JEDg1pi4-gTk1JzUe0psqzsP0aVN9NqvX0azVCkRuHQeqAG3Ssr2GYRC2TKExAUxmcwWIGWqxALlkG2aaW2IDMCxCdjCQzsRzQJ3+fgCQRaIPad06UQhIXSdkoaSiOTEISxPyKf3qgKuTNu93CWQ5CX6ESKYTSoyRKNmsnmwUWACUAArlHF4tBFQnEtAREJRbJFCI1bGuakeWnnS6MtqSpIhDlpNJZaH5MRWKIRQXNCIREUApri91gkJWVAJRO5NIRMRiFWTabqzVLPUG9Y-cOm3aoKJpQZRKnuU50i4M4GxlnJIrdVupygJMl2NKhtBiSMNaNu0HNhXPVsKyjlkLRAXjLOojXozEF3E-MQlhZpKxFEJpas0+ouhvXZlSzLFCFFbnZNJ2KJ2PuoSlO0XDxuji-pVvkvI5DIrERRccxXFY1yNF8t3NIoHCKKJHHtY43zOekYy-TpfSsb1cnsQZ72fEJBzFEdz06bIZUTCQomDXpewXZFszRLV8yOSCQmg7oogzHlXxxR1axPdCyJbNt0j6Lswh7Z8BxQocgTPD1RIzNtpzSWconnVUmOXFj9TYjdOLEO9yUPOShNIpTbS4zlKBGbCFWfRDaxIz8ROsoZE2hFIrVtYDGKXXMMXAgzmisTi5wQ-kzMEtDLLBayunvOyigcr4KjC4iP0UhKKM8+NKB87I-IYtVmLzfSkMg8KFB2BYrBBA8kIE504rcpSvT9LIwkock7zeZ8IjCLKFIlOMOWwxMQn6Aod38srdKWEKqqLMJOPeNIxGG5qa1a+thI6iJugolJOyKewaOfKs5NcnLm1nZ5fTEPoGreXp5p0oLV1CtAok4-Ziu2-jduPNq7vuCIsJwyg8LEAjyh+IibuysaxwouEqOnWjIY+wKwKxQ1EfWwpZxivbXXahK2Um5KeT5edvmaYVkdGptvwxuVekVZVcdArVlsJpnOLsc7hiR4Gj1Q-b4vujkwgTMIer6isgIRsNtpclG2c9CbZWm7DjLm0rPpXViVvViLhl6OIydB6XKbHR48q5N4PhF58ms11mMPBSEImhbJYXhXnyoxM3BbQAlaqJUtBgfexbalinwasRJpXeCEoleKTucGkaDviVOHoe9T+kDbiEWNvG9IgotONg+NH0Tutk9RqUjsSrliguqIrvzmX28e54XpyGwQyrvmKtr5o-ujs10i9eXmYl8ywbbz1L1bXdb3vR9n1fL2C-uzJlSyCQyRM1XtOrqefqgufSzTfI7RX2L7fBnX0l9eW8gSINx8ZuaCMLMj5SgTEmeE3I0wZhDotYKBNCxhgiBFW0gYhjNwsg7CGqQMhZFyAGQo6Ufh2kPgPVkNlej9ErCMWBX1w6IK2AAXSRAAd0qPQfsGQlDwBoGQLA1hFa1CcEgWQEAABmbAnAICMKAMRNBBCYDgE4YIqhMAMAQJQQWAACAAhAAXi0REBcoAoA6CmIINQcBggRDgPwbIWiABUWjVHqMoGaJQSADDoGJD4BA0jCSmMEOYyxwQADkABiRR-hUChK0QAamcWoVxEcPFeJANMQQ4xGFKDmGwZQNBZBkEdAAD0dHIuAgggQ4koG-S4tRzA4CsegRRCAcCSJ0OUTwmBBBNJAIkf4DFMBsDYAomgOAZEgHKZU4IC1NR-G6b0gAwibTpDTemyDYAgApHTCRTKBD4vxnS6A9OCAARQYCIrp5gtEAAoACydytEAFUADKAARAAlKsxpwQTAXNkF0tQNBSDGMmTQCpVTXA1PJkEeZJz0D9O8N83pLS2nCMybs8F0z0ApKdAs4I2pXBaIAJJvORcEDZWzZA7Ojns4IGSjn4vQE87UAAZcl6BKXbIxdkjAswxFlKxUCBlYwkQWPMEoiZuT8mFMdFAEZkjBUQpmSs+pPzOWbO5Yy+FIBll41uQATS+UiBYsihW-IsL46Rarel-MuXQIFIK4W9POfaiwtyHnPPecasVSAJXKNQMYEAyAnAAGtgjCFkFYwkIbw01jWcENpBTYUgDYDgJAUA6ALDWoSTAwjRESKkRMuRCjJXuAgBUuAUBPByGCDANgpBlGit5bGiNBTo3MOjnmkR4jJHSMDaAHAwK2ANlmZYJQ2hdC2stYcpQZAnBsAYDgJgCxDBIWhXbS4zCW0XDjfaE5OSNR5IKUU9waaM1ZrlXIfJNbkKTr0GgHqiEK09OrewNwGAG2SqRPeppOalAvqrbex09bG0CQTegCAJ6D1gohV4td1TalBF5VGi4+gGR5r0EoWt6AECLorV+5ROTWmlhABsqN5QoA9IuMEPDDACMMCCKKsYzCgA): `{"mark": {"type": "point", "opacity": 0}},`.
