### ISSUE TITLE
Revise docs information hierarchy

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#7247]
(Extracted from https://github.com/vega/vega-lite/pull/7187#issuecomment-770457882)

We probably need to re-think about what should show up under "parameters" on the left? 

Currently, the things that show up are only properties of selection parameters, which feels a bit weird because (1) the section header is parameter and (2) some of these properties are property of `select`, which is nested under `parameter`. 

![image](https://user-images.githubusercontent.com/111269/106399180-b2cb7300-6449-11eb-8ece-9b3a50a3b2fd.png)

We probably don't want to restructure the menu to have two-level of nesting.
Thus, I think there are two options:

1) Group select's properties into one page 
```
- Parameter
  - bind
  - value
  - expr
  - select
```

2) Another possible structure is to do

```
- Parameter
  - bind
  - value
  - expr
  - select --> Point to the selection part
- Selection
  - ... selection properties ...
```

I kinda like (1) is better since it's probably less confusing even though it will produce quite a long page for selection (but we have a long page for encoding as well, so that's probably not the biggest problem).

**Comment by domoritz** [comment]
I prefer 1 as well.
