### ISSUE TITLE
Inconsistency in converting line to rule when Y and Y2 specified

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#7257]
The following will generate a range chart with each line extending between two values encoded as `y` and `y2`. It works because Vega-Lite converts the line mark to a rule mark (with an appropriate warning):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      { "sample": 1, "mins": 10, "maxs": 23 },
      { "sample": 2, "mins": 14, "maxs": 20 },
      { "sample": 3, "mins": 17, "maxs": 31 }
    ]
  },
  "encoding": {
    "x": { "field": "sample" },
    "y": { "field": "mins", "type": "quantitative" },
    "y2": { "field": "maxs" }
  },
  "mark": "line"
}
```

If, however the mark is specified as an object, which would be necessary if any other mark modification parameters are provided, the line ignores Y2 encoding and joins the Y values. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      { "sample": 1, "mins": 10, "maxs": 23 },
      { "sample": 2, "mins": 14, "maxs": 20 },
      { "sample": 3, "mins": 17, "maxs": 31 }
    ]
  },
  "encoding": {
    "x": { "field": "sample" },
    "y": { "field": "mins", "type": "quantitative" },
    "y2": { "field": "maxs" }
  },
  "mark": {"type": "line" }
}
```

This seems like inconsistent and unpredictable behaviour to me. My preference would be that whenever both `y` and `y2` are provided for a line mark, always to convert to a rule whether the mark is expressed directly or as an object.

**Comment by domoritz** [comment]
Good catch. Fixed in https://github.com/vega/vega-lite/pull/7260

**Comment by jwoLondon** [comment]
Wow! That was quick!

**Comment by domoritz** [comment]
you wrote a good bug report and I realized it was a simple fix.
