### ISSUE TITLE
Feature request: support angle encoding for image mark

### ISSUE THREAD

**Issue by lassepe** [vega/vega-lite#7258]
Currently, the [image-mark](https://vega.github.io/vega-lite/docs/image.html) can only encode the `x` and `y` positional channels.
It would be great if one could also use the `angle` channel to rotate an image based on data.

**Comment by jwoLondon** [comment]
Related request for enhancement: #5365

**Comment by domoritz** [comment]
I added rotation to https://github.com/vega/vega-lite/issues/5365.
