### ISSUE TITLE
Validate & Auto-modify Spec

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#726]
To truly validate a Vega-Lite spec, we have to validate 

1) if the spec matches Vega-Lite JSON schema

2) Some other rules:
- [ ] **Relationship between the encoding mapping and the mark type**
  - all the required encoding channels for the mark type are specified
  - (and) all the specified encoding channels are supported by the mark type
- **channel and functions**
  - [ ] aggregating fields on `row`, `column`, `shape`, or `detail`
  - [ ] bin on `shape`
- **data type based constraints**
  - [ ] `timeUnit` without type T
    - [ ] auto-drop timeUnit?
  - [ ] `aggregate` with ordinal / nominal 
    - [ ] auto-drop `aggregate`
  - [ ] `bin` without Q
    - [ ] auto-drop
  - [ ] using line without O, T (just warning)
  - [ ] use `scale.type` = `log`, `sqrt`, etc.  for non-‘Q’ type
    - [ ] auto-drop
  - [ ] use `scale.type` = `time` for non-`T` type
    - [ ] auto-drop
  - [ ] use `Q` as dimension for aggregate plot
    - [ ] auto-convert to `O` #688
- [ ] using `order` and `path` with `nominal` field (Nominal by default should not have order)
- **role-based constraints (dimension / measure)**
  - [ ] use two dimension with `line` / `area`
  - [ ] use two measure with `bar`  (Using two dimension with `bar` is fine for us though! — That will produce a heat map.)
- **other rules**
  - [ ] warning people use `bar` with `scale.zero=false`  (If scale doesn’t start at zero, bar is very misleading.)
  - [ ] use summative aggregation (’sum’, ‘count’, etc.) for stack
    We probably should have one `vl.validate()` method for people to call, but that also requires some JSON schema validator. 
  - [ ] use `config.mark.orient` when orientation is unambiguous  (e.g., when x is dimension and y is measure — the orientation should be vertical for sure.  Specifying `horizontal` isn’t a good idea.) 
  - [ ] path can only be used with marktype line
  
  We have a few options:
  (1) implement a method that both calls JSON schema validate and our special rules, and shim ZSchema
  (2) implement only a method that validate our special rules.  

Other suggestions are welcomed!

@domoritz, @yhoonkim  any thoughts?

**Comment by domoritz** [comment]
I think we should offer a utility method. This allows us to change its implementation without breaking other peoples code.

**Comment by kanitw** [comment]
@domoritz  your answer doesn't help me decide anything. lol   
Both of my suggestions above already suggests that we "should offer a utility method".  

Maybe it's saturday morning.  I think my original prompt reads a little confusing too. 
In any case, I just edit the original prompt to make it clearer.   Let me know what you think.

**Comment by domoritz** [comment]
I made my response a bit clearer.

**Comment by kanitw** [comment]
Since there will be  `vl.spec` as utility for spec,  maybe we can have `vl.spec.validate()`  and move all stuff in `validate.ts` to be in namespace `validator` inside `spec.ts`

**Comment by kanitw** [comment]
This article is also a good source of other things to validate 
https://en.wikipedia.org/wiki/Misleading_graph#Logarithmic_scaling

also the famous "How to lie with statistics" book.

**Comment by chrisdone** [comment]
What’s the latest and greatest here? I’m using Vega for a statically typed data language, and I would like to add a static check that the Vega spec is valid. The type system is mine, so I’m free to make it smart enough to call a third party validator.

If I validate using a JSON Schema validator, that’ll check basic schema. But as you point out, things like “get the field from the data named X as part of a theta” or similar are additional checks needed before you can be 100% confident that you gave something consistent and correct for Vega to consume. So a more sophisticated check is needed.

By way of example, JSON is rendered our product as an editable UI, which edits the JSON underneath. 

![55E43BAF-5952-4054-9CBF-15A703A80936](https://user-images.githubusercontent.com/11019/101285202-d83a5880-37db-11eb-8088-a2146b22f0af.png)

The pie chart is produced by `vega(pie_spec)`. This is very nice, but without correctness checks it doesn’t help the user avoid mistakes. I’d like to avoid defining a DSL wrapping around Vega if possible.

**Comment by domoritz** [comment]
The best we have are the typescript typings. However, there will always be things that cannot be validated via the type system and Vega-Lite will (hopefully) show warnings. We designed the Vega-Lite compiler such that invalid properties are ignored rather than breaking the compilation.

**Comment by chrisdone** [comment]
Thanks. I'll see what I can do.

**Comment by kanitw** [comment]
I think the description for this issue is quite outdated. I'll close since it's unlikely that we will do this.

**Comment by domoritz** [comment]
Plus, we have additional validation in Draco, which we could extend even further to cover the cases above.
