### ISSUE TITLE
Blank chart when time is involved.

### ISSUE THREAD

**Issue by sizhky** [vega/vega-lite#7267]
Hi I was going through Altair's tutorial here - https://altair-viz.github.io/altair-tutorial/notebooks/03-Binning-and-aggregation.html

and ran

```python
from vega_datasets import data
temps = data.seattle_temps.url
alt.Chart(temps).mark_point().encode(
    x=alt.X('month(date):T'),
    y='temp:Q'
)
```
that produces following json
```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"
  },
  "mark": "point",
  "encoding": {
    "x": {"type": "temporal", "field": "date", "timeUnit": "month"},
    "y": {"type": "quantitative", "field": "temp"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json"
}
```
but it creates a blank plot as shown in screenshot below

![image](https://user-images.githubusercontent.com/3656100/109494008-517fd980-7ab3-11eb-8516-19f067ad2995.png)

### Edit
Error persists even when using `"$schema": "https://vega.github.io/schema/vega-lite/v5.json"`

Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
Use `seattle-weather-hourly-normals.csv`. The vega datasets package for python needs to be updated. 

See https://github.com/vega/vega-datasets/blob/master/CHANGELOG.md#version-20
