### ISSUE TITLE
Issue with "Annual Weather Heatmap" data rendering

### ISSUE THREAD

**Issue by praveena-pappu** [vega/vega-lite#7279]
We see data discrepancies while checking data in "Annual Weather Heatmap" report.

1) Go to [https://vega.github.io/vega-lite/examples/rect_heatmap_weather.html](https://vega.github.io/vega-lite/examples/rect_heatmap_weather.html) 
2) Click on "View this example in the online editor" and it redirects us to [https://vega.github.io/editor/#/examples/vega-lite/rect_heatmap_weather](url)
3) Update the code by adding line : "mark": {"type":"rect","tooltip":true}
4) We are able to see tooltip for the report. When we check the data for a date on the report and [CSV](https://github.com/vega/vega/blob/master/docs/data/seattle-weather.csv) file we see the data is not matching between the two.
5) We see the next day's maximum temperature as today's maximum temperature. For example: 10-January the maximum temperature is "12.8" in the [CSV](https://github.com/vega/vega/blob/master/docs/data/seattle-weather.csv) file. However the data in the report is shown as "14.4" which is maximum temperature for 11-January. 
![Screenshot 2021-03-02 4 14 33 PM](https://user-images.githubusercontent.com/53495700/109733407-e4804880-7b73-11eb-8b01-b6a2e532dd7b.png)

Can you please resolve this issue as this is a priority bug.

**Comment by domoritz** [comment]
Closing since we did not get a response for a request for clarification.
