### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#7299]
The following link is included in the VL schema and docs, but does not point to a valid page:
http://vega.github.io/vega-lite/docs/init.html

For example, see this docs page (inside the parameter `value` description):
https://vega.github.io/vega-lite/docs/parameter.html#defining-a-parameter

_Update_: And here is another one: https://vega.github.io/vega-lite/docs/project.html. It looks like we need to make a full audit of the documentation links in the schema!

**Comment by domoritz** [comment]
I fixed some links in https://github.com/vega/vega-lite/pull/7282.

**Comment by domoritz** [comment]
Looks like all of the ones you found are already fixed in #7282. I already went over the param docs so I think we can close this.
