### ISSUE TITLE
Broken markdown in documentation

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#7301]
See https://vega.github.io/vega-lite/docs/selection.html#selection-props: the bulleted list of selection `type` values is broken. I think some newlines are missing in the schema entry.

Similarly for the `resolve` property.

Perhaps this is arising in the TypeScript-to-JSON-Schema process? (Just guessing... I haven't checked the source code but I wouldn't be surprised to find proper newlines there not being propagated correctly to the JSON schema strings.)

**Comment by domoritz** [comment]
I think that came in in https://github.com/vega/ts-json-schema-generator/pull/514

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/ts-json-schema-generator/pull/697

**Comment by domoritz** [comment]
<img width="856" alt="Screen Shot 2021-03-12 at 08 13 47" src="https://user-images.githubusercontent.com/589034/110967111-e0d68980-830a-11eb-8754-a7c66e45e7da.png">
