### ISSUE TITLE
German local does not work correctly for plane hours! (Other languages probably too)

### ISSUE THREAD

**Issue by rg98** [vega/vega-lite#7302]
Please:

When I run the example below, I would expect to get German times, this means 24 Hours instead of 12 Hours format with am and pm. It seems that the short time formatting is ignoring the locale time.time. Wouldn't it make sense to parse the hour format descriptor of time.time to format the hour in the example and/or usage of %p in time.time?

Kind regards
Ralph

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "width": "container",
  "height": "container",
  "config": {
      "locale": {
        "number": {
          "decimal": ",",
          "thousands": ".",
          "grouping": [3],
          "currency": ["", " €"]
        },
        "time": {
          "dateTime": "%A, der %e. %B %Y, %X",
          "date": "%d.%m.%Y",
          "time": "%H:%M:%S",
          "periods": ["AM", "PM"],
          "days": ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
          "shortDays": ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
          "months": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
          "shortMonths": [ "Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"]
        }
      }
    },
  "data": {
    "values": [
      {"a": "2020-10-01T08:00:00", "b": 2}, {"a": "2020-10-01T08:00:00", "b": 7}, {"a": "2020-10-01T08:00:00", "b": 4},
      {"a": "2020-10-01T12:00:00", "b": 1}, {"a": "2020-10-01T12:00:00", "b": 2}, {"a": "2020-10-01T12:00:00", "b": 6},
      {"a": "2020-10-01T16:00:00", "b": 8}, {"a": "2020-10-01T16:00:00", "b": 4}, {"a": "2020-10-01T16:00:00", "b": 7}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "a", "type": "temporal" },
    "x": {
      "aggregate": "average", "field": "b", "type": "quantitative",
      "title": "Mean of b"
    }
  }
}
```

<img width="518" alt="Screenshot 2021-03-12 at 16 12 40" src="https://user-images.githubusercontent.com/53708464/110959275-cffb3780-834d-11eb-9eb6-6fbf09e63fc2.png">

I would expect this result instead:

<img width="518" alt="edited Screen Shot" src="https://user-images.githubusercontent.com/53708464/110961034-a7743d00-834f-11eb-9c80-861399f34158.png">

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
Duplicte of https://github.com/vega/vega-lite/issues/6630

**Comment by domoritz** [comment]
Not being able to remove AM/PM from the default time formatter is https://github.com/vega/vega/issues/3116.
