### ISSUE TITLE
oneOf in vega lite v5.json doesn't comply with json schema specification

### ISSUE THREAD

**Issue by gregid** [vega/vega-lite#7349]
According to [json schema specification](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.10.2.1.3) `oneOf` **must be** a non empty array. 
In the following part:
```json
    "FieldOneOfPredicate": {
      "additionalProperties": false,
      "properties": {
        "field": {
          "$ref": "#/definitions/FieldName",
          "description": "Field to be tested."
        },
        "oneOf": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
```
It is an object instead.

The same problem applies to all previous versions (v1, v2, v3, v4) of vega lite schema

**Comment by domoritz** [comment]
Actually, this `oneOf` is a property. It's coming from https://github.com/vega/vega-lite/blob/5167f392c587a154d510ec56e70833cb6cadd119/src/predicate.ts#L149.
