### ISSUE TITLE
Configure parameters (e.g. scales) of plot interactively

### ISSUE THREAD

**Issue by Make42** [vega/vega-lite#7361]
Would it be possible to add the possiblity to add a radio button, a checkbox or something similar to allow parametrization of the plot that is not the data directly? I would like to use a checkbox to indicate whether an axis (here the x-axis) should be displayed normally or in log-scale.

**Comment by domoritz** [comment]
You can parameterize charts with `params`, which can be bound to inputs. Scale types are not supported but you could change parameters of a scale.
