### ISSUE TITLE
Interval selections don't work with aggregations (`Expression parse error`)

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#7374]
When I create a selection of type `'single'` or `'multi'`, I can use either the `fields` or `encodings` key to specify what the selection should select on. However, when I switch to a selection of type `'interval'`, it only works when using `ecodings`. Trying to use `fields` throws the error: `Expression parse error: ? selector033_scale_trigger : {}`. The chart below can be used to reproduce the error, [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLQA2AJxg6YTACY2EgOyHMAVkcAjR9du3MptgEY3ABzGlpYSIHIgGgoATgDWOi4xINyYUJB0JEioIBAADgpgcIQAnqoEGcTQqmgKADak2shsAHS23JSYtZhglVA6HV09ENE2YRE19Y0tvhEAHqoluY0gAI6kCkRFSnBo2tzwnXQ6AJqYSRGl2YvLaxvEysS7ySAKCAjRmAhKy5CkROERRgiBBiFCOLggAbdXqqKFDEYSMJXYpLHQkQiYaITZ4HWp0SgoADaIFOSQAurJ5EoFB1CATsnoFEZTOYrDZ7E5XO42J5vGA-IFgqEiaBSdEUL5jMZDHJRWdxchJdLZST5RKpbYVWL1cYAlq1chrGxHNIKdIgA):

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-69cdce20376e55b52077e9c01b589223"},
  "mark": "bar",
  "encoding": {
    "opacity": {
      "condition": {"value": 0.7, "selection": "selector033"},
      "value": 0.1
    },
    "x": {"type": "quantitative", "field": "Year"},
    "y": {"type": "quantitative", "aggregate": "count"}
  },
  "height": 50,
  "selection": {"selector033": {"type": "interval", "fields": ["Year"]}},
  "datasets": {
    "data-69cdce20376e55b52077e9c01b589223": [
      {
        "Year": 1996
      },
      {
        "Year": 1996
      },
      {
        "Year": 1997
      },
      {
        "Year": 1998
      },
      {
        "Year": 2005
      }
    ]
  }
}
```

With the change below it works as expected, but single and multi selections work fine with either approach, so I would anticipate interval selections to also work with the fields key.

```diff
-"selection": {"selector033": {"type": "interval", "fields": ["Year"]}},
+"selection": {"selector033": {"type": "interval", "encodings": ["x"]}},
```

**Comment by joelostblom** [comment]
I did some more troubleshooting and discovered that the core issue here is that interval selections do not seem to work on aggregate fields. The example below reproduces the error and it goes away if you change so that the aggregated field is not the same as the selection encoding. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygHYQLYFN7mhAtANgE4BjMItAJgAYBmAdjzQFZGAjRq22tYygRjYAcBcuWogAvgBoQKCACcA1pgAOAewCWiKCGlpERVWE0BzeKFXKIRdVACeZkAcRGo61YgcA3CABsArhhwlAB0tNIAzmg+aESu7piR0bGqcjRiUiDe-oEhvBn2CCB2yoEgAI5+EFo20OqeGNIAZupRYJgAmmjyEtIAHg7FpRVVrjCu9Togza0dXXKTEMbGcmjG0KXoVRIZABZo6sY72nCMlBFRMXEehYmXKWkDtiWYmlBoclmTegZGiMbh8AA2iB7ABdcQZSAwSJQAGFKG4QgkMhUOgMZhsDhcHj8RhCERiOCA0CdbpwXgEAh4KQkubwClUmkgUnzcmU2hMln0ykCTl0uBUSiMcTg8RAA)

```json
{
  "data": {"name": "data-69cdce20376e55b52077e9c01b589223"},
  "mark": "point",
  "encoding": {
    "opacity": {
      "condition": {"value": 0.7, "selection": "selector033"},
      "value": 0.1
    },
    "x": {"type": "quantitative", "field": "Year"},
    "y": {"type": "quantitative", "field": "Year", "aggregate": "mean"}
  },
  "height": 50,
  "selection": {"selector033": {"type": "interval", "encodings": ["y"]}},
  "datasets": {
    "data-69cdce20376e55b52077e9c01b589223": [
      {"Year": 1996},
      {"Year": 1996},
      {"Year": 1997},
      {"Year": 1998},
      {"Year": 2005}
    ]
  }
}
```

**Comment by arvind** [comment]
Thanks for reporting the issue @joelostblom. [Our documentation](https://vega.github.io/vega-lite/docs/selection.html#project) does mention that interval selections can only be projected using `encodings` and that aggregated fields are not fully supported. However, I agree that the schema (which is what Altair uses to generate its API) doesn't make this distinction as clear as it could and that, the `Expression parse error` is not a graceful way to handle an invalid specification. #7442 addresses these latter concerns. Thanks!
