### ISSUE TITLE
Make it easy to support arbitrary text overlaid on a plot

### ISSUE THREAD

**Issue by dsandber** [vega/vega-lite#7376]
In this ticket:

https://github.com/altair-viz/altair/issues/2430

Joel was kind enough to explain how existing functionality in Altair (built upon Vega-lite) can be used to overlay a box of text on top of a graph.  However, the process is complicated since the width of the text box has to be manually determined and a bunch of steps are needed.

It is common that a graph depends on a bunch of parameters, and it is often helpful to overlay those parameters on top of a graph.

it would be nice if this could be done with one command:

.text_overlay(text=text, corner=top_left, color=black, background_color=gray, margin=5)

Most of the parameters could have sensible defaults.

I suspect many would find this functionality useful.

**Comment by domoritz** [comment]
Thank you for filing the issue. I think we want to match the level of abstraction we have in the rest of the system so I would propose a more general solution. 

If we support marks without data (https://github.com/vega/vega-lite/issues/6157), you could add a text mark at an arbitrary position. To draw the box, you would still need some way to generate a reactive geometry (the box size depends on the size of the text). It could be part of annotations such as https://github.com/vega/vega-lite/pull/3401. Alternatively, Vega could add a text background color (and padding) option to text marks. 

I will close this issue as it's too abstract for Vega-Lite but I am happy to discuss the ideas here more.

**Comment by dsandber** [comment]
Hi Dominik,

Fortunately (unfortunately?) Altair has shielded me from Vega-lite completely, so that I know little about its implementation.  I'm not sure where the reactive geometry functionality best belongs -- as an option to text marks, part of annotations, etc.

If text marks can already be multi-line, then I suppose adding a padding and background-color would be easiest.  Presumably someone would come along sooner or later and want a non-rectangular shape like a circle or oval.   So what's the best way to abstract away the idea of text with a bounding box so that other shapes can later be used?

**Comment by domoritz** [comment]
We actually requested a similar feature from Vega before but reactive geometries already support what we need: https://github.com/vega/vega/issues/1820#issuecomment-524251897. What we would need do to here is provide the right abstraction but that needs some design work.

**Comment by dsandber** [comment]
I tried the example in the comment and it does seem to do what I'm requesting, though I couldn't get multi-line support to work.  I tried embedded HTML, and I tried "\n", but neither worked.  Any idea how that could be accomplished?  Because if there isn't a way to do it, then Vega does not have the primitives that are needed.

**Comment by domoritz** [comment]
Vega expects an array of strings for multi line text.

**Comment by dsandber** [comment]
I had tried this:

```
  "data": [
    {"name": "labels", "values": [{"label": "Text"}, {"label": "Text2"}]}
  ],

```

But the labels came out super imposed.  What am I doing wrong?

**Comment by dsandber** [comment]
never mind, this works:
```
  "data": [
    {"name": "labels", "values": [{"label": ["Text", "Text2"]}]}
  ],
```

Cool!

**Comment by domoritz** [comment]
You got it. Thanks for confirming it works. If you think the docs could be better, please send a pull request.
