### ISSUE TITLE
Stacking with size channel

### ISSUE THREAD

**Issue by xoolive** [vega/vega-lite#7390]
I am not sure whether this is a bug report or a feature request, but I'll show the logic here.
I wrote the code with Altair but will try to share the **links to the vega-lite editor** as well.

So I first generate a list of temporal events, and shared the resulting json on gist.

I am trying to get a stacked view of different types of events, first the more natural view with stacked `bars`, [(link)](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCFIAnADYoQYwgAdKyAPTGEcSoQB05pqQBGVTOoKFMRK5AC2xgB4QITTg0TGMAdjB7MABWFgAOMABONnsYRMx7RMS4zAlohQAmNjAARkSwkoUANkTjdQVsYzY6OkwCgswYUpYCqolUsLowNiqqgrpxljCWCUwqmAVouIk47ONMXwUvfU1MKwArSmgQORAvBXUAax17C5Bud0g6EiRUHk0IdVVCAE99TB0UAgXhICm03HgmE0dB0YCUmAQnx+9xAlDhu1UdGBChIKAA2iBERAYdxbiSQCF1D8AARklGkKCXIHYKAgAC63HqUAQAOQBIAxCxMGFEgowij+TACjkCvYJZgStEwtFEhLbvY2AowOzZJyILg3r9-jo3NtPmCUZDoTpGBQvtxiF5MABVKBwcTINSEMBeXiMRRuFHEQgYz0nbi+b5-XkgU36c3gkBWmGe20aINwJ2u906UjetPqSgZkMxgvUgAUzoAKgBhACU4ZAyMN0Z0AEdSAoiO6lMEARCsNbPYQIMptLrdCIEGIUCUOA6uZQYJ8vPjQAoEAh1Aj4WuQBB9LCKERLYOU+B4YiqSiFEXh6OLdIOYT1BR9PZmwSCyi4W4r8i2SfbgABI0UYTBzhtQgDCMUwQgQBQbHdRgHCsOAIGMMCIIUYx4IUABaII3Fw6IrDYMiDiOVlpCAA):
```python
base = (
    alt.Chart(
        alt.Data(
            url="https://gist.githubusercontent.com/xoolive/7cbc548c90bf9eb998e35a20c1971a69/raw/0dde22efc14263bf7dc0662d2d4743e6fa583898/example.json"
        )
    )
    .transform_aggregate(total="count(category)", groupby=["hour", "category"])
    .encode(
        alt.X("utchours(hour):T", title="hour (UTC)"),
        alt.Color(
            "category:N",
            scale=alt.Scale(
                domain=["good", "bad", "very bad", "unknown"],
                range=["#4e79a7", "#f28e2b", "#e15759", "#bab0ac"],
            ),
        ),
    )
)

calendar = (
    base.encode(
        alt.Row("utcmonthdate(hour):T", title=""),
        alt.Y("total:Q"),
    )
    .mark_bar()
    .properties(height=100)
)
calendar
```

The output is correctly stacked:
![image](https://user-images.githubusercontent.com/1360812/114620106-8b93ec00-9cab-11eb-812b-fb02ed60e4df.png)

Now since my list of days is much longer, I want to encode things a bit differently, with "bubbles" of different size. So the `y` channel would become the `size` channel [(link)](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9uAG0wJMUOnhAQATliIoQAIwiFCEALYhpskHQCGha2tIa5usYQAOlZAHovCOJUIAOj8mUj0qTA0CQmUgyBMvAA8ICDk4NEwvAHYwPTAAVhYADjAATjY9GFLMPVLSoswJfOsAJjYwAEZSrI7rADZSrw1rbC82OjpMFpbMGE6WFr6JSqy6MDY+vpa6bZYslglMPphrfKKJIvqvTETrEzcFQIArSmhzbhNrDQBrXTA4KIKEDcZSQOgkJCoHhyTRqQgATzcmF0UFMJGszm48EwclUyHAtkUmnhwJAlDAGORULopmsJBQAG0QAgUqpuHprGyQBkNPCAAQcrmkKDfVHYKAgAC63GGUCUjJAAGIWJgsqVrFlSYqYC0Gi09FrMB18ll8qUtRy9GxrGApRZuJQ4AAvKmgBFI3QAR1I1iIcDsxAypOxuN0xjszksiThiKpIBi900GODWFD+MYFA0pOIJkwAFUoP7dKRCGAM45KNn-UD05m+QAKPMAFQAwgBKd4gElQ91xzTgqDJrGpvEgctZ7g5-OF8T4ktgEy8Rg2GJVwg1shyOT2+OyygwTRmZAM0DWBAIDSKQmM0AQNx-Cg6Yc40cUmIs3mk6yV-Hh5PSaVmQ0Cg3D0bsmXHUk3yJT9JVkUB4DkGIs3xFdSBMQJoI-fkAEIAF4+QAcmFUUIHFQjzEAgASclGEwT4XCMDxvC8DIEGsYJ-UYMJAjgCAvFo+jrFYq8AFo0hiViWECIpAg6Z5XglaQgA):

```python
calendar = (
    base.transform_filter("datum.category != 'unknown'")
    .encode(
        alt.Y("utcmonthdate(hour):O", title=None),
        alt.Size("total:Q"),
    )
    .mark_circle()
    .configure_legend(orient="bottom")
)
calendar
```

![image](https://user-images.githubusercontent.com/1360812/114620402-d9a8ef80-9cab-11eb-881a-ad438dffda05.png)

This could look correct, but actually, it appears that the sizes are not stacked and that some bubbles may come in front of others. I wrote the following workaround, generating stacks manually, playing with the `order` channel, and with a stack ordering consistent with my wishes (is it related to https://github.com/vega/vega-lite/issues/1734 ?) but in the end I am not sure whether the process could be facilitate so as to get the following output ⬇️ (with [(link)](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9uAG0wJMUOnhAQATliIoQAIwiFCEALYhpskHQCGha2tIa5usYQAOlZAHovCOJUIAOj8mUj0qTA0CQmUgyBMvAA8ICDk4NEwvAHYwPTAAVhYADjAATjY9GFLMPVLSoswJfOsAJjYwAEZSrI7rADZSrw1rbC82OjpMFpbMGE6WFr6JSqy6MDY+vpa6bZYslglMPphrfKKJIvqvTETrEzcFQIArSmhzbhNrDQBrXTA4KIKEDcZSQOgkJCoHhyTRqQgATzcmF0UFMJGszm48EwclUyHAtkUmnhwJAlDAGORULopmsJBQAG0QAgUqpuHprGyQBkNPCAAQcrmkKDfVHYKAgAC63GGUCUjJAAGIWJgsqVrFlSYqYC0Gi09FrMB18ll8qUtRy9GxrGApRZuJpJho4YiqSBUSZ0ZiQNjcX9CSzee8yXAAF5U0AIpG6ACOpGsRDgdmIGVJvrxIfDLVJxEIQPxxjszksiRd0YLmHumgxaawfvxjAozu4xBMmAAqlAk7pSIQwI3HJQc0n8yABxo+QAKdsAFQAwgBKYMkqFRt2Or21nEZ8fDtud7v43tgEy8Rg2GLDvNUshyOT2kCEWWUGCaMzIBmgawIBAaRSExlQAgNw-goHQsTrDMKRiQMSW4awhwLQwa2kaVmQ0Cg3D0FcmV3bhoKJINJVkUAYQgb5SBA-ECNgtMMPfUAL3sKEoDuN0mIAWiyGAOhgNgWhYOg2BYQoOiKQoikkk0bToPoanKE4JGDb5MBXAkYOJLdcUQpk0AxUhkWIkj0Mw7CFV3NCAhtX4kKLUlXg0cQP1AdNdD0uQDPMNCEIVSgw2Rbg-KzO1OBcuA5BiZ18QvUgTECGjiT5ABCABePkAHJhVFCBxXSrzuAAEnJRhK2YscjA8bwvAyBBrGCJNGDCQI4AgLxitK6r-w4tIYmq-JAjYAbnleCVuCYyhMEIRDGNsawuJ4viBKEkSWDEiSpKyGS5NqNhFMA9TCLUrKxVG7l9KpCRjISoN8RZCAuXczzkBaK6A00-FBVJR6qQ6V6NJu7lIn5T7uG+lA2FQiwgA)) for the previous code snippet ⬆️ 

```python
cheating_sorts = pd.DataFrame(
    dict(category=["unknown", "good", "bad", "very bad"], value=[3, 2, 1, 0])
)
calendar = (
    base.transform_lookup(
        lookup="category",
        from_=alt.LookupData(data=cheating_sorts, key="category", fields=["value"]),
    )
    .transform_stack(
        stack="total",
        as_=["size", "size2"],
        groupby=["hour"],
        sort=[alt.SortField("value")],
    )
    .transform_filter("datum.category != 'unknown'")
    .encode(
        alt.Y("utcmonthdate(hour):O", title=None),
        alt.Size("size2:Q", title="total"),
        alt.Order("category:N"),
    )
    .mark_circle()
    .configure_legend(orient="bottom")
)
calendar
```

![image](https://user-images.githubusercontent.com/1360812/114621278-cba79e80-9cac-11eb-9406-25a62df9dbeb.png)

Thank you for the support!

**Comment by domoritz** [comment]
Great idea. I think we should apply stacking to sized circles as well. 

Here is the simplest example I could come up with. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSACCikEzQAmABwBfBSbQgAQpeuoxYhwF0nEGQAJwBrVygaYKhBOEs4WSg2ZRpZMjRQJME2YIyQADMaOEFlVxQlTABPHDj0WTYEVJ0QQIgaAC9a0ELi0vRrCurakABHBiRZTDo1GlIWhwcgA)

<img width="842" alt="Screen Shot 2021-04-14 at 12 28 40" src="https://user-images.githubusercontent.com/589034/114767814-f7626d00-9d1c-11eb-9d53-33e381a23cbd.png">

Would you want to take a stab at a pull request?

**Comment by xoolive** [comment]
Thank you for the feedback! Glad to see it's welcome.
About the PR, my major weakness is that I need to learn Javascript first :fearful: I'm usually ok at copy-pasting bits here and there, but for this one, I would need much more shepherding... :sweat_smile:

**Comment by kanitw** [comment]
I talked with @domoritz more about this. I don't think we should support this as it was intentionally not supported. 

Even if the circle's area are properly stacked as you suggested, people won't able to effectively compare the area between the inner circles and the outside stroked circles (for the stacked ones). 

It'd be better to do a bar chart with less height, or consider using pies  (which is basically stacking angles of arc marks).

**Comment by xoolive** [comment]
Thank you for spending time on this and I must say that the area comparison argument does make sense. I am fine with my workaround for my need, I should consider other options in the future.

Yet, I am not sure the status quo is a good idea either.
I mean, the Color channel does make sense, but its behaviour with nominal variables is not the one expected anywhere else. It returns something, which in the end is wrong.

I would have at least expected a warning somewhere, no?

**Comment by kanitw** [comment]
I could see an argument for a warning, but this should be rare enough so I don't plan to fix this.  

If you strongly feel like a warning, feel free to submit a PR. :)
