### ISSUE TITLE
Allow text mark to be selected

### ISSUE THREAD

**Issue by tonyxiao** [vega/vega-lite#7395]
Given the current limitation around interactive legends / axis #1657 , I'm trying to re-create the experience of interaction via fundamental building blocks, in this case text. However just ran into another issue - text marks cannot be selected it seems or otherwise interacted with in vega-lite. Is this by design or is it a current limitation?

![CleanShot 2021-04-17 at 10 38 15](https://user-images.githubusercontent.com/696842/115118506-15bca880-9f69-11eb-8c6f-2178716d9545.gif)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemhBQ5mJDVlwATopBqketKGJJBDOBDQBtUIKRM4grQDE2bNaZICGwMsphoAIwATAAMMUo4xlBwYWgxlFEAnDERAMxiuZkAbGJKOoJsJuhGcAEAvgqu7p5aACJGBgDWgcGh4ahRufEgiUbJqajpMWJiRTGZUQAcACy5uWVsFVUgZDUpIA1NHl7oAIJQOsHmmOzySkEhExFicQlJKf3puUVRRUULy1mGy2WiYdjgB0aIDcxx8wjIWB6j36UWWw1G40+lGmixiUQA7DF8Zl1tpNpUtDV6lCYS10ABRMLGPQGBAfJF9NBiZZRN5jdmTSh5CIxZZixb45bAinoXZwfaHaHNE4gAAqHTwHImaylI3eEymuPx3PysVJ5RlIDB9khRzpIAAsjRoFr+tk+Zi0tiohF8XNnstJdLtpg4LYDgBdBogG6YQQQ9AAIQAngACKAWciVZOmFI6NQGMhWEA51CgABmNE8AXQtK8ShkRn6ThA50u-gst1Mvn8pkZoab+lkbNSSnVNE1Sm88MREaUsfjaFkDEEgnuAA9nUuV4I6tG3MnjM5QMgjN0yzHk4lQUgTPO-IIbjg0JgjPYygwjI2tDg2AYB5CIB5v4hbFuuxaVtWWgPJy85XgmIAAI4MEgYR0J2pCmAuCbLquG5bheahsMgBhoOWtgQHASi7OoZEUXAe7BhBVaCDWSqwko8ZkCkNa4buShsDgSBQHQpagDosgFjccjFkJRhBFolHxlAoYBEoNjgpE0YaTagq5IxIy3kEjioC4ICyEECFKXAKm1KY1kqcWmDwT+f6jkBsj5oWJktjmc4xmwZBkIuqDkYIlF7lGUKnueoDOde6Chuu4T3PC8jVDQCIpSA4GoPwYjRsBBayEWF5Jf0FYsWxdYHJFdRAA)

**Comment by domoritz** [comment]
Text can be made interactive like other marks. Here is an example: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABEyTrDsU5kMB3OjEMwaZGMOc7ZZQ3IdtSZpLLKhhBwgnBQ7p7eUMJQANaUhgAUAJKyEDg06nBBTACehgAqSExhSAwA5BCGNLKYcOpIEbrBmHlhlACUiipImCiooMRIggxqaADaoAMg+j1MaABMABwAvgrTaCAAQvNoYmLrm+gAwnuoACwAzEcgMwAi5wCcAIy3MwCi58tvG3dbADFzmIbn8ZgBxc4vJ7vLYACW+AHZYegUsDFqsALrrEA4UxIBAQSagWQEuBbRzOVxYHohMIRNCgNo4cnoHBsWqYHpyLYINgMEK+BogVa3UkIVkgOnhLlKaUMtkcuoizFKZDqOKMkDMyX1AAeXJxcFkUDYylqZC1+q5gxAw1GkuyyhFSj1WoAZjRQs70CglDqtmx1ObSYIXSA8h6vYIfSAFv68iytgBHBgBHT9HSkcOmwRBrWmwJ0XTE3H4hBbeWykCIbSR1DukYhJT2sZbJ0u0B4xoV9CUlxOGlKWttNCNwTNu0jNvoUptrEt6eSsjZY0inGFz2W23QEas0AmQIABSQyhDZDSsmFqAADJQMaKgA).

For axis labels, you can look at #1657.
