### ISSUE TITLE
Basic Geo Type support

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#74]
## Vega-Lite
- [ ] geographic coordinate (latitude and longitude)
- [ ] geographic projection
- [ ] TopoJSON and GeoJSON support
- [ ] add new “geo” shelf for helping with conversion?

## Datalib
- [ ] Utility for converting commonly used geographic information (such as Address, State, Country)

## Examples
- [ ] Symbol Map ~~#26~~

## Advance
- [ ] Adding Zooming and Panning Interaction using vega2 could be very helpful.
- Extend [DataLib](http://github.com/vega/datalib) for converting commonly used geographic information (such as Address, State, Country)

**Comment by rgrp** [comment]
Note that JSON Table Schema has "geopoint" and "geojson" types: http://dataprotocols.org/json-table-schema/#field-types-and-formats

**Comment by kanitw** [comment]
Duplicate with other [newer issues](https://github.com/vega/vega-lite/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.x+Maps%22)
