### ISSUE TITLE
Interval select + point hover together cause `TypeError: Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by tonyxiao** [vega/vega-lite#7402]
This spec
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"date": "2015-01-01", "sum": 95089.68999999989},
      {"date": "2016-01-01", "sum": 94182.42000000004},
      {"date": "2017-01-01", "sum": 65110.070000000014}
    ]
  },
  "width": "container",
  "encoding": {
    "x": {"field": "date", "type": "ordinal", "timeUnit": "year"},
    "y": {"field": "sum", "type": "quantitative"},
    "opacity": {"condition": [{"value": 1, "param": "hover"}], "value": 0.2}
  },
  "mark": "bar",
  "params": [
    {"name": "selected", "select": {"type": "interval", "encodings": ["x"]}},
    {
      "name": "hover",
      "select": {
        "type": "point",
        "fields": ["date"],
        "on": "mouseover",
        "clear": "mouseout"
      }
    }
  ]
}
```
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoVZjhoQAJgAMARjH87j24pAQGCNAE4x1gBxelABsAV5h4QEAvgomauboNrZBzs6u7p6oXgAstn6WlFk21sUl1lnRsWYWiQDsKXZpHmhBYra21pTWNaWltuUAutEgAO40yvQWUHLqNLJwAE6ucLJTyrNkaKAAHpsgAGY0cILKFqbmSpgAnjjxIGzza7I6rpg0CHAAqrJ0FpdwSIshpddgcjid0OkXtdbgBHBhIWSvdSvUggIZsHBIKB0YGaEBTWRrV5yIxaHR6NC2JSY+ZIDIYNikQH9JTaXTxDqWSJDZDzADWFiYANcNLpBlQxhAT3eFggRzgUDMJyUcsECswuyuNwsszM8zZSxWbEeZHFhhAO0GFSldNuMEZCzS8sVmuhFhwbF1rlBxzNKjiIBZd3k6AQbAYcodiyUUDVwtD4cjDA13MGQA)

Produces this error on every interval selection change (during dragging)

![image](https://user-images.githubusercontent.com/696842/115862353-aaa42380-a3f9-11eb-9e81-1736c0a6e5eb.png)

**Comment by arvind** [comment]
Thank you for reporting the issue, @tonyxiao! Should be fixed with #7436.
