### ISSUE TITLE
Hide muliple axis labels/titles when using layered facets

### ISSUE THREAD

**Issue by nmaar** [vega/vega-lite#7407]
Hello,

Is it possible to hide muliple axis labels/titles when using layered facets?

In the following example I would like only to show the bottom axis (sum of horsepower) once.

Thanks,
nmaar
                                       

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/cars.json",
    "format": {
      "type": "json"
    }
  },



"repeat": {"column": ["Horsepower", "Miles_per_Gallon", "Acceleration"]},

  
  "spec": {



"facet": {
    "row": {
      "field": "Cylinders",
      "type": "nominal",
      "header": {"labelAngle": 0, "labelAlign": "left"}
    }
  },

  

  "align": "each",

  

"spec": {

  "facet": {
    "row": {
      "field": "Origin",
      "type": "nominal",
      "header": {"labelAngle": 0, "labelAlign": "left" }
    }
  },




  "spec": {
    "mark": "bar",
    "encoding": {
      
       "x": {"aggregate": "sum", "field": {"repeat": "column"},  "type": "quantitative"}
       
       
       }


  }

  

}
}
}
```

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue? The example raises warnings in the editor.

**Comment by nmaar** [comment]
Hi, below is a minimal example of a nested facet specification.

In this example the x-axis is displayed 5 times. 
I am wondering if it is possible to use one common axis (at the bottom).

Thanks,
nmaar


![visualization](https://user-images.githubusercontent.com/38430586/116196624-05a88400-a734-11eb-849e-50ca37628168.png)


```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.1.json",
  "data": {
    "url": "data/cars.json",
    "format": {
      "type": "json"
    }
  },



"facet": {
    "row": {
      "field": "Cylinders",
      "type": "nominal"
    }
  },


  "align": "each",
  

"spec": {

  "facet": {
    "row": {
      "field": "Origin",
      "type": "nominal"
    }
  },




  "spec": {
    "mark": "bar",
    "encoding": {
      "x": {
        "bin": {
          "maxbins": 15
        },
        "field": "Horsepower",
        "type": "quantitative"
      },
      "x": {
        "aggregate": "count",
        "type": "quantitative"
      }
    }
  }

}
}

```

**Comment by domoritz** [comment]
The example uses facet of facet, which is not officially supported. Please send an example with only a single facet operator.

**Comment by nmaar** [comment]
Hello,
Indeed this is a facet of a facet question.
Thanks for your reply, facet of facet is not officially supported.

Is a facet of a facet supported in the future/roadmap?
This would expand the small multiples functionality of vega lite even further.

Thanks again.
nmaar

**Comment by domoritz** [comment]
Yes. See https://github.com/vega/vega-lite/issues/2761

**Comment by nmaar** [comment]
Keep up the great work!
nmaar

**Comment by domoritz** [comment]
Should I close this issue then?

**Comment by nmaar** [comment]
That's ok, i will post a summary at issue #2761
