### ISSUE TITLE
Unable to interact with Translate and zoom documentation.

### ISSUE THREAD

**Issue by Abhilash-Chandran** [vega/vega-lite#7465]
This is an issue in the documentation page for translate and zoom.

The interactive selection creates a random html in the page and the example code section doesn't change revealing the documentation.

https://vega.github.io/vega-lite/docs/selection.html#translate

A small gif showing the issue.

![1BkyRhL9QR](https://user-images.githubusercontent.com/4489849/118354713-bf915400-b56c-11eb-8fd5-1ed013464f95.gif)

**Comment by domoritz** [comment]
This happens when the example file name in the docs is wrong. Can you help fix it?

**Comment by Abhilash-Chandran** [comment]
I saw that error in the console.logs but I couldn't locate such a file in the vega-lite repo. It must be from Vega repo then. How do I know what is the correct file name for this section.?

**Comment by domoritz** [comment]
We probably renamed a file and forgot to update the reference. Look at the example files and find the appropriate one.

**Comment by Abhilash-Chandran** [comment]
I think [this](https://github.com/vega/vega-lite/tree/master/examples/specs) is where its located. I will look into it.

**Comment by domoritz** [comment]
Looks like the issue is actually that we request `https://vega.github.io/vega-lite/examples/selection_zoom_undefined_shift-drag.vl.json`. The issue is in the select/js. Maybe we just need to have unique ids (`type` and `event` appear twice). I'd suggest trying `type_translate` etc.

**Comment by Abhilash-Chandran** [comment]
Ah ok. Makes sense. I will try to fix that.
