### ISSUE TITLE
Interval selection throws error `Cannot read property '0' of undefined` on drag-drop of selection.

### ISSUE THREAD

**Issue by wahab896** [vega/vega-lite#7476]
Getting an error in logs as `[Error] Cannot read property '0' of undefined`.

Below is the Spec or [editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5KA7jWX00YgAwulUOQDMaZNKGIaOFt-EAhMbTYAazgAdQcnVBcbEEw4AA9MUK85TABlGgAvODQARgBmFKR0mghQwSQmOEEAMVyC4rLypUw6QTg22XyiktQKqpqIAE16xuaABSRlZRpZP1QxKxSIpFkIHO0ENABtUEk2VaQyMm0+NJPQNhx9JFJtK5KlH2blfQBZGj9CAAfRwcG0wIA4khBII5IoQEg6uhXmRgQCgaDwVCYXDrApHs8UW8PgjvoJfugACK1HANKCIOBDBFIl7ENE0iB0pAMhBMrJWAC6NlAJkEUAYDXu6FUmAYCGOAHIMXAQWCIdDYXJFYKAHyy+VK1HowGqrEa3HawUAAgA-NbFQBRTyyNgIGhQRXW1DWg0K5WmtXYzV4nUAHgAvH6jeyTZj1TitbIddaAGSp31qQ2Kznc3n88PRxXG3P0xlDFP25VwFZsKC3L0+xXzcEHZCyBmKlnIkAAYTU5DY2gAniAhUoGsPwQ8QMhtFFQphh2D9DgLsyvoD+pSIgw4EoICMyq4PMIibu4CkcKYkAhkacQLJb6Mws04FAsge3x-F8uX6s0m0YgYQRJlPBWNZ7xAdIEVHYURUfZ99BgXwYGEMgsARCBvyyTRUj-Vd10-EAwLYCCyCgzw4W0EB4MFJRSPI0IYLw8lKRAUseXLYilxXdAAEcGF2Xp1F6UgWUmUIbgcNALx6PoX04-MNxANs1H0BQaPkqAol7NgGGZDYUmgGFRlAYpIjQLwYWwrYlFHViggpf5A3NRM8QRXiX0E4S6DUGhxKUapakXBSXKBAgQ3hL4h2QXDFC01IPSiZFrMEbDtN0-TDM2A8xTMkALLYKybMvFIfFhAB5a8oDoBzRTkFZenhPC0nCUJdkpB9r3eI50BQjD0MwlJ+jWegAApZSQcaAB0MFQobMGBcIhzgOaAEp1tolJgMEPc0BcSgAE4dphfakkoSoPDYajQswfo0FkSVBE3H59H7NIyCHUcegI9BXXdJ89AncgmUpR5tCCQyQEhjDiIaJpWnaI8xgAJjs1I2Bu3oiQfNj9AAOSQ+T7pfIm+U8v7HzdS49AQ-H0BVIMLSTTywsZwNIsteRfr4kAfKGPyxM+VTYvU9AFEoVGvDHAlVKc9ilO4tnSf0JW+RUrz9AFkT-MC0XDnFxQpZloUtmFIA) or [stackoverflow](https://stackoverflow.com/questions/67569124/vega-lite-error-on-drag-drop-of-interval-selection)

```{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {"url": "data/cars.json"},
  "width": 500,
  "config": {
    "view": {"strokeWidth": 0},
    "text": {"fontSize": 13},
    "axis": {"labelFontSize": 13, "titleFontSize": 13},
    "axisY": {"labelPadding": 5}
  },
  "transform": [
    {
      "joinaggregate": [
        {
          "op": "average",
          "field": "Miles_per_Gallon",
          "as": "avg_Miles_per_Gallon"
        },
        {"op": "average", "field": "Displacement", "as": "avg_Displacement"}
      ]
    },
    {
      "calculate": "datum['Miles_per_Gallon']>datum['avg_Miles_per_Gallon'] ? 'Economic' : datum['Miles_per_Gallon']<=datum['avg_Miles_per_Gallon'] && datum['Displacement']<datum['avg_Displacement'] ? 'Mediocre' : 'Performance'",
      "as": "Category"
    }
  ],
  "layer": [
    {
      "mark": {"type": "point", "filled": true, "size": 150, "clip": true},
      "params": [
        {
          "name": "select",
          "select": {"type": "interval", "encodings": ["x", "y"]}
        },
        {
          "name": "highlight",
          "select": {"type": "point", "encodings": ["color"]}
        }
      ],
      "encoding": {
        "x": {
          "field": "Displacement",
          "type": "quantitative",
          "axis": {
            "grid": true,
            "title": "Displacement",
            "format": ",r",
            "tickCount": 5
          },
          "scale": {"zero": false}
        },
        "y": {
          "field": "Miles_per_Gallon",
          "type": "quantitative",
          "axis": {
            "title": "Miles/Gallon",
            "format": ",r",
            "ticks": false,
            "tickCount": 5
          },
          "scale": {"zero": false}
        },
        "fillOpacity": {
          "condition": {
            "test": {
              "and": [
                {"param": "highlight"},
                "length(data(\"highlight_store\"))"
              ]
            },
            "value": 0.9
          },
          "value": 0.3
        },
        "color": {
          "title": null,
          "field": "Category",
          "type": "nominal",
          "legend": {"orient": "right", "labelFontSize": 12}
        },
        "tooltip": [
          {"field": "Name", "title": "Name", "type": "nominal"},
          {
            "field": "Miles_per_Gallon",
            "title": "Miles/Gallon",
            "type": "quantitative",
            "format": ",.2f"
          },
          {
            "field": "Displacement",
            "title": "Displacement",
            "type": "quantitative",
            "format": ",.2f"
          }
        ]
      }
    }
  ]
}
```

Steps to reproduce:
1. Apply an interval selection on some points.
2. Drag and move the applied interval rectangle on other points.
3. I get an error in logs as mentioned above.

**Comment by joelostblom** [comment]
I can't reproduce this in the current (5.2) version of the online editor. Do you still see it @wahab896 ?
