### ISSUE TITLE
theta2Offset not offsetting

### ISSUE THREAD

**Issue by kolky001** [vega/vega-lite#7481]
Excuse me, first-time poster...

theta2Offset (in Vega Editor) does not appear to work no matter what values I enter...?

Link below:

https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIZw1LsJOsyGA7nRiHETOMtXLDypJhUiiA6mBZoIADKNLJkFob66lDB-oFooMRIggxqaADawAC+ALqFSsjqANbpIQCeOHAR9slK6kjKNAwQaADMAEyt7Z0QfWhiAAxK9HCBAPIAZvMQM2j8AIyUYgDsU-BpqJMhe0h9C0srqOubO0czJ72UawAsSlBs6rJw6gBKQ11ohxw7X0sXCByUEEw6jYlTgAHUaMp6GgnoVCkA/view

**Comment by kanitw** [comment]
will be fixed once #7723 is merged
