### ISSUE TITLE
wrong colors with explicit sort order

### ISSUE THREAD

**Issue by aplavin** [vega/vega-lite#7487]
When I explicitly specify a sort order for colors, the colors get mixed up - they correspond to wrong lines: [example](https://vega.github.io/editor/#/url/vega-lite/N4IgJgpgzgxgTgSwA4BcEHsB2IBcIDKK6MA1gARKIzRnoBmZArGQCoQwAWZAwugLZIAhpgQ10ANwhxWCPhAB0IADThBKQblABXOABtcq9QHooRUlHkwo4kAF8VKOMKh10cPrgDaoXenQktJAMoAE8+ACN0fRU6OH5NQw0cUHFBXS1oL1BQiKiDAEF8gAUAGWUQGCi3AzgIMDslbLDI-Tx8gFkALQA5csrfOANw3UFSBqbc1pB2-AAxFj6qwbwAc1qIbHsJloMASQAhdsWBofSIcZAcnbwAcQB5O5vj6rwkHSRdc9sAXXsQEggIWCzTyMVEujAUC8FSWIF+PxUfEEcBICRQISQ5zwugQmHOKiQ6FxKFwjgyfw2lTAuJWCQAHmjZBAAKoiEl4EIQZHlOjg+p4MBqL4qIHJECCFZrCArIUGOTCHl8gyUBDUcrozEGACOWmEaHUaEkDRhJzFUDc7M8IHuj3KHR6cLBEAhwMm6oxWJAmH4uLS5VgaSxoCcmBWQZAvOd-JN1VscZU6CEMAQ6ISkZdeH61RUAc+CRDYa8AEYlEXfipPmHMPzMFpdLo47YgA).
Compare to the same spec, but without `sort`: colors are correct here, [link](https://vega.github.io/editor/#/url/vega-lite/N4IgJgpgzgxgTgSwA4BcEHsB2IBcIDKK6MA1gARKIzRnoBmZArGQCoQwAWZAwugLZIAhpgQ10ANwhxWCPhAB0IADThBKQblABXOABtcq9QHooRUlHkwo4kAF8VKOMKh10cPrgDaoXenQktJAMoAE8+ACN0fRU6OH5NQw0cUHFBXS1oL1BQiKiDAEF8gAUAGWUQGCi3AzgIMDslbLDI-Tx8gFkALQA5csrfOANw3UFSBqbc1pB2-AAxFj6qwbwAc1qIbHsJloMASQAhdsWBofSIcZAcnbwAcQB5O5vj6rwkHSRdc9sAXXsQEggIWCzTyMVEujAUC8FSWIF+PxUfEEcBICRQISQ5zwugQmHOKiQ6FxKFwjgyfw2lTAuJWCQAHmjZBAAKoiEl4EIQZHlOjg+p4MBqL4qIHJECCFZrCArIUGOTCHl8gyUBDUcrozEGACOWmEaHUaEkDRhJzFvIgEOBk3VGKxIEw-FxaXKsDSWNATkwK3dIHNlrw-WqtmDKnQQhgCHRCT9-JN1RUrs+CU93q8AEYlGnfipPt7MPzMFpdLpg7YgA).

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue? I see a lookup and that you explicitly set the the scale range.

**Comment by aplavin** [comment]
This is as minimal as I can get it: [link](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUA5gE4D2aADvCMQIwgA0IAxiSiUVQEYoRMDWDEAA9kKeDUYBPUfABMAX3qFSFKrUEs2HOCG68BjEajlSZcAMyLlZSjuKyNrdlSIYwgo2LizTxuDStqFVsgh0ZNZx1Xd0MzCRBpPwUAXUUQAFsIIgEEEChJcgwqFABLADsixnIScqh4KCJMNIwyljBygnhQIS6QADMSjBR3HU8QNMlegaGRhJk0iO1QaeG1YMEsdjq4XFDBdWTGLCZUItyiCDKCM+XB1Z1F8fln+SA).
"gr1" should be black, and "gr2" should be red - they are actually shown in the opposite colors.
The `scale-range-field` is necessary to get wrong colors: otherwise there is just no notion of "wrong".

**Comment by domoritz** [comment]
I don't think this is totally unexpected. The spec sets only the range but not the domain so they may not have the same correspondence as before. 

If you want to use the color from a field, you can set `scale: null`. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUA5gE4D2aADvCMQIwgA0IAxiSiUVQEYoRMDWDEAA9kKeDUYBPUfABMAX3qFSFKrUEs2HOCG68BjEajlSZcAMyLlZSjuKyNrdlSIYwgo2LizTxuDStqFVsgh0ZNZx1Xd0MzCRBpPwUAXUUQAFsIIgEEEChJcgwqFABLADsixnIScqh4KCJMNIwyljBygnhQIS6QADMSjBR3HU8QNMlegaGRhJk0iO1QaeGqRcEsJlQiuDK0FBR5I6A)

I can't think of a good way to do both: using the color from the data and the category, though. Maybe @kanitw has an idea.

**Comment by aplavin** [comment]
Thanks for suggesting `scale: null`, I wasn't aware of that! However, your example doesn't show the color legend - how to display the color vs value correspondence?

> I don't think this is totally unexpected. The spec sets only the range but not the domain so they may not have the same correspondence as before.

The color range values are not set explicitly in the plot spec, but are taken from a data field. Is there any reasonable scenario at all when breaking color-category correspondence in such case is useful/expected?

**Comment by domoritz** [comment]
A scale defines a mapping from domain to range and `"scale": {"range": {"field": "color"}}` overwrite the range only.

I do agree that we could improve the sorting code to maintain the mapping. I think that would be an excellent improvement.
