### ISSUE TITLE
ExprRef as axis title

### ISSUE THREAD

**Issue by patkwee** [vega/vega-lite#7500]
It would be great if an ExprRef is allowed as axis title. 

The documentation (https://vega.github.io/vega-lite/docs/axis.html#title) currently states that only a string or null is allowed.

Though, I tried to use a {expr: "my_axis_title_param"} as title and it seems to work. Not sure if this is intended and an undocumented feature.

My use case is to change the axis title during runtime via a parameter instead of changing the spec and therefore rebuilding the whole chart.

**Comment by domoritz** [comment]
I added it to https://github.com/vega/vega-lite/issues/7264. I have a fix for it and so we should be adding this soon.
