### ISSUE TITLE
conditional render label color based on another key value in the same data source but it does not work.

### ISSUE THREAD

**Issue by 6vvvvvv** [vega/vega-lite#7507]
In my case, I want to render the label color of axis y ( section ) from black to red based on its resilience value which equals to 0. 

For example, the fifth one **< 4. Hygiene & Cleaning >** should be red instead of black but I can not just get it right anyway. 

I wonder if it is a bug or I simply misunderstand the use of **datum**.

My code as follows:
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "usermeta": {"embedOptions": {"renderer": "svg"}},
  "data": {
    "values": [
      {
        "section": "1. General Health & Safety",
        "Index": 38.40277777777778,
        "resilience": 31
      },
      {
        "section": "10. Environmental Accidents",
        "Index": 38.40277777777778,
        "resilience": 19
      },
      {
        "section": "2. Health - Process",
        "Index": 38.40277777777778,
        "resilience": 39
      },
      {
        "section": "3. Health - People",
        "Index": 38.40277777777778,
        "resilience": 47
      },
      {
        "section": "4. Hygiene & Cleaning",
        "Index": 38.40277777777778,
        "resilience": 0
      },
      {
        "section": "5. Health Care & Working Conditions",
        "Index": 38.40277777777778,
        "resilience": 25
      },
      {
        "section": "6. External Pollution & Extreme Weather Conditions",
        "Index": 38.40277777777778,
        "resilience": 16
      },
      {
        "section": "7. Hazardous Materials/Substances",
        "Index": 38.40277777777778,
        "resilience": 25
      },
      {
        "section": "8. Safety Accidents",
        "Index": 38.40277777777778,
        "resilience": 46
      },
      {
        "section": "9. Subcontractors Training",
        "Index": 38.40277777777778,
        "resilience": "1"
      }
    ]
  },
  "config": {"view": {"stroke": null}},
  "height": 300,
  "autosize": {"resize": true},
  "layer": [
    {
      "mark": {"type": "bar", "cornerRadiusEnd": 2},
      "encoding": {
        "x": {
          "field": "resilience",
          "type": "quantitative",
          "title": null,
          "axis": {"grid": true},
          "scale": {"domain": [0, 100]}
        },
        "y": {
          "field": "section",
          "type": "ordinal",
          "axis": {
            "grid": false,
            "domain": false,
            "ticks": false,
            "labelAlign": "left",
            "labelBaseline": "middle",
            "labelPadding": -5,
            "labelOffset": 0,
            "labelColor": {
              "condition": {"test": "datum.resilience === 0", "value": "red"},
              "value": "black"
            },
            "title": null
          }
        },
        "tooltip": {
          "field": "resilience",
          "type": "quantitative",
          "format": ".0f"
        },
        "color": {
          "field": "resilience",
          "type": "quantitative",
          "title": "Score",
          "scale": {
            "domain": [0, 30, 50, 55, 60, 65, 70, 75, 80, 90, 100],
            "range": [
              "#DE7363",
              "#FB9F38",
              "#F9B821",
              "#FBE8C9",
              "#F5DA01",
              "#E2D91E",
              "#CBD641",
              "#B6D35F",
              "#A2D180",
              "#7CC895",
              "#52BEA9"
            ]
          }
        }
      }
    },
    {
      "mark": {"type": "rule", "color": "red", "size": 3},
      "encoding": {
        "x": {
          "aggregate": "max",
          "field": "Index",
          "type": "quantitative",
          "axis": null,
          "format": ".0f",
          "title": "Module Resilience"
        }
      }
    }
  ]
}

**online editor:**

[https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAEyUAVhDYA7EABoQDCHABOCOJhSpQiJnAAmAeRyZ2siGlBq4sw+vVoQEYmRABfD0sNJt1kGIkQQY4K1QAbVBVKHM5ZwBGSgACAHE7dWDkgAk4YPpkgDJkgGUkADMtAE9FEABJezgADzQAZgAOSgAWAAYxAHZBoeH2pVsIGmE7KDg2hO9ouFiLRJ6UgFFZYho1OU1ZbUFkgEEoKBoHA6slBocW1A7uvuGX-tGQccmaadnUBIBOBYuJZxeToCQ5PKCAr8ZIABV2Mwg13qjXuj16A1eQ3enymshmbUBCkWy3i6FaKVy+RgyVhcLgbBwglmNzRbU6mOxOLGYS+PzQXX6QJioOcXSpVVoGSKyQAwiykLIaLJ3Gy7hynljubi+fjCageiKQSt0ABWKlQgpypC2WUAdTYagA1iqyPK5IY6BYUbdmpqudy3ryJvrfmIzcayWCQAA2DZNTDqWRZOFsQQhUGy9aJ2yaZL2vL0dQe+zeuS+9kPTnPIO60PfAm-BKxqNi9D9KlIABetsMbBUyQAsn51DRghACCVmBBtE3Kxrq1qg8GPnrGwaI23TSBOqUKtUTmcLnZMAv-UvAzqQ-ym4LWyTgdHnP8UtOmFA5Jg1EhYk6IMkAAqP4qm6tR+uiNbati9a3gaIAJJ4AC63ggJ+sjlDQ7i6IE3wAO4BLOuzOr8sgMBmXhKPAWFYG0PQ9EoSAMJgbATN2vw2Hy7FoN+oSoYISBVE4kSgMgLoBJgVQ4L8IBMLatSfmosjqAASkgXoqJshhoGIqHTGwXqqgE9ygJhcCCNp6B4hurIgJJ0nOAAjgwSrmNo5ikLUbksmgZEZoxTQ0OEoBkGoFw8WofFKNAwQcSA-bICqaARAxCT0ShqE1DhZkWc4oorEo9kyU6hnBLUSCBcFICheFqDlBOcA+GwiVgvVgiqIVNBQM64RtR1IACQYgjHMIZAxiy5SYLUg3mQAQkgqjCMpzgIBchg+UoM2CHC6mGdh-BmptSBDcY5TlKoU2GkdQ1yumToBOhXrtqASazs4viYAwCCUNZPzJAAvIDyQ9LUQQhDJtjaahYOhM4TACd1nidZgPmoH5giUXZbDpuYOABDlllrg2AqFVJMnOa5dB+DQnlKOUTrIJdICUD05RI2hd1qPj3y5VZ64k3ZZNOS5BxUx5tneTJJSKbZMWo6ACVIElkQMa0DFmurh2xgxsaHf0DH9Id7QMf8qXpWMSpkL8EQgAAxAAIus-StLGrS1LbABis3-B7HTux7-yze0YiIUonuzes7Ryv8-tmvbxw9KHdvrGI9v-Ak6zu3Ks327GXRJ7bs2xvbrRmh77vHKnCTG+7-RynK7T-Ga7tmmIEfHDHGWUaJtrOhJQtWeRtmfoI9189p0U0NxDx6QSBlgThJkgEgZChXwSYrRVtQE84EFeQPIAU6L7k07ZFVBb55GCHTDN+M4LNs8jqMgEOBlD8kKn83eXgeChQA](url)

the data source shoud be named data source but here I make it inline so you can see more clearly.

Thanks for your help.

**Comment by domoritz** [comment]
Label expressions only have access to the labels. 

```
"labelColor": {
  "condition": {"test": "warn(datum).value === '4. Hygiene & Cleaning'", "value": "red"},
  "value": "black"
},
```

**Comment by 6vvvvvv** [comment]
> Label expressions only have access to the labels.
> 
> ```
> "labelColor": {
>   "condition": {"test": "warn(datum).value === '4. Hygiene & Cleaning'", "value": "red"},
>   "value": "black"
> },
> ```

I guess so. Thank you. I will try to find another way.

**Comment by domoritz** [comment]
The solution I showed you here works. You can remove the warn call.

**Comment by macamhi** [comment]
Does this mean there is no solution currently for highlighting a label value in an axis based on a value of another axis?

**Comment by domoritz** [comment]
Unfortunately, what you are asking for is not possible. An axis gets an aggregated dataset of the scale domain. There is no 1:1 correspondence between different fields/axes. This isn't a limitation of Vega but a general limitation. If you do happen to have a correspondence, then you can use the field that the axis shows.

**Comment by macamhi** [comment]
Ok, thanks again for the answers.
