### ISSUE TITLE
Documentation about dynamic selection parameters

### ISSUE THREAD

**Issue by alaindebecker** [vega/vega-lite#7525]
The examples given here 

- https://vega.github.io/vega-lite/docs/selection.html
- https://vega.github.io/vega-lite/docs/parameter.html#select

are good but they are difficult to understand because they involve html input fields which are not in the attached json.

It would be nice to write nearby :

`<select name="point" onchange="buildProjection('point')">&lt;option value="multi"&gt;multiple&lt;/option&lt;option value="single">a single&lt;/option>&lt;/select>`
`<label onclick="buildProjection('point')"><input type="checkbox" name="point" value="cylinders">Cylinder(s)</label>
`
`<label onclick="buildProjection('point')"><input type="checkbox" name="point" value="origin">Origin(s)</label>
`

And to explain where to find ` buildProjection`, `point` in the json, as well as the minimal code to be writen in the json. 

Maybe it is already explained somewhere else, but I couldn't find it.

**Comment by alaindebecker** [comment]
Note: After a while I found [this page](https://vega.github.io/vega-lite/docs/bind.html), which learns me after a few reading that the `<input>` and `<select>`  are created by Vega-lite.

Which is a nice feature, but by no mean obvious for somebody whose last usage of javascript precludes V7.

**Comment by domoritz** [comment]
I'm glad you found the explanation. If you have a concrete suggestion, please send us a pull request. Otherwise, I don't think this issue is actionable for us.
