### ISSUE TITLE
Can't apply separate color scheme to each chart of a vconcat

### ISSUE THREAD

**Issue by woolyninja** [vega/vega-lite#7601]
I'm current trying to stack 3 different charts vertically using vconcat. The first chart is a line chart and I can give the mark itself a color.

```json
...
"mark": {
  "type": "line",
  "point": false,
  "color": "#ce0000"
}
...
```

The second chart is a bar chart and I want to apply a yelloworangered scheme to it based on a count field.

```json
...
"color": {
  "field": "count",
  "scale": {
    "scheme": "yelloworangered"
  }
}
...
```

The third chart is an area chart with two values folded into their own rows. I want to apply a "blues" color scheme to the areas.

```json
...
"transform": [
  { "fold": ["sent", "recv"] },
]
...
"color": {
  "field": "key",
  "type": "nominal",
  "scale": {
    "scheme": "blues"
  }
}
...
```

No matter what I do the third chart (the area chart) always gets the color scheme defined in a chart above it.

If I just render the area chart on its own it gets the correct color scheme.
If I move the area chart above the bar chart then both get the "blues" color scheme applied.

**Comment by kanitw** [comment]
By default, we use a shared color scale for multi-view plot. 

Please try to use `"resolve": {"scale": {"color": "independent"}}` as shown in http://vega.github.io/vega-lite/docs/resolve.html.

If this doesn't work, feel free to re-open the issue.

**Comment by woolyninja** [comment]
@kanitw thank you! Once I added that to the concatenation schema it all worked as expected!
