### ISSUE TITLE
here's something else that broke in the last few days of checkins (syntax update?)

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#762]
Kindly tell me the syntax update? (Is there a place somewhere where you are documenting syntax updates?)

<img width="266" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/976970/11320820/d8c91fca-905b-11e5-8c50-a7f1e1eb7d2e.png">

```{"marktype": "bar", "data": {"values": [{"m_teps": 33.5330810546875, "dataset": "ak2010"}, {"m_teps": 21.458358764648438, "dataset": "belgium_osm"}, {"m_teps": 1023.6077880859375, "dataset": "cit-Patents"}, {"m_teps": 502.16387939453125, "dataset": "coAuthorsDBLP"}, {"m_teps": 10.410270690917969, "dataset": "delaunay_n13"}, {"m_teps": 187.35877990722656, "dataset": "delaunay_n21"}, {"m_teps": 443.1048889160156, "dataset": "delaunay_n24"}, {"m_teps": 55.096927642822266, "dataset": "europe_osm"}, {"m_teps": 3530.5595703125, "dataset": "kron_g500-logn21"}, {"m_teps": 79.42512512207031, "dataset": "road_usa"}, {"m_teps": 2050.32421875, "dataset": "soc-LiveJournal1"}]}, "encoding": {"y": {"scale": {"type": "log"}, "type": "quantitative", "name": "m_teps", "axis": {"title": "MTEPS"}}, "x": {"type": "ordinal", "name": "dataset"}}}```

**Comment by kanitw** [comment]
I just pull master and I can't reproduce this ...

Can you pull latest master and run `npm run build`

https://www.evernote.com/l/AAiGxO05PCxF37i_tg7jPFUQfnvVLXuoeRg

**Comment by jowens** [comment]
Weird. I'm doing it in the vega-lite editor:
<img width="838" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/976970/11320891/94b47a84-905e-11e5-8d71-86778fbe540f.png">

**Comment by jowens** [comment]
Here's the VL:
```{"marktype": "bar", "data": {"values": [{"m_teps": 33.5330810546875, "dataset": "ak2010"}, {"m_teps": 21.458358764648438, "dataset": "belgium_osm"}, {"m_teps": 1023.6077880859375, "dataset": "cit-Patents"}, {"m_teps": 502.16387939453125, "dataset": "coAuthorsDBLP"}, {"m_teps": 10.410270690917969, "dataset": "delaunay_n13"}, {"m_teps": 187.35877990722656, "dataset": "delaunay_n21"}, {"m_teps": 443.1048889160156, "dataset": "delaunay_n24"}, {"m_teps": 55.096927642822266, "dataset": "europe_osm"}, {"m_teps": 3530.5595703125, "dataset": "kron_g500-logn21"}, {"m_teps": 79.42512512207031, "dataset": "road_usa"}, {"m_teps": 2050.32421875, "dataset": "soc-LiveJournal1"}]}, "encoding": {"y": {"scale": {"type": "log"}, "type": "quantitative", "name": "m_teps", "axis": {"title": "MTEPS"}}, "x": {"type": "ordinal", "name": "dataset"}}}```

**Comment by jowens** [comment]
And here's the Vega (produced from vl2vg):
```{"spec":{"width":144,"height":200,"padding":"auto","data":[{"name":"source","values":[{"m_teps":33.5330810546875,"dataset":"ak2010"},{"m_teps":21.458358764648438,"dataset":"belgium_osm"},{"m_teps":1023.6077880859375,"dataset":"cit-Patents"},{"m_teps":502.16387939453125,"dataset":"coAuthorsDBLP"},{"m_teps":10.410270690917969,"dataset":"delaunay_n13"},{"m_teps":187.35877990722656,"dataset":"delaunay_n21"},{"m_teps":443.1048889160156,"dataset":"delaunay_n24"},{"m_teps":55.096927642822266,"dataset":"europe_osm"},{"m_teps":3530.5595703125,"dataset":"kron_g500-logn21"},{"m_teps":79.42512512207031,"dataset":"road_usa"},{"m_teps":2050.32421875,"dataset":"soc-LiveJournal1"}],"format":{"type":"json","parse":{"m_teps":"number"}},"transform":[{"type":"filter","test":"datum.m_teps!==null"},{"type":"filter","test":"datum.m_teps > 0"}]}],"marks":[{"name":"cell","type":"group","properties":{"enter":{"width":{"value":144},"height":{"value":200}}},"marks":[{"type":"rect","from":{"data":"source"},"properties":{"update":{"xc":{"scale":"x","field":"dataset"},"width":{"value":12,"offset":-1},"y":{"scale":"y","field":"m_teps"},"y2":{"field":{"group":"height"}},"fill":{"value":"#4682b4"}}}}],"scales":[{"name":"x","type":"ordinal","domain":{"data":"source","field":"dataset","sort":true},"range":[0,144],"round":true,"clamp":true,"bandWidth":12,"padding":1,"points":true},{"name":"y","type":"log","domain":{"data":"source","field":"m_teps","sort":true},"range":[200,0],"round":true,"clamp":true,"nice":true}],"axes":[{"type":"x","scale":"x","grid":false,"ticks":5,"title":"dataset","properties":{"labels":{"angle":{"value":270},"align":{"value":"right"},"baseline":{"value":"middle"},"text":{"template":"{{ datum.data | truncate:25}}"}}}},{"type":"y","scale":"y","format":"s","grid":true,"layer":"back","title":"MTEPS","properties":{"grid":{"stroke":{"value":"#000000"},"strokeOpacity":{"value":0.08}}}}]}]}}```

**Comment by kanitw** [comment]
Oh I see, since Vega-Lite `0.9.0` hasn't been released,  the online editor still expect the old type (`O`, `Q`, `T`, `N')  

I recommend that if you want to use "master"  of both vg and vl, you should have a vega-editor running locally.   Note that as we're changing some of vega-lite's API for `0.9.0`, you need to use [this branch](https://github.com/vega/vega-editor/pull/30) to make it work with current vega-lite's master.

**Comment by jowens** [comment]
OK. Switching back to old type results in vega (see above) that works in the Vega editor now, no worries. But it does *not* display with the following scaffold; has there been a change there as well?

```<html>
  <head>
    <title>Vega Scaffold</title>
    <script src="http://vega.github.io/vega-editor/vendor/d3.min.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/d3.geo.projection.min.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/topojson.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/d3.layout.cloud.js"></script>
    <script src="http://vega.github.io/vega/vega.min.js"></script>
  </head>
  <body>
    <div id="vis"></div>
  </body>
<script type="text/javascript">
// parse a spec and create a visualization view
function parse(spec) {
  vg.parse.spec(spec, function(chart) { chart({el:"#vis"}).update(); });
}
parse("_g_bar.json");
</script>
</html>
```

**Comment by jowens** [comment]
_g_bar.json:

```{"spec":{"width":144,"height":200,"padding":"auto","data":[{"name":"source","values":[{"m_teps":33.5330810546875,"dataset":"ak2010"},{"m_teps":21.458358764648438,"dataset":"belgium_osm"},{"m_teps":1023.6077880859375,"dataset":"cit-Patents"},{"m_teps":502.16387939453125,"dataset":"coAuthorsDBLP"},{"m_teps":10.410270690917969,"dataset":"delaunay_n13"},{"m_teps":187.35877990722656,"dataset":"delaunay_n21"},{"m_teps":443.1048889160156,"dataset":"delaunay_n24"},{"m_teps":55.096927642822266,"dataset":"europe_osm"},{"m_teps":3530.5595703125,"dataset":"kron_g500-logn21"},{"m_teps":79.42512512207031,"dataset":"road_usa"},{"m_teps":2050.32421875,"dataset":"soc-LiveJournal1"}],"format":{"type":"json","parse":{"m_teps":"number"}},"transform":[{"type":"filter","test":"datum.m_teps!==null"},{"type":"filter","test":"datum.m_teps > 0"}]}],"marks":[{"name":"cell","type":"group","properties":{"enter":{"width":{"value":144},"height":{"value":200}}},"marks":[{"type":"rect","from":{"data":"source"},"properties":{"update":{"xc":{"scale":"x","field":"dataset"},"width":{"value":12,"offset":-1},"y":{"scale":"y","field":"m_teps"},"y2":{"field":{"group":"height"}},"fill":{"value":"#4682b4"}}}}],"scales":[{"name":"x","type":"ordinal","domain":{"data":"source","field":"dataset","sort":true},"range":[0,144],"round":true,"clamp":true,"bandWidth":12,"padding":1,"points":true},{"name":"y","type":"log","domain":{"data":"source","field":"m_teps","sort":true},"range":[200,0],"round":true,"clamp":true,"nice":true}],"axes":[{"type":"x","scale":"x","grid":false,"ticks":5,"title":"dataset","properties":{"labels":{"angle":{"value":270},"align":{"value":"right"},"baseline":{"value":"middle"},"text":{"template":"{{ datum.data | truncate:25}}"}}}},{"type":"y","scale":"y","format":"s","grid":true,"layer":"back","title":"MTEPS","properties":{"grid":{"stroke":{"value":"#000000"},"strokeOpacity":{"value":0.08}}}}]}]}}```

**Comment by kanitw** [comment]
> parse("_g_bar.json");

I think your `parse` method expects a parsed json object, not a url.  :)

**Comment by jowens** [comment]
Yeah, it's a file. (This has worked for a couple of months now!)

**Comment by kanitw** [comment]
Okay -- just checked.   That's actually an alternative Vega API that I'm not aware of. 

The problem here is that your "_g_bar.json" contains a vega-embed spec, not a vega spec.  
Just remove the `{"spec:":  <vega_spec>}` wrapper and you should be good :)

**Comment by jowens** [comment]
Secret APIs! Love it! (This worked until just a couple of days ago, so something else changed, presumably in vega master.) I will ask guidance once we get our documentation system all set up (if I should be using vega or vega-embed, URLs or files, etc.). Thanks for how to fix it!

**Comment by jowens** [comment]
But, _g_bar.json was produced by vl2vg, so is there an option I can pass to vl2vg so it *doesn't* produce a vega-embed spec?

**Comment by kanitw** [comment]
> Secret APIs! 

It's actually not secret.  It's documented in https://github.com/vega/vega/wiki/Runtime.  But I never used it so I totally forgot that you can parse URL.


> But, _g_bar.json was produced by vl2vg, so is there an option I can pass to vl2vg so it doesn't produce a vega-embed spec?

Ah, now you catch my bug!   Now `vl.compile` return  
```
{
   spec: <vg_spec>
}
```

simply because we want to add warnings / errors as another property in the returned object.  And that happens to look like vg embed.  And I totally forgot to update `vl2vg`!

I'm gonna fix this now.   Thanks a lot!

**Comment by jowens** [comment]
Thank you for putting up with what are surely less-than-intelligent questions from me that lead to you discovering bugs. :)

**Comment by kanitw** [comment]
:)
