### ISSUE TITLE
Non-cartesian plots shouldn't include view stroke by default 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#7621]
![image](https://user-images.githubusercontent.com/111269/127719142-87dc72a0-89a4-46e3-90ff-49ffee29c593.png)

**Comment by domoritz** [comment]
Why not? In a multi view chart it makes it easier to see different radii. 

I'm playing devils advocate here. Let's consider whether the issue really are pie charts or single views more broadly.

**Comment by kanitw** [comment]
> Why not? In a multi view chart it makes it easier to see different radii.

Yes, but (1) I bet people use non-small multiple pie charts way more often than multi-views 
and (2) for pie chart in particular, the radius is fixed. But I think you want to consider [Radial chart](http://vega.github.io/vega-lite/examples/arc_radial.html), which FWIW we did hide the stroke in our example. 

> whether the issue really are pie charts or single views more broadly.

I think the line I'd draw is whether something is a Cartesian plot (has x/y).  For example, I think 
maps like this [one](http://vega.github.io/vega-lite/examples/geo_choropleth.html) shouldn't have default view stroke by default.

**Comment by domoritz** [comment]
That makes sense. I like it if we remove the view stroke from maps as well.
