### ISSUE TITLE
Vega-tooltip image support

### ISSUE THREAD

**Issue by ehknight** [vega/vega-lite#7635]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues.

I could find any duplicate issues

- [x] Describe how to reproduce the bug.

*(x-post from Altair issue here: https://github.com/altair-viz/altair/issues/2474)*

My understanding is that to render tooltips, Vega-Lite and Altair uses the `vega-tooltip` plugin. Per that project's [README](https://github.com/vega/vega-tooltip), one awesome feature that library has is the ability to render images as part of the tooltip with the image key. From the docs:

 > Supports special keys title (becomes the title of the tooltip) and image (used as the url for an embedded image)

However, this does not seem to be supported in Altair, because it is does not seem to be [added yet](https://github.com/altair-viz/altair/issues/2474#issuecomment-875919974) to Vega-Lite. This would be a very useful feature to support.

- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) spec in JSON, wrapped by triple backticks like this:

Works:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-724890d4e94cac4976cbd99ef3589be4"
  },
  "datasets": {
    "data-724890d4e94cac4976cbd99ef3589be4": [
      {
        "a": 1.0,
        "b": 1.0
      }
    ]
  },
  "encoding": {
    "tooltip": [
      {
        "field": "a",
        "title": "My Cool Tooltip",
        "type": "quantitative"
      }
    ],
    "x": {
      "field": "a",
      "type": "quantitative"
    },
    "y": {
      "field": "b",
      "type": "quantitative"
    }
  },
  "mark": "circle",
  "selection": {
    "selector003": {
      "bind": "scales",
      "encodings": [
        "x",
        "y"
      ],
      "type": "interval"
    }
  }
}
```

Does not work:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-724890d4e94cac4976cbd99ef3589be4"
  },
  "datasets": {
    "data-724890d4e94cac4976cbd99ef3589be4": [
      {
        "a": 1.0,
        "b": 1.0
      }
    ]
  },
  "encoding": {
    "tooltip": [
      {
        "field": "a",
        "title": "My Cool Tooltip",
        "type": "quantitative",
        "image": "https://picsum.photos/200/300.jpg"
      }
    ],
    "x": {
      "field": "a",
      "type": "quantitative"
    },
    "y": {
      "field": "b",
      "type": "quantitative"
    }
  },
  "mark": "circle",
  "selection": {
    "selector003": {
      "bind": "scales",
      "encodings": [
        "x",
        "y"
      ],
      "type": "interval"
    }
  }
}
```

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

<img width="554" alt="Screen Shot 2021-08-03 at 10 33 16 AM" src="https://user-images.githubusercontent.com/15150351/128060334-bf969dc3-259e-4cba-b47a-ca03126a5945.png">

**Comment by ehknight** [comment]
@domoritz thanks for the reply — what do you mean by the field?

**Comment by domoritz** [comment]
The name of the references field/column of your data.

**Comment by ehknight** [comment]
I see, thanks @domoritz. I'm new to Vega, and I feel I must be missing something, because when I add a column called image, and reference it in the tooltip, it just displays the URL in that column, not the image itself.

Also, it may be helpful if [the docs](https://vega.github.io/vega-lite/docs/tooltip.html#using-tooltip-channel) could have a usage example of this :). Thanks again for the help

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-724890d4e94cac4976cbd99ef3589be4"
  },
  "datasets": {
    "data-724890d4e94cac4976cbd99ef3589be4": [
      {
        "a": 1.0,
        "b": 1.0,
        "image": "https://picsum.photos/200/300.jpg"
      }
    ]
  },
  "encoding": {
    "tooltip": [
      {
        "title": "My Cool Tooltip",
        "field": "image"
      }
    ],
    "x": {
      "field": "a",
      "type": "quantitative"
    },
    "y": {
      "field": "b",
      "type": "quantitative"
    }
  },
  "mark": "circle",
  "selection": {
    "selector003": {
      "bind": "scales",
      "encodings": [
        "x",
        "y"
      ],
      "type": "interval"
    }
  }
}
```

<img width="389" alt="Screen Shot 2021-08-07 at 7 59 41 PM" src="https://user-images.githubusercontent.com/15150351/128619285-ec78ee5b-cf6d-4adc-b213-e8a81df335bd.png">

**Comment by domoritz** [comment]
Take a look at https://github.com/vega/vega-tooltip/blob/next/examples/specs/images.json (introduced in https://github.com/vega/vega-tooltip/pull/389).

**Comment by ehknight** [comment]
@domoritz it looks like this is an example written in Vega. The Altair author suggested that the image feature is not supported in Vega-lite, and so far it looks like he's right (?) — [link to comment](https://github.com/altair-viz/altair/issues/2474#issuecomment-875919974)

**Comment by domoritz** [comment]
I'll look into this when I have more time. Thanks for raising the issue.

**Comment by ehknight** [comment]
Thanks for looking into this @domoritz. In the meantime, is it possible to embed raw HTML into the tooltip, or use some other workaround? Thanks.

**Comment by domoritz** [comment]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
        {"image": "data/ffox.png"},
        {"image": "data/gimp.png"},
        {"image": "data/7zip.png"}
      ]
  },
  "mark": {"type": "text", "tooltip": true},
  "encoding": {
    "text": {"field": "image"},
    "y": {"field": "image", "axis": null}
  }
}
```

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgpkhkcGghgQQAZplsAB6UOLJkIAC+ConIKWn+GbRmBUWl5SBJVeg1SAQA7ABeWg3FJQC6ZSDI6gDWaKCYAJ44qeiYcLmYwZhsbII6OGiY6jGjcLJQbMo0jeEgy6vTIJk0cILKaa2po7N3D08v6G-BSFyNAgaFkDEEghKUKAA)

<img width="166" alt="Screen Shot 2021-09-23 at 10 55 20" src="https://user-images.githubusercontent.com/589034/134531068-15a0fc7c-b472-4859-aa0d-8808d1660a3b.png">
