### ISSUE TITLE
Ordinal and nominal types produce the same Vega specs

### ISSUE THREAD

**Issue by wylieconlon** [vega/vega-lite#7654]
The [documentation for ordinal type](https://vega.github.io/vega-lite/docs/type.html#ordinal) says that the default sorting is the "natural" sorting, but both ordinal and nominal types are generating scales with `sort: true` in Vega.

For example, if I want to render months in sequential order, my data might already be sorted. Alphabetical sorting is not helpful in this case. To reproduce, try this spec. The expected behavior is that the months should be rendered in the same order as they are provided:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"month": "March", "amount": 5000},
      {"month": "April", "amount": 12000},
      {"month": "May", "amount": 3750},
      {"month": "June", "amount": 9000}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "month", "type": "ordinal"},
    "y": {"field": "amount", "type": "quantitative"}
  }
}
```

Compare [ordinal months](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoBHPpoQAWSQAnWIpBJTDWZjRiADF4C+Ck2ZgLAEEcGxpBByc2FzdUAEYAJi8PX39XQPRrAE9I51c0AGYAdk9UkFN0iwApFzhc6PzUAE5k7wBdX3LbAGsLJlsHOFkoNmUaWTI0UAAPKZAAMxo4QWULCvMlTCycOvQ2GzHZHRBOnM0FpZWLKJiHLZ2LAEcGJFc6NRpSE+9vIA) vs [nominal months](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoBHPpoQAWSQAnWIpBJTDWZjRiADF4C+Ck2ZgLAEEcGxpBByc2FzdUAEYAJi8PX39XQPRrAE9I51c0AGYAdk9UkFN0iwApFzhc6PzUAE5k7wBdX3LbAGsLJlsHOFkoNmUaWTI0UAAPKZAAMxo4QWULCvMlTCycOvRZNgRxnRBOnM0FpZWLKJiHLZ2LAEcGJFc6NRpSE+9vIA) and you'll see that they are the same spec.

As a workaround, you can add a `transform` to calculate the natural sort order, but this should not be required:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"month": "March", "amount": 5000},
      {"month": "April", "amount": 12000},
      {"month": "May", "amount": 3750},
      {"month": "June", "amount": 9000}
    ]
  },
  "mark": "bar",
  "transform": [{ "window": [{ "op": "rank", "as": "rank" }] }],
  "encoding": {
    "x": {"field": "month", "type": "ordinal", "sort": {"field": "rank"}},
    "y": {"field": "amount", "type": "quantitative"}
  }
}
```

Edit: I don't believe this is the same issue as https://github.com/vega/vega-lite/issues/4229 and https://github.com/vega/vega-lite/issues/5013, but they look related.

**Comment by domoritz** [comment]
I see. So you are proposing just not to set `sort: true` for nominal data. I think that would be okay. Do you want to try it and send a pull request to change the behavior?

**Comment by wylieconlon** [comment]
@domoritz I was expecting that ordinal data would be unsorted, but nominal data would be sorted alphabetically by default. Is that what you're expecting too? Happy to send a PR for this.

**Comment by domoritz** [comment]
I would maybe expect the opposite. Ordinal and nominal are really just categorical data. Sorted categorical data is ordinal.

**Comment by wylieconlon** [comment]
Yes, but I thought that order doesn't matter for nominal data, but it does matter for ordinal data. So with the example of Months data the position of each month can't be changed, which is why I think it's a bug that Vega-Lite applies sorting to my pre-sorted ordinal data.

**Comment by domoritz** [comment]
If you have pre-sorted data, you could simply disable the default sorting, no?

**Comment by wylieconlon** [comment]
Yes, using `"sort": null` is a simpler way to do this instead of using `transform`. But this is still a workaround, and doesn't fix the underlying issue. The underlying issue is that ordinal data should not be sorted alphabetically, because it has a natural order.

I went looking for [other examples of ordinal data](https://en.wikipedia.org/wiki/Ordinal_data) and found that few of the examples would work correctly in Vega-Lite today. Here is a [Likert scale example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoKGvJsATgE80IADI0A1nEUgkCNg1mY0ARgC+CiZmZJY26A7OAAQAymwIcADuMGqu7p7eaABMgcGY5ta2AHJwDJgWOmkeXj6oAMy5IKb5oYXoACI0EMLRcQnJqUrpNWgALI3NBeEgnd1OLkPVmahi-gC6gSDIFo62TEgWrnCyUGzKNLJkaKDhoABmNHCCyraTrTZKmFY4LuiW57JKpsAB7XEAPJ4vdDDTKfb6-EAARwYSG8dDUNFIIH8OKAA)

<img width="324" alt="Screen Shot 2021-08-17 at 6 16 40 PM" src="https://user-images.githubusercontent.com/666475/129807931-4ec40f50-1b34-4632-ba48-7641905f8f6d.png">

The input data here is in the correct order, but Vega-Lite has reordered it into alphabetical order.

**Comment by domoritz** [comment]
A challenge is that ordinal is often numerical in which case it does make sense to sort. I think we can only rarely assume that data comes in the correct order already. It's particularly challenging with streaming data or then we have to perform aggregation first.

@kanitw I think you could help us with some insights here.

**Comment by jakevdp** [comment]
I would disagree in classifying `"sort": null` as a workaround. Rather, I consider it the documented API to do what you have in mind.

**Comment by jwoLondon** [comment]
I agree with Jake and Dom here. To me I see a declaration of data as nominal as stating that there is no particular intrinsic order (and therefore unimportant). Similarly with a declaration of ordinal we are asking Vega-Lite to ensure its sequencing reflects the natural order of the data, not the insert order, which could be arbitrary. That is the value of a declarative system - we simply describe the property of the data and don't have to worry about implementing something that reflects that property.

**Comment by domoritz** [comment]
We had a long discussion about ordinal/nominal/categorical types in https://github.com/vega/vega-lite/issues/6633.

**Comment by wylieconlon** [comment]
Good discussion here. I'm a bit confused by the comments about implicit sort order- like the row number. Row number isn't always meaningful, but neither is alphabetical order. In both scenarios, Vega-Lite is making a choice that users won't always prefer. For my main use case of visualizing database queries, the row order of the data is always meaningful.

So for @domoritz and @jwoLondon: are you saying that it's more common to sort by alphabetical value instead of row order? That doesn't match my experience, which is why I think the default should be changed.

**Comment by jakevdp** [comment]
I would be strongly against changing the default behavior for something as central to so many visualizations as the default sort order. Changing it now would break too many existing charts: whatever the merits of a potential change, that ship has sailed long ago.

**Comment by domoritz** [comment]
I agree with @jakevdp. We could consider it for 6.0 if we have a very strong reason but since settings `sort: null` isn't too cumbersome, we would need a very convincing reason.

I think Vega's use case is a bit different from SQL since we can't always expect the sort order of some data to be meaningful especially when we have streaming data.

**Comment by kanitw** [comment]
I think there are two topics here:

1) What's the right default for nominal? 

I could see an argument that `sort: null` should be the default for nominal.
However, in many cases, the original data is not meaningful, and thus applying `sort: true` by default seems sensible and changing this will be a massive breaking change.

A more middle ground approach is to add a config for nominal's default sort (which is `true` by default). With this config for people who use in SQL, they can set it to `null` in the config, and thus can reuse this in the config, but don't have to repeat `sort: null` in encoding every time.

(That said, if we were to do this, we need to determine where is the best place to put this in the config.  (for example, should it be `config.sortNominal` or something)?   


2) What does ordinal mean? 

To me, I see the confusion above as another evidence of my concern in #6633.  (We have "ordinal" type, but the ordinal type doesn't provide the right affordance that to make it work reasonable at all, one should specify custom "sort" order for that ordinal field.)

If it's up to me alone, I'd rather kill this confusion (and remove internal complexity) by deprecating nominal/ordinal (which will be 100% backward compatible for nominal, and mostly for ordinal except for color) and introduce "type: categorical" (which is basically = nominal but sounds way less like a jargon) in the next major version.  

I know that there are pushbacks as we discussed earlier #6633, but this discussion here confirms my feeling that there is a fundamental confusion here.   (Plus, given that type is in the first chapter of our teaching material, we better make this thing *not* confusing). 

After all, I think type is so fundamental to our language, teaching, and also internal complexity that it justifies the cost. 

(If we do this then, `config.sortCategorical` might make more sense.)

**Comment by domoritz** [comment]
I am with @kanitw.

**Comment by wylieconlon** [comment]
Yes, the next steps described by @kanitw make sense. Should there be a new issue for the sort order config?

**Comment by domoritz** [comment]
Since it's a bigger change. I think this issue is sufficient.

**Comment by kanitw** [comment]
I think we can treat this issue as a request for sort order config, and tracked type: categorical in #6633.

**Comment by kanitw** [comment]
Let's break close this and break it into an issue for sort order config (#7656) and track the type: categorical in #6633
