### ISSUE TITLE
Allow time unit to be used as most significant unit. 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#775]
When we format or bin by a time unit, we should offer an option to use it as the most significant unit. 

For example, you can specify the time unit `month` but what if you want the year and the month (`YYYY-MM`) instead of just the month (`MM`)? 

Options:
1. Offer time units for all possible cases `month`, `year`, `year-month`, ...
2 Add a flag `useTimeUnitAsMostSignificantUnit: true|false`

**Comment by kanitw** [comment]
I feel like this should be done at the Vega-Lite-UI level since we can have schema info there -- while we're trying to eliminate stats from Vega-lIte.

**Comment by domoritz** [comment]
Right now we cannot even specify this in vega-lite, though.

**Comment by kanitw** [comment]
I think the description for this issue is totally confusing.   You need to elaborate what you mean `useTimeUnitAsMostSignificantUnit` -- how does that affect the vega output?

**Comment by domoritz** [comment]
Look at the example. If `timeUnit` is `month` and `useTimeUnitAsMostSignificantUnit` is `false`, the the time unit is `MM`. If `useTimeUnitAsMostSignificantUnit` is `true`, then the unit is `YYYY-MM`.

**Comment by domoritz** [comment]
I agree that the name `useTimeUnitAsMostSignificantUnit` is horrible but for now the question is what the right concept is.

**Comment by kanitw** [comment]
I think it's either 

"year-month"

or

`{ 
  year: true,
  month: true
}`

or even use the time format e.g., `d3.time.format()`

What I know for sure is that nobody on earth will understand `useTimeUnitAsMostSignificantUnit` ....

**Comment by kanitw** [comment]
In any case, this is redundant of https://github.com/vega/vega-lite/issues/145

**Comment by domoritz** [comment]
Closing in favor of #145.
