### ISSUE TITLE
Adding Text to Faceted Arc Chart Resulted In Wrong Text Location

### ISSUE THREAD

**Issue by ReichYang** [vega/vega-lite#7767]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues.
- [x] Describe how to reproduce the bug.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) spec in JSON, wrapped by triple backticks like this:

```json
{
    $schema: "https://vega.github.io/schema/vega-lite/v5.json",
    autosize: { contains: "padding", resize: true, type: "fit" },
    description: "A docut chart for comparison",
    data: { values: [
    {
        "Type": "Homelessness",
        "Label": "Los Angeles, CA - 2020",
        "Ethnicity": "Hispanic",
        "value": "0.3251150399612497"
    },
    {
        "Type": "Population",
        "Label": "Los Angeles, CA - 2020",
        "Ethnicity": "Hispanic",
        "value": "0.4693792646714444"
    },
    {
        "Type": "Homelessness",
        "Label": "Los Angeles, CA - 2020",
        "Ethnicity": "Non Hispanic",
        "value": "0.6748849600387503"
    },
    {
        "Type": "Population",
        "Label": "Los Angeles, CA - 2020",
        "Ethnicity": "Non Hispanic",
        "value": "0.5306207353285556"
    }
] },
    spacing: 20,
    facet: {
      column: {
        field: "Type",
      },
    },
    spec: {
      layer: [
        {
          mark: { type: "arc", innerRadius: 50 },
          encoding: {
            theta: { field: "value", type: "quantitative", stack: true },
            color: { field: "Ethnicity", type: "nominal", legend: null },
            tooltip: [
              { field: "Ethnicity", type: "nominal" },
              { field: "value", type: "quantitative", format: ".2%" },
            ],
          },
        },
        {
          mark: {
            type: "text",
          },
          encoding: {
            text: { field: "value", type: "quantitative", format: ".2%" },
            theta: { field: "value", type: "quantitative", stack: true },
           
            
          },
        },
      ],
    },
    config: {
      view: { stroke: null },
      axis: { grid: true },
    },
  };
```

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

I'm working on creating a facted donut chart. I want to add text labels to the charts but the texts were displayed at the center of each faceted chart.

![image](https://user-images.githubusercontent.com/22743682/138154887-288dd23f-5cf1-4855-a3f3-52d0bdcfb41a.png)

**Comment by kanitw** [comment]
Since text is independent layer from the pie, you have to add radius to the text:

Basically if you change`"mark": {"type": "text"}` to `"mark": {"type": "text", "radius": 75}`, then you should get an expected result: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/111269/139597338-09d120d9-b5d8-4131-b6ab-f9c3456998fa.png">

I understand that we should have more intuitive label features, but that's coming along in https://github.com/vega/vega-lite/pull/7378.
