### ISSUE TITLE
Make sure we fully support field names with spaces

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#778]
Right now date fields with names with spaces do not work because we generate code like `data.Foo Bar != null`. Still have to confirm that vega fully supports spaces in names.

**Comment by domoritz** [comment]
Duplicate of https://github.com/vega/vega-lite/issues/358

**Comment by domoritz** [comment]
https://mothereff.in/js-variables

**Comment by domoritz** [comment]
We should just generate array access notation `data['Foo Bar']` to get around any issues. We could of course test whether the name is a valid identifier. As a compromise, we can leave names with only ascii character and a few simple modifiers such as `_` as they are.

**Comment by domoritz** [comment]
Even more relevant https://mothereff.in/js-properties

**Comment by domoritz** [comment]
Ahh, this is really hard. There are so many corner cases.

**Comment by domoritz** [comment]
Some code in https://github.com/vega/vega-lite/pull/779

**Comment by jakevdp** [comment]
It looks like dashes in column names also cause issues (reported in https://github.com/ellisonbg/altair/issues/169)

```
{
  "mark": "bar",
  "data": {
    "values": [
      {"X": "0-12", "Y-10": 17.81},
      {"X": "12-36", "Y-10": 22.35},
      {"X": "36-60", "Y-10": 25.13},
      {"X": ">60", "Y-10": 16.76}
    ]
  },
  "encoding": {
    "y": {"type": "quantitative", "field": "Y-10"},
    "x": {"type": "nominal", "field": "X"}
  }
}
```

**Comment by willium** [comment]
PR that should fix this https://github.com/vega/vega-lite/pull/1492
