### ISSUE TITLE
Viz in Tooltip

### ISSUE THREAD

**Issue by benjcabalona1029** [vega/vega-lite#7783]
Is it possible to have another chart rendered as a tooltip? Something similar to what Tableau has implemented.

https://help.tableau.com/current/pro/desktop/en-us/viz_in_tooltip.html

![tableau](https://user-images.githubusercontent.com/55730940/140444218-3aca2002-9e40-49f1-ae7b-c638561e0d00.PNG)

**Comment by domoritz** [comment]
You'd need to implement your own tooltip handler for that. See https://vega.github.io/vega/docs/api/view/#view_tooltip.
