### ISSUE TITLE
Displacement of views when labels are shown on the edges of the canvas

### ISSUE THREAD

**Issue by enertisbd** [vega/vega-lite#7797]
When using multiple views and dynamic labeling/annotation, when the labels to be displayed are on the edges of one of the views, it causes the next view to be displaced by the amount necessary to accommodate the label.
It may not be a bug per se, but the result is not as professional as one would expect to use in a final product.

If it is not a bug, is there a way to avoid this behavior??

Thanks!

![horizontal_displacement](https://user-images.githubusercontent.com/45589082/141463989-aede840c-1f06-49a7-b884-21fe000cb87b.gif)
![vertical_displacement](https://user-images.githubusercontent.com/45589082/141463994-d4160c56-7885-4c00-a1ba-a5f58c8641a6.gif)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",  
  "data": {
    "values": [
      {"dt": "1996-01-01", "test1": 2.49},
      {"dt": "1996-02-01", "test1": 3.49},
      {"dt": "1996-03-01", "test1": 2.27},
      {"dt": "1996-04-01", "test1": 1.41},
      {"dt": "1996-05-01", "test1": 0.38},
      {"dt": "1996-06-01", "test1": 0.63}
    ]
  },
  "vconcat": [
    {
      "width": 800,
      "mark": {"type": "line"},
      "encoding": {
        "x": {"field": "dt", "timeUnit": "month", "type": "temporal"},
        "y": {"field": "test1", "type": "quantitative"}
      }
    },
    {
      "hconcat": [
        {
          "width": 370,          
          "encoding": {
            "x": {"field": "dt", "timeUnit": "month", "type": "temporal"}
          },
          "layer": [
            {
              "encoding": {"y": {"field": "test1", "type": "quantitative"}},
              "layer": [
                {"mark": {"type": "line"}},
                {
                  "params": [
                    {
                      "name": "label",
                      "select": {"encodings": ["x"], "type": "point", "nearest": true, "on": "mouseover"}
                    }
                  ],
                  "mark": "point",
                  "encoding": {
                    "opacity": {
                      "condition": {"param": "label", "empty": false, "value": 1},
                      "value": 0
                    }
                  }
                }
              ]
            },
            {
              "transform": [{"filter": {"param": "label"}}],
              "mark": {"type": "text","dx": 20,"dy": -10},
              "encoding": {
                "text": {"field": "test1"},                                          
                "y": {"type": "quantitative", "field": "test1"},
                "opacity": {
                  "condition": {"param": "label","empty": false, "value": 1},
                  "value": 0
                }
              }
            }
          ]
        },
        {
          "width": 370,              
          "mark": {"type": "line"},
          "encoding": {
            "x": {"field": "dt", "timeUnit": "month", "type": "temporal"},
            "y": {"field": "test1", "type": "quantitative"}
          }
        }
      ]
    }
  ]
}
```

Vega-Lite Editor version

https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoZZjQgAjAE4rANn4AGC44uKQmfZleoATJQAsVgC+CiZm6NZ2jj4ubh4QXmgAzAHBoSrhljb2DkmxSvGJvpQ+AOwhYeaROf757p7eFgEWFRlV2Y5idYXeDpRJABytpu1RDjmuBQ1ofbZJQQC6ISDEUHJQakagAO40pjBoAw4OSsgATgDWaKCYAJ44cObCso-LcLJryjSyZNcgAB5-ABmNDggmU5hGBRoCDgAFVZHRzAg5PQ4vdHugPAgcGwzjoQMtbsDQeDzD10Q9zABHBhIWSYOhqGikQlBVowNYfTaoYwgXb7ZKlE4gd6fb6-TQAklgiHoKHuGHwxGZFEMg4FDHkxC4-GCNlKQRIW5wM5bUUfNhfH5-YlSkGy7UJSbuLXoWn0xnqRms9mG42m83nK5Su5U9DPV6tHBIfEIAy80CyJCwp5IJhgtwQMFwKDhUBiq0ShOGaULTXhkC475mJQvWOeNCYM56JRyZFsBjZtikM3s8sgYPmasMtyF62S0BsGNQOh20Bcr6M9tSmNxtMZ-VKHV3NBAnTZpTaXSYlpHnR6GbsxatZv0iBAvEIc0gwQeM2r2MpjeZ-unWMhjcbr1P8tYqICvgisodr8BYDhvJaE5-B4oEymSWLTESyHAR6DJMj6jxKA66H1M6hJtjOc5-IudDsPIn7rhG6aZtuOK7qg+6CIeKwXqeyzHpeqDwf2rQCmiqBJMK-6XNhlaRuRFrijaUoQaAxFym00KwgiSLoGqaIVpi9Q4niBJYfapIaRShk0nSeHeiyUY3ksQA

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue?

One thing you might try is setting the opacity of hidden points to 0.0001 instead of 0 so that they take up space. Another is to make sure that you have padding.

**Comment by enertisbd** [comment]
Thank you for looking into.
I have updated the example for a minial version of it.

I tried to add the padding, but I could not find a way to add it only to the view causing the "problem".

**Comment by domoritz** [comment]
Can you reproduce the issue in a single view spec?

**Comment by enertisbd** [comment]
Hi...
I didnt experince this issue in a sigle view setup.
It only happens with adjacent views.

Vega-lite example of single view:
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoZZjQgAjAE4rANn4AGC44uKQmfZleoATJQAsVgC+CiZm6NZ2jj4ubh4QXmgAzAHBoSrhljb2DkmxSvGJvpQ+AOwhYeaROf757p7eFgEWFRlV2Y5idYXeDpRJABytpu1RDjmuBQ1ofbZJQQC6ISAA7jSmMMmlDkpwslBsyjSyZGigAB5nIABmNHCCyuYjBTQIcACqsnTmCHL0cQBPHBwcweBA4NgAJx0IGWAKut3uj3QPUBwPMAEcGEhZJg6GoaKRYctBEgAXBIUZQMhIQBrK6YIEg9DCWQgoKtHBIaEIAyoYwgWRIN7mUlMe5uCD3OBQcKgPYHI4nPmGECXBYFJnmCHHMxKNnczxoTCQvRKOQ-NgMKVsUiUjkakA0+noHW4twKw7HU6aEBsLlQOjw30HWRHPEW31cnmipDiwQe8GMtDXHRSpTaXTMloZnR6GYc1omnEQa5QhBUm40QQeSlR7nC2Px4mO50MrUouDnPUqS6+HYqYP8CwOZaepU+0AebsIu4PUHTOHt9HoLE4vHqPFEpSI+edhKuZb+pCB5MhuTh9jyesxllxiW7JPB1OCdMgTP51A59955mjh1BEAA

**Comment by domoritz** [comment]
Good to know. Here is a repro with just one more view: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoZZjQgAjAE4rANn4AGC44uKQmfZleoATJQAsVgC+CiZm6NZ2jj4ubh4QXmgAzAHBoSrhljb2DkmxSvGJvpQ+AOwhYeaROf757p7eFgEWFRlV2Y5idYXeDpRJABytpu1RDjmuBQ1ofbZJQQC6ISDEUHJQakagyABOANbmOGw0smatAO40pjDJpQ5KcLJryidkaKAAHu8gAGY0cIJlOYRgUaAg4ABVWR0cwIOT0OIATxwcHMHgQRx2OhAy0R3z+AKB6B6SJR5gAjgwkKc6GoaKQcctBEhEXAdlsQLsDpp3MjUehhLJUUFWjgkFiEAZUMYQLIkODzMymAC3BAAXAoOFQI9nq8pYYQF8FgU+Ydjqc3ELxZ40JgdnolHJYWwGGq2KR2SLjZzxdyQEcTmYHk82C9ZG8eWwxVA6HieWtZC9MOx5DyxRLFUhlYI3IgcJg4z8dGqlNpdPyWqWdHoZiLWnbqRAfmwdggOX9BB52WnxfLM9nGd6ud8C2TiXAPkGVF9fPcVHH+BYHMsdaHXiOJ1rfv9AWjpriR6b0JTqcn1MmGUoCbvxwlXMso0gYwXvgmkynvum+wKsyqHhiX1QItBBLFZqwrZYyxrVBly9RYgiAA)

**Comment by domoritz** [comment]
To resolve this effect, you can set `"bounds": "flush"`. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoZZjQgAjAE4rANn4AGC44uKQmfZleoATJQAsVgC+CiZm6NZ2jj4ubh4QXmgAzAHBoSrhljb2DkmxSvGJvpQ+AOwhYeaROf757p7eFgEWFRlV2Y5idYXeDpRJABytpu1RDjmuBQ1ofbZJQQC6ISBMbAyyygboAGa6EDBuxFByUGpGoMgATgDW5jhsNLJmrQDuNKYHqEmlDkpwssdlI8yGhQAAPUEgbY0OCCZTmEYFGgIOAAVVkdHMCDk9DiAE8cHBzB4EPdLjoQMs8ZDobD4egevjCeYAI4MJBPOhqGikSnLQRIPFwS7nEBXW6adwEonoYSyIlBVo4JDkhBbYwgWRIFHmAVMWFuCCwuBQcKgf6A4HqkAQhYFaV3B5PNzylWeNCYS56JRyLFrI1sUgixV2sUqiUge6PMx-AFsIGyEGStjKqB0amS44bOjseSS5Wq3VIfWCNyIHCYDPbHRGpTaXQylp1nR6GaK1qejkQbZsS4IUXQwQeEX5lXaoslvmh8WQyvMhlwMExlQQ3y-FQZ-gWBzLC3x4GzxdmqEwuHE6ZU2cO9BsjmYLn33lKWlnhcJVzLFNINOVyFZoH3r6o6FrKxYGn8pK-qg1aCLWID1q2qBNvBLYyjuIaLEEQA). Since the padding is not determined automatically anymore, you need to set it.

**Comment by enertisbd** [comment]
Nice!
I tried in the multiview plot, and it works.
With this modification I just need to set the spacing between the views.

Thank you!
