### ISSUE TITLE
Check that vega-lite.js is included in npm

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#782]
Right now with `npm install vega-lite`, you don't get vega-lite.js. We have to make sure that we include it.

**Comment by kanitw** [comment]
`0.9.0` surely have vega-lite.js in it.   We should update build script to check if vega-lite.js exists before publishing.

**Comment by kanitw** [comment]
>  We should update build script to check if vega-lite.js exists before publishing.
Done is #852
