### ISSUE TITLE
unexpected result with barley stacked bar example

### ISSUE THREAD

**Issue by timelyportfolio** [vega/vega-lite#783]
After upgrading to the newest build of Vega and Vega-lite locally, the stacked bar barley example yields this result

![image](https://cloud.githubusercontent.com/assets/837910/11351379/efff3872-91fb-11e5-9720-d0273eed3216.png)

which is much different than the expected 

![image](https://cloud.githubusercontent.com/assets/837910/11351440/5386df08-91fc-11e5-8a42-ee9ee7577357.png)

I put the source up on bl.ocks/gist http://bl.ocks.org/timelyportfolio/b61d9bfe3351afc24dcf.  I understand that using the newest builds is risky, but I thought I would report in case you have not seen this yet.

If `color` and `y` are the same, the result seems correct.

Thanks so much for all your efforts on the `vega` suite.

**Comment by timelyportfolio** [comment]
wonder if #784 related

**Comment by kanitw** [comment]
Thanks for reporting and your hunch is right.  It is only incorrect when you use short form of types (such as "N" rather than "nominal").  

I have a  PR that should fix this: https://github.com/vega/vega-lite/pull/786 – so I'm closing this.  
If that doesn't fix the problem, please re-open this issue. :)

**Comment by timelyportfolio** [comment]
@kanitw thanks so much; that fixed it.  Great work!

**Comment by timelyportfolio** [comment]
@kanitw would something like this explain troubles with http://vega.github.io/vega-editor/?mode=vega-lite&spec=trellis_stacked_bar&renderer=svg? `col` has no impact in my local example. I can't check it since `npm run build` does not work for me with recent changes.

**Comment by timelyportfolio** [comment]
never mind, I see that it is `column` instead of `col`.

**Comment by kanitw** [comment]
@timelyportfolio  Yeah - we are changing it for the `0.9` release
