### ISSUE TITLE
Temporal axis doesn't show date depending on width

### ISSUE THREAD

**Issue by simonfuhrmann** [vega/vega-lite#7833]
The temporal axis description changes depending on the width of the chart, which is all good, except that sometimes it doesn't display the date. Here are two examples with the exact same spec but two different width, `500` and `600`:

Width of 500:
![Screen Shot 2021-12-02 at 4 31 56 PM](https://user-images.githubusercontent.com/1150723/144524594-2ce0ba1c-9e39-45b0-a13e-814cffcb9f24.png)

Width of 600:
![Screen Shot 2021-12-02 at 4 32 07 PM](https://user-images.githubusercontent.com/1150723/144524625-644a4a1f-9606-4491-9df1-0d1226aa6def.png)

The latter chart is pretty much useless (well at least in my case) without the date as context.

Is this a bug, is there any work around for this?

Spec for reference:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 500,
  "encoding": {
    "x": {"field": "ts", "type": "temporal"},
    "y": {"field": "raw", "type": "quantitative"}
  },
  "data": {
    "values": [
      {"ts": "2021-11-26T22:19:06.604Z", "raw": 0.141},
      {"ts": "2021-11-27T13:11:38.081Z", "raw": 0.126},
      {"ts": "2021-11-28T13:21:31.652Z", "raw": 0.154},
      {"ts": "2021-11-29T13:06:08.802Z", "raw": 0.167}
    ]
  },
  "mark": {
    "type": "line",
    "point": {"filled": false, "fill": "white"}
  }
}
```

**Comment by domoritz** [comment]
You can reduce the number of ticks so label overlap doesn't kick in. Alternatively, you can set a custom format. 

There isn't much Vega-Lite can do since we don't have access to the data.

Coming up with good labels for temporal data is pretty tricky. Any improvements would need to be done in Vega.
