### ISSUE TITLE
Legend shows incorrect colors when conditions are applied

### ISSUE THREAD

**Issue by bc206nt** [vega/vega-lite#7834]
```json
{
      "color": {
        "title": "Outcome",
        "field": "_source.outcome.result",
        "condition": [
          {"test": "datum['_source.outcome.result'] == 'FAILURE'", "value": "red"},
          {"test": "datum['_source.outcome.result'] == 'SUCCESS'", "value": "green"},
        ]
    }
}
```

I applied conditions as shown above to a basic Gantt chart to specify colors for successes and failures. The colors seem to work on the chart but the legend still shows the default color scheme. As of 11/24/21 the legend was working correctly when only one condition was applied, but it doesn't appear to be working for just one condition anymore either.

Screenshot of the bug: 
<img width="869" alt="Screen Shot 2021-12-05 at 6 40 48 PM" src="https://user-images.githubusercontent.com/95599233/144779499-4c216a55-7677-4460-a7db-6030b42a426e.png">

Screenshot of just one condition (failures are set to red):
<img width="870" alt="Screen Shot 2021-12-05 at 7 01 54 PM" src="https://user-images.githubusercontent.com/95599233/144780305-627f3903-ab75-401c-9ad9-9651f283113e.png">

**Comment by domoritz** [comment]
Instead of condition, please use an ordinal color scale. Then the legend will work.
