### ISSUE TITLE
Add support for half pie

### ISSUE THREAD

**Issue by luiscastro193** [vega/vega-lite#7847]
Some official support for half pie charts would be greatly appreciated. As of now, it is technically possible to make them work ([see this example in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemhBQ5mJDVlwATooxwaZLGgAMla9YCMS5EYDWaUJgCeOOFqRGUKb0cHoA8gBmERChHiBwAB44Juj8AAoAkgQATCAAvkpGSGo0DBBxiclaqhowOfkFIGpIenHESIIMcOWoANqePn7oANSm7Z1DACzWBQO+WvxjHV1oAGwzALqNcLI6JbJkcSGtqKARNHCCalrjK0re8+gAjgxIsph0LTSkptAdQ6A1GxkAY0L1rApsvYto0dII2CkzhcrloHn57oMtLJgQYOg0lDpZOdDqcQIJyDtrqSShAkExyWhMEYunlWUA)) but it feels extremely hacky and prone to bugs.

Edit: [Here it is another alternative](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemhBQ5mJDVlwATooxwaZLGgAMla9YCMS5EYDWaUJgCeOOFqRGUKZGSGo0DBAeIHAAHjgm6KoaMAQATCAAvhlKakh6UcRIggxwkagA2p4+fugA1KaFxTUALNbZVb5a-A1FJWgAbG0AutnRsjphsmRR9HD5qKAAZjRwgmpajX1K3p3oAI4MSLKYdHk0pKbQRTWgIVNwALIGUbHxXQAKAJJpmUp3ZI8kDEXnEEiAvj8sqMdII2Aklis1lodn5ttUtLI2AgDEVMtC5MtpgsQIJyHBZOtiWEIEgmKS0JgjCUoUA) but fixing the height is still problematic.

**Comment by luiscastro193** [comment]
> What if you set the theta range to 0-180?

It doesn't seem to work for me ([Vega Editor example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgkKqCAC+SgCZJMKVKGJJBDOBDQBtLbv3oA1IpAOTt4ALAAM5p56Bvz+gc5oAGzhALrmIHCyUGwWNLJkmiD0cDYFAGY0cIIWBnH6SjpR6ACODEiymHTWNKT+0I7eoCptZN5uoQoAjAAcoalpWYJsKmUVVQYNdYVeBrJsCLmOZvNy5fl2IILkGdXnORBITJdomCrOpu9AA)) but maybe I'm doing something wrong?

**Comment by luiscastro193** [comment]
> > What if you set the theta range to 0-180?
> 
> It doesn't seem to work for me ([Vega Editor example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgkKqCAC+SgCZJMKVKGJJBDOBDQBtLbv3oA1IpAOTt4ALAAM5p56Bvz+gc5oAGzhALrmIHCyUGwWNLJkmiD0cDYFAGY0cIIWBnH6SjpR6ACODEiymHTWNKT+0I7eoCptZN5uoQoAjAAcoalpWYJsKmUVVQYNdYVeBrJsCLmOZvNy5fl2IILkGdXnORBITJdomCrOpu9AA)) but maybe I'm doing something wrong?

Never mind, setting it to [0, PI] works ([Vega Editor example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQyAE4BrNKEwBPHHDQgkKqIpD04mJAHkAZjYgXNIOAA8cKg-wAKASQIAmEABfIKUAEyRLJ2IkQQY4CDQAbS1dfXQAalMYuPSAFgAGUNS9T2zY+LQANiKAXVDnWSg2MJpZMidzKNRQGxo4QTCDHMqlHVL0AEcGJFlMOkiaUlNoWPTQFVmyOABZJBcnV3cDX2CQpWbBNg8ekD6BofRx-TG0g1k2BDbYs4u5Po6t0E5DgskeoFaECQTGBaEwKniISCQA)) but the result is exactly the same so the height is still a problem.

**Comment by domoritz** [comment]
I see. Yeah, I think those fixes are needed right now. I don't see how we could change the grammar to not require them. I'd be happy to discuss any options. Since I don't see a way forward right now, I'll close this issue as not to be fixed.
