### ISSUE TITLE
duplicate parameter definition error in layered charts (because of `"point": true`)

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#7854]
Original observed in this Altair issue comment: https://github.com/altair-viz/altair/pull/2528#issuecomment-992989438.
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgDghgThC2DOIBcBtUA7OBTZIAWAlgOZ4A2xeALiADQjxalYDG1SolAnmDkuAPYF01OsybRcsfgFcGMkSH7pJMuQDcsUEAF9tAXTprmS5hDZp8WCmwCMABjt1Y0ANbIO3XiHLocdMILCyABmEKQM2nRY6MYAJkJE7iAAHknBBIyxuLFmfiCUBLBYAKroBGwgnFgSdFw8uOj8sEJhOnScSRBERFBYRLmS1cp06Zm4YFAEzHl1XgCO0hDC5WYEGjq6NKDOUG7s+Z64vaxtINFxCWkEpKSd3b39lF5FS7Qgo6RZfBNTM4d8CyWBUoq3WkXolCg-BcvFAxnQ8QKSiSajC0i8ACNSBBmG5-NA4LhCCRyCQFFhYGAuCEwhFDGjeOhpDdwal9h8viAck83gUiqVyrgqjUDvU+E9KfwYLddPo6NyIElpFBbnwFQB6eCUfi4+AAOmY8DUpwAJPBmHgKYq+FRKGB4Eh1eqNP09URynhpBi9QR+JqLVbnX0IABachPZ0AVj1ACY9XY9QAreDI7RAA)

```json
{
  "params": [
    {
      "name": "highlight",
      "select": {"type": "point", "clear": "mouseout", "on": "mouseover"}
    }
  ],
  "vconcat": [
    {
      "height":100,
      "mark": {"type": "line", "point": true},
      "encoding": {
        "x": {"field": "date", "timeUnit": "year", "type": "nominal"},
        "y": {"aggregate": "mean", "field": "price", "type": "quantitative"}
      }
    },
    {
      "mark": {"type": "rect"},
      "encoding": {
        "fill": {"aggregate": "mean", "field": "price", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "highlight", "empty": false},
          "value": null
        },
        "x": {"field": "date", "timeUnit": "year", "type": "temporal"}
      }
    }
  ],
  "data": {"url": "data/stocks.csv"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
gives
![image](https://user-images.githubusercontent.com/5186265/145986877-e757d10e-b9a7-4b70-8555-55f954e12293.png)
When setting -upon first sight unrelated- `"point": true` to `"point": false` it will work:
![image](https://user-images.githubusercontent.com/5186265/145984881-50f2adb5-883b-4f60-b310-0e4cc23efdf4.png)

Defining the `parameter` on the view, it will also work with `"point": true`.
```json
{
  "vconcat": [
    {
      "height": 100,
      "mark": {"type": "line", "point": true},
      "encoding": {
        "x": {"field": "date", "timeUnit": "year", "type": "nominal"},
        "y": {"aggregate": "mean", "field": "price", "type": "quantitative"}
      },
      "params": [
        {
          "name": "highlight",
          "select": {"type": "point", "clear": "mouseout", "on": "mouseover"}
        }
      ]
    },
    {
      "mark": {"type": "rect"},
      "encoding": {
        "fill": {"aggregate": "mean", "field": "price", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "highlight", "empty": false},
          "value": null
        },
        "x": {"field": "date", "timeUnit": "year", "type": "temporal"}
      }
    }
  ],
  "data": {"url": "data/stocks.csv"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
![image](https://user-images.githubusercontent.com/5186265/145985187-583f9529-90ae-417b-8cc1-2fa265ad3349.png)

**Comment by mattijn** [comment]
Raised here: https://github.com/altair-viz/altair/pull/2671#issuecomment-1244085790.
Another example of this behaviour, [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEABMkmFKlAMAToLRadSAlCSGICpaoC+GnNaQIIaANqhlbuKYAFAEEAJSCAWQB9GXUQCDhBOChMNFBMAE8cf3QcNhplFI0oROtTBDYGeIrCkDhlKDZNfLIPVE8QAA9Y9JAAXQ1lOGs4CBTUTEMGOA0VMoqq0kMQJxBiGjgAd1b2gDUASQBRAHVovod+kEEkdLgltp8-U33j041kQwBrUygaQ2L-DR1BpNZRkVIgBqCNh3UANZRNTDsVT6EAAM3Wgk0pgA8oYaLRVBoMllTMo2Ah8kgTM5XAhAqEIq9aggcBk0KiqfEVsQqVNTMIyFgyIZrssNBAaAAvbKwlQIpHgnmCPmoSRiGQ0kV09DBMJRGKAlls1AcwRcjRKlWSGQrLoo9EJLHocI0RIQSJZQyRADiVKhhJAxOyIAAjgwkAU6DoaKQxSAevaMU6QAAJaHxXIbW6xIOmMMRxG6RGxhyltQPBDB54nACMsXeX3QmDgHRqQMazXBkOhXbldAVKMtwaYVygX01bnpeqZiFZCdN5tWvODEwjEBchjqKRWzdb4IdmJxeIJOcywbJFN8Jlt+6Tphdbo9tx9ftmRLPefDkaLMf8KwToAHsmaY2HAmbZu+JLoPm37RiWpa9A4QA)

The following works and the `PARAM_0` is applied to both `VIEW_0` and `VIEW_1` even though only `"views": ["VIEW_0"]` is defined within `PARAM_0 `:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {"url": "data/cars.json"},
  "params": [
    {
      "name": "PARAM_0",
      "select": {
        "type": "point",
        "clear": "mouseout",
        "encodings": ["x", "y"],
        "nearest": true,
        "on": "mouseover"
      },
      "views": ["VIEW_0"]
    }
  ],
  "layer": [
    {
      "name": "VIEW_0",
      "mark": "circle",
      "encoding": {
        "color": {
          "condition": {
            "field": "Origin",
            "type": "nominal",
            "param": "PARAM_0",
            "empty": false
          },
          "value": "lightgray"
        },
        "size": {
          "condition": {"value": 250, "param": "PARAM_0", "empty": false},
          "value": 20
        },
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "y": {"field": "Horsepower", "type": "quantitative"}
      }
    },
    {
      "name": "VIEW_1",
      "mark": "text",
      "encoding": {
        "color": {
          "condition": {"value": "black", "param": "PARAM_0", "empty": false},
          "value": "transparent"
        },
        "text": {"field": "Origin", "type": "nominal"},
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "y": {"field": "Horsepower", "type": "quantitative"}
      }
    }
  ]
}
```

But when changing the parameter to include both views (`"views": ["VIEW_0", "VIEW_1"]`), since both views contain references to the param `PARAM_0` it gives the following error:

> ```cmd
> Duplicate signal name: "PARAM_0_tuple"
> ```
I found this hard to understand. Not really know how this can be easily improved as it is not possible to provide name definition on the layer.

**Comment by mattijn** [comment]
This spec is another example: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94HFmzgBmLvzo8G8EUJCEALOKl8VjOAqYBdFiABmEGhijxQegJYYU6vmSgBPAA4Z4IAHYB7ALbm3qELqOEABOEF44cPjuYS5wIFhWGDRQGIxkCShJJgggDs6ujh6+JmQWVmARuAI6XL42mQDmGG5pIIiWAO6VbZ0A+kQgOlrpzpKgfl6xPRgd-SBkXiEA1qa5TlMovi5khcXwUMGYus00HmC+DaunKB7Bq2XWrq15U54+figBZAAe95aPcVgdnWrgAjmgIG4oOYYNDEC5dPY-uVXJRgfk4uDIdDYeZ4V8QB4gjQYUicqcWjDzB43KtkOhYtQgqEvK4MllUgT6Zh4AAGAB07AArExRWQACRYGgACwwi1c0qgUEcWDgAHo1fCGhB+Q0YdK0OR+dS1VLZYtNRhtQBaTYpTVCwX8gUAKywNICQA):
```json
{
  "data": {
    "values": [
      {"a": 1, "b": 1, "c": 1, "d": 1},
      {"a": 2, "b": 2, "c": 1, "d": 2},
      {"a": 3, "b": 1, "c": 2, "d": 3},
      {"a": 4, "b": 2, "c": 2, "d": 4}
    ]
  },
  "facet": {"field": "c", "type": "nominal"},
  "params": [
    {
      "name": "selected",
      "select": {"type": "point", "fields": ["d"]},
      "bind": "legend",
      "views": ["view_1"]
    }
  ],
  "spec": {
    "name": "view_1",
    "mark": {"type": "line", "point": true},
    "encoding": {
      "color": {"field": "d", "type": "nominal"},
      "x": {"field": "a", "type": "quantitative"},
      "y": {"field": "b", "type": "quantitative"},
      "opacity": {"condition": {"value": 1, "param": "selected"}, "value": 0.25}
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
When changing `"point": true` to `"point": false` the error disappear (but the chart won't appear as requested).
Manually defining both the `circle` and line` mark will work though.
```json
{
  "data": {
    "values": [
      {"a": 1, "b": 1, "c": 1, "d": 1},
      {"a": 2, "b": 2, "c": 1, "d": 2},
      {"a": 3, "b": 1, "c": 2, "d": 3},
      {"a": 4, "b": 2, "c": 2, "d": 4}
    ]
  },
  "facet": {"field": "c", "type": "nominal"},
  "spec": {
    "layer": [
      {
        "mark": "line",
        "encoding": {
          "color": {"field": "d", "type": "nominal"},
          "opacity": {
            "condition": {"value": 1, "param": "selected"},
            "value": 0.25
          },
          "x": {"field": "a", "type": "quantitative"},
          "y": {"field": "b", "type": "quantitative"}
        },
        "name": "view_1"
      },
      {
        "mark": "circle",
        "encoding": {
          "color": {"field": "d", "type": "nominal"},
          "opacity": {
            "condition": {"value": 1, "param": "selected"},
            "value": 0.25
          },
          "x": {"field": "a", "type": "quantitative"},
          "y": {"field": "b", "type": "quantitative"}
        }
      }
    ]
  },
  "params": [
    {
      "name": "selected",
      "select": {"type": "point", "fields": ["d"]},
      "bind": "legend",
      "views": ["view_1"]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}```
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94HFmzgBmLvzo8G8EUJCEALOKl8VjOAqYBdFiABmEGhijxQegJYYU6vmSgBPAA4Z4IAHYB7ALbm3qELpYzpKgKBD2GABOeKBeEJEA1q4ovi5kGG40HmC+AOamtB4oHtEI+pbWrox2Ti5w7t6+-roejobmDgVZbjlQ5h5uBcjoddRtkRBerlhWGDRQGIy6w5jwAAwAdOwArLoAHgUWVjawNc6uAI5oEG59MH2ILrr2hxU2lGd1IFc3d9DmjwCuj8Xi+iEsAHcAPpEAKsEBxRKuGjmSI0FBpEAZLI5Nz5MpZYqlMxvKogT6uTw+PwoOEgVrtToEga9fqDMorUZkcaTaazeaLOmc9ZbXZkA5lI6VeqnEAOc71H63Dr-QHPV7HVwfOW1S7XZX3AFPJjaXQ8rw4OD4dyTL4zDEC6oge1zExleVfRweXwmMhSsCW3ACHRcXw2DG5DJO8EYCGBkAx6GwnRaMgAEiwNAAFhg4q4s1AoI4sHAAPSlx65CAbXIdLNocgbfqlzM5uIVjBVgC0KQWFe2Ww2mwAVlgBgEgA)

I assume the `point=True` will duplicate the spec under the hood into a layered chart, but it also duplicates the `"name": "view_1"` for both layers and that causes this error, since I define `"name": "view_1"` on only a single view in the manual layered chart.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, I was looking at a variant of your example https://github.com/vega/vega-lite/issues/7854#issuecomment-1315551841 above.  Here is the version I was looking at: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94zViEIBmLvzo8GHFmzgAWcVL7LGPJgF0WIAGYQaGKPFA6AlhhRq+ZKAE8ADhnggAdgHsAtqZeoQ2+xAAThAeOHD4riFOcCBYFhg0UBiMZHEoCUYIIHaOzvZu3kZkZhZgYbgCWlzeVukA5hguKSCI5gDu5S3tAPpEIFoaqY6SoD4e0V0Ybb0gZB5BANbG2Q4TKN5OZPmF8HoocdqNNG5g3nXLxyhugcslls7NORPuXj4ofmQAHrfm9zGwNlWzgAjmgIC4oKYYJDEE5tLYfqVnJRAbkYqDwZDoaZYR8QG4AjQoQisscmlDTG4XMtkOhotQAsEPM40hlknjaZh4AAGAB07AArExhWQACRYGgACww82ckqgUHsWDgAHoVbC6hBeXUoZK0OReZSVRLpfN1RhNQBadZJdUC-m8vkAKywVL8QA). My version is one step simpler than yours because mine has `"point": false`.  (I also slightly changed the data so that there are lines present.)

If you open my version in the Vega editor and click on "Extended Vega-Lite Spec" at the bottom and then "Edit Extended Vega-Lite Spec", you'll see that the parameter has been moved from the top level to inside the `spec` object.  Also warnings appear in the logs because of the presence of the `"views"` property in this non-top-level parameter.

I can't quite follow the code, but based on [this comment](https://github.com/vega/vega-lite/blob/2ddf38305215038b46ad4be22ac0372be130a5f8/src/normalize/index.ts#L48), my guess is that it might be related to the `normalizeGenericSpec` function.

Does that give you any ideas?

**Comment by mattijn** [comment]
That might be another issue. 
I think the problem here is that the `"point": true` will duplicate the spec under the hood somewhere into a layered version of a `line` mark encoding and a `circle` mark encoding, where the latter is a duplicate of the mark `line` with only the the mark `line` to `circle` replaced. But since there is also a `name` definition (`"name": "view_1"`), it also duplicates that name and that is problematic since it is not allowed to have two identical name definitions in different chart objects in a layered chart. 
If in the duplication process of creating `circle` mark chart object the `name` is popped then the issue will resolve. I think.

If I modify your example into a manual layered version of a `line` and `mark`, [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94zViEIBmLvzo8GHFmzgAWcVL7LGPJgF0WIAGYQaGKPFA6AlhhRq+ZKAE8ADhnggAdgHsAtqZeoQ2+xAAThAeOHD4riFOcCBYFhg0UBiMZHEoCUYIIHaOzvZu3kZkZhZgYbgCWlzeVukA5hguKSCI5gDu5S3tAPpEIFoaqY6SoCgQthiBeKA+HtFdGG29IGQeQQDWzijeTmSNNG5g3nXGtG4oblNZJZbOzTnz7l4+KH5kbgE0pnanB03fpjcLlOyHQ0WoAWCHmcaQyyTeLVQmHgAAYAHTsACs2gAHqcblZYDYHPMAI5oCAuKDfaCmRBObS2fHmW4xSjE3IxcmU6kwan0vxMWSRObOVqLZarDbOL6BGjpFYgfaHY6-c6XZmlO6Kh7OJ7eXzaD76b5MrJ-I7UoEgpHgsiQkIw+KJeHaUHIuDorG4zWs4Q6knOblUmn8hlkM0mFlWdnZQNcikhvl0hlCqogAAkWBoAAsMGtnDmoFB7Fg4AB6cv0uoQNF1b45tDkNGA8vZvNrKsYGsAWm2SSrmIxaPRACssNamEA), it starts with the same error as with `"point": true` (you can check and search for `selected_tuple` in the 'Compiled Vega'), but if you remove line 35 from the Vega-Lite specification (and thus removing the `name` of the second chart in the layered spec) than it works.

Can we find the location in the code where the `"point": true` is start being processed?

**Comment by ChristopherDavisUCI** [comment]
Thank you!  I haven't completely processed what you wrote @mattijn, but I do think I tracked down where the `"point": true` starts to be processed.  This is my best guess: https://github.com/vega/vega-lite/blob/2ddf38305215038b46ad4be22ac0372be130a5f8/src/normalize/pathoverlay.ts#L162-L174

**Comment by mattijn** [comment]
Nope, that is one level too deep. I think my suggestion will turn this:
```json
"name": "foo"
"mark": {"type":"point", "filled": true, "name": "bah"},
```
into:
```json
"name": "foo"
"mark": {"type":"point", "filled": true},
```
Where we like to "`omit`" `"name": "foo"`. Maybe somewhere around line 164?

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, do you know what's the best way to test these kind of code changes?  Is it opening a linked Vega Editor?  Or is there a more natural choice like running the code in VS Code and using debugging?  (All the (limited) JavaScript I've played with before has been website-focused, so I always tested it by using a web browser.)

**Comment by mattijn** [comment]
There is a contributing page in the repo. It mentions VS Code as preferable IDE: https://github.com/vega/vega-lite/blob/next/CONTRIBUTING.md#suggested-programming-environment. 

But I've no much experience in this either.

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn.  I'm just experimenting at this stage, but can you take a look at https://github.com/ChristopherDavisUCI/vega-lite/commit/1ced888950ce5580266fc1fc4f35a902238bd449 and see if you think it helps the error from https://github.com/vega/vega-lite/issues/7854#issuecomment-1315551841 ?

It does not seem to help your initial `vconcat` example.

**Comment by binste** [comment]
@ChristopherDavisUCI Nice catch, I missed the implementation of named views, this is great! For reference, produces

```python
import altair as alt
from vega_datasets import data

stocks = data.stocks.url
highlight = alt.selection_point(name="highlight", on="mouseover", clear="mouseout")

line = (
    alt.Chart(height=100)
    .mark_line(point=True)
    .encode(x=alt.X("date:N", timeUnit="year"), y=alt.Y("mean(price):Q"))
)

rect = (
    alt.Chart()
    .mark_rect()
    .encode(
        x=alt.X("date:T", timeUnit="year"),
        fill=alt.Y("mean(price):Q"),
        stroke=alt.condition(
            highlight, alt.value("black"), alt.value(None), empty=False
        ),
    )
    .add_params(highlight)
)

alt.vconcat(line, rect, data=stocks)
```

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {
    "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/stocks.csv"
  },
  "params": [
    {
      "name": "highlight",
      "select": {"clear": "mouseout", "on": "mouseover", "type": "point"},
      "views": ["view_3"]
    }
  ],
  "vconcat": [
    {
      "encoding": {
        "x": {"field": "date", "timeUnit": "year", "type": "nominal"},
        "y": {"aggregate": "mean", "field": "price", "type": "quantitative"}
      },
      "height": 100,
      "mark": {"point": true, "type": "line"}
    },
    {
      "encoding": {
        "fill": {"aggregate": "mean", "field": "price", "type": "quantitative"},
        "stroke": {
          "condition": {"empty": false, "param": "highlight", "value": "black"},
          "value": null
        },
        "x": {"field": "date", "timeUnit": "year", "type": "temporal"}
      },
      "mark": "rect",
      "name": "view_3"
    }
  ]
}
```
which is valid. Only difference is the naming of `"view_3"` and that the parameter references it. Does this mean that this issue is no longer blocking the Altair 5 release or is there still a common pattern in Altair that is affected?

**Comment by ChristopherDavisUCI** [comment]
Thanks for checking this out, @binste!  You're right that @mattijn's original chart now works in Altair, but I believe this is an example where an update is still needed:
```
import altair as alt
import pandas as pd

sel = alt.selection_point(fields=["c"])

df = pd.DataFrame({
    "a": [1,2,3,4],
    "b": [1,2,1,2],
    "c": [1,1,2,2]
})

alt.Chart(df).mark_line(point=True).encode(
    x="a",
    y="b",
    color="c:N",
).facet(
    "c:N"
).add_params(sel)
```
Like in the other examples, changing to `line=False` will remove the problem.

I think my code [here](https://github.com/ChristopherDavisUCI/vega-lite/commit/1ced888950ce5580266fc1fc4f35a902238bd449) fixes this particular issue, but I'm not sure if it's a reasonable approach or if it causes other problems.

**Comment by mattijn** [comment]
Yes there is still a common pattern affected. The second comment is still problematic. It was raised as well in https://github.com/altair-viz/altair/issues/2713.
I'm somehow surprised your code fix this issue @ChristopherDavisUCI. It is the right thing to do, but before the `name` key was not yet injected there, so it was done elsewhere. Maybe there is a check if there is a `name` defined it does not do this injection.
Does it pass the test bank of Vega-Lite? Otherwise turn it into a PR.

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn!  My understanding is that [this line](https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/pathoverlay.ts#L172) is where the name previously got injected, and so what I tried to do is to remove the "name" property from the encoding at an earlier stage, and then only include it in one spot.  Does that make sense?

**Comment by mattijn** [comment]
You remove the `name` from the encoding? In my understanding there is no `name` key within `encoding`. 

I think what you do is you import the `name` and define it on the first item in the layered specification, just like we make sure on the Altair side to have `name` only be defined on the first item in a manual layered specification. So that make sense.

But how you knew you could define `name` as const around here?
https://github.com/ChristopherDavisUCI/vega-lite/commit/1ced888950ce5580266fc1fc4f35a902238bd449#diff-9d97dcc41d7b274e7a6ad719846874fdd3ebb66ecd70b82dc1ee228e4a598425R104

Which `name` is this?

**Comment by ChristopherDavisUCI** [comment]
You're right, I meant that I remove `name` from the `spec` (not from the encoding).   This is where that happens: https://github.com/ChristopherDavisUCI/vega-lite/blob/1ced888950ce5580266fc1fc4f35a902238bd449/src/normalize/pathoverlay.ts#L104

The main point is that the `name` property doesn't get duplicated.  Does that make more sense?  (If `spec` does not have a `name` property, than my JavaScript understanding is that this `name` will just be undefined.)

Does that make more sense?

**Comment by mattijn** [comment]
Yes it does! Thanks for explaining. I notice there is also an `lineOverlay` next to `pointOverlay`. I don't think we had that combination tested yet on the Altair side. So maybe that is another potential-future-issue solved by this change.

**Comment by mattijn** [comment]
Fixed by https://github.com/vega/vega-lite/pull/8662
