### ISSUE TITLE
Incorrect tooltips for boxplots from data in .csv file

### ISSUE THREAD

**Issue by nholland20** [vega/vega-lite#7889]
How to reproduce the bug:
- When using a .csv file for data input for a vega-lite boxplot, the min and max in the tooltips had incorrect values some of the time. It appeared to be only when there was a different number of digits in the number being plotted within the boxplot. This error was resolved by changing the data to .json format.

Example:
- Example data copy and pasted from a .csv file:
type,GenesDetected
Gene A,10829
Gene A,10671
Gene A,9988
Gene A,10986
Gene A,9818
Gene A,10364
Gene B,8593
Gene B,6730
Gene B,7805
Gene B,8150
Gene B,7351
Gene B,9574

```json
{
  "mark": {"type": "boxplot", "ticks": {"color": "white"}, "color": "white"}, 
"encoding": {"color": {"legend": null, "field": "type", "scale": {"domain": ["Gene A", "Gene B"], "range": ["#CC79A7", "#00FFFF"]}}, 
        "x": {"type": "nominal", "field": "type", "title": null},
 "y": {"type": "quantitative", "field": "GenesDetected"}}
}
```

Example Screenshot:
![vl_bug_report](https://user-images.githubusercontent.com/62782791/147616033-f6534a95-4737-4ff4-ae05-dfe169aa07f1.png)
Based on the data above:
The tooltip for Gene A (left side of image) should read:
Max of GenesDetected: 10829
Min of GenesDetected: 9818
(median, Q1, and Q3 appear to be correct)

The tooltip for Gene B appears to be correct (right side of image)

**Comment by jakevdp** [comment]
Usually for this kind of issue with CSV data, it boils down to the fact that your data are being treated as strings rather than numbers. You can fix this by passing a `parse` argument to the data specification; see https://vega.github.io/vega-lite/docs/data.html#format
