### ISSUE TITLE
Mouseover and Legend selections don't work together

### ISSUE THREAD

**Issue by mershal** [vega/vega-lite#7907]
### Quick overview of the issue
I want one chart that does 2 things:
1. Hovering a bar should change its opacity
2. Clicking on a legend item reduces the opacity of all the unselected items

For this, I created 2 selection params and used them in `fillOpacity` condition.
The error starts when I first click a legend item, and then when I hover the legend.

The error is:
`TypeError: Cannot read properties of undefined (reading '0')`

After this error the entire chart go nuts:
1. I need to double click a legend item to select it (instead of a single click)
2. Clicking on a bar (might) change the selected legend item
3. Hovering a bar doesn't always change its opacity
3. And maybe some other stuff 

### Simple spec to reproduce the issue
[Example in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoKGvJsATgE80IAIKKQ23XDQBGAL4KTZspZvoAEKOznpoAExePpjm1rYAwiE6YagAzB4Aul4gOEgWSAgGqMYgsgWu6DBspBaOEHCCcFCYaKCYVjgVOWw0si1KcrYIbAz11XC1HlGl5baNZHCyynUNTS2aIO2dtjg9fY4AZjQNykWGIKYxfnFZSky9y+jzi8uZSsgWANatmx1dTHkQNlFlA2MpemQfgAPH5HE62S6xGxKLZdSzgsqCIFKAKgOGCR5OZKuFF-WwARwYSD6dDUNFI2JAR0EggA8rkoHRcRc5ODMOx5MVQLl8gg5uQXkkXO5piKCrYqjUpSkAAyUABsSkQOHaaAOOnqbyJ0tQasiSlBgkssOOBIRvn8QKmQA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"category": "A", "value": 1},
      {"category": "B", "value": 2},
      {"category": "C", "value": 3}
    ]
  },
  "params": [
    {"name": "hover", "select": {"type": "point", "on": "mouseover"}},
    {
      "name": "legend",
      "select": {"type": "point", "fields": ["category"]},
      "bind": "legend"
    }
  ],
  "mark": {"type": "bar"},
  "encoding": {
    "x": {"field": "category", "type": "ordinal"},
    "y": {"field": "value", "type": "quantitative"},
    "fillOpacity": {
      "condition": [
        {"param": "legend", "value": 1},
        {"param": "hover", "value": 0.6, "empty": false}
      ],
      "value": 0.2
    },
    "color": {"field": "category"}
  }
}
```

### Screenshot of the error
![image](https://user-images.githubusercontent.com/6480240/148449451-3ea943db-97e4-4199-8b53-443124a09f79.png)

Any quick solutions?
Thanks!

**Comment by arvind** [comment]
Thanks for filing this issue @mershal! This should be fixed as of #8268.
