### ISSUE TITLE
Binned, stacked area charts can have gaps

### ISSUE THREAD

**Issue by paulrosenzweig** [vega/vega-lite#7930]
## Broken Chart
![broken chart](https://user-images.githubusercontent.com/691495/149862989-29623379-ce06-4961-9a4e-08fe0cd52c66.png)

[link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICOOLLIMasiFJnyAvkszakVgGZttCNAG1QrmoKYcNr6NBAAakjCygAUqpgMCN4AOiAAQmzKAJ4ABACySBAQOTFkAJSpALplIHaVSsjaANb6SNpwKEqmUJmWZGigAB4DIP5wgsr6Gdn5hcWlNUpMlmhODHAOIFkjSGRk7RRB+j0Mspi1Sj2CHiNjE-oAyiZQNHAQtXZ2QA)

The chart shouldn't have that gap at the bottom. Also, the areas on top are truncated too early on the right. The correct version would look like this:
## Fixed Chart
![fixed chart](https://user-images.githubusercontent.com/691495/150019078-65082713-68a7-4480-89b9-62dc0fa66bff.png)
[link](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJk6aG+mgBMABhcz4NMlmduZETABPABtDdCg4YOCjDSRMFFQAbVBxJAQwkDEGZQiAfRcjbOj0WPiCHDhLBgsIETFJGQAzNmVkTDRQIIrtUQkjE2UIMNAAITYNQIACAFkkCAhJgAoyAEptcQYEJjhlEABfPZlMZSRxCGbWtGSQLozGmmDMHaM4AA8cXfQaCAA1JGD7ItSptEgAdEBjCYzOYLZYrcEAXTWh06gW66DeT3E7SaNEiWnQkKms3mS1WRggXlSxVkFlyyFeTBquQAjC5ckTciSILlcmReZjKu0UTc0RkmQ0QPd8doidDSXCjHMrrTxPSkIzmWyOeNiTCyWsZBL1Zqzqz2XLuQbcpUtAj-FT-tpjQyJTztZzubz+bk3S9Xlj2qhQJSyNTnXTXVqLbquTDvQKA0L9jIo2c0GyRbdtEgyCo+E8jCo1DgmIEVS6NW7zTqoVbFUbI1Xo7W9QrVjbNEYAMoVKB4iAge0gNh4FVQNTYoe4-GDpIbKLD5VJEC8ifqdoIrNi7QXBAMYIoGRvD7aFyUAQAKmBCDBqpN1Y9uvlsNWiIA1Oerze75XTe6YzrfU4U7DRESVOd7zTADWxfa0EHsFNUXREAaAQHAGELGdggJVdcnXKcZGLBhS3LFdezgfs4EHYcFDgMioObM0nyA9sVnpRDUzgehxm0Yh-gYQwZH44JBLQFxtxQgJ5AUItVBIssKybf8a0tYCOwQu1sNwtdJxxTIWiDUBpRwlUKKomiZBaDRnhXGzoFtCwrC3GRl0SPCCMwXJpOUfTdI3UDpxHRpGiGIMQAALx2Nh9i3YdkGUBQ52uVJ0m0Ex6GInAjGzdAsqMRpVAQDopXkbiStSu4yqeDRcgymB1QsGI4gSAzsjyAoiPk0izL7AchwOY9xAnGySpI0phl0exHGDKU8VM2b8vQOwHBgfZDgwOAvB8WaTIJUAls27bhQODaEqSq4UjSDJzsHI4d3QJBlDgI9MiCUIVSel6grEXySr27Qf3BP9H0AttX3YzTwI2wq2GK2bSlaxpqrgWr6sayQNsqEbJvGuJJpaPEp1mkSxPQUhfJoKAnRhh5ihDamPvCNhghaAr5tw8z+o2+yoGUGgcEwdhJFm0Nw3QcE1LYpYJXEVGVlQSZwUmd8lgAQm+P4AQ0IE4hBYHlNB2D6zfIcVkmAAfC3Jg1iAADELAMRZ3yBxiVJY8GDURc2AH4lZABdgmVxW9ziXXMH1t2jaliHESkf3wXN1XlcAZAJ-ZVyZQ8wcPI5BlsY+tW044TkAViT-2AG5JgAYT0yY2EaSYACVKOs-B09VxYs5z29wX87Fi-BRPy-BKuueoxXlc7zX-kBV3x4gb3Jj9+e+uoxFJknkBwRdvXe5ABfvZTEBXhK6B-gyU-tIjNVoNU58TchxCNrIhmL+0ctr-QfuvNtY-AicGfRmGRP5zRlN-fCelvLxD+jzOA9w5b7UyI6GkM9tY91-IbfOD91JPzAmbSYAAyQhkxvgO3EE7XeEd9552YmDOCIEoYEOIaQ34s8daux-kvFhZDHZPGdpwyBG4j6nT2HFfwwDkpXTSugK+ooUIAjlk9GIcMkBNVFig7QiRaEwU9PGPkvI3SUB8pgeOOj74TDjPMBMvoajGMwKOBEx8TiWDCIkdwIZNHLWmmtMRjZ0waLDE6dA5iPZWJ5AY2x6YNpRVUGgZGwQhgikqh-HKD0QCKJersGQGhVHqNAIjbQWQchwHyOzWcKof7QKen5IR2JAouRAC4sgbjPFBJpJ4bwwopAuGHBQiIaBjiCRkLEmKqAhlwGSddbQE5WbZPkRkayFgnQ5LySLApLUilqBKWUr+B8153QMn9cZyhBIbWaRkamTwyAtHLH4kAGpqKXUyMA1JVl+bJnQKERo+kVD2G7K82RclEInOGTcKmCha4bjPl4kAEQHiLE6VgAgAAWFwyJVnIHUQkoYMhDzbESfE-4uKHn8wSDiuAqYNQAFEkzE3cCABC4haWBnEkcCFc4KUjIsDZU+qAJJSDfkzE+RhCafNkGwbAcNgUEi5eCzAwqC5whlhYRBhoMlIAJXbUSEA1qgspRqglAB5Cmh5sr6vZYoKFxM2nizhVtYIiwVr0AIGyDFkUeVvHEiKc+wrQFiuJhk+Bvz+ayuJQaoWCqMjWswPXRuLcJzKA0Ic-FkQTU7DNYM05EaIUxphe0mZDrEVbS6ai9Fx8Iqer5RJYcoQWmaCkXNKIMyWZs38IELYLMAAq6T+w5A+uyqN2gF6xT2EAA)

## The Change
The current generated code is using the original binned field rather than the `_mid` version. The diff between those chart's Vega code is changing the area's `defined` channel from this
```json
{
  "signal": "isValid(datum[\"bin_maxbins_10_Body Mass (g)\"]) && isFinite(+datum[\"bin_maxbins_10_Body Mass (g)\"]) && isValid(datum[\"__count\"]) && isFinite(+datum[\"__count\"])"
}
```

to 
```json
{
  "signal": "isValid(datum[\"bin_maxbins_10_Body Mass (g)_mid\"]) && isFinite(+datum[\"bin_maxbins_10_Body Mass (g)_mid\"]) && isValid(datum[\"__count\"]) && isFinite(+datum[\"__count\"])"
}
```
## Another issue

I think ideally, the areas would slope down to zero at the edges of the x-extent for consistency. That seems like a slightly different and less severe bug though. I believe fixing that would require changing (and complicating) the imputation transform or adding another transform step.

**Comment by domoritz** [comment]
Nice catch and since you already dug into the issue, do you want to send a pull request to fix it?

**Comment by paulrosenzweig** [comment]
@domoritz Yup! Just opened #7931. It looks I need to be approved to allow running the workflows. I'll un-draft it once those pass.

**Comment by domoritz** [comment]
Unfortunately I have to reapprove every change but I can do that. Make sure that tests are passing locally.
