### ISSUE TITLE
heatmap has lost its color

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#794]
This is JSON that used to work. Now it makes the heatmap appear properly, but the colors in the heatmap are gone.

![vega_scaffold](https://cloud.githubusercontent.com/assets/976970/11408604/26b2eba6-936f-11e5-8a26-6877775047a9.png)

VL json: https://gist.github.com/jowens/bad601593ec88b794d3b (oddly, this doesn't work in the vega-lite editor)

**Comment by kanitw** [comment]
Thanks for reporting and your patience with the dev branch!  It should be good now. :)
