### ISSUE TITLE
y-axis labels get cut off when too long (after panning/zooming)

### ISSUE THREAD

**Issue by tvst** [vega/vega-lite#7943]
When you pan/zoom a chart, the labels for the y axis at some point don't have enough space and get cropped.

Steps to repro:
1. Go to this [demo chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AAVBbTBAAEmAO5tTAMwayoOuWYYQassqaSmycWXHUkTDhlUwg4AEcGPyg4SkUQCxplejQAZgAGDKV4GjIsNABGMWyQHCRAhAg0AG1QWSQEODQQMk1lBPDBOEcW92D1YiRBBKZ3DvRoYbUQAF8AXSVlIJRUUHComOa1kAhMCsw0Ur22HCKAJkoAdiU9uDPUDMpCpSRq9AAPOdmlTEDZCA2NjqBC1UBQYZQBiCILbXbuAAUy0wDAQlA+AEoEm8Wm5ZAjMXMFODIdDYS0oGwIEigqj0VjXu8QJTqYSfqAgYIJjV4fjCUoWQSsfMFkpkOoANYtYT+BIxNjKdxkNCgL47TAATxwcKiSFkOn2OlICRsNDgXJaX1+dG6aFk0MEPxAGpVIFN5omICGgmiCU12pauv1dCCNGN1swttQ9sEjoFbCM6ld7ot6AlcBdvy1cNkbAQ7mGfpt2xjjtmsyAA)
2. Zoom in until the y-axis labels look like `x.xxxx`

Notice how the left-most digits get cropped:

![image](https://user-images.githubusercontent.com/690814/150842406-04b2ade7-734d-4a9c-bffc-8c4bb2491915.png)

In the toy example above you need to scroll quite a bit to get to this point (perhaps beyond what you'd expect a user to do!), but I have seen cases where this does become a problem in reality.

---
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues.
- [x] Describe how to reproduce the bug.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) spec in JSON, wrapped by triple backticks like this:

```json
{
  "mark": "point",
  "encoding": {"x": {"field": "a"}}
}
```

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment]
You can fix this by adding

```json
  "autosize": {
    "resize": true
  },
```

Note that it adds some performance overhead and that it's better to manually trigger a resize (`view.resize()`) when you need to recompute paddings.
