### ISSUE TITLE
Excessive padding when generating a chart with `vl2svg`

### ISSUE THREAD

**Issue by topherhunt** [vega/vega-lite#7956]
**Requesting guidance:** I can't tell if this is a bug or user error. If I'm simply using the `vl2svg` command wrong, please let me know, and sorry for the disruption.

I'm using vega-lite's `vl2svg` CLI helper to headlessly generate chart SVGs on a Heroku server. This works great for the most part, but I'm noticing that the generated SVGs have way too much padding on the left side, to the left of the labels, and the amount of "excess padding" grows as the labels get longer.

For example, here's a simple bar chart with 3 bars and 3 labels. In the [online Vega-Lite editor](https://vega.github.io/editor/#/edited), the chart renders correctly as pictured below (ie. no excessive padding). But when I generate the same chart via `vl2svg` on my local computer (using the same package versions - Vega 5.21.0, Vega-Lite 5.2.0) the chart has around 100px of excess padding on the left side before the labels begin.

The chart's VL spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [{"category":"Male","count":112},{"category":"Female","count":122},{"category":"Other (eg. non-binary)","count":31}]
  },
  "encoding": {
    "y": {"field": "category", "sort": null, "title": "", "type": "nominal", "axis": {}},
    "x": {"field": "count", "title": "", "type": "quantitative", "axis": {}}
  },
  "layer": [
    {"mark": "bar"},
    {
      "mark": {"type": "text", "dx": 3, "dy": 0, "xOffset": 0, "yOffset": 0, "align": "left", "baseline": "middle", "limit": 20, "fontSize": 8},
      "encoding": {"text": {"field": "count"}}
    }
  ]
}
```

Steps I used to generate the svg headlessly (on MacOS 10.15.7 in case the OS matters):

- `npm install vega-lite@5.2.0`
- write the above spec to `test.json`
- `node_modules/vega-lite/bin/vl2svg test.json > test.svg`

The SVG chart rendered by the [online editor](https://vega.github.io/editor/#/edited) (I added the red border to highlight the difference in padding):

<img width="328" alt="Screen Shot 2022-02-01 at 11 38 40 AM" src="https://user-images.githubusercontent.com/4580894/151955446-788177e5-a8d0-4bf2-bd2c-a9b06714e0b9.png">

The SVG chart rendered by `vl2svg` run locally:

<img width="408" alt="Screen Shot 2022-02-01 at 11 38 51 AM" src="https://user-images.githubusercontent.com/4580894/151955470-ba323d05-6308-4a9b-95da-fef11b80dcab.png">

Why does this difference in padding / spacing exist? What can I do to make the headlessly-generated svg render identically to what the online editor generates? Is this a bug, or user error on my part?

NOTE: The excessive spacing _mostly_ disappears when the labels are uniformly short. For example if I reword that third label to "Other", then re-render the svg using `vl2svg`, there's only ~5px of excessive left padding, as shown below:

<img width="289" alt="Screen Shot 2022-02-01 at 11 43 25 AM" src="https://user-images.githubusercontent.com/4580894/151955537-8e46977a-c746-472e-813e-5811af8e9c98.png">

**Comment by domoritz** [comment]
I don't know for sure but I'm guessing that the text measurement is off. We measure text width using an offscreen camera as in Vega and it needs access to the font. 

Can you try the Vega cli tools to make sure the error is in vl2svg and not vg2svg?

**Comment by topherhunt** [comment]
Sorry, I won't have bandwidth to follow up on this :-( -- I switched to rendering the charts via frontend JS (in Puppeteer) to work around this issue and also improve rendering speed.

**Comment by domoritz** [comment]
Great. Can you share the code/a link here?

**Comment by topherhunt** [comment]
Re: this bug (if it is indeed a bug) all that's needed to repro is the steps described above (but please lmk if I've missed some key piece of info).

If you're interested in how I rendered the charts via JS in the PDF, the gist of it is below.

The following HTML body was passed to Puppeteer to render as a PDF:

```html
<html>
  <head>
    <!-- Load Vega and Vega-Lite JS, either from URL (shown here) or to reduce network reliance, write each library's JS directly into the HTML file. -->
    <script src="https://cdn.jsdelivr.net/npm/vega@5.21.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@5.2.0"></script>

    <script type="text/javascript">
      // Call this function to render any Vega-Lite chart.
      function render_vl(target, vl_spec) {
        var vg_spec = vegaLite.compile(vl_spec).spec;
        var view = new vega.View(vega.parse(vg_spec), {
          renderer:  'svg',  // renderer (canvas or svg)
          container: target, // parent DOM container
          hover:     false   // enable hover processing
        });
        view.runAsync();
      }
    </script>
  </head>

  <body>
    <h1>Test PDF with Vega-Lite charts rendered via JS</h1>

    <div id="vlchart-1"></div>
    <script type="text/javascript">
      // Render this chart into the above placeholder div.
      render_vl("vlchart-1", {
        "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
        "data": {
          "values": [{"category":"Male","count":112},{"category":"Female","count":122},{"category":"Other (eg. non-binary)","count":31}]
        },
        "encoding": {
          "y": {"field": "category", "sort": null, "title": "", "type": "nominal", "axis": {}},
          "x": {"field": "count", "title": "", "type": "quantitative", "axis": {}}
        },
        "layer": [
          {"mark": "bar"},
          {
            "mark": {"type": "text", "dx": 3, "dy": 0, "xOffset": 0, "yOffset": 0, "align": "left", "baseline": "middle", "limit": 20, "fontSize": 8},
            "encoding": {"text": {"field": "count"}}
          }
        ]
      });
    </script>
  </body>
</html>
```

Then I ran the following node script to tell Puppeteer to render that HTML to a PDF:

```js
// This script invokes Puppeteer to render & save a PDF based on the given .html files.
// See https://pptr.dev/ for setup, API docs, and debugging tips.
// 
// Puppeteer's PDF renderer has some important caveats:
// - The body, header, and footer are rendered as separate HTML documents with separate
//   styling etc. These are then assembled into the final PDF.
// - The header & footer use a lower DPI than the body (72 vs 96).
//   For more info see https://stackoverflow.com/a/51461829/1729692.
// - The header & footer can't load external resources (fonts, images, JS, etc.); instead
//   these need to be embedded in the HTML markup or encoded as data URIs.
// - The header & footer can't execute JS.
//

const fs = require("fs");
const puppeteer = require("puppeteer");
const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

let id = process.argv[2];
if (!id) {
  console.error("Please provide an ID.");
  process.exit(1);
}

(async () => {
  var body_html = fs.readFileSync(`tmp/pdf-body.html`, "utf8");
  var header_html = fs.readFileSync(`tmp/pdf-header.html`, "utf8");
  var footer_html = fs.readFileSync(`tmp/pdf-footer.html`, "utf8");

  const browser = await puppeteer.launch({args: ['--no-sandbox']});
  const page = await browser.newPage();
  await page.setContent(body_html);
  await sleep(200); // Wait for Vega-Lite charts etc. to finish rendering
  await page.pdf({
    path: `tmp/pdf-output.pdf`,
    margin: {top: "50px", bottom: "50px", left: "10px", right: "10px"},
    displayHeaderFooter: true, // NOTE: Unsure if this flag is needed.
    headerTemplate: header_html,
    footerTemplate: footer_html
  });
  await browser.close();
  console.log("Done.");
})();
```

**Comment by domoritz** [comment]
I'm still confused about what's gaping wrong. https://github.com/vega/vega-render-service should work correctly but I don't have time to dig into getting it up and running again right now. 

Can you try the Vega cli tools to make sure the error is in vl2svg and not vg2svg?

**Comment by domoritz** [comment]
Closing since we don't have nougat details. I can reopen if needed.
