### ISSUE TITLE
Possible Axis Bug in Example

### ISSUE THREAD

**Issue by PBI-David** [vega/vega-lite#7959]
I've been working through the Vega-Lite examples and noticed some strange behaviour on this one. 

https://vega.github.io/vega-lite/examples/facet_bullet.html

I don't think the axis is supposed to look like this, is it?
![04-02-2022 09-53-35](https://user-images.githubusercontent.com/86846675/152508739-b564264c-3193-4a09-a5a8-975ab8cc3394.jpg)

**Comment by domoritz** [comment]
Yeah, it's a known bug with faceting, I think. Can you check for existing issues around that?

**Comment by PBI-David** [comment]
@domoritz  I checked but couldn't find anything similar. Apologies but I'm brand new to Vega-Lite so I have probably missed the existing issue.

**Comment by PBI-David** [comment]
Closing as already report in https://github.com/vega/vega-lite/issues/5547
