### ISSUE TITLE
bar charts with quantitative x axis can't go horizontal

### ISSUE THREAD

**Issue by pdhorn** [vega/vega-lite#7992]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "Google's stock price over time.",
  "data": {
    "values": [
      {"y": 2, "x": 1},
      {"y": 7, "x": 3},
      {"y": 4, "x": 4},
      {"y": 1, "x": 6},
      {"y": 8, "x": 8},
      {"y": 3, "x": 9},
      {"y": 5, "x": 10}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "y", "type": "quantitative"},
    "y": {"field": "x", "type": "quantitative"}
  }
}
```

Note the `encoding` switches the x/y axes.  This should produce a horizontal bar chart, but instead it produces a vertical bar chart:

<img width="256" alt="Screen Shot 2022-02-17 at 10 45 44 AM" src="https://user-images.githubusercontent.com/15755132/154529420-b4fc30aa-05b0-450f-a221-a12cfdf4f586.png">

If you change `encoding.y.type` to `ordinal`, it is horizontal.

I am a user. It feels like this is a Bug.

**Comment by domoritz** [comment]
Vega-Lite has no way of resolving the ambiguity about the orientation of the mark so we need to manually override the default. You can do this by setting `mark.orient`. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AHE2bMoLgByCAAIImNlADWlnJqhxLbUuss6EcSopUkTBRUUGIkQQY1NABtUABPNAAmJQAPNABGAF8FBLQAdjS0AGYcvNQAFiLKspBE1AzqgDZa+oAOarbWkuqATm7UMWqMgAYsgF0ckGR1ezRQTHicODQQJiR1ALZNOFlMVZhtmgAvOWDBECndqDZlGlkyeZB00JAAMxo4QWVVxKVF5arACODCQezoQRopEuSnqoA+Xx+6HS-yWK3QILBOmCOmhWXxQA)

**Comment by pdhorn** [comment]
Thanks! Perhaps this could be added to the docs https://vega.github.io/vega-lite/docs/mark.html

**Comment by domoritz** [comment]
It's documented inhttps://vega.github.io/vega-lite/docs/bar.html#properties. Not all marks have orient.
