### ISSUE TITLE
Calculate property for data?

### ISSUE THREAD

**Issue by depstein** [vega/vega-lite#801]
Documentation implies <code>calculate</code> property can be used to add new fields, either it's unimplemented or I'm using it improperly. Example:

<code>{
  "data": {
    "values": [
      {"x": "A","y": 28},
      {"x": "B","y": 55},
      {"x": "C","y": 43},
      {"x": "D","y": 91},
      {"x": "E","y": 81},
      {"x": "F","y": 53},
      {"x": "G","y": 19},
      {"x": "H","y": 87},
      {"x": "I","y": 52}
    ],
    "calculate":[{"field":"highlight", "expr":"if(datum.y>40, 1, 0)"}]
  },
  "marktype": "bar",
  "encoding": {
    "y": {"type": "Q","name": "y"},
    "x": {"type": "O","name": "x"},
    "color":{"type":"O","name":"highlight"}
  }
}</code>

**Comment by kanitw** [comment]
This should work now.  

Note that I change `name` => `field` and color’s type from `O` to `N`

```
{
"data": {
"values": [
{"x": "A","y": 28},
{"x": "B","y": 55},
{"x": "C","y": 43},
{"x": "D","y": 91},
{"x": "E","y": 81},
{"x": "F","y": 53},
{"x": "G","y": 19},
{"x": "H","y": 87},
{"x": "I","y": 52}
],
"calculate":[{"field":"highlight", "expr":"if(datum.y>40, 1, 0)"}]
},
"marktype": "bar",
"encoding": {
"y": {"type": "Q","field": "y"},
"x": {"type": "O","field": "x"},
"color":{"type":"N","field":"highlight"}
}
}
```

**Comment by kanitw** [comment]
Actually, please `kw/x-stats-color` branch until we merge it.     :)

**Comment by kanitw** [comment]
FYI, you might want to customize color  .... by adding `scale.range` to `color`.  
Below is an example with an ugly `"#ff0000", "#00ff00"`.  

```
{
"data": {
"values": [
{"x": "A","y": 28},
{"x": "B","y": 55},
{"x": "C","y": 43},
{"x": "D","y": 91},
{"x": "E","y": 81},
{"x": "F","y": 53},
{"x": "G","y": 19},
{"x": "H","y": 87},
{"x": "I","y": 52}
],
"calculate":[{"field":"highlight", "expr":"if(datum.y>40, 1, 0)"}]
},
"marktype": "bar",
"encoding": {
"y": {"type": "Q","field": "y"},
"x": {"type": "O","field": "x"},
"color":{"type":"N","field":"highlight", "scale": {"range": ["#ff0000", "#00ff00"]}}
}
}
```

**Comment by depstein** [comment]
Thanks, that was next on my list to figure out :-)

~Daniel Epstein

**Comment by domoritz** [comment]
@depstein You can have a look at the [schema](https://vega.github.io/vega-lite/vega-lite-schema.json) that has all possible properties. It may be a bit overwhelming, though. We will also update polestar soon, which has most options in the UI so they are a bit easier to discover.

**Comment by depstein** [comment]
Sounds good. Thanks!!

~Daniel Epstein
