### ISSUE TITLE
`aggregate: values` does not aggregate on the specified field

### ISSUE THREAD

**Issue by jschulzz** [vega/vega-lite#8019]
I'm experiencing, what I believe to be, a bug when trying to aggregate a field using the `values` aggregation operation. It seems that this operation doesn't use the supplied `field` when constructing the final aggregation. In the vega-lite block below, I'd expect the tooltip to contain the aggregate of the `tag` field, e.g. when hovering over the `[450, 1.8]` mark on the graph, I'd expect to see a tooltip of `["a", "b"]` (or something similar), however, as seen in the screenshot, it displays the entire data objects.

Is the `values` aggregate operation supposed to filter down by field? If not, I believe that should be [clarified in the docs](https://vega.github.io/vega-lite/docs/aggregate.html#ops). If so, is there some additional configuration necessary for this behavior?

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"wavelength": 250, "power": 1, "tag": "a"},
      {"wavelength": 250, "power": 1, "tag": "b"},
      {"wavelength": 450, "power": 1.8, "tag": "a"},
      {"wavelength": 450, "power": 1.8, "tag": "b"}
    ]
  },
  "mark": {"type": "line"},
  "encoding": {
    "x": {"field": "wavelength", "type": "quantitative"},
    "y": {"field": "power", "type": "quantitative"},
    "tooltip": {"field": "tag", "aggregate": "values", "type": "nominal"}
  }
}
```

![image](https://user-images.githubusercontent.com/13259923/156247914-69669dc2-b0c1-468c-a9d6-7d9c392948de.png)

**Comment by domoritz** [comment]
<img width="1559" alt="Screen Shot 2022-03-01 at 23 20 54" src="https://user-images.githubusercontent.com/589034/156294448-0f95bc95-2b20-4d68-92b8-b05c45dde51f.png">

The generated Vega looks correct. Could this be a Vega issue?

**Comment by jschulzz** [comment]
Possibly? I've only worked with vega-lite, so I'll take your word that the generated Vega is correct. I'll raise an issue with Vega
