### ISSUE TITLE
Vega JSON schema is not spec-compliant

### ISSUE THREAD

**Issue by jlorince** [vega/vega-lite#8034]
Please:

The current Vega spec (https://vega.github.io/schema/vega-lite/v4.json) is not JSON-schema compliant, which can cause errors for downstream tools tying to parse it. 

Specifically, the use of a `$ref` at the root of the schema is not valid under the JSON spec:

```
{
  "$ref": "#/definitions/TopLevelSpec",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    ...
  }
}
```
Per the spec (https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3), 
>    Any members other than "$ref" in a JSON Reference object SHALL be ignored.

Instead I believe the TopLevelSpec definition should be hoisted to the root, such that the spec looks something like this:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "anyOf": [
    {
      "$ref": "#/definitions/TopLevelUnitSpec"
    },
    {
      "$ref": "#/definitions/TopLevelFacetSpec"
    },
    {
      "$ref": "#/definitions/TopLevelLayerSpec"
    },
    {
      "$ref": "#/definitions/TopLevelRepeatSpec"
    },
    {
      "$ref": "#/definitions/TopLevelNormalizedConcatSpec<GenericSpec>"
    },
    {
      "$ref": "#/definitions/TopLevelNormalizedVConcatSpec<GenericSpec>"
    },
    {
      "$ref": "#/definitions/TopLevelNormalizedHConcatSpec<GenericSpec>"
    }
  ],
  "description": "A Vega-Lite top-level specification. This is the root class for all Vega-Lite specifications. (The json schema is generated from this type.)",
  "definitions": {
  ...
}
```

**Comment by domoritz** [comment]
We do have an option `--no-top-ref` in the schema generator but I don't see that AJV complains about top level refs. They are convenient for recursive schemas so I will leave this as is unless it causes problems in other tools.
