### ISSUE TITLE
Waffle Charts

### ISSUE THREAD

**Issue by PBI-David** [vega/vega-lite#8036]
I've been having some fun with waffle charts and managed to create the following

[Editor:](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LM2pLIgAzNtoRoA2qADuNWcrZvT1A2HH1tQIB9WQYEJjhtRRAkCH0aZRArAF0lGW1MYJAnGjhBDPQAeW0aWnklV2UE-UboOH8-Mkysm1ATQSgGQTU4fSg4GkEAAgAKVUxY1mVJgkmAJgAGAEoklPDAzIVepH7B4ea1BfTJ-km5hYjvSYAqNfWd1PQoNj0ekEk2PxIMhkbR8TAjVBeEChUZsBiyApKYqlcogKo1PzvfQAFTY6kE6NqXV+-0BwNBFHBhRhnzhCKSyLK+kJmKUu3QuPxLNkAHEIgwcHAMtklCC4TgmABPTxo6pE7qHEB9AZDKnofn+WYXBCUTnHbl88VCgh3HV6glyvzPSYARnWWyx6AACgkxgiKk5zV0lMhtABrNCgTCSwWjGjaKCCEZIiZR8p2BhwWxsb6YGhhVAJpMgCB2Nh+iEgJhDKAB3J5gsAdXS9DQ60oAHYbCA2l9lB1AyAAB6dxmor56WwhwsNQGD5JdmgfGKCQTN6WaIolJnq-ZD0PoUeyY47SfTwaCXKuArofjS5sD1y95eo7lJYMbkCyNgIMdJaDHCGgLiIQsQOCYDaBwgFGZBtOUITVG0J4gHKWBJGwThOP+J52koQzxASSEoWgADMth0FGTpIMo7ayJ0qBiARmBRgAYnImAAMo0AAXhCGxWM2ECsV+IDEMciZoKsAAsNrNpgKaCGmGZQn2zKWnUIAPoWz6vtuPzdFYQA)
![image](https://user-images.githubusercontent.com/86846675/158074731-c81bc09f-10c5-48f1-b110-6f34c870706f.png)

[Editor:](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LM2pLIgAzNtoRoA2qADuNWcrZvT1A2HH1tQIB9WQYEJjhtRRAkCH0aZRArAF0lGW1MYJAnGjhBDPQAeW0aWnklV2UE-UboOH8-MkyckDIIhhwmAE9PECqavxAsm1ATQSgGQTU4fSg4GkEAAgAKVUxY1mUNgg2ARjEASiSU8MDMhRmkOYWl5rV99I3+Dd39iO8NgBUpzEV1S6CgbD00xAkjYfiQZF6fEwy1QXhAoRWbAYsgKSmKpXKo2qtVB+gAKmx1IIxqTstDYfDEdpkaj0ZjwdjcUkCWV9LSJkpruhKdSBbIAOJ9HBwDLZJS9bEDYZo4njeRTe4gWbzRYom445Q7N4ISiix7iqVK2UEH6m800kl+QGnAAMrsuQrBIAACglVriKk4HV0lMhtABrNCgTCDGUrGjaKCCZb49Yp8p2BhwWxsSGYGhhVBZnMgCB2NgR1EgJiLKBR3IVqsAdXS9DQrsoAHYbCA2hDlB1oyAAB7D3lEiF6Wxx6sNeHT5IjmhgmKCQS9lWgCc3IIz+PoeeyR5XZerhaCXKuArofjDXtT1zjkp8ypOuogWMHkCyNgIBdJNAjyoqAXCINWEBwJgJx3CAKZkG05RrhuShTrE8iaEUL5EuKSTwEgjSJJhizxI6JTcugTBUpgf6ZL2EA0AAXiBIDEI82ZoAATAALCcvY0fmhaFDub7qkkX7Vr+-7HlCUxWEAA)
![image](https://user-images.githubusercontent.com/86846675/158074768-ec02c0ee-1e6e-4e94-9fce-77d73e658337.png)

However, I'm unable to create a percentage based waffle chart with normalised values (i.e. USA 63%, Japan 19% and Europe 18%). I _think_ what I need to do is add a data sequence generator to go from 0 to 100 (or whatever my resulting matrix will look like) and then assign values to each datum in the sequence according to the percentages. However, I'm not able to allocate the values from the original dataset's origin field to the relevant data points in the generated sequence. Is there an existing transform or expression that can achieve this or would the data have to be preprocessed before getting to Vega-Lite? If not, can you consider adding a transform to support this type of use case which would be similar to the "stack":  "normalize" encoding I think.  If I have missed an obvious way of achieving this, then pointers are much appreciated.

**Comment by PBI-David** [comment]
After a bit more work, I managed to crack it using sequence and flatten. For those who wish to recreate, this code is [here.](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LM2pLIgAzNtoRoA2qElsaspGRk2nyYcJ6gbDj6UGwMspiKIE40cILK+gDy2jS08kpIEPoAKmzqglk5fiBWALo23r7+gcEUoeEgkdGx8YnJqenoFbmJBcWlSOXZuQDi2rE4cOm1SkHzTACeniBDVXUKoCaCUAyCamHoc3HKABSqmAwIlCVlO7Kz84sEdw9P45OVsgABAAqQEARgADBCAJQjQroAAKcG0UDg8QyTmeE2q+xAASCIXOXg6UXQCCqSj6aX0SJRaMwGKxeny8JACOqNRWlxwGy2rxAewOE2Opza6AgcAAjgw0ajrmCFN9HgiANRg2Es-QAZRxoCcotC8lQHhAOsFIAA7n5lGwLe1OhdbQB9WQPJjIuH6GhLTkgGTaBLGvUpamDKYUjraZQe9DR6Bo5R+Mgc+ogQ4is7ROA0QSA25qH7ewEEcEwz2Ou2p9MnTOxguPIv8QFKyhzC0g0vltNsPTLEDIbQAazQoEw6wW0RoKMEYUpOZnAzsMtsbB7mBopKXcCUEDsbEH5xATFOUGHO73B4A6t76GgIZQAOw2ECytiJ2TJzQgAAeI6SIYGbtmRAMcJ3QVx32xfJvxoeFXUEQRn02L8qUAttElAw8IL8KC8RguCTkEHdXEDEB+E2Z8YkEVw-1QzJwzyEDx0PWQ2HJfxgOgCZzlALhEEPCVMDBHEQBnMgEz-VwUh6C4ciwRI2CcJxBLQSElFOd1yiUlTUAAZlsOgZwRJBlHfT8xAMzAZwAMTkTAtRoAAvc4ACYISsZ8ICcniQGICYZTQFyABYwWfTBV0EddSWJOiwwBDDmP0Vj2OxWoPKAA)


![image](https://user-images.githubusercontent.com/86846675/158147666-403ff811-85c3-4f69-8833-2a7d00eda7a9.png)

@domoritz I'll close this issue but let me know if you'd like me to add the examples as a PR and if so, whether all of them or just specific ones.

**Comment by kanitw** [comment]
@PBI-David  This looks good.  I think it'd be good to add as an example.

I'm happy to review a PR if we wanna a basic example without much customization (so the example is a bit easier to understand).

**Comment by PBI-David** [comment]
Sure. Let me know which you'd like me to add 

1. Stacked waffle absolute (first screenshot)
2. Facet waffle absolute (second screenshot)
3. Stacked waffle percentage (third screenshot)

I can add in a couple of parameters for the matrix size and shape too if you like or just keep it simple.

**Comment by PBI-David** [comment]
On further thought, I have decided to go a different route. 1 and 2 above can both be easily reverse engineered from 3. The problem with 3 though is that percentages don't always add up to 100 in a stacked chart and I can't find an easy way to implement [this algorithm ](https://stackoverflow.com/questions/13483430/how-to-make-rounded-percentages-add-up-to-100)in Vega. I think the more useful chart is a faceted percentage like the one below as it also shows how to use the sequence and flatten transforms. I have added some notes in the description to describe what these are doing. 

[Editor.](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289ABUYNCAAJjJpCYBmSKHExxlJnHHV3ZmJGTgmmSCI4mAO5IVlaCPrBI6piUJoY+mOpIshBWbOoIpkxwgmxBzq7pmSb0PumCeUE0smTWDLJQOnL4JgCMcQDC6nBIDhYmUGyCDAiypTB9JhAw+aZlg2wNmCZsVhaVg9EQcQBMXT19PpZDI2MTUzNzE5FLHqvrSJtQ2yZk6ksuTkwAniYA8ppaLI4gBmOIAERoxBoqlKyVSxQQJl2vj+SRSaQyyNBpTYb3sAxcbjgHi8cDiABY4gBBMjvPj9BY1HAMFaeJgRab4zD4uSCP6TUilIL406jVLWDIAoE1CyyJwABVc7hWKScuI+QR2JgkJm6vX6lgCAEcGKS7NYPsi2nj2gAGe0WUwpCzKZR0XRPRZnEEmABscQAYoI+g5xgtZHAggLBocHE5TebGrdfdybqUkJyfHAAB44dXzfGgx0mLWmAAUbVL5cK6hlNGBAEo4gB2A6G44mKMFcXnILwHomXqwMv5MymOB0QeLVROfwZwGNuXSzkpADWcQAHF0nlAGKH+lru6McuodQBOXeCfeH1MSk8IM87RQqPooVCgBjqQRoN+eAgXnPKQZHkABfJQMURbE0AAbVASQ2BqLwGQoBw4NANgcD-IZllfKwaFyZQ-yXYFX38P99DYTxBFImoQDAgBdCCEKQ2QUJ6NC4AwkAsJwu5MHwwjBGI9A6PkJQKIMainnEgBxD4GC+BjGKUd5Pl+OCQHEkBmIUUAXhvA8jj-RSFQrZQ+lGSgqJo+TFK+AhLMwazbNk2VxgAKgde0m3IiA-2VEkPH+Kw3N-FiQA4xluNQeDeOw9AEHopQCKIwKVVJTBQvC-yMuCwSmLUhzNLi7SPN0yLDNvEz0CTC04CrBRqzaPzJIC9AAGU4DNBqGP0kBwjDUktO63qU0qgbquM9D0BoKwLKshBKDG5NLQAHgAXhMZzrKC1UFB2pbKHEhQAHIAH011kdczraqKOpARU8kKqa9xm2KQDsGhBBMRaXOW1aGpMAgHXuqSQC1fqDPeu8-12wGerWnx+COgHKGPbzqzy9BThU1LbHsNADOGCVicG4TRPK5cJIwXpVHUcnQxyWjNCyv8mGo3kEAYsCIJACAXCgcnkHUddycwH4XBwmg3AiITKkcNAknNSC2GGHREpVuAlAgJI2HXT6AGILzgC8mHN189Y+Q2AHVYXoNB7UoVt+YtNgPVqcnc3JtKRP439IKlz6Mk9p5yNzYw0FkA9BH5n5fcp0z8lfSXpfQUPkMDqLI46mPKl1jJBPQfgE-504MnJoYFU9OQJbUYv-z2l6TE27bLuu27X2IJ5zT-I24H9OBQWH-qBcM2LQC4RBPoCTA2jHv2qee6jU+Dv9ZDYZL2OziJvAVaPY-5iAaAAL0nkAe5GWLdkpNp+d5DWtB4peSIqoP05ATft-Dpi+bAoAA)
![image](https://user-images.githubusercontent.com/86846675/159159112-caad062b-1086-4c6e-8ec8-c5092257cfcc.png)

I also have this but I think it gets too complicated for an example by adding layers in too. 

![image](https://user-images.githubusercontent.com/86846675/159159156-6d4db296-15ee-4a1b-a1a3-ae6f91c11c5e.png)


Let me know if you want me to create a PR for this version, either with or without the percentage text marks.

**Comment by steve257** [comment]
Hi David ... Could you possibly add the code for your last example given which includes the percentage text marks layered on top. Thanks.

**Comment by PBI-David** [comment]
@steve257 here you go. 

[Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LM2pLIgAzNtoRoA2qElsaspGRk2nyYcJ6gbDj6UGwMspiKIE40cILK+gDy2jS08kpIEPoAKmzqglk5fiBWALo23r7+gcEUoeEgkdGx8YnJqenoFbmJBcWlSOXZuQDi2rE4cOm1SkHzTACeniBDVXUKoCaCUAyCamHoc3HKABSqmAwIlCVlO7Kz84sEdw9P45OVsgABAAqQEARgADBCAJQjQroAAKcG0UDg8QyTmeE2q+xAASCIXOXg6UXQCCqSj6aX0SJRaMwGKxeny8JAtNRPWWIFWDBwGy2rxAewOE2Opza6AgcAAjgw0ajrmCFJCwbCWfoAMoyuWyVE40BOcWheSoDwgLWy+VhYUgQ5is76GhOW5qH4WnWowEAHgAvIDvo92fSFP7XY9XgoAOQAfSYp1kAGtI2q8ayEYJSvrbaKTg70KiaIJAS77o93VbAQRwTC4fo5gB3LN23MSgylyjl3VwQH8UPthsg6u1-NsPRcpxIVEJTS20cPE0GlLUwZTCkYOBIZTItCgU5MVIVen6JilTBsdxWS9KCALKA7kCndbb02gZDaBP3zDrBbRGgowRhJShYAQMdhyrYbCjpgNCkmBcDXnYbAJucIAAMQAJxwOhTDYYkECIchADqNDKPQaAQpQADsNggPKbDKH4ZD3gAHveVIDLOzIgF+P7oK4DH+FxSDMTQ8KyCcgg0ZsM7sXWbCNrY34ofxfjYvkIliRJ16uNOID8JsNExBm2j3jEsgMdBcifnA+H6AGlDpqUgI+n6MZxg4SaJMQExyvoqFwAAbHAADMIU4iA0ATOcoBcIgKFSpgYLhbJiIZgkim8SAsjnqpXEAWQaIDOJgiSdeNAAF7RSA3mCL5qAAEwACxgjRZ5QTB7Qpdsq55NxSn6Nl5KCdUdT1CAb4fjOPEoaEzHpUkciYBqFXnMFEKUothFwDkWDHqOSxKHRAlMTO6wYk4CX3jVdVra1cBzaZcgWewC7cTZun2Z2noueCXk+VV904CZ6D2UG8SAgA1ICkYAKSRtUV6ca496RQBKOwHF+gJUlNFdY5CSXrUl5AA)

**Comment by steve257** [comment]
Thanks heaps!
