### ISSUE TITLE
Support local paths for images (file://)

### ISSUE THREAD

**Issue by davibicudo** [vega/vega-lite#8061]
It seems the image mark only works with URLs hosted in the web somewhere, i.e. local paths won't work. 
The motivation is to support images in Vega-Lita/Altair offline HTML-Reports. 
Another interesting alternative would be to allow a base64-String.

**Comment by domoritz** [comment]
That's an issue for Vega or the browser since Vega-Lite does not render the chart itself but only compiles to Vega.
