### ISSUE TITLE
multiple bar graphs broke in a recent checkin

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#809]
No longer renders in vl editor. Vega-lite: https://gist.github.com/jowens/95f7f841cbd0e0810a3c

Here's the important bit; I'd bet something changed:

```
  "encoding": {
    "y": {
      "field": "m_teps",
      "scale": {"type": "log"},
      "type": "quantitative",
      "axis": {"title": "MTEPS"}
    },
    "x": {"field": "dataset","type": "nominal"},
    "row": {"field": "parameters","type": "ordinal"}
  }
```

**Comment by kanitw** [comment]
Thanks for reporting!  I just pushed a fix, so it should work now.  :)

**Comment by jowens** [comment]
OK. Fixed! If you take a look at that graph, though, the labels on the right are now truncated. (I think it's an improvement to put them on the right and make them vertical, but it would be better if they wrapped to multiple lines rather than truncated.)
