### ISSUE TITLE
Ordinal Binning

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#81]
maybe bin by some sort of hash function?

- [ ] implement
- [ ] modify schema to add bin support for `O`

**Comment by kanitw** [comment]
I do not think this will ever be in our roadmap. so closing.

**Comment by domoritz** [comment]
Yu can kind of do it with formula transforms. Just create a new field that is e.g. the first letter and then group by that.

**Comment by kanitw** [comment]
and that's automatically supported by the `calculate`property ... so still legit to close I guess

**Comment by domoritz** [comment]
Exactly. We could make this a bit nicer in the API but as long as there is no request for it.
