### ISSUE TITLE
Apache Arrow 7 table is not working with vega-lite in ObservableHQ

### ISSUE THREAD

**Issue by kimmolinna** [vega/vega-lite#8105]
You will get `TypeError: 'set' on proxy: trap returned falsish for property 'Symbol(vega_id)'` error message if you try to use table from `tableFromIPC(fetch(url))`
```js
arrow =  require('apache-arrow')
table = arrow.tableFromIPC(fetch(url))
```
[Example](https://observablehq.com/@kimmolinna/test-vega-lite-and-apache-arrow-no-plugin)

**Comment by domoritz** [comment]
Yeah, I saw that. Here is a workaround for now https://observablehq.com/@cmudig/duckdb-vega-lite

**Comment by kimmolinna** [comment]
I use that workaround at the moment but I reported this when I remembered to do it. ;)

**Comment by domoritz** [comment]
Can you verify that `@domoritz/apache-arrow@8.0.0-canary.9bbbb770b` fixes the issue?

**Comment by kimmolinna** [comment]
Yes, I can. @domoritz great work.
 [Test page](https://observablehq.com/@kimmolinna/test-vega-lite-and-apache-arrow-no-plugin)

**Comment by domoritz** [comment]
Excellent. Thank you.

**Comment by domoritz** [comment]
Fixed now.
