### ISSUE TITLE
Boxplots with many identical values or just one value are missing the median line

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8126]
For datasets with many identical values, it is understandable that there is no box drawn for q1 and q3, but the median line at q2 should always be present. Currently only outliers are shown which is confusing since it gives the indication that the dataset only contains a few observations, rather than potentially many observations compressed at the same value.

![image](https://user-images.githubusercontent.com/4560057/165193008-93a6660a-9618-4609-a367-bfcdeab8f663.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLQBOAEzG2hgIyHDADgDsmOgCMwdMBJsWArDGMwXbE6eAGwSKnIgGgoATgDWOk4QAB4ADgA2EOLcmFCQdCRIqCBJqvCYaXQ6aApppNrchACeKdrIIACOpApEcMrEaNqy8koKlJiElKp6Ckam5la2Ds6u7p4+fgFBFqEqyADa6DV1KBYynIe1radschfHyNe3INWXJ2d3V+-PR1enTy-3Qw3AC6siAA)

My expectation would be to see the chart like it is shown in seaborn:
![image](https://user-images.githubusercontent.com/4560057/165193054-bf027f73-ae0a-4cd2-9628-cf737737333d.png)

**Comment by joelostblom** [comment]
On a closer look, it appears that the median line is actually there, but since it is drawn in white, it is invisible unless the colored box is present or the chart background is dark:

![image](https://user-images.githubusercontent.com/4560057/165193637-e57712ee-3ddb-4dc5-b83c-14d071666d33.png)

It would be nice to add some logic that changes the color of this line to the color of the box when the box is not present (this could be thought of as compressing the box (q1 and q3) to a line at q2 and draw it on top of the median line)

**Comment by domoritz** [comment]
Ahh, good catch. The tricky bit is that Vega-Lite never sees the data so we have to build the logic in Vega spec.

**Comment by joelostblom** [comment]
Another scenario where the current behavior makes it hard to detect the median, is if it is the same as one of the quartiles as in this case:

![image](https://user-images.githubusercontent.com/4560057/166124667-68008f4f-40f8-4174-b628-4251da7db841.png)

An alternative to introducing logic for these special cases on the Vega side of things would be to change the default median line to a black thicker line (the same grey as the whiskers is hard to see):

![image](https://user-images.githubusercontent.com/4560057/166124840-94c4af46-35e3-488b-b054-213811f79efd.png)

This doesn't look as great as white in most cases, but it does solve both the edge cases I have reported here.

![image](https://user-images.githubusercontent.com/4560057/166124928-49ac9df0-e00d-44bb-9bc3-448ab045ed31.png)

![image](https://user-images.githubusercontent.com/4560057/166124936-31729813-3054-49cc-9cd4-79eadb0b05f2.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygHYQLYFN7mhAtATgCYCAGPARjzwA4B2NMAIwGMwmBmKsgVgDMCfmxBpwBsbWAF8ANCBQQATgGt4oKAE8ADhjggGAewAeGgDZ6oIGejABLCIhUgme0-MwBiYp4sgoAC2tMiohoAM4h8AQS0iBoiE42iADmDgYOPNZoxmCYAG4QxgCuGDLqWpgAjgV2UNYwNTkYUTKQMCFoUOEIWDD4RKQU1HSMLOycvPyCwmRisHAA2qB5hdpUxNKL+UXweGtSG8vbu-tbcGSe6yBLJ2dHl5vaZGcXV9o7EgC6UUA)

**Comment by domoritz** [comment]
Could we add a colored outline around a white line?

**Comment by joelostblom** [comment]
I tried that a little before, but it was difficult to get the top and bottom of the outline flush with the box, since the corners seem to be a bit rounded regardless of the cap style I choose:

![image](https://user-images.githubusercontent.com/4560057/166127684-944bf9a6-ef2e-4a35-bfe8-35bed8f192f2.png)

If you are OK with the median line being contained within the box (rather than the current appearance of splitting the box in two), then I think it can work:

![image](https://user-images.githubusercontent.com/4560057/166127720-c064db61-150a-4f27-a9d8-fad4c8d7fbcb.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygHYQLYFN7mhAtATgCYCAGPARjzwA4B2NMAIwGMwmBmKsgVgDMCfmxBpwBsbWAF8ANCBQQATgGt4oKAE8ADhjggGAewAeGgDZ6oIGfoMqQAZyjy9i7SADEAFgDCNKgEEqFnYOTmgA6gCWYFAAFvAE0rL04RCINkx6pvKYAO7R4VAYMjHhTIqIaLa2cQB0XDL2js6YHt5+AfXBzp4QGpi2AI4ArgoYEgloiOlg4YgA5jbWCCA84WjGYJgAbhDGg4Ug6lqYQylQ+dDhm6MJkDC2aFBVS7e4hCTklLT0zKwc3HwCJhCUTieAAbVA2122ioxGkkJ2e3geDhUgR0ORqPRSLgZGIWJAUJxeIJRO0ZDx8MJiO0KIkAF0xkA) (not sure if some might consider it incorrect that a bit of the box seems to stick out under the median due to the outline although their value is exactly the same, this is a very small difference though).

![image](https://user-images.githubusercontent.com/4560057/166127756-7fdd09fa-ab00-4606-aa4c-c66ef679ecc9.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygHYQLYFN7mhAtATgCYCAGPARjzwA4B2NMAIwGMwmBmKsgVgDMCfmxBpwBsbWAF8ANCBQQATgGt4oKAE8ADhjggGAewAeGgDZ6oIGfoMqQAZyjy9i7SADEAFgDCNKgEEqFnYOTmgA6gCWYFAAFvAE0rL04RCINkx6pvKYAO7R4VAYMjHhTIqIaLa2cQB0XDL2js6YHt5+AfXBzp4QGpi2AI4ArgoYEgloiOlg4YgA5jbWCCA84WjGYJgAbhDGg4Ug6lqYQylQ+dDhm6MJkDC2aFBVS7e4hCTklLT0zKwc3HwCJhCUTieAAbVA2122jwXGkkJ2e3gsPhIChSLgKKkCOhyLh2LRiJh+JxGLIZGIqPRMMpAF0xkA)

**Comment by domoritz** [comment]
I'll defer to @kanitw who might have a better idea.

**Comment by kanitw** [comment]
Boxplot with just one value also suffers from this problem.

I think another option to consider is to do conditional encoding (don't use white color if max === median  === max)?

**Comment by joelostblom** [comment]
Yes, that sounds like a good alternative too
