### ISSUE TITLE
[bug] Schema validator logs incorrect property name

### ISSUE THREAD

**Issue by hydrosquall** [vega/vega-lite#8137]
## Description

When validating an improperly defined Vega-Lite spec, the validation script outputs the property name of the parent (`y`) instead of the child (`scheme`).

In other words,

> Cannot use the scale property "x" with non-color channel.

should be

> Cannot use the scale property "scheme" with non-color channel.

## Reproduction 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/9020979/166294441-786315bd-1379-4076-92f8-16d7962cb9f3.png">

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55} ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "a", "type": "nominal"},
    "x": {"field": "b", "type": "quantitative","scale": { "scheme": "foo"} }
  }
}
```

Example [link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSACCikEzQAmABwBfBSbQgAQpeuoxYhwF0nEGQAJwBrVyYkYMs4WSg2ZRpZMjRQAA9UkAAzGjhBZVcUJUwATxw4V1k2BCSdEECSzJy8gvRrYrKK9ABHBiRZTDo1GlJLaB0u0C5ELuy2NnqHJaA)

**Comment by domoritz** [comment]
It's actually not the schema validator but Vega-Lite itself.
