### ISSUE TITLE
Boxplot's median tick thickness not in mark definition?

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8144]
I think this might be a similar error to https://github.com/vega/vega-lite/issues/3718, but for boxplots. When I use `thickness` for the median, the property is underlined with the yellow squiggly line and the error message on hover says `Incorrect type: expected boolean`:

![image](https://user-images.githubusercontent.com/4560057/167197862-518ab235-2177-467e-8b86-acb416140f20.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCFIAnADYoQYwgAdKyAPTGwdKADoAVpTqZNcNOstRMhY1H0BbY2kwICgC0isqU7pQAAmgAjJYATACclmzGoQrG+hD6pJpKcNA2lNAgciDeCuoA1qqEAJ76mDoARhAAHvqaEOLc3ph0cApQtYxwYFVulJSsstyYUJADUEioIG2q8A50OgoITdz1jToQ6ksK2mV1G1ia28ggjdma+yCHTfcAjqRDxMrE-qUygASShgRiYCo6PSGEx+AIKSwIOBMUjNSwFYyg8EVOGBIKOQiYPwAVgSKSKJWkQA)

The code still works and if I remove the schema specification (5.2),  the squiggly line disappears as well. I initially thought this meant the code was in master but not in the release, but I have seen this error since 4.17 or so, when this altair issue was first reported in https://github.com/altair-viz/altair/issues/2482

**Comment by domoritz** [comment]
Ahh, we only support booleans for the boxplot parts according to the types. That seems to be actually true for all composed mark components. It's interesting that it works so maybe we just have to fix the types here.

**Comment by domoritz** [comment]
Fixed in #8145

**Comment by joelostblom** [comment]
Great! Thanks for fixing it so quickly!
