### ISSUE TITLE
Dates don't parse when using a flatten transform

### ISSUE THREAD

**Issue by snunez1** [vega/vega-lite#8152]
For a while now I've been using a `flatten` transform to move data from a columnar data frame to a Vega Lite spec. I recently tried a time series visualisation, and it seems that date arrays don't flatten/parse correctly.

The [time series spec](https://vega.github.io/editor/#/gist/71f87fe574c403ad345936849d284aa5/spx-time-series.json) is in a gist on the vega editor, along with a similar pattern [plotting sin and cos](https://vega.github.io/editor/#/gist/8adf8b22000332415dc00cfeccbe2a0f/spec.json) that uses flatten without a problem.

As near as I can tell, the spx time series _should_ work with this transform, and it does work if I [flatten the data myself](https://gist.githubusercontent.com/nathanvy/fd5d73263de59e5be68557207b48867d/raw/9c7fd4969665cb314a89f2f663302b1749b8c09c/spx.csv). I've tried every combination of type specification, timeUnit, etc.. It does work if the transform specifically calculates a date, e.g.

```
"transform": [
    {"flatten": ["spxdate", "open", "high", "low", "close"]},
    {"calculate": "toDate(datum.spxdate)", "as": "new"}
```
which does suggest a problem in date parsing and the flatten transform.

**Comment by snunez1** [comment]
Why do floats parse then? This seems to be a problem only with floats.

**Comment by domoritz** [comment]
I suspect JavaScript parses them implicitly somewhere in Vega. A simple + does that. Date parsing is more involved.
