### ISSUE TITLE
Add “Unit” so we automatically append units to axis & legend title.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#817]
In an attempt to make axis title nicer, maybe we add `fieldDef.unit` or allow describing unit in the schema once we support it (#512).  

For example,  if `fieldDef.unit` is `’$’` for mean of `’cost`’,   the axis title could be `’MEAN(cost) (in $)’`.

**Comment by ayush29feb** [comment]
@kanitw is this what you want to?
![image](https://cloud.githubusercontent.com/assets/8674376/12534195/d307ad12-c202-11e5-923e-ba41212588bf.png)

**Comment by domoritz** [comment]
We already use a similar syntax for aggregation functions. I think there are two options here. One is to write "Year in years" and the other is to show the unit with the data on the axis (acceptable for short units such as $).

**Comment by kanitw** [comment]
Good question! Here is what I think:

- `unit` as part of a field can be considered equivalent to having `unit` included from the schema.
- We could introduce `showUnit` as a property to axis and have these possible values: `'none'`, `'title'` (Showing "Year in years" for the axis title), `'label-prefix'` (Showing $100), 'label-suffix` ('Show 100 kg).

@domoritz -- what do you think?

**Comment by domoritz** [comment]
Sounds reasonable.

**Comment by kanitw** [comment]
Cool.  To summarize, 

- [ ] add `unit` to `fieldDef` (interface & schema)
- [ ] add `showUnit` as enum to `axis` (interface & schema).  This should be an enum with four values above.  The default should be `'title'` IMHO.  See `fieldDef.schema.ts`'s `type` for an example of how we declare enum and see `config.schema.ts` for how to declare default. 
   - [ ] For `'title'` case, modify  `model.fieldTitle()`  
   - [ ] For `label-prefix/suffix`, need to modify `axis.ts`'s  `properties.labels`.  Probably need to use output's `text`'s `template` property.

**Comment by ayush29feb** [comment]
I am a little confused why we have the `showUnit` in `fieldDef.axis` and `unit` in `fieldDef`
```js
"encoding": {
    "y": {
      "field": "b2",
      "type": "quantitative",
      "unit": "$",
      "axis": {"showUnit": "label-prefix"}
    },
    "x": {"field": "a","type": "ordinal"}
  }
```

it seems a little weird to define that the `unit` would be in `title` inside `axis`

**Comment by ayush29feb** [comment]
If we plan to procced as @kanitw suggested, I am having some trouble accessing `axis.showUnit` in `fieldDef.title` method.

**Comment by kanitw** [comment]
Instead of calling `fieldDef.title` directly you can either make a new `axis.title()`  or pass unit as a parameter to `fieldDef.title`.  (Pick one that seems more appropriate – if you're unsure, let me know -- I can take a closer look.)

**Comment by kanitw** [comment]
Note: An early attempt of this was in #1301.

**Comment by kanitw** [comment]
It's easy enough to use title/format to do this, so let's close this.
