### ISSUE TITLE
"Join our Slack channel" link in Vega Editor "is no longer active"

### ISSUE THREAD

**Issue by bbkane** [vega/vega-lite#8171]
Clicking the "Help" button in the [Vega Editor](https://vega.github.io/editor/#/edited):

![image](https://user-images.githubusercontent.com/6081085/169155760-55af25e7-bf2d-4673-aab5-60b90a2ea9eb.png)

 has a ["Join our Slack Channel" link](https://bit.ly/join-vega-slack) underneath "Send us your feedback". 

![image](https://user-images.githubusercontent.com/6081085/169155784-ad40e252-81d6-4154-bbc1-01e9b5270201.png)

This link shows the following message:

![image](https://user-images.githubusercontent.com/6081085/169155556-aac6f296-3cb3-4f92-9c02-b42e1d80da45.png)

Is it possible to update the link so anyone can join the Vega Slack?

**Comment by domoritz** [comment]
Thank you. I fixed the links in the editor and the website.
