### ISSUE TITLE
heatmap is much less dense in color than it used to be

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#822]
https://gist.github.com/jowens/04e37346513ac9b8570e

![vega_scaffold](https://cloud.githubusercontent.com/assets/976970/11540816/c5b40f0e-98e3-11e5-8a71-e9365c80c48d.png)

For a heatmap, all that extra padding does little good; I think you'd like much more color than white space. Previous VL builds were mostly color, not so much white space. Now it's much more whitespacey.

**Comment by kanitw** [comment]
@domoritz I think I’ll auto set ROW and COLUMN’s padding to 0 and hide their grid if Y and X are not mapped respectively.
