### ISSUE TITLE
Parameter usage in compound charts

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8230]
_Goal_: Introduce parameters in Altair to get the Altair-repo ready for VL5.
This issue is a combination of the findings of [#7812](https://github.com/vega/vega-lite/issues/7812) and [#7854](https://github.com/vega/vega-lite/issues/7854) and https://github.com/vega/vega-lite/issues/5758#issuecomment-1148085715.

In compound charts, one can define parameters at the top-level or on the nested charts.

Currently it depend on the chart if one should define parameters at the top-level or define the parameter for each nested chart.

Is there any design philosophy that one can stick to when deciding where the parameters in compound charts should be placed?

- `strategy A`: _define parameters at top-level_.
- `strategy B`: _define parameters on nested chart_.

The following spec-examples can be summarized as follow
|           | `strategy A` | `strategy B` |
|-----------|------------|------------|
| example 1 | OK         | ERROR      |
| example 2 | ERROR      | OK         |

* * *

_Example 1_
Given the following example, a layered tick chart with a rule with a range slider as parameter

1. `strategy A` (define parameters at top-level) works: 
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEDiQAnJAghoA2qGV64aEAGUAMgEkAIgFEASupBMaygCZpQnnAyYFrrKZOYayAAeaGIyEZ5ocSAQmHA4aACMAL4axEiCDOaokmJZALoagkgAnnDaRqBeSJgoqKAM2oIWTS0EUDoQCkqqOSDI2gDWFpg0UFMacMpQbF6eZL4g0W0gAGY0cII+6ACyNIJwEAD6OHWXAOL5gipumNU3FgCODEjKMy0zpBAWWBakazVaoDyBQuDXKo3GU22r3e6G0DHObggNAAXkUAMyjRbLVahDZbMGYBgIDZwSI4eroGwOFxAjTIoogL4-P7NGiA4FwoA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "params": [
    {
      "name": "SLIDER",
      "bind": {"input": "range", "max": 50, "min": 0, "step": 1},
      "value": 25
    }
  ],
  "layer": [
    {
      "data": {"url": "data/cars.json"},
      "mark": "tick",
      "encoding": {"x": {"field": "Miles_per_Gallon", "type": "quantitative"}}
    },
    {
      "data": {"values": [{}]},
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": {"expr": "SLIDER"}, "type": "quantitative"}}
    }
  ]
}
```
2. `strategy B` (define parameters on nested chart) does **not** work:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEIKQBPOACc0AbVAATJJhSpQDPYLQgzFglCR6ICpaoC+G5HoDW9pg0UIEacMpQbCY0ymRooAAeCSAAZjRwgib2ALI0gnAQAPo4+kUA4kiCgirqIJjapfYAjgxIysEWwaQgXn1qoDiuSAgQRqDKI3D2AMoAMgCSACIAogBKdUyx2VYgsTgMmPZ67WTTvkjJqGIyvrFotyAQmHA4aACMPiDEVQzTqJIxF4ALoaRyWUA-QR-MaoYwgr5+QK7BpNdB6BgFOoQGgAL3+AGYvhEojE4ikrqZzAwECk4IkcAZ0PNlutehpUf8QK12p1zDQen0EUA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "layer": [
    {
      "data": {"url": "data/cars.json"},
      "mark": "tick",
      "encoding": {"x": {"field": "Miles_per_Gallon", "type": "quantitative"}}
    },
    {
      "params": [
        {
          "name": "SLIDER",
          "bind": {"input": "range", "max": 50, "min": 0, "step": 1},
          "value": 25
        }
      ],
      "data": {"values": [{}]},
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": {"expr": "SLIDER"}, "type": "quantitative"}}
    }
  ]
}
```

> ```cmd
> [Error] Unrecognized signal name: "SLIDER"
> ```

* * *

_Example 2_
In the following example, a layered point chart with a rule including a highlight parameter, the behavior is opposite:

1. `strategy A` (define parameters at top-level) does **not** work:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEABMkmFKlAMAToLRadSAlCSGICpaoC+GnNaQIIaANqhlbuKYAJAEkAcQCAGVCAgBV1EAg4QTgoTDRQTABPHH90HDYaZVSNKCTrUwQ2BgTKopAVcsrq0kMQBwcAXQ1BJAy4FtRvEGRDAGtTPILauGUoNk0CsjSQAA8lgDMaRM1TAFkaJIgAfWzDQ5CkQUF6jUzs0wBHBiRCuh0aUlaNCExDNhGc0CzZTzTDsVT6EDEC4MHIgJjdKBjZyuBCBKKRMKxDSIHCZNBrC4JJyQ6GwgDEAGYAJwAdgAbABBABirTaalAwzGENusMMDCScQgNAAXjkKcTprN5spFhDVhDtJgGKjUGIbllYY9nqDdKCPm0Og4gA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {"url": "data/cars.json"},
  "params": [
    {
      "name": "HIGHLIGHT",
      "select": {"type": "point", "clear": "mouseout", "on": "mouseover"}
    }
  ],
  "layer": [
    {
      "mark": "point",
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "HIGHLIGHT", "empty": false},
          "value": "#3976AF"
        }
      }
    },
    {
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": 5, "type": "quantitative"}}
    }
  ]
}
```

> ```cmd
> [Error] Duplicate signal name: "HIGHLIGHT_tuple"
> ```

2. `strategy B` (define parameters on nested chart) works:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEABMkmFKlAMAToLRadSAlCSGICpaoC+GwUgCecQ2gDaoHNaQIEN6gygFwpgASAJIA4hEAMrERACrqIBBwgnBQmGigmK444eg4bDTKuRpQWdamCGwMGQ2VICp1DU2kng4OALoayIYA1qal5S1wylBsmuVkeSAAHgsAZjSZmqYAsjRZEAD6RYb7MUiCgm0aBUWmAI4MSBV0OjSkIE7pmIZsQ8Wg08pZph2Kp9CBiGcGMUQEwXFARho-IYApEkok4qkNIgcAU0CszhkPhDBFDTABiADMAE4AOwANgAggAxd49NSgQYjMHXaGGBhZNIQGgAL2KFI+k2ms2U8zByzB2kwDAQaDEV0K0Puj2BumBbx6fQcQA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {"url": "data/cars.json"},
  "layer": [
    {
      "params": [
        {
          "name": "HIGHLIGHT",
          "select": {"type": "point", "clear": "mouseout", "on": "mouseover"}
        }
      ],
      "mark": "point",
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "HIGHLIGHT", "empty": false},
          "value": "#3976AF"
        }
      }
    },
    {
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": 5, "type": "quantitative"}}
    }
  ]
}
```
3. `strategy B` also works when the highlight `param` is defined within the 2nd layered chart where no `params` are used:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEABMkmFKlAMAToLRadSAlCSGICpaoC+GwUgCecQ2gDaoZIYDWpjhsNMqY6iBwylBsmqFkaKAAHokgAGY0cIKapgCyNIJwEAD6OB7FAOJIgoIqEZiuZaYAjgxIYXQ6NKQgTiAQmIZs-nCpMcpxmOyq+iDE1Qyj6EwuUIEaONZICKYAEgCSFbsAMoe7ACoRiDgNaGnVEHB984KLpgDEAMwAnADsAGwAQQAYr0HE5QJtDNsIN5QMptksQAcjqcjpcNI9ClBwrMGk10MFQuENFBCtZTAg2AxHtSSSA6ugqTS4GxSJ5wQBdDR+QJ4xpIwwMQoRCA0ABeS0+fSiMTiygSsxSs20mAYO1QYg0+KRrXaU10Ux64IcnIcQA)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {"url": "data/cars.json"},
  "layer": [
    {
      "mark": "point",
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "HIGHLIGHT", "empty": false},
          "value": "#3976AF"
        }
      }
    },
    {
      "params": [
        {
          "name": "HIGHLIGHT",
          "select": {"type": "point", "clear": "mouseout", "on": "mouseover"}
        }
      ],
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": 5, "type": "quantitative"}}
    }
  ]
}
```
Hopefully this can be discussed a bit before introducing `params` in Altair, since this behaviour will surely lead to issues which are difficult to comprehend.

**Comment by PBI-David** [comment]
Is https://github.com/vega/vega-lite/issues/8168 also related?

**Comment by domoritz** [comment]
@arvind @kanitw do you remember what we decided about where params can be defined? IIRC, we said that params should be hoisted and so they are not scoped but I don't remember whether we maybe even said that they can only be defined at the top level.

**Comment by ChristopherDavisUCI** [comment]
I remember coming across this section in the code and wondering if it was related to the discrepancies @mattijn mentions above:
https://github.com/vega/vega-lite/blob/5bdcc3affbd9cd4ed17deb0db942ae7aebb9aa7a/src/parameter.ts#L30-L35

It seems like variable parameters and selection parameters are handled differently, but I admit I've never used TypeScript so I don't have a good understanding of the code.

To me it makes sense that one would want to be able to define a selection parameter that can only make selections on some of the sub-charts.

**Comment by arvind** [comment]
I need to fully page in our thinking with Vega-Lite 5. But, off the top of my head, and skimming the type signatures for `GenericUnitSpec` and `TopLevelProperties`, selections should be able to be defined both within individual views as well as the top-level. I believe the error documented here is with layered specs specifically (which was something @mattijn had previously caught in #7812 as well, thanks @mattijn!). 

I'll look to get the bug resolved shortly. Sorry about the delay.

**Comment by arvind** [comment]
Continuing to page things in and, actually, I might be wrong: the difference is between `VariableParameter` (example 1, `SLIDER`) and `SelectionParameter` (example 2, `HIGHLIGHT`). VariableParameters are only parsed and assembled when they appear at the top-level. (So, it might be a bug that `GenericUnitSpec` allows them to be defined there as well? I'm not sure, I'd need to think it through...)

 SelectionParameters necessarily need some view context for direct manipulation. If they're defined within views, that happens implicitly but, if they're defined at the top-level, they need a `views` property specified which can either be a complete name of a view or a partial path through the view tree. So, for example 2 to work with strategy A, we'd need to update the spec like so:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "data": {"url": "data/cars.json"},
  "params": [
    {
      "name": "HIGHLIGHT",
      "select": {"type": "point", "clear": "mouseout", "on": "mouseover"},
      "views": ["layer_0"]
    }
  ],
  "layer": [
    {
      "name": "layer_0",
      "mark": "point",
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "stroke": {
          "condition": {"value": "black", "param": "HIGHLIGHT", "empty": false},
          "value": "#3976AF"
        }
      }
    },
    {
      "mark": {"type": "rule", "size": 3},
      "encoding": {"x": {"datum": 5, "type": "quantitative"}}
    }
  ]
}
```

**Comment by mattijn** [comment]
Thanks @arvind for your time and reply! 
It would be interesting to see if we can adopt this suggested approach in Altair:

> So, I think a consistent approach Altair can take is to always hoist parameter definitions to the top-level. If the parameter is a selection, then add a corresponding views property and name the constituent view.

I tried it with the spec from this https://github.com/altair-viz/altair/pull/2528#issuecomment-992989438, which more or less has it all in a compact matter, and it worked it out well! Even with two params equally named (`hover`) but with slightly different selection behavior. Pretty neat that this works already!
 
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9ulMAEMANpjwgARgqh0ACgrp0SCAJJQomAE4ouGrbv2GoCAPKlCl6wDo2AdmmyQAAcFCwUAW0oUAG1QKHDVZBB4JSUAfToIMIUSEG51Ejo1EkC3FBBKTBUwcW4IQOJoSOQoqK4pNgBdTlbOADYODq6QOLCEpLgUgAIMrJyAtGVSBJ7+ztlY+LLGUSVRGvLKzGq1QgBPQLHAiBJ9sBUQsrCBTAp96EfniDQPeaxsJqiPCgikIqQAjCAOuthptEowvh45IdjqgQGcLmUrjdciBMMCII4EACQAAPSHccwhTCUcTIQgWJa1KAfKgvb5WX44YkEEGpNipJQKU6WcGQ6EjMbw9k4ipVWmgdGXa5EHF4yCE4lkobvRJPVkIjncDBc6JA3kQqFDHkKWkxECC4VWZqgLIWADWJ3OY125hxWJVdIZmACaoJRjUkCUECdoHglUKiUopzC6ggShxirKUEyJGUIACZNRcaUCZAdBtqm4xFGAFUoHBaSBhQ8q16szm4umAqc1AoEAgLJgEBXHpgtDji6XAhY4GBK2i24kAI6kLTEQg2uDffP+TgbUZla2g-kOkUQ7iuj2ozOJBkqDMQNPEQIoelLEP4wkRtPR7-aBtwDq6CLGM6iCmAHrcMEoRhFsBqqmE9Q9sgMDKBU8wgWU9JaJQ0F4uIBZqJOZTlu4GZwLW9aNs2VithiiTZmEuZdv4QyMCICBiCgYIAKxsOKsJmjaooXiEV4KouICDsccj0hAbqYLQDDMMgYKeAATFWj5KM+r5Bh+6rhkWEzpqifYDkOI66mOzLcMRiTTrO87yMoCSgDM2TMqimAktOZTJGkHlzAEN4gCua4Npu24BDSFjyW5QKGA0XnAUoSxlGBCgQX6IThFsOx7AhSEoKhSjoUamHIGQKSEcZ8YkSOVYUZgdYNmUNEZpJ7iIdGebdkRWAlmUSYpmmnX0cMHZ9ax3CRqQYRQE0YLcKRChqKQFimSAYiEIElDIAA9AdYB0FAngAFaUHQlRbhYnjmIQB1QIEYQHd8w4ALSrRUhCUAAAmganqQAnN4B2rQdNIQBBlCeGAlBoPm3CDpQabbqiLn3qika-okBSYBc2j4ROJllPjhPXSq3CFuUjBUoUu4gAAJPI7FZFshC7ftR3vQongIA2jCkOoniAZDYBswob2WR9uzuG9PEad4F2o8y0hAA)

I'm closing this issue as being resolved

**Comment by ChristopherDavisUCI** [comment]
This all looks very promising!  I haven't totally wrapped my head around it yet.  As an example, can I ask, how would we lift the parameter here to the top level:
https://vega.github.io/vega-lite/examples/interactive_layered_crossfilter.html
I have gotten the strategy to work in a few examples, but what I tried in this example didn't work.

**Comment by mattijn** [comment]
I fear that we will need some brainpower from @arvind again, opened a new issue here: https://github.com/vega/vega-lite/issues/8348
