### ISSUE TITLE
Axis position incorrect for small multiples with one multiple

### ISSUE THREAD

**Issue by depstein** [vega/vega-lite#828]
The axis looks funny when I create a small multiples graph with a single multiple. It's a weird case, but I don't know there's only one multiple when I make the graph :-)

Possibly might be related to fixing cell height

<img width="366" alt="screenshot 2015-12-03 21 57 04" src="https://cloud.githubusercontent.com/assets/2422190/11583067/a453cc50-9a0a-11e5-8fb0-ff6d7c840b75.png">

Can't post data publicly, will send it privately.

**Comment by kanitw** [comment]
@depstein  Fixed in #880

**Comment by depstein** [comment]
Thanks!
