### ISSUE TITLE
Years in X axis clipped in example

### ISSUE THREAD

**Issue by snunez1** [vega/vega-lite#8281]
I've recreated the [bubble plot example](https://vega.github.io/vega-lite/examples/circle_natural_disasters.html), and noticed that the years on the x-axis are 'clipped', e.g. .990 .010, etc. 

![visualization](https://user-images.githubusercontent.com/7775472/178993982-507535fa-e104-4fed-be62-6a964550aff6.png)

The [spec](https://vega.github.io/editor/#/gist/c997af29af7eb1c763a8da1fb2635575/spec.json), except for the field names, looks exactly like the example, and the editor shows no errors.

Any ideas?

**Comment by jwoLondon** [comment]
The problem arises because when parsing inline data, `year` is being treated as an integer rather than as a string to be parsed into date format. You can solve it by being explicit about it being temporal with the following added after the data array:

```javascript
,"format": { "parse": { "year": "date:'%Y'"} }
```
