### ISSUE TITLE
Expose `normalizedNumberFormat` for normalized % stack

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#8300]
For normalized stacked charts (like [bar](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICONjgaC17WVJnyAvkszaksiADM22hGgDaoNzSCmHDa+qqYDAiUAJ5wSNoABAC8SQkATAAMWSAOoFBIglDmanBhapGUEHAAHsmpaQkA-AkA5ABiiAVwLQmorQCyXS2KIEgQ+mRwssohOQC6SsjaANZooJjROKXoTPEjmGxsQTQ4aE4McA4gAO40yvRrIBDBp6gAjADsV1NQbMo0sjIj2ijyQZDI2j4wX0EEiIwCcEEyn0W1MglKjjo6JRpmKmCsI2eSCgq3Qsk8yGEAC9Sldqo8EUj9GDaUpfoJPAyaIjkehJtNZkpoF1Hs5AdsfCAAMQANg+YjeAE4AMwjKX5AAcGplbxAczsBrsQA)), we automatically generate tooltips that calculates ratio / %.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/111269/179632912-9e509c03-62ff-4594-ab9e-0b06514b8a93.png">

However, we haven't applied any % formatting to this % tooltip yet. 

We should

1) Expose `config.normalizedNumberFormat` (or `percentFormat` or sth) for setting formatter for this % tooltip
  - Probably also add `config.normalizedNumberFormatType` so this `config.normalizedNumberFormat` has its own format type. 
2) Set the default `config.normalizedNumberFormat` (`defaultConfig` in `config.ts`) ---  probably  to`.2%`?

For testing, perhaps:

1) modify `stacked_bar_normalize.vl.json` to include `tooltip: true` in mark to test the default format
and 
2) add `stacked_bar_normalize_custom_format.vl.json` to test customized format in the config.

**Comment by kanitw** [comment]
cc: @domoritz @jheer @arvind 

Any opinion for the config name?

At first I thought `percentFormat/percentNumberFormat`, but then the feature is only trigger via "normalize" stack and technically users don't really need to do `%` as the formatter, so `config.normalizedNumberFormat` might best match what the feature is for.

**Comment by domoritz** [comment]
I like `normalizedNumberFormat`.

**Comment by lsh** [comment]
Resolved by #8307
