### ISSUE TITLE
Infinite extent for field with dot in field name

### ISSUE THREAD

**Issue by rgaiacs** [vega/vega-lite#8323]
In R, it is popular to use a dot (`.`) as replacement for a white space (` `) in the column/field name. I tried to load a CSV exported from R into Vega and I got "Infinite extent for field".

# Minimal Working Example

This is an adaptation from https://vega.github.io/vega-lite/docs/data.html#inline where the name of the column/field where changed: `a` to `a.x` and `b` to `b.y`.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a.x": "A", "b.y": 28},
      {"a.x": "B", "b.y": 55},
      {"a.x": "C", "b.yb": 43},
      {"a.x": "D", "b.y": 91},
      {"a.x": "E", "b.y": 81},
      {"a.x": "F", "b.y": 53},
      {"a.x": "G", "b.y": 19},
      {"a.x": "H", "b.y": 87},
      {"a.x": "I", "b.y": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a.x", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b.y", "type": "quantitative"}
  }
}
```

# Observed Output

```
[Warning] Infinite extent for field "b.y_start": [Infinity, -Infinity]
[Warning] Infinite extent for field "b.y_end": [Infinity, -Infinity]
```

![screencapture-vega-github-io-editor-2022-07-27-13_49_18](https://user-images.githubusercontent.com/1506457/181171508-834d0c08-c96f-4cab-8d20-658ca6fa8fff.png)

# Expected Output

Finite start and end for fields.

![screencapture-vega-github-io-editor-2022-07-27-13_55_25](https://user-images.githubusercontent.com/1506457/181171836-2b5ddce8-5c51-42b2-a670-cb3e2e6c7bd0.png)

**Comment by PBI-David** [comment]
Your sample data contains a typo on line 8 and should be b.y instead of b.yb. Also, the editor gives a pretty clear hint on how to access fields with dots if you hover over the property.


![image](https://user-images.githubusercontent.com/86846675/181180498-b4053eab-ed2f-451b-b9d6-cf59fcc5deef.png)

As a result, the example works fine and I think this can be closed.

![image](https://user-images.githubusercontent.com/86846675/181180689-7370a401-1ac2-43ed-b6c0-568ef15fb331.png)


```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a.x": "A", "b.y": 28},
      {"a.x": "B", "b.y": 55},
      {"a.x": "C", "b.y": 43},
      {"a.x": "D", "b.y": 91},
      {"a.x": "E", "b.y": 81},
      {"a.x": "F", "b.y": 53},
      {"a.x": "G", "b.y": 19},
      {"a.x": "H", "b.y": 87},
      {"a.x": "I", "b.y": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a\\.x", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b\\.y", "type": "quantitative"}
  }
}
```

**Comment by rgaiacs** [comment]
Thanks!
