### ISSUE TITLE
Format CI does not work on forked repositories

### ISSUE THREAD

**Issue by lsh** [vega/vega-lite#8326]
It seems that forked repositories do not work even when using the [GitHub Secret as mentioned in the docs](https://github.com/vega/vega-lite/blob/next/.github/PULL_REQUEST_TEMPLATE.md). This causes friction with contribution PRs as seen in #8282, #8302, and #8303.

**Comment by lsh** [comment]
cc @domoritz

**Comment by domoritz** [comment]
Hmm, I didn't test this properly it seems. Did you look into how we may be able to fix it?

**Comment by lsh** [comment]
@jonmmease suggested adding `pull_request` to `checks.yml` as a possible solution.

**Comment by domoritz** [comment]
Iirc that caused us to have to builds for internal prs. But things may have changed.

**Comment by domoritz** [comment]
@lsh are you looking into this issue?

**Comment by lsh** [comment]
I haven't had a chance to take a crack at it but I can probably take a look tomorrow

**Comment by domoritz** [comment]
Ah I remember the difficulty. We need to push to the branch after our check script and win a pull request trigger the target branch is not the right branch. So keep that in mind as you experiment.
