### ISSUE TITLE
Boxplot disappear when there is one value per group

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#8338]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "A", "b": 30}, {"a": "B", "b": 55}
    ]
  },
  "mark": "boxplot",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}

```
<img width="91" alt="image" src="https://user-images.githubusercontent.com/111269/182496476-6115417a-8e60-44a2-b4c4-1006aa901cf6.png">

Nothing shows up for B. 

This is similiar to https://github.com/vega/vega-lite/issues/3488, but is the same problem for boxplot.

**Comment by joelostblom** [comment]
There is a somewhat similar issue in https://github.com/vega/vega-lite/issues/8126 where the median boxplot lines disappears with many identical values, just in case anything here could be applied to fix that too.
