### ISSUE TITLE
Gallery broken in deployment broken because of symlinks

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#840]

**Comment by kanitw** [comment]
Can you explain how it is broken?  I pulled the latest master and it's working for me.

**Comment by domoritz** [comment]
https://vega.github.io/vega-lite/gallery.html

**Comment by kanitw** [comment]
Ok, changing the title to "fix deploy script" -- it's still not in a good shape.  I publish by hand today.

**Comment by kanitw** [comment]
Duplicate of #781

**Comment by domoritz** [comment]
Okay, can you close once you have published by hand?
