### ISSUE TITLE
chart with repeat and a defined name disables the independency of the repeated channel (eg y-axis)

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8446]
When a `name` is defined within a `layer` within a `repeat` `spec` as such:
```json 
 "repeat": ["temp_max", "precipitation", "wind"],
  "spec": {
    "layer": [
      {
        "name": "FOO",
```
Than the axis of the chart get confused, see the following screenshot:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/5186265/193812425-1cfd2549-ff79-41dd-9dce-e9a97e82816d.png">
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAdzhr42ylAjEQAXyXa4OM5jQBtEJkQ4A+sgAPRRAcJygaHDo1dnklYxpZZRAAXSUIFyg0UEEkAE84bQ9QWSQEOH0AMQB5KuDkbQBrLK9cl31w7ShBcocQOFkoNmUEsmagzRAAMxo4QST0VW9gzBoygFVZOn0EOXp7JVzm6dn50CcXNX1z132QJDIyJwol9DKkeV7BwTZCieO5-TfKDROS3CA0ABe5QmxCQggY0LEAAY7KiFKB6k0JphWtCQMJZD0lP1BsNZKMJuNQP95gYlkoVutNm5XrsYLdDn8ZgCJtdLug+W5evdHnwXiA3h8lF8fkdubSgSCPqjkqigA)

VL-spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {"url": "data/weather.csv"},
  "repeat": ["temp_max", "precipitation", "wind"],
  "spec": {
    "layer": [
      {
        "name": "FOO",
        "mark": {"type": "circle"},
        "encoding": {
          "x": {"field": "date", "timeUnit": "month"},
          "y": {"field": {"repeat": "repeat"}, "aggregate": "mean"},
          "color": {"field": "location"},
          "size": {"value": 50}
        }
      },
      {
        "mark": {"type": "line"},
        "encoding": {
          "x": {"field": "date", "timeUnit": "month"},
          "y": {"field": {"repeat": "repeat"}, "aggregate": "mean"},
          "color": {"field": "location"}
        }
      }
    ]
  }
}
```
When removing `"name": "FOO"` of the spec; the circles will be correctly displayed on the axis again:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/5186265/193812924-77c6a7bd-91c4-43dd-b428-24ce26ecf0ab.png">

**Comment by mattijn** [comment]
Hopefully the cause of https://github.com/vega/vega-lite/issues/8348🙏

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, my best guess is that for your example, in the code [here](https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/core.ts#L160-L186) `childSpec` is a layer spec in which one of the layers is named.  If the full layer spec itself had a name, I think [these lines](https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/core.ts#L170-L177) would correctly update that name.  But in your case, it's one of the constituent layers that has a name, and I think that name is getting copied without any special prefix, so the same name is showing up three times in the final result.  Maybe something is going wrong in the creation of `child` here:
https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/core.ts#L179

There is already some special logic for dealing with layers [here](https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/core.ts#L97); see especially [this line](https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/src/normalize/core.ts#L130).  But if I understand right, that code only gets called if we have something like `"repeat": {"layer": ...}`, unlike your case, where the spec is a layer chart.

Does that give you any ideas?

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, here is a first attempt at addressing this issue of the same name showing up multiple times: https://github.com/vega/vega-lite/commit/0ab291a413c58728212c2a9570afbb6b99185454 

(It's the same as I posted on #8348.)

**Comment by domoritz** [comment]
How critical is this issue? It seems weird to name a chart inside a repeat since the name will not be predictable anyway. Can you just remove the name from the chart?

**Comment by mattijn** [comment]
Its eventually to get this spec working, from here: https://github.com/vega/vega-lite/issues/8348#issuecomment-1280162030:
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAM2FksEfgCYA1lJnylxttuSY0oHEm0Q4Hg5h+6KqBIAC+EUpe2kgIEGgA2qCysUEgTNoMEDCKIL6CcFDumiCYAJ44aTSygdrESHpKcLJQbMrVZPGoCSAAHiAAumFKxDRwAO5dCT2wNILKAPoLrYIMCLIL7RDqLX5KgkhlcNoLAAyDCjMwc4vLbKvrm3AHZbkvx2cXVzdLK2sbmBoCD2IHeJ3OAyGAyUmBisggzlciVAUAaUAYB1C6BgbB0EAAFCE1pQQnAAJS5JBdUpAvxhaEgbRwSpqfx-daJFQ0bZIXa5ZTPQ65QHAwbDPKVKD+cY0ZT0NAARjEpyU8Bo5mKCtOKtBh2OyJAKVF6DBnyUyG0Nn0TG8uWarXasjI-n6JWMY3m-iZLOKIHZ8nFTGq-mQvSD8LQVlOkRArxKSDIZCZFCxftxNXCShWLn89VWaQAxAA2EvhSKgWG8hEuBAG92CWr+aKxa2ZbJlhkWq3oG3aO0tNodF3+d3PZRe5lwVnof2Z9LBkqh8NdKMxuOgBNJvip1oMDPi7N9kp5hhpFy8sh0iJDMJAA

The spec renders, but once you start interacting, e.g. start with creating an interval at the last chart, x-axis time (binned), and then delay (binned) and then distance (binned).
Even though this type of chart is maybe not very commin in practice, it is one of the _selling-charts_ of vega-lite.

The layer name is predictable as it is defined in altair code.

**Comment by domoritz** [comment]
> The layer name is predictable as it is defined in Altair code.

What do you mean by this? I don't think were (Vega-Lite) make guarantees about generated names being consistent across versions.

**Comment by mattijn** [comment]
Our current approach of providing interactivity using params for compound charts is based on this https://github.com/vega/vega-lite/issues/8230#issuecomment-1179213186:

> `VariableParameters` are only parsed and assembled when they appear at the top-level. 
> 
>`SelectionParameters` necessarily need some `view` context for direct manipulation. If they're defined within views, that happens implicitly but, if they're defined at the top-level, they need a `views` property specified which can either be a complete name of a view or a partial path through the view tree. 
> 
> So, I think a consistent approach Altair can take is to always hoist parameter definitions to the top-level. If the parameter is a selection, then add a corresponding `views` property and name the constituent view.
> 
> Example: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEABMkmFKlAMAToLRadSAlCSGICpaoC+GnNaQIIaANqhlbuKYAJAEkAcQCAGVCAgBV1EAg4QTgoTDRQTABPHH90HDYaZVSNKCTrUwQ2BgTKopAVcsrq0kMQJxBiGjgAdw9UTxBBJAy4QwB9GRAAXQdJjUHhlr6fP1N5kfG45EMAa1M8gtq4ZSg2TQKyNJAAD0uAM07BTVMAWRokiFHssZCkQUF6jSZbKmACODCQhToOhopFaGggmEMbG2OVAJ2UZ0w7FU+navwYORATEGUF2zlcCECUUiYViGkQOEyaFuvwSbWI+MJAGIAMwATgA7AA2ACCADFWg4nKAtrtcUDCYYGEk4hAaAAvHI8tpHE5nZQXXE3XHaTAMSmoMSArKEsEQrG6LGwqUzBxAA)

Using this approach we almost got all examples working. Except the _layered repeat charts including interactivity_. But just before the _layered repeat charts + interactivity_, are the _repeat charts + interactivity_. This we still got working by 
1. Defining a `name` in the `spec`:
```json
  "spec": {
    "name": "view_1",
```
2. Checking what is being repeated.
```json
  "repeat": {
    "column": ["sepalLength", "sepalWidth"],
    "row": ["petalLength", "petalWidth"]
  },
```
3. Construct the `views` property in the `params`:
```json
  "params": [
    {
      "name": "param_1",
      "select": {"type": "interval", "encodings": ["x", "y"]},
      "bind": "scales",
      "views": [
        "view_1child__row_petalLengthcolumn_sepalLength",
        "view_1child__row_petalLengthcolumn_sepalWidth",
        "view_1child__row_petalWidthcolumn_sepalLength",
        "view_1child__row_petalWidthcolumn_sepalWidth"
      ]
    }
  ]
```
So here it is `<view-name>child__<repeat-row>_<data-field><repeat-column>_<data-field>`

I took the code snippets from the following example specification that we used during development: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO4AnTAAdMAQ3GoeAG1IBbKCgDaISouUaAMpigImIbsYWnaDZgF05EXMkNLCpi1ZtuH0d6GxcZIyUwPBA6VWUY0lkNFBAxQgVKZAB6bLA6KAA6ACtKOkwNODRZQqhMQmyoBW1stEwEZQBaON9jQkoAATQARkKAJgBOQrZsnuVsuFk4ShLKaBAI7WVZAGsYwgBPJVSFCBJxCMtIOhIkdUgNCFkY+Aq6VMoorEpbEEPj5AgKAQbQkUwbbgADxeWA073U8iUqlSDx0egi-0wqQAjqRlEQ4L5iG0ISADjC3jFESo1CBZB5SZicXiCUSqljpNxGCIEGIUMN2NwoMptFjARgcAB9Ya-bChZjIYYANjYEQcshFPy8oGFopO2xF0t+xg0mDAalATMB50wsjQ4O4VwgNysWsM0O45PC3AARiR4UYwKZMD9uBLsG6QOHpWBGHA4ZLJfTsJLguZLNZGKjdJL7H4M4Eo1gU8NY-G6Ink6n6vmAlmIFoc3mNE5C9HS3GE0mPNXfC35dmoLmTOm67922Wu1W063642h83ZyBwm4QAASSixzBbVLpTI5VrtZSFBCExikH2FOAQbKb7lbQ8dTqVQiYVoAVnG01W60kQA), see related https://github.com/altair-viz/altair/pull/2684#issuecomment-1287596272.

Regarding the _layered repeat charts + interactivity_, I don't think we implemented this part yet on the Altair side, see https://github.com/altair-viz/altair/issues/2849, since it is also still halted here.

All above is implemented in the following section of the Altair codebase.
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L2887-L3062
