### ISSUE TITLE
Grouped issue regarding the `repeat` operator

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8453]
We are making good progress in the Altair repo to get it working with Vega-Lite 5, but it seems we are facing a number of issues regarding the usage of the `repeat` operator. I've filled them separate, but let me bundle them here as well:

- https://github.com/vega/vega-lite/issues/8452
- https://github.com/vega/vega-lite/issues/8446
- https://github.com/vega/vega-lite/issues/8348

Is this something we can expect to be fixed in the Vega-Lite repository? Or do you suggest another approach?

**Comment by ChristopherDavisUCI** [comment]
If just for fun I wanted to try to learn some TypeScript by looking into this issue, do you have a guess of what files or functions I might start with?  It seems like it is an issue specific to `repeat`, so I tried looking at https://github.com/vega/vega-lite/blob/next/src/spec/repeat.ts but it looks like very little is happening in that file.  Another place that stands out to my untrained eye is https://github.com/vega/vega-lite/blob/43d3dee23ccbaae3dad9cf933d7b61928f6869b2/src/parameter.ts#L30 but there I don't see anything specific to `repeat`.

No worries if my question is too imprecise and can't be answered!

**Comment by ChiaLingWeng** [comment]
I think this is fixed in #8733
