### ISSUE TITLE
Version numbers for PR branches are broken

### ISSUE THREAD

**Issue by ZacharyBys** [vega/vega-lite#8471]
Version numbers on the PR branches are lower than the release versions. [This PR](https://github.com/vega/vega-lite/pull/8451)'s branch starts with `5.5.1` but the current release version is `v5.6.0-next.4`. 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/26799659/194951859-d2afbd9a-8210-42e8-a7c0-57cc8981ba4c.png">

**Comment by domoritz** [comment]
Well, 5.6 is not released yet, though, so maybe that's okay... but yes, I am also a bit confused about how auto determines version numbers. I'm going to close this until we see issues in non pre-releases.
