### ISSUE TITLE
"binned" is not working with an ordinal field

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#8476]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {
        "startTime": "0",
        "endTime": "8.33",
        "residency": 20
      },
      {
        "startTime": "8.33",
        "endTime": "12.50",
        "residency": 30
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "startTime",
      "type": "ordinal",
      "bin": "binned"
    },
    "x2": {"field": "endTime"},
    "y": {
      "field": "residency",
      "type": "quantitative"
    }
  }
}
```

With `"bin":"binned"`:
![image](https://user-images.githubusercontent.com/6269456/195463370-5a40e803-49dc-473c-bf55-84c31df67913.png)

Without `"bin":"binned"`:
![image](https://user-images.githubusercontent.com/6269456/195463309-2548acca-4656-4992-a90f-f925682dc576.png)

**Comment by kanitw** [comment]
I think if you have ordinal fields, it's better to not use ranged marks.
It's better to derive a field that shows "0 - 8.33" and just use that field.

**Comment by kanitw** [comment]
Actually, looking at the https://vega.github.io/editor/#/examples/vega-lite/histogram_nonlinear this makes more sense.

**Comment by yhoonkim** [comment]
Yeap the spec was from "histogram_nonlinear" but I trimmed out to be minimal. Thanks for revisiting this!
