### ISSUE TITLE
Add "Release notes" / "What's new" page to documentation

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8522]
Due to the many "next"-suffixed released, I find that it is hard to get an overview of new changes from browsing [the Release page](https://github.com/vega/vega-lite/releases) on GitHub. I usually jump between actual releases by editing the URL manually to avoid paging through too many "next" releasing, but I don't think this is very discoverable and you can search all the release notes easily.

It would be great if Vega-Lite could have one page in the docs that lists all the non-"next" releases so that it is easy to see what is new in each release. I think [pandas does this really well](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.5.1.html) and they also include details and examples for the most notable changes in each major and minor release (as Vega-Lite currently does for major releases), which I find quite helpful. Apologies if this already exists somewhere and I missed it.

**Comment by domoritz** [comment]
What if instead we could not have next releases on GitHub at all?

**Comment by joelostblom** [comment]
Yup that would work too! GitHub has a search box for the release page so in terms of functionality I think it is the same. I thought maybe it would be tedious to go in a delete all the old "next" releases or that the way the release pipeline was set up would potentially make it not as straightforward.

**Comment by joelostblom** [comment]
Just a bump about removing the "next" releases on GitHub. It would make it much easier to go through the release notes and see what is new between versions (recently noticed this when trying to figure out what has been added since 5.2 and whether we should update Altair)

**Comment by domoritz** [comment]
We now have a https://github.com/vega/vega-lite/blob/main/CHANGELOG.md and don't make next releases anymore. We may add next releases back to npm but not GitHub releases.

**Comment by joelostblom** [comment]
That's so great, thank you!
