### ISSUE TITLE
repeat operator with defined width and height does not accept layer

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8523]
This spec [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgTgpgDhCGAuIBcoA2sCeEzINogFUBlAfQHEwB7AZ2pABoQB1SsVAEwHcBLdicqrRABdRgGNKqAK4BbAHZ4QASQCyAEQBCJAEoJucgOYMQ2yvHgQ5JACqUZCShGo69hkQF9G1GGOSge7PAAFsgATAAM4YxBENwGQYhIAIwAzFEg7AiwfiBSbMggCfBQ1EgA9GVi7HIAdABW1Hyo3ABuYDVyEPBlclAyZS0QBrAAtJnwsNRd1AACLUk1oQCcNeFl47BlMpQt3E711JQKniD2YADWBc2dxpYS7PpGKCASqKw547I5kDAIV5jYEDuE4ADxyACN9Mh4GApBBGAAzPYcb7QOCJF6SWTHE4YHKwAwGSDDCwFGRwBSI5HsVG-DHoLA4E7wbjwVAQAoqCkAAkoCO5xG5sDk7G5LDYXF4EG5FBodGBJwAJNQxDF7AUiiVygMhrAagZWUEpOCatxKGUVWrNoNhiNmhYBgBWRarA5HIFAA):
```json
{
  "repeat": {
    "layer": ["US_Gross", "Worldwide_Gross"],
    "column": ["IMDB_Rating", "Rotten_Tomatoes_Rating"]
  },
  "spec": {
    "width": 200,
    "height": 130,
    "data": {
      "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/movies.json"
    },
    "mark": "line",
    "encoding": {
      "color": {"datum": {"repeat": "layer"}},
      "x": {"bin": true, "field": {"repeat": "column"}},
      "y": {
        "aggregate": "mean",
        "field": {"repeat": "layer"},
        "title": "Mean of US and Worldwide Gross"
      }
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
Renders correctly. But officially the `layer` cannot be defined, since the schema does not accept it:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/5186265/202025352-5c7c1f08-a22f-4ea7-8cb0-a42fc056a0b8.png">

Which is problematic for Altair-alike software

**Comment by binste** [comment]
When you remove `height` and `width` from your example then the schema error disappears. In the vl schema, I think a repeat chart is either defined as non-layer or with layer:

```json
"RepeatSpec": {
  "anyOf": [
    {
      "$ref": "#/definitions/NonLayerRepeatSpec"
    },
    {
      "$ref": "#/definitions/LayerRepeatSpec"
    }
  ]
}
```
I'm wondering if this example somehow does not fit both definitions and then shows the error based on the first one which is the added "layer" property which should not be there. Would you know any way in the Vega Editor (or other tool) to learn more about the warnings? It would be great to know which definition it matches.

**Comment by ChristopherDavisUCI** [comment]
This is super helpful @binste!  One thing I noticed is that if you use `import altair.vegalite.v4 as alt` (so that you're using an older Vega-Lite schema), then no errors show up.

I have an idea of trying to use `UnitSpecWithFrame<Field>` instead of (or in addition to) `UnitSpec<Field>`, but so far I haven't gotten it to work.

**Comment by binste** [comment]
Interesting! Just checked the v4 schema and indeed, in there the `UnitSpec` schema still allowed `width` and `height`. In v5 `UnitSpec` now refers to "GenericUnitSpec<Encoding,AnyMark>" which does not allow for those parameters. Maybe this was unintentional when changing the vega-lite schema?

Thank you for trying to rebuild the schema! I can't dedicate enough time right now to get up and running myself with vega-lite but really appreciate that you dig into this :) Hopefully a vega-lite contributor can jump in as well and help out.

**Comment by ChristopherDavisUCI** [comment]
Thanks @binste!  I had another look and think I was able to find one possible solution to this issue in #8676.  The main difference is allowing `UnitSpecWithFrame` to the current possibilities for the `spec` parameter.  If you have any comments on this approach, I'm very happy to hear them!  This is the resulting schema: https://raw.githubusercontent.com/ChristopherDavisUCI/vega-lite/cd/allow-size/build/vega-lite-schema.json

**Comment by mattijn** [comment]
Nope, the `$schema` key only defines which version is used to validate against. It does not defines the VL-version that is used to render the spec.
If no `$schema` key is defined, the spec is not validated. 

Rendering issues are still tracked by error and warning messages.

You'll have to build Vega-Editor linked to your updated Vega-Lite bundle plus new VL-schema. 

I think it is a quite complicated proces before we can test and play with your updated vl-schema. I'm not sure how and if this can be simplified. 

Maybe the editor can have a menu-setting where manually another VL-bundle/schema can be specified.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, thanks for looking at it!  I am able to get your spec in https://github.com/vega/vega-lite/issues/8523#issue-1428283314 to work locally on my computer, but only if I change `v5.2.0` to `v5` (or remove the `$schema` property entirely).  The `layer` property is still underlined if I keep `v5.2.0`.

Here is what it looks like locally with `v5.json`:

<img width="1309" alt="Screenshot 2023-01-30 at 11 41 07 AM" src="https://user-images.githubusercontent.com/82750240/215579295-8c008b58-aa18-4361-a2c6-afae08a68408.png">

Here is what it looks like with `v5.2.0.json`:

<img width="1308" alt="Screenshot 2023-01-30 at 11 44 04 AM" src="https://user-images.githubusercontent.com/82750240/215579480-128b57b3-1014-4cfb-8de6-9c6bce075dd0.png">
