### ISSUE TITLE
Some functionality from later Vega-Lite releases seem to be available in the Vega editor even when specifying older Vega-Lite version

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8581]
The Vega Editor lists the VegaLite version in the bottom right corner: 

![image](https://user-images.githubusercontent.com/4560057/205383867-a553e949-cad4-461f-b967-180494d84e96.png)

However this does not seem to change when providing e.g. `  "$schema": "https://vega.github.io/schema/vega-lite/v5.1.0.json"`.

More confusingly, it seems like some (but not all) functionality from later Vega-Lite releases is available in the Vega-Lite editor even when the version is restricted which led to some confusion in this Altair issue https://github.com/altair-viz/altair/issues/2742 (example specs in that thread)

**Comment by domoritz** [comment]
The version shown by the editor is the version of Vega loaded. Right now, the editor does not load a different version when the spec specifies a different version. 

We track this feature request in https://github.com/vega/editor/issues/336.
