### ISSUE TITLE
White line between stacked bars

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#859]
Looks nice. See  https://csnw.github.io/d3.compose/examples/#/horizontal-stacked-bars

**Comment by kanitw** [comment]
I’m wondering if it’s actually nicer:

![vega_editor](https://cloud.githubusercontent.com/assets/111269/11706405/4febd9da-9ead-11e5-803d-65f92974f7dc.png)

Versus no offset:

![vega_editor](https://cloud.githubusercontent.com/assets/111269/11706408/673ff9cc-9ead-11e5-8de7-f2c64305729f.png)


Also, the d3.compose example doesn’t have consistent space between bars, which makes me wonder if it’s a bug.

![example___d3_compose](https://cloud.githubusercontent.com/assets/111269/11706417/824ecd4c-9ead-11e5-8b9b-ecb601f37cfc.png)

**Comment by domoritz** [comment]
Hmm, also, you have to add a white line to the last bar. That's bad. Let's not do it.
