### ISSUE TITLE
bin bin count not working

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#861]
This is one of the recommended charts in voyager

```json
{
  "mark": "point",
  "encoding": {
    "x": {"bin": true,"field": "Displacement","type": "quantitative"},
    "y": {"bin": true,"field": "Horsepower","type": "quantitative"},
    "size": {
      "field": "*",
      "aggregate": "count",
      "type": "quantitative",
      "displayName": "Number of Records"
    }
  },
  "data": {"url": "data/cars.json"}
}
```

![screen shot 2015-12-08 at 12 12 49](https://cloud.githubusercontent.com/assets/589034/11667173/07cb8eec-9da5-11e5-8098-0c3dee9799e5.png)

**Comment by kanitw** [comment]
Please try to build a custom build of Vega with datalib 1.5.7, I think that would make it work.  If not, feel free to reopen this issue.
