### ISSUE TITLE
obtain the number of points for a regression transform?

### ISSUE THREAD

**Issue by jbloom** [vega/vega-lite#8613]
For a regression transform, it is possible to obtain the r-squared values by setting `params=True` and using the `rSquared` value. Likewise, it is possible to get the correlation coefficients. But is it possible to get the number of data points fit?

**Comment by domoritz** [comment]
The number of points would be the size of the input table, right? You can get that using Vega expressions. I'd have to try to see how easy it is to get the right table from Vega-Lite. Id suggest checking the generated Vega.
