### ISSUE TITLE
CodeSandbox can't render anything beyond vega-lite 5.2.0

### ISSUE THREAD

**Issue by nlarusstone** [vega/vega-lite#8702]
I can't render vega-lite specs in a codesandbox using any version of vega-lite beyond 5.2.0. Here's a minimal repro: https://codesandbox.io/s/shy-dream-fvtzbx?file=/src/Visualization.tsx

I am using react-vega to render the VegaLite spec, but I also tried rendering without that package and couldn't do that either. I also tried forking existing vega-lite code sandboxes (e.g. https://codesandbox.io/s/kind-lederberg-nesbo3) and updating the vega-lite version also broke them.

**Comment by domoritz** [comment]
How do you know that anything beyond 5.2 doesn't run? What's the error?

**Comment by nlarusstone** [comment]
It simply doesn't render. In the console you get: `TypeError: (0 , $csb___util.duplicate) is not a function` and `Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: `.

In that sandbox, if you update the package version to 5.2.0 you can get the chart to render. Changing it back to 5.6.0 will prevent it from rendering

**Comment by domoritz** [comment]
I don't know whether this is an issue with Vega-Lite. This sounds like some bundling issue with the util package that has duplicate in it.

**Comment by domoritz** [comment]
Closing since this doesn't look like a bug with Vega-Lite but happy to follow up here.

**Comment by nlarusstone** [comment]
Sorry for the delay in responding! I don't know exactly where the issue is, but I just wanted to flag it as a potential issue for people who want to provide reproductions (there are other alternatives of course)
