### ISSUE TITLE
Automatically format large numbers instead of removing axis labels

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8718]
Currently, if axis tick labels don't fit, it seems like they are automatically removed. This can lead to some unclear charts such as this one where it takes some processing to figure out what happened why one label has been removed and exactly which tick the last label corresponds to:

![image](https://user-images.githubusercontent.com/4560057/218830561-0975df45-c205-4792-9ac6-223f64f22407.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q6rnYAdAjhNSAIyqZVBQpiLnIAW0MBVAEIBhAFoAEQBlfwBJQxJCVQg6UjBiaEDCCED5RUowLCgwTEDdAE8maEMPORJDSgonTENMuUMwOSgAfXVWhHdKNBAZEArVAGstHKd1TBBuV0g6EiRUEAAPZTlluEplYjBh-woiFAB2AfhMdTotDwgmRza0qARSKe5suUntot0p5BB1CCQA0IXx+IAAjqRWsRFMQ0FMBkVlGcLlcIJRCG0FG1GBAPC8QMDvloIVDrAo4HD+gMACTZRiYCpaHT6IyGOEIOSWayMOzmOAQapgekVNmYDmBdTWepoACs5gATOY2OYAFY1KD9IA)

I think it would be better if Vega-Lite automatically formatted tick labels that are so large that they would be removed, either with an exponent or a suffix such as "K", "M" etc. I can see the reasoning for not relying on these solution as a default for all charts, but for charts where tick labels are removed, either of these solutions would be an improvement in my opinion. It would also help if the largest number on the x-axis was not snapped to the left but instead centered on the tick like the other numbers.

**Comment by domoritz** [comment]
Hmm, I don't know what exactly Vega-Lite should do. Vega-Lite doesn't have access to the data and a user could define a different formatting function if the axis labels are not good. We could also have a better default tick label formatter but we need to carefully design that. 

What's your concrete proposal for changing in Vega-Lite?

**Comment by joelostblom** [comment]
My idea was something along the lines of "if VL detects that a label will be dropped (there will be fewer labels than ticks), then switch to suffixes instead of full numbers". I don't know if VL has access to this info or if it happens on the level of Vega or maybe even D3?

**Comment by domoritz** [comment]
Vega-Lite doesn't have access to the data so this would need to happen in Vega.

**Comment by joelostblom** [comment]
Ok! Closing in favor or https://github.com/vega/vega/issues/3666

**Comment by joelostblom** [comment]
It seems like Vega-Lite already does have a mechanism to control the labels shows, e.g. setting `"labelOverlap": false` in the axis config gives this:

![image](https://user-images.githubusercontent.com/4560057/227806018-94b31948-f772-43e7-824b-2dc2213284f3.png)

So the desired functionality here would be to add the option to pass something like `"labelOverlap": "suffix"`, which instead of removing labels, truncates them using the "K", "M" etc suffixes.

**Comment by domoritz** [comment]
That's a cool idea but again needs to be in Vega since we just pass the setting down.
