### ISSUE TITLE
Responsive Bar Chart Example Not Smooth 

### ISSUE THREAD

**Issue by light-and-salt** [vega/vega-lite#8719]
https://user-images.githubusercontent.com/822034/218896889-01faffc1-5123-4bdd-b9ba-6964a91df6ad.mp4

👆 [The responsive bar chart example in vega-lite editor](https://vega.github.io/editor/#/examples/vega-lite/bar_size_responsive) (Vega 5.22.1, Vega-Lite 5.6.1, Vega-Tooltip 0.30.1, Editor dcd825a) is not resizing smoothly.

And axis titles and labels get selected as I resize the container.

**Comment by domoritz** [comment]
Is this a issue with Vega-Lite, Vega, or the editor?

**Comment by light-and-salt** [comment]
If I just use `vega-lite@5.6.1` and `vega@5.22.1` (outside of vega-editor), chart resizing is smooth!
See this gist: https://gist.github.com/light-and-salt/5adf57b6db8395bda92d23313095f3c7#file-index-html

So I think this is most likely a vega-editor issue. Thank you!!!
