### ISSUE TITLE
Day is off by 1 when converting date from int

### ISSUE THREAD

**Issue by qnzhou** [vega/vega-lite#8770]
It seems vega or vega-lite has an off by 1 error when parsing dates from ints.

```python
import pandas as pd
d = pd.to_datetime("2024-10-06T00:00:00")
print(d.day_name())
# Output: Sunday

raw_data = pd.DataFrame({"date": [d], "day": [d.day_name()], "year": [d.year]})                                                                                                                                               
json_data = raw_data.to_json(orient="records")
print(json_data)
# Output: [{"date":1728172800000,"day":"Sunday","year":2024}]
```

Therefore, according to pandas, `1728172800000` is a "Sunday".  However, Vega-Lite thinks it is a Saturday. Here is the Vega-Lite input:

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"values": "[{\"date\":1728172800000,\"day\":\"Sunday\"}]"},
  "mark": "point",
  "encoding": {
    "x": {"field": "date", "timeUnit": "day", "type": "ordinal"},
    "y": {"field": "day", "type": "ordinal"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.17.0.json"
}
```

The `x` encoding uses `day` as the time unit, and the plot is the following, which shows the x value as "Saturday":

![vega-lite output](https://user-images.githubusercontent.com/3606672/224575087-5baf58d0-3899-4049-9f44-98d6fec29b64.svg)

**Comment by jakevdp** [comment]
The issue is that the timestamp is parsed as UTC time but displayed as local time. If you use `"timeUnit": "utcday"` then it should work as expected.

**Comment by qnzhou** [comment]
Thanks @jakevdp!  I just noticed the small paragraph on `utc` prefix in the Vega-Lite doc! Does `utc` prefix work with Altair too?  The following code still produces the wrong plot:

```python
import altair as alt
import pandas as pd

d = pd.to_datetime("2024-10-06T00:00:00")
print(d.day_name())

raw_data = pd.DataFrame({"date": [d], "day": [d.day_name()], "year": [d.year]})
json_data = raw_data.to_json(orient="records")
data = alt.Data(values=json_data)
chart = alt.Chart(data).mark_point().encode(x="utcday(date):O", y="day:O");
chart
```

I am using Altair 4.2.2.

**Comment by jakevdp** [comment]
Altair 4.2.2 uses Vega-Lite 4.17, which handles dates a bit differently than the current release. If you're using Altair, the best way to make sure your dates make sense is to use pandas datetime object directly rather than doing serialization manually, then Altair handles the serialization for you and all times will be represented as local times, so you don't need to worry about UTC:
```python
import altair as alt
import pandas as pd

d = pd.to_datetime("2024-10-06T00:00:00")
data = pd.DataFrame({"date": [d], "day": [d.day_name()], "year": [d.year]})
alt.Chart(data).mark_point().encode(x="day(date):O", y="day:O")
```
![visualization - 2023-03-13T062613 801](https://user-images.githubusercontent.com/781659/224715204-5a282b1e-01eb-42df-bda0-364abad9c2c9.png)

**Comment by qnzhou** [comment]
Thanks @jakevdp !  I was using json serialization to bypass the 5000 rows limit in Altair, which leads me to discover this issue.  Another fix I learned is to specify `date_format='iso'` in pandas `DataFrame`'s `to_json()` method.
