### ISSUE TITLE
Same vega-lite spec provides different png/svg output on different boxes

### ISSUE THREAD

**Issue by bluesmoon** [vega/vega-lite#8798]
I have this vega-lite spec which I convert to a png using vl2png:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "encoding": {
    "x": { "field": "category", "type": "nominal" },
    "y": {"type": "quantitative", "field": "Foo"}
  },
  "mark": "bar",
  "data": {
    "values": [
      {"category": "A", "Foo": 0.1},
      {"category": "B", "Foo": 0.7},
      {"category": "C", "Foo": 0.6}
    ]
  }
}
```
I try the same on two different boxes. Both running Ubuntu 22.04 with node 18.5.0, vega-lite 5.6.0, vega 5.22.1, canvas 2.11.0.

On the first, I get this PNG which looks right:
![download](https://user-images.githubusercontent.com/35098/226451287-da319439-364b-4bb0-90d4-12a75888ec78.png)

On the second I get this PNG which has all the bars squished to a line:
![svgviewer-png-output](https://user-images.githubusercontent.com/35098/226451336-15369931-39b6-4fbf-9341-91b5894e3fa1.png)

Any idea what's happening here? Is there anything else I should look at to determine where the problem could be?

I see the same when converting to svg.

Additionally it looks as though the X & Y axis labels are no longer centered.

Furthermore, if I convert the vega-lite spec to a vega spec (using `vl2vg`), both boxes generate the exact same vega spec, but calling vg2png on that spec also produces different PNGs.

**Comment by domoritz** [comment]
No idea what is happening but since you get different Vega specs, I suspect it's an issue with different Vega-Lite versions or other differences between the machines.

**Comment by bluesmoon** [comment]
@domoritz I get the same vega spec, ie, `vl2vg` on both boxes produce the same output.  `vg2png` and `vg2svg` produce different output.  All package versions are identical.

**Comment by bluesmoon** [comment]
ok.  looks like it was a bug in `vega`. I upgraded to 5.24 and it started working correctly.
