### ISSUE TITLE
Add anaconda build for Mac M1

### ISSUE THREAD

**Issue by Lundez** [vega/vega-lite#8809]
Hi,

Currently there's no build available in `conda-forge` for the following OS/Build: `conda-forge/osx-arm64`

Is this possible to add? Would help our build-process immensly! :)

**Comment by domoritz** [comment]
Vega-Lite is a JS library. There are no python builds.

**Comment by Lundez** [comment]
@domoritz I'm sorry for having a short issue, I expected you to be aware of the packaged content in conda-forge

https://anaconda.org/conda-forge/vega-lite-cli
https://anaconda.org/conda-forge/vega-cli

Anyhow, Anaconda allows to publish all type of binaries, not simply Python.
Hence it's possible, and is, published Vega/Vega Lite CLI's which include Node etc automatically.

This makes it very simple to combine with `altair` & `altair_saver`, where even `altair_saver` recommends using the `conda` distribution.

Who handles this distribution if not you? Not sure where to reach out as this is the repo attached in the conda repo.

Thanks in advance,
Hampus

**Comment by domoritz** [comment]
Oh I see. I didn't know those existed. 

Looks like @xhochy made them and there repo is in https://github.com/conda-forge/vega-lite-cli-feedstock. Can you file an issue/send a pull request there?

**Comment by Lundez** [comment]
Thanks @domoritz
