### ISSUE TITLE
Access to all fields on axis label expressions/conditions

### ISSUE THREAD

**Issue by apbreports** [vega/vega-lite#8813]
It does not seem possible to access other fields when assigning conditional label formatting for weight, color etc.
Can we add this?

Here is our data:
```
{
        "phase": 1,
        "name": "Project 1",
        "start": "2023-03-10",
        "end": "2023-04-15",
        "pay": "2023-05-15",
        "status": "Delayed",
        "description": "This is the description of project 2."
      }
```

This does not work.

```
"labelFontWeight": {"expr": "datum.phase == 1 ?'bold':'normal'"},
"labelColor": {"expr": "datum.phase == 1 ? 'red':'black'"}
```

Only this works:

```
"labelFontWeight": {"expr": "datum.label == 'Project 1' ?'bold':'normal'"},
"labelColor": {"expr": "datum.label == 'Project 1' ? 'red':'black'"}
```

**Comment by PBI-David** [comment]
I think this needs to be moved to Vega.

**Comment by domoritz** [comment]
I think you can access the value. Use the logger expressions to check.

**Comment by PBI-David** [comment]
I think OP wants access to all fields in the datum - not just the value displayed on the axis. I have had this requirement in the past too and resorted to hacks to work around it. @jheer states in https://github.com/vega/vega/issues/791 that axis backing data only includes value and label fields so I think this would need to change at the Vega level.
