### ISSUE TITLE
Website doesn't show latest version

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#8840]
https://vega.github.io/vega-lite/ doesn't show the latest version.

**Comment by binste** [comment]
I don't know where the website gets the information from but maybe it's related to https://github.com/vega/schema/issues/8?

**Comment by domoritz** [comment]
`scripts/update-version.sh` creates a file that Jekyll then picks up to show the right version. It looks like it was all correct and now with the new build it worked out.
