### ISSUE TITLE
Website shows broken example

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#8841]
On https://vega.github.io/vega-lite/. 

<img width="1120" alt="Screenshot 2023-04-14 at 22 48 04" src="https://user-images.githubusercontent.com/589034/232179491-c49c2a69-cd74-4f7a-9ddb-689ce51bdedd.png">

**Comment by domoritz** [comment]
Adding @arvind since he worked on the XSS fix.

**Comment by PBI-David** [comment]
Broken examples half way down the page here too: https://vega.github.io/vega-lite/docs/condition.html

**Comment by hydrosquall** [comment]
👋 I think the issue might be related to the fact that there are 2 copies of `vega-scale` used in vega-lite, as well as multiple copies of `vega-scenegraph` . For the scale registry that we added to work correctly, we make the assumption that `vega-functions` is interacting with only 1 version of `vega-scale` . If there are multiple copies, the upstream code might not succeed at looking up the correct copy.

- Vega-scale: https://a.cl.ly/rRugBWkr
- Vega-scenegraph: https://a.cl.ly/6qubXvYN

After all, the examples in regular vega: 
https://vega.github.io/vega/examples/bar-chart/

Or the same example from the website when opened in the [editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWhiYrn56ADCJagALADMFSBJACK1AJwAjM1JAKK1mT15LQUAYrViTSNJAOK1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBdbqwXCyUGzKNLJkaKAAHq8gAGY0cILKBRQSkwAE8cHACrI2AgnlFgkg3jQIJ9BEhPIJ9M8LGgAAzZY4gz4-P4A9BpYFgiHoACODCQsh0gR0pBA+OyQA) are displaying correctly.

The fix could involve updating some package dependencies in vega such that everything is using the same versions of vega-scenegraph/vega-scale (more involved), or setting a `resolutions` field in the `package.json` that would force everything to use the same (presumably latest) version of vega-scenegraph and vega-scale (less involved but easier to do).

**Comment by hydrosquall** [comment]
IMO the resolutions-based strategy is a band-aid, and avoiding the need for multiple versions is probably the better long-term solution, but pinning to vega-scale 7.3.0 seems to fix the bar chart example locally.

https://a.cl.ly/RBurkEB6

**Comment by jwoLondon** [comment]
Possibly related: None of the [scale binding examples](https://vega.github.io/vega-lite/docs/bind.html#scale-binding) on the web pages currently work when clicked on - reducing the scale to a point. They do work when viewed in the Vega editor.

**Comment by domoritz** [comment]
I sent https://github.com/vega/vega-lite/pull/8857 to hopefully resolve this.

**Comment by domoritz** [comment]
Ah, it's deeper: https://github.com/vega/vega-lite/pull/8857#issuecomment-1517818042. This takes some work and I don't have time for it anymore.

**Comment by domoritz** [comment]
I fixed this issue in https://github.com/vega/vega-lite/pull/8857. I need a review from @kanitw or @lsh or someone else now.

**Comment by hydrosquall** [comment]
The site examples look like they might not be working yet - does the docs
site build have to be triggered separately?

**Comment by domoritz** [comment]
Yes. The site build needs to be triggered and happens with a release.
