### ISSUE TITLE
Errors when using TopLevelSpec as a type

### ISSUE THREAD

**Issue by claresloggett** [vega/vega-lite#8900]
Using TypeScript with vega-lite, I am getting compiler type errors flagged on functional code. I'm not sure if this is a bug or intended behaviour, but I can't find any way to use the library that will not trigger these errors.

The main culprit is when trying to access the `encoding` property of the spec. A simple (artificial) example would be

```
const showEncoding = (spec: TopLevelSpec) => {
    console.log(spec.encoding)
}
```

which gives the errors
```
Property 'encoding' does not exist on type 'TopLevelSpec'.
Property 'encoding' does not exist on type 'TopLevelFacetSpec'.
```

Actually assigning an object containing an `encoding` property to a variable of type `TopLevelSpec` does not create any errors.

The docs at https://vega.github.io/vega-lite/docs/spec.html#single indicate that `encoding` is an allowed property for single-view specs.

Tracing through the source code starting from the export in `src/spec/index.ts`, I can see that `TopLevelSpec` is a union of several other types which themselves are intersections of several types - I _think_ a relevant path for my use-case is 
```
TopLevelSpec = TopLevelUnitSpec<Field> | ....
TopLevelUnitSpec<F> = TopLevel<FacetedUnitSpec<F, TopLevelParameter>> & ....
    = FacetedUnitSpec<F, TopLevelParameter> & TopLevelProperties & ....
FacetedUnitSpec<F,P> = GenericUnitSpec<FacetedCompositeEncoding<F>, AnyMark, P> & ....
```
where `encoding?` is a property of `GenericUnitSpec`.

Is the error I'm getting intended behaviour? 

I realise there are some kinds of specs (e.g. faceted) where `.encoding` wouldn't be a top-level property. If I need to use a more specific type, I'm not sure how to go about doing that - no other spec types are exported, and the type tree is quite complex, so it looks like `TopLevelSpec` is the type we're intended to use?

**Comment by domoritz** [comment]
This all works as expected. As you noted, not all top level specs have to have an encoding. You need to differentiate over the types. How to do that is something you can learn about in typescript tutorials and we have some places where we do that in the Vega-Lite code as well. The Vega-Lite types are very good and we actually use them to generate json schema.

**Comment by claresloggett** [comment]
@domoritz I apologise for my confusion but how can I differentiate between the types when they're not exported from vega-lite itself? Surely doing this inside the Vega-Lite code takes advantage of the fact that all the types are accessible there? Would it be a good idea to export more types? Or am I missing something fundamental.

**Comment by domoritz** [comment]
Good question. The types may not be exported from the top level package but you can import from specific files by adding their paths to the import.
