### ISSUE TITLE
Axes Options for Small Multiples

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#90]
Right now we only show axes for small multiples once per axes in a separate group.  
Maybe some users want to show axes in every single cell

**Comment by kanitw** [comment]
- [ ] Maybe add `axis.shared` to `X` and `Y` with three possible values:
  - [ ] `true` (what we have right now)
  - [ ] `undefined` (show shared axis, but independent grid) like suggested in #920 
  - [ ] `false` (Each single has its own independent axis)
     - [ ] One question is do we produce separate scale.  I think we have to add `scale.shared` as well.  If `scale.shared` is `true` but `axis.shared` is `false` then we visualize the shared scale multiple times.  If both are false, then each single visualize its own independent scale.  Note that we do not allow `scale.shared=false` while `axis.shared=true` because that is semantically broken.  

(I guess adding this to `X` and `Y` is more sensible than `ROW` / `COLUMN`?)

**Comment by domoritz** [comment]
I find it a bit confusing that the difference in `axis.shared` true and undefined is how the grid is displayed. #920 should be orthogonal.

**Comment by kanitw** [comment]
Okay.  I remove the `undefined` option then and assume if we show grid, we always show inside.   
Then there are the following cases:

1) `scale.shared=false` (`axis.shared` is ignored and semantically always false in this case). 
2) `scale.shared=true` & `axis.shared=false` 

For both 1 & 2, an axis def is added to the inner group and all axis properties are applied to it.

3) `scale.shared=true` & `axis.shared=false` 
  - `grid=true` – axis defs are added to both outer group and inner group.  Grid properties are applied to the inner group while other properties are applied to the outer group.  
  - `grid=false` – an axis def is added to the outer group  and all axis properties are applied to it.  (Grid properties are ignored anyway)

**Comment by domoritz** [comment]
Did you mean to write "axis.shared=true" somewhere? I don't get what `scale.shared` is supposed to do.

**Comment by kanitw** [comment]
> Did you mean to write "axis.shared=true" somewhere?

Yep.  That's the 3rd case. 

----

> I don't get what scale.shared is supposed to do

If you read my former comment, there are distinction between shared scale and shared axis.  

> If scale.shared is true but axis.shared is false then we visualize the shared scale multiple times. 
To  clarify, each axis still have the same domain. 

> If both are false, then each single visualize its own independent scale. 
To  clarify, the each axis can have different domain. 

> Note that we do not allow scale.shared=false while axis.shared=true because that is semantically broken.

**Comment by kanitw** [comment]
Also have to consider #214 ...

**Comment by domoritz** [comment]
> Yep. That's the 3rd case.

It is now :-P

I wonder whether we should change the API a bit if we have three modes (shared scale, one axis; scared scale, repeated axis; separate scales). Can we encode three states with one variable rather than two booleans?

**Comment by sampsyo** [comment]
For what it's worth, I found myself wanting this today: specifically, a version with independent scales. This would be nice for comparing trends in similar but distinct data sets that have very different magnitudes without normalizing them (and losing information).

**Comment by domoritz** [comment]
@sampsyo Noted! With composition (vl 2.0) this will be possible. Until then you will need to create separate charts.

**Comment by domoritz** [comment]
This is part of scale and axis resolution in https://github.com/vega/vega-lite/issues/2319
