### ISSUE TITLE
"Ascending" sort order is not the opposite of "descending"

### ISSUE THREAD

**Issue by sfc-gh-tteixeira** [vega/vega-lite#9016]
I have a simple chart where the "ascending" order is _not_ the opposite of "descending". Further, the "ascending" order doesn't match what I expected. My impression is "descending" is the correct one, and "ascending" is incorrect.

The important thing to notice about about this chart: the data mixes integers and strings. This seems to be related to the bug, since when I change them all to be strings, the chart behaves as desired.

### Ascending

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"x": "foo", "color": "color0", "y": "AA"},
      {"x": "bar", "color": "color0", "y": "AB"},
      {"x": "foo", "color": "color1", "y": "AC"},
      {"x": "bar", "color": "color1", "y": "B"},
      {"x": "foo", "color": "color2", "y": "BB"},
      {"x": "bar", "color": "color2", "y": "BA"},
      {"x": "foo", "color": "color3", "y": "3"},
      {"x": "bar", "color": "color4", "y": "4"},
      {"x": "foo", "color": "color5", "y": 1},
      {"x": "bar", "color": "color5", "y": 2}
    ]
  },
  "mark": "circle",
  "encoding": {
    "x": {"field": "x", "type": "nominal"},
    "y": {"field": "y", "type": "nominal", "sort": "ascending"},
    "color": {"field": "color"}
  }
}
```

<img width="149" alt="Screenshot 2023-07-19 at 13 31 51" src="https://github.com/vega/vega-lite/assets/103002884/040eec90-e8a7-45c1-a5d6-e2765d20a410">

[Playground link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAB5oQAMzZtFIKG0FsATufuOnABlsBPcwEE-EABfBVNzJiQXJTdnVwdnLyVfdD8AIWDQkDN0Kxto+Jd0GKcARh9-AGEMsPQIqLsCuPcypPN0kJrLa1tipucAJnL0VPbM7JA6nsaigsHW4cCOrPNcqfc+pwBmIZBtpfHJ-PWZ9wAWHfP9le6j2JPnMSGSq9rItbuG90f5-qCAXRCIGQTgA1q4aE4oII4LY4LJ7MoaLIyGgaqALDQ4IJlOYzEpMN4cDD0LI2AgkToMiBkujMdjzL58YTiSBSeTZJSlDInJhzEhoHDEciqb1NJY6Tj7i4gjKgA)

### Descending

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"x": "foo", "color": "color0", "y": "AA"},
      {"x": "bar", "color": "color0", "y": "AB"},
      {"x": "foo", "color": "color1", "y": "AC"},
      {"x": "bar", "color": "color1", "y": "B"},
      {"x": "foo", "color": "color2", "y": "BB"},
      {"x": "bar", "color": "color2", "y": "BA"},
      {"x": "foo", "color": "color3", "y": "3"},
      {"x": "bar", "color": "color4", "y": "4"},
      {"x": "foo", "color": "color5", "y": 1},
      {"x": "bar", "color": "color5", "y": 2}
    ]
  },
  "mark": "circle",
  "encoding": {
    "x": {"field": "x", "type": "nominal"},
    "y": {"field": "y", "type": "nominal", "sort": "descending"},
    "color": {"field": "color"}
  }
}
```

<img width="149" alt="Screenshot 2023-07-19 at 13 31 58" src="https://github.com/vega/vega-lite/assets/103002884/95a7ecbc-308b-4379-a4f7-5fa332244d2e">

[Playground link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAB5oQAMzZtFIKG0FsATufuOnABlsBPcwEE-EABfBVNzJiQXJTdnVwdnLyVfdD8AIWDQkDN0Kxto+Jd0GKcARh9-AGEMsPQIqLsCuPcypPN0kJrLa1tipucAJnL0VPbM7JA6nsaigsHW4cCOrPNcqfc+pwBmIZBtpfHJ-PWZ9wAWHfP9le6j2JPnMSGSq9rItbuG90f5-qCAXRCIGQTgA1q4aE4oII4LY4LJ7MoaLIyGgaqALDQ4IJlOYzEpMN4cDD0LI2AgkToMiBkujMdjzL58YTiSBSeTZJSlDInJhzMp9FA4YjkVTeppLHScfcXEFZUA)

**Comment by domoritz** [comment]
This seems to depend on the browser

Safari:

<img width="162" alt="Screenshot 2023-07-19 at 08 44 59" src="https://github.com/vega/vega-lite/assets/589034/0a52e71f-5277-4fde-83e8-5f26af9dc64f">

Chrome:

<img width="170" alt="Screenshot 2023-07-19 at 08 45 25" src="https://github.com/vega/vega-lite/assets/589034/bc270db7-2cfd-4b29-a3af-f1145a70cd6a">

**Comment by domoritz** [comment]
Safari

```
$ [ "AA", "AB", "AC", "B", "BB", "BA", "3", "4", 1, 2 ].sort((a,b) => a > b)
[1, 2, "3", "4", "AA", "AB", "AC", "B", "BA", "BB"]
```

Firefox

```
$ [ "AA", "AB", "AC", "B", "BB", "BA", "3", "4", 1, 2 ].sort((a,b) => a > b)
[ "3", "4", "AA", "AB", "AC", "B", "BA", "BB", 1, 2 ]
```

Using `-` is at least consistent but doesn't work for non-numbers so it's not a real option.

```
$ [ "AA", "AB", "AC", "B", "BB", "BA", "3", "4", 1, 2 ].sort((a,b) => a - b)
["AA", "AB", "AC", "B", "BB", "BA", 1, 2, "3", "4"]
```

**Comment by domoritz** [comment]
I think this can be fixed with https://github.com/vega/vega/issues/2900.
