### ISSUE TITLE
Support natural sort for strings

### ISSUE THREAD

**Issue by claresloggett** [vega/vega-lite#9020]
It would be great if the default sort order for strings in axes and legends was the "natural" sort order (https://en.wikipedia.org/wiki/Natural_sort_order).

At the moment, an axis of categorical values ["Category1","Category5","Category12"] will sort alphabetically, like ["Category1","Category12","Category5"]; in most cases the former would be preferable. 

It's possible that natural sort is already the intended behaviour and that this is actually a bug, but I wasn't sure so have put it in as an enhancement suggestion. The documentation at https://vega.github.io/vega-lite/docs/sort.html says that strings will be sorted in their natural order in Javascript, but gives the example of `"a" < "b"`, so is probably meaning to imply the default sort order in Javascript, rather than what is commonly referred to as "natural sort order". 

Either way, this would be an extremely useful enhancement!

**Comment by domoritz** [comment]
We’ll need https://github.com/vega/vega/issues/2900 first.
