### ISSUE TITLE
Cross filtering in Deneb zooming resets the zoom

### ISSUE THREAD

**Issue by RiyadBkhsh** [vega/vega-lite#9107]
In deneb when zooming and after making selection in the chart it resets the zoom to initial position. How it can be prevented, so I can select multiple part in the chart while zoom in place?

Here is the link to the chart: [Timeline Graph](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscIA6hmADQAEADAJyUCCaA5pQEzVsDMNAbHNWoDqlAOIBZACohyIAEbwSZKnUYt2nHgEYA7MLjcxUmSADGihlpNhFAISuysMAE5QA+lACWAWwyKAytBUXCIAIhimlFoAHLT01PyCwkbSsqHQfkSkFDT0TKwc3CAAvuQEitkqeeqF2kJJgikmClnKuWoFmlHRAmxwXFpNsuZEDGzWduOOLu5evgFBlCGU4ZExcVEALPqNEqkg6VCZSjmq+RpFpeWtp9Wdhlq0AloCOkPyFW1nNV1sfdQvXTvEYgSwTIi2KYgJwQVweHzHQJQYJhCLdDZ-HYiPYmQ7HSrtc61EoAXVKIAwADtTAB7MCeSnMeCgACezJAADNPBgUDYiOZZFAWQAHY405z0ymoExeKAoTKUtAoFCyCAAD08OAQIBQEDkPIAwjSUOLFHJdaYANYlYrk3UsjDOPCgYWwiDeLX4EBS+ZEAAWnmYfpQgb9UBMWB5EXD2qFosUwppDPDshplMU3hpaEjNMQjptZW97uOzGcnhsjijphjIGTjuQKGaDL50NMqGwJULPrFws8tO8wojVZjoDjx0TyZMXJ5YE94BAZNkcmbinlzCpNmKJNk3lh1tjIuOclhEagzhplqPFut5KptMlTO1avZ095ilggsPiiOA-F0tVGpaqAur6igACiarCk6RCQFAaDeAAdCBPImMhKBGia0HyNeJiluW8Bnpgsh4WA6RYH6eAAKwIZR24gCRGGmkQpYYGysgAF7Nhgz5wFo5KyvKiiSAiAD0oRoM40CeGmnYgGq4zaq+LYKOStKYS+3JvjBEZtoJ2pgDSu4MngID2CYkILrIkmMpkuAgAAxAAYo5Oi0IIJj2ToDC2NE7mLjqGDrpSfKjp4crHGqkURiy3hyMa-hnheGCMVhABySqNo4MVxSgkhfkQWAAI5oLCfiyGhAAyPhhfAWgcLa0znpexDllAFHarSwVhdJ6ZwF6rqSd4igBkGIZBimFIDkK8AcqgkayA2mC1VuC2oEtAjkjSrqmGFbIdWm9JeDJfWjtgI6cppLZuG4kbytWZDXSYGDFdKRA0hyHKyYtmTUDRVwgAN7qKFtfaGYOq3oJkfF0d98C-ZRtr-WeECUlgHLikNJ0gHMGAAKqUjVRAOrCmaUm1sEYH6WbOFg3gMmgRxYJGnWzlOl2KDCcI4yYEBauAGTc-9ummEqGSKBTOMABTE84kuwfBCF4gAlFQpNtXL0AK8rVAUxrcGIdrlBUxJWB6wrnOzAiKuUHTiqM2biEW-CvjW8zB2m-LjszM7GBK0rPN85SGAAO7CfMK0gLuzj7qO+XY321qNUlZo4be1J0gyj6gDxoBKYoQehwiMpxz+iaSZlIDqpq7JoRBUHi5riFoaheqGsaTHYRAVq4WWfKERgxG92R7W4NRtEcVxPF8fxNLGl4g5Y3nRAF2HZXx+FihgXmZOUAlsJQJQq-F-GRCl3+Ffo84u41gApGAAC0N9yI-LKUDfAAScA3+IX-+KStp0WcNgY0eZ2RYF0pkbOiguKimClScMDUzBpi5FnSugF2QCWSu3LC5ou43ltEAA)

But it will not work in vega editor because I think it is deneb issue.

Click for visual: [Image](https://i.stack.imgur.com/kQug6.gif)

**Comment by domoritz** [comment]
If it's a Daneb issue, please file it there.
