### ISSUE TITLE
The sorting used in Window transform doesn't seem to work with quantitative data from a csv file

### ISSUE THREAD

**Issue by DaRealBurnz** [vega/vega-lite#9138]
When using the Window transform, sorting fields containing quantitative data from csv files does not sort them properly. Rather the sorting appears to be based on the individual digits, as shown in the screenshot below:
![image](https://github.com/vega/vega-lite/assets/87015034/082846e9-9b70-4fac-a942-b895528b8bd5)

On the other hand, manually inputting the same values as a list of data values within the spec sorts them correctly

Here is the spec and csv file I used:
```json
{
  "data": {
    "url": "test.csv"
  },
  "transform": [
    {
      "window": [
        {
          "op": "rank",
          "as": "rank"
        }
      ],
      "sort": [
        {
          "field": "test",
          "order": "descending"
        }
      ]
    }
  ],
  "encoding": {
    "x": {
      "field": "rank"
    },
    "y": {
      "field": "test",
      "sort": "-x"
    }
  },
  "mark": "bar"
}
```
[test.csv](https://github.com/vega/vega-lite/files/12907077/test.csv)

**Comment by DaRealBurnz** [comment]
Sorry for all the edits I accidentally pressed enter too early

**Comment by ChiaLingWeng** [comment]
Hi, I think the cause is that your csv data is not assign as numerical data (especially there is no table but value directly under column name: "test"), and all data is read as string.
``
{
  "data": {
    "values": [
      {"rank": 1,"test": 1}, {"rank": 2,"test":5}, {"rank": 3,"test": 10},{"rank": 4,"test": 50}, {"rank": 5,"test": 100}
    ]
  },
  "transform": [
    {
      "window": [
        {
          "op": "rank",
          "as": "rank"
          
        }
      ],
      "sort": [
        {
          "field": "test",
          "order": "descending"
          
        }
      ]
    }
  ],
  "encoding": {
    "x": {
      "field": "rank"
    },
    "y": {
      "field": "test",
      "sort": "-x",
    }
  },
  "mark": "bar"
}
``

**Comment by domoritz** [comment]
Yep, that's the issue. You can explicitly change the types in a parse block: https://vega.github.io/vega-lite/docs/data.html#format.
