### ISSUE TITLE
Add filter and sort support for vega tooltip

### ISSUE THREAD

**Issue by sfc-gh-cheliu** [vega/vega-lite#9149]
PR: 
https://github.com/vega/vega-lite/pull/9148
https://github.com/vega/vega-tooltip/pull/820

@joelostblom @jakevdp @kanitw @domoritz @arvind @jheer Could any of the maintainers review my PR? Thanks!

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/issues/9152
