### ISSUE TITLE
Improved handing of null values

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#919]
In #597, we defined that the null filter has three values true, false and auto. If the null filter is set to true, we filter all nulls. If it is set to false, no nulls are filtered and the user can manually filter nulls. In the auto mode, we filter nulls in quantitative variables. We could make this behavior even smarter.

For example, let's say we have a line chart and there is missing value. This value could be inferred (e.g. as the mean of the points next to it) and shown accordingly.

**Comment by kanitw** [comment]
Unclear if there is an actionable here, so I'm closing.
