### ISSUE TITLE
"Extent" property for Regression does not modify the regression extent and nullifies the regression.

### ISSUE THREAD

**Issue by chknfr1ed** [vega/vega-lite#9230]
I initially posted this in Vega and was suggested to move to here. 

When I try to add the "extent" property as listed in the [vega-lite documentation,](https://vega.github.io/vega-lite/docs/regression.html) the regression no longer exists and instead the data becomes a line chart.

[This](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA29zQgegLYHsA3ASwFMBnAOgCtz8A7EAXwBoRUIBPU5eAbVC4IyANbxQUTgAdSGKfmL0oINgDNiqVKTDwoyRKVYhS9AMb4wigObiQAD1vrSqHXBAAlfFCgmABABV8ISh8Cl93aGsVEEkZDABHRAglYhgoYkJZI05HMhcMAEkAWQARACFwyPobNljZN0Tk9LSMrKZWQWExBBjpevZFWTZzVHxeN3VkUgAjZGJTMSM9ZPJVMdx+UCmrKfJyYgZC0oqI9Orow7dPbz9A4NDySrObJgBdNhNzS3Oehx6nfJXLw+egBILQB5PKK1PoJJIpFqZZhsHL-PKuEDFcpQ84wuINeHNSJI9odGLIFZrZAbOACEDbXb7S6Y444mogZnXEFg+5hU7QkBSYQQXDkXT6QwsUCmCCoUyIDg+DAAcncACa4L5lQBqKnBAAUkCgiFwlGQAGVGlMwCwtZQAEyqZUASmiEDFV3tzHeICEolsdQwPjsymG+FG4xAkxmcwW0T+IAA7sQwFAABZu1DEKyMNxzKxp0MgVEAWgArEZPhYoj1g8pa7C3PQgopZdEARj3F7Sa8mEA) is the example pulled from the regression example in the vega-lite documentation:

![image](https://github.com/vega/vega-lite/assets/152239887/7595c5c7-1142-4c3d-a7d9-f3fe651b94da)

However, when I add in the extent property to the example, [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA29zQgegLYHsA3ASwFMBnAOgCtz8A7EAXwBoRUIBPU5eAbVC4IyANbxQUTgAdSGKfmL0oINgDNiqVKTDwoyRKVYhS9AMb4wigObiQAD1vrSqHXBAAlfFCgmABABV8ISh8Cl93aGsVEEkZDABHRAglYhgoYkJZI05HMhcMAEkAWQARACFwyPobNljZN0Tk9LSMrKZWQWExBBjpevZFWTZzVHxeN3VkUgAjZGJTMSM9ZPJVMdx+UCmrKfJyYgZC0oqI9Orow7dPbz9A4NDySrOa4zsfJX4ABhYAVk+AXSY-zYJnMlnOPQcPSc+SuXneASC0AeTyitT6CSSKRamWYbBy0LyrhAxXKqPO6LiDSxzUiuPaHRiyBWa2QGzgAhA212+0uJOO5JefOuCLuyLCpzRICkwgguHIun0hhYoFMEFQpkQHB8GAA5O4AE1wXy6gDUrOCAApIFBELhKMgAMqNKZgFgmygAJlUuoAlNEIAqrp7mMCQEJRLY6hgfG9oiMxhhJjM5gtolCQAB3YhgKAACwDqGIVkYbjmVjzynx8AAtD8jKCLFEerHlC2MW56EFFOrojDie4QwzAUA) is the result:

![image](https://github.com/vega/vega-lite/assets/152239887/0ebe60a1-4174-43df-8cd8-529c329d03ad)

**Comment by chknfr1ed** [comment]
Someone else is also having this issue from SO: https://stackoverflow.com/questions/77845962/regression-line-issue-in-vegalite-charts

**Comment by jonmmease** [comment]
When adding this to Vega-Lite:

```json
"transform": [
    {"regression": "IMDB Rating", "on": "Rotten Tomatoes Rating", "extent": [0, 100]}
],
```

The generated Vega ends up with this transform:
```json
    {
      "name": "data_1",
      "source": "source_0",
      "transform": [{"type": "extent", "field": [0, 100]}]
    },
```

This is nonsensical, as `[0, 100]` is not a field, and the extent transform doesn't bind the result to a `signal` anyway, so even if the "field" were valid, it wouldn't do anything.

@vega/maintainers Does anyone have context on how this is supposed to work in terms of the generated Vega? It seems to me like this needs to be a configuration option in the Vega transform, and it's not clear to me how this ever worked.

**Comment by thomascamminady** [comment]
FWIW, I filed the issue on `altair`'s end here: https://github.com/altair-viz/altair/issues/3347

I was certain that this used to work and it seems that with `altair=5.0.0` this is working as expected, but with `altair=5.1.0` this does not work properly. 

Looking at the release notes for 5.1.0 (https://github.com/altair-viz/altair/releases/tag/v5.1.0) this corresponds to the `vega-lite` update from version 5.8.0 to version 5.14.1. 

Comparing both `vega-lite` versions can done here: https://github.com/vega/vega-lite/compare/v5.8.0...v5.14.1

I think I'm unable to pinpoint this further, but maybe this insight helps someone else :)

**Comment by player1537** [comment]
I can confirm that when I test with:

```
<script src="https://cdn.jsdelivr.net/npm/vega@5.25.0/build/vega.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@5.9.3/build/vega-lite.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6.22.2/build/vega-embed.js"></script>
```

and vary the vega-lite version, then `v5.9.3` works, and `v5.10.0` does not work. (They all "work", but the latter has the bug this thread is about)

This brings the relevant changeset down to: https://github.com/vega/vega-lite/compare/v5.9.3...v5.10.0

**Comment by lsh** [comment]
I see the issue. Will put up a fix ASAP.
