### ISSUE TITLE
Cannot use datum expr in scale padding

### ISSUE THREAD

**Issue by nhannt201** [vega/vega-lite#9245]
I'm having trouble utilizing "datum" within "expr" in vega-lite scale padding. I'm attempting to calculate the padding adjustment value but keep encountering the error "datum is not defined." I'm currently using vega-lite v5, and encountering this issue when applying the JSON code.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"x": 1, "y": 10},
      {"x": 2, "y": 5},
      {"x": 3, "y": -3},
      {"x": 4, "y": 8}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative",
      "scale": {"padding": {"expr": "datum.y < 3 ? 20 : 0"}}
    },
    "y": {"field": "y", "type": "quantitative"}
  }
}
```
The document below describes how I can use expr, but in fact, it does not fully support the expr syntax in the above case, specifically does not support "datum".

<img width="608" alt="image" src="https://github.com/vega/vega/assets/12721256/1c21246a-8ae3-44bc-9d8a-970d47ea43a1">

Is there any solution to solve the above problem?

**Comment by nhannt201** [comment]
![image](https://github.com/vega/vega-lite/assets/12721256/2e1a73c1-c72a-4aa8-acca-d88b92121400)
Above is just an example code of not being able to use datum in expr of scale. My purpose is to create a layer of bar chart with padding and a layer of text mark to display data label, if the value is negative then The data label will display below the bar. However, if it is a positive number, the scale padding will return 0. As in the photo I sent, in this case I need to use expr to return the padding to 0 because the data label is a positive number.

**Comment by domoritz** [comment]
In a scale you don't have access to datum I think. Scales are defined over extents or discrete domain values, not data from the datasets.

To place the text, you wouldn't change the scale. 

I'll close this as there isn't a bug here I think. Let me know if you think I misunderstood.

**Comment by nhannt201** [comment]
You can take a look at this example, I took it from vega lite's own example: is there a way to customize the scale padding value of the dynamic x-axis, instead setting the default value to 20? Actually expr cannot be used with scale padding with datum.value value!

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABEyTrDsU5kMB3OjEOy+O0oeJJBDNZUMB1OOaRZQxgaVUN6fyQADxoIQ2U2ZBog4UcFQ0DlQ2SITDgkLIYISPM5ZTpdd0MyTSyoNkE2M0w2ePUkawzDAC84dVaTYtS4SkUVJEwUVFA3DzU0AG1QKZB9MaY0fgAmAA4AXwVltBAAIXW0MTEDo-QAYXPUfgBmJ+uQFYARB4BOAEY3lYAUQeO3+h3exwAYg8xK9wSsAOIPfi-b4A44ACRBAHZ0egAJIwrZ7AC6BxAcFk9XKsjIaFAAE96SAAGY0OCCZTHFBKTAMnBwY6yRLJdxjaKxZkJJJ6FnuYq8mhQADWEDQcsECpAgiQTA5+lpgkFqAADEodXrBAAFAo0umoAAse3JUWZbI5XPQG15-ONIAAjgxAjpJs5BUpoO5jaAcLbkvatibyRK1dMQDVQrcGk1mfVZOUdHJmXlcsdlBMGAhKLNPIYALwNwwmsY1v1MHUqkDk1vHADEygHXed5J1DL6i1AyHUyuOJnUXfBU5nab5AuOeSimHFwjIelAcCiOHn6HLmErlCYhgAPE3DAB+QwAck0ZCwj8MqCfRpZmEfC5UrppgeR5lhWVaXjeJr3oY2wfoYWxDkolLUvGxYHluabupys5jKufqBsGdATDQpBDqSexAA)

**Comment by domoritz** [comment]
You want padding on the y scale, not the x axis, right? https://vega.github.io/vega-lite/examples/layer_bar_labels.html is the closest to your example I can think of right now.

**Comment by nhannt201** [comment]
Thanks, the above example is also close to what I need. However, is there any way to make "scale": {"domain": [0, 60]} dynamic? I want to use transform to calculate domainMax and domainMin values for it. Is this possible?

**Comment by domoritz** [comment]
It's a good question and I think we should have something to make it easy to have enough space for labels. IIRC @kanitw had a better example at some point.

**Comment by PBI-David** [comment]
You can set a dynamic scale using this example here: https://stackoverflow.com/questions/75456476/setting-a-dynamic-domain-min-and-max-axis-in-vega-lite-deneb

**Comment by nhannt201** [comment]
> You can set a dynamic scale using this example here: https://stackoverflow.com/questions/75456476/setting-a-dynamic-domain-min-and-max-axis-in-vega-lite-deneb

This is exactly what I need. Thank you so much for your support!

**Comment by domoritz** [comment]
That's a great approach. We should think about making that easier in Vega-Lite but for now I'd love to have that as an example in the gallery.
