### ISSUE TITLE
Automatically generate JSON Schema from TS Interfaces

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#927]

**Comment by mprudhom** [comment]
I can try working on this. To clarify: is the goal that the `axis.schema.ts` file will contain only the `interface Axis` section and not the extra somewhat-redundant `export var axis` section?

**Comment by domoritz** [comment]
Exactly. We should be able to generate the json scheme from the typescript interfaces.

One thing to keep in mind is that we need to sometimes instantiate parts of the schema for instance when we want to replace `bin: true`. We were hoping that if we use classes with the defaults in addition to interfaces, we could simply instantiate an object of the class. The ts to json schema converter can handle classes.

**Comment by domoritz** [comment]
We cold also instantiate from a #ref or when we merge the defaults into the incoming spec, we could be aware of the fact that we have to replace booleans with objects sometimes. 

There are a lot of options here but we will have to try them out to see which one works (best). 

I'm happy to discuss options on Skype.

**Comment by kanitw** [comment]
>  replace booleans with objects sometimes.

In that case, the signature would be   `boolean | InterfaceName` (e.g.,  `boolean | Axis`) anyway so if the TS-> schema generator handles union type (`A | B`) and interface extension (`A extends B`) correctly.  We should be fine.  

(Default value instantiation should be all moved into `config` soon anyway.)

**Comment by domoritz** [comment]
Done in #1131
