### ISSUE TITLE
developer-experience: deployment previews for pull requests

### ISSUE THREAD

**Issue by hydrosquall** [vega/vega-lite#9276]
## Enhancement Description

Goal: Reduce time and effort to validate change requests, and improve review quality for vega-lite change requests (PRs). By making a deployment preview easy, it makes it easier to test end-user facing behaviors.

Motivating use-cases

- When new PRs are opened, enable maintainers to review and test edge cases
- Create a test environment that shields
- See discussion w/ @domoritz here: https://github.com/vega/vega-lite/pull/9262#issuecomment-1950624437

Expected behavior

- When a new PR is opened, build a copy of the vega-lite docs site and/or vega-editor that uses this branch's copy of vega-lite.
  - TBD which is easier to do first.

## Checklist

- [x] I checked for duplicate issues. ( [preview](https://github.com/vega/vega-lite/issues?q=is%3Aissue+preview+) )

## Notes

- It's possible to set this up with a 3rd party provider (each with their own pricing model), but I'd like to first try if we can do this purely with Github actions.

**Comment by hydrosquall** [comment]
Here's a copy of the setup on Cloudflare so anyone can configure this for their own account.

 For now this only builds the `vega/editor`, not the docs .

![image](https://github.com/vega/vega-lite/assets/9020979/fb07a6a9-59d3-401f-b0da-cdec1363d5b1)

- Disable automatic deployments on `main`
- Blocklist for branches: `dependabot/*` , `docs/*`
- Keeplist for builds: the `src/*` directory
- Build settings
  - run `yarn run build-editor-preview`
  - Output the result to `/editor/dist`

See the result here: https://vega-lite.pages.dev/#/

**Comment by domoritz** [comment]
Sweet. I think we can close this now, right?

**Comment by hydrosquall** [comment]
Yep, unless we also want previews of the docs site to be deployed in
parallel.

**Comment by domoritz** [comment]
That's not as critical as the editor imo but could also be useful. How about we close this for now until we learn a bit more about how the current setup works out?

**Comment by hydrosquall** [comment]
Sounds good!

**Comment by hydrosquall** [comment]
Idea for future : if building previews per commit automatically  eats through the builds too quickly much, we can use the "Deploy hooks" feature to trigger deploys via specialized comments (like `/request-deploy`), or having a microsite where people can request builds by entering the PR #.

**Comment by hydrosquall** [comment]
Noticed today that the current solution works for people in the Vega org. This is good for saving my CI minutes, but less good for enabling new contributors

Short of building a button that lets PRs from forks request a build, I'm saving a possible solution here if we end up needing to intake more external contributions  : https://github.com/vega/vega/issues/3924#issuecomment-2603043456
