### ISSUE TITLE
Make javascript: urls work as values of href

### ISSUE THREAD

**Issue by mtravers** [vega/vega-lite#9309]
## Enhancement Description

I want to use a Vega Lite visualization as a control for other UI elements, meaning, I want to be able to call some javascript when the user clicks on a mark. 

Surprisingly, there seems to be no easy way to do this now (I feel like I might be missing something).

One thing I tried and didn't work: using `javascript:` urls as values for `href` attributes. This didn't work, although they work as hrefs on normal HTML elements.

So, the feature request is to make these work. This would be a simple if somewhat crude way to allow arbitrary interactivity.

```json
{
  "mark": "rect",
  "encoding": {"href": {"value": "javascript:alert('you clicked')"}}
}
```

## Checklist

- [x] I checked for duplicate issues.

**Comment by domoritz** [comment]
We will not support arbitrary callbacks be a use that would introduce security issues.

What you can do instead os use signals in Vega and Params or selections in Vega-Lite and do computations in expressions or add an event handler to the Vega view object (which would let you do exactly what you asked for but not from within the spec).

**Comment by jheer** [comment]
Vega works to prevent arbitrary JavaScript code execution for security reasons. Supporting this could cause major headaches in existing production deployments and so should not be supported (at least, not by default).

An alternative approach would be to use the Vega View API to add your own event listeners, allowing you to perform whatever UI controls like: https://vega.github.io/vega/docs/api/view/

**Comment by mtravers** [comment]
I understand the security concerns, but they don't really make sense. Any web page can include arbitrary javascript code, and any DOM element can have a click handler that executes arbitrary javascript code, so it isn't much of an additional risk to let vega-lite marks have the same powers. It's the browser's job to make sure none of that code can do anything harmful by sandboxing execution, which they do pretty well.

I can't make any of the other methods work in the context I'm working in (ClojureScript/Reagent/Vega-Lite) which otherwise works like a charm. I'm really surprised it is this hard to do something so simple and obviously useful; I can't be the first person to run into this.

If you want to make this capability available as an option but not on by default, that would be fine and would solve my problem. 

I'm contemplating making my own forked version of the Vega libs that can do what I need, but I would much rather not.

**Comment by mattijn** [comment]
FWIW, @mtravers, maybe this issue describes a way-out: https://github.com/vega/vega-lite/issues/6471

**Comment by mtravers** [comment]
I finally figured out how to do this:
- compile from VL to Vega
- add a signal with event handling
- add a signalListeners property to the react component
Still seems like you should be able to do something this simple in VL without so much pain.

**Comment by domoritz** [comment]
> I understand the security concerns, but they don't really make sense. Any web page can include arbitrary javascript code, and any DOM element can have a click handler that executes arbitrary javascript code, so it isn't much of an additional risk to let vega-lite marks have the same powers.

Vega is designed such that you don't have to trust a specification (it may be user provided like on Wikipedia). The idea is that you may embed the chart on any website without exposing that website to any code that may be in the spec. This design has been very successful over the years and enabled many applications and has rarely been a limitation since you have expressions and can add custom hooks on the Vega view (https://vega.github.io/vega/docs/api/view/). 

You can disable the Vega expression parser so that any Javascript is allowed there. You don't need a fork to get that functionality.
