### ISSUE TITLE
Adding domain to scale on bar charts cause phantom bar to show up

### ISSUE THREAD

**Issue by TessaiMusa** [vega/vega-lite#9314]
## Bug Description

When using `"scale": {"domain": [a,b,c]}` in bar chart causes a phantom bar to show up which obscures some of the data (see screenshot):
![image](https://github.com/vega/vega-lite/assets/49408514/fa39e8eb-6c11-4c4f-9ba4-a591e2434738)

Without domain in scale, it renders properly:
![image](https://github.com/vega/vega-lite/assets/49408514/a0c2f732-e5c4-4c53-8ccd-2efbd6ce2ff9)

This is the json I used to create this issue
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": { "url": "data/population.json"},
  "mark": "bar",
  "encoding": {
    "y": {"field": "age", "type": "nominal", "scale": {"domain": [5,10,15]}},
    "x": {
      "aggregate": "sum", "field": "people",
      "title": "population"
    },
    "color": {
      "field": "age", 
      "type": "quantitative"
    },
    "tooltip":{"field": "age"}
  }
}
```

Using tooltip to check the phantom bar shows several y values stacked next to each other, which is not expected behavior.  This seems to not happen for temporal/quantitative values.

## Checklist

- [x] I checked for duplicate issues.

**Comment by PBI-David** [comment]
Those are all the datapoints that are not in your domain. e.g. 20 is not in your domain so has no positioning info and just goes to the chart origin. Use a filter if you want to remove values.
