### ISSUE TITLE
Support `size` channel for `tick` mark

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#932]
We can’t map size to tick mark yet.  We can do it in a similar fashion to bar. 

- [ ] modify `src/compile/mark-tick.ts`  (Seeing `src/compile/mark-bar.ts` as inspiration)  Basically, size should be mapped to either `width` or `height` depending on orientation
- [ ] unit test

**Comment by YuhanLu** [comment]
I see the config for tick and it seems tick doesn't support orient

**Comment by kanitw** [comment]
We actually use orient with tick here: https://github.com/vega/vega-lite/blob/master/src/compile/mark-tick.ts#L33.  

But good catch, we didn't add it to the comment & docs correctly so I just did that in this commit: 36cc5dc6065eb8ea18e14a3843625f0615d17a80.

**Comment by kanitw** [comment]
Done in #1049
