### ISSUE TITLE
Your documentation for bullet chart has wrong label alignment

### ISSUE THREAD

**Issue by LizThompson93** [vega/vega-lite#9322]
https://vega.github.io/vega-lite/examples/facet_bullet.html

It has something to do with `labelAngle` that's also conflicting with the expected fix of: `"labelAlign": "right"`

![image](https://github.com/vega/vega-lite/assets/96261305/1f78edf9-edb0-4b80-90af-8606bc5489bb)

**Comment by PBI-David** [comment]
Dupe: https://github.com/vega/vega-lite/issues/5547
