### ISSUE TITLE
Data with date format "2024, May" renders in Chrome but not in Safari or Firefox

### ISSUE THREAD

**Issue by the21st** [vega/vega-lite#9355]
## Bug Description

Describe how to reproduce this bug. Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) spec in JSON, wrapped by triple backticks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"createdAtByMonth": "2024, May"},
      {"createdAtByMonth": "2024, May"},
      {"createdAtByMonth": "2024, May"},
      {"createdAtByMonth": "2024, Apr"},
      {"createdAtByMonth": "2024, Jan"}
    ]
  },
  "mark": {"type": "bar"},
  "encoding": {
    "x": {
      "type": "temporal",
      "field": "createdAtByMonth",
      "timeUnit": "yearmonth"
    },
    "y": {
      "type": "quantitative",
      "aggregate": "count"
    }
  }
}
```

[Vega editor link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoKACc4auMoCCmAEIBPALJz6aEACYADB4AsCgAInJAcQAF8FE3NLG3tnVxh3bz9A4NCIqItMK1tHF1k3dGT-IJDwyJAzLJy4-MLPHxLrHFNyzJjc+ILEosbAgCkkeTCAXQiQZFMAazRQTAccOHcmJFbxuFkoNmUaWTJZkAAPA-nF92yEHDZTHUUQADMaOEFldyqO2oS7zBoEOABVWR0dwOCymBBfcahTQgU5LdAARwYQx+6h+pDuSDIZHMFGybzYDAK4TCYSAA)

Chrome screenshot:

<img width="1455" alt="image" src="https://github.com/vega/vega-lite/assets/4610874/76d71294-7fd1-46d5-8397-758bf5b432ff">

Firefox screenshot:

<img width="1371" alt="image" src="https://github.com/vega/vega-lite/assets/4610874/82ffa59c-8ae7-42ea-be5e-bf8669ae022f">

## Checklist

- [ ] I checked for duplicate issues.

**Comment by jheer** [comment]
Unfortunately, JavaScript Date parsing is not completely standardized and browsers diverge on the types of formats they support. For non-standard date formats, we recommend including a custom transforms in your Vega/Vega-Lite spec (or perform pre-processing) to ensure consistent behavior. For example, you might use Vega's [`timeParse`](https://vega.github.io/vega/docs/expressions/#timeParse) (or `utcParse` functions).
