### ISSUE TITLE
Avoid filtering out entries from legends when the data is filtered via the legend

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#9360]
## Enhancement Description

If a legend filters the data when clicked, the legend will also be updated to remove all categories that are not selected. This has a few undesirable side effects, such as the color of the category changing after the click, not being able to select multiple legend entries, and having to double click to go back and select another entry (which is not clear unless you know this is how the interaction works). A current workaround for this is to specify a constant domain, but that only works if all the unique values are known ahead of time (which e.g. is not the case when creating a more general spec that will work with multiple data sources, such as in https://github.com/vega/altair/pull/3394).

Would it be possible to add an option so that legends are not filtered when the data is filtered, so that the legend entries correspond to the unique data values from the initial view only?

Here is an example
![image](https://github.com/vega/vega-lite/assets/4560057/56e0c6fa-1643-4187-a7da-0a6524447166)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLkTOVVKK0poEBkQTwyAa2VCAE9dTC1dCBJxbnh1dUw6FEJVUkx8zChIOhIkVB51CFVleDtW5BAAeVVEEhBucsqtKAhPEjlNfIAPcax1KZBBUdCa7Ewx5Yqq6YBHUjkiOEViXzzuMoPJrQBZODNSgAfUqqmBAHFtiMoEsQCs7iBHs9iG8HFVpNxdBk5J5KCgANqgKC4xHY1S44EsOGhZpgcRDBHVWpEOE9PoDfHIAnDUYgAC6+QARiRjs0ED1WpJ+csKVBKDBRp5CaBGoQrspybjqjjPFS8tLuAASShgRiYQpaHT6Iw+PxycwIV6MUhC8xwCCGU3mwp2-wBezqnwAVnMUQA7ElsrlJEA)

If I click to select "Japan", the color scheme changes to show "Japan" in blue instead of as in Orange in the original picture, and there is not way to shift click to add e.g. "USA" to the selection since the other legend entries are now filtered out

![image](https://github.com/vega/vega-lite/assets/4560057/11da84e0-3308-4729-a465-0b85cd2b84b6)

Here is an example of keeping all the entries in the legend even when the data is filtered https://plotly.com/python/plotly-express/#gallery

**Comment by PBI-David** [comment]
Is this any help as a workaround: https://stackoverflow.com/questions/78066133/vega-lite-pie-chart-with-multi-selection-in-the-legend

**Comment by joelostblom** [comment]
Thanks for your suggestion @PBI-David ! I want to avoid a layered spec if possible so I opened https://github.com/vega/vega-lite/pull/9374 to enable another way of doing this in Vega-Lite.
