### ISSUE TITLE
Simplify axis label angle

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#939]
Right now it's nested very deep and the attachment is hard to get right. 

This is how you can add labels with an angle

```json
{
  "description": "Temperature in Seattle as a bar chart with yearmonth time unit.",
  "data": {"url": "data/seattle-temps.csv","formatType": "csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "timeUnit": "yearmonth",
      "axis": {
        "format": "%B of %Y",
        "properties": {
          "labels": {
            "angle": {"value": -45}
          }
        }
      }
    },
    "y": {
      "aggregate": "mean",
      "field": "temp",
      "type": "quantitative"
    }
  }
}
```

We should add a `labelAngle` property to the axis.

**Comment by kanitw** [comment]
I guess you mean add `labelAngle` as a top-level property in `axis`.  If that is the case, I would say that this is better done at Vega level, and once that is done, we just add the same property to Vega-Lite and pass it to Vega.

**Comment by kanitw** [comment]
First, I think removing the `value` layer would benefit all property: https://github.com/vega/vega-lite/issues/975.  After that, we could consider if this is a special one that we would like to support.   I think this should be done at the Vega level though.

**Comment by domoritz** [comment]
Okay. Maybe we can somehow figure out which properties should be passed to vega so that we can get rid of the `properties` property.

**Comment by kanitw** [comment]
- [ ] add `labelAngle` to axis's interface and schema in axis.schema.ts
- [ ] in `axis.properties.labels()` produce `labels.angle` like above and assign `value` = `-45`
- [ ] add unit test
