### ISSUE TITLE
 Color scale doesn't resolve properly in view with facet

### ISSUE THREAD

**Issue by fxwiegand** [vega/vega-lite#9435]
## Bug Description

In the provided Vega-Lite spec, we're layering a rect mark (colored by category) with a line mark (colored by sample), and we've set `"resolve": { "scale": { "color": "independent" } }` to use separate color scales for each. However, we get warnings like:

```sh
[Warning] Conflicting scale property "domains" ([["Category1","Category2"]] and [["A","B"]]). Using the union of the two domains.
[Warning] Conflicting scale property "range" (["red","orange"] and ["blue","green"]). Using ["red","orange"].
```

It seems the color resolution isn't being respected, and the scales are being unified instead of kept independent. Is this a usage issue?

Heres a [minimal example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoWW2VwA+jVnmAHmgCMS7brhoADJQdilUNeTYAJwBPNBAAYX8yIOCHRRAIJAQcQTd0AEF4nDUYRwBfBRMzS2s7NAAmZx09D0oAdh8QP0wAkLDIluiQ8vjE5NSwzKVs+nzCkFNzKxs4e1QnEBca1E8xRubW0PQOzbilPpS0kAAhLJyxoqnS2Yqq11qATnWomPaX7t6kw7DT4fP5gqXEozOYLJZpTwAZmenVe23esU+-SOQxAI1yqHKgImxWmZUxd2WngAbDDNm9YR99l8BhkzqNMdjJsD8WDqhDKAAWMldLYRBF7BI0o6-NH-LHjZl4m4Exbs2oADh5cP5lOCPWpyJ+9IxWIAugUQAAzJBQOCYNCgQJsADuluNNDggmUYXR8UwwRwRyCymsOhAeUNEC9UHtcFkUDM1jI9rmoCNjudYSl13sSg9XrCPr9gniSFsNAMqFkDEEgkDSkESGCcECRlAyECAGswoE4FALUpw5HfbIY5ommxBEF7QmnS70Btee7Pd7Ar3-fs-LTQMo2MhrEZVbt4jteT09UpAkg+2lDCA2y6lEET2Q3AbA9jGy30MJZG4uxGo337Vt44mJzle501nMIAEcGBPTA6DUGhSADXwhxHAcxyTdADgGEDM3QUwEBzXplzSVd1yQTdUHPVFTkPC9bzPEAmGAkAyDbcMQAfQMDSPfQh3ggdoB0IjB2HOt0GuL0ZlkC1HyAA):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"node_index": 1, "value": 0.15, "category": "Category1", "sample": "A", "path": 1},
      {"node_index": 2, "value": 0.75, "category": "Category2", "sample": "A", "path": 1},
      {"node_index": 1, "value": 0.55, "category": "Category1", "sample": "B", "path": 1},
      {"node_index": 2, "value": 0.95, "category": "Category2", "sample": "B", "path": 1},
      {"node_index": 1, "value": 0.35, "category": "Category1", "sample": "A", "path": 2},
      {"node_index": 2, "value": 0.65, "category": "Category2", "sample": "A", "path": 2},
      {"node_index": 1, "value": 0.45, "category": "Category1", "sample": "B", "path": 2},
      {"node_index": 2, "value": 0.85, "category": "Category2", "sample": "B", "path": 2}
    ]
  },
  "facet": {
    "row": {"field": "path", "type": "ordinal"}
  },
  "spec": {
    "encoding": {
      "x": {"field": "node_index", "type": "ordinal", "axis": null}
    },
    "layer": [
      {
        "mark": "rect",
        "encoding": {
          "color": {
            "field": "category",
            "type": "ordinal",
            "scale": {
              "domain": ["Category1", "Category2"],
              "range": ["red", "orange"]
            }
          }
        }
      },
      {
        "mark": "line",
        "encoding": {
          "y": {"field": "value", "type": "quantitative"},
          "color": {
            "field": "sample",
            "type": "nominal",
            "scale": {
              "domain": ["A", "B"],
              "range": ["blue", "green"]
            }
          }
        }
      }
    ]
  },
  "resolve": {
    "scale": {
      "color": "independent"
    }
  }
}

```

**Comment by kgoodrick-uu** [comment]
I believe the `resolve` component is in the wrong part of the spec. If you move it to be within the `spec` dictionary it should give you what you are looking for.

<img width="242" alt="image" src="https://github.com/user-attachments/assets/4dfe3c00-1219-49e9-a30e-f124edb19d60">


[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoWW2VwA+jVnmAHmgCMS7brhoADJQdilUNeTYAJwBPNBAAYX8yIOCHRRAIJAQcQTd0AEF4nDUYRwBfBRMzS2s7NAAmZx09D0oAdh8QP0wAkLDIluiQ8vjE5NSwzKVs+nzCkFNzKxs4e1QnEBca1E8xRubW0PQOzbilPpS0kAAhLJyxoqnS2Yqq11qATnWomPaX7t6kw7DT4fP5gqXEozOYLJZpTwAZmenVe23esU+-SOQxAI1yqHKgImxWmZUxd2WngAbDDNm9YR99l8BhkzqNMdjJsD8WDqhDKAAWMldLYRBF7BI0o6-NH-LHjZl4m4Exbs2oADh5cP5lOCPWpyJ+9IxWIAugUQAAzJBQOCYNCgQJsADuluNNDggmUYXR8UwwRwRyCymsOhAeUNEC9UHtcFkUDM1jI9rmoCNjudYSl13sSg9XrCPr9gniSFsNAMqFkDEEgkDSkESGCcECRlAyECAGswoE4FALUpw5HfbIY5ommxBEF7QmnS70Btee7Pd7Ar3-fs-LTQMo2MhrEZVbt4jteT09UpAkg+2lDCA2y6lEET2Q3AbA9jGy30MJZG4uxGo337Vt44mJzle501nMIAEcGBPTA6DUGhSADXwhxHAcxyTdADgGEDM3QUwEBzXplzSVd1yQTdUHPVFTkPC9bzPEAmGAkAyDbcMQAfQNqLbGRBHggdoB0IjB2HOt0GuL0ZlkC1HzyIA)

**Comment by fxwiegand** [comment]
This seems to be it thank you so much!
