### ISSUE TITLE
Add observable10 color scheme

### ISSUE THREAD

**Issue by apoorvkh** [vega/vega-lite#9458]
The observable10 color scheme was added to Vega in https://github.com/vega/vega/pull/3843. However, I can't find it in vega-lite. Would it be possible to add this scheme? Thanks so much!

(coming here after https://github.com/vega/altair/pull/3626)

**Comment by apoorvkh** [comment]
cc: @mcnuttandrew (since you contributed this to vega originally)

**Comment by domoritz** [comment]
It should be there since it's in the Vega types and we import those. Are you checking main?

**Comment by PBI-David** [comment]
FYI, it works but does cause validation errors in the online editor. 

![Image](https://github.com/user-attachments/assets/e6a8e082-95a7-4fa4-b381-de3bd927b4ae)

**Comment by apoorvkh** [comment]
Oops. I had tried to keyword search via Github, but `grep -r observable10 vega-lite` revealed it.

It is indeed [at this line in vega-lite-schema.json (v5.21.0)](https://github.com/vega/vega-lite/blob/802d661e561068d702459b0b14a15736a6e8ea18/build/vega-lite-schema.json#L4756).

I am not sure why there are validation errors, but I'll at least close this particular issue.

**Comment by domoritz** [comment]
Could be that we haven't updated the editor.
