### ISSUE TITLE
XSS via event filter

### ISSUE THREAD

**Issue by kprevas** [vega/vega-lite#9469]
## Bug Description

The `filter` property of a `select` parameter exposes the browser's `Window` object via `event.view`, allowing arbitrary code to be executed via `scale(event.view.setTimeout, '[code payload here]')`.

This is related to https://github.com/vega/vega/issues/3027.  It is distinct from https://github.com/vega/vega/security/advisories/GHSA-4vq7-882g-wcg4 and is not fixed by https://github.com/vega/vega/commit/ab371a0093a8cb6215f7bdd5716f33aba6b6ee0f as `scale$2` only checks if a scale is registered when the scale is specified as a string; if a function is passed to `scale()` then it is invoked unconditionally.

The following example reproduces the issue:

https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWhiYrn56ADCJagALADMFSBJACK1AJwAjM1JAKK1mT15LQUAYrViTSNJAOK1XR29BQASgwDsy+gAkpPp2QC6uSA4NkgIEPGgsudwBdqXShBwFlCYaKCYAJ44d+g4bBosneSjkHxA31+BQQbAYz2UbCc8iUyHUAGtIX8QKYkGQ7koAGY0QSYODqeIgaBROAACjgpGBlGINDgTkoz0wABVTHBYZgFAByanqTA0gA6LQsIolAEoBTKQEdsocUTY0QVrOSlHBZFA2MogWRwQAPcFEl7KAooJSYgqyNgIIFRYJIY00S7hECCJCeQT6WRkCxoAAMyqUXzNLMElvQaRtPyxAEcGEhgXQAjRSCBldkgA

<details>
  <summary><h2>Checklist</h2></summary>

- [X] I checked for duplicate issues.
</details>

**Comment by domoritz** [comment]
Thanks for the report. All XSS issues are Vega only. Can you create a repro there?

**Comment by kprevas** [comment]
Sorry, I'm not sure I understand your request.  Are you asking if I'm able to repro this with a Vega config?

**Comment by domoritz** [comment]
Vega-Lite compiles to Vega and Vega is the only library needed at runtime after the Vega spec has been compiled. I am saying that this is probably an issue with Vega, no Vega-Lite.

**Comment by kprevas** [comment]
Thank you.  Filed https://github.com/vega/vega/issues/3984
