### ISSUE TITLE
Add ~~quarter, `year-quarter`,~~ century, decade to timeUnit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#947]
Forked from #145.  Currently we do not have support for `quarter`, `year-quarter`, `decade` and `century`.

- [x] `quarter`, `year-quarter`
- [ ] decade
- [ ] century

**Comment by kanitw** [comment]
Since d3-format do not support quarter and decade directly, we probably have to add additional formula transform to calculate quarter / decade from month / year values.

**Comment by kanitw** [comment]
Let's say they can always use `calculate` to make `decade` and `century`.  We have a lot other things to do.

**Comment by domoritz** [comment]
👍
