### ISSUE TITLE
Clean up styling for facet

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#948]
We should provide good default before 1.0 release and may provide customizable property later

- [ ] For example, do we add offset between shared axis and the graphs.  This will cause problem in some case like shown in #523 

- [x] Unconnected grid like in #920

**Comment by kanitw** [comment]
#920 is done.   The only question left is whether we always add offset to axis of facet?

Right now we only add offset to the shared axis like y-axis in the figure below.  

![vega_editor](https://cloud.githubusercontent.com/assets/111269/12997554/531fa18a-d0ef-11e5-89de-ee5690ee5ccf.png)

It could be nice to do so for the x-axis as well for symmetry.

**Comment by kanitw** [comment]
Oops. Although I think it is nice to do so, there is a Vega bug with grid when we add `offset` to `axis`.  https://github.com/vega/vega/issues/519

Let's punt this until it is solved in Vega then.  (Maybe 1.0.1)

**Comment by domoritz** [comment]
@arvind closed vega/vega#519 in https://github.com/vega/vega/commit/96c539f831da716641436baaaf7d1ada10f4ba09
