### ISSUE TITLE
Labels Disappear when using Dark Mode

### ISSUE THREAD

**Issue by Nish0234** [vega/vega-lite#9481]
## Bug Description

Labels visible when using light mode...
![Image](https://github.com/user-attachments/assets/abb32145-0f79-4737-bd31-a04222a635d5)

Labels not visible when using dark mode...

![Image](https://github.com/user-attachments/assets/0b973a8e-1d15-49e9-a672-667425b539a9)

**Comment by domoritz** [comment]
Not sure what this is from. We don't have dark mode.

**Comment by Nish0234** [comment]
There is an option for Dark/Light mode on Deneb Website?

![Image](https://github.com/user-attachments/assets/cfa685dc-e12f-4b72-a659-1bad18860973)
