### ISSUE TITLE
Plot is off by 1 pixel

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#949]
Especially in the area chart, it seems that the plot is off to the left by one pixel.

<img width="282" alt="screen shot 2016-01-15 at 12 47 38" src="https://cloud.githubusercontent.com/assets/589034/12364907/4851871a-bb86-11e5-994f-3ce6362422f7.png">
<img width="272" alt="screen shot 2016-01-15 at 12 47 46" src="https://cloud.githubusercontent.com/assets/589034/12364910/4c1c1900-bb86-11e5-82a4-0c5894a84ac9.png">

**Comment by domoritz** [comment]
This could be a vega issue http://localhost:8000/?mode=vega&spec=scatter_matrix or an issue with my perception.

**Comment by domoritz** [comment]
Seems to be a vega-scenegraph issue https://github.com/vega/vega-scenegraph/issues/22

**Comment by kanitw** [comment]
Yeah, I observe it for bar before but didn't notice that this is problematic for other marks as well.

After this is fixed at the Vega / Vega-scenegraph level, I think we have to re-check all `offset` that we put in Vega-Lite's mark.

**Comment by kanitw** [comment]
@domoritz  Is this still happening with Vega 3?

**Comment by domoritz** [comment]
Yes
```json
{
  "data": {
    "values": [
      {"a": 0,"b": 0},
      {"a": 1,"b": 0},
      {"a": 0,"b": 1},
      {"a": 1,"b": 1},
      {"a": 0.5,"b": 0.5}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a","type": "quantitative"},
    "y": {"field": "b","type": "quantitative"},
    "opacity": {"value": 1},
    "size": {"value": 1}
  }
}
```

**Comment by kanitw** [comment]
More like half pixel?   + I guess this is a Vega issue, so can you file it there and we can close it here?
