### ISSUE TITLE
Adding a script to add example in the docs easier

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#964]
Currently we have to do something like

    ```js
    {
      "data": {"url": "data/cars.json"},
      "mark": "square",
      "encoding": {
        "x": {"field": "Horsepower","type": "quantitative"},
        "y": {"field": "Miles_per_Gallon","type": "quantitative"}
      }
    }
    ```

    <script>
    vg.embed('#square', {
      mode: 'vega-lite',
      spec: {
        "data": {"url": "../data/cars.json"},
        "mark": "square",
        "encoding": {
          "x": {"field": "Horsepower","type": "quantitative"},
          "y": {"field": "Miles_per_Gallon","type": "quantitative"}
        }
      }
    });
    </script>
    <div id="square"></div>

If we have a method that allow importing and display both code and the result of an example (with one line code) like

```
showExample(’square’)
```
where `square.json` is stored separately and can be included in the automated test, this will be useful.

**Comment by willium** [comment]
So the docs are markdown if I'm understanding correctly. Do you see this as a script that parses the markdown and replaces `showExample(’square’)` with
```
    ```js
    {
      "data": {"url": "data/cars.json"},
      "mark": "square",
      "encoding": {
        "x": {"field": "Horsepower","type": "quantitative"},
        "y": {"field": "Miles_per_Gallon","type": "quantitative"}
      }
    }
    ```

    <script>
    vg.embed('#square', {
      mode: 'vega-lite',
      spec: {
        "data": {"url": "../data/cars.json"},
        "mark": "square",
        "encoding": {
          "x": {"field": "Horsepower","type": "quantitative"},
          "y": {"field": "Miles_per_Gallon","type": "quantitative"}
        }
      }
    });
    </script>
    <div id="square"></div>
```
and would square be a vega svg render of the example?

**Comment by willium** [comment]
As it is now the docs stand by themselves in their markdown state  (i.e. I can navigate to https://github.com/vega/vega-lite/blob/master/docs/mark.md and see a pretty good representation of the docs) and are augmented by the use of vega-embed. I see two options:
1. have a preprocessor file of sorts that pre-renders the markdown so its readable (from `showExample(’square’)` to the full vega-embed and embedded code)
2. process the markdown before being rendered to view on https://vega.github.io/vega-lite/docs/

*1* has the advantage of readable markdown files up to the spec of markdown, but the disadvantage of adding essentially another build process and scaffolding to generate the markdown files from some other kind of schematic file.
*2* has the advantage of no need for scaffolding or schemas or new files in vega-lite/docs, but the disadvantage of essentially breaking markdown spec and making it unreadable in its pre-processed form

Is there another option? Which of these two is preferred?

**Comment by domoritz** [comment]
I think I prefer 2 exactly for the reason that you mentioned. I am not too worried about not being able to look at rendered charts on github. We can just release more often and thus update the documentation.

**Comment by willium** [comment]
I personally didn't even realize docs was rendered by ghpages and was confused what you were asking. It took me hunting for a link. It would be nice to have a readme file in the docs dir at the very least linking to the rendered version.

**Comment by kanitw** [comment]
> It would be nice to have a readme file in the docs dir at the very least linking to the rendered version.

We already had.  See "The language and API are described in the documentation." in the first section of README.md.  (Maybe you read that file before we added this)

> 2. process the markdown before being rendered to view on

I guess you understand it more that we can render docs and that's already preprocessed by github pages jekyll engine.  

Basically, what I want is

- [ ]  simply replacing that long code block with short `showExample(’square’)`.  It's fine that github markdown repo preview.

- [ ] write a `embed.js` which contains `showExample()` function in `docs/`, which will show the code with syntax highlighting and the rendered vis (simply calling vega embed)

- [ ]  add  `<script src="embed.js"></script>` to  `_layout/docs.html` 

(If you have better embed.js, that's fine too.  I don't like it that much yet.)

**Comment by willium** [comment]
Ah okay, that's a good solution

**Comment by kanitw** [comment]
I already took care of this in https://github.com/vega/vega-lite/pull/1030.  :)
