### ISSUE TITLE
Add more axis / label properties

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#975]
Currently if we want to customize labels angle of x-axis, we need to add `{"properties": {"labels": {"angle": {"value": -45}}}}` to `x.axis`.   (Like shown in the full spec below).

- [ ] ~~making it `{"properties": {"labels": {"angle": -45}}}` is more reasonable for Vega-Lite~~ 

Example full spec:

```
{
  "description": "Area chart showing weight of cars over time.",
  "data": {"url": "data/cars.json"},
  "mark": "area",
  "encoding": {
    "x": {
      "timeUnit": "year", "field": "Year", "type": "temporal",
      "axis": {"properties": {"labels": {"angle": {"value": -45}}}}
    },
    "y": {"aggregate": "sum", "field": "Weight_in_lbs","type": "quantitative"}
  },
  "config": {"mark": {"interpolate": "monotone"}}
}
```

**Comment by kanitw** [comment]
- [ ] A related task is to extend schema for `properties` of `axis` and `label`.   
(Right now we only say that it is an object.  Better define a schema that is consistent with Vega)

**Comment by kanitw** [comment]
Basically we are passing `axis.properties` to Vega  

See https://github.com/vega/vega/wiki/Axes#custom-axis-styles and https://github.com/vega/vega/wiki/Legends#custom-legend-styles

**Comment by domoritz** [comment]
Can we get rid of `properties` and just wrap the properties that we know should be in `properties` inside a `properties` property?

**Comment by kanitw** [comment]
There are too many of them (all mark properties). That's why Vega do it
this way.

**Comment by domoritz** [comment]
How's that a problem? We could have a list of properties that we know go in other places and pass everything else wrapped.

**Comment by kanitw** [comment]
@YuhanLu   We have some plan changed here.  

Instead of just wrapping properties of `axis.properties` so that we don't have to use specify `value`,
we should get rid of `axis.properties` and add properties to the top level of axis instead. 

For example, we can add `tickColor` which passes value to `properties.tick.fill`.  

Since Vega is introducing theming (in [this PR](https://github.com/vega/vega/pull/489)), we should just name the properties consistently with them.   (See [Vega's config_properties.js](https://github.com/vega/vega/blob/emily/theming-wip/theme/config_properties.js) from the same PR) 

So now the task is the following: 

For each axis and legend property listed in Vega's config_properties.js,

- [ ] add them to our schema
- [ ] make axis.js and legend.ts compile them to the correct `axis.properties.*` output

For some of properties that you're not sure what to do, please feel free to ask us.  

I ~~crossed~~ out the outdated lines above, so hopefully it's clearer.   If this is still unclear to you, let us know.  I'll be around tmr and friday.  We could chat in person about this if it's unclear to you.

**Comment by kanitw** [comment]
@YuhanLu  To help you get started, you should create a google docs listing all axis and legend properties in Vega's [config_properties.js](https://github.com/vega/vega/blob/emily/theming-wip/theme/config_properties.js)
and map them to Vega axis and legend properties and ping us to review.

**Comment by YuhanLu** [comment]
May I ask if it's possible for different properties mapping to the same vega axis and legend property? Like you showed me yesterday, axis axisColor -> axis's properties.axis.stroke.value (in axisDomain()), but I find the tickColor is also mapped to properties.axis.stroke.value (but in axisTicks()). @kanitw
