### ISSUE TITLE
Layout calculation incorrect when we auto-set domain for timeUnit

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#981]
```
{
  "description": "Line chart of Horsepower over time",
  "data": {"url": "data/cars.json"},
  "mark": "line",
  "encoding": {
    "x": {"field": "Year", "type": "temporal", "timeUnit": "month"},
    "y": {"field": "Horsepower", "type": "quantitative", "aggregate": "mean"}
  }
}
```

<img width="319" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/12525909/2c0fcb1a-c11d-11e5-8c50-a62aca237283.png">

Our current formula have `cellWidth` depends on cardinality of x field.  
However, in this case, it should use 12 instead of cardinality.   

- [ ] modify the layout formula to use fixed cardinality when we automatically augment domain

**Comment by domoritz** [comment]
Ups. I totally forgot to do that in #937.

**Comment by kanitw** [comment]
- [ ] need to revise this after finishing the first sketch for composition

**Comment by kanitw** [comment]
Already fixed at some point.  For example: 

<img width="946" alt="vega_editor_" src="https://cloud.githubusercontent.com/assets/111269/19019386/8e84e0d6-88b0-11e6-9848-31a07ba1cca7.png">
