### ISSUE TITLE
Incorrect negative area chart

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#986]
Probably need to add a predicate for y, y2   (swap them when y field < 0)

``` js
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": -55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": -87}, {"a": "I","b": 52}
    ]
  },
  "mark": "area",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

<img width="268" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/12527089/7a786700-c12a-11e5-8546-8bf65b59eb4c.png">

**Comment by domoritz** [comment]
Hmm, I think that they are swapped although they shouldn't be swapped.

**Comment by kanitw** [comment]
This seems like a Vega bug?

**Comment by domoritz** [comment]
It does. The vega spec that we generate looks reasonable to me.

**Comment by kanitw** [comment]
Filed in Vega https://github.com/vega/vega/issues/718
