### ISSUE TITLE
Generate reference to unknown dataset

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#992]
```json
{
  "description": "A scatterplot showing horsepower and miles per gallons.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower","type": "quantitative"},
    "y": {"field": "Miles_per_Gallon","type": "quantitative"},
    "color": {"field": "Origin", "type": "ordinal"}
  }
}
```

The generated vega code references layout but layout does not exist. This should be easy to fix by adding the reference only when it is needed. The vega spec actually never used the referenced dataset.

**Comment by domoritz** [comment]
Started at https://github.com/vega/vega-lite/compare/dom/fix-992

**Comment by kanitw** [comment]
lol is "started at" a new pattern?  I think normally you'd create a PR and says WIP for this issue.

**Comment by domoritz** [comment]
Came out of a conversation with @willium. He's adding tests for it.

**Comment by kanitw** [comment]
Pretty much done in #1059 -- only minor comment left.
